### ISSUE TITLE
include storage migration requirements in manual upgrade doc

### ISSUE THREAD

**Issue by liggitt** [openshift/openshift-docs#10015]
https://github.com/openshift/openshift-docs/blob/master/upgrading/manual_upgrades.adoc

before performing a manual upgrade, `oc adm migrate storage --confirm` should be run to ensure that all persisted objects are using a storage version that will be supported on the next level of openshift

additionally, unless otherwise noted, apiservers should be upgraded one version at a time, and `oc adm migrate storage --confirm` run on each version

unless otherwise noted, the latest version of `oc` matching the apiserver version should be used

for example, to upgrade from 3.6 to 3.9:

1. run `oc adm migrate storage --confirm` against the 3.6 apiserver, using oc 3.6.x
2. upgrade to 3.7
3. run `oc adm migrate storage --confirm` against the 3.7 apiserver, using oc 3.7.x
4. upgrade to 3.8
5. run `oc adm migrate storage --confirm` against the 3.8 apiserver, using oc 3.8.x
6. upgrade to 3.9

**Comment by vikram-redhat** [comment]
@liggitt I am guessing the same steps would apply for upgrade to 3.10

**Comment by liggitt** [comment]
Yes, they apply at every upgrade. 

Additional migrations are available at some levels. For example, at 3.9 and up, `oc adm migrate legacy-hpa` should be run to convert legacy scale references in HPA objects. cc @DirectXMan12

**Comment by vikram-redhat** [comment]
@jhou1 - could you please confirm these steps?

**Comment by vikram-redhat** [comment]
@xltian - could we get someone to QE these steps?

**Comment by jhou1** [comment]
Looks good.

**Comment by kalexand-rh** [comment]
Looks like there's a related bug: https://bugzilla.redhat.com/show_bug.cgi?id=1613759

**Comment by nak3** [comment]
Fix for the docs is fine. But, as some users and RH team is asking or misguiding `oc adm migrate storage` based on the comment in this issue, I will leave a note below.

oc client version, which runs `oc adm migrate storage --confirm`, does not need to be same with the apiserver version accurately. `oc migrate storage` w/ oc 3.7 against apiserver v3.6 is fine.

@enj verified it on bz#1587830.

**Comment by enj** [comment]
> oc 3.7 against apiserver v3.6 is fine

While this is true, we should not encourage it (since you can hit other incompatibilities).  In general our tooling should make sure that the correct version of `oc` is being used for all commands (since that is the only thing we actually test against).
