### ISSUE TITLE
[enterprise-3.9] Edit suggested in file install_config/install/advanced_install.adoc

### ISSUE THREAD

**Issue by nickcmaynard** [openshift/openshift-docs#10024]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/3.9/install_config/install/advanced_install.html#advanced-installation-logging-storage

### What needs fixing?
The documentation here states:

The openshift_logging_es_pvc_dynamic variable must be set in order to use persistent storage for logging. If openshift_logging_es_pvc_dynamic is not set, then cluster logging data is stored in an emptyDir volume, which will be deleted when the Elasticsearch pod terminates.

This contradicts the options listed after this.  Options such as NFS still exist, and are listed immediately after this paragraph.

**Comment by vikram-redhat** [comment]
@bmcelvee PTAL
