### ISSUE TITLE
[online] Edit suggested in file getting_started/basic_walkthrough.adoc

### ISSUE THREAD

**Issue by scoulomb** [openshift/openshift-docs#10022]
### Which section(s) is the issue in?

Setup

### What needs fixing?

`$ git clone https://github.com/<your_github_username>/nodejs-ex`
Should be replaced by
`$ git clone https://github.com/<your_github_username>/nodejs-ex.git`
(`.git` at the end)

**Comment by scoulomb** [comment]
PR created : https://github.com/openshift/openshift-docs/pull/10023

**Comment by vikram-redhat** [comment]
@ahardin-rh PTAL

**Comment by ahardin-rh** [comment]
Closing per https://github.com/openshift/openshift-docs/pull/10023#issuecomment-398046015
