### ISSUE TITLE
[enterprise-3.9] Edit suggested in file install_config/persistent_storage/persistent_storage_vsphere.adoc

### ISSUE THREAD

**Issue by akesterton** [openshift/openshift-docs#10073]
### Which section(s) is the issue in?
Persistent Storage Using VMWare vSphere Volume
Provisioning
2nd sentence

### What needs fixing?
Typo on link to VMware vSphere - name and capitalisation

**Comment by vikram-redhat** [comment]
@tmorriso-rh PTAL

**Comment by tmorriso-rh** [comment]
CP via:

3.6: https://github.com/openshift/openshift-docs/pull/10649
3.7: https://github.com/openshift/openshift-docs/pull/10650
3.9: https://github.com/openshift/openshift-docs/pull/10651
3.10: https://github.com/openshift/openshift-docs/pull/10652
