### ISSUE TITLE
[enterprise-3.0] Edit suggested in file dev_guide/service_accounts.adoc

### ISSUE THREAD

**Issue by BenSturmfels** [openshift/openshift-docs#10094]
### Which section(s) is the issue in?

"Usernames and groups"

### What needs fixing?

The commands refer to "serviceaccounts" which should be "serviceaccount". The plural version will succeed, but won't have the intended effect.

See the admin docs: https://docs.openshift.org/3.6/admin_guide/service_accounts.html

**Comment by BenSturmfels** [comment]
Ah, it looks as though the copy of the docs I found through a search engine is out of date:

https://docs.openshift.com/enterprise/3.0/dev_guide/service_accounts.html

This has been fixed in this copy:

https://docs.openshift.org/3.6/dev_guide/service_accounts.html

It would be nice if the web docs provided a link to other versions, similar to how Django does it (version selector in bottom right):

https://docs.djangoproject.com/en/1.11/ref/models/fields/

**Comment by vikram-redhat** [comment]
Thanks @BenSturmfels - this is on the cards to do soon.
