### ISSUE TITLE
[enterprise-3.9] Edit suggested in file dev_guide/secrets.adoc

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-docs#10100]
### Which section(s) is the issue in?

Serving Service Certificates

### What needs fixing?

This section is really its own topic.  It should be a new, task focused topic like "Securing application traffic with TLS" with a general description of why you should use TLS, then an example of how to use service serving certs.  Also we should describe that a "Reencrypt" route will automatically be verified and encrypted when you use a service serving cert (create a route of type reencypt to a service with a service serving cert and everything will "just work").

**Comment by vikram-redhat** [comment]
@kalexand-rh - do you have the bandwidth to take this one?

**Comment by kalexand-rh** [comment]
Simo agrees with this request and says that @mrogers950 will be the best contact on the security team.
