### ISSUE TITLE
Unclear statement in v3.0.2.0 release note regarding docker registry v2 support

### ISSUE THREAD

**Issue by nak3** [openshift/openshift-docs#1011]
https://docs.openshift.com/enterprise/3.0/whats_new/ose_3_0_release_notes.html#ose-3-0-2-0 says:

~~~
Images

    Importing and pulling from Docker v2 registries is now supported.
~~~

I guess that it indicates this PR https://github.com/openshift/origin/pull/4104 . If so, it should say

~~~
    Importing or creating a new app with an image from Docker v2 registries is now supported.
~~~

**Comment by bfallonf** [comment]
It might be to far gone to fix this, but it's an easy fix, so I did it anyway. Live docs here:

https://github.com/openshift/openshift-docs/blob/enterprise-3.0/whats_new/ose_3_0_release_notes.adoc#ose-3-0-2-0
