### ISSUE TITLE
[oc cluster up docs] update prerequisites for docker on linux

### ISSUE THREAD

**Issue by pmacko1** [openshift/openshift-docs#10123]
https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#prerequisites
### Which section(s) is the issue in?
oc cluster up linux prereqs

### What needs fixing?
Docker versioning system is for non experienced users not clear.
CE version is now ~v18.
Docker Engine is a Superseded product
https://docs.docker.com/cs-engine/1.13/

**Comment by vikram-redhat** [comment]
Hey @pmacko1 - please open this issue in OpenShift Origin here: https://github.com/openshift/origin/issues
