### ISSUE TITLE
Do wee need to set master host as unschedulable by hand before advanced installation 

### ISSUE THREAD

**Issue by nak3** [openshift/openshift-docs#1017]
https://docs.openshift.org/latest/install_config/install/advanced_install.html#configuring-ansible says:

> Before running the Ansible installer, any hosts you intend to designate as masters during the installation process should also be configured as unschedulable nodes, in order to configure the masters as part of the OpenShift SDN.

However, the users doens't have `oadm` command before installation. And this step "any hosts you intend to designate as masters during the installation process should also be configured as unschedulable nodes" is really necessary? I think it will do by ansible installer by itself.

**Comment by abutcher** [comment]
This is calling out that you can configure unschedulable nodes in your host inventory prior to installing.

The byo example inventory mentions this as well.

```
...
# NOTE: Currently we require that masters be part of the SDN which requires that they also be nodes
# However, in order to ensure that your masters are not burdened with running pods you should
# make them unschedulable by adding openshift_scheduleable=False any node that's also a master.
[nodes]
ose3-master[1:3]-ansible.test.example.com
ose3-node[1:2]-ansible.test.example.com openshift_node_labels="{'region': 'primary', 'zone': 'default'}"
...
```

**Comment by nak3** [comment]
Ah, I see. Thank you.

So, documentation should not link to https://docs.openshift.org/latest/admin_guide/manage_nodes.html#marking-nodes-as-unschedulable-or-schedulable in its [unschedulable](https://docs.openshift.org/latest/admin_guide/manage_nodes.html#marking-nodes-as-unschedulable-or-schedulable) ,right?

**Comment by adellape** [comment]
There was an issue early on with the labels not getting set during advanced installations. We can update this to be more clear now. The "unscheduleable" link to the Admin Guide was really just to provide further context about what it means for a node to be unscheduleable. If we update this to be more clear about `openshift_scheduleable`, hopefully that would be more clear.

**Comment by adellape** [comment]
Closing in favor of https://bugzilla.redhat.com/show_bug.cgi?id=1267486.
