### ISSUE TITLE
fluentd (td-agent) should be installed as Pod

### ISSUE THREAD

**Issue by nak3** [openshift/openshift-docs#1019]
https://docs.openshift.org/latest/admin_guide/aggregate_logging.html installs fluentd (td-agent) on Nodes by the RPM package. But It should be installed by the Pod.

**Comment by bmcelvee** [comment]
Hey @nak3! This issue was opened several versions back, and it appears that the documentation has been updated appropriately. Please let me know if you think it is safe to close this issue. Thanks!

**Comment by nak3** [comment]
Sure, let's close.
