### ISSUE TITLE
3.11: pod with sysctl example needs to be updated

### ISSUE THREAD

**Issue by php-coder** [openshift/openshift-docs#10225]
### Which section is the issue in?
https://docs.openshift.org/latest/admin_guide/sysctls.html#setting-sysctls-for-a-pod

### What needs fixing?
OpenShift 3.11 that will be on top of Kubernetes 1.11 won't work with the old sysctl annotations that are present in our example. The example will require an update, like Kubernetes did: https://github.com/kubernetes/website/pull/8804/files#diff-bbdf255eebe738c7c70b93ea3ddcde37L119

@ingvagabund Is this a task for pod team?

CC @kalexand-rh

**Comment by ingvagabund** [comment]
@php-coder should be basically copy-paste with slight modifications to accommodate the OpenShift docs style

**Comment by ingvagabund** [comment]
so anyone can do that, we can do the review

**Comment by kalexand-rh** [comment]
I made a PR for this change here: https://github.com/openshift/openshift-docs/pull/10361

**Comment by vikram-redhat** [comment]
Since this is being tracked via #10361 I am closing it.
