### ISSUE TITLE
Docs should be pointing to stable k8s documents

### ISSUE THREAD

**Issue by soltysh** [openshift/openshift-docs#1022]
There a re a couple of issues here:
1. A lot of documents (eg. [here](https://github.com/openshift/openshift-docs/blob/master/dev_guide/builds.adoc) and a lot more) are pointing to design docs, whereas they should point to user-guide instead, if such exists.
2. IMHO we should be pointing to released docs, and not blob/master like we do now, see previous point for example as well.
3. We are still pointing to GoogleCloudPlatform/kubernetes whereas k8s repo moved quite a long time ago to kubernetes/kubernetes.

@adellape @danmcp @smarterclayton what do you guys think?

**Comment by adellape** [comment]
Agree. We've been updating them as we come across them in other work, but we should do a mass audit.

There could also be cases where we could now just link to our own OpenShift docs. E.g. in that `dev_guide/builds` example you mention, could instead link to our `dev_guide/secrets`, which itself could  link to http://kubernetes.io/v1.0/docs/design/secrets.html for more.

**Comment by soltysh** [comment]
This one should rather point to http://kubernetes.io/v1.0/docs/user-guide/secrets.html imho, because user counter part exists, and we should point to it if such is available. Design docs are not always in sync with current implementation, which might mislead users and additionally might be covering the user part of the resource.

**Comment by adellape** [comment]
@soltysh I'm sorry, that's the link I meant to paste. :) Was comparing between the two and grabbed the wrong one.

**Comment by bmcelvee** [comment]
Hey, @adellape! This was last updated a while back. Do you recall if we've done a mass audit? Is this something we should plan on for 3.7?

**Comment by adellape** [comment]
@bmcelvee It looks like we still have some hits on `docs/design` in master and some other old GoogleCloudPlatform and Kubernetes GH docs that we can update.

**Comment by vikram-redhat** [comment]
Closing this via: https://github.com/openshift/openshift-docs/pull/11319 which contains the last remnants of the GoogleCloudPlatform.
