### ISSUE TITLE
Document required structure of openshift_master_identity_providers

### ISSUE THREAD

**Issue by tongpu** [openshift/openshift-docs#10296]
### Which section(s) is the issue in?

Advanced Installation
Configuring authentication and user agent

### What needs fixing?

Document how the YAML structure in `master-config.yaml` maps to the JSON string passed to Ansible in the 
 variable `openshift_master_identity_providers`. Currently only `HTPasswdPasswordIdentityProvider` is provided as an example and other identity providers have different requirements.

**Comment by tongpu** [comment]
I might be able to pick this up in the future, because I figured out the structure yesterday, but won't find time to update the documentation within the next few weeks.

**Comment by vikram-redhat** [comment]
Thanks @tongpu - ping us when you have the bandwidth.
