### ISSUE TITLE
Origin's authentication is not Deny All, but Allow all by default

### ISSUE THREAD

**Issue by nak3** [openshift/openshift-docs#1030]
The doc https://docs.openshift.org/latest/install_config/install/advanced_install.html#what-s-next 
says Origin's authentication is not **Deny All**.  It is only for OSE(enterprise). Origin sets it as `AllowAllPasswordIdentityProvider` by default.

https://github.com/openshift/openshift-ansible/blob/4b97bb621e0612022eaf8907303b9d3a3db0b713/roles/openshift_facts/library/openshift_facts.py#L350-L359

**Comment by vikram-redhat** [comment]
@adellape - does this just require a conditional adding for enterprise? If yes, could you do that and merge?

**Comment by vikram-redhat** [comment]
Fixed via: https://github.com/openshift/openshift-docs/commit/4051fd6a526efe1010d1f7c5f6ecc9e03b3aa3f4. Closing this issue.
