### ISSUE TITLE
Sample jsons should be downloadable

### ISSUE THREAD

**Issue by soltysh** [openshift/openshift-docs#1040]
Sometimes we provide a json file name right above a sample json, like [here](https://docs.openshift.org/latest/dev_guide/quota.html#sample-resource-quota-file) see resource-quota.json right under the headline. But unfortunately it doesn't do anything. We should allow user click it and he should be provided with a sample json that is presented in the code sample following the name of the file. See for example k8s docs [here](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/ and notice Download example right under the sample code.

**Comment by bmcelvee** [comment]
Hey @soltysh! This issue was opened several versions back, and the Kubernetes link has moved to their docs pages. Do you think this issue is still applicable? If not, I'll go ahead and close it. Thanks!

**Comment by soltysh** [comment]
@bmcelvee the issue still stands, I've updated the link from the description to point to a current docs.

**Comment by bmcelvee** [comment]
Thanks, @soltysh!

**Comment by vikram-redhat** [comment]
This is not something we can work on right now. Closing this.
