### ISSUE TITLE
[enterprise-3.9] Edit suggested in file install_config/master_node_configuration.adoc

### ISSUE THREAD

**Issue by hashnao** [openshift/openshift-docs#10488]
### Which section(s) is the issue in?
The event ttl is set on 15 mins but there's no mention about the default value.

```
apiServerArguments:
  event-ttl:
  - "15m
```

### What needs fixing?
The default value for ttl should be added.
According to the source code [1], the value is 2 hours.

.master_config_test.go
```
		EventTTL:               2 * time.Hour,
```

[1] <https://github.com/openshift/origin/blob/release-3.9/pkg/cmd/server/kubernetes/master/master_config.go#L119>

**Comment by vikram-redhat** [comment]
@Brice - PTAL.

**Comment by bfallonf** [comment]
Thanks @hashnao . I've created a PR for this:

https://github.com/openshift/openshift-docs/pull/10590

If there's anything more, please let me know. I'll close this issue.
