### ISSUE TITLE
Duplicate scheduler upgrade documentation for 3.1/1.1 when the time comes

### ISSUE THREAD

**Issue by sdodson** [openshift/openshift-docs#1048]
Need to duplicate this #1047 for 3.1/1.1 when we get to writing those docs. This is necessary because we've added this after the initial 3.0.2 release so we cannot be sure that folks have performed this step when upgrading to 3.1 even if they've followed the docs.

**Comment by bmcelvee** [comment]
Hey @sdodson! Since this issue was opened for 3.1/1.1, do you think it's safe to go ahead and close it? Thanks!

**Comment by sdodson** [comment]
Yeah, no need to fix 3.1 docs at this point.
