### ISSUE TITLE
[enterprise-3.9] Edit suggested in file using_images/other_images/jenkins.adoc

### ISSUE THREAD

**Issue by etoews** [openshift/openshift-docs#10722]
### Which section(s) is the issue in?

[Creating a Jenkins Service from a Template](https://docs.openshift.com/container-platform/3.9/using_images/other_images/jenkins.html#jenkins-creating-jenkins-service-from-template)

### What needs fixing?

The section is missing important details. Compare it to the [same section from the 3.7 docs](https://docs.openshift.com/container-platform/3.7/using_images/other_images/jenkins.html#jenkins-creating-jenkins-service-from-template).

**Comment by vikram-redhat** [comment]
@bmcelvee - assigning this to you. There were some edits made to this file via this PR that might have caused this. https://github.com/openshift/openshift-docs/pull/7128
