### ISSUE TITLE
Create a section for Priority and Preemption in 3.11

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [openshift/openshift-docs#10761]
### Which section(s) is the issue in?
Scheduling.

### What needs fixing?
We are planning to enable priority and preemption in OpenShift 3.1(https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/), so we need to update scheduler documentation for it.

/cc @sjenning @derekwaynecarr @aveshagarwal @mburke5678

**Comment by mburke5678** [comment]
Closing this issue. Following via https://github.com/openshift/openshift-docs/pull/10772
