### ISSUE TITLE
"Available router plug-ins" has a superfluous heading and introductory text from included topics

### ISSUE THREAD

**Issue by Miciah** [openshift/openshift-docs#10794]
### Which section(s) is the issue in?

`architecture/networking/assembly_available_router_plugins.adoc`, which includes `architecture/topics/haproxy_template_router.adoc` and `architecture/topics/f5_big_ip.adoc` and can be found under Architecture / Networking / Available router plug-ins or the URL <https://docs.openshift.com/container-platform/3.9/architecture/networking/assembly_available_router_plugins.html>.

### What needs fixing?

`architecture/networking/assembly_available_router_plugins.adoc` has a level-2 heading, "Default HAProxy Router", followed immediately by the content of `architecture/topics/haproxy_template_router.adoc`, which begins with another level-2 heading, "HAProxy Template Router".  One of these headings should be deleted.

`architecture/networking/assembly_available_router_plugins.adoc` has a level-2 heading "F5 BIG-IP® Router plug-in" followed immediately by the content of `architecture/topics/f5_big_ip.adoc`, which begins with a general statement about routers:  "A router is one way to get traffic into the cluster." Such a general statement could belong at the start of `architecture/networking/assembly_available_router_plugins.adoc` but is out of place in its present location.

We need clear guidelines for included documents: Should the including document provide a heading (and if so, at what level?) or introductory text, or should that be left to the included document?

**Comment by vikram-redhat** [comment]
@Miciah - thanks for this. Yes, we have been experimenting with modular docs recently and will be updating the guidelines shortly. For this particular issue, I will request that @bfallonf fix it.

**Comment by bfallonf** [comment]
Thanks @Miciah . Yes, as Vikram notes, this came out of some screwey modularization I tired to do. I must've missed this one. I've created #10830 , and it should fix the issue.
