### ISSUE TITLE
Need to mention that OSEv3 doesn't contain RHEL High Availability Add-on

### ISSUE THREAD

**Issue by nak3** [openshift/openshift-docs#1083]
https://docs.openshift.com/enterprise/3.0/install_config/install/prerequisites.html#host-preparation
says:

```
5. If you plan to configure multiple masters for high-availability using the advanced installation method, you must also enable the High Availability Add-on for Red Hat Enterprise Linux repository:

# subscription-manager repos \
    --enable="rhel-ha-for-rhel-7-server-rpms"
```

It looks like OSEv3 can use `rhel-ha-for-rhel-7-server-rpms` repo, but users need to purchase it separately. Please mention that in the OSE v3 doc.

**Comment by nak3** [comment]
But we may need to consider about 3.1.
(internal) http://post-office.corp.redhat.com/archives/openshift-sme/2015-October/msg00547.html

**Comment by bmcelvee** [comment]
Hey @nak3! Since this issue was opened several versions back, do you think it's safe to close out?

**Comment by bmcelvee** [comment]
Hey @nak3! Since this issue was opened several versions back, do you think it's safe to close out?

**Comment by nak3** [comment]
Yeah... This PR is made in 2015... Actually I don't remember it.
