### ISSUE TITLE
OpenShift Getting Started Tutorial not loading

### ISSUE THREAD

**Issue by adamboesch** [openshift/openshift-docs#10865]
Hi, I don't know if this is the correct place for this, but I'm trying to run through the `Getting Started` scenario at https://learn.openshift.com/introduction/getting-started/ and the web Dashboard is coming back with a 502.

### Which section(s) is the issue in?
https://learn.openshift.com/introduction/getting-started/

### What needs fixing?
The Dashboard tab is supposed to load the web dashboard so I can login (according to the docs). But right now it returns a 502.

**Comment by vikram-redhat** [comment]
Hey @adamboesch - it is not the right place as we maintain the docs for OpenShift and not the learning environment. If you have a subscription, you may reach out to Red Hat support for help on this.

Having said that, I loaded it right now and it worked, and it may have been a temporary glitch. Could you try again and reach out to support if it doesn't?
