### ISSUE TITLE
Document how to promote entire deployments

### ISSUE THREAD

**Issue by mfojtik** [openshift/openshift-docs#1094]
We really do need to describe "take an app that runs in one project/cluster and move it somewhere else" concept. This originates from this PR: https://github.com/openshift/origin/pull/4016#discussion-diff-37920832R38

**Comment by bfallonf** [comment]
@mfojtik This would be a good addition. Is this process outlined anywhere? I'm asking if there's more info on this so we can use that to write up the docs rather than bugging you devs. I can see from the link above that there's some info there, but it seems to be largely speculative.
