### ISSUE TITLE
[enterprise-3.7] Edit suggested in file dev_guide/integrating_external_services.adoc

### ISSUE THREAD

**Issue by donovanmuller** [openshift/openshift-docs#10975]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/3.7/dev_guide/integrating_external_services.html

### What needs fixing?

There is mention of credentials throughout this page, like:

```
Environment variables in the appropriate pods containing the credentials.
```

however, there is no examples of how you actually set those credentials. Are they defined in a Secret? Where these credentials come from should be explained and possibly an example of how they are defined be provided or links to Secret etc. be added. For newcomers to OpenShift this could be confusing as to where these credentials come from.

**Comment by vikram-redhat** [comment]
@bfallonf - PTAL
