### ISSUE TITLE
Clarify the usage of ingressIPNetworkCIDR and externalIPNetworkCIDR parameters

### ISSUE THREAD

**Issue by codrinbucur** [openshift/openshift-docs#11024]
### Which section(s) is the issue in?

1. In the "OCP 3.9 - Assigning Unique External IPs for Ingress Traffic docs" [1], you can find these statements:

_One approach to getting external traffic into the cluster is by using ExternalIP or IngressIP addresses.

This feature is only supported in non-cloud deployments. For cloud (GCE, AWS, and OpenStack) deployments, use the Load Balancer services for automatic deployment of a cloud load balancer to target the service’s endpoints._

It is not clear to me if "this feature" refers to ExternalIP, IngressIP or both.

2. The "OCP 3.9 - Using a Load Balancer to Get Traffic into the Cluster - Defining the Public IP Range"  docs [2] use ExternalIPNetworkCIDRs instead of IngressIPNetworkCIDR as an example for allocating IPs for the Load Balancer Service. This seems to be somewhat in conflict with "OCP 3.9 - Assigning Unique External IPs for Ingress Traffic docs" [1] where the Load Balancer Service gets the IP from ingressIPNetworkCIDR

Are ExternalIPNetworkCIDRs and IngressIPNetworkCIDR equivalent, mutually exclusive or interchangeable when using Load Balancer Services?!

Also, this example
egress-2          172.30.236.167   172.29.121.74,172.29.121.74   3306/TCP                  6s

doesn't seem to match the range defined here, 
networkConfig:
  externalIPNetworkCIDRs:
  - 192.168.120.0/24

since /24 will not provide 172.29.121.* IPs.

3. In the "OCP 3.9 - Master and Node Configuration - Network Configuration" docs [3], there are two definitions:

_ExternalIPNetworkCIDRs    Controls what values are acceptable for the service external IP field. If empty, no externalIP may be set. It may contain a list of CIDRs which are checked for access. If a CIDR is prefixed with !, IPs in that CIDR will be rejected. Rejections will be applied first, then the IP checked against one of the allowed CIDRs. You must ensure this range does not overlap with your nodes, pods, or service CIDRs for security reasons.

IngressIPNetworkCIDR    Controls the range to assign ingress IPs from for services of type LoadBalancer on bare metal. It may contain a single CIDR that it will be allocated from. By default 172.46.0.0/16 is configured. For security reasons, you should ensure that this range does not overlap with the CIDRs reserved for external IPs, nodes, pods, or services._

It is not clear to me from here, if IngressIPNetworkCIDR can be only used for pure bare metal or also for VMs (running on-prem). Also, it is not clear if ExternalIPNetworkCIDRs can be used for any type of cluster (bare metal, VM on prem, cloud).

I would very much appreciate some clarity here.

[1] https://docs.openshift.com/container-platform/3.9/admin_guide/tcp_ingress_external_ports.html

[2] https://docs.openshift.com/container-platform/3.9/dev_guide/expose_service/expose_internal_ip_load_balancer.html#expose-lb-ip

[3] https://docs.openshift.com/container-platform/3.9/install_config/master_node_configuration.html#master-node-config-network-config

### What needs fixing?

The usage of ingressIPNetworkCIDR and externalIPNetworkCIDR should be much clearly defined and in sync across all mentioned sections/doc pages.

It should be clear if they are:
- mutually exclusive
- interchangeable
- usable in which type of cluster(s) exactly (bare metal, VM on prem, cloud)

Thanks
-Codrin

**Comment by vikram-redhat** [comment]
Thanks @codrinbucur. @bfallonf - can you look at this?

**Comment by akram** [comment]
@bfallonf ping

I am also suffering the same confusion 😊 
Can you please help?

Furthermore, external IP example adds confusion with:
```
        "externalIPs" : [
            "80.11.12.10"         
        ]
```

**Comment by akram** [comment]
@bfallonf  - can you look at this?
