### ISSUE TITLE
[enterprise-3.9] Edit suggested in file admin_guide/manage_nodes.adoc

### ISSUE THREAD

**Issue by b-mchugh** [openshift/openshift-docs#11023]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/3.9/admin_guide/manage_nodes.html#configuring-node-resources

### What needs fixing?
```
To view all available kubelet options:

$ kubelet -h
```

These seem to be older instructions from 3.7, there is no longer a kubelet binary in 3.9.
The following produces equivalent output as "kubelet -h" did in previous release.

```
To view all available kubelet options:

$ hyperkube kubelet -h
```

**Comment by mburke5678** [comment]
@sjenning Can you confirm if we need to change `kubelet -h` to hyperkube kubelet -h` in 3.9+

**Comment by mburke5678** [comment]
Closing. Proposed changes in https://github.com/openshift/openshift-docs/pull/11070
