### ISSUE TITLE
Need to document how to setup DNS on host when using OpenShift in VM

### ISSUE THREAD

**Issue by mfojtik** [openshift/openshift-docs#1105]
Today, when you start OpenShift in VM (Vagrant, KVM, ..) and you have project with "route", there is no documentation that describe how to configure the host DNS to be able to reach the DNS from the host browser.

We should document possible scenarios:

1) I'm running Vagrant with OpenShift
2) I'm running VM with OpenShift
3) I'm running OpenShift in container

We should document this for Linux, Mac and Windows.

**Comment by mfojtik** [comment]
@smarterclayton @jhadvig @csrwng FYI

**Comment by bfallonf** [comment]
I created a BZ:

https://bugzilla.redhat.com/show_bug.cgi?id=1276516

Closing this issue.
