### ISSUE TITLE
[enterprise-3.9] Edit suggested in file install_config/configuring_local.adoc

### ISSUE THREAD

**Issue by whitingjr** [openshift/openshift-docs#11064]
### Which section(s) is the issue in?
Configure Local Provision-er

### What needs fixing?
The documentation could do with an edit to indicate where the deployment instructions need executing. Is it run on master and all nodes or only master ?

**Comment by vikram-redhat** [comment]
@kalexand-rh - smallish fix (if you think it needs fixing).

**Comment by kalexand-rh** [comment]
@vikram-redhat, this is a storage question.
