### ISSUE TITLE
Arbiter Volume Support by OCS

### ISSUE THREAD

**Issue by ahardin-rh** [openshift/openshift-docs#11159]
### Which section(s) is the issue in?
3.10 Release Notes
https://github.com/openshift/openshift-docs/pull/11010

### What needs fixing?

Comments from @dmoessne:

The example mentions size=4 as well as options for `Storage Class Volume`without any further info or explanation if and why this is needed and I feel that could confuse customers and raise questions. do we have by chance any additional info we could provide or a link explaining this further ?

**Comment by ahardin-rh** [comment]
@childsb Can you please take a look and help me make this section of the release notes clearer? Thanks!

**Comment by tmorriso-rh** [comment]
@jarrpa Jose, can you take a look at this issue? I think it's related to CNS. Here is the link to the example:

https://github.com/ahardin-rh/openshift-docs/blob/7853c8a0a1a84258993ffae00bff57e5e0630933/release_notes/ocp_3_10_release_notes.adoc#arbiter-volume-support-by-ocs

**Comment by ahardin-rh** [comment]
@jarrpa Thank you! This is now addressed in https://github.com/openshift/openshift-docs/pull/11263
