### ISSUE TITLE
Ensure containerized OpenShift docs use --pid=host

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-docs#1119]
We should do a sweep and ensure every docker run of the node includes --pid=host

**Comment by bmcelvee** [comment]
This issue was opened several versions back, and from my preliminary search it appears `--pid=host` is included. I will continue to do a more thorough sweep.

**Comment by vikram-redhat** [comment]
Closing this issue as per @bmcelvee 's last comment.
