### ISSUE TITLE
\u0026 in examples

### ISSUE THREAD

**Issue by php-coder** [openshift/openshift-docs#1120]
In [Example 2. Image Stream Mapping Object Definition](https://docs.openshift.org/latest/architecture/core_concepts/builds_and_image_streams.html#image-stream-mappings) I see the following:

>        "Cmd": [
>          "/bin/sh",
>          "-c",
>          "tar -C /tmp -xf - \u0026\u0026 /tmp/scripts/assemble"
>        ],

Is this command really contains `\u0026`? I believe that `&` should be here.

**Comment by php-coder** [comment]
And the similar issue in [Referencing Images in Image Streams](https://docs.openshift.org/latest/architecture/core_concepts/builds_and_image_streams.html#referencing-images-in-image-streams):

>"Author": "Jakub Hadvig \u003cjhadvig@redhat.com\u003e",

**Comment by tnguyen-rh** [comment]
I've pinged @soltysh -- he says he's taking a look.

**Comment by soltysh** [comment]
All of those values are coming from docker daemon. I don't think we plan on changing it in any way since these are image metadata.

**Comment by tnguyen-rh** [comment]
@soltysh Thanks for taking a look. FTR, to recap our brief IRC discussion:
- It's OK to remove the `ImageStreamMapping` example.  An OpenShift user will never be able to access ISM using `oc get`.
- The `oc describe` command does indeed substitute the \uNNNN with the correct character.

Is that correct?  If so, i think a valid plan is:
- Remove the ISM example.
- Replace the "Referencing Images in Image Streams" example with the invocation and output of the `oc describe` command.

WDYT?

**Comment by php-coder** [comment]
@tnguyen-rh I don't mind.

**Comment by tnguyen-rh** [comment]
@php-coder Cool.  If @soltysh approves i'll get started immediately.

**Comment by soltysh** [comment]
:+1:

**Comment by tnguyen-rh** [comment]
Actually, "immediately" was wishful thinking.  I've created a BZ, instead -- https://bugzilla.redhat.com/show_bug.cgi?id=1279471 -- and will close this issue.  (If there is further discussion, it should be on the BZ.)

**Comment by tnguyen-rh** [comment]
Ugh, i suppose even being able to close this issue is wishful thinking.  I guess the honor falls upon @vikram-redhat  :smile:

**Comment by vikram-redhat** [comment]
Thanks @tnguyen-rh . Closing issue.
