### ISSUE TITLE
[enterprise-3.10] Edit suggested in file upgrading/automated_upgrades.adoc

### ISSUE THREAD

**Issue by gabrielstein** [openshift/openshift-docs#11216]
### Which section(s) is the issue in?
In-place Upgrades, 3.9 to 3.10

### What needs fixing?
Start:
On master hosts, back up the following, including the systemd files that will be removed during the upgrade to the control plane static pod architecture:

## Wrong part  ##

/etc/sysconfig/atomic-openshift-master-controller

###
## Right ##

/etc/sysconfig/atomic-openshift-master-controllers (needs an S on the end from controller)

###

###  How I reproduced that?

Running a Lab and following exactly the documentation.

**Comment by adellape** [comment]
Thanks for reporting!
