### ISSUE TITLE
[enterprise-3.9] Edit suggested in file install_config/cluster_metrics.adoc

### ISSUE THREAD

**Issue by mipam007** [openshift/openshift-docs#11223]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/3.9/install_config/cluster_metrics.html#openshift-prometheus

### What needs fixing?

Missing setting for persistent volume, at least for hostPath. NFS is not working. iSCSI haven't tested as we do not want to mix block and production network.

create LVM, or whatever storage on the compute node where the Prometheus is running and mount it.

chmod g+s /opt/prometheus (maybe not needed)
chown -R nobody:nobody /opt/prometheus/ (maybe not needed)
chcon -Rt svirt_sandbox_file_t /opt/prometheus (not working without that)

note: Couldn't create subdirs for alertmgr, alertmgs-buffer and prometheus-data.. its working only with one directory :(

then manually edit statefulsets, and add under spec, containers, args, volumes

- hostPath:
          path: /opt/prometheus
          type: ""
        name: prometheus-data
      - hostPath:
          path: /opt/prometheus
          type: ""
        name: alertmanager-data
      - hostPath:
          path: /opt/prometheus
          type: ""

**Comment by vikram-redhat** [comment]
Hi @mipam007 I am going to close this as this looks like a question for support, not docs. Please open a ticket with RH Support and they will be able to guide you: https://access.redhat.com/support/cases/#/case/new?intcmp=hp%7Ca%7Ca3%7Ccase

**Comment by mipam007** [comment]
Hi, I disagree as there is missing topic around volumes for Prometheus. There are maybe some bugs, but definitely you are not guiding users how to prepare persistent volume. 

Jindřich Káňa
+420 739 343 908
jindrich.kana@gmail.com

2. 8. 2018 v 5:49, Vikram Goyal <notifications@github.com>:
