### ISSUE TITLE
Wrong node_group_name on Preparing for an Automated Upgrade

### ISSUE THREAD

**Issue by Lasherbr** [openshift/openshift-docs#11233]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/3.10/upgrading/automated_upgrades.html
On section: "Preparing for an Automated Upgrade"
Item 3.e: 

### What needs fixing?
The hostname is confusing about the right node_group_name... infra shoud be placed on node-config-infra.

node1.example.com openshift_node_group_name='node-config-infra'
infra-node1.example.com openshift_node_group_name='node-config-compute'

Should be:

infra-node1.example.com openshift_node_group_name='node-config-infra'
inode1.example.com openshift_node_group_name='node-config-compute'

**Comment by adellape** [comment]
Thanks for reporting!
