### ISSUE TITLE
Selectors for Infra nodes should be using openshift_node_group_name

### ISSUE THREAD

**Issue by davivcgarcia** [openshift/openshift-docs#11299]
### Which section(s) is the issue in?

admin_guide/manage_nodes.adoc
admin_guide/managing_projects.adoc
admin_guide/topics/proc_adding-hosts.adoc
install/configuring_inventory_file.adoc
install_config/cluster_metrics.adoc
install_config/router/default_haproxy_router.adoc

### What needs fixing?

Many parts of the documentation still uses `{"region":"infra"}`, `{"region": "infra"}` or `region=infra` as node selector for Infra nodes. Starting on 3.10, we should be using `{"node-role.kubernetes.io/infra":"true"}` or `node-role.kubernetes.io/infra=true` configured by `openshift_node_group_name` variable.

**Comment by vikram-redhat** [comment]
@mburke5678 - PTAL.
