### ISSUE TITLE
Release notes for 3.1

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-docs#1131]
Here are the items that must be part of the 3.1 release notes:

* Binary builds and the Dockerfile source type for builds are tech preview for 3.1.

This is a tracking issue and should stay open.

**Comment by smarterclayton** [comment]
@adellape @bfallonf

**Comment by soltysh** [comment]
* jobs (although part of the extensions k8s api)

**Comment by kargakis** [comment]
* enchanced logs command (+ deprecated build-logs)

**Comment by soltysh** [comment]
* import external (kind==DokcerImage) images in imagestreams, additionally referencing images

**Comment by smarterclayton** [comment]
* DNS names for service SRV discovery have changed (more details needed) as part of #5613

**Comment by smarterclayton** [comment]
These aren't change notifications guys - these are "indications of a change in behavior that is surprising, or a feature in tech preview, or something people should be aware of"

**Comment by smarterclayton** [comment]
So 

* The `oc build-logs BUILDNAME` syntax has been deprecated and replaced by `oc logs build/BUILDNAME`

**Comment by smarterclayton** [comment]
* OpenShift prereqs Docker 1.8.2 - @ncdc @rhatdan we need to make sure we're set on this and the reasons why

**Comment by pmorie** [comment]
@smarterclayton 

> OpenShift prereqs Docker 1.8.2 - @ncdc @rhatdan we need to make sure we're set on this and the reasons why

Where do you want this doc'd?

**Comment by pmorie** [comment]
Nevermind.

**Comment by derekwaynecarr** [comment]
The OpenShift node defaults to serializing all image pulls from docker registries.

Concurrent docker image pulls may result in corrupted images when using versions of docker prior to 1.9.  To work-around this issue, the node defaults to serializing all image pulls.  We do not recommend changing this default value, but if it is desired, you can change the ```node-config.yaml``` file to add a stanza like the following:

**node-config.yaml**
```
...
kubeletArguments:
  serialize-image-pulls:
    - "false"
kind: NodeConfig
...
```

The default behavior is subject to change in the future to allow concurrent pulls by default once the requisite changes have been made in docker 1.9.

**Comment by pmorie** [comment]
The latest docker 1.8.2 is required; it contains a fix that lets containers without an `/etc/groups` file use supplemental groups.

**Comment by pweil-** [comment]
SCCs should be upgraded but defaults will be provided for FSGroup and SupGroups if they aren't.  Will be updating the UPGRADE doc today with the expectation that the new reconcile command will land https://github.com/openshift/origin/pull/5606

**Comment by sdodson** [comment]
* Openshift Enterprise services have been renamed from `openshift-master` and `openshift-node` to `atomic-openshift-master` and `atomic-openshift-node` respectively
* The configuration path has been renamed from `/etc/openshift` to `/etc/origin`. If you already have `/etc/openshift` at the time of upgrade a symbolic link will be created from `/etc/origin` to `/etc/openshift`
* The data directory has been renamed from `/var/lib/openshift` to `/var/lib/origin`. If you already have `/var/lib/openshift` at the time of upgrade a symbolic link will be created from `/var/lib/openshift` to `/var/lib/origin`

**Comment by smarterclayton** [comment]
In some scenarios, an excessive number of events can be created by components encountering errors. Those events are stored in etcd and can result in memory growth (which, if unchecked, could lead to OOM of etcd). Administrators should set the `event-ttl` advanced argument to a value that makes sense for their deployment if they encounter this issue.  

In `master-config.yaml`, add the following stanza to set the event TTL. If you are experiencing high event volume, set the TTL to a lower value like 15 minutes `15m`. The default is two hours `2h`

    kubernetesMasterConfig:
      apiServerArguments:
        event-ttl:
        - "15m"

**Comment by bparees** [comment]
If a build is created while there are insufficient resources to create the pod for the build, the build will stay in the pending state indefinitely.  The workaround is free up resources, cancel the build, and start a new build.
https://bugzilla.redhat.com/show_bug.cgi?id=1278232

**Comment by miminar** [comment]
There's a high probability a push to internal registry failing when multiple registry replicas share NFS storage volume. The work-around is to set `sessionAffinity` of `docker-registry` service to `ClientIP` causing requests from particular node be handled by the same replica. For example:

    oadm registry --credentials=/etc/origin/master/openshift-registry.kubeconfig --images='registry.access.redhat.com/openshift3/ose-${component}:${version}' --replicas=2
    oc get -o yaml svc docker-registry | sed 's/\(sessionAffinity:\s*\).*/\1ClientIP/' | oc replace -f -

More info in https://bugzilla.redhat.com/show_bug.cgi?id=1277356 and PR#5761

**Comment by bfallonf** [comment]
All, thanks much for all this info.

@sdodson If these have changed, then is there a reason they have not changed in the docs? What I'm asking is, should we be changing all these values in the docs as well?

@bparees @miminar So these are BZ fixes? Are they going to be released by 3.1? I can see the BZs are on NEW and ASSIGNED respectively.

Again, thanks for the help, all.

**Comment by miminar** [comment]
@bfallonf speeking just for [rhbz#1277356](https://bugzilla.redhat.com/show_bug.cgi?id=1277356). No, it's going to be fixed in the upcoming release. For 3.1 we are documenting just a [work-around](https://github.com/openshift/openshift-docs/pull/1174).

**Comment by bparees** [comment]
@bfallonf no, it's a bug that will be in the shipping product which is why it's being release noted.

**Comment by sdodson** [comment]
@bfallonf I've put in https://github.com/openshift/openshift-docs/pull/1176 to update the docs for renames, just need release notes hi-lighting the change. I'm not sure how to do this in a way that ensures we don't update the 3.0 docs though.

**Comment by bfallonf** [comment]
@miminar @bparees  Cool. I get you both. I'll put them into a "Know Issues" section.

@sdodson Cool. I see the PR now. I'll update the OSE Rel Notes accordingly.
