### ISSUE TITLE
[enterprise-3.10] Edit suggested in file install/configuring_inventory_file.adoc

### ISSUE THREAD

**Issue by amelie1979** [openshift/openshift-docs#11348]
### Which section(s) is the issue in?

beginning of the page

### What needs fixing?
the packages name is now openshift-ansible and not atomic-openshift-utils

**Comment by vikram-redhat** [comment]
@amelie1979 Hi there. Thanks for filing this issue but I don't see the reference in the file you have listed this in: https://docs.openshift.com/container-platform/3.10/install/configuring_inventory_file.html.

I will close this issue, but please feel free to open a new one if you find it anywhere else.

**Comment by amelie1979** [comment]
Its in Customizing Inventory Files for Your Cluster

When you install the **openshift-ansible-utils RPM** package as described in Host Preparation, Ansible dependencies create a file at the default location of /etc/ansible/hosts. However, the file is simply the default Ansible example and has no variables related specifically to OpenShift Container Platform configuration. To successfully install OpenShift Container Platform, you must replace the default contents of the file with your own desired configuration per your cluster topography and requirements.
