### ISSUE TITLE
[enterprise-3.10] Edit suggested in file architecture/index.adoc

### ISSUE THREAD

**Issue by vijay-agrawal** [openshift/openshift-docs#11412]
### Which section(s) is the issue in?
Fig 1

### What needs fixing?
No description on the architecture components..what is "Infra Node" purpose? "master node" purpose..either explain it concisely or remove the diagram..

**Comment by vikram-redhat** [comment]
@bmcelvee - can you take a look at this? This issue is that this diagram may now be out of date and the text around it might need updating as well. Please consult with @adellape on it.

**Comment by vikram-redhat** [comment]
@bmcelvee - any update on this?

**Comment by bmcelvee** [comment]
Thanks @vijay-agrawal and @vikram-redhat! Tracking in https://github.com/openshift/openshift-docs/pull/11631.
