### ISSUE TITLE
[enterprise-3.10] Edit suggested in file upgrading/automated_upgrades.adoc

### ISSUE THREAD

**Issue by whitingjr** [openshift/openshift-docs#11416]
### Which section(s) is the issue in?

Preparing for an Automated Upgrade > 3 > f

### What needs fixing?

The playbook in this section does not exist. 

# ls /usr/share/ansible/openshift-ansible/playbooks/openshift-master/openshift_node_group.yml
ls: cannot access /usr/share/ansible/openshift-ansible/playbooks/openshift-master/openshift_node_group.yml: No such file or directory
#

 I suspect the author assumes files in the OCP 3.10 packages are on the filesystem. At this point in the installation the file system still has OCP 3.9 installed.

**Comment by kalexand-rh** [comment]
This is the same issue as #11432, and I'm going to follow up with QE about the fix there. Thanks!

**Comment by whitingjr** [comment]
So it is. Sorry for not spotting that one. Thanks for sorting it.
