### ISSUE TITLE
Document that containerized origin only works on Red Hat systems because of mount propagation

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-docs#1149]
As per https://github.com/openshift/origin/issues/3072

**Comment by smarterclayton** [comment]
@adellape we need to get this fixed really soon, we've also hit this a lot with end users.  We need to say "Containerized install is supported for Fedora, CentOS, and RHEL OS only" somewhere on the install page (no one reads the prerequisites or believes them).

**Comment by adellape** [comment]
@smarterclayton OK, in https://docs.openshift.org/latest/getting_started/administrators.html#running-in-a-docker-container and in the relevant spots as we document the containerized install via Ansible?

**Comment by adellape** [comment]
Will do the former first tho.

**Comment by smarterclayton** [comment]
As long as someone about to start realizes it, that's enough.  People
aren't reading the prereqs page.  Other operating systems should use the
binary install path.
