### ISSUE TITLE
[enterprise-3.10] Edit suggested in file install_config/configuring_aws.adoc

### ISSUE THREAD

**Issue by jsm84** [openshift/openshift-docs#11504]
### Which section(s) is the issue in?
* Permissions
* Labeling Clusters for AWS

### What needs fixing?
There is inconsistency between each of these sections on what the tags/labels should be. Under the *Permissions* section, the labels are defined as `kubernetes.io/cluster/<name>,Value=<clusterid>`, whereas under *Labeling Clusters for AWS* they are mentioned as `kubernetes.io/cluster/<clusterid>,Value=(owned|shared)`. I find that the latter method of tagging AWS resources works in testing (this method makes the most sense), whereas the former seems redundant (eg: `<clusterid>` and `<name>` in the same tag). I believe this is an accidental conglomeration of both the old and new methods of tagging resources, being that `Key=KubernetesCluster,Value=clusterid` is mentioned in the *Labeling Clusters for AWS* section as being the old/outdated label. If I'm incorrect, then perhaps some further clarification/differentiation would help in the docs.

**Comment by vikram-redhat** [comment]
@gaurav-nelson  - PTAL

**Comment by gaurav-nelson** [comment]
Thanks @jsm84 for pointing this one out. Somehow we missed to update those labels in https://github.com/openshift/openshift-docs/pull/10434, I will soon fix this.
