### ISSUE TITLE
Auto generate kubernetesMasterConfig and kubeletArguments documentation

### ISSUE THREAD

**Issue by sdodson** [openshift/openshift-docs#1151]
There's a wealth of kube config options exposed via kubernetesMasterConfig and kubeletArguments that it'd be nice to document in openshift. Ideally by importing docs from kubernetes if that's technically and legally feasible.

**Comment by liggitt** [comment]
There are a wealth of options, but many are untested, and many interact in unpredictable ways. I would not want to make it seem like all possible options are supported at the same level as our tested configurations

**Comment by deads2k** [comment]
Also, when the arguments or acceptable values change, bad values can fail the server.  This was build as an escape hatch for very skilled users with very narrow needs.  The vast majority of customer should never use the feature.

If we have a particular flag we see getting a lot usage, we should add it to our primary config.

**Comment by sdodson** [comment]
Makes sense. The only one I can think of that fits that is maxPods.

**Comment by csrwng** [comment]
Garbage collection ... https://github.com/openshift/openshift-docs/pull/1168

**Comment by bmcelvee** [comment]
Looks like it is safe to close this issue. If there is any additional documentation required, please let me know.
