### ISSUE TITLE
[enterprise-3.10] Edit suggested in file install/running_install.adoc

### ISSUE THREAD

**Issue by whitingjr** [openshift/openshift-docs#11528]
### Which section(s) is the issue in?

Running the RPM-based Installer
Section 2

### What needs fixing?

The cluster command line needs to include a variable ansible_ssh_user. 
eg

`# ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml -e ansible_ssh_user=root`

Why does it need fixing.

Am seeing this issue 
https://github.com/openshift/openshift-ansible/issues/4496

**Comment by kalexand-rh** [comment]
Ok! I'll close this one, then. Please let us know if you come across more issues.
