### ISSUE TITLE
Missing installation of etcd on master when multiple etcd hosts are used

### ISSUE THREAD

**Issue by jmarley** [openshift/openshift-docs#1153]
On advanced_install.adoc there is no instructions to install etcd on the master node when multiple etcd hosts are used. To verify the installation the document asks the user to use etcdctl on the master, but the ansible script as is doesn't install etcd on the master.

**Comment by bmcelvee** [comment]
It looks like the documentation has been updated since this issue was opened: https://docs.openshift.org/latest/install_config/install/advanced_install.html. I going to go ahead and close this issue. If there is any additional documentation needed, please let me know.
