### ISSUE TITLE
[enterprise-3.9] Edit suggested in file release_notes/ocp_3_9_release_notes.adoc

### ISSUE THREAD

**Issue by lukranawetter** [openshift/openshift-docs#11572]
### Which section(s) is the issue in?

Asynchronous Errata Updates -> RHBA-2018:2335 - OpenShift Container Platform 3.9.40 Bug Fix and Enhancement Update

### What needs fixing?

Broken link:
<a href="https://access.redhat.com/errata/RHSA-2018:2335">RHBA-2018:2335</a>

Correct:
<a href="https://access.redhat.com/errata/RHBA-2018:2335">RHBA-2018:2335</a>

**Comment by vikram-redhat** [comment]
@tmorriso-rh PTAL. 

cc: @ahardin-rh

**Comment by tmorriso-rh** [comment]
WIP: https://github.com/openshift/openshift-docs/pull/11612

**Comment by tmorriso-rh** [comment]
The broken link is now fixed via https://github.com/openshift/openshift-docs/pull/11613. The change should be live soon. Closing this issue.
