### ISSUE TITLE
[enterprise-3.10] Edit suggested for https://docs.openshift.com/container-platform/latest URL

### ISSUE THREAD

**Issue by jsm84** [openshift/openshift-docs#11595]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/latest

### What needs fixing?
change the redirect for 'latest' from 3.9 to 3.10

**Comment by vikram-redhat** [comment]
@jsm84 - It does go to 3.10 docs for me. Are you seeing it go to 3.9?
