### ISSUE TITLE
install_config/master_node_configuration.adhoc - Clarify Advanced Auditing documentation

### ISSUE THREAD

**Issue by CelsoSantos** [openshift/openshift-docs#11607]
### Which section(s) is the issue in?
install_config/master_node_configuration.adhoc
Advanced Audit Section

### What needs fixing?
While for Basic Auditing it's clear that one must edit the master-config.yaml file, for advanced auditing it is unclear if one should add the parameters to the `auditConfig` key or if an additional key specific to advanced auditing is needed (something like `advancedAuditConfig`).
Linking to the Kubernetes docs also does not make this clear since on Kubernetes one can use `kube-apiserver` command to make those configurations.

Provide an example of how to add Advanced Auditing on `master-config.yaml`

**Comment by kalexand-rh** [comment]
@CelsoSantos, would this PR answer your questions?  https://github.com/openshift/openshift-docs/pull/11510

**Comment by CelsoSantos** [comment]
Indeed it does.
While I figured it out meanwhile, I find that the way the feature is
described is ambiguous on how to be applied, thus this issue.

Thank you.
Best Regards

**Comment by kalexand-rh** [comment]
This will be fixed with https://github.com/openshift/openshift-docs/pull/11835
