### ISSUE TITLE
imagepolicy link points to wrong location

### ISSUE THREAD

**Issue by bparees** [openshift/openshift-docs#11633]
https://docs.openshift.com/container-platform/3.10/admin_guide/image_policy.html

in the paragraph
```
Allowed Registries for import is an image policy configuration that allows to restrict image origins to particular set of external registries. This set of rules is applied to any image being imported or tagged into any image stream. Therefore any image referencing registry not matched by the rule set will be rejected.
```

the link points to:
https://docs.openshift.com/container-platform/3.10/admin_guide/image_policy.html#image-policy-configuring-the-image-policy-admission-plug-in

but it should point to:
https://docs.openshift.com/container-platform/3.10/install_config/master_node_configuration.html#master-config-image-policy-config

**Comment by bparees** [comment]
@bmcelvee

**Comment by bmcelvee** [comment]
@bparees updating link in https://github.com/openshift/openshift-docs/pull/11647. Mind if I close this issue?
