### ISSUE TITLE
[enterprise-3.9] Edit suggested in file getting_started/developers_console.adoc

### ISSUE THREAD

**Issue by rubin55** [openshift/openshift-docs#11689]
### Which section(s) is the issue in?
Under the header "Configuring Automated Builds"

### What needs fixing?
You provide the instructions to get the webhook url from the build config in Openshift. However, it is neglected to mention that you also need to set the Content Type to application/json. By default the Content Type is application/x-www-form-urlencoded, which will cause a HTTP 400 Bad Request failure. Note that the openshift docs here: https://docs.openshift.com/container-platform/3.9/dev_guide/migrating_applications/web_hooks_action_hooks.html *do* mention to specify the Content Type as application/json.

**Comment by rubin55** [comment]
Why is this closed without fix? What is the point of asking people to open an issue when they run into something, wait more than a year and not do anything, to then close the issue without comment?

**Comment by jboxman** [comment]
@rubin55, I opened https://github.com/openshift/openshift-docs/pull/18757 for this.
