### ISSUE TITLE
openshift start node is deprecated and --config no longer works

### ISSUE THREAD

**Issue by adelton** [openshift/openshift-docs#11751]
### Which section(s) is the issue in?

https://docs.okd.io/latest/install_config/master_node_configuration.html

### What needs fixing?

The text says

> The openshift start command and its subcommands (master to launch a master server and node to launch a node server) ...

and

> To make this easier, the configuration files can be created with the --write-config option and then used with the --config option.

However, running `openshift start node --config /etc/origin/node1/node-config.yaml` command which used to be working for many releases now fails with

```
Command "start" is deprecated, This command will be replaced by the hypershift and hyperkube binaries for starting individual components.
Error: unknown flag: --config


Available Commands:
  etcd        Launch etcd server
  master      Launch a master
  network     Launch node network

Use "openshift <command> --help" for more information about a given command.
```

So it seems that `openshift start node` should not longer be recommended and alternative documentation for starting node is needed. Also, the mention of using `--config` seems no longer correct, as it's no longer recognized at all.

**Comment by adelton** [comment]
No, I sadly don't know how to solve the problem, short of using openshift-ansible.

**Comment by hdonati** [comment]
No news ? 
It is impossible to upgrade OKD cluster 3.10 to 3.11 with freshly delivered Centos7 RPMs from repo http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin/
`systemctl start origin-node `
fails because of line in /etc/systemd/system/origin-node.service : 
`ExecStart=/usr/bin/openshift start node  --config=${CONFIG_FILE} $OPTIONS`
after upgrade 
Is there another way to start a node ???

**Comment by ricardoferreiracosta08** [comment]
On latest version, v3.11.0, the` openshift start node `functionality and `openshift start` have been removed - the Kubelet must now be started directly [#20344](https://github.com/openshift/origin/pull/20344), [#20717](https://github.com/openshift/origin/pull/20717)

- By using the Kubelet directly we make nodes easier to manage and more consistent with the upstream.
- Future releases will remove other parts of `openshift start master`. 

Reference: [https://github.com/openshift/origin/releases/tag/v3.11.0](https://github.com/openshift/origin/releases/tag/v3.11.0)

**Comment by adelton** [comment]
Thanks, @ricardoferreiracosta08. Could the documentation at https://docs.okd.io/latest/install_config/master_node_configuration.html be updated to reflect that change?

**Comment by adelton** [comment]
When I replace

```
openshift start node --config /etc/origin/node-$(hostname)/node-config.yaml
```

with

```
hyperkube kubelet $( /usr/bin/openshift-node-config --config=/etc/origin/node-$(hostname)/node-config.yaml )
```

the process ends up with reporting

```
W0611 10:26:29.656136   27448 cni.go:172] Unable to update cni config: No networks found in /etc/cni/net.d
E0611 10:26:29.656244   27448 kubelet.go:2101] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
```

The `/etc/cni/net.d` is empty, while with `openshift start node` it has `/etc/cni/net.d/80-openshift-network.conf` containing

```
{
  "cniVersion": "0.2.0",
  "name": "openshift-sdn",
  "type": "openshift-sdn"
}
```

@ricardoferreiracosta08, would you know how to force `hyperkube kubelet` to also configure the CNI?

**Comment by krumware** [comment]
Can someone confirm whether or not these instructions are supposed to work with 3.11? We are also seeing the same issue.
https://docs.okd.io/latest/getting_started/administrators.html#downloading-the-binary

**Comment by donghwicha** [comment]
> On latest version, v3.11.0, the`openshift start node`functionality and `openshift start` have been removed - the Kubelet must now be started directly [#20344](https://github.com/openshift/origin/pull/20344), [#20717](https://github.com/openshift/origin/pull/20717)
> 
>     * By using the Kubelet directly we make nodes easier to manage and more consistent with the upstream.
> 
>     * Future releases will remove other parts of `openshift start master`.
> 
> 
> Reference: https://github.com/openshift/origin/releases/tag/v3.11.0

Can you please provide document?

**Comment by adelton** [comment]
The above approach also work for OCP 3.11.

**Comment by adellape** [comment]
Fixed via https://github.com/openshift/openshift-docs/pull/21268.
