### ISSUE TITLE
Running in a Docker Container permanent config and definitions

### ISSUE THREAD

**Issue by shannon** [openshift/openshift-docs#1177]
When running OpenShift in a docker container as per the [docs](https://docs.openshift.org/latest/getting_started/administrators.html#running-in-a-docker-container) it states 

> If you delete the container, any configuration or stored application definitions will also be removed.

Is all of the OpenShift data stored in etcd? I'd like to be able to mount in a volume to the etcd data-dir so that I can persist the data without the container. Mainly for the ability to update OpenShift (by pulling the new image) without having to start over every time. 

I apologize if this has been discussed before, I couldn't find any mention of it.

**Comment by vikram-redhat** [comment]
This is not a docs question (and is also nearly 3 years old). I am now closing it.
