### ISSUE TITLE
team documentation returns 404

### ISSUE THREAD

**Issue by Gl4di4torRr** [openshift/openshift-docs#11809]
### Which section(s) is the issue in?
https://github.com/openshift/openshift-docs/blob/master/contributing_to_docs/contributing.adoc 

Under the section **What happens when you submit a PR?**, the link `documentation team` returns a 404.

Here is the link it is pointing to:
https://github.com/orgs/openshift/teams/team-documentation

### What needs fixing?
Update url

**Comment by vikram-redhat** [comment]
@Gl4di4torRr Hey Chris, it seems that that link is only visible if you are a part of the OpenShift organisation. I have changed it and instead suggested that the use of the tag for team-documentation.

**Comment by Gl4di4torRr** [comment]
@vikram-redhat haha yeah, i noticed that once a redhat engineer referred to the tag in a pr. thanks!
