### ISSUE TITLE
missing new router stuff

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-docs#1192]
https://github.com/openshift/origin/blob/v1.0.8/pkg/cmd/infra/router/router.go#L41-L48

These don't appear to be doc'd either in the help output for the router (`oadm router`) or in the docs.

**Comment by mburke5678** [comment]
@thoraxe What is the status of these flags? These flags do not appear in the docs, from my quick search, and I do not see them in the 3.5 CLI help output. Are they still in the code?

**Comment by thoraxe** [comment]
https://github.com/openshift/origin/blob/master/pkg/cmd/infra/router/router.go#L64-L79

Now there are more...

**Comment by thoraxe** [comment]
@rajatchopra @knobunc

**Comment by mburke5678** [comment]
Created a docs Bugzilla. Closing this issue.
https://bugzilla.redhat.com/show_bug.cgi?id=1461938

**Comment by knobunc** [comment]
Commented on the bug too:

The flags you are looking at are not oadm router flags.  They are the flags for the router command that runs inside the docker container.

The environment variables (which are the expected way to manipulate the settings) are documented at: https://github.com/openshift/openshift-docs/blob/master/architecture/core_concepts/routes.adoc#env-variables

Note that we do not document ROUTE_FIELDS deliberately... the field selector is not supported properly by kube yet.

**Comment by thoraxe** [comment]
Thanks, Ben! This issue is really old and was related to one of the new router features that wasn't previously documented. Sounds like the docs are much improved.
