### ISSUE TITLE
Add mappingMethod docs for identity providers

### ISSUE THREAD

**Issue by liggitt** [openshift/openshift-docs#1196]
https://github.com/openshift/origin/pull/5060 adds a `mappingMethod` option to all identity providers to configure how new identities are mapped to users on login.

A new `mappingMethod` config field is added to all identity providers (peer to `login` and `challenge` fields):

```
oauthConfig:
  ...
  identityProviders:
  - challenge: true
    login: true
    mappingMethod: "..."
    ...
```

`mappingMethod` can be set to the following values:

* **claim** (default)
  * Provision with preferred username for the identity, fail if username is already mapped to another identity
* **lookup**
  * Administrator wants to manually configure identity/user mappings. Login process should only look up existing mappings, not create them
* **generate**
  * Provision with generation of unique usernames, based on the preferred username for the identity (e.g. "bob", "bob2")
  * This strategy should not be used in combination with external processes that require exact matches between OpenShift user names and the identity provider's user names (like LDAP group sync)
* **add**
  * Provision with preferred username for the identity, add to existing user if username is already mapped to another identity
  * Needed when multiple identity providers are configured which identity the same set of users and map to the same usernames

**Comment by bfallonf** [comment]
There's a BZ for this PR already. I'll close this, and put Jordan's above solution into the BZ. 

This will be fixed post-3.1 (and I'll try get it in the docs soon).

**Comment by liggitt** [comment]
if you like, but I have it on my list to put together a PR for this

**Comment by bfallonf** [comment]
@liggitt  I don't mind working on this (though pinging you when it's ready). I already have a PR open atm.

**Comment by liggitt** [comment]
ok, could be as simple as adding `mappingMethod` to the common parameters section for identity providers at https://github.com/openshift/openshift-docs/blob/master/install_config/configuring_authentication.adoc#identity-providers, and updating examples to include the new field

**Comment by bfallonf** [comment]
@liggitt Sure thing. Thanks for that! Expect to be pinged soon...
