### ISSUE TITLE
When to use OpenShift or OKD in the text

### ISSUE THREAD

**Issue by alexandrevicenzi** [openshift/openshift-docs#12104]
### Which section(s) is the issue in?

Many.

### What needs fixing?

Many pages have references to OpenShift in the text and others have OKD.

There are pages that talks about OpenShift v3 and others that refer to OKD v3.
There are pages that in one paragraph is used OpenShift and other is used OKD.

This can cause some confusion in my opinion. Also, I'm not sure when to use one or another term. My guess, everything should reference to OKD in [OKD documentation](https://docs.okd.io/).

**Comment by alexandrevicenzi** [comment]
@kalexand-rh can you help me on this?

**Comment by kalexand-rh** [comment]
@alexandrevicenzi, can you give me a few specific examples? Unless we're talking about a component that has "OpenShift" in its name, we use the {product-title} variable to substitute the correct product name for that specific collection.

**Comment by alexandrevicenzi** [comment]
For example, [here](https://docs.okd.io/3.9/dev_guide/migrating_applications/index.html) is used in the same page both OpenShift v2 / v3 and OKD v3.

Also, [here](https://docs.okd.io/latest/whats_new/index.html) is used OpenShift v3 but it's "OKD Whats New".

[Here](https://docs.okd.io/latest/dev_guide/openshift_pipeline.html) is a case of a component name, in this case, it's correct.

Basically, my question is when should use one or another form.

**Comment by alexandrevicenzi** [comment]
@kalexand-rh for me OKD is the "open source" version, that anyone can use. OpenShift for me is the product available on [openshift.com](https://www.openshift.com/). But I'm not 100% sure of that.

This is what I think it's confusing. Maybe it's a good idea to have a page explaining about OKD, OpenShift, Origin and any other project name related.

**Comment by kalexand-rh** [comment]
@vikram-redhat, what do you think about explaining the versions and names?
Should we defer trying to fix all the names in the collection to 4.0?

**Comment by kalexand-rh** [comment]
@alexandrevicenzi, we're going to discuss this with PM and provide guidance either on https://github.com/openshift/openshift-docs/pull/12516 or a follow-up PR. The docs team will apply the clarifications to the 4.0 collection. At this point, we can't commit to backporting the changes to the 3.x collections.

I can keep this issue open until the changes are in place, but if you're ok with the proposed fix, please close the issue.

**Comment by alexandrevicenzi** [comment]
@kalexand-rh This proposal is ok for me. Looking forward to seeing the updates in version 4.0.
