### ISSUE TITLE
Regarding documentation for hybrid Openshift deployment

### ISSUE THREAD

**Issue by go2murali** [openshift/openshift-docs#12160]
### Which section(s) is the issue in?
Could not find documentation for deploying Openshift Origin 3.6 with masters and infra nodes on VMs and application nodes on Bare metal

### What needs fixing?
Could you please provide documentation for deploying Openshift Origin 3.6 with masters and infra nodes on VMs and application nodes on Bare metal

**Comment by mburke5678** [comment]
We are not updating documentation prior to 3.10.
