### ISSUE TITLE
Enumerate valid trigger names in JSON Schema

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/openshift-docs#1220]
Could we improve the REST API docs to enumerate the valid values of `BuildTriggerPolicy.type`?

https://docs.openshift.org/latest/rest_api/openshift_v1.html#v1-buildtriggerpolicy says it's a required string; we could enumerate the valid values, e.g., `GitHub`, `ImageChange`, etc.

Reference: https://github.com/openshift/origin/issues/4024#issuecomment-157776849

**Comment by rhcarvalho** [comment]
@adellape @tnguyen-rh WDYT?

**Comment by tnguyen-rh** [comment]
@rhcarvalho 
I think the answer is [yes](https://bugzilla.redhat.com/show_bug.cgi?id=1258235) and hope to find some time to learn golang well enough to understand the current swagger deficiencies, as a first step, and make API reference docs more accurate and easier to maintain, as the second step.

**Comment by vikram-redhat** [comment]
Since this is already being captured by the BZ @tnguyen-rh mentioned (https://bugzilla.redhat.com/show_bug.cgi?id=1258235), I am going to close this issue. I have mentioned this issue in the BZ itself.
