### ISSUE TITLE
3.11 Release Notes Feedback Tracker

### ISSUE THREAD

**Issue by ahardin-rh** [openshift/openshift-docs#12263]
Comment with your feedback for the 3.11 Release Notes

**Comment by robszumski** [comment]
Make some Operator related edits here already: https://github.com/openshift/openshift-docs/pull/12270/

**Comment by sichvoge** [comment]
Made some edits to the Prometheus Cluster Monitoring section here: #12284

**Comment by mbearer** [comment]
- Should 

> HA NAMESPCE-WIDE EGRESS IP

_ say NAMESPACE or NAMESPCE?
- Space missing int his sentence: 

> The Node Problem Detector continues to be in Technology Previewfor this release and is not for production workloads.

- (.) missing in row 7 of the 4.0 Deprecated Features table 

Can this sentence be simplified/clarified a bit:

> You can now control the use of the local ephemeral storage feature on your nodes in order to prevent users from exhausting node local storage with their pods and other pods that happen to be on the same node.

**Comment by tmorriso-rh** [comment]
+[[ocp-311-service-catalog-access-control]]
+==== Service Catalog Access Control
+
+The broker now confirms to the Open Service Broker specification, which means

typo - this should be conforms

**Comment by vikram-redhat** [comment]
3.11 is released. Closing this.
