### ISSUE TITLE
Better docs for jobs

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-docs#1227]
1) https://docs.openshift.org/latest/dev_guide/jobs.html doesn't let me know what jobs are about and why would I want to use them (would be better to compare against a deployment (dc) rather than a replication controller?). 

2) I think the explanation about parallelism is slightly wrong. It mentions about running pods concurrently but I think we should be more specific and note that parallelism means the maximum # of pods that can run in **parallel** at a given time. Also we should probably document the [logic](https://github.com/kubernetes/kubernetes/blob/742243bb4adc9dc83411354566667259bcd7d7ee/pkg/controller/job/controller.go#L364) in the job controller. As a user I think I would be interested in these details.

3) The scaling part should make it explicit that by scaling a job we scale the pods that can run in parallel and maybe reduce the amount of times parallelism is mentioned (one would probably be enough?)

cc: @soltysh 

@tnguyen-rh interested in getting into jobs? :P

**Comment by bfallonf** [comment]
I wrote this for the 3.1 release with @soltysh , so i don't mind filling in the blanks (you're off the hook, @tnguyen-rh ...)

@soltysh would you mind addressing the questions above? Then I can put in some more info.

Thanks, guys!

**Comment by soltysh** [comment]
I'll craft a PR explaining above questions and tag you all to review it, but not until tomorrow.

**Comment by tnguyen-rh** [comment]
@kargakis @bfallonf 
Thanks for the opportunity to decline. :-D

**Comment by bfallonf** [comment]
@soltysh That works for me.

@tnguyen-rh You're welcome!

**Comment by vikram-redhat** [comment]
@soltysh if you are submitting a PR, can we close this issue? @bfallonf

**Comment by soltysh** [comment]
@vikram-redhat please leave it open until I'll submit a PR. I'll mention it in there and it'll be closed automatically when PR gtes merged.
