### ISSUE TITLE
Suggestions for Decision Server doc

### ISSUE THREAD

**Issue by bdecoste** [openshift/openshift-docs#1229]
- Maybe replace "regular release of JBoss BRMS" with "full, non-PaaS release of JBoss BRMS". We need a good term for differentiating PaaS and non-PaaS products
- Do we need "Execution of business processes are not supported"? Those require BPMS and aren't supported by the full, non-PaaS BRMS
- "Authoring of business rules are not supported." Should be expanded to authoring of anything through the BRMS console or API is not supported (e.g. Facts). Perhaps state what is different between the PaaS release and https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_BRMS/6.1/html/User_Guide/chap-The_Realtime_Decision_Server.html?

**Comment by adellape** [comment]
xref https://github.com/openshift/openshift-docs/pull/1195

cc @huffmanca

**Comment by vikram-redhat** [comment]
Incorporated by https://github.com/huffmanca/openshift-docs/commit/e170860261ee13e657e054329ae029c8f8e06623. Closing this issue. For any more edits, please log a comment on the PR: https://github.com/openshift/openshift-docs/pull/1195
