### ISSUE TITLE
[enterprise-3.10] Edit suggested in file install_config/certificate_customization.adoc

### ISSUE THREAD

**Issue by jaywryan** [openshift/openshift-docs#12312]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/3.10/install/configuring_inventory_file.html#advanced-install-custom-certificates
https://docs.openshift.com/container-platform/3.10/install_config/certificate_customization.html

### What needs fixing?
 * The references to cafile aren't valid.  the CA cert needs to be combined into the certfile.  the value here doesn't do anything.  There are a few references to this in these docs.

    * ```"cafile": "/path/to/custom-ca1.crt"}]```

  * Guidance is missing to ensure that the certificate should include any intermediate and root certificates in the Chain that aren't already in the trusted store. These certs should be ordered in the file from top to bottom (certificate / intermediate(s) / RootCA)

* In 'Configuring a Custom Master Host Certificate' There is reference to the registry certificate, which belong in the below section 'Configuring a Custom Certificate for the Image Registry'

* Conflicting guidance in Configuring a Custom Wildcard Certificate for the Default Router and Retrofit Custom Router Certificates into a Cluster.  does one run the redeploy-router or the redeploy-router-certificates.  I believe the former is correct if you are moving from self-signed to custom signed, but will need verification.
    * Former - If these certificate files are new to your OpenShift Container Platform cluster, run the Ansible deploy_router.yml playbook 
    * Later - To retrofit custom router certificates: .... Run the following playbook:

        ```ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/openshift-hosted/redeploy-router-certificates.yml```

**Comment by vikram-redhat** [comment]
@kalexand-rh - associated bug: https://bugzilla.redhat.com/show_bug.cgi?id=1635813

**Comment by kalexand-rh** [comment]
@ericavonb, who from the auth team should I sent my questions about this one to?

**Comment by ericavonb** [comment]
@kalexand-rh Most knowledgeable would be @mrogers950 probably.
