### ISSUE TITLE
rhel-7-fast-datapath-rpms required by OCP-3.10

### ISSUE THREAD

**Issue by ghyde** [openshift/openshift-docs#12326]
### Issue

When executing a fresh install of OCP 3.10, the install fails because the package "openvswitch" is not available. The required version of this package is currently available in the "rhel-7-fast-datapath-rpms" repository.

This might apply to 3.11 as well, but I haven't checked.

### What needs fixing?

Revert commit #11763 for 3.10. Might need to revert #11762 for 3.11 and #11565 for master.

**Comment by ghyde** [comment]
@sdodson @kalexand-rh ^^

**Comment by kalexand-rh** [comment]
If @sdodson agrees, I'll put in the changes.

**Comment by sdodson** [comment]
That repo is not necessary in 3.10 or later.

**Comment by ghyde** [comment]
Yup, my mistake. The client's Ansible host had the 3.9 playbooks installed. After upgrading them to 3.10, it worked. Thanks for the feedback.
