### ISSUE TITLE
Search box

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/openshift-docs#1235]
It would be awesome to have searchable documentation.

Having to navigate the menu to find specific things is too hard, and often we need to use an external search engine to find something in the docs.

Initial attempt to integrate Google Custom Search: #349.
Note, though, that I'm not a proponent of that particular solution, just want an integrated search box for the docs to save everyone's time and making pieces of doc easier to find and consume.

**Comment by vikram-redhat** [comment]
@nhr, @CowboysFan - is this something we could implement?

**Comment by nhr** [comment]
I am actively working on this. I finally got the code for two ad-free custom searches that we can use for .org and .com. Now I am working with UX to stitch them into the sites cleanly.

**Comment by vikram-redhat** [comment]
Thanks @nhr . @rhcarvalho  - please see the referenced PR. Closing this issue.
