### ISSUE TITLE
[enterprise-3.10] Edit suggested in file install/disconnected_install.adoc

### ISSUE THREAD

**Issue by binnyrs** [openshift/openshift-docs#12353]
### Which section(s) is the issue in?

orge_url=registry.example.com/openshift3/ose-${component}:${version}

### What needs fixing?

I think there is a typo. It should be "oreg_url" as below

oreg_url=registry.example.com/openshift3/ose-${component}:${version}

**Comment by vikram-redhat** [comment]
@tmorriso-rh - PTAL and verify in older versions as well.

**Comment by kalexand-rh** [comment]
This is only in 3.10 and 3.11. They've both been fixed.
