### ISSUE TITLE
[enterprise-3.6] Edit suggested in file install_config/persistent_storage/persistent_storage_nfs.adoc

### ISSUE THREAD

**Issue by joe-speedboat** [openshift/openshift-docs#12354]
### Which section(s) is the issue in?
nfs-export-settings

### What needs fixing?
iptables -I INPUT 1 -p tcp --dport 111 -j ACCEPT
this needs to be UDP

**Comment by vikram-redhat** [comment]
@tmorriso-rh - please verify with an SME or QE.

**Comment by joe-speedboat** [comment]
@tmorriso-rh @vbatts 
I do not use this version anymore, If you do not fix, I do not mind.
Was just a try to help improve the quality.

thanks chris

**Comment by jboxman** [comment]
@joe-speedboat, thanks for reporting this! We've been working on the docs for OpenShift 4.1 these past months and we haven't had as much time as we'd like to improve the 3.x docs.
