### ISSUE TITLE
oc export is deprecated, docs say otherwise

### ISSUE THREAD

**Issue by Askill** [openshift/openshift-docs#12409]
### Which section(s) is the issue in?
https://docs.okd.io/latest/dev_guide/templates.html

### What needs fixing?
oc export ist deprecated accoring to the console output.
oc get --export is not documented.

**Comment by bysnupy** [comment]
FYI, as I remember, `oc get --export` is not same the result with former `oc export` if you want to export `yaml` format from target `objects`.  Additionally  it needs to specify `-o yaml` for yaml format to export it.

**Comment by Askill** [comment]
Thanks fot the tip however that ist what following message suggests, either this or the Documentation should be changed.
![image](https://user-images.githubusercontent.com/16598120/46936969-59fd2400-d060-11e8-875f-41278613ab0d.png)

**Comment by ahardin-rh** [comment]
This was addressed in https://github.com/openshift/openshift-docs/pull/12579
