### ISSUE TITLE
[enterprise-3.11] Edit suggested in file release_notes/ocp_3_11_release_notes.adoc

### ISSUE THREAD

**Issue by nobusue** [openshift/openshift-docs#12421]
### Which section(s) is the issue in?
ACCESS CONTROL MANAGEMENT
https://docs.openshift.com/container-platform/3.11/release_notes/ocp_3_11_release_notes.html#ocp-311-access-control-management

### What needs fixing?
Placeholder remains. It seems to be a typo of `{product-title}` ?
> {product-tile} 3.11 includes visual management of the cluster’s RBAC roles and RoleBindings, which allows you to:

**Comment by tmorriso-rh** [comment]
This is fixed in https://github.com/openshift/openshift-docs/pull/12437.
