### ISSUE TITLE
Why the master branch is older than enterprise-3.11 branch ?

### ISSUE THREAD

**Issue by bysnupy** [openshift/openshift-docs#12467]
### Which section(s) is the issue in?

When I create new PR about different version branches, I recognize the `master` branch is a little old against other branches (enterprise-3.11 and 3.10). Let me know the master branch management policy in this repository.

For examples, `region=infra` label is not used as of v3.10, but the `master` branch remained the old label. Personally, I think it's odd.

At [master branch](https://raw.githubusercontent.com/openshift/openshift-docs/master/install/configuring_inventory_file.adoc)
~~~
|`template_service_broker_selector`
|Default node selector for automatically deploying template service broker pods,
defaults `{"region": "infra"}`. See
xref:configuring-node-host-labels[Configuring Node Host Labels] for details.
~~~

At [v3.11 branch](https://raw.githubusercontent.com/openshift/openshift-docs/enterprise-3.11/install/configuring_inventory_file.adoc)
~~~
|`template_service_broker_selector`
|Default node selector for automatically deploying template service broker pods,
defaults `{"node-role.kubernetes.io/infra":"true"}`. See
xref:configuring-node-host-labels[Configuring Node Host Labels] for details.
~~~

### What needs fixing?

My common sense is the `master` branch should be most recent code, so I wish to keep the `master` branch up-to-date.

**Comment by kalexand-rh** [comment]
@bysnupy, the policy in this repo is that unless the change has a specific reason that  it can't go into master, it goes into master and is then distributed to other branches through cherry-picks. Master should always have the latest information, and it's a mistake if it doesn't.

@vikram-redhat, FYI

**Comment by bysnupy** [comment]
Thank you for your information @kalexand-rh. I got it.

**Comment by kalexand-rh** [comment]
Happy to help, @bysnupy. If you have time and inclination, will you update your PR to fix this parameter, too?

**Comment by bysnupy** [comment]
@kalexand-rh I've also opened PR for this issue: https://github.com/openshift/openshift-docs/pull/12472

**Comment by bysnupy** [comment]
I close this issue, because it’s cleared.
