### ISSUE TITLE
OpenShift 4.1 Release Notes Tracker

### ISSUE THREAD

**Issue by deads2k** [openshift/openshift-docs#12487]

**Comment by deads2k** [comment]
SecurityContextConstraints only exist in the security.openshift.io group.

**Comment by kalexand-rh** [comment]
Pods have to change the CA cert bundle differently: https://github.com/openshift/openshift-docs/pull/12563

**Comment by mrogers950** [comment]
@kalexand-rh A note for #12563: 
The service-serving cert CA bundle is no longer mounted automatically in pods with service account tokens. Pods must now obtain the CA bundle from a configMap annotated with "service.alpha.openshift.io/inject-cabundle=true"

**Comment by deads2k** [comment]
> @kalexand-rh A note for #12563:
> The service-serving cert CA bundle is no longer mounted automatically in pods with service account tokens. Pods must now obtain the CA bundle from a configMap annotated with "service.alpha.openshift.io/inject-cabundle=true"

@smarterclayton did you approve an immediate break with no release overlap?

**Comment by smarterclayton** [comment]
No.  We can’t regress this.  Can we explain more why this was considered?  The default answer would be that we cannot break this.

**Comment by deads2k** [comment]
> > @kalexand-rh A note for #12563:
> > The service-serving cert CA bundle is no longer mounted automatically in pods with service account tokens. Pods must now obtain the CA bundle from a configMap annotated with "service.alpha.openshift.io/inject-cabundle=true"
> 
> @smarterclayton did you approve an immediate break with no release overlap?

@mrogers950 @ericavonb We need to provide the old and the new CA injection techniques together for at lease one release.  We need consumers (like the build pods) to use the new so they can cleanly upgrade, but we cannot break existing consumers instantly or no one will be able to upgrade.  They need to have the new available so they can upgrade the control plane to get the new technique and then upgrade their code.

**Comment by deads2k** [comment]
> No. We can’t regress this. Can we explain more why this was considered? The default answer would be that we cannot break this.

During a switch to beta, this should break because of the non-standard injection into a token that is being changed/removed upstream.  I'd like to see that in a 4.1 after the alternative exists long enough for a transition.

**Comment by ariordan-redhat** [comment]
https://jira.coreos.com/browse/OSDOCS-178
Comment from SDN team for 4.0:

We do install multus, but anything that actually utilizes it will be tech preview
So we should document that multus is available, and point to the tech preview documentation for how to install the additional networks on top of multus.
We should also document how to disable multus, in case people want it gone for whatever reason.

**Comment by bergerhoffer** [comment]
Deprecation notice to add:

The OpenShift Service Broker and Service Catalog is being replaced over the course of several future OpenShift 4 releases.  Red Hat will be deprecating the template service broker and ansible service brokers once we have ported important dependent content to new Operator driven solutions.  Users should be aware that equivalent and better functionality is present in the Operator Framework and Operator Life Cycle Manager (OLM).  Please use this notice to begin researching how you can advantage your service by leveraging these new technologies now available in OpenShift 4.

**Comment by huffmanca** [comment]
https://jira.coreos.com/browse/AUTH-184
This issue needs to be included in the release notes, as several of the `oc adm` commands have been deprecated. The new certificate details are being tracked under OSDOCS-315.

**Comment by vikram-redhat** [comment]
Known issue: https://bugzilla.redhat.com/show_bug.cgi?id=1668721

**Comment by bergerhoffer** [comment]
@ahardin-rh @sheriff-rh Here's a new section for the change in behavior for the service catalog:

The service catalog is not installed by default in OpenShift Container Platform 4.0. You must install it if you plan on using any of the services from the OpenShift Ansible broker or template service broker. In OpenShift Container Platform 4.0, the service catalog API server is installed into the `openshift-service-catalog-apiserver` namespace and the service catalog controller manager is installed into the `openshift-service-catalog-controller-manager` namespace. In OpenShift Container Platform 3.11, both of these components were installed into the `kube-service-catalog` namespace.

**Comment by bergerhoffer** [comment]
@ahardin-rh @sheriff-rh Can you also make updates to the existing service catalog/brokers deprecation notice in the release notes?

Use the changes suggested in this[ Google doc](https://docs.google.com/document/d/1GyO8czfKan598rJ3uHVuS4vjiMmFnJcb12M8xamH5G0/edit?ts=5c896ef5) under "Deprecation notice".

The paragraph above it might eventually get rolled in, but we're still working it out.

**Comment by yufchang** [comment]
@ahardin-rh @sheriff-rh hi, will UHC（https://cloud.openshift.com） part be added in release notes in the future? don't see this part. Thanks.

**Comment by sichvoge** [comment]
For the "Cluster Monitoring" section, I am missing the following two new features:

1. new Alerting UI natively integrated into the OpenShift console. You can now view cluster-level alerts and alerting rules from a single place, as well as configure silences.
2. Telemeter to collect anonymized cluster-related metrics to proactively help customers with their OpenShift clusters. 

For telemeter, we try to achieve the following additional use cases:
* Gather crucial (health) metrics of OpenShift installation
* Enable viable feedback loop of OpenShift upgrades
* Enable metering

**Comment by jboxman** [comment]
@ahardin-rh @sheriff-rh -- Not sure if this is the proper channel for this, but with regard to _Networking_, I think it makes sense to mention the _Network Operator_ somewhere. @pecameron said:

> network operator is new in 4.1, 3.11 uses ansible playbooks. 
In addition to installing, the network operator does upgrades and monitors networking.

I'm not sure if it also needs a mention under _OperatorHub_, possibly as _Network management_ or similar.

**Comment by yapei** [comment]
@ahardin-rh  @sheriff-rh  I have no idea about  

> Now with Operators, you can pick and choose what functionality you want to enable, allowing the user to customize the interface.
AFAIK, we only support `logoutURL` and `brand & documentationBaseURL`, can we say `you can pick and choose what functionality you want to enable` ?

**Comment by michaelgugino** [comment]
I put both of these at 'medium' as they may impact users and have negative effects, but would not prevent normal cluster operations.

This one may need further consideration for a higher level: https://bugzilla.redhat.com/show_bug.cgi?id=1712056

https://bugzilla.redhat.com/show_bug.cgi?id=1712068

**Comment by adambkaplan** [comment]
Builds with shell substitution for env vars may fail.

https://bugzilla.redhat.com/show_bug.cgi?id=1712245
Docs PR is up: #14977

**Comment by weinliu** [comment]
Autoscaling for Memory Utilization is not working https://bugzilla.redhat.com/show_bug.cgi?id=1707785 , shall we list it as known issue?

**Comment by michaelgugino** [comment]
@ahardin-rh https://bugzilla.redhat.com/show_bug.cgi?id=1712056 no longer applies, further testing revealed it's not a bug.

**Comment by michaelgugino** [comment]
This is an issue, confirmed today: https://bugzilla.redhat.com/show_bug.cgi?id=1713061

When deleting a machine-object (either directly or by scaling down the owning machine-set), if the associated node has already been deleted somehow (possibly by a cluster admin), the machine-controller will fail to successfully delete the backing cloud instance, and the machine-object will be stuck in 'deleting' status.

**Comment by kalexand-rh** [comment]
It looks like @ahardin-rh incorporated all of the issues that were raised here, so I'm going to close this issue. Thanks everyone!
