### ISSUE TITLE
Broken link to 3.10 release notes in "In-place Cluster Upgrades"

### ISSUE THREAD

**Issue by dharmit** [openshift/openshift-docs#12486]
### Which section(s) is the issue in?

Performing Automated In-place Cluster Upgrades

### What needs fixing?

Link to OKD 3.10 release notes in [About this Upgrade](https://docs.okd.io/3.10/upgrading/automated_upgrades.html#about-this-upgrade) section. [Link in question](https://docs.okd.io/3.10/release_notes/ocp_3_10_release_notes.html#ocp-310-notable-technical-changes) throws a 404.

**Comment by ig0rsky** [comment]
This is still an issue in 3.11 OKD. 
What is the correct procedure to upgrade the cluster to the latest z version for OKD?
