### ISSUE TITLE
fix sfc dp link

### ISSUE THREAD

**Issue by jeremyeder** [openshift/openshift-docs#12512]
### Which section(s) is the issue in?
https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html/developer_guide/using-device-plugins

### What needs fixing?
Please update the solarflare device plugin URL to point to here
https://github.com/solarflarecommunications/sfc-k8s-device-plugin

**Comment by ahardin-rh** [comment]
Resolved in https://github.com/openshift/openshift-docs/pull/20292
