### ISSUE TITLE
Openshift documentation should define targeted audience clearly in welcome page

### ISSUE THREAD

**Issue by xiazhao2015** [openshift/openshift-docs#1254]
Description of problem:
Openshift documentation should define targeted audience clearly, e.g. "This document assumes you already have professional understanding on kubernetes architect/docker  container networking merchanism, etc", since in order for understanding the concepts of openshift, is it necessary for reader to have enough background knowledge of some 3rd products such as docker/kubenetes, etc.

Version-Release number of selected component (if applicable):
Document URL: https://docs.openshift.org/latest/welcome/index.html

How reproducible:
always

Steps to Reproduce:
1. Open document URL: https://docs.openshift.org/latest/welcome/index.html

Actual results:
Openshift documentation currently talked zero about targeted audience in welcome page, but in order for understanding a lot of topics, is it necessary for reader to be familiar with some 3rd products such as docker/kubenetes, etc.

Expected results:
Openshift documentation should define targeted audience clearly in welcome page, e.g. This document assumes you already have background knowledge of kubernetes architect/docker conainer networking merchanism, etc

**Comment by vikram-redhat** [comment]
@xiazhao2015 - I am not sure if we can assume such knowledge from the readers. This is covered, in a way, by the architecture guide: https://docs.openshift.org/latest/architecture/index.html. I am going to close this issue, but please reopen if you feel otherwise.
