### ISSUE TITLE
Describe pod autoscaling requirements

### ISSUE THREAD

**Issue by tomason** [openshift/openshift-docs#1263]
Please, include the details of pod autoscaling requirements for deploymentConfig. There needs to be a definition of required cpu, otherwise the autoscaler complains.

Error message in 'oc get events':
FailedComputeReplicas   {horizontal-pod-autoscaler }                           failed to get cpu utilization: failed to get CPU consumption and request: some pods do not have request for cpu

Correct deploymentConfig (omitted most parts):
apiVersion: v1
kind: DeploymentConfig
spec:
  template:
    spec:
      containers:
      - name: container
        resources:
          requests:
            cpu: 500m

Could you please also update the enterprise docs. The autoscaling feature is tech-preview, but it should be documented in case someone wants to try it.

**Comment by mburke5678** [comment]
@tomason Is this still an issue? If so, do you have any guidance on required CPU? 
This is what we have in 3.1 and similar in 3.5:
https://docs.openshift.com/enterprise/3.1/dev_guide/pod_autoscaling.html

**Comment by vikram-redhat** [comment]
No answer was received on this, so closing this issue. Parts of it were also fixed via #1324.
