### ISSUE TITLE
[enterprise-3.11] Edit suggested in file install_config/configuring_vsphere.adoc

### ISSUE THREAD

**Issue by ckulacoglu** [openshift/openshift-docs#12634]
### Which section(s) is the issue in?

APPLYING CONFIGURATION CHANGES
https://docs.openshift.com/container-platform/3.11/install_config/configuring_vsphere.html#vsphere-applying-configuration-changes

### What needs fixing?
Instead of the actual content, the following error is in the section:

Unresolved directive in install_config/topics/manually_configuring_for_vsphere.adoc - include::install_config/topics/applying_configuration_changes.adoc[leveloffset=+2]

**Comment by mburke5678** [comment]
Fixed
