### ISSUE TITLE
Add a blurb on how to test in the Getting Started for Administrators guide

### ISSUE THREAD

**Issue by tkramer-conversant** [openshift/openshift-docs#1265]
I have had two developers trying to do a quick install of OpenShift and they pointed out something that stuck them both.

in:
https://docs.openshift.org/latest/getting_started/administrators.html#running-in-a-docker-container

Under Method 1 it states:

◦starts OpenShift listening on all interfaces (0.0.0.0:8443),

◦starts the web console listening on all interfaces at /console (0.0.0.0:8443),

I think a good third step would be to say to test the console connection.  When they did that they only tried http and it needs https.  I seen the blurb at the bottom but it would make it much clearer to have it in the same set of bullet points.  So a third line that says:
- test the console   -   https://<server>:8443/console

Would make it much clearer.

**Comment by tkramer-conversant** [comment]
or even after the list of bullets since it's not running that.

**Comment by mburke5678** [comment]
@tkramer-conversant 
The current Origin docs contain the following:
_"OpenShift Origin includes a web console which helps you visualize your applications and perform common creation and management actions. You can use the test user we created above to log in to the console via https://<server>:8443/console."_
Does this address your concern?

**Comment by vikram-redhat** [comment]
Based on @mburke5678 response, I am closing this issue.
