### ISSUE TITLE
broken url

### ISSUE THREAD

**Issue by dstockdreher** [openshift/openshift-docs#12680]
### Which section(s) is the issue in?

https://github.com/openshift/openshift-docs/blob/e661f3918334d7824dcbc3f6b33e0ca7c38c3ca9/install_config/monitoring/configuring-openshift-cluster-monitoring.adoc

### What needs fixing?

the inventory_url  goes to a 404

**Comment by dstockdreher** [comment]
inventory file hyperlink rather.

**Comment by vikram-redhat** [comment]
@dstockdreher - Hi there - the url in the final rendered docs is correct: https://docs.openshift.com/container-platform/3.11/install_config/prometheus_cluster_monitoring.html#configuring-openshift-cluster-monitoring
