### ISSUE TITLE
How to add a openshift node manually

### ISSUE THREAD

**Issue by jkroepke** [openshift/openshift-docs#1269]
Hi,

I have a foreman and a pxe kickstart environment. I want to deploy node without rerunning ansible. Ansible will restart some master service, even no changes are there. I think it is not required for adding new nodes.

I need to know which packages must be installed on a node, which command must be executed on the master (oadm create-node-config ...).

For example
- Generate client config on master
- Install this packages on node,
- Place the config form there into the directory.

**Comment by jkroepke** [comment]
Hi!

I found this: https://access.redhat.com/solutions/1983683

Maybe someone can add it to the documenation.

**Comment by mburke5678** [comment]
We have a section on adding nodes, starting in 3.2. The issue reporter appears to no longer be at RH. Closing this issue.
https://docs.openshift.com/container-platform/3.5/install_config/adding_hosts_to_existing_cluster.html#adding-nodes-or-reinstalling-quick
