### ISSUE TITLE
[enterprise-3.3] Edit suggested in file install_config/install/stand_alone_registry.adoc

### ISSUE THREAD

**Issue by schafezp** [openshift/openshift-docs#12758]
### Which section(s) is the issue in?
About OpenShift Container Registry

### What needs fixing?
The link to Atomic Registry, http://www.projectatomic.io/registry , 404s
It could be changed to an archive link or docs introduction
http://www.projectatomic.io/docs/introduction/

**Comment by bysnupy** [comment]
Personally I think only your information would be hard to find where the section is located in. 
So if you can provide more details such as section url and related phrases, it would be more helpful for checking.

**Comment by schafezp** [comment]
https://docs.openshift.com/container-platform/3.3/install_config/install/stand_alone_registry.html

This is the website page with the broken link.

The broken link is in the "About OpenShift Container Registry" section, directly below the second paragraph in the info section next to the blue "I".

The text reads as follows:
"OCR should not be confused with the upstream project Atomic Registry, which is a different implementation using a non-Kubernetes deployment method that leverages systemd and local configuration files to manage services."

In this paragraph "Atomic Registry" is a link to a 404 website.

Does this answer your questions?

**Comment by bysnupy** [comment]
Yes, it does. Thank you for your information.

FYI, I found this article - [Update: Removed links to Atomic Registry as discontinued.](https://www.projectatomic.io/blog/2017/05/oo-standalone-registry/)
