### ISSUE TITLE
Space befora commas

### ISSUE THREAD

**Issue by rludva** [openshift/openshift-docs#12762]
### Which section(s) is the issue in?
Developer Guide, Chapter 5. Projects:
_If allowed by your cluster administrator , you can create a new project using the CLI or the web console._
Space before the comma.

```
== Creating a Project

ifdef::openshift-enterprise,openshift-origin[]
xref:../admin_guide/managing_projects.adoc#selfprovisioning-projects[If allowed] by your cluster administrator
endif::[]
ifdef::openshift-dedicated,openshift-online[]
If allowed
endif::[]
, you can create a new project using xref:../cli_reference/index.adoc#cli-reference-index[the CLI] or the xref:../architecture/infrastructure_components/web_console.adoc#architecture-infrastructure-components-web-console[web console].
```

### What needs fixing?
The space before comma should not be.

**Comment by bergerhoffer** [comment]
PR to fix extra space: https://github.com/openshift/openshift-docs/pull/20382

**Comment by bergerhoffer** [comment]
Closing, fix is live: https://docs.openshift.com/container-platform/3.11/dev_guide/projects.html#create-a-project
