### ISSUE TITLE
[enterprise-3.11] Edit suggested in file install_config/master_node_configuration.adoc

### ISSUE THREAD

**Issue by briantward** [openshift/openshift-docs#12824]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/3.11/install_config/master_node_configuration.html#master-config-image-policy-config

### What needs fixing?

Image Policy Config can now take this variable: "additionalTrustedCA"
This was required for a bugfix: https://bugzilla.redhat.com/show_bug.cgi?id=1592936
Comment #40, 41, 45

This was needed to do a valid import-image from registry.redhat.io

**Comment by mburke5678** [comment]
@bparees We are going through older issues. 
Does `AdditionalTrustedCA` = `additionalTrustedCA`? 

We have this note in the docs. Does it cover this concern here?

> You can also point the registry import controller to another filesystem path for certificates
> by setting the `AdditionalTrustedCA` parameter in the `Image Policy Configuration` section of the master configuration file.

**Comment by bparees** [comment]
yes.  in the yaml it will be `additionalTrustedCA`
