### ISSUE TITLE
[enterprise-3.11] Edit suggested in file install_config/certificate_customization.adoc

### ISSUE THREAD

**Issue by daleking** [openshift/openshift-docs#12869]
### Which section(s) is the issue in?

Configuring Custom Certificates During Installation

### What needs fixing?

The example is missing a closing brace near the end of the line:

openshift_master_named_certificates=[{"names": ["master.148.251.233.173.nip.io"], "certfile": "/home/cloud-user/master-bundle.cert.pem", "keyfile": "/home/cloud-user/master.148.251.233.173.nip.io.key.pem" ]

Should be:

openshift_master_named_certificates=[{"names": ["master.148.251.233.173.nip.io"], "certfile": "/home/cloud-user/master-bundle.cert.pem", "keyfile": "/home/cloud-user/master.148.251.233.173.nip.io.key.pem"}]

This needs to to changed for previous versions of the document as well

**Comment by bergerhoffer** [comment]
PR submitted to add the missing brace: https://github.com/openshift/openshift-docs/pull/20389

**Comment by bergerhoffer** [comment]
Closing, update is live: https://docs.openshift.com/container-platform/3.11/install_config/certificate_customization.html#ansible-configuring-custom-certificates
