### ISSUE TITLE
Document variable expansion in configuration files and commands

### ISSUE THREAD

**Issue by Miciah** [openshift/openshift-docs#1287]
[install_config/install/docker_registry.adoc](https://github.com/openshift/openshift-docs/blob/master/install_config/install/docker_registry.adoc) and [install_config/master_node_configuration.adoc](https://github.com/openshift/openshift-docs/blob/master/install_config/master_node_configuration.adoc) use the `${version}` and `${component}` strings in configuration files and command flag values, but I do not see where in the documentation we specify variable interpolation for configuration files or command flag values  or define the values that will be interpolated for these strings.

Ideally, we should do the following:
1. Specify the `${varname}` syntax used for variable interpolation in some configuration file fields and command flag values.
2. Define what the values of specific variables are (or point to where these values are defined).

We do define the values of `${url}` and `${query}` where they are used in a configuration file in [install_config/configuring_authentication.adoc](https://github.com/openshift/openshift-docs/blob/master/install_config/configuring_authentication.adoc), although we still do not formally specify interpolation.

**Comment by mburke5678** [comment]
@Miciah We are going through old issues. 
I assume this is still a concern of yours? It appears that the command example we use is the same in 3.5 and 3.0, with no information around the {version} and {component} variables. 
I am not clear on what you are asking regarding "variable interpolation"? 
Should we at least put examples?

**Comment by vikram-redhat** [comment]
This comes via AsciiBinder's configuration files. Closing this.
