### ISSUE TITLE
Okd.io website - Getting started link is 404

### ISSUE THREAD

**Issue by raesene** [openshift/openshift-docs#12888]
### Which section(s) is the issue in?

The [okd.io](https://okd.io) website

### What needs fixing?

On the okd website, the "Getting Started" link goes to https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md which appears to be 404.  From the commit history on the directory, looks like a commit 2 days ago deleted the file https://github.com/openshift/origin/commit/f1206f2e637b4cc958fc7ef7dfca0015f43deb58

**Comment by mburke5678** [comment]
Thank you for pointing this out. At this time the Getting Started link works.
In the future, the OKD docs team does not control the okd.io website. Perhaps file a bug with the website team if you see errors. 
https://bugzilla.redhat.com/describecomponents.cgi?product=OKD
