### ISSUE TITLE
Improve consistency in terminology for the image registry

### ISSUE THREAD

**Issue by Miciah** [openshift/openshift-docs#1288]
We refer to the Docker registry and the image registry in many ways:

```console
% grep -hoie '\(\(docker\|image\|integrated\|internal\|openshift\)\(''s\)\? \)\+registry' **/*.adoc | sort | uniq -c | sort -n
      1 Docker image registry
      1 docker registry
      1 Image registry
      1 integrated OpenShift Docker Registry
      1 Integrated OpenShift Registry
      1 Integrated Registry
      1 OpenShift's integrated Docker Registry
      1 OpenShift's integrated registry
      2 Image Registry
      2 integrated OpenShift registry
      2 integrated registry
      2 OpenShift's integrated Docker registry
      5 OpenShift Docker registry
      6 Docker Registry
      6 internal registry
      7 internal Docker registry
      8 integrated Docker registry
     25 Docker registry
```

The inconsistency in words and capitalisation is rather confusing.  One might wonder whether "Docker Registry" (as opposed to "Docker registry") refers to a specific registry, or whether the "OpenShift Docker Registry" is different from the "OpenShift Image Registry", whether there is such a thing as a non-OpenShift image registry (or "Image registry"), and so on.

I also find the term "integrated" confusing: I understand it means integrated into the product, but it could also imply integrated into the OpenShift master (as opposed to running as a distinct pod on a node).  The term "internal" is a little clearer (at least I interpret it to mean internal to the OpenShift cluster), but its inconsistent usage is confusing.

To the best of my understanding, the above phrases refer to two distinct concepts:

* A Docker registry, which provides functionality and interfaces for pushing and pulling images.

* An OpenShift image registry, which provides the same functionality and interfaces as a Docker registry, as well as OpenShift-specific functionality (such as triggering builds or deployments when images are pushed to it).

I propose we standardise the terminology for these two concepts and define whatever terminology is settled on somewhere, such as [contributing_to_docs/term_glossary.adoc](https://github.com/openshift/openshift-docs/blob/master/contributing_to_docs/term_glossary.adoc).

Additionally, if we do the above, it would be worth defining "private Docker registry" and standardising that terminology as well (currently, I see "private registry", "private Docker registry", and "private Docker Registry").

**Comment by tnguyen-rh** [comment]
[BZ created](https://bugzilla.redhat.com/show_bug.cgi?id=1288441); closing.
