### ISSUE TITLE
[enterprise-3.11] Edit suggested in file install_config/master_node_configuration.adoc

### ISSUE THREAD

**Issue by seawolf82** [openshift/openshift-docs#12915]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/3.11/install_config/master_node_configuration.html#master-node-config-advanced-audit

### What needs fixing?

In this section the policy file adv-audit.yaml must be place into /etc/origin/master and not in The policy file /etc/security/
Furthermore i've got created the log directory  into /etc/origin/master/audit. It's works!
Personally I consider useless the section regarding the invetory variable openshift_master_audit_config  in the advance audit more precisely:

openshift_master_audit_config={"enabled": true, "auditFilePath": "/var/log/oscp-audit/-oscp-audit.log", "maximumFileRetentionDays": 14, "maximumFileSizeMegabytes": 500, "maximumRetainedFiles": 5, "policyFile": "/etc/security/adv-audit.yaml", "logFormat":"json"}

because this variable when you create flash install assumes that the file adv-audit.yaml already exists on the machines

When you treatment Sample Audit Policy Configuration I suggest you this example:

apiVersion: audit.k8s.io/v1beta1
kind: Policy
rules:
  - level: Metadata
    userGroups: ["system:authenticated:oauth"]
    verbs: ["create", "delete"]
    resources:
      - group: "project.openshift.io"
        resources: ["projectrequests", "projects"]
    omitStages:
      - RequestReceived

that write a simple policy file to log when an authenticated user creates or deletes an OpenShift project.

Thank you
Andrea

**Comment by fabio79acn** [comment]
Hi @seawolf82 , could you please elaborate your statement 'In this section the policy file adv-audit.yaml must be place into /etc/origin/master and not in The policy file /etc/security/' ; what's wrong with the path /etc/security/ ? Many thanks in advance.

**Comment by seawolf82** [comment]
Hi, from Openshift release 3.10, control plane is into container and if you
place te audit file into /etc/security don't work!
The Openshift documentation 3.10 and 3.11 it must have changed.

Thank you
Andrea

Il giorno lun 10 dic 2018 alle ore 12:38 fabio79acn <
notifications@github.com> ha scritto:
