### ISSUE TITLE
"Unable to delete old node" when using openstack provider

### ISSUE THREAD

**Issue by brenton** [openshift/openshift-docs#1293]
We need to document the workaround @liggitt mentioned in https://github.com/openshift/origin/issues/6159#issuecomment-161731254 until the Kubernetes fix is available.

**Comment by sjwalter2** [comment]
Hi, the workaround (deleting node, restart node service, re-add node labels) appears to already be present in the AWS config docs: https://docs.openshift.com/enterprise/3.1/install_config/configuring_aws.html#aws-applying-configuration-changes
So it should not take much to do the same for configuring for OpenStack

**Comment by mburke5678** [comment]
@brenton @sjwalter2 Is this work-around still required?

**Comment by brenton** [comment]
My understanding from reading through a few related github PRs and https://bugzilla.redhat.com/show_bug.cgi?id=1297075 is that we have a work around in OpenShift that should handle this situation for the openstack provider.  The cloud provider can use the "hostname" or the externalID and I would think that as long as the hostname of the VM matches one of these this probably should no longer happen.
