### ISSUE TITLE
Issues improvement ideas while following Log-Aggregation Documentation

### ISSUE THREAD

**Issue by PatrickSteiner** [openshift/openshift-docs#1294]
Following findings relate to: https://github.com/openshift/openshift-docs/blob/master/install_config/aggregate_logging.adoc

Finding 1)
After creation of the project with

oadm new-project logging --node-selector 

there should be a comment that one needs to change into the project, as oadm new project doesn't do that.

Finding 2)
To be simular to the documentation for Metrics, there should be a comment that the secret could also be created with

oc secrets new logging-deployer nothing=/dev/null

Finding 3)
If the project for logging was created with a node-selector, then the scaling of the fluentd will fail, as the scheduler will try to deploy all fluentds on the same node.
It is therefor required to change the namespace of the project, e.g. with

oc edit namespace logging

and remove the entry for the node-selector, e.g.

openshift.io/node-selector: region=infra

Finding 4)
When adding Kibana entry to the master-config for the UI integration, the "View Archive" button is not under Browse, but on the same page as the logs for a pod. 
A screenshow showing this button would be very helpful.

**Comment by bfallonf** [comment]
@PatrickSteiner I can make a PR to fix these. 

Can I ask about Finding 2? Are you simply saying that there should be an example without the available files? I can't tell too much from your example above.

Thanks!

**Comment by PatrickSteiner** [comment]
@bfallonf thanks for picking this up.

If you take a look at how the same step is documented here: https://docs.openshift.com/enterprise/3.1/install_config/cluster_metrics.html#metrics-deployer-secrets
 the exact same paragraph can be copied over to this documentation.

**Comment by bfallonf** [comment]
@PatrickSteiner I don't have a problem adding this in, but I'm not sure of the advantage. I tried this out, and it seemingly created an empty secret, presumably for the reader to modify to their instance. Is that correct? Is so, this information might be more at home in the Secrets section of the Deployment Guide [1].

I also tried running this without the nothing=/dev/null option and it didn't complete. I'm wondering what the advantage of this is. Like, why do you have to run that as an option if you can just run it with no option, which I think would be ideal to create the same thing. This may be a question for the engineering team, though.

[1] https://docs.openshift.com/enterprise/3.1/dev_guide/secrets.html

**Comment by PatrickSteiner** [comment]
@bfallonf I'm not that experienced in the pros and cons of these two different approaches. I just feel like that the two documentations ( Metrics and Log Aggregation ) are consistent.

**Comment by bfallonf** [comment]
@PatrickSteiner Np. I sent an email to the openshift-sme list. Once I sort that info out I should be ok to finish this off. Thanks!

**Comment by donovanmuller** [comment]
Also see https://github.com/openshift/openshift-docs/issues/1404

**Comment by bfallonf** [comment]
@PatrickSteiner sorry for the delay on this, but the issues you've brought up above should be fixed in #1641 

Can I get an ack it's all there? Big thanks!
