### ISSUE TITLE
migration procedure from redhat/openshift-ovs-subnet to redhat/openshift-ovs-networkpolicy 3.10/3.11

### ISSUE THREAD

**Issue by megian** [openshift/openshift-docs#12947]
The migration procedure from redhat/openshift-ovs-subnet to redhat/openshift-ovs-networkpolicy is not working as described in the documentation.

### Which section(s) is the issue in?

https://docs.okd.io/3.11/install_config/configuring_sdn.html#migrating-between-sdn-plugins

### What needs fixing?

Step 2 is asking for restarting master and nodes. This makes sense so far. But step 3 does stop the etcd cluster, kubernetes master controllers and api. So step 4 has no working Master API and does fail.

I don't see any reason for step 3, as the master controller and api already has been restarted and etcd is not affected by changing the network plugin.

Additional steps are required: To change the network policy in the node group config map. Otherwise the sync pod does reset the configuration to the old network plugin. This causes a cluster outage afterwards.

Manually for each node config configmap:
`oc get configmap node-config-compute -n openshift-node`

```
data:
  node-config.yaml: |
    networkConfig:
      networkPluginName: redhat/openshift-ovs-networkpolicy
```

Or execute:

```
# ansible-playbook -i </path/to/inventory/file> \
    ~/openshift-ansible/playbooks/openshift-master/openshift_node_group.yml
```

**Comment by afcollins** [comment]
+1
Step 4 fails since api server has been stopped in step 3.

The wording of step 3 is inconsistent with the action.  'Stopping node service' in 3.10/3.11 would be `systemctl stop atomic-openshift-node`.  The master services are static pods in that directory.
