### ISSUE TITLE
[enterprise-3.10] Edit suggested in file rest_api/index.adoc

### ISSUE THREAD

**Issue by gVien** [openshift/openshift-docs#12999]
### Which section(s) is the issue in?
Under Service Token Accounts section, step 2

### What needs fixing?
Typo in `serviceaccounts` as there is no "s". 
`oc policy add-role-to-user admin system:serviceaccounts:test:robot`
should be
`oc policy add-role-to-user admin system:serviceaccount:test:robot` (no s in serviceaccount)

It would throw a 403 error when attempting to use the token created from the user 'system:serviceaccounts:test:robot' (with s)

https://docs.openshift.com/container-platform/3.10/rest_api/index.html#rest-api-serviceaccount-tokens

**Comment by chrisbsmith** [comment]
This error exists in the documentation for 3.11 as well.

**Comment by jboxman** [comment]
@gVien, thanks for reporting this! I've fixed it in all affected versions.
