### ISSUE TITLE
redeploy certificates playbook missing from okd 3.11 docs

### ISSUE THREAD

**Issue by brianUK007** [openshift/openshift-docs#12997]
### Which section(s) is the issue in?

if you search for certificate in 3.11 you get no results found. in 3.10 okd returns:

Configuring Custom Certificates | Configuring Clusters | OKD 3.10
Configuring Custom Certificates Overview Administrators...configure custom serving certificates for the public host...Configuring Custom Certificates During Installation...installations, custom certificates can be configured using...openshift_master_named_certificates and openshift_mast

Redeploying Certificates | Configuring Clusters | OKD 3.10
Redeploying Certificates Overview OKD uses certificates to provide...expiration dates for cluster certificates. Playbooks are also...and redeploying these certificates, which can fix common...common certificate errors. Possible use cases for redeploying...redeploying certificates include: Checking Certificate Expirations

Managing Certificates | Day Two Operations Guide | OKD 3.10
Toggle nav Managing certificates Over the lifetime of...of a OKD cluster, certificates will enter various phases...self-signed certificate to CA-signed certificate Some application...create a self-signed certificate that is then directly...self-signed certificates. These self-signed certificates are

Authentication | Developer Guide | OKD 3.10
[-n=<project>] \ [--certificate-authority=</path/to/file...as a given user. --certificate-authority $ oc login...login --certificate-authority=<path/to/file.crt> Correctly...HTTPS. The path to a certificate authority file must...bypassing the server certificate checks; however, note

Pruning objects | Cluster Administration | OKD 3.10
pass --all=false . --certificate-authority The path to...to a certificate authority file to use when communicating...registries. Defaults to the certificate authority data from...has an invalid HTTPS certificate. See Using Secure or...protocol with a mandatory certificate verification. The prune

Routes | Developer Guide | OKD 3.10
encrypted with a key and certificate (PEM-format files which...optionally provide certificates and a key. TLS is the...KEY----- certificate : |- -----BEGIN CERTIFICATE----- [...[...] -----END CERTIFICATE----- caCertificate : |-...-----BEGIN CERTIFICATE----- [...] -----END CERTIFICATE-----

Custom Admission Controllers - Additional Concepts | Architecture | OKD 3.10
Generate a CA certificate and use the certificate to sign...sign the server certificate used by your webhook server...The PEM-formatted CA certificate is supplied to the admission...as Service Serving Certificate Secrets . The following...8 A PEM-encoded CA certificate that signs the server

Docker tasks | Day Two Operations Guide | OKD 3.10
node Managing Docker certificates An OKD internal registry...interprets .crt files as CA certificates and .cert files as...as client certificates. Any CA extensions must be .crt...Installing a certificate authority certificate for external...registry certificate authority (CA) certificate must be

Routes - Networking | Architecture | OKD 3.10
Description DEFAULT_CERTIFICATE The contents of a default...default certificate to use for routes that don’t expose...PEM format. DEFAULT_CERTIFICATE_DIR A path to a directory...used as the default certificate. Only used if DEFAULT_CERTIFICATE...DEFAULT_CERTIFICATE or DEFAULT_CERTIFICATE_PATH are not

Secrets | Developer Guide | OKD 3.10
build. Service Serving Certificate Secrets Service serving...serving certificate secrets are intended to support complex...need out-of-the-box certificates. It has the same settings...settings as the server certificates generated by the administrator...generate a signed serving certificate/key pair into a secret

### What needs fixing?
redeploy certificates is still part of openshift okd, unless this in a mistake there should be some documentation to go along with it. I've seen several other areas like this, I'll keep posting them as I find them, let me know if this is a larger issue with 3.11 docs.

https://github.com/openshift/openshift-ansible/blob/master/playbooks/redeploy-certificates.yml

**Comment by bergerhoffer** [comment]
Closing as this no longer seems to be an issue. The _Redeploying Certificates_ section is available in the 3.11 OKD docs here: https://docs.okd.io/3.11/install_config/redeploying_certificates.html
