### ISSUE TITLE
[enterprise-3.11] Edit suggested in file install/host_preparation.adoc

### ISSUE THREAD

**Issue by amelie1979** [openshift/openshift-docs#13012]
### Which section(s) is the issue in?

Operating system requirements

### What needs fixing?
Original Statement
Master and node hosts must use a base installation of Red Hat Enterprise Linux (RHEL) 7.4 or 7.5 with the latest packages from the Extras channel or RHEL Atomic Host 7.4.2 or later.

The version must include 7.6
use a base installation of Red Hat Enterprise Linux (RHEL) from 7.4 up to 7.6

**Comment by kalexand-rh** [comment]
@jianlinliu, can you confirm this change for me?

**Comment by jianlinliu** [comment]
Yeah, 7.6 should be included, but according to my understanding, correspondingly the old version 7.4 should be removed. @wsun1 help double confirm here.

**Comment by wsun1** [comment]
Yes,we only support the latest two versions

**Comment by kalexand-rh** [comment]
@wsun1, @jianlinliu, while I'm updating versions, which version of Atomic Host are we supporting for 3.11?

**Comment by amelie1979** [comment]
I'm not sure about that, I have client who have deployed OCP 3.11 on RHEL
7.4.  There is a matrix of support saying otherwise. We need to aling
support Matrix and docs.
