### ISSUE TITLE
[enterprise-3.11] Edit suggested in file admin_guide/overcommit.adoc

### ISSUE THREAD

**Issue by DanielFroehlich** [openshift/openshift-docs#13036]
### Which section(s) is the issue in?
Tune Buffer Chunk Limit

### What needs fixing?
I think it does not belong into this chapter/topic at all. It's has nothing todo with overcommitment. It belongs to the Logging Chapter somerhere. To me, it looks like a cut'copy'paste mistake that it is in this chapter.

**Comment by mburke5678** [comment]
@DanielFroehlich Thanks for pointing this out. I think you are correct. All signs point to this material going into the Logging docs. However, I talked to the writer who added this to Overcommitting. She recalled that someone asked that the material go there, but couldn't recall the specifics. What if we leave the topic in both places to be safe:

3.11 https://github.com/openshift/openshift-docs/pull/20030
4.x https://github.com/openshift/openshift-docs/issues/13036

4.x preview of logging topic: https://issue-13036-4x--ocpdocs.netlify.com/openshift-enterprise/latest/logging/config/cluster-logging-collector.html#understandin-fluentd-buffering_cluster-logging-collector

**Comment by DanielFroehlich** [comment]
Looks good to me! Greetings from Germany Dan

Daniel Fröhlich - Senior Solution Architect - M: +49 176 10 24 84 33  - E:
daniel.froehlich@redhat.com
Red Hat GmbH, http://www.de.redhat.com/, Registered seat: Grasbrunn,
Commercial register: Amtsgericht Muenchen, HRB 153243,
Managing Directors: Charles Cachera, Laurie Krebs, Michael O'Neill, Thomas
Savage
