### ISSUE TITLE
[enterprise-3.11] Edit suggested in file admin_guide/scheduling/pod_affinity.adoc

### ISSUE THREAD

**Issue by phekmat** [openshift/openshift-docs#13052]
### Which section(s) is the issue in?
- Examples: Pod Anti-Affinity
- Examples: Pod Affinity with no Matching Labels

### What needs fixing?

The last bullet in each section needs to be switched, i.e. "The pod pod-s2 is not scheduled unless there is a node with a pod that has the security:s2 label. If there is no other pod with that label, the new pod remains in a pending state" should be under "Pod Affinity with no Matching Labels" and "The pod pod-s2 cannot be scheduled on the same node as pod-s1." should be under "Pod Anti-Affinity"

**Comment by mburke5678** [comment]
@phekmat Thank you for pointing this out and apologies for taking so long to respond. I fixed this issue previously in https://github.com/openshift/openshift-docs/pull/17120/files#diff-68b54a4a6c48e088a8f73fb3536ef9aeR321-R375
