### ISSUE TITLE
[enterprise-3.11] Edit suggested in file install/configuring_inventory_file.adoc

### ISSUE THREAD

**Issue by ddouglas9500** [openshift/openshift-docs#13069]
### Which section(s) is the issue in?
Configuring Cluster Logging

### What needs fixing?
The section doesn't mention that it is also required to set the node selector setting:
openshift_logging_es_nodeselector={"node-role.kubernetes.io/infra":"true"}

https://access.redhat.com/solutions/3654961

**Comment by mburke5678** [comment]
Thanks for pointing this out. Making changes in https://github.com/openshift/openshift-docs/pull/20052
