### ISSUE TITLE
[Enterprise 3.11] Wrong PV name in install_config/persistent_storage/persistent_storage_iscsi.html

### ISSUE THREAD

**Issue by tsmetana** [openshift/openshift-docs#13065]
### Which section(s) is the issue in?
install_config/persistent_storage/persistent_storage_iscsi.html

### What needs fixing?
The "iSCSI Multipathing" and "iSCSI Custom Initiator IQN" both use iscsi_pv as the example iSCSI PersistentVolume name. The name must not contain the '_' character though:
```
[tsmetana@openlmi iscsi]$ oc create -f iscsi-pv.yaml 
The PersistentVolume "iscsi_pv" is invalid: metadata.name: Invalid value: "iscsi_pv": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```
The underscore chartacter should be replaced by '-' (dash).

**Comment by mburke5678** [comment]
@tsmetana Thank you for pointing this out. Making the change in https://github.com/openshift/openshift-docs/pull/20805
