### ISSUE TITLE
Link to Storage Class in 3.11 docs for Prometheus Cluster Monitoring throws 404

### ISSUE THREAD

**Issue by dharmit** [openshift/openshift-docs#13075]
### Which section(s) is the issue in?
[Configuring OKD cluster monitoring](https://docs.okd.io/3.11/install_config/prometheus_cluster_monitoring.html) in OKD 3.11 docs.

### What needs fixing?
Link used for "Storage Class" in description for `openshift_cluster_monitoring_operator_prometheus_storage_class_name` and `openshift_cluster_monitoring_operator_alertmanager_storage_class_name` is incorrect.

Correct link seems to be https://docs.okd.io/latest/install_config/persistent_storage/dynamically_provisioning_pvs.html#defining-storage-classes

**Comment by mburke5678** [comment]
Fixed. Links removed.
