### ISSUE TITLE
Broken link to "dedicated infrastructure:" on Example Inventory Files

### ISSUE THREAD

**Issue by vorburger** [openshift/openshift-docs#13092]
On https://docs.okd.io/latest/install/example_inventories.html there are (several) links to _"dedicated infrastructure"_ (e.g. on https://docs.okd.io/latest/install/example_inventories.html#single-master-multi-node-ai _"...and two nodes with the node-role.kubernetes.io/infra=true label for hosting **dedicated infrastructure**:"_ which link to https://docs.okd.io/latest/install/example_inventories.html#configuring-dedicated-infrastructure-nodes which is no longer there.

**Comment by vorburger** [comment]
Oh, looks like you moved that section from example_inventories.adoc to configuring_inventory_file.adoc at some point... https://github.com/openshift/openshift-docs/pull/13093 would fix this, if you want to merge that.

PS: You guys should run some link cross ref checker on all PRs to avoid breaking links... :smile: Do you want a new issue for that?

**Comment by kalexand-rh** [comment]
@vorburger, if you make a new issue to update the CI jobs, tag @vikram-redhat.
