### ISSUE TITLE
Review dev_guide/builds.adoc proposed edits

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/openshift-docs#1310]
In #1289, @tnguyen-rh spotted several existing problems in `dev_guide/builds.adoc`, this is a reminder to address them.

Refer to the comments in the PR.

**Comment by mburke5678** [comment]
@rhcarvalho The associated PR is merged. Closing this reminder PR.

**Comment by rhcarvalho** [comment]
The reference was to comments in the PR that were not addressed before merge... but this is so old, might have lost the relevance, it is fair to simply close it.
