### ISSUE TITLE
[enterprise-3.9] Edit suggested in file admin_guide/out_of_resource_handling.adoc

### ISSUE THREAD

**Issue by jiajunng** [openshift/openshift-docs#13110]
### Which section(s) is the issue in?
Understanding Eviction Thresholds
- UNDERSTANDING HARD EVICTION THRESHOLDS

### What needs fixing?
The values of hard eviction threshold in the example table, "**Sample Node Configuration file with hard eviction thresholds**" should be **percentage** instead of a numeric value. The numeric value is causing an inaccurate reading which creates a false alert that indicates that the node has a disk pressure.

**Comment by tech-mint** [comment]
eviction-pressure-transition-period="5m" this line is not working in the same docs
