### ISSUE TITLE
Why we are not merging upstream/master to master?

### ISSUE THREAD

**Issue by php-coder** [openshift/openshift-docs#1311]
I noticed that sections [Ensure your local repository is in sync with the remote](https://github.com/openshift/openshift-docs/blob/master/contributing_to_docs/create_or_edit_content.adoc#ensure-your-local-repository-is-in-sync-with-the-remote) and [Confirm your changes have been merged](https://github.com/openshift/openshift-docs/blob/master/contributing_to_docs/create_or_edit_content.adoc#confirm-your-changes-have-been-merged) have only 3 steps for syncing fork while I'm expecting 4.

```bash
$ git checkout master
$ git fetch upstream
$ git push origin master
```
The 3rd step currently looks useless because you didn't change the `master` branch! You need to execute `git merge upstream/master` to merge it to your local `master`.

See also guide from GitHub for doing the same: https://help.github.com/articles/syncing-a-fork/

**Comment by adellape** [comment]
Agree, it's missing a step. In our [Mojo doc](https://mojo.redhat.com/docs/DOC-1004281) on the same (see "Keeping your local repo in sync with the remote"), we have the 3rd step as `git rebase upstream/master`.

**Comment by php-coder** [comment]
BTW, also these 2 sections look duplicating each other.

**Comment by php-coder** [comment]
>In our Mojo doc on the same...

@adellape Steps in `Typical Writer Workflow` > `Develop` content are also incomplete.

**Comment by adellape** [comment]
@php-coder Fixing in https://github.com/openshift/openshift-docs/pull/1313.

> BTW, also these 2 sections look duplicating each other.

Are you referring to the 2 sections within `create_or_edit_content.adoc`? Or between the adoc and the Mojo doc.

**Comment by adellape** [comment]
I'll get the Mojo doc updated too.
