### ISSUE TITLE
[enterprise-3.11] Edit suggested in file install_config/persistent_storage/dynamically_provisioning_pvs.adoc

### ISSUE THREAD

**Issue by montknut** [openshift/openshift-docs#13159]
### Which section(s) is the issue in?

Available dynamically provisioned plug-ins

### What needs fixing?

Please add a Line to the table for HPE Nimble 

HPE Nimble Storage | hpe.com/nimble | Configuring HPE Nimble Kube Storage Controller | Dynamic provisioning of HPE Nimble Storage resources using the HPE Nimble Kube Storage Controller.

so it is the same as the OK.org table on this page:  https://docs.okd.io/latest/install_config/persistent_storage/dynamically_provisioning_pvs.html#available-dynamically-provisioned-plug-ins

This is causing customer complaints and HPE is loosing sales because of the mismatch.  

Thanks! 

Monte

**Comment by vikram-redhat** [comment]
AFAIK, Nimble is not actually supported and that is why it is only in the upstream docs.

@mpbarrett @tkatarki @sferich888 @aheslin - someone please let me know if this has changed otherwise I will close this request.

**Comment by sferich888** [comment]
It's not directly supported by Red Hat however HPE may have a partner arrangement with Red Hat and that could be driving the request.

**Comment by montknut** [comment]
They should be fully supported.

That's crazy if not.

They just updated their Cert as well.

Monte

------------------------------
*Monte Knutson*
Principal Engineering Partner Manager
Red Hat
Attn: Monte Knutson, MS 11s221
100 East Davie Street
Raleigh, NC 27601

email: mknutson@redhat.com
office: 919-890-8413
cell: 919-649-0603
