### ISSUE TITLE
[enterprise-3.7] Edit suggested in file admin_guide/sdn_troubleshooting.adoc

### ISSUE THREAD

**Issue by pradeepanchan** [openshift/openshift-docs#13197]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/3.7/admin_guide/sdn_troubleshooting.html#debugging-the-router

### What needs fixing?
This command in the above section has incorrect formatting: `oc get pods --all-namespaces --selector=router --template='{{range .items}}HostIP: {{.status.hostIP}}   PodIP: {{.status.podIP}}{{end}}{{"\n"}}'`

It should rather be: `oc get pods --all-namespaces --selector=router --template='{{range .items}}HostIP: {{.status.hostIP}}   PodIP: {{.status.podIP}}{{"\n"}}{{end}}'`

**Comment by pradeepanchan** [comment]
Any reason why it was closed without being addressed

**Comment by jboxman** [comment]
Hi @pradeepanchan,

Only version 3.11 from the OpenShift 3.x series is currently supported. Is this still an issue in that version of OpenShift?

Thanks.

**Comment by pradeepanchan** [comment]
Yes, the command is still incorrect. 
The location is at [https://docs.openshift.com/container-platform/3.11/admin_guide/sdn_troubleshooting.html#debugging-the-router](url)

The fix is still the same as what i suggested above.

I observed that the entire  _Cluster Administration_ section is missing in 4.x documents.
