### ISSUE TITLE
[enterprise-3.11] Edit suggested in file architecture/infrastructure_components/kubernetes_infrastructure.adoc

### ISSUE THREAD

**Issue by okkyhtf** [openshift/openshift-docs#13198]
### Which section(s) is the issue in?
Overview

### What needs fixing?
It was stated in the information mark that **"OpenShift Container Platform 3.11 uses Kubernetes 1.10 and Docker 1.13."** which is wrong, supposed to be **"OpenShift Container Platform 3.11 uses Kubernetes 1.11 and Docker 1.13."**

**Comment by jboxman** [comment]
@okkyhtf, thanks for reporting this! It's been fixed.
