### ISSUE TITLE
Deployment Resources: mention about "requests"

### ISSUE THREAD

**Issue by php-coder** [openshift/openshift-docs#1324]
In the [Deployment Resources](https://docs.openshift.org/latest/dev_guide/deployments.html#deployment-resources) I see the description about `limits` but there is no information about [`requests`](https://docs.openshift.org/latest/rest_api/openshift_v1.html#v1-resourcerequirements).

See also #1263 about improving example.

**Comment by mburke5678** [comment]
@php-coder There is information in the 3.1 docs (not sure when it was added) regarding `requests`, which is maintained in 3.5.
----
  type: "Recreate"
  resources:
    requests: (1)
      cpu: "100m"
      memory: "256Mi"
---
(1) The requests object contains the list of resources that correspond to the list of resources in the quota.
https://docs.openshift.com/enterprise/3.1/dev_guide/deployments.html#deployment-resources
https://docs.openshift.com/container-platform/3.5/dev_guide/deployments/basic_deployment_operations.html#deployment-resources
Does this address your concern?

**Comment by php-coder** [comment]
@mburke5678 Looks like, yes. Thank you!
