### ISSUE TITLE
[enterprise-3.11] Edit suggested in file admin_guide/manage_nodes.adoc

### ISSUE THREAD

**Issue by ken-zheng** [openshift/openshift-docs#13252]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/3.11/admin_guide/manage_nodes.html#adding-cluster-hosts_manage-nodes

### What needs fixing?

The following command is wrong.

`# oc label node/new-node.example.com logging-infra-fluentd: "true"

It should be:
`# oc label node/new-node.example.com logging-infra-fluentd="true"

**Comment by mburke5678** [comment]
@ken-zheng Thank you for pointing this out. This was fixed in https://github.com/openshift/openshift-docs/pull/14226/files#diff-085b7aade0f63887d05ca560ed7c8a27R141
