### ISSUE TITLE
Rolling Strategy: add information about updatePeriodSeconds and intervalSeconds

### ISSUE THREAD

**Issue by php-coder** [openshift/openshift-docs#1325]
The [Rolling Strategy](https://docs.openshift.org/latest/dev_guide/deployments.html#rolling-strategy) miss the description of `updatePeriodSeconds` and `intervalSeconds`.

See their description in API: https://docs.openshift.org/latest/rest_api/openshift_v1.html#v1-rollingdeploymentstrategyparams

**Comment by mburke5678** [comment]
@php-coder There is a reference to `updatePeriodSeconds` and `intervalSeconds` here:
https://docs.openshift.org/latest/dev_guide/integrating_external_services.html#step-2-consume-a-service

Should we also have this info in the Deployment Strategies doc?
https://docs.openshift.org/latest/dev_guide/deployments/deployment_strategies.html#rolling-strategy

**Comment by php-coder** [comment]
> There is a reference to updatePeriodSeconds and intervalSeconds here:
https://docs.openshift.org/latest/dev_guide/integrating_external_services.html#step-2-consume-a-service

This is just a reference without explanation and also it's located in the place where it's hard to find.

> Should we also have this info in the Deployment Strategies doc?

I believe that yes, they should be documented along with other Deployment fields.

**Comment by mburke5678** [comment]
Created a docs Bugzilla. Closing this issue.
https://bugzilla.redhat.com/show_bug.cgi?id=1461935
