### ISSUE TITLE
Provide a full list of possible icons of template

### ISSUE THREAD

**Issue by php-coder** [openshift/openshift-docs#1329]
In the [Templates overview](https://docs.openshift.org/latest/architecture/core_concepts/templates.html#overview) I see the following:

> The icon that will be shown in the UI for this template; the name of a CSS class defined in [the web console source](https://raw.githubusercontent.com/openshift/origin/master/pkg/assets/bindata.go) (search content for "openshift-logos-icon")

But I couldn't find a list of icons there :( Maybe we could provide this list explicitly?

As far I can see we can get this list by using the command:

``` shell
$ grep name assets/app/styles/fonts/openshift-logos-icon.json | grep -v openshift-logos-icon
                "name": "github"
                "name": "git"
                "name": "openjdk"
                "name": "rails"
                "name": "php"
                "name": "ruby"
                "name": "django"
                "name": "nodejs"
                "name": "jenkins"
                "name": "python"
                "name": "perl"
                "name": "zend"
                "name": "jboss"
                "name": "tomcat"
                "name": "spring"
                "name": "mysql-database"
                "name": "postgresql"
                "name": "mongodb"
                "name": "mariadb"
                "name": "wordpress"
                "name": "drupal"
                "name": "codeigniter"
                "name": "shadowman"
                "name": "stackoverflow"
                "name": "aerogear"
                "name": "capedwarf"
                "name": "redis"
                "name": "clojure"
                "name": "scala"
                "name": "grails"
                "name": "beaker"
                "name": "go-gopher",
                "name": "joomla"
                "name": "load-balancer"
                "name": "wildfly",
                "name": "play",
                "name": "laravel",
```

**Comment by jwforres** [comment]
@sg00dwin we've been getting this question a lot lately, I think ideally we would want to have something like what patternfly has in their docs https://www.patternfly.org/styles/icons/#_

**Comment by rdebeasi** [comment]
A basic icon list is available here: https://rawgit.com/openshift/openshift-logos-icon/master/demo.html

It'd be nice to have this in the official docs, but the information is at least out there! :)

**Comment by jwforres** [comment]
This is actually documented here https://docs.openshift.org/latest/dev_guide/templates.html#writing-description

See bullet 6
