### ISSUE TITLE
4.0: Rework Gluster storage documentation

### ISSUE THREAD

**Issue by jsafrane** [openshift/openshift-docs#13302]
### Which section(s) is the issue in?
https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html/configuring_clusters/configuring-persistent-storage#install-config-persistent-storage-persistent-storage-glusterfs

### What needs fixing?
Whole chapter needs update for 4.0. Server installation and configuration is not done by Ansible now and either corresponding sections need to be updated or removed.

Client configuration is AFAIK documented correctly. 

@humblec @jarrpa @obnoxxx

**Comment by mburke5678** [comment]
Gluster is not supported in 4.x
