### ISSUE TITLE
Node Group Definitions for CRI-O

### ISSUE THREAD

**Issue by Asgoret** [openshift/openshift-docs#13321]
Hi! There is no section in [Defining Node Groups and Host Mappings](https://docs.openshift.com/container-platform/3.11/install/configuring_inventory_file.html#configuring-inventory-defining-node-group-and-host-mappings) for nodes that use CRI-O as primary container runtime. So when you try to label your nodes install is failed.

**Comment by Asgoret** [comment]
Hi guys @gnufied @brenton @rphillips ! Can somebody help me?

**Comment by brenton** [comment]
perhaps @openshift/sig-containers or @openshift/sig-pod can provide guidance to clarify the expected behavior for node configuration with cri-o on 3.11.

**Comment by Asgoret** [comment]
> perhaps @openshift/sig-containers or @openshift/sig-pod can provide guidance to clarify the expected behavior for node configuration with cri-o on 3.11.

em.... this link is unavailable... or they are not public)
