### ISSUE TITLE
[enterprise-3.9] Edit suggested in file release_notes/ocp_3_9_release_notes.adoc

### ISSUE THREAD

**Issue by therevoman** [openshift/openshift-docs#13345]
### Which section(s) is the issue in?
Erratta 3.9.60

### What needs fixing?
Add a "Known issue" section with an entry for "regression error when running on OpenStack".  
the function normalize_openstack_facts pulled in a commit that broke how the inventory file file is parsed when hosted on OpenStack.  details in this bug: https://github.com/openshift/openshift-ansible/issues/10956

Summary: when using OpenStack without a floating IP for your cluster be aware you will see an error.
Workaround: manually patch the file `/usr/share/ansible/openshift-ansible/playbooks/init/cluster_facts.yml` with the attached patch.

[ocp-3_9_60-openstack.patch.txt](https://github.com/openshift/openshift-docs/files/2766919/ocp-3_9_60-openstack.patch.txt)

This is the error with the important part marked Bold.
```TASK [Gather Cluster facts] ***************************************************************************************************************************************************************************************************************************** task path: /usr/share/ansible/openshift-ansible/playbooks/init/cluster_facts.yml:9 Monday 14 January 2019 13:29:05 +0000 (0:00:00.096) 0:00:08.235 ******** An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'list' object has no attribute 'split' fatal: [cae-idev-np-alln-master-host-0.cisco.com]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n File \"/tmp/ansible_oAT2PW/ansible_module_openshift_facts.py\", line 1678, in <module>\n main()\n File \"/tmp/ansible_oAT2PW/ansible_module_openshift_facts.py\", line 1665, in main\n additive_facts_to_overwrite)\n File \"/tmp/ansible_oAT2PW/ansible_module_openshift_facts.py\", line 1331, in __init__\n additive_facts_to_overwrite)\n File \"/tmp/ansible_oAT2PW/ansible_module_openshift_facts.py\", line 1361, in generate_facts\n provider_facts = self.init_provider_facts()\n File \"/tmp/ansible_oAT2PW/ansible_module_openshift_facts.py\", line 1503, in init_provider_facts\nprovider_info.get('metadata')\n File \"/tmp/ansible_oAT2PW/ansible_module_openshift_facts.py\", line 375, in normalize_provider_facts\n facts = normalize_openstack_facts(metadata, facts)\n File \"/tmp/ansible_oAT2PW/ansible_module_openshift_facts.py\", line 340, in normalize_openstack_facts\n **if socket.gethostbyname(metadata['ec2_compat'][h_var]) == metadata['ec2_compat'][ip_var].split(',')[0]:\nAttributeError: 'list' object has no attribute 'split**'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}```

**Comment by ahardin-rh** [comment]
@therevoman Thank you for this! This is now addressed in https://github.com/openshift/openshift-docs/pull/13348
