### ISSUE TITLE
[enterprise-3.11] Edit suggested in file rest_api/examples.adoc

### ISSUE THREAD

**Issue by thecheryl** [openshift/openshift-docs#13373]
### Which section(s) is the issue in?

The block under "To try out the usage examples by copy/paste, first set all of the previously mentioned environment variables, for example:"

### What needs fixing?

I am trying to use the REST API in my OpenShift Online trial account which is running on api-starter-us-east-1-openshift-com. This command did not work for me:

```ENDPOINT=$(oc config current-context | cut -d/ -f2 | tr - .)```

Instead I used:

```ENDPOINT=$(oc config current-context | cut -d/ -f2) ```

**Comment by ahardin-rh** [comment]
@tiwillia Can you please provide a technical review of this proposed change or point us in the right direction? Thanks!
