### ISSUE TITLE
[enterprise-3.11] Edit suggested in file day_two_guide/environment_health_checks.adoc

### ISSUE THREAD

**Issue by sbarre-esit** [openshift/openshift-docs#13426]
### Which section(s) is the issue in?
Creating alerts using Prometheus

### What needs fixing?
Link to Prometheus docs actually links to Hawkular docs (https://docs.openshift.com/container-platform/3.11/install_config/cluster_metrics.html#openshift-prometheus). 

Probably should link to https://docs.openshift.com/container-platform/3.11/install_config/prometheus_cluster_monitoring.html

**Comment by mburke5678** [comment]
Fixed
