### ISSUE TITLE
[enterprise-3.11] Edit suggested in file install_config/persistent_storage/persistent_storage_glusterfs.adoc

### ISSUE THREAD

**Issue by hupiper** [openshift/openshift-docs#13444]
### Which section(s) is the issue in?
Using The Installer

### What needs fixing?
The link on this bullet is broken:
`This does not include OpenShift Logging or OpenShift Metrics, as that is currently still a separate step. See [converged mode for OpenShift Logging and Metrics](https://docs.openshift.com/container-platform/3.11/install_config/persistent_storage/install-example-infra) for more information.`

**Comment by mburke5678** [comment]
@hupiper Thanks for pointing this out. This was fixed in https://github.com/openshift/openshift-docs/pull/13998
