### ISSUE TITLE
Redeploying Certificates has the wrong info - i.e.: 30 days v.s. 365 days

### ISSUE THREAD

**Issue by oybed** [openshift/openshift-docs#13506]
### Which section(s) is the issue in?
Configuring Clusters / Redeploying Certificates

### What needs fixing?
See conversation in issue https://github.com/openshift/openshift-ansible/issues/11098 - the default has changed from 30 days to 365. Also, the warning is now a fatal error, so the docs should in some way mention this.

**Comment by mburke5678** [comment]
Fixed https://docs.openshift.com/container-platform/3.11/install_config/redeploying_certificates.html#install-config-cert-expiry-role-variables
