### ISSUE TITLE
openshift_node_cert_expire_days (3.11)

### ISSUE THREAD

**Issue by faust64** [openshift/openshift-docs#13525]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/3.11/install/configuring_inventory_file.html#configuring-cluster-variables

### What needs fixing?

The ansible variable `openshift_node_cert_expire_days` no longer appears in openshift-ansible, as `openshift_node_certificates` role disappeared in 3.11.

Would love some insight on how to force these, although I suspect its disappearance could imply their being renewed internally/automatically somehow?

**Comment by rmahroua** [comment]
I believe that the duration of validity is now be controlled with: 
osm_controller_args={"experimental-cluster-signing-duration": ["XXh]}

You can add this to the `[OSEv3:vars]` group

**Comment by faust64** [comment]
I'll trust you on that one. Currently experimenting with OpenShift 4, probably won't redeploy OKD3 in a little while.

Thanks for the follow up.

**Comment by rmahroua** [comment]
I retested as I needed to redeploy an OCP 3.11 cluster, and confirm that this works. My client cert is not valid for ten years. 
Adding that note in case someone else is having the same issue.

**Comment by Lumoc** [comment]
osm_controller_args={"experimental-cluster-signing-duration": ["XXh]}

works put you have to run the openshift-master playbook so the parameter is written to the master configs - after that you can run redeploy-certificates playbook
