### ISSUE TITLE
openshift_logging_es_cpu_limit (3.10 - 3.11)

### ISSUE THREAD

**Issue by faust64** [openshift/openshift-docs#13526]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/3.11/install_config/aggregate_logging.html#aggregate-logging-ansible-variables

https://docs.openshift.com/container-platform/3.10/install_config/aggregate_logging.html#aggregate-logging-ansible-variables

### What needs fixing?

The variable `openshift_logging_es_cpu_limit` is only mentionned in `openshift_logging` role defaults, and doesn't seem to be used anywhere.

At first glance, it would look like `openshift_logging_elasticsearch_cpu_limit` or `openshift_logging_es_ops_cpu_limit` should be used instead.

Comparing roles between versions:

```
diff 3.9/roles/openshift_logging_elasticsearch/defaults/main.yml 3.10/roles/openshift_logging_elasticsearch/defaults/main.yml 
5a6,12
> 
> l_openshift_elasticsearch_image_replace: "{{ (openshift_logging_es5_techpreview | bool) | ternary('logging-elasticsearch5', 'logging-elasticsearch') }}"
> openshift_logging_elasticsearch_image: "{{ l_os_registry_url | regex_replace(l_openshift_logging_search | regex_escape, l_openshift_elasticsearch_image_replace) }}"
> 
> 
> openshift_logging_elasticsearch_proxy_image: "{{ l2_os_logging_proxy_image }}"
> 
7c14
< openshift_logging_elasticsearch_cpu_limit: "{{ openshift_logging_es_cpu_limit | default('') }}"
---
> openshift_logging_elasticsearch_cpu_limit: null
9c16
< openshift_logging_elasticsearch_memory_limit: "{{ openshift_logging_es_memory_limit | default('1Gi') }}"
---
> openshift_logging_elasticsearch_memory_limit: "{{ openshift_logging_es_memory_limit | default('16Gi') }}"
58c65
< openshift_logging_master_public_url: "{{ openshift_hosted_logging_master_public_url | default('https://' + openshift.common.public_hostname + ':' ~ (openshift_master_api_port | default('8443', true))) }}"
---
> openshift_logging_master_public_url: "{{ openshift_hosted_logging_master_public_url | default('https://' + openshift.common.public_hostname + ':' ~ openshift_master_api_port) }}"

```

We can confirm `openshift_logging_es_cpu_limit` is gone, since 3.10, for some reason.

Bug? Feature?

**Comment by mburke5678** [comment]
@faust64 We are getting around to cleaning out old issues. Sorry for the delay. If you can access this BZ, it might help. I am closing this issue. LMK if you want to reopen for any reason.
https://bugzilla.redhat.com/show_bug.cgi?id=1598321

> "openshift_logging_elasticsearch_cpu_limit" is defined at the openshift_logging_elasticsearch role level and is what is used when we are creating the template in that role
> 
> "openshift_logging_es_{,ops_}cpu_limit" is defined at the openshift_logging role level and the values specified in those variables are then supposed to be used to set "openshift_logging_elasticsearch_cpu_limit" when calling the openshift_logging_elasticsearch role.
>
