### ISSUE TITLE
Add firewalld configuration to OKD getting started prerequisites

### ISSUE THREAD

**Issue by matthewmodestino** [openshift/openshift-docs#13547]
### Which section(s) is the issue in?

https://docs.okd.io/latest/install/prerequisites.html#install-config-network-using-firewalld

### What needs fixing?

OKD getting started docs should clearly lay out firewalld set up requirements in prerequisites and not assume ansible is being used to install. 

As someone experimenting/learning openshift, and not using ansible, the ability to bring up a cluster with docker locally is awesome! Hoewever, I ran into issues (https://github.com/openshift/origin/issues/21420#issuecomment-459880028) with timeouts, that were solved with documentation found in a totally different area: https://github.com/openshift/origin/blob/release-3.11/docs/cluster_up_down.md#linux

specifically:

```
firewall-cmd --permanent --new-zone dockerc
firewall-cmd --permanent --zone dockerc --add-source 172.17.0.0/16
firewall-cmd --permanent --zone dockerc --add-port 8443/tcp
firewall-cmd --permanent --zone dockerc --add-port 53/udp
firewall-cmd --permanent --zone dockerc --add-port 8053/udp
firewall-cmd --reload
```

This would have gotten me up and running without resorting back to minishift. Ensuring this is called out clearly will likely help others avoid stumbling.

**Comment by mburke5678** [comment]
@vrutkovs Any thoughts on this request?

**Comment by vrutkovs** [comment]
OKD's firewall is configured by ansible, no additional actions required. 

`oc cluster up` is not supported, so actions for exposing it externally (which is incredibly dangerous) should not be listed in the documentation
