### ISSUE TITLE
Add OCP Java S2I Documentation

### ISSUE THREAD

**Issue by ncbaratta** [openshift/openshift-docs#13565]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/3.11/using_images/s2i_images/index.html

### What needs fixing?

We have Java in the OpenShift Online documentation (https://docs.openshift.com/online/using_images/s2i_images/java.html) but not the OpenShift Container Platform documentation. We'd like to see Java S2I documented in the OCP guide.

**Comment by vikram-redhat** [comment]
Closing this issue. Now tracked via: https://jira.coreos.com/browse/OSDOCS-284

**Comment by ncbaratta** [comment]
@vikram-redhat I think I wasn't clear enough.  This issue was for documentation on how to use Java S2I with the latest release of OpenShift.  The Jira you linked to is about moving documentation related to 3.5 and 3.6 to the OpenShift documentation.

**Comment by vikram-redhat** [comment]
Hi @ncbaratta - yes that is correct. In the meeting we discussed this and we said that we don't have any bandwidth for this. The only thing we can do is to move the 3.6 docs to OpenShift docs. I believe these docs are old and shouldn't be in the Online docs either and I will add a note to the Jira for their removal.
