### ISSUE TITLE
[enterprise-3.11] Edit suggested in file admin_guide/managing_projects.adoc

### ISSUE THREAD

**Issue by ifekxp** [openshift/openshift-docs#13577]
### Which section(s) is the issue in?

#disabling-self-provisioning point (5)

### What needs fixing?
self-provisioners needs to be singular in command "$ oc edit clusterrolebinding.rbac self-provisioners" 
So:
$ oc edit clusterrolebinding.rbac self-provisioner

**Comment by mburke5678** [comment]
Thank you for your comment. Apologies for taking to long to respond. Can you confirm that `self-provisioners` is singular? This is what I get when I run the command:
```
oc edit clusterrolebinding.rbac self-provisioner
Error from server (NotFound): clusterrolebindings.rbac.authorization.k8s.io "self-provisioner" not found
```
```
$ oc get clusterrolebinding.rbac
NAME                                                                              AGE
...
self-provisioners                                                                 40m
...
