### ISSUE TITLE
[enterprise-4.0] Description needed for config overrides to api server operator

### ISSUE THREAD

**Issue by jkupferer** [openshift/openshift-docs#13606]
### Which section(s) is the issue in?

Operators

### What needs fixing?

The CRD kubeapiserveroperatorconfig includes a section spec.unsupportedConfigOverrides which can be used to configure the API server with settings that cannot be otherwise configured with the operator. This feature is documented at:

https://github.com/openshift/cluster-kube-apiserver-operator/blob/master/README.md

**Comment by vikram-redhat** [comment]
Tracking: https://bugzilla.redhat.com/show_bug.cgi?id=1691204
