### ISSUE TITLE
https://www.okd.io/ links OKD version to k8s version

### ISSUE THREAD

**Issue by jeffb4** [openshift/openshift-docs#13602]
### Which section(s) is the issue in?

https://www.okd.io/ "What is OKD?"

### What needs fixing?

"An OKD release corresponds to the Kubernetes distribution - for example, OKD 1.10 includes Kubernetes 1.10." With OKD versions going up past 3.9 at this time, that statement does not seem correct (I don't know what if any the linkage is now or where to get compatibility matrices)

**Comment by jeffb4** [comment]
@vikram-redhat I don't understand why you closed this. The OKD website still has misleading version information under "What is OKD?"

**Comment by vikram-redhat** [comment]
@jeffb4 Hey - this is the issues section for the docs site. OKD's main site is not controlled by us.

@wgordon17 are you able to help with this?

**Comment by wgordon17** [comment]
Thanks @vikram-redhat, I've created https://github.com/openshift-cs/okd.io/issues/95
