### ISSUE TITLE
[enterprise-3.11] Edit suggested in file admin_guide/scheduling/descheduler.adoc

### ISSUE THREAD

**Issue by falencastro** [openshift/openshift-docs#13684]
### Which section(s) is the issue in?

Overview

### What needs fixing?

Second bullet point:

"Pod and node affinity requirements, such as taints or labels, have changed and the original scheduling decisions are ***no*** longer appropriate for certain nodes."

**Comment by jboxman** [comment]
Hi @falencastro! Thanks for reporting this. I've opened https://github.com/openshift/openshift-docs/pull/13702 to address it.
