### ISSUE TITLE
Document granting builders permissions to other namespaces

### ISSUE THREAD

**Issue by liggitt** [openshift/openshift-docs#1371]
The service account named "builder" in the same namespace as the build is used to run a build pod. That service account must have permission to push to the target namespace. By default, the "builder" service account is only given push permissions to its own namespace.

You can grant builders in other namespaces permissions. This example gives the builder service account in the "myproject" namespace permission to build and push to the "openshift" namespace:

```
oc policy add-role-to-user system:image-builder system:serviceaccount:myproject:builder -n openshift
```

**Comment by ahardin-rh** [comment]
@liggitt Digging up this old issue. Is this still valid? Looks like some more content has been added since this was opened including https://docs.openshift.com/container-platform/3.5/admin_solutions/user_role_mgmt.html

**Comment by liggitt** [comment]
yes, still valid

**Comment by ahardin-rh** [comment]
@liggitt Thanks. I created https://bugzilla.redhat.com/show_bug.cgi?id=1471219 to better track improvements.
