### ISSUE TITLE
[enterprise-4.0] Configuring an HTPasswd identity provider

### ISSUE THREAD

**Issue by barleyer** [openshift/openshift-docs#13771]
### Which section(s) is the issue in?
Creating the HTPasswd Secret

### What needs fixing?

I think using `$ oc create secret generic htpass-secret --from-file=htpasswd=</path/to/users.htpasswd> -n openshift-config` is simple and clear,and avoiding line changing problem(`$ base64 </path/to/users.htpasswd>`)

**Comment by vikram-redhat** [comment]
@huffmanca - this seems to be an RFE/opinion. Before I create a bug for this, could you look at the request and see if it makes sense to change this?

**Comment by stuartchuan** [comment]
Track in: https://bugzilla.redhat.com/show_bug.cgi?id=1683088
