### ISSUE TITLE
[enterprise-4.0] Configuring 4.0 IDP

### ISSUE THREAD

**Issue by barleyer** [openshift/openshift-docs#13779]
### Which section(s) is the issue in?
Configuring your cluster for Keystone

### What needs fixing?
I think we should delete the whole section,also for other IDPs that having the same section.

**Comment by vikram-redhat** [comment]
@barleyer Hi there - could you elaborate on why it should be deleted? Is this no longer valid in 4.0?

@huffmanca

**Comment by barleyer** [comment]
@vikram-redhat ,we do not have master-config anymore on 4.0 cluster.

**Comment by vikram-redhat** [comment]
Tracking: https://bugzilla.redhat.com/show_bug.cgi?id=1683014
