### ISSUE TITLE
[enterprise-4.0] Machine API overview documentation issues

### ISSUE THREAD

**Issue by jhou1** [openshift/openshift-docs#13778]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.0/machine_management/creating-infrastructure-machinesets.html#machine-api-overview-creating-infrastructure-machinesets

### What needs fixing?
- `MachineClasses` is not supported.
- `MachineHealthChecker` should be `MachineHealthCheck`.

**Comment by vikram-redhat** [comment]
Tracking: https://bugzilla.redhat.com/show_bug.cgi?id=1682997
