### ISSUE TITLE
[enterprise-4.0] MachineSet documentation issues

### ISSUE THREAD

**Issue by jhou1** [openshift/openshift-docs#13777]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.0/machine_management/creating-machineset.html

### What needs fixing?
- Section **Creating a MachineSet**, machineSets should be viewed/created under the `openshift-machine-api` namespaces instead of `openshift-cluster-api`. There are several occurrences of `openshift-cluster-api` in this document.

**Comment by vikram-redhat** [comment]
Tracking: https://bugzilla.redhat.com/show_bug.cgi?id=1682997
