### ISSUE TITLE
[enterprise-4.0] MachineHealthCheck documentation issues

### ISSUE THREAD

**Issue by jhou1** [openshift/openshift-docs#13776]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.0/machine_management/deploying-machine-health-checks.html

### What needs fixing?
- Typo in summary: `s/heath/health/`
- Typo in *About MachineHealthChecks* section, `MachineHealthChecks automatically repair unhealthy ` -> `s/repair/repairs`
- *Sample MachineHealthCheck resource* section, the `MachineHealthCheck` resource should be created under `openshift-machine-api` namespace.

**Comment by vikram-redhat** [comment]
Tracking: https://bugzilla.redhat.com/show_bug.cgi?id=1682997
