### ISSUE TITLE
[enterprise-4.0] Edit suggested in file applications/operators/olm-adding-operators-to-cluster.adoc

### ISSUE THREAD

**Issue by sferich888** [openshift/openshift-docs#13789]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.0/applications/operators/olm-adding-operators-to-cluster.html#olm-operator-lifecycle-manager-olm-adding-operators-to-a-cluster

### What needs fixing?
At some point, the URL to the operator framework is going to change (we may want a plug in the docs that define what this framework is), as its a coreos resource.

**Comment by vikram-redhat** [comment]
Tracking: https://bugzilla.redhat.com/show_bug.cgi?id=1682975
