### ISSUE TITLE
[enterprise-4.0] Using right data type for IDP configuration

### ISSUE THREAD

**Issue by barleyer** [openshift/openshift-docs#13785]
### Which section(s) is the issue in?
Configuring identity providers

### What needs fixing?
All `ca`  field is **cm** type
All `clientSecret` `bindPassword` `tlsClientCert tlsClientKey` field is **secret** type

**Comment by vikram-redhat** [comment]
@barleyer  I can't seem to find where (or what) the issue is. Could you please link to the exact location?

**Comment by barleyer** [comment]
Have to change all fields like:
```
 tlsClientCert: /path/to/client.crt
```
To
```
tlsClientCert:
  name: github-secret
```

**Comment by barleyer** [comment]
For all IDPs, we need to add steps to create the `secret/cm`s

**Comment by stuartchuan** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1683087
