### ISSUE TITLE
[enterprise-4.0] Use openshift-logging namespace

### ISSUE THREAD

**Issue by anpingli** [openshift/openshift-docs#13784]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.0/logging/efk-logging-deploy.html#efk-logging-deploy-pre_efk-logging-deploy

3. Specify a node selector
oc adm new-project logging --node-selector=""

### What needs fixing?
The namespace name should be openshift-logging

oc adm new-project logging --node-selector=""

**Comment by vikram-redhat** [comment]
Tracking: https://bugzilla.redhat.com/show_bug.cgi?id=1682996
