### ISSUE TITLE
[enterprise-4.0] Remove the bracket after storage

### ISSUE THREAD

**Issue by anpingli** [openshift/openshift-docs#13780]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.0/logging/efk-logging.html#efk-logging-configuring-crd

### What needs fixing?
      storage: {}
        storageClass:
          name: "gp2"
          size: "200G"

###
      storage:
        storageClass:
          name: "gp2"
          size: "200G"

**Comment by vikram-redhat** [comment]
Tracking: https://bugzilla.redhat.com/show_bug.cgi?id=1682996
