### ISSUE TITLE
[enterprise-4.0] The link eror in Logging

### ISSUE THREAD

**Issue by anpingli** [openshift/openshift-docs#13781]
### Which section(s) is the issue in?
1. https://docs.openshift.com/container-platform/4.0/logging/efk-logging.html#efk-logging-configuring-crd
 -->OpenShift Documentation Project <dev@lists.openshift.redhat.com> 4.0 :data-uri: :icons: :experimental: :toc: macro :toc-title: :imagesdir: images :prewrap!:

2. https://docs.openshift.com/container-platform/4.0/logging/efk-logging-deploy.html
  -->  The process for deploying the EFK into {prouct-title} involves

**Comment by vikram-redhat** [comment]
Tracking: https://bugzilla.redhat.com/show_bug.cgi?id=1682996
