### ISSUE TITLE
[enterprise-4.0] Correct the URL to get a token.

### ISSUE THREAD

**Issue by barleyer** [openshift/openshift-docs#13795]
### Which section(s) is the issue in?
All IDPs

### What needs fixing?
On 4.0 cluster, we use  `{the route in ns/openshift-authentication}/oauth/token/request` to get a token,all `<master>/oauth/token/request ` should change.
You can get {the route in ns/openshift-authentication} by cmd `oc get route openshift-authentication -n openshift-authentication -o json | jq .spec.host`

**Comment by stuartchuan** [comment]
Tracked in https://bugzilla.redhat.com/show_bug.cgi?id=1683136
