### ISSUE TITLE
[enterprise-4.0] Edit suggested in file applications/operators/olm-adding-operators-to-cluster.adoc

### ISSUE THREAD

**Issue by sferich888** [openshift/openshift-docs#13790]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.0/applications/operators/olm-adding-operators-to-cluster.html#olm-installing-from-operatorhub-using-web-console-olm-adding-operators-to-a-cluster

### What needs fixing?
You use `etcd` as an example but don't call this out (that its an example), consider calling this out or replacing `etcd` with `your_oprator_of_choice`.

**Comment by vikram-redhat** [comment]
Tracking: https://bugzilla.redhat.com/show_bug.cgi?id=1682975
