### ISSUE TITLE
[enterprise-4.0] Wrong link to "AWS quick cluster install" on page welcome/index.html

### ISSUE THREAD

**Issue by liangxia** [openshift/openshift-docs#13793]
### Which section(s) is the issue in?
welcome/index.html#cluster-administrator-activities

### What needs fixing?
There is a task "Deploy OpenShift Container Platform: Choose between an AWS quick cluster install or AWS install with customizations." But the link on "AWS quick cluster install" in not accurate.
Currently, it links to "installing-aws/installing-aws-account.html",
actually, it should link to "installing-aws/installing-quickly-cloud.html"

**Comment by vikram-redhat** [comment]
Tracking: https://bugzilla.redhat.com/show_bug.cgi?id=1683188
