### ISSUE TITLE
[enterprise-4.0] Edit suggested in file authentication/identity_providers/configuring-htpasswd-identity-provider.adoc

### ISSUE THREAD

**Issue by sferich888** [openshift/openshift-docs#13791]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.0/authentication/identity_providers/configuring-htpasswd-identity-provider.html#identity-provider-creating-htpasswd-file-configuring-htpasswd-identity-provider

### What needs fixing?
This process assumes that a user has a RHEL or Linux server where they can `yum install httpd-tools` from. User of OCP 4.0 will not necessarly have a RHEL system like this stood up (on demand to add such tools too). 

Consider replacing with something like: 

```sh
$ printf "USER:$(openssl passwd -crypt PASSWORD)\n" >> .htpasswd
```

- This assumes you have bash (printf) and openssl (installed on a system); so we don't have a good generic solution that would work everywhere (however showing multiple options may help some users).

**Comment by vikram-redhat** [comment]
Tracking: https://bugzilla.redhat.com/show_bug.cgi?id=1682964

**Comment by thoraxe** [comment]
@sferich888 when I try to do that with a password longer than 8 chars I get `Warning: truncating password to 8 characters` which is probably bad.

**Comment by thoraxe** [comment]
https://coderwall.com/p/zvvgna/create-htpasswd-file-for-nginx-without-apache

**Comment by sferich888** [comment]
@thoraxe that is due to the algorithm: https://httpd.apache.org/docs/2.4/misc/password_encryptions.html
You can output other hashes that can be used to record your user/password. 

The htpasswd format lets each user:password combination use a set of factors to define how it should be validated. 

```
Files managed by htpasswd may contain a mixture of different encoding types of passwords; some user records may have bcrypt or MD5-encrypted passwords while others in the same file may have passwords encrypted with crypt().
```
https://httpd.apache.org/docs/2.4/en/programs/htpasswd.html
