### ISSUE TITLE
[enterprise-4.0] Make docs consistent for RHEL CoreOS naming

### ISSUE THREAD

**Issue by jtudelag** [openshift/openshift-docs#13796]
There are references to "Red Hat CoreOS", "RHEL CoreOS" and "RHCOS" all over the 4.0 docs,
it does not seem very consistent to me, although I'm not sure which is the preferred one...
...I guess is "RHEL CoreOS", but just guessing.

### Which section(s) is the issue in?

Everywhere: release-nodes, Architecture, etc.

### What needs fixing?

Make sure references to the new CoreOS based O.S are consistent across the docs.

**Comment by vikram-redhat** [comment]
Tracking: https://bugzilla.redhat.com/show_bug.cgi?id=1683196
