### ISSUE TITLE
[enterprise-3.11] Edit suggested in file install_config/redeploying_certificates.adoc

### ISSUE THREAD

**Issue by jas02** [openshift/openshift-docs#13820]
### Which section(s) is the issue in?

Redeploying Node Certificates Only

### What needs fixing?

There is no such playbook to redeploy certificates on node level. No playbook *playbooks/openshift-node/redeploy-certificates.yml*.

**Comment by bergerhoffer** [comment]
Closing as the playbook paths have been corrected.
