### ISSUE TITLE
[enterprise-3.11] Edit suggested in file install/prerequisites.adoc

### ISSUE THREAD

**Issue by kirby** [openshift/openshift-docs#13851]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/3.11/install/prerequisites.html#node-hostnames-prereq

### What needs fixing?

1. One one node, obtain the host name:

should read

1. On one node, obtain the hostname:

**Comment by jboxman** [comment]
Hi @kirby, thanks for reporting this! I've created https://github.com/openshift/openshift-docs/pull/13867 to resolve it. I fixed _s/One/On/_. We use the IBM style guide, where _host name_ is the correct form.
