### ISSUE TITLE
Describe setting KUBECONFIG

### ISSUE THREAD

**Issue by adellape** [openshift/openshift-docs#1385]
As shown in https://github.com/openshift/openshift-docs/pull/888, describe setting/exporting KUBECONFIG (particularly for the Origin docs) for clarity in relevant topics.

**Comment by ahardin-rh** [comment]
Looks like more information has been added to https://docs.openshift.com/container-platform/3.5/admin_solutions/master_node_config.html since this was opened, so I will close this. We can reopen if more is needed here.
