### ISSUE TITLE
Running In Container Docs incomplete

### ISSUE THREAD

**Issue by Setheck** [openshift/openshift-docs#13870]
### Which section(s) is the issue in?
https://docs.okd.io/latest/getting_started/administrators.html#running-in-a-docker-container

### What needs fixing?
The doc states that you can get up and running quickly with images from docker hub. But makes no reference to which images are related. 
One can only assume that `https://hub.docker.com/r/openshift/origin` is the image being referenced. However, the very first line in the container description is
```
NO LONGER UPDATED: This image was deprecated after the 3.10 OpenShift release, being split into multiple other images. It is no longer used by commands like oc cluster up or the openshift-ansible install.
```
On top of this, that image also has 3.11 tags.

So these docs are incomplete and very confusing.

**Comment by mburke5678** [comment]
@vrutkovs Any thoughts on which image should be used here?

**Comment by vrutkovs** [comment]
There's no such section in latest docs.

3.11 docs should remove this section - `openshift/origin` is no longer used

**Comment by zerodayz** [comment]
@vrutkovs Hi, linked the other issue reported in origin repository. I would like to take this issue as my first contribution. Currently following https://github.com/openshift/openshift-docs/blob/master/contributing_to_docs/tools_and_setup.adoc and preparing the needed tools.

**Comment by vrutkovs** [comment]
In order to build OKD documentation I used `python3 build.py --distro openshift-origin --product "OKD" --version 4.4 --no-upstream-fetch && python3 makeBuild.py && asciibinder build -t 0`. It needs quite a few gems installed to succeed.

**Comment by zerodayz** [comment]
@vrutkovs I am on Fedora 32 and everything worked first time, changed administration.adoc, built docs, confirmed the change and PR is coming now. I will note your commands for future reference.

**Comment by zerodayz** [comment]
@vrutkovs  I used:
1. Forked the repo
2. Cloned the repo
```
git clone ... openshift-docs
```
3. Prepared tools
```
sudo yum install rubygems
sudo yum install ruby-devel
sudo yum install gcc-c++
sudo yum install redhat-rpm-config
sudo yum install make
gem install asciidoctor-diagram --version=1.5.6
gem install ascii_binder
```
4. Cloned the repo
```
git clone ...openshift-docs
cd openshift-docs
git checkout origin/enterprise-3.11
git checkout -b "docs-getting-started-13870"
vi getting_started/administrators.adoc
git add getting_started/administrators.adoc
git commit -s
...
git push
```

**Comment by zerodayz** [comment]
@vrutkovs Pull request https://github.com/openshift/openshift-docs/pull/21942

**Comment by zerodayz** [comment]
> In order to build OKD documentation I used `python3 build.py --distro openshift-origin --product "OKD" --version 4.4 --no-upstream-fetch && python3 makeBuild.py && asciibinder build -t 0`. It needs quite a few gems installed to succeed.

Thank you for your help. Can you please check on my https://github.com/openshift/openshift-docs/issues/13870#issuecomment-625695435 ? When I build I can see the OKD documentation but your comment made me unsure, if I need to submit PR against different branch?

**Comment by mburke5678** [comment]
Changes made in https://github.com/openshift/openshift-docs/pull/21942
