### ISSUE TITLE
[enterprise-4.0] eu-west-3 (Paris) AWS region should not be supported

### ISSUE THREAD

**Issue by tale-toul** [openshift/openshift-docs#13887]
### Which section(s) is the issue in?

 Installing clusters on AWS / Configuring an AWS account / Supported AWS regions

### What needs fixing?

AWS Paris region does not support m4 instances, it should be removed from the list of supported regions.

**Comment by vikram-redhat** [comment]
Tracking: https://bugzilla.redhat.com/show_bug.cgi?id=1684100
