### ISSUE TITLE
Add more content about the creation of the optional ssh keys

### ISSUE THREAD

**Issue by tale-toul** [openshift/openshift-docs#13889]
### Which section(s) is the issue in?

Installing clusters on AWS Installing a cluster quickly on AWS / Configuring your computer for installation

### What needs fixing?
I think that step 4 needs some more content to clarify things like:
The ssh keys mention are the keypairs you can create in AWS or are they local keys you create in the computer your are running the installation from?  In the latter case what types of keys are supported (rsa,dsa, etc).
An example can clarify these things.

May be it is found in another part of the documentation but during an actual installation of OCP 4.0 I tried to connect to an instance using an ssh key and it didn't work, most likely because I was not using the proper user to connect as (ec2-user)

**Comment by vikram-redhat** [comment]
Tracking: https://bugzilla.redhat.com/show_bug.cgi?id=1684251
