### ISSUE TITLE
[enterprise-3.11] Edit suggested in file welcome/oce_about.adoc

### ISSUE THREAD

**Issue by erockwood** [openshift/openshift-docs#13906]
### Which section(s) is the issue in?
Final Table - Advanced Cluster Management and beyond

### What needs fixing?
Content placed in the wrong columns

![image](https://user-images.githubusercontent.com/46362781/53610376-70bf9580-3b7f-11e9-91a0-1ec394ab53ab.png)

**Comment by jboxman** [comment]
@erockwood, thanks for reporting this! Fixed in PR https://github.com/openshift/openshift-docs/pull/13933
