### ISSUE TITLE
[enterprise-3.0] Edit suggested in file dev_guide/persistent_volumes.adoc

### ISSUE THREAD

**Issue by chriskim06** [openshift/openshift-docs#13904]
### Which section(s) is the issue in?

The indentation in the Persistent Volume Claim object definition is incorrect on the "Using Persistent Volumes" page. It shows the following object:
```
{
    "apiVersion": "v1",
    "kind": "PersistentVolumeClaim",
    "metadata": {
        "name": "claim1"
    },
    "spec": {
        "accessModes": [ "ReadWriteOnce" ],
        "resources": {
            "requests": {
                "storage": "5Gi"
            },
        "volumeName": "pv0001"
        }
    }
}
```

### What needs fixing?

The `.spec.resources.volumeName` key/value pair should be indented once. This gave me some trouble earlier because I skimmed over the object definition, didn't notice this, and thought `volumeName` was in the `spec` object.

**Comment by jboxman** [comment]
@chriskim06, thanks for reporting this issue! I've created this PR https://github.com/openshift/openshift-docs/pull/13934 to resolve it.
