### ISSUE TITLE
[enterprise-3.11] Edit suggested in file scaling_performance/managing_hugepages.adoc

### ISSUE THREAD

**Issue by erockwood** [openshift/openshift-docs#13905]
### Which section(s) is the issue in?
What Huge Pages Do
Memory is managed in blocks known as pages. On most systems, a page is 4Ki. 1Mi of memory is equal to 256 pages; 1Gi of memory is 256,000 pages, and so on.

### What needs fixing?
1Gi would be 262,144 or use ~256,000 pages.

**Comment by jboxman** [comment]
@erockwood, thanks for reporting this issue. I've open a PR https://github.com/openshift/openshift-docs/pull/13931 with the change.
