### ISSUE TITLE
[enterprise-3.11] Edit suggested in file install_config/adding_hosts_to_existing_cluster.adoc

### ISSUE THREAD

**Issue by Alveel** [openshift/openshift-docs#13953]
### Which section(s) is the issue in?

Procedure list entry 5

### What needs fixing?

I think
`oc label node/new-node.example.com logging-infra-fluentd: "true"`
should be
`oc label node/node4 logging-infra-fluentd=true`

**Comment by mburke5678** [comment]
Thanks for pointing this out. The command was fixed in https://github.com/openshift/openshift-docs/pull/14226
