### ISSUE TITLE
Unclear description of endpoint for self-provisioning projects

### ISSUE THREAD

**Issue by Miciah** [openshift/openshift-docs#1397]
The documentation on [Self-Provisioned Projects](../blob/master/admin_guide/selfprovisioned_projects.adoc) states, "An accessible endpoint exists that will provision a project according to a template. This endpoint is made accessible when a developer creates a new project." These two statements are confusing: They seem say that you can use an endpoint to create a project, but you need to have a project in order to have the endpoint to create a project.  What?

If I had to make an uninformed guess (i.e., without reading further), I would interpret these statements to mean that for each project, there exists an API endpoint  to create a new project using the old project as a template.  However, from reading further, that does not appear to be the case.

A more informed guess (i.e., from reading further) is that the second quoted statement, "This endpoint is made accessible when a developer creates a new project", is intended to refer to the web console, in which case a clearer wording might be, "If this endpoint is configured, then the web console will show an option to create a new project using this template."  Is that statement correct?

Aside from the above confusion, the phrase "accessible endpoint" is also confusing.  What is the word "accessible" intended to convey? Could we just say "endpoint" or "API endpoint"?

The word "exists" seems misleading; shouldn't that be "can be enabled"/"can be configured"? (Arguably the endpoint exists whether or not it is configured, but it does not create a project unless it is configured appropriately.)

@deads2k, @bfallonf, could you clarify please?

**Comment by bfallonf** [comment]
@Miciah Thanks for the issue. Unfortunately I'm just as uninformed as you are... @deads2k is Miciah right in his presumptions above? I don't mind making a PR with the changes, but I don't want to go down the wrong path.

**Comment by deads2k** [comment]
Hopefully https://github.com/openshift/openshift-docs/pull/1405 will help.

Basically, the endpoint is exposed to all authenticated users by default and a POST to that endpoint will create a project using the template.  `oc new-project --loglevel=8` will help you sort out exactly what the REST requests look like.

**Comment by bfallonf** [comment]
@deads2k Thanks for making that PR. I think this clears it up. @Miciah do you agree?

**Comment by Miciah** [comment]
Thanks! It's a lot clearer.

It might be clearer still to change, "This endpoint is used [...]" to, "The web console and `oc new-project` command use this endpoint [...]", in order to move the focus to and explicitly state what the reader probably cares about (namely how to configure a template that OpenShift will use when a developer creates a new project using these tools), but I don't feel too strongly about this.

Also, we use "endpoint" differently in different parts of the documentation, so maybe it would be good to be more explicit: "API endpoint", "REST API endpoint", or whatever the prevailing terminology is (or should be).  That concern over terminology may warrant a separate issue though (if it warrants consideration at all).

**Comment by bfallonf** [comment]
@Miciah I agree. It's always best to explicitly say what is using the thing over stating that the thing is being used.

And re: type of endpoint, it'd be good to get the type in here, then create another issue, otherwise we're just going back to already-completed work.

@deads2k are you ok to make those changes to your PR, then I can merge?

Thanks for the work on this, guys.

**Comment by deads2k** [comment]
> @deads2k are you ok to make those changes to your PR, then I can merge?

sorry, was watching the pull, not the issue.  Updated in the pull.
