### ISSUE TITLE
[enterprise-4.0] Edit suggested in file nodes/pods/nodes-pods-using.adoc

### ISSUE THREAD

**Issue by sunilcio** [openshift/openshift-docs#13981]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.0/nodes/pods/nodes-pods-using.html

### What needs fixing?
"For the maximum number of pods per OpenShift Container Platform node host, see the Cluster Limits."

In above statement, add a link to below Cluster Limits page.

https://docs.openshift.com/container-platform/4.0/scalability_and_performance/planning-your-environment-according-to-object-limits.html

**Comment by vikram-redhat** [comment]
Unfortunately, linking to content from within modules is something we can't do at this point in time. I am closing this issue, but will start a wider discussion in the team about how to tackle this.
