### ISSUE TITLE
[enterprise-4.0] Issues with OperatorHub docs

### ISSUE THREAD

**Issue by aravindhp** [openshift/openshift-docs#14009]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.0/applications/operators/olm-adding-operators-to-cluster.html#olm-operatorhub-olm-adding-operators-to-a-cluster

### What needs fixing?
In the sentence, "Cluster administrators can choose from CatalogSources of Operators grouped into the following categories:",  it should be `OperatorSources` instead of `CatalogSources of Operators`. 

### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.0/applications/operators/olm-adding-operators-to-cluster.html#olm-installing-operator-from-operatorhub-using-cli-olm-adding-operators-to-a-cluster

### What needs fixing?
Under "Procedure", it will help if you mention that you pick one of the packages you see in step 1 when you create the CatalogSourceConfig in step 2, namely in the `spec.packages`.

In step 4, we need to mention that the `namespace` picked requires to have an `OperatorGroup` that matches the `installMode` of the operator and that we only support `AllNamespaces` or `SingleNamespace` modes.

**Comment by chrisnegus** [comment]
Thanks Aravindh. I made the changes you suggested. Let me know if further changes are needed:

https://docs.openshift.com/container-platform/4.0/applications/operators/olm-adding-operators-to-cluster.html#olm-installing-from-operatorhub-using-web-console-olm-adding-operators-to-a-cluster
