### ISSUE TITLE
[enterprise-4.0]  olm-adding-operators-to-cluster etcd example

### ISSUE THREAD

**Issue by johwes** [openshift/openshift-docs#14019]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.0/applications/operators/olm-adding-operators-to-cluster.html#olm-installing-from-operatorhub-using-web-console-olm-adding-operators-to-a-cluster

### What needs fixing?
The example is to install the etcd operator
Step 4
On the Create Operator Subscription page, select All namespaces…​ under Installation Mode, choose an Update Channel (if more than one is available), And select Automatic or Manual Approval Strategy, as described earlier.
On the Create Operator Subscription page, select All namespaces…​ 

When trying to install the etcd operator for "All namespaces" the dialog is greyed out and below it shows the message "This mode is not supported by this Operator" 
So only only the "A specific namespace on the cluster" options is possible to choose.

**Comment by vikram-redhat** [comment]
Tracking: https://bugzilla.redhat.com/show_bug.cgi?id=1691206
