### ISSUE TITLE
[enterprise-4.0] Certified operators maintained by - under Architecture

### ISSUE THREAD

**Issue by johwes** [openshift/openshift-docs#14018]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.0/architecture/architecture.html#OLM-operators-architecture

### What needs fixing?
OpenShift Container Platform also offers certified Operators, which the community built and maintains

Is the community building and maintaining Certified Operators? I thought that was our ISV vendors.?

**Comment by vikram-redhat** [comment]
@openshift/team-documentation - can anyone answer this question?
