### ISSUE TITLE
Aggregate Logging steps need to be updated

### ISSUE THREAD

**Issue by detiber** [openshift/openshift-docs#1404]
https://docs.openshift.com/enterprise/3.1/install_config/aggregate_logging.html

On Topic 1. 
Should inform to join on project, after created. 

oc project logging

Or use "oc new-project logging" to create instead oadm...

2. Inform the option without certs:
oc secrets new logging-deployer nothing=/dev/null

**Comment by akram** [comment]
Hi @detieber 

it is also required to update the oc edit scc section, otherwise we got the following error.

```
Deleting existing secrets
+ echo 'Deleting existing secrets'
+ oc delete secret logging-fluentd logging-elasticsearch logging-kibana logging-kibana-proxy logging-kibana-ops-proxy
Error from server: User "system:serviceaccount:default:logging-deployer" cannot delete secrets in project "default"
Error from server: User "system:serviceaccount:default:logging-deployer" cannot delete secrets in project "default"
Error from server: User "system:serviceaccount:default:logging-deployer" cannot delete secrets in project "default"
Error from server: User "system:serviceaccount:default:logging-deployer" cannot delete secrets in project "default"
Error from server: User "system:serviceaccount:default:logging-deployer" cannot delete secrets in project "default"
Creating secrets
+ :
+ echo 'Creating secrets'
+ oc secrets new logging-elasticsearch key=/etc/deploy/keystore.jks truststore=/etc/deploy/truststore.jks searchguard.key=/etc/deploy/searchguard_node_key.key
Error from server: User "system:serviceaccount:default:logging-deployer" cannot create secrets in project "default"
```

It is missing:
```
- system:serviceaccount:default:logging-deployer
```

**Comment by bfallonf** [comment]
@detiber That issue will be fixed in #1641 

@akram I'm not too sure which section you're referring to. Is it step 2 of the pre-deployment phase?

https://docs.openshift.com/enterprise/3.1/install_config/aggregate_logging.html#pre-deployment-configuration

**Comment by ewolinetz** [comment]
@bfallonf so that they're not lost there are also two PRs that I opened to improve documentation for EFK as well.
#1613 and #1625

**Comment by bfallonf** [comment]
@ewolinetz Ah I see. Thanks for the notification. I can make some comments on #1613  and get the in, but should we close #1625 in favor of my #1641 ?

**Comment by ewolinetz** [comment]
@bfallonf it makes sense to me to close #1625. I'll address your comments in #1613

**Comment by bfallonf** [comment]
@ewolinetz Thanks for that!

@akram Let me know if you get to my question above.

**Comment by akram** [comment]
Hi @bfallonf 
I was talking about step 3.

**Comment by bfallonf** [comment]
@akram See #1663 . One question in there for you.

I'll close this issue.

Thanks, all!

**Comment by mgjadoul** [comment]
OK it is closed, but following the documentation I get an error.... I did it twice.... But I do not know what is wrong....
My guess If you are still in  the project logging when doing the step 1 of "Deploying the EFK Stack", it fail with the following error similar to the one above:
 
Deleting existing secrets
+ echo 'Deleting existing secrets'
+ oc delete secret logging-fluentd logging-elasticsearch logging-kibana logging-kibana-proxy logging-kibana-ops-proxy
Error from server: User "system:serviceaccount:logging:logging-deployer" cannot delete secrets in project "logging"
Error from server: User "system:serviceaccount:logging:logging-deployer" cannot delete secrets in project "logging"
Error from server: User "system:serviceaccount:logging:logging-deployer" cannot delete secrets in project "logging"
Error from server: User "system:serviceaccount:logging:logging-deployer" cannot delete secrets in project "logging"
Error from server: User "system:serviceaccount:logging:logging-deployer" cannot delete secrets in project "logging"
Creating secrets
+ :
+ echo 'Creating secrets'
+ oc secrets new logging-elasticsearch key=/etc/deploy/keystore.jks truststore=/etc/deploy/truststore.jks searchguard.key=/etc/deploy/searchguard_node_key.key
Error from server: User "system:serviceaccount:logging:logging-deployer" cannot create secrets in project "logging"
