### ISSUE TITLE
Day two docs: document how to replace master and router certificates

### ISSUE THREAD

**Issue by leoluk** [openshift/openshift-docs#14136]
https://github.com/openshift/openshift-docs/blob/master/day_two_guide/certificate_management.adoc

See: https://github.com/openshift/openshift-ansible/issues/10318

We should document on what's the best way to replace public master and router certificates in a running cluster, without touching the internal CA.

This is a common tasks when running a cluster with wildcard certificates.

**Comment by Bengrunt** [comment]
As of today, this is still an issue.

I guess people have moved or will move to OKD4 now, but I imagine plenty of others still have running 3.11 clusters that might have to do this quite critical operation.
