### ISSUE TITLE
Mention about `oc start-build --build-loglevel=5`

### ISSUE THREAD

**Issue by php-coder** [openshift/openshift-docs#1416]
When we are [describing log verbosity](https://docs.openshift.org/latest/dev_guide/builds.html#accessing-build-logs) I suggest to also mention that `oc start-build` has `--build-loglevel=5` option that will affect only the current build.

(Hint from @mfojtik)

**Comment by mfojtik** [comment]
@php-coder I think we already document this somewhere :-) Or I do remember writing some docs about this.

**Comment by php-coder** [comment]
This option now doesn't take effect (see https://github.com/openshift/origin/issues/8738), so we don't need to document it.

**Comment by php-coder** [comment]
Update: it should work when plugin `BuildDefaults` plugin is enabled but it's disabled by default.
