### ISSUE TITLE
[enterprise-4.0] Edit suggested in file storage/persistent-storage/persistent-storage-iscsi.adoc

### ISSUE THREAD

**Issue by rmahroua** [openshift/openshift-docs#14170]
### Which section(s) is the issue in?
Persistent Storage Using iSCSI

### What needs fixing?
Replace "inquisitor" with "initiator" at the end of the section (https://docs.openshift.com/container-platform/4.0/storage/persistent-storage/persistent-storage-iscsi.html#iscsi-custom-iqn-persistent-storage-iscsi)

**Comment by vikram-redhat** [comment]
Tracking: https://bugzilla.redhat.com/show_bug.cgi?id=1691207
