### ISSUE TITLE
[enterprise-3.11] Edit suggested in file install_config/aggregate_logging.adoc

### ISSUE THREAD

**Issue by JensKuehnel** [openshift/openshift-docs#14176]
### Which section(s) is the issue in?
Configuring Fluentd to Send Logs to an External Log Aggregator

### What needs fixing?
-w 0 is missing with base64.
Current:
$ oc patch secrets/logging-fluentd --type=json \
  --patch "[{'op':'add','path':'/data/your_ca_cert','value':'$(base64 /path/to/your_ca_cert.pem)'}]"

Correct:
$ oc patch secrets/logging-fluentd --type=json   \
--patch "[{'op':'add','path':'/data/your_ca_cert','value':'$(base64 -w 0 /path/to/your_ca_cert.pem)'}]"

**Comment by mburke5678** [comment]
Thanks for pointing this out. Making the change in https://github.com/openshift/openshift-docs/pull/20057
