### ISSUE TITLE
[enterprise-4.0] Edit suggested in file applications/operators/olm-what-operators-are.adoc

### ISSUE THREAD

**Issue by jboxman** [openshift/openshift-docs#14182]
### Which section(s) is the issue in?

Operator Lifecycle Manager
Controls the installation, upgrade, and RBAC of Operators in a cluster. Deployed by default in OpenShift Container Platform 4.

### What needs fixing?

Define RBAC. Role-based access control.

**Comment by vikram-redhat** [comment]
@jboxman, tracking: https://bugzilla.redhat.com/show_bug.cgi?id=1691211. In future, just use this link to create the bugs for 4.0/4.1 directly. https://tiny.cc/ocp_create_docs_bug
