### ISSUE TITLE
"Persistent" is misspelled in architecture_overview.png

### ISSUE THREAD

**Issue by danwinship** [openshift/openshift-docs#1418]
On the right side of architecture/images/architecture_overview.png is a box labeled "PERSISTANT STORAGE". That should be "PERSISTENT".

**Comment by danwinship** [comment]
(and I guess if someone is going to regenerate that image anyway, the labels in the bottom box [especially "PHYSICAL" and "VIRTUAL"] aren't really aligned with their images...)

**Comment by Prabhnith** [comment]
fix in #2401 . 
Reviews ..

**Comment by mburke5678** [comment]
Fixed. See:
https://github.com/openshift/openshift-docs/commit/d949c064b3c00aa31c5badaaba70055ff9047ebd
