### ISSUE TITLE
[enterprise-4.0] Edit suggested in file nodes/scheduling/nodes-scheduler-default.adoc

### ISSUE THREAD

**Issue by rmahroua** [openshift/openshift-docs#14213]
### Which section(s) is the issue in?
Modifying scheduler policies

### What needs fixing?
It seems that configuration map named `policy-configmap`no longer exists. In fact, the `openshift-config` project does not have any configuration map in it. 
Which config map replaces it? And where is it located?

**Comment by mburke5678** [comment]
@rmahroua Thank you for pointing this out. 
I will change the references to `policy-configmap`. The scheduler config map, I believe, can be named anything. It appears that I was not consistent with the name throughout the docs.  
https://github.com/openshift/openshift-docs/pull/20116

I see that the title suggests you were working in Openshift 4.0, is that correct? 
In 4.1+ I see that the `openshift-config` project appears frequently in the documentation and I see the project in a 4.3 cluster (I don't have access to 4.1 and 4.2 at the moment):

```
$ oc get projects
NAME                                                    DISPLAY NAME   STATUS
default                                                                Active
kube-node-lease                                                        Active
kube-public                                                            Active
kube-system                                                            Active
openshift                                                              Active
openshift-apiserver                                                    Active
openshift-apiserver-operator                                           Active
openshift-authentication                                               Active
openshift-authentication-operator                                      Active
openshift-cloud-credential-operator                                    Active
openshift-cluster-machine-approver                                     Active
openshift-cluster-node-tuning-operator                                 Active
openshift-cluster-samples-operator                                     Active
openshift-cluster-storage-operator                                     Active
openshift-cluster-version                                              Active
openshift-config                                                       Active

```
