### ISSUE TITLE
NFS docs are inconsistent about squash settings on export

### ISSUE THREAD

**Issue by pmorie** [openshift/openshift-docs#1425]
There are two different (similar) docs in the tree for NFS, and they make different recommendations about squash settings.  The squash setting users should be using is `root_squash`.  References to `all_squash` should be removed.

See:
1.  https://docs.openshift.com/enterprise/3.1/install_config/persistent_storage/persistent_storage_nfs.html
2.  https://docs.openshift.com/enterprise/3.0/admin_guide/persistent_storage_nfs.html

@erinboyd @childsb

**Comment by erinboyd** [comment]
These are for different versions of OSE. OSE 3.1+ has the ability to better secure the data, therefore it's more restrictive in the export setting.

**Comment by screeley44** [comment]
no_root_squash OR root_squash?  3.1 shows "root_squash" and 3.0 shows "all_squash"

@pmorie @erinboyd

**Comment by pmorie** [comment]
@screeley44 You're right, I meant `root_squash`, not `no_root_squash`

**Comment by erinboyd** [comment]
@pmorie the difference is intentionally and appropriate for the versions.

**Comment by pmorie** [comment]
I think we should add a pointer to the 3.1 docs from 3.0

**Comment by pmorie** [comment]
Here's the real problem to mitigate: when someone sees these docs on the web, it's not obvious that they're for different versions, and people wind up confused. So, really we need to do something to make it obvious from the 3.0 doc that the guidance is updated in 3.1.  

@adellape, is there a precedent in the doc for when guidance changes significantly between versions and you need to funnel people to the latest version from older versoins?

**Comment by adellape** [comment]
@pmorie Sounds like a Note box explaining the situation w/ a link to the equivalent 3.1 doc would be appropriate.

**Comment by erinboyd** [comment]
@adellape what is a 'note box'?

**Comment by adellape** [comment]
@erinboyd Sorry, more specifically, a "Note" admonition:

https://github.com/openshift/openshift-docs/blob/master/contributing_to_docs/doc_guidelines.adoc#admonitions

http://www.methods.co.nz/asciidoc/userguide.html#X22

**Comment by erinboyd** [comment]
@adellape Created PR for fix issue. Linked above ^^

**Comment by ahardin-rh** [comment]
Looks like this was fixed via https://github.com/openshift/openshift-docs/issues/2310
