### ISSUE TITLE
[enterprise-4.0] Edit suggested in file welcome/index.adoc

### ISSUE THREAD

**Issue by amelie1979** [openshift/openshift-docs#14317]
### Which section(s) is the issue in?

Missing Section for System and environment requirements

### What needs fixing?
The section is completely missing, we need System and environment requirements for UPI,
Point to add : 
OS Requirement and supported version
CPU & Memory requirement by Roles (masters,etcd,infra nodes, app nodes)
DISK requirements by partition by roles.

**Comment by vikram-redhat** [comment]
This section hadn't been published when this issue was filed: https://docs.openshift.com/container-platform/4.1/installing/installing_bare_metal/installing-bare-metal.html
