### ISSUE TITLE
[enterprise-3.11] Edit suggested in file install_config/configuring_local.adoc

### ISSUE THREAD

**Issue by huizengaJoe** [openshift/openshift-docs#14349]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/3.11/install_config/configuring_local.html
The Overview section is saying:

Local volumes is a Technology Preview feature only. Technology Preview features are not supported with Red Hat production service level agreements (SLAs), might not be functionally complete, and Red Hat does not recommend to use them for production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process. For more information on Red Hat Technology Preview features support scope, see https://access.redhat.com/support/offerings/techpreview/.
--
Does this really apply to any usage of Local Volumes or is it referring to the Local Volume provisioner only?  This seems to conflict with 
https://docs.openshift.com/container-platform/3.11/install_config/persistent_storage/persistent_storage_local.html

I found the following link for some context:
https://kubernetes.io/blog/2018/04/13/local-persistent-volumes-beta/

### What needs fixing?
I am really just looking for a confirmation on which one is correct,  we would like to start recommending to our teams to use Local Volumes but this link is stopping us from making this recommendation. Are local volumes without the local volume provisioner supported with openshift 3.11?

**Comment by jboxman** [comment]
@sichvoge, I know storage isn't your area, but because of your involvement lately, do you know who might have a definitive answer to this question? Thank you.

**Comment by listey** [comment]
For OpenShift 3.11 Local Volumes are considered in Tech Preview as per your original link. HTH.

**Comment by rdzimmer** [comment]
I have not had any success yet finding any issues or roadmaps that point to when Local Volumes may move from Tech Preview to a supported feature in OpenShift now that it is GA in kubernetes.  If any of you have any insight into that process I would appreciate it, thanks! https://kubernetes.io/blog/2019/04/04/kubernetes-1.14-local-persistent-volumes-ga/

**Comment by sichvoge** [comment]
The current plan is to release Local Volumes GA in 4.2.
