### ISSUE TITLE
[enterprise-3.11] Edit suggested in file dev_guide/dev_tutorials/openshift_pipeline.adoc

### ISSUE THREAD

**Issue by kkoller** [openshift/openshift-docs#14372]
### Which section(s) is the issue in?
The Jenkinsfile -> deploy stage

### What needs fixing?
In the deploy section, the given example will not result in a deployment:
def rm = openshift.selector("dc", templateName).rollout()
Selector.rollout() returns a RolloutManager on which you can call .latest() to trigger a new deployment. You can find the docs here, although it is an image so I can't link directly to it.  It is the final section at the bottom of the page: https://github.com/openshift/jenkins-client-plugin

Please update the line to read:
def rm = openshift.selector("dc", templateName).rollout().latest()

**Comment by vikram-redhat** [comment]
Fixed by #14384
