### ISSUE TITLE
[enterprise-4.0] Edit suggested in file registry/registry-options.adoc

### ISSUE THREAD

**Issue by hrishin** [openshift/openshift-docs#14465]
It is hard to figure out how to enable V2 schema for the integrated registry.

### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.0/registry/registry-options.html

### What needs fixing?
Need to an env `REGISTRY_MIDDLEWARE_REPOSITORY_OPENSHIFT_ACCEPTSCHEMA2`
for `deployment/image-registry` in OpenShift 4.
 
It would really nice if one could list all configuration options available for the integrated registry. 

cc: @vdemeester

**Comment by vikram-redhat** [comment]
Being worked on in an internal ticket. Closing this issue.
