### ISSUE TITLE
Add explanation for docker_log_driver to Ansible installer

### ISSUE THREAD

**Issue by nak3** [openshift/openshift-docs#1447]
It has been added since this [PR/734](https://github.com/openshift/openshift-ansible/pull/734)

Please add it to https://docs.openshift.com/enterprise/3.1/install_config/install/advanced_install.html

**Comment by nak3** [comment]
close for https://github.com/openshift/openshift-docs/pull/1495

**Comment by bmcelvee** [comment]
Thanks! Closing issue.
