### ISSUE TITLE
[enterprise-3.11] Edit suggested in file dev_guide/application_health.adoc

### ISSUE THREAD

**Issue by pavelanni** [openshift/openshift-docs#14496]
### Which section(s) is the issue in?

The link to kubernetes.io at the bottom of the page is not working.

### What needs fixing?

Change the link to https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/

**Comment by jboxman** [comment]
@pavelanni thanks for reporting this!
