### ISSUE TITLE
"oc get images" isn't mentioned anywhere

### ISSUE THREAD

**Issue by mrosic** [openshift/openshift-docs#1449]
This is an incredibly simple, beautiful and useful command but is isn't mentioned anywhere. Please mention this command in the docs somewhere.

For example here:
https://docs.openshift.org/latest/architecture/infrastructure_components/image_registry.html
or here:
https://docs.openshift.org/latest/cli_reference/basic_cli_operations.html

**Comment by Scyta1e** [comment]
I must admit I have no idea what it's doing. I thought it was listing the images in the openshift docker-registry but if the registry is not running the command still returns the list. Is it the list of active images being referenced within the cluster?

**Comment by ahardin-rh** [comment]
Thanks! We document `oc get`, but could do more to explain use cases for `oc get images`. I created this bug to track the doc improvements: https://bugzilla.redhat.com/show_bug.cgi?id=1469818
