### ISSUE TITLE
[enterprise-3.9] Improve cert generation documentation to include DNS

### ISSUE THREAD

**Issue by hexfusion** [openshift/openshift-docs#14536]
### Which section(s) is the issue in?

admin_guide/assembly_restoring-cluster.html#manually-adding-etcd-host_admin-restore-cluster

### What needs fixing?

We outline ENV variables to generate new certs but the example only shows defining `IP:` in SAN. Most clusters will also use `DNS:`. We should adjust the example to include the DNS usage.

existing

```
export NEW_ETCD_HOSTNAME="*etcd0.example.com*"
export NEW_ETCD_IP="192.168.55.21"

export CN=$NEW_ETCD_HOSTNAME
export SAN="IP:${NEW_ETCD_IP}"
export PREFIX="/etc/etcd/generated_certs/etcd-$CN/"
export OPENSSLCFG="/etc/etcd/ca/openssl.cnf"
```

proposed 

```
export NEW_ETCD_HOSTNAME="*etcd0.example.com*"
export NEW_ETCD_IP="192.168.55.21"

export CN=$NEW_ETCD_HOSTNAME
export SAN="IP:${NEW_ETCD_IP}, DNS:${NEW_ETCD_HOSTNAME}"
export PREFIX="/etc/etcd/generated_certs/etcd-$CN/"
export OPENSSLCFG="/etc/etcd/ca/openssl.cnf"
```

/assign

**Comment by kalexand-rh** [comment]
We merged this change, so I'm closing the issue. Thanks @hexfusion!
