### ISSUE TITLE
Wrong file path in "Creating Image Streams for OpenShift Images"

### ISSUE THREAD

**Issue by tpoitras** [openshift/openshift-docs#1454]
https://docs.openshift.com/enterprise/3.1/install_config/install/first_steps.html#creating-image-streams-for-openshift-images

This path is wrong:
oc create -f \
    openshift-ansible/roles/openshift_examples/files/examples/image-streams/image-streams-rhel7.json \
    -n openshift

The file path is correct up to here:

openshift-ansible/roles/openshift_examples/files/examples/

But then it diverges into directories:

v1.0
v1.1

The rest of the file path is correct. I'm unclear about what the versions indicate, or what their numbers correspond with.

**Comment by nak3** [comment]
`v1.0` and `v1.1` are from origin(upstream project)'s version.

  https://github.com/openshift/origin/releases

`OSE v3.1` is apparently based on `v1.1`, however I need the confirmation from engineer team.

**Comment by adellape** [comment]
For OSE, we should probably show the full paths for all six of those `oc create` commands anyway, e.g.:

```
/usr/share/ansible/openshift-ansible/roles/openshift_examples/files/examples/v1.1/image-streams/image-streams-centos7.json
/usr/share/ansible/openshift-ansible/roles/openshift_examples/files/examples/v1.1/image-streams/image-streams-rhel7.json
```

**Comment by tnguyen-rh** [comment]
In the past, i changed some docs to convert shell var references (e.g., `$KUBECONFIG`) to absolute filenames.  I think this is a good strategy when there are no (or few) repetitions and the filenames are (relatively) short.  With longer filenames, and especially those repeated often, i think it would increase readability and also reproducibility (for cut-and-paste) by introducing shell var references for the common *directory* part of the filename.

In practical terms, i would suggest adding a blurb conceptually defining a shell var (say `IMAGESTREAMDIR`), and then using that in the discussion and the example code blocks (e.g., `$IMAGESTREAMDIR/image-streams-rhel7.json`).  This intro blurb would also be a good place to discuss (or link to) info on `v1.0` vs `v1.1`.

**Comment by adellape** [comment]
@tnguyen-rh :+1:

**Comment by tpoitras** [comment]
@tnguyen-rh 
Clever, I like that idea! :+1: :dart:

**Comment by adellape** [comment]
Just came across https://github.com/openshift/openshift-docs/pull/1261 and reminded me that the paths actually were updated in Dec for Origin, but I added a "to_followup" label on it so that we could differentiate between Origin and OSE (basically what I said in https://github.com/openshift/openshift-docs/issues/1454#issuecomment-173228118 yesterday). But then I never did the follow-up...

Either way, it should still be updated and conditionals used to show different paths for Origin vs OSE.

**Comment by ahardin-rh** [comment]
Closing this oldie
