### ISSUE TITLE
Command "systemctl restart openshift-master" changed to "systemctl restart atomic-openshift-master"

### ISSUE THREAD

**Issue by tpoitras** [openshift/openshift-docs#1455]
Fix here:

https://docs.openshift.com/enterprise/3.0/admin_guide/configuring_authentication.html#RequestHeaderIdentityProvider

And search for anywhere else this command is included.

**Comment by nak3** [comment]
Your doc is for `3.0`. Please refer `3.1`'s doc from here:

https://docs.openshift.com/enterprise/3.1/install_config/configuring_authentication.html#RequestHeaderIdentityProvider

Until OSE v3.0, the service name was `openshift-master`, but it has been changed to `atomic-openshift-master` after 3.1 release.

**Comment by adellape** [comment]
@tpoitras Yeah, as @nak3 mentions, those services (e.g., openshift-master and openshift-node) should stick w/ that older name for the 3.0 docs.

**Comment by tpoitras** [comment]
Ah dang. Must have chose the wrong set of docs by accident, apologies!

**Comment by tpoitras** [comment]
Closing.
