### ISSUE TITLE
[enterprise-4.1] Edit suggested in file nodes/scheduling/nodes-scheduler-default.adoc

### ISSUE THREAD

**Issue by sunilcio** [openshift/openshift-docs#14564]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.1/nodes/scheduling/nodes-scheduler-default.html#nodes-scheduler-default-creating_nodes-scheduler-default

### What needs fixing?

In step 3, it is specified to edit scheduler.yaml file installed by default.

I see scheduler named 'cluster' is already present in cluster and there would be no scheduler.yaml file.
I guess this statement meant to say that edit existing scheduler named 'cluster' to refer to newly created ConfigMap 'scheduler-policy'?

If this is the case, we need to modify step 3 and then I guess we do not need step 4?

**Comment by vikram-redhat** [comment]
@mburke5678  - can you take a look at this?

**Comment by mburke5678** [comment]
@vikram-redhat Where is the scheduler named 'cluster'? I am not seeing it or am looking in the wrong place. But, I am using an older version of the install (Dev Preview).
I just stood up a new cluster:
```
mburke@mburke ~ $ oc edit Scheduler cluster  --all-namespaces
Error from server (NotFound): schedulers.config.openshift.io "cluster" not found
mburke@mburke ~ $ oc get Schdulers --all-namespaces
error: the server doesn't have a resource type "Schdulers"
mburke@mburke ~ $ vi scheduler.yaml
mburke@mburke ~ $ oc create -f scheduler.yaml
scheduler.config.openshift.io/cluster created
mburke@mburke ~ $ oc get Scheduler cluster
NAME      AGE
cluster   50s
```

**Comment by sunilcio** [comment]
@mburke5678 this was introduced recently and probably not present in the Dev Preview cluster you setup. Could you please check on recent build? 

Below output from nightly build:

$ oc version --short
Client Version: v4.1.0-201904140051+4f38681-dirty
Server Version: v1.13.4+48de222

$ oc get clusterversion
NAME      VERSION                             AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.1.0-0.nightly-2019-05-01-002148   True        False         27h     Cluster version is 4.1.0-0.nightly-2019-05-01-002148

$ oc get scheduler
NAME      AGE
cluster   27h

$ oc get scheduler cluster -o yaml
apiVersion: config.openshift.io/v1
kind: Scheduler
metadata:
  annotations:
    release.openshift.io/create-only: "true"
  creationTimestamp: "2019-05-01T05:25:22Z"
  generation: 1
  name: cluster
  resourceVersion: "1632"
  selfLink: /apis/config.openshift.io/v1/schedulers/cluster
  uid: 845e554a-6bd1-11e9-a69f-06ceab75fb1a
spec: {}

**Comment by mburke5678** [comment]
Closing in favor of https://github.com/openshift/openshift-docs/pull/14676
