### ISSUE TITLE
[enterprise-4.1] Edit suggested in file nodes/clusters/nodes-cluster-disabling-features.adoc

### ISSUE THREAD

**Issue by sunilcio** [openshift/openshift-docs#14565]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.1/nodes/clusters/nodes-cluster-disabling-features.html

### What needs fixing?

This doc section only explains how to enable or disable featureSet 'TechPreviewNoUpgrade'.
Can we also include example to enable or disable individual feature gate from below list?

https://github.com/openshift/openshift-docs/blob/enterprise-4.1/modules/nodes-cluster-disabling-features-list.adoc

Also in current 4.1 doc, I do not see above feature gate list included. Can we add a link to above list in this section of doc?

**Comment by markmc** [comment]
It looks like enabling or disabling individual feature gates is not supported. See

https://github.com/openshift/openshift-docs/pull/14293#discussion_r272370455
https://github.com/openshift/api/pull/211

**Comment by sunilcio** [comment]
Hi Mark,

Thank for checking. I am confused by this.

With 'featureSet: TechPreviewNoUpgrade', it will either enable or disable below tech preview features.

CSIBlockVolume
ExperimentalCriticalPodAnnotation
RotateKubeletServerCertificate
SupportPodPidsLimit

And the available options are 'Default' or 'TechPreviewNoUpgrade'.
Suppose if user want to enable CPUCFSQuotaPeriod from below list which is disabled by default, how can we achieve it?

https://github.com/openshift/openshift-docs/blob/enterprise-4.1/modules/nodes-cluster-disabling-features-list.adoc

**Comment by sunilcio** [comment]
Okay, I misread your comment. So it is either the default feature set or TechPreviewNoUpgrade.
I will add a comment in 14293 if there is already plan to enable or disable individual feature.

**Comment by vikram-redhat** [comment]
@sunilcio ok to close this?

**Comment by sunilcio** [comment]
@vikram-redhat yes, ok to close. Thank you.
