### ISSUE TITLE
[enterprise-4.1] Edit suggested in file nodes/nodes/nodes-nodes-working.adoc

### ISSUE THREAD

**Issue by sunilcio** [openshift/openshift-docs#14626]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.1/nodes/nodes/nodes-nodes-working.html

### What needs fixing?

I do not see docs section on how to set seccomp profile as it was available in 3.x [1]

[1] https://docs.openshift.com/container-platform/3.11/admin_guide/seccomp.html#seccomp-configuring-openshift-with-custom-seccomp

Also I see there is no kubelet configurable option to set this [2], is my understanding correct?
[2] https://github.com/kubernetes/kubelet/blob/release-1.13/config/v1beta1/types.go

**Comment by vikram-redhat** [comment]
Tracking: https://bugzilla.redhat.com/show_bug.cgi?id=1704996

**Comment by mburke5678** [comment]
Per [Seth Jennings in slack](https://coreos.slack.com/archives/GBF4GNEFM/p1556743576104600):

> 
`--seccomp-profile-root` is not settable via the `KubeletConfguration` and thus not configurable in 4.1
