### ISSUE TITLE
Make NTP (or other timekeeping) a prerequisite

### ISSUE THREAD

**Issue by rwehner** [openshift/openshift-docs#1470]
While synchronized time on a cluster may be common knowledge, I think it'd still be helpful to people like me who forget this to mention that this is a prerequisite for all cluster nodes on the [prerequisites page](https://docs.openshift.org/latest/install_config/install/prerequisites.html).

When any nodes are out of sync the ansible installation will fail and you'll get errors like this in the logs of `origin-node.service`:

```
E0122 05:41:53.690848    2022 event.go:207] Unable to write event: 'Post https://master1.example.com:8443/api/v1/namespaces/default/events: x509: certificate has expired or is not yet valid' (may retry after sleeping)
```

**Comment by mburke5678** [comment]
NTP is currently a requisite 3.3 and forward. Closing
https://docs.openshift.org/latest/install_config/install/prerequisites.html#prereq-NTP
