### ISSUE TITLE
[enterprise-3.11] Edit suggested in file admin_guide/disabling_features.adoc

### ISSUE THREAD

**Issue by apolymen** [openshift/openshift-docs#14730]
### Which section(s) is the issue in?

In introduction, after the first example.

### What needs fixing?

An additional example is needed explaining how to specify multiple feature gates in one, comma-delimited line.
This is included in OKD documentation (https://docs.okd.io/latest/admin_guide/disabling_features.html) but not in OCP 3.10 and 3.11

**Comment by mburke5678** [comment]
@apolymen Thanks for pointing this out. It appears I missed cherrypicking the PR that added disabling feature gates on a comma-delimited line. I CP'd the PR to OCP 3.11. We are no longer updating the 3.10 docs.

https://github.com/openshift/openshift-docs/pull/14347
