### ISSUE TITLE
[enterprise-4.1] Edit suggested in file architecture/architecture-topology.adoc

### ISSUE THREAD

**Issue by dgangaia** [openshift/openshift-docs#14750]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.1/architecture/architecture-topology.html#abstraction-layers-architecture-topology

### What needs fixing?
In the Figure 1. OpenShift Container Platform Architecture Overview the OS is mentioned as "RHEL or Atomic Host" instead it should be Redhat CoreOS (RHCOS)/RHEL CoreOS

**Comment by vikram-redhat** [comment]
Thanks @dgangaia. We are doing some new diagrams and redo of the arch docs, and this isssue will be addressed there.
