### ISSUE TITLE
[enterprise-4.1] Edit suggested in file authentication/identity_providers/configuring-github-identity-provider.adoc

### ISSUE THREAD

**Issue by cblecker** [openshift/openshift-docs#14752]
### Which section(s) is the issue in?

Registering a GitHub application

### What needs fixing?

When offering an example for the homepage URL, it should be something like:
`https://console-openshift-console.apps.example-openshift-cluster.com/`

When configuring the callback URL, it should be:
```
https://openshift-authentication-openshift-authentication.apps.<clusterDomain>/oauth2callback/<identityProviderName>/
```

example:
```
https://openshift-authentication-openshift-authentication.apps.example-openshift-cluster.com/oauth2callback/githubidp/
```

The important point is that the specific apps URL endpoint is important. Just providing the API server address isn't enough.

**Comment by vikram-redhat** [comment]
Tracking: https://bugzilla.redhat.com/show_bug.cgi?id=1707637

**Comment by zgalor** [comment]
I tested with @cben and came to similar conclusions, except it seems better to omit the `/oauth2callback/<identityProviderName>` from callback URL:

- > Enter a homepage URL, such as https://myapiserver.com:8443.
  
  This matches console URLs in openshift 3.x but in 4.0 console URL is in `console-openshift-console.apps.` subdomain and on regular port 433
  (e.g. https://console-openshift-console.apps.zgalor20may-osd.eyoh.sdev.devshift.net)

  There are many examples on this page using `myapiserver.com:8443` , but I only tested a github provider.

- > Enter the authorization callback URL, where the end of the URL contains the identity provider name, which is defined in the identityProviders stanza of the master configuration file, which you configure in the next section of this topic:
  > `<apiserver>/oauth2callback/<identityProviderName>`
  > For example:
  > `https://myapiserver.com:8443/oauth2callback/github/`

  Tested on a 4.0.0-0.alpha-2019-04-10-154442 cluster, this is wrong, leads to [redirect-uri-mismatch error](https://developer.github.com/apps/managing-oauth-apps/troubleshooting-authorization-request-errors/#redirect-uri-mismatch).  
  First, the callback needed is neither to API nor console domain - it's to `openshift-authentication-openshift-authentication.apps.` subdomain.  
  Second, the `/oauth2callback/<identityProviderName>` sub-path is automatically included in the `redirect_uri` that GitHub sends; including it in the callback URL leads to eventually redirecting the browser to `<console>/oauth2callback/<identityProviderName>`, showing a 404 error (but logged in successfully, can navigate around).  It's best to just set callback URL to the bare openshift-authentication-openshift-authentication domain (e.g.
https://openshift-authentication-openshift-authentication.apps.zgalor20may-osd.eyoh.sdev.devshift.net/), then after login the user lands on the main console page.
  (per https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#redirect-urls it's OK for redirect URL to be a sub-directory of callback URL)

cc @cben

**Comment by cblecker** [comment]
@zgalor we got this fixed up in https://github.com/openshift/openshift-docs/pull/14873
