### ISSUE TITLE
[enterprise-4.1] Edit suggested in file authentication/identity_providers/configuring-github-identity-provider.adoc

### ISSUE THREAD

**Issue by cblecker** [openshift/openshift-docs#14753]
### Which section(s) is the issue in?

Creating the Secret / Creating a ConfigMap

### What needs fixing?

The command calls it out, but the docs should be clearer that both these items should go in the `openshift-config` namespace. It could also be clearer that a configmap is only needed for the certificate bundle, and only if you're using a GitHub Enterprise install with a non-publicly trusted root.

**Comment by vikram-redhat** [comment]
Tracking: https://bugzilla.redhat.com/show_bug.cgi?id=1707637
