### ISSUE TITLE
Feature Request: Link Documentation to GitHub Pages

### ISSUE THREAD

**Issue by danielhelfand** [openshift/openshift-docs#14761]
Something that would be helpful to consider would be to attach GitHub source pages to all documentation so that users can easily report errors and contribute pull requests to address those issues. This will help put more eyes on documentation and keep information communicated to the public about using OpenShift valid and up to date. 

This would be similar to what MongoDB does with its [documentation](https://docs.mongodb.com/manual/), where you can click the edit button at the top of the page and be directly linked to the corresponding GitHub page:

![image](https://user-images.githubusercontent.com/34258252/57389141-8f499a80-7187-11e9-9822-c2815cbade23.png)

### Which section(s) is the issue in?
All documentation for OpenShift.

### What needs fixing?
It would be nice for those who find issues with the documentation to be easily able to locate the documentation source so that issues and pull requests can be opened without having to do a lot of searching.

**Comment by vikram-redhat** [comment]
@danielhelfand have you seen the Page History link at the top of each page? Next to the Suggest and edit link?

**Comment by danielhelfand** [comment]
@vikram-redhat Thank you for pointing this out. My apologies for not noticing that some docs feature this. All the documentation I have looked at so far did not feature Page History or Suggest an Edit, and it seems like a fair amount of docs are still missing these links. Not sure if there are efforts underway to include this in docs where this isn't available yet, but I think including Page History and Suggest an Edit would be very helpful.

**Comment by vikram-redhat** [comment]
Hi @danielhelfand  - Page History and Suggest an Edit are on all pages of the commercial product docs. They are not on the community (OKD) docs and there is no plan to add them there.

**Comment by danielhelfand** [comment]
@vikram-redhat Would the docs team be interested in accepting contributions to add these to the community docs, or is there reasoning for not including them in OKD?

**Comment by vikram-redhat** [comment]
Hey @danielhelfand  - adding these links for Suggest an edit and Page History in the community docs is a matter of taking the if(distro == "community docs") block out :). So it is mostly a business decision.

Having said that, note that almost all our improvements to the docs for the commercial product are first merged to our master branch, which builds the docs for the community docs first. So keep sending us those suggestions for the commercial product via these links and that will continue to improve both the community and commercial docs.

**Comment by danielhelfand** [comment]
@vikram-redhat Gotcha, I see. Thanks for being patient with me and taking the time to help me understand the process for docs.
