### ISSUE TITLE
[enterprise-4.1] Edit suggested in file registry/architecture-component-imageregistry.adoc

### ISSUE THREAD

**Issue by sbarre-esit** [openshift/openshift-docs#14765]
### Which section(s) is the issue in?

Integrated OpenShift Container Platform registry

### What needs fixing?

```
When new a new image is pushed to the registry
```

has too many `new`s in there, should be

```
When a new image is pushed to the registry
```

**Comment by vikram-redhat** [comment]
Fixed via: https://github.com/openshift/openshift-docs/commit/752cbb75378dd4f61b9285d7b8d1950f7d601960
