### ISSUE TITLE
Wrong file path for metrics-deployer template

### ISSUE THREAD

**Issue by JayKayy** [openshift/openshift-docs#1478]
is currently seen at docs.openshift.com as:
usr/share/ansible/openshift-ansible/roles/openshift_examples/files/examples/infrastructure-templates/enterprise/metrics-deployer.yaml

but is actually 

usr/share/ansible/openshift-ansible/roles/openshift_examples/files/examples/**v1.1**/infrastructure-templates/enterprise/metrics-deployer.yaml

**Comment by adellape** [comment]
@JayKayy Thanks, will get picked up in the weekly publish.

**Comment by ronsengupta** [comment]
It is even missing there /usr/share/ansible/openshift-ansible/roles/openshift_examples/files/examples/latest


drwxr-xr-x. 2 root root 4096 Mar  9 20:48 db-templates
drwxr-xr-x. 2 root root  101 Mar  9 20:48 image-streams
drwxr-xr-x. 2 root root 4096 Mar  9 20:48 quickstart-templates
drwxr-xr-x. 2 root root   66 Mar  9 20:48 xpaas-streams
drwxr-xr-x. 2 root root 8192 Mar  9 20:48 xpaas-templates
