### ISSUE TITLE
Organize the modules directory into topics (folders). 

### ISSUE THREAD

**Issue by sferich888** [openshift/openshift-docs#14836]
### Which section(s) is the issue in?
None

### What needs fixing?
The **openshift-docs/modules/** directory needs to be grouped into sections (for better organization)

For example, the following files could all be placed into an installation topic or folder, and the "installation-" preface could be removed. 

- modules/installation-clouds.adoc
-  modules/installation-dns-upi.adoc
-  modules/installation-options.adoc
-  modules/installation-overview.adoc
-  modules/installation-planning.adoc
-  modules/installation-aws-limits.adoc
-  modules/installation-aws-regions.adoc
-  modules/installation-aws-route53.adoc
-  modules/installation-customizing.adoc
-  modules/installation-network-upi.adoc
-  modules/installation-about-custom.adoc
-  modules/installation-aws-iam-user.adoc
-  modules/installation-complete-upi.adoc
-  modules/installation-initializing.adoc
-  modules/installation-base-packages.adoc
-  modules/installation-uninstall-aws.adoc
-  modules/installation-required-ports.adoc
-  modules/installation-aws-config-yaml.adoc
-  modules/installation-aws-permissions.adoc
-  modules/installation-configuring-dns.adoc
-  modules/installation-preparing-hosts.adoc
-  modules/installation-creating-aws-dns.adoc
-  modules/installation-creating-aws-vpc.adoc
-  modules/installation-generate-aws-upi.adoc
-  modules/installation-operators-config.adoc
-  modules/installation-preparing-assets.adoc
-  modules/installation-preparing-custom.adoc
-  modules/installation-requirements-upi.adoc
-  modules/installation-security-warning.adoc
-  modules/installation-upi-machines-iso.adoc
-  modules/installation-vsphere-machines.adoc
-  modules/installation-aws-upi-bootstrap.adoc
-  modules/installation-aws-upi-rhcos-ami.adoc
-  modules/installation-registering-hosts.adoc
-  modules/installation-cloudformation-dns.adoc
-  modules/installation-cloudformation-vpc.adoc
-  modules/installation-extracting-infraid.adoc
-  modules/installation-infrastructure-upi.adoc
-  modules/installation-creating-aws-worker.adoc
-  modules/installation-initializing-manual.adoc
-  modules/installation-launching-installer.adoc
-  modules/installation-obtaining-installer.adoc
-  modules/installation-provide-credentials.adoc
-  modules/installation-vsphere-config-yaml.adoc
-  modules/installation-aws-upi-installation.adoc
-  modules/installation-aws-upi-requirements.adoc
-  modules/installation-storage-requirements.adoc
-  modules/installation-cloudformation-worker.adoc
-  modules/installation-creating-aws-security.adoc
-  modules/installation-installing-bare-metal.adoc

**Comment by vikram-redhat** [comment]
We did a vote on this and the team was evenly split for now. I am going to close this issue, but @sferich888 feel free to reach out so I can go through how we can make it work for contributions from everyone.

**Comment by sferich888** [comment]
I guess the question is what is the out come that docs will be taking.

**Comment by jboxman** [comment]
@sferich888, we're going to continue using just `modules/` for now.
