### ISSUE TITLE
[enterprise-4.1] Edit suggested in file scalability_and_performance/optimizing-storage.adoc

### ISSUE THREAD

**Issue by neoncyrex** [openshift/openshift-docs#14843]
### Which section(s) is the issue in?
Available persistent storage options

### What needs fixing?
Ceph RBD was mentioned twice

**Comment by vikram-redhat** [comment]
@ahardin-rh - since this is a typo, I am not creating a bug for it.

**Comment by ahardin-rh** [comment]
Thank you! This is now addressed in https://github.com/openshift/openshift-docs/pull/14866
