### ISSUE TITLE
[enterprise-4.1] Edit suggested in file machine_management/applying-autoscaling.adoc

### ISSUE THREAD

**Issue by zvonkok** [openshift/openshift-docs#14862]
### Which section(s) is the issue in?

ClusterAutoscaler resource definition

Specify the minimum number of GPU **cores** to deploy.

### What needs fixing?

nvidia.com/gpu specifies whole GPUs not cores. 
It should be: 

Specify the minimum number of GPUs to deploy.

**Comment by ahardin-rh** [comment]
@zvonkok Thanks! This is now fixed in https://github.com/openshift/openshift-docs/pull/14864
