### ISSUE TITLE
[enterprise-3.11] nuage images 

### ISSUE THREAD

**Issue by brianredbeard** [openshift/openshift-docs#14872]
### Which section(s) is the issue in?

`architecture/topics/nuage.adoc`

### What needs fixing?
In Third Party SDN -> Nuage -> Mapping of Constructs the image `nuageopenshift_mapping.png` is missing.

**Comment by jboxman** [comment]
@brianredbeard, thanks for reporting this. I believe this is fixed now: https://docs.openshift.com/container-platform/3.11/architecture/networking/network_plugins.html#nuage-sdn
