### ISSUE TITLE
[enterprise-4.1] Edit suggested in file installing/installing_bare_metal/installing-bare-metal.adoc

### ISSUE THREAD

**Issue by SafPlusPlus** [openshift/openshift-docs#14910]
### Which section(s) is the issue in?

[Network connectivity requirements](https://docs.openshift.com/container-platform/4.1/installing/installing_bare_metal/installing-bare-metal.html#network-connectivity_installing-bare-metal)

### What needs fixing?

"During the initia boot," should be "During the initial boot,"

**Comment by vikram-redhat** [comment]
Fixed.
