### ISSUE TITLE
[enterprise-4.1] Edit suggested in file machine_management/adding-rhel-compute.adoc

### ISSUE THREAD

**Issue by SafPlusPlus** [openshift/openshift-docs#14911]
### Which section(s) is the issue in?

[System requirements for RHEL compute nodes
](https://docs.openshift.com/container-platform/4.1/machine_management/adding-rhel-compute.html#rhel-compute-requirements_adding-rhel-compute)

### What needs fixing?

Typo at
"meet the following minumum hardware specifications"
should be
"meet the following minimum hardware specifications"

**Comment by vikram-redhat** [comment]
Fixed via: https://github.com/openshift/openshift-docs/commit/7786a09d8df840c84f4e28dbfa8cd55a8a4faeb0
