### ISSUE TITLE
[enterprise-3.11] Edit suggested in file cli_reference/admin_cli_operations.adoc

### ISSUE THREAD

**Issue by DanielVaknin** [openshift/openshift-docs#14931]
### Which section(s) is the issue in?
Install CLI Operations/router

### What needs fixing?
`ocadm` instead of `oc adm`

**Comment by bergerhoffer** [comment]
Fixed with this PR: https://github.com/openshift/openshift-docs/pull/20385

**Comment by bergerhoffer** [comment]
Closing, update is live: https://docs.openshift.com/container-platform/3.11/cli_reference/admin_cli_operations.html#router
