### ISSUE TITLE
Provide PDF version for downloading

### ISSUE THREAD

**Issue by php-coder** [openshift/openshift-docs#1498]
I would like to have ability to download all documentation as PDF file to read it on reader or print it. I think this would be useful not only for me.

**Comment by mfojtik** [comment]
@nhr any clues?

**Comment by nak3** [comment]
It might be workaround, but you can use PDF/ePub format from here: https://access.redhat.com/documentation/en/openshift-enterprise/

The OpenShift's docs in `access.redhat.com` is sync from `docs.openshift.com`.

However, of course, `access.redhat.com` doesn't provide [origin's doc](https://docs.openshift.org/latest/welcome/index.html)

**Comment by nhr** [comment]
Presently @nak3 offers the best option. AsciiBinder doesn't generate PDF yet, but feel free to [open an issue](https://github.com/redhataccess/ascii_binder/issues)

**Comment by bfallonf** [comment]
Established as an asciibinder issue and not specifically a docs issue. I'll close this for now.

**Comment by php-coder** [comment]
@bfallonf Could you share a link to this issue, please?

**Comment by bfallonf** [comment]
@php-coder Was one reported? As I said, this isn't exactly a docs issue, but an asciibinder issue, and there's a workaround above. Unless I'm mistaken, tooling stuff is beyond the scope of the docs repo.

**Comment by nhr** [comment]
@php-coder - https://github.com/redhataccess/ascii_binder/issues/18

**Comment by ThomasSteinbach** [comment]
Any news on how to compile the documentation to ePub or PDF? Why does redhat provide both formats on its downloading page ( https://access.redhat.com/documentation/en-us/openshift_container_platform ) when there is no official way to compile the docs of this repo to ePub/PDF?

**Comment by nhr** [comment]
@ThomasSteinbach - single-volume output support needs to be added to AsciiBinder in order to make this possible. The feature request is here: https://github.com/redhataccess/ascii_binder/issues/108
