### ISSUE TITLE
oc output in various places is outdated

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-docs#1499]
For example in https://docs.openshift.com/enterprise/3.1/install_config/install/docker_registry.html#securing-the-registry

```
$ oc get svc docker-registry
NAME              LABELS                                    SELECTOR                  IP(S)            PORT(S)
docker-registry   docker-registry=default                   docker-registry=default   172.30.124.220   5000/TCP
```

but when I run the latest version of `oc get` (oc v1.1.1-268-g0215022-dirty)

```
$ oc get svc docker-registry
NAME              CLUSTER_IP      EXTERNAL_IP   PORT(S)    SELECTOR                  AGE
docker-registry   172.30.77.196   <none>        5000/TCP   docker-registry=default   3m
```

Not sure if this a big deal or not and how docs can keep up with such client changes. Opening this issue for discussion.

cc: @tnguyen-rh

**Comment by tnguyen-rh** [comment]
@kargakis 
It's a big deal, indeed.  Accuracy is the minimum we should aim for.  Ideally, whenever the output format of a command changes, whoever is making that change should also prepare a docs patch.  It's more a question of discipline than anything...

**Comment by kargakis** [comment]
> whoever is making that change should also prepare a docs patch

@tnguyen-rh a lot of the changes come from kubectl so this cannot be always the case.

**Comment by mburke5678** [comment]
BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1477765
