### ISSUE TITLE
[enterprise-4.1] Edit suggested in file installing/installing_vsphere/installing-vsphere.adoc

### ISSUE THREAD

**Issue by daveolker** [openshift/openshift-docs#15014]
### Which section(s) is the issue in?

Network connectivity requirements

### What needs fixing?
All the Red Hat Enterprise Linux CoreOS (RHCOS) machines require network in initramfs during boot to fetch Ignition config files from the Machine Config Server. During the **initia** boot, the machines require a DHCP server 

"initia" should be "initial"

**Comment by adityahiran** [comment]
I have made the change here: https://github.com/openshift/openshift-docs/pull/15020
