### ISSUE TITLE
Fuse Document has github references

### ISSUE THREAD

**Issue by sferich888** [openshift/openshift-docs#1502]
Most images ship templates or imagestreams with the product however fuse is pointing to a github URI. 

https://github.com/jboss-fuse/application-templates/blob/master/fis-image-streams.json

**Comment by tnguyen-rh** [comment]
@sferich888 
I'm confused.  Which line in that file is the github URI?

**Comment by adellape** [comment]
@tnguyen-rh I think he means here:

https://docs.openshift.com/enterprise/latest/using_images/xpaas_images/fuse.html#fuse-using-application-templates

**Comment by adellape** [comment]
It should be pointing (at least for OSE) to:

/usr/share/openshift/examples/xpaas-streams/fis-image-streams.json

Those example files are laid down by the Ansible-based installation.
