### ISSUE TITLE
[enterprise-4.1] Edit suggested in file nodes/nodes/nodes-nodes-opaque-resources.adoc

### ISSUE THREAD

**Issue by zvonkok** [openshift/openshift-docs#15029]
### Which section(s) is the issue in?

The complete topic about opaque integer resources.

### What needs fixing?

Extended resources are replacing opaque integer resources.

**Comment by vikram-redhat** [comment]
@mburke5678 - is this correct? If yes, can you please confirm and work on it to remove as we won't have time to do this before GA.

**Comment by mburke5678** [comment]
@vikram-redhat It appears that Extended Resources has replaced Opaque Integer Resources in the upstream. I will check with @sjenning  and the Pod team. 
@zvonkok Thank you for pointing this out. This is the upstream Kubernetes doc? 
https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#extended-resources

**Comment by vikram-redhat** [comment]
@mburke5678 looks like extended resources is in 1.14 of Kubernetes and not 1.13, which is what 4.1 is based on. I am closing this issue.

**Comment by zvonkok** [comment]
Kubernetes website and documentation repo: https://github.com/kubernetes/website

`git clone https://github.com/kubernetes/website.git`
`git checkout release-1.8`
`git grep 'Opaque Integer'`


.manage-compute-resources-container.md:**Note:** Opaque Integer Resources **will be removed in version 1.9.**
manage-compute-resources-container.md:[Extended Resources](#extended-resources) are a replacement for Opaque Integer`
manage-compute-resources-container.md:**Note:** Extended Resources replace [Opaque Integer
