### ISSUE TITLE
[enterprise-4.1] Edit suggested in file installing/installing_aws/installing-aws-account.adoc

### ISSUE THREAD

**Issue by tfriman** [openshift/openshift-docs#15109]
### Which section(s) is the issue in?

Configuring an AWS account

### What needs fixing?

JSON files containing correct AWS permissions would make configuration of the AWS account much easier.

**Comment by vikram-redhat** [comment]
Thanks for the note @tfriman. This is not something we are looking to do at the moment.

**Comment by kalexand-rh** [comment]
The intention, as stated by development, is that you should use [`AdministratorAccess` policy](https://docs.openshift.com/container-platform/4.1/installing/installing_aws/installing-aws-account.html#installation-aws-iam-user_installing-aws-account), as described in the process itself. The list of permissions is provided primarily for reference.
