### ISSUE TITLE
[enterprise-4.1] Edit suggested in file welcome/index.adoc

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-docs#15108]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.1/welcome/index.html#cluster-installation-activities

### What needs fixing?

> Choose a deployment platform: Amazon AWS is the first supported platform for OpenShift Container Platform 4.1. Other supported platforms include bare metal and vSphere.

The language "first supported platform" gives undue weight to AWS.  I would describe this more like:

> Choose a deployment platform: The installer can provision and deploy to Amazon AWS, or you may elect to deploy onto pre-provisioned infrastructure on AWS, bare metal, or vSphere.

**Comment by kalexand-rh** [comment]
@smarterclayton, will you PTAL at my proposed change? https://github.com/openshift/openshift-docs/pull/15207

I moved AWS, bare metal, and vSphere into separate list items.

@vikram-redhat, do you want a QE review on this change?/////////
