### ISSUE TITLE
[enterprise-4.1] registry/securing-exposing-registry.adoc doesn't work as documented.

### ISSUE THREAD

**Issue by praveenkumar** [openshift/openshift-docs#15113]
### Which section(s) is the issue in?

Exposing a non-secure registry manually

### What needs fixing?

As of now when you follow this section you are not able to expose the unsecured registry also the registry service is part of `openshift-image-registry` namespace but in the document it shows `default` namespace. Does this document tested or still in the progress ?

**Comment by vikram-redhat** [comment]
@bmcelvee - PTAL

**Comment by bmcelvee** [comment]
Thanks @praveenkumar and @vikram-redhat - I copied the recommendation from the Github issue and am tracking the updates in the associated BZ (https://bugzilla.redhat.com/show_bug.cgi?id=1718163). Closing the issue so we can track everything in the BZ. 

Thanks again!
