### ISSUE TITLE
[enterprise-4.1] Edit suggested in file installing/installing_aws/installing-aws-account.adoc

### ISSUE THREAD

**Issue by brahmadalei** [openshift/openshift-docs#15157]
### Which section(s) is the issue in?
Supported AWS regions for Openshift 4.1
https://docs.openshift.com/container-platform/4.1/installing/installing_aws/installing-aws-account.html

### What needs fixing?
AWS Stockholm Region is not in the list. 
Include Stockholm as a supported Region (eu-north)? 
Wondering if there are any AWS services consumed by Openshift that are not available in Stockholm region yet?

**Comment by vikram-redhat** [comment]
@xltian @jianlinliu - would we know if this is supported?

@kalexand-rh

**Comment by kalexand-rh** [comment]
@wking, will you please confirm that this list of regions is still correct: https://github.com/openshift/openshift-docs/blob/master/modules/installation-aws-regions.adoc

**Comment by wking** [comment]
Hasn't changed recently.  We can add Stockholm, etc., if/when the RHCOS folks push there (openshift/os#371).

**Comment by kalexand-rh** [comment]
@wking, thanks! Please let me know if that happens. Until then, there's no action that we can take.
I'm going to close this issue and track https://github.com/openshift/installer/issues/1814.
