### ISSUE TITLE
[enterprise-4.1] Outdated Operator Deployment instructions

### ISSUE THREAD

**Issue by dmesser** [openshift/openshift-docs#15158]
### Which section(s) is the issue in?
https://github.com/openshift/openshift-docs/blob/master/modules/managing-memcached-operator-using-olm.adoc

### What needs fixing?
The instructions to deploy an Operator generated with the SDK are mixing concepts of packaging with OLM and manual deployment of the bare manifests. We should guide using packaging with OLM. The SDK binary has a `gen-csv` subcommand for this. Instructions on how to package and test with OLM can be found [here](https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md).

**Comment by vikram-redhat** [comment]
@adellape, PTAL

**Comment by vikram-redhat** [comment]
@adellape bump.

**Comment by vikram-redhat** [comment]
@adellape were you able to look at this?

**Comment by adellape** [comment]
Working to address this along with follow-up re QE's comment in https://github.com/openshift/openshift-docs/pull/13705#issuecomment-493891428.

**Comment by adellape** [comment]
Going to let https://github.com/openshift/openshift-docs/pull/15636 stay focused on the CLI usage updates, and address these Getting Started / OLM-related updates in a separate PR, still incoming.

**Comment by vikram-redhat** [comment]
@adellape I will leave this as your third issue for this sprint (169).
