### ISSUE TITLE
v3.11: openshift_node_sdn_mtu inventory variable should be documented

### ISSUE THREAD

**Issue by oybed** [openshift/openshift-docs#15186]
### Which section(s) is the issue in?
Configuration / Installation for v3.11 

### What needs fixing?
The `openshift_node_sdn_mtu` inventory variable is not documented, but it should be. See issue https://github.com/openshift/openshift-ansible/issues/11664 for some more details.

**Comment by jboxman** [comment]
@oybed, thanks for reporting this!
