### ISSUE TITLE
explain node selectors

### ISSUE THREAD

**Issue by sosiouxme** [openshift/openshift-docs#1519]
There is basically no doc I can find on our support for node selectors.

Here are the basics for a pod:
http://kubernetes.io/v1.1/docs/user-guide/node-selection/README.html

However we need to describe how this interacts with the per-project selector (oadm new-project --node-selector=...) and the defaultNodeSelector in master config, and we really don't have anything to say about it.

**Comment by adellape** [comment]
@sosiouxme That's currently WIP here:

https://github.com/openshift/openshift-docs/pull/1490/files#diff-e27713e5f0f507233118f9edeb62ddeeR105

**Comment by bfallonf** [comment]
@sosiouxme If I'm understanding correctly, I think we're covering this info in the PR. If there's something missing, please let us know.

**Comment by bfallonf** [comment]
The above PR merged. Nodeselectors info is in the docs. I'll close this issue. If there's anything more here, let us know.
