### ISSUE TITLE
Minishift documentation not available in docs.okd.io/3.11

### ISSUE THREAD

**Issue by LalatenduMohanty** [openshift/openshift-docs#15196]
Minishift documentation which was available `docs.okd.io/latest` [1] before 4.0 release still valid and necessary for OpenShift 3.11 [2]. 

This page also needs to be fixed https://www.okd.io/minishift/

[1] https://docs.okd.io/latest/welcome/index.html
[2] https://docs.okd.io/3.11/welcome/index.html

**Comment by LalatenduMohanty** [comment]
cc @gbraad @praveenkumar

**Comment by gbraad** [comment]
I do see the assemble script here:

https://github.com/openshift/openshift-docs/blob/f264885d9aa05d8e144a414d7a4c5cb8e40e73cf/.s2i/bin/assemble#L45-L59

and the artifacts are available ...

**Comment by gbraad** [comment]
@vikram-redhat

**Comment by gbraad** [comment]
The GA for 4.1 and modifying the latest rewrite happened in: https://github.com/openshift/openshift-docs/commit/b342a1174ff08379ed0c30563c54a22971ac710a

The 3.11 branch would still have to point to the Minishift release... right?

**Comment by vikram-redhat** [comment]
That is correct. I am looking into it.

**Comment by vikram-redhat** [comment]
I have made a fix. MiniShift is now available for OKD latest: https://docs.okd.io/latest/minishift/index.html.

**Comment by wgordon17** [comment]
@vikram-redhat looks like the Minishift docs have gone missing again.

**Comment by wgordon17** [comment]
And they're back!
