### ISSUE TITLE
[enterprise-4.1] Edit suggested in file authentication/identity_providers/configuring-htpasswd-identity-provider.adoc

### ISSUE THREAD

**Issue by rbaumgar** [openshift/openshift-docs#15212]
### Which section(s) is the issue in?
no issue, please append this topic with

if you have added an admin user, you can apply the cluster admin right to this user (e.g. admin)
   
`   $ oc adm policy add-cluster-role-to-user cluster-admin admin`
   
after haveing a new cluster admin, you can safely remove the default kubeadmin user by

`   $ oc delete secret kubeadmin -n kube-system`

**Comment by vikram-redhat** [comment]
@huffmanca - PTAL

**Comment by huffmanca** [comment]
We do have a section on removing the default kubeadmin user:

> https://docs.openshift.com/container-platform/4.1/authentication/remove-kubeadmin.html

In addition, we have instructions on adding the cluster-admin role:

> https://docs.openshift.com/container-platform/4.1/authentication/using-rbac.html#creating-cluster-admin_using-rbac

Perhaps it would be better to highlight this section in a more generic manner than by placing it at the end of each IDP?

**Comment by rbaumgar** [comment]
Sorry, for some reason I did not saw the "removing the default kubeadmin".

May be it is a good place to highlight this in the Understanding identity provider configuration:

https://docs.openshift.com/container-platform/4.1/authentication/understanding-identity-provider.html

**Comment by vikram-redhat** [comment]
@huffmanca bump. Could you either close or adapt @rbaumgar's suggestion.

**Comment by huffmanca** [comment]
I created [BZ1724311](https://bugzilla.redhat.com/show_bug.cgi?id=1724311) to track this issue, and submitted [PR15608](https://github.com/openshift/openshift-docs/pull/15608) to address it. Closing this issue, as further conversation will be performed in the BZ or PR.
