### ISSUE TITLE
[enterprise-4.1] Edit suggested in file installing/installing_bare_metal/installing-bare-metal.adoc

### ISSUE THREAD

**Issue by jkantihub** [openshift/openshift-docs#15249]
### Which section(s) is the issue in?
Available platforms

### What needs fixing?
There is duplication of platform list.

"Available platforms
In OpenShift Container Platform 4.1, you can install a cluster that uses installer-provisioned infrastructure on only Amazon Web Services (AWS).

In OpenShift Container Platform 4.1, you can install a cluster that uses user-provisioned infrastructure on the following platforms:

AWS

VMware vSphere

Bare metal"

**Comment by kalexand-rh** [comment]
@jkantihub, those are different lists. The installer provisions the infrastructure on only AWS. If you create infrastructure on AWS, vSphere, or bare metal, you can install a cluster on them.
