### ISSUE TITLE
[enterprise-4.1] [need help] container engine changes

### ISSUE THREAD

**Issue by lcnsir** [openshift/openshift-docs#15273]
### Which section(s) is the issue in?

-technical-changes

### What needs fixing?

Refer to the doc https://docs.openshift.com/container-platform/4.1/release_notes/ocp-4-1-release-notes.html#ocp-4-1-notable-technical-changes

System Containers for Docker, CRI-O | - | -
-- | -- | --

The container engine is support Docker and CRI-O

but do not see the configuration about install 4.x on Docker,

Is OCP 4.x do not support Docker container engine anymore ?

Just support CRI-O ?

**Comment by kalexand-rh** [comment]
Yes. From the [architecture guide](https://docs.openshift.com/container-platform/4.1/architecture/architecture.html):
> CRI-O Container Engine is the streamlined container engine that is is developed in tandem with Kubernetes releases and provides facilities for running, stopping, and restarting containers. It fully replaces the Docker Container Engine in OpenShift Container Platform 4.1.

**Comment by kalexand-rh** [comment]
@sheriff-rh, will you check and see if there's a way to make this clearer in the release notes?

**Comment by sheriff-rh** [comment]
I think the easiest fix here is to remove the mention of `Docker` to avoid future confusion.  I've made the pull request here, and merged it. Changes will go live on the website shortly: 
https://github.com/openshift/openshift-docs/pull/15415

Please let me know if there's anything further we can change. Thanks for bringing this to our attention!
