### ISSUE TITLE
[enterprise-4.1] Edit suggested in file installing/install_config/configuring-firewall.adoc

### ISSUE THREAD

**Issue by deadh** [openshift/openshift-docs#15315]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.1/installing/install_config/configuring-firewall.html#configuring-firewall

### What needs fixing?

cert-api.cloud.redhat.com:443
api.cloud.redhat.com:443

Those two URL's do not resolve. I believe they need to be replaced with:

cert-api.access.redhat.com and api.access.redhat.com

**Comment by kalexand-rh** [comment]
You're right. This issue was also reported on a [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1718428), and I have a [PR](https://github.com/openshift/openshift-docs/pull/15279) in flight to address it. I'm going to close this issue as a duplicate.
