### ISSUE TITLE
[enterprise-4.1] Edit suggested in file installing/installing_aws/installing-aws-customizations.adoc

### ISSUE THREAD

**Issue by TinyExplosions** [openshift/openshift-docs#15334]
### Which section(s) is the issue in?
Figure #1

### What needs fixing?
Item 3 in figure reads “Manager OpenShift cluster”. It should read “Manage OpenShift cluster”.

Thank you!
X

**Comment by kalexand-rh** [comment]
Thanks! I found a correct version of the image and will swap it out.
