### ISSUE TITLE
Booleans Show up Weird on Firefox in OSE Docs

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/openshift-docs#1539]
Seen [here](https://access.redhat.com/documentation/en/openshift-enterprise/version-3.1/installation-and-configuration/#node-configuration-examples):
![screenshot from 2016-02-03 15 10 24](https://cloud.githubusercontent.com/assets/7328370/12795480/5ced8aa0-ca88-11e5-8e18-2bbc73da00e5.png)

**Comment by tnguyen-rh** [comment]
Unfortunately, this also happens for other documentation, not only OpenShift: https://access.redhat.com/documentation/en/red-hat-enterprise-linux-atomic-host/version-7/getting-started-with-containers/#pod

**Comment by mburke5678** [comment]
@stevekuznetsov @tnguyen-rh 

I think this has been fixed. The code example is different from above and renders correctly: 
3.2: Example 11.13. LDAP Sync Configuration Using Active Directory Schema: active_directory_config.yaml
https://access.redhat.com/documentation/en-us/openshift_enterprise/3.2/html/installation_and_configuration/install-config-syncing-groups-with-ldap#sync-ldap-active-directory
3.3-3.5
Example 13.13. LDAP Sync Configuration Using Active Directory Schema
https://access.redhat.com/documentation/en-us/openshift_container_platform/3.5/html/installation_and_configuration/install-config-syncing-groups-with-ldap#sync-ldap-active-directory

I am closing. Reopen, if needed.
