### ISSUE TITLE
[enterprise-3.9] Edit suggested in file release_notes/ocp_3_9_release_notes.adoc

### ISSUE THREAD

**Issue by pamoedom** [openshift/openshift-docs#15406]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/3.9/release_notes/ocp_3_9_release_notes.html#ocp-3.9.78

### What needs fixing?

The title of the section is incorrect, it says "RHBA-2019:0618 - OpenShift Container Platform 3.9.74 Bug Fix Update" when it should be "RHBA-2019:0788 - OpenShift Container Platform 3.9.78 Bug Fix Update"

**Comment by sheriff-rh** [comment]
Hello,

Thank you for bringing this to my attention! I have filed a pull request to resolve this:
https://github.com/openshift/openshift-docs/pull/15409

I'll merge it as soon as all the build checks clear. Thanks again!
Andrew

**Comment by sheriff-rh** [comment]
Changes are now merged to master and 3.9 branches and will publish shortly. I will mark this issue as resolved. Thanks again for your help!

**Comment by pamoedom** [comment]
Thanks you too for the quick turnaround.
Regards.
