### ISSUE TITLE
Advanded Installation Section missing details on adding a node

### ISSUE THREAD

**Issue by detiber** [openshift/openshift-docs#1543]
Rough steps are:
- create a new group in the inventory file call new_nodes
```
[new_nodes]
```
- create a host definition in the new_nodes group for each additional node to add to the cluster
- run playbooks/byo/openshift-cluster/scaleup.yml

A description of the process:
The scaleup playbooks will connect to the "first" master host, generate the certificates and kubeconfigs for the new nodes, the certificates are then copied over to the new nodes and the node configuration is performed only on the nodes listed in the new_nodes group.

*If* you run the playbook without specifying the new_nodes group, configuration will be run on all nodes defined in your inventory (the 'nodes' group).

We should also mention the manual node configuration steps, which are roughly described here: https://access.redhat.com/solutions/1983683

**Comment by nak3** [comment]
As one of the enterprise customers report this issue, I filed bz and update KCS.

bz:  https://bugzilla.redhat.com/show_bug.cgi?id=1304954
kcs: https://access.redhat.com/solutions/2150381

**Comment by adellape** [comment]
Thanks @detiber @nak3. Had this on my ToDo list this week; grabbing the BZ and will follow through there, should get to it early next week.
