### ISSUE TITLE
[enterprise-3.7,3.9,3.10] Edit suggested in file architecture/networking/routes.adoc

### ISSUE THREAD

**Issue by briantward** [openshift/openshift-docs#15457]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/3.7/architecture/networking/routes.html#routes-sticky-sessions

This relates to 3.7, 3.9, and 3.10.

### What needs fixing?
Remove this, as it is incorrect: 
>> The default HAProxy template implements sticky sessions using the balance source directive, which balances based on the source IP.

The defaults are explained near the bottom of the paragraph:
>> By default, sticky sessions for passthrough routes are implemented ...

Also, change this:
>> By default, sticky sessions for passthrough routes are implemented using the source load balancing strategy. The default can be changed for all passthrough routes by using the ROUTER_TCP_BALANCE_SCHEME environment variable, and for individual routes by using the haproxy.router.openshift.io/balance route specific annotation.

To this:
By default, sticky sessions for passthrough routes are implemented using the source load balancing strategy; however, roundrobin is default when there are active services with weights greater than 1 [1]. The default can be changed for all passthrough routes by using the ROUTER_LOAD_BALANCE_ALGORITHM environment variable, and for individual routes by using the haproxy.router.openshift.io/balance route specific annotation.

The variable ROUTER_TCP_BALANCE_SCHEME was removed in this code:
https://github.com/openshift/origin/blob/release-3.7/images/router/haproxy/conf/haproxy-config.template#L429-L433
Related commit:
https://github.com/openshift/origin/commit/2ed8547c7bac9d86d503bc6f1374096ffa05a31b
https://bugzilla.redhat.com/show_bug.cgi?id=1618563
But it was added back in release-3.11.

[1] https://github.com/openshift/origin/commit/a4815c6314f9df1d2ce8060216d0924181c48b6c

**Comment by briantward** [comment]
Perhaps it would be reasonable to make an exclamation statement correcting the actual wording, since it was _supposed_ to work the way originally written in the documentation, but a bug was introduced and not fixed until 3.11.  Either way works for me.

**Comment by vikram-redhat** [comment]
@jboxman - assigning this to you as the third bug/issue for you for this sprint (169).

**Comment by jboxman** [comment]
@briantward, I've updated the docs with the proposed change. Thanks!
