### ISSUE TITLE
[enterprise-4.1] Edit suggested in file logging/efk-logging-deploying.adoc

### ISSUE THREAD

**Issue by hashnao** [openshift/openshift-docs#15489]
### Which section(s) is the issue in?
Installing the Cluster Logging and Elasticsearch Operators

### What needs fixing?
It's a minor typo.
openshift-operators-red projects should be openshift-operators-redhat projects.

**Comment by vikram-redhat** [comment]
@mburke5678 PTAL.

**Comment by mburke5678** [comment]
@hashnao Thank you very much for pointing out this error. Please let me know if the change in the following PR meets your expectations and we can correct the error. 
https://github.com/openshift/openshift-docs/pull/15493
