### ISSUE TITLE
[ARO] Customer admin permissions

### ISSUE THREAD

**Issue by sabbour** [openshift/openshift-docs#15486]
### Which section(s) is the issue in?

The role names are incorrect. On ARO there is nothing called "dedicated-cluster-admin"

```
oc describe clusterrole/dedicated-cluster-admin
Error from server (NotFound): clusterroles.authorization.openshift.io "dedicated-cluster-admin" not found
```

Additionally, the permissions are not all correct. I see there is `customer-admin-cluster`, `customer-admin-project` and `customer-admin-controller` with the permissions below.

```
oc describe clusterrole/customer-admin-cluster
Name:						customer-admin-cluster
Created:					2 days ago
Labels:						azure.openshift.io/owned-by-sync-pod=true
Annotations:					<none>
Verbs						Non-Resource URLs	Resource Names	API Groups		Resources
[create delete get list patch update watch]	[]			[]		[servicecatalog.k8s.io]	[clusterservicebrokers]
```

```
oc describe clusterrole/customer-admin-project
Name:						customer-admin-project
Created:					2 days ago
Labels:						azure.openshift.io/owned-by-sync-pod=true
Annotations:					<none>
Verbs						Non-Resource URLs	Resource Names	API Groups		Resources
[create delete get list patch update watch]	[]			[]		[]			[limitranges resourcequotas]
[create delete get list patch update watch]	[]			[]		[ network.openshift.io]	[egressnetworkpolicies]
```

```
oc describe clusterrole/customer-admin-controller
Name:						customer-admin-controller
Created:					2 days ago
Labels:						azure.openshift.io/owned-by-sync-pod=true
Annotations:					<none>
Verbs						Non-Resource URLs	Resource Names	API Groups			Resources
[create delete get list patch update watch]	[]			[]		[rbac.authorization.k8s.io]	[rolebindings]
[create get list watch]				[]			[]		[]				[namespaces]
[create get update]				[]			[]		[user.openshift.io]		[groups]
```

**Comment by kalexand-rh** [comment]
@vikram-redhat, will you PTAL?

**Comment by vikram-redhat** [comment]
@patrickstrick would you or Kevin be able to confirm this?

**Comment by patrickstrick** [comment]
@jim-minter did a walk through of the docs with the writer. I would defer to him on this section.

**Comment by jim-minter** [comment]
@sabbour is right, this is a valid issue.

**Comment by vikram-redhat** [comment]
Thanks for the confirmation @jim-minter. 

@sabbour I am **_assuming_** that the correct role names should be: customer-admin-cluster, customer-admin-project and customer-admin-controller.

@adellape assigning this to you till we have a replacement for David. The page in question is: https://docs.openshift.com/aro/admin_guide/index.html but make sure to check the rest of the set for occurrences of dedicated-cluster-admin.

**Comment by adellape** [comment]
Fixed via https://github.com/openshift/openshift-docs/pull/15623.
