### ISSUE TITLE
[enterprise-4.1] Edit suggested in file authentication/managing-security-context-constraints.adoc

### ISSUE THREAD

**Issue by k-wall** [openshift/openshift-docs#15651]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.1/authentication/managing-security-context-constraints.html#security-context-constraints-about_configuring-internal-oauth

### What needs fixing?

Simple typo: "Whether a pod can run rivileged containers." misspelt privileged

**Comment by kalexand-rh** [comment]
Thanks @k-wall!!
