### ISSUE TITLE
Cert is untrusted

### ISSUE THREAD

**Issue by PixnBits** [openshift/openshift-docs#1566]
In Chrome (47.0.2526.111 64-bit), I'm getting the `NET::ERR_CERT_AUTHORITY_INVALID` error.

![image](https://cloud.githubusercontent.com/assets/3945917/12929547/8de209fe-cf30-11e5-8a42-364e60d16339.png)

**Comment by adellape** [comment]
cc @nhr

**Comment by nhr** [comment]
@stenwt I thought we fixed this?

**Comment by PixnBits** [comment]
Now working on my phone and personal laptop (both Chrome 48). Might be a v47 thing?
