### ISSUE TITLE
[enterprise-4.1] Edit suggested in file nodes/nodes/nodes-nodes-resources-configuring.adoc

### ISSUE THREAD

**Issue by ggore-rh** [openshift/openshift-docs#15667]
### Which section(s) is the issue in?
# https://docs.openshift.com/container-platform/4.1/nodes/nodes/nodes-nodes-resources-configuring.html#nodes-nodes-resources-configuring-setting_nodes-nodes-resources-configuring
  
name: set-allocatable(1) and custom-kubelet: small-pods(2) are marked 1 and 2 respectively in above section, however there is no explanation provided for the same.

### What needs fixing?
Provide explanation for following points provided in sample yaml configuration.
name: set-allocatable(1) and 
custom-kubelet: small-pods(2)

**Comment by mburke5678** [comment]
There are two call-outs in this topic with no explanation. This applies to all 4.x.

**Comment by mburke5678** [comment]
See changes in https://github.com/openshift/openshift-docs/pull/27254
