### ISSUE TITLE
Missing nodeselector and projectnodeselector docs/examples

### ISSUE THREAD

**Issue by soltysh** [openshift/openshift-docs#1570]
$subj. There are a few mentions of the topic here and there, but there's literally nothing good explaining how to use them and apply.

**Comment by adellape** [comment]
@soltysh WIP here https://github.com/openshift/openshift-docs/pull/1490.

**Comment by soltysh** [comment]
:+1:

**Comment by bfallonf** [comment]
With the above PR merged, I'll close this issue. If there's anything more needed, please let us know.
