### ISSUE TITLE
[enterprise-3.1] Edit suggested in file install_config/aggregate_logging.adoc

### ISSUE THREAD

**Issue by jpcabrales** [openshift/openshift-docs#15726]
### Which section(s) is the issue in?

Fluentd section -- misspelled Elasticsearch, lacking a "t"

### What needs fixing?

When you make changes to any part of the EFK stack, specifically Elasticsearch or Fluentd, you should first scale Elas**t**icsearch down to zero and scale Fluentd so it does not match any other nodes. Then, make the changes and scale Elas**t**icsearch and Fluentd back.

To scale Elas**t**icsearch to zero:

**Comment by mburke5678** [comment]
We no longer support or update the 3.1 docs.
