### ISSUE TITLE
[enterprise-3.11] Edit suggested in file admin_guide/high_availability.adoc

### ISSUE THREAD

**Issue by aelicieguo** [openshift/openshift-docs#15724]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/3.11/admin_guide/high_availability.html#configuring-a-highly-available-service

### What needs fixing?
"Run the geo-cache service with a replica on each of the nodes. See an example configuration for running a geo-cache service."

Then link "example configuration" leads to page404
https://raw.githubusercontent.com/openshift/openshift-docs/master/admin_guide/examples/geo-cache.json is page404
![Screenshot from 2019-07-04 11-23-51](https://user-images.githubusercontent.com/19474270/60637755-38420800-9e4e-11e9-91c0-ee7b7bd67707.png)

**Comment by jboxman** [comment]
@aelicieguo, thanks for reporting this!
