### ISSUE TITLE
[enterprise-4.1] Edit suggested in file release_notes/ocp-4-1-release-notes.adoc

### ISSUE THREAD

**Issue by geekspertise** [openshift/openshift-docs#15748]
### Which section(s) is the issue in?

Technology preview features

### What needs fixing?
 
Please remove Istio from the table. 

Istio (not in TP) is the upstream counterpart to our Red Hat OpenShift Service Mesh product (currently in TP).

Can @sheriff-rh please take a look at this?

Thanks!

**Comment by sheriff-rh** [comment]
Pull request created, will merge/cherrypick asap. Thanks @geekspertise !
