### ISSUE TITLE
[enterprise-4.1] Edit suggested in file architecture/architecture.adoc

### ISSUE THREAD

**Issue by daveolker** [openshift/openshift-docs#15798]
### Which section(s) is the issue in?

OpenShift Container Platform architecture -> DEPLOYMENT AND SCALING BENEFITS

### What needs fixing?

You can also deploy and test a new version of an application alongside the existing version. Deploy the new application version in addition to the current version. If the container passes your tests, simply deploy more new containers **and** remove the old ones. 
...
Similarly, scaling **containerized** applications is simple. OpenShift Container Platform offers a simple, standard way of scaling any containerized service. For example, if you build applications as a set of microservices rather than large, monolithic applications, you can scale the individual microservices individually to meet demand. This capability allows **you** to scale only the required services instead of the entire application, which can allow you to meet application demands while using minimal resources.

The bold-faced words above need addressing.

**Comment by jboxman** [comment]
@daveolker, thanks for reporting this!
