### ISSUE TITLE
[enterprise-4.1] Edit suggested in file welcome/oce_about.adoc

### ISSUE THREAD

**Issue by daveolker** [openshift/openshift-docs#15796]
### Which section(s) is the issue in?

Core Kubernetes and container orchestration

### What needs fixing?

OpenShift Container Engine offers full access to an enterprise-ready Kubernetes environment that is easy to install and offers an extensive compatibility test matrix with many of the **that** software elements that you might use in your data center.

Remove "that" from the above sentence.

**Comment by jboxman** [comment]
@vikram-redhat, this is in 3.x, but it shows up as for enterprise-4.1.

**Comment by vikram-redhat** [comment]
@jboxman it is in both 4.1 and 3.11.
