### ISSUE TITLE
[enterprise-3.0] Edit suggested in file architecture/core_concepts/deployments.adoc

### ISSUE THREAD

**Issue by suryaveerc** [openshift/openshift-docs#15854]
### Which section(s) is the issue in?
https://docs.openshift.com/enterprise/3.0/architecture/core_concepts/deployments.html#replication-controllers

### What needs fixing?
**Kubernetes documentation** has a dead link.
https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/replication-controller.md

**Comment by bergerhoffer** [comment]
Closing as we don't maintain the 3.0 version, and 3.11 does not have this dead link.
