### ISSUE TITLE
[enterprise-4.1] Edit suggested in file registry/securing-exposing-registry.adoc

### ISSUE THREAD

**Issue by christianh814** [openshift/openshift-docs#15863]
### Which section(s) is the issue in?

All of it

### What needs fixing?

The service is not called `podman-registry` it's called `image-registry`

**Comment by bmcelvee** [comment]
Thanks @christianh814! We are working on fixing this content in https://github.com/openshift/openshift-docs/pull/15370. It will be merged today. 

I'll go ahead and close this issue.
