### ISSUE TITLE
[enterprise-3.11] Edit suggested in file install_config/prometheus_cluster_monitoring.adoc

### ISSUE THREAD

**Issue by amej** [openshift/openshift-docs#15875]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/3.11/install_config/prometheus_cluster_monitoring.html#dead-mans-switch-pagerduty

### What needs fixing?

Replace 'DeadManSnitch' with 'DeadManSwitch'

**Comment by kalexand-rh** [comment]
@amej, will you point out the line that contains this error for me? https://github.com/openshift/openshift-docs/blame/enterprise-3.11/install_config/monitoring/configuring-alertmanager.adoc
I don't see 'DeadManSnitch', and I'm not sure which of it's variants is causing the problem.

**Comment by amej** [comment]
The issue no longer exists. Closing the issue.
