### ISSUE TITLE
DaemonSet docs is missing

### ISSUE THREAD

**Issue by soltysh** [openshift/openshift-docs#1598]
We've introduced DaemonSet in current revision of OpenShift but there's literally nothing in our docs about that feature.

**Comment by nak3** [comment]
ping @bfallonf 
I think that this request can be closed since https://bugzilla.redhat.com/show_bug.cgi?id=1337329
 https://github.com/openshift/openshift-docs/pull/2242

**Comment by bfallonf** [comment]
Good eye @nak3 . I'll close this. Thanks!
