### ISSUE TITLE
Found description "Setting up the HAProxy router to accept ingress objects" in documentation of okd but not in OpenShift Enterprise

### ISSUE THREAD

**Issue by olaf-meyer** [openshift/openshift-docs#15985]
### Which section(s) is the issue in?
I found that the okd documentation mentions how "Setting up the HAProxy router to accept ingress objects". However I couldn't find this chapter in enterprise branch (i.e enterprise 3.11). I assume that the branch "master-3" is used to create the latest okd documentation. In this file "https://github.com/openshift/openshift-docs/blame/master-3/admin_guide/managing_networking.adoc" i can find the chapter "Setting up the HAProxy router to accept ingress objects". In the enterprise branch "enterprise-3.11" in the file managing_networking.adoc the chapter is not included.

### What needs fixing?
Add chapter "Setting up the HAProxy router to accept ingress objects" in the file "managing_networking.ado" to the branch enterprise-3.11 and maybe earlier branches as well.

I couldn't find any issues or hints why this feature should not included in the enterprise version. This is why I created the issue. 

Thank you very much in advance.

**Comment by mburke5678** [comment]
@knobunc Should this section still be in the OKD docs for 3.10 and 3.11? Your comment in the PR where the topic was added seems to suggest this.
https://github.com/openshift/openshift-docs/pull/8109#issuecomment-374591363

This section does appears in `master-3` but doesn't seem to appear in any docs. Not sure why. 
If the section is no longer valid, should I remove it from master-3 to be safe?

**Comment by mburke5678** [comment]
Section replaced with [Disabling Host Name Collision Prevention For Routes and Ingress Objects](https://docs.okd.io/3.10/admin_guide/managing_networking.html#admin-guide-disabling-hostname-collision)
