### ISSUE TITLE
[enterprise-4.1] Edit suggested in file openshift_images/create-images.adoc

### ISSUE THREAD

**Issue by east4ming** [openshift/openshift-docs#16020]
### Which section(s) is the issue in?

repeat content:
SET IMAGE METADATA
Including metadata in images 

### What needs fixing?
del SET IMAGE METADATA

**Comment by bmcelvee** [comment]
Those are separate topics built on the same page. It's a bit awkward in flow, but could be detrimental if the introductory content is removed from one of the topics if they are used in separate contexts. I'm going ahead and closing this issue for now. Thank you for pointing this out so we can look into restructuring this file in the future.
