### ISSUE TITLE
documenation to outline how to make sti builds consum selfsigned certificates on git servers

### ISSUE THREAD

**Issue by ivanthelad** [openshift/openshift-docs#1603]
According to this trello board and the github issue this should be possible using secrets and defining 

ssl-cert - certificate

https://github.com/openshift/origin/pull/4387
https://trello.com/c/6EhPEbM4/569-5-add-other-auth-methods-for-accessing-private-repos
# 

In TC 4166, you will need to use a git server with a self-signed SSL cert so you can test the custom ca.crt. Github.com can be validated with a public c certificate authority.

In TC 4162, you will need to use 2 separate keys in your secret, one for username and another one for password. It would also be useful to test the case where the username is specified in the source URL like: https://[user]@github.com/blah and you only specify a password secret in your source secret.

Apart from that, the test cases look good.

**Comment by ivanthelad** [comment]
https://docs.openshift.com/enterprise/3.1/dev_guide/builds.html#source-code 
Is the documentation here, where it describie how to include a ca-cert covering the use case i describe here ? 
if yes then this can be closed

**Comment by mburke5678** [comment]
The Builds section has been significantly reorganized. The material referenced in the second comment appears to be here and seems to cover the issue. Closing. LMK otherwise if you disagree.
https://docs.openshift.com/container-platform/3.6/dev_guide/builds/build_inputs.html#source-code
