### ISSUE TITLE
[enterprise-4.1] Edit suggested in file nodes/nodes/nodes-nodes-working.adoc

### ISSUE THREAD

**Issue by blues-man** [openshift/openshift-docs#16046]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.1/nodes/nodes/nodes-nodes-working.html#nodes-nodes-working-marking_nodes-nodes-working

### What needs fixing?

```$ oc uncordon <node1>```

to

```$ oc adm uncordon <node1>```

**Comment by mburke5678** [comment]
@blues-man Thank you for pointing this out! I tested all these procedures before 4.1 came out but missed this one. I fixed the error in https://github.com/openshift/openshift-docs/pull/16089
We greatly appreciate the input!
