### ISSUE TITLE
[enterprise-3.11] Edit suggested in file admin_guide/managing_projects.adoc

### ISSUE THREAD

**Issue by aelicieguo** [openshift/openshift-docs#16045]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/3.11/admin_guide/managing_projects.html#disabling-self-provisioning

### What needs fixing?
there is no clusterrolebinding named self-provisioners. some of the commands has an 's'. it should be self-provisioner instead of self-provisioners

**Comment by kalexand-rh** [comment]
@barleyer, do you agree with the change suggested in this bug?

**Comment by barleyer** [comment]
Nope,`clusterrolebindings` have a subfix-s  corresponde to their `clusterroles`.
