### ISSUE TITLE
CNV 2.0 requires an HCO to be created

### ISSUE THREAD

**Issue by e-minguez** [openshift/openshift-docs#16078]
### Which section(s) is the issue in?
Installing Container-native Virtualization

### What needs fixing?
After deploying CNV and all the steps, it is required to create an `HyperConverged` object in the namespace the HCO watches (in this case `openshift-operators`)

```
cat << EOF | oc create -n openshift-operators -f -
apiVersion: hco.kubevirt.io/v1alpha1
kind: HyperConverged
metadata:
  name: hyperconverged-cluster
spec: {}
EOF
```

**Comment by e-minguez** [comment]
More information here https://github.com/kubevirt/hyperconverged-cluster-operator

**Comment by kalexand-rh** [comment]
@ousleyp, @aburdenthehand, PTAL?

**Comment by ousleyp** [comment]
@kalexand-rh I think this can be closed. I closed the associated BZ (https://bugzilla.redhat.com/show_bug.cgi?id=1734908) a few days ago after discussing this via email with PM.

Reasoning: We do have this step in the docs, but it's a UI step. We don't have plans to add CLI-based documentation (yet). The instructions for the UI equivalent are "Click the KubeVirt HyperConverged Cluster Operator Deployment tab and click Create HyperConverged."

**Comment by kalexand-rh** [comment]
@ousleyp, thank for the update! I think it's fair to close this issue, then. If you add the CLI-based documentation in the future, getting it to parity with the UI-based flow would include these steps.

@e-minguez, thanks for opening the issue!
