### ISSUE TITLE
[enterprise-4.1] Edit suggested in file release_notes/ocp-4-1-release-notes.adoc

### ISSUE THREAD

**Issue by geekspertise** [openshift/openshift-docs#16092]
### Which section(s) is the issue in?
Technology Preview features

### What needs fixing?
Starting with "ImageStreams with Kubernetes Resources" the table is built incorrectly. The feature names move to the OCP 3.11 column and the status information moves to the Feature column. It's unclear as to which features have what status for OCP 3.11 and OCP 4.x. 

@sheriff-rh can you look at this? @brian-avery from the Service Mesh team was kind enough to call this to my attention. Thanks!

**Comment by sheriff-rh** [comment]
Hey Elise! Thanks for bringing this to my attention.

It seems the whole table is skewed--it thinks it's supposed to have four columns! I found the error and fixed it. To confirm it, I published locally here to confirm the fix: 
http://file.rdu.redhat.com/~antaylor/080419/issue16092/issue16092/release_notes/ocp-4-1-release-notes.html#ocp-4-1-technology-preview

I created a PR here: 
https://github.com/openshift/openshift-docs/pull/16125

Thanks again Elise!

**Comment by vikram-redhat** [comment]
Fixed via: https://github.com/openshift/openshift-docs/commit/939d4f092cd03275729048b11803ad4cd7293aca#diff-8eb40e5404d0c6ad14085893c9c2f789

**Comment by sheriff-rh** [comment]
Hey Elise,
Just wanted to update that the tech preview table has been fixed and I'll close this issue at this time. Thanks again for bringing it up!
http://file.rdu.redhat.com/~antaylor/080419/issue16092/issue16092/release_notes/ocp-4-1-release-notes.html#ocp-4-1-technology-preview
