### ISSUE TITLE
Group var openshift_master_dns_port should be added to the Advanced Installation page

### ISSUE THREAD

**Issue by donovanmuller** [openshift/openshift-docs#1610]
If you already have a DNS server running on the same machine as your master(s), then you must choose a different port for SkyDNS to bind too.

You can do this via the `openshift_master_dns_port` group var as per [here](https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_master/tasks/main.yml#L57)

This should be documented briefly.

**Comment by donovanmuller** [comment]
See https://github.com/openshift/openshift-ansible/issues/1433

**Comment by donovanmuller** [comment]
Ignore reference to https://github.com/openshift/openshift-ansible/issues/1433. Nothing to see there...

**Comment by mburke5678** [comment]
@sdodson Not sure whom to address this to. 
We are going through old issues. Do you know if this is still a concern? It appears that there were changes to DNS in 3.2(?). 
Thank you for any help.

**Comment by sdodson** [comment]
The option still exists but I don't think it's worth documenting.
