### ISSUE TITLE
[enterprise-4.1] Edit suggested in file authentication/managing-security-context-constraints.adoc

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [openshift/openshift-docs#16114]
### Which section(s) is the issue in?

SCC

### What needs fixing?

We need to update the SCC section with a note:

```When hostnetwork SCC is granted and some pods allowed to land onto nodes which have instance based creds the entire cluster can be compromised, so exercise caution when allowing workloads onto master nodes```

/cc @bergerhoffer

**Comment by bergerhoffer** [comment]
Thanks @ravisantoshgudimetla. I've opened https://bugzilla.redhat.com/show_bug.cgi?id=1737533 to track this and I'll work on the update.

Closing this issue. CC @vikram-redhat
