### ISSUE TITLE
[enterprise-3.0] Edit suggested in file dev_guide/application_health.adoc

### ISSUE THREAD

**Issue by FrancescoPolitano** [openshift/openshift-docs#16122]
### Which section(s) is the issue in?
https://docs.openshift.com/enterprise/3.0/dev_guide/application_health.html#container-health-checks-using-probes

### What needs fixing?
"A probe is a Kuberbetes action that periodically performs diagnostics on a running container."
Kuberbetes should be Kubernetes

**Comment by bergerhoffer** [comment]
Closing as we don't update 3.0 version anymore, and the typo "Kuberbetes" does not exist in 3.11.
