### ISSUE TITLE
[enterprise-4.1] Update conflicting minimum of compute nodes required

### ISSUE THREAD

**Issue by kevchu3** [openshift/openshift-docs#16150]
### Which section(s) is the issue in?
`/openshift-docs/blob/master/modules/installation-vsphere-config-yaml.adoc`
`/openshift-docs/blob/master/modules/installation-vsphere-machines.adoc`

### What needs fixing?
In the `/openshift-docs/blob/master/modules/installation-vsphere-config-yaml.adoc` document, footnote 4 states: "This parameter controls the number of workers that the cluster deploys for you, so you must set the number of workers to 0 in this file. Remember that you must manually deploy at least one compute, or worker, machine in the cluster."

However, in the '/openshift-docs/blob/master/modules/installation-vsphere-machines.adoc` document, the Important footnote states: "You must create the boostrap and control plane machines at this time. Because some pods are deployed on compute machines by default, also create at least two compute machine before you install the cluster."

From the two sets of documentation is unclear whether the minimum compute machines that are required for installation is one or two.  Based on the wording, I'd gather that the minimum should be two, and thus the first footnote 4 would be updated to reference as such.

**Comment by kalexand-rh** [comment]
Thank you @kevchu3! The annotation in `/openshift-docs/blob/master/modules/installation-vsphere-config-yaml` now says: 

> You must set the value of the `replicas` parameter to `0`. This parameter
controls the number of workers that the cluster creates and manages for you,
which are functions that the cluster does not perform when you
use user-provisioned infrastructure. You must manually deploy worker
machines for the cluster to use before you finish installing {product-title}.

Do you have any concerns with the current text?

**Comment by kevchu3** [comment]
Hi @kalexand-rh, the new wording looks clear and doesn't conflict with the other reference now, thank you!
