### ISSUE TITLE
groupUIDAttribute usage on LDAP Sync section

### ISSUE THREAD

**Issue by eitchugo** [openshift/openshift-docs#16164]
### Which section(s) is the issue in?

Branch: enterprise-3.11 (mostly 3.x)
Section: install_config/syncing_groups_with_ldap.adoc

### What needs fixing?

I really don't know if this is a documentation problem or a bug into code, so I apologize. Let me know about this and I can redirect the issue to the proper place.

Documentation says this about `groupUIDAttribute` in examples:

> The attribute that uniquely identifies a group on the LDAP server. You cannot specify groupsQuery filters when using DN for groupUIDAttribute. For fine-grained filtering, use the whitelist / blacklist method.

When I use DN as the attribute, and I **don't use a filter** attribute, I get this error:

```
error: validation of LDAP sync config failed: groupsQuery.filter: Invalid value: "": invalid query filter: LDAP Result Code 201 "Filter Compile Error": ldap: filter does not start with an '('
```

And when I specify a filter, it works. This is essentially the opposite of what documentation says. 

There's also the same note about using DN and not specifying a filter in the `userUIDAttribute` and it's valid. Could this be a mistake while copying behavior from the `userUIDAttribute`?

**Comment by arprasto** [comment]
I am also facing same issue on 3.11. Did you find any solution so far for this ? I am using `filter: (x=y)` still same issue appearing for me.
