### ISSUE TITLE
Advanced installation docs don't talk about api_port or console_port

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-docs#1616]
The advanced install docs don't seem to currently describe the api_port and console_port Ansible options for moving the default ports...

I believe the options are:

openshift_master_api_port - https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_master/tasks/main.yml#L34
openshift_master_console_port - https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_master/tasks/main.yml#L39

There may be other options we wish to more fully document, or at least include some kind of link to somewhere (like the main.yml) for additional reference?

**Comment by mburke5678** [comment]
This issue being followed in:
https://bugzilla.redhat.com/show_bug.cgi?id=1436817
https://github.com/openshift/openshift-docs/pull/4988

Closing this issue.
