### ISSUE TITLE
[enterprise-3.11] Edit suggested in file install_config/aggregate_logging.adoc

### ISSUE THREAD

**Issue by ehvs** [openshift/openshift-docs#16204]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/3.10/install_config/aggregate_logging.html#aggregate-logging-ansible-variables

### What needs fixing?

Add the following ansible variables:
These inventory variables were changed in 3.10 but were not documented.

openshift_logging_curator_image=<registry_url>:5000/openshift3/logging-curator:v3.x.x
openshift_logging_fluentd_image=<registry_url>:5000/openshift3/logging-fluentd:v3.X.X
openshift_logging_kibana_image=<registry_url>:5000/openshift3/logging-kibana:v3.X.X
openshift_logging_elasticsearch_image=<registry_url>:5000/openshift3/logging-elasticsearch:v3.X.X
openshift_logging_eventrouter_image=<registry_url>:5000/openshift3/logging-eventrouter:v3.X.X
openshift_logging_kibana_proxy_image=<registry_url>:5000/openshift3/logging-auth-proxy:v3.X.X
openshift_logging_image=<registry_url>:5000/openshift3/logging-deployer:v3.X.X

Reference:
https://access.redhat.com/solutions/4102981

**Comment by mburke5678** [comment]
@ehvs Thank you for bringing this up. I hope the delay in response hasn't caused any issues. Please follow my changes in https://github.com/openshift/openshift-docs/pull/20021
