### ISSUE TITLE
[enterprise-4.1] Edit suggested in file storage/persistent-storage/persistent-storage-csi.adoc

### ISSUE THREAD

**Issue by nobusue** [openshift/openshift-docs#16405]
### Which section(s) is the issue in?
Note in headline.

### What needs fixing?
```
OpenShift Container Platform 4.1 supports version 0.4.0 of the CSI specification.
```
CSI spec v0.4.0 doesn't exist. I guess it should be v1.0.0?
https://github.com/container-storage-interface/spec/releases

**Comment by bobfuru** [comment]
Sue-san, thank you for opening this issue. You are correct. OpenShift Container Platform 4.1 supports CSI v1.0.0. and the doc has been updated.
