### ISSUE TITLE
[enterprise-3.11] Edit suggested in file admin_guide/assembly_replace-etcd-member.adoc

### ISSUE THREAD

**Issue by TomVanBerlo** [openshift/openshift-docs#16415]
### Which section(s) is the issue in?
Removing the etcd node step2: the commands used to stop the pod(s)
```
# mkdir -p /etc/origin/node/pods-stopped
# mv /etc/origin/node/pods/* /etc/origin/node/pods-stopped/
```

### What needs fixing?
the second line should only move the etcd pod:
`# mv /etc/origin/node/pods/etcd.yaml /etc/origin/node/pods-stopped/`

If you move all the pods, the apiserver and the controller are not recreated by the scaleup playbook later in the procedure.

**Comment by bergerhoffer** [comment]
@hexfusion or @retroflexer - can you confirm whether this should be updated in the docs for 3.11 [1] to only move the etcd pod file as suggested here?

[1] https://docs.openshift.com/container-platform/3.11/day_two_guide/environment_backup.html#etcd-data-backup_environment-backup
