### ISSUE TITLE
[enterprise-4.1] Edit suggested in file updating/updating-cluster.adoc

### ISSUE THREAD

**Issue by hashnao** [openshift/openshift-docs#16425]
### Which section(s) is the issue in?
About the OpenShift Container Platform update service

### What needs fixing?
It should be mentioned that master nodes and worker nodes are restarted during the upgrade process even though the control planes would have no downtime but pods running on worker nodes may not able to provide their services if pods have only one replica while a node is restarted and the pods on the node are placed on other nodes.

**Comment by wking** [comment]
> ...pods running on worker nodes may not able to provide their services if pods have only one replica...

This is generically true of any service backed by a single, bare pod; it is not update-specific.  For example, changing MachineConfig will also (currently) lead to a rolling drain/reboot across nodes in the associated pool.  And nodes can just crash/die if they have a hardware failure, network outage, etc.  Folks who want highly-available services should be using Deployments, PodDisruptionBudgets, and similar to perform robustly in the face of these stressors.  I don't think we want to go into that in update docs, but I have no problem linking to central HA docs from docs for any activity that could trigger a rollout.
