### ISSUE TITLE
[enterprise-3.11] Edit suggested in file dev_guide/cron_jobs.adoc

### ISSUE THREAD

**Issue by llidd** [openshift/openshift-docs#16421]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/3.11/dev_guide/cron_jobs.html

### What needs fixing?
Wrong API version? In dev_guide it is beta, here it is alpha:
https://docs.openshift.com/container-platform/3.11/rest_api/apis-batch/v2alpha1.CronJob.html

**Comment by jboxman** [comment]
Hi @llidd,

The API docs are outdated. We're working on updating them.
