### ISSUE TITLE
[enterprise-4.1] Edit suggested in file nodes/nodes/nodes-nodes-working.adoc

### ISSUE THREAD

**Issue by lipecki** [openshift/openshift-docs#16467]
### Which section(s) is the issue in?
Working with nodes
Understanding how to evacuate pods on nodes

### What needs fixing?
The sentence "The replication controllers create new pods on other nodes and removes the existing pods from the specified node(s)" needs congruency between noun and verb in the plural or the singular; either the controllers create and remove or a replication controller creates and removes.

**Comment by lipecki** [comment]
https://docs.openshift.com/container-platform/4.1/nodes/nodes/nodes-nodes-working.html

**Comment by mburke5678** [comment]
Thank you! 
https://github.com/openshift/openshift-docs/pull/20841
