### ISSUE TITLE
Document how to improve ansible run times

### ISSUE THREAD

**Issue by ivanthelad** [openshift/openshift-docs#1648]
If a user is executing the ose ansible scripts using a sudo user and said sudo user needs to be authenticated against against a remote server then this can lead to extremely long ansible runs. 

Documenation should outline how to improve installation speeds by using ssh pieplining feature of ansible 
https://www.ansible.com/blog/ansible-performance-tuning
http://docs.ansible.com/ansible/intro_configuration.html#pipelining

**Comment by mburke5678** [comment]
Ansible SSH pipelining was added to 3.5+ 

https://docs.openshift.com/container-platform/3.6/scaling_performance/install_practices.html#scaling-performance-install-optimization
