### ISSUE TITLE
[enterprise-4.1] List of Internet URL's required for OCP should be documented in architecture/architecture-installation.adoc

### ISSUE THREAD

**Issue by nccurry** [openshift/openshift-docs#16485]
### Which section(s) is the issue in?
OpenShift Container Platform installation overview

### What needs fixing?

Most user's of OCP4 will want to restrict traffic to the internet from the cluster hosts.
It would be helpful to have a list of required URL's OpenShift 4 needs access to so they could be appropriately whitelisted.

The current list I have is 
cloud.openshift.com
quay.io
registry.connect.redhat.com
registry.redhat.io
api.openshift.com/api/upgrades_info/v1/graph
infogw.api.openshift.com
cloudfront.net

I am not certain that is comprehensive.

**Comment by bergerhoffer** [comment]
This is documented here [1] as of 4.2. Closing, thanks!

[1] https://docs.openshift.com/container-platform/4.2/installing/install_config/configuring-firewall.html#configuring-firewall_configuring-firewall
