### ISSUE TITLE
[enterprise-4.1] vSphere dynamic provisioning should be mentioned in storage/dynamic-provisioning.adoc

### ISSUE THREAD

**Issue by nccurry** [openshift/openshift-docs#16511]
### Which section(s) is the issue in?
Available dynamic provisioning plug-ins

### What needs fixing?
vSphere dynamic storage needs to be mentioned.

**Comment by bobfuru** [comment]
This was addressed in https://github.com/openshift/openshift-docs/pull/17078. vSphere is mentioned in the dynamic provisioning plug-ins now and there is also a vSphere object definition example. Closing issue.
