### ISSUE TITLE
[enterprise-3.11] Edit suggested in file install_config/master_node_configuration.adoc

### ISSUE THREAD

**Issue by MikeTomlin19** [openshift/openshift-docs#16535]
### Which section(s) is the issue in?

Basic Audit

### What needs fixing?

Change the last word of this sentence from "file" to "directory"

"Because the OpenShift Container Platform master API now runs as static pod, you must define the auditFilePath location in the /var/lib/origin or /etc/origin/master/ file."
--

**Comment by bergerhoffer** [comment]
Closing, updates are live: https://docs.openshift.com/container-platform/3.11/install_config/master_node_configuration.html#master-node-config-audit-config
