### ISSUE TITLE
Fix metrics documentation to point to a valid template file

### ISSUE THREAD

**Issue by mwringe** [openshift/openshift-docs#1656]
A recent update removed the template for deploying metrics (https://github.com/openshift/openshift-docs/commit/7d78e65248af96fe3469e199a3f9dca5b978d9e9)

While this is good in practice, we don't need to have that template listed there, the docs now point to a file which is not guaranteed to actually be on the users system. This means anyone who has installed OpenShift directly will not be able to install metrics following those direction.

**Comment by bfallonf** [comment]
@mwringe So would leaving the template in, but conditionalizing it for Origin readers work here? Seems that no matter what we do there a different method for it that makes it irrelevant...

**Comment by mwringe** [comment]
@bfallonf a note that if you didn't install via the installer the metrics configuration file can be found at https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_examples/files/examples/v1.1/infrastructure-templates/origin/metrics-deployer.yaml would be very helpful. As it is right now, if I installed directly from the tar, I would have no idea where to get that template from

**Comment by adellape** [comment]
@bfallonf Agree w/ @mwringe, conditionalized for Origin.

**Comment by bfallonf** [comment]
Created #1662 .

I'll close this issue and move the conversation to there.
