### ISSUE TITLE
Add some document for how to check OCP kubelet log

### ISSUE THREAD

**Issue by gyliu513** [openshift/openshift-docs#16651]
In the OCP doc section https://docs.openshift.com/container-platform/4.1/logging/efk-logging.html , there is no document for how to check log of kubelet, but kubelet is very important for cluster admin if some nodes goes done or some pods goes failure, where can I get some document for debug kubelet and check its logs with OCP?

**Comment by mburke5678** [comment]
@gyliu513 Please let me know if these topics help. 

Viewing node audit logs
https://docs.openshift.com/container-platform/4.3/nodes/nodes/nodes-nodes-audit-log.html

Viewing system event information in an OpenShift Container Platform cluster
https://docs.openshift.com/container-platform/4.3/nodes/clusters/nodes-containers-events.html
