### ISSUE TITLE
[enterprise-4.1] Edit suggested in file authentication/identity_providers/configuring-google-identity-provider.adoc

### ISSUE THREAD

**Issue by liusongdu** [openshift/openshift-docs#16661]
### Which section(s) is the issue in?
As it is mentioned at the front of this chapter, it says "Using Google as an identity provider requires users to get a token using <master>/oauth/token/request to use with command-line tools", but for the test part, it suggest to use oc login -u, which, as I understand, uses local user pool. So should it be corrected from below paragraph:

_Adding an identity provider to your clusters
Procedure
Log in to the cluster as a user from your identity provider, entering the password when prompted.
$ oc login -u <username>_

### What needs fixing?
Should above paragraph be modified to below?
_Adding an identity provider to your clusters
Procedure
Log in to the cluster using the token get.
$ oc login --token=******_

**Comment by bergerhoffer** [comment]
Closing as this was recently updated to use a token for the login: https://docs.openshift.com/container-platform/4.1/authentication/identity_providers/configuring-google-identity-provider.html
