### ISSUE TITLE
[enterprise-4.2] Edit suggested in file machine_management/adding-rhel-compute.adoc

### ISSUE THREAD

**Issue by therevoman** [openshift/openshift-docs#16693]
### Which section(s) is the issue in?
Repositories needed

### What needs fixing?
ansible-2.7 needs to change to ansible-2.8
also, the ocp repository needs to change from 4.1 to 4.2

**Comment by kalexand-rh** [comment]
Thank you @therevoman! I bumped the ocp version earlier this week, but I'm fixing the ansible version now.
