### ISSUE TITLE
[enterprise-4.1] Edit suggested in file installing/installing_vsphere/installing-vsphere.adoc

### ISSUE THREAD

**Issue by itewk** [openshift/openshift-docs#16728]
### Which section(s) is the issue in?
The title

### What needs fixing?
For AWS the page titles are:
* `Installing on AWS`
* `Installing on user-provisoned AWS`

which map to IPI and UPI respectivly.

The VMware page title is `Installing on vSphere` so following the same pattern the logical assumption is that that is IPI. But then after closer inspection is actually UPI.

Therefor the title of this page should be `Installing on user-provisioned vSphere`

Or really to make everything more clear, i think there should just be two different sections of the installing doc.

```
|- Installing
  | - User Provisioned Infrastructure (UPI)
    |- AWS
    |- vSphere
    |- bare metal
  | - Installer Provisioned Infrastructure (IPI)
    |- AWS
```

That would be the most clear.

**Comment by vikram-redhat** [comment]
Tracking via: https://bugzilla.redhat.com/show_bug.cgi?id=1753211
