### ISSUE TITLE
[enterprise-4.1] Edit suggested in file storage/dynamic-provisioning.adoc

### ISSUE THREAD

**Issue by itewk** [openshift/openshift-docs#16729]
### Which section(s) is the issue in?
This doesn't list VMware vsphere-volume as an option

### What needs fixing?
According to https://docs.openshift.com/container-platform/4.1/installing/installing_vsphere/installing-vsphere.html when doing UPI for VMware vSphere it will set up dynamic storage via the vSphere api. But that option isn't listed here as one of the supported dynamic storage provider options, which is inconsistent and confusing.

**Comment by kalexand-rh** [comment]
@huffmanca, can we talk about this one?

**Comment by kalexand-rh** [comment]
@itewk, it looks like this issue was fixed on https://github.com/openshift/openshift-docs/pull/17078. Will you please check again and either close this issue or post an update?

**Comment by itewk** [comment]
@kalexand-rh looks great. thank you.
