### ISSUE TITLE
[enterprise-3.11] Edit suggested in file install_config/persistent_storage/pod_security_context.adoc

### ISSUE THREAD

**Issue by r2d2rnd** [openshift/openshift-docs#16753]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/3.11/install_config/persistent_storage/pod_security_context.html#overview

### What needs fixing?

The documentation is referring to the next guide: "WordPress and MySQL using NFS" linking to this [0]. This link is broken and if I go to OpenShift examples [1], I can't find a WordPress example.

[0] https://github.com/openshift/origin/tree/master/examples/wordpress
[1] https://github.com/openshift/origin/tree/release-3.11/examples

**Comment by bobfuru** [comment]
Fixed in https://github.com/openshift/openshift-docs/pull/25928. Thank you @r2d2rnd!
