### ISSUE TITLE
route doc for the web console needs an update

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-docs#1684]
https://docs.openshift.org/latest/dev_guide/routes.html#creating-routes

"In the web console, they are displayed but there is not yet a method to create them."

@spadgett @jwforres

**Comment by mburke5678** [comment]
@kargakis 
I believe this was remedied in the 3.2+ docs. It is now:
"You can create unsecured and secured routes routes using the web console or the CLI."
https://docs.openshift.com/enterprise/3.2/dev_guide/routes.html

Please let me know if this does not address your concerns and we can re-open.
