### ISSUE TITLE
[enterprise-3.11] Edit suggested in file rest_api/index.adoc

### ISSUE THREAD

**Issue by r2d2rnd** [openshift/openshift-docs#16873]
### Which section(s) is the issue in?

Session Tokens [0]

### What needs fixing?

In this section, we can read the next command:

$ oc whoami --token
dIAo76N-W-GXK3S_w_KsC6DmH3MzP79zq7jbMQvCOUo

The --token doesn't exist. It should be --show-token or -t.

$ oc whoami --show-token
or
$ oc whoami -t

[0] https://docs.openshift.com/container-platform/3.11/rest_api/index.html#rest-api-session-tokens

**Comment by jboxman** [comment]
@r2d2rnd, thanks for reporting this! It is now fixed.
