### ISSUE TITLE
Quota doc references "Kubernetes compute units"

### ISSUE THREAD

**Issue by spadgett** [openshift/openshift-docs#1687]
https://docs.openshift.org/latest/dev_guide/quota.html#sample-resource-quota-file

The sample quota callout (3) talks about "Kubernetes compute units." Shouldn't this just be "cores"?

/cc @derekwaynecarr

**Comment by derekwaynecarr** [comment]
@spadgett historically, it was called "Kubernetes compute units" to reserve our future ability to normalize the meaning of a core, since not all cores are equal in a heterogeneous cluster.  Right now, we do not have a conversion factor, so its really "a random core on a node".

**Comment by mburke5678** [comment]
@spadgett @derekwaynecarr 
I cannot find the phrase "Kubernetes compute units" in the current docs. It appears that the quota.html topic was re-worked for 3.2 into "Quotas and Limit Ranges". Perhaps the phrase was removed at that time. 
Please re-open if I am incorrect.
