### ISSUE TITLE
[enterprise-4.2] Update to use "master": "ens5" in YAML configuration file

### ISSUE THREAD

**Issue by weliang1** [openshift/openshift-docs#16886]
### Which section(s) is the issue in?
multiple networks

### What needs fixing?
YAML configures use "master": "eth1"
But output displays use "master": "ens5"

Better to update YAML for use "master": "ens5" which is the correct interface name from node:
[root@dhcp-41-193 FILE]# oc debug node/ip-10-0-56-206
Starting pod/ip-10-0-56-206-debug ...
To use host binaries, run `chroot /host`
Pod IP: 10.0.56.206
If you don't see a command prompt, try pressing enter.
sh-4.2# chroot /host
sh-4.4# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens5: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc mq state UP group default qlen 1000
    link/ether 02:0e:2c:9b:62:c4 brd ff:ff:ff:ff:ff:ff
    inet 10.0.56.206/20 brd 10.0.63.255 scope global dynamic noprefixroute ens5
       valid_lft 1953sec preferred_lft 1953sec
    inet6 fe80::e:2cff:fe9b:62c4/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever

**Comment by jboxman** [comment]
@weliang1, do you know which page this change applies to? Thanks.

**Comment by jboxman** [comment]
I can only find a reference to `ens5` in `modules/nw-multus-edit-network.adoc`, but I can't find any associated `eth1` reference in the assembly.
