### ISSUE TITLE
"Disabling feature" article misinforms of possibility in 3.11

### ISSUE THREAD

**Issue by byako** [openshift/openshift-docs#16889]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/3.11/admin_guide/disabling_features.html

### What needs fixing?
Article says:"If you disable a feature that appears in the web console, you might see that feature, but no objects are listed. For example, if you disable builds, you can see the Builds tab in the web console, but there are no builds present.

If you attempt to use commands associated with a disabled feature, such as oc start-build, OpenShift Container Platform displays an error."

Disabling builds? There is no evidence anywhere that this is possible to disable builds, neither there is any mentioning how to achieve this - the table in the end of the article has no notion of build. Likewise in Origin sources I didn't find any evidence of FeatureGate defined with name anything close to *build*. Please either provide reference and example how to disable builds, or change it to not mention disabling builds, because in my case I need exactly this, and it seems impossible at the moment for Openshift Enterprise 3.11

**Comment by mburke5678** [comment]
I am removing the example from the docs for now to avoid further confusion.
If you are still looking for a way to disable builds, can I ask you to put in another issue specific to that? I reached out to the developer who suggested I add builds as an example as to whether you can disable builds using a feature gate or not. 
Thanks for the suggestion!!
