### ISSUE TITLE
[enterprise-3.11] Edit suggested in file day_two_guide/environment_health_checks.adoc

### ISSUE THREAD

**Issue by annelson-rh** [openshift/openshift-docs#16897]
### Which section(s) is the issue in?

Creating alerts using Prometheus

### What needs fixing?

link "Prometheus on OpenShift Container Platform section in the Installation and configuration guide" points to metrics installation instead of prometheus config.

**Comment by bergerhoffer** [comment]
Updates are live: https://docs.openshift.com/container-platform/3.11/day_two_guide/environment_health_checks.html#day-two-guide-creating-alerts-using-prometheus

Closing this issue.
