### ISSUE TITLE
Update the outputs for "oc get svc -n <myproject>"

### ISSUE THREAD

**Issue by weliang1** [openshift/openshift-docs#16893]
### Which section(s) is the issue in?
Configuring ingress cluster traffic using a load balancer

### What needs fixing?
The outputs from two commands of "oc get svc -n openshift-ingress" are two default svc from project openshift-ingress, they are not the new created svc under project <myproject>.

Need to update to have the outputs of "oc get svc -n <myproject>" to reflect what a new svc is created.

**Comment by mburke5678** [comment]
@weliang1 Thank you for pointing this out. I think there was a copy and paste error in the initial PR. I am working on a fix here: https://github.com/openshift/openshift-docs/pull/20837
