### ISSUE TITLE
Add the steps of assigning a nodeport for using a NodePort

### ISSUE THREAD

**Issue by weliang1** [openshift/openshift-docs#16901]
### Which section(s) is the issue in?
Configuring ingress cluster traffic using a NodePort

### What needs fixing?
Please reference v3.11 doc: https://docs.openshift.com/container-platform/3.11/dev_guide/expose_service/expose_internal_ip_nodeport.html, add the steps of "Edit the service definition to specify spec.type:NodePort" in v4.2 doc.

**Comment by jboxman** [comment]
Fixed in https://github.com/openshift/openshift-docs/pull/18368.
