### ISSUE TITLE
[enterprise-3.11] Edit suggested in file rest_api/oapi/v1.DeploymentConfig.adoc

### ISSUE THREAD

**Issue by TimMurnaghan** [openshift/openshift-docs#16931]
### Which section(s) is the issue in?
The API YAML

### What needs fixing?
Having a >900 line YAML sucks pretty badly. But, given that we have to document the API we have we need to make it bearable. I've tried to copy the yaml into a file so that I can correctly capture the schema - but it fails as invalid around line 345. I don't know if it's a bad original YAML or a cut and paste error. I suggest giving us an acutal file download of the yaml so that I can eliminate one of the possibilitiles.

As a longer term goal - work on the YAML tools to product some usable API documentation which shows the structure (maybe we can annotate it with the paths so that we can see the nesting?)

**Comment by jboxman** [comment]
@TimMurnaghan, I agree. The current plan is to provide API docs similar to what Kubenetes offers, and then expand upon it.
