### ISSUE TITLE
[enterprise-4.5] Route specific ip whitelist documentation missing in file networking/routes/route-configuration.adoc

### ISSUE THREAD

**Issue by nccurry** [openshift/openshift-docs#16954]
### Which section(s) is the issue in?
Entire section is missing

### What needs fixing?

In the 3.11 documentation, there is a section called [Route-specific IP Whitelists](https://docs.openshift.com/container-platform/3.11/architecture/networking/routes.html#whitelist) that documents how to annotate the HAProxy router to whitelist particular IP's.

This section is missing from the 4.X documentation.

**Comment by jboxman** [comment]
@nccurry, I've created a PR to rescue this content: https://github.com/openshift/openshift-docs/pull/26631.
