### ISSUE TITLE
[enterprise-4.1] Edit suggested in file networking/configuring-ingress-cluster-traffic/configuring-ingress-cluster-traffic-service-external-ip.adoc

### ISSUE THREAD

**Issue by gnu300** [openshift/openshift-docs#16991]
### Which section(s) is the issue in?
In the documentation for OpenShift 4.1 there is no guidance [1] for configuring the External-IP for a Service. Furthermore there is no distinction between RHCOS and RHEL compute nodes. Under RHCOS there is no supported path for configuring an additional IP or interface [2].

[1] https://docs.openshift.com/container-platform/4.1/networking/configuring-ingress-cluster-traffic/configuring-ingress-cluster-traffic-service-external-ip.html#nw-creating-project-and-service_configuring-ingress-cluster-traffic-service-external-ip
[2] https://docs.openshift.com/container-platform/4.1/networking/configuring-ingress-cluster-traffic/configuring-ingress-cluster-traffic-service-external-ip.html#nw-service-external-ip_configuring-ingress-cluster-traffic-service-external-ip

### What needs fixing?
It seems the documentation is aimed to Cloud-Provider installs because there the External-IP is automatically assigned. For Bare-Metal installs the External-IP needs to be patched with:

`oc patch svc ubi8-httpd -p '{"spec":{"externalIPs":["192.168.254.100"]}}'`

Assigning the External-IP on RHCOS to an interface or configure it as additional interface is not needed and also not supported (i believe that is also true for RHEL compute nodes). The routing is handled by iptables:

```
[core@master-0 ~]$ sudo iptables -S -t nat|grep 192.168.254.100
-A KUBE-SERVICES -d 192.168.254.100/32 -p tcp -m comment --comment "test/ubi8-httpd:8080-tcp external IP" -m tcp --dport 8080 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 192.168.254.100/32 -p tcp -m comment --comment "test/ubi8-httpd:8080-tcp external IP" -m tcp --dport 8080 -m physdev ! --physdev-is-in -m addrtype ! --src-type LOCAL -j KUBE-SVC-6RTKLRCQCJVYONPH
-A KUBE-SERVICES -d 192.168.254.100/32 -p tcp -m comment --comment "test/ubi8-httpd:8080-tcp external IP" -m tcp --dport 8080 -m addrtype --dst-type LOCAL -j KUBE-SVC-6RTKLRCQCJVYONPH
```

```
[core@master-0 ~]$ sudo iptables -S -t nat | grep KUBE-SVC-6RTKLRCQCJVYONPH
-N KUBE-SVC-6RTKLRCQCJVYONPH
-A KUBE-SERVICES -d 172.30.26.170/32 -p tcp -m comment --comment "test/ubi8-httpd:8080-tcp cluster IP" -m tcp --dport 8080 -j KUBE-SVC-6RTKLRCQCJVYONPH
-A KUBE-SERVICES -d 192.168.254.100/32 -p tcp -m comment --comment "test/ubi8-httpd:8080-tcp external IP" -m tcp --dport 8080 -m physdev ! --physdev-is-in -m addrtype ! --src-type LOCAL -j KUBE-SVC-6RTKLRCQCJVYONPH
-A KUBE-SERVICES -d 192.168.254.100/32 -p tcp -m comment --comment "test/ubi8-httpd:8080-tcp external IP" -m tcp --dport 8080 -m addrtype --dst-type LOCAL -j KUBE-SVC-6RTKLRCQCJVYONPH
-A KUBE-SVC-6RTKLRCQCJVYONPH -j KUBE-SEP-J5VCHHNEZ77RRFMX
```

```
[core@master-0 ~]$ sudo iptables -S -t nat | grep KUBE-SEP-J5VCHHNEZ77RRFMX
-N KUBE-SEP-J5VCHHNEZ77RRFMX
-A KUBE-SVC-6RTKLRCQCJVYONPH -j KUBE-SEP-J5VCHHNEZ77RRFMX
-A KUBE-SEP-J5VCHHNEZ77RRFMX -s 10.128.5.46/32 -j KUBE-MARK-MASQ
-A KUBE-SEP-J5VCHHNEZ77RRFMX -p tcp -m tcp -j DNAT --to-destination 10.128.5.46:8080
```

**Comment by jboxman** [comment]
@gnu300, thanks for reporting this! I've updated the procedure.
