### ISSUE TITLE
[enterprise-4.1] Edit suggested in file installing/installing_vsphere/installing-vsphere.adoc

### ISSUE THREAD

**Issue by zhigangwang315** [openshift/openshift-docs#16996]
### Which section(s) is the issue in?
Sample install-config.yaml file for VMware vSphere

### What needs fixing?
networking: section is missing
Something like this should be added:
networking: 
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineCIDR: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16

**Comment by jboxman** [comment]
Related: https://github.com/openshift/openshift-docs/pull/15999
