### ISSUE TITLE
[enterprise-3.1] Edit suggested in file install_config/aggregate_logging.adoc

### ISSUE THREAD

**Issue by lcrespom** [openshift/openshift-docs#17035]
### Which section(s) is the issue in?
Fluentd section in "Aggregating Container Logs", i.e.: https://docs.openshift.com/enterprise/3.1/install_config/aggregate_logging.html#fluentd

### What needs fixing?
There is a typo where it says "Elasicsearch" instead of "Elasticsearch". The typo appears 3 consecutive times.

**Comment by mburke5678** [comment]
@lcrespom Thanks for pointing this out. However, we are no longer supporting nor updating the 3.1 documentation, including anything from 3.10 and lower.
