### ISSUE TITLE
[enterprise-4.2] Edit suggested in file installing/installing_restricted_networks/installing-restricted-networks-preparations.adoc

### ISSUE THREAD

**Issue by kanekoh** [openshift/openshift-docs#17047]
### Which section(s) is the issue in?
Mirroring the OpenShift Container Platform image repository

### What needs fixing?
The command mirroring the repository includes undefined environment variable 'UPSTREAM_REPO'.
According to the blog[1], It seems not to be 'PRODUCT_REPO' but 'UPSTREAM_REPO'

[1]: https://blog.openshift.com/openshift-4-2-disconnected-install/

**Comment by kalexand-rh** [comment]
It's an environment variable, so it just needs to be consistent. Thanks for pointing this out - they're all `PRODUCT_REPO` now.
