### ISSUE TITLE
[enterprise-3.11] Edit suggested in file install/configuring_inventory_file.adoc

### ISSUE THREAD

**Issue by flaviopv** [openshift/openshift-docs#17103]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/3.11/install/configuring_inventory_file.html#advanced-install-configuring-registry-location

### What needs fixing?
I suggest you change the line:
oreg_url=registry.redhat.io/openshift3/ose-$<component>:$<version>
to
oreg_url=example.com/openshift3/ose-${component}:${version}

Since it can be confusing sometimes and we usually copy and paste the example in our inventory generating some error. This change does not impact the reason to change "component" and "version" if needed.

**Comment by jboxman** [comment]
@flaviopv, thanks for reporting this! We've fixed this in an update.
