### ISSUE TITLE
[enterprise-4.2] Edit suggested in file storage/understanding-persistent-storage.adoc

### ISSUE THREAD

**Issue by amelie1979** [openshift/openshift-docs#17125]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.2/storage/understanding-persistent-storage.html#pv-access-modes_understanding-persistent-storage

### What needs fixing?
Table 2. Supported access modes for PVs

Need to add GCP as Volume Plug-in

**Comment by vikram-redhat** [comment]
Looks like this was updated: https://docs.openshift.com/container-platform/4.2/storage/understanding-persistent-storage.html#block-volume-support_understanding-persistent-storage
