### ISSUE TITLE
[enterprise-4.1] Edit suggested in file welcome/index.adoc

### ISSUE THREAD

**Issue by rolfedh** [openshift/openshift-docs#17130]
### Which section(s) is the issue in?

All.

### What needs fixing?

The body text is grey, which makes it more difficult to read (esp for individuals with vision problems). 
Please make body text black.
https://www.wired.com/2016/10/how-the-web-became-unreadable/

**Comment by lamek** [comment]
Great point Rolfe. We are green if you measure our current ratio on this site:
https://contrast-ratio.com/#%23545454-on-%23ffffff

But the customer portal version of our docs has an even higher ratio, and imho is easier to read.
https://contrast-ratio.com/#%23252525-on-%23ffffff

I'll bring this issue to the team.

**Comment by rolfedh** [comment]
Is there any reason to use grey when black is more readable?

**Comment by jboxman** [comment]
@openshift/team-documentation, FYI

**Comment by vikram-redhat** [comment]
Let's have a chat in the next team meeting.
