### ISSUE TITLE
Add portal_net in advanced installation documentation 

### ISSUE THREAD

**Issue by akram** [openshift/openshift-docs#1716]
Hi,

The documetantion needs update:
https://docs.openshift.com/enterprise/3.0/install_config/install/advanced_install.html

```
openshift_master_portal_net
```

and

```
This variable overrides the network CIDR used by services. It overrides the master-config.yaml parameters servicesSubnet and serviceNetworkCIDR. Default value is 172.30.0.0/16.
```

Also considering adding the parameter to update the network used by SDN.

**Comment by mburke5678** [comment]
The flag was added in 3.1+
https://docs.openshift.com/enterprise/3.1/install_config/install/advanced_install.html
