### ISSUE TITLE
[enterprise-4.2] Edit suggested in file release_notes/ocp-4-2-release-notes.adoc

### ISSUE THREAD

**Issue by sunilcio** [openshift/openshift-docs#17174]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.2/release_notes/ocp-4-2-release-notes.html#ocp-4-2-known-issues

### What needs fixing?

Bug 1690754 has been fixed, so we need to remove below statement.

Unsafe sysctl cannot be used in OpenShift Container Platform 4.2. (BZ#1690754)

**Comment by ahardin-rh** [comment]
@sunilcio Thank you! This is addressed in https://github.com/openshift/openshift-docs/pull/17296/
