### ISSUE TITLE
'Configuring the SDN - Expanding the service network' incomplete?

### ISSUE THREAD

**Issue by eitchugo** [openshift/openshift-docs#17227]
### Which section(s) is the issue in?

Using openshift-3.11 docs for reference
Configuring Clusters - Configuring the SDN - Expanding the service network

### What needs fixing?

I think this section is incomplete. After Step 8, there's no more steps to re-enable scheduling in the nodes we just drained. If we drain and disable scheduling on every node we get a empty cluster. 

Also I think the instructions are a bit "overkill". I did the same procedure as follow, without having to redeploy the whole masters with the playbook:

1. Change `serviceNetworkCIDR` on masters config (same as Step 1 on current docs).

2. Delete `clusternetwork default` (same as Step 2 on current docs)

3. Restart master controllers (same as Step 3 on current docs)

4. Delete OVS pods from project openshift-sdn:

```
$ oc project openshift-sdn
$ oc get pods
$ oc delete pods ovs-xxxx ovs-xxxx ovs-xxxx
```

Done, the pods will be recreated with the new tunnel interface and route on all nodes. This takes some seconds.

Maybe adding draining/disabling schedule to evict downtimes?

**Comment by eitchugo** [comment]
I created updated instructions (but internal), skipping the playbook section. Would you be interested in a pull request with it?

It also includes the "missing" steps after step 8 - rebooting the nodes and making them schedulable again.

**Comment by vikram-redhat** [comment]
Thanks @eitchugo - if you can submit a PR, that will be appreciated.

**Comment by eitchugo** [comment]
Instructions work for me, but I would really appreciate another opinion on it :)

**Comment by jboxman** [comment]
@eitchugo, thanks!
