### ISSUE TITLE
[enterprise-4.1] Edit suggested in file installing/install_config/configuring-firewall.adoc

### ISSUE THREAD

**Issue by DrOwl** [openshift/openshift-docs#17252]
A good start but a little vague 

### Which section(s) is the issue in?
Procedure

### What needs fixing?
Firewall rules should be in the form "Source - Destination - Protocol"

**Source:** Which nodes require this access bootstrap, master, Compute, all of them?

**Destination:** Please Supply IP Address as I am not aware of any firewalls whose rules can be configured with host names (especially as it appears the protocol appears to be https so the firewall can not even see the uri in the request)

**Protocol:** should ether use a named protocol such as https or specify a type such as TCP.

**Comment by kalexand-rh** [comment]
@DrOwl, we rewrote this topic in 4.2: https://docs.openshift.com/container-platform/4.2/installing/install_config/configuring-firewall.html
Does this information better meet your needs?
