### ISSUE TITLE
[enterprise-4.2] Edit suggested in file installing/installing_gcp/installing-gcp-account.adoc

### ISSUE THREAD

**Issue by cblecker** [openshift/openshift-docs#17391]
### Which section(s) is the issue in?

Enabling API services

### What needs fixing?

This section should come before the DNS section, as you need to enable the DNS API. This section can go first.

**Comment by kalexand-rh** [comment]
Thanks for pointing this out! I opened a PR to fix both of your GCP issues. Please let us know if you find more issues.
