### ISSUE TITLE
[enterprise-4.2] Edit suggested in file installing/installing_gcp/installing-gcp-account.adoc

### ISSUE THREAD

**Issue by cblecker** [openshift/openshift-docs#17390]
### Which section(s) is the issue in?

left hand nav bar

### What needs fixing?

left hand nav bar calls this page "installing GCP account", but it should be "installing GCP project"

**Comment by kalexand-rh** [comment]
Thanks for pointing this out! I opened a PR to fix both of your GCP issues. Please let us know if you find more issues.
