### ISSUE TITLE
[enterprise-4.2] Edit suggested in file release_notes/ocp-4-2-release-notes.adoc

### ISSUE THREAD

**Issue by rbaumgar** [openshift/openshift-docs#17421]
### Which section(s) is the issue in?
Networking - OVN (TECHNOLOGY PREVIEW)

### What needs fixing?
some lines are multiple! e.g.
- Heterogeneous Linux/Windows clusters. <-> Heterogeneous clusters with Windows nodes
- The ability to have a cluster network that spans on-premise nodes and cloud nodes. <-> The capability to span on-premise and cloud nodes

**Comment by ahardin-rh** [comment]
Thank you for pointing this out! A fix is now submitted. Please let me know if I can help further.
