### ISSUE TITLE
routestatus is not documented in API docs

### ISSUE THREAD

**Issue by sosiouxme** [openshift/openshift-docs#1746]
https://docs.openshift.org/latest/rest_api/openshift_v1.html#v1-routestatus is empty. The actual route object has plenty in it.

**Comment by mburke5678** [comment]
@sosiouxme Has your concern here been addressed? The earliest API guide 1.2 has the same info as the latest. 
https://docs.openshift.org/1.5/rest_api/openshift_v1.html#v1-routestatus

**Comment by sosiouxme** [comment]
Yeah - looks good now. Thanks for following up!
