### ISSUE TITLE
NodePort Examples looks wrong

### ISSUE THREAD

**Issue by git001** [openshift/openshift-docs#17464]
### Which section(s) is the issue in?
4.x

### What needs fixing?
https://docs.openshift.com/container-platform/4.2/networking/configuring-ingress-cluster-traffic/configuring-ingress-cluster-traffic-nodeport.html  
https://github.com/openshift/openshift-docs/blob/enterprise-4.2/networking/configuring-ingress-cluster-traffic/configuring-ingress-cluster-traffic-nodeport.adoc

In the section "Creating a project and service" does not match the step 4 to the step 3

Step 3
```
oc new-app \
    -e MYSQL_USER=admin \
    -e MYSQL_PASSWORD=redhat \
    -e MYSQL_DATABASE=mysqldb \
    registry.redhat.io/openshift3/mysql-55-rhel7
```

Step 4
```
oc get svc -n openshift-ingress
```
But to see if the service is created in `<myproject>` you should use `oc get svc -n  <myproject>`

I also assume that you want to create a project in the example of Step 2  like `oc new-project mysql`

The doc includes other docs but this looks wrong to me for this case.
https://raw.githubusercontent.com/openshift/openshift-docs/enterprise-4.2/networking/configuring-ingress-cluster-traffic/configuring-ingress-cluster-traffic-nodeport.adoc

**Comment by jboxman** [comment]
Thanks for opening this @git001; I've merged a PR with the fix https://github.com/openshift/openshift-docs/pull/18368.
