### ISSUE TITLE
Need create doc about config google credentials on gce env

### ISSUE THREAD

**Issue by mdshuai** [openshift/openshift-docs#1748]
See bug [#1311840](https://bugzilla.redhat.com/show_bug.cgi?id=1311840#c10) comment 10

Now the openshift doc about "Configuring for GCE" only doc how set cloud-provider but no credentials
https://docs.openshift.org/latest/install_config/configuring_gce.html

**Comment by Themodem** [comment]
Any word on the doc? - Comment 10 has vanished

Even just a quick list of params for that file?

**Comment by mburke5678** [comment]
@mdshuai The `cloud-config` parameter was added to 1.3 docs. Does this meet your needs?
https://docs.openshift.org/1.3/install_config/configuring_gce.html#gce-configuring-masters-manual

**Comment by vikram-redhat** [comment]
This was fixed as per the last comment so closing this issue.
