### ISSUE TITLE
[enterprise-4.2] Edit suggested in file installing/installing_bare_metal/installing-bare-metal.adoc

### ISSUE THREAD

**Issue by zhigangwang315** [openshift/openshift-docs#17582]
### Which section(s) is the issue in?
In "Installing a cluster on bare metal" -> "Sample install-config.yaml file for bare metal" section, note#4 

You "must" set the value of the replicas parameter to 0. This parameter controls the number of workers that the cluster creates and manages for you, which are functions that the cluster does not perform when you use user-provisioned infrastructure. You must manually deploy worker machines for the cluster to use before you finish installing OpenShift Container Platform.

### What needs fixing?
The wording "must" is misleading and should be changed. Customer is saying it still works even if you set the field to a non-zero value

**Comment by lospringliu** [comment]
actually, for UPI, this number is the way to tell the bootstrap node to how many workers to expect

the same as how master replicas tell bootstrap how many masters to expect

**Comment by kalexand-rh** [comment]
I checked with the engineering lead for the install team, and you still need to explicitly set the number of workers to 0 for UPI.
