### ISSUE TITLE
[enterprise-4.1] Edit suggested in file nodes/scheduling/nodes-scheduler-node-selectors.adoc

### ISSUE THREAD

**Issue by rbrt86** [openshift/openshift-docs#17653]
### Which section(s) is the issue in?

The first paragraph on this page contains a typo:
https://docs.openshift.com/container-platform/4.1/nodes/scheduling/nodes-scheduler-node-selectors.html

### What needs fixing?

the document states specofic  instead of specific

**Comment by jboxman** [comment]
@rbrt86, thanks for reporting this!
