### ISSUE TITLE
[enterprise-4.2] Edit suggested in file installing/installing_bare_metal/installing-bare-metal.adoc

### ISSUE THREAD

**Issue by amelie1979** [openshift/openshift-docs#17679]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.2/installing/installing_bare_metal/installing-bare-metal.html#installation-bare-metal-config-yaml_installing-bare-metal

### What needs fixing?
install-config.yaml example should include all possible configuration such as : networking.machineCIDR or add a link to a full possible configuration install-config.yaml.

**Comment by jboxman** [comment]
@amelie1979, `machineCIDR` is used for installer provisioned infrastructure; I don't think it is used at all for user provisioned infrastructure, so that's why it's absent from the `install-config.yaml`.
