### ISSUE TITLE
[enterprise-4.2] Edit suggested in file cli_reference/openshift_developer_cli/installing-odo.adoc

### ISSUE THREAD

**Issue by thescouser89** [openshift/openshift-docs#17696]
### Which section(s) is the issue in?
Installing odo on Linux

### What needs fixing?
Download link in the linux section uses the macos binary. It should be updated to point to the linux binary (https://mirror.openshift.com/pub/openshift-v4/clients/odo/latest/odo-linux-amd64)

**Comment by vikram-redhat** [comment]
@Preeticp - can you take a look at this?

**Comment by Preeticp** [comment]
@boczkowska can you please take a look at this?

**Comment by boczkowska** [comment]
@Preeticp this was fixed in https://github.com/openshift/openshift-docs/pull/17811

**Comment by Preeticp** [comment]
Awesome, in that case we will need to close this issue. @vikram-redhat how do we close an issue?

**Comment by jboxman** [comment]
@Preeticp, I'll close.

**Comment by Preeticp** [comment]
Thank you @jboxman !!
