### ISSUE TITLE
nodeSelector should be defaultNodeSelector

### ISSUE THREAD

**Issue by eformat** [openshift/openshift-docs#1770]
docs bug:
https://docs.openshift.com/enterprise/3.1/admin_guide/managing_projects.html#using-node-selectors

should be "defaultNodeSelector"

projectConfig:
  defaultNodeSelector: "type=user-node,region=east"

**Comment by bfallonf** [comment]
@eformat Thanks for checking that out. PR created #1771 

Closing this.
