### ISSUE TITLE
[enterprise-4.2] Edit suggested in file installing/installing_vsphere/installing-vsphere.adoc

### ISSUE THREAD

**Issue by gyucegok** [openshift/openshift-docs#17732]
### Which section(s) is the issue in?

install-config.yaml example

### What needs fixing?

There is no networking section, which is present on the baremetal page for instance, as follows;

 networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14 
    hostPrefix: 23 
  networkType: OpenShiftSDN
  serviceNetwork: 
  - 172.30.0.0/16

is this normal?

**Comment by kalexand-rh** [comment]
@dav1x, is there value in adding additional networking information to https://docs.openshift.com/container-platform/4.2/installing/installing_vsphere/installing-vsphere.html#installation-vsphere-config-yaml_installing-vsphere? I thought that information that you provided in the current `install-config.yaml` was enough, and that your vSphere instance provided the rest of the networking information.
