### ISSUE TITLE
[enterprise-4.2] Edit suggested in file installing/installing_azure/installing-azure-account.adoc

### ISSUE THREAD

**Issue by hkamel** [openshift/openshift-docs#17762]
### Which section(s) is the issue in?
Azure account limits

### What needs fixing?
Default limits vary by offer category types, such as Free Trial and Pay-As-You-Go, and by series, such as Dv2, F, and G. For example, the default for Enterprise Agreement subscriptions is 350 core.
check [Subscription limits - Azure Resource Manager](https://docs.microsoft.com/en-us/azure/azure-subscription-service-limits#subscription-limits---azure-resource-manager)

**Comment by kalexand-rh** [comment]
Thanks for opening a PR, @hkamel! I'm going to get confirmation from QE or PM and get it merged as soon as I can.
