### ISSUE TITLE
Recreate Strategy: mention about Mid deployment hook

### ISSUE THREAD

**Issue by php-coder** [openshift/openshift-docs#1779]
Documentation about [Recreate Strategy](https://docs.openshift.org/latest/dev_guide/deployments.html#recreate-strategy) doesn't mention about [`Mid` deployment hook that was added](https://github.com/openshift/origin/commit/bde5983196b5d1e0a311ff8e86685f95542f0e18) in [1.1.2](https://github.com/openshift/origin/releases/tag/v1.1.2):

> The Recreate strategy now supports mid hooks which run while all old pods have been scaled down and before any new pods are scaled up - use it to run migrations or config changes that can only happen while the application is completely shut down

**Comment by mburke5678** [comment]
@php-coder Information on mid hooks was added to 3.2 
https://github.com/openshift/openshift-docs/commit/5ea53ac1ec2925efcd580c18ac97a890e6cc4e4e#diff-bb64229c6f759cb3173e8feed89d827b

Closing the issue unless you feel that this does not address your issue.
