### ISSUE TITLE
link to openstack image formats is 404

### ISSUE THREAD

**Issue by dlbewley** [openshift/openshift-docs#17797]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.2/installing/installing_openstack/installing-openstack-installer-custom.html#installation-osp-creating-image_installing-openstack-installer-custom

`modules/installation-osp-creating-image.adoc`

### What needs fixing?

https://docs.openstack.org/image-guide/image-formats.html link is 404

Perhaps the intended target is https://docs.openstack.org/image-guide/convert-images.html

**Comment by vikram-redhat** [comment]
I can't replicate the error anymore, I believe it was fixed via this: https://github.com/openshift/openshift-docs/pull/17839. Closing.
