### ISSUE TITLE
[enterprise-4.2] Edit suggested in file operators/olm-adding-operators-to-cluster.adoc

### ISSUE THREAD

**Issue by leifmadsen** [openshift/openshift-docs#17810]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.2/operators/olm-adding-operators-to-cluster.html#olm-installing-operator-from-operatorhub-using-cli_olm-adding-operators-to-a-cluster

Procedure step number 2, example output is invalid

### What needs fixing?

Current:

```
$ oc describe packagemanifests -n <operator_name> -n openshift-marketplace
```

Fixed:

```
$ oc describe packagemanifests <operator_name> -n openshift-marketplace
```

**Comment by ahardin-rh** [comment]
@leifmadsen Thank you! Looks like this fix was applied. I see step 2 now reflects:
`$ oc describe packagemanifests <operator_name> -n openshift-marketplace`
