### ISSUE TITLE
[enterprise-4.2] Edit suggested in file cli_reference/openshift_developer_cli/installing-odo.adoc

### ISSUE THREAD

**Issue by noseka1** [openshift/openshift-docs#17821]
### Which section(s) is the issue in?

Installing odo on Linux / Binary installation

### What needs fixing?

Replace the URL https://mirror.openshift.com/pub/openshift-v4/clients/odo/latest/odo-darwin-amd64 with https://mirror.openshift.com/pub/openshift-v4/clients/odo/latest/odo-linux-amd64

**Comment by jboxman** [comment]
@noseka1, thanks for reporting this! It's fixed in the latest version of the docs.
