### ISSUE TITLE
incorrect namespace in EFK hostpath example

### ISSUE THREAD

**Issue by dlbewley** [openshift/openshift-docs#17855]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/3.11/install_config/aggregate_logging.html#aggregated-logging-hostPath-Elasticsearch

### What needs fixing?

This command example uses the old `logging` namespace. Default install of EFK stack on (at least 3.11) results in installation to `openshift-logging` namespace.

```
  $ oc adm policy add-scc-to-user privileged  \
   system:serviceaccount:logging:aggregated-logging-elasticsearch
```

So the above should instead read 

```
  $ oc adm policy add-scc-to-user privileged  \
   system:serviceaccount:openshift-logging:aggregated-logging-elasticsearch
```

**Comment by jcantrill** [comment]
We should probably mention something to the affect that if you migrated from earlier versions logging may have been installed in the `logging` ns and you should adjust the SA accordingly

**Comment by mburke5678** [comment]
https://github.com/openshift/openshift-docs/pull/18092
