### ISSUE TITLE
Developer Guide: Builds: define build context

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/openshift-docs#1786]
Both "context" and "build context" are used somewhat generously in [the builds dev guide](https://docs.openshift.org/latest/dev_guide/builds.html), but **the concept is not explicitly defined**.

Docker does define what build context mean for a Docker build:
- https://docs.docker.com/engine/reference/builder/
- https://docs.docker.com/engine/reference/glossary/ (under build)

In our case, "build context" can either mean the same as in Docker, or in case of S2I it's normally conveying to me the idea that there's a directory in the container's file system (`/opt/app-root/src`) and some data (e.g., coming from a Git repo, binary stream, etc).

We can use `contextDir`, a relative path, to change the working directory / build context relative to the original context.

From the discussion in https://github.com/openshift/openshift-docs/pull/1745#discussion_r56864482.

**Comment by ahardin-rh** [comment]
Created a docs bug for this to better track the work: https://bugzilla.redhat.com/show_bug.cgi?id=1485028
