### ISSUE TITLE
[enterprise-4.2] Edit suggested in file metering/metering-installing-metering.adoc

### ISSUE THREAD

**Issue by jaxx0r** [openshift/openshift-docs#17860]
### Which section(s) is the issue in?
The whole page uses "namespace" instead of "project". At least the instruction "Administration → Namespaces → Create Namespace." should be changed to "Administration → Projects → Create Project." to be inline with OCP Web Console

### What needs fixing?
Replace "namespace" with "project" on whole page.

**Comment by vikram-redhat** [comment]
Kevin - can you take a look?
