### ISSUE TITLE
[enterprise-3.11] Disconnected install references 3.10 repos

### ISSUE THREAD

**Issue by ghyde** [openshift/openshift-docs#17893]
### Which section(s) is the issue in?

OCP 3.11 [Disconnected installation](https://github.com/openshift/openshift-docs/blob/a3008833195c76d9281cd681f62c183f75a1665b/install/disconnected_install.adoc)

### What needs fixing?

There are three instances of "3.10" in the documentation, which should be "3.11". Two of these instances are found in the IBM POWER subsections, which will result in the wrong repo being synced.

**Comment by kalexand-rh** [comment]
Closing the issue because the change is merged. Thank you for submitting the issue and the fix, @ghyde!
