### ISSUE TITLE
[enterprise-4.2] Edit suggested in file logging/cluster-logging.adoc

### ISSUE THREAD

**Issue by syedriko** [openshift/openshift-docs#17908]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.2/logging/cluster-logging.html#cluster-logging-about_cluster-logging

### What needs fixing?
"As an OpenShift Container Platform cluster administrator, you can deploy cluster logging to aggregate logs for a range of OpenShift Container Platform services." is repeated twice.

**Comment by ahardin-rh** [comment]
@syedriko Thank you! Fixes submitted
