### ISSUE TITLE
Code Blocks Don't Line Wrap or Allow Scrolling on Mobile

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/openshift-docs#1793]
It's not clear to me if mobile is in the scope of the docs website, but at the moment code blocks are pretty broken:

<img src="https://cloud.githubusercontent.com/assets/7328370/13955594/a33d7f02-f01b-11e5-9ecb-d484bbd4a631.png" align="left" height="400" >

The code blocks don't line wrap (which I'd argue is good) but they also don't allow side-to-side scrolling, so you can't really see their content.

**Comment by mburke5678** [comment]
@stevekuznetsov Is this still an issue for you? I did a quick, quick test on my Android and I found several pages (including the page above) that had code blocks with non-wrapping code and I could scroll the text block (and tables).  It is not obvious that you can scroll, no scroll bar, until you scroll.

**Comment by stevekuznetsov** [comment]
Do you have some specific pages I could look at? I'd be happy to test them out.
