### ISSUE TITLE
[enterprise-4.2] Edit suggested in file architecture/architecture-installation.adoc

### ISSUE THREAD

**Issue by mistergareth** [openshift/openshift-docs#18013]
### Which section(s) is the issue in?
THE INSTALLATION PROCESS WITH INSTALLER-PROVISIONED INFRASTRUCTURE

### What needs fixing?
The "Caution" call-out under the section title for IPI should either be removed entirely or updated.

It currently says IPI is supported only for AWS in version 4.2. Pretty sure this is an error carried forward from 4.1 docs and should be deleted (or fixed). Version 4.2 enables IPI for AWS plus GCP, Azure and OSP 13/14 as listed under *Available Platforms* (https://docs.openshift.com/container-platform/4.2/architecture/architecture-installation.html#available-platforms_architecture-installation)

**Comment by mistergareth** [comment]
Also, the first sentence makes this whole section reads as if it is for AWS only.

Maybe just change "on AWS" to say "on supported platforms" with a link back up to https://docs.openshift.com/container-platform/4.2/architecture/architecture-installation.html#available-platforms_architecture-installation

Or else describe the steps for each of the newly-supported IPI platforms - GCP, Azure and OpenStack - if warranted.

**Comment by kalexand-rh** [comment]
@mistergareth, thanks! It looks like I've fixed these issues on other pull requests. If you see any other issues, please reopen this issue or file a new one.
