### ISSUE TITLE
[enterprise-4.2] Typo: Edit suggested in file release_notes/ocp-4-2-release-notes.adoc

### ISSUE THREAD

**Issue by mistergareth** [openshift/openshift-docs#18012]
### Which section(s) is the issue in?
Node Tuning Operator Enhancements
(https://docs.openshift.com/container-platform/4.2/release_notes/ocp-4-2-release-notes.html#ocp-4-2-node-tuning-operator-enhancements)

### What needs fixing?
Typo in first sentence. Change "Turning" to "Tuning".

**Comment by jboxman** [comment]
@mistergareth, thanks for reporting this!
