### ISSUE TITLE
[enterprise-4.2] Edit suggested in file installing/installing_restricted_networks/installing-restricted-networks-vsphere.adoc

### ISSUE THREAD

**Issue by mlcassatt** [openshift/openshift-docs#18027]
### Which section(s) is the issue in?
User-provisioned DNS requirements

### What needs fixing?
etcd

etcd-<index>.<cluster_name>.<base_domain>

OpenShift Container Platform requires DNS records for each etcd instance to point to the control plane machines that host the instances. The etcd instances are differentiated by <index> values, which start with 0 and end with n-1, where n is the number of control plane machines in the cluster. The DNS record must resolve to an unicast IPv4 address for the control plane machine, and the records must be resolvable from all the nodes in the cluster.

_etcd-server-ssl._tcp.<cluster_name>.<base_domain>

For each control plane machine, OpenShift Container Platform also requires a SRV DNS record for etcd server on that machine with priority 0, weight 10 and port 2380. A cluster that uses three control plane machines requires the following records:

# _service._proto.name.                            TTL    class SRV priority weight port target.
_etcd-server-ssl._tcp.<cluster_name>.<base_domain>  86400 IN    SRV 0        10     2380 etcd-0.<cluster_name>.<base_domain>.
_etcd-server-ssl._tcp.<cluster_name>.<base_domain>  86400 IN    SRV 0        10     2380 etcd-1.<cluster_name>.<base_domain>.
_etcd-server-ssl._tcp.<cluster_name>.<base_domain>  86400 IN    SRV 0        10     2380 etcd-2.<cluster_name>.<base_domain>.

########
Should be (missing periods at the end of record name in both instructions and example):
########

etcd

etcd-<index>.<cluster_name>.<base_domain>.

OpenShift Container Platform requires DNS records for each etcd instance to point to the control plane machines that host the instances. The etcd instances are differentiated by <index> values, which start with 0 and end with n-1, where n is the number of control plane machines in the cluster. The DNS record must resolve to an unicast IPv4 address for the control plane machine, and the records must be resolvable from all the nodes in the cluster.

_etcd-server-ssl._tcp.<cluster_name>.<base_domain>.

For each control plane machine, OpenShift Container Platform also requires a SRV DNS record for etcd server on that machine with priority 0, weight 10 and port 2380. A cluster that uses three control plane machines requires the following records:

# _service._proto.name.                            TTL    class SRV priority weight port target.
_etcd-server-ssl._tcp.<cluster_name>.<base_domain>.  86400 IN    SRV 0        10     2380 etcd-0.<cluster_name>.<base_domain>.
_etcd-server-ssl._tcp.<cluster_name>.<base_domain>.  86400 IN    SRV 0        10     2380 etcd-1.<cluster_name>.<base_domain>.
_etcd-server-ssl._tcp.<cluster_name>.<base_domain>.  86400 IN    SRV 0        10     2380 etcd-2.<cluster_name>.<base_domain>.

**Comment by jboxman** [comment]
@mlcassatt, would this correction also apply to the other DNS records in the table?

Thanks.

**Comment by mlcassatt** [comment]
@jboxman, specifically referring to only the SRV records that need to be created in DNS. The additional  periods must be used when creating the records.

**Comment by jboxman** [comment]
@mlcassatt, it's been awhile since I've worked with DNS. It's only the _SRV_ records that need to be shown with the trailing period, but no other DNS entry in the table requires this? I thought this is necessary for all DNS entries?

**Comment by mlcassatt** [comment]
@jboxman, only the SRV records require the trailing "." when defined. 

2 (two) "." (periods). Should look like this:
_etcd-server-ssl._tcp.<cluster_name>.<base_domain>**.** 86400 IN SRV 0 10 2380 etcd-0.<cluster_name>.<base_domain>**.**

**Comment by zhaozhanqi** [comment]
I checked the AWS route53 SRV record, it should be:
  the name has '.', but target has not '.'
_etcd-server-ssl._tcp.<cluster_name>.<base_domain>. 86400 IN SRV 0 10 2380 etcd-0.<cluster_name>.<base_domain>

**Comment by jboxman** [comment]
@mlcassatt, does it matter what DNS software is used? Is this defined directly in vSphere somewhere? I'm unfamiliar with vSphere. I know that when creating DNS records in some interfaces, it tries to _help_ you by allowing the omission of the terminal period that I think the spec requires.
