### ISSUE TITLE
Document IAM permissions required for AWS integration

### ISSUE THREAD

**Issue by abutcher** [openshift/openshift-docs#1802]
Upstream Doc: [Identity and Access Management](https://github.com/kubernetes/kubernetes/blob/8cc91944e0555af82f86cc7f21fb638be60665fd/docs/design/aws_under_the_hood.md#identity-and-access-management-iam)

Upstream has provided IAM policies required for [masters](https://github.com/kubernetes/kubernetes/blob/8cc91944e0555af82f86cc7f21fb638be60665fd/cluster/aws/templates/iam/kubernetes-master-policy.json) and [minions](https://github.com/kubernetes/kubernetes/blob/8cc91944e0555af82f86cc7f21fb638be60665fd/cluster/aws/templates/iam/kubernetes-minion-policy.json) which we should document along with AWS configuration.

For demo-ansible, we are using the following policies:

Nodes

```
{
    "Statement":[
    {
        "Resource":"*",
        "Action":"ec2:Describe*",
        "Effect":"Allow"
    },
    {
        "Resource":"*",
        "Action":"ec2:AttachVolume",
        "Effect":"Allow"
    },
    {
        "Resource":"*",
        "Action":"ec2:DetachVolume",
        "Effect":"Allow"
    }
    ],
    "Version":"2012-10-17"
}
```

Masters

```
{
    "Statement":[
    {
        "Resource":"*",
        "Action":"ec2:*",
        "Effect":"Allow"
    },
    {
        "Resource":"*",
        "Action":"elasticloadbalancing:*",
        "Effect":"Allow"
    }
    ],
    "Version":"2012-10-17"
}
```

@ncdc do you know if there is a more restrictive list of required permissions?

**Comment by ncdc** [comment]
@abutcher I've never looked into the AWS permissions so I don't know - sorry!

**Comment by mburke5678** [comment]
@abutcher Is this still an issue that we should address in the docs? Has anything changed in the AWS or Kubernetes architecture that would eliminate this issue?

**Comment by abutcher** [comment]
@mburke5678 Yes, we don't cover these policies in the "Configuring for $cloud" topics. It looks like the AWS policies have changed slightly from the OC but they appear to still be pretty global in terms of the access required.

**Comment by mburke5678** [comment]
Created [BZ 1480336](https://bugzilla.redhat.com/show_bug.cgi?id=1480336). Closing issue
