### ISSUE TITLE
[enterprise-4.2] Edit suggested in file registry/configuring-registry-storage/configuring-registry-storage-baremetal.adoc

### ISSUE THREAD

**Issue by jcordes73** [openshift/openshift-docs#18036]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.2/registry/configuring-registry-storage/configuring-registry-storage-baremetal.html#registry-configuring-storage-baremetal_configuring-registry-storage-baremetal

### What needs fixing?
NFS shouldn't be recommended or caveats should be outlined as in https://docs.openshift.com/container-platform/4.2/scalability_and_performance/optimizing-storage.html#specific-application-storage-recommendations.

**Comment by vikram-redhat** [comment]
@codyhoag might just be a matter of copying over that warning to these docs.

**Comment by codyhoag** [comment]
@jcordes73 Thanks for bringing this up. Since the suggestion for using NFS was simply removed for these docs in 4.3, I've removed the suggestion for 4.1/4.2. I've sent this for review:

#19305 
#19306

**Comment by codyhoag** [comment]
The NFS suggestion has been replaced with OCS for OCP 4.2+:

#19306 
#19665
