### ISSUE TITLE
[enterprise-3.11] Edit suggested in file release_notes/ocp_3_11_release_notes.adoc

### ISSUE THREAD

**Issue by zhigangwang315** [openshift/openshift-docs#18041]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/3.11/release_notes/ocp_3_11_release_notes.html#ocp-3-11-153-images

### What needs fixing?
The path to container images is wrong

The path in this doc is correct
https://docs.openshift.com/container-platform/3.11/install/disconnected_install.html#disconnected-syncing-images

**Comment by codyhoag** [comment]
@zhigangwang315 just to confirm, are you suggesting the registry URL defined as `registry.access.redhat.com` be updated to `registry.redhat.io`?

**Comment by zhigangwang315** [comment]
A customer tried to download the container images listed at the end of the 3.11 release notes:

https://docs.openshift.com/container-platform/3.11/release_notes/ocp_3_11_release_notes.html
The first container image on the list does not exist:


sudo docker pull registry.access.redhat.com/openshift3/aos3-installation-container-v3.11.153-3<http://registry.access.redhat.com/openshift3/aos3-installation-container-v3.11.153-3>

Using default tag: latest

Error response from daemon: repository registry.access.redhat.com/openshift3/aos3-installation-container-v3.11.153-3<http://registry.access.redhat.com/openshift3/aos3-installation-container-v3.11.153-3> not found


When we point him to the doc below to download image using version tag, it works.

https://docs.openshift.com/container-platform/3.11/install/disconnected_install.html#disconnected-syncing-images

So someone need to verify the path in the release notes.


Thanks.

Zhigang


________________________________

**Comment by codyhoag** [comment]
@zhigangwang315 I have requested the image names for 3.11.153 from the release team. I will update the doc once I've received them.

**Comment by codyhoag** [comment]
@zhigangwang315 I've updated the release notes with the appropriate image names in #18074. This update should be reflected in the published docs soon. Thanks for reporting!
