### ISSUE TITLE
OpenShift dedicated 'latest' URL points to V3

### ISSUE THREAD

**Issue by kgibm** [openshift/openshift-docs#18080]
The URL https://docs.openshift.com/dedicated/latest/welcome/index.html points to https://docs.openshift.com/dedicated/3/welcome/index.html instead of https://docs.openshift.com/dedicated/4/welcome/index.html

**Comment by vikram-redhat** [comment]
@kgibm that is by design as we slowly move all dedicated clusters to 4.
