### ISSUE TITLE
[enterprise-4.2] Edit suggested in file networking/configuring-ingress-cluster-traffic/configuring-ingress-cluster-traffic-service-external-ip.adoc

### ISSUE THREAD

**Issue by fmeulenk** [openshift/openshift-docs#18172]
### Which section(s) is the issue in?

Creating a project and service

### What needs fixing?

Step 3 would create a create a Service without an External-IP but only the Cluster-IP.
The figure in Step 4 suddenly shows an External-IP and the last sentence even states: 

> By default, the new service does not have an external IP address

What is missing, is the step in which the External-IP was added to the service.

Otherwise, the figure for `Creating a project and service` Step 4. is not related, as it is showing services from another project and not the services that was created in the previous step.

**Comment by jboxman** [comment]
@fmeulenk, I've rewritten the procedure. Thanks!
