### ISSUE TITLE
[enterprise-4.2] Edit suggested in file networking/configuring-ingress-cluster-traffic/configuring-ingress-cluster-traffic-service-external-ip.adoc

### ISSUE THREAD

**Issue by fmeulenk** [openshift/openshift-docs#18173]
### Which section(s) is the issue in?

Exposing the service by creating a route

### What needs fixing?

This does not make any sense at all, in this context.
It is showing the IP from the Portal-Net and not the external IP that (should have been/) was created in the previous section.
Otherwise, this example exposes an non-HTTP port for MySQL, which will not work.
Step 4 is not using the Route at all.

As External-IPs are usually used for non-HTTP-ish traffic I would suggest to remove this section

**Comment by jboxman** [comment]
@fmeulenk, I've rewritten the procedure. Thanks!
