### ISSUE TITLE
[enterprise-4.2] Edit suggested in file logging/cluster-logging-deploying.adoc

### ISSUE THREAD

**Issue by ChetHosey** [openshift/openshift-docs#18218]
### Which section(s) is the issue in?

Create a Namespace for the Cluster Logging Operator (for example, clo-namespace.yaml):

### What needs fixing?

Applying a selector to the namespace as suggested ("If you want the logging pods to run on specific nodes, you can specify a node selector value such as openshift.io/node-selector: node-role.kubernetes.io/infra= here.") will keep the fluentd from deploying on all cluster nodes. It would be nice to be able to do this on the namespace and then override the selector for fluentd. I haven't tried it.

If the suggestion is kept, it should be updated to include a comment on how to address fluentd.

**Comment by mburke5678** [comment]
@ChetHosey Thanks for pointing this out. Since you filed this issue we have removed the information about using nodeselectors here for the reason you specified. See https://github.com/openshift/openshift-docs/pull/18728/files#diff-3835df169d4485d60f176ea11dc46e80L90-L91
