### ISSUE TITLE
[enterprise-4.2] Edit suggested in file operators/operator_sdk/osdk-getting-started.adoc

### ISSUE THREAD

**Issue by akieling** [openshift/openshift-docs#18248]
### Which section(s) is the issue in?
Managing a Memcached Operator using the Operator Lifecycle Manager

### What needs fixing?
"Building a CSV for the Operator Framework" link pointing to https://github.com/operator-framework/operator-lifecycle-manager/blob/master/Documentation/design/building-your-csv.md is broken.

**Comment by ahardin-rh** [comment]
@akieling Thank you! These link fixes are now addressed in https://github.com/openshift/openshift-docs/pull/18780
