### ISSUE TITLE
[online] Edit suggested in file getting_started/access_your_services.adoc

### ISSUE THREAD

**Issue by erjosito** [openshift/openshift-docs#18268]
### Which section(s) is the issue in?

Create an Internal-Only TCP Service

### What needs fixing?
```
$ oc expose dc httpd-example --type=LoadBalancer --name=internal-lb --dry-run -o yaml | awk '1;/metadata:/{ print "  annotations:\n    service.beta.kubernetes.io/azure-load-balancer-internal: 0.0.0.0/0" }' | oc create -f -service/internal-lb exposed
```

should probably be (according to the annotation for internal load balancers described in [internal-lb](https://docs.microsoft.com/bs-latn-ba/azure/aks/internal-lb) )

```
$ oc expose dc httpd-example --type=LoadBalancer --name=internal-lb --dry-run -o yaml | awk '1;/metadata:/{ print "  annotations:\n    service.beta.kubernetes.io/azure-load-balancer-internal: \"true\"" }' | oc create -f -service/internal-lb exposed
```

**Comment by sheriff-rh** [comment]
Hi Jose, I have made the corrections as you have suggested. If the changes are satisfactory to you, I will merge them later today: #18665

**Comment by erjosito** [comment]
@sheriff-rh Looks good! Thanks!

**Comment by sheriff-rh** [comment]
Changes have been merged, I will mark this issue as closed. 

Jose, thank you for helping us keep our docs in shape! Have a great holiday and 2020!
