### ISSUE TITLE
[enterprise-4.2] Edit suggested in file cnv/cnv_users_guide/cnv-openshift-cluster-monitoring.adoc

### ISSUE THREAD

**Issue by rbaumgar** [openshift/openshift-docs#18308]
### Which section(s) is the issue in?

About Telemetry
    Information collected by Telemetry

### What needs fixing?
Why is the chapter "Showing data collected by Telemetry" no longer existing?
It is always a good way to SHOW customer which data we are collecting...
See https://docs.openshift.com/container-platform/4.1/telemetry/showing-data-collected-by-telemetry.html

**Comment by vikram-redhat** [comment]
@rbaumgar I see the chapter on the link you posted (https://docs.openshift.com/container-platform/4.1/telemetry/showing-data-collected-by-telemetry.html). Please reopen if the issue persists.

**Comment by rbaumgar** [comment]
Yes that's true, but it does no longer available in 4.2!

**Comment by rbaumgar** [comment]
@vikram-redhat I don't know how to reopen

**Comment by vikram-redhat** [comment]
That is because it moved to another location: https://docs.openshift.com/container-platform/4.2/support/remote_health_monitoring/showing-data-collected-by-remote-health-monitoring.html#showing-data-collected-from-the-cluster_showing-data-collected-by-remote-health-monitoring :)
