### ISSUE TITLE
[enterprise-4.2] Edit suggested in file logging/config/cluster-logging-collector.adoc

### ISSUE THREAD

**Issue by manuvaldi** [openshift/openshift-docs#18369]
### Which section(s) is the issue in?

Viewing logging collector pods

### What needs fixing?
$ oc get pods --all-namespaces -o wide | grep fluentd
instead of: 
$ oc get pods -o wide | grep fluentd

**Comment by ahardin-rh** [comment]
@manuvaldi Thank you for the suggestion! I opened https://github.com/openshift/openshift-docs/pull/18779 and will seek SME and QE approval.
