### ISSUE TITLE
Delete users from htpasswd identity provider in openshift 4

### ISSUE THREAD

**Issue by manimadhu** [openshift/openshift-docs#18376]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.2/authentication/identity_providers/configuring-htpasswd-identity-provider.html

### What needs fixing?

Steps to delete user from htpaaswd

 1. #oc get secret htpasswd-6qh84 -ojsonpath={.data.htpasswd} -n openshift-config | base64 -d | tee htpasswd

 2. Remove the entires from the htpasswd file.
   $ cat htpasswd
     labuser:$xxxxxxxxxxxxxx
    mani:$apxxxxxxxx@          <====  remove the user entry

 3. #oc delete user/mani
 
 4. #oc delete identity/quicklab_htpasswd:mani

 5.  #oc create secret generic htpass-secret --from-file=htpasswd --dry-run -o yaml -n openshift-config | oc replace -f -

 6. wait for the oauth pod get restarts then verify.

**Comment by bergerhoffer** [comment]
Hi @manimadhu thanks for submitting this issue!

It looks like this was also raised in a BZ, so I'm going to close this GitHub issue, and work will be tracked in the BZ instead: https://bugzilla.redhat.com/show_bug.cgi?id=1778362
