### ISSUE TITLE
[enterprise-4.2] Edit suggested in file architecture/architecture.adoc

### ISSUE THREAD

**Issue by rludva** [openshift/openshift-docs#18378]
### Which section(s) is the issue in?
This capability allows your to scale only 
should be:
This capability allows you to scale only

### Which section(s) is the issue in?
OpenShift Container Platform architecture -> Deployment and scaling benefits
https://docs.openshift.com/container-platform/4.2/architecture/architecture.html#deployment-scaling-benefits_architecture

### What needs fixing?
change your to you..

**Comment by jboxman** [comment]
@rludva, thanks for reporting this!
