### ISSUE TITLE
[enterprise-4.2] Edit suggested in file nodes/scheduling/nodes-scheduler-pod-affinity.adoc

### ISSUE THREAD

**Issue by bmillemathias** [openshift/openshift-docs#18389]
### Which section(s) is the issue in?
in the section [Configuring a pod anti-affinity rule](https://docs.openshift.com/container-platform/4.2/nodes/scheduling/nodes-scheduler-pod-affinity.html#nodes-scheduler-pod-anti-affinity-configuring_nodes-scheduler-pod-affinity).

### What needs fixing?
step ` 3.` says
"_Use the `podAffinity` stanza to configure_"
instead of
"_Use the `podAntiAffinity` stanza to configure_"

**Comment by ahardin-rh** [comment]
@bmillemathias Thank you for reporting this! This is now addressed in https://github.com/openshift/openshift-docs/pull/18625
