### ISSUE TITLE
[enterprise-4.2] Edit suggested in file installing/installing_bare_metal/installing-bare-metal.adoc

### ISSUE THREAD

**Issue by kjw3** [openshift/openshift-docs#18429]
### Which section(s) is the issue in?
Creating Red Hat Enterprise Linux CoreOS (RHCOS) machines by PXE or iPXE booting
https://docs.openshift.com/container-platform/4.2/installing/installing_bare_metal/installing-bare-metal.html#installation-user-infra-machines-pxe_installing-bare-metal

### What needs fixing?
At a customer site on older Dell M610 Blades, we saw an issue where the pxe menu items for bootstrap, master and worker while creating the entry like the doc suggests (using HTTP urls for kernel and initramfs files), would cause the pxe menu to just reload itself and take no action.

We believe that instead, the kernel and initramfs files should be put directly on the tftp server. We believe the cause for the failure is that pxelinux.0 does not have drivers for some physical nics that cause the option inability to pull down the kernel and initramfs files over http.

The examples should be changed to have the user place those files directly on the tftp server and then use relative paths from the tftp boot in the pxe menu configs.

**Comment by johnsimcall** [comment]
The Dell M610 blades have Broadcom-based NICs.
