### ISSUE TITLE
OCP 4.4 Release Notes Tracker

### ISSUE THREAD

**Issue by ahardin-rh** [openshift/openshift-docs#18426]
Please leave comments here for anything that should be highlighted in the 4.4 release notes. Thank you!

Draft Preview: https://docs.openshift.com/container-platform/4.4/release_notes/ocp-4-4-release-notes.html

**Comment by deads2k** [comment]
In 4.3 and before, the kube-apiserver checked tokens before client certificates for authentication.  In 4.4 and after, the kube-apiserver will check client-certificates before tokens.  As an example, this means that if you have a system:admin kubeconfig and run `oc --token=foo get pod` in 4.3 that would authenticate as a the user with token foo, in 4.4 and after it will authenticate as system:admin.  The recommendation for many releases has been to use `--as` in such cases instead of overriding the token when using a client-certificate as well.

**Comment by soltysh** [comment]
`oc build-logs` was deprecated in 3.11 (https://github.com/openshift/origin/pull/20322) and we are now removing it entirely from `oc` (https://github.com/openshift/oc/pull/232). Users should use `oc logs` instead.

**Comment by stlaz** [comment]
As stated in 4.1 release notes, the deprecated `/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt` file will be removed in 4.5.

**Comment by soltysh** [comment]
oc's `--config` flag is being deprecated in 4.4, users should start using `--kubeconfig`, instead.
`OS_EDITOR` is also being deprecated in 4.4, users should start using `KUBE_EDITOR` or `EDITOR`, instead.

**Comment by soltysh** [comment]
`oc rsh --timeout` flag is being deprecated in https://github.com/openshift/oc/pull/260, users should use `--request-timeout`, instead.

**Comment by codyhoag** [comment]
The `machineCIDR` network parameter has been deprecated. It's recommended to use `machineNetwork.cidr` instead.

See #19212 for sample entry for release notes.

https://issues.redhat.com/browse/OSDOCS-877

**Comment by soltysh** [comment]
`oc secrets` subcommands (`new`, `new-basicauth`, `new-dockercfg`, `new-sshauth`) were deprecated in 3.9 (https://github.com/openshift/origin/commit/5046e19f71a6480c131fbf6bd19c73b8a9d47018), they are being removed entirely now. Users should use `oc create secret` command, instead.

**Comment by jboxman** [comment]
So for 4.4, we support SCTP. The linux man page hilarious doesn't define the term, but it's _Stream Control Transmission Protocol_. This is a networking/SDN item.

**Comment by bergerhoffer** [comment]
Hopefully should be caught in the fixed issues bug query, but https://bugzilla.redhat.com/show_bug.cgi?id=1806620 should be included in the bug fixes section.

**Comment by codyhoag** [comment]
**Installing a cluster on Microsoft Azure using user-provisioned infrastructure**

OpenShift Container Platform 4.4 introduces support for installing a cluster on Azure using user-provisioned infrastructure. This allows you to deploy your own infrastructure hosted on Azure instead of being forced to use the opinionated installer-provisioned infrastructure. Running user-provisioned infrastructure on Azure lets you use customizations your environment might require, like regulatory, security, and operational control.

You can incorporate example Azure Resource Manager (ARM) templates provided by Red Hat to assist in the deployment process, or reference them to help model your own. You are also free to create the required resources through other methods; the ARM templates are just an example.

See [Installing a cluster on Azure using ARM templates](https://azure-upi--ocpdocs.netlify.com/openshift-enterprise/latest/installing/installing_azure/installing-azure-user-infra.html#installation-creating-azure-vnet_installing-azure-user-infra) (link when published) for details.

**Comment by bergerhoffer** [comment]
**Evicting Pods using the descheduler (Technology Preview)**

The descheduler provides the ability to evict a running Pod so that the Pod can be rescheduled onto a more suitable node.

You can benefit from descheduling Pods in situations such as the following:

- Nodes are underutilized or overutilized.
- Pod and node affinity requirements, such as taints or labels, have changed and the original scheduling decisions are no longer appropriate for certain nodes.
- Node failure requires Pods to be moved.
- New nodes are added to clusters.

See [Evicting Pods using the descheduler](https://docs.openshift.com/container-platform/4.4/nodes/scheduling/nodes-descheduler.html) for more information.

**Comment by vikram-redhat** [comment]
Might need to go into 4.2+ but definitely 4.4. https://bugzilla.redhat.com/show_bug.cgi?id=1814081

**Comment by mmuehlfeldRH** [comment]
I created a PR for a RN, but it still needs to be reviewed:
https://github.com/openshift/openshift-docs/pull/20073#issuecomment-601174814

**Comment by mburke5678** [comment]
Sending cluster logs using the Fluentd syslog plug-in (RFC 3164)
Due to changes introduced with the Log Forwarding feature in {product-title} 4.3, you could no longer use the Fluentd *syslog* plug-in to forward logs to an external syslog server.  
In {product-title} 4.4, this functionality was fixed and you can use the *syslog* plug-in. Note that the procedure for configuring the plug-in has changed. For more information, see xref:../logging/config/cluster-logging-external.html#cluster-logging-collector-syslog_cluster-logging-external[logging/config/cluster-logging-external.html#cluster-logging-collector-syslog_cluster-logging-external].

**Comment by vikram-redhat** [comment]
Upcoming change in license for docs to change to Apache 2.0 from CC BY-SA. - I will follow up with text for this.

**Comment by spadgett** [comment]
We should mention the new monitoring dashboards for console (CONSOLE-1893, Monitoring -> Dashboards in the left nav).

**Comment by jatanmalde** [comment]
With OpenShift 4.4, I see some change with installation format, should we include one such paragraph of it in the release docs. I see etcd-member and etcd-metrics running on the bootstrap and not on the masters as per previous installation methods?

**Comment by sichvoge** [comment]
**Logging**

@mburke5678 Would you agree that the paragraph for syslog should actually move into the "Notable technical changes" section and out from the "New features and enhancements". 

**Monitoring**

As @spadgett already highlighted, it would be nice to mention that we have a new view for dashboards inside the console (the linked epic). 

We have put all the Monitoring related console changes under the "Monitoring" section so far, @spadgett should we continue with that?

**Comment by mburke5678** [comment]
@sichvoge i think it makes sense to move the SENDING CLUSTER LOGS USING THE FLUENTD SYSLOG PLUG-IN (RFC 3164) section to Notable technical changes.

**Comment by qinpingli** [comment]
In OCP 4.4, the RHCOS version should be `Red Hat Enterprise Linux CoreOS release 4.4`, not `as well as Red Hat Enterprise Linux CoreOS 4.3`

**Comment by qinpingli** [comment]
`You must use Red Hat Enterprise Linux CoreOS (RHCOS) for the control plane, or master, machines and can use either RHCOS or Red Hat Enterprise Linux 7.6 or later for compute, or worker, machines.`, the `,` is not needed in `master, machines` and `worker, machines.`

**Comment by zhaozhanqi** [comment]
```
SCTP is a reliable message based protocol that runs on top of an IP network. If your cluster is installed on bare metal infrastructure,
```
do we need to specify `bare metal` here, AFAIK, sctp can work on aws also, not only bare metal 
@weliang1

**Comment by juzhao** [comment]
Table 1. Technology Preview Tracker
User workload monitoring is still TP in 44

**Comment by juzhao** [comment]
section:
Service Catalog, Template Service Broker, Ansible Service Broker, and their Operators

If they are enabled in 4.3
it is better change to
If they are enabled in 4.3 or above version

The following alerts can be viewed from the Monitoring → Alerts page and have a Warning severity
->
it is Monitoring → Alerting page

**Comment by qinpingli** [comment]
in `Table 1. Technology Preview Tracker`
* feature `External provisioner for AWS EFS` should be still TP in 4.4.
* don't know what is the feature `CephFS`, if it means `cephfs-provisioner`, we did not release this in OCP 4.x.
* we did not release `Manila Provisioner` in OCP 4.x either, so I think we should remove it from the table.

@jsafrane  Could you help double confirm?

**Comment by juzhao** [comment]
Known issues,  [1806620](https://bugzilla.redhat.com/show_bug.cgi?id=1806620) is fixed in 4.5, [1814898](https://bugzilla.redhat.com/show_bug.cgi?id=1814898) is the cloned bug fixed in 4.4

**Comment by zhaozhanqi** [comment]
`OVN-Kubernetes Pod network provider` will be GA in 4.5. So 4.4 still be `TP`.

**Comment by barleyer** [comment]
> Known issues, [1806620](https://bugzilla.redhat.com/show_bug.cgi?id=1806620) is fixed in 4.5, [1814898](https://bugzilla.redhat.com/show_bug.cgi?id=1814898) is the cloned bug fixed in 4.4, I don't think we need to mention it now as known issue. @barleyer WDYT?

Ahh right, we dont need to mention it as known issue!

**Comment by wzheng1** [comment]
Per bug https://bugzilla.redhat.com/show_bug.cgi?id=1810461 ,for self-signed OSP 16 cluster, image cannot pull/push to internal image registry without this workaround:  to set  
config.imageregistry/cluster and set spec.disableRedirects = true
This allows the client to pull the image layers from the image registry rather than from links directly from Swift. The Swift CA needs to be added to worker nodes.

**Comment by xiuwang** [comment]
A known issue [1780125](https://bugzilla.redhat.com/show_bug.cgi?id=1780125#c4)
Need config proxy for jenkins deployment behind proxy cluster.

**Comment by wzheng1** [comment]
- git clone operations that go through an HTTPS proxy will fail. Non-TLS (HTTP) proxies can be used successfully. (BZ#1750650)
- git clone via git:// protocol fails behind a proxy [https://bugzilla.redhat.com/show_bug.cgi?id=1751738]

**Comment by wzheng1** [comment]
When using mirror for build, pull secret for mirror registry should not just link to builder serviceaccount, but also add to buildconfig. ([BZ#1810904](https://bugzilla.redhat.com/show_bug.cgi?id=1810904))

**Comment by sunilcio** [comment]
In Technology Preview features table, can we add more info on features which do not have any marker TP, GA or -(Depricated) and are blank?

https://docs.openshift.com/container-platform/4.4/release_notes/ocp-4-4-release-notes.html#ocp-4-4-technology-preview

**Comment by gpei** [comment]
OpenStack is adding UPI to the OCP 4.4 release https://issues.redhat.com/browse/CORS-1308

**Comment by jsafrane** [comment]
> feature External provisioner for AWS EFS should be still TP in 4.4.
I think we want to remove the feature completely. Or did you test it in 4.4.? @qinpingli 

> don't know what is the feature CephFS, if it means cephfs-provisioner, we did not release this in OCP 4.x.
Again, in-tree ceph is not supported. To be replaced with CSI later.

> we did not release Manila Provisioner in OCP 4.x either, so I think we should remove it from the table.

Should we *remove* items when they become unsupported or leave them blank for the readers to see the change?

**Comment by codyhoag** [comment]
@qinpingli @jsafrane we made the decision to carry over everything from our 4.3 TP table, iterating the versions by one to reflect 4.2-4.4 statuses, and adding any additional features introduced in 4.4. This decision was made to show unsupported features and to see their changes.

CephFS (i.e., cephfs-provisioner) and Manila Provisioner are both listed as TP in 4.2/4.3. Is this correct, and will it continue to be TP for 4.4?

**Comment by weliang1** [comment]
> ```
> SCTP is a reliable message based protocol that runs on top of an IP network. If your cluster is installed on bare metal infrastructure,
> ```
> 
> do we need to specify `bare metal` here, AFAIK, sctp can work on aws also, not only bare metal
> @weliang1

@zhaozhanqi @jboxman 
"Bare Metal" is already removed from https://github.com/openshift/openshift-docs/pull/20036/files

**Comment by s-urbaniak** [comment]
For cluster monitoring we have the following changes for 4.4:

- node-exporter: disabled unused `hwmon` collector
- cluster-reader role can now read node metrics by default
- new cluster alerts:
  - `MultipleContainersOOMKilled`: Fires when multiple containers were out of memory killed within the past 15 minutes.
- new api server alerts:
  - `ErrorBudgetBurn`: Fires when api server issues 5xx request responses.
  - `AggregatedAPIErrors`: Fires when the number of errors have increased for aggregated api servers.
- prometheus-operator: tightened permissions scoped at CRDs under its jurisdiction.

Version changes:
- prometheus: version upgrade from 2.14.0 to 2.15.2
- alertmanager: version upgrade from 0.19.0 to 0.20.0
- prometheus-operator: version upgrade from 0.34.0 to 0.35.1
- kube-state-metrics: version upgrade from 1.8.0 to 1.9.5
- grafana: version upgrade from 6.4.3 to 6.5.3

cc @lilic @sichvoge

**Comment by qinpingli** [comment]
> @qinpingli @jsafrane we made the decision to carry over everything from our 4.3 TP table, iterating the versions by one to reflect 4.2-4.4 statuses, and adding any additional features introduced in 4.4. This decision was made to show unsupported features and to see their changes.
> 
> CephFS (i.e., cephfs-provisioner) and Manila Provisioner are both listed as TP in 4.2/4.3. Is this correct? If so, will it continue to be TP for 4.4?

@codyhoag cephfs-provisioner and manila provisioner did not support in 4.2 and 4.3 either.

**Comment by qinpingli** [comment]
> > feature External provisioner for AWS EFS should be still TP in 4.4.
> > I think we want to remove the feature completely. Or did you test it in 4.4.? @qinpingli
> 
> > don't know what is the feature CephFS, if it means cephfs-provisioner, we did not release this in OCP 4.x.
> > Again, in-tree ceph is not supported. To be replaced with CSI later.
> 
> > we did not release Manila Provisioner in OCP 4.x either, so I think we should remove it from the table.
> 
> Should we _remove_ items when they become unsupported or leave them blank for the readers to see the change?

@chao007 Did we test efs-provisioner in OCP4.x?

**Comment by Preeticp** [comment]
Web console>DEVELOPER PERSPECTIVE
You can now use the Developer perspective to edit applications in the *Topology* view, monitor application metrics using the *Monitoring* view, and create Helm releases from the Helm charts provided in the *Developer Catalog*.

**Comment by spadgett** [comment]
> We have put all the Monitoring related console changes under the "Monitoring" section so far, @spadgett should we continue with that?

@sichvoge works for me

**Comment by emmajiafan** [comment]
OCP 4.4 doesn't release ansible broker anymore. So I think the install&config&uninstall openshift ansible broker is not necessary . what do you think ?@cuipinghuo

**Comment by cuipinghuo** [comment]
> OCP 4.4 doesn't release ansible broker anymore. So I think the install&config&uninstall openshift ansible broker is not necessary . what do you think ?@cuipinghuo

yes, no need for asb.

**Comment by chao007** [comment]
> chao

We did not test efs-provisioner in OCP4.x

**Comment by chao007** [comment]
> > > feature External provisioner for AWS EFS should be still TP in 4.4.
> > > I think we want to remove the feature completely. Or did you test it in 4.4.? @qinpingli
> > 
> > 
> > > don't know what is the feature CephFS, if it means cephfs-provisioner, we did not release this in OCP 4.x.
> > > Again, in-tree ceph is not supported. To be replaced with CSI later.
> > 
> > 
> > > we did not release Manila Provisioner in OCP 4.x either, so I think we should remove it from the table.
> > 
> > 
> > Should we _remove_ items when they become unsupported or leave them blank for the readers to see the change?
> 
> @chao007 Did we test efs-provisioner in OCP4.x?

We did not test efs-provisioner in OCP4.x

**Comment by yapei** [comment]
Shall we add Marketplace integration in Operator Hub as a notable feature in 4.4 ? the features brought in [CONSOLE-1953](https://issues.redhat.com/browse/CONSOLE-1953) and [CONSOLE-1971](https://issues.redhat.com/browse/CONSOLE-1971)

**Comment by jianzhangbjz** [comment]
@ecordell For the introduction of the [opm](https://docs.openshift.com/container-platform/4.4/release_notes/ocp-4-4-release-notes.html#ocp-4-4-deprecation-of-operatorsources), seems like some changes for the structure of the `Bundle`. I remember we don't use the `manifest` directory before, `YAML` files and `metadata` are in the same level.
```
/
├── manifests
│   ├── etcdcluster.crd.yaml
│   └── etcdoperator.clusterserviceversion.yaml
└── metadata
    └── annotations.yaml
```
If we use the `manifest` directory, will get the `no yaml files` error when running `./opm alpha bundle build`.
```console
mac:operator-registry jianzhang$ tree test-manifests/etcd/0.9.0/
test-manifests/etcd/0.9.0/
├── manifest
│   ├── Dockerfile
│   ├── etcdbackups.etcd.database.coreos.com.crd.yaml
│   ├── etcdclusters.etcd.database.coreos.com.crd.yaml
│   ├── etcdoperator.v0.9.0.clusterserviceversion.yaml
│   └── etcdrestores.etcd.database.coreos.com.crd.yaml
└── metadata
    └── annotations.yaml

mac:operator-registry jianzhang$ ./opm alpha bundle build -d test-manifests/etcd/0.9.0/ -t quay.io/example/etcd:0.9.0 --package etcd -c alpha -e alpha
Error: The directory test-manifests/etcd/0.9.0/ contains no yaml files
Usage:
  opm alpha bundle build [flags]
```
It works well when remove the `manifest` directory, as follows:
```console
mac:0.9.0 jianzhang$ tree
.
├── Dockerfile
├── etcdbackups.etcd.database.coreos.com.crd.yaml
├── etcdclusters.etcd.database.coreos.com.crd.yaml
├── etcdoperator.v0.9.0.clusterserviceversion.yaml
├── etcdrestores.etcd.database.coreos.com.crd.yaml
└── metadata
    └── annotations.yaml

1 directory, 6 files

./opm alpha bundle build -d test-manifests/etcd/0.9.0/ -t quay.io/example/etcd:0.9.0 --package etcd -c alpha -e alpha
INFO[0000] Building annotations.yaml                    
INFO[0000] An annotations.yaml already exists in directory 
INFO[0000] Validating existing annotations.yaml  
...
```
Besides, for previous [manifests](https://github.com/openshift/cluster-logging-operator/tree/master/manifests), they all contain the [package YAML](https://github.com/openshift/cluster-logging-operator/blob/master/manifests/cluster-logging.package.yaml), but for this manifest of the `Bundle`, it doesn't need the package YAML. We should explain this point.

**Comment by emmajiafan** [comment]
https://docs.openshift.com/container-platform/4.4/release_notes/ocp-4-4-release-notes.html#ocp-4-4-service-catalog-deprecated

**Comment by xingxingxia** [comment]
Shall we add **[MSTR-880](https://issues.redhat.com/browse/MSTR-880), MSTR-933 and MSTR-893** as notable features in 4.4?

**Comment by emmajiafan** [comment]
Since ansible service broker is deleted in OCP 4.4 , should delete the install&config&uninstall openshift ansible broker. And mentioned in https://docs.openshift.com/container-platform/4.4/release_notes/ocp-4-4-release-notes.html#ocp-4-4-service-catalog-deprecated that  AnsibleServiceBroker and .osb.openshift.io/v1 have already removed . And Service Catalog and Template Service Broker should be "GA" in OCP 4.3,4.4. OpenShift Ansible Service Broker should be "GA" in OCP 4.3.

**Comment by cuipinghuo** [comment]
> Since ansible service broker is deleted in OCP 4.4 , should delete the install&config&uninstall openshift ansible broker.
> And mentioned in https://docs.openshift.com/container-platform/4.4/release_notes/ocp-4-4-release-notes.html#ocp-4-4-service-catalog-deprecated that AnsibleServiceBroker and .osb.openshift.io/v1 have already removed .
> And Service Catalog and Template Service Broker should be "GA" in OCP 4.3,4.4. OpenShift Ansible Service Broker should be "GA" in OCP 4.3.

@shawn-hurley besides what have mentioned above about asb, for https://docs.openshift.com/container-platform/4.4/applications/service_brokers/installing-template-service-broker.html ```Create a namespace.

Navigate in the web console to Administration → Namespaces and click Create Namespace.

Enter openshift-template-service-broker in the Name field and click Create.```  We should also add label for Namespace as Enter openshift-ansible-service-broker in the Name field and openshift.io/cluster-monitoring=true in the Labels field and click Create.

**Comment by emmajiafan** [comment]
And mentioned in https://docs.openshift.com/container-platform/4.4/release_notes/ocp-4-4-release-notes.html#ocp-4-4-service-catalog-deprecated that service catalog can't enable in the cluster with kury because this bug: https://bugzilla.redhat.com/show_bug.cgi?id=1821589 .

**Comment by adambkaplan** [comment]
Samples are not installed by default if the samples operator cannot connect to `registry.redhat.io` during installation.

https://issues.redhat.com/browse/DEVEXP-507

**Comment by adambkaplan** [comment]
New `ImagePruner` resource lets admins manage a new CronJob that automatically prunes images from the cluster. This is installed by default on new clusters.

https://issues.redhat.com/browse/DEVEXP-472

**Comment by adambkaplan** [comment]
`Build` objects now report conditions in their status.

https://issues.redhat.com/browse/DEVEXP-526

**Comment by adambkaplan** [comment]
Image registry can use the `Recreate` rollout strategy during upgrades. This allows the image registry to use "Block" storage types like EBS on AWS.

https://issues.redhat.com/browse/DEVEXP-523

**Comment by bergerhoffer** [comment]
> Shall we add **[MSTR-893](https://issues.redhat.com/browse/MSTR-893)** as notable feature in 4.4 release notes?

Thanks @xingxingxia, this is being addressed by #21160.

**Comment by jhou1** [comment]
OCP on RHV is to be released in 4.4, here is a list of bugs to show that machine-api integration on RHV isn't customer ready. I think these bugs need to be listed as **known bugs** and we tell customer that machine-api on RHV isn't working properly in 4.4.
- https://bugzilla.redhat.com/show_bug.cgi?id=1815394
- https://bugzilla.redhat.com/show_bug.cgi?id=1815435
- https://bugzilla.redhat.com/show_bug.cgi?id=1817853
- https://bugzilla.redhat.com/show_bug.cgi?id=1822118

**Comment by wsun1** [comment]
Add one known issue:
OSP 16 kuryr will not work until https://bugzilla.redhat.com/show_bug.cgi?id=1812009 is  fixed from OSP 16 side

**Comment by maxwelldb** [comment]
**Installing a cluster on Red Hat OpenStack Platform no longer requires the Swift object storage service**

Beginning with version 4.4, {product-title} no longer requires that the Swift object storage service be present on the {rh-openstack} cloud where it is installed. If Swift is not available and configured for {product-title} installation, the installation program uses the Cinder block storage and Glance image registry services, instead. 

For more information, see Installing a cluster on OpenStack using your own infrastructure (link when published).

**Comment by maxwelldb** [comment]
**Clusters that are installed on Red Hat OpenStack Platform now support self-signed certificates**

{product-title} 4.4 may now be installed on {rh-openstack} clouds that use self-signed certificates for authorization.

For more information, see [Installing a cluster on OpenStack using your own infrastructure](https://ssc-osasinfra1122--ocpdocs.netlify.com/openshift-enterprise/latest/installing/installing_openstack/installing-openstack-installer-custom.html#installation-osp-describing-cloud-parameters_installing-openstack-installer-custom) (link when published).

**Comment by adellape** [comment]
@emmajiafan @cuipinghuo Per earlier comments:

* Removed Ansible Service Broker docs: https://github.com/openshift/openshift-docs/pull/21295
* Carried over the 4.3 release note "Service Catalog, Template Service Broker, Ansible Service Broker, and their Operators" and updated it for 4.4: https://github.com/openshift/openshift-docs/pull/21294
* Still need to update https://docs.openshift.com/container-platform/4.3/applications/service_brokers/provisioning-template-application.html, however, because it mentions using Ansible Service Broker for the example. Will look at switching to Template Service Broker for the example.
* Also will sync with @jmrodri about adding https://bugzilla.redhat.com/show_bug.cgi?id=1821589 as a Known Issue.

@juzhao Also from earlier:

> Service Catalog, Template Service Broker, Ansible Service Broker, and their associated Operators were deprecated in OpenShift Container Platform 4.2 and will be removed in a future OpenShift Container Platform release. If they are enabled in 4.3
> 
> will be removed in a future OpenShift Container Platform release
> it is better change to
> is removed from 4.3 and above version

My understanding is only they're only labeled as deprecated in 4.2 and above, and now in 4.4 only ASB is actually removed.

**Comment by shawn-hurley** [comment]
> My understanding is they're labeled as deprecated in 4.2 and above, but now in 4.4 ASB is the only one that is actually removed.

+1

**Comment by sreber84** [comment]
I think information should be added about `haproxy` 2.0 coming and `dns` forwarding capabilities.

**Comment by emmajiafan** [comment]
@adellape  Yes, your understand is exactly right. 
Only ''Service Catalog" "Template Service Broke" "OpenShift Ansible Service Broker"  GA for OCP 4.2 & OCP 4.3.  ''Service Catalog" "Template Service Broke" GA for OCP 4.4.

**Comment by mburke5678** [comment]
Cluster Resource Override Opertator
{product-title} administrators can control the level of overcommit and manage container density on nodes. You can configure cluster-level overcommit using the Cluster Resource Override Operator to override the ratio between requests and limits set on developer containers.
https://github.com/openshift/openshift-docs/pull/21319

**Comment by sdodson** [comment]
Upgrades from 4.3.15 or later to 4.4.0 will be available in the fast channel at GA. Based on telemetry data collected after the release upgrades from 4.3 will be promoted into the stable channel approximately 2-4 weeks later.

**Comment by adellape** [comment]
@jianzhangbjz @ecordell 

> @ecordell For the introduction of the [opm](https://docs.openshift.com/container-platform/4.4/release_notes/ocp-4-4-release-notes.html#ocp-4-4-deprecation-of-operatorsources), seems like some changes for the structure of the `Bundle`. I remember we don't use the `manifest` directory before, `YAML` files and `metadata` are in the same level.

After discussion with PM and GSS, this has been truncated in the OCP 4.4 release notes, with a link to the OKD docs for this additional info including the bundle structure:

https://docs.openshift.com/container-platform/4.4/release_notes/ocp-4-4-release-notes.html#ocp-4-4-deprecation-of-operatorsources

https://docs.okd.io/latest/operators/understanding_olm/olm-understanding-olm.html#olm-new-bundle-opm_olm-understanding-olm

I haven't updated the bundle structure per latest comments yet, awaiting confirmation. Please LMK!

**Comment by mburke5678** [comment]
Known Issue:
During an update to cluster logging from 4.3 to 4.4, the Elasticsearch pods might get stuck in CrashLoopBackOff status. You can workaround this issue by deleting the Elasticsearch deployments in sequence.
https://bugzilla.redhat.com/show_bug.cgi?id=1824006

**Comment by anpingli** [comment]
@mburke5678  Thanks

**Comment by sheriff-rh** [comment]
4.4 is now live. Thanks all!
4.5 release notes tracker is here: 
https://github.com/openshift/openshift-docs/issues/19847
