### ISSUE TITLE
metrics documentation refers to incorrect storage access mode based on PVC in template

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-docs#1842]
https://docs.openshift.com/enterprise/latest/install_config/cluster_metrics.html#metrics-persistent-storage

This is incorrect. Currently upstream metrics requires a RWX. We need to confirm which template we're using and make sure that the documented installation procedure recommends the correct volume type.

**Comment by mburke5678** [comment]
@thoraxe Is this still an issue? 
"For cluster metrics to work with persistent storage, ensure that the persistent volume has the ReadWriteOnce access mode. "

**Comment by thoraxe** [comment]
I guess not? You probably need to ask someone from the metrics team...

**Comment by mwringe** [comment]
We switched a while ago to be using ReadWriteOnce only.

**Comment by mburke5678** [comment]
@thoraxe @mwringe Closing this issue based on Matthew's comment. Please advise if I am reading his comment incorrectly.
