### ISSUE TITLE
registry installation docs should prefer object storage and describe how to configure it

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-docs#1843]

**Comment by aweiteka** [comment]
Related to this is a question on how much of the upstream registry config file do we support. Since storage drivers are configured through that config file your concern may get better treatment when the broader config story is updated.

**Comment by thoraxe** [comment]
@smarterclayton

**Comment by smarterclayton** [comment]
@adellape @sdodson @pweil- @miminar this documentation is pretty important to have.

**Comment by aweiteka** [comment]
I'll take this.

**Comment by miminar** [comment]
Object storage? Like S3? Is #1900 what you're looking for?

**Comment by mburke5678** [comment]
@thoraxe @smarterclayton 
Has this issue been addressed in the docs? There has been additions around registry storage:
https://docs.openshift.org/latest/install_config/registry/deploy_registry_existing_clusters.html#storage-for-the-registry

**Comment by thoraxe** [comment]
The list of supported drivers is now there, but only one of the object stores (S3) is documented. What about Google and etc?

**Comment by mburke5678** [comment]
Opened https://bugzilla.redhat.com/show_bug.cgi?id=1480364

Closing this issue.
