### ISSUE TITLE
[enterprise-Branch Build] Edit suggested in file installing/installing-fips.adoc

### ISSUE THREAD

**Issue by pdhamdhe** [openshift/openshift-docs#18430]
### Which section(s) is the issue in?

http://file.rdu.redhat.com/kalexand/120519/osdocs617/installing/installing-fips.html#installation-about-fips-validation_installing-fips

### What needs fixing?

In Table 1: FIPS mode attributes and limitations in OpenShift Container Platform Branch Build
the following statement has been written in first Attributes which needs to be correct.

Statement :  FIPS compliant operating systems: RHEL 7 and RHCOS 8.

Correct Statement would be : FIPS compliant operating systems: RHEL 7 and RHCOS.

Evidences:

o RHOCP version

$ oc version
Client Version: openshift-clients-4.2.1-201910220950
Server Version: 4.3.0-0.nightly-2019-12-04-004448
Kubernetes Version: v1.16.2

o RHCOS release
sh-4.4# cat /etc/redhat-release 
Red Hat Enterprise Linux CoreOS release 4.3

**Comment by kalexand-rh** [comment]
I'm incorporating this change onto the linked PR. Thanks!
