### ISSUE TITLE
Can we remove the SSH requirement from the backup_and_restore section?

### ISSUE THREAD

**Issue by etsauer** [openshift/openshift-docs#18468]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.2/backup_and_restore/

### What needs fixing?

The message around the value of RHCOS is that it is so slim, minimal, and operator driven that most organizations should be able to disable SSH and have all management activities in the OS be facilitated through the platform. However, some of our Day 2 documentation, such as backup and restore, cites that SSH is required to do these steps.

I believe there are alternatives we could suggest that better aligns with the RHCOS value prop.  One such solution could be to use `oc debug node` as the entrypoint to perform these activities. For example:

```
$ oc debug node/master0.ocp42.acme.bz
Starting pod/master0ocp42acme.bz-debug ...
To use host binaries, run `chroot /host`
Pod IP: 192.168.5.52
If you don't see a command prompt, try pressing enter.

sh-4.2# chroot /host
sh-4.4# cd /tmp
sh-4.4# /usr/local/bin/etcd-snapshot-backup.sh /tmp/snapshot.db
Downloading etcdctl binary..
etcdctl version: 3.3.10
API version: 3.3
Trying to backup etcd client certs..
etcd client certs already backed up and available ./assets/backup/
etcd-member.yaml found in ./assets/backup/
Snapshot saved at /tmp/snapshot.db

sh-4.4# ls
assets									    snapshot.db
machine-config-daemon.master0.unknownuser.log.INFO.20191122-220804.3382     systemd-private-7037522579524b30834545a69c00d9f7-chronyd.service-iFPqYx
machine-config-daemon.master0.unknownuser.log.WARNING.20191122-220804.3382

sh-4.4# rsync -avr /tmp/snapshot.db root@192.168.1.10:/mnt/volume2/security
root@192.168.1.10's password: 
sending incremental file list
snapshot.db

sent 58,861,718 bytes  received 35 bytes  13,080,389.56 bytes/sec
total size is 58,847,264  speedup is 1.00
```

Additional valuable suggestions could be around providing options to automate this task through a simple CronJob solution.

**Comment by vikram-redhat** [comment]
@bergerhoffer - thoughts on this?

**Comment by bergerhoffer** [comment]
@hexfusion @retroflexer Is SSH still required for these backup/DR procedures, or are there alternative methods we could look into using in our docs (as suggested in the description above)?

**Comment by bergerhoffer** [comment]
@vikram-redhat We can probably close this issue. We already have a BZ open questioning this: https://bugzilla.redhat.com/show_bug.cgi?id=1774389

FYI @etsauer in case you want to follow that BZ.

**Comment by etsauer** [comment]
@bergerhoffer ok thanks, I left a comment in the BZ, so if you'd rather track there, I'm fine closing this issue.
