### ISSUE TITLE
[enterprise-4.2] Edit suggested in file metering/metering-usage-examples.adoc

### ISSUE THREAD

**Issue by jaxx0r** [openshift/openshift-docs#18485]
### Which section(s) is the issue in?
Cron Example code in https://docs.openshift.com/container-platform/4.2/metering/metering-usage-examples.html#metering-cluster-utilization-examples_metering-usage-examples

### What needs fixing?
Indentation of line 9 needs to be one level lower
Copy&Paste of the example gives the following error:
"Error parsing YAML: YAMLException: bad indentation of a mapping entry at line 9, column 7:
          expression: "0 0 * * 1-5" 
          ^
"
This is accepted by the parser:
"
spec:
  query: cluster-cpu-utilization
  schedule:
    period: cron
    expression: 0 0 * * 1-5
"

**Comment by ahardin-rh** [comment]
@jaxx0r Thank you for reporting this! Does this resolve the issue?
https://github.com/openshift/openshift-docs/pull/18486

**Comment by jaxx0r** [comment]
@ahardin-rh thanks for the swift response, sorry I think in my initial comment copy&paste removed one indent level too much. We only need to remove two blanks in the line of expression, the other indent was perfect.

spec:
  query: cluster-cpu-utilization
  schedule:
    period: cron
    expression: 0 0 * * 1-5

**Comment by ahardin-rh** [comment]
@jaxx0r Thanks for clarifying! I made an update. Please let me know if further adjustments are needed: https://github.com/openshift/openshift-docs/pull/18486

**Comment by jaxx0r** [comment]
@ahardin-rh Thank you, this looks ok now :)

**Comment by ahardin-rh** [comment]
@jaxx0r Awesome. Thanks! Merging :smile:
