### ISSUE TITLE
[enterprise-4.2] Edit suggested in file networking/multiple-networks/understanding-multiple-networks.adoc

### ISSUE THREAD

**Issue by rmahroua** [openshift/openshift-docs#18498]
### Which section(s) is the issue in?
Understanding multiple networks

### What needs fixing?
> OpenShift Container Platform uses the Multus CNI plug-in to allow
chaining of CNI plug-ins. During cluster installation, you configure
your default Pod network. The default network handles all routine
network traffic for the cluster. You can define an additional network
based on the available CNI plug-ins and attach one or more of these
networks to your Pods. You can define more than one additional network
for your cluster, depending on your needs.

Should read (s/routine/routing/)
> OpenShift Container Platform uses the Multus CNI plug-in to allow
chaining of CNI plug-ins. During cluster installation, you configure
your default Pod network. The default network handles all **routing**
network traffic for the cluster. You can define an additional network
based on the available CNI plug-ins and attach one or more of these
networks to your Pods. You can define more than one additional network
for your cluster, depending on your needs.

Unless routine is the right word - as in 'usual'?

**Comment by ahardin-rh** [comment]
@rmahroua Thank you for your feedback! This is now addressed in https://github.com/openshift/openshift-docs/pull/18622. I discussed this with the original author and we believe "ordinary" is more precise. Thanks again!
