### ISSUE TITLE
[enterprise-4.2] Edit suggested in file installing/install_config/configuring-firewall.adoc

### ISSUE THREAD

**Issue by radekvokal** [openshift/openshift-docs#18529]
### Which section(s) is the issue in?
Red Hat Insights 

### What needs fixing?
insights-operator needs additional endpoint - https://cloud.redhat.com/api/ingress

**Comment by ahardin-rh** [comment]
@radekvokal Thank you for raising this! Does this pull request fulfill your request? https://github.com/openshift/openshift-docs/pull/18547 

Please let me know if any adjustments are needed. Thank you again!
