### ISSUE TITLE
Document pushing build to external insecure registry

### ISSUE THREAD

**Issue by aweiteka** [openshift/openshift-docs#1859]
Some users want to push their images to an external registry that is insecure. The docker daemon `--insecure-registry=...` setting must be configured for each build node in `/etc/sysconfig/docker`.

**Comment by ahardin-rh** [comment]
Looks like this is now documented in the [Securing and Exposing the Registry](https://docs.openshift.com/container-platform/3.6/install_config/registry/securing_and_exposing_registry.html) docs. Closing this, but feel free to reopen if you feel like more information is needed. Thanks!
