### ISSUE TITLE
No oc apply description

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/openshift-docs#1868]
There's no mention of "oc apply" at https://docs.openshift.org/latest/cli_reference/basic_cli_operations.html which is a command to be used to update existing resource definitions.

See: https://github.com/openshift/origin/issues/8387

**Comment by MarkRx** [comment]
For reference if anyone comes across this - the kubernetes apply command doc is here: https://kubernetes.io/docs/user-guide/kubectl/v1.5/#apply. I would imagine the oc apply command would act similiar.

**Comment by mburke5678** [comment]
Added to https://bugzilla.redhat.com/show_bug.cgi?id=1477765

**Comment by dmoebius** [comment]
In https://bugzilla.redhat.com/show_bug.cgi?id=1477765 I don't see any mentioning of `oc apply` or any reference to this issue here, so I fear that the whole thing got lost.
2½ years later and the OKD docs still have no proper docs for `oc apply`!

**Comment by mburke5678** [comment]
@dmoebius `oc apply` is currently in the CLI guide:
https://docs.okd.io/latest/cli_reference/openshift_cli/developer-cli-commands.html#apply

It seems to have been added November 2018: https://github.com/openshift/openshift-docs/pull/12726/files#diff-9aec59d43f8d745a066ed53cadc27e83R616-R621

**Comment by dmoebius** [comment]
@mburke5678 thanks for the pointer, wasn't aware of this. It's missing in the 3.11 docs. But it's a bit scarce, isn't it? Given that `apply` is the most important and powerful command for handling config changes to templates and deployments. Anyway, that's not the topic of this ticket. Case closed.
