### ISSUE TITLE
[enterprise-4.2] Edit suggested in file installing/installing_vsphere/installing-vsphere.adoc

### ISSUE THREAD

**Issue by suulperi** [openshift/openshift-docs#18732]
### Which section(s) is the issue in?
Load balancers
Before you install OpenShift Container Platform, you must provision two layer-4 load balancers. The API requires one load balancer and the default Ingress Controller needs the second load balancer to provide ingress to applications.

### What needs fixing?
Why layer-4 load balancers? If I have not misunderstood all traffic related to OpenShift through load balancers is based on http(s), so we should recommend to use L7 LBs.  Then customers could use for example Web Application Firewall on LB level as well.

**Comment by ahardin-rh** [comment]
@Miciah Can you please help provide clarification, or point me in the right direction? Thank you!
