### ISSUE TITLE
[enterprise-4.2] Edit suggested in file logging/config/cluster-logging-configuring-about.adoc

### ISSUE THREAD

**Issue by xcoulon** [openshift/openshift-docs#18900]
### Which section(s) is the issue in?

About deploying and configuring cluster logging

### What needs fixing?

replace 
```
The following describes the configurations you can make when installing your cluster logging instance or modify after installtion.
``` 
with 
```
The following describes the configurations you can make when installing your cluster logging instance or modify after installation.
``` 
-> typo in `installation` at the end of the sentence.

**Comment by codyhoag** [comment]
@xcoulon thanks for pointing this out! I provided the fix here: https://github.com/openshift/openshift-docs/pull/19313

**Comment by xcoulon** [comment]
thanks @codyhoag!
