### ISSUE TITLE
Suggestions on OSE Secrets documentation

### ISSUE THREAD

**Issue by thescouser89** [openshift/openshift-docs#1895]
The OSE secrets documentation (found [here](https://docs.openshift.com/enterprise/3.0/dev_guide/secrets.html)) does not mention that the value of the secrets have to be base64 encoded.

Another suggestion would be to also say that we can mount those secrets in the deployment config, instead of just showing an example of mounting it into a pod.

**Comment by mburke5678** [comment]
Using Secrets
"The value associated with keys in the the data map must be base64 encoded."

Adding Secrets to Deployment Configurations from the Web Console
https://docs.openshift.com/container-platform/3.6/dev_guide/deployments/basic_deployment_operations.html#adding-secrets-to-deployment-config
