### ISSUE TITLE
Incomplete persistentVolumeClaim example

### ISSUE THREAD

**Issue by brennv** [openshift/openshift-docs#1911]
The docs here make reference to all 3 of the variables used when making a PVC:
https://docs.openshift.com/enterprise/3.0/dev_guide/persistent_volumes.html

The docs here also describe a PVC but the examples only make use of 2/3 of the variables:
https://docs.openshift.com/enterprise/3.1/rest_api/kubernetes_v1.html#v1-persistentvolumeclaimspec

Submitted PRs for 3.0 https://github.com/openshift/openshift-docs/pull/1907 and 3.1 https://github.com/openshift/openshift-docs/pull/1910

**Comment by vikram-redhat** [comment]
Closing issue as the submitted PRs were merged long ago.
