### ISSUE TITLE
[enterprise-4.2] Edit suggested in file scalability_and_performance/recommended-host-practices.adoc

### ISSUE THREAD

**Issue by rbaumgar** [openshift/openshift-docs#19115]
### Which section(s) is the issue in?
Recommended etcd practices

### What needs fixing?
If we recommend to defragment etcd shouldn't we document how to to this?
Or much better should OpenShift raise an alarm?
Or much much better should OpenShift defragement etcd automatically? by an operator?

Kind regards

**Comment by hexfusion** [comment]
This should be a doc bug if its not already

**Comment by retroflexer** [comment]
With cluster-etcd-operator operational in 4.4, the defrag happens automatically whenever a pod restarts. We will add the needed documentation.

**Comment by rbaumgar** [comment]
@retroflexer do we have somewhere the documentation?

**Comment by hexfusion** [comment]
This feature was never added to 4.4.

**Comment by hexfusion** [comment]
4.2 is EOL we are creating a bug to track.

**Comment by retroflexer** [comment]
We are tracking this using this bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1882405

We will get it into 4.6.
