### ISSUE TITLE
Need General Backup/Restore Doc

### ISSUE THREAD

**Issue by danmcp** [openshift/openshift-docs#1912]
There is a backup and restore section in here:

https://access.redhat.com/sites/default/files/attachments/openshiftenterprise3architectureguide.pdf

That lists what needs to be backed up for the masters.  

Here is the restore process for etcd:

https://docs.openshift.com/enterprise/3.1/install_config/downgrade.html#downgrading-restoring-etcd

But we could use a nice all in one section in the OpenShift docs about backup/restore.

**Comment by adellape** [comment]
Here's where that effort left off:

Bug 1259544 - [DOCS] Document backup and restore procedures
https://bugzilla.redhat.com/show_bug.cgi?id=1259544#c9

**Comment by mburke5678** [comment]
There is a full section on backup and restore. 
https://docs.openshift.com/container-platform/3.6/admin_guide/backup_restore.html

Closing this issue. @danmcp feel free to re-open, if needed.
