### ISSUE TITLE
[enterprise-4.2] Edit suggested in file operators/olm-what-operators-are.adoc

### ISSUE THREAD

**Issue by miyadav** [openshift/openshift-docs#19185]
### Which section(s) is the issue in?

Operators

### What needs fixing?

grammer or text 

"How do Operators compare with Service Brokers?
A Service Broker is a step towards programmatic discovery and deployment of an app. However, because it is not a long running process, it cannot execute **Day 2** operations like upgrade, failover, or scaling. Customizations and parameterization of tunables are provided at install time, versus an Operator that is constantly watching your cluster’s current state. Off-cluster services continue to be a good match for a Service Broker, although Operators exist for these as well."

**Comment by jboxman** [comment]
@adellape, is this still valid?
