### ISSUE TITLE
Helm lint shows errors

### ISSUE THREAD

**Issue by siamaksade** [openshift/openshift-docs#19202]
Following the Helm docs: 
https://github.com/openshift/openshift-docs/blob/master/modules/helm-creating-a-custom-helm-chart-on-openshift.adoc

Step 5 gives the following error:
```
$ helm lint
==> Linting .
[ERROR] Chart.yaml: directory name (nodejs-ex-k) and chart name (Node.js) must be the same
[INFO] Chart.yaml: icon is recommended

Error: 1 chart(s) linted, 1 chart(s) failed
```

Step 4 should be edited to only update the description:
```
description: A Helm chart for OpenShift
```

**Comment by boczkowska** [comment]
PR with the bugfix. https://github.com/openshift/openshift-docs/pull/19604
QE has verified that this is the proper solution. We decided to leave the fields such as `apiVersion` and `name` but added callouts that explain the respective fields in more detail.
