### ISSUE TITLE
[enterprise-4.3] Edit suggested in file nodes/scheduling/nodes-scheduler-default.adoc

### ISSUE THREAD

**Issue by kasturinarra** [openshift/openshift-docs#19283]
### Which section(s) is the issue in?
Understanding the scheduler predicates 

### What needs fixing?
In the section Other Static Predicates i see CheckNodeMemoryPressure, CheckNodeDiskPressure but they have been practically deprecated since TaintNodeByConditions was in Beta (since 1.12)" so these needs to be removed.

Git Hub links where these were removed : https://github.com/kubernetes/kubernetes/issues/84100
https://github.com/kubernetes/kubernetes/pull/84152

Also by https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/#taint-based-evictions, CheckNodeMemoryPressure is replaced by node.kubernetes.io/memory-pressure taint.

**Comment by mburke5678** [comment]
@kasturinarra Thank you for pointing this out. See my changes in https://github.com/openshift/openshift-docs/pull/20096
