### ISSUE TITLE
Remove step from oidc auth docs

### ISSUE THREAD

**Issue by wgordon17** [openshift/openshift-docs#19302]
### Which section(s) is the issue in?
"Adding an identity provider to your clusters"
* GitHub: https://docs.openshift.com/container-platform/4.2/authentication/identity_providers/configuring-github-identity-provider.html#add-identity-provider_configuring-github-identity-provider
* Google: https://docs.openshift.com/container-platform/4.2/authentication/identity_providers/configuring-google-identity-provider.html#add-identity-provider_configuring-google-identity-provider
* OpenID: https://docs.openshift.com/container-platform/4.2/authentication/identity_providers/configuring-oidc-identity-provider.html#add-identity-provider_configuring-oidc-identity-provider

### What needs fixing?
This section on the above docs mention testing login with `$ oc login -u <username>`. This step is *ONLY* valid if the `challenge: true` configuration is supported for the IdP backend. The above IdP's do not support `challenge: true`:
* GitHub: https://github.com/openshift/cluster-authentication-operator/blob/master/pkg/operator2/idp.go#L84
* Google: https://github.com/openshift/cluster-authentication-operator/blob/master/pkg/operator2/idp.go#L112
* OpenID: https://github.com/openshift/cluster-authentication-operator/blob/master/pkg/operator2/idp.go#L191

**Comment by wgordon17** [comment]
On those 3 IdP pages, we should actually call out the `oc login` with username/password is actually *not* possible, and that `oc login` with token is the only CLI authentication method.

**Comment by bergerhoffer** [comment]
Thanks @wgordon17!

I've opened BZ https://bugzilla.redhat.com/show_bug.cgi?id=1795264 for this update. Closing this GitHub issue as we will track the request in the BZ.
