### ISSUE TITLE
Technology Preview Tracker invalid on OCP 4.3 release notes

### ISSUE THREAD

**Issue by brian-avery** [openshift/openshift-docs#19339]
### Which section(s) is the issue in?
In the `Table 1. Technology Preview Tracker broken on OCP 4.3` table on https://docs.openshift.com/container-platform/4.3/release_notes/ocp-4-3-release-notes.html#ocp-4-3-technology-preview, the OCP 4.1 column lists several components as TP that were actually GA in 4.1. For example, `OpenShift Service Mesh` and `Operator Lifecycle Manager`

### What needs fixing?
The components that are GA in OCP 4.1 should be marked as GA.

**Comment by codyhoag** [comment]
Thanks, @brian-avery! Processing this update now: #19341

**Comment by codyhoag** [comment]
Merged. This update will be published soon.
