### ISSUE TITLE
[enterprise-4.3] Edit suggested in file nodes/nodes/nodes-nodes-opaque-resources.adoc

### ISSUE THREAD

**Issue by kasturinarra** [openshift/openshift-docs#19347]
### Which section(s) is the issue in?
Advertising hidden resources for nodes in an OpenShift Container Platform cluster

### What needs fixing?
I see that Opaque Integer Resources are removed from 1.9 version as per the link here https://github.com/kubernetes/enhancements/issues/76#issuecomment-343274099 so documentation related to Opaque Integer Resources should be removed.

**Comment by soltysh** [comment]
@openshift/team-documentation fyi

**Comment by mburke5678** [comment]
@kasturinarra Thank you for pointing this out. Changes in process in https://github.com/openshift/openshift-docs/pull/19592
