### ISSUE TITLE
[enterprise-4.3] Edit suggested in file backup_and_restore/disaster_recovery/scenario-3-expired-certs.adoc

### ISSUE THREAD

**Issue by CSSolomon** [openshift/openshift-docs#19399]
### Which section(s) is the issue in?
Initial steps

### What needs fixing?
There is no mention of how to work around below:
```bash
# oc adm release info --registry-config='/var/lib/kubelet/config.json' "${RELEASE_IMAGE}" --image-for=cluster-kube-apiserver-operator
error: release image did not contain an image-references file```

**Comment by bergerhoffer** [comment]
@CSSolomon Can you provide more details on the steps you used? Did you complete the previous step of `RELEASE_IMAGE=<release_image>`?

We did just fix a bug in the example provided where `quay.io/openshift-release-dev/ocp-release:4.3.0` was fixed to be `quay.io/openshift-release-dev/ocp-release:4.3.0-x86_64`. Let me know if this resolves the error, or if there is still an issue. Thanks!

**Comment by CSSolomon** [comment]
Hello, I am no longer part of the organization that the issue was reported for, therefore cannot help further, due to lack of access.
