### ISSUE TITLE
[enterprise-4.3] Edit suggested in file scalability_and_performance/using-cluster-loader.adoc

### ISSUE THREAD

**Issue by williamcaban** [openshift/openshift-docs#19406]
### Which section(s) is the issue in?

The documentation refers to `registry.svc.ci.openshift.org/ocp/4.3:tests` which is a RHT internal registry.

### What needs fixing?

The public URL might be ` quay.io/openshift/origin-tests:4.3` or `registry.svc.ci.openshift.org/origin/4.3:tests`

**Comment by ahardin-rh** [comment]
@williamcaban Thanks for the suggestion! We were advised not to use registry.svc.ci.openshift.org/origin/* and to use registry.svc.ci.openshift.org/ocp/*  instead. I will look into whether this guidance has changed.

**Comment by ahardin-rh** [comment]
Resolved via https://github.com/openshift/openshift-docs/pull/24578
