### ISSUE TITLE
[enterprise-4.3] Edit suggested in file serverless/interacting-serverless-apps.adoc

### ISSUE THREAD

**Issue by noelo** [openshift/openshift-docs#19437]
### Which section(s) is the issue in?
Verifying your serverless application deployment

### What needs fixing?
"Find the application host."

should be 

"Find the application URL" 

as it's the URL that output as part of the "oc get ksvc helloworld-go" command and the value being used in the next step in the next step with CURL command

**Comment by markusthoemmes** [comment]
Good catch, that's absolutely right!
