### ISSUE TITLE
[enterprise-4.3] Edit suggested in file serverless/interacting-serverless-apps.adoc

### ISSUE THREAD

**Issue by noelo** [openshift/openshift-docs#19438]
### Which section(s) is the issue in?
Interacting with a serverless application using HTTP2 / gRPC

### What needs fixing?
I think (but check) that the wrong namespace "istio-system" is being used in step 2.
The namespace should be "knative-serving-ingress"

"The ingress gateway’s public address can be determined using this command:

oc -n istio-system get svc istio-ingressgateway"

should be 

"The ingress gateway’s public address can be determined using this command:

oc -n knative-serving-ingress get svc istio-ingressgateway"

**Comment by markusthoemmes** [comment]
Thanks for reporting this!

Actually, at this point it'll likely need to be `oc -n knative-serving-ingress get svc kourier`

**Comment by abrennan89** [comment]
@mburke5678 I think this issue can be closed now, but I don't have permissions to do it?
