### ISSUE TITLE
[enterprise-4.1] Edit suggested in file logging/efk-logging-deploying.adoc

### ISSUE THREAD

**Issue by takleung** [openshift/openshift-docs#19436]
### Which section(s) is the issue in?
2c eo-csc.yaml 

### What needs fixing?
example should be changed on the following;

apiVersion: "operators.coreos.com/v1"
kind: "CatalogSourceConfig"
metadata:
  name: "elasticsearch"
  namespace: "openshift-marketplace"
spec:
  targetNamespace: "openshift-operators-redhat" 
  source: "elasticsearch"
  packages: "elasticsearch-operator"

**Comment by mburke5678** [comment]
@takleung Thank you for your comment. I am adding the `source` parameter to the example. However, I am told by the QE source in charge of the Cluster Logging installation process that the parameter should be `source: redhat-operators`. 
You can follow my changes in  https://github.com/openshift/openshift-docs/pull/19977
