### ISSUE TITLE
OKD docs for OLM referencing Redhat

### ISSUE THREAD

**Issue by lbrigman124** [openshift/openshift-docs#19431]
### Which section(s) is the issue in?
Installing the Operator Framework.
https://docs.okd.io/3.11/install_config/installing-operator-framework.html#installing-olm-using-ansible_installing-operator-framework

### What needs fixing?
References to needing a redhat account and credentials to install the operator framework.
I says it is mandatory which is incorrect for an OKD installation.

**Comment by mburke5678** [comment]
@vrutkovs Can you help with this? Is there a method for installing the Operator Framework in OKD that doesn't require a subscription to the Customer Portal?
I found this on the internet, just guessing if this is a better source: https://github.com/operator-framework/operator-lifecycle-manager

**Comment by vrutkovs** [comment]
OLM would work out of the box in OKD. We inject a configuration which allows community operators only, so the part about required credentials needs to be omitted

**Comment by mburke5678** [comment]
Making changes in https://github.com/openshift/openshift-docs/pull/20653
