### ISSUE TITLE
iptables.adoc should talk about firewalld

### ISSUE THREAD

**Issue by danwinship** [openshift/openshift-docs#1947]
iptables.adoc talks about saving and restoring iptables rules if you have to restart iptables.service, but it would be better if it said to use firewalld to manage your persistent firewall rules rather than iptables.service, since OpenShift/kubernetes/docker all integrate seamlessly with firewalld (and will handle recreating their iptables rules as needed if firewalld restarts, etc).

right @knobunc?

**Comment by knobunc** [comment]
That is reasonable.

We should also make the rules we add to iptables refresh in the same way that the core kubernetes ones do.

**Comment by eparis** [comment]
https://docs.openshift.com/container-platform/3.3/admin_guide/sdn_troubleshooting.html#is-code-firewalld-code-disabled should be fixed to not suggest that firewalld is somehow bad.

**Comment by knobunc** [comment]
This is being worked on as https://github.com/openshift/openshift-docs/pull/3000

**Comment by knobunc** [comment]
This is being worked on as https://github.com/openshift/openshift-docs/pull/3000

**Comment by knobunc** [comment]
The PR has merged
