### ISSUE TITLE
[enterprise-3.11] Edit suggested in file install_config/aggregate_logging.adoc

### ISSUE THREAD

**Issue by syedriko** [openshift/openshift-docs#19488]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/3.11/install_config/aggregate_logging.html#aggregated-fluentd

### What needs fixing?
In "See the fluentd documentation for more information about the file output.", the https://docs.fluentd.org/v0.12/articles/out_file link is stale. The new location is https://docs.fluentd.org/v/0.12/output/file.

**Comment by mburke5678** [comment]
@syedriko Thank you for reporting the bad link. However, the link you provided does not work. Do you have another link to the Fluentd docs? I am not sure where the original link went to. 
I am removing the link for now and closing this issue. Leave a comment if you have a better link we can use. I will inquire with the logging team also.

**Comment by syedriko** [comment]
It's looking like they botched an update of the v0.12 docs. For 1.0, the link is https://docs.fluentd.org/output/file and there was a corresponding one for 0.12 when I looked, but now the entire sections on plugins are gone from 0.12. Even their own internal links are broken, like "We will use the in_http and the out_stdout plugins as examples" on the https://docs.fluentd.org/v/0.12/quickstart/life-of-a-fluentd-event page. I filed an issue for this with Fluentd docs, https://github.com/fluent/fluentd-docs-gitbook/issues/157 .

**Comment by syedriko** [comment]
@mburke5678 Fluentd folks fixed their 0.12 docs, https://docs.fluentd.org/v/0.12/output/file works now.

**Comment by mburke5678** [comment]
@syedriko Thank you! What are the odds that the page would be down right when I was checking it. Thank you for confirming that the page works. I am reverting the PRs:
https://github.com/openshift/openshift-docs/pull/20002
https://github.com/openshift/openshift-docs/pull/20001
