### ISSUE TITLE
[enterprise-4.3] Edit suggested in file registry/configuring-registry-storage/configuring-registry-storage-vsphere.adoc

### ISSUE THREAD

**Issue by tux-o-matic** [openshift/openshift-docs#19523]
### Which section(s) is the issue in?
3.4.3. Configuring registry storage for VMware vSphere

### What needs fixing?
It is ill-advised to suggest NFS as storage backend for the registry. This exposes the users to data corruption. It's been documented both by Docker and in documentation of earlier OCP releases. Even Quay needs something else than NFS for its PGSQL internal DB.

And why the need for RWX? Rolling deployment strategy of the registry, overwise the single instance would be fine with just RWO.

**Comment by tux-o-matic** [comment]
@bobfuru, you recently added more documentation for this setup that is considered unstable.

**Comment by bobfuru** [comment]
> @bobfuru, you recently added more documentation for this setup that is considered unstable.

@tux-o-matic Red Hat registries are moving towards documenting and encouraging object storage as the most stable and therefore recommended storage solution for scale, availability, and resilience. Anything other than object storage starts to impede on one or more of these imperatives.
