### ISSUE TITLE
[enterprise-4.2] Edit suggested in file machine_management/creating_machinesets/creating-machineset-azure.adoc

### ISSUE THREAD

**Issue by bennerv** [openshift/openshift-docs#19567]
### Which section(s) is the issue in?
Sample YAML for a MachineSet Custom Resource on Azure

### What needs fixing?
The node label on the MachineSet is not valid YAML.  Please see below:
`        labels: node-role.kubernetes.io/<role>: "" `

It should look something like this instead:
```yaml
labels:
  node-role.kubernetes.io/<role>: ""
```

**Comment by codyhoag** [comment]
This has been corrected in #20213. The published docs should be updated shortly. Thanks!
