### ISSUE TITLE
For macOS X 10.8 and later. "openshift-install" cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by rocrisp** [openshift/openshift-docs#19589]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.3/installing/installing_aws/installing-aws-customizations.html#installation-configuration-parameters_installing-aws-customizations

Creating the installation configuration file

### What needs fixing?
A new Gatekeeper security feature with )S 10.8 and later will prevent openshift-install from executing.
There are several workaround for this error and it should be in the doc.
Example of a workaround:
FInd openshift-install in Finder, right click on it, select Open, and a dialog window appears, click the "Open" button. Once done, try running the installer again.

**Comment by jboxman** [comment]
This is true for `oc` as well.

**Comment by jboxman** [comment]
@rocrisp, I created a BZ[0] for this.

[0] https://bugzilla.redhat.com/show_bug.cgi?id=1808542

**Comment by jboxman** [comment]
The signed binaries are available here: https://access.redhat.com/downloads/content/290/ver=4.3/rhel---8/4.3.8/x86_64/product-software

**Comment by jboxman** [comment]
@kalexand-rh, the signed binaries are available from a different URL, above, than we're using at https://cloud.redhat.com/openshift/install. (Which points to https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/; And the bug I filed about having the binaries signed available on the public mirror was closed as deferred at this time.)

Do we want to point to the signed binaries instead? Or is pointing to https://cloud.redhat.com/openshift/install immutable?

**Comment by kalexand-rh** [comment]
@luciddreamz, do you have an opinion about providing a link to the signed installer binaries (https://access.redhat.com/downloads/content/290/ver=4.3/rhel---8/4.3.8/x86_64/product-software) in the docs instead of the https://cloud.redhat.com/openshift/install pages?

**Comment by jboxman** [comment]
@kalexand-rh @luciddreamz so on the latest OS X I have to re-approve `oc` every day if it came from cloud.redhat.com. It's unpleasant. I'd expect users are having a similar experience.

**Comment by luciddreamz** [comment]
We don't point at the access.redhat.com version because it requires an active OpenShift subscription to access. OpenShift is free to install without an active subscription, so the content is hosted on mirror.openshift.com without the paywall.

**Comment by jboxman** [comment]
@luciddreamz, when I filed a bug, the reason given is it's not easily done to sign binaries also on `mirror.openshift.com`. Given this new information, that OS X nags daily instead of just once, I'll try to re-open the issue. But I'm not optimistic.

**Comment by jboxman** [comment]
Given this, is there something useful we can say so that for those with a subscription, their experience on OS X isn't extremely frustrating?

> Luke Meyer 
> The signing step necessary to make the client binaries acceptable to Mac OS X is not really available to perform as part of the OCP build pipeline (which is what you get when you extract the clients from release images, and what is published to the public mirror site). The same problem exists for Windows binaries. However the client binaries are signed as part of the full release process that lands on the portal (e.g. https://access.redhat.com/downloads/content/290/ver=4.3/rhel---8/4.3.8/x86_64/product-software). This process was also recently updated to be suitable for Catalina, IIRC, possibly more recently than this bug's creation.
> There has been some discussion of re-publishing those portal artifacts to the public mirror. But there's really no good way to get them into the release images. I think this has all been discussed a great deal and not considered worth the effort. For now, the official answer is to get clients from the portal. If that's not working, please re-open this.

**Comment by luciddreamz** [comment]
How do you even manage to get a message about unsigned binaries on the Mac? I'm a Mac user and I can download the installer from the mirrors, unpack it, and run it from the CLI without warning. 

Users shouldn't be double clicking on the binary after downloading it. That won't do anything productive. Here's what happens if you double click it (after bypassing the warning):
![Screen Shot 2020-08-18 at 11 26 33 AM](https://user-images.githubusercontent.com/928421/90532844-b4c4a280-e145-11ea-8431-4c8d82260a68.png)

It just runs and exits the terminal session...

**Comment by jboxman** [comment]
@luciddreamz, I copy the binary into my `PATH`, and then run it as normal. Every day when I run it anew, I am prompted to approve it as an unsigned binary. It doesn't matter how the binary is run, OS X prompts that it is unsigned with only options to delete or abort. Once approved in _Security & Privacy_, it prompts again, but allows me to bypass the warning. This happens every day since upgrading to OS X 10.15.5.

Before it happened every time I downloaded a new unsigned binary only on the first run.

**Comment by luciddreamz** [comment]
Weird - I can't find a way to have it prompt me on Mac OS X 10.15.6 and I never saw it on older versions either. The only way it prompts is if I double click. 

My Gatekeeper settings:
![Screen Shot 2020-08-18 at 12 33 59 PM](https://user-images.githubusercontent.com/928421/90540405-2fde8680-e14f-11ea-96b7-b491950313e7.png)
