### ISSUE TITLE
[enterprise-3.11] Edit suggested in file dev_guide/environment_variables.adoc

### ISSUE THREAD

**Issue by syedriko** [openshift/openshift-docs#19599]
### Which section(s) is the issue in?
 Developer Guide/Managing Environment Variables 

### What needs fixing?
finds environment variables ... whose names begin with RAILS_ ...
$ env | grep RAILS_ | oc set env rc/r1 -e -

The regexp needs a ^ to match names that begin with RAILS_ and not just contain it: grep ^RAILS_

**Comment by codyhoag** [comment]
Fixed and merged in #20245. This should be published soon. Thanks!
