### ISSUE TITLE
[enterprise-4.3] Edit suggested in file networking/multiple-networks/understanding-multiple-networks.adoc

### ISSUE THREAD

**Issue by xsgordon** [openshift/openshift-docs#19605]
### Which section(s) is the issue in?

Understanding multiple networks
https://docs.openshift.com/container-platform/4.3/networking/multiple-networks/understanding-multiple-networks.html

### What needs fixing?

The documentation for multiple networks does a great job of explaining how to expose a secondary interface to a Pod in environments where the node has been presented with a second NIC. There is a gap between our install documentation and this documentation however, where we do not clearly explain how to achieve this on platforms with cloud provider integration turned on - whereby OpenShift manages creation of the virtual machines (and thus whether or not there is a NIC to expose).

In particular, several customers have been caught out by the fact that the cloud provider integration for OpenStack - for both IPI and UPI - does not provide a way to define machine configs that provide a second interface. So there is no way for an OpenShift on OpenStack user to use provider integration and a secondary interface at the same time, but the documentation never calls this out.

**Comment by xsgordon** [comment]
@augustrh fyi

**Comment by xsgordon** [comment]
I should add, I mention OpenStack specifically because that is the one that has come up several times. I have not investigated which of the other providers is more flexible.

**Comment by xsgordon** [comment]
Marc pointed out to me that technically on OSP you can define multiple interfaces at the multus level from the same NIC, but this doesn't achieve what these users are typically attempting to do which is plumb through separate NICs.

**Comment by jboxman** [comment]
@xsgordon, so is the issue that on certain platforms, it is not actually possible to configure an additional network? Under what circumstances is it possible?

Is a cloud provider always used, or is it possible to disable it? Would someone ever do that?

So maybe my question is, which cloud providers support exposing additional network interfaces? And is this done at installation time or after?

Thanks!
