### ISSUE TITLE
[enterprise-4.3] Edit suggested in file installing/install_config/installation-types.adoc

### ISSUE THREAD

**Issue by jeffcpullen** [openshift/openshift-docs#19612]
### Which section(s) is the issue in?

installing/install_config/installation-types.adoc

The table that lists supported installation methods

### What needs fixing?

The table has different labels for the rows for IPI and UPI which is confusing, and probably wrong. For example, Custom and Network Operator exist on both tables. Custom is a yes on both, Network Operator only for IPI. That makes sense as you can see a clear difference between the two methods.

Other labels are skipped. Does skipped mean that they are a 'No', or does it mean it is an assumed 'Yes'. For example, we say that you can use IPI for an Existing VPC, but if you're configuring all the bits of the installer with UPI, surely you can use an existing VPC for that as well. Since 'Existing Virtual Private Cloud' isn't mentioned with UPI, some people might assume they can't use UPI there.

I'd suggest matching up the named rows in the tables so that people can make a more informed decision on what their options are.

**Comment by jboxman** [comment]
Applies to: https://docs.openshift.com/container-platform/4.3/installing/install_config/installation-types.html
