### ISSUE TITLE
[enterprise-4.3] Edit suggested in file networking/configuring-ingress-cluster-traffic/configuring-ingress-cluster-traffic-load-balancer.adoc

### ISSUE THREAD

**Issue by NissesSenap** [openshift/openshift-docs#19619]
### Which section(s) is the issue in?
The following command dosen't work anymore. 

3. Use the oc new-app command to create a service. For example:

$ oc new-app \
    -e MYSQL_USER=admin \
    -e MYSQL_PASSWORD=redhat \
    -e MYSQL_DATABASE=mysqldb \
    registry.redhat.io/openshift3/mysql-55-rhel7

### What needs fixing?
Update for example with: 

 oc new-app mysql:8.0~https://github.com/sclorg/mysql-container.git \
    --name my-mysql-rhel8 \
    --context-dir=examples/extend-image \
    --env MYSQL_OPERATIONS_USER=opuser \
    --env MYSQL_OPERATIONS_PASSWORD=oppass \
    --env MYSQL_DATABASE=opdb \
    --env MYSQL_USER=user \
    --env MYSQL_PASSWORD=pass

I grabbed it from: https://access.redhat.com/containers/#/registry.access.redhat.com/rhel8/mysql-80

**Comment by jboxman** [comment]
Thanks @NissesSenap! Fixed in https://github.com/openshift/openshift-docs/pull/18368.
