### ISSUE TITLE
[dedicated] Edit suggested in file support/gathering-cluster-data.adoc

### ISSUE THREAD

**Issue by pwright** [openshift/openshift-docs#19627]
### Which section(s) is the issue in?
https://docs.openshift.com/dedicated/4/support/gathering-cluster-data.html

### What needs fixing?

prereq of cluster-admin is not valid for OSD user, right?

**Comment by bergerhoffer** [comment]
Thanks for submitting this issue @pwright!

@sferich888 Can you speak to this? Can users running dedicated still use must-gather, and if so, should the prereq of being cluster-admin be removed?

**Comment by sferich888** [comment]
Correct users in dedicated should not run must-gather. 

Instead users should use `oc adm inspect <resource>` (on resources such as namespaces). 

@radekvokal isn't the CCX team working on a way to automate the collection of must-gather? Can that implementation be used on dedicated?

**Comment by bergerhoffer** [comment]
Thanks @sferich888! I've removed the must-gather docs from dedicated via #20158.

**Comment by bergerhoffer** [comment]
QE approval received and PRs have been merged for 4.1-4.4.

**Comment by bergerhoffer** [comment]
Closing, removal is live: https://docs.openshift.com/dedicated/4/support/getting-support.html
