### ISSUE TITLE
[enterprise-4.2] Edit suggested in file web-console/customizing-the-web-console.adoc

### ISSUE THREAD

**Issue by tdaleibm** [openshift/openshift-docs#19640]
### Which section(s) is the issue in?
Page: OCP 4.2 Customizing the web console in OpenShift Container Platform. Section: Adding a custom logo and product name
https://docs.openshift.com/container-platform/4.2/web-console/customizing-the-web-console.html

### What needs fixing?
Yaml example indentation in step 2 is off on line "customProductName: My Console" and subsequent lines

**Comment by jboxman** [comment]
@tdaleibm, thanks for reporting this!
