### ISSUE TITLE
admission control customization doesn't describe ProjectRequestLimit plugin

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/openshift-docs#1966]
This page describes how to customize admission controler:
https://docs.openshift.org/latest/install_config/configuring_admission_control.html

It references the existing plugins and possible configuration.

In this other page (https://docs.openshift.org/latest/admin_guide/managing_projects.html#limit-projects-per-user), there is one admission controller plugin described "ProjectRequestLimit" that's not mentioned in the customizing admission controller.

**Comment by bfallonf** [comment]
I attached this issue to a BZ:

https://bugzilla.redhat.com/show_bug.cgi?id=1338919

Closing this in favour of that.
