### ISSUE TITLE
[enterprise-4.3] Edit suggested in file metering/configuring-metering/metering-configure-persistent-storage.adoc

### ISSUE THREAD

**Issue by shortsteps** [openshift/openshift-docs#19678]
### Which section(s) is the issue in?

[Storing data in Microsoft Azure](https://docs.openshift.com/container-platform/4.3/metering/configuring-metering/metering-configure-persistent-storage.html#metering-store-data-in-azure_metering-configure-persistent-storage)

### What needs fixing?

The command which creates the secret has a typo in the last option:
```
oc create secret -n openshift-metering generic your-azure-secret --from-literal=azure-storage-account-name=your-storage-account-name --from-literal=azure-secret-access-key-your-secret-key
```

` --from-literal=azure-secret-access-key-your-secret-key` 
should be 
`--from-literal=azure-secret-access-key=your-secret-key` 
(with "=" before the key value).

**Comment by bobfuru** [comment]
Thank you, @shortsteps 
OpenShift docs 4.3+ now have the correct command string. For example: https://docs.openshift.com/container-platform/4.5/metering/configuring_metering/metering-configure-persistent-storage.html#metering-store-data-in-azure_metering-configure-persistent-storage shows the following command:

> `$ oc create secret -n openshift-metering generic your-azure-secret --from-literal=azure-storage-account-name=your-storage-account-name --from-literal=azure-secret-access-key=your-secret-key`

Closing issue.
