### ISSUE TITLE
[enterprise-4.2] Edit suggested in file authentication/certificates/replacing-default-ingress-certificate.adoc

### ISSUE THREAD

**Issue by skamphax0r** [openshift/openshift-docs#19758]
### Which section(s) is the issue in?

Replacing the default ingress certificate

### What needs fixing?

in https://access.redhat.com/documentation/en-us/openshift_container_platform/4.2/html/networking/configuring-ingress#nw-ingress-setting-a-custom-default-certificate_configuring-ingress there is a warning box about using non publicly signed CAs

in this doc there is not - depending on which doc the customer uses, this may cause confusion and support tickets.

**Comment by codyhoag** [comment]
Good call! This is now being tracked in #19856. Thanks!
