### ISSUE TITLE
[enterprise-4.2] Edit suggested in file scalability_and_performance/scaling-cluster-monitoring-operator.adoc

### ISSUE THREAD

**Issue by ChetHosey** [openshift/openshift-docs#19764]
### Which section(s) is the issue in?

Prometheus database storage requirements -> Recommendations for OpenShift Container Platform

### What needs fixing?

This section says that OpenShift Container Storage is tech preview. OCS has gone GA.

**Comment by ahardin-rh** [comment]
Thank you! This is now addressed in https://github.com/openshift/openshift-docs/pull/20286
