### ISSUE TITLE
[enterprise-4.3] Edit suggested in file authentication/remove-kubeadmin.adoc

### ISSUE THREAD

**Issue by ckyriakidou** [openshift/openshift-docs#19821]
### Which section(s) is the issue in?
Need  to add a save system:admin credentials

### What needs fixing?
Please mention that system:admin credentials exist under .kubeconfig and how to use them when everyhting else fails and the kubeadmin user is disabled. This user credentials need to be kept safe in a password vault and the user is not allowed to log in to the web-ui. Just the console.

**Comment by tdaleibm** [comment]
I agree. For instance the information at https://access.redhat.com/solutions/4845381 answers part of this and should be added to the docs.
