### ISSUE TITLE
[enterprise-4.2] Edit suggested in file logging/config/cluster-logging-external.adoc

### ISSUE THREAD

**Issue by aelicieguo** [openshift/openshift-docs#19820]
### Which section(s) is the issue in?
Configuring log collector to send logs to an external syslog server

There are no info on configuration for sending logs to external syslog server with UDP

### What needs fixing?
add REMOTE_SYSLOG_TYPE

defaults to syslog_buffered, declare to syslog for sending messages with UDP

**Comment by mburke5678** [comment]
Thanks for pointing this out. The parameter was added to the code recently and the docs were not updated. Follow my changes in https://github.com/openshift/openshift-docs/pull/20008
