### ISSUE TITLE
OCP 4.5 Release Notes Tracker

### ISSUE THREAD

**Issue by soltysh** [openshift/openshift-docs#19847]
Please leave comments here for anything that should be highlighted in the 4.5 release notes. Thank you!

Rendered draft of 4.5 release notes: https://docs.openshift.com/container-platform/4.5/release_notes/ocp-4-5-release-notes.html

**Comment by soltysh** [comment]
https://github.com/openshift/oc/pull/310 drops the following commands and flags:
- `oc policy can-i` command deprecated in 3.9 (https://github.com/openshift/origin/commit/73338c4), users should use `oc auth can-i` instead
- `oc new-app --image` and `oc new-build --image` flags deprecated in 3.2 (https://github.com/openshift/origin/commit/6517d76), users should use `--image-stream` instead
- `oc process -t` flag deprecated in 3.11 (https://github.com/openshift/origin/commit/6a8cc0b), users should use `--template` instead
-  `oc process --output-version` flag deprecated in 3.11 (https://github.com/openshift/origin/commit/6a8cc0b), the flag was already ignored
- `oc set deployment-hook -v` flag deprecated in 3.11 (https://github.com/openshift/origin/commit/2fcf185), users should use `--volumes` instead
- `oc set volumes --list` flag deprecated in 3.3 (https://github.com/openshift/origin/commit/af79d7d), `oc set volumes` w/o flags will list volumes
- `oc status -v` and `oc status --verbose` flags deprecated in 3.11 (https://github.com/openshift/origin/commit/2fcf185), users should use `--suggest` instead

**Comment by codyhoag** [comment]
The deprecated `/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt` file will be removed in 4.5. From https://github.com/openshift/openshift-docs/issues/18426#issuecomment-574239835.

**Comment by soltysh** [comment]
https://github.com/openshift/oc/pull/355 changes default behavior of `oc new-app`, starting since 4.5 the default resource produced by `oc new-app` will be Deployment and not DeploymentConfig (for more information about differences see https://docs.openshift.com/container-platform/4.3/applications/deployments/what-deployments-are.html). Users interested in generating DeploymentConfig can pass `--as-deployment-config` flag when invoking `oc new-app`.

**Comment by jatanmalde** [comment]
With OpenShift 4.4, I see some change with installation format, should we include one such paragraph of it in the release docs. I see etcd-member and etcd-metrics running on the bootstrap and not on the masters as per previous installation methods?

**Comment by jboxman** [comment]
_Notable changes_

The OpenShift SDN and OVN-Kubernetes Pod network providers now use the Open vSwitch (OVS) version installed on the cluster nodes. Previously, OVS ran in a container on each node, managed by a DaemonSet. Using the host OVS eliminates any possible downtime from upgrading the containerized version of OVS.

Hi @mccv1r0 -- Is the above correct? If not, what changes can you suggest? Thanks!

**Comment by mccv1r0** [comment]
@jboxman  I can speak to OVN-Kubernetes (I'm not sure what OpenShift SDN is doing.)  What you wrote is correct.  No need to change a thing.

**Comment by yapei** [comment]
https://docs.openshift.com/container-platform/4.5/release_notes/ocp-4-5-release-notes.html#ocp-4-5-new-attribute-filters

```
NEW CAPABILITY AND SUBSCRIPTION REQUIRED FILTERS FOR OPERATORS IN OPERATORHUB
OLM provides a list of attributes that Operator developers can tag their Operators with, that describe the Operator’s functionality or attributes, such as disconnected, license required, FIPS mode, and so on. You can now filter these options by Capability and Subscription Required in OperatorHub
```

The filter type in OperatorHub is `Infrastructure Features`

<img width="240" alt="Screen Shot 2020-05-27 at 11 09 39 AM" src="https://user-images.githubusercontent.com/12692381/82973695-ad8c6d80-a00a-11ea-84b0-1fbedf88c92e.png">

**Comment by bmcelvee** [comment]
**Node Pull Secrets**
You can import and use images from any registry configured during or after the cluster installation by sharing node's pull secret credentials with `openshift-api`, `builder` and `image-registry` Pods.

**Comment by qinpingli** [comment]
`External provisioner for AWS EFS` in table 2 should be moved to table 1.

**Comment by qinpingli** [comment]
Looks raw block feature is GA in k8s 1.18, but in table 2, `Raw Block with iSCSI` is GA from OCP4.3 and the `Raw Block with Cinder` is TP feature.

Suggest we can merge these two into one named `Block Volume`.

**Comment by qinpingli** [comment]
`CSI volume cloning` is GA in OCP 4.5

**Comment by jianzhangbjz** [comment]
`Service Catalog`, `Template Service Broker`, and `CatalogSourceConfigs` are removed for OCP 4.5. `OperatorSources` is `DEP` for 4.5. @emmajiafan correct me if I'm wrong, thanks!

**Comment by gpei** [comment]
we're starting to support VMware vSphere IPI deployment - https://issues.redhat.com/browse/CORS-1272, GCP UPI shared VPC (XPN) - https://issues.redhat.com/browse/CORS-1390 in 4.5, better to highlight them in the release notes.

**Comment by lihongan** [comment]
The `INGRESS ENHANCEMENTS` is missing in `New features and enhancements` section and should add 2 enhancements below:
1. https://issues.redhat.com/browse/NE-280 ingress access logging
2. https://issues.redhat.com/browse/NE-278 wildcard route policy

**Comment by duanwei33** [comment]
For storage part, `Manila CSI Driver` and `AWS ebs CSIi Driver` should be added in Table 2. Technology Preview tracker, they are TP features from 4.5.

**Comment by duanwei33** [comment]
Just my personal view, for a lot of features with GA from 4.3, also GA for 4.4 and 4.5, do we need to list them in Table 2. Technology Preview tracker? At least using another table if really need to track them.

**Comment by gpei** [comment]
`OpenShift Container Platform 4.5 is supported on Red Hat Enterprise Linux 7.6 or later, as well as Red Hat Enterprise Linux CoreOS (RHCOS) 4.5.`
RHEL-7.6 is not in QE's testing coverage for OCP-4.5, RHEL-7.7 and RHEL-7.8 were tested.

**Comment by xiuwang** [comment]
New feature:
1. [Support nodeAffinity scheduler feature in image-registry CRD](https://issues.redhat.com/browse/DEVEXP-544)
Use nodeAffinity to ensure if image registry pod cannot land on infra nodes, that it lands somewhere else.
2. [Node pull secret](https://issues.redhat.com/browse/DEVEXP-521)
as mentioned in https://github.com/openshift/openshift-docs/issues/19847#issuecomment-634715933

Known issue:  bug #1787112 ,[card](https://issues.redhat.com/browse/IR-34)
ImageContentSourcePolicy for image registry pull-through does not support yet, that conduce jenkins pods use default jenkins imagestream meet ImagePullBackOff error.

**Comment by jianzhangbjz** [comment]
This photo here https://docs.openshift.com/container-platform/4.5/operators/olm-what-operators-are.html#olm-maturity-model_olm-what-operators-are is wrong. @joelanford Correct me if I'm wrong, thanks!
![image](https://user-images.githubusercontent.com/15416633/83213801-a47bd780-a195-11ea-9960-dfdf380fbfe8.png)
Should be: 
![image](https://user-images.githubusercontent.com/15416633/83213864-c9704a80-a195-11ea-95d0-181cce1c4bcf.png)

**Comment by huiran0826** [comment]
https://docs.openshift.com/container-platform/4.5/networking/multiple_networks/configuring-ptp.html

There are two places need update:

1. The ptp-namespace.yaml changed to :
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-ptp
  labels:
    name: openshift-ptp
    openshift.io/cluster-monitoring: "true"

2. oc get packagemanifest ptp-operator -n openshift-marketplace -o jsonpath='{.status.defaultChannel}'
4.4  

4.4 needs update to 4.5

**Comment by codyhoag** [comment]
Hi all; please keep the comments in this tracker related only to the release notes. Please work with the tech writer on your team to resolve known bugs in other parts of the documentation. Thank you!

**Comment by huiran0826** [comment]
Migration from openshift-sdn to ovn-kubernetes is missed in "New features and enhancements"
https://issues.redhat.com/browse/SDN-821

**Comment by jinyunma** [comment]
vSphere/ipi support on 4.5 is missed in `"New features and enhancements"`.
https://issues.redhat.com/browse/CORS-1272

**Comment by bobfuru** [comment]
> `External provisioner for AWS EFS` in table 2 should be moved to table 1.

Noted: https://issues.redhat.com/browse/OSDOCS-1017?focusedCommentId=14122497&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14122497. I'll address this in my 4.5 Release Notes PR.

**Comment by bobfuru** [comment]
> Looks raw block feature is GA in k8s 1.18, but in table 2, `Raw Block with iSCSI` is GA from OCP4.3 and the `Raw Block with Cinder` is TP feature.
> 
> Suggest we can merge these two into one named `Block Volume`.

I don't think we want to merge these. Cinder is still a TP feature and a carry-over from 3.11. I suggest we drop that one from the table and leave iSCSI, which went GA in 4.3, as you noted.

**Comment by bandrade** [comment]
@adellape 
https://docs.openshift.com/container-platform/4.5/operators/crds/crd-extending-api-with-crds.html#crd-creating-custom-resources-definition_crd-extending-api-with-crds at step 2, mentions that: 
```
A new RESTful API endpoint is created at:
/apis/<spec:group>/<spec:version>/<scope>/*/<names-plural>/...
```
I think it would be nice to add here which command user can use to obtain this endpoint. It's not clear where it's being created and how you can get this info. Please let me know if that makes sense to you. cc: @jianzhangbjz

**Comment by qinpingli** [comment]
> I don't think we want to merge these. Cinder is still a TP feature and a carry-over from 3.11. I suggest we drop that one from the table and leave iSCSI, which went GA in 4.3, as you noted.

@bobfuru Thanks for your checking, I didn't find there is different between cinder plug-in and other in-tree plug-ins, and checked the 3.11 release notes too, did not find the description of cinder raw block volume, is there something I missed?

**Comment by bobfuru** [comment]
> > I don't think we want to merge these. Cinder is still a TP feature and a carry-over from 3.11. I suggest we drop that one from the table and leave iSCSI, which went GA in 4.3, as you noted.
> 
> @bobfuru Thanks for your checking, I didn't find there is different between cinder plug-in and other in-tree plug-ins, and checked the 3.11 release notes too, did not find the description of cinder raw block volume, is there something I missed?

@qinpingli On second look, Cinder block was not TP in 3.11 but rather was introduced as TP in 4.3. So as you noted in your original comment, OCP support for iSCSI was GA in 4.3; Cinder was TP in 4.3. And although k8s 1.18 is raw block GA, I think we want our OCP table to remain as is, separating the Red Hat Support distinction between these two raw block volume types. Is that okay with you?

**Comment by qinpingli** [comment]
> > > I don't think we want to merge these. Cinder is still a TP feature and a carry-over from 3.11. I suggest we drop that one from the table and leave iSCSI, which went GA in 4.3, as you noted.
> > 
> > 
> > @bobfuru Thanks for your checking, I didn't find there is different between cinder plug-in and other in-tree plug-ins, and checked the 3.11 release notes too, did not find the description of cinder raw block volume, is there something I missed?
> 
> @qinpingli On second look, Cinder block was not TP in 3.11 but rather was introduced as TP in 4.3. So as you noted in your original comment, OCP support for iSCSI was GA in 4.3; Cinder was TP in 4.3. And although k8s 1.18 is raw block GA, I think we want our OCP table to remain as is, separating the Red Hat Support distinction between these two raw block volume types. Is that okay with you?

@bobfuru  Thank you, checked the jira items for raw block. Yes, you are right, cinder raw block in TP in 4.3.

@codyhoag  We had a conclusion for raw block features now.

**Comment by xingxingxia** [comment]
@codyhoag , with [service-ca crt dropped from token secret in 1813894](https://bugzilla.redhat.com/show_bug.cgi?id=1813894) is verified, need mention this dropping in 4.5 release note. It affects many components and applications. [1813894#c2](https://bugzilla.redhat.com/show_bug.cgi?id=1813894#c2) mentions 4.1 deprecation. This is like another dropping "The oc policy can-i command was deprecated in OpenShift Container Platform 3.9 and has been removed" already mentioned in 4.5 release notes.

**Comment by adambkaplan** [comment]
@bmcelvee late addition - the image registry supports virtual-hosted buckets names if the user provides a custom S3 endpoint, such as `https://mybucketname.customs3.corp`.

https://issues.redhat.com/browse/DEVEXP-623

**Comment by adambkaplan** [comment]
@bmcelvee @dmage image registry operator now supports node affinity for scheduling the image registry pods: https://issues.redhat.com/browse/DEVEXP-544

**Comment by bobfuru** [comment]
> For storage part, `Manila CSI Driver` and `AWS ebs CSIi Driver` should be added in Table 2. Technology Preview tracker, they are TP features from 4.5.

Added these to TP Tracker. @duanwei33 Plan for Manila CSI Driver Operator is GA in 4.5, so I

**Comment by e-tienne** [comment]
Do you include subcommands to `openshift-installer` in the release notes? I could not a mention of `openshift-installer migrate` (https://github.com/openshift/installer/pull/3343)

**Comment by codyhoag** [comment]
@e-tienne yeah, we should include that. I'll look into it and see if we can get it added.

**Comment by enxebre** [comment]
Machine API:
- AWS/Azure/GCP Support autoscaling from/to zero now.
- AWS supports spot instances now.
- A Machine Health check with an empty selector will monitor all machines now.

**Comment by jatanmalde** [comment]
Hello Team, 

We moved the Logging stack from ES5 to ES6, Should we be including it in the product release notes?
Logforwarder is GA as well if I am not wrong? are we including it?

Thanks..

**Comment by peterclauterbach** [comment]
OpenShift virtualization (formerly CNV) is GA in OCP 4.5. As a feature of It should appear as a separate item under "New features and enhancements" as Virtualization.
It should also appear as an item in the Technology Preview Tracker table as moving from TP to GA in this release.

**Comment by codyhoag** [comment]
@jatanmalde The ES6 upgrade release note is being worked on in #23277. Log forwarding will be released as GA in a z-stream; therefore, we're listing it as `TP` in the table until it is officially GA.

**Comment by vikram-redhat** [comment]
> OpenShift virtualization (formerly CNV) is GA in OCP 4.5. As a feature of It should appear as a separate item under "New features and enhancements" as Virtualization.
> It should also appear as an item in the Technology Preview Tracker table as moving from TP to GA in this release.

Hey @peterclauterbach - CNV is not actually releasing till the 29th July while OCP GAs on the 9th. It might make most sense to not mark it as GA with OCP 4.5 GA since we won't be releasing the docs for CNV till then (otherwise this is likely to cause confusion). We should probably mark it as GA only when CNV GAs.

Let me know if you disagree and/or if we should discuss this at the PgM level.

@aspauldi

**Comment by peterclauterbach** [comment]
@vikram-redhat Agreed.  As long as we can update the main OCP release notes in the appropriate OCP 4.5.z stream, concurrent with the planned OpenShift virtualization updates.

**Comment by codyhoag** [comment]
@peterclauterbach @vikram-redhat what we can do is draft a new feature release note and TP table entry, and hide it in the doc for now. Once Virtualization goes GA, we can uncomment the text for a quick add.

**Comment by wabouhamad** [comment]
@codyhoag I need to add this comment to the OCP 4.5 release notes under known issues: 

>  The Special Resources Operator (a community operator) cannot be deployed successfully due to BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1847805.  This will prevent us from deploying the NVIDIA drivers needed by OpenShift to run workloads requiring GPU resources.  Also the OCP 4.5 Topology Manager feature could not be tested with GPU resources as a result of that SRO BZ.

**Comment by adambkaplan** [comment]
@codyhoag the release note for the "Node Pull Secrets" feature is misleading and vague. I propose the following to be added under "Developer Experience" rather than "Node":

```
Builds and Imagestream imports will automatically use the pull secret used to install the cluster if a pull secret is not explicitly set. Developers will not need to copy this pull secret into their namespace.
```
fyi @dmage @ricardomaraschini @bmcelvee

**Comment by adambkaplan** [comment]
@codyhoag @dmage I do not see anything for the image registry supporting Virtual Hosted buckets with custom S3 endpoints [1]. This is an important fix for customers who are trying to deploy in AWS GovCloud and newer AWS regions.

[1] https://issues.redhat.com/browse/DEVEXP-566 -

**Comment by bmcelvee** [comment]
@adambkaplan I have a WIP PR to update DevEx release notes: https://github.com/openshift/openshift-docs/pull/23326/files and can update the Pull Secrets content there too.

**Comment by wjiangjay** [comment]
For OCP on OSP, we have a known issue, https://bugzilla.redhat.com/show_bug.cgi?id=1848945 - Bug 1848945 - [OpenShift on OpenStack] Routes failed to access once ingress port VIP is on RHEL worker

**Comment by anpingli** [comment]
> Thank
Logging forward not GA in 4.5.

**Comment by lihongan** [comment]
For Azure platform, we have a known issue https://bugzilla.redhat.com/show_bug.cgi?id=1854383, it might occur when upgrade cluster from 4.4.x to 4.5.

**Comment by zhaozhanqi** [comment]
For Azure platform. we have a know issue https://bugzilla.redhat.com/show_bug.cgi?id=1851549 
sometimes the oc commands fail intermittently with TLS Handshake timeout Errors

**Comment by zhaozhanqi** [comment]
Sometimes the pods in one node maybe lose the network communication. means these pods cannot be working well (crashed). 
there is a known issue https://bugzilla.redhat.com/show_bug.cgi?id=1855118 this issue maybe happen after upgrade. 
There is workaround is "delete the crashed pods and make it re-created" the new created pod can work well.

**Comment by mffiedler** [comment]
Log indexing performance is degraded compared to OCP 4.4:  https://bugzilla.redhat.com/show_bug.cgi?id=1833486  @jcantrill can probably provide additional info if needed.

**Comment by jinyunma** [comment]
For ipi on vsphere, we have an known issue: https://bugzilla.redhat.com/show_bug.cgi?id=1852545:
Bug 1852545 - VSphere IPI fails to bootstrap workers: default resource pool resolves to multiple instances, please specify

**Comment by codyhoag** [comment]
OCP 4.5 docs are now live. Thanks all!

OCP 4.6 release notes tracker is here: #22406
