### ISSUE TITLE
[enterprise-4.2] Edit suggested in file backup_and_restore/disaster_recovery/scenario-2-restoring-cluster-state.adoc

### ISSUE THREAD

**Issue by aelicieguo** [openshift/openshift-docs#19893]
### Which section(s) is the issue in?
There should be one last step that is to restart the node one by one. We did this test and all tune pods goes into Pending mode. Restarting all nodes one by one would fix this.

**Comment by bergerhoffer** [comment]
@aelicieguo Thanks for submitting this request!

@retroflexer @hexfusion Could either of you speak to this?

https://docs.openshift.com/container-platform/4.2/backup_and_restore/disaster_recovery/scenario-2-restoring-cluster-state.html#dr-scenario-2-restoring-cluster-state_dr-restoring-cluster-state

**Comment by retroflexer** [comment]
We added restarting kubelets. That will be sufficient for avioding pods getting into Pending mode.

**Comment by jboxman** [comment]
@retroflexer, does that mean we can close this issue? Thanks!

**Comment by retroflexer** [comment]
Yes. Close it.
