### ISSUE TITLE
[enterprise-4.3] Edit suggested in file networking/accessing-hosts.adoc

### ISSUE THREAD

**Issue by peterclauterbach** [openshift/openshift-docs#19919]
### Which section(s) is the issue in?
Title
Accessing hosts on Amazon Web Services (AWS) after a full-stack automation (IPI) installation

### What needs fixing?
My understanding is that we do not use IPI or UPI acronyms in external docs.

**Comment by jboxman** [comment]
@kalexand-rh, is it _installer-provisioned_ now?

**Comment by kalexand-rh** [comment]
@jboxman, _installer-provisioned_ is correct. IPI and UPI should not be used anywhere in the collection.

**Comment by codyhoag** [comment]
Fixed in #20038
