### ISSUE TITLE
Serverless release note's format is broken on OCP 4.3

### ISSUE THREAD

**Issue by nak3** [openshift/openshift-docs#19923]
Please refer to https://docs.openshift.com/container-platform/4.3/serverless/serverless-release-notes.html (4.3 docs's Serverless release note).

- The first block is metadata.
- All of `{ServerlessProductName}` is not replaced by `OpenShift Serverless`.

Please note that it is only on 4.3 docs, 4.2 docs does not have this issue https://docs.openshift.com/container-platform/4.2/serverless/serverless-release-notes.html.

/cc @abrennan89 

P.S I found https://github.com/openshift/openshift-docs/pull/19739. It will fix this issue? It is 10 days ago, though.

**Comment by abrennan89** [comment]
Thanks @nak3 I'll fix it first thing! It's just an issue with including the attributes file afaik but it should be a quick fix.

**Comment by abrennan89** [comment]
Fixed by https://github.com/openshift/openshift-docs/pull/19950 :slightly_smiling_face:
