### ISSUE TITLE
[enterprise-4.3] Edit suggested in file networking/multiple_networks/configuring-sr-iov.adoc

### ISSUE THREAD

**Issue by braultatgithub** [openshift/openshift-docs#19933]
In section 
https://docs.openshift.com/container-platform/4.3/networking/multiple_networks/configuring-sr-iov.html

It seems to imply that SR-IOV is Tech Preview in OCP 4.3.

Bases on the release notes:
https://docs.openshift.com/container-platform/4.3/release_notes/ocp-4-3-release-notes.html#ocp-4-3-technology-preview

This is expected to be GA.

### Which section(s) is the issue in?

OCP 4.3

### What needs fixing?
Remove the following paragraph assuming release notes are correct.

"Network Interface Card (NIC) SR-IOV hardware is a Technology Preview feature only. Technology Preview features are not supported with Red Hat production service level agreements (SLAs) and might not be functionally complete. Red Hat does not recommend using them in production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

For more information about the support scope of Red Hat Technology Preview features, see https://access.redhat.com/support/offerings/techpreview/."
For more information about the support scope of Red Hat Technology Preview features, see https://access.redhat.com/support/offerings/techpreview/.

**Comment by jboxman** [comment]
@braultatgithub, thanks for reporting this!
