### ISSUE TITLE
need docs for oadm diagnostics

### ISSUE THREAD

**Issue by sosiouxme** [openshift/openshift-docs#1996]
The only mention is outdated, at the bottom of https://docs.openshift.org/latest/install_config/upgrading/automated_upgrades.html

Where is a good place to discuss it, and at what level of detail? I could add a paragraph in a troubleshooting guide somewhere (if there were one with the right scope), or a full description of the complete list of existing diagnostics.

**Comment by bfallonf** [comment]
@sosiouxme I checked out the `openshift ex --help` screen. Seems it's in beta. I'd be hesitant to document something that is "under development and may change without notice" or "may evolve in a different direction".

Or do you mean this will be released for 3.2?

**Comment by adellape** [comment]
Reminder about this one: https://github.com/openshift/openshift-docs/pull/1383 (at least just for the conversation, if not rebasing/continuing with the PR)

**Comment by sosiouxme** [comment]
@bfallonf did you check out `oadm diagnostics`?

The "beta" tool was left in place, with only an unnoticeable deprecation notice. I'm not honestly certain when it made it into OSE but I thought it was 3.1.

**Comment by adellape** [comment]
`oadm diagnostics` is not in OSE 3.1.1.6, but it is in 3.2. But also in 3.2 we should start using `oc adm` instead of `oadm`, e.g., `oc adm diagnostics`. (I had hoped to do a mass update of the docs for 3.2 to make that switch, we'll see if it happens.)

**Comment by bfallonf** [comment]
@adellape sounds like it might be easier to get @sosiouxme 's PR going rather than start with something new. Unless we want to sort out an actual troubleshooting docs placement beforehand?

**Comment by ahardin-rh** [comment]
Closing this, as the Diagnostics Tool content was added in https://github.com/openshift/openshift-docs/pull/2885. Additional information is being added in https://github.com/openshift/openshift-docs/pull/3302.
