### ISSUE TITLE
[enterprise-4.3] Edit suggested in file networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-nodeport.adoc

### ISSUE THREAD

**Issue by nickcmaynard** [openshift/openshift-docs#19993]
### Which section(s) is the issue in?
This entire page.

### What needs fixing?
Most of the instructions are for ExternalIP.  There are no instructions for NodePort - see v3 docs https://docs.openshift.com/container-platform/3.11/dev_guide/expose_service/expose_internal_ip_nodeport.html

**Comment by jboxman** [comment]
@nickcmaynard, I've merged a PR with `NodePort` updates: https://github.com/openshift/openshift-docs/pull/18368

I have a separate PR covering some of ExternalIP: https://github.com/openshift/openshift-docs/pull/21388
