### ISSUE TITLE
[enterprise-4.3] Edit suggested in file installing/install_config/configuring-private-cluster.adoc

### ISSUE THREAD

**Issue by seferovic** [openshift/openshift-docs#19992]
### Which section(s) is the issue in?

After you install OpenShift Container Platform version 4.2 cluster, you can set some of its core components to be private.

### What needs fixing?

Version number 4.2 -> 4.3

**Comment by codyhoag** [comment]
Thanks! Fixed and merged here: #20229. This should be published soon.
