### ISSUE TITLE
Document TagImages hook

### ISSUE THREAD

**Issue by php-coder** [openshift/openshift-docs#2010]
Looks like we're missing documentation for `TagImages` hook that was added by https://github.com/openshift/origin/commit/3d8b8d549d1cc7f76c5323d31ef100166e39d95a

**Comment by bfallonf** [comment]
Thanks @php-coder . Looks like the info still isn't in the docs. I've created a BZ for this: https://bugzilla.redhat.com/show_bug.cgi?id=1484630

Let me know if there's anything more for this issue. Closing.
