### ISSUE TITLE
[enterprise-4.3] Edit suggested in file logging/cluster-logging.adoc

### ISSUE THREAD

**Issue by syedriko** [openshift/openshift-docs#20111]
### Which section(s) is the issue in?
 Logging/About cluster logging 
https://docs.openshift.com/container-platform/4.3/logging/cluster-logging.html

### What needs fixing?
The paragraph beginning with "OpenShift Container Platform cluster administrators" is repeated twice.

**Comment by vikram-redhat** [comment]
@mburke5678 is this because of reusing the same text in the assembly and module?

**Comment by mburke5678** [comment]
@vikram-redhat Probably. I can rework one or the other sentence to make it less redundant.

**Comment by mburke5678** [comment]
Making changes in https://github.com/openshift/openshift-docs/pull/20272
