### ISSUE TITLE
Internal registry reference

### ISSUE THREAD

**Issue by e-minguez** [openshift/openshift-docs#20133]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.3/scalability_and_performance/using-cluster-loader.html#installing-cluster-loader_

### What needs fixing?
The registry exposed there is an internal registry only accessible from within Red Hat VPN

**Comment by e-minguez** [comment]
A quick search show this as well https://docs.openshift.com/container-platform/4.3/installing/installing_vsphere/installing-restricted-networks-vsphere.html#installation-vsphere-config-yaml_installing-restricted-networks-vsphere

**Comment by jboxman** [comment]
@e-minguez, thanks for reporting this!

**Comment by jboxman** [comment]
@kalexand-rh, do you know who might know the public-facing registry for vSphere-restricted?

**Comment by jboxman** [comment]
```
modules/installation-bare-metal-config-yaml.adoc
  60,11:   source: registry.svc.ci.openshift.org/ocp/release

modules/installation-generate-aws-user-infra-install-config.adoc
  104,11:   source: registry.svc.ci.openshift.org/ocp/release

modules/installation-vsphere-config-yaml.adoc
  58,11:   source: registry.svc.ci.openshift.org/ocp/release

modules/installing-cluster-loader.adoc
  13,20: $ sudo podman pull registry.svc.ci.openshift.org/ocp/4.3:tests

modules/running-cluster-loader.adoc
  21,1: registry.svc.ci.openshift.org/ocp/4.3:tests /bin/bash -c 'export KUBECONFIG=/root/.kube/config && \
  32,4: -i registry.svc.ci.openshift.org/ocp/4.3:tests \
```

**Comment by jboxman** [comment]
cc @ahardin-rh

**Comment by kalexand-rh** [comment]
@jboxman, I'm confused. For the restricted vSphere registry, you pull the images from the public registry and load them elsewhere. It's the same public registry as any installation.

**Comment by jboxman** [comment]
@kalexand-rh, I'm not familiar with what URLs are public vs private/internal; I haven't been able to determine if this issue is valid or not.

**Comment by e-minguez** [comment]
Let me try to clarify.

There are:
* registries exposed to internet where you can access without login (such as dockerhub, https://registry.centos.org/containers, etc.), aka. public registries.
* registries exposed to internet that require some kind of login (registry.redhat.io, others), aka. public registries (but require login)
* internal registries only accessible from within your company network (registry.svc.ci.openshift.org), aka. private registries.

In this case, as you say here "for the restricted vSphere registry, you pull the images from the public registry and load them elsewhere" means, you need to spin up a private registry somewhere (a VM, as a container, whatever) within your company network, and not exposing it to the internet.

The issue I've created is because 'registry.svc.ci.openshift.org' is a Red Hat internal registry used that stores non GA builds, test containers, etc. so users cannot use that registry unless they are Red Hat employees :)

In this particular case, the "registry.svc.ci.openshift.org/ocp/4.3:tests" image should be available somewhere else, but I'm not an expert here so you need to ask the proper person.

**Comment by kalexand-rh** [comment]
@ahardin-rh, @sjug, is there an external source for the cluster loader instead of `registry.svc.ci.openshift.org/ocp/4.3:tests`?

**Comment by ahardin-rh** [comment]
Resolved in https://github.com/openshift/openshift-docs/pull/24578
