### ISSUE TITLE
[enterprise-4.3] Edit suggested in file networking/multiple_networks/configuring-sr-iov.adoc

### ISSUE THREAD

**Issue by braultatgithub** [openshift/openshift-docs#20130]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.3/networking/multiple_networks/configuring-sr-iov.html

### What needs fixing?
"Disabling SRIOV Operator Admission Control Webhook
The SRIOV Operator Admission Control Webhook a Kubernetes Dynamic Admission Controller application that:"

it is missing "is" 

The SRIOV Operator Admission Control Webhook is a Kubernetes...

**Comment by jboxman** [comment]
@braultatgithub, thanks for reporting this!
