### ISSUE TITLE
[enterprise-4.2] Edit suggested in file cli_reference/openshift_developer_cli/creating-a-multicomponent-application-with-odo.adoc

### ISSUE THREAD

**Issue by adisky** [openshift/openshift-docs#20136]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.2/cli_reference/openshift_developer_cli/creating-a-multicomponent-application-with-odo.html#creating-a-project_creating-a-multicomponent-application-with-odo

### What needs fixing?
Move `Step2` and `Step3` from _Creating the _Project_ to _Deploying the back-end component_
 and _Deploying the front-end component_
> Creating a Project
1. `$ odo login -u developer -p developer`
2. `$ odo project create myproject`

> Deploying the back-end component

Keep Step 1, 2, 3 same.
4. `$ mkdir my_components`
5. Download the example application backend component
`$ git clone https://github.com/openshift-evangelists/Wild-West-Backend backend`
6. Change directory to the back-end source directory and check that you have the correct files in the directory: 
`$ cd backend 
... and so on

>  Deploying the front-end component
1.  Change the current directory to the front-end directory:
`$ cd ../frontend`
2.  Download the example application frontend component
`$ git clone https://github.com/openshift-evangelists/Wild-West-Frontend frontend`
3.  List the contents of the directory to see that the front end is a Node.js application.
`ls`
... and so on

**Comment by dharmit** [comment]
+1 to Aditi's suggestion.

**Comment by dharmit** [comment]
IIUC, this is not fixed. Between the `Validate` step mentioned in [Deploying the back-end component](https://docs.openshift.com/container-platform/4.6/cli_reference/developer_cli_odo/creating_and_deploying_applications_with_odo/creating-a-multicomponent-application-with-odo.html#deploying-the-back-end-component_creating-a-multicomponent-application-with-odo) section and `git clone` command of [Deploying the front-end component](https://docs.openshift.com/container-platform/4.6/cli_reference/developer_cli_odo/creating_and_deploying_applications_with_odo/creating-a-multicomponent-application-with-odo.html#deploying-the-front-end-component_creating-a-multicomponent-application-with-odo) section, user needs to make sure to `cd` into `my_components` directory created earlier.
