### ISSUE TITLE
[enterprise-4.2] Edit suggested in file cli_reference/openshift_developer_cli/creating-a-single-component-application-with-odo.adoc

### ISSUE THREAD

**Issue by adisky** [openshift/openshift-docs#20134]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.2/cli_reference/openshift_developer_cli/creating-a-single-component-application-with-odo.html#creating-a-project_creating-a-single-component-application-with-odo

### What needs fixing?
It is better to move `step2` and `step3` from _Creating a project_ to  _Creating a Node.js application with odo_ and with these changes there is no need for `step1` in _Creating a Node.js application with odo_, the flow will be like
> Creating a Project
1.  `odo login -u developer` -p `developer`
2.  `odo project create myproject`

>  Creating a Node.js application with odo
1. `mkdir my_components`, ` cd my_components`
2.  `git clone https://github.com/openshift/nodejs-ex`
3. `odo create nodejs`
...... and so on

**Comment by dharmit** [comment]
@adisky +1 to your suggestion. Steps 2 & 3 don't have anything to do with project creation.

**Comment by dharmit** [comment]
This is fixed.

/close
