### ISSUE TITLE
No apparent information on licensing on docs.okd.io

### ISSUE THREAD

**Issue by richardfontana** [openshift/openshift-docs#20183]
### Which section(s) is the issue in?

All.

### What needs fixing?

docs.okd.io should somehow or other provide some basic legal information including at least how OKD docs are licensed. This should be consistent with https://github.com/openshift/openshift-docs/blob/master/LICENSE (which says openshift-docs are dual licensed under the Apache License 2.0 and the Creative Commons Attribution-ShareAlike 3.0 Unported license).

For some OKD versions, there are links to legal notice pages where such information might seem to be found, but these appear to be 404s, e.g.
https://docs.okd.io/3.10/welcome/legal_notice.html#welcome-legal-notice
and are not present for all versions.

I'd recommend just having a globally applicable statement someplace that could be as simple as:

License: [Apache License 2.0](https://www.apache.org/licenses/LICENSE-2.0) or [Creative Commons Attribution-ShareAlike 3.0 Unported](https://creativecommons.org/licenses/by-sa/3.0/).

**Comment by richardfontana** [comment]
I see that the product docs legal notice is maintained in https://github.com/openshift/openshift-docs/blob/master/welcome/legal-notice.adoc (I assume). IMO it would **not** be preferable to reuse this for the community version, but if that's the easiest thing to do I guess that's okay. However there's one paragraph this notice that needs to be included also in the community version, at least in connection with the portion of docs it refers to (unless it's no longer accurate): 
`Portions adapted from https://github.com/kubernetes-incubator/service-catalog/ with modifications by Red Hat. Licensed under the link:https://www.apache.org/lic
enses/LICENSE-2.0[Apache License 2.0].`

**Comment by vikram-redhat** [comment]
@vrutkovs @dmueller2001 - what is the licensing for OKD and for OKD docs?

@mburke5678 FYI.

**Comment by vrutkovs** [comment]
@vikram-redhat OKD docs are licensed same as OCP docs

**Comment by vikram-redhat** [comment]
Thanks @vrutkovs - I am clarifying some licensing aspects with Richard offline and once done will add the same license to the OKD docs.

**Comment by mburke5678** [comment]
@vikram-redhat Do we need to do anything with this? OKD and OCP now both carry the _OpenShift documentation is licensed under the Apache License 2.0 (https://www.apache.org/licenses/LICENSE-2.0)._ wording.

**Comment by vikram-redhat** [comment]
Nope nothing else needs doing.
