### ISSUE TITLE
CC BY-SA attribution for openshift docs

### ISSUE THREAD

**Issue by richardfontana** [openshift/openshift-docs#20185]
### Which section(s) is the issue in?

Legal Notice

### What needs fixing?

Either the enterprise docs Legal Notice should do something to reference the existence of the openshift-docs github repo, or we should stop using CC-BY-SA for OpenShift docs and instead use the Apache License 2.0 as the license of enterprise OpenShift docs. 

Creative Commons licenses have requirements to provide attribution to authors. We can assume this requirement would apply to Red Hat as maintainer of openshift-docs to the extent that any copyrightable contribution to openshift-docs is ever received from contributors who are not Red Hat employees. A reasonable approach to attribution in this case would be simply to reference this repository given that it should have a record of any such contributions. 

One simple way of doing this would be to add a sentence to the Legal Notice (e.g. https://github.com/openshift/openshift-docs/blob/master/welcome/legal-notice.adoc) like:

> Derived from the [OpenShift documentation GitHub repository](https://github.com/openshift/openshift-docs). 

However, as an alternative, we could stop using CC BY-SA for the license for OpenShift enterprise documentation and instead use the Apache License 2.0 -- in which case we could also simplify the license of the openshift-docs repository to just Apache-2.0. I actually consider this slightly preferable because at this point we are only using CC BY-SA 3.0 in Red Hat product and project docs for historical reasons. Also the practice of using CC BY-SA 3.0 for Red Hat product documentation did not really contemplate a situation where documentation for both community and product versions of the same documentation would be created at essentially the same time by the same people. The Apache LIcense (normally used for software, but it can also be used for documentation) does not have an affirmative requirement to provide attribution, though any existing attribution notices have to be preserved. Note also that CC BY-SA 3.0 has been superseded by CC BY-SA 4.0 and there is no particular reason why we should continue using 3.0 anyway.

**Comment by vikram-redhat** [comment]
Thanks @richardfontana. @sferich888 and @reestr do you have a preference/thoughts on this? Once I hear from you I will run by legals/BU.

**Comment by vikram-redhat** [comment]
@aheslin FYI

**Comment by jboxman** [comment]
@vikram-redhat, did we ever resolve this? I thought we had?

**Comment by vikram-redhat** [comment]
We did.
