### ISSUE TITLE
[enterprise-4.3] Edit suggested in file storage/persistent_storage/persistent-storage-local.adoc

### ISSUE THREAD

**Issue by ChetHosey** [openshift/openshift-docs#20181]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.3/storage/persistent_storage/persistent-storage-local.html#local-storage-install_persistent-storage-local

### What needs fixing?

The project creation step should include an annotation which blocks a default node selector, such as with:

```
oc annotate project local-storage openshift.io/node-selector=''
```

Without this annotation pods will inherit the cluster-wide default selector.

Clusters with infrastructure nodes are likely to use a default node selector that includes only worker nodes. This prevents the scheduler from running user apps on infra nodes in compliance with licensing.

However one might want to use the local storage operator to create volumes on infrastructure nodes in support of logging and monitoring components.

This is similar to https://bugzilla.redhat.com/show_bug.cgi?id=1782151.

**Comment by bobfuru** [comment]
Thanks, @ChetHosey!

**Comment by bobfuru** [comment]
Docs have been updated to include the optional step:
https://docs.openshift.com/container-platform/4.2/storage/persistent_storage/persistent-storage-local.html#local-storage-install_persistent-storage-local
