### ISSUE TITLE
Document AlwaysPullImages and BuildOverrides admission controllers

### ISSUE THREAD

**Issue by liggitt** [openshift/openshift-docs#2019]
install_config/configuring_admission_control.html#overriding-the-default-list-of-admission-control-plug-ins-for-kubernetes-resources does not include new admission controllers

Two important ones are AlwaysPullImages and BuildOverrides

BuildOverrides is in the OpenShift admission chain, and requires builds to pull their builder/source images. This ensures the builder in the current project has access to those images, instead of possibly reusing an image that was already pulled to the node by another user.

AlwaysPullImages is in the Kubernetes admission chain, and overrides pods' image pull policy to "Always". This ensures pods in the current project have access to those images, instead of possibly reusing an image that was already pulled to the node by another user.

Enabling these admission controllers mean that the source registry for build and pod images must be reachable to perform access checks, or builds/deployments will fail.

cc @pweil- @ncdc @deads2k

**Comment by adellape** [comment]
When we add BuildOverrides to the list, we can link to the dedicated topic: https://docs.openshift.org/latest/install_config/build_defaults_overrides.html

Currently no docs on AlwaysPullImages.

**Comment by bfallonf** [comment]
I attached this issue to a BZ:

https://bugzilla.redhat.com/show_bug.cgi?id=1338919

Closing this in favour of that.
