### ISSUE TITLE
[enterprise-4.3] Edit suggested in managing memcached operator

### ISSUE THREAD

**Issue by KedarS05** [openshift/openshift-docs#20198]
### Which section(s) is the issue in?

Managing memcached-operator section -> Step 5. Update an application.

In the below statement the Operator manifest file hyperlink seems to be broken

- The following command demonstrates applying a new "[Operator manifest file](https://github.com/operator-framework/getting-started/blob/master/memcachedoperator.0.0.2.csv.yaml)" using a new version  
   of the Operator and shows that the pods remain executing

**Comment by vikram-redhat** [comment]
@adellape https://docs.openshift.com/container-platform/4.3/operators/operator_sdk/osdk-getting-started.html#managing-memcached-operator-using-olm_osdk-getting-started

**Comment by adellape** [comment]
Looks like they were removed via https://github.com/operator-framework/getting-started/pull/57.

Might be able to use the following instead:

https://github.com/operator-framework/operator-sdk/blob/master/test/test-framework/deploy/olm-catalog/memcached-operator/0.0.2/memcached-operator.v0.0.2.clusterserviceversion.yaml

Will update again shortly.

**Comment by KedarS05** [comment]
@adellape thanks .. i guess we need to make these changes in every OCP 4.x documentation as the link seems to be missing from every documentation section. For now we can provide this manifest file to the users.
