### ISSUE TITLE
[enterprise-4.3] Edit suggested in file service_mesh/service_mesh_install/installing-ossm.adoc

### ISSUE THREAD

**Issue by yocum137** [openshift/openshift-docs#20218]
### Which section(s) is the issue in?

Customer has encountered an issue with the "Installing the Jaeger Operator" section.  

### What needs fixing?

Please add the following to the beginning of the section:

You must install the Jaeger Operator for the Red Hat OpenShift Service Mesh Operator to install the control plane.  

Note: After installing the Elasticsearch Operator, ensure that the Elasticsearch pods have successfully rolled out prior to installing the Jaeger Operator otherwise the Jaeger Operator will attempt to roll them out, again.

**Comment by vikram-redhat** [comment]
@JStickler @neal-timpe

**Comment by knrc** [comment]
@objectiser may be able to advise

**Comment by objectiser** [comment]
@JStickler I thought the install section does require the user to first install Elasticsearch Operator, then Jaeger operator and only then Service Mesh operator?

@yocum137 just to confirm, you are referring to the Elasticsearch Operator pod? This may be a side effect of the "requires" dependency currently defined between the Jaeger operator and Elasticsearch operator, which will be removed in the next release. However if it is causing such problems, it may be best to include a warning in the docs for now.
