### ISSUE TITLE
[enterprise-4.3] Edit suggested in file networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-service-external-ip.adoc

### ISSUE THREAD

**Issue by dmesser** [openshift/openshift-docs#20224]
### Which section(s) is the issue in?

This chapter misses essential information on how to configure CIDR ranges that are used with external service IPs using `NetworkPolicy`. Because of this it is not clear, how the IP `172.30.131.89` from the example of the [Exposing a Service by Creating a Route](https://docs.openshift.com/container-platform/4.3/networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-service-external-ip.html#nw-exposing-service_configuring-ingress-cluster-traffic-service-external-ip) was determined.

### What needs fixing?

At the very beginning of this chapter there needs to be either pointers, or even better, directions on how to define IP address pools for external service IPs and the fact that this is the primary method to expose applications in bare-metal environments if you don't want to rely on NodePort.
The information is currently hidden in a subscriber-only KB: https://access.redhat.com/solutions/4550681

**Comment by bmcelvee** [comment]
Since there is an existing, related Jira issue (https://issues.redhat.com/browse/OSDOCS-536). I'm going to go ahead and link this Github there so the work can be tracked in one place. 

Thanks again, @dmesser, for brining this up!
