### ISSUE TITLE
[enterprise-4.2] Edit suggested in file web_console/customizing-the-web-console.adoc

### ISSUE THREAD

**Issue by KedarS05** [openshift/openshift-docs#20276]
### Which section(s) is the issue in?
Step 2 of Procedure:[Edit the web console’s Operator configuration to include customLogoFile and customProductName:] the document points to wrong command needs to be modified to the below command.

$ oc apply -f <file> <-----------------------------------------Wrong command which does not suggest an edit 
$ oc edit console.operator.openshift.io cluster <------New command which edits the web-console operator

**Comment by ahardin-rh** [comment]
The fix in https://github.com/openshift/openshift-docs/pull/20277 is now merged
