### ISSUE TITLE
Documentation doesn't work with Firefox's Reader View

### ISSUE THREAD

**Issue by mnagy** [openshift/openshift-docs#2031]
Open a page (e.g. [Builds and Image Streams](https://ci.openshift.redhat.com/openshift-docs-master-testing/latest/architecture/core_concepts/builds_and_image_streams.html)) and enter the [Reader View](https://support.mozilla.org/en-US/kb/firefox-reader-view-clutter-free-web-pages). The result is pretty bad, I can only see some YAML. On some other pages, the view doesn't load at all (e.g. [here](https://docs.openshift.org/latest/install_config/install/rpm_vs_containerized.html))

**Comment by mburke5678** [comment]
After discussing the matter with the team, I am told there is nothing in our production environment we can do to prevent this from occurring.  Please let us know if you have a solution. Closing.
