### ISSUE TITLE
[enterprise-4.2] Edit suggested in file installing/installing_vsphere/installing-vsphere.adoc

### ISSUE THREAD

**Issue by chuckersjp** [openshift/openshift-docs#20360]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.2/installing/installing_vsphere/installing-vsphere.html#installation-vsphere-machines_installing-vsphere

Step 5 section d.

### What needs fixing?

This section states:
```In the window that is displayed, enter the folder name. The folder name must match the cluster name that you specified in the install-config.yaml file.```

but doesn't indicate why this is actually needed.  It would be helpful for customers to understand the reasoning for this requirement.

### Suggested change

```In the window that is displayed, enter the folder name. The folder name must match the cluster name that you specified in the install-config.yaml file.  The reason for this is so that the dynamic provisioning of storage through vcenter is able to select the appropriate location for its Workspace configuration.```

**Comment by tsailiming** [comment]
The document should also highlight that the folder name is a top level folder.

**Comment by bergerhoffer** [comment]
@chuckersjp It looks like this step has been updated with PR #24161: https://docs.openshift.com/container-platform/4.7/installing/installing_vsphere/installing-vsphere.html#installation-vsphere-machines_installing-vsphere

It now says: 

```
In the window that is displayed, enter the folder name. If you did not specify an existing folder in the install-config.yaml file, then create a folder with the same name as the infrastructure ID.
```

Can you let me know if/what we still need clarification around this updated text?

p.s. I can see that the formatting/numbering of this procedure is messed up, so I'll fix that right now in the meantime.

**Comment by chuckersjp** [comment]
Again, it doesn't really explain _why_ you need the names to match up or the ramifications of it not being the same.
