### ISSUE TITLE
Update links to OCP-4.3 errata

### ISSUE THREAD

**Issue by ableischwitz** [openshift/openshift-docs#20384]
### Which section(s) is the issue in?
/updating/updating-cluster-cli.html

### What needs fixing?
"You can find information about available OpenShift Container Platform advisories and updates **in the errata section** of the Customer Portal." <= Link pointing to **OCP-4.1 errata**, should be **4.3** with 4.3 documentation.
Are there ways to link the version of the doc to the versions given in the links?

**Comment by codyhoag** [comment]
Thanks for pointing this out! Submitted and merged for 4.2 and 4.3: #20386 and #20387
