### ISSUE TITLE
[enterprise-4.2] Edit suggested in file networking/routes/route-configuration.adoc

### ISSUE THREAD

**Issue by cskidmor** [openshift/openshift-docs#20414]
### Which section(s) is the issue in?

the route-configuration section or possibly other sections where the reference to F5 BIG-IP seems to be omitted.

### What needs fixing?

As part of the earlier 3.11 documentation from the following link:

https://docs.openshift.com/container-platform/3.11/install_config/router/f5_router.html

"The F5 router plug-in will be deprecated in OpenShift Container Platform version 3.11. The functionality of the F5 router plug-in is replaced in the F5 BIG-IP® Controller for OpenShift. For more information, see F5 BIG-IP Controller for OpenShift. For information about migrating existing deployments from the F5 router plug-in to the BIG-IP Controller for OpenShift, see Replace the F5 Router with the F5 BIG-IP Controller for OpenShift."

However, there is no reference to the F5 BIG-IP Controller for OpenShift in 4.x documentation.  Please add references to the F5 BIG-IP Controller.  Thank you!

**Comment by vikram-redhat** [comment]
Documentation for partner content is still under review.
