### ISSUE TITLE
“no longer supported” text overlaps body on mobile

### ISSUE THREAD

**Issue by bderiso** [openshift/openshift-docs#20486]
This is using Safari or Chrome on iOS 13.3.1, iPhone XR.

### Which section(s) is the issue in?
Overlay

### What needs fixing?
Add ability to dismiss message?
Change text to render in-line?

**Comment by bderiso** [comment]
![52AB3FF9-1B8D-48F6-BC02-122FAAB36CA1](https://user-images.githubusercontent.com/6864575/76708173-d4e9c480-66c2-11ea-92f8-672f67571866.png)

**Comment by bderiso** [comment]
![B768EBBE-86CF-4821-BD42-6C2AB36E8834](https://user-images.githubusercontent.com/6864575/76708189-e92dc180-66c2-11ea-92e6-096518f50daa.png)

**Comment by bderiso** [comment]
Example: https://docs.openshift.com/container-platform/3.10/welcome/index.html
![0AD7CDBF-379C-4B8C-96A6-59F914F098A3](https://user-images.githubusercontent.com/6864575/76708213-1ed2aa80-66c3-11ea-8842-a694cb193d32.png)

**Comment by jboxman** [comment]
@vikram-redhat, this looks like it's on mobile.
