### ISSUE TITLE
[OKD] Document pages footer

### ISSUE THREAD

**Issue by lbrigman124** [openshift/openshift-docs#20578]
### Which section(s) is the issue in?
All pages in the OKD docs show a RedHat logo and Powered by OpenShift Online by Redhat.

### What needs fixing?
I'm unsure if this needs a fix or not but it should be examined to determine the right information on the footer.

**Comment by mburke5678** [comment]
The OKD Latest docs appear to have the same footer as the OKD 3.x docs. 
@vikram-redhat @vrutkovs Is the  footer for the OKD docs appropriate or do we need a change?

**Comment by vrutkovs** [comment]
OKD is a Red Hat-sponsored project (like Fedora for instance) and docs site is powered by OpenShift Online.

What would you like to change?

**Comment by lbrigman124** [comment]
I was just asking that others with more knowledge verify that the OKD project authorized to use the Redhat logo and other icons that are in the footer of every doc page.
