### ISSUE TITLE
[OKD] Vsphere install page references Redhat Cluster Manager

### ISSUE THREAD

**Issue by lbrigman124** [openshift/openshift-docs#20577]
### Which section(s) is the issue in?
https://docs.okd.io/latest/installing/installing_vsphere/installing-vsphere.html#installing-vsphere
Internet and Telemetry Access for OKD

### What needs fixing?
Document what is needed for OKD installations instead of OpenShift Enterprise entitlements.

**Comment by lbrigman124** [comment]
There are other references on this page further down that refer to RHCOS as the base images.

This URL reference later: https://access.redhat.com/articles/4128421
for prereqs in user provisioned infrastructure.

References to Redhat images: https://access.redhat.com/downloads/content/290
And a Redhat COS Mirrors: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.3/

**Comment by mburke5678** [comment]
@vrutkovs Is this something you can help with?

**Comment by vrutkovs** [comment]
Yeah, I'll take care of that
