### ISSUE TITLE
"Configuration for ipam CNI plug-in" section needs to be clarified with each IPAM plugin because of its configuration.

### ISSUE THREAD

**Issue by s1061123** [openshift/openshift-docs#20630]
### Which section(s) is the issue in?

"Configuration for ipam CNI plug-in" in the following documents:
- https://docs.openshift.com/container-platform/4.3/networking/multiple_networks/configuring-bridge.html#nw-multus-ipam-object_configuring-bridge
- https://docs.openshift.com/container-platform/4.3/networking/multiple_networks/configuring-ipvlan.html#nw-multus-ipam-object_configuring-ipvlan
- https://docs.openshift.com/container-platform/4.3/networking/multiple_networks/configuring-host-device.html#nw-multus-ipam-object_configuring-host-device

### What needs fixing?

 Currently "Configuration for ipam CNI plug-in" describes IPAM configuration in one configuration as all IPAM plugin (dhcp/static) shared same configuration so that user misunderstanding that dhcp and static CNI configuration is same, however actually dhcp and static CNI configuration is very different from each other, hence we need to add more description for that.

 In addition, current document, "Configuration for ipam CNI plug-in" describe that `addresses` fields accepts a block of IP addresses but actually it only supports `an IP address`, not a block nor an IP range.

### Proposed Solution

1. Create following subsection under  "Configuration for ipam CNI plug-in"
  - Configuration for dhcp ipam CNI plug-in
  - Configuration for static ipam CNI plug-in

2. Show example config for each as following:

Configuration for dhcp ipam CNI plug-in:

```
{
        "ipam": {
                "type": "dhcp",
        }
}
```

Configuration for dhcp ipam CNI plug-in:
This config is same as current document.

```
{
  "ipam": {
    "type": "<type>",
    "addresses": [
      {
        "address": "<address>",
        "gateway": "<gateway>"
      }
    ],
    "routes": [
      {
        "dst": "<dst>"
        "gw": "<gw>"
      }
    ],
    "dns": {
      "nameservers": ["<nameserver>"],
      "domain": "<domain>",
      "search": ["<search_domain>"]
    }
  }
}
```

3. In static IPAM configuration, we need to change `A block of IP addresses` to `An IP address`.

### Reference discussion

See following discussion for the detail.

- https://bugzilla.redhat.com/show_bug.cgi?id=1780604

**Comment by jboxman** [comment]
@s1061123, finally working on this.

**Comment by jboxman** [comment]
This will be resolved by https://github.com/openshift/openshift-docs/pull/23057.

**Comment by jboxman** [comment]
@s1061123, I've completed the work for this. Thanks!
