### ISSUE TITLE
"Removing a Pod from an additional network" is not supported yet

### ISSUE THREAD

**Issue by s1061123** [openshift/openshift-docs#20647]
### Which section(s) is the issue in?

'Removing a Pod from an additional network' at 4.2/4.3 doc.

 https://docs.openshift.com/container-platform/4.3/networking/multiple_networks/removing-pod.html
 https://docs.openshift.com/container-platform/4.2/networking/multiple_networks/removing-pod.html

### What needs fixing?

This document describes that changing annotation with `oc edit` command removes interface from pod,
however, current multus-cni does not support remove interfaces dynamically yet.
So this section needs to be changed.

**Comment by jboxman** [comment]
@s1061123, how do you remove a Pod from an additional network today?

Thanks!
