### ISSUE TITLE
[enterprise-4.3] Edit suggested in file service_mesh/service_mesh_install/preparing-ossm-installation.adoc

### ISSUE THREAD

**Issue by jxadro** [openshift/openshift-docs#20644]
In the documentation about Service Mesh you can find the following information:

https://docs.openshift.com/container-platform/4.3/service_mesh/service_mesh_install/preparing-ossm-installation.html#ossm-installation-activities_preparing-ossm-installation

" Please see configuring Elasticsearch for details on configuring the default Jaeger parameters for Elasticsearch in a production environment."

But there is no link to any additional documentation, the only related thing I have found is: https://docs.openshift.com/container-platform/4.3/service_mesh/service_mesh_day_two/configuring-jaeger.html#ossm-jaeger-config-elasticsearch_configuring-jaeger

To what documentation is referring that sentence?

Thank you.

**Comment by jxadro** [comment]
This is where a links should point:

https://docs.openshift.com/container-platform/4.3/service_mesh/service_mesh_install/customizing-installation-ossm.html#ossm-configuring-jaeger-elasticsearch_customizing-installation-ossm

**Comment by neal-timpe** [comment]
I've added a fix to this PR which should be merged later this week. https://github.com/openshift/openshift-docs/pull/20503

**Comment by neal-timpe** [comment]
Fixed
