### ISSUE TITLE
registry doc fixes

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-docs#2068]
https://docs.openshift.org/latest/install_config/install/docker_registry.html
- [ ] https://docs.openshift.org/latest/install_config/install/docker_registry.html#file-storage [1]
- [ ] https://docs.openshift.org/latest/install_config/install/docker_registry.html#file-storage [2]
- [ ] https://docs.openshift.org/latest/install_config/install/docker_registry.html#access-logging-in-to-the-registry [3]
- [ ] https://docs.openshift.org/latest/install_config/install/docker_registry.html#securing-the-registry [4]
- [ ] https://docs.openshift.org/latest/install_config/install/docker_registry.html#deploying-updated-configuration [5]

[1] `grep ose-docker-registry` should be `grep docker-registry` and soon `grep registry` (https://github.com/openshift/origin/issues/8849)  in step 3.
[2] `docker exec -it 4c01db0b339c find /registry` should be `oc rsh dc/docker-registry find /registry`   in step 4.
[3] 2. can be squashed in 3. (`docker login -u $(oc whoami) -e <any_email_address> -p $(oc whoami -t) <registry_ip>:<port>`)
[4] Once we support `oc rollout {pause,resume}` in Origin, we should pause the deployment **before** starting the configuration (step.6) and resume it **after** finishing (step.9).
[5] We should use configmaps now instead of secrets for configuration

cc: @miminar @legionus @soltysh

**Comment by miminar** [comment]
:+1:

**Comment by mburke5678** [comment]
@kargakis @miminar 
Issue [1] mentions that the command will change again "soon." Will `grep registry` work now? Which OCP versions?
[1]  soon grep registry 

Also, do we support `oc rollout`? Which version?

**Comment by kargakis** [comment]
> Issue [1] mentions that the command will change again "soon." Will grep registry work now? Which OCP versions?

The renaming is still outstanding: https://github.com/openshift/origin/issues/8849

> Also, do we support oc rollout? Which version?

Not sure what you mean with "which version". Openshift now moves in 3.7 as its latest version. We have been supporting `oc rollout` ever since 3.5 IIRC.

**Comment by kargakis** [comment]
Maybe 3.4

**Comment by mburke5678** [comment]
@kargakis 
So, `oc rollout` was added in 3.5 for certain.

Which OCP versions can we apply [1] and [2]? 3.3, 3.4. 3.5?

**Comment by mburke5678** [comment]
@kargakis 
Also, can you help with [5]? Not sure how to use a ConfigMap to apply config changes to the registry service.

**Comment by miminar** [comment]
> So, oc rollout was added in 3.5 for certain.

3.4 has `oc rollout {pause,resume,status}` as well.

> Which OCP versions can we apply [1] and [2]? 3.3, 3.4. 3.5?

For [1], all the mentioned [3.3](https://github.com/openshift/openshift-docs/blob/enterprise-3.3/install_config/install/docker_registry.adoc#file-storage), [3.4](https://github.com/openshift/openshift-docs/blob/enterprise-3.4/install_config/install/docker_registry.adoc#file-storage), [3.5](https://github.com/openshift/openshift-docs/blob/enterprise-3.5/install_config/install/docker_registry.adoc#file-storage) apply. And the same for [2].

**Comment by mburke5678** [comment]
@jianlinliu Can you suggest someone in QE to review these changes?
