### ISSUE TITLE
[enterprise-4.3] Edit suggested in file machine_management/creating-infrastructure-machinesets.adoc

### ISSUE THREAD

**Issue by kfryklund** [openshift/openshift-docs#20688]
### Which section(s) is the issue in?
I'd like to suggest we append some additional information to this doc

### What needs fixing?
Please add the following sub sections to this documentation:
1. How to prevent normal user applications from landing on infra nodes.  Whether this be by using taints or by editing the cluster scheduler with something like "defaultNodeSelector: node-role.kubernetes.io/worker=" as detailed here [1].  Or, if there's another preferred method.
2. How to create new machineConfigPools for your infrastructure nodes.  This is very easy, but not detailed in the documentation.  It as already been documented in a redhat article here [2]

[1] https://docs.openshift.com/container-platform/4.3/nodes/scheduling/nodes-scheduler-node-selectors.html#nodes-scheduler-node-selectors-cluster_nodes-scheduler-node-selectors
[2] https://access.redhat.com/solutions/4342791

**Comment by yrro** [comment]
>   2. How to create new machineConfigPools for your infrastructure nodes.  This is very easy, but not detailed in the documentation.  It as already been documented in a redhat article here [2]
> 
> [2] https://access.redhat.com/solutions/4342791

This results in infra nodes having both the `infra` role (from the newly created `*-infra` MachineSet) _and_ the `worker` role (from the `01-worker-kubelet` MachineConfig). It's not documented how to then prevent your workloads from placing on the `infra` nodes without further work:

If there is a way to annotate a project to say "deploy on nodes with role `worker` *and* without role `infra` then I couldn't find it.

I ended up modifying my `*-worker` MachineSet to add an additional `app` role to the machines it creates, and then deleted my worker machines. Once new nodes had finished bootstrapping they came up with both the `worker` and `app` rules. It's then easy to configure projects to schedule only on `app` nodes.
