### ISSUE TITLE
[enterprise-4.3] Edit suggested in file networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-ingress-controller.adoc

### ISSUE THREAD

**Issue by shortsteps** [openshift/openshift-docs#20694]
### Which section(s) is the issue in?
[Creating a project and service](https://docs.openshift.com/container-platform/4.3/networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-ingress-controller.html#nw-creating-project-and-service_configuring-ingress-cluster-traffic-ingress-controller), step 4

### What needs fixing?
Is the command correct?
```
$ oc get svc -n openshift-ingress
NAME                      TYPE           CLUSTER-IP      EXTERNAL-IP      PORT(S)                      AGE
router-default            LoadBalancer   172.30.16.119   52.230.228.163   80:30745/TCP,443:32561/TCP   2d6h
router-internal-default   ClusterIP      172.30.101.15   <none>           80/TCP,443/TCP,1936/TCP      2d6h
```
I would have expected something related to _myproject_ namespace just created or to _mysql-55-rhel7_ service referenced shortly after.
I could not understand this step and it confuses me.

**Comment by jboxman** [comment]
@shortsteps, I've rewritten the procedure. If that doesn't help, open a new issue. Thanks!
