### ISSUE TITLE
The --credentials for oadm router and oadm registry was deprecated

### ISSUE THREAD

**Issue by mnagy** [openshift/openshift-docs#2074]
The --credentials flag for oadm router and oadm registry has been deprecated, but we use it all over the place in the docs. @liggitt @deads2k can you confirm please? Not sure what we should put in docs instead, but it's not a great experience going through the steps and getting deprecated errors.

**Comment by liggitt** [comment]
Correct, need to sweep and remove. One thing to watch out for is that omitting credentials triggers those commands to create the referenced service account, which assumes it does not already exist. If the instructions include steps to manually create the service account first, those should probably be removed.

**Comment by tnguyen-rh** [comment]
@mnagy Can the deprecation messages be suppressed (by an environment variable, for example)?

**Comment by liggitt** [comment]
> Can the deprecation messages be suppressed (by an environment variable, for example)?

I don't think so. We should fix the docs to use non-deprecated examples.

**Comment by mburke5678** [comment]
Fixed in https://github.com/openshift/openshift-docs/pull/3552
