### ISSUE TITLE
[enterprise-4.2] Edit suggested in file logging/config/cluster-logging-collector.adoc

### ISSUE THREAD

**Issue by aelicieguo** [openshift/openshift-docs#20748]
### Which section(s) is the issue in?

There should be a section on how to push audit logs to elasticsearch/kibana

### What needs fixing?
Cluster logging should be set to unmanaged state, thereafter add the following env variables:
AUDIT FILE = /var/log/kube-apiserver/audit.log
AUDIT_POS_FILE = /var/log/kubeapiserver/audit.pos

**Comment by mburke5678** [comment]
@aelicieguo We have a log forwarding feature that can use a new API (currently tech preview) or fluentd or syslog protocols to forward logs to external systems. Does this address your concern? 
https://docs.openshift.com/container-platform/4.4/logging/config/cluster-logging-external.html
https://docs.openshift.com/container-platform/4.5/logging/cluster-logging-external.html

**Comment by mburke5678** [comment]
@aelicieguo How does this look? Feel free to re-open this issue if this doesn't meet your expectations.
**Forward audit logs to the log store**
https://docs.openshift.com/container-platform/4.5/logging/config/cluster-logging-log-store.html#cluster-logging-elasticsearch-audit_cluster-logging-store
