### ISSUE TITLE
[enterprise-4.2] Edit suggested in file networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-service-external-ip.adoc

### ISSUE THREAD

**Issue by kavithakatepalli** [openshift/openshift-docs#20801]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.3/networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-service-external-ip.html#configuring-ingress-cluster-traffic-service-external-ip 

### What needs fixing?
This page explains upto accessing service within cluster.
configuring externalip and accessing it from outside cluster information is missing

**Comment by jboxman** [comment]
This also relates to _ExternalIP_ provided by the Cluster Network Operator. We have a Jira for this.

**Comment by jboxman** [comment]
Hi @kavithakatepalli, I've updated the content for this: https://docs.openshift.com/container-platform/4.5/networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-service-external-ip.html

Thanks!
