### ISSUE TITLE
[enterprise-4.3] Edit suggested in file serverless/installing_serverless/installing-openshift-serverless.adoc

### ISSUE THREAD

**Issue by AarneO** [openshift/openshift-docs#20855]
### Which section(s) is the issue in?

Installing the OpenShift Serverless Operator

### What needs fixing?

Link to "Installing Knative Serving" gives 404, link probably should point to this url https://docs.openshift.com/container-platform/4.3/serverless/installing_serverless/installing-knative-serving.html

**Comment by jboxman** [comment]
@abrennan89 ^

**Comment by abrennan89** [comment]
Thanks @jboxman  - are you able to assign this to me? I'll fix it today.

**Comment by jboxman** [comment]
@abrennan89, done!

**Comment by abrennan89** [comment]
@jboxman the fix has been merged for this so the issue can probably be closed. Thanks!

**Comment by jboxman** [comment]
@abrennan89, epic!
