### ISSUE TITLE
[enterprise-4.3] Edit suggested in file cli_reference/openshift_cli/administrator-cli-commands.adoc

### ISSUE THREAD

**Issue by franckgr** [openshift/openshift-docs#20860]
### Which section(s) is the issue in?
create-api-client-config

### What needs fixing?
Remove the section this command doesn't exist anymore

oc adm create-api-client-config
error: unknown command "create-api-client-config"
See 'oc adm -h' for help and examples

**Comment by bergerhoffer** [comment]
Open against the master branch.

**Comment by kcclemo** [comment]
@bergerhoffer I'd like to work on this.

**Comment by bergerhoffer** [comment]
Closing as the above linked PRs covered the updates.
