### ISSUE TITLE
[enterprise-4.1] Edit suggested in file authentication/certificates/replacing-default-ingress-certificate.adoc

### ISSUE THREAD

**Issue by chuckersjp** [openshift/openshift-docs#20889]
### Which section(s) is the issue in?

Under Replacing Default Ingress Certificate and the Procedure

### What needs fixing?
The following is missing:

Procedure

    Create a ConfigMap that includes the certificate authority used to signed the new certificate:

    $ oc create configmap custom-ca \
         --from-file=ca-bundle.crt=</path/to/example-ca.crt> \
         -n openshift-config

Either this section needs to be added OR a header should be placed at the top of all 4.1 docs stating that you are not looking at the most recent release.

**Comment by bergerhoffer** [comment]
Closing - there is now a banner at the top that warns that you're looking at an old version.
