### ISSUE TITLE
We don't explain what deployment hooks are for

### ISSUE THREAD

**Issue by danmcp** [openshift/openshift-docs#2092]
Looking here:

https://docs.openshift.org/latest/dev_guide/deployments.html#lifecycle-hooks

We could really use more examples of how to actually use the deployment hooks and what they should/could be used for.  Ex: rake db:migrate.

**Comment by ahardin-rh** [comment]
Looks like this content was reworked and expanded since this was filed:
https://docs.openshift.com/container-platform/3.6/dev_guide/deployments/deployment_strategies.html#lifecycle-hooks

Closing, but please reopen if you think more work is needed.
