### ISSUE TITLE
Formatting inconsistencies for true/false literals

### ISSUE THREAD

**Issue by mnagy** [openshift/openshift-docs#2093]
We use various forms of true/false literal. I can see backquotes and asterisks both:

```
$ git grep -F '*true*' | wc -l
47
$ git grep -F '`true`' | wc -l
10
$ git grep -F '`*true*`' | wc -l
1
$ git grep -F '*false*' | wc -l
10
$ git grep -F '`false`' | wc -l
7
```

This is inconsistent and resulting text is rendered differently.

**Comment by mburke5678** [comment]
Fixed in https://github.com/openshift/openshift-docs/pull/2102
