### ISSUE TITLE
Sizing recommendations have misprint

### ISSUE THREAD

**Issue by etsauer** [openshift/openshift-docs#2095]
The sizing recommendations here: https://github.com/openshift/openshift-docs/blob/master/install_config/install/prerequisites.adoc#sizing-recommendations

It specifies 1 CPU and 2.5 GB Ram per _**1000**_ pods... I believe that should say _**100**_.

**Comment by adellape** [comment]
@etsauer That addition came from this PR: https://github.com/openshift/openshift-docs/pull/1961

Which got its info from this Issue: https://github.com/openshift/openshift-docs/issues/1949

The Issue mentions "per 1k pods". @timothysc Can you verify?

**Comment by etsauer** [comment]
@adellape there's no way the recommendation could be 1 core & 2.5 GB RAM for 1000 pods. Also, in the next line there's some math that calculates to 20 cores and 50 GB RAM for 2000 pods. That math doesn't add up. Either way, i'd like to know where the numbers came from. Even it was meant to be _**100**_, that's assuming VERY tiny pods. A single java pod could easily consume 2GB Ram on its own. These measures are highly dependent on the language, and nature of the workload running inside of it. I'm all for recommending reasonable defaults to start with, but these don't seem very reasonable.

**Comment by timothysc** [comment]
The sizing is for the **master daemons in a HA configuration**.  

If you want to run 20k pod cluster you will need to size your 
3 Masters, 3 - Etcd servers appropriately. 

1 cpu core, and 2.5 GB of memory atop of the defaults per 1k pods. So for 20k pods that would be (20+2) cpu cores and and (50+8) GB of ram.

That means each **master** machine is large. 

This **is not** the sizing of compute nodes.. It's the sizing of master daemons.

**Comment by etsauer** [comment]
ok, that makes way more sense. That section needs to be more clear about being sizing for masters. However, if we're going to have sizing for masters, it seems we should also talk about calculating sizing for nodes.

**Comment by adellape** [comment]
@bfallonf FYI on the above, per https://github.com/openshift/openshift-docs/pull/1961.

**Comment by timothysc** [comment]
Sizing of the nodes, is entirely based on workloads being run.  Operators will need to determine their workload profile and size appropriately based on the profiles of their pods - some system reserve for those machines.

**Comment by etsauer** [comment]
@timothysc agreed its very subjective, but its confusing if we provide guidelines for masters and not nodes. At minimum we need to say something about calculating workload size, leaving room for overhead, and determining node size based on that.

**Comment by timothysc** [comment]
sgtm.

**Comment by bfallonf** [comment]
@etsauer @timothysc Started a PR on this #2108 

Let me know if this needs more info.
