### ISSUE TITLE
[enterprise-4.3] Edit suggested in file logging/cluster-logging-troubleshooting.adoc

### ISSUE THREAD

**Issue by aelicieguo** [openshift/openshift-docs#20956]
### Which section(s) is the issue in?
The command oc delete oauthclient/kibana-proxy doesn't work.

oc delete oauthclient/kibana-proxy
Error from server (NotFound): oauthclients.oauth.openshift.io "kibana-proxy" not found

oc get oauthclient
NAME                           SECRET                                        WWW-CHALLENGE   TOKEN-MAX-AGE   REDIRECT URIS
console                        awY3deNzRStOfX0ED0kEEYHI35wO7biKNv_EK6ubL5w   false           default         https://console-openshift-console.apps.ocp-prod-bkk2.krungsri.net/auth/callback
kiali-istio-system                                                           false           default         https://kiali-istio-system.apps.ocp-prod-bkk2.krungsri.net,localhost:3000
openshift-browser-client       ceHQz8G8BfgAYsQIIxqIPgI5BJYoXgMixgmuGZ9mgig   false           default         https://oauth-openshift.apps.ocp-prod-bkk2.krungsri.net/oauth/token/display
openshift-challenging-client                                                 true            default         https://oauth-openshift.apps.ocp-prod-bkk2.krungsri.net/oauth/token/implicit

**Comment by mburke5678** [comment]
@aelicieguo Thanks for pointing this out.
https://github.com/openshift/openshift-docs/pull/25973

**Comment by aelicieguo** [comment]
Hi, there were sensitive info in the comment, can I request for the team to remove this issue?

**Comment by mburke5678** [comment]
@aelicieguo Please let me know what info you think we should remove and I can look into it.
