### ISSUE TITLE
`odo init` in documentation makes it sound like it's a command

### ISSUE THREAD

**Issue by cdrage** [openshift/openshift-docs#20979]
### Which section(s) is the issue in?

https://docs.openshift.com/online/starter/cli_reference/openshift_developer_cli/using_odo_in_a_restricted_environment/about-odo-in-a-restricted-environment.html (and others, the entire section)

### What needs fixing?

I was going through the documentation on how to use odo in an offline environment and found multiple references to `odo init` image (in that way).

To me (and maybe to others) it makes it sound as though `odo init` is an actual command. Perhaps we can remove the whole `odo init` image and just say: "odo init image" ? 

ping @boczkowska

**Comment by cdrage** [comment]
![Screenshot from 2020-04-07 14-45-31](https://user-images.githubusercontent.com/6422176/78707967-5f4ad000-78df-11ea-998a-d1064f6bdb47.png)

**Comment by bergerhoffer** [comment]
Closing as PR #20991 addressed this.
