### ISSUE TITLE
[enterprise-4.3] Edit suggested in file networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-service-external-ip.adoc

### ISSUE THREAD

**Issue by jxadro** [openshift/openshift-docs#21027]
https://docs.openshift.com/container-platform/4.3/networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-service-external-ip.html

I think the content of this page is wrong

"4. Run the following command to see that the new service is created:
oc get svc -n openshift-ingress"

I think it has no sense to list the services in the namespaces openshift-ingress I think you should list the services in the new create projects.

Later the example "curl 172.30.131.89:3306" uses and IP that has no been described before from where it comes.

Thank you.

**Comment by jboxman** [comment]
@jxadro, I've rewritten the content for the page. If that doesn't help, please open an issue. Thanks!
