### ISSUE TITLE
Provide instructions to serve registry self-signed cert

### ISSUE THREAD

**Issue by aweiteka** [openshift/openshift-docs#2104]
When a registry is secured using a self-signed cert an admin should serve the cert from the static web server so users can download it.

cc @thomasmckay

**Comment by aweiteka** [comment]
@adellape I added this in the Atomic Registry install/config[1]. It's probably worth including in stand-alone registry deployment docs.

[1] registry_quickstart/administrators/system_configuration.adoc#serving-self-signed-certificate-for-docker-clients

**Comment by mburke5678** [comment]
@aweiteka We are going through older issues. Is this still needed in the current doc set (3.4 and later)?

https://docs.openshift.com/container-platform/3.6/install_config/registry/index.html

**Comment by aweiteka** [comment]
No, i'm not sure this is an important use case since the CA should be available from a separate trusted source.
