### ISSUE TITLE
[enterprise-4.3] Edit suggested in file installing/installing_vsphere/installing-vsphere.adoc

### ISSUE THREAD

**Issue by AndreaFerraresi** [openshift/openshift-docs#21072]
Hi I would have a list of prerequisites and a full list of vmware service account permission and a whole overview in form of a checklist of what needs to be done before the deployment happens that I have been sharing with customers, what is the best way to submit a pull request? 

Best, 
Andrea

**Comment by jboxman** [comment]
@AndreaFerraresi, that sounds fantastic! @kalexand-rh has done much of the work on the OCP installation documentation, and may have ideas on how best to proceed.
