### ISSUE TITLE
[enterprise-4.3] Edit suggested in file authentication/understanding-authentication.adoc

### ISSUE THREAD

**Issue by aelicieguo** [openshift/openshift-docs#21085]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.3/authentication/understanding-authentication.html#authentication-prometheus-system-metrics_understanding-authentication

### What needs fixing?
This is not available on prometheus

![image](https://user-images.githubusercontent.com/19474270/78967296-a5e53800-7b34-11ea-982a-216ab782b8b6.png)

**Comment by jboxman** [comment]
I can confirm I'm not seeing any of these either in CI build.

<img width="970" alt="Screen Shot 2020-04-21 at 4 32 03 PM" src="https://user-images.githubusercontent.com/354496/79911033-b11a4c80-83ed-11ea-8791-4fa935223d6a.png">

**Comment by jboxman** [comment]
@bergerhoffer @bobfuru 

Is this a topic either of you are familiar with?

**Comment by bobfuru** [comment]
> @bergerhoffer @bobfuru
> 
> Is this a topic either of you are familiar with?

I am not familiar with it.

**Comment by bergerhoffer** [comment]
> > @bergerhoffer @bobfuru
> > Is this a topic either of you are familiar with?

I'm not either.

> 
> I am not familiar with it.
> @maximsvistunov Are you familiar with this issue in Prometheus?

@rh-max - See @bobfuru's question above. 

@bobfuru - I made the mistake of picking the wrong GitHub ID for Max a few weeks ago myself. @rh-max is the right one.

**Comment by bergerhoffer** [comment]
@pneedle-rh Any chance this is something you know anything about?

**Comment by pneedle-rh** [comment]
> @pneedle-rh Any chance this is something you know anything about?

@bergerhoffer I have looked into this issue this morning.

In OCP 4.3 and later, three of the five system metrics documented in `modules/authentication-prometheus-system-metrics.adoc` are available the OCP web console and in the Prometheus UI. The available metrics are:

* `openshift_auth_form_password_count`
* `openshift_auth_form_password_count_result`
* `openshift_auth_password_total`

Here are screenshots from OCP 4.3.38 listing those metrics in both UIs:

* In the OCP web console in the *Administrator* perspective under *Monitoring* -> *Metrics*:

![ocp_4_3_38_metrics_query_openshift_auth](https://user-images.githubusercontent.com/62505557/95737325-68966a00-0c7f-11eb-9bf1-b95971e0bcb0.png)

* In the Prometheus UI:

![ocp_4_3_38_metrics_query_openshift_auth_prometheus_ui](https://user-images.githubusercontent.com/62505557/95737361-751ac280-0c7f-11eb-9273-44ea0c576be5.png)

The following two metrics are also included in that docs section, but they are not present in the OCP web console or the Prometheus UI:

* `openshift_auth_basic_password_count`
* `openshift_auth_basic_password_count_result`

This is true for OCP 4.3, 4.4, 4.5 and 4.6. I have updated this issue's labels accordingly.

###Next steps

I have taken ownership of this issue. Next steps are as follows:

1. I will verify whether the `openshift_auth_basic_password_count` and `openshift_auth_basic_password_count_result` metrics are intended to be in OCP 4.

2a. If they are, then I will file a Bugzilla requesting that they are added to the product.

2b. If they are not then we need to remove them from the docs and possibly add a change notice.

**Comment by pneedle-rh** [comment]
@ericavonb hi! I was just reading [BZ 1684407](https://bugzilla.redhat.com/show_bug.cgi?id=1684407), which relates to this docs issue to some degree.

Can you please advise as to whether the `openshift_auth_basic_password_count` and `openshift_auth_basic_password_count_result` metrics are intended to be in OCP 4? They are [referenced in our documentation](https://docs.openshift.com/container-platform/4.3/authentication/understanding-authentication.html#authentication-prometheus-system-metrics_understanding-authentication) but do not seem to be present in OCP 4.3, 4.4, 4.5 or 4.6.

Thanks!

**Comment by pneedle-rh** [comment]
Following on from a conversation with our Engineering team and my further testing, I have filed [this Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1892642) in relation to this issue. I will update this issue once progress has been made in the BZ.

**Comment by pneedle-rh** [comment]
From an investigation into this by our Monitoring team, I understand that these metrics likely only appear after a user login attempt because the metrics counter is not initialised at start up.

We are in the process of reviewing how to address this.

Paul.
