### ISSUE TITLE
Configuring Openstack in a containerized deployment

### ISSUE THREAD

**Issue by righteousjester** [openshift/openshift-docs#2110]
I was following this link, https://docs.openshift.org/latest/install_config/configuring_openstack.html, to configure Openstack. I kept running into an error whereby once I added the /etc/cloud.conf file the origin-master-api service and origin-node would complain that it cannot find the file: /etc/cloud.conf, and then fail to start.

To resolve the issue I need to put the file in /etc/origin/master and /etc/origin/node as the docker containers running those services could not access /etc/cloud.conf, the could only see their mounted volumes, namely /etc/origin/master and /etc/origin/node/

**Comment by mburke5678** [comment]
Fixed in docs.
