### ISSUE TITLE
scaleup docs incorrect. References a scaleup.yml file that doesn'T exist 

### ISSUE THREAD

**Issue by ivanthelad** [openshift/openshift-docs#2113]
https://docs.openshift.com/enterprise/3.2/install_config/install/advanced_install.html#adding-nodes-advanced

Docs state the file should be under 
https://github.com/openshift/openshift-ansible/tree/master/playbooks/byo/openshift-cluster
but file exists under 
https://github.com/openshift/openshift-ansible/blob/master/playbooks/byo/openshift-node/scaleup.yml

**Comment by adellape** [comment]
Fixed in https://github.com/openshift/openshift-docs/pull/2135
