### ISSUE TITLE
[enterprise-4.3] Edit required in file backup_and_restore/disaster_recovery/scenario-1-infra-recovery.adoc

### ISSUE THREAD

**Issue by cptmorgan-rh** [openshift/openshift-docs#21159]
### Which section(s) is the issue in?

5.a.i
5.b.i

### What needs fixing?

oc login should be performed using sudo to prevent issues when running export in 5.a.ii and 5.b.ii

The command in 5.a.ii and 5.b.ii utilizes sudo to be able to read the contents of the file /var/lib/kubelet/config.json.

This produces the follow error because the `oc login` command performed in 5.a.i and 5.a.ii is done by the core user. 

error:

[core@master3 ~]$ export SETUP_ETCD_ENVIRONMENT=$(sudo oc adm release info --image-for machine-config-operator --registry-config=/var/lib/kubelet/config.json)
error: info expects one argument, or a connection to an OpenShift 4.x server: invalid configuration: Missing or incomplete configuration info.  Please login or point to an existing, complete config file:

  1. Via the command-line flag --config
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

To view or setup config directly use the 'config' command.

Additionally, performing the command w/o sudo produces an error stating access is denied to /var/lib/kubelet/config.json.

**Comment by bergerhoffer** [comment]
These procedures have been updated to use sudo: https://docs.openshift.com/container-platform/4.3/backup_and_restore/disaster_recovery/scenario-1-infra-recovery.html

Closing this issue.
