### ISSUE TITLE
[enterprise-4.2] Edit suggested in file architecture/architecture.adoc

### ISSUE THREAD

**Issue by nphariharan** [openshift/openshift-docs#21250]
### Which section(s) is the issue in?
OpenShift Container Platform architecture - DEPLOYMENT AND SCALING BENEFITS

### What needs fixing?
Grammar error.
![Grammar Error - Screenshot](https://user-images.githubusercontent.com/6111144/79533701-24daf300-8096-11ea-9c7f-caecc7401ead.jpg)

without downtime  - In this sentence, the article 'the' is missing. It should be written as 'without the downtime'. Refer the attached screenshot.

**Comment by jboxman** [comment]
@nphariharan, thanks for reporting this; we've opted to keep the wording as is for now.
