### ISSUE TITLE
Be more clear about IPv6 support in OCP 4

### ISSUE THREAD

**Issue by saracferguson** [openshift/openshift-docs#21269]
### Which section(s) is the issue in?

Several sections of the OCP 4.3 documentation: 

In the final example in: 
    https://docs.openshift.com/container-platform/4.3/cnv/cnv_virtual_machines/cnv-accessing-vm-consoles.html#cnv-accessing-rdp-console_cnv-accessing-vm-consoles

In two different places here: 
    https://docs.openshift.com/container-platform/4.3/networking/multiple_networks/configuring-bridge.html

In one place in each of these sections, mentioning that "Both IPv4 and IPv6 addresses are supported." 
    https://docs.openshift.com/container-platform/4.3/networking/multiple_networks/configuring-ipvlan.html
    https://docs.openshift.com/container-platform/4.3/networking/multiple_networks/configuring-host-device.html
    https://docs.openshift.com/container-platform/4.3/networking/multiple_networks/configuring-macvlan.html

This page also makes it seem as if dual-stack is supported:
    https://docs.openshift.com/container-platform/4.3/networking/hardware_networks/configuring-sriov-net-attach.html

This section only mentions a couple of ipv6 sysctl parameters
    https://docs.openshift.com/container-platform/4.3/nodes/nodes/nodes-node-tuning-operator.html

Several mentions of IPv6 with some disclaimers that it is not fully supported on all platforms:
    https://docs.openshift.com/container-platform/4.3/rest_api/index.html

In the 4.2 docs it shows OVN being in tech preview with IPv6 and DHCPv6 capabilities, but then is not mentioned in the 4.3 docs:
        https://docs.openshift.com/container-platform/4.2/release_notes/ocp-4-2-release-notes.html#ocp-4-2-OVN

### What needs fixing?

There are mentions of being able to add/use an IPv6 address, but IPv6 is not fully supported on OCP 4. Some of these sections do state that IPv6 may not be fully supported, but other areas make it seem as if IPv6 works and is supported. Perhaps for those components only, but it is still not entirely clear to me. 

Requesting that we make a more clear statement on whether IPv6 is supported in OCP 4.3.

**Comment by jboxman** [comment]
@saracferguson, thanks for opening this issue. I've asked for confirmation about this.
