### ISSUE TITLE
[enterprise-4.3] Edit suggested in file networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-service-external-ip.adoc

### ISSUE THREAD

**Issue by rmkraus** [openshift/openshift-docs#21286]
### Which section(s) is the issue in?
The documentation seems incomplete. It only discusses how to create a service but then does discuss how to make that service available outisde the cluster.

### What needs fixing?
I think there is a section missing at the end of this documentation.

**Comment by jboxman** [comment]
@rmkraus, I've updated the content so that it is now correct: https://docs.openshift.com/container-platform/4.5/networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-service-external-ip.html

Thanks!
