### ISSUE TITLE
[okd] OCP references in installing-bare-metal page

### ISSUE THREAD

**Issue by gcecchi** [openshift/openshift-docs#21293]
### Which section(s) is the issue in?
installing-bare-metal

### What needs fixing?

In general the page resembles the OCP one and it is not adapted to OKD:

the sentence:
"Note that FCOS is based on Red Hat Enterprise Linux 8"
should have Fedora Core 31 (at least now..) and the link related to "Red Hat Enterprise Linux technology capabilities and limits" could not be appropriate in OKD perhaps

the paragraph related to "Internet and Telemetry access for OKD" that regards needed entitlements.
I think are needed only for OCP and not for OKD

Also below, in "Network Topology Requirements" section,  there is "OKD requires all nodes to have internet access to pull images for platform containers and provide telemetry data to Red Hat."

The part related to "Obtaining the installation program" needs modification because the pull of the secret and so on should be only an OCP thing...

**Comment by mburke5678** [comment]
@vrutkovs Can you help with this?

**Comment by vrutkovs** [comment]
This has been resolved by multiple PRs (see above). Please re-open if more tweaks are required
/close
