### ISSUE TITLE
PR #21337 introduced an invalid URL in the documentation.  

### ISSUE THREAD

**Issue by brianredbeard** [openshift/openshift-docs#21424]
In the attempt to parameterize example URLs in the Service Mesh documentation, PR #21337 instead broke the examples.

The change was attempting to parameterize MaistraVersion.  The challenge arises that parameter substitution inside of a code block [requires additional configuration][1].  

A discussion about this can be found here:  https://github.com/asciidoctor/asciidoctor/issues/1741#issuecomment-216256423

As of the present time #21405 should also not be merged until this issue is resolved.

My concern comes from the fact that there were multiple LGTM on the PR and yet in the [netlify preview][2] the issue is present:

![image](https://user-images.githubusercontent.com/57542/80045648-f9ed0680-84bc-11ea-810f-acd4df600921.png)

In the future, can the preview be checked before signing off?

### Which section(s) is the issue in?

https://github.com/openshift/openshift-docs/blob/29e642c7fa40e60f843bc506eec52760f11a6b8c/modules/ossm-tutorial-bookinfo-adding-destination-rules.adoc#L17
https://github.com/openshift/openshift-docs/blob/29e642c7fa40e60f843bc506eec52760f11a6b8c/modules/ossm-tutorial-bookinfo-adding-destination-rules.adoc#L23
https://github.com/openshift/openshift-docs/blob/29e642c7fa40e60f843bc506eec52760f11a6b8c/modules/ossm-tutorial-bookinfo-install.adoc#L81
https://github.com/openshift/openshift-docs/blob/29e642c7fa40e60f843bc506eec52760f11a6b8c/modules/ossm-tutorial-bookinfo-install.adoc#L87

### What needs fixing?
Annotate the source blocks in the files noted above to force processing of attributes, e.g.:

```
[subs="attributes"]
```

[1]: https://asciidoctor.org/docs/user-manual/#built-in-blocks-summary
[2]: https://maistrasamplepath--ocpdocs.netlify.app/openshift-enterprise/latest/service_mesh/service_mesh_day_two/ossm-example-bookinfo.html#ossm-tutorial-bookinfo-adding-destination-rules_ossm-bookinfo-tutorial

**Comment by brianredbeard** [comment]
cc @neal-timpe @JStickler

**Comment by neal-timpe** [comment]
Resolved in PR https://github.com/openshift/openshift-docs/pull/21479. Thanks for pointing it out.
