### ISSUE TITLE
[enterprise-4.3] Edit suggested in file backup_and_restore/backing-up-etcd.adoc

### ISSUE THREAD

**Issue by lbohnsac** [openshift/openshift-docs#21433]
### What needs fixing?
The described way is not correct for OCP4.3.0 - 4.3.8!
Add the correct procedure to back up etcd for the older (still used by customers) version!

**Comment by jboxman** [comment]
FYI @bergerhoffer

**Comment by bergerhoffer** [comment]
Hi @lbohnsac, can you give more specifics to what older procedure you're looking for? We made a few changes along the way, but as far as I'm aware, none specific to stopping at 4.3.8.

* In 4.2, you backed up etcd and it produced a single snapshot.db file.
* In 4.3.0, you backed up etcd and it produced a single tar.gz file containing both the snapshot.db file and static resources.
* In 4.3.2+, you back up etcd and it produces two files: the snapshot.db and the static resources tar.gz

The restore procedure is backward compatible to accept any of these. Our docs are aimed at the latest z-stream, so I can't change it back, but I can potentially add a note to assist customers on older z-streams. But again, this 4.3 change came with 4.3.2, not after 4.3.8.

**Comment by lbohnsac** [comment]
Hi @bergerhoffer, you already pointed it out ..
There were several changes but they aren't mentioned in the docu.
But the docu reads this in the Prerequisites:
A backup directory containing both the etcd snapshot and static Kubernetes API server resources taken from the same backup. The file names in the directory must be in the following formats: snapshot_<datetimestamp>.db and static_kuberesources_<datetimestamp>.tar.gz.

This will create confused customers! They start searching this two files ... and won't find it if they  are running older 4.3.x clusters.
So it'll be a good idea to mention your information above in the docs.

Btw the info about "not working before 4.3.9" i just heard ... i didn't check it (my bad)... i'll do that in the next days ... ;)

**Comment by bergerhoffer** [comment]
@lbohnsac Thanks for the clarification. I'll look into adding a note to the restore procedure that mentions the backward compatibility with the single file.

**Comment by bergerhoffer** [comment]
Closing this issue as #21690 has been merged. Updates are live: https://docs.openshift.com/container-platform/4.3/backup_and_restore/disaster_recovery/scenario-1-infra-recovery.html#dr-scenario-1-recover-master-hosts_dr-infrastructure-recovery

FYI @lbohnsac
