### ISSUE TITLE
[enterprise-4.3] Edit suggested in file nodes/pods/nodes-pods-secrets.adoc

### ISSUE THREAD

**Issue by buuhsmead** [openshift/openshift-docs#21430]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.3/nodes/pods/nodes-pods-secrets.html#nodes-pods-secrets-troubleshooting_nodes-pods-secrets

### What needs fixing?
In the example at the bottom of the page:
====
$ oc delete secret <secret_name>
$ oc annotate service <service_name> service.alpha.openshift.io/serving-cert-generation-error-1
$ oc annotate service <service_name> service.alpha.openshift.io/serving-cert-generation-error-num-1
====

Should be changed into:
====
$ oc delete secret <secret_name>
$ oc annotate service <service_name> service.alpha.openshift.io/serving-cert-generation-error-
$ oc annotate service <service_name> service.alpha.openshift.io/serving-cert-generation-error-num-
====

The character '1' is a asciidoc metadata notation but it is not used as a reference.

**Comment by jboxman** [comment]
@buuhsmead, fixed, thanks!
