### ISSUE TITLE
[enterprise-4.3] No info about latency requirements.

### ISSUE THREAD

**Issue by christianh814** [openshift/openshift-docs#21435]
### Which section(s) is the issue in?

I'm not sure, but I think it should go in the "installation" section. (all of them)

### What needs fixing?

There is no info about latency requirements between master~>master or master~>node. When designing an OpenShift rollout over multiple datacenters ("stretch clusters"), or even within the same datacenter; we need to know what the latency requirement is.

This should be in line with what's the minimum we'll support.

**Comment by therevoman** [comment]
This traditionally was found in the CoreOS etcd documentation, but with Operators and other components a more comprehensive value is needed when discussing cluster limitations.

**Comment by maxwelldb** [comment]
@ahardin-rh Might this be a scalability team project?

**Comment by vikram-redhat** [comment]
Related to: https://bugzilla.redhat.com/show_bug.cgi?id=1877064

**Comment by pfeifferj** [comment]
can this be closed since 4.3 is end of life?
