### ISSUE TITLE
[enterprise-4.3] Edit suggested in file scalability_and_performance/scaling-cluster-monitoring-operator.adoc

### ISSUE THREAD

**Issue by fgiloux** [openshift/openshift-docs#21465]
### Which section(s) is the issue in?
https://github.com/openshift/openshift-docs/blob/master/modules/prometheus-database-storage-requirements.adoc
Section: Lab environment

### What needs fixing?
"Currently, OpenStack environments are not supported for OpenShift Container Platform 4.3."
OCP 4.3 (and previous version too) is supported on OpenStack. This warning should be removed

**Comment by maxwelldb** [comment]
@fgiloux Thanks!
