### ISSUE TITLE
[enterprise-4.4] Add and explain example output

### ISSUE THREAD

**Issue by lbohnsac** [openshift/openshift-docs#21471]
### Which section(s) is the issue in?

CLI commands

### What needs fixing?
For every example the output is missing!
Add output and the explanation about the provided output!

**Comment by bergerhoffer** [comment]
We try to provide output for CLI commands when it is helpful. Closing as we are not going to do a sweep of every CLI command to add example output.

Please feel free to open a new issue if you have specific sections/commands that you think would benefit from adding example output.
