### ISSUE TITLE
[enterprise-4.3] Edit suggested in file logging/cluster-logging-manual-rollout.adoc

### ISSUE THREAD

**Issue by shortsteps** [openshift/openshift-docs#21602]
### Which section(s) is the issue in?
[Performing an Elasticsearch rolling cluster restart](https://docs.openshift.com/container-platform/4.3/logging/cluster-logging-manual-rollout.html#cluster-logging-manual-rollout-rolling_cluster-logging-rollout) - step 7

### What needs fixing?
The right command is 
`oc exec <any_es_pod_in_the_cluster> -c elasticsearch -- es_util --query=_cluster/settings -XPUT 'https://localhost:9200/_cluster/settings' -d '{ "transient": { "cluster.routing.allocation.enable" : "all" } }'` 
(and not ` { "cluster.routing.allocation.enable" : "none" }` as in step 4).

Thank you

**Comment by mburke5678** [comment]
I am working on improving this entire topic via #[22465](https://github.com/openshift/openshift-docs/pull/22465)
