### ISSUE TITLE
[enterprise-4.3] Edit suggested in file rest_api/index.adoc

### ISSUE THREAD

**Issue by dhellmann** [openshift/openshift-docs#21632]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.3/rest_api/index.html

### What needs fixing?

The page is unusably long. Rendering in the browser takes forever, and it is impossible to scroll, search, or do anything else with the page.

**Comment by jboxman** [comment]
@dhellmann, complete agree. A redesign is in the works for this.

**Comment by dhellmann** [comment]
@jboxman Nice :-) Thanks for the quick response!

**Comment by jboxman** [comment]
@dhellmann, this is still in flight, but I've made progress and expect to have something before the end of July at the latest.

**Comment by jboxman** [comment]
@dhellmann, the fix for this landed some time ago for 4.4 and 4.5:

https://docs.openshift.com/container-platform/4.5/rest_api/index.html
