### ISSUE TITLE
[enterprise-4.3] Edit suggested in file logging/cluster-logging-manual-rollout.adoc

### ISSUE THREAD

**Issue by ChetHosey** [openshift/openshift-docs#21689]
### Which section(s) is the issue in?

Reenabling shard balancing

### What needs fixing?

Reenabling shard balancing shows the same command as disabling shard balancing:

```
oc exec <any_es_pod_in_the_cluster> -c elasticsearch -- es_util --query=_cluster/settings -XPUT 'https://localhost:9200/_cluster/settings' -d '{ "transient": { "cluster.routing.allocation.enable" : "none" } }'
```

It should probably use `null` instead of `"none"`, to return to the default behavior:

```
oc exec <any_es_pod_in_the_cluster> -c elasticsearch -- es_util --query=_cluster/settings -XPUT 'https://localhost:9200/_cluster/settings' -d '{ "transient": { "cluster.routing.allocation.enable" : null } }'
```

**Comment by jboxman** [comment]
@mburke5678, FYI

**Comment by mburke5678** [comment]
I am working on improving this entire topic via https://github.com/openshift/openshift-docs/pull/22465

I was asked to update the command for disabling shard balancing to:
`$ oc exec <any_es_pod_in_the_cluster> -c elasticsearch -- es_util --query=_cluster/settings?pretty=true -XPUT 'https://localhost:9200/_cluster/settings' -d '{ "persistent": { "cluster.routing.allocation.enable" : "primaries" } }'`
