### ISSUE TITLE
[enterprise-4.3] Edit suggested in file cnv/cnv_virtual_machines/cnv_virtual_disks/cnv-preparing-cdi-scratch-space.adoc

### ISSUE THREAD

**Issue by aglitke** [openshift/openshift-docs#21699]
### Which section(s) is the issue in?
All sections

### What needs fixing?
In many instances the words "the CDI" are used.  When referring to CDI itself, 'the' should not precede 'CDI'.

**Comment by mburke5678** [comment]
@aglitke Thank you for pointing this out. Do you have a definitive source that I could use for reference? I looked at this page: https://kubevirt.io/2018/containerized-data-importer.html and https://github.com/kubevirt/containerized-data-importer#containerized-data-importer, which seem pretty authoritative to me.

I created a PR to make the change, if you want to look. A quick review of the docs using a text editor shows only 3 instances of `the CDI` remaining, two for `the CDI object` and one `the CDI controller`.

**Comment by mburke5678** [comment]
The PR is merged.
