### ISSUE TITLE
[enterprise-4.3] Edit suggested in file logging/cluster-logging-deploying-about.adoc

### ISSUE THREAD

**Issue by kanekoh** [openshift/openshift-docs#21715]
### Which section(s) is the issue in?
A link in Storage considerations for cluster logging and OpenShift Container Platform is not available.

Following `keep absolute storage consumption around 50% and below 70% at all times` linked https://signalfx.com/blog/how-we-monitor-and-run-elasticsearch-at-scale/ but, the URL is not available right now

```
Therefore, consider how much data you need in advance and that you are aggregating application log data. Some Elasticsearch users have found that it is necessary to keep absolute storage consumption around 50% and below 70% at all times. 
```

### What needs fixing?
Please re-link to the blog post again.

**Comment by jboxman** [comment]
This appears to be that post:

http://web.archive.org/web/20190901225900/https://signalfx.com/blog/how-we-monitor-and-run-elasticsearch-at-scale/

**Comment by kanekoh** [comment]
@jbornemann Thanks for the information. Looks like the article was no longer available on the original site.

**Comment by mburke5678** [comment]
https://github.com/openshift/openshift-docs/pull/24063
