### ISSUE TITLE
[enterprise-4.3] Edit suggested in file architecture/architecture-installation.adoc

### ISSUE THREAD

**Issue by pamoedom** [openshift/openshift-docs#21742]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.3/architecture/architecture-installation.html#available-platforms_architecture-installation

### What needs fixing?

"Red Hat Virtualization (RHV)" should be removed from the IPI list, it was included recently with version 4.4 but not available within 4.3

Thanks and regards.

**Comment by maxwelldb** [comment]
@rolfedh Would this and #21764 be of interest to you?

**Comment by maxwelldb** [comment]
Closing per #21800. Feel free to reopen if necessary.
