### ISSUE TITLE
Master Host Sizing Recommendations Does Not Add Up

### ISSUE THREAD

**Issue by itewk** [openshift/openshift-docs#2180]
**Page**
https://docs.openshift.com/enterprise/3.2/install_config/install/prerequisites.html#sizing-recommendations

**Issue**

> In a highly-available OpenShift Enterprise cluster with external etcd, a master host should have 1 CPU core and 2.5 GB of memory, on top of the defaults in the table above, for each 1000 pods. Therefore, the recommended size of master host in an OpenShift Enterprise cluster of 2000 pods would be 20 CPU cores and 50 GB of RAM, as well as the minimum requirements for a master host of 2 CPU cores and 8 GB of RAM.

The math here does not make sense.

If it is 1 CPU and 2.5 GB of memory per 1000 pods then the sentience should read:

> Therefore, the recommended size of master host in an OpenShift Enterprise cluster of 2000 pods would be 2 CPU cores and 5.0 GB of RAM....

Either that or the recommendations is for 10 vCPUs and 25 GB of RAM per 1000 pods.

**Request**:

1. Let me know what the correct recommendations is
2. Update the documentation accordingly

**Comment by bfallonf** [comment]
PR #2306 solves this issue.

Thanks, and sorry for the delay.

**Comment by itewk** [comment]
@bfallonf thank you

**Comment by brennv** [comment]
Additionally, 'as well as ' should be replaced with 'plus'  to make it more clear that the total of such a master is 4 CPU cores and 13 GB of RAM.

Resolved with #2804

**Comment by rhcarvalho** [comment]
@bfallonf is this issue to be considered closed?

**Comment by bfallonf** [comment]
@rhcarvalho Sure thing. Thanks for the heads up.
