### ISSUE TITLE
Web console extension examples link is broken

### ISSUE THREAD

**Issue by spadgett** [openshift/openshift-docs#2181]
The link to the examples is broken since we moved the web console code to the new origin-web-console repository.

@jwforres @sspeiche

**Comment by spadgett** [comment]
The correct link is now

https://github.com/openshift/origin-web-console/tree/master/extensions/examples

**Comment by spadgett** [comment]
@jwforres I think we should add a README will the new link at the old location in addition to fixing the link from the docs.

**Comment by mburke5678** [comment]
Fixed in the docs
https://github.com/openshift/openshift-docs/commit/96e7e886140910dde5985ca9cc99801a1ea84df3#diff-935cb90eb0ad3aa5bc7ff42db7ca1f8c
