### ISSUE TITLE
[enterprise-4.4] Edit suggested in file installing/installing_rhv/installing-rhv-creating-custom-vm.adoc

### ISSUE THREAD

**Issue by steled** [openshift/openshift-docs#21820]
### Which section(s) is the issue in?
Using an Ansible playbook to upload an RHCOS image to a data storage domain

### What needs fixing?
The name of the Ansible playbook at 5.

See below:

`1. Create an Ansible playbook file upload_rhcos_disk.yaml on the Red Hat Virtualization (RHV) Manager. For example:` _$ vi **upload_rhcos_disk.yaml**_

`5. On the Manager, run the Ansible playbook. For example: ` _$ ansible-playbook **rhcos_image.yaml** -vvv_

Could be confusing for someone.

**Comment by kalexand-rh** [comment]
I no longer see this file in the repository, so I'm closing this issue.
