### ISSUE TITLE
[enterprise-4.4] Edit suggested in file nodes/clusters/nodes-containers-events.adoc

### ISSUE THREAD

**Issue by pamoedom** [openshift/openshift-docs#21906]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.3/nodes/clusters/nodes-containers-events.html#nodes-containers-events-list_nodes-containers-events

### What needs fixing?
Just a small typo with word "ploicy" instead of "policy", located at "Table 18. LoadBalancer Service Events" -> "ExternalTrafficPolicy":

~~~
Lists the new ExternalTrafficPolicy. For example, <old-policy> → <new-ploicy>.
~~~

Best Regards.

**Comment by maxwelldb** [comment]
@pamoedom Thanks!
