### ISSUE TITLE
[enterprise-4.4] Edit suggested in file logging/cluster-logging-upgrading.adoc

### ISSUE THREAD

**Issue by lbohnsac** [openshift/openshift-docs#21957]
### Which section(s) is the issue in?
Update precedure is only described for webUI ... update procedure for cli is missing!

### What needs fixing?
Add the update procedure with cli!
you can't automate webUI clicks!

**Comment by mburke5678** [comment]
@rolfedh FYI

**Comment by rolfedh** [comment]
@mburke5678 I've created https://issues.redhat.com/browse/RHDEVDOCS-2754
