### ISSUE TITLE
[enterprise-4.3] Edit suggested in file logging/cluster-logging-upgrading.adoc

### ISSUE THREAD

**Issue by lbohnsac** [openshift/openshift-docs#21956]
### Which section(s) is the issue in?
Update precedure is only described for webUI ... update procedure for cli is missing!

### What needs fixing?
Add the update procedure with cli!
you can't automate webUI clicks!

**Comment by mburke5678** [comment]
Closing as a duplicate of https://github.com/openshift/openshift-docs/issues/21957. Both procedures should be the same (or similar enough) to CP and tweak should we want to add this information,
