### ISSUE TITLE
improvement suggestion for documentation. Having all yaml files available somewhere  to include them in an automation process.

### ISSUE THREAD

**Issue by dwojciec** [openshift/openshift-docs#22014]
### Which section(s) is the issue in?
All files (yaml) mentionned into the documentation 

### What needs fixing?
Why not to have a copy of each yaml file present in the documentation somewhere on github (maybe openshift-docs/yaml-file/ to facilitate the life of users and to allow to integrate them quickly if we want to automate some tasks.
Just 1 example : in the logging part (https://docs.openshift.com/container-platform/4.4/logging/cluster-logging-deploying.html#cluster-logging-deploy-eo-cli_cluster-logging-deploying) 
it will be very useful for user to be able to download the file mentioned (eo-sub.yaml) from a github raw link. Copy/paste is nice but to be able to execute a 
```
oc create -f https://raw.githubusercontent.com/openshift/openshift-docs/master/logging/eo-sub.yaml
```
is better. it will avoid syntax error and we can include script directly inside automation process.
It's a smooth way to consume our yaml files.

**Comment by jboxman** [comment]
@mburke5678 I think we do this for install topics now? So this is now technically possible.
