### ISSUE TITLE
[online] Edit suggested in file networking/accessing-hosts.adoc

### ISSUE THREAD

**Issue by dudash** [openshift/openshift-docs#22095]
### Which section(s) is the issue in?
Accessing Hosts (ARO)
https://docs.openshift.com/aro/4/networking/accessing-hosts.html

### What needs fixing?
References to EC2 need to be replaced with instructions for ARO hosts (if possible).

**Comment by lamek** [comment]
Thanks for spotting this. I created a PR to pull the current aws topic down and added a note to track the work of creating a new ARO specific topic.
https://github.com/openshift/openshift-docs/pull/23312
