### ISSUE TITLE
scheduler config: json vs yaml

### ISSUE THREAD

**Issue by tnguyen-rh** [openshift/openshift-docs#2211]
By default the configuration file for the scheduler is in [JSON format](https://github.com/openshift/openshift-docs/pull/2157).  We provide several sample configuration files, all in YAML.  (They used to be in JSON, but for consistency w/ the rest of the doc set, [were converted to YAML](https://github.com/openshift/openshift-docs/commit/24f5bffa73d7dda6013162226f3722c6aaa08c2e).)

So, here we have two levels of consistency [in opposition](https://github.com/openshift/openshift-docs/pull/2157#issuecomment-222824966).  What to do?

**Comment by adellape** [comment]
@abhgupta Does `/etc/origin/master/scheduler.json` still need to be in JSON (i.e., not YAML)? On a OSE 3.2 machine, it still shows JSON by default, so I presumed that we should still be showing JSON for docs on scheduler policy files.

cc @bfallonf

**Comment by abhgupta** [comment]
@adellape As of now it seems to be just handling JSON as the JSON specific encoder/decoder are specified. However, there is no reason it could not be made generic to handle both formats.

**Comment by mburke5678** [comment]
@abhgupta Is this still an issue in the current docs (3.4 and forward)?

**Comment by vikram-redhat** [comment]
@mburke5678 it is not. I am closing this issue.
