### ISSUE TITLE
[enterprise-4.4] Edit suggested in file release_notes/ocp-4-4-release-notes.adoc

### ISSUE THREAD

**Issue by therevoman** [openshift/openshift-docs#22133]
### Which section(s) is the issue in?
API changes

### What needs fixing?
the Kubernetes Deployment object has been upgraded from `extensions/v1beta1` to `apps/v1`.  This should be boldly highlighted as there are some considerations that need to be made along with this

**Comment by jboxman** [comment]
@therevoman, can you elaborate on what those considerations are?

It is mentioned in the [release notes](https://docs.openshift.com/container-platform/4.3/release_notes/ocp-4-3-release-notes.html#ocp-4-3-beta-workload-alerts-deprecated).
