### ISSUE TITLE
[enterprise-4.4] Edit suggested in file storage/persistent_storage/persistent-storage-vsphere.adoc

### ISSUE THREAD

**Issue by maxwelldb** [openshift/openshift-docs#22178]
FYI, @bobfuru -- not sure if you have anything cooking that would fix this, anyhow, but git blame says you own this.

### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.4/storage/persistent_storage/persistent-storage-vsphere.html#vsphere-static-provisioning_persistent-storage-efs

Step 4

### What needs fixing?
The example has callouts 1,3, and 4, but not 2.

**Comment by bobfuru** [comment]
Thank you, @maxwelldb! Good catch. I fixed this in https://github.com/openshift/openshift-docs/pull/22187. Closing this issue.
