### ISSUE TITLE
[enterprise-4.4] Edit suggested in file logging/cluster-logging-deploying.adoc

### ISSUE THREAD

**Issue by iamparamvs** [openshift/openshift-docs#22216]
### Which section(s) is the issue in?
In the section 4: "**Install the Cluster Logging Operator by creating the following objects**"

### What needs fixing?

Section 4-a should be about creating the Cluster-logging namespace. First the Cluster logging namespace must be created then the Operator group shall be created.

Create a file for creating a cluster-logging namespace(e.g. clo-namespace.yaml)

> apiVersion: v1
kind: Namespace
metadata:
  name: openshift-logging
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-logging: "true"

$ oc create -f clo-namespace.yaml

**Comment by jboxman** [comment]
fyi @mburke5678

**Comment by mburke5678** [comment]
@iamparamvs CAn I ask you to take another look at https://docs.openshift.com/container-platform/4.4/logging/cluster-logging-deploying.html#cluster-logging-deploy-cli_cluster-logging-deploying? 

I had several odd issues with these files when merging them last week and had to do some fixes on Monday 5/18. 
The step to create the ClusterLogging namespace is Step 2. I don't think this step was missing. 

Would it make more sense to include the name space creation as a sub-step?

1 Install the Elasticsearch Operator by creating the following objects:
 a. Create the namespace
 b. Create the operator group
 c. Create the subscription

And the same for the Cluster Logging Operator?

**Comment by iamparamvs** [comment]
Hi @mburke5678 

I think you have inserted the "clo-namespace" beneath the "eo-namespace" which is not in the correct sequence. 

I will write the correct order in which the files are to be created.

**1. Create a Namespace for the Elasticsearch Operator**
a. Create a Namespace object YAML file (for example, eo-namespace.yaml) for the Elasticsearch Operator
b. Create the Namespace

**2. Install the Elasticsearch Operator by creating the following objects**
a. Create an Operator Group object YAML file (for example, eo-og.yaml) for the Elasticsearch operator
b. Create an Operator Group object
c. Create a Subscription object YAML file (for example, eo-sub.yaml) to subscribe a Namespace to the Elasticsearch Operator
d. Create the Subscription object
e. Verify the Operator installation

**3. Create a Namespace for the Cluster Logging Operator**
a. Create a Namespace object YAML file (for example, clo-namespace.yaml) for the Cluster Logging Operator
b. Create the Namespace

**4. Install the Cluster Logging Operator by creating the following objects**
a. Create an OperatorGroup object YAML file (for example, clo-og.yaml) for the Cluster Logging Operator
b. Create the OperatorGroup object
c. Create a Subscription object YAML file (for example, clo-sub.yaml) to subscribe a Namespace to the Cluster Logging Operator
d. Create the Subscription object
e. Verify the Operator installation

**Points 5 and 6 are in the correct order.**

I hope this helps. Cheers!

**Comment by mburke5678** [comment]
@iamparamvs As I understand and practice, you can create the two namespaces first, then the operator group and subscription for each operator after. I can change the order to match what you have, if the team thinks that is better. 

FYI:
I have a script I use to install cluster logging and it seems to work. The major steps are:

oc create -f eo-namespace.yaml

oc create -f clo-namespace.yaml

oc create -f eo-og.yaml

oc create -f eo-sub.yaml

oc project openshift-operators-redhat

oc create -f eo-rbac.yaml

oc create -f clo-og.yaml

oc create -f clo-sub.yaml

oc get csv --all-namespaces

oc create -f cl-instance.yaml

oc project openshift-logging

I think I can remove `oc create -f eo-rbac.yaml`, but haven't tried it yet.

 (In fact, I don't *think* it matters which order you need to use with the operator groups and subscriptions. I know, before I created the script, I have done installs where I missed a step and went back after and the install seemed fine)

**Comment by iamparamvs** [comment]
Hi @mburke5678 

Yes, I agree that the two namespaces can be created at first as well but what I suggested refers to the order in which it was documented for the earlier version.

Also, you have not used the RBAC file in the documentation for this version. Are you sure that it is not required for v4.4?

Thanks!

**Comment by mburke5678** [comment]
@iamparamvs I am told be QE that the RBAC is no longer needed as the OLM will create all the RBAC for Logging for both the console and CLI installs. 

The earlier version of the install, that you mention, was in error, I think. I recall having significant problems when merging those docs and I might have made the error with the operator group and namespace when fixing a merge issue. Thank you for pointing out the problem. I think we have it right now!

**Comment by iamparamvs** [comment]
@mburke5678 thank you for sharing the information. 

I think you have it right now.
