### ISSUE TITLE
[enterprise-4.4] Edit suggested in file logging/cluster-logging-deploying.adoc

### ISSUE THREAD

**Issue by iamparamvs** [openshift/openshift-docs#22217]
### Which section(s) is the issue in?
In the section 4-e **Verify the Operator installation**

### What needs fixing?

The command "**oc get csv --openshift-logging**" does not run properly

> [root@host-xxx.xxx.xx.x Cluster-Logging]# oc get csv --openshift-logging
> Error: unknown flag: --openshift-logging
> See 'oc get --help' for usage.

**Comment by jboxman** [comment]
fyi @mburke5678

**Comment by mburke5678** [comment]
@iamparamvs Thanks for pointing this out! Got the command from a QE resource in a Slack conversation. I should have caught this myself at the time. 
 
Fixed in https://github.com/openshift/openshift-docs/pull/22243
