### ISSUE TITLE
[enterprise-3.11] Edit suggested in file install_config/cluster_metrics.adoc

### ISSUE THREAD

**Issue by KyWa** [openshift/openshift-docs#22248]
### Which section(s) is the issue in?
The core of the deployment of metrics on OCP 3.11 is incorrect, thus the whole document.

### What needs fixing?
The official docs state that Heapster and Hawkular are the metrics platform (which was the case in previous version of OCP 3), however, in 3.11 this is no longer the case and the docs are misleading, not allowing HPA to work on clusters. This information was found in a support doc: https://access.redhat.com/solutions/3766511

**Comment by jboxman** [comment]
@KyWa, there is a note on the [page](https://docs.openshift.com/container-platform/3.11/install_config/cluster_metrics.html) regarding HPA:

> Previous versions of OpenShift Container Platform used metrics from Heapster to configure horizontal pod autoscalers. Now horizontal pod autoscalers use metrics from the OpenShift Container Platform metrics server. See Requirements for Using Horizontal Pod Autoscalers for detailed information.

**Comment by KyWa** [comment]
This is correct, but there is some misleading information in the HPA document. In the requirements for HPA it states to install 'metrics-server' which is accurate, but it mentions a way to test if it was correctly installed is to issue an `oc adm top pods/nodes` and if metrics return then its installed. For customers who have upgraded from previous versions it will be misleading.

I suppose the actual issue is in the autoscaling document:

https://docs.openshift.com/container-platform/3.11/dev_guide/pod_autoscaling.html#req-for-using-hpas.
