### ISSUE TITLE
[enterprise-4.4] Edit suggested in file authentication/certificate-types-descriptions.adoc

### ISSUE THREAD

**Issue by kanekoh** [openshift/openshift-docs#22253]
### Which section(s) is the issue in?

The section of Expiration at etcd certificates. 

### What needs fixing?

The product documentation states that the validity period of certificates for etcd client, peer and server are 3 years, however the source code seems to set a different value (10 years).
 
The certificate period for the cluster I deployed was also 10 years. With is the correct explanation for the validity period of certificates?

https://github.com/openshift/cluster-etcd-operator/blob/release-4.4/pkg/operator/etcdcertsigner/etcdcertsignercontroller.go#L42

**Comment by jboxman** [comment]
@ahardin-rh fyi

**Comment by ahardin-rh** [comment]
@hexfusion Can you please advise?

**Comment by hexfusion** [comment]
This is a bug https://bugzilla.redhat.com/show_bug.cgi?id=1837594 fix for 4.5 will be up shortly.

**Comment by ahardin-rh** [comment]
@hexfusion Thank you for confirming! 
@kanekoh I am going to close this docs issue, but please let me know if you need anything else from the docs team.

**Comment by retroflexer** [comment]
Thanks @kanekoh for identifying the bug. It will be fixed in 4.5 and backported to 4.4.
