### ISSUE TITLE
[enterprise-4.4] Edit suggested in file applications/pruning-objects.adoc

### ISSUE THREAD

**Issue by vanallp** [openshift/openshift-docs#22258]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.4/applications/pruning-objects.html#pruning-images_pruning-objects

in the section Automatically pruning images

### What needs fixing?
schedule: "*/0 * * * *"          is wrong.   generates error:

2020-05-19 07:58:19.525	cluster-image-registry-operator (cluster-image-registry-operator-57779d8f8b-cwhxx)	stderr	E0519 11:58:19.525753      
13 controllerimagepruner.go:260] (imaeg pruner) unable to sync: unable to apply objects: failed to update object *v1beta1.CronJob, 
Namespace=openshift-image-registry, Name=image-pruner: CronJob.batch "image-pruner" is invalid: spec.schedule: Invalid value: "*/0 * * * *": 
Step of range should be a positive number: */0, requeuing

change to:
schedule: "0 0 * * *"         

to tun every day at midnight

thanks.
-paul

**Comment by jboxman** [comment]
@vanallp, this is now fixed, thanks!
