### ISSUE TITLE
[enterprise-3.11] Edit suggested in file dev_guide/pod_autoscaling.adoc

### ISSUE THREAD

**Issue by KyWa** [openshift/openshift-docs#22259]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/3.11/dev_guide/pod_autoscaling.html#req-for-using-hpas

Requirements for Using Horizontal Pod Autoscalers

### What needs fixing?

The Requirements section assumes a fresh install. For customers who have upgraded from previous versions of OCP will not have metrics-server, but will be able to run `oc adm top pods/nodes` and get a successful return despite `metrics-server` not being installed. There should be a note informing customers coming from previous versions to also check if the `openshift-metrics-server` namespace exists (created from the metrics-server playbooks).

**Comment by mburke5678** [comment]
@joelsmith Can you comment on this issue?

**Comment by KyWa** [comment]
This issue didn't get updated, but I did see that the doc itself did which is good. Closing the issue.
