### ISSUE TITLE
[enterprise-4.3] Edit suggested in file logging/cluster-logging-deploying.adoc

### ISSUE THREAD

**Issue by jboyd01** [openshift/openshift-docs#22267]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.3/logging/cluster-logging-deploying.html#cluster-logging-deploy-clo_cluster-logging-deploying
under "Install the Cluster Logging Operator using the web console"
note 5 for 4.e presently states:
"Specify that each Elasticsearch node in the cluster is bound to a Persistent Volume Claim." 

Same issue for https://docs.openshift.com/container-platform/4.3/logging/cluster-logging-deploying.html#cluster-logging-deploy-clo-cli_cluster-logging-deploying
### What needs fixing?

That is not helpful nor is it accurate.  This parameter is specifying the storageClass name that will be used to create the PV.  The example specified here in this documentation is "gp2" which is **specific to AWS**.  IE if you are running in IBM Cloud or GKS or another provider, chances are you **must** specify a different storageClass.  It should also be noted that block storage should be used per your documented performance best practices.

**Comment by jboxman** [comment]
fyi @mburke5678

**Comment by mburke5678** [comment]
@jboyd01 Does this address your concerns?

> Enter the name of an existing storageClass for Elasticsearch storage. The storageClass should be a block storage provider. 

Changes via https://github.com/openshift/openshift-docs/pull/22341

**Comment by jboyd01** [comment]
Looks better, thanks @mburke5678!  Not certain if  "The storageClass should be a block storage **provider**" is quite accurate (ie the provider bit).  Perhaps "The storageClass should allocate block storage for best performance".  Thanks for addressing this.

**Comment by mburke5678** [comment]
Closing in favor of https://github.com/openshift/openshift-docs/pull/22341
