### ISSUE TITLE
[enterprise-4.4] Edit suggested in file networking/ingress-operator.adoc

### ISSUE THREAD

**Issue by pamoedom** [openshift/openshift-docs#22270]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.4/networking/ingress-operator.html#nw-ingress-setting-a-custom-default-certificate_configuring-ingress

### What needs fixing?

It would be highly recommended to put a note within this section linking against "Custom PKI" section (https://docs.openshift.com/container-platform/4.4/networking/configuring-a-custom-pki.html) if needed. Usually the Ingress router is changed with Custom/Corporate CAs, which need to be also trusted cluster-wide using the "trustedCA" spec from the proxy object.

Best Regards.

**Comment by sheriff-rh** [comment]
Pedro and I discussed this issue on Red Hat IRC. I describe how our docs are built and published, and that we cannot cross reference other sections of documentation within modules, or subsections. The Setting A Custom Default Certificate section mentions what to do if Custom PKIs are in use, and the end of the page has an Additional Resources section with the link to the Custom PKI page. We have agreed that this is sufficient at this time, and agreed to close this issue. 

Thanks Pedro!
