### ISSUE TITLE
[enterprise-4.4] Edit suggested in file networking/hardware_networks/configuring-sriov-net-attach.adoc

### ISSUE THREAD

**Issue by boris-deschenes** [openshift/openshift-docs#22344]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.4/networking/hardware_networks/configuring-sriov-net-attach.html#configuring-sr-iov-networks_about-sriov

### What needs fixing?
the doc says the IPAM section is optional but it does not seem to be the case, omitting the ipam definition gives the following error from the srio operator and the network attach definition is not created...

(adding a small 192.168.0.0/24 ipam definition fixes the issue and the NAD appears)

2020-05-21T12:44:08.991832382+00:00 stderr F {"level":"error","ts":1590065048.9917593,"logger":"controller_sriovnetwork","msg":"Couldn't create NetworkAttachmentDefinition","Request.Namespace":"openshift-sriov-network-operator","Request.N
ame":"el8000-sriov-network","Namespace":"openshift-sriov-network-operator","Name":"el8000-sriov-network","error":"admission webhook \"multus-validating-config.k8s.io\" denied the request: configuration string is not in JSON format","stack
trace":"github.com/openshift/sriov-network-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/openshift/sriov-network-operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/openshift/sriov-network-op
erator/pkg/controller/sriovnetwork.(*ReconcileSriovNetwork).Reconcile\n\t/go/src/github.com/openshift/sriov-network-operator/pkg/controller/sriovnetwork/sriovnetwork_controller.go:142\ngithub.com/openshift/sriov-network-operator/vendor/si
gs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/openshift/sriov-network-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215\ngithub.com/open
shift/sriov-network-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/openshift/sriov-network-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/openshift/sriov-network-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/openshift/sriov-network-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/
openshift/sriov-network-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/openshift/sriov-network-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/openshift/sriov-network-operator
/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/openshift/sriov-network-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}

**Comment by jboxman** [comment]
The optionality was removed in _4.5_: https://docs.openshift.com/container-platform/4.5/networking/hardware_networks/configuring-sriov-net-attach.html

I'll look at _4.4_.

**Comment by jboxman** [comment]
This appears related to this BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1843374

**Comment by jboxman** [comment]
Fix available: https://github.com/openshift/openshift-docs/pull/26737
