### ISSUE TITLE
[enterprise-4.4] Edit suggested in file installing/installing_vsphere/installing-vsphere.adoc

### ISSUE THREAD

**Issue by janehojy** [openshift/openshift-docs#22342]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.4/installing/installing_vsphere/installing-vsphere.html#installation-infrastructure-user-infra_installing-vsphere

### What needs fixing?

```
ETHERNET ADAPTOR HARDWARE ADDRESS REQUIREMENTS
When provisioning VMs for the cluster, the ethernet interfaces configured for each VM must use a MAC address from the VMware Organizationally Unique Identifier (OUI) allocation ranges:

00:05:69:00:00:00 to 00:05:69:FF:FF:FF

00:0c:29:00:00:00 to 00:0c:29:FF:FF:FF

00:1c:14:00:00:00 to 00:1c:14:FF:FF:FF

00:50:56:00:00:00 to 00:50:56:FF:FF:FF

If a MAC address outside the VMware OUI is used, the cluster installation will not succeed.
```

This section on MAC address requirements need to be added to the other vsphere installations too. 
- [installing a cluster on vSphere with network customizations](https://docs.openshift.com/container-platform/4.4/installing/installing_vsphere/installing-vsphere-network-customizations.html)
- [restricted network vSphere installation](https://docs.openshift.com/container-platform/4.4/installing/installing_vsphere/installing-restricted-networks-vsphere.html)

**Comment by jboxman** [comment]
@janehojy thanks for opening this!
