### ISSUE TITLE
3.2 console customization docs point to examples link that doesn't exist

### ISSUE THREAD

**Issue by jwforres** [openshift/openshift-docs#2236]
From this page https://docs.openshift.com/enterprise/3.2/install_config/web_console_customization.html#loading-custom-scripts-and-stylesheets

We link to origin for some example customizations.  That link is no longer valid since those files have been moved into origin-web-console repo for 3.3+ and the examples in the new repo don't work with 3.2

The 3.2 docs should point to https://github.com/openshift/origin/tree/v1.2.0/assets/extensions/examples

Origin and enterprise 3.3+ can point to https://github.com/openshift/origin-web-console/tree/master/extensions/examples

**Comment by jwforres** [comment]
@adellape @benjaminapetersen I know you guys were looking into doc issues around the extension examples, not sure if you were already working on fixing this

**Comment by adellape** [comment]
@jwforres Yeah, PR is here https://github.com/openshift/openshift-docs/pull/2220

Didn't know about the 3.2 vs 3.3 discrepancy tho, I'll update it.

**Comment by bfallonf** [comment]
@adellape So can we close this issue in favour of your PR above?

**Comment by mburke5678** [comment]
close this issue in favour of your PR above
