### ISSUE TITLE
[enterprise-4.4] Edit suggested in file applications/pruning-objects.adoc

### ISSUE THREAD

**Issue by TinyExplosions** [openshift/openshift-docs#22399]
### Which section(s) is the issue in?
Automatically Pruning Images - https://docs.openshift.com/container-platform/4.4/applications/pruning-objects.html#pruning-images_pruning-objects

### What needs fixing?
Copying the sample code produces an error "Incorrect type" for the `keepYoungerThan` object. Needs to be an integer.
Should be
`keepYoungerThan: '60'`
instead of
`keepYoungerThan: 60m`

**Comment by lbohnsac** [comment]
Take care ... if you just define the integer 60 the unit is ns (nanoseconds)!
