### ISSUE TITLE
[enterprise-4.4] Edit suggested in file applications/pruning-objects.adoc

### ISSUE THREAD

**Issue by TinyExplosions** [openshift/openshift-docs#22398]
### Which section(s) is the issue in?
Automatically Pruning Images - https://docs.openshift.com/container-platform/4.4/applications/pruning-objects.html#pruning-images_pruning-objects

### What needs fixing?
Copying the sample code produces an error "Incorrect type. Expected an array" for the `tolerations` object. Should be
` tolerations: []`
instead of
` tolerations: {}`

**Comment by jboxman** [comment]
@TinyExplosions, thanks for reporting this. It is now resolved.
