### ISSUE TITLE
[online] Edit suggested in file storage/understanding-persistent-storage.adoc

### ISSUE THREAD

**Issue by tonyiams** [openshift/openshift-docs#22414]
### Which section(s) is the issue in?

Azure Red Hat OpenShift Documentation - Understanding persistent storage

### What needs fixing?

Azure Red Hat OpenShift supports the following PersistentVolume plug-ins:
AWS Elastic Block Store (EBS)

This does not seem correct....Azure Red Hat OpenShift should support an Azure storage service, not an AWS storage service

**Comment by jboxman** [comment]
@lamek fyi
