### ISSUE TITLE
[enterprise-4.4] Edit suggested in file openshift_images/create-images.adoc

### ISSUE THREAD

**Issue by mattreid** [openshift/openshift-docs#22435]
### Which section(s) is the issue in?
Defining image metadata

### What needs fixing?
This label contains a list of tags represented as **[a]** list of comma-separated string values. The tags are the way to categorize the container images into broad areas of functionality. Tags help UI and generation tools to suggest relevant container images during the application creation process.

There's a missing a in this description.

**Comment by jboxman** [comment]
@mattreid, thanks for reporting this!
