### ISSUE TITLE
[enterprise-4.4] Edit suggested in file builds/running-entitled-builds.adoc

### ISSUE THREAD

**Issue by ChetHosey** [openshift/openshift-docs#22441]
### Which section(s) is the issue in?

Squash layers with docker builds

### What needs fixing?

This content probably isn't specific to running entitled builds. It might be a better fit at https://docs.openshift.com/container-platform/4.4/builds/build-strategies.html#builds-strategy-docker-build_build-strategies, for example.

**Comment by rolfedh** [comment]
I've transferred this image to https://issues.redhat.com/browse/RHDEVDOCS-2778.

**Comment by rolfedh** [comment]
@ChetHosey Thanks for reporting this issue. I've created a pull request to move the content as suggested.
