### ISSUE TITLE
[enterprise-4.5] Understanding the OperatorHub

### ISSUE THREAD

**Issue by jianzhangbjz** [openshift/openshift-docs#22479]
### Which section(s) is the issue in?
There are 2 problems here:

1.  There is a new `OperatorSource` called `redhat-marketplace`, I guess we should describe it in 
[understanding-operatorhub](https://docs.openshift.com/container-platform/4.5/operators/olm-understanding-operatorhub.html#olm-operatorhub-overview_olm-understanding-operatorhub). @robszumski What do you think?

2.  > While OperatorHub no longer uses CatalogSourceConfig resources, they are still supported in OpenShift Container Platform.

      The `CatalogSourceConfig` has been removed for 4.5, which means it won't be supported.
https://docs.openshift.com/container-platform/4.5/operators/olm-understanding-operatorhub.html#olm-operatorhub-arch_olm-understanding-operatorhub

**Comment by robszumski** [comment]
> There is a new OperatorSource called redhat-marketplace, I guess we should describe it in
understanding-operatorhub. @robszumski What do you think?

Yes, we should include a quick blurb about this source
