### ISSUE TITLE
OLM Exposed metrics

### ISSUE THREAD

**Issue by jianzhangbjz** [openshift/openshift-docs#22480]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.5/operators/understanding_olm/olm-understanding-olm.html#olm-metrics_olm-understanding-olm

### What needs fixing?

1. The `csv_upgrade_count` means the `Monotonic count of CSV upgrades`, not the `Monotonic count of CatalogSources`.

2. Should add the `catalog_source_count`, which means the `Number of catalog sources`.

3. Should add the `subscription_sync_total`, which means the `Monotonic count of subscription syncs`.

4. Should add the `csv_succeeded`, which means the `Successful CSV install`.

5. Should add the `csv_abnormal`, which means the `CSV is not installed`.

**Comment by adellape** [comment]
Corrected `csv_upgrade_count` typo and caught the downstream branches up with `master`, which already had the other parameters (missed a cherry-pick when it was originally added).

Fixed for 4.5 and 4.6 via https://github.com/openshift/openshift-docs/pull/24261 (new file location).

Fixed for 4.3 and 4.4 in the old location via https://github.com/openshift/openshift-docs/pull/24264 and https://github.com/openshift/openshift-docs/pull/24265.
