### ISSUE TITLE
[enterprise-4.3] Edit suggested in file scalability_and_performance/using-cluster-loader.adoc

### ISSUE THREAD

**Issue by rahmed-rh** [openshift/openshift-docs#22482]
### Which section(s) is the issue in?
Installing Cluster Loader

### What needs fixing?
To pull the container image, run:
$ sudo podman pull quay.io/openshift/origin-tests:4.3

**Comment by bergerhoffer** [comment]
@rahmed-rh Can you be more specific about what the issue is? The command you have there is what I see in the docs.

**Comment by rahmed-rh** [comment]
Yes it was fixed
