### ISSUE TITLE
[enterprise-4.4] Edit suggested in file service_mesh/service_mesh_install/installing-ossm.adoc

### ISSUE THREAD

**Issue by hashnao** [openshift/openshift-docs#22519]
### Which section(s) is the issue in?
Installing the Elasticsearch Operator

### What needs fixing?
The Elasticsearch Operator is to be installed in the **openshift-operators-redhat** namespace but not the openshift-operators namespace by default and I think it should be installed in the **openshift-operators-redhat** namespace according to the Elasticsearch Operator installation guide [1]. In addition, the **openshift-operators-redhat** namespace is selected by default when choosing All namespaces on the cluster (default) in the installation mode as follows.
<img width="892" alt="elasticsearch_operator_subscription" src="https://user-images.githubusercontent.com/1663165/83368538-181b2000-a3f4-11ea-8d97-baa268119576.png">
The Elasticsearch Operator installation says, _You must specify the openshift-operators-redhat Namespace. To prevent possible conflicts with metrics, you should configure the Prometheus Cluster Monitoring stack to scrape metrics from the openshift-operators-redhat Namespace and not the openshift-operators Namespace. The openshift-operators Namespace might contain Community Operators, which are untrusted and could publish a metric with the same name as an OpenShift Container Platform metric, which would cause conflicts._ Nevertheless, the No. 6 procedure says, _On the Create Operator Subscription page, select All namespaces on the cluster (default). This installs the Operator in the default openshift-operators project and makes the Operator available to all projects in the cluster._

[1] https://docs.openshift.com/container-platform/4.4/logging/cluster-logging-deploying.html#cluster-logging-deploy-console_cluster-logging-deploying

**Comment by mburke5678** [comment]
@neal-timpe Is this something you can look into? I know for Cluster Logging the Elasticsearch Operator must be installed into `openshift-operators-redhat`.

**Comment by neal-timpe** [comment]
@mburke5678 Yep, I'll create a Jira and put it into our queue. Thanks!

**Comment by pavolloffay** [comment]
@jcantrill @ewolinetz could you please have a look and provide feedback?

**Comment by jkandasa** [comment]
I tested this change on OCP 4.4 cluster with Jaeger 1.17.3.
Works as expected.
```
$ oc get pods -n openshift-operators-redhat
NAME                                      READY   STATUS    RESTARTS   AGE
elasticsearch-operator-7b778b9d97-cllgr   1/1     Running   0          16m

$ oc get pods -n jkandasa
NAME                                                    READY   STATUS    RESTARTS   AGE
elasticsearch-cdm-jkandasajaegerqe-1-7945f5467f-jhcxt   2/2     Running   0          4m44s
elasticsearch-cdm-jkandasajaegerqe-2-6848fb4f96-v2njk   2/2     Running   0          4m41s
elasticsearch-cdm-jkandasajaegerqe-3-5f98589dd-n5lx9    2/2     Running   0          4m8s
jaegerqe-collector-c5bd49948-xgqv5                      1/1     Running   0          3m49s
jaegerqe-query-78cf9488c-4cppz                          2/2     Running   0          3m49s
```

Jaeger CR: 
```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaegerqe
spec:
  ingress:
    security: none
  strategy: production
  storage:
    type: elasticsearch
    elasticsearch:
      nodeCount: 3
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "1Gi"
```
