### ISSUE TITLE
[dedicated] Edit suggested in file logging/cluster-logging.adoc

### ISSUE THREAD

**Issue by patrickstrick** [openshift/openshift-docs#22553]
### Which section(s) is the issue in?
Intro paragraph

### What needs fixing?
Change "two" to "seven" as shown below. We increased the log retention duration, but docs were not updated.
from...
Logs in OpenShift Dedicated are retained for two days before rotation.
to...
Logs in OpenShift Dedicated are retained for seven days before rotation.

**Comment by jboxman** [comment]
@mburke5678, FYI

**Comment by mburke5678** [comment]
@patrickstrick PTAL: https://github.com/openshift/openshift-docs/pull/22556

Can you suggest a QE resource to review?
