### ISSUE TITLE
[enterprise-4.4] Router changes placed under header "Machine Config Operator" in release_notes/ocp-4-4-release-notes.adoc

### ISSUE THREAD

**Issue by chlunde** [openshift/openshift-docs#22599]
#### Machine Config Operator

```md

*Machine Config Operator*

* Because some applications are sensitive to HAProxy timeout values, such as
Kuryr, 24 hour timeout values were used for the API LB. If an HAProxy reload
operation was triggered many times in a short period, it was possible for many
HAProxy processes to accumulate. This bug fix forces sending `SIGTERM` after a
default timeout of 120 seconds to old HAProxy processes which have not yet
terminated. As a result, the number of long lived duplicate HAProxy processes is
reduced.
(link:https://bugzilla.redhat.com/show_bug.cgi?id=1771566[*BZ#1771566*])
```

### What needs fixing?
The header says "Machine Config Operator", but should probably be OpenShift Router similar, because the contents of the section is about OpenShift Router/Ingress memory use.

PS! It might also be worth to mention that web sockets will now be terminated earlier than they used to, because that is seems like a side effect of this change.

**Comment by jboxman** [comment]
@codyhoag FYI

**Comment by mandre** [comment]
Hi, Machine Config Operator is correct here - the change was about tweaking the configuration for the haproxy static pod used in on-premise deployments, in this case OpenStack.
The change made sure that defunct haproxy processes did not accumulate and had no effect on alive processes, so there is no side effect.

**Comment by codyhoag** [comment]
Thank you for explaining, @mandre. I'm closing this issue since the current text correctly aligns with the bug fix.

**Comment by chlunde** [comment]
Cool, thanks for taking a look! I did not know that some OpenShift installations have a separate HAProxy unrelated to the router, it was not clear to me after reading the release notes.

I guess you might want to consider explicitly saying this does not affect the router in case other people also find this confusing.
