### ISSUE TITLE
[enterprise-4.4] Edit suggested in file applications/deployments/managing-deployment-processes.adoc

### ISSUE THREAD

**Issue by akostadinov** [openshift/openshift-docs#22601]
### Which section(s) is the issue in?

> #deployments-setting-resources_deployment-operations

### What needs fixing?

Under this section I think it needs to be explained the difference between `limits` and `requests`. And what they mean depending on CPU or Memory node availability.

Basically this section from old documentationt:
https://docs.openshift.com/enterprise/3.2/dev_guide/compute_resources.html#quality-of-service-tiers

Should be added this page or linked to in case it is somewhere else I can't find.

**Comment by mburke5678** [comment]
@akostadinov Howdy. Cleaning out old issues. Does this section provide the information you are suggesting? If so, we can add a link to the docs to this section, 
[Understanding managing application memory ](https://docs.openshift.com/container-platform/4.9/nodes/clusters/nodes-cluster-resource-configure.html#nodes-cluster-resource-configure-about_nodes-cluster-resource-configure)
