### ISSUE TITLE
[enterprise-4.4] Edit suggested in file storage/container_storage_interface/persistent-storage-csi.adoc

### ISSUE THREAD

**Issue by ckyriakidou** [openshift/openshift-docs#22613]
### Which section(s) is the issue in?

4.4 supports 1.2 CSI 

### What needs fixing?
the version which is supported needs to change from 1.1. to 1.2

**Comment by jboxman** [comment]
@bobfuru, FYI

**Comment by bobfuru** [comment]
Addressing this in https://github.com/openshift/openshift-docs/pull/22617 - closing issue.
