### ISSUE TITLE
[enterprise-4.4] Edit suggested in file release_notes/ocp-4-4-release-notes.adoc

### ISSUE THREAD

**Issue by lbohnsac** [openshift/openshift-docs#22701]
### Which section(s) is the issue in?

etcd cluster operator

### What needs fixing?
OpenShift Container Platform 4.4 introduces the etcd cluster Operator, which handles the scaling of etcd and provisioning etcd dependencies such as TLS certificates. The etcd cluster Operator simplifies the disaster recovery procedure to restore to a previous cluster state, automates the addition of etcd members, provides more accurate etcd member health reporting, and reports events to assist with debugging the etcd cluster.

Where is the etcd cluster operator documented?

**Comment by bergerhoffer** [comment]
PR to add the etcd cluster operator to the list of operators doc: https://github.com/openshift/openshift-docs/pull/24348

**Comment by bergerhoffer** [comment]
Closing as this update is live: https://docs.openshift.com/container-platform/4.5/operators/operator-reference.html#etcd-cluster-operator_red-hat-operators
