### ISSUE TITLE
[enterprise-4.4] Edit suggested in file machine_management/manually-scaling-machineset.adoc

### ISSUE THREAD

**Issue by lbohnsac** [openshift/openshift-docs#22700]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.4/machine_management/

### What needs fixing?
machine configs are still missing!
Add documentation for machineconfig and and machineconfigpool ... machine sets are completely useless on bare metal and UPI installations!

**Comment by yrro** [comment]
#20688 also mentions the missing docs for creation of MachineConfigPools; this could be closed as a dupe of that issue.

(FYI, that issue links to https://access.redhat.com/solutions/4342791 which describes how to create an MCP).
