### ISSUE TITLE
[enterprise-4.4] Add guidance to create additional storage classes supporting using more performant disk types 

### ISSUE THREAD

**Issue by aakarshg** [openshift/openshift-docs#22726]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.4/scalability_and_performance/optimizing-storage.html

### What needs fixing?

We'll need to document how to create storage classes to facilitate more performant disk options - example would be that an OCP cluster deployed on GCP comes with just [pd-standard storage class](https://github.com/openshift/cluster-storage-operator/blob/master/assets/gcp.yaml). However we in the performance and scale team have noticed that using a storage class that provisions pd-ssd disks are much more performant. 

[Link to a related bugzilla that was closed](https://bugzilla.redhat.com/show_bug.cgi?id=1754001)

**Comment by ahardin-rh** [comment]
@chaitanyaenr @aakarshg Can we sync up about what exactly is needed here? Thanks!
