### ISSUE TITLE
[online] architecture/architecture.adoc has misleading info only relevant to OCP

### ISSUE THREAD

**Issue by cben** [openshift/openshift-docs#22729]
# Which section(s) is the issue in?

https://docs.openshift.com/online/starter/architecture/architecture.html

### What needs fixing?

1. First half of the doc (Introduction to OpenShift Online–OpenShift Online overview): the info here looks correct, but I'd expect it to mention Online is a shared environment where you can start usign OpenShift quickly (and only paying for a small part of a cluster).

2. Second half has lots of **misleading** info that talks about installing a cluster, which is not relevant to Online:

    - CUSTOM OPERATING SYSTEM:
  
        > In OpenShift Online Starter, you must use RHCOS for all control plane machines, but you can use Red Hat Enterprise Linux (RHEL) as the operating system for compute machines

        Wrong, the customer can't create Online clusters, and has no choice in underlying OS.

    - SIMPLIFIED INSTALLATION AND UPDATE PROCESS: 

       > you can deploy a production cluster in supported clouds by running a single command and providing a few values

        Wrong, this refers to OCP installer, irrelevant to Online

    - OPENSHIFT ONLINE LIFECYCLE — again talks about OCP installer.

    - Internet and Telemetry access for OpenShift Online

        > In OpenShift Online Starter, you require access to the internet to install your cluster

        LOL, it has "Online" in the product name :wink:

        > If your cluster is connected to the internet, Telemetry runs automatically, and your cluster is registered to the Red Hat OpenShift Cluster Manager (OCM).

        Wrong.  I guess Online clusters do send telemetry and the teams that operate them can see them in OCM (?), but none of this is visible to the customer.  The login that has an Online account will NOT see the cluster in OCM.

Generally looks like this doc is produced from same source as OCP docs, with the product name replaced to OpenShift Online Starter?  
Could use a significant rewrite for Online, or possibly just hide this page.

**Comment by cben** [comment]
Some context:
A customer who had an OpenShift Online account could no longer find how to log in from openshift.com.
I googled "openshift online" trying to see how would I find it, and indeed it's hard at present :frowning_face:.  
I expected the front page of the docs for Online to explain what Online is and directly say "go [here] to manage your subscription and access your console", before explaining how to use the console.
- The [entry point for Online Starter docs](https://docs.openshift.com/online/starter/welcome/index.html) says "you You can start with an Introduction to OpenShift Online" linking to this architecture.adoc which is mostly irrelevant, certainly as first into to Online :-1:.
- For comparison, [the Online Pro docs](https://docs.openshift.com/online/pro/welcome/index.html) do a much better job on the intro pages :+1:, but still no in-text links to manage.openshift.com.

The docs site "Log In" link on top does lead to manage.openshift.com :+1: but I didn't expect to look there knowing I'm a docs site.

**Comment by vikram-redhat** [comment]
Thanks @cben! Online docs need a bit of a revamp, and this might just be the right incentive.
