### ISSUE TITLE
[enterprise-4.4] Edit suggested in file machine_management/creating-infrastructure-machinesets.adoc

### ISSUE THREAD

**Issue by pamoedom** [openshift/openshift-docs#22779]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.4/machine_management/creating-infrastructure-machinesets.html#infrastructure-moving-monitoring_creating-infrastructure-machinesets

### What needs fixing?

When moving monitoring components to infra nodes, as documented in that section, please note that not all components can be moved in this OCP version, as discussed with Engineering via [BZ#1845187](https://bugzilla.redhat.com/show_bug.cgi?id=1845187), node selector for `thanos-querier` pods are not implemented until 4.6 and will not be backported to 4.4.

Best Regards.

**Comment by lilic** [comment]
cc @maximsvistunov FYI, we do not support thanos querier infra nodes in 4.4 and 4.5, this seems to be misleading to users, so we should just add note that we do not support setting infra node for the above mentioned releases.

**Comment by pmkovar** [comment]
Is this something to close now given 4.4/5 being EOL?

**Comment by mburke5678** [comment]
I believe this issue was resolved in [Add the Thanos querier to the list of configurable components](https://github.com/openshift/openshift-docs/pull/22481/files). I am closing this issue. If this is not correct, please re-open.
