### ISSUE TITLE
[enterprise-4.4] Edit suggested in file jaeger/jaeger_install/rhbjaeger-deploying.adoc

### ISSUE THREAD

**Issue by worsco** [openshift/openshift-docs#22838]
### Which section(s) is the issue in?

"Restrictions" bulletpoints in the "Jeager storage configuration options" section

### What needs fixing?

Third bullet point contains {Product-Name}.  I assume that should say "OpenShift" and not a variable placeholder.

**Comment by ahardin-rh** [comment]
Looks like this was addressed in https://github.com/openshift/openshift-docs/pull/22844
