### ISSUE TITLE
[enterprise-4.4] Edit suggested in file service_mesh/service_mesh_install/installing-ossm.adoc

### ISSUE THREAD

**Issue by christianh814** [openshift/openshift-docs#22866]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.4/service_mesh/service_mesh_install/installing-ossm.html#ossm-operator-install-elasticsearch_installing-ossm

### What needs fixing?

It should be noted that installing the Elastic Search Operator isn't needed if you've already done it when installing the Log Aggregation stack (EFK)

**Comment by JStickler** [comment]
Added a note to the docs.
