### ISSUE TITLE
[enterprise-4.4] Edit suggested in file service_mesh/service_mesh_install/customizing-installation-ossm.adoc

### ISSUE THREAD

**Issue by andrew-garner** [openshift/openshift-docs#22876]
### Which section(s) is the issue in?
[Istio Gateway Configuration](https://docs.openshift.com/container-platform/4.4/service_mesh/service_mesh_install/customizing-installation-ossm.html#ossm-cr-gateway_customizing-installation-ossm)

### What needs fixing?
The Service Mesh page on [Automatic Route Creation](https://docs.openshift.com/container-platform/4.4/service_mesh/service_mesh_day_two/ossm-auto-route.html#ossm-auto-route-enable_{context}) describes the ior_enabled configuration option for the Istio Gateway, however on the Istio Gateway Configuration page, which is linked to from the Automatic Route Creation page, there is no mention of the ior_enabled option.

**Comment by JStickler** [comment]
Added ior_enabled to the parameters table.
