### ISSUE TITLE
[enterprise-4.4] Edit suggested in file welcome/index.adoc

### ISSUE THREAD

**Issue by SaravanaStorageNetwork** [openshift/openshift-docs#22970]
### Which section(s) is the issue in?

Could you add a new section for terminology(in OpenShift)?

### What needs fixing?

Adding a new section for terminology

**Comment by vikram-redhat** [comment]
@SaravanaStorageNetwork - can you give more details of what you are expecting in this new document?

**Comment by SaravanaStorageNetwork** [comment]
I want to see a terminology link accessible from index page which contains different terms used in OpenShift - for example CRD, image streams, Projects(namespace), etc.,
 
One example for reference (in some other product): 
https://access.redhat.com/documentation/en-us/red_hat_certificate_system/9/html/planning_installation_and_deployment_guide/Glossary
