### ISSUE TITLE
[enterprise-4.4] Edit suggested in file applications/quotas/quotas-setting-per-project.adoc

### ISSUE THREAD

**Issue by sbarre-esit** [openshift/openshift-docs#22988]
### Which section(s) is the issue in?

Requiring explicit quota to consume a resource

### What needs fixing?

According to RH Case 02675594 there is no way to configure the `admissionConfig` plugin in OCP 4. So this section should be removed.

**Comment by jboxman** [comment]
@sbarre-esit, thanks! This content came over from 3.11 and must be inapplicable to 4.x: https://docs.openshift.com/container-platform/3.11/admin_guide/quota.html

**Comment by sbarre-esit** [comment]
FYI @mrobson

**Comment by jboxman** [comment]
This is being addressed by: https://bugzilla.redhat.com/show_bug.cgi?id=1844942
