### ISSUE TITLE
[enterprise-4.4] Edit suggested in file installing/install_config/configuring-firewall.adoc

### ISSUE THREAD

**Issue by lautou** [openshift/openshift-docs#22990]
### Which section(s) is the issue in?

In Whitelist the following registry URLs:
...
*.quay.io
...
### What needs fixing?
Replace quay.io instead of *.quay.io. (Because firewall think https://quay.io cannot match *.quay.io with the dot before "quay.io")

**Comment by vikram-redhat** [comment]
@codyhoag ^
