### ISSUE TITLE
Cluster Loader authentication

### ISSUE THREAD

**Issue by trexx** [openshift/openshift-docs#23009]
### Which section(s) is the issue in?
OpenShift Container Platform / 4.4 / Scalability and performance / Using Cluster Loader

### What needs fixing?
Could there be further elaboration on the prerequisites section. In particular regarding authentication and downloading from the repository:
> The repository will prompt you to authenticate. The registry credentials allow you to access the image, which is not publicly available. Use your existing authentication credentials from installation.

I've tried pull secrets from https://cloud.redhat.com/openshift/install/pull-secret, and my cloud.redhat.com credentials to no avail.
Which authentication credentials? What installation?

**Comment by sjug** [comment]
Hey there @trexx, you should use the same credentials you used (your pull-secret) to install the cluster initially.

**Comment by trexx** [comment]
So in my pull secrets, I see credentials for `cloud.openshift.com, quay.io, registry.connect.redhat.com, registry.redhat.io` but the documentation asks for me to pull from `registry.svc.ci.openshift.org` as far as I can tell, my pull secret doesn't authenticate me against the domain the documentation is asking me to pull from.

**Comment by sjug** [comment]
@trexx the registries have been in flux so you're entirely correct. I'm looking into this further.

**Comment by trexx** [comment]
Thanks. I've also come across this BZ too: [[doc] a different registry for the Cluster Loader [NEEDINFO]](https://bugzilla.redhat.com/show_bug.cgi?id=1817620)

**Comment by sjug** [comment]
Hey @trexx, we have a PR here to change the registry: https://github.com/openshift/openshift-docs/pull/23321.
Can you see if it works for you?

**Comment by trexx** [comment]
Hi @sjug. Yep that registry change works for me, I've been using it since I discovered PR18293 however I've had issues with some of the examples on that page. For example,

```
$ sudo podman run -v ${LOCAL_KUBECONFIG}:/root/.kube/config:z -i \
quay.io/openshift/origin-tests:4.5 /bin/bash -c 'export KUBECONFIG=/root/.kube/config && \
openshift-tests run-test "[Feature:Performance][Serial][Slow] Load cluster should load the \
cluster [Suite:openshift]"'
```

Results in "error: no test exists with that name"

Should I open another issue?

**Comment by ahardin-rh** [comment]
@trexx @JaredBurck @sjug What's the way forward on this?

**Comment by sjug** [comment]
@trexx Hey there, the name of the test to run has changed to:
```
"[sig-scalability][Feature:Performance] Load cluster should populate the cluster [Slow][Serial] [Suite:openshift]"
```

**Comment by ahardin-rh** [comment]
@trexx @sjug Thanks! I opened https://github.com/openshift/openshift-docs/pull/24453 to update the test names

**Comment by mffiedler** [comment]
@RH-ematysek Please take a look and provide a QE review.  Thanks.   /cc: @cpmeadors if you have a chance to look since I know you were looking at cluster-loader semi-recently.

**Comment by trexx** [comment]
@sjug @ahardin-rh 

Thanks for the updates, I've been able to successfully run the load cluster tests now.

**Comment by ahardin-rh** [comment]
Thanks, all! The updates are all merged, so I am closing this issue out. Please let me know if you have any questions or concerns.
