### ISSUE TITLE
[enterprise-4.4] Edit suggested in file installing/installing_bare_metal/installing-bare-metal.adoc

### ISSUE THREAD

**Issue by williamcaban** [openshift/openshift-docs#23012]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.4/installing/installing_bare_metal/installing-bare-metal.html#installation-complete-user-infra_installing-bare-metal

### What needs fixing?

This section is missing a step indicating to the user that the bootstrap node can be removed after the control plane deployment is completed.

**Comment by jeana-redhat** [comment]
Actually it appears this is already covered earlier in the docs. See step 2 here: https://docs.openshift.com/container-platform/4.4/installing/installing_bare_metal/installing-bare-metal.html#installation-installing-bare-metal_installing-bare-metal
