### ISSUE TITLE
[enterprise-4.3] Edit suggested in file nodes/nodes/nodes-nodes-resources-configuring.adoc

### ISSUE THREAD

**Issue by bmillemathias-1a** [openshift/openshift-docs#23064]
### Which section(s) is the issue in?
all that use "`curl <certificate details> https://<master>/api/....`"

### What needs fixing?

curl examples require for the reader to 
* know the url details
* to sort out the certificates validation
* to pass the authentication parameters ...

That should be more interesting and simpler to use
`oc get --raw '/api/..' `that hides all that stuff.

That applies to any version and any pages that use curl to talk to the API.

**Comment by jboxman** [comment]
@bmillemathias-1a, thanks for reporting this!

**Comment by jboxman** [comment]
Updated to use `oc` instead of `curl`.
