### ISSUE TITLE
[enterprise-4.4] Edit suggested in file cnv/cnv-about-cnv.adoc

### ISSUE THREAD

**Issue by peterclauterbach** [openshift/openshift-docs#23078]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.5/virt/about-virt.html#openshift-virtualization-support

### What needs fixing?

OpenShift virtualization will be Generally Available (GA) with OCP 4.5. Either remove the TP language, or replace a notice that it is GA.

**Comment by peterclauterbach** [comment]
it seems the TP language is on just about every page. We just need to make the GA notification in the release notes, and remove the TP language everywhere else.

**Comment by jboxman** [comment]
@bgaydosrh FYI

**Comment by jboxman** [comment]
@peterclauterbach, it looks like we removed the TP language?

**Comment by aburdenthehand** [comment]
Tech Preview language was removed with the OpenShift Virtualization 2.4 release (but was still present with preview builds up until the release).
Closing
