### ISSUE TITLE
[enterprise-4.4] Edit suggested in file cnv/cnv-about-cnv.adoc

### ISSUE THREAD

**Issue by peterclauterbach** [openshift/openshift-docs#23077]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.5/virt/about-virt.html#virt-what-you-can-do-with-virt_about-virt

### What needs fixing?

"OpenShift virtualization is an add-on to OpenShift Container Platform"
s.b.
"OpenShift virtualization is a feature of OpenShift Container Platform"

**Comment by jboxman** [comment]
@bgaydosrh FYI

**Comment by jboxman** [comment]
@peterclauterbach, this looks resolved, I think?

**Comment by peterclauterbach** [comment]
ack, closing.
