### ISSUE TITLE
[enterprise-4.5] Edit suggested in file virt/virt-2-4-release-notes.adoc

### ISSUE THREAD

**Issue by peterclauterbach** [openshift/openshift-docs#23079]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.5/virt/virt-2-4-release-notes.html#openshift-virtualization-support

### What needs fixing?

OpenShift virtualization will be GA with OCP 4.5, replace TP language with GA notice.

**Comment by jboxman** [comment]
@bgaydosrh FYI

**Comment by bgaydosrh** [comment]
This request has been satisfied by https://github.com/openshift/openshift-docs/pull/23748 (in progress)

The associated Jira story is: 
https://issues.redhat.com/browse/CNV-4363

cc: @vikram-redhat @peterclauterbach @jboxman @lmandavi
