### ISSUE TITLE
[enterprise-4.4] Issue in file networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-service-external-ip.adoc

### ISSUE THREAD

**Issue by lautou** [openshift/openshift-docs#23149]
### Which section(s) is the issue in?

Using a service external IP to get traffic into the cluster

### What needs fixing?
No explanations about how manage High Availability if a node holding the external IP fall down.

**Comment by jboxman** [comment]
@lautou, right now HA is outside the scope of what we're documenting.

**Comment by lautou** [comment]
@jboxman "HA is outside the scope" --> This apply for the complete doc or only for this page?

**Comment by jboxman** [comment]
@lautou, for [Configuring ingress cluster traffic using a service external IP](https://docs.openshift.com/container-platform/4.5/networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-service-external-ip.html), there aren't any current plans to describe how to configure your network infrastructure for HA for external IPs.

**Comment by jboxman** [comment]
@lautou, there's an RFE open to bring back _ipfailover_ or similar functionality from OCP 3.x.

I'm going to close this, and if that gets implemented, I will update the documentation accordingly. Thanks!
