### ISSUE TITLE
[enterprise-4.4] Issue in file builds/understanding-buildconfigs.adoc

### ISSUE THREAD

**Issue by christianh814** [openshift/openshift-docs#23165]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.4/builds/understanding-buildconfigs.html

### What needs fixing?

There is no example on how to specify  a branch under `spec.source.git`

**Comment by garbagego** [comment]
spec.source.git.ref

   **ref	<string>
     ref is the branch/tag/ref to build.**
