### ISSUE TITLE
[enterprise-4.4] Issue in file networking/openshift_sdn/assigning-egress-ips.adoc unfortune example in step 2

### ISSUE THREAD

**Issue by lbohnsac** [openshift/openshift-docs#23199]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.4/networking/openshift_sdn/assigning-egress-ips.html#nw-egress-ips-automatic_egress-ips

### What needs fixing?
The example in step 2 does not fit to the explanation!
Add also an example with one command as explained in the example directly above not only with two commands ...

**Comment by jboxman** [comment]
@lbohnsac, how doesn't it fit? What would make it fit?

Thanks.
