### ISSUE TITLE
[enterprise-4.4] Issue in file networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-service-external-ip.adoc

### ISSUE THREAD

**Issue by lbohnsac** [openshift/openshift-docs#23198]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.4/networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-service-external-ip.html#nw-service-external-ip_configuring-ingress-cluster-traffic-service-external-ip

### What needs fixing?
important steps are missing!
1. how to define the IP/IP range to use for ingress traffic on the node(s)
2. how to define/choose a specific IP for the service user wants to use

**Comment by jboxman** [comment]
@lbohnsac, I've updated the documentation with the correct procedure for this.
