### ISSUE TITLE
[enterprise-4.2] Issue in file storage/persistent_storage/persistent-storage-nfs.adoc

### ISSUE THREAD

**Issue by chuckersjp** [openshift/openshift-docs#23216]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.2/storage/persistent_storage/persistent-storage-nfs.html#nfs-selinux_persistent-storage-nfs

### What needs fixing?
The procedure documented only applies to RHEL worker nodes.  The setting in question is already present RHCOS machines.  This can lead to confusion for the user and should be made more clear.
This clarification should be made to the earliest version available.

### Suggested fix
Change: 
`To enable writing to a remote NFS server, follow the below procedure.`

to be: 
`To enable writing to a remote NFS server, follow the below procedure. **NOTE** This only needs to be performed on RHEL based worker nodes.  This is the default for RHCOS nodes.`

**Comment by bobfuru** [comment]
Thanks for reporting this, @chuckersjp! 🥇  
The setting to enable writing in remote NFS is also present in RHEL machines, as tested by QE, and the docs have been updated in 4.4+ to indicate this in https://github.com/openshift/openshift-docs/pull/27388. Closing this issue.
