### ISSUE TITLE
[enterprise-4.4] Issue in file backup_and_restore/replacing-unhealthy-etcd-member.adoc

### ISSUE THREAD

**Issue by peterclauterbach** [openshift/openshift-docs#23236]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.4/backup_and_restore/replacing-unhealthy-etcd-member.html#restore-replace-stopped-etcd-member_replacing-unhealthy-etcd-member

### What needs fixing?

> You have taken an etcd backup.
> It is important to take an etcd backup before performing this procedure so that your cluster can be restored if you encounter any issues.

This should have a link to the section about how to take an etcd backup somewhere in here.

https://docs.openshift.com/container-platform/4.4/backup_and_restore/backing-up-etcd.html#backing-up-etcd-data_backup-etcd

**Comment by vikram-redhat** [comment]
Hey @peterclauterbach unfortunately, due to modular docs requirements, we are not allowed to add links from within procedures to other docs. 

That said the prereq for this section does provide the link to taking a backup. 

@bergerhoffer
