### ISSUE TITLE
[enterprise-4.4] Issue in file nodes/nodes/nodes-nodes-rebooting.adoc

### ISSUE THREAD

**Issue by michaelgugino** [openshift/openshift-docs#23244]
### Which section(s) is the issue in?

Need a new section

### What needs fixing?

In OpenShift 4, there is no direct way to reboot a node from within the cluster.  We should add this information specifically to this document.  The document currently reads as if it's going to instruct you 'how' to reboot a node or 'why' to reboot a node, but it really talks about other details.

This section also seems to be a hold-over from OpenShift 3, as there are no infra nodes by default in OpenShift 4: https://docs.openshift.com/container-platform/4.4/nodes/nodes/nodes-nodes-rebooting.html#nodes-nodes-rebooting-infrastructure_nodes-nodes-rebooting

**Comment by mburke5678** [comment]
@michaelgugino thank you for your comments. 
I made a quick first cut at reworking the rebooting topic with the goal of making it clear that the topic is about things to consider when rebooting a node and not about *how* to reboot a node. 
Do these changes start to address your concerns? We can certainly do more work on these file. Just want to make sure I am moving in the right direction. Please feel free to make further suggestions on getting this righ.
https://github.com/openshift/openshift-docs/pull/23256
