### ISSUE TITLE
[enterprise-4.4] Use of LoadBalancer services with OCP on OpenStack

### ISSUE THREAD

**Issue by yrro** [openshift/openshift-docs#23253]
### Which section(s) is the issue in?
[Creating a LoadBalancer service](https://docs.openshift.com/container-platform/4.4/networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-load-balancer.html#nw-create-load-balancer-service_configuring-ingress-cluster-traffic-load-balancer)

### What needs fixing?
"The service has an external IP address automatically assigned if there is a cloud provider enabled"

It is not clear what "if there is a cloud provider enabled" means. I assume that clusters on OpenStack are not currently able to use this functionality. Can this be clarified in this section of the documentation?

**Comment by yrro** [comment]
After a bit of research I stumbled upon https://access.redhat.com/solutions/4722521 which explains that Octavia is not supported with OpenShiftSDN. Can this information be incorporated into the manual?

**Comment by maxwelldb** [comment]
This might be addressed in upcoming ShiftStack load balancing docs. 

https://github.com/openshift/openshift-docs/pull/28275 (more to come)

**Comment by maxwelldb** [comment]
I'd take a look at the load balancing procedures added in 4.7. Feel free to re-open this issue if the docs there are lacking, but do note that they are unsupported in versions <4.7.
