### ISSUE TITLE
[enterprise-4.5] Issue in file release_notes/ocp-4-5-release-notes.adoc

### ISSUE THREAD

**Issue by KedarS05** [openshift/openshift-docs#23314]
### Which section(s) is the issue in?
The issue lies in the following documentation section
- https://docs.openshift.com/container-platform/4.5/release_notes/ocp-4-5-release-notes.html#rhba-2020-1234

### What needs fixing?
In the documentation section :
- https://docs.openshift.com/container-platform/4.5/release_notes/ocp-4-5-release-notes.html#rhba-2020-1234

The following link is showing 404 error when accessed
- [OpenShift Container Platform 4.5.0 container image list](https://access.redhat.com/solutions/123456789)

**Comment by codyhoag** [comment]
@KedarS05 the 4.5 release notes are a work in progress. The link for the container image list is a placeholder at this time, since the final image list has not been finalized. This will be updated before the official 4.5 GA and publishing of the supported 4.5 docs.
