### ISSUE TITLE
Clarify:  Cluster resources must adjust to the new pull secret, which can temporarily limit the usability of the cluster.

### ISSUE THREAD

**Issue by wking** [openshift/openshift-docs#23378]
In #16955, [discussion][1] between @mburke5678, @bergerhoffer, @radekvokal, and @iNecas landed:

> Cluster resources must adjust to the new pull secret, which can temporarily limit the usability of the cluster.

I think that's still too threatening ;). What usability limits do we expect? It will take a bit to get the new secret rolled out, and we currently have some hiccups around availability during reboots ([rhbz#1845411][2] and [rhbz#1809665][3]). If that's the expected usability impact, I'd rather call it out explicitly. As it stands, it seems to be stirring up fear and uncertainty without providing the reader with a means to assess the trade-offs (or importance of bumping pull secrets during a scheduled maintenance window, or things to watch for during that maintenance window, or how to judge completion).

[1]: https://github.com/openshift/openshift-docs/pull/16955#discussion_r331501320
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=1845411
[3]: https://bugzilla.redhat.com/show_bug.cgi?id=1809665

**Comment by LalatenduMohanty** [comment]
I see below text in [1] and I am assuming node drain would impact availability. Is that right?
```
This update is rolled out to all nodes, which can take some time depending on the size of your cluster. During this time, nodes are drained and Pods are rescheduled on the remaining nodes.
```
[1] https://docs.openshift.com/container-platform/4.4/openshift_images/managing_images/using-image-pull-secrets.html#images-update-global-pull-secret_using-image-pull-secrets

**Comment by wking** [comment]
It shouldn't impact availability (once we fix the bugs I linked in the opening comment).  And if we are calling the rolling reboots out there, can we drop the warning?  And link to docs about monitoring node rebooting so users can judge completion?
