### ISSUE TITLE
[enterprise-4.4] Unworkable example in file networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-service-external-ip.adoc

### ISSUE THREAD

**Issue by flozanorht** [openshift/openshift-docs#23407]
### Which section(s) is the issue in?

Headings "Creating a project and service" and "Exposing the service by creating a route" of "Configuring ingress cluster traffic using a service external IP"

### What needs fixing?

The example of exposing a mysql server using a route does not work. OpenShift routes support only HTTP, TLS with SNI, and WebSockets protocols. None of these are supported my neither MySQL nor MariaDB.

The examples are also inconsistent with the section heading of "Configuring ingress cluster traffic using a service external IP". An external IP is not the same as the Cluster-IP of a regular service. If you wanna use a service external IP, you would not use a route.

The are multiple issues trying to follow the steps in the documentation, but in the end there's no way to make them work. You could switch to any of the many "hello, world" types of sample apps available, many of them are quickstart templates that come in ready to run with OpenShift, to make the route works, but using the service or pod IPs would still fail, and the steps would still not be using a service external IP.

In the end it is not just a fix to a few commands nor sentences. This section of the product docs require an almost complete rewrite.

See my attempts to follow the example in product docs in an OpenShift 4.4.8 cluster installed in a bare metal test lab:

```
$ oc new-project test-mysql
Now using project "test-mysql" on server "https://api.ocp4.example.com:6443".
...
```

```
$ oc new-app \
>     -e MYSQL_USER=admin \
>     -e MYSQL_PASSWORD=redhat \
>     -e MYSQL_DATABASE=mysqldb \
>     registry.redhat.io/rhscl/mysql-80-rhel7
W0701 10:14:43.580645   31621 dockerimagelookup.go:236] container image registry lookup failed: registry.redhat.io/rhscl/mysql-80-rhel7:latest: Get https://registry.redhat.io/v2/rhscl/mysql-80-rhel7/manifests/latest: unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/RegistryAuthentication
error:  local file access failed with: stat registry.redhat.io/rhscl/mysql-80-rhel7: no such file or directory
error: unable to locate any images in image streams, templates loaded in accessible projects, template files, local docker images with name "registry.redhat.io/rhscl/mysql-80-rhel7"
```

I can workaround the previous failure by either using the mysql-ephemeral quickstart template or using the still available public registry. Using the second approach:

```
$ oc new-app \
>   -e MYSQL_USER=admin \
>     -e MYSQL_PASSWORD=redhat \
>     -e MYSQL_DATABASE=mysqldb \
>     registry.access.redhat.com/rhscl/mysql-80-rhel7
--> Found container image 3c7ae7d (13 days old) from registry.access.redhat.com for "registry.access.redhat.com/rhscl/mysql-80-rhel7"
...
--> Creating resources ...
    imagestream.image.openshift.io "mysql-80-rhel7" created
    deploymentconfig.apps.openshift.io "mysql-80-rhel7" created
    service "mysql-80-rhel7" created
--> Success
...
```

My database pod is ready and running:

```
$ oc get pod
NAME                      READY   STATUS      RESTARTS   AGE
mysql-80-rhel7-1-deploy   0/1     Completed   0          89s
mysql-80-rhel7-1-j2xh8    1/1     Running     0          87s
```

```
$ oc expose service mysql-80-rhel7
route.route.openshift.io/mysql-80-rhel7 exposed
```

Step 4 says "using the cluster IP address for the service" but the sample command is "curl <pod_ip>:<port>". These are not the same, and none of them is available to clients outside of the cluster, by design. Also, why using a service or pod IP if I just created a route? 

Anyway, here's what happens, first using the service IP:

```
$ oc get svc
NAME             TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
mysql-80-rhel7   ClusterIP   172.30.47.124   <none>        3306/TCP   4m40s
```

```
$ curl 172.30.47.124:3306
^C
```

It never connects so I had to terminate curl using Ctrl+C. Adding verbosity and a timeout to curl to make things clearer:

```
$ curl --connect-timeout 9 -v 172.30.47.124:3306
* Rebuilt URL to: 172.30.47.124:3306/
*   Trying 172.30.47.124...
* TCP_NODELAY set
* Connection timed out after 9001 milliseconds
* Closing connection 0
curl: (28) Connection timed out after 9001 milliseconds
```

Now try using the pod IP, same thing happens: curl never connects:

```
$ oc get pod -o wide
NAME                      READY   STATUS      RESTARTS   AGE     IP          NODE       NOMINATED NODE   READINESS GATES
mysql-80-rhel7-1-deploy   0/1     Completed   0          9m23s   10.8.2.19   worker03   <none>           <none>
mysql-80-rhel7-1-j2xh8    1/1     Running     0          9m21s   10.8.2.20   worker03   <none>           <none>
```

```
$ curl --connect-timeout 9 -v 10.8.2.20:3306
* Rebuilt URL to: 10.8.2.20:3306/
*   Trying 10.8.2.20...
* TCP_NODELAY set
* Connection timed out after 9000 milliseconds
* Closing connection 0
curl: (28) Connection timed out after 9000 milliseconds
```

Using the MySQL client does not makes things better for neither the service nor the pod IP:

```
$ mysql -h 172.30.47.124 -u admin -p
Enter password: 
^C
```

```
$ mysql -h 172.30.47.124 -u admin -p -v --connect-timeout=9
Enter password: 
ERROR 2003 (HY000): Can't connect to MySQL server on '172.30.47.124' (110)
```

```
$ mysql -h 172.30.47.124 -u admin -p -v --connect-timeout=9
Enter password: 
ERROR 2003 (HY000): Can't connect to MySQL server on '172.30.47.124' (110)
```

```
[student@workstation ~]$ mysql -h 10.8.2.20 -u admin -p -v --connect-timeout=9
Enter password: 
ERROR 2003 (HY000): Can't connect to MySQL server on '10.8.2.20' (110)
```

Well, these examples were about using a route to expose the service, right? Using the hostname of the route does not work either. It can connect to the OpenShift router but the router gets no replies from MySQL:

```
$ curl --connect-timeout 9 -v mysql-80-rhel7-test-mysql.apps.ocp4.example.com 
* Rebuilt URL to: mysql-80-rhel7-test-mysql.apps.ocp4.example.com/
*   Trying 192.168.50.254...
* TCP_NODELAY set
* Connected to mysql-80-rhel7-test-mysql.apps.ocp4.example.com (192.168.50.254) port 80 (#0)
> GET / HTTP/1.1
> Host: mysql-80-rhel7-test-mysql.apps.ocp4.example.com
> User-Agent: curl/7.61.1
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host mysql-80-rhel7-test-mysql.apps.ocp4.example.com left intact
curl: (52) Empty reply from server
```

```
$ mysql -h mysql-80-rhel7-test-mysql.apps.ocp4.example.com -u admin -p -v --connect-timeout=9
Enter password: 
ERROR 2003 (HY000): Can't connect to MySQL server on 'mysql-80-rhel7-test-mysql.apps.ocp4.example.com' (113)
```

I repeated these steps on an IPI cluster on AWS and using the MariaDB client and got similar results.

**Comment by jboxman** [comment]
@flozanorht, yes, this content is incorrect in its entirety. And as a prerequisite, external IPs must be configured for the cluster. [Work on that is inflight](https://github.com/openshift/openshift-docs/pull/21388). Once that is complete, this content will be updated.

**Comment by jboxman** [comment]
I've updated the procedure with proper steps. Thanks!
