### ISSUE TITLE
[dedicated] Issue in file logging/dedicated-cluster-deploying.adoc

### ISSUE THREAD

**Issue by cblecker** [openshift/openshift-docs#23496]
### Which section(s) is the issue in?

`4. Create and deploy a cluster logging instance`

### What needs fixing?

In the YAML that the directions say to copy and paste, there is one variable in there that needs to be modified:
`storageClassName: "<storage-class-name>"`

On AWS, this should be `storageClassName: "gp2"` and on GCP this should be `storageClassName: "standard"`

I'm not sure if it is easier to provide 2 copy/paste examples and just tell users to copy the right one, or to explicitly call out this one value need to be modified.. but either way, this documentation should lay this out a bit more clearly.

cc: @jewzaam

**Comment by jewzaam** [comment]
cc @lamek

**Comment by mburke5678** [comment]
@cblecker @jewzaam @lamek This has been fixed and the docs are updated. Thank you for pointing this out.

https://docs.openshift.com/dedicated/4/logging/dedicated-cluster-deploying.html#dedicated-cluster-install-deploy

**Comment by cblecker** [comment]
/reopen

@mburke5678 This does not appear to be addressed. The docs only handle the AWS use case, and don't speak to the GCP use case above.

**Comment by mburke5678** [comment]
@lamek Do you want to take this one?

**Comment by mburke5678** [comment]
@cblecker While we are looking at the Dedicated install, can you confirm the namespace to install the Elasticsearch Operator into? The Dedicated docs suggest the `openshift-logging` namespace. For OCP logging, the Elasticsearch Operator must be installed into openshift-operators-redhat` with the note:
_You must specify the openshift-operators-redhat Namespace. To prevent possible conflicts with metrics, you should configure the Prometheus Cluster Monitoring stack to scrape metrics from the openshift-operators-redhat Namespace and not the openshift-operators Namespace. The openshift-operators Namespace might contain Community Operators, which are untrusted and could publish a metric with the same name as an OpenShift Container Platform metric, which would cause conflicts._

**Comment by jewzaam** [comment]
@mburke5678 we have successfully run with ES and cluster-logging in `openshift-logging` since OSD GA.  Is there a technical reason this is not going to work?  Because it does work... @igor-karpukhin is working on an add-on for logging that is following the same pattern.

**Comment by cblecker** [comment]
/remove-lifecycle rotten

still relevant

**Comment by mburke5678** [comment]
@cblecker Sorry for dragging on this one. I brought this issue up with the Dedicated writer @sfortner-RH earlier today.
