### ISSUE TITLE
[enterprise-4.4] Issue in file installing/installing_bare_metal/installing-bare-metal.adoc

### ISSUE THREAD

**Issue by gyucegok** [openshift/openshift-docs#23498]
### Which section(s) is the issue in?
Configuring a three-node cluster, exactly here;

- compute:
    name: worker
    platform: {}
    replicas: 0

### What needs fixing?

The list item is under compute, something like this exactly;

compute:
- name: worker
  platform: {}
  replicas: 0

**Comment by codyhoag** [comment]
This was fixed in #24463. Thanks!
