### ISSUE TITLE
[enterprise-4.3] Issue in file cli_reference/openshift_cli/getting-started-cli.adoc

### ISSUE THREAD

**Issue by novacain1** [openshift/openshift-docs#23511]
### Which section(s) is the issue in?
Installing the CLI by using an RPM

### What needs fixing?
We have no reference how to install the openshift-clients RPM in a RHEL8 system.  RHEL8 has been out more than a year.  The repo specifically is rhocp-4.4-for-rhel-8-x86_64-rpms, and this section should really address how to install the openshift-clients on RHEL8.

**Comment by bergerhoffer** [comment]
PRs have been merged, closing this issue.
