### ISSUE TITLE
[enterprise-4.5] Issue in file release_notes/ocp-4-5-release-notes.adoc

### ISSUE THREAD

**Issue by hupiper** [openshift/openshift-docs#23524]
### Which section(s) is the issue in?
https://redhat:redhat@docs.openshift.com/container-platform/4.5/release_notes/ocp-4-5-release-notes.html#ocp-4-5-encrypt-ebs-instance-volumes-with-kms-key

### What needs fixing?
Are we going to describe how to do this via machineconfig if it is not done during installation?

**Comment by codyhoag** [comment]
@abhinavdahiya can you advise on whether we should describe the machineconfig case in the release notes?

**Comment by abhinavdahiya** [comment]
Can you explain why machineconfigs would come into picture? The installer generates machine objects either correct default volumes encrypted with the provided key

**Comment by hupiper** [comment]
At one point it wasn't being done at all. If you can do it during install, we can close this issue.
