### ISSUE TITLE
s2i image docs tell me to set dev mode on build sourceStrategy

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-docs#2353]
https://docs.openshift.org/latest/using_images/s2i_images/nodejs.html#nodejs-configuration says to set DEV_MODE on the build sourceStrategy or in the s2i/environment file, but I can't think of when I would actually ever want to do that.  I would only ever want to set it on a DC.

@bparees @csrwng

**Comment by bparees** [comment]
setting it on the buildconfig results in it being part of the image so you don't have to set it on the DC.  (and you can always override it back to false on the DC if you don't want it set).

DEV_MODE could also affect build time package installation decisions in the future.

**Comment by smarterclayton** [comment]
But why would I *want* a dev mode image?

**Comment by bparees** [comment]
because you're not running it on openshift where you can easily have a fixed DC that defines dev_mode?  because you want dev mode to be the default mode for your image?

we can certainly update the doc to note that you can also set the value on the DC if you don't want it part of the image.

**Comment by smarterclayton** [comment]
But if I'm not running on openshift why would I be using the build
sourceStrategy?  I can't really see dev mode as anything other than "turn
it on to rapidly iterate, then turn it off and never think about it
again".  Forcing the image to have that default seems to defeat the intent
of being able to iterate.

**Comment by bparees** [comment]
> But if I'm not running on openshift why would I be using the build sourceStrategy?

because it's an easy way to build nodejs images no matter where you want to run it?

anyway i created the PR to update the docs, we can discuss/debate the merits of my change there.
