### ISSUE TITLE
[enterprise-3.11] Issue in file admin_guide/image_signatures.adoc

### ISSUE THREAD

**Issue by 2s1ddhant** [openshift/openshift-docs#23538]
### Which section(s) is the issue in?
Importing Image Signatures Automatically from Signature Stores

### What needs fixing?
The link in the last line "For more details about the registries configuration directory, see [Registries Configuration Directory](https://github.com/containers/image/blob/master/docs/registries.d.md)"  redirects to an invalid page.

**Comment by codyhoag** [comment]
Fix has been merged. It will be available live soon. Thanks for reporting!
