### ISSUE TITLE
[enterprise-4.3] Issue in file scalability_and_performance/using-node-tuning-operator.adoc

### ISSUE THREAD

**Issue by peterducai** [openshift/openshift-docs#23588]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.3/scalability_and_performance/using-node-tuning-operator.html doesn't contain how to validate setup

### What needs fixing?
could we get 'how to check if profile was set' from https://access.redhat.com/solutions/4448351 to official docs?

**Comment by ahardin-rh** [comment]
@peterducai Thank you! 
@jmencak What are your thoughts on this suggestion? Thanks!

**Comment by jmencak** [comment]
I agree that adding something like this to the documentation would be useful.  Happy to review!

**Comment by ahardin-rh** [comment]
@jmencak @peterducai Please review: https://github.com/openshift/openshift-docs/pull/23659

**Comment by ahardin-rh** [comment]
@peterducai Thanks again for your suggestion! The pull request is merged, so I am closing this issue. 
@jmencak Thanks for your guidance on the docs!
