### ISSUE TITLE
[enterprise-4.4] Issue in file service_mesh/service_mesh_install/removing-ossm.adoc

### ISSUE THREAD

**Issue by FilipB** [openshift/openshift-docs#23625]
### Which section(s) is the issue in?
Clean up Operator resources

### What needs fixing?
Typo in (mutatingwebhoookconfigurations contains three letters 'o'):
oc delete mutatingwebhoookconfigurations/<operator-project>.servicemesh-resources.maistra.io
it should be:
oc delete mutatingwebhookconfigurations/<operator-project>.servicemesh-resources.maistra.io

**Comment by JStickler** [comment]
@FilipB , I can't find this misspelling in either the source files or in the published output.

https://docs.openshift.com/container-platform/4.4/service_mesh/service_mesh_install/removing-ossm.html#ossm-remove-cleanup_removing-ossm
