### ISSUE TITLE
[enterprise-4.2] Issue in file updating

### ISSUE THREAD

**Issue by lbohnsac** [openshift/openshift-docs#23626]
### Which section(s) is the issue in?
One Topic is completely missing!

### What needs fixing?
How to upgrade a cluster in a disconnected environment!

**Comment by mburke5678** [comment]
Closing. We are no longer updating 4.2 docs. Issue has been addressed in 4.3+.
https://docs.openshift.com/container-platform/4.3/updating/updating-restricted-network-cluster.html
