### ISSUE TITLE
[enterprise 4.5] No documentation for vSphere MachineSet configs

### ISSUE THREAD

**Issue by jomeier** [openshift/openshift-docs#23624]
Hi,

in the latest docs there is no clue about how to configure MachineSets for vSphere.

We had to reverse engineering the source code to get it up and running ...

Thanks and greetings,

Josef

**Comment by jomeier** [comment]
The docs for OpenShift 4.5 are live. And the documentation for MachineSets on vSphere is still completely missing.

**Comment by jomeier** [comment]
@maxwelldb

**Comment by maxwelldb** [comment]
@jomeier Thanks for looking! 

@kalexand-rh I think this is related to some changes you merged in over the last few days. Am I right?

**Comment by jomeier** [comment]
Any news?

**Comment by maxwelldb** [comment]
@jomeier Hi! This is still in Kathryn's queue. She should be able to take a look soon.

**Comment by jomeier** [comment]
This would be nice because this important new OpenShift 4.5 feature is not documented at all.

**Comment by jomeier** [comment]
@kalexand-rh 
Any chance that this will be documented anytime soon?

**Comment by codyhoag** [comment]
@jomeier I've got this on my radar. We'll try to prioritize this since it's a clear doc gap.
