### ISSUE TITLE
[enterprise-4.4] Issue in file networking/multiple_networks/configuring-ptp.adoc

### ISSUE THREAD

**Issue by ChetHosey** [openshift/openshift-docs#23621]
### Which section(s) is the issue in?
Configuring PTP (entire page)

### What needs fixing?
This page is nested within "Multiple Networks". It doesn't seem relevant to running multiple networks. It should be a top-level item, or go in another section.

**Comment by jboxman** [comment]
@ChetHosey, agreed. Not sure how that happened; I've been planning on moving it for several weeks now, probably under hardware networks.
