### ISSUE TITLE
Documenation command issue

### ISSUE THREAD

**Issue by MohdIzhar** [openshift/openshift-docs#23681]
### Which section(s) is the issue in?

minishift --profile profile-demo minishift start
Error: unknown command "minishift" for "minishift"
Run 'minishift --help' for usage.
unknown command "minishift" for "minishift"
The command mentioned in documentation https://docs.okd.io/3.11/minishift/using/profiles.html

### What needs fixing?
command update needs to be fixed

**Comment by vikram-redhat** [comment]
@gbraad can you take a look at this?

**Comment by gbraad** [comment]
That is not what the documentation states. The user might have added an erronoeus "minishift" between the profile option and start.
The command reads:

```
$ minishift --profile [profilename] start
```

**Comment by gbraad** [comment]
![Screenshot_20200714-165520_Firefox.jpg](https://user-images.githubusercontent.com/1894/87406065-d1c00000-c5f2-11ea-95dd-47d4cdd6d517.jpg)

**Comment by gbraad** [comment]
Took another look, it is in another section: https://docs.okd.io/3.11/minishift/using/profiles.html#example-workflow-profile-config

**Comment by gbraad** [comment]
![Screenshot_20200714-184535_Firefox](https://user-images.githubusercontent.com/1894/87417087-3f275d00-c602-11ea-86fc-5b543898377a.jpg)

**Comment by gbraad** [comment]
@kowen can you have a look at this?

**Comment by gbraad** [comment]
Resolved in both upstream and downstream. Thanks @kowen

**Comment by jboxman** [comment]
@gbraad, if this is fixed, I'll close this. Thanks.

**Comment by gbraad** [comment]
Done
