### ISSUE TITLE
[enterprise-4.2] Issue in file applications/quotas/quotas-setting-per-project.adoc

### ISSUE THREAD

**Issue by aelgendy** [openshift/openshift-docs#23692]
### Which section(s) is the issue in?

Cluster Administration or Application section

### What needs fixing?
The 4.x doc is missing the `Setting Limit Ranges` section,  similar to 3.11 docs: https://docs.openshift.com/container-platform/3.11/admin_guide/limits.html

**Comment by aelgendy** [comment]
@maxwelldb Could you please check the missing docs belongs to which section and assign the labels/issue accordingly?  Thanks

**Comment by maxwelldb** [comment]
@aelgendy The 3 -> 4 transition is before my time, but some investigation makes me believe that content similar to what's contained on Setting Limit Ranges has been worked into the 4.x docs in different ways. For example: 

- https://docs.openshift.com/container-platform/4.4/rest_api/schedule_and_quota_apis/limitrange-core-v1.html
- https://docs.openshift.com/container-platform/4.4/nodes/clusters/nodes-cluster-overcommit.html
- https://docs.openshift.com/container-platform/4.4/applications/deployments/managing-deployment-processes.html#deployments-setting-resources_deployment-operations
- https://docs.openshift.com/container-platform/4.4/metering/configuring_metering/metering-common-config-options.html

Is there a particular question that you're trying to answer with the 4.x docs that you can't, or are you looking for a page close to what you linked that you can point to?

FYI @vikram-redhat

**Comment by aelgendy** [comment]
Thanks Max, I went through the links provided above and unfortunately this doesn't address my point, so on a project you can /or rather/ you should (_as a best practice_) specify a Project quota (act on project level) and limit range (for the compute resources in the project like, pods,containers,imagestream ...etc.) 

In v4.2 which I'm using there's no "oc create" command specifically for limit ranges like it does for resource quotas. The only alternative is to use YAML or JSON files. For this reason I need the example of a YAML file like it used to be in [ 3.11](https://docs.openshift.com/container-platform/3.11/admin_guide/limits.html) to define the resources If I would be only depending on 4.2 docs without searching older docs!

The Metering config links above serve a different resource type/different purpose it's not the YAML example of limitranges resource type.

**Comment by maxwelldb** [comment]
Thanks for the thoughtfulness! I'm going to investigate this a bit more and then get back to you.

**Comment by maxwelldb** [comment]
Also, would this be more like what you're looking for? @aelgendy 

https://docs.openshift.com/container-platform/4.5/applications/quotas/quotas-setting-per-project.html

**Comment by aelgendy** [comment]
Thanks @maxwelldb for investigating this further, the example of the quota settings above is good, and we should have similar explanation (YAML examples) for the limit range after that section indeed.

I understand that 4.2 is now EOL, but wouldn't it make sense (_as this is a working feature still in 4.2 for customers still using 4.2.x_) to have the docs consistent accord different versions? Not listing it _to me at least_ looks like Resource doesn't exist in 4.2 but the version after.

**Comment by maxwelldb** [comment]
Thanks! We're still looking into this.

**Comment by mburke5678** [comment]
The [Setting Limit Range topic](https://docs.openshift.com/container-platform/4.7/nodes/clusters/nodes-cluster-limit-ranges.html) was added back to the 4.x docs in PR: https://github.com/openshift/openshift-docs/pull/23778
