### ISSUE TITLE
[online] Issue in file getting_started/basic_walkthrough.adoc

### ISSUE THREAD

**Issue by SeanClosson** [openshift/openshift-docs#23722]
### Which section(s) is the issue in?
Creating a New Application

### What needs fixing?
Skipped steps between 2 and 3.  In Step 2, after creating a new project and naming it, the walkthrough skips navigating to Workloads from the Overview page and clicking "add other content" then selecting "From Git" or whichever option is desired.

**Comment by vikram-redhat** [comment]
@sfortner-RH @lamek ^
