### ISSUE TITLE
[enterprise-4.5] Issue in file virt/about-virt.adoc

### ISSUE THREAD

**Issue by 2s1ddhant** [openshift/openshift-docs#23721]
### Which section(s) is the issue in?
All the links in OpenShift Virtualization section redirect to the same URL ie _https://docs.openshift.com/container-platform/4.5/virt/about-virt.html_

### What needs fixing?
Expected redirection of sections to their correct links.

**Comment by vikram-redhat** [comment]
This is expected. It will redirect to the correct docs once OpenShift Virtualization is GA.
