### ISSUE TITLE
[dedicated] Issue in file administering_a_cluster/dedicated-admin-role.adoc

### ISSUE THREAD

**Issue by madhusudanupadhyay** [openshift/openshift-docs#23809]
### Which section(s) is the issue in?

[Logging in and verifying permissions
](https://docs.openshift.com/dedicated/4/administering_a_cluster/dedicated-admin-role.html#dedicated-admin-logging-in-verifying-permissions_dedicated-administrator)

### What needs fixing?
Just a typo it seems:
`You can log in as an OpenShift Dedicated cluster administration via the web console or CLI, just as you would if you were an application developer.`

`administration --> administrator`

**Comment by wgordon17** [comment]
@lamek FYI

**Comment by vikram-redhat** [comment]
@sfortner-RH No QE required.
