### ISSUE TITLE
Document \A template parameter generator expression modifier (ASCII symbols)

### ISSUE THREAD

**Issue by yrro** [openshift/openshift-docs#23903]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.5/openshift_images/using-templates.html#templates-writing-parameters_using-templates

### What needs fixing?
The `\A` modifier expands to ACSII symbols:

https://github.com/openshift/library-go/blame/master/pkg/template/generator/expressionvalue.go#L98

It's not documented.

It is mentioned in https://access.redhat.com/solutions/5231811.

**Comment by EricPonvelle** [comment]
Commenting.
