### ISSUE TITLE
[enterprise-4.5] Issue in file installing/installing_vsphere/installing-vsphere-installer-provisioned.adoc

### ISSUE THREAD

**Issue by mallmen** [openshift/openshift-docs#23921]
### Which section(s) is the issue in?
DNS requirements

### What needs fixing?
Need to clarify what the requirements are.  The table implies that api and *.apps need to resolve to an existing load balancer.  For an IPI install, there is no requirement to have an external load balancer.  The doc should clearly state that the IPs for api and *.apps are just DNS entries for an IP with no connection to an existing load balancer.

**Comment by itewk** [comment]
i think it would be helpful to have some details on how the IPs will float around using keapplived and etc. maybe some step about how to verify the A/AAAA is configured correctly. that it resolves, to an IP, but that IP isn't assigned anywhere.

**Comment by lautou** [comment]
Should be great to explain how load balancing is implemented in IPI. We are talking about keepalived. Is this keepalived created by the IPI installer?

**Comment by mallmen** [comment]
Yes, the IPI installer installs and configured haproxy and keepalived

**Comment by itewk** [comment]
@lautou ideally making the entry in the table more clear that only the `A`/`AAAA` record needs to be created (it mentions `cname` as option too, probably should explain what the use case there would be cuz I don't get that one. And then also like some sort of appendix or something with a pritty picture of what haproxy and keepalived are doing moveing the floating VIP around.

**Comment by lautou** [comment]
By the way. How haproxy and keepalived installation is implemented? Does the IPI installer create a dedicated VM for these two components (how many)? The documentation is mute on that aspect.
Also what about api-int VIP load-balacing? I don't see if a VIP is created for this internal API traffic url.

**Comment by mallmen** [comment]
haproxy and keepalived are implemented as system containers, not full vms.  Some of the details can be found here.  https://github.com/openshift/installer/blob/master/docs/design/baremetal/networking-infrastructure.md
