### ISSUE TITLE
[enterprise-4.5] Issue in file nodes/scheduling/nodes-scheduler-node-selectors.adoc

### ISSUE THREAD

**Issue by sudarshan-uc** [openshift/openshift-docs#23979]
Bugzilla:
https://bugzilla.redhat.com/show_bug.cgi?id=1859050

### Which section(s) is the issue in?

Point 2. last command. Need Modification to the following section:

Procedure:
2. Edit a node or MachineSet to add labels:

To label a MachineSet:
~~~
$ oc label MachineSet abc612-msrtw-worker-us-east-1c type=user-node region=east
~~~

### Fix:

Procedure:
2. Edit a node or MachineSet to add labels:

To label the node managed by a MachineSet:
~~~
$ oc label MachineSet opatch machineset <machineset name> --type='json' -p='[{"op":"add","path":"/spec/template/spec/metadata/labels", "value":{"type":"user-node","region":"east"}}]'
~~~

### Additional information:
This issue needs to be fixed for all the versions of OCP 4.x

**Comment by vikram-redhat** [comment]
Since we are now tracking this in the BZ as well, I am going to close this issue. Thanks for filing this @sudarshan-uc
