### ISSUE TITLE
[dedicated] Issue in file dev_guide/pod_autoscaling.adoc

### ISSUE THREAD

**Issue by PriyankaKanthale** [openshift/openshift-docs#24002]
### Which section(s) is the issue in?

[Pod Autoscaling](https://docs.openshift.com/dedicated/3/dev_guide/pod_autoscaling.html)

### What needs fixing?

Using REST API, HPA  creation is mentioned. However, pod autoscaling section missing details: 

- Understanding horizontal pod autoscalers
- Supported metrics
- Creating a horizontal pod autoscaler for CPU utilization
- Creating a horizontal pod autoscaler object for memory utilization
- Understanding horizontal pod autoscaler status conditions
- Viewing horizontal pod autoscaler status conditions
- Additional resources

Similar provided in [OCP 3.11](https://docs.openshift.com/container-platform/3.11/dev_guide/pod_autoscaling.html)  and [OSD 4](https://docs.openshift.com/dedicated/4/nodes/pods/nodes-pods-autoscaling.html#additional-resources) documentation.

**Comment by vikram-redhat** [comment]
@wgordon17 are those missing sections correct for Dedicated docs?

@lamek

**Comment by wgordon17** [comment]
I would leave out the "Requirements for Using Horizontal Pod Autoscalers" and "Autoscaling for Memory Utilization" sections, but otherwise LGTM to include 👍🏻
