### ISSUE TITLE
[dedicated] Issue in file nodes/jobs/nodes-nodes-jobs.adoc

### ISSUE THREAD

**Issue by PriyankaKanthale** [openshift/openshift-docs#24001]
### Which section(s) is the issue in?

[Using Jobs and DaemonSet ](https://docs.openshift.com/dedicated/4/nodes/jobs/nodes-nodes-jobs.html)

### What needs fixing?

Section missing: 
- Overview of DaemonSet 
- How to create a DaemonSet 

Example : As given in[OSD 3 documentation](https://docs.openshift.com/dedicated/3/dev_guide/daemonsets.html)

**Comment by vikram-redhat** [comment]
@lamek was this deliberately removed from OSD 4 docs? IF not, could you add them back?
