### ISSUE TITLE
[enterprise-4.5] Issue in file monitoring/monitoring-your-own-services.adoc

### ISSUE THREAD

**Issue by christianh814** [openshift/openshift-docs#24106]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.5/monitoring/monitoring-your-own-services.html#enabling-monitoring-of-your-own-services_monitoring-your-own-services

### What needs fixing?

The verbiage on the doc makes it seem like the `cluster-monitoring-config` should already be there. It's not

```
$ oc -n openshift-monitoring get configmap cluster-monitoring-config
Error from server (NotFound): configmaps "cluster-monitoring-config" not found
```

^ this is a fresh 4.5.2 install. If the user needs to create it, it should be stated. Having `oc edit` there makes it seem like it should be there already.

**Comment by VeerMuchandi** [comment]
Documentation is incorrect. The configmap cluster-monitoring-config should be created as it doesnt exist by default.
