### ISSUE TITLE
[enterprise-4.5] Issue in file machine_management/creating-infrastructure-machinesets.adoc

### ISSUE THREAD

**Issue by germanparente** [openshift/openshift-docs#24129]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.5/machine_management/creating-infrastructure-machinesets.html#infrastructure-moving-registry_creating-infrastructure-machinesets

### What needs fixing?

it seems that the object to get/edit is not:

oc get config/cluster -o yaml
oc edit config/cluster

But instead

oc get configs.imageregistry.operator.openshift.io cluster -o yaml
oc edit configs.imageregistry.operator.openshift.io cluster

**Comment by garbagego** [comment]
Indeed it's always good practice to access CR using group FQDN
[PR](https://github.com/openshift/openshift-docs/pull/24305)

**Comment by sheriff-rh** [comment]
@garbagego and @germanparente  , 

Thanks for filing this issue and the pull request; it made my job easy :) 

I've merged and confirmed these changes are now live on the Customer Portal and on docs.openshift.com: 
https://access.redhat.com/documentation/en-us/openshift_container_platform/4.5/html-single/machine_management/index#infrastructure-moving-registry_creating-infrastructure-machinesets
https://docs.openshift.com/container-platform/4.5/machine_management/creating-infrastructure-machinesets.html#infrastructure-moving-registry_creating-infrastructure-machinesets

I will close this issue at this time. Thanks again!

**Comment by ctauchen** [comment]
Closes BZ 1860063: https://bugzilla.redhat.com/show_bug.cgi?id=1860063
