### ISSUE TITLE
[dedicated] Issue in file nodes/pods/nodes-pods-using.adoc

### ISSUE THREAD

**Issue by PriyankaKanthale** [openshift/openshift-docs#24149]
### Which section(s) is the issue in?

Managing Security Context Constraints in OSD 4 

### What needs fixing?

In the documentation of OSD4 the entire Security Context Constraints (SCC) is missing. 

As provided in [OSD 3](https://docs.openshift.com/dedicated/3/admin_guide/manage_scc.html)

**Comment by vikram-redhat** [comment]
@wgordon17 if you could confirm it applies in dedicated, @sfortner-RH can add it in.

**Comment by wgordon17** [comment]
From: https://docs.openshift.com/container-platform/4.4/authentication/managing-security-context-constraints.html

Leave off the "Creating Security Context Constraints" section, but otherwise LGTM 👍🏻

**Comment by mburke5678** [comment]
@sfortner-RH Can this issue be closed?
