### ISSUE TITLE
[enterprise-4.5] Issue in file welcome/index.adoc.  Missing article on Integrating External Services

### ISSUE THREAD

**Issue by alberttwong** [openshift/openshift-docs#24207]
OCP 3.x used to have a article on "Integrating External Services".  This page is missing in OCP 4.x.

**Comment by jboxman** [comment]
This is: https://docs.openshift.com/container-platform/3.11/dev_guide/integrating_external_services.html

**Comment by alberttwong** [comment]
There isn't a 4.x version of that page.

**Comment by jboxman** [comment]
@alberttwong, yes, I pasted that there so it's clear what content this issue refers to.
