### ISSUE TITLE
[enterprise-4.4] Issue in file networking/openshift_sdn/assigning-egress-ips.adoc

### ISSUE THREAD

**Issue by lbohnsac** [openshift/openshift-docs#24209]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.4/networking/openshift_sdn/assigning-egress-ips.html#nw-egress-ips-static_egress-ips

### What needs fixing?
In Step2 the explanation of the red mark1 reads "Specify the name of the project" ... that's wrong!
It should read "Specify the name of the node"!

This has to be fixed in ALL versions 4.1 - 4.5!

**Comment by jboxman** [comment]
@lbohnsac, fixed.
