### ISSUE TITLE
[enterprise-4.5] Issue in file installing/installing_bare_metal/installing-bare-metal.adoc

### ISSUE THREAD

**Issue by varungur** [openshift/openshift-docs#24211]
### Which section(s) is the issue in?
Installing a cluster on bare metal --> Configuring a three-node cluster

### What needs fixing?
This statement "This provides smaller, more resource efficient clusters for cluster administrators and developers to use for deployment, development, and testing." needs to be updated to include the word "Production" since this feature is GAd with 4.5 release.

**Comment by jboxman** [comment]
@bmcelvee fyi
