### ISSUE TITLE
[enterprise-4.5] Issue in file release_notes/ocp-4-5-release-notes.adoc

### ISSUE THREAD

**Issue by varungur** [openshift/openshift-docs#24210]
### Which section(s) is the issue in?
Release Notes --> New Features and Enhancements --> Three-node bare metal deployments

### What needs fixing?
This statement "This provides smaller, more resource-efficient clusters for deployment, development, and testing." needs to be updated to mention that this feature is ready for "Production" since it's been GAd in this release.

**Comment by jboxman** [comment]
@bmcelvee fyi

**Comment by ahardin-rh** [comment]
Fixed in https://github.com/openshift/openshift-docs/pull/25999. Thank you!
