### ISSUE TITLE
[dedicated] Issue in file openshift_images/images-understand.adoc

### ISSUE THREAD

**Issue by madhusudanupadhyay** [openshift/openshift-docs#24239]
### Which section(s) is the issue in?
[Using Images section](https://docs.openshift.com/dedicated/4/openshift_images/images-understand.html)

### What needs fixing?
[Setting Up a Nexus Mirror for Maven](https://docs.openshift.com/dedicated/3/dev_guide/dev_tutorials/maven_tutorial.html) section was available for OSD3 but is missing in OSD4

Please disregard in case this was intentional.

**Comment by madhusudanupadhyay** [comment]
@lamek , just an fyi. Thanks.

**Comment by vikram-redhat** [comment]
I believe this is intentional. @wgordon17 can you confirm? If no, @lamek can we add it?

**Comment by wgordon17** [comment]
Yes, intentional. @madhusudanupadhyay Is there a customer attempting to do this on v4?
