### ISSUE TITLE
Add section explaining resources, limits, requests in the Deployment/DeploymentConfig docs

### ISSUE THREAD

**Issue by InfoSec812** [openshift/openshift-docs#24308]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.5/applications/deployments/what-deployments-are.html#deployments-and-deploymentconfigs_what-deployments-are

### What needs fixing?

We should have a link to the details of the embedded pod template or more detailed documentation explaining how to create the pod template and configuration settings which are allowed (e.g. resources/limits/requests/etc...)

**Comment by germanparente** [comment]
Hi,

any possibility to treat this issue. I have an internal customer that is interested to have this fixed. Would it help if I create a bugzilla ?

Thanks.
