### ISSUE TITLE
[dedicated] Issue in file web_console/odc-about-developer-perspective.adoc

### ISSUE THREAD

**Issue by madhusudanupadhyay** [openshift/openshift-docs#24336]
### Which section(s) is the issue in?

OSD4 [Developer Guide](https://docs.openshift.com/dedicated/4/web_console/odc-about-developer-perspective.html)

### What needs fixing?

OSD3 had the mention of [Integrating External Services](https://docs.openshift.com/dedicated/3/dev_guide/integrating_external_services.html) which is missing from OSD4 as above. 

PTAL and let me know in case I am missing or overlooking any information already provided.

**Comment by vikram-redhat** [comment]
@wgordon17 I am pretty sure this is removed intentionally. Let me know if you disagree. 

@sfortner-RH

**Comment by wgordon17** [comment]
This is a valid thing to include in v4 OSD docs 👍🏻
