### ISSUE TITLE
[dedicated] Issue in file authentication/using-service-accounts-in-applications.adoc

### ISSUE THREAD

**Issue by madhusudanupadhyay** [openshift/openshift-docs#24337]
### Which section(s) is the issue in?

[Using Service accounts in Applications in OSD4
](https://docs.openshift.com/dedicated/4/authentication/using-service-accounts-in-applications.html)

### What needs fixing?

OSD3 had [Managing Allowed Secrets](https://docs.openshift.com/dedicated/3/dev_guide/service_accounts.html#managing-allowed-secrets)
and [Using Service account's credentials inside a container](https://docs.openshift.com/dedicated/3/dev_guide/service_accounts.html#using-a-service-accounts-credentials-inside-a-container) section which is missing from OSD4 as mentioned above. 

Also, need to confirm if this is something done as a matter of design. 

Thanks

**Comment by vikram-redhat** [comment]
@wgordon17 again, I am pretty sure this is intentional, but if not, @sfortner-RH if you can conditionally add it back.

**Comment by sfortner-RH** [comment]
@wgordon17 I'll wait for you to ack this. I'm not clear on the history of this content or why it was removed. Let me know if I need to add it back. Thanks!

**Comment by wgordon17** [comment]
Yes, this should be added in, thanks 👍🏻
