### ISSUE TITLE
Add Bahrain to supported AWS regions

### ISSUE THREAD

**Issue by walidshaari** [openshift/openshift-docs#24442]
### Which section(s) is the issue in?

https://docs.okd.io/latest/installing/installing_aws/installing-aws-account.html#installation-aws-regions_installing-aws-account
docs.okd.io lates, installing aws account/ supported aws regions(installation-aws-regions_installing-aws-account)
### What needs fixing?

Add Middle-East-South-1 Bahrain to the supported regions 

I was able to install with no quota issues to "me-south-1" OKD4.5
```
[2:23 PM] [walid@Bei-win okd]$ ./oc get nodes
NAME                                          STATUS   ROLES    AGE     VERSION
ip-10-0-131-164.me-south-1.compute.internal   Ready    worker   3h1m    v1.18.3
ip-10-0-149-9.me-south-1.compute.internal     Ready    master   3h14m   v1.18.3
ip-10-0-169-150.me-south-1.compute.internal   Ready    master   3h14m   v1.18.3
ip-10-0-185-167.me-south-1.compute.internal   Ready    worker   3h1m    v1.18.3
ip-10-0-221-225.me-south-1.compute.internal   Ready    worker   3h1m    v1.18.3
ip-10-0-223-117.me-south-1.compute.internal   Ready    master   3h15m   v1.18.3
```

![image](https://user-images.githubusercontent.com/1757428/89299309-234a3080-d66f-11ea-97da-032635691fa4.png)

**Comment by ahardin-rh** [comment]
@walidshaari Thank you! We will work to get this added.

**Comment by walidshaari** [comment]
I saw it is already added 3 months ago, sorry, false issue

**Comment by ahardin-rh** [comment]
@walidshaari Well, thanks for contacting us!
