### ISSUE TITLE
[enterprise-4.3] Issue in file authentication/understanding-and-creating-service-accounts.adoc

### ISSUE THREAD

**Issue by arizon-dread** [openshift/openshift-docs#24441]
### Which section(s) is the issue in?

I tried using the search bar to find "service accounts", the result yielded nothing. I proceeded to google "openshift 4.3 service accounts" to find it. 

### What needs fixing?

The search function doesn't seem to find parts of the documentation that's actually there.

**Comment by jboxman** [comment]
@vikram-redhat FYI

**Comment by arizon-dread** [comment]
This works now, it was a temporary problem. Closing the issue.
