### ISSUE TITLE
[enterprise-4.5] [Feature] OpenShift-Docs Site to default Latest rather than a specific version

### ISSUE THREAD

**Issue by GrooveCS** [openshift/openshift-docs#24484]
### Which section(s) is the issue in?
Permalink URL to access the latest resource rather then the specific version. 

![odo architecture - Developer CLI (odo) _ CLI tools _ OpenShift Container Platform 4 5](https://user-images.githubusercontent.com/1635152/89417494-c1380c80-d6fc-11ea-955e-d88e424d43dc.jpg)

### What needs fixing?

1. The default permalink should be the latest version
1. The user has the option to use a specific version if relevant to a specific use-case. 
1. The archive versions should provide permalink to the current relevant information.

**Comment by vikram-redhat** [comment]
@GrooveCS 

Hey there,

We do have the 'latest' tag. 

So, you can use: https://docs.openshift.com/container-platform/latest/welcome/index.html and that will take you to the latest version, which right now, is 4.5. So it will go to: https://docs.openshift.com/container-platform/4.5/welcome/index.html.

IF I am understanding what you are asking for.
