### ISSUE TITLE
pods-per-core documentation

### ISSUE THREAD

**Issue by jeremyeder** [openshift/openshift-docs#2455]
https://github.com/kubernetes/kubernetes/pull/25813#issuecomment-221380650

And ... if you have say, 100 pods running on a node, and you REDUCE the max-pods to, say 80...kubernetes will kill (random?) 20 pods.  So we want to explicitly note this, as well as recommend that a node be evacuated if max-pods is being reduced.

**Comment by jeremyeder** [comment]
we're going to file a separate issue.

**Comment by jeremyeder** [comment]
In OpenShift 3.3.1, the default number of pods that can be run on a node (```max-pods```) will change from a static integer to a sliding scale based on the number of CPU cores available to the node.

By default, the OpenShift installer will set ```pods-per-core=10``` and ```max-pods=250```.

This table describes the effective ```max-pods``` value for certain node sizes:

| pods-per-core and max-pods | # CPU cores | Effective max-pods |
| --- | --- | --- |
| 10, 250 | 2 | 20 |
| 10, 250 | 8 | 80 |
| 10, 250 | 16 | 160 |
| 10, 250 | 32 | 250 |

Both pods-per-core and max-pods are configurable when using the Advanced Installer or post-install.

You can verify the capacity of a node as follows:

```
# oc describe node <node_name>
<snip>
Capacity:
 alpha.kubernetes.io/nvidia-gpu:        0
 cpu:                                   4
 memory:                                16004788Ki
 pods:                                  40
```

**Comment by jeremyeder** [comment]
This BZ is slated for 3.3.1:  https://bugzilla.redhat.com/show_bug.cgi?id=1371309

@adellape @ahardin-rh

**Comment by jeremyeder** [comment]
https://github.com/openshift/origin/pull/11174

**Comment by bfallonf** [comment]
The above docs PR covers this. Closing this issue.
