### ISSUE TITLE
Setting up a cluster: confusing references to VM operation

### ISSUE THREAD

**Issue by owtaylor** [openshift/openshift-docs#2457]
"If you wish to run the server from a Windows or Mac OS X host, you should download and run the Origin Vagrant image as described in Method 3."

Method 3 is titled "Building from source" and has a broken link to a document that apparently was about how to build OpenShift Origin from source using a vagrant machine.

Presumably what users should be directed to if they want to stat using a VM is https://www.openshift.org/vm/ ?

**Comment by mburke5678** [comment]
@stevekuznetsov The link that Owen is talking about, I think, went to a section in the _Contributing to OpenShift_ document (https://github.com/openshift/origin/blob/master/CONTRIBUTING.adoc#develop-on-virtual-machine-using-vagrant). 

You removed the section in a commit here:
https://github.com/openshift/origin/commit/7fc5091c811436acc52e43ddcd521587dabb0a28#diff-bf6c05f66a41e4a8d614764c22eaf178

What should we change the link to? Or remove Method 3?
"Method 3: Building from Source
You can build OpenShift Origin from source locally or using Vagrant. See the OpenShift Origin repository on GitHub **for instructions**."

**Comment by stevekuznetsov** [comment]
@mburke5678 I'll take a look, thanks
