### ISSUE TITLE
[enterprise-4.5] Issue in file installing/installing_vsphere/installing-vsphere-installer-provisioned.adoc

### ISSUE THREAD

**Issue by LucianoRed** [openshift/openshift-docs#24587]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.5/installing/installing_vsphere/installing-vsphere-installer-provisioned.html#installation-vsphere-installer-infra-requirements_installing-vsphere-installer-provisioned

### What needs fixing?
The instructions do not include the  Datastore.FileManagement (Low level file operations) permission, so, in order to dynamic and static vsphere volume provisioning it would be necessary to have those permissions. 
Source: https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/vcp-roles.html 
--

**Comment by codyhoag** [comment]
This was resolved in #25782
