### ISSUE TITLE
Setting up a cluster: registry creation missing service account

### ISSUE THREAD

**Issue by owtaylor** [openshift/openshift-docs#2458]
I tried the 'oadm registry' command under "Trying it out" on the "Setting up a cluster" page, and got an error message because there was no service account for the registry. I had to look at:

https://docs.openshift.org/latest/install_config/install/docker_registry.html

to figure out what to do.

**Comment by adellape** [comment]
This doesn't seem to be an issue any longer with the latest build, though I had to use `oc adm` instead of `oadm` (used the "Downloading the Binary" method):

```
# oc adm registry
--> Creating registry registry ...
    serviceaccount "registry" created
    clusterrolebinding "registry-registry-role" created
    deploymentconfig "docker-registry" created
    service "docker-registry" created
--> Success
```

Updating command via https://github.com/openshift/openshift-docs/pull/5339.
