### ISSUE TITLE
Setting up a cluster: oc tag doesn't work

### ISSUE THREAD

**Issue by owtaylor** [openshift/openshift-docs#2459]
In https://docs.openshift.org/latest/getting_started/administrators.html the example command:

   oc tag deployment-example:v2 deployment-example:latest

Fails with:

error: "deployment-example:v2" is not currently pointing to an image, cannot use it as the source of a tag

I had luck with:

oc tag --source=docker openshift/deployment-example:v2 deployment-example:latest

Its possible that the tag command might work as specified if the import-image command was modified?

**Comment by willm** [comment]
related to https://github.com/openshift/origin/issues/8359

**Comment by mburke5678** [comment]
Closing. See fix in https://github.com/openshift/openshift-docs/pull/4929
