### ISSUE TITLE
browser requirements are out of date

### ISSUE THREAD

**Issue by danmcp** [openshift/openshift-docs#2461]
https://docs.openshift.org/latest/architecture/infrastructure_components/web_console.html#browser-requirements

Not a single item listed isn't horribly out of date:

Windows 8, ipad 2, iphone 4 and macOSX (is now just macOS).  Even Fedora should be 24 now.  But I am not sure what good this list really does.  If it's going to be out of date this quickly, perhaps we should just remove it.

**Comment by danmcp** [comment]
@adellape @vikram-redhat FYI

**Comment by vikram-redhat** [comment]
@danmcp - I agree. We should just remove it. I will get it removed soon.

**Comment by adellape** [comment]
@danmcp @vikram-redhat This was originally added not that long ago via https://bugzilla.redhat.com/show_bug.cgi?id=1322352 and https://github.com/openshift/openshift-docs/pull/1874, requested by GSS. It looks like the table was based on the support matrix from QE: https://mojo.redhat.com/docs/DOC-1013063. Maybe that needs to get updated? But agree that this table will be easy to get out of date on.

cc @ahardin-rh

**Comment by danmcp** [comment]
@vikram-redhat @adellape Can we move it to the release notes or some other place.  I know it isn't right for windows/iphone/ipad versions.  And macOS was just renamed.  It was correct for the Fedora version but isn't like we aren't going to support it on the latest Fedora now that it's out.  If we have to put it somewhere then so be it.  But given how off the messaging is from reality, it's only going to confuse people.  No one is going to see that list and say thank you for letting me know my ipad 2 is supported.

**Comment by vikram-redhat** [comment]
@danmcp I believe this was correct at the time of publishing for 3.2. This is what had been tested by QE, as opposed to what will work, and I think matters most to support.

I think the solution might be to add this to the release notes, as you suggest, for that particular version to say that this version of OpenShift has been tested with these OS/Browser settings.

Asking for @sferich888 's input.

**Comment by sferich888** [comment]
Sounds good to me. That is what we say on the tested configuration matrix.

**Comment by bfallonf** [comment]
Thanks @danmcp I've created a PR for this:

https://github.com/openshift/openshift-docs/pull/2889

I'll close this issue and if there's anything to say, we can move the conversation to there.
