### ISSUE TITLE
"Configuring kube-proxy" is inaccurate / out of date

### ISSUE THREAD

**Issue by danwinship** [openshift/openshift-docs#24676]
### Which section(s) is the issue in?
"Configuring kube-proxy", eg, https://docs.openshift.com/container-platform/4.5/networking/openshift_sdn/configuring-kube-proxy.html

### What needs fixing?

1. There is no reason anyone should ever change `iptablesSyncPeriod` any more in 4.3 or later. It used to be the case that setting this to a larger-than-default-value would improve performance on large clusters, but this is no longer true. (You now get the "improved" level of performance regardless of the value of `iptablesSyncPeriod`.) The only thing that `iptablesSyncPeriod` controls now is how long it takes kube-proxy to recover from certain errors.

   If we have 3.11-to-4.x upgrade docs, then it is worth mentioning there that you no longer need to override this value in 4.x. I'm not sure if it's worth having something in _this_ doc (or anywhere else), since all it would be saying is "don't touch this"...

2. The default value for `iptables-min-sync-period` is not `30s`, it's `0s`, which means that kube-proxy will always try to update iptables as soon as anything changes. Any non-`0` value means that it will wait at least `iptables-min-sync-period` between updates, so the docs are right about that part, they're just not describing the default behavior correctly. This is true for all releases (including 3.11 though I'm not sure sure what we say about `iptables-min-sync-period` there...).

**Comment by jboxman** [comment]
@danwinship, I can certainly try to push for the removal of `iptablesSyncPeriod` through our change control process, but it'll need sign-offs from support and other places.
