### ISSUE TITLE
[enterprise-4.5] Issue in file logging/cluster-logging-deploying.adoc

### ISSUE THREAD

**Issue by syedriko** [openshift/openshift-docs#24712]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.5/logging/cluster-logging-deploying.html#cluster-logging-deploy-console_cluster-logging-deploying
2. Install the Cluster Logging Operator

### What needs fixing?
The namespace in  "You must select this option to ensure that cluster monitoring scrapes the openshift-operators-redhat namespace." should be openshift-logging

**Comment by mburke5678** [comment]
https://github.com/openshift/openshift-docs/pull/25053
