### ISSUE TITLE
[enterprise-4.4] Issue in file nodes/nodes/nodes-nodes-managing.adoc

### ISSUE THREAD

**Issue by ehashman** [openshift/openshift-docs#24726]
### Which section(s) is the issue in?

Bad link in file nodes/nodes/nodes-nodes-managing.adoc

### What needs fixing?

Link to "KubeletConfig options" hardcodes Kubernetes branch 1.11, which is many major releases behind OpenShift 4.4.

**Comment by mburke5678** [comment]
@ehashman Thanks for your comment. Making the change: https://github.com/openshift/openshift-docs/pull/25055
Let me know if you think the new link makes sense.
