### ISSUE TITLE
[enterprise-4.5] Issue in file rest_api/project_apis/projectrequest-project-openshift-io-v1.adoc

### ISSUE THREAD

**Issue by SirTediousOfFoo** [openshift/openshift-docs#24733]
### Which section(s) is the issue in?

First word of the **Description** paragraph.

### What needs fixing?

Typo in the first word says "ProjecRequest" should be fixed to "ProjectRequest"

**Comment by jboxman** [comment]
@SirTediousOfFoo, thanks for filing this. The docs are auto-generated, so probably needs to be fixed elsewhere, maybe in OCP api repo.

**Comment by jboxman** [comment]
Fix: https://github.com/openshift/api/pull/814

**Comment by jboxman** [comment]
@SirTediousOfFoo thanks for reporting this.
