### ISSUE TITLE
[enterprise-4.5] Issue in file nodes/nodes/nodes-nodes-working.adoc

### ISSUE THREAD

**Issue by davivcgarcia** [openshift/openshift-docs#24777]
### Which section(s) is the issue in?

This [part](https://docs.openshift.com/container-platform/4.5/nodes/nodes/nodes-nodes-working.html#nodes-nodes-working-master-schedulable_nodes-nodes-working): 

"In version 4.5, the ability to create a cluster that does not have worker nodes is available to only clusters that are deployed on bare metal as a technology preview. For all other cluster types, you can set the masters to be schedulable but must retain worker nodes."

### What needs fixing?

According to [release notes](https://docs.openshift.com/container-platform/4.5/release_notes/ocp-4-5-release-notes.html#ocp-4-5-technology-preview) this feature is already GA on 4.5.

**Comment by mburke5678** [comment]
@davivcgarcia Thanks for pointing this out. Please see my changes in https://github.com/openshift/openshift-docs/pull/25050
