### ISSUE TITLE
Disconnected installation instruction for 'createrepo' clobbers repodata for all but the last repo.

### ISSUE THREAD

**Issue by georgegoh** [openshift/openshift-docs#2495]
Step 5 in the section 'Syncing Repositories' (https://github.com/openshift/openshift-docs/blob/master/install_config/install/disconnected_install.adoc#disconnected-syncing-repos)

Shows:
````
# for repo in \
rhel-7-server-rpms rhel-7-server-extras-rpms \
rhel-7-server-ose-3.2-rpms
do
  reposync --gpgcheck -lm --repoid=${repo} --download_path=/path/to/repos
  createrepo -v </path/to/repos/>${repo}
done
````

By default, the `createrepo` command will dump the repodata in the current directory unless the `-o` option is specified, clobbering all but the last processed repodata.

Suggest to change this line to:

`createrepo -v </path/to/repos/>${repo} -o </path/to/repos/>${repo}`

**Comment by adellape** [comment]
cc @bfallonf

**Comment by bfallonf** [comment]
@georgegoh Thanks very much for that. I created the fix in the PR above.
