### ISSUE TITLE
Need to document multi AZ volume scheduling

### ISSUE THREAD

**Issue by danmcp** [openshift/openshift-docs#2497]
As was implemented here:

https://trello.com/c/33kShOjC/
https://github.com/kubernetes/kubernetes/pull/17916

Need to explain how it works (including mentioning dynamic provisioning) and if it's enabled by default.

**Comment by danmcp** [comment]
@DirectXMan12 @ncdc FYI

**Comment by ncdc** [comment]
Depends on https://github.com/openshift/origin/pull/9822 merging first

**Comment by ncdc** [comment]
There's nothing about this specific to dynamic provisioning. I assume you're referring to the fact that this only works with PVs & PVCs?

**Comment by danmcp** [comment]
@ncdc Just that if you make a claim for something that is dynamically provisioned, it will be provisioned in the right AZ.

**Comment by bfallonf** [comment]
@danmcp @ncdc I've created a BZ for this in order to track for, hopefully, the next release:

https://bugzilla.redhat.com/show_bug.cgi?id=1378309

We'll work from there, so I'll close this issue. Thanks!
