### ISSUE TITLE
[dedicated] Issue in file logging/dedicated-cluster-deploying.adoc

### ISSUE THREAD

**Issue by squirrd** [openshift/openshift-docs#24981]
### Which section(s) is the issue in?
There a few issues in a few sections on this page.

### What needs fixing?

- You have an info bubble that states `When you deploy an instance of the Cluster Logging Operator, it also deploys an instance of the Elasticsearch Operator.`.   But then the documentation starts by deploying elasticsearch.  I think the quoted buble is incorrect, as you DO need to install elasticsearch first. It isn't auto deployed.

- There is an option to choose the `Update Channel`.  This defaults to the highest available even though the cluster might be on a lower version level.  This can cause issues with mismatched features.  This should be documented as a step when installing elasticsearch and cluster logging.  This new step should be added at 1.d.  and 2.d.  

- 4.a to 4.d needs to be re-worded as the names of the tabs and other web objects have changed.

- Also in section 4. there are now tabs for `Log Forwarding` and `Log Collector` as well as `cluster logging`, which have their own Custom Resources, these should also be documented; most likely on a separate page.

**Comment by mburke5678** [comment]
@lamek Is this still in your purview?

**Comment by mburke5678** [comment]
> You have an info bubble that states When you deploy an instance of the Cluster Logging Operator, it also deploys an instance of the Elasticsearch Operator.

This refers to the custom resource objects. When you create the Cluster Logging CR, the CLO creates the Elasticsearch CR. We can remove this sentence for clarity. Step 4d states that deploy the logging instance _creates the Cluster Logging and Elasticsearch Custom Resources_. This statement should be sufficient. 

> Update Channel should be documented as a step when installing elasticsearch and cluster logging. 

Good point. The OCP logging install states the version to select. _Select 4.6 as the Update Channel._ However, I just checked. In OCP 4.6 the Update Channel is set and cannot be changed. (My account doesn't have quota to bring up a Dedicated cluster so I cannot verify.)

> 4.a to 4.d needs to be re-worded as the names of the tabs and other web objects have changed.

This step is for creating the cluster logging CR. In OCP 4.6, you cannot create the CR through the *Installed Operators* page as described. (My account doesn't have quota to bring up a Dedicated cluster so I cannot verify.)

> there are now tabs for Log Forwarding and Log Collector as well as cluster logging, which have their own Custom Resources

It appears that configuring Log Forwarding and the log collector are not allowed in Dedicated.  (My account doesn't have quota to bring up a Dedicated cluster so I cannot verify.)

@sfortner-RH Can you look into @squirrd concerns?

**Comment by mburke5678** [comment]
@sfortner-RH Is Dedicated your area?
