### ISSUE TITLE
[dedicated] Issue in file support/getting-support.adoc

### ISSUE THREAD

**Issue by mmurphy** [openshift/openshift-docs#25003]
### Which section(s) is the issue in?
Getting Support (https://docs.openshift.com/dedicated/4/support/getting-support.html)

### What needs fixing?
* The `Page History` navigation, at the top, links to (https://github.com/openshift/openshift-docs/commits/enterprise-3.11/support/getting-support.adoc), which does not exist.
* The `Open an issue` navigation links to GitHub new issue, however the text in the page says
   > If you have a suggestion for improving this documentation or have found an error, please submit a Bugzilla report

   It should be consistent, either GitHub issues or Bugzilla.

**Comment by jboxman** [comment]
fyi @sheriff-rh

**Comment by bergerhoffer** [comment]
Hi @mmurphy, can this issue be closed, with #28314 being merged? Thanks!

**Comment by mmurphy** [comment]
Hi @bergerhoffer, the merge only fixes one part of the issue (maybe I should have created seperate issues but it initially seemed straightforward when I opened the issue)
The "Open an issue" link at the top of the page (and every other page) seems inconsistent with the instruction at the bottom of this page `If you have a suggestion for improving this documentation or have found an error, please submit a Bugzilla report`
I think the Bugzilla instructions should be replaced with instructions to use the "Open an issue" link.
If you think so I can make a PR with alternative text.
wdyt?

**Comment by bergerhoffer** [comment]
@mmurphy thanks, I see your second issue now. So we definitely support both GitHub issue and BZ issues, but Bugzilla really is our preferred method for submitting an issue. 

But really, the main factor is that our docs are both on docs.openshift.com and on the Customer Portal. So when viewing these docs from the portal [1], the "Open an issue" link isn't an option. So the the "Open an issue" link is provided more just as a convenience to make it easy for people to open an issue quickly, when viewing from docs.openshift.com. So we wouldn't be able to replace this text as you've requested. Does that make sense?

[1] https://access.redhat.com/documentation/en-us/openshift_dedicated/4/html/support/getting-support#support_getting-support

**Comment by mmurphy** [comment]
@bergerhoffer Yes, that makes sense give the different publishing routes.
