### ISSUE TITLE
[enterprise-4.5] Issue in file installing/installing_vsphere/installing-vsphere-installer-provisioned.adoc

### ISSUE THREAD

**Issue by therevoman** [openshift/openshift-docs#25015]
### Which section(s) is the issue in?
VSphere service account permissions section.

### What needs fixing?
While provisioning with a barebones service account my client ran across an issue with permissions.  
Seems a clarification is needed regarding this error:

Error: error reconfiguring virtual machine: error processing disk changes post-clone: disk.0: ServerFaultCode: NoPermission: RESOURCE (vm-996:2000), ACTION (queryAssociatedProfile): RESOURCE (vm-996), ACTION (PolicyIDByVirtualDisk)

Seems the fix is in the last comment
https://github.com/hashicorp/terraform-provider-vsphere/issues/974#issuecomment-609814731
In the vSphere 6.7 UI, the permission is found under Profile-driven storage -> Profile-driven storage view, not Storage views

**Comment by therevoman** [comment]
Client used this link to fix their service-account
https://github.com/hashicorp/terraform-provider-vsphere/issues/966

**Comment by kalexand-rh** [comment]
@therevoman, the docs currently say that you must grant all privileges for Profile-driven storage: https://docs.openshift.com/container-platform/4.5/installing/installing_vsphere/installing-vsphere-installer-provisioned.html#installation-vsphere-installer-infra-requirements_installing-vsphere-installer-provisioned

I don't see a mention of the Storage view on that page, so I'm closing this issue. If you have more information that can help me make a different change, please reopen the issue with it.
