### ISSUE TITLE
[enterprise-4.5] Issue in file logging/config/cluster-logging-log-store.adoc

### ISSUE THREAD

**Issue by pucher1983** [openshift/openshift-docs#25028]
### Which section(s) is the issue in?

A code template in paragraf 7 of the section 'Performing an Elasticsearch rolling cluster restart', 

### What needs fixing?

I guess it should be 

$ oc exec <any_es_pod_in_the_cluster> -c elasticsearch -- es_util --query=_cluster/settings -XPUT 'https://localhost:9200/_cluster/settings' -d '{ "transient": { "cluster.routing.allocation.enable" : "all" } }'

instead of

$ oc exec <any_es_pod_in_the_cluster> -c elasticsearch -- es_util --query=_cluster/settings -XPUT 'https://localhost:9200/_cluster/settings' -d '{ "transient": { "cluster.routing.allocation.enable" : "none" } }'

I.e. "all" instead of "none"

**Comment by jboxman** [comment]
@mburke5678 fyi

**Comment by mburke5678** [comment]
@pucher1983 
I am working on updating this topic in https://github.com/openshift/openshift-docs/pull/22465. 
Does this address your concerns?
