### ISSUE TITLE
[enterprise-4.5] Issue in file machine_management/adding-rhel-compute.adoc

### ISSUE THREAD

**Issue by rhdojun** [openshift/openshift-docs#25070]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.5/machine_management/adding-rhel-compute.html#installation-approve-csrs_adding-rhel-compute

### What needs fixing?
It would be good if the approval step first shows how to review a CSR before approving it and maybe link to an external explanation about how CSR approval works in general for people who care about understanding it more in-depth.

**Comment by lbarbeevargas** [comment]
@rhdojun  Thank you for submitting this issue. After conversing with the engineers for our OCP Cloud team, it looks like Step #2 covers the key things to look out for when reviewing a CSR before approval:

> Review the pending CSRs and ensure that you see a client and server request with the `Pending` or `Approved` status for each machine that you added.

Specifically, review that the status for each machine is `Pending` or `Approved`. I am adding a link to the Kubernetes (upstream) documentation with more information on CSRs. The OCP 4.2 documentation is no longer supported, so this update will be reflected in the 4.3+ documentation.

4.5 OCP Documentation: https://docs.openshift.com/container-platform/4.5/machine_management/user_infra/adding-rhel-compute.html#installation-approve-csrs_adding-rhel-compute
