### ISSUE TITLE
[enterprise-4.5] Issue in file security/container_security/security-network.adoc

### ISSUE THREAD

**Issue by hupiper** [openshift/openshift-docs#25135]
### Which section(s) is the issue in?
First paragraph

### What needs fixing?
It looks like you are missing a letter. Third sentence, allowing an rejecting should probably be allowing and rejecting.

Network security can be managed at several levels. At the pod level, network namespaces can prevent containers from seeing other pods or the host system by restricting network access. Network policies give you control over **allowing an rejecting** connections. You can manage ingress and egress traffic to and from your containerized applications.

**Comment by kcclemo** [comment]
I can work on this.

**Comment by bergerhoffer** [comment]
Closing as the related PR has been merged!
