### ISSUE TITLE
[enterprise-4.5] Issue in file installing/install_config/installing-restricted-networks-preparations.adoc

### ISSUE THREAD

**Issue by matmille** [openshift/openshift-docs#25153]
### Which section(s) is the issue in?
In "Configuring credentials that allow images to be mirrored", the use of the command "oc registry login" fails unless a ~/.kube/config file or KUBECONFIG environment variable exists.

Unless the user has a kubeconfig; which would be provided by a login - they receive the following error:
error: Missing or incomplete configuration info.  Please login or point to an existing, complete config file:

  1. Via the command-line flag --config
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

To view or setup config directly use the 'config' command.

### What needs fixing?
Utilize a different command that does not require kubeconfig or create a template ~/.kube/config file ....

apiVersion: v1
clusters:
- cluster:
    server: https://localhost
  name: example
contexts:
- context:
    cluster: example
    namespace: example
    user: example
  name: example
current-context: example
kind: Config
preferences: {}
users:
- name: example
  user:
    token: example

**Comment by kalexand-rh** [comment]
@matmille, thanks for pointing this out! We've fixed this here: https://github.com/openshift/openshift-docs/pull/25833

Please reopen the issue with more information if you're still having this issue. Thanks!
