### ISSUE TITLE
[dedicated] Issue in file welcome/index.adoc

### ISSUE THREAD

**Issue by madhusudanupadhyay** [openshift/openshift-docs#25155]
### Which section(s) is the issue in?

Missing information on Service Mesh Supportability

### What needs fixing?

We need to update the OpenShift Dedicated 4 docs to highlight that [OpenShift Online and OpenShift Dedicated are not supported for Red Hat OpenShift Service Mesh 1.1.7](https://docs.openshift.com/container-platform/4.5/service_mesh/servicemesh-release-notes.html#ossm-supported-configurations_ossm-release-notes).

**Comment by lbarbeevargas** [comment]
@madhusudanupadhyay Can you please confirm if the docs update needs to reflect that OpenShift Online and OpenShift Dedicated are not supported for _both_ Service Mesh 1.1.7 and 1.1.8? Or that the current documentation is incorrect and the note should be `1.1.7` and not `1.1.8`, thank you. Current note:

> OpenShift Online and OpenShift Dedicated are not supported for Red Hat OpenShift Service Mesh 1.1.8.

**Comment by knrc** [comment]
No version of Service Mesh supports Dedicated/Online at this time, we will be qualifying a version on those platforms post-2.0 release.

**Comment by lbarbeevargas** [comment]
@knrc Would this update apply to the 4.3 and later versions of the OCP docs?

**Comment by lbarbeevargas** [comment]
PR #25990 closes this issue.
