### ISSUE TITLE
[enterprise-4.5] Issue with supported values of no_proxy for cluster-proxy on installation

### ISSUE THREAD

**Issue by masayag** [openshift/openshift-docs#25195]
### Which section(s) is the issue in?
In https://github.com/openshift/openshift-docs/blob/master/modules/installation-configure-proxy.adoc
The description of 'noProxy' field contains 'Use * to bypass proxy for all destinations'
However, when setting noProxy to '*' and trying to generate ignition files, action fails with:
```
openshift-install --dir no_proxy_star create ignition-configs
FATAL failed to fetch Kubeconfig Admin Client: failed to load asset "Install Config": invalid "install-config.yaml" file: NoProxy: Invalid value: "*": must be a CIDR or domain, without wildcard characters
```

Also on the installer side, '*' isn't mentioned as a supported value: https://github.com/openshift/installer/blob/4c69c591a34ceac5fd18b13c975442b3192c5f09/data/data/install.openshift.io_installconfigs.yaml#L1576

IIUC, There is a difference between configuring the proxy on installation time which doesn't allow to set noProxy with '*' to the configuration of the Proxy element on an installed cluster as described in https://github.com/openshift/openshift-docs/blob/master/modules/nw-proxy-configure-object.adoc in which it is allowed.

### What needs fixing?
Omit the part of 'Use * to bypass proxy for all destinations' from noProxy description in https://github.com/openshift/openshift-docs/blob/master/modules/installation-configure-proxy.adoc

**Comment by masayag** [comment]
Issue seems to exist on 4.6 as well.

**Comment by bergerhoffer** [comment]
Closing as PR #25201 has been merged.
