### ISSUE TITLE
[online] Issue in file welcome/index.adoc

### ISSUE THREAD

**Issue by michaelshire** [openshift/openshift-docs#25211]
### Which section(s) is the issue in?
<Search>

### What needs fixing?
The search function seems to be broken.  Returns no results for a generic term like "openshift".

**Comment by jboxman** [comment]
@michaelshire, is it still broken? It is working for me with _openshift_:

<img width="1184" alt="Screen Shot 2020-09-02 at 12 55 03 PM" src="https://user-images.githubusercontent.com/354496/92013323-994bc100-ed1b-11ea-961c-52aa30f16ef6.png">

**Comment by michaelshire** [comment]
> @michaelshire, is it still broken? It is working for me with _openshift_:
> 
>

The issue I found is specific to the ARO4 docs:
https://docs.openshift.com/aro/4/welcome/index.html

**Comment by jboxman** [comment]
@vikram-redhat, is search intended to work for ARO4 docs? It returns empty results right now.

**Comment by michaelshire** [comment]
> @vikram-redhat, is search intended to work for ARO4 docs? It returns empty results right now.

bump

**Comment by vikram-redhat** [comment]
Sorry, I missed this.

@jiri-fiala - could we include ARO distributions for search?
