### ISSUE TITLE
[dedicated] Issue in file applications/projects/working-with-projects.adoc

### ISSUE THREAD

**Issue by PriyankaKanthale** [openshift/openshift-docs#25278]
### Which section(s) is the issue in?

[Working with the Projects](https://docs.openshift.com/dedicated/4/applications/projects/working-with-projects.html)

### What needs fixing?

OSD 4 documentation does not contain application back up steps as it is provided in https://docs.openshift.com/dedicated/3/admin_guide/assembly_backing-up-restoring-project-application.html

**Comment by vikram-redhat** [comment]
@bergerhoffer this would not apply to a Dedicated cluster? @wgordon17

**Comment by bergerhoffer** [comment]
@vikram-redhat If I'm remembering correctly, I believe that this was a known gap. As in, we didn't convert the day 2 operations content from 3 -> 4. However, I know that @ahardin-rh just added in that post-install section to 4.x, but as far as I'm aware, it's mostly a collection of existing documentation into one place. And less of converting what was in the day 2 guide from 3.x to 4.x (though please correct me if I'm wrong about this). 

So I'm not sure where this all stands today.

**Comment by wgordon17** [comment]
Yeah, this is actually a _great_ doc to include in OSD docs 👍🏻

**Comment by vikram-redhat** [comment]
@sfortner-RH can you work with @bergerhoffer and @ahardin-rh on this? If the content in the new post-install section can now apply for a version 4 dedicated cluster, we should be able to use it.

**Comment by bergerhoffer** [comment]
@vikram-redhat Just to be clear, we're talking about two different versions here. 3.11 has steps for project and application backups, but 4.x does not at all (not OCP and not dedicated). @ahardin-rh can confirm, but I don't believe that the post-install content that was recently added added in anything for this. 

So this isn't necessarily a dedicated-only issue. Perhaps the new post-install section could apply to dedicated too, but I think that's a separate issue. Even if that was added to dedicated, it doesn't not include application backup, as is requested by this issue (if I understand correctly).

**Comment by vikram-redhat** [comment]
@bergerhoffer ok, I misread when you said that "However, I know that @ahardin-rh just added in that post-install section to 4.x" that we did add some of the project backup and restore content in. :) 

Let me work with Stephanie to see if we can schedule this in.

@PriyankaKanthale this will take a little while.

**Comment by bergerhoffer** [comment]
@vikram-redhat Yes I could definitely have worded that better sorry :)
