### ISSUE TITLE
[dedicated] Issue in file logging/cluster-logging.adoc

### ISSUE THREAD

**Issue by madhusudanupadhyay** [openshift/openshift-docs#25291]
### Which section(s) is the issue in?

Information about the level of access for the logging stack. 

### What needs fixing?

It would be worth while to add in the docs:
- dedicated admins do not have access to cluster level logs. 
- dedicated admins can view logs of *all* the customer workload project in the cluster 
- searchguard plugin in ES leverages the user's rbac in-cluster to determine what projects and therefore which indexes the users have access to. 
- Customer should never see operations logs but only the logs for projects in which they have access to pod logs already.
- It would also help if Information on Audit logs are available to the customer on the official docs. 

Information around the above is mentioned in:
  [+] https://access.redhat.com/articles/4660601#logging

**Comment by lamek** [comment]
Thanks for spotting this. We carded this work in Jira here - https://issues.redhat.com/browse/OSDOCS-1473
