### ISSUE TITLE
Informational command would be helpful for multitenant 

### ISSUE THREAD

**Issue by Jooho** [openshift/openshift-docs#2534]
From https://docs.openshift.com/enterprise/3.1/install_config/configuring_sdn.html#migrating-between-sdn-plugins, it explains how to migrate from ovs-subnet to the ovs-multitenant but user can not check it is applied well without log checking.

" oc get netnamespaces " show net id which each project use so I believe it is useful command to check changed plugin.

**Comment by ahardin-rh** [comment]
Addressed in https://github.com/openshift/openshift-docs/pull/2891
