### ISSUE TITLE
[enterprise-4.5] Edit suggested in file installing/installing_aws/installing-aws-default.adoc

### ISSUE THREAD

**Issue by eponafyrefly** [openshift/openshift-docs#25395]
### Which section(s) is the issue in?
Installing a cluster quickly on AWS.
https://docs.openshift.com/container-platform/4.5/installing/installing_aws/installing-aws-default.html#installing-aws-default

### What needs fixing?
This line under Prerequisites has a typo:
"If you do not allow the system to manage identity and access management (IAM), then a cluster administrator can **can** manually create and maintain IAM credentials."

**Comment by jboxman** [comment]
@eponafyrefly, thanks!
