### ISSUE TITLE
[enterprise-4.5] Issue in file installing/installing_vsphere/installing-vsphere.adoc

### ISSUE THREAD

**Issue by amelie1979** [openshift/openshift-docs#25403]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.3/installing/installing_vsphere/installing-vsphere.html#registry-configuring-storage-vsphere_installing-vsphere

https://docs.openshift.com/container-platform/4.5/post_installation_configuration/storage-configuration.html#vsphere-definition_post-install-storage-configuration

https://docs.openshift.com/container-platform/4.5/registry/configuring_registry_storage/configuring-registry-storage-vsphere.html#registry-configuring-storage-vsphere_configuring-registry-storage-vsphere

### What needs fixing?
We should add a note that NFS is not recommend for production, like everywhere else in the doc.

----Statement to reuse about NFS Warning (Therefore, using RHEL NFS to back PVs used by core services is not recommended.)
https://docs.openshift.com/container-platform/4.5/scalability_and_performance/optimizing-storage.html#specific-application-storage-recommendations

**Comment by kalexand-rh** [comment]
I'm adding the note to these topics:

https://docs.openshift.com/container-platform/4.3/installing/installing_vsphere/installing-vsphere.html#registry-configuring-storage-vsphere_installing-vsphere

https://docs.openshift.com/container-platform/4.5/registry/configuring_registry_storage/configuring-registry-storage-vsphere.html#registry-configuring-storage-vsphere_configuring-registry-storage-vsphere

The note is already in the third topic, and I think it makes more sense where it is. https://docs.openshift.com/container-platform/4.5/post_installation_configuration/storage-configuration.html#vsphere-definition_post-install-storage-configuration
