### ISSUE TITLE
[dedicated] Issue in file networking/openshift_sdn/configuring-egress-firewall.adoc

### ISSUE THREAD

**Issue by madhusudanupadhyay** [openshift/openshift-docs#25441]
### Which section(s) is the issue in?

https://docs.openshift.com/dedicated/4/networking/openshift_sdn/configuring-egress-firewall.html

### What needs fixing?

The docs mention that cluster admin is required to make changes and create egress network policy. On the contrary:

$ oc adm policy who-can create egressnetworkpolicy -n dedicated-admin | grep -A100 ^Group
Groups: dedicated-admins
        osd-sre-cluster-admins
        system:cluster-admins
        system:masters
        system:serviceaccounts:dedicated-admin

The above group has users that can create the policies which also includes dedicated-admins.

**Comment by jboxman** [comment]
@sheriff-rh, do I need to add a conditional for OSD for this? It's probably true for `NetworkPolicy` as well.

**Comment by sheriff-rh** [comment]
@jboxman a conditional seems likely, but you may want to confirm with @lamek since that's his wheelhouse.

**Comment by jboxman** [comment]
@madhusudanupadhyay, thanks for reporting this!

**Comment by jboxman** [comment]
I'll need to apply this fix to the entirety of networking, I think, in _4.3_+.
