### ISSUE TITLE
[enterprise-4.5] Issue in file updating/updating-restricted-network-cluster.adoc

### ISSUE THREAD

**Issue by pamoedom** [openshift/openshift-docs#25471]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.5/updating/updating-restricted-network-cluster.html#update-oc-configmap-signature-verification_updating-restricted-network-cluster

### What needs fixing?

[Google Cloud Storage (GCS)](https://storage.googleapis.com/openshift-release/official/signatures) link is broken, please review.

**Comment by jboxman** [comment]
@LalatenduMohanty, do you know what the correct link is for this now or who to ask?

Thanks!

**Comment by LalatenduMohanty** [comment]
The link is correct, how ever GCS does not support directory listing , refer https://github.com/openshift/openshift-docs/pull/21993#discussion_r424696542

**Comment by kalexand-rh** [comment]
The user doesn't have enough information to use the curl statement in https://github.com/openshift/openshift-docs/pull/21993#discussion_r424696542 without getting it from mirror.openshift.com, so I'm going to remove the link. @LalatenduMohanty, @wking, if you think that this is a mistake or have a better way to do it, please let me know.

**Comment by pamoedom** [comment]
Then the removal of that link makes sense, thanks.

**Comment by LalatenduMohanty** [comment]
> Then the removal of that link makes sense, thanks.

+1
