### ISSUE TITLE
[enterprise-4.5] Issue in file nodes/pods/nodes-pods-secrets.adoc

### ISSUE THREAD

**Issue by kanekoh** [openshift/openshift-docs#25475]
### Which section(s) is the issue in?

There are different versions of service serving certificate annotation on the OCP 4.4 and 4.5 documentation. I believed that "service.beta.openshift.io/serving-cert-secret-name" is the correct version on OCP 4.4 and 4.5.

\As the section "Generating signed certificates for use with secrets", the annotation name for Service Serving Certificate is "service.alpha.openshift.io/serving-cert-secret-name"

However, the following document shows different annotation name.
https://docs.openshift.com/container-platform/4.4/security/certificates/service-serving-certificate.html#add-service-certificate_service-serving-certificate

"service.beta.openshift.io/serving-cert-secret-name"

### What needs fixing?

The annotation name "service.beta.openshift.io/serving-cert-secret-name" may be the correct name. So Please fix the name in the document.

**Comment by jonquilwilliams** [comment]
I did a search for "service.alpha.openshift.io" in the 4.4 and 4.5 versions of the documentation and am not finding "alpha". I see only Beta. I believe this is no longer an issue because it got fixed somehow, perhaps by a duplicate issue.

**Comment by jboxman** [comment]
@jonquilwilliams, I just happened to have left this in my inbox. I did find _alpha_ in the _master_ branch locally:

```
/Users/jasonb/Self/work/openshift-docs/modules/builds-service-serving-certificate-secrets.adoc
  13,12: * Set the `service.alpha.openshift.io/serving-cert-secret-name` annotation on your service with the value set to the name you want to use for your secret.

/Users/jasonb/Self/work/openshift-docs/modules/configuring-dynamic-admission.adoc
  260,7:       service.alpha.openshift.io/serving-cert-secret-name: server-serving-cert

/Users/jasonb/Self/work/openshift-docs/modules/monitoring-exposing-custom-application-metrics-for-horizontal-pod-autoscaling.adoc
  147,5:     service.alpha.openshift.io/serving-cert-secret-name: prometheus-adapter-tls

/Users/jasonb/Self/work/openshift-docs/modules/nodes-pods-secrets-certificates-about.adoc
  25,7:       service.alpha.openshift.io/serving-cert-secret-name: registry-cert<1>

/Users/jasonb/Self/work/openshift-docs/modules/nodes-pods-secrets-certificates-creating.adoc
  9,6: the `service.alpha.openshift.io/serving-cert-secret-name` annotation, then add the secret to the pod.
  17,12: . Add the `service.alpha.openshift.io/serving-cert-secret-name` annotation
  27,7:       service.alpha.openshift.io/serving-cert-secret-name: my-cert <1>
```

**Comment by jonquilwilliams** [comment]
Opened PR: https://github.com/openshift/openshift-docs/pull/26009 to fix this. After QE, please merge to master and CP to 4.4.and 4.5. Thanks!
