### ISSUE TITLE
[enterprise-4.5] Issue in file machine_management/creating-infrastructure-machinesets.adoc

### ISSUE THREAD

**Issue by Koma-Andrea** [openshift/openshift-docs#25472]
### Which section(s) is the issue in?
The components identified to be scheduled on infra nodes should also contain the accessory product that the customer could already have a subscription on. 
Or else RH is selling double subscriptions on components which normally  shouldn't happen.

### What needs fixing?
The list should (IMHO) comprehend 

- Quay (that maybe nominating it in the docs could spark some attention)
- 3Scale (the ctrl plane part)
- OCS
- Kafka (doubt on this as is not infrastructural per se)
- istio (the ctrl plane part)
- ACM (when will be released)
- etc.

**Comment by Koma-Andrea** [comment]
*edited: added info per project

**Comment by codyhoag** [comment]
Updating the infra component list is in progress in #26920
