### ISSUE TITLE
[enterprise-4.5] Issue in file updating/updating-cluster-between-minor.adoc

### ISSUE THREAD

**Issue by pwright** [openshift/openshift-docs#25493]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.5/updating/updating-cluster-between-minor.html#understanding-upgrade-channels_updating-cluster-between-minor

### What needs fixing?

I'm having trouble understanding the documentation

![image](https://user-images.githubusercontent.com/5154224/93238094-e21e6380-f778-11ea-91cd-4df1257837bf.png)

The doc says:
"Upgrade channels are tied to a minor version of OpenShift Container Platform. For instance, OpenShift Container Platform 4.5 upgrade channels will never include an upgrade to a 4.5 release. "

**Comment by codyhoag** [comment]
@pwright thanks for pointing this out. It's currently being worked on in #25307 and should be fixed soon.
