### ISSUE TITLE
Origin "m4" docs redirect to "latest" docs

### ISSUE THREAD

**Issue by tiwillia** [openshift/openshift-docs#2550]
The Origin m4 docs appear to be inaccessible. The drop down on https://docs.openshift.org/index.html has two links, "Origin m4" -> "origin-m4/index.html" and "Origin Latest" -> "latest/index.html". Both of these links lead to https://docs.openshift.org/latest/welcome/index.html

**Comment by adellape** [comment]
cc @nhr per recent discussion on updating the drop-down for Origin docs.

**Comment by tiwillia** [comment]
Due to this, pages like the cartridge developers guide http://docs.openshift.org/origin-m4/oo_cartridge_developers_guide.html are completely inacessible.

**Comment by adellape** [comment]
We ended up removing the M4 docs from the site entirely via https://github.com/openshift/openshift-docs/pull/2819. The source is still available via https://github.com/openshift/origin-server/tree/master/documentation.
