### ISSUE TITLE
[enterprise-4.5] Issue in file logging/cluster-logging-deploying.adoc

### ISSUE THREAD

**Issue by squirrd** [openshift/openshift-docs#25539]
### Which section(s) is the issue in?
In both
Procedure -> 1. Install the Elasticsearch Operator:->  Click Subscribe.
Procedure -> 2.Install the Cluster Logging Operator: -> Click Subscribe.

### What needs fixing?

The button is now `Install` not `Subscribe`

**Comment by jboxman** [comment]
@mburke5678 FYI

**Comment by mburke5678** [comment]
https://github.com/openshift/openshift-docs/pull/25567

**Comment by mburke5678** [comment]
@squirrd Thanks for catching this!!
