### ISSUE TITLE
[enterprise-4.5] Issue in file logging/config/cluster-logging-log-store.adoc

### ISSUE THREAD

**Issue by zene22** [openshift/openshift-docs#25538]
### Which section(s) is the issue in?

The yaml that is provided in https://docs.openshift.com/container-platform/4.5/logging/config/cluster-logging-log-store.html#cluster-logging-elasticsearch-audit_cluster-logging-store (Forward audit logs to the log store) contains a wrong address for the elastic search cluster.

### What needs fixing?

The endpoint parameter points to the internal Elasticsearch instance: 
`endpoint: 'elasticsearch-cluster.openshift-logging.svc:9200'`

but this should read
`endpoint: 'elasticsearch.openshift-logging.svc:9200'`

**Comment by jboxman** [comment]
@mburke5678 FYI

**Comment by mburke5678** [comment]
Thanks for catching this! This is possibly an endpoint used by QE, as I got the code sample from a QE engineer.
