### ISSUE TITLE
Issue in file /installing/installing_vsphere

### ISSUE THREAD

**Issue by DustinTrap** [openshift/openshift-docs#25540]
### Which section(s) is the issue in?

Section "Required vCenter account privileges" on https://docs.openshift.com/container-platform/4.5/installing/installing_vsphere/installing-vsphere-installer-provisioned.html#installation-vsphere-installer-infra-requirements_installing-vsphere-installer-provisioned 

### What needs fixing?

Required vCenter account privileges is incomplete based on customer testing with a non-administrator account. Specific failures were encountered when attempting to automatically provision a PV to satisfy a PVC. See attached imaged for the corrected permissions that do allow for automatic provisioning of the PVs as a VMWare vmdk file in the preselected datastore.

![image](https://user-images.githubusercontent.com/12038788/93471094-e5bd0200-f8c0-11ea-94fd-0b9d004c2fa8.png)

**Comment by DustinTrap** [comment]
Also tracking here: https://bugzilla.redhat.com/show_bug.cgi?id=1879959

**Comment by vikram-redhat** [comment]
Closing in favor of the bug.
