### ISSUE TITLE
[enterprise-4.5] Issue in file installing/installing_rhv/installing-rhv-customizations.adoc -- dns_vip missing

### ISSUE THREAD

**Issue by funixz** [openshift/openshift-docs#25579]
### Which section(s) is the issue in?
In the sample configs and in the requirements, the dns_vip is missing.
https://docs.openshift.com/container-platform/4.5/installing/installing_rhv/installing-rhv-customizations.html#installing-rhv-installation-configuration-parameters_installing-rhv-customizations

### What needs fixing?
dns_vip is a required string and IP according to the upstream documentation. 
https://github.com/openshift/installer/blob/release-4.5/docs/user/ovirt/customization.md

**Comment by kalexand-rh** [comment]
@rolfedh, PTAL?

**Comment by rolfedh** [comment]
Support for the dns_vip was removed in OCP 4.5 per https://bugzilla.redhat.com/show_bug.cgi?id=1842280
The upstream developer's notes (e.g., this topic) should to be updated to reflect this change. @rgolangh

**Comment by rolfedh** [comment]
@kalexand-rh This issue does not affect openshift/openshift-docs. It should be migrated to openshift/installer.
