### ISSUE TITLE
ca-bundler.crt should be ca-bundle.crt in secret for logging forward api

### ISSUE THREAD

**Issue by git001** [openshift/openshift-docs#25612]
### Which section(s) is the issue in?

Understanding the Log Forwarding API
https://github.com/openshift/openshift-docs/blob/master/modules/cluster-logging-log-forwarding-about.adoc

### What needs fixing?

The secret key does not match the template in the code.

Code: https://github.com/openshift/cluster-logging-operator/blob/release-4.6/pkg/generators/forwarding/fluentd/templates.go#L596
`tls_cert_path {{ .SecretPath "ca-bundle.crt"}}`

Doc:

```
An output supports TLS communication using a secret. Secrets must have keys of: tls.crt, tls.key, 
and ca-bundler.crt which point to the respective certificates for which they represent. Secrets 
must have the key shared_key for use when using forward in a secure manner.
```

I also suggest to add the info that the secret must be in the namespace **openshift-logging**

In the code template is the key not in use because of `#` at the beginning of the line.
https://github.com/openshift/cluster-logging-operator/blob/release-4.6/pkg/generators/forwarding/fluentd/templates.go#L594

**Comment by mburke5678** [comment]
@git001 Thanks for catching this!

4.6 changes: https://github.com/openshift/openshift-docs/issues/25612
4.5 changes: https://github.com/openshift/openshift-docs/pull/25900
