### ISSUE TITLE
Configuring block registry storage for VMware vSphere

### ISSUE THREAD

**Issue by leethomasrh** [openshift/openshift-docs#25610]
Please expand this section to include examples for the pvc creation and also include steps necessary to set the registry to a Managed state.

The order of these steps is very important when configuring block storage for the registry in vSphere because the customer doesn't see the difference and sees the NFS examples above and tries to use that PVC yaml example which doesn't work with the thin storage class that dynamically provisions storage in vSphere.

### Which section(s) is the issue in?
Procedure

### What needs fixing?
Keep the patch step as step number one.  Please expand steps two and three.  Please add a fourth step.

Step 2 should include the steps from this document section (https://docs.openshift.com/container-platform/4.5/storage/persistent_storage/persistent-storage-vsphere.html#vsphere-dynamic-provisioning-cli_persistent-storage-efs )with the following changes.
Change one - the pvc name must be image-registry-storage
Change two - the size must be 100Gi

Step 3 should include these steps: - same as step 4b in this document with one change to the claim: line (bolded below) - https://docs.openshift.com/container-platform/4.5/registry/configuring_registry_storage/configuring-registry-storage-vsphere.html

"Add the name of your PVC:
(in a code block) 
$ oc edit configs.imageregistry.operator.openshift.io -o yaml
(in a second code block)
storage:
  pvc:
    **claim:**  "

Add a step 4 to change the registry to Managed: - same as the bullet point in this section of the document - https://docs.openshift.com/container-platform/4.5/registry/configuring_registry_storage/configuring-registry-storage-vsphere.html#registry-change-management-state_configuring-registry-storage-vsphere

**Comment by bobfuru** [comment]
Thanks, @leethomasrh! I've created https://github.com/openshift/openshift-docs/pull/25941 if you would like to have a look.

**Comment by bobfuru** [comment]
PR merged and now published here: https://docs.openshift.com/container-platform/4.6/registry/configuring_registry_storage/configuring-registry-storage-vsphere.html#installation-registry-storage-block-recreate-rollout_configuring-registry-storage-vsphere
