### ISSUE TITLE
[enterprise-3.11] Issue in file admin_guide/node_problem_detector.adoc

### ISSUE THREAD

**Issue by sbuvaneshkumar** [openshift/openshift-docs#25613]
### Which section(s) is the issue in?

Customizing Detected Conditions

### What needs fixing?
"4. To display Node Problem Detector output to standard output (stdout) and standard error (stderr) add the following to the **configuration map**:"
It should be daemonset, not the configmap.
Even the example provided following the line describes the content of daemonset, not cnfigmap.

**Comment by jboxman** [comment]
This is now fixed, thanks!
