### ISSUE TITLE
[enterprise-4.5] Issue in file logging/cluster-logging-deploying.adoc

### ISSUE THREAD

**Issue by rhatbob** [openshift/openshift-docs#25619]
### Which section(s) is the issue in?
[Installing cluster logging using the CLI](https://docs.openshift.com/container-platform/4.5/logging/cluster-logging-deploying.html#cluster-logging-deploy-cli_cluster-logging-deploying)

### What needs fixing?
Step 5 @ "Procedure" should highlight in the ClusterLogging object that omission of the `.spec.logStore.elasticsearch.storage` block will result in a deployment that includes ephemeral storage only, as per [0].

[0] https://github.com/openshift/cluster-logging-operator/blob/release-4.5/docs/configuration.md#backing-storage

**Comment by mburke5678** [comment]
@rhatbob Thanks for the tip! 
https://github.com/openshift/openshift-docs/pull/25903
