### ISSUE TITLE
[enterprise-3.11] Issue in file upgrading/automated_upgrades.adoc

### ISSUE THREAD

**Issue by syedriko** [openshift/openshift-docs#25677]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/3.11/upgrading/automated_upgrades.html#upgrading-efk-logging-stack-dots
https://docs.openshift.com/container-platform/3.11/upgrading/automated_upgrades.html#upgrading-efk-logging-stack-nodots

### What needs fixing?
Prior to patching the fluentd DS, take a note of the value of its nodeSelector.
The fluentd DS patching command should look like this:
```
oc patch daemonset logging-fluentd --type=json -p '[{"op":"replace", "path":"/spec/template/spec/nodeSelector", "value": {"non-existing":"true"}}]'
```
There should be a extra step added post-upgrade in both "dots" and "no-dots" scenarios that restores the nodeSelector to what it was prior to patching.

**Comment by mburke5678** [comment]
Closing in favor of https://issues.redhat.com/browse/OSDOCS-1514
