### ISSUE TITLE
[enterprise-4.5] Extracting openshift-install If the mirror host does not have internet access

### ISSUE THREAD

**Issue by e-desouza** [openshift/openshift-docs#25710]
### Which section(s) is the issue in?

The "Creating a mirror registry for installation in a restricted network"

Specifically, this link : https://docs.openshift.com/container-platform/4.5/installing/install_config/installing-restricted-networks-preparations.html#installation-mirror-repository_installing-restricted-networks-preparations

### What needs fixing?

3. Mirror the version images to the internal container registry:
* If your mirror host does not have internet access, take the following actions: [...instructions...]
* If the local container registry is connected to the mirror host, take the following actions: [...instructions...]

4. To create the installation program that is based on the content that you mirrored, extract it and pin it to the release:
$ oc adm -a ${LOCAL_SECRET_JSON} release extract --command=openshift-install "${LOCAL_REGISTRY}/${LOCAL_REPOSITORY}:${OCP_RELEASE}-${ARCHITECTURE}"

The `-${ARCHITECTURE}` tag in step 4 isn't valid if Step 3 (a) above is followed and only valid if step 3 (b) is followed. The fix is either removing the need for `-${ARCHITECTURE}` which would break multi-arch manifest support in future, or fixing 3 (a) to force inclusion of the `-${ARCHITECTURE}` just like in 3 (b).

**Comment by kalexand-rh** [comment]
@e-desouza, I'm not seeing an instance of `${OCP_RELEASE}` in step 3a that does not also include either `-${ARCHITECTURE` or `*`. Can you please tag the line that's causing the problem: https://github.com/openshift/openshift-docs/blame/enterprise-4.5/modules/installation-mirror-repository.adoc

**Comment by kalexand-rh** [comment]
@e-desouza, will you PTAL?
