### ISSUE TITLE
proudct_title

### ISSUE THREAD

**Issue by sosiouxme** [openshift/openshift-docs#2572]
Under https://docs.openshift.com/enterprise/3.2/install_config/install/prerequisites.html#software-prerequisites under "Installing Docker" there is a typo {proudct-title}. This looks to have been a bad cherry-pick in 3.2 - this doesn't appear in master at any point.

**Comment by adellape** [comment]
:scream: :scream_cat: 

Fixed in https://github.com/openshift/openshift-docs/pull/2573 and published. Thanks!!

**Comment by ahardin-rh** [comment]
Thanks, @sosiouxme and @adellape! :sweat:
