### ISSUE TITLE
Fix typos

### ISSUE THREAD

**Issue by bergerhoffer** [openshift/openshift-docs#25785]
### What needs fixing?

The typos in this list of files:

| File  | Typo |
| ------------- | ------------- |
|storage/container_storage_interface/persistent-storage-csi-manila.adoc |installled
|modules/installation-gcp-user-infra-shared-vpc-config-yaml.adoc |the the
|modules/olm-installing-from-operatorhub-using-cli.adoc | the the
|modules/update-oc-configmap-signature-verification.adoc |the the
|modules/builds-basic-start-source.adoc | can can
|modules/installation-gcp-service-account.adoc | that that 
|modules/installation-gcp-user-infra-config-host-project-vpc.adoc | that that
|modules/olm-restricted-networks-configuring-operatorhub.adoc |that that
|modules/cluster-logging-elasticsearch-retention.adoc | than than
|modules/installation-osp-deleting-bootstrap-resources.adoc |,,
|modules/olm-deleting-operators-from-a-cluster-using-web-console.adoc | Uninistall

Marking this as a good issue for a Hacktoberfest contribution! These typos should be fixed in the master branch, and should be fixed in all supported 4.x versions as well (currently 4.3-4.6).

**Comment by lmalivert** [comment]
I'll work on the issue for Hacktoberfest.

**Comment by chikaldirick** [comment]
Since previous MRs were either closed or contained only partial changes, I've created [this one](https://github.com/openshift/openshift-docs/pull/26073) containing all changes in one place.

**Comment by bergerhoffer** [comment]
Closing this issue as the related PR was merged. Thanks!
