### ISSUE TITLE
[enterprise-4.5] Issue in file rest_api/operator_apis/operator-apis-index.adoc

### ISSUE THREAD

**Issue by vanallp** [openshift/openshift-docs#25780]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.5/rest_api/operator_apis/operator-apis-index.html

Description
Etcd provides information to configure an operator to manage kube-apiserver.

### What needs fixing?

That is wrong. 
Etcd provides information to configure an operator to manage etcd operator Not the kube-apiserver

**Comment by adellape** [comment]
This needs to be updated upstream at https://github.com/openshift/api/blob/master/operator/v1/types_etcd.go#L11

Something like: "Etcd configures the etcd-operator which manages the cluster's etcd service."

Then the CRD config can be regenerated from those changes, and the API docs can be regenerated to reflect the changes as well. I'll make a PR against upstream to address. It will probably take a bit longer after that to actually flow into the docs, however.

**Comment by jboxman** [comment]
Finally fixed this upstream.
