### ISSUE TITLE
[enterprise-4.7] Issue in file rest_api/operator_apis/etcd-operator-openshift-io-v1.adoc

### ISSUE THREAD

**Issue by vanallp** [openshift/openshift-docs#25781]
### Which section(s) is the issue in?

Description
Etcd provides information to configure an operator to manage kube-apiserver.

### What needs fixing?

Etcd provides information to configure an operator to manage etcd

**Comment by adellape** [comment]
This was previously addressed and already merged by @jboxman via https://github.com/openshift/api/pull/841.
