### ISSUE TITLE
[enterprise-4.5] Issue in file logging/cluster-logging.adoc

### ISSUE THREAD

**Issue by syedriko** [openshift/openshift-docs#25815]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.5/logging/cluster-logging.html#cluster-logging-about-logstore_cluster-logging

### What needs fixing?
syslsog

**Comment by vikram-redhat** [comment]
Not enough information. Closing.

**Comment by syedriko** [comment]
"syslsog" is a typo, it's supposed to be syslog.

**Comment by vikram-redhat** [comment]
Fix in master, CP to 4.5/4.6.

**Comment by Rohitkrops** [comment]
I would like to work on this. Let me know if I can pick it.

**Comment by mburke5678** [comment]
@syedriko Thanks!

**Comment by mburke5678** [comment]
https://github.com/openshift/openshift-docs/pull/25955
