### ISSUE TITLE
[enterprise-4.5] Issue in file applications/deployments/what-deployments-are.adoc

### ISSUE THREAD

**Issue by dpkshetty** [openshift/openshift-docs#25816]
### Which section(s) is the issue in?
Applications/Deployments /Understanding Deployments and DeploymentConfigs

### What needs fixing?
**Section - "DeploymentConfigs-specific features"**

Expectation is to get more details on DC specific features like automatic rollbacks, triggers, lifecycle hooks and custom strategies
Currently it only details what deployment has.. but doesn't say anything about the DC specific details.

For eg: Under "Triggers" it says deployment has only ConfigChange trigger, but the expectation is to know what additional triggers DC has and how they are better than what's available in deployment

**Comment by jboxman** [comment]
@dpkshetty, we'd like to encourage usage of `Deployment` as it is the upstream implementation.

**Comment by dpkshetty** [comment]
@jboxman I did not understand your point. The section says "DeploymentConfigs-specific features" so this issue is for putting better documentation for DC section

**Comment by germanparente** [comment]
Hi,

any possibility to treat this issue. I have an internal customer that is interested to have this fixed. Would it help if I create a bugzilla ?

Thanks.
