### ISSUE TITLE
[enterprise-4.5] Issue in file logging/cluster-logging.adoc

### ISSUE THREAD

**Issue by syedriko** [openshift/openshift-docs#25814]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.5/logging/cluster-logging.html#cluster-logging-about-components_cluster-logging

### What needs fixing?
In this document, this document might refer

**Comment by vikram-redhat** [comment]
Not enough information. Closing.

**Comment by syedriko** [comment]
It's a suggestion to remove duplicate "this document".

**Comment by vikram-redhat** [comment]
Fix in master, and CP to 4.5/4.6.

**Comment by Rohitkrops** [comment]
I would like to work on this. Let me know if I can pick it.

**Comment by bergerhoffer** [comment]
@Rohitkrops Sorry for the delay in responding - yes please go ahead and submit the fix for this if you're able!

Make the change against master, and we'll take care of applying it to other versions.

**Comment by Rohitkrops** [comment]
Sure, will open PR today

**Comment by rounaksarda** [comment]
@bergerhoffer please review the pull request https://github.com/openshift/openshift-docs/issues/25814

**Comment by bergerhoffer** [comment]
PR for this issue is #26697.

**Comment by bergerhoffer** [comment]
Closing as the PR has been merged!
