### ISSUE TITLE
Typos in 3.11

### ISSUE THREAD

**Issue by bergerhoffer** [openshift/openshift-docs#25828]
### What needs fixing?

The typos in this list of files in the `enterprise-3.11` branch:

| File  | Typo |
| ------------- | ------------- |
|release_notes/ocp_3_6_release_notes.adoc |Kublet (should be Kubelet)
|architecture/infrastructure_components/kubernetes_infrastructure.adoc |kublet (should be kubelet)
|dev_guide/topics/about_device_manager.adoc |Manger
|install_config/topics/ocp_osp_provisioning.adoc |file file
|servicemesh-install/topics/tutorial-rhoar-missions.adoc |are are
|servicemesh-release-notes/topics/rn-known-issues.adoc | it it (should be it is)
|servicemesh-release-notes/topics/rn-new-features.adoc |and and
|install_config/master_node_configuration.adoc |commmand
|dev_guide/managing_images.adoc | `importPolicy.insecure`` (extra ending backtick)
|install_config/router/customized_haproxy_router.adoc | `map\[string](ServiceAliasConfig)`` (extra ending backtick)
|install_config/router/customized_haproxy_router.adoc | ``[]Endpoint`  (extra beginning backtick)
|install_config/router/customized_haproxy_router.adoc | ``$cfg` (extra beginning backtick)
|install_config/router/customized_haproxy_router.adoc |``$balanceAlgo`   (extra beginning backtick)
|install_config/aggregate_logging.adoc | enviroment

Marking this as a good issue for Hacktoberfest!

**Comment by amycruz97** [comment]
can i take this

**Comment by amycruz97** [comment]
i will work on it for hacktoberfest

**Comment by bergerhoffer** [comment]
Thanks @amycruz97! This needs to be opened against the `enterprise-3.11` branch. Let me know if you have any questions along the way!

**Comment by Nitin2702** [comment]
Can I do this for my hacktoberfest?

**Comment by amycruz97** [comment]
I have forked and cloned the page
is this what i need for the setup [https://github.com/amycruz97/openshift-docs/blob/master/contributing_to_docs/tools_and_setup.adoc](url)

**Comment by maxwelldb** [comment]
@amycruz97 You're able to run asciibinder on macOS--I do it myself, sometimes. 

Are you able to `gem install ascii_binder`?

(You may want a Ruby environment manager like RVM or rbenv for working with this and other gems.)

**Comment by amycruz97** [comment]
How do i install asciibinder on mac os that's where i got stocked

**Comment by maxwelldb** [comment]
@amycruz97 If you have Ruby and RubyGems installed, you should be able to install it from the terminal as shown here: https://rubygems.org/gems/ascii_binder

**Comment by amycruz97** [comment]
alright Thanks i am working on it

**Comment by amycruz97** [comment]
i have made a pull request

**Comment by bergerhoffer** [comment]
Closing this issue as the PR was merged.
