### ISSUE TITLE
[enterprise-3.11] Issue in file install/prerequisites.adoc

### ISSUE THREAD

**Issue by ehvs** [openshift/openshift-docs#25822]
### Which section(s) is the issue in?
The URL says 'envirornment'
https://docs.openshift.com/container-platform/3.11/install/prerequisites.html#envirornment-requirements

### What needs fixing?
The spelling in the URL should be 'environment-requirements'

**Comment by maxwelldb** [comment]
@ehvs Thanks!

**Comment by maxwelldb** [comment]
@vikram-redhat Do we need to get redirects for anchor link changes?

**Comment by vikram-redhat** [comment]
Hey @maxwelldb - redirects don't work at anchor levels so nothing we can do here.

**Comment by maxwelldb** [comment]
@vikram-redhat Yeah, I didn't think we attempted anything clientside. Thanks!

**Comment by maxwelldb** [comment]
@openshift/team-documentation PTAL. Not urgent, but really quick. Thanks!
