### ISSUE TITLE
[enterprise-4.5] Issue in file operators/operator_sdk/osdk-leader-election.adoc

### ISSUE THREAD

**Issue by yashgiri** [openshift/openshift-docs#25883]
### Which section(s) is the issue in?

"Using Leader-for-life election" 

### What needs fixing?
The code example given in this section might not have been updated as the packages 'leader' and 'status' have been removed in a previous version and moved to operator-lib which is supposed to be used over here with its corresponding functions.
Reference: https://github.com/operator-framework/operator-sdk/pull/3503

**Comment by jboxman** [comment]
@adellape fyi
