### ISSUE TITLE
[enterprise-4.5] Issue in file installing/installing_vsphere/installing-vsphere-installer-provisioned.adoc

### ISSUE THREAD

**Issue by lautou** [openshift/openshift-docs#25884]
### Which section(s) is the issue in?
VMware vSphere infrastructure requirements

### What needs fixing?
NSX Operator is certified : https://catalog.redhat.com/software/operators/detail/5ef0f362701a9cb8c147cf4b
Remove these sentence : 
"Because previous versions of vSphere with NSX-T are not currently compatible with OpenShift Container Platform, NSX-T is not supported. NSX-T certification is in process and will be supported in a future release."

**Comment by kalexand-rh** [comment]
This text was adjusted on https://github.com/openshift/openshift-docs/pull/26439, so I'm closing this issue.
