### ISSUE TITLE
Truncated example command in mongodb documentation.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/openshift-docs#2594]
In:

* https://github.com/openshift/openshift-docs/blob/master/using_images/db_images/mongodb.adoc

It has example:

```
$ oc new-app -e \
    MONGODB_USER=<username>,MONGODB_PASSWORD=<password>,MONGODB_DATABASE=<database_name>,MONGODB_ADMIN_PASSWORD=<admin_password> \
```

This appears to be truncated, not actually showing the arguments after the environment variables, such as the image name.

**Comment by php-coder** [comment]
This is because GitHub couldn't process `ifdef`s correctly. Final documentation doesn't affected by this: https://docs.openshift.org/latest/using_images/db_images/mongodb.html#creating-the-service-pod
