### ISSUE TITLE
ServiceMesh: "Determining the ingress IP and ports" section does not work always as istio-ingressgateway is type ClusterIP

### ISSUE THREAD

**Issue by nak3** [openshift/openshift-docs#26032]
# Which section(s) is the issue in?

* Determining the ingress IP and ports
https://docs.openshift.com/container-platform/4.5/service_mesh/service_mesh_user_guide/ossm-traffic-manage.html#ossm-routing-determine-ingress_routing-traffic

### What needs fixing?

> If the EXTERNAL-IP value is <none>, or perpetually <pending>, your environment does not provide an external load balancer for the ingress gateway. You can access the gateway using the service’s node port.

Although my env provides an external LB:

e.g.
```
$ oc get svc -n openshift-ingress router-default
NAME             TYPE           CLUSTER-IP      EXTERNAL-IP                                                                    PORT(S)                      AGE
router-default   LoadBalancer   172.30.44.160   a8b61a0496ff249268c8299de0065e0e-1332559681.ap-northeast-2.elb.amazonaws.com   80:31730/TCP,443:32406/TCP   6h21m
```

The istio-ingressgateway does not have `EXTERNAL-IP` because the type is `ClusterIP` not `LoadBalancer`.

```
$ oc get svc -n istio-system  istio-ingressgateway
NAME                   TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                              AGE
istio-ingressgateway   ClusterIP   172.30.67.247   <none>        15020/TCP,80/TCP,443/TCP,15443/TCP   28m
```

It seems ServiceMesh operator always install istio-ingressgateway with `ClusterIP`, but how this section work?

**Comment by vikram-redhat** [comment]
@JStickler I can't see Vidya's GH account here, so tagging you.

**Comment by vidya-iyengar** [comment]
@vikram-redhat my Github account: vidya-iyengar

**Comment by JStickler** [comment]
https://issues.redhat.com/browse/OSSMDOC-187

**Comment by nak3** [comment]
The section can work only when users change the service type in SMCP as:

```
apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
 ...
spec:
  gateways:
    ingress:
      service:
        type: LoadBalancer
```

I think ut is not usual configuration so doc should be updated anyway.
