### ISSUE TITLE
Document OpenShift Image object

### ISSUE THREAD

**Issue by soltysh** [openshift/openshift-docs#2608]
Our current documentation describes nicely [image streams](https://docs.openshift.org/latest/architecture/core_concepts/builds_and_image_streams.html#image-streams) or [docker images](https://docs.openshift.org/latest/architecture/core_concepts/containers_and_images.html#docker-images). But we have an object that is called an `Image` which generally describes any docker image, along with its entire metadata, it would be nice to have this part documented, as well.

@ahardin-rh you can assign this one to me, I'll try to find some time when we close 1.3 to document this.

**Comment by bfallonf** [comment]
@soltysh @ahardin-rh judging from the PR attached, I see this was documented. I'll close this PR then. Let me know if I'm wrong. Thanks!

**Comment by soltysh** [comment]
@bfallonf nope, this issue was opened as a result of the discussion we've had in the attached PR. So this should stay open until actually addressed.

**Comment by mburke5678** [comment]
@soltysh We are going through old issues. Have we added to the docs what you were looking for here? If not, please let me know exactly what you are looking for and I can open a BZ to get this moving.

**Comment by soltysh** [comment]
@mburke5678 what I would want to see is a description of an Image resource openshift provides, which is visible only to cluster admins and those responsible for pruning the images. In short Image is the actual metadata information about every image. Every image stream actually points to such an image (or to multiple), and normally users can't access all the images, unless through ImageStreamImage object, which you can think of a read-only access to images that are part of your image stream.

**Comment by soltysh** [comment]
I defer to @bparees who currently owns images.

**Comment by bparees** [comment]
i'd say it's still valid but no one is currently lined up to document it.  @bmcelvee would you maybe have some time to draft something if i give you some background?

**Comment by bmcelvee** [comment]
@bparees yeah, I can draft something.
