### ISSUE TITLE
[enterprise-4.5] Issue in file architecture/architecture-rhcos.adoc

### ISSUE THREAD

**Issue by annelson-rh** [openshift/openshift-docs#26169]
### Which section(s) is the issue in?
Changing Ignition Configs after installation

### What needs fixing?

remove:" If you wanted to change a setting in one of those files, for example to change pids_limit to 1500 (pids_limit = 1500) inside the crio.conf file, you could create a new machineconfig containing only the file you want to change."

ContainerRuntimeConfig is the way to change crio.conf. this causes confusion when customers see the docs do not match the preffered way to change it.

**Comment by jonquilwilliams** [comment]
@annelson-rh I understand about the crio.conf. But what about the other files listed in the doc, like storage.conf - would the doc hold true for the other files? Please let me know so I can update the doc correctly. Thanks.

**Comment by annelson-rh** [comment]
storage.conf is also controlled by containerruntimeconfig, registries.conf looks like its controlled by image.config.openshift.io/cluster

**Comment by jonquilwilliams** [comment]
So is it best to remove the paragraph altogether as you suggested? 

Or keep the prargraph but remove the example and add a note that any containers that are controlled by containerruntimeconfig, like storage.conf and crio.conf, should only be changed using ContainerRuntimeConfig?

Thanks for taking with with this.

**Comment by annelson-rh** [comment]
imo: removing the paragraph would be best. 
might be worthwhile to have a separate section in the docs regarding adding/updating files on the nodes via machineconfig.
