### ISSUE TITLE
[enterprise-4.5] Issue in file networking/ingress-operator.adoc

### ISSUE THREAD

**Issue by rhatbob** [openshift/openshift-docs#26188]
### Which section(s) is the issue in?
Ingress controller configuration parameters @ https://docs.openshift.com/container-platform/4.5/networking/ingress-operator.html#nw-ingress-controller-configuration-parameters_configuring-ingress

### What needs fixing?
Table header highlights column [#1](https://docs.openshift.com/container-platform/4.5/networking/ingress-operator.html#nw-ingress-controller-configuration-parameters_configuring-ingress) as `Parameter`, but displays operator types [0] instead (like `IngressControllerLogging` instead), leading to looking for the non-existent `IngressControllerLogging` parameters instead of `logging`:
~~~
# oc explain ingresscontrollers.spec.logging
error: field "IngressControllerLogging" does not exist

# oc explain ingresscontrollers.spec.logging
KIND:     IngressController
VERSION:  operator.openshift.io/v1

RESOURCE: logging <Object>

DESCRIPTION:
     logging defines parameters for what should be logged where. If this field
     is empty, operational logs are enabled but access logs are disabled.

FIELDS:
   access	<Object>
     access describes how the client requests should be logged. If this field is
     empty, access logging is disabled.

~~~

[0] https://github.com/openshift/api/blob/master/operator/v1/types_ingress.go#L113

**Comment by jboxman** [comment]
So this is https://docs.openshift.com/container-platform/4.5/rest_api/operator_apis/ingresscontroller-operator-openshift-io-v1.html#ingresscontroller-operator-openshift-io-v1.
