### ISSUE TITLE
Example LDAP auth and groupsync configs

### ISSUE THREAD

**Issue by liggitt** [openshift/openshift-docs#2624]
Need to add examples for auth config and group sync for most common LDAP schemas:

* OpenLDAP
* IPA
* Active Directory

Things to outline for each LDAP schema:
* User query (baseDN is unique per install, but standard attribute for login and display name could be given as examples)
* Group query
* Typical LDAP credentials required (bindDN/bindPassword)

**Comment by liggitt** [comment]
As an example, IPA defaults to only allowing authenticated users to list group membership, so bindDN and bindPassword are likely required for group sync against IPA

**Comment by bfallonf** [comment]
@liggitt Thanks! This would require more than a quick fix, so I'm going to create a BZ for this so that we can track it as part of a release.
