### ISSUE TITLE
OpenShift Add Documentation for CSV Patches on Cluster

### ISSUE THREAD

**Issue by nathanbrophy** [openshift/openshift-docs#26244]
### Which section(s) is the issue in?

This issue is in the Operators Section, and more specifically, the `OLM` portion of the information.  

### What needs fixing?

Today the process flow for installing an `OLM` Operator might look like the following:

1. Apply a `CatalogSource` resource to the cluster that contains an index image with your Operator bundles in the registry
1. Either through the UI install the operator, or create a `Subscription` to the Operator
1. This creates a `CSV` resource on the cluster

Today, this CSV is not synced with the registry in the `CatalogSource`.  This means that a team can apply configuration changes and hot-fixes to an operator after it is installed by editing the `CSV` directly on the cluster.  

The change proposed to the documentation is the following:

> Add documentation to the OLM section of the Operators guide in the OpenShift documentation (on a release basis) to clearly state whether the CSV is synced with the registry in the CatalogSource or not, and if it is synced how to disable this feature.  Purpose of this is to understand on an OCP to OCP release, what customizations can be made to a CSV after it is installed, whether the CSV will be reconciled and synced to the value in the index database, and how this feature can be disabled when it is rolled out.

**Comment by jboxman** [comment]
@adellape FYI
