### ISSUE TITLE
[enterprise-4.3] Issue in file release_notes/ocp-4-3-release-notes.adoc

### ISSUE THREAD

**Issue by stevenewsted** [openshift/openshift-docs#26264]
### Which section(s) is the issue in?
When using the version pulldown menu from a higher version to a lower one, the link fails because there is no corresponding release notes for the newer version in the older docs. 

eg, on the 4.4 release notes, using the pulldown to change to the 4.3 ones, it tries to point to a "4-4" page in the "4.3" directory.

### What needs fixing?
Either update those links to change the path and file name?

**Comment by jboxman** [comment]
@vikram-redhat FYI

**Comment by vikram-redhat** [comment]
Fixed for 4.x release.
