### ISSUE TITLE
[enterprise-4.4] Issue in file authentication/identity_providers/configuring-gitlab-identity-provider.adoc

### ISSUE THREAD

**Issue by hawkowl** [openshift/openshift-docs#26278]
### Which section(s) is the issue in?

authentication/identity_providers/configuring-gitlab-identity-provider.adoc

### What needs fixing?

The GitLab identity provider does not support plain OAuth2, only OIDC, in 4.0+ (see https://github.com/openshift/cluster-authentication-operator/blob/release-4.0/pkg/operator2/idp.go#L114 ).

**Comment by jboxman** [comment]
@hawkowl 

So does that mean that this is wrong?

> Configure a gitlab identity provider to use GitLab.com or any other GitLab instance as an identity provider. If you use GitLab version 7.7.0 to 11.0, you connect using the OAuth integration. If you use GitLab version 11.1 or later, you can use OpenID Connect (OIDC) to connect instead of OAuth.

And that you cannot use the identity provider with GitLab `7.7.0` to `11.0` at all? GitLab seems to be up to `13.9` now.
