### ISSUE TITLE
Fix kubectl docs redirect link

### ISSUE THREAD

**Issue by bergerhoffer** [openshift/openshift-docs#26536]
### Which section(s) is the issue in?

https://github.com/openshift/openshift-docs/blob/master/cli_reference/openshift_cli/usage-oc-kubectl.adoc

### What needs fixing?

The link to the kubectl docs uses Google to redirect:

```
https://www.google.com/url?q=https://kubernetes.io/docs/reference/kubectl/overview/&sa=D&ust=1576620297762000&usg=AFQjCNGBR2LsVeM-JuLDz1rA5U9n-WwcPw
````
This shouldn't use Google to redirect, it should go directly to the kubernetes docs page:

```
https://kubernetes.io/docs/reference/kubectl/overview/
```

Marking as a good issue for Hacktoberfest. Apply the fix to the master branch, and when opening the PR, notify the admins that it should be cherry picked back to 4.4.

**Comment by AishwaryaKaranth** [comment]
Can I work on this issue?

**Comment by bergerhoffer** [comment]
@AishwaryaKaranth yes, thank you! Let me know if you have any questions along the way.

**Comment by AishwaryaKaranth** [comment]
The link now redirects directly to the kubernetes doc page. I have  submitted a PR.
https://github.com/openshift/openshift-docs/pull/26696

**Comment by bergerhoffer** [comment]
Closing as the PR was merged. Thanks again!
