### ISSUE TITLE
[enterprise-4.5] Issue in file installing/installing_vsphere/installing-restricted-networks-vsphere.adoc

### ISSUE THREAD

**Issue by pamoedom** [openshift/openshift-docs#26574]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.5/installing/installing_vsphere/installing-restricted-networks-vsphere.html#installation-vsphere-machines_installing-restricted-networks-vsphere

### What needs fixing?

"append-bootstrap.ign" example mentions version: "2.1.0" but I think it should be "version": "2.2.0" like the rest of ignition files, example from the doc:

~~~
{
  "ignition": {
    "config": {
      "append": [
        {
          "source": "<bootstrap_ignition_config_url>", 
          "verification": {}
        }
      ]
    },
    "timeouts": {},
    "version": "2.1.0"
  },
  "networkd": {},
  "passwd": {},
  "storage": {},
  "systemd": {}
}
~~~

Best Regards.

**Comment by jboxman** [comment]
@codyhoag FYI

**Comment by codyhoag** [comment]
@jinyunma according to the [4.5 upstream doc](https://github.com/openshift/installer/blob/release-4.5/docs/user/vsphere/install_upi.md#bootstrap-vm), `"version": "2.1.0"` is correct. Can you confirm?

**Comment by jinyunma** [comment]
@codyhoag QE used [upstream terraform template ](https://github.com/openshift/installer/tree/release-4.5/upi/vsphere)to create cluster nodes, I checked generated ignition file, its version is "2.1.0", and there is no issue with this version.

**Comment by codyhoag** [comment]
Closing this as version `2.1.0` was the confirmed version for the ignition file.

**Comment by pamoedom** [comment]
Please reopen, all current supported OCP versions use ignition 2.2.0 (3.1.0 for newer OCP 4.6), here you have an example using an old 4.2.13 to demostrate that it was already present in previous no-longer-supported versions:

~~~
$ ./openshift-install version
./openshift-install v4.2.13
built from commit 46f909e4ccb4f7a4f82bf1ee28b32fa011a6bd1f
release image quay.io/openshift-release-dev/ocp-release@sha256:782b41750f3284f3c8ee2c1f8cb896896da074e362cf8a472846356d1617752d

$ ./openshift-install create manifests --dir pamoedom-test
INFO Consuming "Install Config" from target directory 

$ ./openshift-install create ignition-configs --dir pamoedom-test/
INFO Consuming "Common Manifests" from target directory 
INFO Consuming "Worker Machines" from target directory 
INFO Consuming "Openshift Manifests" from target directory 
INFO Consuming "Master Machines" from target directory 

$ cat pamoedom-test/*.ign | jq . | grep "\"version\":"
    "version": "2.2.0"
    "version": "2.2.0"
    "version": "2.2.0"
~~~

I suppose that version 2.1.0 is also compatible but please note that the example in the doc is not accurate.

Just to reinforce this assumption, you can also check to recent version 4.6 template [here](https://docs.openshift.com/container-platform/4.6/installing/installing_vsphere/installing-restricted-networks-vsphere.html#installation-vsphere-machines_installing-restricted-networks-vsphere) and you'll see that it also using version 3.1.0 accordingly.

Regards.

**Comment by codyhoag** [comment]
@jinyunma after some digging, I recall updating ignition version 2.2.0 &rarr; 3.1.0 for [BZ#1862924](https://bugzilla.redhat.com/show_bug.cgi?id=1862924). So with that and the evidence shown by @pamoedom above, perhaps 2.2.0 is a better example, even if 2.1.0 is supported. Can you confirm?

**Comment by jinyunma** [comment]
I tested upi installation with ignition version 2.2.0 manually on vsphere platform on 4.5, the installation is successful.
so it's ok for me to update doc with 2.2.0 as an example.

**Comment by codyhoag** [comment]
This has been fixed. Thanks for flagging it @pamoedom!
