### ISSUE TITLE
memory settings for jdk11+ on openshift

### ISSUE THREAD

**Issue by hhellbusch** [openshift/openshift-docs#26681]
### Which section(s) is the issue in?

https://github.com/openshift/openshift-docs/blob/master/modules/nodes-cluster-resource-configure-jdk.adoc

### What needs fixing?

In java 11; they dropped the "UseCGroupMemoryLimitForHeap" and have added "UseContainerSupport"

See for more details.
https://www.eclipse.org/openj9/docs/xxusecontainersupport/

The docs page should be updated to make note of the new flag

**Comment by bergerhoffer** [comment]
@hhellbusch Can you let me know if this update is what you were looking for?

PR: https://github.com/openshift/openshift-docs/pull/30784

**Comment by hhellbusch** [comment]
Looks great! thanks @bergerhoffer
