### ISSUE TITLE
[enterprise-4.6] Issue in file release_notes/ocp-4-6-release-notes.adoc

### ISSUE THREAD

**Issue by rbaumgar** [openshift/openshift-docs#26807]
### Which section(s) is the issue in?
Minimum disk side for control plane nodes has increased for Azure installations

### What needs fixing?
typo in the topic. Shoud be "disk si**z**e"

**Comment by ahardin-rh** [comment]
@rbaumgar Thank you for reporting this! This is now fixed in https://github.com/openshift/openshift-docs/pull/26808
