### ISSUE TITLE
Metrics sizing

### ISSUE THREAD

**Issue by timothysc** [openshift/openshift-docs#2682]
Can we distill down https://github.com/ekuric/openshift/blob/master/metrics/openshift-recommendations.md into a doc change? 

/cc @jeremyeder @mwringe @ekuric

**Comment by jeremyeder** [comment]
This is waiting for @ekuric to return from PTO, correct?  Also there was feedback from @mwringe around the correct way to scale out the metrics pods.  Want to make sure we capture that.

**Comment by timothysc** [comment]
Sure, but the docs folks can do a 1st pass distillation.

**Comment by adellape** [comment]
FYI @bfallonf per your https://bugzilla.redhat.com/show_bug.cgi?id=1303505.

**Comment by adellape** [comment]
@bfallonf Oh, looks like this is happening in https://github.com/openshift/openshift-docs/pull/2753.

**Comment by timothysc** [comment]
yup, I'll close this one.
