### ISSUE TITLE
[enterprise-4.6] Issue in file pipelines/creating-applications-with-cicd-pipelines.adoc

### ISSUE THREAD

**Issue by ocarvajarh** [openshift/openshift-docs#26873]
### Which section(s) is the issue in?

Running a Pipeline

### What needs fixing?

In step 3 the parameter deployment-name=vote-api should be changed to deployment-name=vote-ui

**Comment by bergerhoffer** [comment]
@Preeticp Can you look into this issue that was raised?

**Comment by Preeticp** [comment]
@bergerhoffer thanks for bringing this to my notice. I have assigned the Dev Tools label so that we can filter the issues and track them in our sprints. If you come across any such issues, please let me know or assign the Dev Tools label. Thank you.

**Comment by Preeticp** [comment]
This has been fixed: https://docs.openshift.com/container-platform/4.6/pipelines/creating-applications-with-cicd-pipelines.html#running-a-pipeline_creating-applications-with-cicd-pipelines
Closing this issue, for now. Please reopen if you have any concerns.

**Comment by bergerhoffer** [comment]
Thanks @Preeticp! I think I saw a few others, so I'll tag you in those once I come across them again. Thanks!
