### ISSUE TITLE
[enterprise-4.6] Issue in file pipelines/creating-applications-with-cicd-pipelines.adoc

### ISSUE THREAD

**Issue by ocarvajarh** [openshift/openshift-docs#26874]
### Which section(s) is the issue in?

Adding Triggers to a Pipeline

### What needs fixing?

In step 5 the sample yaml to create EventListener is wrong (bindings section), this should be the equal to https://raw.githubusercontent.com/openshift/pipelines-tutorial/release-tech-preview-2/03_triggers/03_event_listener.yaml

**Comment by bergerhoffer** [comment]
@Preeticp Here is another pipelines issue, if your team can take a look. Thanks!

**Comment by Preeticp** [comment]
We will fix the issue in Step 7 in this section: https://docs.openshift.com/container-platform/4.6/pipelines/creating-applications-with-cicd-pipelines.html#adding-triggers_creating-applications-with-cicd-pipelines via this [Jira issue](https://issues.redhat.com/browse/RHDEVDOCS-2864)

**Comment by sounix000** [comment]
Doc PRs (either merged or with LGTMs):
- `4.6`: [https://github.com/openshift/openshift-docs/pull/31051](https://github.com/openshift/openshift-docs/pull/31051)
- `4.7` and `4.8`: [https://github.com/openshift/openshift-docs/pull/31051](https://github.com/openshift/openshift-docs/pull/31051)

Please close this issue.
CC - @Preeticp 
Thanks!
