### ISSUE TITLE
Recommend 20GB of disk space for etcd

### ISSUE THREAD

**Issue by jeremyeder** [openshift/openshift-docs#2688]
The cloud images we use leave only 5.5GB free on the root partition, and that free space was totally consumed by etcd during our 20,000-project master vertical scale runs.

As we increased further to 20,000 projects, etcd space increased to approx 12.5GB.  We would like to note this in documentation and recommend that users provide at least 20GB for etcd.

Here is a graph of disk usage across a 3-node etcd cluster during our test runs.

The disk was filled around 8:00pm 8/16.  We fixed that and re-ran successfully, and you can see around 4:00pm on 8/17, etcd disk usage peaked around 12.5GB on each node.

![etcd-disk-utilization](https://cloud.githubusercontent.com/assets/1919640/17808944/0f36eadc-65e1-11e6-943f-d82c12202de7.png)

/cc @mffiedler @timothysc

**Comment by timothysc** [comment]
We should just update the base requirements on the masters available disk space to lesson any ambiguity.

**Comment by timothysc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Hv12SAuK&#x2F;181-1-docs-pr-for-basic-etcd-disk-sizing"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> (1) Docs PR for basic etcd disk sizing</a>

**Comment by jeremyeder** [comment]
@adellape @bfallonf

**Comment by adellape** [comment]
@jeremyeder Ack. Some prereq topics might be moving around, so I need to see how things land. But I'll pin this to get in with my general install guide 3.3 updates.

**Comment by timothysc** [comment]
See this comment: https://github.com/openshift/openshift-docs/pull/2814#discussion_r78208243

**Comment by adellape** [comment]
@jeremyeder Should the recommendation for an additional 20GB for etcd be noted only for external etcd? Any different language needed for embedded?

cc @ahardin-rh

**Comment by timothysc** [comment]
We only support external etcd.

**Comment by ahardin-rh** [comment]
Addressed in https://github.com/openshift/openshift-docs/pull/2814 and https://github.com/openshift/openshift-docs/pull/2850
