### ISSUE TITLE
[enterprise-4.6] Issue in file support/gathering-cluster-data.adoc

### ISSUE THREAD

**Issue by sogutcu** [openshift/openshift-docs#26913]
### Which section(s) is the issue in?
Querying bootstrap node journal logs

### What needs fixing?
Missing @ in `ssh core<bootstrap_fqdn> journalctl -b -f -u bootkube.service`

**Comment by bergerhoffer** [comment]
@sogutcu Thanks for pointing out this issue! We've now merged an update to include the missing "@" and the fix should be live shortly.
