### ISSUE TITLE
[enterprise-4.6] Issue in file installing/installing_ibm_z/installing-restricted-networks-ibm-z.adoc

### ISSUE THREAD

**Issue by clayb-ssc** [openshift/openshift-docs#26945]
### Which section(s) is the issue in?
Creating Red Hat Enterprise Linux CoreOS (RHCOS) machines

This affects both the restricted network and standard IBM Z installation docs.

### What needs fixing?
`rd.neednet=1 console=ttysclp0 coreos.inst.install_dev=dasda coreos.inst.image_url=ftp://
cl1.provide.example.com:8080/assets/rhcos-live-rootfs.s390x.img
coreos.inst.ignition_url=ftp://cl1.provide.example.com:8080/ignition-bootstrap-0
ip=172.18.78.2::172.18.78.1:255.255.255.0:::none nameserver=172.18.78.1
rd.znet=qeth,0.0.bdf0,0.0.bdf1,0.0.bdf2,layer2=1,portno=0 zfcp.allow_lun_scan=0 cio_ignore=all,
!condev rd.dasd=0.0.3490`

This will not work on 4.6.1 when installing to a z/VM guest. Using "console=ttysclp0" throws an error and "coreos.inst.image_url" must be replaced with "coreos.live.rootfs_url" and **must** use HTTP/HTTPS. FTP isn't supported. I also encountered issues pulling the ignition file over FTP and had to switch to HTTP. I had used FTP in 4.5.x.

Below is a working parmfile configuration template which I've used to successfully deploy RHCOS 4.6.1 on z/VM (s390x).
`rd.neednet=1 coreos.inst=yes coreos.inst.install_dev=dasda coreos.live.rootfs_url=http://
cl1.provide.example.com:8080/assets/rhcos-live-rootfs.s390x.img
coreos.inst.ignition_url=http://cl1.provide.example.com:8080/ignition-bootstrap-0
ip=172.18.78.2::172.18.78.1:255.255.255.0:::none nameserver=172.18.78.1
rd.znet=qeth,0.0.bdf0,0.0.bdf1,0.0.bdf2,layer2=1,portno=0 zfcp.allow_lun_scan=0 cio_ignore=all,
!condev rd.dasd=0.0.3490`

**Comment by jeana-redhat** [comment]
@clayb-ssc - I picked this up for an issue burndown since you kindly provided the exact change needed (thank you!). However, looking into this, I see that he content in question has already been changed to some degree (including fixing the use of FTP you mentioned). The current version of the example config doesn't 100% match what you provided, but could you let me know if it works for you? If not, let me know what still needs to be changed. Current config in docs:
```
rd.neednet=1 console=ttysclp0 coreos.inst.install_dev=dasda coreos.live.rootfs_url=http://
cl1.provide.example.com:8080/assets/rhcos-live-rootfs.s390x.img
coreos.inst.ignition_url=http://cl1.provide.example.com:8080/ignition/bootstrap.ign
ip=172.18.78.2::172.18.78.1:255.255.255.0:::none nameserver=172.18.78.1
rd.znet=qeth,0.0.bdf0,0.0.bdf1,0.0.bdf2,layer2=1,portno=0 zfcp.allow_lun_scan=0 cio_ignore=all,
!condev rd.dasd=0.0.3490
```
