### ISSUE TITLE
[enterprise-4.6] Issue in file authentication/identity_providers/configuring-htpasswd-identity-provider.adoc

### ISSUE THREAD

**Issue by andreasottosson** [openshift/openshift-docs#26976]
### Which section(s) is the issue in?

Updating users for an HTPasswd identity provider / 3. Replace the htpass-secret secret with the updated users in the users.htpasswd file

### What needs fixing?

`oc create secret generic htpass-secret --from-file=htpasswd=users.htpasswd --dry-run -o yaml -n openshift-config | oc replace -f -`

should be

`oc create secret generic htpass-secret --from-file=htpasswd=users.htpasswd --dry-run=client -o yaml -n openshift-config | oc replace -f -`

**Comment by andreasottosson** [comment]
Opened a PR that fixes this https://github.com/openshift/openshift-docs/pull/27028

**Comment by bergerhoffer** [comment]
@andreasottosson Sorry for the delay on this one. In testing, it looks like this change starts with OCP 4.5, can you confirm that is correct?

**Comment by bergerhoffer** [comment]
Closing as #27028 was merged
