### ISSUE TITLE
[enterprise-4.6] Better clarify for installation options

### ISSUE THREAD

**Issue by tsailiming** [openshift/openshift-docs#26999]
### Which section(s) is the issue in?

Customers feedback that the multiple installation options in OpenShift documentation is confusing and hard to navigate.

For example: "Installation on AWS". There are many possible options and confusing to figure out which one to read and follow.

### What needs fixing?

To be clearer on the various options, pros and cons. A table will be helpful. For example for AWS, 

1. IPI and UPI
2. Public and Private cluster
3. Network customization
4. Cluster wide proxy
5. Mirrored Registry

This greatly reduce the confusion that customer faces and helps to decide which installation steps to follow.

[Installing a cluster on AWS in a restiricted network](https://docs.openshift.com/container-platform/4.6/installing/installing_aws/installing-restricted-networks-aws.html) - This is UPI and uses a mirrored registry. 

[Installing a private cluster on AWS](https://docs.openshift.com/container-platform/4.6/installing/installing_aws/installing-aws-private.html) - This is IPI for private cluster and support mirrored registry

**Comment by mburke5678** [comment]
@tsailiming I believe the problem you mention was addressed in the 4.7 docs [1]. I am not sure if there are plans to make similar changes in 4.5 and 4.6. @kalexand-rh do you know?

[1] https://docs.openshift.com/container-platform/4.7/installing/installing-preparing.html

**Comment by kalexand-rh** [comment]
@mburke5678, that change was part of a larger restructuring of the installation docs that we're not planning to validate and backport.
