### ISSUE TITLE
If using explicit IDs in cross references is required, let's add a note saying so.

### ISSUE THREAD

**Issue by rolfedh** [openshift/openshift-docs#26992]
### Which section(s) is the issue in?

https://github.com/openshift/openshift-docs/blob/master/contributing_to_docs/doc_guidelines.adoc#internal-cross-references

### What needs fixing?

The current example shows an explicit ID but we don't state that using them is required. If they are required, let's say so.

**Comment by kalexand-rh** [comment]
https://github.com/openshift/openshift-docs/blob/master/contributing_to_docs/doc_guidelines.adoc#links-hyperlinks-and-cross-references

> All links to internal content is created using xref and must have an anchor ID.
