### ISSUE TITLE
[enterprise-4.4] Issue in file migration/migrating_4_1_4/deploying-cam-4-1-4.adoc

### ISSUE THREAD

**Issue by silviayuu** [openshift/openshift-docs#27086]
### Which section(s) is the issue in?
Deploying and upgrading the Cluster Application Migration tool
- https://docs.openshift.com/container-platform/4.4/migration/migrating_4_1_4/deploying-cam-4-1-4.html

### What needs fixing?
The Cluster Application Migration Operator mentioned in document needs to be replaced by "Migration Toolkit for Containers Operator" as MTC is a brand rename from CAM and MTC is available in Operator Hub.

**Comment by bergerhoffer** [comment]
4.4 is out of support, and it looks like 4.5+ have the correct new Operator name of "Migration Toolkit for Containers Operator": https://docs.openshift.com/container-platform/4.5/migration/migrating_4_1_4/deploying-cam-4-1-4.html

Closing this issue.
