### ISSUE TITLE
Fix serviceaccounts typo

### ISSUE THREAD

**Issue by aweiteka** [openshift/openshift-docs#2711]
When creating a "long-lived" service account (rest_api/index, registry_quickstart/developers), the oc policy command should reference **system:serviceaccount:test:push**

Also, it is better to use these commands:

```
oc policy add-role-to-user <role> -z <SA> -n <PROJECT>
oc sa new-token ...
oc sa get-token ...
```

**Comment by vikram-redhat** [comment]
Both those books are out of use now, so I am closing this issue.
