### ISSUE TITLE
[enterprise-4.6] Issue in file security/compliance_operator/compliance-operator-understanding.adoc

### ISSUE THREAD

**Issue by amelie1979** [openshift/openshift-docs#27182]
### Which section(s) is the issue in?
also the $NAMESPACE variable is not identify with a source.. ? (git repo use openshift-compliance) (redhat operator goes default to openshift-operators namespace)

### What needs fixing?
Its missing the part to how to deploy the operator (namespace name and scope)
Its also missing the part how to create a ScanSettingBinding (would be good to walkthrough the whole process from installation to configuration example CIS-Benchmark profile).

**Comment by ahardin-rh** [comment]
@JAORMX @jhrozek Can you please provide guidance on these doc updates?

**Comment by jhrozek** [comment]
I guess for the basic docs we can just stick with openshift-compliance as the namespace. In general, it's not a hard requirement and especially in conjuction with RHACM the policies and the operator are not required to live in the same namespace, but if the doc is supposed to easily cover the 80% case, then I guess going with openshift-compliance makes sense.

About the installation and basic usage..I wonder if a chapter slipped from the original google doc proposal that we wrote a couple of weeks ago to bootstrap the official docs? In the doc, I see chapters on installation and basic usage, which I don't see in the resulting doc...

**Comment by amelie1979** [comment]
any update on updating the doc ?

**Comment by amelie1979** [comment]
> @JAORMX @jhrozek Can you please provide guidance on these doc updates?

**Comment by amelie1979** [comment]
@ahardin-rh  can you review @jhrozek comments ?

**Comment by ahardin-rh** [comment]
Work in progress: https://github.com/openshift/openshift-docs/pull/29673

**Comment by ahardin-rh** [comment]
The updates are now published: https://docs.openshift.com/container-platform/4.7/security/compliance_operator/compliance-operator-installation.html

I am going to close this issue, but please let us know if further updates are needed. Thank you!
