### ISSUE TITLE
[enterprise-4.5] Issue in file installing/install_config/installing-restricted-networks-preparations.adoc

### ISSUE THREAD

**Issue by ElCoyote27** [openshift/openshift-docs#27199]
### Which section(s) is the issue in?

Near the end of the page. 

```oc create configmap registry-config --from-file=${MIRROR_ADDR_HOSTNAME}..5000=$path/ca.crt```

I think this should be:

```oc create configmap registry-config --from-file=${MIRROR_ADDR_HOSTNAME}:5000=$path/ca.crt```

E.g: ":" instead of ".."

**Comment by codyhoag** [comment]
@jianlinliu can you confirm this update proposal in step 3 here [1]?

[1] https://docs.openshift.com/container-platform/4.5/installing/install_config/installing-restricted-networks-preparations.html#installation-restricted-network-samples_installing-restricted-networks-preparations

**Comment by jianlinliu** [comment]
@xiuwang Can you help review this?

**Comment by xiuwang** [comment]
`..` in cmd `oc create configmap registry-config --from-file=${MIRROR_ADDR_HOSTNAME}..5000=$path/ca.crt` is correct, see the related doc.
https://docs.openshift.com/container-platform/4.6/registry/configuring-registry-operator.html#images-configuration-cas_configuring-registry-operator

**Comment by codyhoag** [comment]
QE has confirmed the current command usage with `..`. Closing this now.
