### ISSUE TITLE
[enterprise-4.5] Issue in file backup_and_restore/graceful-cluster-shutdown.adoc

### ISSUE THREAD

**Issue by Optica1** [openshift/openshift-docs#27212]
### Which section(s) is the issue in?

Shutting down the cluster / Procedure 

### What needs fixing?

In a, the command 'nodes=$(oc get nodes -o name)' returns all hostnames but adds 'node/' in front of them.
When trying to shut down the node using the next command, the hostname can not be resolved.

To fix this, i used: nodes=$(oc get nodes -o name | sed 's/node\///')

Maybe there's a better way to  remove the 'node/' at the start of every line, but this works ;)

EDIT: My cluster is on version 4.5.16

Cheers

**Comment by jboxman** [comment]
@Optica1, I believe this works as well:

```
oc get nodes -o jsonpath='{range .items[*]}{.metadata.name}{end}'
```

**Comment by jboxman** [comment]
@Optica1 thanks for reporting this!
