### ISSUE TITLE
[enterprise-4.6] Issue in file updating/updating-cluster-cli.adoc

### ISSUE THREAD

**Issue by lbohnsac** [openshift/openshift-docs#27213]
### Which section(s) is the issue in?

Updating a cluster within a minor version by using the CLI

### What needs fixing?

Why do we have 4.5. example outputs in the 4.6. documentation?
Please fix the example outputs to 4.6.

**Comment by ahardin-rh** [comment]
@lbohnsac Thanks for pointing this out! I opened https://github.com/openshift/openshift-docs/pull/27233 to address this. Somehow this was missed when I opened https://github.com/openshift/openshift-docs/pull/25551 before 4.6 GA.
