### ISSUE TITLE
Updates for 3.3 Upgrade

### ISSUE THREAD

**Issue by dgoodwin** [openshift/openshift-docs#2728]
A new type of init container support was added in 1.3/3.3, if any pods were pre-created with the appropriate annotation, these pods would have drastically elevated privleges after the upgrade, it is recommended admins delete them all with the command outlined in https://github.com/openshift/openshift-ansible/issues/2227. However, given that we currently document node evacuation as mandatory, this command may not be necessarily.

That said, Clayton has raised the point that we perhaps should not require node evacuation during upgrade. If Docker does not have to be upgraded, it is technically not required (though should be tested, I will do a quick test to make sure). 

Requsted changes:
- Soften our language around evacuating nodes, only do it if Docker needs an upgrade.
- Document the init container cleanup command if you *don't* need a node evac.
- pluginOrderOverride is being deprecated in master-config.yaml, if present user should consider replacing it. Can link to /architecture/additional_concepts/admission_controllers.html to give the user more info, docs will appear here if they're not there already.
- Reconciling roles has already moved to between master and node upgrades, but it looks like your docs already have it in this order, so no change required.
- Document that Docker service should be *stopped* before upgrading the rpm, this can do really nasty things.
- The upgrade playbooks now clean out *unused* Docker images on all hosts before they even start the upgrade process, this isn't technically required but might be a nice thing to document if they're going to do a Docker upgrade. It would mean running this command on all docker hosts: ```docker rmi `docker images -aq```. This will only delete unused images, anything in use will report as an error which can be safely ignored.
- All master and node configs should be upgraded for the new protobuf support: https://github.com/openshift/openshift-ansible/issues/2214

I think that's it, let me know if you have questions, I will try an upgrade on 3.2 cluster that already has Docker 1.10, and disable node evac and make sure my pods survive.

**Comment by dgoodwin** [comment]
Situation without evac is a little weird, I tried an upgrade without doing evac, my pod survives it but then the node comes back up and pulls the new ose-pod container version, and my pod gets restarted. It does however not disappear like it does with an evac.

What do you think we should document here @adellape? We should probably document the init container cleanup regardless, it won't hurt anything to delete them prior to evac. 

As for evac itself, we could clarify that we suggest it, but you can skip it, though your pods will probably still get restarted when the system needs to pull a new pod image version.

**Comment by adellape** [comment]
Spoke with @dgoodwin about these. Decided to wait on the optional-evac stuff for now until the next minor release when there will be more work and testing done around that topic. The rest is handled via https://github.com/openshift/openshift-docs/pull/2893.

**Comment by JoaoJoia** [comment]
There is someone that can help me with the upgrade of OpenShift Origin cluster from 1.2 to 1.3. the v3_4 upgrade?
Someone can guide me?
I want to get up to date to the new OpenShift Origin cluster version.

Cumps, João
