### ISSUE TITLE
docs for advanced install script fail on install with sudo user

### ISSUE THREAD

**Issue by ivanthelad** [openshift/openshift-docs#2729]
The installation documentation outlines that  the following command is sufficent for a sudo install (once the documented sudo vars are set), this is not the case
- ansible-playbook  /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml

This install will fail due to permission issue. The following command solves the problem. 
- ansible-playbook --become-method=sudo --become /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml

The docs should be updated to reflect this 
https://docs.openshift.com/enterprise/3.2/install_config/install/advanced_install.html

**Comment by vikram-redhat** [comment]
This is described in the table that follows: https://docs.openshift.com/enterprise/3.2/install_config/install/advanced_install.html#configuring-cluster-variables.
