### ISSUE TITLE
[enterprise-4.6] Issue in file networking/routes/route-configuration.adoc

### ISSUE THREAD

**Issue by annelson-rh** [openshift/openshift-docs#27356]
### Which section(s) is the issue in?

Route-specific annotations

### What needs fixing?
new annotation added in 4.6.1 - "router.openshift.io/cookie-same-site" (added via [RHBA-2020](https://issues.redhat.com/browse/RHBA-2020):4196, bug 1867186) 

KCS article - https://access.redhat.com/solutions/5576201

**Comment by jboxman** [comment]
`oc annotate route <routename> router.openshift.io/cookie-same-site=<"Lax"|"Strict"|"None">`

**Comment by ghyde** [comment]
I believe this issue was resolved with #26607.
