### ISSUE TITLE
[enterprise-4.6] Issue in file nodes/scheduling/nodes-scheduler-node-selectors.adoc

### ISSUE THREAD

**Issue by dpkshetty** [openshift/openshift-docs#27371]
### Which section(s) is the issue in?
Using node selectors to control pod placement

### What needs fixing?

1) Change _To add node selectors to an existing pod, add a node selector to the controlling object for that **node**_ 
to
_To add node selectors to an existing pod, add a node selector to the controlling object for that **pod**_

2) Change _To add node selectors to an existing pod, add a node selector to the controlling object for that node, such as a replica set, daemon set, **or stateful set**_
to
_To add node selectors to an existing pod, add a node selector to the controlling object for that node, such as a replica set, daemon set, stateful set, **deployment or deploymentconfig**_

In my testing, when I modified the replicaset (which controlled the Pod) with the nodeSelector label.. a new replica set was created but the Pod was **not** re-scheduled. The nodeSelector worked only when I modified the deployment yaml, the Pod was re-scheduled to the Node which matched the label. So for #2 above please check if you really want to mention replicaset when we add deployment / deploymentconfig ? Also my testing was on 4.3 version... I don't have access to 4.6 cluster at the moment.

**Comment by dpkshetty** [comment]
If the above proposed changes are acceptable, I would like to send a pull request. Let me know please.

**Comment by dpkshetty** [comment]
@jboxman @vikram-redhat who can help take this issue forward ? Its been more than a month and there is no update !

**Comment by jboxman** [comment]
@dpkshetty, updated.
