### ISSUE TITLE
[enterprise-4.6] Issue in file installing/installing_vsphere/installing-vsphere-installer-provisioned.adoc

### ISSUE THREAD

**Issue by ndox** [openshift/openshift-docs#27383]
### Which section(s) is the issue in?

Prerequisites ports needed to be opened for IPI VMware comparing to UPI

### What needs fixing?

Need to precise that port 443/TCP must be open between Bastion (from which you run the installer) ans ESxi hosts in order to upload templates

**Comment by codyhoag** [comment]
Fixed in #37873
