### ISSUE TITLE
[enterprise-4.4] Issue in file cnv/cnv_virtual_machines/cnv_virtual_disks/cnv-configuring-local-storage-for-vms.adoc

### ISSUE THREAD

**Issue by boris-deschenes** [openshift/openshift-docs#27444]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.6/virt/virtual_machines/virtual_disks/virt-configuring-local-storage-for-vms.html#virt-using-hostpath-provisioner_virt-configuring-local-storage-for-vms
you have the following yaml displayed:
---
apiVersion: hostpathprovisioner.kubevirt.io/v1beta1
kind: HostPathProvisioner
metadata:
  name: hostpath-provisioner
spec:
  imagePullPolicy: IfNotPresent
  pathConfig:
    path: "</path/to/backing/directory>" 
    useNamingPrefix: "false" 

I had to removed the " from useNamingPrefix: "false" for it to work.. I think boolean != string

### What needs fixing?
useNamingPrefix is a boolean, hence the value false must be without double-quotes

**Comment by aburdenthehand** [comment]
Thanks for raising this!
Fixed in #28886
