### ISSUE TITLE
NetworkAttachmentDefinition CR changed to network-attachment-definitions.k8s.cni.cncf.io

### ISSUE THREAD

**Issue by clarkhale** [openshift/openshift-docs#27485]
### Which section(s) is the issue in?
virt

Specifically:
https://github.com/openshift/openshift-docs/blob/master/virt/virtual_machines/vm_networking/virt-attaching-vm-multiple-networks.adoc, but may be other sections.

### What needs fixing?

CRD Name for NetworkAttachmentDefinition changed between 2.4->2.5 to network-attachment-definitions.k8s.cni.cncf.io

**Comment by dougbtv** [comment]
Wait hold up... This has not changed, at least the standard and the behind the scenes implementation. If there's a correction needed to the docs, that's another story.

Basically the gist is, the `kind` has always been (and remains) `NetworkAttachmentDefinition`. And the `name` itself, has always been (and remains): `network-attachment-definitions.k8s.cni.cncf.io`

The spec which defines this custom resource, as handled by the Network Plumbing Working Group can be found here, and the custom resource details can be found in section 3 here @ https://docs.google.com/document/d/1Ny03h6IDVy_e_vmElOqR7UdTPAG_RNydhVE1Kx54kFQ/edit#

**Comment by clarkhale** [comment]
Thanks for that working group doc.  Confirmed in https://bugzilla.redhat.com/show_bug.cgi?id=1917499
