### ISSUE TITLE
[enterprise-4.6] Issue in file installing/installing_vsphere/installing-vsphere-installer-provisioned.adoc

### ISSUE THREAD

**Issue by ryandevlin-redhat** [openshift/openshift-docs#27491]
### Which section(s) is the issue in?
Networking requirements

### What needs fixing?

There is no section in the networking requirements describing NTP configuration. It would be useful to include something along the lines of:

**"Network Time Protocol (NTP)
Each OpenShift Container Platform node in the cluster must have access to an NTP server discoverable via DHCP."**

If there is no NTP server discoverable over DHCP available to the vSphere VMs, the installation will fail. This requirement would prevent customers from struggling to debug this common pattern.

**Comment by skrthomas** [comment]
Looking into this for doc issue burndown

**Comment by skrthomas** [comment]
This issue says rotten, but it has been merged: https://github.com/openshift/openshift-docs/pull/30926
