### ISSUE TITLE
[enterprise-4.6] Issue in file installing/installing_bare_metal_ipi/ipi-install-prerequisites.adoc

### ISSUE THREAD

**Issue by ryandevlin-redhat** [openshift/openshift-docs#27490]
### Which section(s) is the issue in?
Network requirements

### What needs fixing?

In the section that discusses the NTP server it says the following:

**_"Network Time Protocol (NTP)
Each OpenShift Container Platform node in the cluster must have access to an NTP server."_**

What's unclear about this is that the NTP server must be **discoverable via DHCP**. If this is not the case, the installation will fail.
If there could be a line of text in the "Network Time Protocol (NTP)" section stating this, it would allow customers to avoid long debugging sessions due to this misunderstanding.

**Comment by jeana-redhat** [comment]
@ryandevlin-redhat - opened a PR to resolve this. Does the same edit still apply to releases post-4.6?

**Comment by ryandevlin-redhat** [comment]
@jeana-redhat Yes this applies to OCP 4.5+

**Comment by jeana-redhat** [comment]
Thanks!
