### ISSUE TITLE
[online] Issue in file welcome/index.adoc

### ISSUE THREAD

**Issue by b-mchugh** [openshift/openshift-docs#27506]
### Which section(s) is the issue in?
https://docs.openshift.com/dedicated/4/*
https://docs.openshift.com/aro/4/*

### What needs fixing?
All Dedicated 4 pages have wrong Page History links.
Page history links to "[enterprise-3](https://issues.redhat.com/browse/enterprise-3).11" https://github.com/openshift/openshift-docs/commits/enterprise-3.11/welcome/index.adoc

All ARO 4 pages have wrong Page History / Open an issue links.
Page history links to OCP 3.11 (https://github.com/openshift/openshift-docs/commits/enterprise-3.11/welcome/index.adoc
Open an issue links seem to all be titled [online] which seems unexpected given [dedicated] has it's own title, would expect [aro] for aro specific docs issues.
https://github.com/openshift/openshift-docs/issues/new?title=[online]%20Issue%20in%20file%20welcome/index.adoc

**Comment by b-mchugh** [comment]
Looks like the dedicated 4 page history links have changed but still point to older version of ocp.
https://docs.openshift.com/dedicated/4/welcome/index.html
https://github.com/openshift/openshift-docs/commits/enterprise-4.3/welcome/index.adoc

ARO page history still points to 3.11
https://docs.openshift.com/aro/4/welcome/index.html
https://github.com/openshift/openshift-docs/commits/enterprise-3.11/welcome/index.adoc

**Comment by pneedle-rh** [comment]
1. Regarding the Dedicated 4 page history, [here](https://github.com/openshift/openshift-docs/blob/dedicated-4/_templates/_page_openshift.html.erb#L86-L101) are the related lines.

I am looking into how to handle the dedicated-4 URL specifically. My understanding is that the page history should point to https://github.com/openshift/openshift-docs/commits/dedicated-4 from https://docs.openshift.com/dedicated/4/welcome/index.html.

2. Regarding the ARO page history, [here](https://github.com/openshift/openshift-docs/blob/master/_templates/_page_openshift.html.erb#L86-L101) are the related lines.

My understanding is that the page history should point to https://github.com/openshift/openshift-docs/commits/enterprise-4.7/welcome/index.adoc from https://docs.openshift.com/aro/4/welcome/index.html.

I will update this issue when I have progressed with this.

**Comment by pneedle-rh** [comment]
@b-mchugh thank you for your detailed problem description.

Following a conversation with our OpenShift Docs Program Manager, we are removing the "Page history" link from the ARO docs. See [PR 30931](https://github.com/openshift/openshift-docs/pull/30931) for more details.

We are in the process of reviewing the "Page history" link in the Dedicated documentation and I will update this issue once we have determined how to proceed.

Please let me know if you have any questions in the meantime. Thanks!

**Comment by pneedle-rh** [comment]
@b-mchugh the "Page history" link has now been removed from [the ARO documentation](https://docs.openshift.com/aro/4/welcome/index.html).

We also plan to provide a "Page history" link in Dedicated 4 documentation as part of our current documentation developments for that distribution.

Please let me know if you have any questions. Thanks!

**Comment by b-mchugh** [comment]
@pneedle-rh thanks for the update.
Looks like the ROSA and OSD "Page History" links still point to enterprise-3.11.
Would be useful to have them fixed to point to whatever the relevant "dedicated-4" link is instead such as 
https://github.com/openshift/openshift-docs/commits/dedicated-4
