### ISSUE TITLE
[online] Issue in file service_mesh/v1x/preparing-ossm-installation.adoc

### ISSUE THREAD

**Issue by b-mchugh** [openshift/openshift-docs#27507]
### Which section(s) is the issue in?
https://docs.openshift.com/aro/4/service_mesh/*

### What needs fixing?
Not clear if any ARO specific steps are required/missing compared to standard OCP 4.x. as it seems to be direct copy/paste of the original OCP 4.x Service Mesh Docs.

The correctness of the entire Service Mesh section with regards to ARO seems questionable when starting for example with the prerequisites include broken references things like:

Install Azure Red Hat OpenShift 4 on vSphere
Install Azure Red Hat OpenShift 4 on bare metal

https://docs.openshift.com/aro/4/service_mesh/v1x/preparing-ossm-installation.html

**Comment by b-mchugh** [comment]
Still not clear if any ARO specific steps are needed or if Service Mesh is expected to work on ARO, since the ARO docs have been removed and now point to the OCP4 docs instead.

No mention of Azure in prerequisites.
https://docs.openshift.com/container-platform/4.6/service_mesh/v2x/preparing-ossm-installation.html#prerequisites

**Comment by JStickler** [comment]
@b-mchugh as far as the service mesh docs team has been told by engineering and QE, the installation steps should be the same for ARO.   Have you attempted installation and failed?
