### ISSUE TITLE
[enterprise-4.6] Issue in file installing/installing_bare_metal/installing-bare-metal.adoc

### ISSUE THREAD

**Issue by pamoedom** [openshift/openshift-docs#27554]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.6/installing/installing_bare_metal/installing-bare-metal.html#installation-network-user-infra_installing-bare-metal

### What needs fixing?

In the table 1, the list of ports that should be opened from all machines to all machines is missing one port:

~~~
TCP    1936    Metrics
~~~

This port is necessary to reach the "router-default" ingress endpoints by the servicemonitor "router-internal-default":

~~~
$ oc get ep -n openshift-ingress router-internal-default -o yaml | grep ports -A10
  ports:
  - name: metrics
    port: 1936
    protocol: TCP
  - name: https
    port: 443
    protocol: TCP
  - name: http
    port: 80
    protocol: TCP
~~~

If the port is not open, Prometheus will trigger an alert with the following:

~~~
66.67% of the router-internal-default targets in openshift-ingress namespace are down
~~~

Best Regards.

**Comment by skrthomas** [comment]
looking into this for issue burndown

**Comment by skrthomas** [comment]
@pamoedom can you take a look at this PR and let me know if you have any feedback? I added a row to that first table with the info you provided. 
GitHub PR: https://github.com/openshift/openshift-docs/pull/30823
Direct link to doc: https://deploy-preview-30823--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_bare_metal/installing-bare-metal.html#installation-network-user-infra_installing-bare-metal

**Comment by pamoedom** [comment]
Hi @skrthomas, LGTM, thks.
