### ISSUE TITLE
document egress router

### ISSUE THREAD

**Issue by danwinship** [openshift/openshift-docs#2760]
We added the "egress router" feature in 3.3 but apparently forgot to document it.

It's described here: https://github.com/openshift/origin/tree/master/images/router/egress

It should be documented somewhere close to the docs for the new EgressNetworkPolicy stuff (#2675)

**Comment by adellape** [comment]
xref for Trello card: https://trello.com/c/3mQOsCBm/57-13-control-the-outbound-ip-address-used-by-a-pod-sdn-functionality-egress-13

@danwinship Is there a technical relationship between the egress policy/firewall and the egress router? Or is it just that they're both about egress traffic. I see the policy requires the multitenant SDN, but it doesn't seem like it also requires an egress router be deployed, right?

One reason I ask is I have a WIP (https://github.com/openshift/openshift-docs/pull/2776) where I'm breaking up the existing router topic (about the default HAProxy router and F5 router) into a subdirectory of separate topics:

http://file.rdu.redhat.com/~adellape/090116/standalone_registry/install_config/router/index.html

Would it make sense to have all "router" (i.e., egress as well) setup docs there?

**Comment by danwinship** [comment]
> Is there a technical relationship between the egress policy/firewall and the egress router? Or is it just that they're both about egress traffic.

It's just that they're both about egress traffic. And the two features came out of related customer conversations, and in some use cases, either one might work. eg, If you want to make sure that only pods in Namespace A can talk to external server B, then you could either:

1. add an egress router to Namespace A, and have B only accept connections from the egress router's IP.
2. use an EgressNetworkPolicy to prevent pods other than in Namespace A from being able to connect to B (and not do anything special on B)

Which one works better depends on circumstances, what else you're doing, etc.

> I see the policy requires the multitenant SDN, but it doesn't seem like it also requires an egress router be deployed, right?

Correct

> Would it make sense to have all "router" (i.e., egress as well) setup docs there, under the "Setting up a Router" subdirectory?

I don't think so. Both technologically and semantically, the egress router is a totally different thing from the "ingress" routers (haproxy/f5).

**Comment by adellape** [comment]
@danwinship Thanks. What if the existing egress firewall topic was reworked to be generally "Controlling Egress Traffic", and it included details on both the firewall and router methods in the single topic?

cc @tpoitras

**Comment by danwinship** [comment]
yes, that would make sense

**Comment by adellape** [comment]
Fixed in https://github.com/openshift/openshift-docs/pull/2934.
