### ISSUE TITLE
[enterprise-4.6] Issue in file installing/installing_vsphere/installing-vsphere-installer-provisioned.adoc

### ISSUE THREAD

**Issue by thekoma** [openshift/openshift-docs#27620]
### Which section(s) is the issue in?
Prerequisites

### What needs fixing?
With the [RHBA-2020](https://issues.redhat.com/browse/RHBA-2020):4196 we fixed the problem in 4.6.1 (GA) so that 

> Ensure that your vSphere server has only one datacenter and cluster. If it has multiple datacenters and clusters, it also has multiple default root resource pools, and the worker nodes will not provision during installation.

is not needed, and as a matter of fact now we can deploy on multidatacenter and multilcluster scenarios..

More info on the Slack Channel:
[SLACK POST](https://coreos.slack.com/archives/CH06KMDRV/p1606214891365200)

**Comment by giannisalinetti** [comment]
Hi Andrea, thank you for pushing this update on documentation. A customer of mine has already highlighted the gap between the published RHBA and docs.

**Comment by bergerhoffer** [comment]
Closing as it looks like this bullet was removed through #29694.
