### ISSUE TITLE
[enterprise-4.6] Issue in file applications/deployments/route-based-deployment-strategies.adoc

### ISSUE THREAD

**Issue by alfonzjanfrithz** [openshift/openshift-docs#27639]
### Which section(s) is the issue in?
In the introduction section, it is mentioned that the in-production version is the **green** version and the newer version is the **blue** version

### What needs fixing?
The common terminology is that the blue is the in production version and the green is the newer version.
This can cause mixed up terminology with common ground.

Reference:
https://martinfowler.com/bliki/BlueGreenDeployment.html
https://docs.cloudfoundry.org/devguide/deploy-apps/blue-green.html
Cloud Native Patterns - Cornelia Davies -  Chapter 7. The application lifecycle: Accounting for constant change (7.2.1)
Many more..

**Comment by bergerhoffer** [comment]
Agree after searching that blue seems to be the production version. Another example that is Red Hat-specific: https://www.redhat.com/en/topics/devops/what-is-blue-green-deployment
