### ISSUE TITLE
[enterprise-4.6] Issue in file service_mesh/v2x/installing-ossm.adoc

### ISSUE THREAD

**Issue by jpkrohling** [openshift/openshift-docs#27645]
### Which section(s) is the issue in?
- Deploying the control plane from the CLI

The option `sampling: 10000` under the Jaeger configuration seems quite strange: it would be good to have some (short) explanation on what this value means. Does it mean 100% sampling? Or perhaps 1%? I'm sure this is documented elsewhere, but even for a quick start, users will have to be aware of what this specific value means.

### What needs fixing?
Perhaps a note saying "This Jaeger configuration will sample [1%|10%|all] of the requests".

**Comment by bergerhoffer** [comment]
@JStickler Is this something that your team could look at?

**Comment by JStickler** [comment]
@jpkrohling , we do have a note to that effect, but it's in the topic about customizing the smcp where we explain all of the various configuration parameters.  Does that cover what you're looking for?

https://docs.openshift.com/container-platform/4.7/service_mesh/v2x/ossm-custom-resources.html#ossm-enabling-tracing_ossm-custom-resources-v2x

**Comment by jpkrohling** [comment]
It does, perhaps just add a mention + link, in case people haven't seen this other doc before seeing this option?

**Comment by JStickler** [comment]
@jpkrohling  there's not really an easy way to drop a link where we need one (file structure restrictions).  Reading between the lines here, is the concern that the setting is to have Envoy sample 100% of traces?  Since I can't link to the other topic, should we modify this value to be lower? Or are you OK with closing this issue?

**Comment by jpkrohling** [comment]
I'm OK with closing this one here. The concern is only that the notation on service mesh isn't used anywhere else that I'm aware of, so it might not be immediately clear to users what the value translates to, but if it's being mentioned elsewhere, we are covered.
