### ISSUE TITLE
[enterprise-3.11] Issue in file install_config/configuring_azure.adoc

### ISSUE THREAD

**Issue by rhatbob** [openshift/openshift-docs#27643]
### Which section(s) is the issue in?
Configuring OpenShift Container Platform for Azure using Ansible

### What needs fixing?
> You can configure OpenShift Container Platform for Azure at installation time **or by running the Ansible inventory file after installation.**

The above-highlighted section should either be updated or removed, as it leads to believe Azure File can be run as day-2 operation by **running the Ansible inventory file**. 

The only two ways to add Azure File storage support to a cluster would be:
- By either doing it at installation time (updating the inventory file, adding the azure variables and deploy de cluster).
- Or doing it manually, as highlighted lower in that same doc section: https://docs.openshift.com/container-platform/3.11/install_config/configuring_azure.html#manually-configuring-for-azure_configuring-for-azure

**Comment by vikram-redhat** [comment]
@bobfuru - no rush, when you are able to in the next sprint.

**Comment by bobfuru** [comment]
Created https://github.com/openshift/openshift-docs/pull/31243, under review

**Comment by bobfuru** [comment]
Thank you for reporting this and for the suggested edit, @rhatbob (nice handle, too!). The change has been implemented and is published live in 3.11 docs: https://docs.openshift.com/container-platform/3.11/install_config/configuring_azure.html#azure-configuring-ansible_configuring-for-azure

Closing this issue.
