### ISSUE TITLE
[enterprise-4.6] Issue in file service_mesh/v2x/ossm-custom-resources.adoc

### ISSUE THREAD

**Issue by rvansa** [openshift/openshift-docs#27641]
The [reference for SMCP|https://docs.openshift.com/container-platform/4.6/service_mesh/v2x/ossm-custom-resources.html#ossm-cr-parameters_ossm-custom-resources-v2x] is incomplete (see below).

In addition to that the options are not hyperlinks ('For more information, see Table 2') and that makes it hard to navigate, compared to Istio community reference. It would be convenient to display a complete tree leading to the detailed section about the option.

### Which section(s) is the issue in?

ServiceMeshControlPlane parameters

### What needs fixing?

For example `spec.runtime` says that there's `components` and `defaults` but no details whatsover. The same situation is for `security`. Basically unless the type is scalar and there's a hyperlink leading somewhere, the documentation is missing.

**Comment by rvansa** [comment]
/remove-lifecycle stale

Is there no issue review cycle in this project?

**Comment by bergerhoffer** [comment]
@JStickler Could your team take a look at this one?

**Comment by JStickler** [comment]
Created https://issues.redhat.com/browse/OSSMDOC-283 to track this.

**Comment by rvansa** [comment]
/remove-lifecycle rotten

Though it really looks like rotting away without any interest.

**Comment by JStickler** [comment]
@rvansa Our JIRA is still open (so even if this Issue closes, that JIRA is still open), and I'm lobbying to get back to work on updating the configuration reference, but we've had other priorities for our small docs team.
