### ISSUE TITLE
[enterprise-3.11] Issue in file install_config/router/default_haproxy_router.adoc

### ISSUE THREAD

**Issue by namloc2001** [openshift/openshift-docs#27651]
### Which section(s) is the issue in?
Hi, not sure if this is the correct mechanism for this, but is there an equivalent of this page for OpenShift 4.x? I'm looking for details regarding DDoS protection configuration.

**Comment by bergerhoffer** [comment]
@bmcelvee Do you know anything about whether these docs should've been brought forward to 4.x? I couldn't find anything on DDoS in 4.x and wasn't sure if you knew any history on this.

**Comment by bmcelvee** [comment]
Apologies for the delay! I do not know the history on this one.
