### ISSUE TITLE
Cannot send a mention to @openshift/team-documentation.

### ISSUE THREAD

**Issue by kurokobo** [openshift/openshift-docs#27678]
### Which section(s) is the issue in?

[Create content or edit existing content](https://github.com/openshift/openshift-docs/blob/master/contributing_to_docs/create_or_edit_content.adoc)

### What needs fixing?

Sorry for trivial issue.

According to [Create content or edit existing content](https://github.com/openshift/openshift-docs/blob/master/contributing_to_docs/create_or_edit_content.adoc), I should tag the PR with @openshift/team-documentation.

> 4. Tag the documentation team with @openshift/team-documentation.

But the team @openshift/team-documentation is visible for the members of organization only, and I'm not a member. Therefore it seems that I can't send a mention to the team. Even if I write team's name in issues or PR comments, it will look unlinked and plain text.

I've created some PRs, but is there any way to request to the team for review?

**Comment by kurokobo** [comment]
Just plain text...
![image](https://user-images.githubusercontent.com/2920259/100369479-45195a00-3048-11eb-9cde-6b46b0875475.png)

**Comment by jboxman** [comment]
@vikram-redhat FYI

**Comment by vikram-redhat** [comment]
Thanks @kurokobo. I have updated the instructions to recommend tagging team-documentation for folks within the openshift org, and myself otherwise.
