### ISSUE TITLE
[enterprise-4.6] Issue in file builds/running-entitled-builds.adoc

### ISSUE THREAD

**Issue by b-mchugh** [openshift/openshift-docs#27686]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.6/builds/running-entitled-builds.html#builds-create-imagestreamtag_running-entitled-builds
https://docs.openshift.com/container-platform/4.6/builds/running-entitled-builds.html#builds-source-secrets-entitlements_running-entitled-builds
https://docs.openshift.com/container-platform/4.6/builds/running-entitled-builds.html#builds-source-input-subman-config_running-entitled-builds

### What needs fixing?
The Prerequisites step for all three above sections are too vague.

**Creating an ImageStreamTag to the Red Hat Universal Base Image**
Prerequisites:
"You must create a pull secret for registry.redhat.io, and link it to a user project."

How?
Minimally a link to existing steps needed.

**Adding subscription entitlements as a build secret**
Prerequisites:
"You must have access to Red Hat entitlements through your subscription, and the entitlements must have separate public and private key files."

From where?
The cluster itself has no such public and private keys, clusters are no longer registered through the Customer Portal as subscriptions are handled by Subscription Watch so there is nothing to download from the Customer Portal.

**Adding Subscription Manager configurations to builds**
Prerequisites:
"You must have access to the Subscription Manager’s configuration and certificate authority files."

From where?
There is no rhsm.conf available on any of the nodes on the cluster.

**Comment by rolfedh** [comment]
Transferred to https://issues.redhat.com/browse/RHDEVDOCS-2777

**Comment by b-mchugh** [comment]
cares go stale after 90d of inactivity.
