### ISSUE TITLE
[enterprise-4.6] Issue in file networking/routes/route-configuration.adoc

### ISSUE THREAD

**Issue by tux-o-matic** [openshift/openshift-docs#27689]
### Which section(s) is the issue in?
[Creating a route through an Ingress object](https://docs.openshift.com/container-platform/4.6/networking/routes/route-configuration.html#nw-ingress-creating-a-route-via-an-ingress_route-configuration)

### What needs fixing?
Kubernetes SIG Network has graduated the widely used Ingress API to general availability in Kubernetes 1.19 (OCP 4.6).
The example in the documentation should be updated to reference *networking.k8s.io/v1* instead of *networking.k8s.io/v1beta1*.
And eventually any change in structure of the YAML structure that might come with it.

**Comment by jboxman** [comment]
@tux-o-matic, this is fixed, thanks!
