### ISSUE TITLE
OLM Restricted Network Requires Openshift Client `oc` from Linux

### ISSUE THREAD

**Issue by MichaelWasher** [openshift/openshift-docs#27696]
### Which section(s) is the issue in?
https://github.com/openshift/openshift-docs/blob/master/operators/admin/olm-restricted-networks.adoc

### What needs fixing?
There should be a disclaimer somewhere noting that the Mac and Windows versions of `oc` are unable to complete this tutorial.

The `oc` tool does not include the `oc adm catalog build` command in the Mac / Windows versions of the tool.
https://github.com/openshift/oc/blob/master/pkg/cli/admin/catalog/build.go#L1

**Comment by bergerhoffer** [comment]
@soltysh Do you know if we have this discrepancy with `oc` where they don't have the `oc adm catalog build` command on Mac/Windows?

**Comment by rolfedh** [comment]
@bergerhoffer I came across this admonition in modules/olm-understanding-operator-catalog-images.adoc

When creating custom catalog images, previous versions of {product-title} 4 required using the `oc adm catalog build` command, which has been deprecated for several releases. With the availability of Red Hat-provided index images starting in {product-title} 4.6, catalog builders should start switching to using the `opm index` command to manage index images before the `oc adm catalog build` command is removed in a future release.

**Comment by soltysh** [comment]
> @soltysh Do you know if we have this discrepancy with `oc` where they don't have the `oc adm catalog build` command on Mac/Windows?

There were some dependancy issues, iirc, and what @rolfedh wrote about `opm` is reasonable iirc.

**Comment by bergerhoffer** [comment]
Thanks @rolfedh!

And thanks @soltysh! Quick followup though, that message that @rolfedh found says that `oc adm catalog build` is deprecated, but if I run `oc adm catalog build --help` (using oc version 4.7.2), I don't see a message saying that it's deprecated. Should there be one?

Then for this actual issue, @adellape do you think you'd be able to look into the right `opm index` commands to use in the files mentioned above instead of `oc adm catalog build`?

**Comment by adellape** [comment]
The `oc adm catalog build` command is only relevant for catalogs using the [Package Manifest Format](https://docs.openshift.com/container-platform/4.6/operators/admin/olm-managing-custom-catalogs.html#olm-managing-custom-catalogs-package-manifest-format), which itself is also [deprecated](https://docs.openshift.com/container-platform/4.7/release_notes/ocp-4-7-release-notes.html#ocp-4-7-deprecated-removed-features). The `opm index` command is only relevant for catalogs using the [Bundle Format](https://docs.openshift.com/container-platform/4.6/operators/admin/olm-managing-custom-catalogs.html#olm-managing-custom-catalogs-package-manifest-format).

So we can't just swap the commands to use `opm index`, but if the Mac/Win version of `oc` doesn't even have `adm catalog build` available, then that seems worth mentioning for the remaining (albeit deprecated) procedures.
