### ISSUE TITLE
[enterprise-4.6] Issue in file logging/cluster-logging-external.adoc

### ISSUE THREAD

**Issue by tux-o-matic** [openshift/openshift-docs#27702]
### Which section(s) is the issue in?
Description of lines in YAML of [Forwarding application logs from specific projects](https://docs.openshift.com/container-platform/4.6/logging/cluster-logging-external.html#cluster-logging-collector-log-forward-project_cluster-logging-external)

### What needs fixing?
The description *10* says *Optional: A label to add to the logs* but that number in the YAML is placed on ```outputRefs```and everything after that is off. The description list ends at *11* but there is a *12* in the YAML.

**Comment by rolfedh** [comment]
Thanks for reporting this, @tux-o-matic. The numbering issue has been corrected. @jboxman, would you mind closing this issue? Thanks.
