### ISSUE TITLE
[enterprise-4.5] Issue in file support/troubleshooting/troubleshooting-storage-issues.adoc

### ISSUE THREAD

**Issue by ableischwitz** [openshift/openshift-docs#27701]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.5/support/troubleshooting/troubleshooting-storage-issues.html

### What needs fixing?
"
    If you encounter a multi-attach error message with an RWO volume, you can either recover or delete the failed node to make the volume available to other nodes.
"

As per https://bugzilla.redhat.com/show_bug.cgi?id=1884643 removing a non-responsive node from OpenShift VMWare IPI may result in removed vmdks on VMWare and thus lead to data-loss.

The BZ also states that it would be better to forcefully remove the pods to have OpenShift clean up the storage attachments.

**Comment by ableischwitz** [comment]
/remove-lifecycle stale

This data-loss scenario should be mentioned in the docs to prevent such scenario.

**Comment by jboxman** [comment]
cc @bobfuru

**Comment by bobfuru** [comment]
Thank you, ableischwitz. I've added a note about data loss per your suggestion. See https://github.com/openshift/openshift-docs/pull/30116.
