### ISSUE TITLE
[enterprise-4.6] Issue in file installing/install_config/installing-customizing.adoc

### ISSUE THREAD

**Issue by iranzo** [openshift/openshift-docs#27700]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.6/installing/install_config/installing-customizing.html#installation-special-config-crony_installing-customizing

### What needs fixing?

Daemon is called `chrony` so there's a typo in the bookmark anchor

**Comment by codyhoag** [comment]
@iranzo the bookmark anchor matches the title and section. Can you elaborate on what you mean here? Maybe I'm missing something.

**Comment by iranzo** [comment]
@codyhoag  the program is named CHRONY with 'h' the bookmark and section might require a typo fix as well :-)

**Comment by codyhoag** [comment]
@iranzo good call; I completely missed that! I'll go ahead and update that. :+1:

**Comment by codyhoag** [comment]
#27736 has been merged. Thanks again!
