### ISSUE TITLE
[enterprise-4.5] Issue in file installing/installing_bare_metal/installing-bare-metal.adoc

### ISSUE THREAD

**Issue by kfryklund** [openshift/openshift-docs#27716]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.6/installing/installing_bare_metal/installing-bare-metal.html#installation-approve-csrs_installing-bare-metal

### What needs fixing?
It's a very small issue with the order of operations.  In UPI baremetal deployments, you won't see any new nodes until you sign the CSR's.  The documentation implies that you'll see the nodes, and then need to sign CSR's AFTER you're able to see them with "oc get nodes".

When deploying a new cluster, I only saw my master nodes with "oc get nodes".  Only after signing all pending CSRs was I able to list the worker nodes that I needed to add.

This lead me to believe that my new nodes were not deployed correctly, when in fact, they were available all along.

**Comment by codyhoag** [comment]
Thanks for this suggestion! This was fixed in #29143. Since that has merged, I'm closing this issue.
