### ISSUE TITLE
[enterprise-4.5] Issue in file backup_and_restore/replacing-unhealthy-etcd-member.adoc

### ISSUE THREAD

**Issue by apurty** [openshift/openshift-docs#27741]
### Which section(s) is the issue in?
In the section "Replacing an unhealthy etcd member whose machine is not running or whose node is not ready"
In the "Procedure" section, under step 3.c

https://docs.openshift.com/container-platform/4.5/backup_and_restore/replacing-unhealthy-etcd-member.html#restore-replace-stopped-etcd-member_replacing-unhealthy-etcd-member

### What needs fixing?
Under step 3.c, we can add additional sub-steps to remove the following portions from the new-master-machine.yaml file:
- Remove the 'metadata.annotations'  and 'metadata.generations' field:
~~~
metadata:
  annotations:
    machine.openshift.io/instance-state: running
  creationTimestamp: "2020-12-01T09:59:18Z"
  finalizers:
  - machine.machine.openshift.io
  generation: 2
~~~

- Remove the 'metadata.resourceVersion' and 'metadata.uid' field:
~~~
resourceVersion: "12836"
uid: a5658f0a-dbc2-4dee-841b-ee71c3b90d05
~~~

**Comment by bergerhoffer** [comment]
@apurty Thanks for submitting this. The updates were made with PR #30922, and should be live within a few hours.
