### ISSUE TITLE
[enterprise-4.6] Issue in file pipelines/creating-applications-with-cicd-pipelines.adoc

### ISSUE THREAD

**Issue by ghurel-rh** [openshift/openshift-docs#27743]
### Which section(s) is the issue in?
Assembling a Pipeline

### What needs fixing?
In the Pipeline YAML, a workspace is declared for the last task (update-deployment), but the associated TaskRun object does not declare one, leading to the failure of the associated TaskRun and of the whole pipeline.

```
$ oc get taskrun
...
build-and-deploy-run-rv2jb-update-deployment-qhktv   False       TaskRunValidationFailed   29m
...

$ oc describe taskrun build-and-deploy-run-rv2jb-update-deployment-qhktv
...
  Warning  Failed         29m   TaskRun  bound workspaces did not match declared workspaces: provided extra values: [source]
  Warning  InternalError  29m   TaskRun  1 error occurred:
           * bound workspaces did not match declared workspaces: provided extra values: [source]
...
```

**Comment by Preeticp** [comment]
@ghurel-rh thank you for raising this issue, we have a [related issue in our Jira backlog](https://issues.redhat.com/browse/RHDEVDOCS-2743). I have added a link to this issue there. We will fix both of them together.

**Comment by sounix000** [comment]
Docs PR with LGTMs: https://github.com/openshift/openshift-docs/pull/31271

**Comment by sounix000** [comment]
\close
