### ISSUE TITLE
[enterprise-4.6] Issue in file pipelines/creating-applications-with-cicd-pipelines.adoc

### ISSUE THREAD

**Issue by ghurel-rh** [openshift/openshift-docs#27742]
### Which section(s) is the issue in?
Assembling a Pipeline

### What needs fixing?
In the Pipeline YAML, the git-revision parameter default value is set to 'release-tech-preview-3'. However, on the two target git repo (vote-ui and vote-api), only release-tech-preview-1 and release-tech-preview-2 branches exist.

**Comment by bergerhoffer** [comment]
@Preeticp Here is another pipelines issue, if your team can take a look. Thanks!

**Comment by Preeticp** [comment]
Thank you @ghurel-rh for raising this issue.  It is being tracked via this [Jira issue](https://issues.redhat.com/browse/RHDEVDOCS-2863)

**Comment by sounix000** [comment]
lifecycle/close

**Comment by sounix000** [comment]
See https://github.com/openshift/openshift-docs/pull/33246#issuecomment-904410099 for reason of closing.
