### ISSUE TITLE
[enterprise-4.6] Issue in file authentication/ldap-syncing.adoc

### ISSUE THREAD

**Issue by germanparente** [openshift/openshift-docs#27766]
Since I have had several customers hitting this issue, I would like to submit this issue. It's not extremely important but it could help.

### Which section(s) is the issue in?
- About the Active Directory configuration file
- About the augmented Active Directory configuration file
- LDAP nested membership sync example

In the three sections above, the examples are about Active Directory and the filter is

(objectclass=inetorgperson)

In general, AD does not include this objectclass by default. Most of the customers are copying the example literally and changing few parameters. They fail to change the filter and they open a case.

I would suggest to replace:
(objectclass=inetorgperson)
by 
(objectclass=person)

even if it's an example, as customers are copying it literally, it could help to include an objectclass that is present in the ldap schema of active directory by default.

Apologies for the noise.

Thanks a lot,

German.

**Comment by bergerhoffer** [comment]
@germanparente Can you take a look at this PR and let me know if this is the update you were looking for? Thanks!

PR: https://github.com/openshift/openshift-docs/pull/30796
Preview: https://deploy-preview-30796--osdocs.netlify.app/openshift-enterprise/latest/authentication/ldap-syncing.html
