### ISSUE TITLE
[enterprise-4.5] Issue in file installing/installing_ibm_z/installing-ibm-z.adoc

### ISSUE THREAD

**Issue by R3dje** [openshift/openshift-docs#27818]
### Which section(s) is the issue in?
Minimal requirements for IBM Z on 4.2 to 4.5 is 3 IFL's
Minimal requirements For IBM Z on 4.6 is 6 IFL's

Is this a typo?
Because the preferred requirements are 6 IFL's for all versions....

### What needs fixing?
What I stated above :)

**Comment by vikram-redhat** [comment]
@SNiemann15 can you take a look?

**Comment by SNiemann15** [comment]
@R3dje It's correct like its written in the docs. We have raised the minimum to 6 IFLs in 4.6. 
Preferred reqs have always been higher with 6 IFLs.

**Comment by R3dje** [comment]
Thanks @SNiemann15 for the clarification.
