### ISSUE TITLE
[enterprise-4.6] Issue in file installing/installing_openstack/installing-openstack-installer-custom.adoc

### ISSUE THREAD

**Issue by martineg** [openshift/openshift-docs#27863]
### Which section(s) is the issue in?

*Defining parameters for the installation program*

### What needs fixing?

Instructions for trusting a self-signed CA issued certificate on the RHOSP endpoints are Linux specific.
If running the installer on a Mac, to trust the self-signed RHOSP self-signed CA certificate the following command could be used:
```bash
$ security add-trusted-cert -r trustRoot ca.crt.pem
```

When trusting the self-signed CA certificate this way there is no need to mention the cacert explicitly in the clouds.yaml file.

**Comment by maxwelldb** [comment]
Closing due to relevant versions falling out of support. If this issue is still valid, re-open against a supported version.
