### ISSUE TITLE
[enterprise-4.6] Issue in file support/gathering-cluster-data.adoc

### ISSUE THREAD

**Issue by pamoedom** [openshift/openshift-docs#27862]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.6/support/gathering-cluster-data.html#about-must-gather_gathering-cluster-data

### What needs fixing?

Audit logs are no longer collected by default to reduce the size of the log bundle, this was suppressed via [this commit](https://github.com/openshift/must-gather/commit/7b3fff50ac06fa3dd288aaf55679d46a53db8a84#diff-bad6eb3f5953b7f47f014fd8b04a48470c1d64d94bbd29566af842f0b60c909c).

If needed, the audit logs can be gathered again on the following manner:

~~~
$ oc adm must-gather -- /usr/bin/gather_audit_logs
~~~

or, if needed, they can be gathered together with the regular logs on the following manner:

~~~
$ oc adm must-gather -- /usr/bin/bash -c '/usr/bin/gather ; /usr/bin/gather_audit_logs'
~~~

Best Regards.

**Comment by mburke5678** [comment]
@sferich888 Do we want to document this funtionality? Or, is there a specific reason not to?

**Comment by sferich888** [comment]
@mburke5678 yes we want to document this; however its 'kinda' already documented (to some degree). 
We probably want to do a better job of describing/explaining the 'optional' scripts that users can run in each image; but that is likely to be an undertaking...

**Comment by mburke5678** [comment]
@pamoedom Can you please take a look at [my PR for this issue](https://github.com/openshift/openshift-docs/pull/38415) and let me know if it meets your expectations.

**Comment by pamoedom** [comment]
Thanks @mburke5678, I've replied there with my suggestions.
Regarding OCP versions, I think it would be recommended to reflect that from 4.6 onwards.

**Comment by mburke5678** [comment]
PR is merged. Closing
