### ISSUE TITLE
[enterprise-4.6] Issue in file nodes/scheduling/nodes-scheduler-taints-tolerations.adoc

### ISSUE THREAD

**Issue by apolymen** [openshift/openshift-docs#27920]
### Which section(s) is the issue in?

Tolerating all taints
https://docs.openshift.com/container-platform/4.6/nodes/scheduling/nodes-scheduler-taints-tolerations.html#nodes-scheduler-taints-tolerations-all_nodes-scheduler-taints-tolerations

### What needs fixing?

"You can configure a node" should be "You can configure a pod"

**Comment by jboxman** [comment]
@mburke5678 FYI

**Comment by mburke5678** [comment]
@apolymen Thanks for catching this!
