### ISSUE TITLE
[enterprise-4.6] Issue in file installing/installing_bare_metal/installing-bare-metal.adoc

### ISSUE THREAD

**Issue by max-allan-surevine** [openshift/openshift-docs#27946]
### Which section(s) is the issue in?
Required machines vs Three node cluster.

### What needs fixing?
The required machines section states "The smallest OpenShift Container Platform clusters require" ... 1 temp, 3 control, 2 workers.
Then in the "Three Node Cluster" section it says you don't need the workers. So the smallest cluster _doesn't_ require 2 workers. Which of these sections is lying? What else is a lie? Do I really _need_ 4CPU and 16GB per control node?

**Comment by codyhoag** [comment]
For bare metal, either 0 (for three node clusters) or 2+ workers (all other BM installs) is supported. A cluster with one worker machine is not supported. I will update the doc so that is clearer.
