### ISSUE TITLE
[enterprise-4.6] Issue in file installing/installing_bare_metal/installing-restricted-networks-bare-metal.adoc

### ISSUE THREAD

**Issue by af778998** [openshift/openshift-docs#27987]
### Which section(s) is the issue in?
Advanced RHCOS installation reference/Routing and bonding options at RHCOS boot prompt

### What needs fixing?
it looks like the order of "nameserver" and "ip" options is important.
when we specified nameserver before ip, for example like 
nameserver=4.4.4.41 ip=10.10.10.2::10.10.10.254:255.255.255.0:core0.example.com:enp1s0:none 
(instead of 
ip=10.10.10.2::10.10.10.254:255.255.255.0:core0.example.com:enp1s0:none nameserver=4.4.4.41)

the nameserver settings were not configured and resolv.conf was missing (when it nameserver is after ip, then it worked)

What needs fixing: probably this should be documented, that the order is important?
It would also be nice to get example on how to disable dhcp on an interface (e.g. if there are 2 interfaces with uplinks and only one is being used, then on the other one will be tried dhcp and there are timeouts - will something like this work?
ip=10.10.10.2::10.10.10.254:255.255.255.0:core0.example.com:enp1s0:none ip=::::core0.example.com:enp2s0:none 
)

**Comment by bobfuru** [comment]
@af778998 Thank you so much for creating this issue and for providing the example!

This update has been reviewed, approved, merged, and is now live in OCP 4.6+ docs. For example, 4.7 link: https://docs.openshift.com/container-platform/4.7/installing/installing_bare_metal/installing-bare-metal.html#installation-user-infra-machines-static-network_installing-bare-metal.
