### ISSUE TITLE
[enterprise-4.6] Issue in file nodes/nodes/nodes-nodes-rebooting.adoc

### ISSUE THREAD

**Issue by apolymen** [openshift/openshift-docs#28020]
### Which section(s) is the issue in?

Understanding infrastructure node rebooting
https://docs.openshift.com/container-platform/4.6/nodes/nodes/nodes-nodes-rebooting.html#nodes-nodes-rebooting-infrastructure_nodes-nodes-rebooting

### What needs fixing?
"The nodes to run the infrastructure are called **master** nodes" should be "The nodes to run the infrastructure are called **infra** nodes"

**Comment by mburke5678** [comment]
@apolymen Thanks for reaching out. In Openshift 4.x, if I understand correctly, the `infra` nodes are not deployed by default, You can create them, if needed. In 4.x the default node roles are `master` and `worker`, as shown (I removed the IP address from the node names). I'm not sure if your comment is relevant tn the 4.x docs. Please let me know if I do not understand your comment correctly. 

```
NAME           STATUS   ROLES    AGE     VERSION
ec2.internal   Ready    worker   6h52m   v1.20.0+e1bc274
ec2.internal   Ready    master   8h      v1.20.0+e1bc274
ec2.internal   Ready    worker   8h      v1.20.0+e1bc274
ec2.internal   Ready    worker   8h      v1.20.0+e1bc274
ec2.internal   Ready    master   8h      v1.20.0+e1bc274
ec2.internal   Ready    master   8h      v1.20.0+e1bc274
ec2.internal   Ready    worker   8h      v1.20.0+e1bc274

```

**Comment by apolymen** [comment]
@mburke5678 My comment refers to the sentence which says "The nodes to run the infrastructure are called **master** nodes". I guess it should say **infrastructure** instead of **master**.

**Comment by mburke5678** [comment]
@apolymen I believe that the infrastructure components run on the master nodes now; we do not use infra nodes by default. I will verify to be certain. Is this more clear?
```
When rebooting the master nodes, which host critical {product-title} infrastructure components,
ensure that there are at least three nodes available to run these components. 
```

**Comment by apolymen** [comment]
@mburke5678 It's true that infra nodes are not deployed by default in 4.x. But, if I'm not mistaken, after the initial cluster installation, infrastructure components like routers, registry, monitoring and logging, get deployed on worker nodes and not master nodes. At least that was my experience with 4.4. You can check that with the engineering or architecture team.

**Comment by mburke5678** [comment]
@apolymen You are correct. How about:
_When rebooting nodes that host critical OpenShift infrastructure components, such as the routers, the registry, and monitoring, ensure that there are at least three nodes available to run these components. _

**Comment by apolymen** [comment]
@mburke5678 Yes, I guess it describes correctly the situation in general. You may need to adjust the rest of the paragraph accordingly to fit this in.

**Comment by mburke5678** [comment]
@apolymen Thanks for your help with this. Do you mind taking a look at https://github.com/openshift/openshift-docs/pull/30492 to see if the changes meet your expectations and understanding before I ask for QE input?

**Comment by apolymen** [comment]
@mburke5678 You also need to change the paragraph title from "Understanding how to reboot master nodes running critical infrastructure" to "Understanding how to reboot nodes running critical infrastructure". Just remove the word "master".

**Comment by mburke5678** [comment]
@sunilcio Is this an issue you can review for QE?

**Comment by sunilcio** [comment]
Added a comment in that PR, thanks.

**Comment by mburke5678** [comment]
Merged PR. Thanks again @apolymen
