### ISSUE TITLE
[dedicated] Issue in file welcome/index.adoc

### ISSUE THREAD

**Issue by squirrd** [openshift/openshift-docs#28021]
### Which section(s) is the issue in?
The OSD documentation is missing an entire section for Metering.  Similar to what is available in OCP
https://docs.openshift.com/container-platform/4.5/metering/metering-about-metering.html

This became available in OSD v4.4 (I think).  I assisted an OSD CU to install it previously as it became available and just assisted the CU to troubleshoot an issue. In case 02814580 && 02801849.  This section can be confirmed with the BU or Product Managers.

Thanks
David Squirrell

**Comment by mburke5678** [comment]
@squirrd Thanks for pointing this out. It seems that the Metering book was never added to OSD. @sfortner-RH I believe you are the Dedicated writer? is this something you can look into?
