### ISSUE TITLE
[enterprise-4.6] Issue in file service_mesh/v2x/ossm-custom-resources.adoc

### ISSUE THREAD

**Issue by aelicieguo** [openshift/openshift-docs#28045]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.6/service_mesh/v2x/ossm-custom-resources.html#ossm-cr-istio-global_ossm-custom-resources-v2x

tried to add global config as such ant smcp doesn't take effect:
spec:
  istio:
    global:
      mtls:
        enabled: false

### What needs fixing?
This works
spec:
  techPreview:
    global:
      mtls:
        enabled: false

**Comment by JStickler** [comment]
Created https://issues.redhat.com/browse/OSSMDOC-285 to track this.
