### ISSUE TITLE
[enterprise-4.6] Issue in file web_console/customizing-the-web-console.adoc

### ISSUE THREAD

**Issue by lukyky414** [openshift/openshift-docs#28046]
### Which section(s) is the issue in?
All

### What needs fixing?
by default, `console.operator.openshift.io` doesn't exist in OpenShift 4.6. 
It is `consoles.operator.openshift.io`

**Comment by ahardin-rh** [comment]
@lukyky414 Thank you for reporting this! I will work on the updates as soon as I can.
