### ISSUE TITLE
[enterprise-4.5] Issue in file metering/metering-troubleshooting-debugging.adoc

### ISSUE THREAD

**Issue by squirrd** [openshift/openshift-docs#28044]
### Which section(s) is the issue in?
Not enough compute resources

### What needs fixing?
I don't think there is enough information in here to troubleshoot this operator well.  I just created the following KCS that may assist in improving the `Not enough compute resources` section.
https://access.redhat.com/solutions/5640401

The key information that could be added is:
- How to check for OOMKilled states
- Knowing which object needs to be altered so the resource limits to take effect. `meteringconfig/operator-metering`
- What the sensible defaults are and that if the defaults are double and there are still issues it might be time to look for an underlying issue or reach out to support.

**Comment by lbarbeevargas** [comment]
@squirrd This issue has been addressed and the content was added/merged in https://github.com/openshift/openshift-docs/pull/30798.
