### ISSUE TITLE
[enterprise-4.6] Issue in file service_mesh/v2x/ossm-traffic-manage.adoc

### ISSUE THREAD

**Issue by aelicieguo** [openshift/openshift-docs#28077]
### Which section(s) is the issue in?
All the yaml files in this page, should the apiVersion be 

"apiVersion: networking.istio.io/v1beta1", instead of 
"apiVersion: networking.istio.io/v1alpha3"

### What needs fixing?
all the yaml files

**Comment by JStickler** [comment]
Created https://issues.redhat.com/browse/OSSMDOC-284 to track this.

**Comment by JStickler** [comment]
Currently both "apiVersion: networking.istio.io/v1alpha3" and "apiVersion: networking.istio.io/v1beta1" are documented in the Istio upstream docs.

https://istio.io/latest/docs/reference/config/networking/virtual-service/
