### ISSUE TITLE
[enterprise-4.6] Issue in file post_installation_configuration/machine-configuration-tasks.adoc

### ISSUE THREAD

**Issue by spasche** [openshift/openshift-docs#28111]
### Which section(s) is the issue in?

Configuring container image registry settings

### What needs fixing?

It is described to add the `unqualified-search-registries` configuration to the `/etc/containers/registries.d/99-worker-unqualified-search-registries.conf` file.

However, on OKD 4.6 that should be in `/etc/containers/registries.conf.d/99-worker-unqualified-search-registries.conf` (Notice the *.conf.d*).

There's also a typo with `registries.s`.

Moreover, I would suggest to create the file with permission 0644 instead of 0420, so that it's readable by non-privileged users and is aligned with the permission of other files such as `/etc/containers/registries.conf`.

**Comment by ahardin-rh** [comment]
This issue is now addressed in https://github.com/openshift/openshift-docs/pull/30820 and https://github.com/openshift/openshift-docs/pull/30805
