### ISSUE TITLE
[enterprise-4.6] Issue in file cli_reference/opm-cli.adoc

### ISSUE THREAD

**Issue by jeichler** [openshift/openshift-docs#28154]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.6/cli_reference/opm-cli.html#olm-installing-opm_opm-cli , point 3

### What needs fixing?

it is 
```
oc image extract registry.redhat.io/openshift4/ose-operator-registry:v4.6 \
    --path /usr/bin/opm:. \
    --confirm
```

instead of /usr/bin/*registry*/opm

**Comment by jboxman** [comment]
@adellape FYI

**Comment by bergerhoffer** [comment]
@adellape @skrthomas Here is another one related to the opm path. Can you guys confirm if this one is now resolved?

**Comment by adellape** [comment]
The `opm` install instructions were updated to now show downloading the binary from the OpenShift mirror site:

https://docs.openshift.com/container-platform/4.6/cli_reference/opm-cli.html#olm-installing-opm_opm-cli
