### ISSUE TITLE
[enterprise-4.6] Issue in file registry/configuring_registry_storage/configuring-registry-storage-vsphere.adoc

### ISSUE THREAD

**Issue by patrickstrick** [openshift/openshift-docs#28150]
### Which section(s) is the issue in?
Creating registry storage \ Configuring block registry storage for VMware vSphere
Creating registry storage \ Configuring registry storage for VMware vSphere

### What needs fixing?
Need to change to openshift-image-registry project before running configuration commands
oc project openshift-image-registry

**Comment by bmcelvee** [comment]
This issue and https://github.com/openshift/openshift-docs/issues/29904 look to be the same. I'll open a PR to resolve both.
