### ISSUE TITLE
[enterprise-4.6] Issue in file nodes/edge/nodes-edge-remote-workers.adoc

### ISSUE THREAD

**Issue by mschmitt25414** [openshift/openshift-docs#28167]
### Which section(s) is the issue in?
If a zone is fully disrupted, where all nodes in the zone have a Ready condition that is False or Unknown, the control plane does not apply the taint 

### What needs fixing?
There needs to be some clarity around what taint is (or in this case isn't) applied when using zones for remote worker nodes.

**Comment by mburke5678** [comment]
PR is merged
