### ISSUE TITLE
Where can we find clientid and clientsecret to create oAuth custom client

### ISSUE THREAD

**Issue by rajasekaran07** [openshift/openshift-docs#2816]
Hello Team,

I am trying to import Openshift plugin in Eclipse Che by following "https://eclipse-che.readme.io/docs/openshift-config". Here I am struggling to register a custom oAuth client in my OpenShift master node.
I am not familiar with OpenShift concepts. I dont know where can I get these clientid and clientsecret.
Can someone kindly suggest on this.
Regards,
Raja

**Comment by liggitt** [comment]
when you create the oauthclient API object, you choose a client_id and client_secret

**Comment by bfallonf** [comment]
@liggitt thanks for answering @rajasekaran07 

This information seems to be documented in https://github.com/openshift/openshift-docs/blob/80b959aa5907d7190e67b38bd43cb2f65dc1f5c3/architecture/additional_concepts/authentication.adoc#oauth

I'll close this issue, but if there's anything that needs to be documented, please let me know and we can go from there.
