### ISSUE TITLE
[enterprise-4.6] Issue in file installing/installing_vsphere/installing-vsphere-installer-provisioned-customizations.adoc

### ISSUE THREAD

**Issue by lautou** [openshift/openshift-docs#28191]
### Which section(s) is the issue in?

Prerequisites

### What needs fixing?

Precise which resource pool is selected by the installer since there is no possibility to specify a resource pool in the install-config.yaml.

**Comment by lautou** [comment]
Hi any update for this ticket?

**Comment by codyhoag** [comment]
@staebler do you have any guidance on what we could include in the [vSphere IPI prereqs](https://docs.openshift.com/container-platform/4.7/installing/installing_vsphere/installing-vsphere-installer-provisioned-customizations.html#prerequisites) section for the resource pool selected by the installer?

**Comment by lautou** [comment]
Hi any update?

**Comment by lautou** [comment]
Hi any update for this?
