### ISSUE TITLE
[enterprise-4.6] Issue in file installing/installing_vsphere/installing-vsphere.adoc

### ISSUE THREAD

**Issue by justin-cohesity** [openshift/openshift-docs#28200]
### Which section(s) is the issue in?

There is a missing example of the append-bootstrap.ign which existed in prior versions.
This is even more important/critical as this file has changed from prior versions, so it's not possible to look at and use an example from a prior version with 4.6.

### What needs fixing?

Please include an example of append-bootstrap.ign like prior versions of this page but updated so it works with OCP 4.6

This seems to be the needed/correct example, however, please verify:

`
{
  "ignition": {
    "config": {
      "merge": [
        {
          "source": "http://webserver/ignition/bootstrap.ign"
        }
      ]
    },
    "version": "3.1.0"
  }
}
`

**Comment by jboxman** [comment]
@codyhoag FYI

**Comment by codyhoag** [comment]
I know only bits and pieces of this. @bobfuru I think this was part of the restructure done in #27394. Can you provide any background?

**Comment by bobfuru** [comment]
This is up for discussion (https://github.com/openshift/openshift-docs/pull/28106) with a resolution coming soon. See [this](https://github.com/openshift/openshift-docs/pull/28106#issuecomment-744713076) comment about using extra config properties rather than webserver.
