### ISSUE TITLE
BestEffort is not defined

### ISSUE THREAD

**Issue by bparees** [openshift/openshift-docs#2820]
this page repeatedly refers to "besteffort" but it's not defined anywhere what besteffort means or how a pod is given a "besteffort" quality of service:
https://docs.openshift.org/latest/admin_guide/quota.html#quota-scopes

**Comment by brennv** [comment]
Added definition with wording from https://kubernetes.io/docs/admin/resourcequota/walkthrough/
Proposed PR https://github.com/openshift/openshift-docs/pull/3596

**Comment by derekwaynecarr** [comment]
See the definition here:

https://docs.openshift.org/latest/admin_guide/overcommit.html#qos-classes

**Comment by brennv** [comment]
Thanks @derekwaynecarr, I removed the definition and simply added a link to QoS Classes. The BestEffort definition is definitely clearer in the context of the other QoS class definitions.

**Comment by bparees** [comment]
from the linked doc:

>If requests and limits are not set for any of the resources, then the container is classified as BestEffort.

1) I thought you're still best effort if you have a limit, I thought best effort was purely based on not have requests set.
2) "not set for any of the resources" is unclear.  it could be read as "if all resources do not have limits and requests set" or as "if any one resource does not have a limit+request set".  I'm not sure which is correct, but it should be updated to be more clear for whatever the correct definition is.

**Comment by bmcelvee** [comment]
Issue resolved, thanks!
