### ISSUE TITLE
Links to the top level anchor broken in docs.openshift.com

### ISSUE THREAD

**Issue by brian-avery** [openshift/openshift-docs#28205]
### Which section(s) is the issue in?
All cross references in the OpenShift docs that link to a top level anchor ID.

### What needs fixing?

The OpenShift docs style says that cross references should be of the form: 

```
xref: doc.adoc#anchor[]
```

This works great for headers below the top level due to the fact that anchors are automatically generated for headers below the top level. However, for the top level headers, these are not generated. This is because asciidoc assumes that this is a title and will be controlled by the site style. A similar issue was addressed in [jekyll-asciidoctor](https://github.com/asciidoctor/jekyll-asciidoc/issues/219).

Looking at the [OpenShift styles](https://github.com/openshift/openshift-docs/blob/master/_templates/_page_openshift.html.erb#L127), we see something similar: 

```
<div class="page-header">
          <h1><%= article_title %></h1>
        </div>
```

It looks like the topic id is available [here](https://github.com/openshift/openshift-docs/blob/a372192cd28b1b2b94845f7d9070d6ce01fe465b/_templates/page.html.erb#L26). Including it as an anchor should fix the problem across the OpenShift docs site. 

@vikram-redhat Can you please help find the proper owner for this?

**Comment by jboxman** [comment]
@vikram-redhat FYI

**Comment by vikram-redhat** [comment]
Ack - and will need some discussion/followp.

**Comment by brian-avery** [comment]
This isn't fixed yet but we chose to hold off for now. 
/remove-lifecycle stale
