### ISSUE TITLE
Sync Policy section with Upstream

### ISSUE THREAD

**Issue by bysnupy** [openshift/openshift-docs#28225]
### Which section(s) is the issue in?

* Section name: [Configuring the default scheduler to control pod placement](https://docs.openshift.com/container-platform/4.6/nodes/scheduling/nodes-scheduler-default.html)

### What needs fixing?

There is not Profile information on OCPv4.6(k8s 1.19)+ docs, even though upstream(k8s) docs is providing Profile which is successor of the Policy feature. We need to add it. Refer related issue ticket, kubernetes/website#22530

~~~
With Profiles graduating to beta in 1.19, there is no motivation to continue to promote the usage of Policies.
~~~

**Comment by bysnupy** [comment]
As of OCPv4.7, warning message is shown for the Policy deprecation. Refer [here](https://github.com/openshift/cluster-kube-scheduler-operator/blob/658677dba2eab6bba74131f62915471374343245/pkg/operator/targetconfigcontroller/targetconfigcontroller.go#L294) for more details.
~~~
klog.Warningf("Setting .spec.policy is deprecated and will be removed eventually. Please use .spec.profile instead.")
~~~

**Comment by bergerhoffer** [comment]
Scheduler profiles were added as a tech preview feature in 4.7. Here are the updated docs reflecting this:

* Deprecation note in scheduler policy docs: https://docs.openshift.com/container-platform/4.7/nodes/scheduling/nodes-scheduler-default.html
* Tech preview scheduler profile docs: https://docs.openshift.com/container-platform/4.7/nodes/scheduling/nodes-scheduler-profiles.html
* TP release note: https://docs.openshift.com/container-platform/4.7/release_notes/ocp-4-7-release-notes.html#ocp-4-7-nodes-scheduler-profiles

Thanks for submitting this, closing the issue now.
