### ISSUE TITLE
Carrying this documentation with me? 

### ISSUE THREAD

**Issue by flickerfly** [openshift/openshift-docs#28245]
### Which section(s) is the issue in?

re-deploying this documentation

### What needs fixing?

Less a fix, and more an enhancement. I'm wondering if this is built into a container published somewhere already. I'd like to package it up and take it into an air gapped environment so that access especially to the API reference would be accessible to those without direct internet access while interacting with our OpenShift cluster and enhance the value. I already do this with the PDF versions, but I'd really like to give HTML access as that's easier to link to for people with questions.

If there isn't one already, is there some documentation on getting some output that I could deliver as HTML into a simple web server container. I see a .s2i directory which has me hopeful that this is a nearly solved problem.

**Comment by jboxman** [comment]
@flickerfly, I'd like to containerize the API reference documentation someday, but that's entirely out of scope of my work at Red Hat.

In any case, you can actually generate the API reference docs locally, if you'd like. The documentation for this is absent, because I wasn't anticipating any external interest, but the repo for the tool is here: https://github.com/jboxman/openshift-apidocs-gen

By default it generates `.adoc` files that build locally and can theoretically be used entirely as they are. There's a WIP document that describes the process for our team, which I can share separately if there's interest.

Also, we run the OCP docs in a container on OpenShift, so it's probably possible to just deploy our documentation on a cluster. I've never tried this, however, and I'm not sure how it's actually setup.

**Comment by flickerfly** [comment]
Thanks for the thoughts! If you could push that container into quay or something, I'd just try to deploy that. That sounds awesome! If that doesn't work I can explore the harder route.

**Comment by jboxman** [comment]
@vikram-redhat, is external consumption of our OCP docs container possible I wonder?

**Comment by vikram-redhat** [comment]
Less of a container solution but more of direct fix is to simply run the following in your local environment (after [installing the  asciibinder gem](https://github.com/openshift/openshift-docs/blob/master/contributing_to_docs/tools_and_setup.adoc#install-asciibinder-and-dependencies)):

`asciibinder package --site=commercial`

That will output the whole HTML for all versions into a folder called _package as a deployable site folder. You can copy that onto a USB to take into air gapped environments (and either server it via a local webserver, or just open up an output HTML file in a browser).

**Comment by flickerfly** [comment]
Okay, I like where that's going. 

I prefer to ship things into the repo rather than flat files for automation reasons. If I made a multistage Dockerfile that built the docs and put the html into a simple web server would you be interested in that? 

@vikram-redhat Any chance of running into any other dependencies?

**Comment by vikram-redhat** [comment]
I can't think of any reason that would not work. Check out our assemble file: https://github.com/openshift/openshift-docs/blob/master/.s2i/bin/assemble.

Not sure what you mean by us being interested in that. Do you mean we host the Dockerfile as part of this repo for others in the future who may want the same thing?

**Comment by benhosmer** [comment]
@vikram-redhat  @flickerfly  and I know each other and I'm jumping in to implement this. Would you (Red Hat or this community) be interested or offer guidance as to upstream contribution of the automation of building these docs? Meaning, perhaps a pull request back for this repo with some mechanism to build these docs within a cluster? I think some competing products already do include documentation as part of the initial install of their cluster.

**Comment by benhosmer** [comment]
@jboxman yesterday I was able to build the docs using just the Dockerfile contained here. I also see a Jenkinsfile here too that seems to get pretty far and perhaps is even being used currently internally by Red Hat or Openshift?

Do you have any thoughts on a path forward without duplicating work across multiple private clusters?

I suspect we may not be the only consumers that might want to do this.

**Comment by jboxman** [comment]
@benhosmer, oh, when I tried I wasn't able to get a build through the OCP build system. I actually ended up with a segfault or something. I hadn't tried just the Dockerfile itself.

I don't think internally, we have cycles to do anything regarding docs portability; I spend my days on OCP networking docs. Any contribution that provides a mechanism for this is surely welcome, though!
