### ISSUE TITLE
[logging] document how to use systemd journal support

### ISSUE THREAD

**Issue by richm** [openshift/openshift-docs#2824]
Need to document the fluentd and deployer parameters `use-journal`, `journal-source`, and `journal-read-from-head` as described in https://github.com/openshift/origin-aggregated-logging/tree/master/deployer#create-deployer-configmap and https://github.com/openshift/origin-aggregated-logging/tree/master/deployer#have-fluentd-use-the-systemd-journal-as-the-log-source

**Comment by vikram-redhat** [comment]
Thanks @richm . Tracking here: https://bugzilla.redhat.com/show_bug.cgi?id=1383903
