### ISSUE TITLE
[enterprise-4.6] Issue in file machine_management/creating-infrastructure-machinesets.adoc

### ISSUE THREAD

**Issue by giofontana** [openshift/openshift-docs#28264]
### Which section(s) is the issue in?

Binding infrastructure node workloads using taints and tolerations

### What needs fixing?

In case user decides to use TAINTS, it is important to add tolerations for machine-config-daemon, node-ca, csi-cephfsplugin (if customer has OCS) and csi-rbdplugin (if customer has OCS). This KCS has more details about this: https://access.redhat.com/solutions/5061861

**Comment by mburke5678** [comment]
@giofontana Has this issue been fixed through https://bugzilla.redhat.com/show_bug.cgi?id=1780318
I checked a few defult DS in a 4.7 cluster and they all had a `operator: Exists` toleration.
