### ISSUE TITLE
High availability docs should not show ifconfig/netstat

### ISSUE THREAD

**Issue by jkupferer** [openshift/openshift-docs#2828]
In admin_guide/high_availability.adoc, under the heading "Configuring a Highly-available Routing Service" step 2, there is a code block that shows using deprecated commands ifconfig and netstat. These should be replaced with examples showing use of the ip command.

    ifconfig $interface | grep -i MULTICAST

Should be replaced with:

    ip addr show $interface | grep -i MULTICAST

And:

    netstat -g -n | grep 224.0.0 | grep $interface

Should be replaced with:

    ip maddr show $interface | grep 224.0.0

**Comment by bfallonf** [comment]
PR #2888  merged. Closing this issue.
