### ISSUE TITLE
[enterprise-4.6] Issue in file operators/admin/olm-adding-operators-to-cluster.adoc

### ISSUE THREAD

**Issue by magreenberg** [openshift/openshift-docs#28296]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.6/operators/admin/olm-adding-operators-to-cluster.html#olm-installing-operator-from-operatorhub-using-cli_olm-adding-operators-to-a-cluster

Section 4.
Create a Subscription object YAML file to subscribe a namespace to an Operator, for example sub.yaml:

### What needs fixing?
In the box:
    Example Subscription object
The line:
    channel: alpha
appears that a hardcoded channel is needed. However, this will not work. The channel value should be in angle brackets <channel> with an explanation that the "channel" must match the "defaultChannel" value from the "oc describe packagemanifests <operator_name> -n openshift-marketplace" output of Section  2.

**Comment by jboxman** [comment]
Looks like finding other channels is extra work: https://github.com/operator-framework/operator-registry#using-the-catalog-locally
