### ISSUE TITLE
[enterprise-4.6] Issue in file service_mesh/v2x/ossm-vs-community.adoc

### ISSUE THREAD

**Issue by RHmilti** [openshift/openshift-docs#28322]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.6/service_mesh/v2x/ossm-vs-community.html#ossm-routes-gateways_ossm-vs-istio

### What needs fixing?

theres the directive to *For more information, see Automatic route creation." but there is no link to another page...

whats the page to see for more information?

**Comment by stevsmit** [comment]
Hi @RHmilti 

Thanks for submitting this bug. We added an "Additional resources" section to this module so that users could easily find the referred section in the text. I will request that this issue be closed. 

Steven
