### ISSUE TITLE
Add Spell Checker to OpenShift docs

### ISSUE THREAD

**Issue by brian-avery** [openshift/openshift-docs#28333]
### Which section(s) is the issue in?
General issue

### What needs fixing?
Currently, it's pretty easy for spelling errors and broken links to get merged in the OpenShift documentation. When I ran a spell checker against it, I found several spelling errors. It may be useful to add a spell checker for the OpenShift docs. 

If it helps, we use Vale for Maistra.io, which could also be useful in enforcing the OpenShift docs standard as well (there's already an effort by Red Hatters to add implement our standards for the tool). This vocab file currently validates against everything except for misspelled content in the OpenShift Service Mesh docs: https://github.com/maistra/maistra.github.io/blob/maistra-2.0/vocab.txt.

**Comment by mburke5678** [comment]
@vikram-redhat Any thoughts?

**Comment by jboxman** [comment]
@brian-avery, that's interesting, and I've finally had time to investigate this. We use around 2,000 lowercased _words_ that aren't in the LibreOffice English (US) dictionary. This probably requires additional study.

**Comment by brian-avery** [comment]
Thanks @jboxman. To clarify, some of the spelling errors I caught can be found here: https://github.com/openshift/openshift-docs/pull/28346/files. It's been a bit since I've run the tooling, but some examples from that PR: 

* Repeating words -- `push actions by by editing the` -- also seen with the instead of `by`. 
* `assoicated` instead of `associated`
* `Mananger` instead of `manager`
* `Prerequistes` instead of `prerequisites`
* `Verfication` instead of `verification`

A lot of these are easy to miss when reviewing, but easily caught with a spell checker.

**Comment by jboxman** [comment]
@brian-avery, cool, @bergerhoffer recently went through and remove all the the doubles and similar.

**Comment by brian-avery** [comment]
Thanks. So we should be good at the moment. I cleaned up all the ones that were there in January. Would it be good to have tooling to detect these issues before they are merged?

**Comment by jboxman** [comment]
@brian-avery, not sure how viable this is pre-merge. (For example, it's not unheard of that someone touches dozens of files; a pre-commit hook or Travis build could run for quite a while, even if limited to changed files only.) In any case, I'm developing OCP docs specific tooling for this:

https://github.com/jboxman/adoc-after

I'm experimenting with automated YAML validation as well.

**Comment by brian-avery** [comment]
Awesome. Thanks! In that case, this issue can probably be closed. Curious to see how this turns out. Especially the automated YAML validation.
