### ISSUE TITLE
[enterprise-4.6] Issue in file operators/user/olm-installing-operators-in-namespace.adoc

### ISSUE THREAD

**Issue by cfilleke** [openshift/openshift-docs#28402]
### Which section(s) is the issue in?

"Installing from OperatorHub using the CLI"
Procedures
"Step 4. Create a Subscription object YAML file to subscribe a namespace to an Operator, for example sub.yaml:"

### What needs fixing?

For the naive user, there needs to be a little more explanation of the "channel" entry in the subs.yaml file, and how to find the valid channels of a particular operator as discovered in Step 2.  Just using 'alpha' as in the example leads to a broken deployment.  All the other changes the user must consider and adjust are discussed in laudable detail.

**Comment by jboxman** [comment]
I handled this for SR-IOV Operator in this way:

https://docs.openshift.com/container-platform/4.6/networking/hardware_networks/installing-sriov-operator.html#install-operator-cli_installing-sriov-operator

It might be that the same approach works here.

**Comment by jboxman** [comment]
But it looks like there is no easy way to get a list of channels: https://github.com/operator-framework/operator-registry#using-the-catalog-locally

**Comment by adellape** [comment]
> But it looks like there is no easy way to get a list of channels: [operator-framework/operator-registry#using-the-catalog-locally](https://github.com/operator-framework/operator-registry#using-the-catalog-locally)

Right, no easy way to get the list via CLI, AFAIK, and it doesn't have to be from a standard set of channel names. Created https://github.com/openshift/openshift-docs/pull/30901 to at least change the suggested "alpha" to a replaceable and provide some context around channel naming.
