### ISSUE TITLE
Backup/Restore should talk more about the relationship between etcd and storage

### ISSUE THREAD

**Issue by danmcp** [openshift/openshift-docs#2842]
This page:

https://docs.openshift.org/latest/admin_guide/backup_restore.html

Briefly mentions volume storage.  But it would be helpful to be more elaborate about how the etcd backup still has all the references to the storage volumes.  So when you restore etcd, OpenShift will start launching the previous pods on nodes and reattaching the same storage.  It might be useful to give the analogy that this is really no different than the process of when you remove a node from the cluster and add a new one back in its place.  Anything attached to that node will be reattached to the pods on whatever nodes they get rescheduled to.

**Comment by ahardin-rh** [comment]
Addressed in https://github.com/openshift/openshift-docs/pull/5706
