### ISSUE TITLE
[enterprise-4.6] Issue in file cli_reference/opm-cli.adoc

### ISSUE THREAD

**Issue by acsulli** [openshift/openshift-docs#28448]
### Which section(s) is the issue in?

Installing OPM

### What needs fixing?

The command to extract the binaries (step 3) uses the path `/usr/bin/registry/< file >`, however with the current container image the files are located at `/usr/bin`.

**Comment by bergerhoffer** [comment]
@adellape @skrthomas I know you both did some updates related to opm's path. I think this issue is resolved - can one of you please confirm?

**Comment by adellape** [comment]
The `opm` install instructions were updated to now show downloading the binary from the OpenShift mirror site:

https://docs.openshift.com/container-platform/4.6/cli_reference/opm-cli.html#olm-installing-opm_opm-cli

Therefore, the `oc image extract` steps are no longer relevant.
