### ISSUE TITLE
[enterprise-4.4] Issue in file logging/cluster-logging-deploying.adoc

### ISSUE THREAD

**Issue by RiRa12621** [openshift/openshift-docs#28442]
![Screenshot 2021-01-08 at 12 54 57](https://user-images.githubusercontent.com/14996407/104012798-b8b69700-51b0-11eb-8f4d-ce38b58449ce.png)

### Which section(s) is the issue in?
container-platform/4.4/logging/cluster-logging-deploying.html

### What needs fixing?
One templated value doesn't render. See attached screenshot

**Comment by jboxman** [comment]
@RiRa12621 thanks for reporting this!

**Comment by rolfedh** [comment]
@jboxman, would you close this issue as resolved? Thanks.
