### ISSUE TITLE
questionable link to Ignition config spec

### ISSUE THREAD

**Issue by dlbewley** [openshift/openshift-docs#28507]
### Which section(s) is the issue in?

https://raw.githubusercontent.com/openshift/openshift-docs/master/modules/ignition-config-viewing.adoc

```
* Format: The format of the file is defined in the
https://github.com/coreos/ignition/tree/spec2x[Ignition config spec].
Files of the same format are used later by the MCO to merge changes into a
machine’s configuration.
```

### What needs fixing?

Should this link now point to the `master` branch of this repo? 
Or maybe even better should it link to https://coreos.github.io/ignition/specs/ ?

**Comment by mburke5678** [comment]
@dlbewley Thanks for the comment. The link was changed here: https://github.com/openshift/openshift-docs/pull/29342
