### ISSUE TITLE
[enterprise-4.6] Issue in file cli_reference/opm-cli.adoc

### ISSUE THREAD

**Issue by ldojo** [openshift/openshift-docs#28515]
### Which section(s) is the issue in?
In the "Installing OPM" section (https://docs.openshift.com/container-platform/4.6/cli_reference/opm-cli.html#olm-installing-opm_opm-cli)

### What needs fixing?
the command for extracting the opm binary is:
oc image extract registry.redhat.io/openshift4/ose-operator-registry:v4.6 \
    -a ${REG_CREDS} \
    --path /usr/bin/registry/opm:. \
    --confirm

However, the path of the opm binary is /usr/bin/opm, not /usr/bin/registry/opm in that image. This works:
oc image extract registry.redhat.io/openshift4/ose-operator-registry:v4.6 \
    -a ${REG_CREDS} \
    --path /usr/bin/opm:. \
    --confirm

**Comment by skrthomas** [comment]
This was fixed by this [PR](https://github.com/openshift/openshift-docs/pull/28935) for this Bugzilla [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1910319)
