### ISSUE TITLE
[enterprise-4.6] Issue in file cli_reference/opm-cli.adoc

### ISSUE THREAD

**Issue by aelicieguo** [openshift/openshift-docs#28540]
### Which section(s) is the issue in?
Installing OPM, --path /usr/bin/registry/opm path not found

**Comment by jboxman** [comment]
URL: https://docs.openshift.com/container-platform/4.6/cli_reference/opm-cli.html

**Comment by skrthomas** [comment]
This was fixed by this [PR](https://github.com/openshift/openshift-docs/pull/28935) for this Bugzilla [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1910319)
