### ISSUE TITLE
[enterprise-4.5] Issue in file networking/configuring_ingress_cluster_traffic/configuring-externalip.adoc

### ISSUE THREAD

**Issue by ronnessim** [openshift/openshift-docs#28569]
### Which section(s) is the issue in?
The section which explains that you can assign an external IP address to a service (Configuration for ExternalIP). The text says "To use IP address blocks defined by autoAssignCIDRs in OpenShift Container Platform, you must configure the necessary IP address assignment and routing for your host network."

### What needs fixing?

There are no references on how to do this. It's not clear for an experienced network administrator what must be set up. Is it NAT? Is it something else? Is it routed? How are these virtual IPs set up in the cluster? All I want to do is add a new virtual IP and assign it to a service, but there no documentation on how to do so, and no examples.

**Comment by jboxman** [comment]
@ronnessim, originally in [3.x](https://docs.openshift.com/container-platform/3.11/dev_guide/expose_service/expose_internal_ip_service.html) we offered a method for this, but with RHCOS nodes in 4.x and no `oc adm ipfailover` support, this has been left entirely up to the user to divine a solution.

I've not come across any suggestions for how to do this, and it seems somewhat environment dependent.

@squeed, do we have any suggestions we can offer to someone regarding providing IPs that are routable to a cluster and eligible for use as an externalIP on non-cloud platforms? Maybe I just need to improve the language on what is recommended regarding how these IP are situated in the external environment?

Thanks!

**Comment by ronnessim** [comment]
Thanks for the comment – we’re just trying to set up a simple cluster in our lab with a self-hosted load balancer. There’s literally nothing out there on how to add more IP addresses to keepalived, or how to set up a self-contained openshift that can load balance traffic from external IPs towards the services. A really basic example would help a lot of people. At the moment we’re manually hacking the /etc/keepalived/keepalived.conf files to manually add virtual IPs to worker nodes. I’m sure there’s a better way 😉

**Comment by jboxman** [comment]
So I haven't heard back from anyone about this.

@sferich888, do you know if we have any supported approach for IP address assignment and routing for _ExternalIP_ on bare metal? Maybe I just need to be more specific about what is generally required?

Thanks!

**Comment by ronnessim** [comment]
Hi Jason – We found this as a way to make it work when there is no cloud provider:

https://github.com/redhat-cop/keepalived-operator

The idea is that there is an operator which creates keepalived containers that act as your LBs when you’re not using a cloud provider. It’s still an alpha project, but with enough hacking, it sort of does what the cloud ALBs do.

Ron.

**Comment by sferich888** [comment]
@jboxman we can probably close this.

**Comment by jboxman** [comment]
@ronnessim, we've added ipfailover in 4.8 that might help with this: https://docs.openshift.com/container-platform/4.8/networking/configuring-ipfailover.html
