### ISSUE TITLE
API documentation is pretty hard to navigate

### ISSUE THREAD

**Issue by gnufied** [openshift/openshift-docs#2860]
It may just me (and feel free to tell me to go away) but I find API documentation - https://docs.openshift.com/enterprise/3.2/rest_api/openshift_v1.html#definitions pretty hard to navigate. it is literally one big page that lists all API calls, with no listing/index for individual API endpoints which is generally a norm for documenting APIs.

**Comment by brennv** [comment]
Agreed, it's a but unnavigable. Proposed PR https://github.com/openshift/openshift-docs/pull/3593

**Comment by ahardin-rh** [comment]
The REST API area of the documentation is auto-generated from the Origin code. A new guide that will provide end to end use cases for working with the OpenShift REST API is in the works. Thanks!
