### ISSUE TITLE
[enterprise-4.6] Issue in file openshift_images/using-templates.adoc

### ISSUE THREAD

**Issue by JaredBurck** [openshift/openshift-docs#28623]
### Which section(s) is the issue in?
The last section "Creating a template from existing objects" 

### What needs fixing?
Command and now flag to export is deprecated as seen below

```
oc get -o yaml --export all > exported.yaml
Error: unknown flag: --export
See 'oc get --help' for usage.

oc version
Client Version: 4.6.8
```

Found this bugzilla on with details
https://bugzilla.redhat.com/show_bug.cgi?id=1444613

Alternate recommendations could be to use Helm or Kustomize depending on use case(s) and requirement(s).

**Comment by bergerhoffer** [comment]
Closing, PR #28943 removes the `--export` flag from the docs.
