### ISSUE TITLE
[enterprise-4.5] Issue in file authentication/configuring-user-agent.adoc

### ISSUE THREAD

**Issue by esimim** [openshift/openshift-docs#28631]
### Which section(s) is the issue in?
You construct user agents for the OpenShift Container Platform CLI from a set of values within OpenShift Container Platform:

### What needs fixing?
You construct user agents for the OpenShift Container Platform API from a set of values within OpenShift Container Platform:

**Comment by jboxman** [comment]
This looks like it isn't even applicable to OCP 4. This content appears to predate OCP 3 as well.

**Comment by bergerhoffer** [comment]
This section has been removed by PR #30739 and bug https://bugzilla.redhat.com/show_bug.cgi?id=1843583.

Thanks for submitting! Closing this issue now.
