### ISSUE TITLE
[enterprise-4.6] Issue in file installing/installing_vsphere/installing-vsphere-installer-provisioned.adoc

### ISSUE THREAD

**Issue by leethomasrh** [openshift/openshift-docs#28646]
### Which section(s) is the issue in?
Networking requirements
1. This sentence is misleading - You must use DHCP for the network and ensure that the DHCP server is configured to provide persistent IP addresses to the cluster machines.
2. Even in an IPI installation the network firewall needs to be configured.

### What needs fixing?
1. Recommend changing the sentence to read something like:  Due to the way vSphere generates MAC addresses during VM creation you must use dynamically assigned IPs for the initial cluster installation.  Once the cluster is installed you can create reservations within the DHCP server using the generated MAC addresses and, if necessary, performing a rolling reboot of the nodes to make the cluster IPs statically assigned if desired. 
2. Recommend including tables Table 4. API load balancer and Table 5. Application Ingress load balancer from this page (https://docs.openshift.com/container-platform/4.6/installing/installing_vsphere/installing-vsphere.html) in this page (https://docs.openshift.com/container-platform/4.6/installing/install_config/configuring-firewall.html) under a heading something like: Firewall port requirements.  You will need to explain that these ports need to be allowed for the IPs of the api and ingress controllers created in the DNS requirements. 

Something like:
Firewall port requirements:
Once the IPs for the api and ingress controllers have been designated you will need to ensure the firewall is configured to allow these ports.  
   API controller
      Table 4
   Ingress controller
       Table 5

Once this information has been added link to it from this document under a sub heading of the Networking requirements section.  I recommend right after the DNS requirements.  Something like:

Firewall requirements:
Follow the steps on this page to configure the necessary ports and URL whitelists in the organization firewall - https://docs.openshift.com/container-platform/4.6/installing/install_config/configuring-firewall.html

NOTE: The reason I'm recommending the tables be added to the firewall configuration page is because the URL whitelisting steps mentioned on that page are also required.  

Please let me know if you have any questions.

**Comment by leethomasrh** [comment]
Note: the information about manually creating the load balancers prior to Tables 4 and 5 on this page https://docs.openshift.com/container-platform/4.6/installing/installing_vsphere/installing-vsphere.html are not required for an IPI install - just the requirement to open the ports within the tables for the IPs designated for the api and ingress load balancers that the IPI install creates.

**Comment by skrthomas** [comment]
I'm looking into this issue for docs
