### ISSUE TITLE
master config docs need examples

### ISSUE THREAD

**Issue by bparees** [openshift/openshift-docs#2866]
The doc explaining how the master config is defined really needs examples of the fields it is talking about:
https://github.com/openshift/openshift-docs/blob/master/install_config/master_node_configuration.adoc

tables like this:
https://docs.openshift.org/latest/install_config/master_node_configuration.html#master-config-image-config

aren't very helpful without examples of valid values.

the node config section has an example, the master section should have one too:
https://docs.openshift.org/latest/install_config/master_node_configuration.html#node-configuration-files

**Comment by bfallonf** [comment]
@bparees 

Hmm it seems the example you're asking for was there, but was taken away by #2764 

@ahardin-rh was the decision to replace the example with the tables of possible values? Right now there seems to be an inconsistency between the master and node sections of this doc.

I also closed #722. I think both issues can be approached at the same time.

**Comment by ahardin-rh** [comment]
@bfallonf The previous example did not give very much information, as only one value actually defined. I decided to incorporate the tables to add more information. I will be working with @abutcher and team to continually improve both master-config and node-config sections.

**Comment by bfallonf** [comment]
@ahardin-rh Cool. I'll assign this one to you then :)

**Comment by adellape** [comment]
@ahardin-rh This came up again on IRC today via @ncdc (he in particular pointed out the [Audit Configuration](https://docs.openshift.org/latest/install_config/master_node_configuration.html#master-node-config-audit-config) section as confusing/incomplete in this setup). I think we could reintroduce a full example master config maybe at the end of the topic as a sort of appendix, and move the existing node config example there too? I think the newer subsections/tables setup is better for navigation and having more room for longer explanations as needed, but being able to also reference example syntax in the context of a full config file would be helpful.

**Comment by ncdc** [comment]
To reiterate my irc conversation, if, for example, you want to know how to configure auditing, the doc in its current form tells you all the options for the auditing config section, but it does *not* tell you the actual name of that section in the master config. Is it `audit:`? `auditConfig:`? `auditing:`? Get my drift? 😄

**Comment by adellape** [comment]
FWIW, the [Audit Configuration](https://docs.openshift.org/latest/install_config/master_node_configuration.html#master-node-config-audit-config) now has an example block, but we still should add back in a full example master-config file.

**Comment by mburke5678** [comment]
@ahardin-rh @adellape Did anything come of this issue?

**Comment by vikram-redhat** [comment]
I am going to close this issue as the example block added covers part of the original issue.
