### ISSUE TITLE
[enterprise-4.6] Issue in file installing/install_config/configuring-firewall.adoc

### ISSUE THREAD

**Issue by noseka1** [openshift/openshift-docs#28665]
### Which section(s) is the issue in?

Configuring your firewall for OpenShift Container Platform
https://docs.openshift.com/container-platform/4.6/installing/install_config/configuring-firewall.html#configuring-firewall_configuring-firewall

### What needs fixing?

We should add domain name `releases-art-rhcos.svc.ci.openshift.org` to the white-list.

Not white-listing the above domain led to an error during OCP installation:
```
FATAL failed to fetch Terraform Variables: failed to generate asset "Terraform Variables": failed to get vsphere Terraform variables: failed to use cached vsphere image: Get "https://releases-art-rhcos.svc.ci.openshift.org/art/storage/releases/rhcos-4.6/46.82.202011260640-0/x86_64/rhcos-46.82.202011260640-0-vmware.x86_64.ova?sha256=d73c7bdfd22e5a1231e23663266744c98c10de6f08f6d1fc718e7f72d0490c4a": dial tcp 35.196.103.194:443: connect: network is unreachable 
```

**Comment by codyhoag** [comment]
@noseka1 is this something that would be needed by customers? This looks like a CI service.

**Comment by noseka1** [comment]
@codyhoag It looks like a CI service, however, this domain name is used by the OCP installer to download images from, see also https://github.com/openshift/installer/blob/master/data/data/rhcos.json Yes, this is needed by the customer.
