### ISSUE TITLE
[enterprise-4.6] Issue in file cli_reference/opm-cli.adoc

### ISSUE THREAD

**Issue by damobrisbane** [openshift/openshift-docs#28729]
### Which section(s) is the issue in?

Installing opm

### What needs fixing?

Incorrect reference to opm binary:

$ oc image extract registry.redhat.io/openshift4/ose-operator-registry:v4.6 \
    -a ${REG_CREDS} \
    --path /usr/bin/registry/opm:. \
    --confirm
    
    Should instead be (remove "registry" from the image source path):
    
    $ oc image extract registry.redhat.io/openshift4/ose-operator-registry:v4.6 \
    -a ${REG_CREDS} \
    --path /usr/bin/opm:. \
    --confirm

&& the other paths, ie these are the locations of the opm files:

$ find . -name *opm
./usr/bin/darwin-amd64-opm
./usr/bin/opm
./usr/bin/windows-amd64-opm

**Comment by adellape** [comment]
The `opm` install instructions were updated to now show downloading the binary from the OpenShift mirror site:

https://docs.openshift.com/container-platform/4.6/cli_reference/opm-cli.html#olm-installing-opm_opm-cli

Therefore, the `oc image extract` steps are no longer relevant.
