### ISSUE TITLE
[enterprise-4.7] Issue in file installing/installing_gcp/installing-gcp-network-customizations.adoc

### ISSUE THREAD

**Issue by pamoedom** [openshift/openshift-docs#28766]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.7/installing/installing_gcp/installing-gcp-network-customizations.html#installation-gcp-config-yaml_installing-gcp-network-customizations

https://docs.openshift.com/container-platform/4.7/installing/installing_gcp/installing-gcp-network-customizations.html#installation-configuration-parameters_installing-gcp-network-customizations

### What needs fixing?

As part of the 4.7 hackathon efforts, I was trying GCP installation using KMS feature using the install-config.yaml example from the doc, but those paratemers are not correct, let me explain by parts:

From the example we can see the following related parameters:

~~~
        encryptionKey: 
          kmsKey:
            name: worker-key
            keyRing: test-machine-keys
            location: global
            projectID: project-id
          kmsKeyServiceAccount: openshift-service-account@openshift-gcp-project.iam.gserviceaccount.com
~~~

But as confirmed with @JoelSpeed over email (and also tested by me on various labs using 4.7.0-fc.3), the `kmsKeyServiceAccount` parameter is something not fully supported yet, specially for master nodes, so the way of making this feature work is removing both `kmsKeyServiceAccount` entries (master and workers) and granting the correct permissions for the default SA account as follows:

~~~
gcloud kms keys add-iam-policy-binding test-key \
    --keyring test-keyring \
    --location global \
    --member "serviceAccount:service-<project_number>@compute-system.iam.gserviceaccount.com" \
    --role 'roles/cloudkms.cryptoKeyEncrypterDecrypter'
~~~

Best Regards.

**Comment by codyhoag** [comment]
@tsze-redhat can you verify?

**Comment by tsze-redhat** [comment]
I am able to include kmsKeyServiceAccount: openshift-service-account@openshift-gcp-project.iam.gserviceaccount.com in the install-config under both the control node and worker node section as long as correct permission has been granted to the default compute service account (for control nodes) and the service account listed (for worker nodes).
The service account listed in install-config for control nodes won't take effect during install but it will take effect for day-2 operations.
@pamoedom did you try installing with the service account listed after you grant permission?

My apology if I miss understood.

**Comment by pamoedom** [comment]
Hi @tsze-redhat, that's a good question, I don't recall exactly all the different tests I did on that cluster but based on @JoelSpeed comments, the `kmsKeyServiceAccount` for control plane is something not fully supported yet, right? let me quote him:

~~~
The upshot of this is that the kmsKeyServiceAccount field doesn’t have any effect on the `controlPlane` block, the example in the documentation shouldn’t include that field in the `controlPlane` block.

Instead, you must grant the Compute Engine default service account permission to access your key, as this will be used for the control plane machines (format of service-<project_number>@compute-system.iam.gserviceaccount.com )

You can only use a custom service account for worker machines or, day 2, if you manually replace the control plane machines.

We need to modify the docs to make this limitation more obvious.
~~~

@JoelSpeed, can you please confirm if this is still the current status for 4.7?

**Comment by JoelSpeed** [comment]
Nothing has changed, this is still true for 4.7. The installer CANNOT use the value of kmsKeyServiceAccount for control plane machines, it will use the default service account instead

**Comment by tsze-redhat** [comment]
@pamoedom 
I understand now.
Yes, @JoelSpeed is recommending that the kmsServiceAccount is to be removed from the install portion of the user facing doc because of the fact that specified account will only work for worker.
I thought you were saying that the setting doesn't even work for worker or that the presence of it will make install fail.
As long as we are not seeing anything different, it is ok that the setting be left out of the install doc.
Thanks.

**Comment by pamoedom** [comment]
I've seen now the comments from https://github.com/openshift/openshift-docs/pull/28818 and understood your concerns, I don't recall making the installation attempt keeping the `kmsServiceAccount` in place while granting the proper permissions to the default SA account, so it makes sense that the installation has worked from your side just ignoring those values.

Apologies for the bad description of the issue and thanks for the follow up, appreciated!
