### ISSUE TITLE
[enterprise-4.6] Issue in file networking/configuring-a-custom-pki.adoc

### ISSUE THREAD

**Issue by lautou** [openshift/openshift-docs#28782]
### Which section(s) is the issue in?

Configuring the cluster-wide proxy during installation
Enabling the cluster-wide proxy

### What needs fixing?

"A comma-separated list of destination domain names, domains, IP addresses, or other network CIDRs to exclude proxying. Preface a domain with . to include all subdomains of that domain. Use * to bypass proxy for all destinations."

Add the following sentence:
"If both httpProxy and httpProxy are empty, this setting is ignored"

**Comment by jboxman** [comment]
@lautou thanks!
