### ISSUE TITLE
Deprecate Logging old style Curator config

### ISSUE THREAD

**Issue by tux-o-matic** [openshift/openshift-docs#28868]
### Which section(s) is the issue in?
All Curator YAML examples in https://docs.openshift.com/container-platform/4.6/logging/config/cluster-logging-curator.html#cluster-logging-curator-yaml_cluster-logging-curator 
This is valid for from 4.6.

### What needs fixing?
In OCP 4.5, the Cluster Logging Operator changed index naming structure. For example `.operations` indices are now named `infra-`. So Curator examples only apply to those old indices, new ones are cleaned up based on retention policies in the `CR`. To reduce confusion the ConfigMap doc should be deprecated.

**Comment by rolfedh** [comment]
@rolfedh transferred this to https://issues.redhat.com/browse/RHDEVDOCS-2763

**Comment by rolfedh** [comment]
Thanks @tux-o-matic. I've updated the first paragraph in this topic to make it clear that this procedure applies only to curating 4.5 and earlier indices.  If you're satisfied, please close this issue.
