### ISSUE TITLE
[enterprise-4.5] Issue in file networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-ingress-controller.adoc

### ISSUE THREAD

**Issue by esimim** [openshift/openshift-docs#28924]
### Which section(s) is the issue in?
When a set of routes is created in various projects, the overall set of routes is available to the set of Ingress Controllers.

### What needs fixing?
When a set of routes are created in various projects, the overall set of routes are available to the set of Ingress Controllers.

**Comment by jboxman** [comment]
So I wonder if this isn't clear in general:

> When a set of routes is created in various projects, the overall set of routes
is available to the set of Ingress Controllers. Each Ingress Controller admits
routes from the set of routes. By default, all Ingress Controllers
admit all routes.

Maybe;

_By default, every ingress controller in the cluster can admit any route created in any project in the cluster._

But there could be more nuance in this and we care specifically about _sets_ of routes?

Hi @Miciah, what do you think? Thanks!

**Comment by Miciah** [comment]
Yeah, speaking in terms of sets is unnecessary and potentially confusing.  This suggested wording makes sense and eliminates possible confusion from using "set" terminology:  

> _By default, every ingress controller in the cluster can admit any route created in any project in the cluster._
