### ISSUE TITLE
[enterprise-4.5] Issue in file networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-ingress-controller.adoc

### ISSUE THREAD

**Issue by esimim** [openshift/openshift-docs#28920]
### Which section(s) is the issue in?
When a set of routes is created in various projects

### What needs fixing?
When a set of routes are created in various projects

**Comment by jboxman** [comment]
Basically dups https://github.com/openshift/openshift-docs/issues/28924.
