### ISSUE TITLE
[enterprise-4.6] Issue in file virt/install/preparing-cluster-for-virt.adoc

### ISSUE THREAD

**Issue by kobi86** [openshift/openshift-docs#29004]
### Which section(s) is the issue in?

Before you install OpenShift Virtualization, ensure that your OpenShift Container Platform cluster meets the following requirements:

https://docs.openshift.com/container-platform/4.6/virt/install/preparing-cluster-for-virt.html

### What needs fixing?

In order to be able to migrate VM's to the cluster , you need to make sure that all the nodes in the pool are form the same CPU family 
One pool can be AMD and one can be INTEL , BUT you CANT mix the pools. 
It better to have all the CPU family  has one module if possible

**Comment by bgaydosrh** [comment]
Will close this issue when bug 1926199 closes (Jira CNV-10445).

**Comment by kobi86** [comment]
So the documentation is ready?

**Comment by bgaydosrh** [comment]
> So the documentation is ready?

As stated in https://github.com/openshift/openshift-docs/pull/30340 we need to ensure we are providing the correct links for the appropriate information, which is more complex than what was requested in the bug. We are going as fast as we can. Thanks.

**Comment by bgaydosrh** [comment]
Resolved so marking /close
