### ISSUE TITLE
[OKD] Hardcoded RHEL/RHCOS versions referenced

### ISSUE THREAD

**Issue by omenos** [openshift/openshift-docs#29079]
### Which section(s) is the issue in?

https://docs.okd.io/latest/installing/installing_bare_metal_ipi/ipi-install-prerequisites.html

[L11] https://github.com/openshift/openshift-docs/blob/master/installing/installing_bare_metal_ipi/ipi-install-prerequisites.adoc

[L23x3] https://github.com/openshift/openshift-docs/blob/master/modules/ipi-install-node-requirements.adoc

[L27x2] https://github.com/openshift/openshift-docs/blob/master/modules/ipi-install-configuring-nodes.adoc

### What needs fixing?

On the rendered OKD docs page there are 6 instances of RHEL's version being referenced, turning the OKD docs into:

* Fedora 8.1
* Fedora 8
* Fedora 8.x

**Comment by mburke5678** [comment]
@omenos Thanks for catching this. 
@vrutkovs What should the version be for Fedora?

**Comment by vrutkovs** [comment]
I'd prefer not t hardcode the version (stable stream would eventually move to F34), but if you must lets set Fedora 33
