### ISSUE TITLE
[enterprise-4.5] Issue in file nodes/pods/nodes-pods-secrets.adoc

### ISSUE THREAD

**Issue by esimim** [openshift/openshift-docs#29255]
### Which section(s) is the issue in?

View a list of all secrets:

$ oc get secrets

Example output

NAME                         TYPE                                  DATA      AGE
my-cert                  kubernetes.io/tls                     2         9m

View details on your secret:

$ oc describe secret my-service-pod

### What needs fixing?
When you list all of your secrets, there is only one secret called my-cert. Then you go on and get the details on a secret called my-service-pod. It does not make sense, you should get the details on secret my-cert.

**Comment by mburke5678** [comment]
@esimim Please see my changes in https://github.com/openshift/openshift-docs/pull/30221

**Comment by mburke5678** [comment]
See changes in https://github.com/openshift/openshift-docs/pull/30221
