### ISSUE TITLE
[enterprise-4.5] Typos that break links in file ocp-4-5-release-notes.adoc

### ISSUE THREAD

**Issue by jeana-redhat** [openshift/openshift-docs#29256]
### Which section(s) is the issue in?
[4.5 GA RN Bug fixes](https://docs.openshift.com/container-platform/4.5/release_notes/ocp-4-5-release-notes.html#ocp-4-5-bug-fixes)
- Last entry in Image Registry section: `The Operator is now installed with two pods for high avaijk:https://bugzilla.redhat.com/show_bug.cgi?id=1810317[BZ#1810317])`
- Web console (Administrator perspective) same issue `With this release, an update to a library that is used by the web console resolvjtps://bugzilla.redhat.com/show_bug.cgi?id=1796658[BZ#1796658])`

### What needs fixing?
Use source text to fix what appears in the docs. Probably a copy-paste error. Intended text can be found [here](https://docs.google.com/spreadsheets/d/1mfl0NllGhURWM4jUsYdHgWFgJpRH168epaV4gKSmVUA).

**Comment by jeana-redhat** [comment]
Cc: @vikram-redhat these are the typos you reported. FYI for some reason I can't assign @stevsmit though it seems I can @ mention him in a comment.

**Comment by vikram-redhat** [comment]
Awesome. Thanks @jeana-redhat
