### ISSUE TITLE
Add a "Debugging" section in deployment doc

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-docs#2930]
Should contain:
- the most common cases for a failure (failed probes, insufficient quota, image does not exist, container crashloops due to misconfigured runtime, what else?)
- how to workaround these problems (look at `oc status`, the deployment status in `oc describe` - coming with Conditions, `oc get events`, get logs from the deployer pod and from any running pods if any exist)

@mfojtik

**Comment by kargakis** [comment]
Increase logging in the deployer with:
```
customParams:
      command:
      - openshift-deploy
      - --loglevel=10
```

**Comment by bfallonf** [comment]
Thanks for the tips, @kargakis . I've referenced this issue in the #2890 , and we can probably get this info in with that PR.

cc: @adellape @ahardin-rh

**Comment by kargakis** [comment]
Shouldn't we keep this issue open until it's done?

**Comment by mburke5678** [comment]
Associated issue is closed. https://github.com/openshift/openshift-docs/pull/2890
PR associated to the associated issue is merged. https://github.com/openshift/openshift-docs/pull/3149
Closing this issue. Please re-open, if needed.
