### ISSUE TITLE
Link to Limiting Run-once Pod Duration for builds

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-docs#2931]
It'd be useful to explicitly link to:

https://docs.openshift.org/latest/admin_guide/managing_pods.html#manage-pods-limit-run-once-duration

from:

https://docs.openshift.org/latest/install_config/build_defaults_overrides.html

As it's a topic that is relevant to build pod management, and it's not super obvious that BuildConfig.Spec.ActiveDeadlineSeconds should be overridden using RunOnceDurationConfigs.

**Comment by mburke5678** [comment]
@jim-minter Can you describe how these two topics are related? I am not seeing it. Where in the Global Builds page would the link make sense? 
See https://github.com/openshift/openshift-docs/issues/2931

**Comment by jim-minter** [comment]
I think my point is that defining a hard limit on how long build pods can run for (i.e. via RunOnceDuration) is a relevant topic for an administrator who is considering defining hard CPU and memory resource limits for builds.  So, in the overview, after discussing BuildOverrides, I'd also cross-reference RunOnceDuration as an additional setting that may be relevant.

**Comment by mburke5678** [comment]
"When defining hard CPU and memory resource limits for builds, you can define a hard limit 
on how long build pods can run by using the 
xref:../../admin_guide/managing_pods.adoc#manage-pods-limit-run-once-duration[RunOnceDuration plugin]."

**Comment by jim-minter** [comment]
You don't need one for the other - just a, "hey, since you're here you might also be interested in knowing that you can..." would be better.

**Comment by mburke5678** [comment]
Closing. See: https://github.com/openshift/openshift-docs/pull/5589
