### ISSUE TITLE
OpenShift 1.4/3.4 Release Notes Tracker

### ISSUE THREAD

**Issue by kargakis** [openshift/openshift-docs#2933]
All notes related to the Origin 1.4 / OCP 3.4 release

**Comment by kargakis** [comment]
The `deploymentConfig.spec.strategy.rollingParams.updatePercent` field is removed in favor of `deploymentConfig.spec.strategy.rollingParams.maxUnavailable` and `deploymentConfig.spec.strategy.rollingParams.maxSurge`.

**Comment by smarterclayton** [comment]
In 1.4 the pre OpenShift 1.0 compatibility fields for Service `spec.portalIP` and Pod `spec.host` have been removed from the API.  Use `spec.clusterIP` for services and `spec.nodeName` for services.  Clients that send these fields to the server will have those values ignored.

**Comment by smarterclayton** [comment]
When upgrading etcd between the 2.3.x releases and the 3.0+ releases, administrators should be careful to upgrade only from 2.3.7+ to 3.0+.  Upgrades from 2.3.0-2.3.6 to etcd 3+ are not supported.  Rollback is also not supported - administrators should ALWAYS back up etcd prior to upgrading their etcd servers.

**Comment by liggitt** [comment]
from https://github.com/openshift/origin/pull/11150

`oc whoami --token` is deprecated in favor of `oc whoami -t` and will be removed in a future release.
`oc whoami --context` is deprecated in favor of `oc whoami -c` and will be removed in a future release.

**Comment by kargakis** [comment]
https://github.com/openshift/origin/pull/11426

In 1.4 support for 1.1 clients for deployment configs is dropped (more specifically just `oc scale` won't work as expected)

**Comment by ahardin-rh** [comment]
Prior to 3.4, we need to revisit the content introduced in https://github.com/openshift/openshift-docs/pull/3088 to evaluate whether or not the Scheduled Jobs feature is still in Technology Preview and whether or not the stated Known Issues still exist.

**Comment by mmilata** [comment]
openshift/origin#11539

In 1.4 it is no longer possible to set multiple environment variables or template parameters by passing comma-separated list to single `--env`/`--param`/`--value` option. E.g. `oc new-app mysql --param MYSQL_USER=user,MYSQL_PASSWORD=pass` will not work, `oc new-app mysql --param MYSQL_USER=user --param MYSQL_PASSWORD=pass` should be used instead.

**Comment by kargakis** [comment]
https://github.com/openshift/origin/pull/9349

New deployment endpoint for triggering rollouts via the API

https://github.com/openshift/origin/pull/11223

In the presence of the instantiate endpoint, we restore the way spec.triggers[*].automatic was working prior to 1.3.

**Comment by legionus** [comment]
https://github.com/openshift/origin/pull/11690

Importing an image from a remote registry that is insecure.

**Comment by adellape** [comment]
Relevant notes have been incorporated into the 3.4 release notes via https://github.com/openshift/openshift-docs/pull/3486, mostly under the "Miscellaneous Changes" section.

**Comment by soltysh** [comment]
@adellape https://github.com/openshift/origin/pull/11192 adds:

Allow setting external file for audit logs. Docs PR: https://github.com/openshift/openshift-docs/pull/3269.

**Comment by php-coder** [comment]
Looks like this issue can be closed.
