### ISSUE TITLE
[enterprise-4.6] Issue in file installing/installing_bare_metal_ipi/ipi-install-installation-workflow.adoc

### ISSUE THREAD

**Issue by sfxworks** [openshift/openshift-docs#29437]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.6/installing/installing_bare_metal_ipi/ipi-install-installation-workflow.html - > Table 2. Optional Parameters -> quote: "If using power management, BMC’s must be accessible from the machine networks. User must provide two IP addresses on the external network that are used for the provisioning services."

### What needs fixing?
- `clusterProvisioningIP` and `bootstrapProvisioningIP` default to IPs of the provisioning subnet. It is worded as if the user needs to provide this, but isn't directly referenced (may be a leftover from UPI?)
- `external network` should be `provisioning network` to be more in line with how the above is treated.
- `machine networks` should be `machine network` (just one) with it preferably renamed to `baremetal network` to keep itself consistent with the rest of the document.

**Comment by dadreggors** [comment]
In regards to `clusterProvisioningIP` and `bootstrapProvisioningIP` I agree it looks like this is propbablt a copy/paste issue from using UPI docs. The IPI installer spins up a bootstrap vm that creates a dnsmasq pod that gives these two addresses out based on the `provisioningNetworkCIDR` value in the install config.

With the latter 2 points I also agree, we call for creation of provisioning and baremetal networks elsewhere and reference using them both for cluster network activity or provisioning network activity but they called external or machine network here which leads to misunderstanding and confusion
