### ISSUE TITLE
[enterprise-4.6] Issue in file updating/updating-cluster-rhel-compute.adoc

### ISSUE THREAD

**Issue by rhatbob** [openshift/openshift-docs#29452]
### Which section(s) is the issue in?
"Procedure" section, step 2c @ [Updating RHEL compute machines in your cluster](https://docs.openshift.com/container-platform/4.6/updating/updating-cluster-rhel-compute.html#rhel-compute-updating_updating-cluster-rhel-compute)

### What needs fixing?
Looking at the following sections of the documentation:

(a) RHEL-based worker deployment section: `Preparing the machine to run the playbook` [0]
```
# subscription-manager repos \
    --enable="rhel-7-server-rpms" \
    --enable="rhel-7-server-extras-rpms" \
    --enable="rhel-7-server-ansible-2.9-rpms" \
    --enable="rhel-7-server-ose-4.6-rpms"
```

(b) RHEL-based worker upgrade section: `Updating RHEL compute machines in your cluster` [1]
```
# subscription-manager repos --disable=rhel-7-server-ose-4.5-rpms \
                             --enable=rhel-7-server-ose-4.6-rpms  \
                             --enable=rhel-7-fast-datapath-rpms   \
                             --enable=rhel-7-server-optional-rpms
```

The [Updating RHEL compute machines in your cluster](https://docs.openshift.com/container-platform/4.6/updating/updating-cluster-rhel-compute.html#rhel-compute-updating_updating-cluster-rhel-compute) section is missing the `rhel-7-server-rpms` and `rhel-7-server-extras-rpms` repositories, which can lead to dependencies issues when using the above (b) command, after doing the following:

```
subscription-manager refresh
subscription-manager repos --disable='*'
```
Suggestion for improvement: switch the current subscription-manager command on step 2c @ [Updating RHEL compute machines in your cluster](https://docs.openshift.com/container-platform/4.6/updating/updating-cluster-rhel-compute.html#rhel-compute-updating_updating-cluster-rhel-compute) with something alike following:
```
# subscription-manager repos \
    --disable=* \
    --enable=rhel-7-server-ose-4.6-rpms  \
    --enable="rhel-7-server-rpms" \
    --enable="rhel-7-server-extras-rpms" \
    --enable=rhel-7-fast-datapath-rpms   \
    --enable=rhel-7-server-optional-rpms
```

[0] https://docs.openshift.com/container-platform/4.6/machine_management/user_infra/adding-rhel-compute.html#rhel-preparing-playbook-machine_adding-rhel-compute
[1] https://docs.openshift.com/container-platform/4.6/updating/updating-cluster-rhel-compute.html#rhel-compute-updating_updating-cluster-rhel-compute

**Comment by kalexand-rh** [comment]
@rhatbob, is running these commands part of the standard workflow to update RHEL machines?

```
subscription-manager refresh
subscription-manager repos --disable='*
```

They're not currently in the topic, and if they're required, it seems like now would be a good time to add them.
