### ISSUE TITLE
[enterprise-4.5] Issue in file nodes/scheduling/nodes-scheduler-node-selectors.adoc

### ISSUE THREAD

**Issue by esimim** [openshift/openshift-docs#29478]
### Which section(s) is the issue in?
Add labels to a node by using a machine set or editing the node directly:

    Use a MachineSet object to add labels to nodes managed by the machine set when a node is created:

        Run the following command to add a node selector to a MachineSet object:

### What needs fixing?
Add labels to a node by using a machine set or editing the node directly:

    Use a MachineSet object to add labels to nodes managed by the machine set when a node is created:

        Run the following command to add labels to a MachineSet object:

**Comment by mburke5678** [comment]
@esimim Thank you for catching this. Can you take a look at https://github.com/openshift/openshift-docs/pull/30221 to see if it meets your expectations?

**Comment by mburke5678** [comment]
See changes in https://github.com/openshift/openshift-docs/pull/30221
