### ISSUE TITLE
URL for downloading OC client is incorrect

### ISSUE THREAD

**Issue by iranzo** [openshift/openshift-docs#29523]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.6/installing/installing_bare_metal_ipi/ipi-install-installation-workflow.html#retrieving-the-openshift-installer_ipi-install-installation-workflow

### What needs fixing?

Sync with US module which has the right url:  https://openshift-kni.github.io/baremetal-deploy/4.6/Deployment.html#retrieving-the-openshift-installer_ipi-install-installation-workflow

**Comment by iranzo** [comment]
@johnwilkins

**Comment by skrthomas** [comment]
Looking into this as part of GitHub issue burndown

**Comment by iranzo** [comment]
In OC download
`openshift-client-linux-$VERSION.tar.gz` should not have `-$VERSION`
