### ISSUE TITLE
[enterprise-4.6] Issue in file installing/install_config/installation-types.adoc

### ISSUE THREAD

**Issue by bmarlow** [openshift/openshift-docs#29542]
### Which section(s) is the issue in?
'Supported installation methods for defferent platforms', Table 1 'Installer-provisioned infrastructure options'

### What needs fixing?
vSphere should be listed as supported for restricted networks with IPI
These are supported and tested by QE
This is per Katherine Dube

**Comment by ably77** [comment]
Link to IPI matrix:
https://docs.openshift.com/container-platform/4.6/installing/install_config/installation-types.html
