### ISSUE TITLE
[enterprise-4.6] Issue in file logging/cluster-logging-deploying.adoc

### ISSUE THREAD

**Issue by Alveel** [openshift/openshift-docs#29574]
### Which section(s) is the issue in?

Installing cluster logging using the web console

### What needs fixing?

Explanation of points 6 and 7 for the YAML example are duplicates. Point 7 should be something closer to point 7 in the same YAML file in the section installing using the CLI.

**Comment by Alveel** [comment]
Faster link: https://docs.openshift.com/container-platform/4.6/logging/cluster-logging-deploying.html#clipboard-0

**Comment by lbscorpio** [comment]
Nice catch, I noticed the same issue and have included on my PR#29637, waiting review then merge, thanks.

**Comment by rolfedh** [comment]
@vikram-redhat  Please close. Issue has been resolved.

**Comment by jboxman** [comment]
@rolfedh done
