### ISSUE TITLE
[enterprise-4.6] Issue in file operators/operator_sdk/osdk-getting-started.adoc

### ISSUE THREAD

**Issue by horeaporutiu** [openshift/openshift-docs#29581]
### Which section(s) is the issue in?
Step 4. Add a new controler

### What needs fixing?
The link to the example controller code doesn't work.

**Comment by adellape** [comment]
Fixed in OCP 4.7 by including the example controller in the doc:

https://docs.openshift.com/container-platform/4.7/operators/operator_sdk/golang/osdk-golang-tutorial.html#osdk-golang-implement-controller_osdk-golang-tutorial
