### ISSUE TITLE
[enterprise-4.5] Issue in file applications/quotas/quotas-setting-per-project.adoc

### ISSUE THREAD

**Issue by esimim** [openshift/openshift-docs#29590]
### Which section(s) is the issue in?
compute-resources-time-bound.yaml

Across all pods in a non-terminal state, the sum of CPU limits cannot exceed this value.
Across all pods in a non-terminal state, the sum of memory limits cannot exceed this value.
Across all pods in a non-terminal state, the sum of ephemeral storage limits cannot exceed this value.

### What needs fixing?
Across all pods in a Terminating state, the sum of CPU limits cannot exceed this value.
Across all pods in a Terminating state, the sum of memory limits cannot exceed this value.
Across all pods in a Terminating state, the sum of ephemeral storage limits cannot exceed this value.

**Comment by bobfuru** [comment]
Thank you for raising this issue, @esimim! I don't have much knowledge of resource quotas but I did open https://github.com/openshift/openshift-docs/pull/30945 to see about getting this addressed.

**Comment by bobfuru** [comment]
Thanks again, @esimim! The related PR https://github.com/openshift/openshift-docs/pull/30945 was approved by QE and has been merged to the docs. It is now live, for example:
https://docs.openshift.com/container-platform/4.7/applications/quotas/quotas-setting-per-project.html#quotas-sample-resource-quota-definitions_quotas-setting-per-project

Closing this issue.
