### ISSUE TITLE
[enterprise-4.7] Issue in file openshift_images/image-streams-manage.adoc

### ISSUE THREAD

**Issue by maxwelldb** [openshift/openshift-docs#29595]
### Which section(s) is the issue in?

Nav title, assembly title

### What needs fixing?

Is it "imagestreams" or "image streams?"

**Comment by bergerhoffer** [comment]
It should be "image streams" two words. Looks like @bmcelvee has a PR open (#28198) that should hopefully address this.

**Comment by bmcelvee** [comment]
Yeah, that PR is in progress. I think it's safe to close this issue if you're comfortable with it @maxwelldb.

**Comment by maxwelldb** [comment]
@bmcelvee TY! The issue should close automatically after the PR is merged.
