### ISSUE TITLE
configure HAProxy through route annotation - add some documentation

### ISSUE THREAD

**Issue by eformat** [openshift/openshift-docs#2960]
whilst investigating AB deployments in 1.3/3.3 openshift, the default load balancing mechanism is 

balance leastconn

which doesn't do quite what you expect when you use 'oc set route-backends' - you need roundrobin load balancing for that

it would be great if the docs mentioned that you could change the behaviour of HAProxy through annotating your route:

oc annotate route/ab haproxy.router.openshift.io/balance=roundrobin

i looked in the haproxy template in the image to find this out.

/var/lib/haproxy/conf/haproxy-config.template

  option forwardfor
    {{ with $balanceAlgo := index $cfg.Annotations
"haproxy.router.openshift.io/balance" }}
      {{ with $matchValue := (matchValues $balanceAlgo "roundrobin"
"leastconn" "source" ) }}
  balance {{ $balanceAlgo }}

Thanks

**Comment by knobunc** [comment]
We need to document all of the possible annotation that you can set on a route.  We seem to be missing:

- router.openshift.io/haproxy.health.check.interval
- haproxy.router.openshift.io/balance

It would be nice to gather all of the other annotations in one place and document them.

**Comment by sosiouxme** [comment]
We have at least these ones to document:

```
haproxy.router.openshift.io/balance
haproxy.router.openshift.io/timeout
haproxy.router.openshift.io/rate-limit-connections 
haproxy.router.openshift.io/rate-limit-connections.concurrent-tcp
haproxy.router.openshift.io/rate-limit-connections.rate-http
```

I'm wondering if `router.openshift.io/haproxy.health.check.interval` would have been moved to `haproxy.router.openshift.io/haproxy.health.check.interval` or similar.

**Comment by knobunc** [comment]
@sosiouxme It probably should have been named that, but it came in first and noone caught the discrepancy until too late.

**Comment by JacobTanenbaum** [comment]
Documentation has been added for the annotations PR3301

**Comment by DanyC97** [comment]
Can this be close since PR https://github.com/openshift/openshift-docs/pull/3301 was merged ?

**Comment by knobunc** [comment]
@DanyC97 Seems reasonable.
