### ISSUE TITLE
[enterprise-4.6] Issue in file security/compliance_operator/compliance-operator-understanding.adoc

### ISSUE THREAD

**Issue by pdhamdhe** [openshift/openshift-docs#29646]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.6/security/compliance_operator/compliance-operator-understanding.html#compliance_profiles_understanding-compliance

### What needs fixing?
Remove deprecated ncp profiles from Example output
i.e ocp4-ncp & rhcos4-ncp

**Comment by ahardin-rh** [comment]
@pdhamdhe Thank you for reporting this issue! This is now addressed in https://github.com/openshift/openshift-docs/pull/30774
