### ISSUE TITLE
OCP 4.8 Release Notes Tracker

### ISSUE THREAD

**Issue by soltysh** [openshift/openshift-docs#29652]
Please leave comments here for anything that should be highlighted in the 4.8 release notes. Thank you!

**Comment by soltysh** [comment]
`oc newapp` might not work on RHEL7 for clients using older Docker versions. https://github.com/openshift/oc/pull/745 removes support for docker v1 API.

**Comment by jianzhangbjz** [comment]
- OLM is not supported on SNO cluster - https://issues.redhat.com/browse/OLM-2017, besides, there is bug: https://bugzilla.redhat.com/show_bug.cgi?id=1953977
- The `build` subcommand had been removed from the `oc adm catalog`.
```yaml
[root@preserve-olm-env debug-manifests]# oc adm catalog --help
This tool is used to extract and mirror the contents of catalogs for Operator Lifecycle Manager.

 The subcommands allow you to mirror catalog content across registries.

Usage:
  oc adm catalog [flags]

Available Commands:
  mirror      Mirror an operator-registry catalog
```

**Comment by pamoedom** [comment]
Not sure if we should include the experimental AWS tagging feature as tech preview, I've asked the developer within [OSDOCS-1959](https://issues.redhat.com/browse/OSDOCS-1959) to confirm/discard.

**Comment by tsze-redhat** [comment]
GCP installation:
Change to subnets created during installation to increase number of IP available 
https://issues.redhat.com/browse/CORS-1660

**Comment by miabbott** [comment]
RHCOS will be based on RHEL 8.4; this brings in new kernel features, hardware enablements, etc

**Comment by travier** [comment]
In RHCOS, we longer set the `PEERNTP=no` option in the chrony configuration (`/etc/chrony.conf`) by default on cloud platforms (AWS, GCP, Azure) if (and only if) the administrator has already set a custom `chrony.conf` configuration. All other cases are unchanged (i.e. this option is set by default on those platforms). See https://github.com/coreos/fedora-coreos-config/pull/845 for reference.

**Comment by dmesser** [comment]
OLM has better installation/update error handling and reporting: https://issues.redhat.com/browse/OLM-2048

- missing or invalid OperatorGroups will now be reported at the `InstallPlan` level
- missing or wrong package, catalog and channel names will now be reported at the `Subscription` level
- InstallPlans are now automatically retried to overcome transient errors

**Comment by dulek** [comment]
In deployments on OSP with Kuryr-Kubernetes, the API LB for the `default/kubernetes` Service is no longer managed by CNO, but by kuryr-controller itself. This means that:
* On upgrade it's expected this service will have some downtime (more in deployments where no ovn-octavia is available).
* The `default/kubernetes` LB was previously forced to be using Amphora Octavia provider. This is not true anymore, if ovn-octavia is available in the OSP cloud, it will be used to implement that service.

Please note that I added the same to the bug [1] doc text.

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1949509

**Comment by tsze-redhat** [comment]
@pamoedom I suggest also includes CORS-1600:

Installer now attempts to automatically collect and analyze when installation fails.
Potential causes for installation failures will be displayed if the terminal running the installer has the proper ssh key configured and user specifies a ssh key during install process.

What do you think?

**Comment by pamoedom** [comment]
> @pamoedom I suggest also includes [CORS-1600](https://issues.redhat.com/browse/CORS-1600):
> 
> Installer now attempts to automatically collect and analyze when installation fails.
> Potential causes for installation failures will be displayed if the terminal running the installer has the proper ssh key configured and user specifies a ssh key during install process.
> 
> What do you think?

That's a good point @tsze-redhat but I recall @codyhoag telling we don't have any customer facing documentation for this in [CORS-1627](https://issues.redhat.com/browse/CORS-1627?focusedCommentId=16027403&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16027403), so not sure if we could refer it in the official release notes.

**Comment by tsze-redhat** [comment]
Based on feedback from @staebler I also added CORS-1533 (registry accessing causing bootstrap).
Maybe we can consider the output from installer is self-explanatory enough to not require user doc.

I shall leave it to you to decide whether we include or not include bootstrap improvements. @pamoedom 

Thanks.

**Comment by adduarte** [comment]
OpenStack platform: SSH port is explicitly CLOSED on  cluster deployment. 
having ssh port to the cluster exposed (open) is a security risk. 
Also, ssh to nodes is not the suggested way to connect to the cluster nodes. Instead the user should use the "oc debug" command when possible. 
If the user wants to ssh to the nodes, they must explicitly open port 22 in the security rules for the cluster, as pointed out in https://docs.openshift.com/container-platform/4.7/virt/virtual_machines/virt-accessing-vm-consoles.html#virt-accessing-vmi-ssh_virt-accessing-vm-consoles


Bug 1873079 - SSH to api and console route is possible when the clsuter is hosted on Openstack (https://bugzilla.redhat.com/show_bug.cgi?id=1873079)

**Comment by adambkaplan** [comment]
Builds: Image change triggers will not start a build based on changes to the `lastImageChangeTriggeredID` field in the BuildConfig spec. The image IDs that trigger a build will be recorded in the BuildConfig's status, which cannot be changed by most users.

**Comment by jeana-redhat** [comment]
https://issues.redhat.com/browse/CCO-21 GA of AWS STS with new `ccoctl` tool

**Comment by dulek** [comment]
OCP on OSP deployments using Kuryr require a workaround to deploy a worker with ports from networks with `port_security_enabled=False` (SR-IOV use case). In order to do that the primary port of such worker has to have set `portSecurity: False` and the Machine itself needs to have empty `securityGroups` list. The worker nodes SG can be applied to the primary worker port after the VM is created.

More detailed info: openshift/installer#4957

**Comment by mburke5678** [comment]
I am adding via https://github.com/openshift/openshift-docs/pull/31237

Automatic rotation of kubelet-ca.crt does not require reboot (https://issues.redhat.com/browse/GRPA-3190)
Updates now report status based on all machine config pools (https://issues.redhat.com/browse/GRPA-3000)
Vertical pod autoscaling is generally available (https://issues.redhat.com/browse/OCPNODE-437)
tlsSecurityProfile parameter for Kubelet as a server (https://issues.redhat.com/browse/OCPNODE-464)
workaround to restrict CPU on pause container (https://issues.redhat.com/browse/OCPNODE-476)
Adding specific repositories to pull images (https://issues.redhat.com/browse/OCPNODE-461)
Vertical pod autoscaling minimum can be configured (https://issues.redhat.com/browse/OCPNODE-452)
Automatically allocate CPU and memory resources for nodes (https://issues.redhat.com/browse/OCPNODE-367)

**Comment by romfreiman** [comment]
Single Node OpenShift, as dev-preview on BareMetal

**Comment by SNiemann15** [comment]
For IBM P/Z input @ktania46 has created WIP PR https://github.com/openshift/openshift-docs/pull/32733

**Comment by simonpasquier** [comment]
Monitoring: the notable changes are listed at https://github.com/openshift/cluster-monitoring-operator/blob/master/CHANGELOG.md#48

- [#1087](https://github.com/openshift/cluster-monitoring-operator/pull/1087) Decrease alert severity to "warning" for ThanosQueryHttpRequestQueryErrorRateHigh and ThanosQueryHttpRequestQueryRangeErrorRateHigh alerts.
- [#1087](https://github.com/openshift/cluster-monitoring-operator/pull/1087) Increase "for" duration to 1 hour for all Thanos query alerts.
- [#1087](https://github.com/openshift/cluster-monitoring-operator/pull/1087) Remove ThanosQueryInstantLatencyHigh and ThanosQueryRangeLatencyHigh alerts.
- [#1090](https://github.com/openshift/cluster-monitoring-operator/pull/1090) Decrease alert severity to "warning" for all Thanos sidecar alerts.
- [#1090](https://github.com/openshift/cluster-monitoring-operator/pull/1090) Increase "for" duration to 1 hour for all Thanos sidecar alerts.
- [#1093](https://github.com/openshift/cluster-monitoring-operator/pull/1093) Bump kube-state-metrics to major new release v2.0.0-rc.1. This changes a lot of metrics and flags, see kube-state-metrics CHANGELOG for full changes. 
- [#1126](https://github.com/openshift/cluster-monitoring-operator/pull/1126) Remove deprecated techPreviewUserWorkload field from CMO's configmap.

**Comment by bgilbert** [comment]
OpenShift now includes the Butane config transpiler to assist with producing and validating machine configs.  Documentation now recommends using Butane to create machine configs for LUKS disk encryption, root disk RAID, and custom kernel modules.

Epic link: https://issues.redhat.com/browse/GRPA-3065
(the referenced docs haven't landed yet)

**Comment by lwan-wanglin** [comment]
For [CCO-21](https://issues.redhat.com/browse/CCO-21) **GA of AWS STS** as @jeana-redhat mentioned above, we don't support the below 2 scenario now,  it's worth to add to release note， cc @joelddiaz @akhil-rane 

1.  not support in OCP 4.8 on goveronment region
   - Bug [1935058](https://bugzilla.redhat.com/show_bug.cgi?id=1935058) -  Can’t finish install sts clusters on aws government region
2.  not support in OCP 4.8 in a disconnected installation
  - Bug [1939842](https://bugzilla.redhat.com/show_bug.cgi?id=1939842) -  Image registry Degraded caused by requesting to aws sts global endpoint timeout when installing sts cluster in a disconnected network

**Comment by sunzhaohua2** [comment]
Machine API:

- Support Azure DiskEncryptionSets for machines: https://issues.redhat.com/browse/OCPCLOUD-954
- vSphere: autoscaling from/to zero support: https://issues.redhat.com/browse/OCPCLOUD-848
- Apply user defined tags in AWS - EC2: https://issues.redhat.com/browse/OCPCLOUD-1116

**Comment by duanwei33** [comment]
For storage: (cc @chao007)

TP feature:

- Storage: CSI Migration for OpenStack Cinder and AWS EBS (Tech Preview): https://issues.redhat.com/browse/STOR-361
- CSI operator for Azure Disk (Tech preview): https://issues.redhat.com/browse/STOR-364:
- Storage: CSI Operator for vSphere (Tech Preview): https://issues.redhat.com/browse/STOR-434

TP to GA:

- CSI Operator for GCE (GA): https://issues.redhat.com/browse/STOR-255

**Comment by asood-rh** [comment]
For networking (cc @jboxman  )
Please include features covered in these epics -  https://issues.redhat.com/browse/SDN-1364 and https://issues.redhat.com/browse/SDN-1340

**Comment by jboxman** [comment]
@asood-rh, there's https://github.com/openshift/openshift-docs/pull/32956 and will be one for network policy audits shortly.

**Comment by weliang1** [comment]
For networking (cc @jboxman )
Please include features covered in these epics - https://issues.redhat.com/browse/OSDOCS-1861

**Comment by yanpzhan** [comment]
Web Console
Some words update:
For console and downloads routes, custom routes **functionally/functionality** is now implemented to use the new ingress config route configuration API **spec.componenetRoutes**.The Console Operator **config** already contained custom route customization, but for the console route only.

**Comment by lihongan** [comment]
Networking:

-  Support Ingress Class (see https://issues.redhat.com/browse/NE-477)
-  Provide Global Access Option for GCP Ingress Internal LB  (https://issues.redhat.com/browse/NE-447)
- Control openshift-dns Pod Placement (https://issues.redhat.com/browse/NE-360)
- Support for ipfailover (https://issues.redhat.com/browse/NE-455)
- Customizable HAProxy nbthread (https://issues.redhat.com/browse/NE-302)
- Update CoreDNS to v1.8.z (https://issues.redhat.com/browse/NE-377)

**Comment by apinnick** [comment]
Migration Toolkit for Applications new features:
- Direct image and volume migration (https://issues.redhat.com/browse/MIG-284)
- Migration rollback (https://issues.redhat.com/browse/MIG-249)

**Comment by stlaz** [comment]
Authentication:
- OAuth tokens that do not include a SHA-256 prefix can no longer be used or created. This is a continuation of the effort to secure the OAuth token storage as announced in release notes of OpenShift Container Platform 4.6.

**Comment by dulek** [comment]
Known issue:
* [OVN bug](https://bugzilla.redhat.com/show_bug.cgi?id=1937392) causes persistent connectivity issues to Octavia loadbalancers. The problem affects Neutron subnets (OpenShift namespaces) at random. This means that OCP 4.8 deployments with Kuryr used as SDN are not recommended on OSP 16.1 with OVN (and OVN-Octavia) configured. Please follow the bug to find out which OSP z-stream release will include a fix to the problem.

cc: @MaysaMacedo @EricArrakis @luis5tb

**Comment by chao007** [comment]
Storage:
Merge multiple persistent daemonsets into one for LSO, so if create local volume CR,  only daemonset.apps/diskmaker-manager is created. (See [https://issues.redhat.com/browse/STOR-492])

**Comment by anuragthehatter** [comment]
We should mention dual stack IPv6 support for IPsec as well  in notes

**Comment by jboxman** [comment]
> We should mention dual stack IPv6 support for IPsec as well in notes

@ctauchen, this is an easy win. Can you add this to the OCP 4.8 release notes under the _Networking_ section? (https://docs.openshift.com/container-platform/4.8/release_notes/ocp-4-8-release-notes.html#ocp-4-8-networking)

This is the prior 4.7 release note entry for IPsec itself: https://docs.openshift.com/container-platform/4.7/release_notes/ocp-4-7-release-notes.html#ocp-4-7-ovn-kubernetes-ipsec-support

Thanks!

**Comment by rolfedh** [comment]
> Builds: Image change triggers will not start a build based on changes to the `lastImageChangeTriggeredID` field in the BuildConfig spec. The image IDs that trigger a build will be recorded in the BuildConfig's status, which cannot be changed by most users.

Thanks, @adambkaplan. @Srivaralakshmi and I are documenting this issue in [the release notes for builds](https://docs.google.com/document/d/11toR_NFW03SBtQmKE-vPDtF21GNePg3e6ASZNhxLAXo/edit#), which you have reviewed and commented upon.

**Comment by rolfedh** [comment]
@soltysh @oarribas @adambkaplan: @Srivaralakshmi will be adding release notes for the BUILDS project. These will include [the items listed in this bz query](https://bugzilla.redhat.com/buglist.cgi?bug_status=ON_QA&bug_status=VERIFIED&bug_status=RELEASE_PENDING&bug_status=CLOSED&classification=Red%20Hat&columnlist=product%2Ccomponent%2Cassigned_to%2Cbug_status%2Cresolution%2Cshort_desc%2Cchangeddate%2Ccf_doc_type%2Ccf_release_notes&component=Build&f1=cf_release_notes&f2=target_release&list_id=11944069&o1=isnotempty&o2=anywordssubstr&product=OpenShift%20Container%20Platform&query_format=advanced&resolution=---&resolution=CURRENTRELEASE&resolution=ERRATA&resolution=UPSTREAM&v2=4.8.0%2C4.8.z) and  https://issues.redhat.com/browse/BUILD-213.

**Comment by jeana-redhat** [comment]
> For [CCO-21](https://issues.redhat.com/browse/CCO-21) **GA of AWS STS** as @jeana-redhat mentioned above, we don't support the below 2 scenario now, it's worth to add to release note， cc @joelddiaz @akhil-rane
> 
>     1. not support in OCP 4.8 on goveronment region
> 
> 
>     * Bug [1935058](https://bugzilla.redhat.com/show_bug.cgi?id=1935058) -  Can’t finish install sts clusters on aws government region
> 
> 
>     1. not support in OCP 4.8 in a disconnected installation
> 
> 
>     * Bug [1939842](https://bugzilla.redhat.com/show_bug.cgi?id=1939842) -  Image registry Degraded caused by requesting to aws sts global endpoint timeout when installing sts cluster in a disconnected network
> 
> 
> Bug [1935058](https://bugzilla.redhat.com/show_bug.cgi?id=1935058) has fixed.

Making a note here for RN team tracking: As Lin notes, 1935058 is resolved and does not need to be included. Further conversation on [1935058](https://bugzilla.redhat.com/show_bug.cgi?id=1935058) indicates this will likely go in as a Known Issue.

**Comment by jeana-redhat** [comment]
We need to add a statement along the lines of "The scope of support on OCP for the different add-ons is stated in the respective Release Notes." (And elaborating a bit about what we mean by add-ons, perhaps where to find these respective RNs, etc.)

Per [Slack discussion](https://coreos.slack.com/archives/C2ZA5QGMV/p1623754125194300) kicked off by @SNiemann15 :bow:

**Comment by sdodson** [comment]
For the Installation and Upgrades section a broadly scoped note along the lines of
```
We have significantly reduced the upgrade duration for Cluster Operators which deploy DaemonSets to all nodes.
This change has reduced the upgrade duration of a 250 node test cluster from 7.5hrs to 1.5hrs, resulting in
upgrade duration scaling by less than one minute per additional node. Note, this change does not affect
MachineConfigPool rollout duration.
```

Backing bugs for this are https://bugzilla.redhat.com/show_bug.cgi?id=1933159 https://bugzilla.redhat.com/show_bug.cgi?id=1933174 https://bugzilla.redhat.com/show_bug.cgi?id=1934711 https://bugzilla.redhat.com/show_bug.cgi?id=1933173 https://bugzilla.redhat.com/show_bug.cgi?id=1933179 https://bugzilla.redhat.com/show_bug.cgi?id=1933184

**Comment by robszumski** [comment]
![image](https://user-images.githubusercontent.com/755540/123682624-35016d00-d819-11eb-9d83-0a0a332ca8ef.png)

OpenShift Pipelines and OpenShift GitOps can be marked as GA from TP

**Comment by jeana-redhat** [comment]
@s-urbaniak Thanks for this excellent write-up! I'm not exactly sure what area this content belongs in - could you take a peek at the [draft release notes](https://docs.openshift.com/container-platform/4.8/release_notes/ocp-4-8-release-notes.html) and let me know which "New features and enhancements" heading it would best fit under?

**Comment by zhaozhanqi** [comment]
@jboxman we need to add note for 4.7 customer which is using OVN network plugin and RHEL7.9 workers want to upgrade to 4.7 latest version or 4.8 version.   there is bug https://bugzilla.redhat.com/show_bug.cgi?id=1976232 blocked the  upgrade for now. So if you wan to upgrade your 4.7 cluster version.  please wait the bug 1976232 is moved to verified and use the fixed version

**Comment by robszumski** [comment]
![image](https://user-images.githubusercontent.com/755540/123966730-aeb56a00-d983-11eb-803e-8e6852bdc5cb.png)

This continues as tech preview. Direct any questions to @marrusl.

**Comment by robszumski** [comment]
![image](https://user-images.githubusercontent.com/755540/123967010-ed4b2480-d983-11eb-86ab-cc375e97da1d.png)

This continues as tech preview. Direct any questions to @mgoldboi.

**Comment by robszumski** [comment]
![image](https://user-images.githubusercontent.com/755540/123968685-757df980-d985-11eb-8e2c-b42247b6b435.png)

We'd like to downgrade this feature from tech preview. Follow up with @sichvoge and @gauravsingh85.

**Comment by kasturinarra** [comment]
Add DevPreviewLongLifecycle in the release notes for descheduler. More info could be found at [1] and also since this is only for certain audiences we would like to call it out.  you could contat @ingvagabund  or @damemi for any questions.

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1955595

**Comment by bergerhoffer** [comment]
> Add DevPreviewLongLifecycle in the release notes for descheduler. More info could be found at [1] and also since this is only for certain audiences we would like to call it out. you could contat @ingvagabund or @damemi for any questions.
> 
> [1] https://bugzilla.redhat.com/show_bug.cgi?id=1955595

@kasturinarra @damemi @ingvagabund Is this new profile dev preview (as the name implies)? If so, I don't believe we document dev preview features or even mention them in the release notes at all. CC @sjstout @vikram-redhat to confirm.

**Comment by soltysh** [comment]
> @kasturinarra @damemi @ingvagabund Is this new profile dev preview (as the name implies)? If so, I don't believe we document dev preview features or even mention them in the release notes at all. CC @sjstout @vikram-redhat to confirm.

@bergerhoffer yeah. that's fair :+1:

**Comment by kasturinarra** [comment]
> > @kasturinarra @damemi @ingvagabund Is this new profile dev preview (as the name implies)? If so, I don't believe we document dev preview features or even mention them in the release notes at all. CC @sjstout @vikram-redhat to confirm.
> 
> @bergerhoffer yeah. that's fair

Thank you but i am just curious how the targeted audiences would know about this if we do not let them know about this ?

**Comment by jeana-redhat** [comment]
> > > @kasturinarra @damemi @ingvagabund Is this new profile dev preview (as the name implies)? If so, I don't believe we document dev preview features or even mention them in the release notes at all. CC @sjstout @vikram-redhat to confirm.
> > 
> > 
> > @bergerhoffer yeah. that's fair
> 
> Thank you but i am just curious how the targeted audiences would know about this if we do not let them know about this ?

Emailing you offline :)

**Comment by lwan-wanglin** [comment]
> > For [CCO-21](https://issues.redhat.com/browse/CCO-21) **GA of AWS STS** as @jeana-redhat mentioned above, we don't support the below 2 scenario now, it's worth to add to release note， cc @joelddiaz @akhil-rane
> > ```
> > 1. not support in OCP 4.8 on goveronment region
> > 
> > 
> > * Bug [1935058](https://bugzilla.redhat.com/show_bug.cgi?id=1935058) -  Can’t finish install sts clusters on aws government region
> > 
> > 
> > 1. not support in OCP 4.8 in a disconnected installation
> > 
> > 
> > * Bug [1939842](https://bugzilla.redhat.com/show_bug.cgi?id=1939842) -  Image registry Degraded caused by requesting to aws sts global endpoint timeout when installing sts cluster in a disconnected network
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Bug [1935058](https://bugzilla.redhat.com/show_bug.cgi?id=1935058) has fixed.
> 
> Making a note here for RN team tracking: As Lin notes, 1935058 is resolved and does not need to be included. 

Bug 1935058 can be removed from known issues.

>Further conversation on [1939842](https://bugzilla.redhat.com/show_bug.cgi?id=1939842) indicates this will likely go in as a Known Issue.

@jeana-redhat , we need to use this bug [1977184](https://bugzilla.redhat.com/show_bug.cgi?id=1977184) replacing 1939842 to track image registry issue, the dev changes the target release to 4.8.z, so we should also treat it as a known issue.

**Comment by jeana-redhat** [comment]
> > > For [CCO-21](https://issues.redhat.com/browse/CCO-21) **GA of AWS STS** as @jeana-redhat mentioned above, we don't support the below 2 scenario now, it's worth to add to release note， cc @joelddiaz @akhil-rane
> > > ```
> > > 1. not support in OCP 4.8 on goveronment region
> > > 
> > > 
> > > * Bug [1935058](https://bugzilla.redhat.com/show_bug.cgi?id=1935058) -  Can’t finish install sts clusters on aws government region
> > > 
> > > 
> > > 1. not support in OCP 4.8 in a disconnected installation
> > > 
> > > 
> > > * Bug [1939842](https://bugzilla.redhat.com/show_bug.cgi?id=1939842) -  Image registry Degraded caused by requesting to aws sts global endpoint timeout when installing sts cluster in a disconnected network
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Bug [1935058](https://bugzilla.redhat.com/show_bug.cgi?id=1935058) has fixed.
> > 
> > 
> > Making a note here for RN team tracking: As Lin notes, 1935058 is resolved and does not need to be included.
> 
> Bug 1935058 can be removed from known issues.
> 
> > Further conversation on [1939842](https://bugzilla.redhat.com/show_bug.cgi?id=1939842) indicates this will likely go in as a Known Issue.
> 
> @jeana-redhat , we need to use this bug [1977184](https://bugzilla.redhat.com/show_bug.cgi?id=1977184) replacing 1939842 to track image registry issue, the dev changes the target release to 4.8.z, so we should also treat it as a known issue.

Thanks, Lin! I have let @ctauchen and @stevsmit know about this one.

**Comment by xiuwang** [comment]
May need a release note for https://bugzilla.redhat.com/show_bug.cgi?id=1924568#c21
On AWS C2S, when occur above bug x509 error, then need a workaround on image reigstry.
`oc patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{"spec":{"disableRedirect":true}}'`

**Comment by lwan-wanglin** [comment]
According to @dmage's comment in https://bugzilla.redhat.com/show_bug.cgi?id=1939842#c18 , we need a FRE rather than a bug for a disconnected sts cluster install, so I will close the bug with wontfix , @jeana-redhat @ctauchen , maybe we can remove the bug from the 4.8 RN.  cc PM @billmvt and @mbracho

**Comment by vikram-redhat** [comment]
OCP 4.9 RN Tracker: https://github.com/openshift/openshift-docs/issues/33497
