### ISSUE TITLE
[enterprise-4.7] Issue in file release_notes/ocp-4-7-release-notes.adoc

### ISSUE THREAD

**Issue by patrickstrick** [openshift/openshift-docs#29665]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.7/release_notes/ocp-4-7-release-notes.html#ocp-4-7-web-console-developer-perspective

After you have the Container Security Operator installed on your cluster:

### What needs fixing?

We may want to say "Quay Container Security Operator" instead of just "Container Security Operator". In OperatorHub it is listed as "Quay Container Security" and so it was not immediately obvious to me that they were the same.

**Comment by jeana-redhat** [comment]
@patrickstrick good eye, and thanks for bringing this to our attention. The RNs are now updated to reflect the name in OperatorHub.
