### ISSUE TITLE
[enterprise-4.6] Issue in file cli_reference/opm-cli.adoc

### ISSUE THREAD

**Issue by jkupferer** [openshift/openshift-docs#29678]
### Which section(s) is the issue in?

Installing opm -> Procedure

### What needs fixing?

The command provided to extract the `opm` executable does not work because `/usr/bin/opm` is a symbolic link in the image.

Depending on `oc` client version it produces different broken behavior. With `oc` 4.5.9 I saw:

```
error: unable to extract layer sha256:40e6de4bca35ef5f47841b160f4a3a12ef7817e61c973fa9f0a3eede0ad19d8e from registry.redhat.io/openshift4/ose-operator-registry:v4.6: invalid symlink "opm" -> "/bin/registry/opm"
```

While with `oc` 4.6.0 it reported no error, but created a broken symbolic pointing to `/bin/registry/opm`. The correct location for the `opm` executable in the image is `/usr/bin/registry/opm`.

Looking inside the image I see the same problem for all platforms:

```
$ ls -l /usr/bin/registry/*opm*
-rwxr-xr-x. 1 root root 67033944 Feb 13 02:23 /usr/bin/registry/darwin-amd64-opm
-rwxr-xr-x. 1 root root 57137352 Feb 13 02:22 /usr/bin/registry/opm
-rwxr-xr-x. 1 root root 92769455 Feb 13 02:24 /usr/bin/registry/windows-amd64-opm
```

The correct extract command is:

```
oc image extract registry.redhat.io/openshift4/ose-operator-registry:v4.6 -a ${REG_CREDS} --path /usr/bin/registry/opm:. --confirm
```

And likewise should be updated for mac and windows... though having to extract an executable from a container image seems a rather cumbersome way to distribute software!

**Comment by adellape** [comment]
The `opm` install instructions were updated to now show downloading the binary from the OpenShift mirror site:

https://docs.openshift.com/container-platform/4.6/cli_reference/opm-cli.html#olm-installing-opm_opm-cli

Therefore, the `oc image extract` steps are no longer relevant.
