### ISSUE TITLE
[enterprise-4.6] Issue in file installing/install_config/installation-types.adoc

### ISSUE THREAD

**Issue by xmorano2** [openshift/openshift-docs#29681]
### Which section(s) is the issue in?
Supported installation methods for different platforms - Table 2

### What needs fixing?
Azure also supports restricted network installation, as shown in https://issues.redhat.com/browse/CORS-1365

**Comment by jeana-redhat** [comment]
Checked with Install author (@codyhoag) and this is not actually a supported and documented option at this time. Closing this issue and related PRs.
