### ISSUE TITLE
Table Renders Too Wide, Doesn't Respect Smaller Window Size

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/openshift-docs#2973]
The first table labeled "Cluster Variables" under [Configuring Cluster Variables](https://docs.openshift.org/latest/install_config/install/advanced_install.html#configuring-cluster-variables) seems to be much wider than any of the other content on that page, which makes it hard to zoom into the content itself. furthermore, if the window size shrinks due to zoom, this table doesn't honor that and falls off of the screen to the right.

**Comment by jim-minter** [comment]
Also "Table 1. Supported Metadata" on https://docs.openshift.org/latest/creating_images/metadata.html, as another example.

**Comment by stevekuznetsov** [comment]
This is an example of what this looks like for me:
![table](https://cloud.githubusercontent.com/assets/7328370/20753716/b328721a-b6d5-11e6-8a14-27852164e621.png)

**Comment by mburke5678** [comment]
@stevekuznetsov @jim-minter It appears that this issue has been addressed? I am closing. Please let me know if https://github.com/openshift/openshift-docs/pull/3372 didn't address your concern

**Comment by stevekuznetsov** [comment]
The link I posted still looks like

![screenshot from 2017-10-06 13-40-13](https://user-images.githubusercontent.com/7328370/31297695-e99f2fb8-aa9b-11e7-868c-98d349737e89.png)

**Comment by jim-minter** [comment]
@mburke5678 it's the tables that are the issue, not the code snippet. Please re-open.

**Comment by mburke5678** [comment]
@jim-minter It appears that the tables need to be wide in order to accommodate the code block snippets in the right column. The column widths are set relative to one another. If I remove that mark-up, the code blocks become regular text. 
@stevekuznetsov  Where is the issue with zooming? Are you looking at a cell phone?

**Comment by stevekuznetsov** [comment]
Maybe I've just got old-man eyes ;)

**Comment by stevekuznetsov** [comment]
I have a 4k monitor so I hover around 180% zoom to make my text larger. If you think that's not a use-case you need to support, feel free to close this!

**Comment by mburke5678** [comment]
@vikram-redhat Came across this issue. What do you think? Should we close as the use case is an outlier?

**Comment by vikram-redhat** [comment]
@mburke5678 - yeah pretty much :)
