### ISSUE TITLE
[enterprise-4.7] Issue in file architecture/architecture.adoc

### ISSUE THREAD

**Issue by rag4God** [openshift/openshift-docs#29906]
### Which section(s) is the issue in? Deployment and scaling benefits
Link: https://docs.openshift.com/container-platform/4.7/architecture/architecture.html#deployment-scaling-benefits_architecture

### What needs fixing?
The first 2 sentences of paragraph 2 in this section should be combined, or reworded.
1: "You can also deploy and test a new version of an application alongside the existing version."
2: "Deploy the new application version in addition to the current version."
You may also want to simply delete sentence #2.

**Comment by rolfedh** [comment]
Thanks, @rag4God. I've submitted a PR to fix this issue.
