### ISSUE TITLE
[enterprise-4.6] Issue in file registry/configuring_registry_storage/configuring-registry-storage-vsphere.adoc

### ISSUE THREAD

**Issue by benoorazem** [openshift/openshift-docs#29904]
### Which section(s) is the issue in?

Configuring block registry storage for VMware vSphere
https://docs.openshift.com/container-platform/4.6/installing/installing_vsphere/installing-vsphere-installer-provisioned.html#installation-registry-storage-block-recreate-rollout_installing-vsphere-installer-provisioned
Step: 2.b

and in
Configuring block registry storage for VMware vSphere 
https://docs.openshift.com/container-platform/4.6/registry/configuring_registry_storage/configuring-registry-storage-vsphere.html#installation-registry-storage-block-recreate-rollout_configuring-registry-storage-vsphere
Step: 2.b

### What needs fixing?

When one log on for the first time it gets to the default namespace. Following the guide the PVC would be created in the default namespace. I assume the existing command for creating pvc `$ oc create -f pvc.yaml` should be `$ oc create -f pvc.yaml -n openshift-image-registry`.

**Comment by rolfedh** [comment]
FYI @bobfuru

**Comment by bobfuru** [comment]
Cc: @lpettyjo or @bmcelvee - seems like a simple fix that core storage or reg storage dev/QE could verify

**Comment by bmcelvee** [comment]
This issue and https://github.com/openshift/openshift-docs/issues/28150 look to be the same. I'll open a PR to resolve both.

**Comment by bmcelvee** [comment]
Resolved.
