### ISSUE TITLE
[enterprise-4.7] Missing docs for OpenShift Virtualized 

### ISSUE THREAD

**Issue by tumido** [openshift/openshift-docs#29926]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.7/virt/about-virt.html

### What needs fixing?
Missing docs for OpenShift Virtualized 2.6, while Openshift.com is already marketing it.

https://www.openshift.com/blog/whats-new-in-openshift-virtualization-in-ocp-4.7

**Comment by rolfedh** [comment]
Hi, @tumido. It looks like the OpenShift Virtualization docs have been published. If you're satisfied, please close this issue.
https://docs.openshift.com/container-platform/4.7/virt/virt-2-6-release-notes.html

**Comment by tumido** [comment]
Hi @rolfedh Thank you very much! :+1: This issue can be closed now. :slightly_smiling_face:
