### ISSUE TITLE
[enterprise-4.7] Issue in file installing/installing-preparing.adoc

### ISSUE THREAD

**Issue by peterclauterbach** [openshift/openshift-docs#29961]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.7/installing/installing-preparing.html#supported-installation-methods-for-different-platforms

### What needs fixing?
The two tables for:
Table 1. Installer-provisioned infrastructure options
Table 2. User-provisioned infrastructure options
need updating for OCP on RHV.  As of OpenShift 4.6, we support disconnected (restricted network) deployments for both methods.

**Comment by vap0rtranz** [comment]
Can it be made clearer that the RHV IPI method can (or cannot) use the same/similar method OSP uses for disconnected?

https://github.com/openshift/installer/blob/release-4.7/docs/dev/openstack/customization.md
