### ISSUE TITLE
[enterprise-4.5] Issue in file authentication/managing-security-context-constraints.adoc

### ISSUE THREAD

**Issue by esimim** [openshift/openshift-docs#29973]
### Which section(s) is the issue in?
A FSGroup SCC strategy of MustRunAs

### What needs fixing?
Apply the proper format to the FSGroup just as MustRunAs, following SupplementalGroups format two paragraphs over.

**Comment by esimim** [comment]
This is by far the worst documentation I have ever read, really bad. Terrible explanations filled up with errors of all kinds. It comes as huge discredit for the product which is supposed to be pretty advanced. Kubernetes documentation is rich and correct all the way up, the gab is big.

**Comment by rolfedh** [comment]
Hi @esimim. Thanks for your feedback. To make sure I understand, you're referring to the following topic: https://docs.openshift.com/container-platform/4.7/authentication/managing-security-context-constraints.html#admission_configuring-internal-oauth

And the comparison you're making refers to these topics (probably among others):
- https://kubernetes.io/docs/concepts/policy/pod-security-policy/#enabling-pod-security-policies
- https://kubernetes.io/docs/concepts/policy/pod-security-policy/#volumes-and-file-systems
