### ISSUE TITLE
incorrect example image name in aggregate_logging doc

### ISSUE THREAD

**Issue by dlbewley** [openshift/openshift-docs#3003]
See: 

- https://docs.openshift.com/container-platform/3.3/install_config/aggregate_logging.html#deploying-the-efk-stack
- https://raw.githubusercontent.com/openshift/openshift-docs/enterprise-3.3/install_config/aggregate_logging.adoc

Where it says:
	
>The version for logging component images. For example, setting the version to v3.2 creates registry.access.redhat.com/openshift3/ose-logging-deployer:v3.2.

The example `ose-logging-deployer` is bogus. That image does not exist. It should be `logging-deployer`

```bash
$ curl -s https://registry.access.redhat.com/v1/repositories/openshift3/ose-logging-deployer/tags
Not Found


$ curl -s https://registry.access.redhat.com/v1/repositories/openshift3/logging-deployer/tags | jq .
{
  "3.3.0": "4901f872c0e8ac5acd89068361d0d3a0b78d9e8867c447cbeac60e2653bcb915",
  "3.3.0-12": "4901f872c0e8ac5acd89068361d0d3a0b78d9e8867c447cbeac60e2653bcb915",
  "latest": "4901f872c0e8ac5acd89068361d0d3a0b78d9e8867c447cbeac60e2653bcb915",
  "v3.3": "4901f872c0e8ac5acd89068361d0d3a0b78d9e8867c447cbeac60e2653bcb915"
}
```

**Comment by bfallonf** [comment]
Thanks @dlbewley Not sure if you guys planned this, but @sosiouxme created a PR fixing this just before you submittied this PR...

#2999 

I'll close this issue and merge his PR.

Thanks!
