### ISSUE TITLE
[enterprise-4.7] Issue in file storage/container_storage_interface/persistent-storage-csi-ovirt.adoc

### ISSUE THREAD

**Issue by peterclauterbach** [openshift/openshift-docs#30049]
### Which section(s) is the issue in?

Red Hat Virtualization (oVirt) CSI Driver Operator

### What needs fixing?

This documentation is very light, and does not say anything about what features are supported (thick or thin provisioned), and there are no examples of how to set up different storage classes with different properties.

**Comment by rolfedh** [comment]
FYI @emarcusRH
