### ISSUE TITLE
[enterprise-4.7] Indentation problem on logging installation docs

### ISSUE THREAD

**Issue by boranx** [openshift/openshift-docs#30052]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.7/logging/cluster-logging-deploying.html

Hey team,
If you search `memory: "8Gi"` on the page, you'll see that there are 2 results where one of them's resource section's indentation had slid one tab. (Number 7 on yml)

### What needs fixing?
The resource tab needs to be fixed otherwise the operator doesn't reconcile the requested memory by CU.

**Comment by rolfedh** [comment]
https://issues.redhat.com/browse/RHDEVDOCS-2752

**Comment by rolfedh** [comment]
@boranx Please take a look at https://github.com/openshift/openshift-docs/pull/30170/files . Thanks.
