### ISSUE TITLE
[enterprise-4.5] Issue in file openshift_images/using-imagestreams-with-kube-resources.adoc

### ISSUE THREAD

**Issue by kelly-brown** [openshift/openshift-docs#30062]
### Which section(s) is the issue in?
image-lookup explanations

### What needs fixing?
The information about the image-lookup command is confusing.  After running through it with Red Hat support, it seems to me that this is required to update the order in which it's looking for an image.  I.E. it looks for an image stream in your namespace first, before it goes trying to pull it from the registries in the /etc/containers/registries.conf file.  I never would have gotten that from what is written there.  Just wanted to share my experience in case you wanted to update to document.

**Comment by rolfedh** [comment]
Hi @kelly-brown. Thanks for reporting this issue. To make sure I understand, it sounds like you're referring to this [Enabling imagestreams with Kubernetes resources](https://docs.openshift.com/container-platform/4.7/openshift_images/using-imagestreams-with-kube-resources.html#images-managing-images-enabling-imagestreams-kube_using-imagestreams-with-kube-resources) topic.
