### ISSUE TITLE
[enterprise-4.5] Issue in file service_mesh/v1x/customizing-installation-ossm.adoc

### ISSUE THREAD

**Issue by rhatbob** [openshift/openshift-docs#30065]
### Which section(s) is the issue in?
"Configuring Jaeger" @ https://docs.openshift.com/container-platform/4.5/service_mesh/v1x/customizing-installation-ossm.html#ossm-configuring-jaeger_customizing-installation-ossm-v1x

### What needs fixing?
The [ServiceMeshControlPlane code block](https://github.com/openshift/openshift-docs/blob/enterprise-4.5/modules/ossm-configuring-jaeger.adoc) has an indentation issue:

- How it currently looks:
  ~~~
    apiVersion: maistra.io/v1
    kind: ServiceMeshControlPlane
    spec:
      istio:
        tracing:
          enabled: true
          jaeger:
            template: all-in-one
  ~~~

- Proposal to amend:
  ~~~
  apiVersion: maistra.io/v1
  kind: ServiceMeshControlPlane
  spec:
    istio:
      tracing:
        enabled: true
        jaeger:
          template: all-in-one
  ~~~

**Comment by rolfedh** [comment]
Hi, @rhatbob.  Thanks for reporting this issue. I've created a PR to fix this indentation issue and others like it, here: https://github.com/openshift/openshift-docs/pull/30430

**Comment by JStickler** [comment]
Looks like this has been addressed.  Closing.
