### ISSUE TITLE
[enterprise-4.7] Issue in file welcome/oke_about.adoc

### ISSUE THREAD

**Issue by MarsForever** [openshift/openshift-docs#30180]
### Which section(s) is the issue in?

About OpenShift Kubernetes Engine
Table 1

### What needs fixing?
what does “X” meaning in the table?
Does it mean it doesn’t work in the openshit kubernetes engine and openshift container platform?

**Comment by rolfedh** [comment]
See https://english.stackexchange.com/questions/397384/symbols-for-yes-and-no-in-formal-english-writing
This issue refers to welcome/oke_about.adoc

**Comment by rolfedh** [comment]
Updated the tables in two files. Replaced X with Yes so they are like other tables in:
- modules/recommended-configurable-storage-technology.adoc
- modules/serverless-workflow-traffic-splitting-flags.adoc

**Comment by rolfedh** [comment]
Thank you for raising this issue, @MarsForever. I have submitted a fix for review.

**Comment by rolfedh** [comment]
Hello, @MarsForever. @codyhoag has reviewed and merged the issue. The fix should show up in our published documentation, [such as this topic](https://docs.openshift.com/container-platform/4.7/welcome/oke_about.html), within a day.

**Comment by MarsForever** [comment]
> Thank you for raising this issue, @MarsForever. I have submitted a fix for review.

@rolfedh Thanks for fixing it.

**Comment by rolfedh** [comment]
Hi, @codyhoag. Would you close this issue for me? Thanks.
