### ISSUE TITLE
Need doc admission controllers more clear

### ISSUE THREAD

**Issue by mdshuai** [openshift/openshift-docs#3019]
As there are many admission controllers both openshift and kubernetes, If I know I can configure my env more intelligent.

Example: Sometime I want to know which is only supported by openshift, which is supported both openshift and k8s. Also sometime I want to know which is enabled or disabled by default in openshift, so I can enable/disable some admission controllers in my scenario:.

https://github.com/openshift/origin/blob/master/pkg/cmd/server/origin/master_config.go#L324-L361

**Comment by bfallonf** [comment]
I attached this issue to a BZ:

https://bugzilla.redhat.com/show_bug.cgi?id=1338919

Closing this in favour of that.
