### ISSUE TITLE
[enterprise-4.6] Issue in file support/gathering-cluster-data.adoc

### ISSUE THREAD

**Issue by rhatbob** [openshift/openshift-docs#30292]
### Which section(s) is the issue in?
[Gathering data about specific features](https://docs.openshift.com/container-platform/4.6/support/gathering-cluster-data.html#gathering-data-specific-features_gathering-cluster-data)

### What needs fixing?
Proposal to update the `Table 1. Supported must-gather images` with the missing the Local Storage Operator must-gather image:

```
# source: https://github.com/openshift/local-storage-operator/blob/master/docs/must-gather.md
$ oc adm must-gather --image=quay.io/openshift/local-must-gather:latest
```

**Comment by rolfedh** [comment]
Hi @bergerhoffer. Would you like to make this update to modules/gathering-data-specific-features.adoc?

**Comment by bergerhoffer** [comment]
Checked with @huffmanca and the image is not available in quay yet. Following this BZ, so that when it is added, and supported, we will update the docs: https://bugzilla.redhat.com/show_bug.cgi?id=1930631

**Comment by huffmanca** [comment]
@bergerhoffer 

The image is now available in quay.io - https://quay.io/repository/openshift/origin-local-storage-mustgather .
