### ISSUE TITLE
Document arp cache tuning for > 1000 routes

### ISSUE THREAD

**Issue by jeremyeder** [openshift/openshift-docs#3030]
Document outcome of https://trello.com/c/DZb8ghlZ/228-5-scale-document-tuning-options-for-arp-cache

@jmencak @sdodson @detiber @timothysc @brenton

**Comment by ahardin-rh** [comment]
@aheslin FYI. Targeted 3.4.

**Comment by bfallonf** [comment]
There's a BZ created for this, so I'll close this in favour of that;

https://bugzilla.redhat.com/show_bug.cgi?id=1384746
