### ISSUE TITLE
[enterprise-4.7] Issue in file installing/installing_aws/installing-aws-government-region.adoc

### ISSUE THREAD

**Issue by pekramp** [openshift/openshift-docs#30325]
### Which section(s) is the issue in?
Uploading a custom RHCOS AMI in AWS

### What needs fixing?
step 6. 
aws ec2 import-snapshot --region ${AWS_DEFAULT_REGION} \
     --description "<description>" \ 
     --disk-container <file_path>/containers.json 

should be 
aws ec2 import-snapshot --region ${AWS_DEFAULT_REGION} \
     --description "<description>" \ 
     --disk-container "file://<file_path>/containers.json "

**Comment by rolfedh** [comment]
Hi, @codyhoag. Would you like to make this update to https://github.com/openshift/openshift-docs/blob/master/modules/installation-aws-upload-custom-rhcos-ami.adoc

**Comment by codyhoag** [comment]
Sure thing; this has been submitted in #30325

**Comment by codyhoag** [comment]
@pekramp thanks for this suggestion. The update has been merged.
