### ISSUE TITLE
[enterprise-4.7] Issue in file logging/config/cluster-logging-curator.adoc

### ISSUE THREAD

**Issue by r2d2rnd** [openshift/openshift-docs#30343]
### Which section(s) is the issue in?
Configuring the log curator

### What needs fixing?
It's possible to read:

"The Elasticsearch Curator tool removes Elasticsearch indices that use the data model prior to OpenShift Container Platform 4.7."

When it should be say:

"The Elasticsearch Curator tool removes Elasticsearch indices that use the data model prior to OpenShift Container Platform 4.5."

Since the database model was changed in OCP 4.5

At the same time, a bug was created with this: https://bugzilla.redhat.com/show_bug.cgi?id=1937685

**Comment by rolfedh** [comment]
Thanks for reporting this issue, @r2d2rnd. There is no need to create multiple reports for the same issue in different releases of the documentation. For something like this, we typically fix the issue in the master branch and then cherry-pick the fix to multiple release branches. Please comment `/close` to close this issue.
