### ISSUE TITLE
[enterprise-4.7] Issue in file applications/quotas/quotas-setting-per-project.adoc

### ISSUE THREAD

**Issue by sinicis** [openshift/openshift-docs#30355]
### Which section(s) is the issue in?
* [Resources managed by quotas](https://docs.openshift.com/container-platform/4.7/applications/quotas/quotas-setting-per-project.html#quotas-resources-managed_quotas-setting-per-project)
  * Table 1. Compute resources managed by quota 
    * row: *ephemeral-storage*

### What needs fixing?
IMHO the ephemeral storage is enabled by default in 4.7. So the sentence "This resource is available only if you enabled the ephemeral storage technology preview. This feature is disabled by default." should be removed.

**Comment by rolfedh** [comment]
Thanks for reporting this issue, @sinicis. I've created a PR to fix it that is now being reviewed.

**Comment by rolfedh** [comment]
This issue is also mentioned in https://bugzilla.redhat.com/show_bug.cgi?id=1769845#c13

**Comment by rolfedh** [comment]
@bergerhoffer Please close this issue.
