### ISSUE TITLE
[enterprise-4.7] Issue in file authentication/identity_providers/configuring-github-identity-provider.adoc

### ISSUE THREAD

**Issue by christianh814** [openshift/openshift-docs#30414]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.7/authentication/identity_providers/configuring-github-identity-provider.html#identity-provider-creating-configmap_configuring-github-identity-provider

### What needs fixing?

It should be noted that this section should say "This step only needs to be done if you're using an on-prem installation of GitHub"

**Comment by bergerhoffer** [comment]
@christianh814 Updates are live now here: https://docs.openshift.com/container-platform/4.7/authentication/identity_providers/configuring-github-identity-provider.html#identity-provider-creating-configmap_configuring-github-identity-provider
