### ISSUE TITLE
[enterprise-4.7] Issue in file nodes/scheduling/nodes-scheduler-taints-tolerations.adoc

### ISSUE THREAD

**Issue by hashnao** [openshift/openshift-docs#30427]
### Which section(s) is the issue in?
Understanding evicting pods by condition (taint-based evictions)

### What needs fixing?
1. Replace `tolerationsSeconds` with `tolerationSeconds` in the following sentence.
Taint Based Evictions have ..., unless the pod uses the tolerationsSeconds parameter.
Taint Based Evictions have ..., unless the pod uses the tolerationSeconds parameter.

2. Replace `tolerationSections` with `tolerationSeconds` in the following sentence.
The tolerationSeconds parameter allows ... after the tolerationSections period,
The tolerationSeconds parameter allows ... after the tolerationSeconds period,

**Comment by rolfedh** [comment]
Thanks for reporting this issue, @hashnao. I have created a pull request to fix it that will most likely be merged on Monday.

**Comment by rolfedh** [comment]
Hi, @hashnao. We've merged the fix. If you're satisfied, you can close this issue. Thanks again.

**Comment by hashnao** [comment]
@rolfedh Thanks for your immediate response.
