### ISSUE TITLE
[enterprise-4.5] Issue in file nodes/pods/nodes-pods-secrets.adoc

### ISSUE THREAD

**Issue by esimim** [openshift/openshift-docs#30436]
### Which section(s) is the issue in?
then the version of the secret will be used for the pod will not be defined.

### What needs fixing?
then the version of the secret that will be used for the pod will not be defined.

**Comment by esimim** [comment]
that missing word, if I managed to guess it right, brings lots of confusion to the phrase.

**Comment by mburke5678** [comment]
@esimim Thanks again for catching this one, too. See https://github.com/openshift/openshift-docs/pull/30476
Can you explain better what this means?

**Comment by mburke5678** [comment]
Changes made: https://github.com/openshift/openshift-docs/pull/30476
