### ISSUE TITLE
[enterprise-4.7] Issue in file updating/updating-cluster-between-minor.adoc: explicit mention that client application has to be downloaded manually is missing

### ISSUE THREAD

**Issue by germanparente** [openshift/openshift-docs#30437]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.7/updating/updating-cluster-between-minor.html#prerequisites

### What needs fixing?

My customer would like an explicit mention in the update section that shows the client aplication "oc" has to be downloaded manually.

**Comment by rolfedh** [comment]
Thanks for reporting this issue, @germanparente. I'll help find the best writer to take this issue.

**Comment by bergerhoffer** [comment]
Hi @germanparente. The section you're linking to [1] doesn't actually have any OpenShift CLI (`oc`) commands in it. It 
provides information and then shows you a procedure using the web console. Can you clarify why `oc` is necessary for this section - or did you mean a different section? Thanks!

[1] https://docs.openshift.com/container-platform/4.7/updating/updating-cluster-between-minor.html

**Comment by germanparente** [comment]
Hi,

thanks a lot for taking care about this. In fact, I have chosen this section but in any section you find appropriate to add this remark would be perfect. 

The idea is to mention somewhere that "oc" has to be updated manually by downloading the right version.

It's rather evident for most of customers but I had seen one for whom it was necessary to clarify.

Thanks indeed. Best regards,

German.

**Comment by pneedle-rh** [comment]
@germanparente hi! Thank you for clarifying the requirement.

https://docs.openshift.com/container-platform/4.7/updating/updating-cluster-between-minor.html contains a note at the start of the document that states the following:

"Because of the difficulty of changing update channels by using oc, use the web console to change the update channel. It is recommended to complete the update process within the web console. You can follow the steps in [Updating a cluster within a minor version by using the CLI](https://docs.openshift.com/container-platform/4.7/updating/updating-cluster-cli.html#updating-cluster-cli) to complete the update after you change to a 4.7 channel."

My view is that the following prerequisite in [this section of the document that the note points to](https://docs.openshift.com/container-platform/4.7/updating/updating-cluster-cli.html#update-upgrading-cli_updating-cluster-cli) should be updated to clarify the `oc` version requirement:

* Install the OpenShift CLI (oc) that matches the version for your updated version.

@wking is my understanding correct that you must use the most recent version of the OpenShift CLI (`oc`) that is relevant to your infrastructure provider and installation type, when updating a cluster by using the CLI? Thanks!

**Comment by germanparente** [comment]
hi @pneedle-rh . Thanks for taking care. I think your mention is enough just to clarify that oc command has to be updated manually if someone cannot realize of it. We could even add the link to the binary, like in install section:

https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz

But I let @wking to confirm what's the best.

Thanks a lot,

Best regards,

**Comment by wking** [comment]
I had a chat with @pneedle-rh about this, and the main point here is that there is nothing special about updates with regard to `oc` <-> cluster compatibility.  The [existing compatibility policy][1] still applies, and the relevant server version is the version of the server process you end up being connected to (so if the cluster is partially updated, with some API servers running 4.6.20 and some running 4.7.2, if your `oc` call gets connected to one running 4.6.20, that's the server version that matters to for that call).  In practice, the documented update workflows have been very stable, so things like `oc adm upgrade --to-latest` don't care all that much about either the server or client version.

[1]: https://docs.openshift.com/container-platform/4.7/release_notes/versioning-policy.html

**Comment by germanparente** [comment]
Hi, I agree we can use a former version of "oc" and it could work or the opposite. But it would have helped my customer a sentence saying " you should also upgrade your client manually even if the version can be compatible ". In this case, there was a bug fixed in "oc debug" and the customer kept hitting the bug. I showed how to update the client and the issue was solved. The customer complained he/she had not the proper information and that's the reason why I have reported this.

Thanks !

**Comment by pneedle-rh** [comment]
@germanparente following on from my conversation with @wking yesterday, I will create a draft that applies several changes to help make this topic clearer in the documentation. This includes:

- Making [this compatibility matrix](https://docs.openshift.com/container-platform/4.7/release_notes/versioning-policy.html) findable within the [CLI tools ](https://docs.openshift.com/container-platform/4.7/updating/updating-cluster-cli.html#update-upgrading-cli_updating-cluster-cli) book and from [Updating a cluster by using the CLI](https://docs.openshift.com/container-platform/4.7/updating/updating-cluster-cli.html#update-upgrading-cli_updating-cluster-cli)

- Adding a note to the [Getting started with the OpenShift CLI ](https://docs.openshift.com/container-platform/4.7/cli_reference/openshift_cli/getting-started-cli.html#installing-the-cli) subsections that state that the `oc` version downloaded by using https://cloud.redhat.com/openshift/install is the latest version

- Adding a new subsection [Getting started with the OpenShift CLI ](https://docs.openshift.com/container-platform/4.7/cli_reference/openshift_cli/getting-started-cli.html#installing-the-cli) that describes how to download `oc` from a cluster and states that it is a version match for the cluster

- Updating the first prerequisite in [Updating a cluster by using the CLI](https://docs.openshift.com/container-platform/4.7/updating/updating-cluster-cli.html#update-upgrading-cli_updating-cluster-cli) to state that you must install the `oc` version that is compatible with your cluster. I will also add some additional resources links under that subsection to the [compatibility matrix](https://docs.openshift.com/container-platform/4.7/release_notes/versioning-policy.html) and to [CLI tools -> OpenShift CLI (`oc`)](https://docs.openshift.com/container-platform/4.7/cli_reference/openshift_cli/getting-started-cli.html).

We will then review the draft for suitability, once it has been created. Please let me know if you have any feedback about the proposal in the meantime. Thanks!

**Comment by germanparente** [comment]
Hi,

this is amazing ! THANKS A LOT, @pneedle-rh !!!!

I am on PTO but I can check this later today.

regards,

German.

**Comment by wking** [comment]
> In this case, there was a bug fixed in "oc debug" and the customer kept hitting the bug.

The version-compatibility matrix is only about minor-version compat (e.g. which 4.y you can use).  With each minor version's 4.y.z stream, we'll find and fix bugs.  So yeah, definitely if 4.y.z is giving you trouble, checking Bugzilla and/or updating to the latest z' in that 4.y make a lot of sense.  I dunno if it's worth adding language to the version-compatibility docs to point that out, or if it's just something that folks should expect patch releases to do.
