### ISSUE TITLE
[enterprise-4.7] Issue in file operators/understanding/olm-packaging-format.adoc

### ISSUE THREAD

**Issue by joelanford** [openshift/openshift-docs#30459]
### Which section(s) is the issue in?
["Additionally supported objects"](https://docs.openshift.com/container-platform/4.7/operators/understanding/olm-packaging-format.html#olm-bundle-format-manifests-optional_olm-packaging-format)

### What needs fixing?
The list of supported objects is out-of-date.

As of 4.7, the set of supported objects is here: https://github.com/operator-framework/operator-registry/blob/a97d366a92d302ff2056fa2d19aa3e48b0fbc99c/pkg/lib/bundle/supported_resources.go#L4-L19

Related: https://github.com/operator-framework/olm-docs/issues/119

**Comment by rolfedh** [comment]
Thanks for reporting this issue, @joelanford. I'll help find the writer who is in the best position to fix it.
