### ISSUE TITLE
[enterprise-4.7] Issue in file virt/install/preparing-cluster-for-virt.adoc

### ISSUE THREAD

**Issue by adamgoossens** [openshift/openshift-docs#30497]
### Which section(s) is the issue in?

First para, second bullet point - "Additionally, your cluster must use installer-provisioned infrastructure and deploy machine health checks to maintain high availability (HA) of virtual machines."

### What needs fixing?

This line suggests that IPI is a requirement for use of OCP Virtualisation. This is not correct, so we should reword this statement to something of the effect of:

"It is recommended, but not required, that your baremetal cluster use Installer-Provisioned Infrastructure (IPI) with MachineHealthChecks properly configured, to support high availability (HA) of virtual machines"

**Comment by rolfedh** [comment]
Thanks for reporting this issue, @adamgoossens. I'll help find a writer to take this issue.

**Comment by dankenigsberg** [comment]
To me, the suggested text is adding to the confusion, not resolving it. We need to find a text the delivers two points:
1. You can use OpenShift Virtualization with any bare-metal on-prem cluster, be it IPI or UPI.
2. To achieve true high-availability (e.g in case of network segmentation of the cluster) you have to either
- Use IPI and enable MHC
- Have a monitoring system (or a human) monitor node availability. When a node is lost, the monitor should shut it down and run `oc adm delete node <lost_node>`.

**Comment by rolfedh** [comment]
Separating those two concerns makes it much clearer. Thanks, @dankenigsberg! 
@mgarrellRH will be fixing this issue.

**Comment by mgarrellRH** [comment]
After reading @dankenigsberg 's concerns, the initial wording of the text doesn't seem to be too far off the mark.

**Comment by rolfedh** [comment]
@mgarrellRH Please close this issue. Thanks.

**Comment by sjhala-ccs** [comment]
Closing this issue on behalf of @mgarrellRH
