### ISSUE TITLE
[enterprise-4.7] Issue in file security/compliance_operator/compliance-operator-understanding.adoc

### ISSUE THREAD

**Issue by benemon** [openshift/openshift-docs#30514]
### Which section(s) is the issue in?
Security and Compliance

### What needs fixing?
There's no 'install and configure' section in the docs. When I add the Compliance Operator to my cluster, I'm presented by 11 CustomResources I could create in relation to the compliance operator, but no indication of how or where to start with them. What should I add first? How do I get started? How do I configure a basic compliance scan? etc etc

**Comment by rolfedh** [comment]
Thanks for reporting this issue, @benemon. I'll ask around to see who can help answer these questions in our docs.

**Comment by ahardin-rh** [comment]
@benemon Thanks for reporting this! I am working on addressing these issues in the docs, starting in https://github.com/openshift/openshift-docs/pull/29673. In the meantime, if you have any questions , you can reach out to SME @JAORMX . Thanks!

**Comment by benemon** [comment]
Thanks @ahardin-rh @rolfedh @JAORMX for picking this up and looking to address it so quickly - very much appreciated. The addition of a 'getting started with the compliance operator' section of the docs will go a long way to ensuring people use this capability, and use it correctly!

**Comment by ahardin-rh** [comment]
https://github.com/openshift/openshift-docs/pull/29673 is now merged and the content is now published:https://docs.openshift.com/container-platform/4.7/security/compliance_operator/compliance-operator-installation.html

I am going to close this issue, but please let me know if you have further feedback.
