### ISSUE TITLE
[enterprise-4.7] Issue in file architecture/understanding-development.adoc

### ISSUE THREAD

**Issue by linuxstudio** [openshift/openshift-docs#30557]
### Which section(s) is the issue in?

Building a simple container

### What needs fixing?

In step 2 the text:

"Put your Dockerfile and the software you want to containerized in a directory on your RHEL system."

should be instead:

"Put your Dockerfile and the software you want to containerize in a directory on your RHEL system."

In step 3 the text:

"Run buildah or docker build: Run the buildah build-using-dockerfile or the docker build command to pull you chosen base image to the local system and creates a container image that is stored locally. You can also build container without a Dockerfile by using buildah."

should be instead:

"Run buildah or docker build: Run the buildah build-using-dockerfile or the docker build command to pull your chosen base image to the local system and create a container image that is stored locally. You can also build container images without a Dockerfile by using buildah."

**Comment by sagidlow** [comment]
@linuxstudio This issue has been addressed in our documentation.

**Comment by bobfuru** [comment]
Merged, closing issue. Thanks, @linuxstudio!
