### ISSUE TITLE
[enterprise-4.7] Issue in file architecture/understanding-development.adoc

### ISSUE THREAD

**Issue by linuxstudio** [openshift/openshift-docs#30558]
### Which section(s) is the issue in?

Base image options

### What needs fixing?

The text:

"Special versions of some of these runtime base images referred to as Source-to-image (S2I) images."

should be instead:

"Special versions of some of these runtime base images are referred to as Source-to-image (S2I) images.

**Comment by sagidlow** [comment]
@linuxstudio This issue has been addressed and updated in our documentation.
