### ISSUE TITLE
[enterprise-4.7] Issue in file architecture/control-plane.adoc

### ISSUE THREAD

**Issue by linuxstudio** [openshift/openshift-docs#30555]
### Which section(s) is the issue in?

Understanding the Machine Config Operator

### What needs fixing?

The text in the very last paragraph "Additional information":

"For information on preventing the control plane machines from after the Machine Config Operator makes changes to the machine config, see Disabling Machine Config Operator from automatically rebooting."

should be instead:

"For information on preventing the control plane machines from rebooting after the Machine Config Operator makes changes to the machine config, see Disabling Machine Config Operator from automatically rebooting."

**Comment by sagidlow** [comment]
@linuxstudio This issue has been addressed in our documentation.
