### ISSUE TITLE
[enterprise-4.7] Issue in file machine_management/creating-infrastructure-machinesets.adoc

### ISSUE THREAD

**Issue by soukron** [openshift/openshift-docs#30567]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.7/machine_management/creating-infrastructure-machinesets.html#infrastructure-moving-logging_creating-infrastructure-machinesets

### What needs fixing?
The text:  _You should set your machine set to use at least 6 replicas._ seems to be wrong. The minimal number should be 3.

**Comment by rolfedh** [comment]
Sure, @mburke5678. Thanks for asking. @soukron Are you referring the "You should set your machine set to use at least 6 replicas" note in https://docs.openshift.com/container-platform/4.7/machine_management/creating-infrastructure-machinesets.html#infrastructure-moving-logging_creating-infrastructure-machinesets?

**Comment by rolfedh** [comment]
@mburke5678 Would you mind assigning this to me? Thanks.

**Comment by rolfedh** [comment]
@soukron, the note you reported doesn't make sense where it is located. We are removing it. Thanks again.

**Comment by soukron** [comment]
> @soukron, the note you reported doesn't make sense where it is located. We are removing it. Thanks again.

Thanks. Please excuse the delay. GitHub notification mails are filtered and I missed it.
