### ISSUE TITLE
[enterprise-4.6] Issue in file installing/installing_azure/installing-azure-government-region.adoc

### ISSUE THREAD

**Issue by mohmdnofal** [openshift/openshift-docs#30570]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.6/installing/installing_azure/installing-azure-government-region.html#installation-about-custom-azure-permissions_installing-azure-government-region

The Azure credentials that you use when you create your cluster do not need the networking permissions that are required to make VNets and core networking components within the VNet, such as subnets, routing tables, internet gateways, NAT, and VPN. You still need permission to make the application resources that the machines within the cluster require, such as ELBs, security groups, S3 buckets, and nodes.

### What needs fixing?
Change the above sentence to;

The Azure credentials that you use when you create your cluster do not need the networking permissions that are required to make VNets and core networking components within the VNet, such as subnets, routing tables, internet gateways, NAT, and VPN. You still need permission to make the application resources that the machines within the cluster require, such as Load Balancers, security groups, Storage Accounts, and nodes.

**Comment by codyhoag** [comment]
Thanks for the suggestion. This was fixed in #30590
