### ISSUE TITLE
Typo in command to configure route timeouts

### ISSUE THREAD

**Issue by elyscape** [openshift/openshift-docs#3065]
The page that describes [how to configure route timeouts][timeouts] has a typo in the example command it gives. The command it gives is:
```shellsession
# oc annotate route myroute --overwrite haproxy.router.opensfhit.io/timeout=2s
```
This has `opensfhit` instead of `openshift`. It should read:
```shellsession
# oc annotate route myroute --overwrite haproxy.router.openshift.io/timeout=2s
```

[timeouts]: https://github.com/openshift/openshift-docs/blob/94eef9e/install_config/configuring_routing.adoc#configuring-route-timeouts

**Comment by bfallonf** [comment]
Thanks @elyscape . I created a PR for this. I'll close this PR and merge it.
