### ISSUE TITLE
[enterprise-4.7] Improperly rendered {product-version} in RHV docs 

### ISSUE THREAD

**Issue by maxwelldb** [openshift/openshift-docs#30718]
### Which section(s) is the issue in?
"Downloading the Ansible playbooks"

https://docs.openshift.com/container-platform/4.7/installing/installing_rhv/installing-rhv-user-infra.html#installation-rhv-downloading-ansible-playbooks_installing-rhv-user-infra

### What needs fixing?
{product-version} is shown in the command rather than the actual product version.

**Comment by maxwelldb** [comment]
FYI @rolfedh

**Comment by jboxman** [comment]
I notice this is still an issue and any customer trying to run this will blow up.
