### ISSUE TITLE
Obsolete URL for client tools

### ISSUE THREAD

**Issue by lbrigman124** [openshift/openshift-docs#30745]
### Which section(s) is the issue in?
Installing a cluster on Vsphere.
https://docs.okd.io/latest/installing/installing_vsphere/installing-vsphere-installer-provisioned.html
https://docs.okd.io/latest/installing/installing_vsphere/installing-vsphere-installer-provisioned-customizations.html
https://docs.okd.io/latest/installing/installing_vsphere/installing-vsphere-installer-provisioned-network-customizations.html

### What needs fixing?
There are multiple references in the installing on Vsphere section and others that 
reference this obsolete URL for client tools:
https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/

Replace this link with one that doesn't have a deprecated location message file.
Note the message file points here: https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/
Which is for OCP.

**Comment by GroceryBoyJr** [comment]
Please assign this issue to me....
