### ISSUE TITLE
[enterprise-4.7] Issue in file installing/installing_vsphere/installing-restricted-networks-vsphere.adoc

### ISSUE THREAD

**Issue by cmalafis** [openshift/openshift-docs#30879]
### Which section(s) is the issue in?
Generating an ssh key - this applies for all installation methods, not just vsphere

### What needs fixing?
There should be a note that if the cluster is being installed in FIPS mode, only FIPS allowed algorithms should be used to generate the ssh key.  The key should be either rsa or ecdsa

**Comment by skrthomas** [comment]
Looking into this for Git Hub issue burndown
