### ISSUE TITLE
Lots of broken urls after doc restructure

### ISSUE THREAD

**Issue by ryanj** [openshift/openshift-docs#309]
Looks like we may need to revert.  The current content doesn't look ready.

Including a link to the contributor guidelines might be better than adding empty pages (if the goal is to restructure the docs, and content isn't ready)

**Comment by adellape** [comment]
I'm fixing up broken links ASAP.

**Comment by adellape** [comment]
WIP PR: https://github.com/openshift/openshift-docs/pull/316

**Comment by adellape** [comment]
Fixed in https://github.com/openshift/openshift-docs/pull/316.
