### ISSUE TITLE
[online] Issue in file rosa_getting_started/rosa-creating-cluster.adoc

### ISSUE THREAD

**Issue by mayurshetty** [openshift/openshift-docs#30900]
### Which section(s) is the issue in?

Enter the following command to check the status of your cluster. During cluster creation the State field from the output will transition from pending to installing, and finally to ready.

$ rosa describe cluster rh-rosa-test-cluster1

### What needs fixing?

mshetty@mshetty-mac ROSA % **./rosa describe cluster my-rosa-test** 
Error: required flag(s) "cluster" not set
Usage:
  rosa describe cluster [flags]

Examples:
  # Describe a cluster named "mycluster"
  rosa describe cluster mycluster

  # Describe a cluster using the --cluster flag
  rosa describe cluster --cluster=mycluster

Flags:
  -c, --cluster string   Name or ID of the cluster to describe.
  -h, --help             help for cluster
      --region string    Use a specific AWS region, overriding the AWS_REGION environment variable.

Global Flags:
      --debug            Enable debug mode.
      --profile string   Use a specific AWS profile from your credential file.

Failed to execute root command: required flag(s) "cluster" not set

**It works fine with the --cluster option**

mshetty@mshetty-mac ROSA % ./rosa describe cluster --cluster=my-rosa-test
Name:                       my-rosa-test
ID:                         1jkm7oujlvg69tq3gtakoc4549ft0bfh
External ID:                52382975-5a10-4eac-ab54-90a69babd5b4
OpenShift Version:          
Channel Group:              stable
DNS:                        my-rosa-test.3idi.p1.openshiftapps.com
AWS Account:                631649580137
API URL:                    
Console URL:                
Region:                     us-west-2
Multi-AZ:                   false
Nodes:
 - Master:                  3
 - Infra:                   2
 - Compute:                 2 (m5.xlarge)
Network:
 - Service CIDR:            172.30.0.0/16
 - Machine CIDR:            10.0.0.0/16
 - Pod CIDR:                10.128.0.0/14
 - Host Prefix:             /23
State:                      installing 
Private:                    No
Created:                    Mar 24 2021 21:41:00 UTC
Details Page:               https://cloud.redhat.com/openshift/details/1jkm7oujlvg69tq3gtakoc4549ft0

**Comment by vkareh** [comment]
@sfortner-RH @jonquilwilliams

**Comment by vkareh** [comment]
Related: https://github.com/openshift/rosa/pull/312

**Comment by jonquilwilliams** [comment]
This issue is being fixed by this PR: https://github.com/openshift/openshift-docs/pull/30938
