### ISSUE TITLE
[enterprise-4.7] Issue in file installing/installing_platform_agnostic/installing-platform-agnostic.adoc

### ISSUE THREAD

**Issue by acsulli** [openshift/openshift-docs#30919]
### Which section(s) is the issue in?
The very top-most info/warning message.

### What needs fixing?
The info message linking to https://access.redhat.com/articles/4207611, at the top of the page, has a rendering error.

![image](https://user-images.githubusercontent.com/614443/112480184-243de880-8d4c-11eb-8a27-ab07bf3f82e7.png)

**Comment by codyhoag** [comment]
Thanks, Andrew! This has been updated in #30920
