### ISSUE TITLE
[online] Issue in file rosa_architecture/rosa-basic-architecture-concepts.adoc

### ISSUE THREAD

**Issue by blues-man** [openshift/openshift-docs#30929]
### Which section(s) is the issue in?
https://docs.openshift.com/rosa/rosa_architecture/rosa-basic-architecture-concepts.html#rosa-openshift-concept_rosa-basic-architecture-concepts

### What needs fixing?

Do we need to link comparison table from IBM Cloud? It may look ambiguous as that page talk about IBM Cloud Kubernetes and OpenShift offering

**Comment by jonquilwilliams** [comment]
Merged in 31003.
