### ISSUE TITLE
[enterprise-4.5] Issue in file authentication/understanding-and-creating-service-accounts.adoc

### ISSUE THREAD

**Issue by esimim** [openshift/openshift-docs#30958]
### Which section(s) is the issue in?
oc policy add-role-to-user view system:serviceaccount:top-secret:robot
oc policy add-role-to-user <role_name> -z <service_account_name>
oc policy add-role-to-group view system:serviceaccounts -n top-secret
oc policy add-role-to-group edit system:serviceaccounts:managers -n top-secret

### What needs fixing?
oc adm policy add-role-to-user view system:serviceaccount:top-secret:robot
oc adm policy add-role-to-user <role_name> -z <service_account_name>
oc adm policy add-role-to-group view system:serviceaccounts -n top-secret
oc adm policy add-role-to-group edit system:serviceaccounts:managers -n top-secret

**Comment by kartikaysharma27** [comment]
Hello @esimim 

I followed the steps mentioned in doc: https://docs.openshift.com/container-platform/4.5/authentication/understanding-and-creating-service-accounts.html and it's working as expected, are you also referring to the same?

Could you elaborate or let me know the fix you are looking for while executing the below commands:
oc policy add-role-to-user view system:serviceaccount:top-secret:robot
oc policy add-role-to-user <role_name> -z <service_account_name>
oc policy add-role-to-group view system:serviceaccounts -n top-secret
oc policy add-role-to-group edit system:serviceaccounts:managers -n top-secret

As, it's works for both the administrator and normal user.

**Comment by kartikaysharma27** [comment]
Hi @vikram-redhat Can you assign this to me?

**Comment by esimim** [comment]
Hi, I saw
'oc *adm* policy add-role-to-user ...'
all over the documentation, like:

[image: Screen Shot 2021-04-12 at 15.35.10.png]

[image: Screen Shot 2021-04-12 at 15.37.49.png]

I didn't actually test and did not know that this:
oc policy add-role-to-user <role_name> -z <service_account_name>
would also work, my apologies.

I just thought that it had to be like the above.

Cheers
