### ISSUE TITLE
[enterprise-4.7] Issue in file installing/installing_bare_metal/installing-bare-metal-network-customizations.adoc

### ISSUE THREAD

**Issue by pamoedom** [openshift/openshift-docs#30974]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.7/installing/installing_bare_metal/installing-bare-metal.html#installation-user-infra-machines-pxe_installing-bare-metal

https://docs.openshift.com/container-platform/4.7/installing/installing_bare_metal/installing-bare-metal-network-customizations.html#installation-user-infra-machines-pxe_installing-bare-metal-network-customizations

https://docs.openshift.com/container-platform/4.7/installing/installing_bare_metal/installing-restricted-networks-bare-metal.html#installation-user-infra-machines-pxe_installing-restricted-networks-bare-metal

### What needs fixing?

When using iPXE with `UEFI` boot mode, the kernel line should also contain the variable `initrd=`, but instead of pointing to the whole `initramfs` URL, it should only contain the image file name, for example:

~~~
#!ipxe

kernel  http://<HTTP_server>/rhcos-<version>-live-kernel-<architecture> initrd=rhcos-<version>-live-initramfs.<architecture>.img coreos.live.rootfs_url=http://<HTTP_server>/rhcos-<version>-live-rootfs.<architecture>.img coreos.inst.install_dev=/dev/sda coreos.inst.ignition_url=http://<HTTP_server>/bootstrap.ign  
initrd http://<HTTP_server>/rhcos-<version>-live-initramfs.<architecture>.img
boot
~~~

I think we should include a note about this, please see [BZ#1940586](https://bugzilla.redhat.com/show_bug.cgi?id=1940586) for more details.

**Comment by jlebon** [comment]
This has come up in the past as well, see discussions in https://bugzilla.redhat.com/show_bug.cgi?id=1845180.

**Comment by pamoedom** [comment]
Thanks @jlebon, I'll reopen the BZ because for versions >=4.6, iPXE boot with UEFI mode is not working unless the initrd for kernel argument points to just the image file name and not the whole URL.

**Comment by bgilbert** [comment]
Fixed in https://github.com/openshift/openshift-docs/pull/31769.
