### ISSUE TITLE
[enterprise-4.7] Issue in file logging/cluster-logging-deploying.adoc

### ISSUE THREAD

**Issue by forenkla** [openshift/openshift-docs#30976]
### Which section(s) is the issue in?
3.1 Installing OpenShift Logging

### What needs fixing?

- Elasticsearch Operator should be OpenShift Elasticsearch Operator
- Cluster Logging should be Red Hat OpenShift Logging
- No button to copy YAML-file, only select/copy which includes footnotes

**Comment by Preeticp** [comment]
@rolfedh can you PTAL and create a parallel jira issue for the same?

**Comment by rolfedh** [comment]
https://issues.redhat.com/browse/RHDEVDOCS-2900

**Comment by rolfedh** [comment]
Thank you for your feedback @forenkla. I will be addressing these issues. 
* To copy YAML and other code snippets, please use the OpenShift documentation here: https://docs.openshift.com/container-platform/4.7/logging/cluster-logging-deploying.html

**Comment by rolfedh** [comment]
@Preeticp Would you please assign this issue to me? Thanks.

**Comment by rolfedh** [comment]
- I'm updating a couple of instances of "Cluster Logging" on the customer portal documentation site that we still needed to update to "Openshift Logging." PR 
- I'm also updating "Elasticsearch Operator" in the documentation to "OpenShift Elasticsearch Operator."

**Comment by jeana-redhat** [comment]
Cherrypicks are merged, attempting to close.
