### ISSUE TITLE
[enterprise-4.7] Issue in file nodes/nodes/nodes-nodes-garbage-collection.adoc

### ISSUE THREAD

**Issue by ikke-t** [openshift/openshift-docs#30986]
### Which section(s) is the issue in?

file: nodes-nodes-garbage-collection-configuring.adoc

Configuring garbage collection for containers and images -> Procedure

### What needs fixing?

There is sample configuration for a container garbage collection CR. I don't dare to put it into place, as it has undocumented feature. This whole page talks about disk pressure and cleaning it, however this CR template has parameter: ```memory.available: "500Mi"``` and ohters related to memory. What do they mean and how are they related to disk pressure?

-> explain the parameters, or take them away if they  are not needed here.

**Comment by mburke5678** [comment]
@ikke-t Thank you for pointing this out. Sorry to have take so long to get around to it. Can you take a [look at my PR](https://github.com/openshift/openshift-docs/pull/38581/files#diff-0b5e69508ec8e718945927f50949de41b4f098bd73a9e4b716fd629efe54e5c7) to see if this is what you expect?

**Comment by mburke5678** [comment]
PR is merged. Thsnks for the request @ikke-t
