### ISSUE TITLE
[enterprise-4.7] Issue in file service_mesh/v2x/installing-ossm.adoc

### ISSUE THREAD

**Issue by jwennerberg** [openshift/openshift-docs#30981]
### Which section(s) is the issue in?
- Installing Elasticsearch Operator
- Installing Jaeger Operaror

### What needs fixing?
- References to "Elasticsearch Operator" should be changed to "OpenShift Elasticsearch Operator"
- References to "Jaeger Operator" should be changed to "Red Hat OpenShift Jaeger"

**Comment by JStickler** [comment]
Tracking this work as part of https://issues.redhat.com/browse/OSSMDOC-288.
