### ISSUE TITLE
[enterprise-4.7] Issue in file windows_containers/windows-containers-release-notes-2-x.adoc

### ISSUE THREAD

**Issue by johanodell** [openshift/openshift-docs#31008]
### Which section(s) is the issue in?

Under known issues 

To pick the correct image for the MachineSet object, follow the instructions based on your cloud provider:

### What needs fixing?

Running the suggested AWS query for AMIs does return the value null in every region tested. 

aws ec2 describe-images --filters Name=name,Values=Windows_Server-2019-English-Full-ContainersLatest-2020.09.09 --region <region> --query 'Images[*].[ImageId]' --output=json | jq .[0][0] 

Need to update search values in document to something that exists.

**Comment by codyhoag** [comment]
This was a known issue that was just recently resolved today in #30927. The workaround is no longer necessary and, therefore, has been removed. The live docs should reflect the changes soon.
