### ISSUE TITLE
[enterprise-4.7] Issue in file windows_containers/enabling-windows-container-workloads.adoc

### ISSUE THREAD

**Issue by johanodell** [openshift/openshift-docs#31015]
### Which section(s) is the issue in?

Installing the Windows Machine Config Operator using the web console
4. On the Install Operator page:
Select the 4.7 channel as the Update Channel. The 4.7 channel enables the latest stable release of the WMCO to be installed.

### What needs fixing?

the Update Channels available are preview or stable. There is no 4.7 alternative. This needs to be reflected in the documentation to minimize confusion.

**Comment by codyhoag** [comment]
Thanks for identifying that issue. I have sent a PR to be merged in #31020
