### ISSUE TITLE
[enterprise-4.5] Issue in file security/certificate_types_descriptions/proxy-certificates.adoc

### ISSUE THREAD

**Issue by adityad97** [openshift/openshift-docs#31018]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.5/security/certificate_types_descriptions/proxy-certificates.html#purpose
 Purpose section

### What needs fixing?
~~~
data:
  ca-bundle.crt: |
  -----BEGIN CERTIFICATE-----
  Custom CA certificate bundle.
  -----END CERTIFICATE-----
~~~
Indentation needs to be fixed for certificate details. 

It should be like:
~~~
data:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    Custom CA certificate bundle.
    -----END CERTIFICATE-----
~~~

**Comment by ctauchen** [comment]
Can you assign this to me @vikram-redhat ? Thanks!
