### ISSUE TITLE
[enterprise-4.7] Issue in file release_notes/ocp-4-7-release-notes.adoc

### ISSUE THREAD

**Issue by cvantuin** [openshift/openshift-docs#31088]
### Which section(s) is the issue in?

About this release

### What needs fixing?
OpenShift Container Platform 4.7 is supported on Red Hat Enterprise Linux (RHEL) 7.7 or later, as well as Red Hat Enterprise Linux CoreOS (RHCOS) 4.6.

Is CoreOS 4.6 correct?   Usually OCP version = CoreOS version?

**Comment by vikram-redhat** [comment]
@jeana-redhat can you take a look?

**Comment by jeana-redhat** [comment]
@cvantuin thanks for reporting! I'm sure that you are right, and am just waiting on confirmation before I make the change.

**Comment by jeana-redhat** [comment]
Update: PR can be merged pending change notification process

**Comment by jeana-redhat** [comment]
Forgot to close this issue after the fix was merged, closing now.
