### ISSUE TITLE
route json defs still include id field

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-docs#311]

**Comment by adellape** [comment]
@thoraxe I see `"id"` fields in the following spots:

http://docs.openshift.org/latest/architecture/core_objects/routing.html#route-types

http://docs.openshift.org/latest/architecture/core_objects/openshift_model.html#route

I assumed with this Issue you were saying that they should be removed, but I was comparing against the beta3 training and found them still there as well:

https://github.com/openshift/training/blob/master/beta-3-setup.md#routing

https://github.com/openshift/training/blob/master/beta-3-setup.md#creating-the-definition

Can you confirm / give some context for this? Thanks.

**Comment by adellape** [comment]
OK, I see the `"id"`-less route here:

https://github.com/openshift/training/blob/master/beta3/sinatra-route.json

**Comment by adellape** [comment]
This was addressed as the examples were updated for the v1 API, and route definitions no longer contain "id". E.g.,:

Arch topic - https://docs.openshift.org/latest/architecture/core_concepts/routes.html

Dev guide topic - https://docs.openshift.org/latest/dev_guide/routes.html
