### ISSUE TITLE
Links on router overview page broken

### ISSUE THREAD

**Issue by tiwillia** [openshift/openshift-docs#3110]
There are several links at the bottom of this page that either 404 or resolve to a non-existing hash anchor:

  https://docs.openshift.org/latest/install_config/router/index.html

These links appear to have been introduced with https://github.com/openshift/openshift-docs/commit/5fc665d227aeb4bd02bc5ecc6b85415c6bbf6412#diff-f59186b0be7d942d5e6688257c3b91eaR102

**Comment by bfallonf** [comment]
@tiwillia This is very strange. I get the 404 errors and the incorrect hash thing, but the raw ascii file is correct. Plus, when I sent this issue to two others, the links worked for them.

Don't suppose you know why that's happening? Could it be a problem with the site?

**Comment by tiwillia** [comment]
@bfallonf I submitted the issue instead of a fix because I couldn't figure out why it was happening :open_mouth: 

In fact, I just loaded up the page today and the links all appear to be working without issue in both firefox and chrome on my two separate systems. Interesting that you also hit the issue. Did some change go through between yesterday and today on the docs website?

**Comment by bfallonf** [comment]
@tiwillia Guh, this is odd. @adellape did the weekly release overnight, but I don't think he touched this file. I...have no idea.

I'll leave this issue open for now, and check in a day or two *shrugs*

**Comment by bfallonf** [comment]
@tiwillia I've been checking this, and it seems to be OK. I'll close this issue, but let me know if you find there's still something wrong here. Thanks, again!
