### ISSUE TITLE
[enterprise-4.7] Issue in file installing/installing_bare_metal_ipi/ipi-install-prerequisites.adoc

### ISSUE THREAD

**Issue by larsks** [openshift/openshift-docs#31151]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.7/installing/installing_bare_metal_ipi/ipi-install-prerequisites.html#network-requirements_ipi-install-prerequisites

### What needs fixing?

The "Network Requirements" section says:

> Installer-provisioned installation of OpenShift Container Platform involves several network requirements by default. First, installer-provisioned installation involves a non-routable provisioning network for provisioning the operating system on each bare metal node and a routable baremetal network. Since installer-provisioned installation deploys ironic-dnsmasq, the networks should have no other DHCP servers running on the same broadcast domain. Network administrators must reserve IP addresses for each node in the OpenShift Container Platform cluster.

But that's incorrect: `ironic-dnsmasq` only provides services on the
*provisioning* network. The operator is expected to provide their own
DHCP service on the baremetal network.

**Comment by jboxman** [comment]
fyi @johnwilkins
