### ISSUE TITLE
Confusing sizing considerations

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/openshift-docs#3118]
# What

The numbers in the documentation don't add up.

# Where

https://docs.openshift.org/latest/install_config/install/planning.html#sizing

----

## Sizing Considerations

Determine how many nodes and pods you require for your OpenShift Origin cluster.
The following table provides the sizing limits for nodes and pods:

Type | Maximum
------ | -------------
Maximum nodes per cluster |1000
Maximum pods per cluster |120,000
Maximum pods per nodes |250
Maximum pods per core |10

For example, if you require 2200 pods, you need at least 20 nodes in your
environment.

This also means the maximum number of pods that can run safely in your
environment is 33,000.

----

# Details

If it is 250 pods per node, then 250 * 9 = 2250, so "if you require 2200 pods, you need at least **9** nodes in your environment, and you can safely run a maximum of **2250**".

This is somewhat related to #2180, though the content is different.

A minor nit, the usage of thousands separator in that section is inconsistent: "1000", "2200", "33,000"...

**Comment by rhcarvalho** [comment]
@openshift/team-documentation

**Comment by vikram-redhat** [comment]
@danmacpherson - one more issue to take a look at in the same section. Thanks!

**Comment by ahardin-rh** [comment]
@vikram-redhat This is being addressed in https://github.com/openshift/openshift-docs/pull/2987. Thanks!

**Comment by rhcarvalho** [comment]
Closing this in favor of the existing PR / bugzilla.
