### ISSUE TITLE
Confusing table in RPM vs Containerized installation topic

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/openshift-docs#3119]
Maybe it is just me, but I have a hard time trying to understand the table in:

https://docs.openshift.org/latest/install_config/install/planning.html#rpm-vs-containerized

![image](https://cloud.githubusercontent.com/assets/88819/19729918/d9396ae8-9b98-11e6-9aa8-7ab92916dbdc.png)
### 1. Column titles

The relationship between "Type", "RPM", "Containerized" and "Installation Method" is unclear.

> ... the differences between the RPM and Containerized methods:

Are _type_ and _method_ being used interchangeably?

On the same page, "[Installation Method](https://docs.openshift.org/latest/install_config/install/planning.html#installation-methods)" referred to either _quick install_ or _advanced install_, but that seems unrelated to the contents of that column.
### 2. Unclear comparisons

The comparison is between two things, but the table has 4 columns. It seems like facts are scattered around and I need to figure out what is related to the "RPM installation method" and what is related to "Containerized installation method".

**Comment by rhcarvalho** [comment]
@openshift/team-documentation

**Comment by vikram-redhat** [comment]
Thanks @rhcarvalho . Looks like something got messed up in the asciidoc. Yes, this table is not supposed to look like this. 

@danmacpherson - assigning this to you as part of the Install/Config re-org that you are doing.

**Comment by ahardin-rh** [comment]
Looks like this work was addressed via https://github.com/openshift/openshift-docs/pull/2776
