### ISSUE TITLE
[enterprise-4.7] Issue in file security/compliance_operator/compliance-operator-manage.adoc

### ISSUE THREAD

**Issue by r2d2rnd** [openshift/openshift-docs#31225]
### Which section(s) is the issue in?
Using image streams

### What needs fixing?

The commands to be executed against the imagestreams are not indicating the namespace. This is an issue since if you are in a different project than "openshift", you won't able to list the "is" or do any operation on them. 

Then, it should be changed for a better understanding, the next commands:

This:

~~~
$ oc get is
~~~

By this:

~~~
$ oc -n openshift get is
~~~

This:

~~~
$ oc patch is openscap-ocp4-ds \
    -p '{"spec":{"lookupPolicy":{"local":true}}}' \
    --type=merge
~~~

By this:

~~~
$ oc -n openshift patch is openscap-ocp4-ds \
    -p '{"spec":{"lookupPolicy":{"local":true}}}' \
    --type=merge
~~~

This:

~~~
$ oc get istag
~~~

By this:

~~~
$ oc -n openshift get istag
~~~

**Comment by kartikaysharma27** [comment]
Hello @vikram-redhat Can you assign this to me? Thanks.

**Comment by kartikaysharma27** [comment]
@r2d2rnd thank you for reporting. I am quite sure you are right to have a namespace mentioned. But as per the doc: https://docs.openshift.com/container-platform/4.7/security/compliance_operator/compliance-operator-manage.html , I don't think that we will get the mentioned "image stream" from "openshift" namespace. Let me know what you think.

I need to confirm before proceeding, but while have a look at # oc get is , the image stream is referring to image repository "image-registry.openshift-image-registry.svc:5000/openshift-compliance". Hence namespace would be "openshift-compliance"

On the other look, if you try to get image stream from "openshift" namespace, then the image stream might be referring to image repository "image-registry.openshift-image-registry.svc:5000/openshift/", hence namespace would be "openshift".

After having a confirmation and check with the team, I will proceed further.

Let me know if you have any questions.

**Comment by kartikaysharma27** [comment]
https://github.com/openshift/openshift-docs/pull/31270

**Comment by ahardin-rh** [comment]
@r2d2rnd Thanks for reporting this issue and thank you @kartikaysharma27 for addressing it. The fix is now merged and I am closing the issue. Please let me know if I can provide further assistance. Thank you!
