### ISSUE TITLE
[online] Issue in file rosa_getting_started/rosa-aws-prereqs.adoc

### ISSUE THREAD

**Issue by tnk4on** [openshift/openshift-docs#31227]
### Which section(s) is the issue in?

Prerequisites for Red Hat OpenShift Service on AWS

### What needs fixing?

All "AWS Organization" should be "AWS Organizations".
"AWS Organizations" is a proper noun.

Reference link:
https://aws.amazon.com/organizations/

**Comment by tnk4on** [comment]
All "AWS Organiation" in this page should be "AWS Organizations".

https://docs.openshift.com/rosa/rosa_getting_started/rosa-aws-prereqs.html

**Comment by jonquilwilliams** [comment]
This is fixed in: https://github.com/openshift/openshift-docs/pull/32616

**Comment by tnk4on** [comment]
@jonquilwilliams Thanks!

**Comment by jonquilwilliams** [comment]
@tnk4on  Thanks for catching these typos!
