### ISSUE TITLE
[enterprise-Branch Build] Issue in file security/compliance_operator/compliance-operator-remediation.adoc

### ISSUE THREAD

**Issue by pdhamdhe** [openshift/openshift-docs#31274]
### Which section(s) is the issue in?

https://deploy-preview-29673--osdocs.netlify.app/openshift-enterprise/latest/security/compliance_operator/compliance-operator-remediation.html#compliance-unapplying_compliance-remediation

### What needs fixing?
Need to mention complete patch command. It looks incomplete. Refer section https://deploy-preview-29673--osdocs.netlify.app/openshift-enterprise/latest/security/compliance_operator/compliance-operator-remediation.html#compliance-applying_compliance-remediation

**Comment by kartikaysharma27** [comment]
@vikram-redhat Can you assign this to me? Thanks

**Comment by kartikaysharma27** [comment]
@pdhamdhe Thanks for reporting. I will do the needful check and will proceed further. Meanwhile, if possible can you share the complete patch command you are looking for fix(two check that we are on same page :-) ) https://deploy-preview-29673--osdocs.netlify.app/openshift-enterprise/latest/security/compliance_operator/compliance-operator-remediation.html#compliance-unapplying_compliance-remediation

**Comment by pdhamdhe** [comment]
@kartikaysharma27 Hi, You can refer the patch command from [compliance-applying_compliance-remediation](https://deploy-preview-29673--osdocs.netlify.app/openshift-enterprise/latest/security/compliance_operator/compliance-operator-remediation.html#compliance-applying_compliance-remediation) section and just replace `"apply":true` in command with `"apply":false`.

**Comment by vikram-redhat** [comment]
Hi @pdhamdhe and @kartikaysharma27 - is this an issue in published docs? Or the preview for another PR of https://github.com/openshift/openshift-docs/pull/29673? I believe it is for the later so this review should be left in that PR itself rather than opening a new issue. 

New issues are for published docs only.

**Comment by pdhamdhe** [comment]
@vikram-redhat Hi, This issue from published 4.6 docs [compliance-unapplying_compliance-remediation](https://docs.openshift.com/container-platform/4.6/security/compliance_operator/compliance-operator-remediation.html#compliance-unapplying_compliance-remediation) hence I opened a new issue.

**Comment by vikram-redhat** [comment]
Thanks @pdhamdhe! It looks like you may have used the report an issue from the preview docs here https://deploy-preview-29673--osdocs.netlify.app/openshift-enterprise/latest/security/compliance_operator/compliance-operator-remediation.html#compliance-unapplying_compliance-remediation which is a temporary preview site. :) 

All good if @kartikaysharma27 knows where the actual fix needs to be.

**Comment by kartikaysharma27** [comment]
Ack @vikram-redhat I will work on it. Thank you.

@pdhamdhe I will proceed further with it, once I get clarification on the patch command. Let me know if you have any questions.

**Comment by pdhamdhe** [comment]
@vikram-redhat Oh.. Sorry for the confusion. Yes, you are right. I reported it through a temporary preview site instead of published docs.
