### ISSUE TITLE
No way to access documentation for older versions

### ISSUE THREAD

**Issue by exowaucka** [openshift/openshift-docs#3128]
I'm still running OpenShift Origin 1.2.  I want to read the documentation without having to guess which parts only apply to 1.3.  If the 1.2 documentation exists anywhere, it's pretty well-hidden.  All Google queries lead to https://docs.openshift.org/latest (the 1.3 documentation).

**Comment by bfallonf** [comment]
@vikram-redhat @nhr Have you guys got any thoughts on this? I'm not sure what the thoughts on past releases of Origin are.

**Comment by vikram-redhat** [comment]
I don't know how much control or influence we have over the direction or policies of the OpenShift Origin docs. The decision to have only one version of Origin docs was probably taken before I started looking after the Enterprise docs.

cc: @aheslin or @danmcp or @mpbarrett - what is our policy here?

**Comment by exowaucka** [comment]
The URL path prefix for the docs is `/latest`, which suggests that whoever set it up was thinking about having multiple versions available.

**Comment by nhr** [comment]
@exowaucka Sorry for the difficulty here. `/latest` refers to the fact that the primary published Origin docs are continuously being built from the `master` branch. If we reach a point where Origin and commercial releases are not in lock-step on features, we will begin tagging the docs repo specifically for Origin releases. However, for the time being we can generate Origin docs from the same branch that we use for the corresponding commercial release.

Having said that, we haven't actually been doing it. I've opened a PR that will build Origin 1.2 docs and publish them to the docs.openshift.org site: https://github.com/openshift/openshift-docs/pull/3129
