### ISSUE TITLE
[v3 online] add example of how to get oauth token from api and from web interface

### ISSUE THREAD

**Issue by dustymabe** [openshift/openshift-docs#3130]
It would be nice if we had docs that told the users how to get the api token for openshift online.

We should mention how to get it from the about page (with screenshots maybe) as well as how to get it directly from the API (https://api.preview.openshift.com/oauth/token/request) 

I looked for docs on this [here](https://docs.openshift.com/online/cli_reference/get_started_cli.html) but did not find anything.

**Comment by bfallonf** [comment]
Thanks, @dustymabe !

I've created a BZ for this:

https://bugzilla.redhat.com/show_bug.cgi?id=1390030

Hopfully this can be get to within the next few sprints. I'll close this issue in favour of that.
