### ISSUE TITLE
Full PS1 prompt or just $?

### ISSUE THREAD

**Issue by e-minguez** [openshift/openshift-docs#31330]
### Which section(s) is the issue in?

Installing / Deploying installer-provisioned clusters on bare metal / Setting up the environment for an OpenShift installation / Generating the self-signed certificate (optional)

### What needs fixing?

Those commands include the full PS1 prompt (which I think it is useless) and for instance https://docs.openshift.com/container-platform/4.7/installing/install_config/installing-restricted-networks-preparations.html only include the dollar sign.
I guess it would be nice to be consistent and use only the dollar sign.

**Comment by jboxman** [comment]
@e-minguez thanks!
