### ISSUE TITLE
GitHub account required to install OpenShift

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/openshift-docs#3133]
Going through the [installation prerequisites](https://docs.openshift.com/container-platform/3.3/install_config/install/prerequisites.html#prereq-git), I found it weird that we require people to have a __GitHub account__ in order to install OpenShift.

Looking back at the repo history, seems this concept is as old as the first installation draft:
https://github.com/openshift/openshift-docs/pull/69/files#diff-e863331939418b2a436f75d863b8a71bR52

Since I don't know why it is listed there this issue is about either:

- Clarify why a GitHub account is required and listed in the installation prerequisites; or
- Remove that section from the prerequisites documentation.

**Comment by rhcarvalho** [comment]
@openshift/team-documentation /cc @adellape @nhr

**Comment by bfallonf** [comment]
cc @danmacpherson for your install guide efforts.
