### ISSUE TITLE
Installation prerequisites references a playbook out of context

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/openshift-docs#3134]
I've been reading the installation docs from the beginning. When I got to:

https://docs.openshift.com/container-platform/3.3/install_config/install/prerequisites.html#overriding-detected-ip-addresses-and-host-names

> ```
> # ansible-playbook playbooks/byo/openshift_facts.yml
> ```

I noticed it is referencing a playbook from openshift-ansible, much before anything was said about the existence of openshift-ansible, so only someone who knows already how to install can possibly know what that playbook is...

@openshift/team-documentation and /cc @adellape @ahardin-rh for contents added in #1730.

**Comment by bfallonf** [comment]
cc @danmacpherson for your install guide efforts.

**Comment by vikram-redhat** [comment]
I believe this was fixed with the reorg last year. Please feel free to reopen if the issue persists.
