### ISSUE TITLE
Setting min value to 0 in a LimitRange does not allow the pod to consume more than the max CPU value

### ISSUE THREAD

**Issue by alosadagrande** [openshift/openshift-docs#31354]
### Which section(s) is the issue in?

[Container Limits](https://docs.openshift.com/container-platform/4.7/nodes/clusters/nodes-cluster-limit-ranges.html#nodes-cluster-limit-container-limits)
[Pod limits](https://docs.openshift.com/container-platform/4.7/nodes/clusters/nodes-cluster-limit-ranges.html#nodes-cluster-limit-pod-limits)

### What needs fixing?

The documentation states "The minimum amount of CPU that a single container in a pod can request. Not setting a min value or setting 0 is unlimited, allowing the Pod to consume more than the max CPU value." and "The minimum amount of memory that a single container in a pod can request. Not setting a min value or setting 0 is unlimited, allowing the Pod to consume more than the max memory value.
"

During my tests, I have not been able to reproduce what it states. I created a LimitRange and set the min value to 0 and even remove the min value for CPU. Then I set the max CPU request to a proper value, for instance, 500m (0.5). 

Next, I created a deployment requesting 2 CPUs. From the doc I understand that if I do not define min or set it to 0, the Pod can consume more than the max CPU value. In this case, my pod did not get scheduled since the value I was requesting was greater than the max CPU value configured in the LimitRange:

```
    - lastTransitionTime: "2021-04-07T13:01:55Z"
      lastUpdateTime: "2021-04-07T13:01:55Z"
      message: 'pods "test-requests-54d99fdc4f-gqnlv" is forbidden: maximum cpu usage per Pod is 500m, but limit is 2'
      reason: FailedCreate
      status: "True"
      type: ReplicaFailure
    observedGeneration: 16
    unavailableReplicas: 1
```

This means that the Pod cannot consume more than the max CPU value.

**Comment by mburke5678** [comment]
@alosadagrande Thank you for catching this error. I changed the sentence to read: _Not setting a `min` value uses the default value._ Please take a look. https://github.com/openshift/openshift-docs/pull/31501/files

**Comment by mburke5678** [comment]
PR is merged.
