### ISSUE TITLE
[enterprise-4.7] Issue in file logging/config/cluster-logging-curator.adoc

### ISSUE THREAD

**Issue by ehvs** [openshift/openshift-docs#31475]
### Which section(s) is the issue in?
First paragraph.
https://docs.openshift.com/container-platform/4.7/logging/config/cluster-logging-curator.html

### What needs fixing?
The first sentence is very misleading. It gives the understanding that Curator still the main tool being used in the stack when actually are the `IndexManagement` cronjobs for 4.5 and later.

~~~
In OpenShift Container Platform 4.7, log curation is performed by Elasticsearch Curator, based on a retention policy that you define.
The Elasticsearch Curator tool removes Elasticsearch indices that use the data model prior to OpenShift Container Platform 4.5. You can modify the Curator index retention policy for your old data.
~~~

Suggestions for improvement: 

~~~
In OpenShift Container Platform 4.7, log curation is performed by ElasticSearch `IndexManagement` - the `elasticsearch-im-app`, `elasticsearch-im-audit` and `elasticsearch-im-infra ` cronjobs that can be set in [retentionPolicy](https://docs.openshift.com/container-platform/4.7/logging/config/cluster-logging-log-store.html#cluster-logging-elasticsearch-retention_cluster-logging-store).

Elasticsearch Curator will be deprecated in future versions and if the cluster was deployed on RHOCP 4.5 version, Elasticsearch Curator is not required.
The Elasticsearch Curator tool removes Elasticsearch indices that use the data model prior to OpenShift Container Platform 4.5. You can modify the Curator index retention policy for your old data in the `clusterlogging` instance.
~~~

Additional information: 
The same modification can be applied to OCP 4.5 and 4.6

**Comment by Preeticp** [comment]
@rolfedh PTAL, request you to create a parallel Jira issue, we can take it up and fix it based on our DPM planning.

**Comment by rolfedh** [comment]
@Preeticp WIP. Please reassign to me. Thanks!

**Comment by rolfedh** [comment]
Thanks again for flagging this issue, @ehvs. I've finished applying your suggestion to the documentation.

**Comment by rolfedh** [comment]
@Preeticp would you close this for me. Thanks.
