### ISSUE TITLE
[enterprise-4.7] Issue in file operators/operator_sdk/golang/osdk-golang-tutorial.adoc

### ISSUE THREAD

**Issue by porridge** [openshift/openshift-docs#31478]
### Which section(s) is the issue in?

The `About OpenAPI validation` section.

### What needs fixing?

The whole section is duplicated.

**Comment by mburke5678** [comment]
@porridge Thank you for pointing this out!

**Comment by mburke5678** [comment]
@adellape It looks like the text from the  _osdk-about-openapi-validation.adoc_ module is also in the previous  module: _osdk-golang-generate-crd.adoc_

See: 
https://github.com/openshift/openshift-docs/blob/master/modules/osdk-golang-generate-crd.adoc
https://github.com/openshift/openshift-docs/blob/master/modules/osdk-about-openapi-validation.adoc

Let me know if you want me to fix this.
