### ISSUE TITLE
Metrics Deployer template's PATH not existent anymore in OSCP 3.3

### ISSUE THREAD

**Issue by alezzandro** [openshift/openshift-docs#3148]
Hello,

I've just checked that on section "Modifying the Deployer Template":
https://docs.openshift.com/container-platform/3.3/install_config/cluster_metrics.html#modifying-the-deployer-template

The documentation referes to PATH: "/usr/share/openshift/examples/infrastructure-templates/origin/metrics-deployer.yaml", that's not existent anymore.

In detail, if you're upgrading your OSCP from 3.2 to 3.3, following the documentation you'll end up deploying a 3.2 metrics on a 3.3 cluster. This will drive you to a not-working metrics deployment.

I was able to find that file again through yum in package:

openshift-ansible-roles-3.3.41-1.git.0.a1a327b.el7.noarch : Openshift and Atomic Enterprise Ansible roles
Repo        : @rhel-7-server-ose-3.3-rpms
Matched from:
Filename    : /usr/share/ansible/openshift-ansible/roles/openshift_examples/files/examples/v1.4/infrastructure-templates/origin/metrics-deployer.yaml
Filename    : /usr/share/ansible/openshift-ansible/roles/openshift_examples/files/examples/v1.3/infrastructure-templates/origin/metrics-deployer.yaml
Filename    : /usr/share/ansible/openshift-ansible/roles/openshift_examples/files/examples/v1.3/infrastructure-templates/enterprise/metrics-deployer.yaml
Filename    : /usr/share/ansible/openshift-ansible/roles/openshift_examples/files/examples/v1.2/infrastructure-templates/origin/metrics-deployer.yaml
Filename    : /usr/share/ansible/openshift-ansible/roles/openshift_examples/files/examples/v1.1/infrastructure-templates/enterprise/metrics-deployer.yaml
Filename    : /usr/share/ansible/openshift-ansible/roles/openshift_examples/files/examples/v1.4/infrastructure-templates/enterprise/metrics-deployer.yaml
Filename    : /usr/share/ansible/openshift-ansible/roles/openshift_examples/files/examples/v1.2/infrastructure-templates/enterprise/metrics-deployer.yaml
Filename    : /usr/share/ansible/openshift-ansible/roles/openshift_examples/files/examples/v1.0/infrastructure-templates/enterprise/metrics-deployer.yaml
Filename    : /usr/share/ansible/openshift-ansible/roles/openshift_examples/files/examples/v1.1/infrastructure-templates/origin/metrics-deployer.yaml
Filename    : /usr/share/ansible/openshift-ansible/roles/openshift_examples/files/examples/v1.0/infrastructure-templates/origin/metrics-deployer.yaml

Actually I don't know if that was the right path/file to use, anyway it worked well, deployed latest & working metrics components.

**Comment by bfallonf** [comment]
@alezzandro This interesting. I can find this file in my 3.3 our environment and I can't find the one you ask to replace it with... Maybe something was missed in your installation?

**Comment by ronsengupta** [comment]
I also did not find this file. Please update the documentation.
