### ISSUE TITLE
[enterprise-4.7] Issue in file operators/understanding/olm/olm-understanding-olm.adoc

### ISSUE THREAD

**Issue by linuxstudio** [openshift/openshift-docs#31508]
### Which section(s) is the issue in?
Cluster service version
second paragraph

### What needs fixing?
"think of the packaging step for OLM as the stage at which you make your rpm, dep, or apk bundle."
should be instead:
"think of the packaging step for OLM as the stage at which you make your rpm, deb, or apk bundle."

**Comment by pneedle-rh** [comment]
Updated content is now available in the following:

https://docs.openshift.com/container-platform/4.7/operators/understanding/olm/olm-understanding-olm.html
https://docs.openshift.com/container-platform/4.7/operators/understanding/olm/olm-understanding-olm.html
