### ISSUE TITLE
[enterprise-4.7] Issue in file installing/installing_aws/installing-aws-government-region.adoc

### ISSUE THREAD

**Issue by matt314** [openshift/openshift-docs#31504]
### Which section(s) is the issue in?
Uploading a custom RHCOS AMI in AWS, step 6.

### What needs fixing?
It's unclear in the docs that --disk-container requires a URL, so file://<path/to>/containers.json is the correct argument.
```
[root@xxx user]# aws ec2 import-snapshot --region us-gov-xxx --description "rhcos-aws.x86_64-4.6.vmdk" --disk-container ./containers-aws-vmdk.json

Error parsing parameter '--disk-container': Expected: '=', received: 'EOF' for input:
./containers-aws-vmdk.json
                          ^

[root@03876210cbc5 user]# aws ec2 import-snapshot --region us-gov-west-1 --description "rhcos-aws.x86_64-4.6.vmdk" --disk-container file://containers-aws-vmdk.json
{
    "Description": "rhcos-aws.x86_64-4.6.vmdk",
...
```

Reference: https://github.com/aws/aws-cli/issues/3878#issuecomment-457079963

**Comment by matt314** [comment]
AWS cli installed from pip:
[root@xxx user]# aws --version
aws-cli/1.19.50 Python/3.6.8 Linux/4.18.0-240.1.1.el8_3.x86_64 botocore/1.20.50

**Comment by codyhoag** [comment]
@matt314 thanks for this suggestion. The update has been merged.
