### ISSUE TITLE
[enterprise-4.7] Issue in file installing/installing_aws/installing-aws-account.adoc

### ISSUE THREAD

**Issue by dlystra** [openshift/openshift-docs#31527]
### Which section(s) is the issue in?
Required AWS permissions

### What needs fixing?
ec2:DescribeInstanceTypes is missing from the list of required permissions for installation

**Comment by codyhoag** [comment]
@staebler can you confirm? We just recently added `ec2:DescribeInstanceTypeOfferings` as an optional permission for instance and quota checks (bottom list [here](https://docs.openshift.com/container-platform/4.7/installing/installing_aws/installing-aws-account.html#installation-aws-permissions_installing-aws-account)). Not sure if this is any way related.

**Comment by dlystra** [comment]
I had the customer add ec2:DescribeInstanceTypeOfferings, but I still received the same error. The install proceeded properly after adding ec2:DescribeInstanceTypes.

**Comment by staebler** [comment]
Yes, the `ec2:DescribeInstanceTypes` permission is needed when the user specifies an instance type in a machine pool, rather than using the default.

**Comment by codyhoag** [comment]
@staebler do you recommend we include this into the hard requirements listed for [Required EC2 permissions for installation](https://docs.openshift.com/container-platform/4.7/installing/installing_aws/installing-aws-account.html#installation-aws-permissions_installing-aws-account)? Or is this more of a corner case warning?

**Comment by staebler** [comment]
I am loathe to have it as a hard requirement, but I don't think it is a corner case. I expect that it is common enough to have as a hard requirement. It is also used for quota checking, which is always attempting although not required.

**Comment by codyhoag** [comment]
This has been merged. @dlystra thanks for reporting this!
