### ISSUE TITLE
[enterprise-4.7] Issue in file installing/installing_aws/installing-aws-account.adoc

### ISSUE THREAD

**Issue by gtinsley** [openshift/openshift-docs#31545]
### Which section(s) is the issue in?
Required AWS permissions

### What needs fixing?
The Required IAM permissions for installation is missing 

iam:CreateServiceLinkedRole

**Comment by codyhoag** [comment]
@staebler here's another AWS permissions change request. Can you confirm?

**Comment by staebler** [comment]
What is requiring that permission? Where are we seeing a failure when that permission has not been granted? I am not aware of anything that requires that permission, but there may have been a change to some in-cluster operator.

**Comment by dlystra** [comment]
This is the error received when running the install in log-level debug:

```ERROR Error: Error creating network Load Balancer: AccessDenied: User: arn:aws:iam::454876819616:user/ocp-install-service-user is not authorized to perform: iam:CreateServiceLinkedRole on resource: arn:aws:iam::454876819616:role/aws-service-role/elasticloadbalancing.amazonaws.com/AWSServiceRoleForElasticLoadBalancing ```

**Comment by staebler** [comment]
> This is the error received when running the install in log-level debug:
> 
> `ERROR Error: Error creating network Load Balancer: AccessDenied: User: arn:aws:iam::454876819616:user/ocp-install-service-user is not authorized to perform: iam:CreateServiceLinkedRole on resource: arn:aws:iam::454876819616:role/aws-service-role/elasticloadbalancing.amazonaws.com/AWSServiceRoleForElasticLoadBalancing `

@dlystra Would you mind providing a bit more of the .openshift_install.log surrounding this error so that I can get a better feel for what is happening?

**Comment by dlystra** [comment]
I'd be happy to.

```DEBUG module.masters.aws_instance.master[1]: Creation complete after 21s [id=i-073b4e80fea4a68a2] 
DEBUG module.masters.aws_instance.master[0]: Creation complete after 22s [id=i-0d8d6b43a6ac2f87c] 
DEBUG module.masters.aws_instance.master[2]: Still creating... [30s elapsed] 
DEBUG module.masters.aws_instance.master[2]: Creation complete after 32s [id=i-0a9888f7aaece15f9] 
DEBUG module.masters.aws_lb_target_group_attachment.master[3]: Creating... 
DEBUG module.masters.aws_lb_target_group_attachment.master[2]: Creating... 
DEBUG module.masters.aws_lb_target_group_attachment.master[5]: Creating... 
DEBUG module.masters.aws_lb_target_group_attachment.master[0]: Creating... 
DEBUG module.masters.aws_lb_target_group_attachment.master[1]: Creating... 
DEBUG module.masters.aws_lb_target_group_attachment.master[4]: Creating... 
DEBUG module.masters.aws_lb_target_group_attachment.master[4]: Creation complete after 0s [id=arn:aws:elasticloadbalancing:us-east-1:454876819616:targetgroup/dev-nsw9s-aint/09992de5b6d78a71-20210414161044339200000007] 
DEBUG module.masters.aws_lb_target_group_attachment.master[3]: Creation complete after 0s [id=arn:aws:elasticloadbalancing:us-east-1:454876819616:targetgroup/dev-nsw9s-sint/cccedbec2332f63f-20210414161044351900000008] 
DEBUG module.masters.aws_lb_target_group_attachment.master[0]: Creation complete after 0s [id=arn:aws:elasticloadbalancing:us-east-1:454876819616:targetgroup/dev-nsw9s-aint/09992de5b6d78a71-20210414161044403900000009] 
DEBUG module.masters.aws_lb_target_group_attachment.master[5]: Creation complete after 0s [id=arn:aws:elasticloadbalancing:us-east-1:454876819616:targetgroup/dev-nsw9s-sint/cccedbec2332f63f-2021041416104443230000000a] 
DEBUG module.masters.aws_lb_target_group_attachment.master[2]: Creation complete after 0s [id=arn:aws:elasticloadbalancing:us-east-1:454876819616:targetgroup/dev-nsw9s-aint/09992de5b6d78a71-2021041416104443640000000b] 
DEBUG module.masters.aws_lb_target_group_attachment.master[1]: Creation complete after 1s [id=arn:aws:elasticloadbalancing:us-east-1:454876819616:targetgroup/dev-nsw9s-sint/cccedbec2332f63f-2021041416104450790000000c] 
ERROR                                              
ERROR Error: Error creating network Load Balancer: AccessDenied: User: arn:aws:iam::454876819616:user/ocp-install-service-user is not authorized to perform: iam:CreateServiceLinkedRole on resource: arn:aws:iam::454876819616:role/aws-service-role/elasticloadbalancing.amazonaws.com/AWSServiceRoleForElasticLoadBalancing 
ERROR 	status code: 403, request id: c6ad9928-34b5-48e3-b165-b6f43e75262c 
ERROR                                              
ERROR   on ../../tmp/openshift-install-183966031/vpc/master-elb.tf line 1, in resource "aws_lb" "api_internal": 
ERROR    1: resource "aws_lb" "api_internal" {     
ERROR                                              
ERROR                                              
FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply Terraform: failed to complete the change ```

**Comment by staebler** [comment]
Interesting. Thank you. I will need to do some research into this to figure out why the loadbalancer needs it own service role.

**Comment by staebler** [comment]
From https://docs.aws.amazon.com/elasticloadbalancing/latest/userguide/elb-service-linked-roles.html, it looks like this is only needed if the `AWSServiceRoleForElasticLoadBalancing` role has not already been created for the account. AWS creates that role on your behalf when creating ELBs.

**Comment by staebler** [comment]
I am hesitant to call out this permission as required when doing an install. In most cases, this is probably not required. Is there a way that we can say that the permission **may** be needed if an ELB has never been created in the account?

**Comment by codyhoag** [comment]
We could create a note under the `Required EC2 permissions for installation` list warning of this requirement. I'm hesitant to add a lot of corner cases to the docs because it muddies the hard requirements, but right now, there aren't many corner cases we point out currently. So it should be fine.

**Comment by codyhoag** [comment]
This has been merged. @dlystra thanks for reporting this!
