### ISSUE TITLE
capacity planning information presented differently for logging and metrics

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-docs#3159]
Aggregating logging has an entire dedicated section/page for its sizing guidelines:
https://docs.openshift.com/container-platform/3.3/install_config/aggregate_logging_sizing.html

Cluster metrics has a subsection in the configuration/installation section:
https://docs.openshift.com/container-platform/3.3/install_config/cluster_metrics.html#capacity-planning-for-openshift-metrics

I don't particularly care which method is used, but right now the fact that they are different is confusing to the reader.

**Comment by ahardin-rh** [comment]
In a later release, we created the [Scaling and Performance Guide](https://docs.openshift.com/container-platform/3.6/scaling_performance/index.html) to centralize this information. Closing this, but feel free to reopen if necessary. Thanks!
