### ISSUE TITLE
[enterprise-4.6] | [enterprise-4.7] Issue in file networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-aws-network-load-balancer.adoc

### ISSUE THREAD

**Issue by klaphi** [openshift/openshift-docs#31618]
### Which section(s) is the issue in?
Configuring an Ingress Controller Network Load Balancer on an existing AWS cluster

### What needs fixing?
Please add an additional hint for using the tag "kubernetes.io/role/internal-elb" on internal subnets. 

In our case all networks was tagged with kubernetes.io/cluster/<<cluster-id>> = shared" which created a NLB with public and private subnets. If you want to deploy an internal NLB without having issues, please check upfront for those two tags on private subnets and everything works fine.

**Comment by jboxman** [comment]
fyi @bmcelvee
