### ISSUE TITLE
[online] Issue in file rosa_getting_started/rosa-required-aws-service-quotas.adoc

### ISSUE THREAD

**Issue by brizrobbo** [openshift/openshift-docs#31634]
### Which section(s) is the issue in?

https://docs.openshift.com/rosa/rosa_getting_started/rosa-required-aws-service-quotas.html#rosa-required-aws-service-quotas_rosa-required-aws-service-quotas

### What needs fixing?

Typo: ...documentation on requesting a quota inscrease. <== on the word 'inscrease'

**Comment by bergerhoffer** [comment]
This typo was fixed via #32852. Closing!
