### ISSUE TITLE
[enterprise-4.6] Issue in file builds/creating-build-inputs.adoc

### ISSUE THREAD

**Issue by hugomelendez** [openshift/openshift-docs#31630]
### Which section(s) is the issue in?
Creating a basic authentication secret with a CA certificate

### What needs fixing?
It says:
$ oc create secret generic <secret_name> \
    --from-literal=username=<user_name> \
    --from-literal=password=<password> \
    --from-file=ca-cert=</path/to/file> \
    --type=kubernetes.io/basic-auth

And should say:
$ oc create secret generic <secret_name> \
    --from-literal=username=<user_name> \
    --from-literal=password=<password> \
    --from-file=ca.crt=</path/to/file> \
    --type=kubernetes.io/basic-auth

the key that works is "ca.crt" not "ca-cert"

**Comment by kartikaysharma27** [comment]
@vikram-redhat can you assign this to me. Thank you.

**Comment by kartikaysharma27** [comment]
Hello @hugomelendez thanks for reporting. I will take a look at the suggested changes. Let me know if you have any questions.

**Comment by jboxman** [comment]
Any news on this?

**Comment by kartikaysharma27** [comment]
Hey @jboxman is it possible for you to take this one? Thanks in advance.
