### ISSUE TITLE
[enterprise-4.7] Issue in file cicd/gitops/configuring-sso-for-argo-cd-on-openshift.adoc

### ISSUE THREAD

**Issue by gnunn1** [openshift/openshift-docs#31646]
### Which section(s) is the issue in?

Configuring Argo CD OIDC

### What needs fixing?

There's no existing secret called `openshift-gitops-secret` so one needs to be created but the docs show an edit command instead of apply.

Second the example yaml has the word `yaml` in it which means you cannot copy/paste it as a template without removing it.

**Comment by gnunn1** [comment]
Actually the issue in the docs is that the secret is called `argocd-secret` and not `openshift-gitops-secret`

**Comment by bergerhoffer** [comment]
Fixed via #35366. Updates will be live shortly
