### ISSUE TITLE
[online] Issue in file rosa_policy/rosa-service-definition.adoc

### ISSUE THREAD

**Issue by tnk4on** [openshift/openshift-docs#31699]
### Which section(s) is the issue in?
ROSA service definition | Policies and service definition | Red Hat OpenShift Service on AWS
https://docs.openshift.com/rosa/rosa_policy/rosa-service-definition.html#rosa-sdpolicy-upgrades_rosa-service-definition

### What needs fixing?
OpenShift Dedicated is wrong and needs to be fixed in ROSA.
-> "See the OpenShift Dedicated Life Cycle for more information on the upgrade policy and procedures."

Word: OpenShift Dedicated
-> Red Hat OpenShift Service on AWS

Link: https://access.redhat.com/support/policy/updates/openshift/dedicated
-> https://docs.openshift.com/rosa/rosa_policy/rosa-life-cycle.html

**Comment by jonquilwilliams** [comment]
This was fixed at some point under another PR. Closing this one.
