### ISSUE TITLE
[online] Issue in file upgrading/rosa-upgrading.adoc

### ISSUE THREAD

**Issue by tnk4on** [openshift/openshift-docs#31786]
### Which section(s) is the issue in?

Upgrading ROSA | Upgrading | Red Hat OpenShift Service on AWS
~~https://docs.openshift.com/rosa/rosa_upgrading/rosa-upgrading.html~~
https://docs.openshift.com/rosa/upgrading/rosa-upgrading.html

### What needs fixing?

It is wrong that the link to the lifecycle policy is in the OSD.
"To plan an upgrade, review the lifecycle policies. "

Link: https://access.redhat.com/support/policy/updates/openshift/dedicated
-> https://docs.openshift.com/rosa/rosa_policy/rosa-life-cycle.html

**Comment by tnk4on** [comment]
The link has not been fixed yet. Please check.

**Comment by tnk4on** [comment]
"lifecycle policies" is still linked to OSD.

**Comment by jboxman** [comment]
@jonquilwilliams FYI

**Comment by tnk4on** [comment]
It was updated to the correct link. Close this issue.
