### ISSUE TITLE
[enterprise-4.7] Issue in file installing/installing_vsphere/installing-vsphere-installer-provisioned.adoc

### ISSUE THREAD

**Issue by akesterton** [openshift/openshift-docs#31852]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.7/installing/installing_vsphere/installing-vsphere-installer-provisioned.html
section entitled Cluster Resources

### What needs fixing?
States the installation will install 3 compute machines.  I believe this should read 2 (two) compute machines.

**Comment by codyhoag** [comment]
@patrickdillon can you confirm a standard cluster installation creates three compute machines as described in the official docs [here](https://docs.openshift.com/container-platform/4.7/installing/installing_vsphere/installing-vsphere-installer-provisioned.html#installation-vsphere-installer-infra-requirements_installing-vsphere-installer-provisioned)?

It appears this is accurate based off of this upstream doc: https://github.com/openshift/installer/blob/master/docs/user/vsphere/requirements.md

**Comment by patrickdillon** [comment]
> @patrickdillon can you confirm a standard cluster installation creates three compute machines as described in the official docs [here](https://docs.openshift.com/container-platform/4.7/installing/installing_vsphere/installing-vsphere-installer-provisioned.html#installation-vsphere-installer-infra-requirements_installing-vsphere-installer-provisioned)?
> 
> It appears this is accurate based off of this upstream doc: https://github.com/openshift/installer/blob/master/docs/user/vsphere/requirements.md

Default compute count is 3 for vSphere and all other clusters (except libvirt). See:
https://github.com/openshift/installer/blob/6d778f911e79afad8ba2ff4301eda5b5cf4d8e9e/pkg/types/defaults/machinepools.go#L10
