### ISSUE TITLE
[enterprise-4.7] Issue in file backup_and_restore/replacing-unhealthy-etcd-member.adoc

### ISSUE THREAD

**Issue by dlbewley** [openshift/openshift-docs#31928]
### Which section(s) is the issue in?

* Determining the state of the unhealthy etcd member
  * Determine if the machine is not running:

### What needs fixing?

Statement:  _This output lists the node and the status of the node’s machine. If the status is anything other than running, then the machine is not running._

Contradiction from vSphere cluster:

```bash
oc get machines -A -o jsonpath='{range .items[*]}{@.status.nodeRef.name}{"\t"}{@.status.providerStatus.instanceState}{"\n"}' | grep -v running
vipi-hpgrz-master-0     poweredOn
vipi-hpgrz-master-1     poweredOn
vipi-hpgrz-master-2     poweredOn
vipi-hpgrz-worker-2s4ck poweredOn
vipi-hpgrz-worker-5zpx6 poweredOn
vipi-hpgrz-worker-97n9f poweredOn
vipi-hpgrz-worker-dqrbk poweredOn
vipi-hpgrz-worker-gngtz poweredOn
vipi-hpgrz-worker-vpc29 poweredOn
```

**Comment by bergerhoffer** [comment]
@hmaclean73 Another one to consider. Apparently the status can be something other than `running` exactly.

**Comment by bergerhoffer** [comment]
FYI @tmalove of this issue if you want to look into it!
