### ISSUE TITLE
[enterprise-4.7] Issue in file migration/migrating_3_4/planning-migration-3-to-4.adoc

### ISSUE THREAD

**Issue by DArachchi** [openshift/openshift-docs#32015]
### Which section(s) is the issue in?
Migration considerations -> Networking considerations -> Encrypting traffic between hosts

### What needs fixing?

Docs state `OpenShift Container Platform 4.7 does not support IPsec.` but release notes state OCP 4.7 DOES support IPsec.

**Comment by jboxman** [comment]
@apinnick fyi

**Comment by apinnick** [comment]
Resolved: https://github.com/openshift/openshift-docs/pull/32102
