### ISSUE TITLE
[enterprise-4.7] Issue in file backup_and_restore/backing-up-etcd.adoc

### ISSUE THREAD

**Issue by hupiper** [openshift/openshift-docs#32085]
### Which section(s) is the issue in?
The last note on the page

### What needs fixing?
Keep in mind that etcd encryption only encrypts values, not keys. This means that resource types, namespaces, and object names are unencrypted - this blurb should probably be on the etcd encryption page too (https://docs.openshift.com/container-platform/4.7/security/encrypting-etcd.html).

**Comment by bergerhoffer** [comment]
@hmaclean73 something to consider

**Comment by hmaclean73** [comment]
Thanks @bergerhoffer. Will take a look at this.

**Comment by hmaclean73** [comment]
Resolved with https://github.com/openshift/openshift-docs/pull/35025
