### ISSUE TITLE
[enterprise-4.7] Issue in file authentication/identity_providers/configuring-ldap-identity-provider.adoc

### ISSUE THREAD

**Issue by TheRealJon** [openshift/openshift-docs#32137]
### Which section(s) is the issue in?
Sample LDAP CR -> Information note
![screenshot-docs openshift com-2021 05 03-13_05_55](https://user-images.githubusercontent.com/22625502/116908003-62aea900-ac10-11eb-9352-c3b7ab74280e.png)

### What needs fixing?
"whitelist" should be replaced with alternative term.

**Comment by bergerhoffer** [comment]
@vikram-redhat did we have a plan for doing a sweep for whitelist/blacklist in the repo?

**Comment by jboxman** [comment]
@bergerhoffer, would this in some cases be dependent upon what the variable or field is in the particular feature being documented as well? The control plane was easy enough, because that term only covers how to identify that set of machines.

**Comment by mburke5678** [comment]
@vikram-redhat did we have a plan for doing a sweep for whitelist/blacklist in the repo?

**Comment by bergerhoffer** [comment]
@mbearer @sjstout @TanyaShearonRH Do you know if we ever planned on doing an update to the doc set to remove "whitelist" and "blacklist"?

I don't think it would be as extensive of an effort as it was to do the master -> control plane sweep.

**Comment by apinnick** [comment]
@bergerhoffer I just did an inclusive language assessment of all the RHV docs. The whitelist/blacklist update was much easier than master/slave, primarily because master/slave is so prevalent in networking and storage domains. 

With the exception of the 'blacklist' command for the kernel settings, I found that blacklist could be replaced by blocked or disabled, while whitelist could be replaced by allowed or enabled.

**Comment by bergerhoffer** [comment]
Thanks @apinnick! Yeah I think I had actually started working on an update to try to remove as many instances of whitelist and blacklist from our doc set as possible, but I think I was told to hold off on it until we had a better plan on moving forward with the updates. But then when it came time, we only ever took care of master and must not have followed through with the rest.

A quick search against main, there are only 76 instances of whitelist and 35 instances of blacklist. I'm sure some of these will be flags or parameters we can't change, but should be a pretty easy update to fix what we can.

**Comment by bergerhoffer** [comment]
@kalexand-rh As far as I'm aware, we've never done the whitelist/blacklist sweep in our repo. Is this something we should open a jira for (if we don't have one already) and prioritize?

**Comment by kalexand-rh** [comment]
@bergerhoffer, this does not appear to have been done. Will you make an OCPBUGS Jira for it?

**Comment by bergerhoffer** [comment]
@kalexand-rh Done: https://issues.redhat.com/browse/OCPBUGS-590

**Comment by bergerhoffer** [comment]
Closing this since the effort is being tracked via https://issues.redhat.com/browse/OCPBUGS-590.
