### ISSUE TITLE
[enterprise-4.7] Issue in file networking/routes/route-configuration.adoc

### ISSUE THREAD

**Issue by g8sman** [openshift/openshift-docs#32143]
### Which section(s) is the issue in?

Documentation / OpenShift Container Platform 4.7 / Networking / Configuring Routes / Route configuration / Route-specific annotations

https://docs.openshift.com/container-platform/4.7/networking/routes/route-configuration.html#nw-route-specific-annotations_route-configuration

### What needs fixing?

The annotation "haproxy.router.openshift.io/cookie-same-site" does not look to be the one that is in the haproxy-config.template. It looks like the annotation should be "router.openshift.io/cookie-same-site". This can be found at https://github.com/openshift/router/blob/1df7535e452e0b4d8e3eca6457d3fdebafe8361c/images/router/haproxy/conf/haproxy-config.template#L597 as well as in a running router container.

```
kubectl -n openshift-ingress exec -it router-default-755478778b-54l2f -- cat haproxy-config.template | grep samesite
      {{- with $samesite := firstMatch "Lax|Strict|None" (index $cfg.Annotations "router.openshift.io/cookie-same-site") "None" }}
        {{- ""}} secure attr SameSite={{ $samesite }}
```

**Comment by jboxman** [comment]
cc @bmcelvee
