### ISSUE TITLE
[enterprise-4.6] Issue in file nodes/scheduling/nodes-scheduler-default.adoc

### ISSUE THREAD

**Issue by yrro** [openshift/openshift-docs#32174]
### Which section(s) is the issue in?

Default predicates

### What needs fixing?

The docs for `MaxCSIVolumeCountPred` are missing.

**Comment by mburke5678** [comment]
Sam --

Nice catch. Thank you. I grabbed the definition from the Kubernetes docs.

Can you take a quick look?
https://github.com/openshift/openshift-docs/pull/32714/files

**Comment by yrro** [comment]
LGTM - thanks!
