### ISSUE TITLE
[enterprise-4.6] Issue in file installing/installing_vsphere/installing-vsphere-installer-provisioned-network-customizations.adoc

### ISSUE THREAD

**Issue by gojeaqui** [openshift/openshift-docs#32182]
### Which section(s) is the issue in?
Required vCenter account privileges

### What needs fixing?
There needs to be more clear steps on how to assign the privileges, something like this guide:  https://github.com/openshift/installer/blob/master/docs/user/vsphere/privileges.md

Where the roles are separated into different vCenter levels because the customer does not want to assign all the privileges to the entire vCenter.

**Comment by codyhoag** [comment]
This issue is being tracked under [OSDOCS-1921](https://issues.redhat.com/browse/OSDOCS-1921), which is part of an improvement effort to more distinctly document the vSphere permissions required for OCP.

**Comment by codyhoag** [comment]
This issue was resolved in #33102
