### ISSUE TITLE
[enterprise-3.11] Issue in file release_notes/ocp_3_11_release_notes.adoc

### ISSUE THREAD

**Issue by jmtejal** [openshift/openshift-docs#32200]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/3.11/release_notes/ocp_3_11_release_notes.html#ocp-3-11-420
RHBA-2021:1147 - OpenShift Container Platform 3.11.420 bug fix update
Issued: 2021-03-21 --> Should this be Issued:2021-04-21 ?

### What needs fixing?

Should this be:

Issued:2021-04-21
Updated:2021-04-21

**Comment by jboxman** [comment]
@jeana-redhat FYI

**Comment by jeana-redhat** [comment]
Thanks, Jason!
@stevsmit can you update this one?

**Comment by vikram-redhat** [comment]
@stevsmit Bump
