### ISSUE TITLE
[enterprise-4.7] Issue in file web_console/web-console.adoc

### ISSUE THREAD

**Issue by ElliottBignell** [openshift/openshift-docs#32218]
### Which section(s) is the issue in?

"Accessing the web console"

### What needs fixing?

How about saying what command produced that output? I've been trying for nearly half a day just to get into the web console so I can get started and there's NOWHERE that the information is available. The course I'm following shows the use of links that apparently no longer exist, and now you show the output of a command but DON'T SAY WHAT THE COMMAND IS. Are you TRYING to piss people off?

Rant over.

**Comment by ahardin-rh** [comment]
@ElliottBignell Thanks for your feedback! I opened https://github.com/openshift/openshift-docs/pull/32775 to address this issue. Please take a look. Thanks!

**Comment by ahardin-rh** [comment]
https://github.com/openshift/openshift-docs/pull/32775 is now merged, so I am closing this issue. Please let me know if I can help with further updates.
