### ISSUE TITLE
[enterprise-4.6] Issue in file installing/installing_bare_metal/installing-bare-metal.adoc

### ISSUE THREAD

**Issue by nbalacha** [openshift/openshift-docs#32254]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.6/installing/installing_bare_metal/installing-bare-metal.html#minimum-resource-requirements_installing-bare-metal

### What needs fixing?
The table entry for compute is incorrect.

The vCPU column contains OS info, the RAM contains the value for CPU and the storage actually contains the value for RAM

![Screenshot from 2021-05-06 14-35-50](https://user-images.githubusercontent.com/12027441/117272019-63e20f00-ae78-11eb-9f10-02845f364175.png)

**Comment by codyhoag** [comment]
@nbalacha thanks for reporting this! I have sent a PR to fix this: #32264

**Comment by codyhoag** [comment]
The fix is now live: https://docs.openshift.com/container-platform/4.6/installing/installing_bare_metal/installing-bare-metal.html#minimum-resource-requirements_installing-bare-metal
