### ISSUE TITLE
[enterprise-4.6] Issue in file openshift_images/image-streams-manage.adoc

### ISSUE THREAD

**Issue by pjwebster** [openshift/openshift-docs#32253]
### Which section(s) is the issue in?
Configuring periodic importing of image stream tags

https://docs.openshift.com/container-platform/4.6/openshift_images/image-streams-manage.html#images-imagestream-import_image-streams-managing

### What needs fixing?
Typo in the following paragraph. Replace "release_notes" with "reverts" or something similar:

```
Remove the periodic check, re-run above command but omit the --scheduled flag. This release_notes its behavior to default.
```

**Comment by bergerhoffer** [comment]
Marking this as a good candidate for Hacktoberfest. Looking at the history for the file, it looks like "resets" would be the best term to use.

PR to fix this should be submitted against the `main` branch, and ping me with any questions!

**Comment by bergerhoffer** [comment]
Closing as this has been fixed!
