### ISSUE TITLE
[enterprise-4.7] Issue in file networking/network_policy/about-network-policy.adoc

### ISSUE THREAD

**Issue by rinormaloku** [openshift/openshift-docs#32434]
### Which section(s) is the issue in?
This line:

> Egress network policy as specified by the egress field is not supported.

### What needs fixing?
The reason. Why isn't it supported? Is it a work in progress?  How long do I have to wait for this to be supported? Or it ain't going to be supported?

**Comment by rinormaloku** [comment]
Hi @jboxman ,

Thanks for the information. Would it be useful to have it phrased in some way within the doc?

**Comment by rinormaloku** [comment]
In that case, the ticket can be closed from my POV.

Thanks!

**Comment by jboxman** [comment]
@rinormaloku thanks!
