### ISSUE TITLE
[enterprise-4.7] Issue in file cli_reference/developer_cli_odo/creating_and_deploying_applications_with_odo/using-devfiles-in-odo.adoc

### ISSUE THREAD

**Issue by Keyvan-rh** [openshift/openshift-docs#32439]
### Which section(s) is the issue in?
Deploying a Java application using a devfile
Step 2.

### What needs fixing?
There is no java-spring-boot component
       odo create java-spring-boot myspring --starter
Should be as follow(no dash between spring and boot):
       odo create java-springboot myspring --starter

**Comment by Preeticp** [comment]
This issue is being fixed by @boczkowska as part of this PR: https://github.com/openshift/openshift-docs/pull/32602

**Comment by Keyvan-rh** [comment]
This issue has been fixed #32602 and confirmed
