### ISSUE TITLE
Section Granting Users Daemonset Permissions doesn't work

### ISSUE THREAD

**Issue by nak3** [openshift/openshift-docs#3243]
Section: https://ci.openshift.redhat.com/openshift-docs-master-testing/latest/admin_guide/manage_authorization_policy.html#admin-guide-granting-users-daemonset-permissions

I think there are several issues as below:

#### 1. ClusterRole file has wrong format.

~~~
[root@knakayam-ose33-smaster ~]# cat foo.yaml 
- apiVersion: v1
  kind: ClusterRole
  metadata:
    name: daemonset-admin
  rules:
  - resources:
    - daemonsets
    apiGroups:
    - extensions
    verbs:
    - create
    - get
    - list
    - watch
    - delete
    - update
[root@knakayam-ose33-smaster ~]# oc create -f foo.yaml 
unable to decode "foo.yaml": json: cannot unmarshal array into Go value of type unversioned.TypeMeta
~~~

#### 2. `oadm policy add-role-to-user system:daemonset-admin <user>` is not correct role name

Above `clusterrole` file creates role name `daemonset-admin`, not `system:daemonset-admin`.

**Comment by bfallonf** [comment]
Thanks @nak3 . I've submitted a BZ for this issue. Hopefully it can be fixed soon.

https://bugzilla.redhat.com/show_bug.cgi?id=1396340

I'll close this issue.
