### ISSUE TITLE
[enterprise-4.7] Issue in file networking/routes/route-configuration.adoc

### ISSUE THREAD

**Issue by erzhan46** [openshift/openshift-docs#32547]
### Which section(s) is the issue in?
container-platform/4.7/networking/routes/route-configuration.html#nw-annotating-a-route-with-a-cookie-name_route-configuration

The issue is applicable to both v.4.6 and v.4.7 of the documentation.

Let me know if you'd prefer that I create and submit the PR. 

### What needs fixing?
'Procedure' section provides incorrect steps for setting-up a custom cookie for a route.
Annotation key should be set to router.openshift.io/cookie_name
Any other key, such as router.openshift.io/my_cookie provided as an example won't work.
'Procedures' section needs to be modified to specify that and examples provided there should be updated accordingly.

**Comment by erzhan46** [comment]
Let me know if any supporting information is required.

**Comment by jboxman** [comment]
@erzhan46, how does this look? https://github.com/openshift/openshift-docs/pull/31530

**Comment by erzhan46** [comment]
Yes - it is the same issue.
I prepared the nw-annotating-a-route-with-a-cookie-name.adoc file with proposed fixes - but it seems that it is already done (but not approved yet). The only difference I have is for curl example. Let me know if it's still worth submitting.

. Save the cookie, and access the route:
+
[source,terminal]
----
$ MYROUTE=$(oc get route my_route -o jsonpath='{.spec.host}')

$ curl $MYROUTE -k -o /dev/null -c /tmp/my_cookie

$ cat /tmp/my_cookie
....
#HttpOnly_my_route-...	FALSE	/	FALSE	0	my_cookie	aeb1...f2
...

**Comment by erzhan46** [comment]
Submitted pull request just in case

**Comment by jboxman** [comment]
We've fixed this, thanks!
