### ISSUE TITLE
[enterprise-4.7] Issue in file logging/config/cluster-logging-log-store.adoc

### ISSUE THREAD

**Issue by r2d2rnd** [openshift/openshift-docs#32638]
### Which section(s) is the issue in?
Configuring CPU and memory requests for the log store

### What needs fixing?
Bug 1962122 [1] was opened at the same time. This is happening also for documentation for [enterprise-4.5] (OCP 4.6 is ok)

The example is having different values for limits.memory and request.memory and the values should be the same.

This is the current example:
~~~
      elasticsearch:
        resources: 
          limits:
            memory: 16Gi
          requests:
            cpu: "1"
            memory: "64Gi"
~~~

And it should be like this:
~~~
      elasticsearch:
        resources: 
          limits:
            memory: 16Gi
          requests:
            cpu: "1"
            memory: 16Gi
~~~

or

~~~
      elasticsearch:
        resources: 
          limits:
            memory: 64Gi
          requests:
            cpu: "1"
            memory: 64Gi
~~~

At the same time, not only the value is wrong, the request.memory has the value between " " and the limits.memory not. Then, not consistency in the example. It's ok without " "

[1]  https://bugzilla.redhat.com/show_bug.cgi?id=1962122

**Comment by rolfedh** [comment]
@r2d2rnd please close this issue as a duplicate, then.
