### ISSUE TITLE
[enterprise-4.6] Issue in file modules/nw-ingress-controller-configuration-parameters.adoc

### ISSUE THREAD

**Issue by wcushen** [openshift/openshift-docs#32656]
Document URL:
https://docs.openshift.com/container-platform/4.6/networking/ingress-operator.html

Section Number and Name:
`endpointPublishingStrategy` parameter

Describe the issue:
"Private" as an endpointPublishingStrategy is documented here: https://docs.openshift.com/container-platform/4.6/rest_api/operator_apis/ingresscontroller-operator-openshift-io-v1.html#ingresscontroller-operator-openshift-io-v1 and has been confirmed by Red Hat GES as a supported solution. 

Suggestions for improvement:
Given that it is supported and referenced in the correlated API documentation, should it not be referenced alongside all the other `endpointPublishStrategy`'s in https://docs.openshift.com/container-platform/4.6/networking/ingress-operator.html

**Comment by jboxman** [comment]
cc @bmcelvee
