### ISSUE TITLE
[enterprise-4.7] Issue in file storage/understanding-persistent-storage.adoc

### ISSUE THREAD

**Issue by annelson-rh** [openshift/openshift-docs#32686]
### Which section(s) is the issue in?

Mount options

### What needs fixing?

per https://kubernetes.io/docs/concepts/storage/persistent-volumes/#mount-options
the annotation is deprecated - and preferred method is to update mountOptions attribute

example: 
```
apiVersion: v1
kind: PersistentVolume
spec:
  mountOptions:
  - nfsvers=4.1
...
```

**Comment by bergerhoffer** [comment]
This looks to have been resolved via #36420. Closing!
