### ISSUE TITLE
[enterprise-4.6] Issue in file nodes/containers/nodes-containers-using.adoc

### ISSUE THREAD

**Issue by davidhildenbrand** [openshift/openshift-docs#32694]
### Which section(s) is the issue in?

"where nproc is the number of process reported by the nproc command. "

### What needs fixing?
"process" is wrong, correct  would be "processors"/"CPUs" or rather "processing units" as given by "man nproc".

**Comment by ehvs** [comment]
Hi @davidhildenbrand , nice catch! I'll work on this issue and submit a PR soon

**Comment by codyhoag** [comment]
This has been fixed in #32776. Closing
