### ISSUE TITLE
[enterprise-4.7] Issue in file logging/cluster-logging-deploying.adoc

### ISSUE THREAD

**Issue by rahulait** [openshift/openshift-docs#32713]
### Which section(s) is the issue in?
Section: Installing OpenShift Logging using the web console
Point/step 2. Install the Cluster Logging Operator:

### What needs fixing?
There is no "Cluster Logging" in OperatorHub. Either 2nd step of installing cluster logging operator needs to be fixed or removed.

**Comment by rahulait** [comment]
It is renamed as "Red Hat OpenShift Logging"

**Comment by lbscorpio** [comment]
@rahulait Nice catch, I have raised [PR#32726](https://github.com/openshift/openshift-docs/pull/32726) to fix this issue. Waiting to review now, thanks.

**Comment by rolfedh** [comment]
Thank you both for your work on this, @rahulait @lbscorpio.
