### ISSUE TITLE
[enterprise-4.6] Document `service.beta.kubernetes.io/load-balancer-source-ranges` annotation

### ISSUE THREAD

**Issue by mkimuram** [openshift/openshift-docs#32723]
### Which section(s) is the issue in?
[Route configuration](https://docs.openshift.com/container-platform/4.6/networking/routes/route-configuration.html)

### What needs fixing?
By the change described [here](https://bugzilla.redhat.com/show_bug.cgi?id=1906267), users need to specify allowed IP source ranges by using `service.beta.kubernetes.io/load-balancer-source-ranges` annotation in [4.6.9](https://access.redhat.com/errata/RHSA-2020:5614) or later. However, it is not documented.

Restricting access by source IPs is required in most cases when OCP is deployed in public cloud but should only be accessed by particular people. Therefore, it must be documented clearly. In addition, the behavior that the cluster-ingress-operator overwrites the AWS Security Group is also needed to be documented there, not just in [kbase](https://access.redhat.com/solutions/5158751). Lack of these descriptions will potentially make users misconfigure and more likely to expose clusters to security threats.

**Comment by jboxman** [comment]
cc @bmcelvee
