### ISSUE TITLE
[enterprise-4.7] Issue in file virt/virtual_machines/virt-create-vms.adoc

### ISSUE THREAD

**Issue by thomasphall** [openshift/openshift-docs#32780]
### Which section(s) is the issue in?
In the additional resources section at the bottom.

The VirtualMachineSpec definition in the [KubeVirt v0.36.2 API Reference](https://kubevirt.io/api-reference/v0.36.2/definitions.html#_v1_virtualmachinespec) provides broader context for the parameters and hierarchy of the virtual machine specification.

### What needs fixing?
404 is returned here: https://kubevirt.io/api-reference/v0.36.2/definitions.html#_v1_virtualmachinespec

**Comment by thomasphall** [comment]
Link should be this: http://kubevirt.io/api-reference/v0.36.1/index.html

**Comment by thomasphall** [comment]
https://docs.openshift.com/container-platform/4.7/virt/virtual_machines/virt-create-vms.html#additional-resources and the linked page is incorrect here: 
`The VirtualMachineSpec definition in the KubeVirt v0.36.2 API Reference provides broader context for the parameters and hierarchy of the virtual machine specification.`

**Comment by apinnick** [comment]
@ctomasko I will open a Jira for this fix.
