### ISSUE TITLE
[enterprise-4.7] Issue in file installing/installing_vsphere/installing-restricted-networks-vsphere.adoc

### ISSUE THREAD

**Issue by 2s1dhant** [openshift/openshift-docs#32786]
### Which section(s) is the issue in?
[Sample install-config.yaml file for VMware vSphere
](https://docs.openshift.com/container-platform/4.7/installing/installing_vsphere/installing-restricted-networks-vsphere.html#installation-vsphere-config-yaml_installing-restricted-networks-vsphere)

### What needs fixing?
The sample install-config.yaml has explanations of its fields given below it. They are identified by numbers 1 - 17. 
- There are 1 - 17 numbers in the install-config.yaml template but an explanation for only 16 fields. 
- The `pullSecret` field ie. number 14 from the template has no explanation below. In the explanation section number 14 talks about `sshKey` instead. 
-  There is a discrepancy between the numbers in the template and their explanation below. 

### Additional: 
- I see this in [v4.6](https://docs.openshift.com/container-platform/4.6/installing/installing_vsphere/installing-restricted-networks-vsphere.html#installation-vsphere-config-yaml_installing-restricted-networks-vsphere) docs as well.

**Comment by bergerhoffer** [comment]
Thanks for submitting this! The incorrect numbering and field mismatch was recently fixed via #33551 and the updates are live. Closing this issue.
