### ISSUE TITLE
Types of Persistent Volumes does a wrong redirect

### ISSUE THREAD

**Issue by spolti** [openshift/openshift-docs#3293]
Doc Link: https://docs.openshift.org/latest/architecture/additional_concepts/storage.html

Description:
In this [topic](https://docs.openshift.org/latest/architecture/additional_concepts/storage.html#types-of-persistent-volumes) the HostPath link redirects the user to the kubernetes REST API instead to show how to use/configure the hostPath method.

**Comment by bfallonf** [comment]
@spolti thanks for this.

I'm not too sure what you're asking for, though. Are you asking for a better description on how to use the HostPath method? The Kubernetes API doc does link to the Kubernetes docs, which I'll admit is a longer way to find the HostPath method.

Am I missing something else?

**Comment by gaurav-nelson** [comment]
Closing this, no response from reporter.
