### ISSUE TITLE
[enterprise-4.7] Issue in file operators/user/olm-installing-operators-in-namespace.adoc

### ISSUE THREAD

**Issue by pwright** [openshift/openshift-docs#32952]
### Which section(s) is the issue in?

Installing from OperatorHub using the web console

### What needs fixing?

Step 5 says:

Choose a specific, single namespace in which to install the Operator. 

but afaik, the default is still 'All namespaces', that option isn't accounted for.. 

Later there's a note:

"For the All namespaces…​ installation mode, the status resolves to InstallSucceeded in the openshift-operators namespace, but the status is Copied if you check in other namespaces."

but 'All namespaces' wasn't mentioned earlier

**Comment by jboxman** [comment]
cc @adellape
