### ISSUE TITLE
Example is incorrect for OKD

### ISSUE THREAD

**Issue by mburke5678** [openshift/openshift-docs#32958]
Example references RHCOS, which is incorrect for OKD
`node.openshift.io/os_id: rhcos`

### Which section(s) is the issue in?
https://docs.okd.io/latest/nodes/scheduling/nodes-scheduler-node-selectors.html#nodes-scheduler-node-selectors-about_nodes-scheduler-node-selectors

### What needs fixing?

Change `rhcos` to `fedora`

**Comment by elmiko** [comment]
testing something out
/assign @dmueller2001
