### ISSUE TITLE
The nodeSelector example is error

### ISSUE THREAD

**Issue by aitchjoe** [openshift/openshift-docs#32984]
### Which section(s) is the issue in?

The nodeSelector example in [Moving monitoring components to different nodes](https://github.com/openshift/openshift-docs/blob/945740c5b9001bcf4eebe45c15d4073e7a36b2d3/modules/monitoring-moving-monitoring-components-to-different-nodes.adoc):

```
    prometheusK8s:
      nodeSelector:
        nodename: worker1
        nodename: worker2
```

but by [nodeSelector](https://v1-20.docs.kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector)'s define:

> For the pod to be eligible to run on a node, the node **must have each of** the indicated key-value pairs as labels

so we cannot run prometheusK8s pods on worker1 or worker2 via this config.

### What needs fixing?

Remove this misleading example. 

If we want run pods on node1 or node2, we can do it via [Node affinity](https://v1-20.docs.kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity), but from [PrometheusK8sConfig](https://github.com/openshift/cluster-monitoring-operator/blob/release-4.7/Documentation/user-guides/configuring-cluster-monitoring.md#prometheusk8sconfig), there is no affinity config, we will create issue in that project.

**Comment by jboxman** [comment]
@bergerhoffer, possibly useful for Ofest.

**Comment by bergerhoffer** [comment]
@jboxman the solution isn't obvious to me. Can you share what the fix would be? To remove the whole example?

**Comment by mburke5678** [comment]
@pneedle-rh You changed these examples from one `nodeSelector` to two. Can we simply remove the second (`nodename: worker2`)?

**Comment by pneedle-rh** [comment]
@mburke5678 thanks for your message.

Is this specific to the `prometheusK8s` entry in the config only, or does this apply to the other entries too?

The updates to this section were made as part of my broader testing of each of the procedures when I restructured the whole Monitoring book through https://github.com/openshift/openshift-docs/pull/24722 in October 2020. I discussed each of my changes at the time with the Monitoring and with QE teams.

I can't find any specific reference in my notes or in the comments in https://github.com/openshift/openshift-docs/pull/24722 to the `prometheusK8s` element in this code block. Given this, please discuss the issue with the Monitoring Engineering team for guidance on how to resolve the issue. Thanks!
