### ISSUE TITLE
[enterprise-4.5] Issue in file nodes/containers/nodes-containers-copying-files.adoc

### ISSUE THREAD

**Issue by tripod70** [openshift/openshift-docs#32985]
### Which section(s) is the issue in?

it is part of published example:

WARNING: cannot use rsync: rsync not available in container
status.txt

so you writing that command execution unsuccessful

### What needs fixing?
documentation,
please add correct example with -c option

**Comment by mburke5678** [comment]
@tripod70 Thanks for bringing this up. I actually [changed the docs to add this output](https://github.com/openshift/openshift-docs/pull/14059/files#diff-8137b75546413c094e15268476b89b51152c6bc6f86c677bb2c76e9dad2032e3R44-R47). I'm not sure why. I will look into it on Monday.

**Comment by mburke5678** [comment]
@tripod70 Please take a look at my PR to see if it meets your expectations. Thank you!

https://github.com/openshift/openshift-docs/pull/38276

**Comment by mburke5678** [comment]
PR is merged. Closing
