### ISSUE TITLE
[enterprise-4.6] Issue in file networking/routes/route-configuration.adoc

### ISSUE THREAD

**Issue by andyedwardsibm** [openshift/openshift-docs#32988]
### Which section(s) is the issue in?
"Route-specific annotations"

### What needs fixing?
The table lists `haproxy.router.openshift.io/cookie-same-site` but setting that annotation has no effect on the behaviour of the Route.  From https://bugzilla.redhat.com/show_bug.cgi?id=1867186 the last comment seems to indicate the annotation is `router.openshift.io/cookie-same-site` (without the leading `haproxy.`) and that does seem to work and change the behaviour of the Route.

We've tested this in 4.6 but suspect it's a problem in 4.7 as well.

**Comment by jboxman** [comment]
cc @bmcelvee

**Comment by andyedwardsibm** [comment]
Looks like this is fixed for the [4.6](https://docs.openshift.com/container-platform/4.6/networking/routes/route-configuration.html) docs upwards, so closing
