### ISSUE TITLE
List which storage providers allow which access modes

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-docs#3299]
It would be good to document the range of storage providers we include, and the different types of access mode that they permit in a table:

As of OCP 3.3, FWIW, this is:

aws_ebs: RWO
azure_file: ROM, RWM, RWO
cephfs: ROM, RWM, RWO
cinder: RWO
fc: ROM, RWO
flexvolume: ROM, RWO
gce_pd: ROM, RWO
glusterfs: ROM, RWM, RWO
host_path: RWO
iscsi: ROM, RWO
nfs: ROM, RWM, RWO
rbd: ROM, RWO
vsphere_volume: RWO

It may be that this should be autogenerated by looking at the GetAccessModes() functions under vendor/k8s.io/kubernetes/pkg/volume.

**Comment by bfallonf** [comment]
Thanks @jim-minter . I've created a Bug for this: https://bugzilla.redhat.com/show_bug.cgi?id=1400361

With a BZ created, it'll be easier to track, and hopefully this can be worked on soon. I'll close this issue.

**Comment by bfallonf** [comment]
Correction, there was already a BZ open for this issue, so I've closed mine, and I'll add this issue to the one already existing:

https://bugzilla.redhat.com/show_bug.cgi?id=1399358

**Comment by jim-minter** [comment]
thanks @bfallonf, it didn't occur to me that openshift-docs used bugzilla as well.

**Comment by bfallonf** [comment]
@jim-minter Sure do! We use them for tracking our numbers, etc, but we use these issues and emails to openshift-docs@redhat.com for ways for people to report things. Things usually end up as BZs.
