### ISSUE TITLE
[enterprise-4.7] Issue in file service_mesh/v1x/ossm-observability.adoc

### ISSUE THREAD

**Issue by mmusaji** [openshift/openshift-docs#33023]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.7/service_mesh/v1x/ossm-observability.html#ossm-observability-access-console_observability-v1x

### What needs fixing?

The steps below, step 2 is incorrect.

> For administrators
> 1) Use the perspective switcher to switch to the Administrator perspective.
> 2) Click Home > Overview.
> 3) In the Launcher section, click Open on Kiali.
> 4) ...

Should read
> 2) Click Home > Projects -> bookinfo
> 3) In the Launcher section, click Open on Kiali.

For the developers section below it, it can be made clearer than you need to select the project bookinfo.

**Comment by JStickler** [comment]
Created https://issues.redhat.com/browse/OSSMDOC-349 to track.

**Comment by JStickler** [comment]
Should have been addressed via #39931
