### ISSUE TITLE
Add postgresql clustered sample

### ISSUE THREAD

**Issue by sspeiche** [openshift/openshift-docs#3307]
https://github.com/sclorg/postgresql-container/tree/master/examples/replica

Postgresql is missing but can find:
https://docs.openshift.com/container-platform/3.3/using_images/db_images/mysql.html#using-mysql-replication
https://docs.openshift.com/container-platform/3.3/using_images/db_images/mongodb.html#using-mongodb-replication

**Comment by bfallonf** [comment]
Thanks @sspeiche 

I've created a BZ for this here: https://bugzilla.redhat.com/show_bug.cgi?id=1400741

I'll close this issue and move the tracking there.
