### ISSUE TITLE
[okd] Pipeline information is not quite accurate for 4.7

### ISSUE THREAD

**Issue by elmiko** [openshift/openshift-docs#33080]
### Which section(s) is the issue in?

[CI/CD -> Pipelines -> OpenShift Pipelines Release Notes](https://docs.okd.io/latest/cicd/pipelines/op-release-notes.html)

### What needs fixing?

According to the section,
> Red Hat OpenShift Pipelines General Availability (GA) 1.4 is now available on OKD 4.7.

but this does not appear to be accurate with the current release, see [this email from the OKD working group mailing list](https://groups.google.com/g/okd-wg/c/WOYVj8Sa-3w/m/JGhtWMjzAAAJ)

from the email:
> Finally, following up on the latest docs working group meeting, the OKD docs currently include Openshift Pipelines content (https://docs.okd.io/latest/cicd/pipelines/op-release-notes.html), which includes the statement “Red Hat OpenShift Pipelines General Availability (GA) 1.4 is now available on OKD 4.7”, which I don’t believe is true?  So something needs to be added about how to add the pipelines functionality to OKD, so the rest of the documentation section is valid content for OKD

**Comment by mburke5678** [comment]
@elmiko it appears that OpenShift Pipeline Operator is not available in OKD. Is that the case?

**Comment by elmiko** [comment]
@mburke5678 yes, that is what is being reported by the user. i think the instructions for usage are still valid, but the installation does not appear to work as it does for ocp.

**Comment by mburke5678** [comment]
@elmiko Thank you. I was worried that just the 1.4 version wasn't supported in OKD, but earlier versions were. But I see that you cannot install Pipelines (at least not in the web console). PTAL: https://github.com/openshift/openshift-docs/pull/33117

**Comment by mburke5678** [comment]
PR is merged.
