### ISSUE TITLE
Language versions not up to date in preview developer FAQ.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/openshift-docs#3314]
In:

* https://github.com/openshift/openshift-docs/blob/master/getting_started/devpreview_faq.adoc

the list of supported language versions is not up to date.

At the minimum should also list Python 3.5.

Think Ruby may be out of date as well, as now have Ruby 2.3.

Not sure what else.

**Comment by bfallonf** [comment]
Thanks @GrahamDumpleton !

Updated in #3370 . Just waiting to see if the updated images are correct.

I'll close this issue.
