### ISSUE TITLE
Developer preview restrictions not detailed

### ISSUE THREAD

**Issue by gbraad** [openshift/openshift-docs#3315]
In:
https://github.com/openshift/openshift-docs/blob/master/getting_started/devpreview_faq.adoc
the usage restrictions are not in sync between:

  * WHAT ARE THE RESOURCE LIMITS DURING THE DEVELOPER PREVIEW?
  * Current Usage Considerations

Note: duplication, suggest to consolidate

**Comment by gbraad** [comment]
#3313

**Comment by bfallonf** [comment]
Thanks @gbraad . I can see what you mean, but I think the paragraphs have different intentions. I took in the info from #3313 , and created #3370 . It should be fine.
