### ISSUE TITLE
Dynamic Storage

### ISSUE THREAD

**Issue by christianh814** [openshift/openshift-docs#3320]
A working examples would be useful [here](https://github.com/openshift/openshift-docs/blob/f3f7583bf6e7e2d3b9af72c2d43faa357be6ed97/install_config/persistent_storage/dynamically_provisioning_pvs.adoc)

**Comment by ahardin-rh** [comment]
Thank you. I created this [documentation bug](https://bugzilla.redhat.com/show_bug.cgi?id=1485385) to better track improvements to that section of the docs.

**Comment by adellape** [comment]
Closed the related BZ because it looks like there are a lot of examples in that file now:

https://docs.openshift.com/container-platform/3.11/install_config/persistent_storage/dynamically_provisioning_pvs.html
