### ISSUE TITLE
[OKD] Troubleshooting - Deploying installer-provisioned clusters on bare metal | Installing | OKD 4

### ISSUE THREAD

**Issue by Elbehery** [openshift/openshift-docs#33228]
### Which section(s) is the issue in?

https://docs.okd.io/latest/installing/installing_bare_metal_ipi/ipi-install-troubleshooting.html

### What needs fixing?
3 mentions of `rhcos` needs to be changed to `fedora`

### potential resolution 

- review example
- test with diff versions
- retest with each new release

/assign @mburke5678 
/assign @dmueller2001

**Comment by mburke5678** [comment]
@Elbehery Can you help determine what these strings should be? I cannot verify. 

curl -s -o /dev/null -I -w "%{http_code}\n" http://webserver.example.com:8080/rhcos-44.81.202004250133-0-qemu.x86_64.qcow2.gz?sha256=7d884b46ee54fe87bbc3893bf2aa99af3b2d31f2e19ab5529c60636fbd0f1ce7

bootstrapOSImage: http://<ip:port>/rhcos-43.81.202001142154.0-qemu.x86_64.qcow2.gz?sha256=9d999f55ff1d44f7ed7c106508e5deecd04dc3c06095d34d36bf1cd127837e0c

clusterOSImage: http://<ip:port>/rhcos-43.81.202001142154.0-openstack.x86_64.qcow2.gz?sha256=a1bda656fa0892f7b936fdc6b6a6086bddaed5dafacedcd7a1e811abb78fe3b0
