### ISSUE TITLE
[okd] Installing a cluster on oVirt with user-provisioned infrastructure - Installing on oVirt | Installing | OKD 4

### ISSUE THREAD

**Issue by Elbehery** [openshift/openshift-docs#33229]
### Which section(s) is the issue in?

https://docs.okd.io/latest/installing/installing_rhv/installing-rhv-user-infra.html

### What needs fixing?
deployment with `rhcos` 

change `rhcos` to `fedora` 

### Resolution 

- review example
- test with diff versions
- retest with each new release

/assign @mburke5678
/assign @dmueller2001

**Comment by mburke5678** [comment]
@Elbehery I see that there are 18 instances of `rhcos` in this topic. Which ones need to be changed? Many reference images, I am not aware if similar `fcos` images exist. Many others are related to template files, for ex: `template: rhcos_tpl`. Should there be a `template: fcos_tpl` in the inventory file?
What would `operating_system: "rhcos_x64"` be in a OKD cluster?
