### ISSUE TITLE
[okd] Discussion of Machine Config Daemon should not mention RHCOS and RHEL

### ISSUE THREAD

**Issue by bdlink** [openshift/openshift-docs#33227]
### Which section(s) is the issue in?

https://docs.okd.io/latest/nodes/nodes/nodes-nodes-machine-config-daemon-metrics.html

### What needs fixing?

In table 1 MCO Metrics, mcd_host_os_and_version description mentions RHCOS as example twice, RHEL once

###potential resolution
Replace RHCOS with FCOS (need to check second reference whether version is indeed reported)

delete "or RHEL" from description.
/assign @mburke5678
/assign @dmueller2001

**Comment by mburke5678** [comment]
@bdlink Can you take a look at my PR to see if it meets your expectations? Apologies that I cannot produce a preview for external review.
https://github.com/openshift/openshift-docs/pull/33240

**Comment by mburke5678** [comment]
@vrutkovs PTAL

**Comment by mburke5678** [comment]
Changes are live
