### ISSUE TITLE
[OKD] Deprecated features | What's new? | OKD 4

### ISSUE THREAD

**Issue by Elbehery** [openshift/openshift-docs#33230]
### Which section(s) is the issue in?

https://docs.okd.io/latest/whats_new/deprecated-features.html

### What needs fixing?
 following needs to be replaced 

- Red Hat’s enterprise
- Red Hat Enterprise Linux 
- rhcos

/assign @mburke5678
/assign @dmueller2001

**Comment by mburke5678** [comment]
@Elbehery Please take a look at my PR to see if it meets your expectations: https://github.com/openshift/openshift-docs/pull/33236

**Comment by mburke5678** [comment]
PR is merged
