### ISSUE TITLE
[enterprise-4.8] Issue in file scalability_and_performance/recommended-host-practices.adoc

### ISSUE THREAD

**Issue by mallmen** [openshift/openshift-docs#33287]
### Which section(s) is the issue in?
Creating a KubeletConfig CRD to edit kubelet parameters

### What needs fixing?
Need to include instructions on configuring `tlsSecurityProfile` like there is for ingress at https://docs.openshift.com/container-platform/4.8/networking/ingress-operator.html#nw-ingress-controller-tls-profiles_configuring-ingress

**Comment by mburke5678** [comment]
@mallmen This is a work in progress. We are documenting this new feature for 4.8. We haven't decided where exactly the new information will be added. See: https://github.com/openshift/openshift-docs/pull/31903

**Comment by mallmen** [comment]
Thanks, I will close this since it is covered elsewhere already
