### ISSUE TITLE
Need to document which rollout commands work only with DC

### ISSUE THREAD

**Issue by mfojtik** [openshift/openshift-docs#3336]
The `rollout cancel` will only work for DeploymentConfig, we should document which rollout subcommands works with upstream deployments.

**Comment by mfojtik** [comment]
@kargakis fyi

**Comment by bfallonf** [comment]
@mfojtik I'm not too sure what you mean here.

The `oc rollout` command is only found in the "Basic Deployment Operations" section[1], and nowhere else of note. Are you saying we should document that `rollout cancel` subcommand in this section?

Also, not sure what you mean by "we should document which rollout subcommands works with upstream deployments". What makes a deployment upstream?

[1] https://docs.openshift.com/container-platform/3.3/dev_guide/deployments/basic_deployment_operations.html

**Comment by mfojtik** [comment]
@bfallonf this was more like a placeholder for me (or @kargakis). The `oc rollout cancel` and `oc rollout retry` (which I will be working on today) will only work with deployment configs (not upstream deployment) which deviate from the other `rollout` sub-commands that work with both types.

**Comment by kargakis** [comment]
oc rollout latest also only works with DCs

**Comment by bfallonf** [comment]
@mfojtik @kargakis Has something been submitted for this? There's this PR:

https://github.com/openshift/openshift-docs/pull/3185/files

But it was submitted before this issue. Is more work required here, or has this been sorted? Thanks.
