### ISSUE TITLE
[enterprise-4.6] Issue in file backup_and_restore/backing-up-etcd.adoc

### ISSUE THREAD

**Issue by IronicBadger** [openshift/openshift-docs#33366]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.6/backup_and_restore/backing-up-etcd.html#backing-up-etcd-data_backup-etcd

### What needs fixing?

The documentation references `cluster-backup.sh` as an opaque item with little to no explanation of what it is, where it comes from or an assumed purpose (backing up etcd obviously).

In step 4 it would be useful to have an explanation that this file is provided by the etcd-cluster-operator and is a wrapper around `etcdctl snapshot save`. The OG file is from [here](https://github.com/openshift/cluster-etcd-operator/blob/master/bindata/etcd/cluster-backup.sh).

Also applies to 4.7 and I assume other releases too.

**Comment by bergerhoffer** [comment]
Closing, as #33367 resolves this issue.
