### ISSUE TITLE
Scrolling on iPhone is sticky and frustrating - use native scrolling

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-docs#3338]
Sometime recently docs.openshift.org stopped respecting native iPhone scrolling - acceleration no longer works, returning to the top on click is also broken, and the general usability of the docs site in general dropped precipitously.

We should use native scrolling on devices - anything that gets in the way of that becomes very frustrating.

**Comment by bfallonf** [comment]
@smarterclayton Thanks.

@nhr Another one for you. Thanks to you, also!

**Comment by nhr** [comment]
@luciddreamz any thoughts on this?

**Comment by luciddreamz** [comment]
@nhr We had someone on my team report this as well (back when I fixed the non-responsive tables). I was thinking it was lower priority, but I'll get it on my to-do list for this week. I'm not 100% clear yet why this is an issue only on the docs site.

**Comment by ahardin-rh** [comment]
@luciddreamz @nhr Resurrecting this discussion. :ghost: Is this still an issue, or can this be closed?

**Comment by luciddreamz** [comment]
Still an issue.

Jacob Lucky
jlucky@redhat.com

**Comment by ahardin-rh** [comment]
@luciddreamz Thanks. I created a docs BZ for better tracking: https://bugzilla.redhat.com/show_bug.cgi?id=1454451
