### ISSUE TITLE
ceph secret creation chapter incomplete

### ISSUE THREAD

**Issue by jekader** [openshift/openshift-docs#3344]
The docs chapter is incomplete/incorrect:
https://docs.openshift.org/latest/install_config/persistent_storage/persistent_storage_ceph_rbd.html
https://github.com/openshift/openshift-docs/blob/master/install_config/persistent_storage/persistent_storage_ceph_rbd.adoc#creating-the-ceph-secret

Step 1 says:
Run ceph auth get-key on a Ceph MON node to display the key value for the client.admin user:

however then a template follows instead of "ceph auth-key" output. Moreover, it is not specified that the output of "ceph auth-key" must be passed through base64 again, otherwise authentication will fail.

Also, the chapter does not say what permissions the user must have on Ceph (as it's not good enough for production to share the admin key across projects).

**Comment by bfallonf** [comment]
Thanks @jekader I've created a BZ for this issue: https://bugzilla.redhat.com/show_bug.cgi?id=1484614

Hopefully we can work on this in the next few sprints. Let us know if there's further issues. I'll close this issue.
