### ISSUE TITLE
[enterprise-4.7] Issue in file windows_containers/windows-containers-release-notes-2-x.adoc

### ISSUE THREAD

**Issue by vap0rtranz** [openshift/openshift-docs#33470]
### Which section(s) is the issue in?

"Windows Container Support for Red Hat OpenShift release notes"
https://docs.openshift.com/container-platform/4.7/windows_containers/windows-containers-release-notes-2-x.html

### What needs fixing?

Replace Windows Server versions with those that are supported by Microsoft.  This doc references an EOL version.  "Windows Server Semi-Annual Channel (SAC): Windows Server 1909 with Microsoft patch KB4565351".  Server v1909 is EOL'd.

A Microsoft customer has confirmed that they no longer have access to v1909, and another user has confirmed that Amazon  already removed the AMI for v1909.

**Comment by codyhoag** [comment]
Fixed in #34180
