### ISSUE TITLE
[enterprise-4.7] Issue in file installing/installing_openstack/installing-openstack-installer-restricted.adoc

### ISSUE THREAD

**Issue by lautou** [openshift/openshift-docs#33489]
### Which section(s) is the issue in?

Installing a cluster on OpenStack in a restricted network

### What needs fixing?

There is no page for "Installing a cluster on OpenStack on your own infrastructure in a restricted network" (as it is already done for other iaaS)

**Comment by lautou** [comment]
Hi any update for this ticket?

**Comment by bergerhoffer** [comment]
@maxwelldb Do you happen to know if there are any plans for docs for OpenStack UPI in a restricted env?
