### ISSUE TITLE
Potential Issue in STS docs 

### ISSUE THREAD

**Issue by paulczar** [openshift/openshift-docs#33510]
### Which section(s) is the issue in?

Creating your cluster using STS

### What needs fixing?

Currently STS OIDC endpoints are all in us-east-1 regardless of region settings.  The first time I went through the docs I was using us-east-2, therefore updated the commands to use that which then meant it couldn't deploy.  We should make it clear in the docs that regardless of region being deployed to, not to change the us-east-1 to another region.

**Comment by nermina-redhat** [comment]
@paulczar is this still relevant or we took care of it with the latest doc changes?
