### ISSUE TITLE
Correctness of Links within OpenShift Documetation Shall Be Verified by Continuous Integration

### ISSUE THREAD

**Issue by pospispa** [openshift/openshift-docs#3354]
Continuous Integration that is started for each pull request does not verify if there are no broken links within OpenShift documentation. Such automatic verification will prevent broken links and bugs like [this one](https://bugzilla.redhat.com/show_bug.cgi?id=1399418).

That's why I propose that OpenShift documentation Continuous integration is extended with checks for broken links.

**Comment by a2batic** [comment]
There are many broken links in [index-atomic-registry.html](https://github.com/openshift/openshift-docs/blob/master/index-atomic-registry.html)

**Comment by php-coder** [comment]
`awesome_bot` can do this. If it will be also integrated with Danger then it's possible to have comments like this: https://github.com/dkhamsing/awesome_bot#danger
