### ISSUE TITLE
RFE - Requesting documentation on the OpenShift build process

### ISSUE THREAD

**Issue by maxamillion** [openshift/openshift-docs#336]
The current builder documentation appears to be [here](https://github.com/openshift/origin/blob/master/docs/builds.md) instead of included in the [openshift-docs repo](https://github.com/openshift/openshift-docs) that is then published to users [here](http://docs.openshift.org/latest/welcome/index.html).

Also, I wanted to request some clarification on the builder process documentation [here](https://github.com/openshift/origin/blob/master/docs/builds.md) as it currently sounds as thought the user code ends up in a builder container with access to the docker socket, however I was explained to on irc that this is not the case and instead the OpenShift docker-builder container has access to the docker socket so that it may spawn the container in which the user code is actually run/built in.

**Comment by brenton** [comment]
Just for clarification OSBS is "3rd party" build tooling built on top of OpenShift.  What you are requesting here is still valid though.  You're just asking for more documention on docs.openshift.org related to OpenShift Build internals.

**Comment by maxamillion** [comment]
@brenton - Yes, that. :) ... Sorry, I didn't really know how best to word that. Thank you for the clarification.

**Comment by bfallonf** [comment]
@maxamillion @brenton A PR has been created for this issue: #1067 . Please let me know if there's anything else needed.
