### ISSUE TITLE
[online] Issue in file rosa_getting_started/rosa-required-aws-service-quotas.adoc

### ISSUE THREAD

**Issue by smirman** [openshift/openshift-docs#33600]
### Which section(s) is the issue in?

Required AWS Service Quotas

### What needs fixing?

There is just a typo in the link "requesting a quota inscrease".  That should say "requesting a quota increase"

**Comment by jonquilwilliams** [comment]
Thanks for catching that. It's actually been fixed as part of another update, but is On QA. We hope to get it published soon.

Related JIRA: https://issues.redhat.com/browse/OSDOCS-2228
