### ISSUE TITLE
[enterprise-4.7] Issue in file installing/install_config/installing-customizing.adoc

### ISSUE THREAD

**Issue by pamoedom** [openshift/openshift-docs#33682]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.7/installing/install_config/installing-customizing.html#installation-special-config-encrypt-disk-tang_installing-customizing

### What needs fixing?

Various points, let me elaborate using the same numbering of that section:

5.b) Documentation states the following:

~~~
When the Do you wish to trust these keys? [ynYN] prompt displays, type Y, and the thumbprint is displayed:
~~~ 

But that's confusing because the `thumberprint` parameter that we need to set within the `MachineConfig` is not that one, is the previous small string (key) that is showed in the 5.a section, this one:

~~~
The advertisement contains the following signing keys:

PLjNyRdGw03zlRoGjQYMahSZGu9
~~~

6) The URL within the `tang` section is incorrect, Tang server doesn't use TLS and default port 80 is commonly in use, in fact we recommend to set port 7500 in our Network-bound disk encryption [doc](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/security_hardening/configuring-automated-unlocking-of-encrypted-volumes-using-policy-based-decryption_security-hardening#network-bound-disk-encryption_configuring-automated-unlocking-of-encrypted-volumes-using-policy-based-decryption), therefore, the example for both configs should be something like:

~~~
            tang:
              - url: http://tang.example.com:7500
                thumbprint: PLjNyRdGw03zlRoGjQYMahSZGu9
~~~

7) After creating the MachineConfig for both roles, documentation states to also include the following extra kernel argument:

~~~
  apiVersion: machineconfiguration.openshift.io/v1
  kind: MachineConfig
  metadata:
    name: <node_type>-tang 
  spec:
    config:
      ignition:
        version: 3.2.0
    kernelArguments:
      - rd.neednet=1 
~~~

But this example has various problems, it lacks the file name with the proper numbering, it lacks the `machineconfiguration.openshift.io/role` label, it duplicates the same internal name than previous configs, etc.

___

In summary, I think the points 6 and 7 should be merged as follows for more clarity:

~~~
In the openshift directory, create master and/or worker files to encrypt disks for those nodes, example:

$ cat << EOF > ./99-openshift-worker-tang-encryption.yaml
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: worker-tang
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      luks:
        - name: root
          device: /dev/disk/by-partlabel/root
          clevis:
            tang:
              - url: http://tang.example.com:7500
                thumbprint: PLjNyRdGw03zlRoGjQYMahSZGu9
          options: [--cipher, aes-cbc-essiv:sha256]
          wipeVolume: true
      filesystems:
        - device: /dev/mapper/root
          format: xfs
          wipeFilesystem: true
          label: root
    kernelArguments:
      - rd.neednet=1 
EOF

$ cat << EOF > ./99-openshift-master-tang-encryption.yaml
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: master-tang
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      luks:
        - name: root
          device: /dev/disk/by-partlabel/root
          clevis:
            tang:
              - url: http://tang.example.com:7500
                thumbprint: PLjNyRdGw03zlRoGjQYMahSZGu9
          options: [--cipher, aes-cbc-essiv:sha256]
          wipeVolume: true
      filesystems:
        - device: /dev/mapper/root
          format: xfs
          wipeFilesystem: true
          label: root
    kernelArguments:
      - rd.neednet=1 
EOF
~~~

And include at the bottom some notes about the use of HTTP and the port 7500, properly redirecting again to the Network-bound doc if needed.

Best Regards.

**Comment by pamoedom** [comment]
Hi @pneedle-rh , thanks for taking this issue, in addition to above comments I would like to also add the following:

In section 5.a, there is also a command example with a wrong URL, please note we need to also modify that one as follows in accordance with the same changes:

~~~
$ echo nifty random wordwords \
     | clevis-encrypt-tang \
       '{"url":"http://tang.example.org:7500"}'
~~~

As a side note, I've found also related BZ#1937763 that corroborates that `https` is not a valid protocol for Tang.

Best Regards.

**Comment by pneedle-rh** [comment]
Pull request for 4.8: https://github.com/openshift/openshift-docs/pull/34317

Pull requests for earlier releases to follow.

**Comment by pneedle-rh** [comment]
Pull request for enterprise-4.7: https://github.com/openshift/openshift-docs/pull/34425

**Comment by pneedle-rh** [comment]
Pull request for 4.6: https://github.com/openshift/openshift-docs/pull/34427

**Comment by pamoedom** [comment]
LGTM, thanks.
