### ISSUE TITLE
maven proxy docs should be image specific

### ISSUE THREAD

**Issue by bparees** [openshift/openshift-docs#3368]
This doc:
https://docs.openshift.com/container-platform/3.3/install_config/http_proxies.html#using-maven-behind-a-proxy

is referring to behavior that's specific to the xpaas images, it should be part of the xpaas image documentation, not the general product documentation.

**Comment by bparees** [comment]
@bfallonf looks like you introduced the content.

**Comment by bfallonf** [comment]
@bparees I do remember this... I think it was put in when the xpaas docs were still in the openshift docs. I'll work on this. Thanks!

**Comment by bfallonf** [comment]
PR created to comment this out of the OpenShift docs #3386 

Created a BZ for this for xpaas: https://bugzilla.redhat.com/show_bug.cgi?id=1404538

I'll close this issue.
