### ISSUE TITLE
Reference cloudprovider installer options in "Configuring for GCE" topic

### ISSUE THREAD

**Issue by abutcher** [openshift/openshift-docs#3369]
Setting `openshift_cloudprovider_kind=gce` in the inventory (similar to AWS and Openstack) will automatically configure the gce cloudprovider.

The manual configuration steps should also include setting a GCE `cloud-config` (`/etc/gce/gce.conf` or similar) which includes multi-zone configuration when the environment is spread across multiple zones.

```
[Global]
multizone = true
```

/cc @detiber @themurph @scollier

**Comment by bfallonf** [comment]
Thanks @abutcher .

I've submitted a BZ for this: https://bugzilla.redhat.com/show_bug.cgi?id=1409698

Hopefully it can be worked on in an upcoming sprint. Any notes can be made there, so I'll close this BZ.

**Comment by vikram-redhat** [comment]
@mburke5678 made some changes in the bug. Have set a needinfo for you @abutcher .
