### ISSUE TITLE
[enterprise-4.6] Issue in file service_mesh/v2x/servicemesh-release-notes.adoc

### ISSUE THREAD

**Issue by germanparente** [openshift/openshift-docs#33709]
### Which section(s) is the issue in?

we will need to add explicitly in 4.6 service mesh release notes that service mesh 2.0 is tech preview as we mention in 4.7:

https://docs.openshift.com/container-platform/4.7/service_mesh/v2x/servicemesh-release-notes.html#ovnkubernetes-technology-preview

### What needs fixing?

Please, add the same paragraph than in 4.7 to show explicitly service mesh 2.x is also tech preview in 4.6

**Comment by germanparente** [comment]
It seems this commit has been done for 4.7 and 4.8 already but, no idea why not in 4.6:

https://github.com/openshift/openshift-docs/pull/30068

**Comment by JStickler** [comment]
Closing as WON.T FIX.  As noted in the Service Mesh release notes, this feature was introduced on OCP 4.7.

https://docs.openshift.com/container-platform/4.7/service_mesh/v2x/servicemesh-release-notes.html#ovnkubernetes-technology-preview

**Comment by germanparente** [comment]
@JStickler we have customers complaining about not explicitly mentioning this n 4.6 where OVN is already GA. And also service mesh but clearly not the integration.

**Comment by JStickler** [comment]
@germanparente I do not think this is a documentation bug, I have not been able to confirm with Engineering that the OVN + service mesh integration works on 4.6.

**Comment by germanparente** [comment]
Hi,
ok. Since we know it's not working fine, I wanted to tell the customers that either it's unsupported or tech preview as in 4.7. But say it explicitly because the customers are doing a very bad reasoning:

ovn: GA in 4.6
service mesh 2.X: GA in 4.6

the deduce the integration of both is GA in 4.6 and we should explicitly say that it's not.

**Comment by JStickler** [comment]
When we introduced the integration for OVN it was not supported on OCP4.6.  As of May there were open issues that needed to be backported to 4.6 to get the OVN integration to work. I have not been able to confirm if/when that backport happened to 4.6.  At best it would be tech preview on 4.6, but right now I'm trying to track down why OSSM-282 was reopened.  At this point I think you're better off asking Engineering what the status is than docs, because they'll have the answers we're both looking for.

**Comment by germanparente** [comment]
Hi @JStickler thanks a lot. In 4.7 it's tech preview. We need to add a paragraph here to say either "not supported" or also "tech preview" or something. But I agree that it's to engineering to confirm that. From support point of view, we have issues with customers because this is not explicitly stated.

For instance, one customer is deducing that OVN+SM is GA because  both components are GA in 4.6 which cannot be true.

I will reach engineering and come back to this. But for sure we need a clear statement since both features are already available in 4.6.

**Comment by JStickler** [comment]
@germanparente I don't want to update the docs that this is tech preview if it's actually broken.  But I also don't want to update as not supported if the tech preview has been backported to 4.6.  At any rate, here are the JIRAs to watch:
Engineering - OSSM-282
Docs - OSSMDOC-352

**Comment by germanparente** [comment]
Hi. Thanks again. I agree but it's still unknown to the customers and we need to clarify this explicitly in 4.6 docs. We have currently a big problem because of not having this explicitly stated in service mesh release notes.
