### ISSUE TITLE
[enterprise-4.7] Issue in file release_notes/ocp-4-7-release-notes.adoc

### ISSUE THREAD

**Issue by pbmoses** [openshift/openshift-docs#33734]
### Which section(s) is the issue in?
Networking - routes are not being created when invalid/short names are used in the spec.host field. 

### What needs fixing?
OpenShift 4.7.x will no longer invalid host names to be used in routes (or short DNS names consisting of a single word). Route hosts must conform to DNS 1123 naming conventions. This can result in applications unreachable, as the routes do not get created. 

A bugzilla exists: https://bugzilla.redhat.com/show_bug.cgi?id=1957584
Please considering adding this info to the release notes as routes could easily be identified and corrected with `oc get routes -A`

**Comment by pbmoses** [comment]
PR opened for 4.6 release notes as this is when the issue first became present. https://github.com/openshift/openshift-docs/pull/34606

**Comment by jboxman** [comment]
cc @bmcelvee

**Comment by pbmoses** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1965402 and https://access.redhat.com/errata/RHBA-2021:2502 closing.
