### ISSUE TITLE
[enterprise-4.6] Issue in file security/compliance_operator/compliance-operator-remediation.adoc

### ISSUE THREAD

**Issue by tjungbauer** [openshift/openshift-docs#33738]
### Which section(s) is the issue in?
Filters for failed compliance check results --> typo in command

### What needs fixing?

The 1st command at "List all failing checks that can be remediated automatically:"  has a typo

It says: 
`$ oc get compliancecheckresults -l 'compliance.openshift.io/check-status=FAIL,compliance.openshift.io/automated-remmediation'`

But it should be 
`$ oc get compliancecheckresults -l 'compliance.openshift.io/check-status=FAIL,compliance.openshift.io/automated-remediation'`

(without double 'm' in "remediation")

**Comment by tmalove** [comment]
@vikram-redhat  please assign this issue to me. Thanks!
