### ISSUE TITLE
[enterprise-4.7] Issue in file cicd/gitops/gitops-release-notes.adoc

### ISSUE THREAD

**Issue by gerbigma** [openshift/openshift-docs#33741]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.7/cicd/gitops/gitops-release-notes.html#upgrading-from-red-hat-openshift-gitops-v1-0-1

### What needs fixing?
Shouldn't 3. rather be "create new Instance " ?

**Comment by wtam2018** [comment]
Step 3 and 4 are to restore the data section entirely but change the url (in the data section) as described.   We can make step 3 and 4 into a single step or leave it as is.   
The user doesn't need to create a new instance.   The old default instance is re-created with a new name by controller/reconciler after upgrading to v1.1.
