### ISSUE TITLE
build --loglevel docs out of date

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-docs#3399]
Since PR https://github.com/openshift/origin/issues/9905 the docs are a little out of date at https://docs.openshift.org/latest/dev_guide/builds.html#accessing-build-logs:

"A platform administrator can set verbosity for the entire OpenShift Origin instance by passing the --loglevel option to the openshift start command. If both --loglevel and BUILD_LOGLEVEL are specified, BUILD_LOGLEVEL takes precedence."

The above para should be updated, maybe also mentioning the build defaults (for an admin) and oc start-build --build-loglevel (for an end-user).

@jupierce

**Comment by bfallonf** [comment]
Thanks @jim-minter . I've created a BZ for this: https://bugzilla.redhat.com/show_bug.cgi?id=1405268

I'll close this issue and track it through the BZ.
