### ISSUE TITLE
[enterprise-4.7] Issue in file cli_reference/openshift_cli/developer-cli-commands.adoc

### ISSUE THREAD

**Issue by annelson-rh** [openshift/openshift-docs#34003]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.7/cli_reference/openshift_cli/developer-cli-commands.html#convert

### What needs fixing?
oc convert was removed in 4.7

**Comment by jboxman** [comment]
cc @bergerhoffer - do we have auto-generated CLI docs for 4.7 or is that only for 4.8?

**Comment by bergerhoffer** [comment]
@jboxman The autogen CLI docs are only for 4.8+. Thanks for the heads up, I'll take this issue.

**Comment by soltysh** [comment]
> @soltysh Do you know if there is a replacement oc command to accomplish what `oc convert` did?

No replacement, it's a separate binary which we don't ship by default anymore.

**Comment by soltysh** [comment]
> oc convert was removed in 4.7

`oc convert` was deprecated long before 4.7

**Comment by apinnick** [comment]
@bergerhoffer Thanks. I will look into this.

**Comment by bergerhoffer** [comment]
Thanks @apinnick! Should I keep this issue open in the meantime, or will your Jira be good enough to track that update?

**Comment by apinnick** [comment]
@bergerhoffer You can close this issue. MTC created an epic to find an alternative. My PR for removing the section containing 'oc convert' has been merged. Thanks.

**Comment by bergerhoffer** [comment]
PR to remove from CLI docs has been merged. Closing!
