### ISSUE TITLE
[enterprise-3.11] Issue in file install_config/master_node_configuration.adoc

### ISSUE THREAD

**Issue by AmrGanz** [openshift/openshift-docs#34018]
### Which section(s) is the issue in?

In Document:
https://docs.openshift.com/container-platform/3.11/install_config/master_node_configuration.html#master-node-config-audit-config

The section that starts with the note:

> Because the OpenShift Container Platform master API now runs as static pod, you must define the auditFilePath location in the /var/log/audit/, /var/lib/origin/ or /etc/origin/master/ directory.

There is an example configuration as below:

> Example Audit Configuration
> 
> auditConfig:
>   auditFilePath: "/var/log/origin/audit-ocp.log"
>   enabled: true
>   maximumFileRetentionDays: 14
>   maximumFileSizeMegabytes: 500
>   maximumRetainedFiles: 15

### What needs fixing?

> auditConfig:
>   auditFilePath: "/var/log/origin/audit-ocp.log"   <--- as per the note, the file path should be under [/var/log/audit/, /var/lib/origin/ or /etc/origin/master/]
>   enabled: true
>   maximumFileRetentionDays: 14
>   maximumFileSizeMegabytes: 500
>   maximumRetainedFiles: 15

**Comment by bergerhoffer** [comment]
@mburke5678 it looks like you updated this section per #23948, but updated some to say `/var/log/origin` and other are `/var/lib/origin`. Do you know which one is actually correct?

I see both file paths in more than one place in this document.

**Comment by mburke5678** [comment]
I believe the note should say `var/log/origin`. based on @anpingli comments in the other PR: https://github.com/openshift/openshift-docs/pull/23948#discussion_r468266261

> 
>  Shall we use /var/log/origin/audit-ocp.log instead of /var/lib/origin/audit-ocp.log?
>  we can use any directory. /var/log/origin is a more common directory to store logs.

**Comment by bergerhoffer** [comment]
Closing - PR has been merged. Updates will be live shortly.
