### ISSUE TITLE
[enterprise-4.7] Issue in file operators/operator_sdk/osdk-installing-cli.adoc

### ISSUE THREAD

**Issue by javajon** [openshift/openshift-docs#34020]
### Which section(s) is the issue in?

> ## Installing the Operator SDK CLI

RedHat
https://docs.openshift.com/container-platform/4.7/operators/operator_sdk/osdk-installing-cli.html
https://v0-19-x.sdk.operatorframework.io/docs/install-operator-sdk/#install-from-github-release
https://v1-9-x.sdk.operatorframework.io/docs/installation/
https://docs.okd.io/3.11/operators/osdk-getting-started.html#installing-operator-sdk-cli_osdk-getting-started

Notice on the page https://v0-19-x.sdk.operatorframework.io you have to click on "Latest releases" in the version drop-down to reveal newer releases like 1.9. Instead, one would expect the reverse of a short dropdown list of latest releases with a selection for "Older releases".

IBM
https://ibm.github.io/kubernetes-operators/lab2/

And a proliferation of static articles and books such as
https://learning.oreilly.com/library/view/kubernetes-operators/9781492048039/ch04.html#idm45261334672120

This RedHat article was written just last summer points to an older SDK 0-19 version:
https://developers.redhat.com/blog/2020/08/21/hello-world-tutorial-with-kubernetes-operators#

### What needs fixing?

There are at least three public RedHat provided places titled "Installing the Operator SDK CLI" that detail installation instructions. Each place has the same page/section title yet varies greatly in the version numbers referenced and installation instructions. Each page appears to be the "latest".

I'm surmising the current best place is: https://v1-9-x.sdk.operatorframework.io/docs/installation/

Perhaps there is a reason, but it's conflicting for those trying to get started. Suggestions:

- The documentation should be clearer about the difference on pages or better yet insure all install reference points to a single source of truth.  
- Make the selection for the documentation versions less obscure.
- Add a warning on the pages when the user is reading older version documentation.

**Comment by jboxman** [comment]
cc @adellape
