### ISSUE TITLE
[enterprise-4.6] Issue in file authentication/configmaps.adoc

### ISSUE THREAD

**Issue by apolymen** [openshift/openshift-docs#34037]
### Which section(s) is the issue in?
Whole document/page

### What needs fixing?
This page talks about ConfigMaps which is not related to Authentication. I would suggest moving it under Builds (as it was in 4.3/4.4) or under Applications.

**Comment by jboxman** [comment]
cc @mburke5678

**Comment by mburke5678** [comment]
@bmcelvee You moved the Config Maps docs from Build to Authentication and authorization here: https://github.com/openshift/openshift-docs/pull/27860/files#r536357048 based on a suggestion from @siamaksade . Do you recall the reason for this change?

**Comment by bmcelvee** [comment]
@mburke5678 Hey, yes. It a PM request from Siamak. I apologize, but I don't remember more specifics off the top of my head.

**Comment by mburke5678** [comment]
PR is merged. Closing

**Comment by apolymen** [comment]
Hmm, it seems it has not been backported to 4.7 while 4.6 is ok.

**Comment by bergerhoffer** [comment]
@mburke5678 Looks like the PR for the 4.7 cherry pick didn't get merged automatically. I would hit it, except it looks like there's a conflict now with the topic map. Can you resolve?

https://github.com/openshift/openshift-docs/pull/37999
