### ISSUE TITLE
[enterprise-4.6] Issue in file installing/installing_vsphere/installing-vsphere-installer-provisioned.adoc

### ISSUE THREAD

**Issue by yocum137** [openshift/openshift-docs#34185]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.5/installing/installing_vsphere/installing-vsphere-installer-provisioned.html#installation-vsphere-infrastructure_installing-vsphere-installer-provisioned

### What needs fixing?

The SDRS Warning from the v4.5 docs was not carried into the v4.6 docs.  Specifically, this warning MUST be present:

"A limitation of using VPC is that the Storage Distributed Resource Scheduler (SDRS) is not supported. See vSphere Storage for Kubernetes FAQs in the VMware documentation."

With a link to the VMWare docs, here: https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/faqs.html#is-sdrs-supported-on-vms-hosting-kubernetes-cluster

**Comment by bergerhoffer** [comment]
This warning was removed via #29499. Specifically, see this discussion on it: https://github.com/openshift/openshift-docs/pull/29499/files#r578410587

Per the linked conversation above, I'm closing this issue. But please feel free to reopen this issue if you still feel that this warning needs to be present.
