### ISSUE TITLE
ansible install doesn't document deployment_type

### ISSUE THREAD

**Issue by bparees** [openshift/openshift-docs#3424]
deployment_type is a required value (the install fails without it) and the examples include it, eg:

```
deployment_type=origin
```

but nothing in the docs actually indicates that it's required or what the possible values are.  the key only shows up in the examples, there's no discussion of it:

https://docs.openshift.org/latest/install_config/install/advanced_install.html#install-config-install-advanced-install

**Comment by bfallonf** [comment]
@bparees I made a BZ involving this one:

https://bugzilla.redhat.com/show_bug.cgi?id=1406602

There should probably be a section about the necessary things in an ansible file, not just examples like we currently have.

I'll close this issue and the work can move there. Thanks for this.
