### ISSUE TITLE
not clear that infra node labels are mandatory

### ISSUE THREAD

**Issue by bparees** [openshift/openshift-docs#3425]
When discussing setting labels on cluster nodes, it is not made clear that you must have a at least one node with the infra label, because the registry and router will only run on a node w/ the infra label.

The infra label is discussed, but the dots aren't connected that you must have a node with that label.

https://docs.openshift.org/latest/install_config/install/advanced_install.html#configuring-node-host-labels

**Comment by bfallonf** [comment]
PR #3427  submitted for this.

I'll close this issue and any conversation can be moved there.

Thanks @bparees
