### ISSUE TITLE
Context path is not set in Nexus setup guide

### ISSUE THREAD

**Issue by siamaksade** [openshift/openshift-docs#3429]
The default context path for the official nexus image ```sonatype/nexus``` is ```/nexus``` and therefore the repository url would be ```/nexus/content/groups/public``` rather than ```/content/groups/public``` which is specified in the readiness probe and therefore the container doesn't get deployed.

Either the urls should be corrected or instead set the context path to ```/``` when deploying the image:
```
oc new-app sonatype/nexus -e CONTEXT_PATH=/
```

Doc url: https://docs.openshift.org/latest/dev_guide/app_tutorials/maven_tutorial.html

**Comment by bfallonf** [comment]
@siamaksade @oatmealraisin I created #3437 for this issue. We can move the conversation to there. I'll close this issue.

Thanks!
