### ISSUE TITLE
Incorrect docker registry subnet?

### ISSUE THREAD

**Issue by mmilata** [openshift/openshift-docs#344]
When upgrading from 0.4.3 to 0.4.4 i noticed that the value of `servicesSubnet` changed from `172.30.17.0/24` to `172.30.0.0/16`. However `getting_started/dev_get_started/setup.adoc` suggests setting the docker insecure registry to the former value.

openshift/origin#1742 might be related.

**Comment by adellape** [comment]
Thanks for reporting. This was fixed in https://github.com/openshift/openshift-docs/pull/345.
