### ISSUE TITLE
[enterprise-4.7] Issue in file operators/admin/olm-managing-custom-catalogs.adoc

### ISSUE THREAD

**Issue by isldj** [openshift/openshift-docs#34420]
### Which section(s) is the issue in?
in this section https://docs.openshift.com/container-platform/4.7/operators/admin/olm-managing-custom-catalogs.html#olm-mirroring-package-manifest-catalog_olm-managing-custom-catalogs
Mirroring a Package Manifest Format catalog image
Procedure 2.a
echo "select * from related_image where operatorbundle_name like 'clusterlogging.4.3%';" | sqlite3 -line /tmp/190214037/bundles.db 

### What needs fixing?
I guess the name of the file changed with 4.7
bundles.db  should be index.db

**Comment by jboxman** [comment]
cc @adellape
