### ISSUE TITLE
Update etcd prereqs. 

### ISSUE THREAD

**Issue by timothysc** [openshift/openshift-docs#3447]
I would add the following language to the docs: 

"Please consult https://github.com/coreos/etcd/blob/master/Documentation/op-guide/hardware.md#hardware-recommendations to properly size your etcd Nodes"  

* Minimum ... 

NOTE: Openshift currently stores image meta-data in etcd,  operators should take special consideration take special care to periodically prune old images.  If you are planning to leverage a large number of images, then operators should consider placing etcd on machines with large amounts of memory and fast ssd drives.

/cc @ahardin-rh

**Comment by ahardin-rh** [comment]
Doc PR: https://github.com/openshift/openshift-docs/pull/3448
