### ISSUE TITLE
[enterprise-4.7] Issue in file openshift_images/managing_images/using-image-pull-secrets.adoc

### ISSUE THREAD

**Issue by troppens** [openshift/openshift-docs#34518]
### Which section(s) is the issue in?
In this sentence:

You use this pull secret to authenticate with the services that are provided by the included authorities, including Quay.io and registry.redhat.io, which serve the container images for OpenShift Container Platform components.

### What needs fixing?

The links to "Quay.io" and "registry.redhat.io", are broken and need to be fixed.

**Comment by bergerhoffer** [comment]
Link in question is at https://docs.openshift.com/container-platform/4.9/openshift_images/managing_images/using-image-pull-secrets.html

Will need to check which versions this applies to
