### ISSUE TITLE
Unsupported Versions Warning on Mobile

### ISSUE THREAD

**Issue by afflom** [openshift/openshift-docs#34631]
### Which section(s) is the issue in?

Unsupported Versions

### What needs fixing?
An unsupported versions warning message displays poorly on mobile devices.
![image](https://user-images.githubusercontent.com/30676559/125936235-155d68cc-6f57-4eb2-b7e1-83eb178305a7.png)

**Comment by jboxman** [comment]
@aireilly any ideas? Thanks!

**Comment by aireilly** [comment]
@jboxman If it were up to me, I think I would just remove the `<div id="annoying-box"/>` altogether, for mobile and desktop. I don't think it serves a purpose. We also have an admonition that is front and center at the start of the page. I think this is enough.
![image](https://user-images.githubusercontent.com/74046732/127022070-102e8fc6-1c80-483c-9043-cf7bac40526a.png)

**Comment by jboxman** [comment]
It's probably up to @vikram-redhat how aggressive this notice needs to be.

**Comment by aireilly** [comment]
Fixed in https://github.com/openshift/openshift-docs/pull/37963 /close
