### ISSUE TITLE
The "allow 'allow-lists' per container repo" feature might not have been thoroughly tested 

### ISSUE THREAD

**Issue by mburke5678** [openshift/openshift-docs#34642]
In researching https://github.com/openshift/openshift-docs/pull/34585, @mtrmac suggested _[The API in https://github.com/openshift/api/blob/02b64ca27d54dafe24b8740e45662f45bd3a332e/config/v1/types_image.go#L110-L114 is not documented that way, there are AFAIK no regression tests, the relevant MCO code talks about registries and not repos. Unless all of that changes, the behavior may change any time, whether due to unrelated feature work or because someone decides to add stricter validation for allowedRegistries.)](https://github.com/openshift/openshift-docs/pull/34585#pullrequestreview-707654238)_

I reviewed the [QE test](https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-38176) case and it appears you might be correct. It appears that he used a dummy repo/registry to verify that the MCO updated the search registry lists on the nodes (which I also did, not having access to live repos/registries to test), and not whether the change has an effect on the node's ability to pull just from that registry.

We need to verify that the change was properly tested and might need to remove the changes to 4.8+ added in https://github.com/openshift/openshift-docs/pull/31263

**Comment by mtrmac** [comment]
From my side I have added https://issues.redhat.com/browse/OCPNODE-461?focusedCommentId=16434016&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16434016 to hopefully do the necessary work for code to catch up.
