### ISSUE TITLE
[enterprise-4.7] Issue in file support/troubleshooting/troubleshooting-crio-issues.adoc

### ISSUE THREAD

**Issue by silliman** [openshift/openshift-docs#34745]
### Which section(s) is the issue in?

[Verifying CRI-O runtime engine status](https://docs.openshift.com/container-platform/4.7/support/troubleshooting/troubleshooting-crio-issues.html#verifying-crio-status_troubleshooting-crio-issues)

### What needs fixing?

Step _d_ is described as _Output a more detailed kubelet.service status summary:_ but then the command given is `systemctl status crio`

So the description probably just needs to change to something like _Output a more detailed crio.service status summary:_

**Comment by bergerhoffer** [comment]
CC @JoeAldinger

**Comment by JoeAldinger** [comment]
Testing, testing, 1, 2.

**Comment by bergerhoffer** [comment]
PR #41162 has been merged, closing this issue!
