### ISSUE TITLE
Indicate that extensions are injected as extensions.js/extensions.css

### ISSUE THREAD

**Issue by jawnsy** [openshift/openshift-docs#3490]
I'm not sure how to best describe this, but the [Customizing the Web Console](https://docs.openshift.org/latest/install_config/web_console_customization.html) topic should be updated to indicate that extension scripts and styles are concatenated and returned as a single `extensions.js` and `extensions.css` file.

For practical purposes, what this means is that any variables declared (e.g. `var abc = '123'`) will be global variables (`window.abc` will have value `123`), unless using the [Immediately-Invoked Function Expression pattern](http://benalman.com/news/2010/11/immediately-invoked-function-expression/) to ensure that variables are closure-scoped.

I suggest something like:

> JavaScript code from extensions are concatenated into a single file, named `extensions.js`. Any code will be executed in-line, so variable declarations will affect global state. It is recommended to wrap extensions in a closure, following the Immediately-Invoked Function Expression (IIFE) pattern, to ensure that variable declarations don't leak to the `window` object.

(Could use some phrasing help simplifying this)

**Comment by jawnsy** [comment]
cc @jwforres

**Comment by gaurav-nelson** [comment]
Thank you @jawnsy for the suggestion. I have addressed this in PR #4767 

Closing this.
