### ISSUE TITLE
[enterprise-4.8] "Windows Container Support for OpenShift" is missing in 4.8 docs

### ISSUE THREAD

**Issue by jomeier** [openshift/openshift-docs#34922]
Hi,

the docs for "Windows Container Support for OpenShift" are missing in the 4.8 docs.

Greetings,

Josef

**Comment by codyhoag** [comment]
@jomeier The docs are now available for OCP 4.8: https://docs.openshift.com/container-platform/4.8/windows_containers/windows-containers-release-notes-3-x.html. Closing this as it is now resolved.
