### ISSUE TITLE
[enterprise-4.7] Issue in file cli_reference/helm_cli/getting-started-with-helm-on-openshift-container-platform.adoc

### ISSUE THREAD

**Issue by Keyvan-rh** [openshift/openshift-docs#34927]
### Which section(s) is the issue in?
Installing a Helm chart on an OpenShift Container Platform cluster
  2. Add a repository of Helm charts to your local Helm client:

### What needs fixing?
this repo does not exist anymore 
      https://kubernetes-charts.storage.googleapis.com/
Needs to be changed to:
     https://charts.helm.sh/stable

**Comment by bergerhoffer** [comment]
CC @Preeticp
