### ISSUE TITLE
[enterprise-4.7] Issue in file security/certificates/replacing-default-ingress-certificate.adoc

### ISSUE THREAD

**Issue by meahoibm** [openshift/openshift-docs#35026]
### Which section(s) is the issue in?
The certificate must include the subjectAltName extension showing *.apps.<clustername>.<domain>.

### What needs fixing?
Show an example line of 
subjectAltName=DNS:*.apps.<clustername>.<domain> 
as specifying 
subjectAltName=*.apps.<clustername>.<domain> 
is an error the inexperienced will encounter.  
Also would be nice on how to find <clustrername>.<domain> for new learners of OpenShift admin

**Comment by jboxman** [comment]
@meahoibm, what does this mean?

> Also would be nice on how to find . for new learners of OpenShift admin

Thanks!

**Comment by meahoibm** [comment]
Looks like the wildcard asterisk did not take for my original post
subjectAltName=DNS:<asterisk>.apps.<clustername>.<domainname>
and would be helpful if a knowledge expert could input on what the line should look like whether in a configuration file or on a command line interface.

I don't recall what I meant with my last comment in the original post.  But I would say the CA and the final certificate information could use a bit more of explanation for that process for the inexperienced.  

I am reading about 4.8 Ingress certificates on the link 
https://docs.openshift.com/container-platform/4.8/security/certificate_types_descriptions/ingress-certificates.html

and eventually hope to resolve the problems I am having establishing the CA and certificates for doing ingress on my open shift install.

**Comment by jboxman** [comment]
fyi @bmcelvee
