### ISSUE TITLE
[online] Issue in file rosa_getting_started/rosa-creating-cluster.adoc

### ISSUE THREAD

**Issue by madhusudanupadhyay** [openshift/openshift-docs#35039]
### Which section(s) is the issue in?
Prerequisites

### What needs fixing?

Typo: 
You have installed {product-title].

Not sure if this was intended. Seems like a typo though.

**Comment by ahardin-rh** [comment]
@madhusudanupadhyay Thank you for reporting this typo! I folded the fix into https://github.com/openshift/openshift-docs/pull/34960/files#diff-61014101e502210acb2d7bac9bcb5a577b03a51e05e3320d329cb0a5168f00d6R14

**Comment by ahardin-rh** [comment]
This issue is now resolved: https://docs.openshift.com/rosa/rosa_getting_started/rosa-creating-cluster.html
