### ISSUE TITLE
[enterprise-4.8] Issue in file cli_reference/openshift_cli/getting-started-cli.adoc

### ISSUE THREAD

**Issue by steveteahan** [openshift/openshift-docs#35079]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.8/cli_reference/openshift_cli/getting-started-cli.html#cli-installing-cli_cli-developer-commands

### What needs fixing?

**Navigate to the [Infrastructure Provider](https://cloud.redhat.com/openshift/install) page on the Red Hat OpenShift Cluster Manager site.**

The Infrastructure Provider link appears to bring me to a page to create a new cluster.  The instructions that follow don't appear to lead me to a `oc` binary unless I'm missing something.  Should this link point to [Downloads](https://console.redhat.com/openshift/downloads) instead?

**Comment by bergerhoffer** [comment]
Closing, the related PR was merged. Updates will be live shortly (now pointing to the customer portal for downloading the CLI).
