### ISSUE TITLE
[enterprise-4.6] Issue in file logging/cluster-logging-exported-fields.adoc

### ISSUE THREAD

**Issue by bergerhoffer** [openshift/openshift-docs#35085]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.6/logging/cluster-logging-exported-fields.html

### What needs fixing?

There are a bunch of `TODO` words in the descriptions in the tables. Even if these were pulled from a description somewhere, I don't think we should be showing TODOs.

The 4.7+ versions of this page at least looks to have been redone and doesn't have any TODOs: https://docs.openshift.com/container-platform/4.7/logging/cluster-logging-exported-fields.html

**Comment by bergerhoffer** [comment]
@kalexand-rh Since 4.6 is only being maintained a little longer, should I close this issue?

**Comment by kalexand-rh** [comment]
@bergerhoffer, that sounds reasonable to me.

**Comment by bergerhoffer** [comment]
Thanks, closing!
