### ISSUE TITLE
[enterprise-4.8] Issue in file modules/cnf-assigning-a-sriov-network-to-a-vrf.adoc

### ISSUE THREAD

**Issue by martinkennelly** [openshift/openshift-docs#35299]
### Which section(s) is the issue in?
https://github.com/openshift/openshift-docs/blob/940059c583703d1f6e84f70ba507d4564c8499de/modules/cnf-assigning-a-sriov-network-to-a-vrf.adoc#L36

This command does not work.

```
$ oc create sriovnetwork.openshift.io cluster
Error: must specify one of -f and -k

error: unknown command "sriovnetwork.openshift.io cluster"
```

```
$ oc version
Client Version: 4.8.2
Server Version: 4.8.2
```

### What needs fixing?
Removal of this command

**Comment by jboxman** [comment]
fyi @aireilly

`oc create` takes a file, so the command needs to be invoked with the YAML like `oc create -f <sriovnetwork_object>.yaml`. Sort of like in `modules/nw-sriov-dpdk-example-intel.adoc`.

**Comment by aireilly** [comment]
@fedepaol @kononovn Can you comment on this please. We have a broken command in this procedure. I think we missed a typo here, this command should be `oc edit sriovnetwork.openshift.io cluster`. Also we are not creating a `SriovNetwork` resource, only modifying it resource by adding the `metaPlugins` element? 

Note in https://github.com/openshift/openshift-docs/blob/main/modules/cnf-assigning-a-secondary-network-to-a-vrf.adoc we have `oc edit networks.operator.openshift.io cluster`
