### ISSUE TITLE
[enterprise-4.6] Issue in file serverless/admin_guide/installing-knative-serving.adoc

### ISSUE THREAD

**Issue by veronicaboychuk** [openshift/openshift-docs#35338]
### Which section(s) is the issue in?
"Installing Knative Serving using YAML"

### What needs fixing?
The example output includes a `kn-cli-downloads-xxx` pod but this does not seem to appear in most, if any, installations. I think this pod name should be excluded from example output since installations can work without it + it does not seem to accurately reflect new installations (and is therefore likely to make users think their installation didn't succeed).

**Comment by jboxman** [comment]
fyi @abrennan89
