### ISSUE TITLE
[OKD]Topic name for "Migration from 3to4" section is OCP instead of OKD.

### ISSUE THREAD

**Issue by tnk4on** [openshift/openshift-docs#35357]
### Which section(s) is the issue in?

Topic map for
https://docs.okd.io/latest/migrating_from_ocp_3_to_4/about-migrating-from-3-to-4.html
https://docs.okd.io/latest/migrating_from_ocp_3_to_4/planning-migration-3-4.html

### What needs fixing?

Change the topic name "OpenShift Container Platform 3 to 4" to "OKD 3 to 4".

**Comment by bergerhoffer** [comment]
FYI @apinnick

**Comment by apinnick** [comment]
I am not an OpenShift writer, so I have no idea what the problem is or what is required.

**Comment by bergerhoffer** [comment]
PR has merged, updates will be live shortly
