### ISSUE TITLE
[enterprise-4.7] Issue in file networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-ingress-controller.adoc

### ISSUE THREAD

**Issue by paraenggu** [openshift/openshift-docs#35459]
### Which section(s) is the issue in?
* [Creating a project and service](https://docs.openshift.com/container-platform/4.7/networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-ingress-controller.html#nw-creating-project-and-service_configuring-ingress-cluster-traffic-ingress-controller)
* [Exposing the service by creating a route](https://docs.openshift.com/container-platform/4.7/networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-ingress-controller.html#nw-exposing-service_configuring-ingress-cluster-traffic-ingress-controller)

### What needs fixing?
The section [Using Ingress Controllers and routes](https://docs.openshift.com/container-platform/4.7/networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-ingress-controller.html#nw-using-ingress-and-routes_configuring-ingress-cluster-traffic-ingress-controller) states the following:
> The Ingress Operator manages Ingress Controllers and wildcard DNS.
>
> Using an Ingress Controller is the most common way to allow external access to an OpenShift Container Platform cluster.
>
> An Ingress Controller is configured to accept external requests and proxy them based on the configured routes. This is limited to HTTP, HTTPS using SNI, and TLS using SNI, which is sufficient for web applications and services that work over TLS with SNI.

However, the [subsequent chapters](https://docs.openshift.com/container-platform/4.7/networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-ingress-controller.html#nw-creating-project-and-service_configuring-ingress-cluster-traffic-ingress-controller) shows an example with a MySQL service, which is confusing, as one would expect an example whereas a HTTP/HTTPS service will be exposed, including an explanation regarding the wildcard ingress URL an other ingress configuration possibilities.

It would be very helpful if the chapter could be adapted to provide an example with a HTTP/HTTPS service.

**Comment by jboxman** [comment]
cc @bmcelvee 

This is the subject of one of the open BZs I think.
