### ISSUE TITLE
[online] Issue in file installing/install-ocp-operator.adoc

### ISSUE THREAD

**Issue by dlbewley** [openshift/openshift-docs#35452]
### Which section(s) is the issue in?

Generating an init bundle by using the RHACS portal

### What needs fixing?

Instructions reference _Click Generate Bundle (add icon) on the top right._ but the button at top right is _New integration_.
Screenshot https://www.dropbox.com/s/6m0o3b402ev1z2v/Screen%20Shot%202021-08-11%20at%2013.24.34.png?raw=1

**Comment by gaurav-nelson** [comment]
Thanks @bergerhoffer This is already fixed https://docs.openshift.com/acs/3.66/installing/install-ocp-operator.html#portal-generate-init-bundle_install-ocp-operator Please feel free to close this issue.

**Comment by bergerhoffer** [comment]
Awesome thanks @gaurav-nelson! Closing
