### ISSUE TITLE
[enterprise 4.8] Missing configuration step in modules/nw-sriov-configuring-operator.adoc

### ISSUE THREAD

**Issue by martinkennelly** [openshift/openshift-docs#35461]
### Which section(s) is the issue in?
https://github.com/openshift/openshift-docs/blob/main/modules/nw-sriov-configuring-operator.adoc

No current section seems to fit what I want to fix.

### What needs fixing?
No where in the docs is mentioned that, by default, we need to apply a label to the nodes that we want the SRIOV Network Operator to config when a ```SriovNetworkNodePolicy``` is specified. You must apply a label and add that label to ```SriovNetworkNodePolicy``` spec's field ```nodeSelector```.
See upstream readme for example of ```SriovNetworkNodePolicy``` and ```nodeSelector```
Need any extra information, reach out.

**Comment by jboxman** [comment]
cc @mikemckiernan @ctauchen 

@zshi-redhat, does this make sense to add?

Thanks!

**Comment by zshi-redhat** [comment]
> cc @mikemckiernan @ctauchen
> 
> @zshi-redhat, does this make sense to add?
> 
> Thanks!

@martinkennelly @jboxman  There is a chapter about configuring the sriov device via sriovnetworknodepolicy: https://docs.openshift.com/container-platform/4.8/networking/hardware_networks/configuring-sriov-device.html#nw-sriov-networknodepolicy-object_configuring-sriov-device, nodeSelector parameter is explained with the index 4.

Here is the doc module link: https://github.com/openshift/openshift-docs/blob/main/modules/nw-sriov-networknodepolicy-object.adoc

**Comment by martinkennelly** [comment]
Thanks Zenghui..That is sufficient. I missed this.
