### ISSUE TITLE
Incorrect htpasswd path in docs

### ISSUE THREAD

**Issue by mazzystr** [openshift/openshift-docs#3553]
https://docs.openshift.com/container-platform/3.3/install_config/registry/accessing_registry.html
https://docs.openshift.com/container-platform/3.4/install_config/registry/accessing_registry.html

browser search for '/etc/origin/openshift-htpasswd'

The correct path is /etc/origin/master/htpasswd

Please update to match default path per openshift-ansible installation

Thanks!

**Comment by bfallonf** [comment]
@mazzystr Seems that on my test machine, the path is indeed '/etc/origin/openshift-htpasswd'. Am I missing something? My install is OCP 3.4. Is yours any different?

**Comment by mazzystr** [comment]
My install is OCP 3.3

**Comment by gaurav-nelson** [comment]
@mazzystr Thank you for creating this. 
`htpasswd`command adds a `username:password` key value pair at the specified pah. See [htpasswd](https://httpd.apache.org/docs/current/programs/htpasswd.html) for more details. It really doesn't matter whatever the path is. Closing this.
