### ISSUE TITLE
Installing Stand-Alone Registry document is incorrect or incomplete

### ISSUE THREAD

**Issue by maxamillion** [openshift/openshift-docs#3557]
The [Installing a Stand-alone Registry](https://docs.openshift.org/latest/install_config/install/stand_alone_registry.html) document is either incorrect or incomplete. When following this document, the resulting deployment OAuth provider does not work and there is no public facing route to either the ``docker-registry`` service or ``registry-console`` service.

**Comment by bfallonf** [comment]
Thanks @maxamillion . This is more than a simple fix, and would require some testing out, so I've reported a BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1415880

If you have any more information, please add it to the BZ. I'll close this issue.
