### ISSUE TITLE
Should warn if cockpit is already running (atomic-registry)

### ISSUE THREAD

**Issue by burhan** [openshift/openshift-docs#3562]
The documentation for atomic registry should include a warning that if the host you are running on already has cockpit running, to shut it down first otherwise the registry console (which is also based on cockpit and thus uses the same port `9090`) will refuse to start.

**Comment by brennv** [comment]
Agreed, that can be frustrating. PR with a proposed change: https://github.com/openshift/openshift-docs/pull/3566

**Comment by bfallonf** [comment]
@burhan @brennv Thanks! OpenShift has Cockpit integration as well, so I think it's ok to merge into everything. With the change in comment 2, I'll close this issue.

Thanks!
