### ISSUE TITLE
Fix typo: 'specific file' vs 'literal value'

### ISSUE THREAD

**Issue by brennv** [openshift/openshift-docs#3565]
Lines 182 and 270 of dev_guide/configmaps.adoc have the same wording:

`. Create the `*ConfigMap*` specifying a specific file:`

Line 182 is correct because the section is about creating ConfigMaps from files. https://github.com/openshift/openshift-docs/blob/master/dev_guide/configmaps.adoc#creating-from-files

But the section with line 270 is about creating ConfigMaps from literal values.
https://github.com/openshift/openshift-docs/blob/master/dev_guide/configmaps.adoc#creating-from-literal-values

So line 270 should read:

`. Create the `*ConfigMap*` specifying a literal value:`

Fixed with https://github.com/openshift/openshift-docs/pull/3564

**Comment by bfallonf** [comment]
Thanks for making the PR, @brennv . With it merged, I'll close this issue.
