### ISSUE TITLE
[enterprise-4.7] Issue in file security/certificates/replacing-default-ingress-certificate.adoc

### ISSUE THREAD

**Issue by ryannelle** [openshift/openshift-docs#35680]
### Which section(s) is the issue in?
Replacing the default ingress certificate

### What needs fixing?
Procedure 1.
"Create a config map that includes **only the root CA certificate** used to sign the wildcard certificate:"
The example code shows to use --from-file=**ca-bundle.crt** but line above it says use only the root CA certificate. 

It's confusing to know if only a single CA certificate should be loaded or a larger CA bundle.

**Comment by jboxman** [comment]
cc @bmcelvee
