### ISSUE TITLE
[online] Issue in file installing/installing_helm/install-helm-quick.adoc

### ISSUE THREAD

**Issue by takleung** [openshift/openshift-docs#35767]
### Which section(s) is the issue in?
Adding the Helm chart repository

### What needs fixing?
change "helm repo add stackrox  https://mirror.openshift.com/pub/rhacs/charts/" to "helm repo add rhacs  https://mirror.openshift.com/pub/rhacs/charts/"

**Comment by bergerhoffer** [comment]
@gaurav-nelson FYI

**Comment by gaurav-nelson** [comment]
Thanks @bergerhoffer .

@IAmATeaPot418 Can you confirm if this is correct?

**Comment by takleung** [comment]
It is better to go through the parameter from the document. Repository should be called either rhacs or stackrox

**Comment by gaurav-nelson** [comment]
Fixed by https://github.com/openshift/openshift-docs/pull/38505

@bergerhoffer Can you please close this?
