### ISSUE TITLE
No documentation link provided to report issues with registry?

### ISSUE THREAD

**Issue by burhan** [openshift/openshift-docs#3580]
There is no place in the documentation to file bugs against the registry component itself, or ask questions when things are not working.

Where should one raise issues?

**Comment by vikram-redhat** [comment]
Hey Burhan - For origin docs issues, creating an issue like you have is a great way to start. For enterprise docs, you can either send an email to openshift-docs@redhat.com, or file a bug: https://bugzilla.redhat.com/enter_bug.cgi?product=Openshift%20Container%20Platform%20&component=Documentation

**Comment by burhan** [comment]
Hi Vikram - I think I may not be using the right terms here. I am having an issue specifically with the atomic registry part.

I have followed the documentation and installed it on our RedHat Atomic test machine. I think everything went fine because the interface at `:9090` looks the same as that in the documentation.

I can also create projects and push/pull images from the command line.

The problem I have is that the images I have pushed to the registry do not show up in the online interface.

I am new to OpenShift so I am not sure where to report this issue; because its not with the documentation, its rather with the software itself.

**Comment by brennv** [comment]
It sounds like you might be hitting [Bug 1373455](https://bugzilla.redhat.com/show_bug.cgi?id=1373455). For reference you can also review the upstream [origin-web-console issues for the registry](https://github.com/openshift/origin/issues?utf8=%E2%9C%93&q=registry%20).

**Comment by gaurav-nelson** [comment]
This seems like a software problem and not a docs specific thing. (Closing this)

@burhan as @brennv mentioned, please see  the upstream [origin-web-console issues for the registry](https://github.com/openshift/origin/issues?utf8=%E2%9C%93&q=registry%20). If none of those help feel free to create a new issue there.
