### ISSUE TITLE
[enterprise-4.8] Issue in file installing/installing_bare_metal_ipi/ipi-install-installation-workflow.adoc

### ISSUE THREAD

**Issue by mistergareth** [openshift/openshift-docs#35880]
### Which section(s) is the issue in?
Step 14 - Create the pull-secret.txt file for Bare Metal IPI.

### What needs fixing?
The description of how to find and copy the pull-secret appears to be based an older version of the web UI. It doesn't quite match what you see when you click the link.

Here is the current text. The **bold** indicates the linked text.

>In a web browser, navigate to **Install on Bare Metal with user-provisioned infrastructure**, and scroll down 
>to the Downloads section. Click Copy pull secret. Paste the contents into the pull-secret.txt file and save the 
>contents in the kni user’s home directory.

First, there's not need to "scroll down." At least not when I clicked the link and logged in. It's right at the top. And no need to go to a "Downloads" section. It's the 2nd item from the top, Titled **Pull Secret** with a button to download and one to **Copy pull secret**.

You can still get to it in the "Downloads" section, but it's simply a menu item on the left panel, and _then_ you can scroll down to **Tokens** where you will again have both a *Download* button and a *Copy pull secret* link.

Just needs a bit of a touch up.

**Comment by codyhoag** [comment]
@johnwilkins wanted to tag you for awareness since this is for bare metal IPI

**Comment by johnwilkins** [comment]
Addressing this now. /close
