### ISSUE TITLE
[enterprise-4.6] Issue in file networking/configuring-a-custom-pki.adoc

### ISSUE THREAD

**Issue by smossber** [openshift/openshift-docs#35943]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.6/networking/configuring-a-custom-pki.html#certificate-injection-using-operators_configuring-a-custom-pki
Overall the whole page except the add ca using operators. 
But I guess mostly the intro, first section below the heading

### What needs fixing?

```

Some platform components, such as the web console, use Routes for communication and must trust other components' certificates to interact with them. If you are using a custom public key infrastructure (PKI), you must configure it so its privately signed CA certificates are recognized across the cluster.

You can leverage the Proxy API to add cluster-wide trusted CA certificates. You must do this either during installation or at runtime.
```
` to add cluster-wide trusted CA certificates` 
Add it how? What will happen if I do this? Will it automatically be sourced by any Pod? 
Will it be added as part of `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt` ? 

I think `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt` is the answer but I can't see it mentioned anywhere. 

Certificates has to be one of the most confused topics we encounted in our support and administration of OCP.
I think the topic overall could use a bit more verbosity and clearness.
This could be a start.

Cheers! :)

**Comment by jboxman-rh** [comment]
cc @skrthomas
