### ISSUE TITLE
"The check is deemed successful if the hook returns with 200 or 399"

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-docs#3600]
The above text appears in dev_guide/application_health.html.  As per https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/pkg/probe/http/http.go#L81, I believe this should read "The check is deemed successful if the hook returns a value >= 200 and < 400".  All versions.

**Comment by gaurav-nelson** [comment]
Not an issue anymore, fixed in the latest docs. https://docs.openshift.org/latest/dev_guide/application_health.html#container-health-checks-using-probes under *HTTP Checks* heading. The text now reads:

> The check is deemed successful if the HTTP response code is between 200 and 399.
