### ISSUE TITLE
[enterprise-4.8] Issue in file applications/application_life_cycle_management/creating-applications-using-cli.adoc

### ISSUE THREAD

**Issue by 0kashi** [openshift/openshift-docs#36055]
### Which section(s) is the issue in?
Create and application from source code - https://docs.openshift.com/container-platform/4.8/applications/application_life_cycle_management/creating-applications-using-cli.html#applications-create-using-cli-source-code_creating-applications-using-cli

### What needs fixing?
The text currently states that "The new-app command typically also creates a DeploymentConfig object to deploy...", though it actually creates a "Deployment" object and you need a flag in oc `--as-deployment-config=true` to force a deploymentconfig.  So correct it to state that it created a deployment object instead.

**Comment by stevsmit** [comment]
We have fixed your submission, @0kashi. Thank you for submitting!
