### ISSUE TITLE
[online] Issue in file rosa_getting_started/rosa-aws-privatelink-creating-cluster.adoc

### ISSUE THREAD

**Issue by 0kashi** [openshift/openshift-docs#36068]
### Which section(s) is the issue in?
https://docs.openshift.com/rosa/rosa_getting_started/rosa-aws-privatelink-creating-cluster.html#rosa-aws-privatelink-create-cluster.adoc_rosa-getting-started

### What needs fixing?
There is a standalone "+" that doesnt look like it belongs there.  Literally a plus sign.

**Comment by stevsmit** [comment]
@jonquilwilliams

**Comment by jonquilwilliams** [comment]
This is being fixed in a different issue: https://github.com/openshift/openshift-docs/pull/35314

Thanks for catching it!
