### ISSUE TITLE
[enterprise-4.8] Issue in file networking/ingress-operator.adoc

### ISSUE THREAD

**Issue by flozanorht** [openshift/openshift-docs#36067]
### Which section(s) is the issue in?
"Configuring application domain for the Ingress Controller Operator on AWS"
Procedure step 1.b

### What needs fixing?
The sample YAML makes no sense. It looks like it is incomplete, has extra unecessary information, or just plain wrong.

spec:
  domain: apps.<domain_url>
  appsDomain: apps.acme.io

What is "<domain_url>" ? Looks like a marker that I would replace with an actual value, what is the value?

Why should I be changing the "domain" attribute then the instructions only mention the "appsDomain" attribute?

If I do need to change the "domain" attribute also, which would be is the correct value for that example?

**Comment by jboxman** [comment]
cc @bmcelvee
