### ISSUE TITLE
[enterprise-4.8] Copy shortcut Issue in file backup_and_restore/disaster_recovery/scenario-2-restoring-cluster-state.adoc

### ISSUE THREAD

**Issue by dpkshetty** [openshift/openshift-docs#36105]
### Which section(s) is the issue in?
All sections

### What needs fixing?
When I click on the copy option (top right of all the commands)... it copies the prompt too, due to which one cannot just paste it and run it in the terminal window! Expectation is that the copy option should copy just the cmd such that one can paste and hit enter 

Here is an example of what gets copied
```
[core@ip-10-0-154-194 ~]sudo mv /var/lib/etcd/ /tmp
```

while the expectation is
```
sudo mv /var/lib/etcd/ /tmp
```

**Comment by stevsmit** [comment]
Hi @dpkshetty . I'm not sure if we're able to resolve this issue given that it would require fixing the `Copy Code` command. This is a rare exception to how we normally document commands on the CLI.

**Comment by dpkshetty** [comment]
@stevsmit just remove the prompt from the code block, won't that work ?
