### ISSUE TITLE
[enterprise-4.6] Issue in file scalability_and_performance/cnf-performance-addon-operator-for-low-latency-nodes.adoc

### ISSUE THREAD

**Issue by boris-deschenes** [openshift/openshift-docs#36143]
### Which section(s) is the issue in?
DEV PREVIEW WARNING in "Installing the Performance Addon Operator using the web console"
DEV PREVIEW WARNING in "Allocating multiple huge page sizes"

### What needs fixing?
This is causing confusion because the 4.6 release note (https://docs.openshift.com/container-platform/4.6/release_notes/ocp-4-6-release-notes.html#ocp-4-6-performance-addon-operator) states that his is fully supported in 4.6

this issue is still there in 4.7 and 4.8 same pages

**Comment by aireilly** [comment]
@vikram-redhat can you assign this one to me please.

**Comment by aireilly** [comment]
@boris-deschenes @vikram-redhat This issue can be closed, the dev preview warnings were removed for all affected branches in a seperate PR.
