### ISSUE TITLE
[enterprise-4.8] Issue in file installing/index.adoc

### ISSUE THREAD

**Issue by mistergareth** [openshift/openshift-docs#36147]
### Which section(s) is the issue in?
The "Supported Platforms for OpenShift Clusters for IPI"
https://docs.openshift.com/container-platform/4.8/installing/index.html#supported-platforms-for-openshift-clusters_ocp-installation-overview

### What needs fixing?
I'm pretty sure we support IPI on Bare Metal now. We're doing this with partners. But "Bare Metal" is missing from this list.

However Bare Metal does appear in the next list in the doc for UPI targets. So it appears to be missing from the IPI list. Unless I am mistaken and it's still in TP.

This may also be present in the 4.7 docs.

**Comment by codyhoag** [comment]
Thanks for catching this! I have submitted a PR to address the IPI list missing bare metal: #36158
