### ISSUE TITLE
[enterprise-4.8] Issue in file operators/operator_sdk/golang/osdk-golang-tutorial.adoc

### ISSUE THREAD

**Issue by TheRealJon** [openshift/openshift-docs#36166]
### Which section(s) is the issue in?
[About OpenAPI validation](https://docs.openshift.com/container-platform/4.8/operators/operator_sdk/golang/osdk-golang-tutorial.html#osdk-golang-generate-crd-validation_osdk-golang-tutorial)

### What needs fixing?
This section is repeated twice

**Comment by jboxman** [comment]
cc @adellape

**Comment by bergerhoffer** [comment]
Marking this as a good candidate for Hacktoberfest.

I believe that the duplicated lines can just be removed from the `osdk-golang-generate-crd.adoc` file.

PR to fix this should be submitted against the `main` branch, and ping me with any questions!
