### ISSUE TITLE
[enterprise-4.8] Issue in file rest_api/network_apis/route-route-openshift-io-v1.adoc

### ISSUE THREAD

**Issue by pdhamdhe** [openshift/openshift-docs#36223]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.8/rest_api/network_apis/route-route-openshift-io-v1.html#specification

Inside .spec.tls.insecureEdgeTerminationPolicy the Disable setting is not valid.  if we try to set Disable then it reports:

routes.route.openshift.io "edge-route" was not valid:
* spec.tls.insecureEdgeTerminationPolicy: Invalid value: "Disable": invalid value for InsecureEdgeTerminationPolicy option, acceptable values are None, Allow, Redirect, or empty

### What needs fixing?
The valid values are None or empty instead of Disable which is also mentioned in document section 

https://docs.openshift.com/container-platform/4.8/networking/routes/secured-routes.html#nw-ingress-creating-a-passthrough-route_secured-routes

`Optional insecureEdgeTerminationPolicy. The only valid values are None, Redirect, or empty for disabled.`

**Comment by jboxman** [comment]
@pdhamdhe, thanks for reporting this; These docs are generated from the OpenAPI spec, which is derived mostly from `openshift/api` repository. To fix this, the change needs to be made there.
