### ISSUE TITLE
[enterprise-4.8] Issue in file networking/routes/secured-routes.adoc

### ISSUE THREAD

**Issue by pdhamdhe** [openshift/openshift-docs#36224]
### Which section(s) is the issue in?
Does not mention all values of  `spec.tls.insecureEdgeTerminationPolicy` parameter. `Allow` is missing.   
https://docs.openshift.com/container-platform/4.8/networking/routes/secured-routes.html#nw-ingress-creating-a-passthrough-route_secured-routes

`Optional insecureEdgeTerminationPolicy. The only valid values are None, Redirect, or empty for disabled.
`
### What needs fixing?
Need to add `Allow` keyword in above section to define it's all valid values.

**Comment by jboxman** [comment]
cc @bmcelvee
