### ISSUE TITLE
[enterprise-4.8] Issue in file release_notes/ocp-4-8-release-notes.adoc

### ISSUE THREAD

**Issue by jaboc** [openshift/openshift-docs#36248]
### Which section(s) is the issue in?
The following link gives access denied
https://access.redhat.com/solutions/6308491

### What needs fixing?
Authorisation

**Comment by jboxman** [comment]
@jeana-redhat:

>UNPUBLISHED: This document is not published or is a draft that is on track to be published.

**Comment by jeana-redhat** [comment]
Published it :+1:  @darshan-nagaraj reminder to do this step when the release goes live :)

Thanks @jaboc and @jboxman !
