### ISSUE TITLE
redirect loop on docs.okd.io

### ISSUE THREAD

**Issue by sdhoward** [openshift/openshift-docs#36271]
### Which section(s) is the issue in?

https://docs.okd.io/latest/welcome/index.html

### What needs fixing?

The IBM links are broken and result in an infinite redirect loop:

- https://docs.okd.io/latest/installing/installing_ibm_z/installing-ibm-z.html#installing-ibm-z
- https://docs.okd.io/latest/installing/installing_ibm_z/installing-ibm-z-kvm.html#installing-ibm-z-kvm
- https://docs.okd.io/latest/installing/installing_ibm_power/installing-ibm-power.html#installing-ibm-power
- https://docs.okd.io/latest/installing/installing_ibm_z/installing-restricted-networks-ibm-z.html#installing-restricted-networks-ibm-z

**Comment by jboxman** [comment]
cc @mburke5678 @SNiemann15

**Comment by SNiemann15** [comment]
@jboxman I have to admit never seen that page before. Is the source also welcome/index.adoc?

**Comment by mburke5678** [comment]
@SNiemann15 Should the IBM install docs be in docs.okd.io?

**Comment by SNiemann15** [comment]
@mburke5678 I discussed this with @holgwolf today who said OKD should work on IBM Z but hasn't been verified. 

Not sure whats the best "fast" approach. Fix the broken links or remove from OKD and add again once its verified.

**Comment by SNiemann15** [comment]
For Power @manojnkumar should know.

**Comment by mburke5678** [comment]
@SNiemann15 I asked our OKD person, Vadim, if OKD runs on IBM-Z and IBM Power systems, He told me _Probably not, at least its not available at this point._

**Comment by sdhoward** [comment]
https://github.com/openshift/openshift-docs/commit/cc4ec4b9de2f695a0959a668ba745da4ce614f1f#diff-40d72ccc658b0f56a1a01387cffdf2a793c5cd21234a0fcbfcc25cf880d318c5R42

**Comment by SNiemann15** [comment]
@mburke5678 Then lets remove them for OKD.

**Comment by mburke5678** [comment]
See: https://github.com/openshift/openshift-docs/pull/36328
