### ISSUE TITLE
[enterprise-4.7] Issue in file installing/installing_bare_metal/installing-bare-metal-network-customizations.adoc

### ISSUE THREAD

**Issue by bortek** [openshift/openshift-docs#36282]
### Which section(s) is the issue in?
Approving the certificate signing requests for your machines

### What needs fixing?
Whats the correct hostnames of the master and worker node? Is is master-0 and worker-0 or is it master0 and worker0. In the examples under "Approving the certificate signing requests for your machines" there is a dash in the naming while throughout the document it says that there is no dash.

**Comment by bortek** [comment]
the same might be true for 4.8 docs page

**Comment by bergerhoffer** [comment]
I believe that these are just example node names, both where master-0 and master0 are shown. The node names will most likely be something different altogether depending on the cluster. 

We could consider adding a note that these are just example names. Or we could consider coming through this whole page and updating them all to follow our example node name guidelines here, which would be `control-plane-1.example.com`, and so on.
