### ISSUE TITLE
[enterprise-4.7] Issue in file cicd/gitops/configuring-sso-for-argo-cd-on-openshift.adoc

### ISSUE THREAD

**Issue by radudd** [openshift/openshift-docs#36289]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.7/cicd/gitops/configuring-sso-for-argo-cd-on-openshift.html#configuring-groups-and-argocd-rbac_configuring-sso-for-argo-cd-on-openshift

### What needs fixing?
The groups claim in the JWT token contain the groups preceded by a "/". So the correct policy should look like:

```
g, /ArgoCDAdmins, role:admin
```

**Comment by stevsmit** [comment]
Hi Radu, 

I have submitted a PR for review.

Thanks!
