### ISSUE TITLE
[online] Issue in file installing/install-ocp-operator.adoc

### ISSUE THREAD

**Issue by suulperi** [openshift/openshift-docs#36283]
### Which section(s) is the issue in?

https://docs.openshift.com/acs/installing/install-ocp-operator.html#portal-generate-init-bundle_install-ocp-operator

### What needs fixing?

Replace step number 6. "Click Download Helm Values File to download the generated bundle." to "Download Kubernetes Secrets file to download the generated bundle."

**Comment by bergerhoffer** [comment]
Looks like this was fixed by @gaurav-nelson in #36277. Closing!
