### ISSUE TITLE
[RHACS] Issue in file installing/install-ocp-operator.adoc

### ISSUE THREAD

**Issue by suulperi** [openshift/openshift-docs#36284]
### Which section(s) is the issue in?

https://docs.openshift.com/acs/installing/install-ocp-operator.html#create-resource-init-bundle_install-ocp-operator

### What needs fixing?

Few improvements:

1. Chapter "Procedure" - Modify `Run the following command to create the resources` to be something more descriptive like `Run the following command to create the resources on a cluster which will be monitored`
2. Explanation of the command  `oc create -f <init_bundle>.yaml \ 
  -n <stackrox> ` Replace "Specify the name of the project where you installed Central" with "Specify the name of the project where you will install secured cluster services"

**Comment by stevsmit** [comment]
@gaurav-nelson
