### ISSUE TITLE
[online] Issue in file installing/install-ocp-operator.adoc

### ISSUE THREAD

**Issue by cmays20** [openshift/openshift-docs#36316]
### Which section(s) is the issue in?
Creating an Init bundle using the RHACS Portal.

### What needs fixing?
The instructions say to download the Helm Values File, when it should say to Download the Kubernetes Secrets File.  It is that file that can later be using in the oc create command.

**Comment by bergerhoffer** [comment]
This was fixed by @gaurav-nelson in #36277. Closing!
