### ISSUE TITLE
Replace the version to latest 4.9 in sample content for PSAP

### ISSUE THREAD

**Issue by liqcui** [openshift/openshift-docs#36318]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.9/scalability_and_performance/psap-node-feature-discovery-operator.html
https://docs.openshift.com/container-platform/4.9/scalability_and_performance/psap-driver-toolkit.html

### What needs fixing?
Please replace all the version from 4.8 to 4.9 in above two document.

**Comment by jboxman** [comment]
cc @ahardin-rh

**Comment by bergerhoffer** [comment]
@vikram-redhat Do we have someone doing this last minute task of the 4.8->4.9 sweep in @ahardin-rh's absence?

**Comment by bergerhoffer** [comment]
@kalexand-rh Whenever you do the 4.8->4.9 sweep (via https://issues.redhat.com/browse/OSDOCS-2368), can you close out this issue? Thanks!
