### ISSUE TITLE
[enterprise-4.8] Issue in file scalability_and_performance/cnf-performance-addon-operator-for-low-latency-nodes.adoc

### ISSUE THREAD

**Issue by mrVectorz** [openshift/openshift-docs#36355]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.8/scalability_and_performance/cnf-performance-addon-operator-for-low-latency-nodes.html#configuring_hyperthreading_for_a_cluster_cnf-master

Procedure step number 2

### What needs fixing?
The example[0] is misleading with the given yaml[1]. We need to change the example yaml and the given example.
The performance operator uses CPUSets lists ([perf doc](https://github.com/openshift-kni/performance-addon-operators/blob/master/docs/performance_profile.md#cpu) and [cpuset doc](https://man7.org/linux/man-pages/man7/cpuset.7.html)) meaning that instead of isolation cpu 0 and 4 it isolates 0 to 4 (same story for `reserved` cpu config). Additionally as per the same performance-addon-operators doc the union of `reserved` CPUs and `isolated` CPUs should include all online CPUs which this section of doc does not mention.

[0] - given example
> Apply the isolated and reserved CPUs in the PerformanceProfile YAML. For example, you could set logical cores CPU0 and CPU4 as isolated, and logical cores CPU1 and CPU5 as reserved. When you configure reserved and isolated CPUs, the infra containers in pods use the reserved CPUs and the application containers use the isolated CPUs.

[1] - yaml
```
  cpu:
    isolated: 0-4
    reserved: 1-5
```

**Comment by aireilly** [comment]
@vikram-redhat can you assign this one to me please
