### ISSUE TITLE
Duplicated text "You can also use the `oc set build-secret` command to set the secret on the..."

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-docs#3653]
The paragraph beginning "You can also use the `oc set build-secret` command to set the secret on the..." is duplicated:

https://github.com/openshift/openshift-docs/blame/enterprise-3.4/dev_guide/builds.adoc#L1027-L1044

looks ok in master, haven't checked other branches.

**Comment by adellape** [comment]
Fixed via https://github.com/openshift/openshift-docs/pull/3649.
