### ISSUE TITLE
[online] Issue in sidebar link for RHACS documentation

### ISSUE THREAD

**Issue by bostoys** [openshift/openshift-docs#36579]
### Which section(s) is the issue in?

In the sidebar, under the "Operating" section, there is a link for "Examining images for vulnabilities" which misspelled vulnerabilities. The URL itself is correct as well as the title of the page it links to. Only the sidebar link is misspelled.

**Comment by maxwelldb** [comment]
@gaurav-nelson Assigning based on history. Feel free to throw it back if I'm wrong!

**Comment by maxwelldb** [comment]
Fixed by #36635
