### ISSUE TITLE
[online] Issue in file architecture/acs-architecture.adoc

### ISSUE THREAD

**Issue by bostoys** [openshift/openshift-docs#36578]
### Which section(s) is the issue in?

In the "Sensor" subsection of the "Per-cluster components" section. 

### What needs fixing?

"Red Hat Advanced Cluster Security for Kubernetes uses the Sensor component to monitor Kubernetes and OpenShfit clusters" has a typo in "OpenShift".

**Comment by bostoys** [comment]
public URL for the page is https://docs.openshift.com/acs/architecture/acs-architecture.html

**Comment by maxwelldb** [comment]
@gaurav-nelson I think you last touched this one, going by history.

**Comment by maxwelldb** [comment]
Fixed by #36635
