### ISSUE TITLE
[online] Issue in file storage/persistent_storage/osd-persistent-storage-aws.adoc

### ISSUE THREAD

**Issue by sunsern-k** [openshift/openshift-docs#36638]
### Which section(s) is the issue in?

The introduction of this document mentioning AWS EFS.
However, there is the second sentence mentioning AWS **AFS** 

> This document describes the basic steps needed to set up your AWS account to prepare EFS to be used by Red Hat OpenShift Service on AWS. For more information about AWS **AFS**, see the AWS EFS documentation.

### What needs fixing?
I understood that it is a typo which should be AWS **EFS**.

**Comment by bergerhoffer** [comment]
Marking this as a good candidate for Hacktoberfest.

PR to fix this should be submitted against the `dedicated-4` branch, and ping me with any questions!

**Comment by bergerhoffer** [comment]
Closing as #36967 was merged!
