### ISSUE TITLE
[enterprise-4.7] Issue in file storage/persistent_storage/persistent-storage-iscsi.adoc

### ISSUE THREAD

**Issue by hupiper** [openshift/openshift-docs#36637]
### Which section(s) is the issue in?
Very first sentence on the page - You can provision your OpenShift Container Platform cluster with persistent storage using iSCSI. Some familiarity with Kubernetes and iSCSI is assumed.

### What needs fixing?
The word iSCSI is a link, the link is: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Storage_Administration_Guide/ch-iscsi.html

and that link is broken

**Comment by jboxman** [comment]
@hupiper thanks for reporting this!

**Comment by bergerhoffer** [comment]
This was recently fixed by @jboxman in https://github.com/openshift/openshift-docs/pull/36704. Closing!
