### ISSUE TITLE
[enterprise-4.8] Issue in file service_mesh/v2x/servicemesh-release-notes.adoc

### ISSUE THREAD

**Issue by theadisoni** [openshift/openshift-docs#36687]
### Which section(s) is the issue in?
Below  [1] having issues with referring to the version of TA[Technical Preview] for OVN-Kubernetes have included till v4.6 and v4.7 not anything about v4.8 as these docs of V4.8 then it must include info regarding that creating lots of confusion while referring them.

Let me know if you need more explanation about it.

[1] https://docs.openshift.com/container-platform/4.8/service_mesh/v2x/servicemesh-release-notes.html#ovn-kubernetes-technology-preview

### What needs fixing?
Docs missing information regarding the version of TA[Technical Preview] for OVN-Kubernetes have included till v4.6 and v4.7 not anything about v4.8 as these[[1]] docs of V4.8 so it's must be there.

**Comment by JStickler** [comment]
The OVN-Kubernetes interface is no longer Tech Preview in 4.8, it's GA and that is documented here
https://docs.openshift.com/container-platform/4.8/service_mesh/v2x/servicemesh-release-notes.html#ovn-kubernetes-container-network-interface-cni-generally-available 

What sort of confusion was that generating?
