### ISSUE TITLE
[OKD] Diagram refers to RHCOS instead of FCOS

### ISSUE THREAD

**Issue by brianinnes** [openshift/openshift-docs#36703]
### Which section(s) is the issue in?

The installation overview page : https://docs.okd.io/latest/installing/index.html

### What needs fixing?

Figure 2. Creating the bootstrap, control plane, and compute machines : shows the control plane nodes running on RHCOS instead of FCOS

/assign @mburke5678
/assign @dmueller2001

**Comment by mburke5678** [comment]
@brianinnes Any changes to the diagrams/images in the OpenShift docs need to be made by the graphics team. I am told that the OKD diagrams also need to be created/edited by the team. I put in a request to re-create the graphic with FCOS in place of RHCOS. Not sure how long the process takes. Thanks for point this one out!

**Comment by mburke5678** [comment]
@brianinnes PTAL: https://github.com/openshift/openshift-docs/pull/38627
