### ISSUE TITLE
[OSD 4] - https://github.com/openshift/openshift-docs/blob/dedicated-4/modules/ccs-aws-provisioned.adoc

### ISSUE THREAD

**Issue by sunsern-k** [openshift/openshift-docs#36778]
### Which section(s) is the issue in?
https://github.com/openshift/openshift-docs/blob/dedicated-4/modules/ccs-aws-provisioned.adoc
The VPC section mentions that "the VPC needs the following configurations:"

**Router tables: One router table per private subnet, and one additional table per cluster.**

### What needs fixing?
Should the "router table(s)" be the "route table(s)" per the resource name from the AWS official document: https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Route_Tables.html?

**Comment by bergerhoffer** [comment]
We'll get QE/SME to confirm, but I agree that it's probably "route table"

**Comment by bergerhoffer** [comment]
Marking this as a good candidate for Hacktoberfest.

PR to fix this should be submitted against the `dedicated-4` branch, and ping me with any questions!
