### ISSUE TITLE
Document kubernetes API (JSON/YAML)

### ISSUE THREAD

**Issue by cmoulliard** [openshift/openshift-docs#369]
To deploy a project on Openshift, it is required to design a YAML or JSON Kubernetes "template" file based on that API - https://godoc.org/github.com/GoogleCloudPlatform/kubernetes/pkg/api

As this is our responsibility to tell to our clients/end users how to create or generate such a file, that could be interesting that we develop a document explaining the different fields/tags, type, default value, if the field is optional or mandatory like a DTD or XSD file does file XML parsing/validation

**Comment by adellape** [comment]
The API docs are auto-generated and appear here:

Kubernetes API - https://docs.openshift.org/latest/rest_api/kubernetes_v1.html

OpenShift API - https://docs.openshift.org/latest/rest_api/openshift_v1.html

@cmoulliard Can you take a look and see if you have further requests for enhancement?

**Comment by adellape** [comment]
@cmoulliard Please reopen if you have any outstanding issues here.
