### ISSUE TITLE
Callouts should use normal callout syntax

### ISSUE THREAD

**Issue by bergerhoffer** [openshift/openshift-docs#36914]
### Which section(s) is the issue in?

Running tasks in pods using jobs: https://docs.openshift.com/container-platform/4.8/nodes/jobs/nodes-nodes-jobs.html#nodes-nodes-jobs-creating-cron_nodes-nodes-jobs

### What needs fixing?

The callouts below the code block use regular numbers to specify the text for each callout:

![image](https://user-images.githubusercontent.com/7443887/135311926-b12bf1e7-050f-44df-b8f6-b89f7026b437.png)

Instead, they should use the callout syntax, which looks like:

```
<1> The pod replicas a job should run in parallel.
<2> Successful pod completions are needed to mark a job completed.
...
```

This will render the numbers in a blue circle, like this:

![image](https://user-images.githubusercontent.com/7443887/135312377-a9de711b-a459-4074-a508-e0f783bf1d2b.png)

**Comment by bergerhoffer** [comment]
Marking this as a good candidate for Hacktoberfest.

PR to fix this should be submitted against the `main` branch, and ping me with any questions!

**Comment by jmakhack** [comment]
@bergerhoffer, I just opened a pull request for this issue: #36919.
Please let me know if anything else is required from my end.

**Comment by bergerhoffer** [comment]
@jmakhack that's great, thanks! I assigned this issue to you. Are you wanting this PR to count toward Hacktoberfest? Because I think that you might have to wait until Oct 1 to submit the PR before it will count toward that (if I understand the rules correctly). 

So if you want it to count, you might want to close that PR and open it again in 2 days :) The PR looks great though. Just let me know how you want to proceed!

**Comment by jmakhack** [comment]
@bergerhoffer Ah that's right. Looks like I went ahead of myself with the pull request. I closed the current one and will open a new one in two days.

**Comment by bergerhoffer** [comment]
@jmakhack Sounds good! I like the enthusiasm :)

**Comment by bergerhoffer** [comment]
Issue closed because PR has been merged!
