### ISSUE TITLE
Command and text are cut off in a note

### ISSUE THREAD

**Issue by bergerhoffer** [openshift/openshift-docs#36912]
### Which section(s) is the issue in?

"Creating cron jobs": https://docs.openshift.com/container-platform/4.8/nodes/jobs/nodes-nodes-jobs.html#nodes-nodes-jobs-creating-cron_nodes-nodes-jobs

### What needs fixing?

The note at the bottom of the page has a long command that is wider than the box and some of the words and command are cut off:

![image](https://user-images.githubusercontent.com/7443887/135310604-63d9aea1-f809-4f70-b4cc-3e79848fc98c.png)

This can probably be fixed by using "\\" to continue the command onto a second line, like:

```
$ oc create cronjob pi --image=perl --schedule='*/1 * * * *' \ 
-- perl -Mbignum=bpi -wle 'print bpi(2000)'
```

**Comment by bergerhoffer** [comment]
Marking this as a good candidate for Hacktoberfest.

PR to fix this should be submitted against the `main` branch, and ping me with any questions!

**Comment by jboxman** [comment]
@aireilly this might be a relatively easy CSS fix.

**Comment by aireilly** [comment]
@jboxman what are you thinking? like a scoll bar or something?

**Comment by jboxman** [comment]
@aireilly, yes, outside of these admonition boxes I think these do scroll. Not sure why the box breaks this behavior.

**Comment by aireilly** [comment]
Also, Hacktoberfest?! sign me up :)

**Comment by bergerhoffer** [comment]
@aireilly @jboxman Let us know if you think you'll pursue a CSS fix for this and/or if someone should fix this instance in the meantime.

**Comment by bergerhoffer** [comment]
Awesome thanks @gaurav-nelson! I don't know how to verify the PR though since the CSS isn't used in the preview. @jboxman can you help with that?
