### ISSUE TITLE
Missing source in code blocks in limit ranges

### ISSUE THREAD

**Issue by bergerhoffer** [openshift/openshift-docs#36918]
### Which section(s) is the issue in?

Restrict resource consumption with limit ranges: https://docs.openshift.com/container-platform/4.8/nodes/clusters/nodes-cluster-limit-ranges.html

### What needs fixing?

A few modules in this limit ranges assembly have code blocks that are missing the source specification. They need to have `[source,terminal]` added above the code block, like:

```
[source,terminal]
----
// command
----
```

- https://docs.openshift.com/container-platform/4.8/nodes/clusters/nodes-cluster-limit-ranges.html#nodes-cluster-limit-creating_nodes-cluster-limit-ranges, step 2 needs [source,terminal]
- https://docs.openshift.com/container-platform/4.8/nodes/clusters/nodes-cluster-limit-ranges.html#nodes-cluster-limit-viewing_nodes-cluster-limit-ranges, all 4 code blocks need [source,terminal]
- https://docs.openshift.com/container-platform/4.8/nodes/clusters/nodes-cluster-limit-ranges.html#nodes-cluster-limit-ranges-deleting_nodes-cluster-limit-ranges, code block needs [source,terminal]

**Comment by bergerhoffer** [comment]
Marking this as a good candidate for Hacktoberfest.

PR to fix this should be submitted against the `main` branch, and ping me with any questions!

**Comment by Annysah** [comment]
Hello @bergerhoffer, 
I would love to work on this issue.

**Comment by bergerhoffer** [comment]
@Annysah great thank you! I've assigned the issue to you. Let me know if you have any questions!

**Comment by mburke5678** [comment]
Fixed
