### ISSUE TITLE
Procedure formatting/numbering is off

### ISSUE THREAD

**Issue by bergerhoffer** [openshift/openshift-docs#36916]
### Which section(s) is the issue in?

Creating the frontend service: https://docs.openshift.com/container-platform/4.8/openshift_images/templates-using-ruby-on-rails.html#templates-rails-creating-frontend-service_templates-ruby-on-rails

### What needs fixing?

Something is off about this procedure, where step 3 is an "Example output", and then after that code block, the numbering resets to 1:

![image](https://user-images.githubusercontent.com/7443887/135313883-cd2aeedb-8765-4f6d-ac30-7ab0a9059f88.png)

I'm guessing that the example output heading there is currently `. Example output` (which marks it as a list), but instead there should be no space after the period, like `.Example output`, which would render it as a heading.

**Comment by bergerhoffer** [comment]
Marking this as a good candidate for Hacktoberfest.

PR to fix this should be submitted against the `main` branch, and ping me with any questions!

**Comment by eliseaston** [comment]
I would like to work on this if it's still available please

**Comment by bergerhoffer** [comment]
@eliseaston absolutely, thank you! You can tag me when you open the PR. Let me know if you have any questions!

**Comment by bergerhoffer** [comment]
Closing as the PR has been merged!
