### ISSUE TITLE
Add note that NFS storage is not recommended for metrics

### ISSUE THREAD

**Issue by mwringe** [openshift/openshift-docs#3692]
We have seen a few issues of people using NFS storage in their cluster and having metrics start to fail for them. This is due to the slow disk access when dealing with NFS.

We need to add a note to the docs to explain that when using NFS they made encounter problems due to the slow disk write speed associated with NFS

**Comment by mwringe** [comment]
@bmcelvee can you take a look at this? I would have opened a PR but https://github.com/openshift/openshift-docs/pull/3529 is already going to be bringing in a lot of changes.

**Comment by bmcelvee** [comment]
@mwringe, in PR#3869 I added a note recommending moving off NFS for production. Do you think that is sufficient in addressing that NFS storage is not recommended for metrics? If not, I can add more information on this subject.

Thanks!

**Comment by mwringe** [comment]
I think we would need something similar on the metrics, that PR is for the registry.

For metrics I would also add in an additional note that its because of performance reasons and that NFS may not be able to keep up when writing metrics.

**Comment by vikram-redhat** [comment]
This was covered via multiple updates recently. Closing.
