### ISSUE TITLE
[enterprise-4.8] Issue in file updating/update-using-custom-machine-config-pools.adoc

### ISSUE THREAD

**Issue by florianmoss** [openshift/openshift-docs#37072]
### Which section(s) is the issue in?
The first paragraph, the word 'scenario' is spelled wrong.

### What needs fixing?
FROM
"There might be some secenarios where you want a more controlled rollout"
TO
"There might be some scenarios where you want a more controlled rollout"

**Comment by bergerhoffer** [comment]
Thanks for noticing and reporting!

Marking this as a good candidate for Hacktoberfest.

If anyone wants to fix this typo, make the update against the `main` branch. And ping me with any questions!

**Comment by bergerhoffer** [comment]
PR has been merged, closing!
