### ISSUE TITLE
[online] Issue in file operating/examine-images-for-vulnerabilities.adoc

### ISSUE THREAD

**Issue by raffamendes** [openshift/openshift-docs#37125]
### Which section(s) is the issue in?
https://docs.openshift.com/acs/operating/examine-images-for-vulnerabilities.html#pereodic-scanning-of-images_examine-images-for-vulnerabilities

### What needs fixing?
Pereodic -> Periodic

**Comment by bergerhoffer** [comment]
Right, the branch to fix this in would be `rhacs-docs`. 

CCing @gaurav-nelson 

Also marking this as a good candidate for Hacktoberfest, in case any outside contributors want to take a stab at the fix.

**Comment by gaurav-nelson** [comment]
The issue was fixed by https://github.com/openshift/openshift-docs/pull/37904 the updated docs are at https://docs.openshift.com/acs/3.67/operating/examine-images-for-vulnerabilities.html#periodic-scanning-of-images_examine-images-for-vulnerabilities
