### ISSUE TITLE
Typo when referring to existing CAs

### ISSUE THREAD

**Issue by codyhoag** [openshift/openshift-docs#37164]
### Which section(s) is the issue in?

- https://docs.openshift.com/container-platform/4.8/installing/installing_aws/installing-restricted-networks-aws.html#installation-generate-aws-user-infra-install-config_installing-restricted-networks-aws
- https://docs.openshift.com/container-platform/4.8/installing/installing_ibm_z/installing-restricted-networks-ibm-z-kvm.html#installation-bare-metal-config-yaml_installing-restricted-networks-ibm-z-kvm

### What needs fixing?

There is a typo in the following phrase found in both aforementioned sections:

```
The value must be the contents of the certificate file that you used for your mirror
registry, which can be an exiting, trusted certificate authority or the self-signed certificate
that you generated for the mirror registry.
```
**Typo fix:**

`exiting` -> `existing`

**Comment by codyhoag** [comment]
This is marked for Hacktoberfest.

The PR to fix this should be submitted against the `main` branch. Feel free to reach out to me with any questions!

**Comment by poo17nam** [comment]
@codyhoag  Thank you! I've raised a PR with the fix.
https://github.com/openshift/openshift-docs/pull/37171
