### ISSUE TITLE
[enterprise 4.9] typo in egress router spec

### ISSUE THREAD

**Issue by martinkennelly** [openshift/openshift-docs#37180]
### Which section(s) is the issue in?
https://github.com/openshift/openshift-docs/blob/940059c583703d1f6e84f70ba507d4564c8499de/modules/nw-egress-router-cr.adoc

Within "Example egress router specification" spec:
```  mode: "bridge"```

### What needs fixing?
It should be "Bridge" instead of "bridge"
Otherwise you get error:

``The EgressRouter "er" is invalid: spec.networkInterface.macvlan.mode: Unsupported value: "bridge": supported values: "Bridge", "Private", "VEPA", "Passthru"``

@mikemckiernan This may occur back in old revisions.

**Comment by sbulage** [comment]
@bergerhoffer can this also be fixed .?

**Comment by bergerhoffer** [comment]
CC @JoeAldinger In https://docs.openshift.com/container-platform/4.9/networking/ovn_kubernetes_network_provider/deploying-egress-router-ovn-redirection.html#nw-egress-router-ovn-cr_deploying-egress-router-ovn-redirection

The instance of `mode: "bridge"` should be `mode: "Bridge"`. This will need QE review.

**Comment by JoeAldinger** [comment]
https://github.com/openshift/openshift-docs/pull/41534

**Comment by bergerhoffer** [comment]
PR #41534 has been merged. Closing this issue!
