### ISSUE TITLE
Some code samples are unreadable

### ISSUE THREAD

**Issue by jfmatth** [openshift/openshift-docs#3727]
This seems to have happened recently, look at this page [https://docs.openshift.com/container-platform/3.3/admin_guide/managing_projects.html](here), it's got the old format and a new format that i can't read well on my laptop.

thoughts

**Comment by larkly** [comment]
It seems to be due to CSS related to code snippets with [source,bash] (not confirmed if this is exclusive to bash - issue may be a factor with other kinds of code snippets as well)

**Comment by php-coder** [comment]
At least yaml sources are affected:
![docs-bug](https://cloud.githubusercontent.com/assets/87088/22887858/e25edef2-f203-11e6-835a-06e2526a5d50.png)

**Comment by larkly** [comment]
Issue may be related to commit d10e2de719d333cd5c83f0dd628efbeea2a1ab72, as that is the only change on CSS in a while.

**Comment by adellape** [comment]
This has been fixed via https://github.com/openshift/openshift-docs/pull/3731:

https://docs.openshift.com/container-platform/3.3/admin_guide/managing_projects.html#limit-projects-per-user

![screenshot from 2017-02-13 13-08-06](https://cloud.githubusercontent.com/assets/3442316/22896277/7cf129b4-f1ed-11e6-9620-7b77919f92c6.png)
