### ISSUE TITLE
issue in hardware_enablement psap-special-resource-operator.html for ocp 4.9

### ISSUE THREAD

**Issue by liqcui** [openshift/openshift-docs#37292]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.9/hardware_enablement/psap-special-resource-operator.html

### What needs fixing?
The issue have in the following section
Installing the Special Resource Operator by using the CLI

Change:
Create the following Subscription CR and save the YAML in the sro-sub.yaml file:
Example Subscription CR

**apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: special-resource-operator
  namespace: openshift-special-resource-operator
spec:
  channel: "4.9" 
  installPlanApproval: Automatic
  name: special-resource-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace**

To:
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-special-resource-operator
  namespace: openshift-special-resource-operator
spec:
  channel: "4.9" 
  installPlanApproval: Automatic
  name: openshift-special-resource-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace

in the section:
Save the following YAML template for the RBAC resources and daemon set in the templates directory as 1000-driver-container.yaml:

Change:
  **annotations:
    specialresource.openshift.io/wait: "true"
    specialresource.openshift.io/state: "driver-container"
    specialresource.openshift.io/driver-container-vendor: simple-kmod
    specialresource.openshift.io/kernel-affine: "true"**

To:
  annotations:
    specialresource.openshift.io/wait: "true"
    specialresource.openshift.io/state: "driver-container"
    specialresource.openshift.io/driver-container-vendor: simple-kmod
    specialresource.openshift.io/kernel-affine: "true"
    specialresource.openshift.io/from-configmap: "true"

**Comment by kmccarron-rh** [comment]
Doc changes have been merged in  https://github.com/openshift/openshift-docs/pull/38265.
This PR can be closed.

**Comment by kmccarron-rh** [comment]
Hi @liqcui ! This PR can be closed, the  issue was fixed in PR  #38265 as described above.
