### ISSUE TITLE
[online] Broken link in resources section of Installing OpenShift Pipelines

### ISSUE THREAD

**Issue by Javatar81** [openshift/openshift-docs#37426]
### Which section(s) is the issue in?
In the online docs of OCP 4.7 and 4.8. Section: [Installing OpenShift Pipelines](https://docs.openshift.com/container-platform/4.7/cicd/pipelines/installing-pipelines.html#additional-resources)

### What needs fixing?

Link to Mirroring images to run pipelines in a restricted environment is broken. 

This is the broken link: https://docs.openshift.com/container-platform/4.7/creating-applications-with-cicd-pipelines.html#op-mirroring-images-to-run-pipelines-in-restricted-environment_creating-applications-with-cicd-pipelines

The contents can be found in the enterprise docs: https://access.redhat.com/documentation/en-us/openshift_container_platform/4.7/html/cicd/pipelines#op-mirroring-images-to-run-pipelines-in-restricted-environment_creating-applications-with-cicd-pipelines

**Comment by sounix000** [comment]
Created JIRA https://issues.redhat.com/browse/RHDEVDOCS-3787 to address this issue.
