### ISSUE TITLE
[enterprise-4.8] Issue in file machine_management/applying-autoscaling.adoc

### ISSUE THREAD

**Issue by TiloGit** [openshift/openshift-docs#37505]
### Which section(s) is the issue in?
ClusterAutoscaler resource definition
https://docs.openshift.com/container-platform/4.8/machine_management/applying-autoscaling.html#cluster-autoscaler-cr_applying-autoscaling

### What needs fixing?
Please clarify if 3-6. Is for worker nodes only or also include control plane (like maxNodesTotal)

<html><body>

  | Specify the minimum number of cores to deploy in the cluster.
-- | --
  | Specify the maximum number of cores to deploy in the cluster.
  | Specify the minimum amount of memory, in GiB, in the cluster.
  | Specify the maximum amount of memory, in GiB, in the cluster.

</body>
</html>

**Comment by mburke5678** [comment]
@elmiko @TiloGit When you say these limits include the master nodes, does that mean that the limits are also applied to the master nodes, or the total of the resources is also spread across the master nodes?

**Comment by elmiko** [comment]
@mburke5678 when the cluster autoscaler looks at the total memory/cpu/gpu in the cluster, it does not differentiate between the type of nodes. so if a user sets the maximum memory resource limit, the autoscaler will include all nodes in the cluster when calculating the current memory usage, and then it will use that calculation to determine if it has the capacity to add more resources.

for example, user sets the maximum cpu limit to 64 cores. when the cluster starts it has 30 cores (for the sake of argument), if the autoscaler is configured to only create machines that have 8 cores each, then it can effectively add 4 more nodes. 

these limits are not single machine oriented, they are an aggregation of all the resources used in the entire cluster. even if the autoscaler is not managing those nodes, it will still count their resources towards the total limit.

hope that helps =)

**Comment by mburke5678** [comment]
@elmiko @TiloGit Can you take a look at my PR? I added [elmiko's words](https://github.com/openshift/openshift-docs/issues/37505#issuecomment-966492645) and _on the worker and control plane nodes_ to the call out definitions 3-6.
As in: _Specify the minimum number of cores to deploy **on the worker and control plane nodes** in the cluster._

**Comment by mburke5678** [comment]
@elmiko Thank you for reminding me. 

> even if the autoscaler is not managing those nodes 

Which type(s) of nodes are not managed by the cluster autoscaler? You mention in the PR that it doesn't manage the control plane nodes. Does it manage workers and infra?

**Comment by elmiko** [comment]
the autoscaler operates in openshift by utilizing machinesets. a user must specify which machinesets will be used by the autoscaler for its scaling activity. each machineset can have a minimum and maximum number of machines that can be created.

by default, when the cluster is first installed, there are no machinesets participating in autoscaling. at this point a user would specify which machinesets should be autoscaled, and what the machine limits should be. (note these are limits on the number of machines, not the resources limits on the cluster).

our control plane nodes do not belong to a machineset, and cannot be included in any autoscaling activity. and this is where the confusion enters, imo, those resource limits (cpu/mem/gpu) are cluster-wide, they include all the nodes in the cluster, but the autoscaler may not be watching all the nodes for scaling. it could potentially scale workers and infra nodes, if the user has setup machinesets to cover those nodes.

sorry for being long-winded here, i know this is a nuanced topic. happy to clarify further.

**Comment by mburke5678** [comment]
PR is merged. Closing
