### ISSUE TITLE
[enterprise-4.9] Typo in OVN egress firewall example

### ISSUE THREAD

**Issue by jwennerberg** [openshift/openshift-docs#37670]
### Which section(s) is the issue in?

Issue in file networking/ovn_kubernetes_network_provider/configuring-egress-firewall-ovn.adoc
"How an egress firewall works in a project"

### What needs fixing?

Typo in first example in the "Important" block:

```
- deny:
    cidrSelector: 0.0.0.0/0 
  type: Deny
```
 should be changed to:
```
- to:
    cidrSelector: 0.0.0.0/0 
  type: Deny
```

Needs fixing in `4.6`, `4.7`, `4.8` and `4.9` branches.

**Comment by jboxman** [comment]
cc @huiran0826 does this look good? Thanks!
