### ISSUE TITLE
[enterprise-4.8] Issue in file backup_and_restore/backing-up-etcd.adoc

### ISSUE THREAD

**Issue by lgchiaretto** [openshift/openshift-docs#37696]
### Which section(s) is the issue in?

Backing up etcd

### What needs fixing?

In this section, there's a reference to an Openshift 4.7.2 and it may be to an Openshift 4.8.z. 

Be sure to take an etcd backup after you upgrade your cluster. This is important because when you restore your cluster, you must use an etcd backup that was taken from the same z-stream release. For example, an OpenShift Container Platform **4.7.2** cluster must use an etcd backup that was taken from **4.7.2**

**Comment by tmalove** [comment]
Will do @bergerhoffer.

**Comment by lgchiaretto** [comment]
@tmalove Why don't you use 4.y.z?
