### ISSUE TITLE
[enterprise-3.11] Issue in file admin_guide/out_of_resource_handling.adoc

### ISSUE THREAD

**Issue by bshirren** [openshift/openshift-docs#37740]
### Which section(s) is the issue in?

"Controlling Node Condition Oscillation" [1]

### What needs fixing?

Syntax error in "kubeletArguments" example:

~~~
kubeletArguments:
  eviction-pressure-transition-period="5m"
~~~

Above does not apply at all due incorrect syntax. Per other examples in document the correct syntax is:

~~~
kubeletArguments:
  eviction-pressure-transition-period:
  - 5m
~~~

[1] https://docs.openshift.com/container-platform/3.11/admin_guide/out_of_resource_handling.html#out-of-resource-oscillation-of-node-conditions

**Comment by mburke5678** [comment]
PR is merged. Closing.
