### ISSUE TITLE
f5 native integration architecture should be a different document.

### ISSUE THREAD

**Issue by juanluisvaladas** [openshift/openshift-docs#3775]
Hi,
The F5 integration details should be in a separate document for the following reasons:
1- It's not a core component
2- It's not a logical place to look for it. If I want information about the F5 integration I'd look for it in a place having F5 in the title.
3- Talks more about SDN than actual routing. Therefore barely related to the scope of the document.

I think the document should be either on the f5 router document before talking about the integration or in a separate document in the architecture section.

**Comment by bfallonf** [comment]
@juanluisvaladas Sorry, I'm not too sure which section you're talking about. F5 information is in multiple places. There is the "Using the F5 Router Plug-in" file which I think is what you're asking for: https://docs.openshift.com/container-platform/latest/install_config/router/f5_router.html

It's separate from the other router docs.

Can you please add some more information? Perhaps a link to the places you think need to be adjusted? Then we can take a closer look. Thanks.

**Comment by juanluisvaladas** [comment]
Hi @bfallonf I'm talking about the F5 architecture documentation: https://docs.openshift.com/container-platform/latest/architecture/core_concepts/routes.html#f5-router

I agree it makes sense for it to be in the architecture but I think it doesn't make sense for it to be in the core concepts section since it's not core but a plugin. It would make more sense in the Additional Concepts section in a new document called something like F5 BIG IP Router Plugin

**Comment by bfallonf** [comment]
@juanluisvaladas Ah, I see what you mean now.

I've reported this BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1437738

There's plans to organise the Architecture section, and I can include this BZ to those efforts. Hopefully they will be active by the next release.

Thanks, and I'll close this issue.
