### ISSUE TITLE
Add redirects for backward compatible urls

### ISSUE THREAD

**Issue by php-coder** [openshift/openshift-docs#3783]
I noticed that documentation was refactored and long pages were split by smaller ones. After such change I see that at least one link gets broken: https://docs.openshift.org/latest/dev_guide/deployments.html

Is it possible to add redirects for this (and probably other) pages? Having working URLs is good for users who may have them bookmarked, for blogs/answers on StackOverflow, and also for CEO.

**Comment by bfallonf** [comment]
Hmm we usually cover this. Thanks @php-coder .

@vikram-redhat can you verify this and set up the redirects if need be?

**Comment by vikram-redhat** [comment]
Hmm - sorry for the delay. Yes, we do normally cover this. Looks like we may have missed a redirect here. @adellape - thought we had set these up when we broke the deployments guide?

**Comment by adellape** [comment]
Oof, looks like we did it for everything but Origin. :| Emailing.

**Comment by vikram-redhat** [comment]
Thanks @adellape. I am going to close this issue.

**Comment by adellape** [comment]
This is done:

https://docs.openshift.org/latest/dev_guide/deployments.html
