### ISSUE TITLE
[enterprise-4.8] Issue in file virt/live_migration/virt-live-migration.adoc

### ISSUE THREAD

**Issue by kobi86** [openshift/openshift-docs#37844]
### Which section(s) is the issue in?
Understanding live migration

### What needs fixing?
The section ```Virtual machines must have a persistent volume claim (PVC) with a shared ReadWriteMany (RWX) access mode to be live migrated.```
Needs to be highlighted like in docs for 4.5 

** 
The lest part in the Note section: ```This might degrade its security.```
Cant be That hidden, its can stay in the Note section but with aside from the explanation

**Comment by apinnick** [comment]
@ctomasko  Has this issue been reviewed?

**Comment by ctomasko** [comment]
https://issues.redhat.com/browse/CNV-17973

**Comment by apinnick** [comment]
The note about security refers to the SR-IOV feature gate, so it has to remain there. In 4.10, the SR-IOV feature gate is no longer required, so the note does not appear.
