### ISSUE TITLE
[enterprise-4.8] Issue in file web_console/odc-about-web-terminal.adoc

### ISSUE THREAD

**Issue by germanparente** [openshift/openshift-docs#37845]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.8/web_console/odc-about-web-terminal.html#removing-the-web-terminal-operator-and-the-custom-resources-that-support-it

### What needs fixing?

we see some differences than in:

 https://github.com/devfile/devworkspace-operator/blob/main/doc/uninstall.md 

More precisely, we are missing in the official doc:

"oc delete customresourcedefinitions.apiextensions.k8s.io devworkspacetemplates.workspace.devfile.io"

also, this command:

oc delete all --selector app.kubernetes.io/part-of=devworkspace-operator,app.kubernetes.io/name=devworkspace-webhook-server

should include "-n openshift-operators"

**Comment by amisevsk** [comment]
Issue can be closed as https://github.com/openshift/openshift-docs/pull/39532 is merged

**Comment by ahardin-rh** [comment]
Thank you!
