### ISSUE TITLE
Backup-Restore documentation is wrong

### ISSUE THREAD

**Issue by sttts** [openshift/openshift-docs#3793]
Compare https://github.com/openshift/openshift-docs/pull/3047/files#r102164443. Following the docs the restore will fail with invalid cluster-ids on the second and third node.

**Comment by bfallonf** [comment]
@sttts I can see you've commented on a BZ about this already, so I'll close this issue:

https://bugzilla.redhat.com/show_bug.cgi?id=1419670
https://bugzilla.redhat.com/show_bug.cgi?id=1421072
