### ISSUE TITLE
[enterprise-4.9] Issue in file installing/installing_azure/installing-azure-user-infra.adoc

### ISSUE THREAD

**Issue by thomasphall** [openshift/openshift-docs#37980]
### Which section(s) is the issue in?
OpenShift Azure documentation does not include supported machine types like AWS. Example: https://docs.openshift.com/container-platform/4.9/installing/installing_aws/installing-aws-customizations.html#installation-supported-aws-machine-types_installing-aws-customizations

### What needs fixing?
Additional section containing Azure supported machine types needs to be included

**Comment by codyhoag** [comment]
We are working with Engineering to get an Azure list out for supported machine types. This should be available soon.
