### ISSUE TITLE
[enterprise-4.9] Issue in file networking/openshift_sdn/configuring-egress-firewall.adoc

### ISSUE THREAD

**Issue by stefaneri** [openshift/openshift-docs#38114]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.9/networking/openshift_sdn/configuring-egress-firewall.html#nw-egressnetworkpolicy-about_openshift-sdn-egress-firewall
Red box labeled IMPORTANT

### What needs fixing?
The manifest points to k8s.ovn.org/v1. It should probably be network.openshift.io/v1 as this is in the openshift SDN section.

**Comment by jboxman-rh** [comment]
@stefaneri, thanks for reporting this!
