### ISSUE TITLE
[enterprise-4.8] Issue in file authentication/understanding-identity-provider.adoc

### ISSUE THREAD

**Issue by jamessevener** [openshift/openshift-docs#38141]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.8/authentication/understanding-identity-provider.html#identity-provider-parameters_understanding-identity-provider
Mapping methods claim that add, generate, claim, and lookup are all supported, but the oauth config rejects generate.

### What needs fixing?
Error "Unsupported value: "generate": supported values: "add", "claim", "lookup"" for field "spec.identityProviders[0].mappingMethod".

**Comment by bergerhoffer** [comment]
Closing, as #68395 has merged to address this. Thanks!
