### ISSUE TITLE
[enterprise-4.9] Issue in file cli_reference/openshift_cli/developer-cli-commands.adoc

### ISSUE THREAD

**Issue by ChetRHosey** [openshift/openshift-docs#38217]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.9/cli_reference/openshift_cli/developer-cli-commands.html#oc-secrets-link

### What needs fixing?

There's a reference to `limitSecretReferences`. This was a setting in 3.x but was removed from 3.11 and 4.x (see https://access.redhat.com/solutions/4124711 for reference).

The documentation for `oc secrets link` should be updated to remove the reference.

**Comment by jboxman-rh** [comment]
cc @bergerhoffer

**Comment by bergerhoffer** [comment]
The CLI reference docs are automatically generated from the code, so we'll need to make the change there.

@soltysh I'm happy to submit the PR (looks to be in the oc repo luckily) to update this example description, but I'll need help with what to change it to. Suggestions?

**Comment by bergerhoffer** [comment]
Closing - the above PR merged, and this example has been removed for 4.10: https://docs.openshift.com/container-platform/4.10/cli_reference/openshift_cli/developer-cli-commands.html#oc-secrets-link
