### ISSUE TITLE
[enterprise-4.8] Issue in file rest_api/operatorhub_apis/clusterserviceversion-operators-coreos-com-v1alpha1.adoc

### ISSUE THREAD

**Issue by TheRealJon** [openshift/openshift-docs#38233]
### Which section(s) is the issue in?

The documentation for the following API properties should be more descriptive:

- `.spec.customresourcedefinitions.owned[].resources`
- `.spec.customresourcedefinitions.required[].resources`
- `.spec.apiservicedefinitions.owned[].resources`
- `.spec.apiservicedefinitions.required[].resources`

### What needs fixing?
The `resources` property referenced in the above APIs is an array of resource references that are used in the console UI to list related operand resources. There has been recent confusion about the usage of this API and improving the docs could alleviate future bugs. Each item in the `resources` array is an object with 3 properties:

- `name`: If the resource references a CRD, this property should be the `metadata.name` of the CRD, otherwise it should be an empty string.
- `kind`: string value representing the REST resource this object represents
- `version`: the versioned schema of this representation of an object

**Comment by jboxman-rh** [comment]
@TheRealJon, so these are pulled from the OpenAPI spec and would need to be fixed elsewhere.

cc @adellape
