### ISSUE TITLE
[enterprise-4.8] Issue in file monitoring/configuring-the-monitoring-stack.adoc

### ISSUE THREAD

**Issue by adityad97** [openshift/openshift-docs#38275]
### Which section(s) is the issue in?
Persistent storage prerequisites
https://docs.openshift.com/container-platform/4.8/monitoring/configuring-the-monitoring-stack.html#persistent-storage-prerequisites

### What needs fixing?
4th point where Note is mentioned. In the note, it is mentioned that Elasticsearch cannot use raw block volumes.
The documentation is for Monitoring where we have to configure storage for Prometheus and Alertmanager.
This should be replaced with proper words or according to the comments from Monitoring component's Engineering team.

**Comment by stevsmit** [comment]
PR at https://github.com/openshift/openshift-docs/pull/38354
