### ISSUE TITLE
[enterprise-4.9] Issue in file scalability_and_performance/recommended-host-practices.adoc

### ISSUE THREAD

**Issue by kgibm** [openshift/openshift-docs#38286]
### Which section(s) is the issue in?

<https://docs.openshift.com/container-platform/latest/scalability_and_performance/recommended-host-practices.html#master-node-sizing_>

### What needs fixing?

> To avoid cascading failures, keep the overall resource usage on the control plane nodes to at most half of all available capacity to handle the resource usage spikes. Increase the CPU and memory on the control plane nodes accordingly to avoid potential downtime due to lack of resources.

I think the second sentence implies the answer is yes; but, to confirm, does "keep the overall resource usage on the control plane nodes" refer to both CPU and memory, or just CPU?

**Comment by mburke5678** [comment]
@chaitanyaenr It appears [you added this paragraph to the docs](https://github.com/openshift/openshift-docs/pull/32230/files#diff-20cc7311e3ca9ba07f50068dd946123b147a3b421bb8e7e7914c06ba757cf8d1R29). Can you help answer @kgibm question? I think he is correct, as we uses _resoruces_ to mean both memory and CPU.

**Comment by chaitanyaenr** [comment]
> @chaitanyaenr It appears [you added this paragraph to the docs](https://github.com/openshift/openshift-docs/pull/32230/files#diff-20cc7311e3ca9ba07f50068dd946123b147a3b421bb8e7e7914c06ba757cf8d1R29). Can you help answer @kgibm question? I think he is correct, as we uses _resoruces_ to mean both memory and CPU.

@mburke5678 Right, it means both CPU and Memory. Thanks.

**Comment by kgibm** [comment]
Created PR: https://github.com/openshift/openshift-docs/pull/38740

**Comment by mburke5678** [comment]
PR is merged. Closing. Thank you @kgibm for this clarification!
