### ISSUE TITLE
[enterprise-4.9] Issue in file monitoring/configuring-the-monitoring-stack.adoc

### ISSUE THREAD

**Issue by jan--f** [openshift/openshift-docs#38321]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.9/monitoring/configuring-the-monitoring-stack.html#persistent-storage-prerequisites

### What needs fixing?

The `Note` box mentions: "Elasticsearch cannot use raw block volumes." Should read "Prometheus cannot use raw block volumes."

**Comment by stevsmit** [comment]
PR submitted
