### ISSUE TITLE
Change get packagemanifest command for SRO

### ISSUE THREAD

**Issue by liqcui** [openshift/openshift-docs#38413]
https://docs.openshift.com/container-platform/4.9/hardware_enablement/psap-special-resource-operator.html

### Which section(s) is the issue in?

Installing the Special Resource Operator by using the CLI
2. Install the SRO in the namespace you created in the previous step:
c. Run the following oc get command to get the channel value required for the next step:

Change:
oc get packagemanifest special-resource-operator -n openshift-marketplace -o jsonpath='{.status.defaultChannel}'

To:
oc get packagemanifest openshift-special-resource-operator -n openshift-marketplace -o jsonpath='{.status.defaultChannel}'

**Comment by kmccarron-rh** [comment]
This issue can be closed.
The change is now live here: https://docs.openshift.com/container-platform/4.9/hardware_enablement/psap-special-resource-operator.html#installing-the-special-resource-operator-using-cli_special-resource-operator
