### ISSUE TITLE
It's not clear for what is using 7001 port

### ISSUE THREAD

**Issue by php-coder** [openshift/openshift-docs#3847]
I thought that all using ports are described in the ["Required Ports" chapter](https://docs.openshift.org/latest/install_config/install/prerequisites.html#required-ports) but later I found [this](https://docs.openshift.org/latest/getting_started/administrators.html#running-in-a-docker-container):

> OpenShift Origin listens on ports 53, 7001, and 8443.

I didn't found for what 7001 port is using. I believe that documentation should mention about it.

**Comment by php-coder** [comment]
Looks like this port was used by etcd some time ago:

> The official etcd ports are 2379 for client requests, and 2380 for peer communication. Some legacy code and documentation still references ports 4001 and 7001, but all new etcd use and discussion should adopt the assigned ports.

Source: https://coreos.com/etcd/docs/latest/v2/configuration.html

**Comment by bfallonf** [comment]
Thanks @php-coder . @jcantrill from the file history, I can see you've worked on some of the port stuff. Is the above accurate? Would it be an easy fix and just get rid of where it mentions 7001?

**Comment by jcantrill** [comment]
@bfallonf I know nothing about that port

**Comment by bfallonf** [comment]
Ok. If it's not important, and seems outdated, then I guess the reference to the port should go.

I created #4059 . I'll close this PR. Thanks, all.
