### ISSUE TITLE
Document logoutURL

### ISSUE THREAD

**Issue by liggitt** [openshift/openshift-docs#385]
When using requestheader and oauth/openid providers, it is often desired to specify an external logout url to direct users to on logout to destroy their SSO sessions.

This option is located in the master config file:
```
assetConfig:
  logoutURL: "..."
```

If specified, the web console will direct the user to the logoutURL on logout.

**Comment by bfallonf** [comment]
@liggitt See #1068 for the PR on adding this to the docs.

Can I get an ack everything is included here?

Thanks!
