### ISSUE TITLE
[docs.openshift look and feel] - use a standard UX interaction metaphor for small screen navigation

### ISSUE THREAD

**Issue by aireilly** [openshift/openshift-docs#38512]
### What needs fixing?

Currently, there is a small hamburger nav menu which is not intuitive for users when browsing on smaller screens. 

### Suggested update

Create a sticky secondary nav bar for small screens only which contains search and hamburger nav buttons. On page scroll, the secondary nav should take over from the primary nav.  Illustrative example below: 
![image](https://user-images.githubusercontent.com/74046732/141086742-5c2a6f2a-a036-4262-bbae-a9d0cd57c1b6.png)

⬇️⬇️⬇️

![image](https://user-images.githubusercontent.com/74046732/141086826-65e7e353-3aef-41fc-b324-2520dc9fda24.png)

**Comment by aireilly** [comment]
@vikram-redhat @jboxman we could add a search icon beside the existing new icons, and make this nav sticky. On a small screens, the hamburger would appear on the right of this sticky nav.

**Comment by vikram-redhat** [comment]
@aireilly that works for me, but we don't have search in mobile hooked up yet (so we could leave that space empty for now?). See the separate discussion around that.

**Comment by aireilly** [comment]
> @aireilly that works for me, but we don't have search in mobile hooked up yet (so we could leave that space empty for now?). See the separate discussion around that.

Yes. We could just hide the search on small screens.

**Comment by gaurav-nelson** [comment]
How does the following look, instead of the breadcrumb we show this secondary navbar on small screens.
- I also tried the navbar without the issue buttons but it looked empty. 

Any other suggestions?

https://user-images.githubusercontent.com/23069445/142606258-1ac6bf3a-a68a-4bea-bb11-dacef05b14ba.mov

**Comment by aireilly** [comment]
Yeah this is exactly what we need.

**Comment by aireilly** [comment]
What about the search also in the new nav bar?

**Comment by vikram-redhat** [comment]
Love it.

Might need to think about how we would incorporate search and the text itself (OpenShift Documentation seems repetitive), but minor quibbles. 

When you have a chance, ping it in the team-docs channel.

**Comment by gaurav-nelson** [comment]
Here is another option with the search bar. I tried placing other buttons too, but then the bar looks too crowded.

https://user-images.githubusercontent.com/23069445/142757742-e01b139b-3083-41a2-9b7b-a99fb53c0fe3.mov

https://user-images.githubusercontent.com/23069445/142757744-cad28679-ff62-4207-8d34-91d0fa79f492.mov

**Comment by aireilly** [comment]
Looks good to me, I guess next step would be to solicit some feedback from team docs. BTW, I spent some time cleaning up the viewport breakpoints a bit. Would that PR interfere with this work?
