### ISSUE TITLE
[enterprise-4.9] Issue in file updating/updating-cluster-rhel-compute.adoc

### ISSUE THREAD

**Issue by asadawar** [openshift/openshift-docs#38558]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.9/updating/updating-cluster-rhel-compute.html#rhel-compute-updating-minor_updating-cluster-rhel-compute

### What needs fixing?
- We started supporting RHEL 8 as a compute node from OCP 4.9: https://docs.openshift.com/container-platform/4.9/release_notes/ocp-4-9-release-notes.html#ocp-4-9-machine-api-rhel8 
- However, the current docs say that only RHEL 7 nodes are supported. 
- Also, the steps to enable RHEL 8 repos on the RHEL 8 compute node are also missing from the "[Updating RHEL compute machines in your cluster](https://docs.openshift.com/container-platform/4.9/updating/updating-cluster-rhel-compute.html#rhel-compute-updating-minor_updating-cluster-rhel-compute)" section.

**Comment by jboxman-rh** [comment]
cc @stevsmit
