### ISSUE TITLE
Advanced installation: document deployment_type parameter

### ISSUE THREAD

**Issue by php-coder** [openshift/openshift-docs#3861]
[Advanced installation guide](https://docs.openshift.org/latest/install_config/install/advanced_install.html) is using `deployment_type` parameter in its examples but it doesn't documented: what it does? what is the possible values?

Also note that it is going to be deprecated soon (comment from [`roles/openshift_facts/tasks/main.yml`](https://github.com/openshift/openshift-ansible/blob/68aa6f269a6b0c4bf9af5f30d0dfb5ac6428b575/roles/openshift_facts/tasks/main.yml#L39-L40)):
```python
      # TODO: Deprecate deployment_type in favor of openshift_deployment_type
      deployment_type: "{{ openshift_deployment_type | default(deployment_type) }}"
```

**Comment by php-coder** [comment]
I've just found this useful link: https://github.com/openshift/openshift-ansible/blob/master/DEPLOYMENT_TYPES.md

**Comment by bfallonf** [comment]
Thanks @php-coder I've reported a BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1437317

If there's any more information, please add it there. I'll close this issue.

**Comment by php-coder** [comment]
https://github.com/openshift/openshift-docs/pull/4208
