### ISSUE TITLE
Preparing for Advanced Installations: Python3 is required on Fedora

### ISSUE THREAD

**Issue by php-coder** [openshift/openshift-docs#3862]
[Preparing for Advanced Installations](https://docs.openshift.org/latest/install_config/install/host_preparation.html#preparing-for-advanced-installations-origin) chapter is missing **important** point for Fedora users: Python 3 is required to be installed on the host where we're running Ansible (see https://github.com/openshift/openshift-ansible/issues/3543)

**Comment by bfallonf** [comment]
I'm wondering if we should be documenting this actually. The docs state pretty clearly that OpenShift must be installed on RHEL, so I'm wondering if Fedora installs are supported. @sferich888 @vikram-redhat @aheslin Can anyone attest to this?

**Comment by php-coder** [comment]
> The docs state pretty clearly that OpenShift must be installed on RHEL

There are a lot of places that claim that Fedora is also supported. For example:

https://docs.openshift.org/latest/install_config/install/advanced_install.html#overview
https://docs.openshift.org/latest/install_config/install/prerequisites.html#hardware
https://docs.openshift.org/latest/getting_started/administrators.html#running-in-a-docker-container
https://docs.openshift.org/latest/install_config/install/host_preparation.html#what-s-next

**Comment by vikram-redhat** [comment]
This is for upstream docs. I someone wants to submit a PR to fix, we can merge.
