### ISSUE TITLE
[enterprise-4.9] Issue in file virt/install/uninstalling-virt-web.adoc

### ISSUE THREAD

**Issue by aglitke** [openshift/openshift-docs#38626]
### Which section(s) is the issue in?
Deleting the OpenShift Virtualization Operator Deployment custom resource

### What needs fixing?
In step 8 we are asked to run the following command:
oc delete apiservices v1alpha3.subresources.kubevirt.io -n openshift-cnv

This results in the following error:
warning: deleting cluster-scoped resources, not scoped to the provided namespace
Error from server (NotFound): apiservices.apiregistration.k8s.io "v1alpha3.subresources.kubevirt.io" not found

**Comment by bgaydosrh** [comment]
Hi @aglitke -

What should we do in this case? is deleting Step 8 enough? Should we replaceStep 8 with another step or include other explanatory verbiage?

Once I know this, I can submit the final PR that rolls all changes in summarized by [CNV-14999](https://issues.redhat.com/browse/CNV-14999)

Thanks
Bob

**Comment by aglitke** [comment]
@tiraboschi Do you know the correct answer here?  Unfortunately I no longer have an environment set up to check what it should be.

**Comment by apinnick** [comment]
@aglitke @bgaydosrh 
Is it possible that the problem is a typo? I think the correct command is `oc delete apiservice v1alpha3.subresources.kubevirt.io -n openshift-cnv` (remove the 's' from apiservices).

**Comment by bgaydosrh** [comment]
Thanks @apinnick - Looking at https://cloud.redhat.com/blog/the-hidden-dangers-of-terminating-namespaces --  I am not sure. Would @awels know?

Bob

**Comment by awels** [comment]
`Error from server (NotFound): apiservices.apiregistration.k8s.io "v1alpha3.subresources.kubevirt.io" not found` appears to be the problem, it is highly likely that version no longer exists.

**Comment by bgaydosrh** [comment]
Thanks @awels - Can I simply substitute a variable like _version_ for `v1alpha3`?

**Comment by awels** [comment]
No we need a specific version that gets shipped with 4.9. I don't know which one of the top of my head.

**Comment by tiraboschi** [comment]
on a 4.9.3 I still see:
```
$ oc get apiservices | grep subresources.kubevirt.io
v1.subresources.kubevirt.io                          openshift-cnv/virt-api                                       True        183d
v1alpha3.subresources.kubevirt.io                    openshift-cnv/virt-api                                       True        651d
```

**Comment by bgaydosrh** [comment]
Hi @aglitke -

Chatted a bit with @tiraboschi - It seems the version is valid, but maybe the user is not supposed to attempt the delete? He said that `virt-operator `should be doing the delete.....
Let me know what you think.

**Comment by aglitke** [comment]
As I recall this was all a workaround.  If deleting CNV has been fixed so as to require no extra steps then I think much of this section can be removed.
