### ISSUE TITLE
[enterprise-4.9] Issue in file machine_management/adding-rhel-compute.adoc

### ISSUE THREAD

**Issue by ryandevlin-redhat** [openshift/openshift-docs#38678]
### Which section(s) is the issue in?
[Preparing the machine to run the playbook](https://docs.openshift.com/container-platform/4.9/machine_management/adding-rhel-compute.html#rhel-preparing-playbook-machine_adding-rhel-compute)

### What needs fixing?
This section launches into an explanation about preparing a RHEL machine to run "the playbook". There is not introduction as to what this playbook is, what it does, or why we need it.

There needs to be one or two sentences added describing why we are doing this. For example:

"In order to add a RHEL node to an OpenShift cluster, one needs a RHEL7 machine with network connectivity to the cluster and the new cluster node. This machine will be used to run an Ansible playbook which will automatically add the new node to the cluster."

**Comment by mburke5678** [comment]
Sounds like a good idea to me! 

I found [this description of the scaleup.yml from 3.7](https://docs.okd.io/3.7/install_config/adding_hosts_to_existing_cluster.html#adding-cluster-hosts_adding-hosts-to-cluster). Would you know if it still applies? 

> You can add new hosts to your cluster by running the scaleup.yml playbook. This playbook queries the master, generates and distributes new certificates for the new hosts, and then runs the configuration playbooks on only the new hosts.
