### ISSUE TITLE
[enterprise-4.9] Issue in file machine_management/adding-rhel-compute.adoc

### ISSUE THREAD

**Issue by ryandevlin-redhat** [openshift/openshift-docs#38679]
### Which section(s) is the issue in?

[Preparing a RHEL compute node](https://docs.openshift.com/container-platform/4.9/machine_management/adding-rhel-compute.html#rhel-preparing-node_adding-rhel-compute)

### What needs fixing?
When performing these tasks on a RHEL 8 machine, I ran the following (according to the docs):
```
$ sudo subscription-manager repos --disable="*"
$ sudo yum repolist
$ yum-config-manager --disable <repo_id> # ran this a few times to disable 3 repos
```

At this point, I was **not** able to enable the repos in the documentation with the command below:
```
$ subscription-manager repos \
    --enable="rhel-7-server-rpms" \
    --enable="rhel-7-fast-datapath-rpms" \
    --enable="rhel-7-server-extras-rpms" \
    --enable="rhel-7-server-optional-rpms" \
    --enable="rhel-7-server-ose-4.9-rpms"
```
After a lot of trial and error, I discovered I first needed to run the following command:
```
$ sudo subscription-manager config --rhsm.manage_repos=1
```
Once I did this, I was able to enable the 4 repos shown above. This is probably something that should be mentioned in the documentation.

**Comment by codyhoag** [comment]
@gpei can you confirm this requested additional step?

**Comment by mburke5678** [comment]
@gpei can you confirm this requested additional step?

**Comment by gpei** [comment]
@codyhoag sorry, we don't test this through subscription-manager, @mtnbikenc do you happen to know this?

**Comment by mtnbikenc** [comment]
I can confirm this is a new necessary step.  I have come across this requirement when testing RHEL8 worker node deployment because I believe the cloud images have `rhsm.manage_repos=0` configured as default.  Also, the issue description states this was found on a RHEL8 node, but it is also mentioned they are trying to enable rhel-7* repos.  The repos for rhel-8 are different.

**Comment by ryandevlin-redhat** [comment]
@mtnbikenc That's my mistake, I was correctly running the command to enable the RHEL 8 repos below, but pasted the wrong command into this issue thread. The step I described was still required to enabled the RHEL 8 repos below:
```
$ subscription-manager repos \
 --enable="rhel-8-for-x86_64-baseos-rpms" \
 --enable="rhel-8-for-x86_64-appstream-rpms" \
 --enable="rhocp-4.9-for-rhel-8-x86_64-rpms" \
 --enable="fast-datapath-for-rhel-8-x86_64-rpms"
```

**Comment by mburke5678** [comment]
@mtnbikenc Can you help me further with this issue? Or know someone who can?

I'm a bit confused by this topic: [Preparing a RHEL compute node](https://docs.openshift.com/container-platform/4.9/machine_management/adding-rhel-compute.html#rhel-preparing-node_adding-rhel-compute).

* It talks about a _RHEL compute node_, a _RHEL machine_, and a _host_. Is this all the same thing? We need to configure subsctiption-manager and the repos on the box that we want to add to the cluster as a compute node? 
* It says _Preparing **a** RHEL compute node_ and _**each** host_. Should this be _**the** host?_

Also, will we need to add the `sudo subscription-manager config --rhsm.manage_repos=1` step before all instances of `subscription-manager repos` in the docs? Does this apply to RHEL 7 also?

**Comment by mburke5678** [comment]
@mtnbikenc Is this a bug? I found a knowledgebase article that seems to suggest that `rhsm.manage_repos=1` is the default? Or am I mistaken (seems likely)?

[Disabling the Subscription-Manager Repository](https://access.redhat.com/solutions/265523)

**Comment by mtnbikenc** [comment]
@patrickdillon Could you follow up on this?
