### ISSUE TITLE
Installation doc is using atomic-specific service names in some cases

### ISSUE THREAD

**Issue by php-coder** [openshift/openshift-docs#3867]
* https://docs.openshift.org/latest/install_config/configuring_aws.html#aws-configuring-masters-ansible

  Mention `/etc/sysconfig/atomic-openshift-master` and `/etc/sysconfig/atomic-openshift-node` files. Looks like Atomic Host specific because on Fedora they have names `/etc/sysconfig/origin-master` and `/etc/sysconfig/origin-node`

* https://docs.openshift.org/latest/install_config/configuring_aws.html#aws-applying-configuration-changes

  `On each node host, restart the atomic-openshift-node service`. On Fedora service named `origin-node`

* https://docs.openshift.org/latest/install_config/install/advanced_install.html#advanced-verifying-the-installation

  Suggests to execute command `atomic-openshift-excluder exclude` on but it doesn't exist on Fedora.

**Comment by bfallonf** [comment]
Similar question to #3862 , I'm wondering if Fedora is supported. I'll see what the response is there, and respond here accordingly.

**Comment by php-coder** [comment]
I don't think that this case is Fedora specific. I thought that any non-enterprise installation will have non-atomic service names.

**Comment by vikram-redhat** [comment]
This is for upstream docs. If someone wants to submit a PR, we can update.
