### ISSUE TITLE
[enterprise-4.8] Issue in file nodes/nodes/nodes-nodes-managing.adoc

### ISSUE THREAD

**Issue by ehashman** [openshift/openshift-docs#38690]
### Which section(s) is the issue in?

> Most KubeletConfig Options can be set by the user. The following options are not allowed to be overwritten:

### What needs fixing?

1) This links to the upstream kubernetes code at HEAD, which probably don't correspond to the current version of OpenShift and are hard to read. We could at least link to the API docs, like so: https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/
2) It looks like featureGates also can't be set, but that's not documented: `message: 'Error: KubeletConfiguration: featureGates is not allowed to be set, but contains: map[nodeSwap:true]'`

**Comment by mburke5678** [comment]
PR is merged. Closing
