### ISSUE TITLE
Document installer performance optimization techniques

### ISSUE THREAD

**Issue by jeremyeder** [openshift/openshift-docs#3875]
1. Here's an ansible config that we use for large scale deployments.

```
# config file for ansible -- http://ansible.com/  
# ==============================================  
[defaults]  
forks = 100  
host_key_checking = False  
remote_user = root  
roles_path = roles/  
gathering = smart  
fact_caching = jsonfile  
fact_caching_connection = $HOME/ansible/facts  
fact_caching_timeout = 600  
log_path = $HOME/ansible.log  
nocows = 1  
callback_whitelist = profile_tasks  
  
[privilege_escalation]  
become = True  
  
[ssh_connection]  
ssh_args = -o ControlMaster=auto -o ControlPersist=600s  
control_path = %(directory)s/%%h-%%r  
pipelining = True  
timeout = 10  
```

2. One of the key pieces behind being able to deploy at scale is creating pre-built images that include as many of the network/disk ops baked in (rpm install, images pre-pulled).

Here's what we use:  https://github.com/openshift/svt/tree/master/image_provisioner

3. Ansible uses ssh for command-and-control of nodes.  This exacerbates the impact of network latency between the control node and target nodes.  Users should make sure they're running the installer from the lowest-possible latency control node (LAN speeds).  Running over a WAN is not advised.  ```pipelining = True``` reduces the number of connections between control and target nodes, this helps to improve installer performance.

4. Do not run over a lossy network connection

**Comment by jeremyeder** [comment]
See section 8.1 of https://www.redhat.com/cms/managed-files/ose-scale-master.pdf

**Comment by jeremyeder** [comment]
@bfallonf

**Comment by bfallonf** [comment]
Thanks, @jeremyeder . I'll close this issue and make sure it's included in the Scaling and Performace efforst in this BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1420956
