### ISSUE TITLE
[enterprise-4.9] Issue in file monitoring/managing-alerts.adoc

### ISSUE THREAD

**Issue by matttarwater** [openshift/openshift-docs#38776]
### Which section(s) is the issue in?
Throughout the entirety of the Monitoring section

### What needs fixing?
In the UI it is no longer called Monitoring in 4.9, it's called Observe.

**Comment by opayne1** [comment]
@bburt-rh

**Comment by bburt-rh** [comment]
Fixed in https://github.com/openshift/openshift-docs/pull/39117
