### ISSUE TITLE
Global Configuration does not exist

### ISSUE THREAD

**Issue by matttarwater** [openshift/openshift-docs#38777]
### Which section(s) is the issue in?
[Monitoring / managing-alert](https://docs.openshift.com/container-platform/4.9/monitoring/managing-alerts.html#configuring-alert-receivers_managing-alerts)

### What needs fixing?
Global Configuration does not exist in 4.9, it's has changed names.

**Comment by bburt-rh** [comment]
This is fixed and merged for OCP 4.9+ in https://github.com/openshift/openshift-docs/pull/38962
