### ISSUE TITLE
[enterprise-4.8] Issue in file security/certificates/replacing-default-ingress-certificate.adoc

### ISSUE THREAD

**Issue by mrivasxvale** [openshift/openshift-docs#38783]
### Which section(s) is the issue in?

Replacing the default ingress certificate

### What needs fixing?

It is not needed to create a new CA certificate when inserting a new ingress certificate.

**Comment by jboxman-rh** [comment]
@mrivasxvale, is it that everything except the final step is not strictly necessary?

**Comment by mrivasxvale** [comment]
The change of the ingress certificate does not require to change the custom-ca configmap. Mind also that normally the ingress certificate will have an expiration period much shorter than the custom CA.

**Comment by jboxman-rh** [comment]
cc @skrthomas @bmcelvee
