### ISSUE TITLE
Navigation "hamburger" broken on mobile layout

### ISSUE THREAD

**Issue by wgordon17** [openshift/openshift-docs#38807]
E.g., https://docs.openshift.com/container-platform/4.9/welcome/index.html

The hamburger menu appears to have it's `z-index` too low, and is therefore hidden under the header

![image](https://user-images.githubusercontent.com/22222756/142043765-d35d9cb0-b07c-453e-b655-cba0f00ac192.png)

Then scrolling down, it finally comes out of hiding

![image](https://user-images.githubusercontent.com/22222756/142043836-8a5a3bd9-4de6-4146-aada-0804c1f8ab89.png)

Before finally becoming usable

![image](https://user-images.githubusercontent.com/22222756/142043926-04b6c58b-c71a-4f5b-9c2a-b61ff58a6c0a.png)

This was on a Chrome browser, on a desktop machine with the window-width fully minimized. Same thing happened on a Chrome browser on an iPhone.

There's also an issue I noticed using the "Google Search" app on my iPhone, where the hamburger menu isn't actually clickable, and doesn't scroll with page, just stays at the top. I can't replicate outside of the specific "Google Search" app.

**Comment by wgordon17** [comment]
cc @vikram-redhat

**Comment by jboxman-rh** [comment]
cc @aireilly

**Comment by aireilly** [comment]
Yes. This needs to change. Figured something like this would work: https://github.com/openshift/openshift-docs/issues/38512 thoughts?

**Comment by aireilly** [comment]
Fixed in https://github.com/openshift/openshift-docs/pull/38946

**Comment by kaovilai** [comment]
Another issue @aireilly  is search doesn't work.
https://user-images.githubusercontent.com/11228024/153318565-ce7d05a2-8b27-439c-b6c6-50f1df8b806a.mp4


https://user-images.githubusercontent.com/11228024/153318567-6748f6f2-df05-408d-a991-8f57845246d6.mp4

**Comment by aireilly** [comment]
Thanks @kaovilai what browser and OS are you running? I can't replicate this on iOS 15.1 handset or in the Chrome Andriod emulator.

**Comment by kaovilai** [comment]
@aireilly here I recorded a profile for you. You should be able to unzip and load it on your desktop computer Edge ( or maybe chrome too)'s inspect > Performance > Load Profile (arrow pointing up with a line on top).

It shows all the events happening.

[Profile-20220210T111449.json.zip](https://github.com/openshift/openshift-docs/files/8042557/Profile-20220210T111449.json.zip)

**Comment by wgordon17** [comment]
Of course I don't have an Android device either 🙈  I used to actually be pretty handy with remotely debugging Chrome browser on Android devices with `adb` 😏

**Comment by kaovilai** [comment]
Fix here.
https://github.com/openshift/openshift-docs/blob/b47f09e4ef238879eb32f8a17b2c67fbdda87146/_templates/_page_openshift.html.erb#L280

**Comment by kaovilai** [comment]
> _Interesting_! Thanks @kaovilai, I'm seeing the same behavior with that resize now as well (I blame Android for causing a resize with the keyboard popup 😅 )...but lets see what we can figure out 😊

Technically resize is the correct way to do things.. if you web app depends on correct size reporting.. and you don't resize when keyboard shows up... you're going to have a bad time forcing user to close keyboard unnecessarily.

**Comment by kaovilai** [comment]
Especially if content isn't expected to scroll but fit to screen such as games.

**Comment by wgordon17** [comment]
@kaovilai Yeah, I'm thinking the _proper_ fix will be to use some kind of `.sidebar-open` class with `display: block !important` that way the resize doesn't override the state of the nav bar. I think we should be able to get this fixed pretty easily! Thank you for _all_ your help on this!! Makes things so much easier 🙏

**Comment by kaovilai** [comment]
See you in the tower :)
