### ISSUE TITLE
[enterprise-4.9] Issue in file virt/virtual_machines/virtual_disks/virt-creating-data-volumes.adoc

### ISSUE THREAD

**Issue by aglitke** [openshift/openshift-docs#38859]
### What needs fixing?
CDI stands for "Containerized Data Importer" and I see some places incorrectly referring to it as the Containerized Data Interface.

**Comment by bgaydosrh** [comment]
Fixed this occurrence. Checked the rest of the doc and this seems to be the only place we misstate this. Opening separate PR to address this issue: [Xref to be inserted when final PR is ready]

**Comment by bgaydosrh** [comment]
@aglitke - Hi Adam, can you close this PR? I don't have close rights. Thanks, Bob
