### ISSUE TITLE
[enterprise-4.9] Issue in file virt/virtual_machines/virtual_disks/virt-storage-defaults-for-datavolumes.adoc

### ISSUE THREAD

**Issue by aglitke** [openshift/openshift-docs#38858]
### Which section(s) is the issue in?
Entire page

### What needs fixing?
This content is no longer relevant and should have been removed.  We now use Storage Profiles to determine DataVolume settings.

**Comment by bgaydosrh** [comment]
Deleted Topic map entry for this assembly and issuing `git rm` for the assembly file mentioned in the title of this PR. Opening separate PR to address this issue: [Xref to be inserted when final PR is ready]

**Comment by bgaydosrh** [comment]
@aglitke - Can you close this PR? I don't have close rights. Thanks! Bob
