### ISSUE TITLE
[enterprise-4.9] Issue in file service_mesh/v2x/ossm-federation.adoc

### ISSUE THREAD

**Issue by cfilleke** [openshift/openshift-docs#38876]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.9/service_mesh/v2x/ossm-federation.html#exposing-the-federation-ingress-on-clusters-running-on-bare-metal

### What needs fixing?

Needs to indicate that 'bare metal' also refers to IBM Systems Z and P, with a link to some test deployment code and example installation scripts in https://github.com/IBM/OSSM-federation-zap-config

### Where else is this issue tracked?

https://issues.redhat.com/browse/OSSM-728

**Comment by JStickler** [comment]
@cfilleke I know we've discussed this elsewhere.  Can we close this issue?

**Comment by JStickler** [comment]
Closed via #44163
