### ISSUE TITLE
[enterprise-4.9] Issue in file installing/installing_rhv/installing-rhv-restricted-network.adoc

### ISSUE THREAD

**Issue by abaars** [openshift/openshift-docs#38917]
### Which section(s) is the issue in?
[Downloading the Ansible playbooks](https://docs.openshift.com/container-platform/4.9/installing/installing_rhv/installing-rhv-restricted-network.html#installation-rhv-downloading-ansible-playbooks_installing-rhv-restricted-network)

### What needs fixing?
There is a mismatch in versions in the docs.

The Github link refers to '?ref=release-4.9', which gets a version of the playbooks that expects ovirt-ansible-vm-infra and ovirt-ansible-image-template to be roles. This fails in combination with the packages in the earlier section [Setting up the installation machine](https://docs.openshift.com/container-platform/4.9/installing/installing_rhv/installing-rhv-restricted-network.html#installing-rhv-setting-up-installation-machine_installing-rhv-restricted-network), because RHEL 8 automatically installs ovirt-ansible-collection instead of these roles when following the instructions.

**Comment by rolfedh** [comment]
@stoobie @emarcusRH FYI

**Comment by stoobie** [comment]
@Gal-Zaidman @janosdebugs Can either of you help me understand the issue here and what to fix?

**Comment by janosdebugs** [comment]
@stoobie there seems to be an issue with the instructions, but I don't know off the top of my head how to fix it. I would suggest opening a BZ.

**Comment by ctomasko** [comment]
Tracking issue in https://bugzilla.redhat.com/show_bug.cgi?id=2044757.

**Comment by apinnick** [comment]
@santos1709 
Can this problem be fixed in documentation? Or do we need to open an issue to update the Ansible playbook?

**Comment by janosdebugs** [comment]
@santos1709 the master would reference the latest unstable version, which may or may not work.

**Comment by janosdebugs** [comment]
It will work, but it needs to be updated for every release. About export regulations I can't say anything, that's a question for legal. To me it makes no difference if people download from github.com or api.github.com

**Comment by emarcusRH** [comment]
Closing this bug - the ansible playbook links have been updated in https://github.com/openshift/openshift-docs/pull/43020
which was merged into /main and will be published with the 4.11 release

**Comment by ctomasko** [comment]
Close. Resolved https://github.com/openshift/openshift-docs/pull/43020

**Comment by ctomasko** [comment]
/close

Catherine Tomasko

Documentation Program Manager

Red Hat <https://www.redhat.com/>

***@***.***
M: 440-773-3097
<https://www.redhat.com/>
***@***.***
