### ISSUE TITLE
OKD - insecure ovirt config file is invalid

### ISSUE THREAD

**Issue by binnes** [openshift/openshift-docs#38932]
### Which section(s) is the issue in?
There is a common section on 2 different pages, installing on oVirt - quick install and with customizations:
https://docs.okd.io/latest/installing/installing_rhv/installing-rhv-default.html#installing-rhv-insecure-mode_installing-rhv-default
https://docs.okd.io/latest/installing/installing_rhv/installing-rhv-customizations.html#installing-rhv-insecure-mode_installing-rhv-customizations

### What needs fixing?

The user is advised to copy the following into a file named ~/.ovirt/ovirt-config.yaml:

```
ovirt_url: \https://ovirt.example.com/ovirt-engine/api
ovirt_fqdn: ovirt.example.com
ovirt_pem_url: ""
ovirt_username: ocpadmin@internal
ovirt_password: super-secret-password
ovirt_insecure: true
```

There is a `\` character in the ovirt_url line.  It should read `ovirt_url: https://ovirt.example.com/ovirt-engine/api`

The default admin user name on oVirt is admin, so the ovirt_username should read `ovirt_username: admin@internal`

I also think it is worth mentioning that the user needs to modify the file, not copy as it is provided,  The content the user needs to modify is:
- ovirt_url : The hostname or address of their oVirt engine needs to replace ovirt.example.com
- ovirt_fqdn : The Fully Qualified Domain Name of their oVirt engine needs to replace ovirt.example.com
- ovirt_password : The user needs to replace super-secret-password with the admin password for their oVirt engine

/assign @mburke5678
/assign @dmueller2001

**Comment by mburke5678** [comment]
@binnes The `ovirt_username` was [changed to `ocpadmin@internal` recently](https://bugzilla.redhat.com/show_bug.cgi?id=1849398),  because using `admin@internal` is bad practice. WDYT?

**Comment by binnes** [comment]
`admin` is the default name of the oVirt admin user that is created when you do a standard oVirt install, it is not a username that is being set here.  This config is providing the login credentials for the oVirt server where OKD will be installed.

I suggest this name matches the default admin user created during a standard oVirt install.

**Comment by mburke5678** [comment]
@binnes OK. Why don't we set the username back to `admin` for OKD and leave the OCP username in place. 

@vrutkovs PTAL also

**Comment by mburke5678** [comment]
@binnes Can you PTAL at my PR? Vadim approved of the changes but wants you to review them too. Thank you!

**Comment by mburke5678** [comment]
PR is merged. Closing
