### ISSUE TITLE
[enterprise-4.9] Issue in file rest_api/monitoring_apis/prometheus-monitoring-coreos-com-v1.adoc

### ISSUE THREAD

**Issue by jan--f** [openshift/openshift-docs#38993]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.9/rest_api/monitoring_apis/prometheus-monitoring-coreos-com-v1.html

### What needs fixing?
`remote_write` is listed as experimental. I believe this [originates in prometheus-operator](https://github.com/prometheus-operator/prometheus-operator/blob/main/pkg/apis/monitoring/v1/types.go#L251). In OpenShift 4.9 remote write is not considered experimental, so this statement likely confuses users. I'm not sure what the best path forward is, as the api doc is automatically extracted iiuc. Maybe a  clarifying note that those docs don't necessarily reflect Red Hats support statements and a link to relevant content?

**Comment by bburt-rh** [comment]
Thanks, @jan--f . Now being tracked in https://issues.redhat.com/browse/RHDEVDOCS-3483
