### ISSUE TITLE
beta and alpha REST API references are missing

### ISSUE THREAD

**Issue by t0ffel** [openshift/openshift-docs#3922]
At the moment there is only api version "v1" reference available in the documentation:
https://docs.openshift.org/latest/rest_api/kubernetes_v1.html#rest-api-kubernetes-v1

Would it be possible to add similar sections for beta/alpha?
Specifically `daemonset`, `statefulset` are missing along with some other resource types.

**Comment by vikram-redhat** [comment]
This is something that we are not doing at the moment.
