### ISSUE TITLE
[enterprise-4.9] Issue in file backup_and_restore/graceful-cluster-shutdown.adoc

### ISSUE THREAD

**Issue by rhn-support-wcheng** [openshift/openshift-docs#39278]
### Which section(s) is the issue in?
No master available to serve oc command for graceful shutdown after master is down.

[wcheng@wcheng ~]$ for node in $(oc get nodes -o jsonpath='{.items[*].metadata.name}'); do oc debug node/${node} -- chroot /host shutdown -h 1; done
Starting pod/blue-8nwc5-master-0-debug ...
To use host binaries, run `chroot /host`
Shutdown scheduled for Fri 2021-11-26 00:51:24 UTC, use 'shutdown -c' to cancel.

Removing debug pod ...
Starting pod/blue-8nwc5-master-1-debug ...
To use host binaries, run `chroot /host`
Shutdown scheduled for Fri 2021-11-26 00:52:07 UTC, use 'shutdown -c' to cancel.

Removing debug pod ...
Starting pod/blue-8nwc5-master-2-debug ...
To use host binaries, run `chroot /host`

Removing debug pod ...
error: unable to delete the debug pod "blue-8nwc5-master-2-debug": Delete https://api.blue.openshift.com:6443/api/v1/namespaces/kai-design-container/pods/blue-8nwc5-master-2-debug: read tcp 192.168.155.186:45710->192.168.10.30:6443: read: connection reset by peer
error: watch closed before UntilWithoutRetry timeout
The connection to the server api.blue.openshift.com:6443 was refused - did you specify the right host or port?
The connection to the server api.blue.openshift.com:6443 was refused - did you specify the right host or port?
[wcheng@wcheng ~]$ oc get pods
The connection to the server api.blue.openshift.com:6443 was refused - did you specify the right host or port?

### What needs fixing?
Allow longer time to wait in shutdown command. (may need adjust if larger cluster)
for node in $(oc get nodes -o jsonpath='{.items[*].metadata.name}'); do oc debug node/${node} -- chroot /host shutdown -h 10; done

**Comment by bergerhoffer** [comment]
@sttts Should we make any adjustments to the shutdown command's time from of `1` here? Or perhaps add a note saying that you can increase it form `1` to whatever if needed?
