### ISSUE TITLE
[enterprise-4.9] Issue in file welcome/oke_about.adoc

### ISSUE THREAD

**Issue by bweidenb** [openshift/openshift-docs#39273]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.9/welcome/oke_about.html

### What needs fixing?
x3 instances of typo for ACM 
Graphic has a typo for ACM - Advanced cluster management
Change to Advanced Cluster Management

As well some product text is in mixed case with wrong word choice.  Change to consistent case and proper word choice per formal product page & name https://www.redhat.com/en/technologies/management/advanced-cluster-management
Red Hat® Advanced Cluster Management for Kubernetes

Current 
Advanced cluster management
OpenShift Kubernetes Engine is compatible with your additional purchase of Red Hat Advanced Cluster Manager for Kubernetes

Proposed 
Advanced Cluster Management
OpenShift Kubernetes Engine is compatible with your additional purchase of Red Hat Advanced Cluster Management for Kubernetes

**Comment by bweidenb** [comment]
also added this to  [17724](https://github.com/open-cluster-management/backlog/issues/17724) 
ACM 2.4 3 tech preview doc 404s found here  
https://multicloud-console.apps.pm-demo.demo.red-chesterfield.com/multicloud/cluster-pools

https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.4/html/clusters/managing-cluster-pools#claiming-clusters-from-cluster-pools

https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.4/html/clusters/managing-cluster-pools

https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.4/html/clusters/managing-cluster-pools

**Comment by JoeAldinger** [comment]
Hi @bweidenb thanks for submitting the issue. The issue was resolved on 2.24.22 and appreciate your help.

**Comment by ahardin-rh** [comment]
Closing, as https://github.com/openshift/openshift-docs/pull/42386 is now merged.
