### ISSUE TITLE
document deploymentConfig hostPort

### ISSUE THREAD

**Issue by johnkeck** [openshift/openshift-docs#394]
We are missing documentation on hostPort in the deploymentConfig docs.  Not sure what other attributes are missing as well but we should cover all of them even if they are seldom used.

**Comment by bfallonf** [comment]
@johnkeck  I can see that in the upgrade docs the hostport parameter is there[1], but in the deploymentconfig it isn't part of the example[2]. I can also see in the API docs that the paramter is talked about, but that's not too specific[3].


[1] https://docs.openshift.com/enterprise/3.0/install_config/upgrades.html#openshift-enterprise-3-0-2-0
[2] https://docs.openshift.com/enterprise/3.0/dev_guide/deployments.html#creating-a-deployment-configuration
[3] https://docs.openshift.com/enterprise/3.0/rest_api/kubernetes_v1.html

**Comment by adellape** [comment]
@bfallonf It's not an error, it's just not mentioned at all (in the deployconfig doc). And I think the main point was that it's not explained as to what it is (other than the brief API doc description you'd have to hunt for) or why you'd use it (or more likely, not use it).

See also:

http://kubernetes.io/v1.0/docs/user-guide/config-best-practices.html
http://kubernetes.io/v1.0/docs/user-guide/application-troubleshooting.html
