### ISSUE TITLE
[RHACS] Issue in file operating/respond-to-violations.adoc

### ISSUE THREAD

**Issue by mattparko** [openshift/openshift-docs#39400]
### Which section(s) is the issue in?

Security Context section (under operating/respond-to-violations.adoc)

### What needs fixing?

Typo in line: "Lists whether the container is running as a privilaged container."

Should be: "Lists whether the container is running as a privileged container."

**Comment by jboxman-rh** [comment]
@mattparko, in what version of the docs? Thanks!

**Comment by jboxman** [comment]
https://docs.openshift.com/acs/3.66/operating/respond-to-violations.html

**Comment by gaurav-nelson** [comment]
@tmalove Can you please fix this one?
