### ISSUE TITLE
[enterprise-4.9] Issue in file storage/persistent_storage/persistent-storage-ocs.adoc

### ISSUE THREAD

**Issue by secobau** [openshift/openshift-docs#39473]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.9/storage/persistent_storage/persistent-storage-ocs.html

### What needs fixing?

The documentation page is pointing to Red Hat Openshift Container Storage 4.7

Should it not point to 4.8 instead?

**Comment by lbscorpio** [comment]
@secobau Thanks for your feedback, I think so. The [PR#39517](https://github.com/openshift/openshift-docs/pull/39517) will fix it, waiting for review, thanks.
