### ISSUE TITLE
[OKD] Add a new book to topic map for OKD community docs

### ISSUE THREAD

**Issue by mburke5678** [openshift/openshift-docs#39472]
We have a request to add links to [the OKD community docs](https://www.okd.io/docs/) to the official OKD doc set. A list of links will be provided by the OKD team.

My thought was to add a new assembly to the topic map with a single module containing the links.

**Comment by mburke5678** [comment]
@vikram-redhat Is this something we can do? The OKD community docs are created and maintained by the OKD community and are not reviewed by OpenShift QE. As this new assembly would be in the OKD docs only, the OCP QE review isn't necessary. Please let us know if you think otherwise.
@dmueller2001 @vrutkovs FYI

**Comment by vikram-redhat** [comment]
Is this new book likely to ever make it downstream?

**Comment by mburke5678** [comment]
@vikram-redhat No. These are documents written by the OKD community, not Red Hat folks. I will let @vrutkovs determine if any of the docs could be used as a basis for downstream OCP.

**Comment by vrutkovs** [comment]
Not entirely sure which links do we want to add to docs.okd.io - should this be a link to https://www.okd.io/docs/ or more links about OKD community? I'm fine with the former (its a bit confusing to have docs.okd.io and okd.io/docs pointing to different sources though, perhaps worth renaming)
