### ISSUE TITLE
[enterprise-4.8] Issue in file post_installation_configuration/machine-configuration-tasks.adoc

### ISSUE THREAD

**Issue by afcollins** [openshift/openshift-docs#39580]
### Which section(s) is the issue in?

"Creating a ContainerRuntimeConfig CR to edit CRI-O parameters"
Code block: "Example ContainerRuntimeConfig CR"

### What needs fixing?
The callouts 2-5 don't match what they are labeling.

I believe the correct ordering of callout comments is (from current numbers):
5, 2, 4, 3

Checked enterprise-4.9 and it is also incorrect there.

Thank you!

**Comment by mburke5678** [comment]
@afcollins Thanks for pointing this out. The problem did get fixed for 4.9+.. Not sure why the changes didn't get ported back to 4.7 and 4.8. I will look into it!

**Comment by mburke5678** [comment]
Fixed: 
https://github.com/openshift/openshift-docs/pull/40506
https://github.com/openshift/openshift-docs/pull/40505
