### ISSUE TITLE
[online] Issue in file welcome/index.adoc

### ISSUE THREAD

**Issue by boogiespook** [openshift/openshift-docs#39603]
### Which section(s) is the issue in?
The search facility in https://docs.openshift.com/acs/3.67/welcome/index.html does not return any results

### What needs fixing?
All searches return "No results found. Try rewording your search." But searching in the previous version (https://docs.openshift.com/acs/3.66/welcome/index.html) works fine.

**Comment by vikram-redhat** [comment]
Fixed.
