### ISSUE TITLE
Console about page customization JS example missing a line

### ISSUE THREAD

**Issue by jwforres** [openshift/openshift-docs#3964]
This doc section, https://docs.openshift.org/latest/install_config/web_console_customization.html#customizing-the-about-page
the bottom of the about.js example needs to have

```
hawtioPluginLoader.addModule('aboutPageExtension');
```
Originally reported as https://github.com/openshift/origin-web-console/issues/1353

**Comment by bfallonf** [comment]
Thanks @jwforres . PR #4053 created.

I'll close this issue.
