### ISSUE TITLE
[online] Issue in file rosa_policy/rosa-policy-process-security.adoc

### ISSUE THREAD

**Issue by filiy** [openshift/openshift-docs#39655]
### Which section(s) is the issue in?

Under the Privileged access controls in Red Hat OpenShift Service on AWS section there is a table. "Right under Each of these access types have different levels of access to components:"

### What needs fixing?

"Node Operatiing system" there are two i's. Small typo. Thanks!!

**Comment by arendej** [comment]
Thanks! captured in: https://issues.redhat.com/browse/OSDOCS-3174

**Comment by JoeAldinger** [comment]
@filiy Thanks for submitting this bug. It has been addressed and closed on 2.12.22.
