### ISSUE TITLE
[enterprise-4.9] Issue in file migration_toolkit_for_containers/upgrading-mtc.adoc

### ISSUE THREAD

**Issue by asadawar** [openshift/openshift-docs#39729]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.9//migration_toolkit_for_containers/upgrading-mtc.html#migration-upgrading-mtc-on-ocp-4_upgrading-mtc

### What needs fixing?
Step 7 and 8 in the procedure is not required and should be removed as the MigController instance is already available which gets updated automatically when you update the MTC operator.

~~~
7. Click Migration Toolkit for Containers Operator.
8. Under Provided APIs, locate the Migration Controller tile, and click Create Instance.
~~~

https://docs.openshift.com/container-platform/4.9//migration_toolkit_for_containers/upgrading-mtc.html#migration-upgrading-mtc-on-ocp-4_upgrading-mtc

**Comment by apinnick** [comment]
@nunzy1  @RichardHoch 
Can you follow this up?

**Comment by RichardHoch** [comment]
remove-lifecycle rotten

**Comment by apinnick** [comment]
Issue fixed.
