### ISSUE TITLE
OKD doesn't support installation with Assisted Installer

### ISSUE THREAD

**Issue by JayDoubleu** [openshift/openshift-docs#39759]
### Which section(s) is the issue in?

https://docs.okd.io/latest/installing/installing_sno/install-sno-installing-sno.html

### What needs fixing?

OKD doesn't yet support single node clusters using assisted installer. The document above is for installation of  OC SNO instead of OKD.

_Docs are incorrect, OKD doesn't support installation with Assisted Installer just yet, please file a bug at https://github.com/openshift/openshift-docs_

_Originally posted by @vrutkovs in https://github.com/openshift/okd/discussions/1012#discussioncomment-1786980_

**Comment by mburke5678** [comment]
Docs PR merged.
