### ISSUE TITLE
[enterprise-4.9] Issue in file virt/virtual_machines/cloning_vms/virt-cloning-vm-using-datavolumetemplate.adoc

### ISSUE THREAD

**Issue by jpeimer** [openshift/openshift-docs#39890]
The example uses pvc api, but we recommend using the storage api, because it has some usability fixes.

### Which section(s) is the issue in?
YAML file for a VirtualMachine object
and 
Template: Data volume virtual machine configuration file

spec:
  dataVolumeTemplates:
  - metadata:
      name: favorite-clone
    spec:
      pvc:

### What needs fixing?

spec:
  dataVolumeTemplates:
  - metadata:
      name: favorite-clone
    spec:
      storage:

(Need to use "storage" instead of "pvc")

**Comment by jpeimer** [comment]
Tagging @aglitke

**Comment by ctomasko** [comment]
https://issues.redhat.com/browse/CNV-17912

**Comment by bgaydosrh** [comment]
Resolving in: https://github.com/openshift/openshift-docs/pull/53118.

@jpeimer - Please close this issue when resolved to your satisfaction, I cannot close GH issues.
Thanks
Bob

**Comment by jpeimer** [comment]
Closing the issue as it's being resolved in https://github.com/openshift/openshift-docs/pull/53118
