### ISSUE TITLE
[enterprise-4.9] Issue in file service_mesh/v2x/installing-ossm.adoc

### ISSUE THREAD

**Issue by ScriptingShrimp** [openshift/openshift-docs#39928]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.9/service_mesh/v2x/installing-ossm.html#ossm-installation-activities_installing-ossm

>Operator overview
Red Hat OpenShift Service Mesh requires the following four Operators:

and

>Installing the Operators
To install Red Hat OpenShift Service Mesh, install following Operators in this order. Repeat the procedure for each Operator.

### What needs fixing?
![image](https://user-images.githubusercontent.com/86114326/146274058-f23b4ee4-a564-40d9-b809-40a24fbd26aa.png)
I do believe that we should use **Red Hat OpenShift distributed tracing platform** in OCP versions ?larger than? 4.9
Thanks for verification

**Comment by JStickler** [comment]
@ScriptingShrimp  Jaeger is being rebranded to distributed tracing.  The updates to the documentation are ongoing can can be tracked in [OSSMDOC-456](https://issues.redhat.com/browse/OSSMDOC-456) (Service Mesh docs) and [OSSMDOC-409](https://issues.redhat.com/browse/OSSMDOC-409) (Epic for rebranding the entire doc set)

**Comment by JStickler** [comment]
Closed via  OSSMDOC-288 ( #39643) and  OSSMDOC-456 (#40980)
