### ISSUE TITLE
[dedicated] Issue in file identity_providers/config-identity-providers.adoc

### ISSUE THREAD

**Issue by hupiper** [openshift/openshift-docs#39930]
### Which section(s) is the issue in?
https://docs.openshift.com/dedicated/identity_providers/config-identity-providers.html#config-htpasswd-idp_config-identity-providers
![Screen Shot 2021-12-15 at 5 03 47 PM](https://user-images.githubusercontent.com/1512878/146278478-e82e4153-48b9-45ce-9926-b5803c64b637.png)

### What needs fixing?
Step 8: Grant the static user permission to manage the cluster:
Select Add user in the Cluster administrative users section of the Access control page

That should say click on the Cluster Roles and Access section, the select Add user...

**Comment by hupiper** [comment]
Was anything ever done here? I comment on doc issues often, and they seem to sit as open issues, and are ignored and dropped.

**Comment by kalexand-rh** [comment]
@hupiper, we're working on a new process for managing our GitHub issues queue and balancing work on them against work on items in our two other queues. We hope that this will improve the speed of addressing issues. Thank you for opening issues, and I hope that the dedicated writers can take a look soon.
