### ISSUE TITLE
Cron Job for LDAP groups sync code syntax error on OCP 4 documentation

### ISSUE THREAD

**Issue by nstamatelopoulos** [openshift/openshift-docs#39937]
### Which section(s) is the issue in?

The Syntax of the CronJob container's command in the CronJob definition file example that is present in the step 11. **Define a cron job:** under the **Automatically syncing LDAP groups section is wrong** in openshift [documentation](https://docs.openshift.com/container-platform/4.9/authentication/ldap-syncing.html#ldap-auto-syncing_ldap-syncing-groups) 4.

### What needs fixing?

The Syntax of the CronJob container's command in the CronJob definition file example is wrong as you can see below:

```
command:
  - "/bin/bash"
  - "-c"
  - oc adm groups sync
  - --sync-config=/etc/config/ldap-group-sync.yaml --confirm
```

Suggestions for improvement: 

The command syntax should be like this:

```
command:
  - "/bin/bash"
  - "-c"
  - oc adm groups sync --sync-config=/etc/config/ldap-group-sync.yaml --confirm
```
I have also this bugzilla [bug](https://bugzilla.redhat.com/show_bug.cgi?id=2029919) open.

Thank you!

**Comment by bergerhoffer** [comment]
Thanks for reporting! This has already been reported via #39966, so I'm going to close this as a duplicate. We do already have a PR in progress (#39966) to address this. 

I will also take ownership of that BZ.
