### ISSUE TITLE
[enterprise-4.9] Issue in file installing/installing_bare_metal_ipi/ipi-install-installation-workflow.adoc

### ISSUE THREAD

**Issue by iconeb** [openshift/openshift-docs#39949]
### Which section(s) is the issue in?
Mirroring the repository (optional)

### What needs fixing?
/usr/local/bin/oc adm release mirror \
  -a pull-secret-update.txt
  --from=$UPSTREAM_REPO \
  --to-release-image=$LOCAL_REG/$LOCAL_REPO:${VERSION} \
  --to=$LOCAL_REG/$LOCAL_REPO

is missing a \ at the end of the second line

**Comment by codyhoag** [comment]
Thanks for reporting this, @iconeb! I have merged the fix.
