### ISSUE TITLE
[dedicated] Issue in file osd_quickstart/osd-quickstart.adoc

### ISSUE THREAD

**Issue by hupiper** [openshift/openshift-docs#39962]
### Which section(s) is the issue in?
https://docs.openshift.com/dedicated/osd_quickstart/osd-quickstart.html#create-cluster_osd-quickstart

### What needs fixing?
Bullet point 9: Select the amount of Persistent storage and Load balancers you want set on the deployed cluster or accept the defaults. 
![Screen Shot 2021-12-16 at 10 55 58 AM](https://user-images.githubusercontent.com/1512878/146414861-4cddaaea-b355-4d9e-8c34-aed9a3c85449.png)

There is no option for that when setting up an OSD cluster for AWS. See attached.

**Comment by hupiper** [comment]
@kalexand-rh Just wondering why none of my doc issues are worked on. Have they been fixed?

**Comment by kalexand-rh** [comment]
@hupiper, we're trying to improve the process around our GitHub issue triage so that the right writers are more likely to find and fix them.
