### ISSUE TITLE
[enterprise-4.8] Issue in file logging/cluster-logging-external.adoc

### ISSUE THREAD

**Issue by cnuland** [openshift/openshift-docs#39981]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.8/logging/cluster-logging-external.html#cluster-logging-troubleshooting-log-forwarding_cluster-logging-external

### What needs fixing?
`$ oc delete pod --selector logging-infra=fluentd`

I believe should be

`$ oc delete pod --selector logging-infra=collector`

In 4.8

**Comment by cbremble** [comment]
Added to Jira: https://issues.redhat.com/browse/RHDEVDOCS-4309

**Comment by cbremble** [comment]
This should have been addressed now by a duplicate issue: https://issues.redhat.com/browse/RHDEVDOCS-3771. Please let us know if you see any further issues. 

/close
