### ISSUE TITLE
[enterprise-4.9] Issue in file monitoring/configuring-the-monitoring-stack.adoc

### ISSUE THREAD

**Issue by rbaumgar** [openshift/openshift-docs#40033]
### Which section(s) is the issue in?
Setting log levels for monitoring components
1. Edit the ConfigMap object:

### What needs fixing?
in this section you should define the component that you are applying a log level to, but it is not described which component names are available.
You have to know (!) that the component is not kubernetes it is kubernetesk8s...

**Comment by rbaumgar** [comment]
This is the link
https://docs.openshift.com/container-platform/4.9/monitoring/configuring-the-monitoring-stack.html#setting-log-levels-for-monitoring-components_configuring-the-monitoring-stack

**Comment by cbremble** [comment]
Added to Jira: https://issues.redhat.com/browse/RHDEVDOCS-4311

**Comment by bburt-rh** [comment]
This issue has been fixed, and the change is live in the 4.9+ docs at:

* https://docs.openshift.com/container-platform/4.11/monitoring/configuring-the-monitoring-stack.html#setting-log-levels-for-monitoring-components_configuring-the-monitoring-stack
* https://docs.openshift.com/container-platform/4.10/monitoring/configuring-the-monitoring-stack.html#setting-log-levels-for-monitoring-components_configuring-the-monitoring-stack
* https://docs.openshift.com/container-platform/4.9/monitoring/configuring-the-monitoring-stack.html#setting-log-levels-for-monitoring-components_configuring-the-monitoring-stack
