### ISSUE TITLE
[enterprise-4.9] Issue in file installing/installing_azure/installing-azure-customizations.adoc

### ISSUE THREAD

**Issue by jboutaud** [openshift/openshift-docs#40104]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.9/installing/installing_azure/installing-azure-customizations.html#installing-azure-customizations, specifically, this section:
Configuring the cluster-wide proxy during installation

### What needs fixing?
There are details about AWS but the section is specifically about Azure. This text should be reworked with Azure as a context instead or removed: 

If your cluster is on AWS, you added the ec2.<region>.amazonaws.com, elasticloadbalancing.<region>.amazonaws.com, and s3.<region>.amazonaws.com endpoints to your VPC endpoint. These endpoints are required to complete requests from the nodes to the AWS EC2 API. Because the proxy works on the container level, not the node level, you must route these requests to the AWS EC2 API through the AWS private network. Adding the public IP address of the EC2 API to your allowlist in your proxy server is not sufficient.

**Comment by codyhoag** [comment]
@jboutaud Thanks for reporting this! The fix has been merged.
