### ISSUE TITLE
[rhacs-docs] Issue in file integration/integrate-with-ci-systems.adoc

### ISSUE THREAD

**Issue by kirson-git** [openshift/openshift-docs#40117]
### Which section(s) is the issue in?
Download Links are wrong :) Use "Latest" will fix it 

### What needs fixing?
Not Working -- > $ curl -O https://mirror.openshift.com/pub/rhacs/assets/3.67.2/bin/Linux/roxctl
Working -->  https://mirror.openshift.com/pub/rhacs/assets/latest/bin/Linux/roxctl

**Comment by gaurav-nelson** [comment]
Thanks for the issue @kirson-git There was a problem with publishing of packages. This is now resolved.
