### ISSUE TITLE
[enterprise-4.8] Issue in file virt/virtual_machines/virtual_disks/virt-reserving-pvc-space-fs-overhead.adoc

### ISSUE THREAD

**Issue by jpeimer** [openshift/openshift-docs#40118]
### Which section(s) is the issue in?
Overriding the default file system overhead value

### What needs fixing?
It is not possible to override the default file system overhead value since OpenShift Virtualization (CNV) v4.8 
So the doc should be changed for 4.8, 4.9, and upcoming 4.10 and 4.11

**Comment by bergerhoffer** [comment]
Marking as a duplicate of #40119
