### ISSUE TITLE
[enterprise-4.9] Issue in file virt/virtual_machines/virtual_disks/virt-reserving-pvc-space-fs-overhead.adoc

### ISSUE THREAD

**Issue by jpeimer** [openshift/openshift-docs#40119]
### Which section(s) is the issue in?
Overriding the default file system overhead value

### What needs fixing?
It is not possible to override the default file system overhead value since OpenShift Virtualization (CNV) v4.8
So the doc should be changed for 4.8, 4.9, and upcoming 4.10 and 4.11

**Comment by apinnick** [comment]
@jpeimer There is a related task in progress - CNV-19923

**Comment by maya-r** [comment]
this is true for 4.10/4.9 but not for 4.11 and later (it got changed in CNV-16974 so it is configurable)

**Comment by apinnick** [comment]
> this is true for 4.10/4.9 but not for 4.11 and later (it got changed in [CNV-16974](https://issues.redhat.com//browse/CNV-16974) so it is configurable)

Understood. I will create a Jira issue to remove the section in 4.9 and 4.10.

**Comment by apinnick** [comment]
Issue resolved.
