### ISSUE TITLE
[enterprise-4.9] RFE in file networking/dns-operator.adoc

### ISSUE THREAD

**Issue by renatoppuccini** [openshift/openshift-docs#40168]
### Which section(s) is the issue in?
Missing dns reverse configuration. It has only forward.

### What needs fixing?
Missing dns reverse configuration. It has only forward configuration.
Customers having application relying on reverse dns look up, would need to configure this, but could find examples only on community pages -> https://coredns.io/plugins/reverse/
This should also be validated with engineering team if supported/tested as well.

**Comment by skrthomas** [comment]
I'm checking with engineering on whether the DNS Operator supports reverse.

**Comment by skrthomas** [comment]
@renatoppuccini Reverse is not currently supported by the DNS Operator. If you want to file an RFE to request this feature, you can do so through Jira: https://issues.redhat.com/projects/RFE/summary. Please be sure to include a detailed use case in any RFE that you file. Thank you!

**Comment by skrthomas** [comment]
Closing
