### ISSUE TITLE
[enterprise-4.9] Issue in file installing/installing_bare_metal_ipi/ipi-install-installation-workflow.adoc

### ISSUE THREAD

**Issue by aireilly** [openshift/openshift-docs#40199]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.9/installing/installing_bare_metal_ipi/ipi-install-installation-workflow.html#ipi-install-creating-an-rhcos-images-cache_ipi-install-installation-workflow

### What needs fixing?

Parse errors in the following commands: 

`export RHCOS_OPENSTACK_URI=$(curl -s -S https://raw.githubusercontent.com/openshift/installer/$COMMIT_ID/data/data/rhcos.json  | jq .images.openstack.path | sed 's/"//g')`

`export RHCOS_QEMU_URI=$(curl -s -S https://raw.githubusercontent.com/openshift/installer/$COMMIT_ID/data/data/rhcos.json  | jq .images.qemu.path | sed 's/"//g')`

`export RHCOS_PATH=$(curl -s -S https://raw.githubusercontent.com/openshift/installer/$COMMIT_ID/data/data/rhcos.json | jq .baseURI | sed 's/"//g')jq`

`export RHCOS_QEMU_SHA_UNCOMPRESSED=$(curl -s -S https://raw.githubusercontent.com/openshift/installer/$COMMIT_ID/data/data/rhcos.json  | jq -r '.images.qemu["uncompressed-sha256"]')`

`export RHCOS_OPENSTACK_SHA_COMPRESSED=$(curl -s -S https://raw.githubusercontent.com/openshift/installer/$COMMIT_ID/data/data/rhcos.json  | jq -r '.images.openstack.sha256')`

**Comment by aireilly** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2036968

**Comment by kalexand-rh** [comment]
The bug attached to this issue is closed with a status of WONTFIX. Closing.
