### ISSUE TITLE
[online] Issue in file rosa_getting_started/rosa-creating-cluster.adoc

### ISSUE THREAD

**Issue by supernovae** [openshift/openshift-docs#40220]
### Which section(s) is the issue in?

https://docs.openshift.com/rosa/rosa_getting_started/rosa-creating-cluster.html#rosa-creating-cluster_rosa-getting-started

Would be beneficial to have notes about what the CIDR blocks are that follow the kubernetes documentation.  I've had customers ask what these ranges are and it would be nice to have them documented across all of our openshift docs.

### What needs fixing?

We should note what the  Machine cidr, pod cidr and service cidr are for. Noting the following:

Machine Cider - Worker Nodes.  A non overlapping CIDR is needed for each AZ.

POD CIDR - IP Addresses of pods are allocated from the POD CIDR.  This allows pods to communicate with each other.  The CIDR block for pods cannot overlap with the CIDR block for Service CIDR

Service CIDR -  The IP address of a service within the OpenShift Cluster.
Service CIDR block cannot overlap with POD CIDR Block.

**Comment by 0kashi** [comment]
This is actually located here in the table: https://docs.openshift.com/rosa/rosa_getting_started_sts/rosa_creating_a_cluster_with_sts/rosa-sts-interactive-mode-reference.html

Though I agree that this could be helpful to have in a more intuitive place, maybe under networking topic.  This has been noted.
