### ISSUE TITLE
[enterprise-4.7] Issue in file monitoring/exposing-custom-application-metrics-for-autoscaling.adoc

### ISSUE THREAD

**Issue by nickallenjr** [openshift/openshift-docs#40244]
### Which section(s) is the issue in? 
Exposing custom application metrics for horizontal pod autoscaling

### What needs fixing?
[Here ](https://docs.openshift.com/container-platform/4.7/monitoring/exposing-custom-application-metrics-for-autoscaling.html#exposing-custom-application-metrics-for-horizontal-pod-autoscaling_exposing-custom-application-metrics-for-autoscaling)it says 
_**Prerequisites**
You have a custom Prometheus instance installed. In this example, it is presumed that Prometheus was installed in a user-defined custom-prometheus project._

But [here ](https://docs.openshift.com/container-platform/4.7/monitoring/configuring-the-monitoring-stack.html#support-considerations_configuring-the-monitoring-stack)
It says 
_The following modifications are explicitly not supported:_
**Installing custom Prometheus instances on OpenShift Container Platform.**

**Comment by cbremble** [comment]
Added to Jira: https://issues.redhat.com/browse/RHDEVDOCS-4310

**Comment by bburt-rh** [comment]
Closing. This fix is added in https://github.com/openshift/openshift-docs/pull/51404
