### ISSUE TITLE
[enterprise-4.9] Issue in file release_notes/ocp-4-9-release-notes.adoc

### ISSUE THREAD

**Issue by davidlanouette** [openshift/openshift-docs#40259]
### Which section(s) is the issue in?

"About this release" paragraph.  (from https://docs.openshift.com/container-platform/4.9/release_notes/ocp-4-9-release-notes.html#ocp-4-9-about-this-release)

### What needs fixing?

The second sentence of the second paragraph has what looks like a template expression that wasn't expanded.

> The **{cloud-redhat-com}** application for OpenShift Container Platform allows you to deploy OpenShift clusters to either on-premise or cloud environments.

Versus the previous version:

> The **Red Hat OpenShift Cluster Manager** application for OpenShift Container Platform allows you to deploy OpenShift clusters to either on-premise or cloud environments.

**Comment by ahardin-rh** [comment]
Addressed in https://github.com/openshift/openshift-docs/pull/40577
