### ISSUE TITLE
[rhacs-docs] Issue in file upgrading/upgrade-helm.adoc

### ISSUE THREAD

**Issue by boazmichaely** [openshift/openshift-docs#40282]
### Which section(s) is the issue in?
* Upgrading using Helm charts

### What needs fixing?
Typos:
Update **configuraition** files for the central-services Helm chart.
Update **configuraition** files for the secured-cluster-services Helm chart.

**Comment by gaurav-nelson** [comment]
@kcarmichael08 You can take this one next.

**Comment by boazmichaely** [comment]
Thanks for fixing
