### ISSUE TITLE
[enterprise-4.9] Issue in file machine_management/user_infra/adding-compute-user-infra-general.adoc

### ISSUE THREAD

**Issue by pjwebster** [openshift/openshift-docs#40296]
### Which section(s) is the issue in?
Each link to the platform specific instructions, ie "Adding compute machines to bare metal", is invalid. This seems to be the case going back to 4.8 and 4.7 documentation too

### What needs fixing?
Links need to point to the right location, or perhaps the target documents are missing altogether

**Comment by mburke5678** [comment]
@pjwebster Thanks for this issue. Can I ask you to check the links again? They seem to be working for me. Thanks!
