### ISSUE TITLE
[enterprise-4.9] Issue in file logging/config/cluster-logging-collector.adoc

### ISSUE THREAD

**Issue by lebrisg** [openshift/openshift-docs#40311]
### Which section(s) is the issue in?
1) Viewing logging collector pods
2) Advanced configuration for the log forwarder

### What needs fixing?
1)
Fluentd pods have been renamed collector in OpenShift Logging 5.3 (https://access.redhat.com/solutions/6611131).
=> Changes in Procedure: $ oc get pods --selector component=collector -o wide -n openshift-logging
=> Changes in Example output.
2)
Configmap name has changed from fluentd to collector.
=> Changes in Procedure / "4. Check that the new values are in the fluentd->collector config map:" $ oc extract configmap/collector --confirm

**Comment by cbremble** [comment]
Added to Jira: https://issues.redhat.com/browse/RHDEVDOCS-4308

**Comment by kalexand-rh** [comment]
This was fixed on https://issues.redhat.com/browse/RHDEVDOCS-3771.
