### ISSUE TITLE
[enterprise-4.9] Issue in file monitoring/configuring-the-monitoring-stack.adoc

### ISSUE THREAD

**Issue by hunter86bg** [openshift/openshift-docs#40368]
### Which section(s) is the issue in?
At https://docs.openshift.com/container-platform/4.9/monitoring/configuring-the-monitoring-stack.html#configuring-persistent-storage there is a warning about Prometheus memory consumption related to https://bugzilla.redhat.com/show_bug.cgi?id=1925061

### What needs fixing?
As https://bugzilla.redhat.com/show_bug.cgi?id=1925061 is fixed, the warning most probably can be removed .

**Comment by Amrita42** [comment]
Related PR https://github.com/openshift/openshift-docs/pull/39047

**Comment by Amrita42** [comment]
Yes we can as the fix is already implemented

**Comment by hunter86bg** [comment]
Closing as it was implemented
