### ISSUE TITLE
[enterprise-4.9] Issue in file service_mesh/v2x/ossm-threescale-webassembly-module.adoc

### ISSUE THREAD

**Issue by InfoSec812** [openshift/openshift-docs#40406]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.9/service_mesh/v2x/ossm-threescale-webassembly-module.html#prerequisites_ossm-threescale-webassembly-module

### What needs fixing?

The working/organization is confusing. It almost sounds like OpenID Connect is not supported, but we believe it actually is saying that OIDC is only supported on 3Scale >= 2.11.

**Comment by JStickler** [comment]
@dfennessy

**Comment by dfennessy** [comment]
> @dfennessy

:eyes:

**Comment by dfennessy** [comment]
Track here: https://issues.redhat.com/browse/THREESCALE-8071

**Comment by dfennessy** [comment]
Resolved in this PR: https://github.com/openshift/openshift-docs/pull/41328
