### ISSUE TITLE
[enterprise-4.6] Issue in file migration_toolkit_for_containers/installing-mtc.adoc

### ISSUE THREAD

**Issue by jaymiracola** [openshift/openshift-docs#40519]
### Which section(s) is the issue in?

Installing the legacy Migration Toolkit for Containers Operator on OpenShift Container Platform 4.2 to 4.5

### What needs fixing?

Step 4 mentions "Log in to your OpenShift Container Platform 3 cluster" and should be OpenShift Container Platform 4.

Step 6 mentions "You can ignore Error from server (AlreadyExists) messages. They are caused by the Migration Toolkit for Containers Operator creating resources for earlier versions of OpenShift Container Platform 3 that are provided in later releases." and again should be OpenShift Container Platform 4.

**Comment by apinnick** [comment]
@nunzy1 @RichardHoch 
Please check this. Thanks.
