### ISSUE TITLE
[enterprise-4.9] Issue in file authentication/managing_cloud_provider_credentials/cco-mode-sts.adoc

### ISSUE THREAD

**Issue by renatoppuccini** [openshift/openshift-docs#40543]
### Which section(s) is the issue in?
What are the permissions in AWS IAM the ccoctl need in order to create the credentials, s3 bucket, oidc and all resources?

### What needs fixing?
Explicit describe permissions needed for ccoctl to create credentials and oidc endpoint in aws.

**Comment by jeana-redhat** [comment]
Resolved in #44837
