### ISSUE TITLE
search widget misbehaves on anything other than 'latest' version of the documentation for docs.okd.io

### ISSUE THREAD

**Issue by nate-duke** [openshift/openshift-docs#40551]
### Which section(s) is the issue in?

all, at least for docs.okd.io.

### What needs fixing?

The in-page search widget only works for 'latest' docs. If you're browsing a specific version of the docs, say 4.9 for example and use the search widget no results will ever be returned. If you change the url to /latest/ from /4.9/ then the search widget will return results.

e.g. this is a search for 'routes' on 4.9 and latest
![image](https://user-images.githubusercontent.com/40432118/149334015-af89567c-713e-4c36-82a3-8ae6535f189d.png)

**Comment by nate-duke** [comment]
/remove-lifecycle rotten
/remove-lifecycle stale

This issue is still present.
![image](https://user-images.githubusercontent.com/40432118/172403425-c96e0ae6-e58c-4f67-bda1-1ce0cbf9be0e.png)

**Comment by bergerhoffer** [comment]
Confirmed that this is still an issue

/remove-lifecycle stale

@kalexand-rh Do you know who knows the most about our search that could investigate this? Seems like an important issue, unless we're only supporting the 'latest' version of OKD.

**Comment by PaulCapestany** [comment]
I'm new to these projects but I recently came across this search issue as well, okd documentation (e.g. 4.10, 4.11) returns no results for any search term when using the built-in search bar on [docs.okd.io](https://docs.okd.io/latest/welcome/index.html), whereas other versions (e.g. latest, 4.9) do indeed return what seem like expected search results

**Comment by nate-duke** [comment]
@kalexand-rh  I think the recent shuffle and redeploy of the docs sites has fixed this up.
![image](https://user-images.githubusercontent.com/40432118/195177340-08e0a089-38aa-404a-8d62-8e17b33d8271.png)
![image](https://user-images.githubusercontent.com/40432118/195177381-90ddb684-52da-4ffc-b919-c6d3ade49d0e.png)

**Comment by kalexand-rh** [comment]
I'm glad to hear that this has been fixed! I'm going to close this issue.
