### ISSUE TITLE
[rhacs-docs] Issue in file installing/install-ocp-operator.adoc for v3.67

### ISSUE THREAD

**Issue by jwilliams-shadowsoft** [openshift/openshift-docs#40576]
### Which section(s) is the issue in?
Installing: Installing by using an Operator: Admission controller settings table

### What needs fixing?
`admissionControl.contactImageScanners` incorrectly lists the key as accepting a boolean value. However, the only accepted values are shown in this message when I try to edit the object:

```
# * spec.admissionControl.contactImageScanners: Invalid value: "boolean": spec.admissionControl.contactImageScanners in body must be of type string: "boolean"
# * spec.admissionControl.contactImageScanners: Unsupported value: true: supported values: "ScanIfMissing", "DoNotScanInline"
```

**Comment by gaurav-nelson** [comment]
Fixed by https://github.com/openshift/openshift-docs/pull/40632
