### ISSUE TITLE
[enterprise-4.8] Issue in file service_mesh/v2x/ossm-create-mesh.adoc

### ISSUE THREAD

**Issue by yocum137** [openshift/openshift-docs#40665]
### Which section(s) is the issue in?

"Installing the Bookinfo application"

Step 11

### What needs fixing?
Add "-o wide" to verify that bookinfo project has been added to the smmr:

oc get smmr -n istio-system -o wide

**Comment by neal-timpe** [comment]
@ahardin-rh I left this team last year. I think @JStickler is the right person to assign this to.

**Comment by ahardin-rh** [comment]
@neal-timpe Oops! Thank you! Pulled your name from the file history, but I will be sure to cross-check assignments moving forward. :smile:
