### ISSUE TITLE
[enterprise-4.8] Issue in file service_mesh/v2x/upgrading-ossm-to-2-1.adoc

### ISSUE THREAD

**Issue by saurabhsadhale** [openshift/openshift-docs#40700]
### Which section(s) is the issue in?
[Upgrading to Red Hat OpenShift Service Mesh 2.1
](https://docs.openshift.com/container-platform/4.8/service_mesh/v2x/upgrading-ossm-to-2-1.html#ossm-upgrading-upgrade-2-1_upgrading-ossm-to-2-1)
Prerequisites

- You have the Red Hat OpenShift Service Mesh version 2.1.0  

### What needs fixing?
- You have the Red Hat OpenShift Service Mesh version 2.0 

We are upgrading from 2.0 to 2.1 version operator.

**Comment by JStickler** [comment]
Closing as NOTABUG, since you need to have the v2.1 Operator installed to be able to upgrade from 2.0 to 2.1.  Note that upgrading your Operator does not upgrade your SMCP.
