### ISSUE TITLE
Document that Custom Build Strategy is disabled by default and how to enable it

### ISSUE THREAD

**Issue by php-coder** [openshift/openshift-docs#4081]
Inspired by the question on IRC:
>tjololo> hi, is it possible to "enable" Custom Builds when you are using "oc cluster up". I'm trying to test a Custom Builder, but when I try to register the BuildConfig with custom as build strategy I get a error message saying: "build strategy Custom is not allowed."

It turns out that our documentation doesn't cover the current state of the Custom Build Strategy:
- nowhere is mentioned that this is disabled by default (and why)
- there is also no instructions how to enable it

I believe that *at least* the following places should be updated:
- https://docs.openshift.org/latest/dev_guide/builds/build_strategies.html#custom-strategy-options
- https://docs.openshift.org/latest/admin_guide/securing_builds.html#disabling-a-build-strategy-globally

Related issues:
- https://bugzilla.redhat.com/show_bug.cgi?id=1380462
- https://github.com/openshift/origin/pull/11411

CC @bparees @coreydaley

**Comment by bparees** [comment]
actually the doc clearly states that is it *not* disabled by default, so the question would be why is it disabled in oc cluster up?  That is a question for @csrwng 

```
By default, all users that can create builds are granted permission to use all build strategies (Docker, Source-to-Image, and Custom).
```

and i think this covers "instructions on how to enabled it":
https://docs.openshift.org/latest/admin_guide/securing_builds.html#restricting-build-strategies-to-a-user-globally  

(but again we claim it's enabled by default, so if it's not we need to sort that out).

**Comment by csrwng** [comment]
Actually it should not be (enabled by default):
https://bugzilla.redhat.com/show_bug.cgi?id=1380462
https://github.com/openshift/origin/pull/11411

**Comment by bparees** [comment]
assigning to @coreydaley then since the docs should have been updated when that change was put in.

**Comment by vrutkovs** [comment]
The docs are not updated yet, [Securing builds by strategies](https://docs.openshift.org/latest/admin_guide/securing_builds.html#overview) states:  
>By default, all users that can create builds are granted permission to use all build strategies (Docker, Source-to-Image, and Custom).

**Comment by bparees** [comment]
@vrutkovs yes that's why this issue is still open....
