### ISSUE TITLE
Weird CSS issue - No search bar visible on Safari

### ISSUE THREAD

**Issue by jeromeza** [openshift/openshift-docs#40909]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.9/welcome/index.html

### What needs fixing?
Search bar not visible in Safari - unable to search through documentation for key words as a result - only visible when on Chrome.

**VERSION:**
Safari v14.1.2 (16611.3.10.1.6)

**IMAGES:**
https://imgur.com/a/7A0awOc

**Comment by maxwelldb** [comment]
I'm experiencing the same issue. 

Safari 15.2 (17612.3.6.1.6)

**Comment by alishaIBM** [comment]
Same issue is seen in **Safari Version 15.3 ( 17612.4.9.1.8 )**

Document link used : https://docs.openshift.com/container-platform/4.9/welcome/index.html

On **Safari Version 15.3 ( 17612.4.9.1.8 )** : 

![image](https://user-images.githubusercontent.com/32256846/154225397-e3a70e2d-d342-4a73-a721-81f39f4c8106.png)

Search bar not visible. Unable to search through documentation for key words as a result.

Note : Search bar is visible in Chrome , Firefox.

FYI : @aireilly @nalhadef @maxwelldb

**Comment by alishaIBM** [comment]
Same issue is seen in **Safari Version 15.3 ( 17612.4.9.1.8 )**

Document link used : https://docs.openshift.com/container-platform/4.9/welcome/index.html

On **Safari Version 15.3 ( 17612.4.9.1.8 )** : 

![image](https://user-images.githubusercontent.com/32256846/154225397-e3a70e2d-d342-4a73-a721-81f39f4c8106.png)

Search bar not visible. Unable to search through documentation for key words as a result.

Note : Search bar is visible in Chrome , Firefox.

FYI : @aireilly @nalhadef @maxwelldb @wgordon17

**Comment by aireilly** [comment]
> Same issue is seen in **Safari Version 15.3 ( 17612.4.9.1.8 )**
> 
> Document link used : https://docs.openshift.com/container-platform/4.9/welcome/index.html
> 
> On **Safari Version 15.3 ( 17612.4.9.1.8 )** :
> 
> ![image](https://user-images.githubusercontent.com/32256846/154225397-e3a70e2d-d342-4a73-a721-81f39f4c8106.png)
> 
> Search bar not visible. Unable to search through documentation for key words as a result.
> 
> Note : Search bar is visible in Chrome , Firefox.
> 
> FYI : @aireilly @nalhadef @maxwelldb @wgordon17

@wgordon17 is working on a fix.

**Comment by maxwelldb** [comment]
@wgordon17 @aireilly Is this issue verified as fixing #42097?

(GitHub didn't auto-close this issue, for whatever reason.)

**Comment by wgordon17** [comment]
@maxwelldb Just confirmed, only fixed on a `resize` event. I'm pushing a new PR to hopefully fix it on first load as well 👍

**Comment by wgordon17** [comment]
Confirmed working page load now
