### ISSUE TITLE
[dedicated] Need to remove/rewrite section on managing templates/image-streams

### ISSUE THREAD

**Issue by sspeiche** [openshift/openshift-docs#4099]
There is a section that wrongly indicates end users can edit the `openshift` namespace to manage cluster wide image-streams and templates at https://docs.openshift.com/dedicated/getting_started/dedicated_administrators.html#gs-dedicated-admin-adding-or-removing-default-image-streams-and-templates

I'd recommend removing the section until the feature is enabled. Perhaps we could replace with some text that indicates that they can't.

fyi @spurtell

**Comment by ahardin-rh** [comment]
Closing per https://github.com/openshift/openshift-docs/pull/4101
