### ISSUE TITLE
[enterprise-4.6] Issue in file service_mesh/v2x/ossm-traffic-manage.adoc

### ISSUE THREAD

**Issue by mmv2010** [openshift/openshift-docs#41021]
### Which section(s) is the issue in?
Not sure if #Sidecar is the best part to include this.

### What needs fixing?
Handle protocol selection based on target service name selector for services hosted under Mesh
(https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/) 

For traffic gRPC default service http will not be sufficient due to the fact that the esrvice mesh will act like gRPC traffic flows as HTTP/1.1 which is not accurate.
This will help others having the issue that I have encountered, to fix the gRPC traffic through Route -> Gateway -> VirtualService correctly handled as gRPC rather then HTTP/1.1

Thank you
Hope this will help someone!
Regards,
Mihai

**Comment by JStickler** [comment]
@mmv2010 Could you provide more details around this issue?
What problem did you encounter?  If I'm reading this correctly, your gRPC traffic wasn't flowing as expected?
Was it due to an error in the docs? Or a configuration error? Or is this a docs enhancement request to provide additional information in the product docs?

**Comment by mmv2010** [comment]
Hello @JStickler ,

Yes, we had some issue with the traffic flow for gRPC. It was a while when I have opened this issue, I think the table from istio Protocol Selection should be also available under the documentation for all users will be able to review this and understand the protocol set based on name under service for example.
Route -> Gateway -> VirtualService for gRPC traffic , based on the virtualService I will reach service test-service with below config. (sample app runnining in container listening for gRPC on 8080 and 8081)

`kind: Service
apiVersion: v1
metadata:
  name: test-service
spec:
  ports:
    - name: http2-grpc
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: http-grpc
      protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    app: mmv
  type: ClusterIP`

The gRPC traffic will work on port 8081 - only when name is set as http2 instead of http.

If you consider that ProtocolSelection part containing the table is not needed, I have no problem to close this issue.

Thank you!
Mihai
