### ISSUE TITLE
[online] Issue in file rosa_policy/rosa-policy-process-security.adoc

### ISSUE THREAD

**Issue by thoward-rh** [openshift/openshift-docs#41188]
### Which section(s) is the issue in?
Backup and recovery section

### What needs fixing?
This document mentions that etcd is backed up by SRE, however I was also informed this is not the case for STS clusters. This should be updated.

**Comment by 0kashi** [comment]
Thanks @thoward-rh!  This has been noted.

**Comment by bmcelvee** [comment]
Hi @thoward-rh! Here's the PR introducing the fix: https://github.com/openshift/openshift-docs/pull/43997
