### ISSUE TITLE
Update rest api docs to include the content types

### ISSUE THREAD

**Issue by kalexand-rh** [openshift/openshift-docs#41241]
### Which section(s) is the issue in?

All of the rest api docs.

### What needs fixing?

Because these are automatically generated, it would do no good to update the files currently in the repo. For the 4.6+ docs, update the scripts to add the `:_content-type:` attributes, such as `:_content-type: ASSEMBLY`, to the generated files.

**Comment by jboxman** [comment]
@kalexand-rh afaict this is done:

```
// Automatically generated by 'openshift-apidocs-gen'. Do not edit.
:_content-type: ASSEMBLY
[id="api-index"]
= API index
ifdef::product-title[]
include::_attributes/common-attributes.adoc[]
endif::[]
```

**Comment by jboxman-rh** [comment]
@kalexand-rh afaict this is done:

```
// Automatically generated by ‘openshift-apidocs-gen’. Do not edit.
:_content-type: ASSEMBLY
[id=“api-index”]
= API index
ifdef::product-title[]
include::_attributes/common-attributes.adoc[]
endif::[]
```

**Comment by kalexand-rh** [comment]
Great! We might need a follow-up change because the API docs are failing spectacularly in Ganymede. I'll close this issue and open another one.
