### ISSUE TITLE
[enterprise-4.9] Issue in file updating/preparing-eus-eus-upgrade.adoc

### ISSUE THREAD

**Issue by vitus133** [openshift/openshift-docs#41270]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.9/updating/preparing-eus-eus-upgrade.html

### What needs fixing?
<h1>Performing to perform an EUS to EUS upgrade</h1>
to
<h1>Preparing to perform an EUS to EUS upgrade</h1>

**Comment by codyhoag** [comment]
@sagidlow FYI

**Comment by sagidlow** [comment]
https://github.com/openshift/openshift-docs/pull/41290 PR fixes this issue.
