### ISSUE TITLE
[enterprise-4.9] Issue in file storage/persistent_storage/persistent-storage-ocs.adoc

### ISSUE THREAD

**Issue by gpulido-redhat** [openshift/openshift-docs#41340]
### Which section(s) is the issue in?

Red Hat OpenShift Container Storage 

### What needs fixing?

The link to the "complete set of Red Hat OpenShift Data Foundation documentation identified below" is wrong. It has an additional "-us".

**Comment by stevsmit** [comment]
Hi,

I have fixed your issue at https://github.com/openshift/openshift-docs/pull/44145. I am merging this issue and closing it. Thanks!
