### ISSUE TITLE
Changing ode selectors at the project level

### ISSUE THREAD

**Issue by fgiloux** [openshift/openshift-docs#4147]
The documentation for changing node selectors [1] for projects is inaccurate. It needs to be done at the namespace level not the project one. Extract:
"You can edit a project, and change the openshift.io/node-selector value to override the default:"
Should read:
" You can edit a project namespace, and change the openshift.io/node-selector value to override the default:"

It can also be done through a command:

```
 # oc patch namespace myproject -p '{"metadata":{"annotations":{"openshift.io/node-selector":"region=infra"}}}'
```

[1] https://docs.openshift.com/container-platform/3.4/admin_guide/managing_projects.html#using-node-selectors

**Comment by gaurav-nelson** [comment]
Thank you @fgiloux. Tracking this in PR# #4765
