### ISSUE TITLE
Why Three masters ?

### ISSUE THREAD

**Issue by soufiane8096** [openshift/openshift-docs#4152]
Hi,

I'm trying to understand how work OpenShift, I read a sentence that I did not understand in documentation. Can someone give more explications about it : 
"If etcd is being installed on the master hosts, you must configure your cluster to use at least three masters. It cannot use only two masters, because etcd would not be able to decide which one is authoritative. The only way to successfully run only two masters is if you install etcd on hosts other than the masters." source : https://docs.openshift.com/container-platform/3.3/admin_solutions/master_node_config.html

If one of the three masters goes down, only two will work, so it's possible to work with 2 masters only ? 

Thank your for your help !

**Comment by juanluisvaladas** [comment]
Yes, 2 masters is the minimum for HA, 3 etcd is the minimum for HA.

The thing is if you're going to install  etcd and master on the same host normally you install masters on the 3 servers.

**Comment by vikram-redhat** [comment]
Hopefully @juanluisvaladas 's answer has helped you @soufiane8096 . I am going to close this issue. Please feel free to reopen if you don't have your answer.
