### ISSUE TITLE
[enterprise-4.9] Issue in file cicd/builds/understanding-buildconfigs.adoc

### ISSUE THREAD

**Issue by MarcNo** [openshift/openshift-docs#41545]
### Which section(s) is the issue in?

A customer says in "Understanding build configurations"[1] is unclear where to get more information for "BuildConfig object definition" callout #4.  They didn't know where to get more info.

> The source section defines the source of the build. The source type determines the primary source of input, and can be either Git, to point to a code repository location, Dockerfile, to build from an inline Dockerfile, or Binary, to accept binary payloads. It is possible to have multiple sources at once. See the documentation for each source type for details.

[1] https://docs.openshift.com/container-platform/4.9/cicd/builds/understanding-buildconfigs.html

### What needs fixing?

Perhaps include a link on "See the documentation for each source type for details." to the "Creating build inputs"[2] section.

[2] https://docs.openshift.com/container-platform/4.9/cicd/builds/creating-build-inputs.html

FWIW, the document flow is more clear on the equivalent access.redhat.com pages because of the clear table of contents on the left-hand side.

**Comment by stevsmit** [comment]
Thanks for submitting @MarcNo. I've merged the changes and I'm closing this issue. Please PM me if I can help further.
