### ISSUE TITLE
[enterprise-4.9] Issue in file operators/operator_sdk/golang/osdk-golang-tutorial.adoc

### ISSUE THREAD

**Issue by itewk** [openshift/openshift-docs#41565]
### Which section(s) is the issue in?

Bundling an Operator and deploying with Operator Lifecycle Manager -> Bundling an Operator

### What needs fixing?

Step 2 says to
```
Update your Makefile by setting the IMG URL to your Operator image name and tag that you pushed:
```

But the rest of the other instructions in that same doc say to just pass IMG as a command line argument vs messing with the Makefile.

This is partly an issue and partly a question. Why in this one step does it say to mess with the Makefile rather then just pass the command line argument? This came up when was trying to automate this process, its far more complicated to mess with the value in that stock Makefile then it is to just pass a command line argumnet. It would seem more consistent to have this step suggest the same approach as all the other steps and do:

```
make bundle IMG=<registry>/<user>/<operator_image_name>:<tag>
```

**Comment by sheriff-rh** [comment]
Hey Ian, thanks for opening this issue. I'm currently updating other aspects of the Operator SDK documentation and I see what you're talking about. It seems like combining steps 2 and 3 (step 3 being just a `make bundle`) would make this process much easier. I'll get started on a PR.

**Comment by sheriff-rh** [comment]
PR created. Let me know what you think!

**Comment by itewk** [comment]
LGTM
