### ISSUE TITLE
[enterprise-4.8] Issue in file cicd/gitops/configuring-an-openshift-cluster-by-deploying-an-application-with-cluster-configurations.adoc

### ISSUE THREAD

**Issue by azasa** [openshift/openshift-docs#41621]
### Which section(s) is the issue in?

Optional: If required, you can also apply taints and isolate the workloads on infrastructure nodes and prevent other workloads from scheduling on these nodes:

$ oc adm taint nodes -l node-role.kubernetes.io/infra
infra=reserved:NoSchedule infra=reserved:NoExecute

### What needs fixing?

When copying the command from The command box on cli it fails because of the double line and it run in the following way:

oc adm taint nodes -l node-role.kubernetes.io/infra
ra=reserved:NoSchedule infra=reserved:NoExecuteerror: at least one taint update is required
azasa@LAPTOP-58J6TMI6:~$ infra=reserved:NoSchedule infra=reserved:NoExecute

Instead copying manually the command all in one line it works

**Comment by bergerhoffer** [comment]
Section in question is https://docs.openshift.com/container-platform/4.9/cicd/gitops/configuring-an-openshift-cluster-by-deploying-an-application-with-cluster-configurations.html#run-argo-cd-instance-on-cluster_configuring-an-openshift-cluster-by-deploying-an-application-with-cluster-configurations

I believe that the command is probably just missing a "\" at the end to extend the command, or perhaps it could all be just brought onto the same line.

This will need QE review to be sure.

**Comment by JoeAldinger** [comment]
Hi @azasa thank you for submitting this bug. The changes have been made and successfully merged on 2.14.22.
