### ISSUE TITLE
Resolve confusion in networking/subnetting section

### ISSUE THREAD

**Issue by jeremyeder** [openshift/openshift-docs#4164]
Per comment thread here:  https://github.com/openshift/openshift-docs/pull/3881#pullrequestreview-32010481

We need to ensure that what's stated in the docs accounts for hard coded defaults.

**Comment by jeremyeder** [comment]
https://trello.com/c/CcjUgY2S/403-docs-resolve-confusion-in-networking-subnetting-section

**Comment by nak3** [comment]
At least following two values in https://docs.openshift.com/container-platform/3.4/install_config/install/advanced_install.html should be clear .

osm_cluster_network_cidr ... 10.128.0.0/14 or 10.1.0.0/16
osm_host_subnet_length ... 9 or 8

**Comment by bfallonf** [comment]
Thanks. PR #4171 seems to solve this. If there's any comments, we can make them there, or in followup. I'll close this issue.
