### ISSUE TITLE
[enterprise-4.9] Issue in file cicd/gitops/run-gitops-control-plane-workload-on-infra-nodes.adoc

### ISSUE THREAD

**Issue by mtulio** [openshift/openshift-docs#41810]
### Which section(s) is the issue in?

Page:
- CI/CD > [GitOps](https://docs.openshift.com/container-platform/4.9/cicd/gitops/gitops-release-notes.html)   > [Running Control Plane Workloads on Infra nodes](https://docs.openshift.com/container-platform/4.9/cicd/gitops/run-gitops-control-plane-workload-on-infra-nodes.html)

Section:
```
Adding infrastructure nodes > Procedure 1.
```

Typo:
```
$ oc label node ip-10-0-140-183.ec2.internal node-role.kubernetes.io/infra
error: at least one label update is required

$ oc label node ip-10-0-140-183.ec2.internal node-role.kubernetes.io/infra=
node/ip-10-0-140-183.ec2.internal labeled
```

### What needs fixing?

From:
```
oc label node <node-name> node-role.kubernetes.io/infra
```
To:
```
oc label node <node-name> node-role.kubernetes.io/infra=
```

**Comment by JoeAldinger** [comment]
Thanks @mtulio for submitting this issue. The typo was fixed and merged on 2.15.22.
