### ISSUE TITLE
Managing Container Logs should advise to use Journald for aggregated logging

### ISSUE THREAD

**Issue by jcantrill** [openshift/openshift-docs#4185]
We should advise users to use journald instead of JSON logging as:

* There is an outstanding BZ with terminated pods related to busy resources and JSON logs
* The additional metadata we can get
* Openshift installer sets it to journald by default? @sdodson ??

Need to work with @portante to rewrite:

* https://docs.openshift.com/container-platform/3.5/install_config/install/host_preparation.html#managing-docker-container-logs
* https://docs.openshift.com/container-platform/3.5/install_config/aggregate_logging.html#aggregate-logging-ansible-variables

**Comment by jcantrill** [comment]
@bmcelvee It is urgent we resolve this for 3.5

**Comment by sdodson** [comment]
> Openshift installer sets it to journald by default? @sdodson ??

Yes, in 1.5/3.5. It was json-file prior.

**Comment by vikram-redhat** [comment]
@jcantrill Since Brandi is out on PTO now, moving this to @ahardin-rh to look at.

**Comment by ahardin-rh** [comment]
@vikram-redhat @jcantrill I will take a look ASAP. Thanks!

**Comment by ahardin-rh** [comment]
Sorry for the delay. I opened  https://github.com/openshift/openshift-docs/pull/4205 to address this.
