### ISSUE TITLE
oadm new-project behaviour is different oc new-project

### ISSUE THREAD

**Issue by Jooho** [openshift/openshift-docs#4186]
Hi,

From this doc[1], in order to assign node-selector on new project, we have to use `oadm new-project myproject --node-selector='type=user-node,region=east' `. This command works well. 

However, nobody expect the behaviour is different from `oc new-project`. Usually, projectRequestTemplate is used to set default limitRange or quota when new project is created. The default project template is working well when I use `oc new-project` command but if I use `oadm new-project`, it is ignored. That's why a new project does not have limitRange or quota.

Therefore, we should notice it to people.
(By the way, I am not sure it is expected behavior or not now so I am going to open ticket on origin project too)

Example)
~~~ 
$ oadm new-project test-oadm --node-selector=region=infra
$ oc describe project tes-oadm
..
Node Selector:		region=infra
Quota:			<none>
Resource limits:	<none>

$ oc new-project test-oc 
$ oc describe project test-oc
...
Node Selector:	<none>
Quota:		<none>
Resource limits:
	Name:		core-resource-limits
	Type		Resource	Min	Max	Default
	----		--------	---	---	---
	Pod		memory		6Mi	1Gi	-
	Pod		cpu		200m	2	-
	Container	cpu		100m	2	300m
	Container	memory		4Mi	1Gi	200Mi
...
~~~

[1]https://docs.openshift.org/latest/admin_guide/managing_projects.html#setting-the-project-wide-node-selector

**Comment by php-coder** [comment]
Link to origin issue: https://github.com/openshift/origin/issues/13760
