### ISSUE TITLE
[enterprise-4.8] Issue in file logging/cluster-logging-external.adoc

### ISSUE THREAD

**Issue by mancubus77** [openshift/openshift-docs#41971]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.8/logging/cluster-logging-external.html#cluster-logging-collector-log-forward-syslog_cluster-logging-external
Syslog section doesn't have `inputs` reference, therefore it's not obvious if it can be used with Syslog forwarder. 
<img width="339" alt="image" src="https://user-images.githubusercontent.com/16170560/154248147-244a5e6e-12c9-46ea-a774-7d50f46da1be.png">

### What needs fixing?
Add input and number reference to YAML example for syslog forwarder.
<img width="339" alt="image" src="https://user-images.githubusercontent.com/16170560/154248147-244a5e6e-12c9-46ea-a774-7d50f46da1be.png">

**Comment by cbremble** [comment]
Added to Jira: https://issues.redhat.com/browse/RHDEVDOCS-4333
