### ISSUE TITLE
[enterprise-4.9] Issue in file logging/cluster-logging-external.adoc

### ISSUE THREAD

**Issue by kfryklund** [openshift/openshift-docs#42020]
### Which section(s) is the issue in?
This article is missing a section for version 5.3 of the Openshift Logging operator

### What needs fixing?
Needs to be updated to include "Supported log data output types in OpenShift Logging 5.3"

**Comment by cbremble** [comment]
Added to Jira: https://issues.redhat.com/browse/RHDEVDOCS-4332
