### ISSUE TITLE
[enterprise-4.8] Issue in file authentication/managing_cloud_provider_credentials/cco-mode-sts.adoc

### ISSUE THREAD

**Issue by gswallow** [openshift/openshift-docs#42083]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.8/authentication/managing_cloud_provider_credentials/cco-mode-sts.html#cco-ccoctl-configuring_cco-mode-sts

### What needs fixing?
"Obtain the Openshift Container Platform release image" is not a link. How does one do that?

**Comment by stevsmit** [comment]
This has been merged with https://github.com/openshift/openshift-docs/pull/44155. I am closing this issue. Thanks!
