### ISSUE TITLE
Default Docker subnet must not overlap with osm_cluster_network_cidr and openshift_portal_net

### ISSUE THREAD

**Issue by lpsantil** [openshift/openshift-docs#4209]
Ran into this with a customer.  Contact me off-line for case number.

**Affected Docs:**
https://github.com/openshift/openshift-docs/blob/master/admin_guide/sdn_troubleshooting.adoc
https://github.com/openshift/openshift-docs/blob/master/install_config/install/prerequisites.adoc
https://github.com/openshift/openshift-docs/blob/master/install_config/master_node_configuration.adoc
https://github.com/openshift/openshift-docs/blob/master/install_config/install/advanced_install.adoc
others?

**Issue:**
Customer picked a Pod subnet and CIDR that overlaps with the default Docker subnet (installation of which on all nodes is pre-requisite for the ansible installer). So, when the installer and the SDN plugin come to install the SDN configuration, they silently fail and then reach the point of the installer where it attempts to stand up the SDN one node at a time by restarting the atomic-openshift-node service. When the node service is executed, it doesn't find a a configured cluster network to work with. Hence: barf!

Customer & I noticed that they docker bridge network and the ansible hosts file configured Pod subnet were close but our CIDR math must have been off because we didn't expect them to clash, and, it seemed like the installer had "rationalized" the settings we had given to what we saw configured in `ip a` output.

**Workaround:**
To fix this pass docker the option --bip with a ip range that will not conflict. 
Example `/etc/sysconfig/docker-network` is a file that gets loaded to pass the docker service environmental variables. 
```
  $ cat /etc/sysconfig/docker-network 
   # /etc/sysconfig/docker-network
   DOCKER_NETWORK_OPTIONS="--bip=192.168.2.1/24"
```
**Resolution:**
So, the issue is mentioned here [0] but there isn't a red warning label like in other parts of the docs.
1) Give stronger warnings about choosing subnets in the above docs
2) Use the red warning icon used elsewhere in the docs.
3) Mention the work around in the sdn troubleshooting doc

**Comment by lpsantil** [comment]
See https://github.com/openshift/openshift-ansible/pull/3972

**Comment by bfallonf** [comment]
Thanks @lpsantil . I've reported a BZ for this issue: https://bugzilla.redhat.com/show_bug.cgi?id=1466118

Hopefully will be updated soon. I'll close this issue. Please let us know if there's anything else.
