### ISSUE TITLE
`{product-title}` is not substituted in published docs for sdn_troubleshooting.

### ISSUE THREAD

**Issue by lpsantil** [openshift/openshift-docs#4210]
**Affected Docs:**
https://github.com/openshift/openshift-docs/blob/master/admin_guide/sdn_troubleshooting.adoc
https://docs.openshift.com/container-platform/3.5/admin_guide/sdn_troubleshooting.html#debugging-steps
https://docs.openshift.com/container-platform/3.4/admin_guide/sdn_troubleshooting.html#debugging-steps

**Issue:**
`{product-title}` is not substituted in published docs.

**Workaround:**

**Resolution:**
Fix substitution.

**Comment by ahardin-rh** [comment]
Thank you! Closing this, as the issue is being addressed in https://github.com/openshift/openshift-docs/pull/4212
