### ISSUE TITLE
[enterprise-4.9] Issue in file authentication/managing_cloud_provider_credentials/cco-mode-sts.adoc

### ISSUE THREAD

**Issue by annelson-rh** [openshift/openshift-docs#42123]
### Which section(s) is the issue in?
 under "Configuring the Cloud Credential Operator utility"

Prerequisites
Obtain the OpenShift Container Platform release image.

### What needs fixing?
no instruction on how to obtain that. 

the release image is typically 'quay.io/openshift-release-dev/ocp-release:4.x.z-ARCH' but this is not called out anywhere. 

example: quay.io/openshift-release-dev/ocp-release:4.9.18-x86_64

**Comment by stevsmit** [comment]
I have merged this with https://github.com/openshift/openshift-docs/pull/44155. I am closing this issue. Thanks!
