### ISSUE TITLE
Architecture web console CLI Downloads screenshot needs updating for online

### ISSUE THREAD

**Issue by tiwillia** [openshift/openshift-docs#4215]
https://docs.openshift.com/online/architecture/infrastructure_components/web_console.html

The screenshot image 'CLI Downloads' needs to be updated for openshift-online. That page is wildly different in 3.5, which openshift online is using.

Here is a proper example:

![command_line_tools](https://cloud.githubusercontent.com/assets/5197933/25294337/af58e43e-26ac-11e7-92ef-7242f5797c37.png)

**Comment by tiwillia** [comment]
@ahardin-rh fyi

**Comment by ahardin-rh** [comment]
Updates addressed inn https://github.com/openshift/openshift-docs/pull/4263
