### ISSUE TITLE
Browser Requirements are possibly outdated

### ISSUE THREAD

**Issue by tiwillia** [openshift/openshift-docs#4218]
https://docs.openshift.com/online/architecture/infrastructure_components/web_console.html

Unsure if this is correct or not, but Fedora 23 and Windows 8 are the latest operating systems reportedly supported for accessing the webconsole.

@ahardin-rh fyi

**Comment by ahardin-rh** [comment]
@jwforres Can you please help us confirm? Thanks!

**Comment by ahardin-rh** [comment]
Closing this, since we now point to https://access.redhat.com/articles/2176281 as the source of truth
