### ISSUE TITLE
[enterprise-4.9] Issue in file installing/installing_sno/install-sno-installing-sno.adoc

### ISSUE THREAD

**Issue by omertuc** [openshift/openshift-docs#42214]
### Which section(s) is the issue in?
The entire document

### What needs fixing?
The entire document uses confusing terminology when discussing ISO files - it mixes up regular ISO files and "discovery" ISO files.

The two main section headers mention the word "Discovery ISO" even though in one of them it does not apply.

A "Discovery ISO" is purely an "Assisted Installer" concept. The discovery ISO should not be mentioned in any title and is merely an implementation detail of just the Assisted Installer method of installation. 

The section headers should instead be something along the lines of "Installing single node OpenShift using the Assisted Installer" and "Installing single node OpenShift using the OpenShift Installer".

The ISO created in the (currently named) "Generating the discovery ISO manually" section is *not* a "discovery" ISO - it's a regular RHCOS ISO with single node bootstrap-in-place ignition. There's no "discovery" process, the node simply installs itself, there's no assisted installer or assisted service that the node gets discovered to, so the word discovery is wrong and misleading.

I propose the following structure to this doc to eliminate this confusion:

3 sections, one for each of the two methods of installation, and another auxiliary section on how to format USB drives -

1) Assisted Installer section
	- Explains the entire process of how to install Single Node Openshift using the assisted installer
	- Only mentions the term "discovery ISO" in passing when it's relevant, it's just an implementation detail and should not be part of titles
	- Links to the "Formatting a USB drive" section mentioned below
	- Contains the "Monitoring the installation with the Assisted Installer" section as a subsection

2) Manual installation section
	- Explains the entire process of how to install Single Node Openshift using the regular OpenShift installer
	- Does not mention the term "Discovery ISO"
	- Links to the "Formatting a USB drive" section mentioned below
	- Contains the "Monitoring the installation manually" section as a subsection

3) A generic "Formatting a USB drive with an ISO image"
	- This section will be referenced from the two sections above. Alternatively it can just be duplicated into both of them, since it's rather small and it might lower the need to jump around when reading the doc.

**Comment by aireilly** [comment]
Created https://bugzilla.redhat.com/show_bug.cgi?id=2092791 @kalexand-rh can you assign this GH  issue to me please.

**Comment by aireilly** [comment]
Fixed in https://github.com/openshift/openshift-docs/pull/46277
