### ISSUE TITLE
[F5]  F5 routers don't have feature parity with HA proxy

### ISSUE THREAD

**Issue by juanluisvaladas** [openshift/openshift-docs#4222]
The docs say:

> The F5 router has feature parity with the HAProxy template router, and has additional features over the F5 BIG-IP® support in OpenShift Enterprise 2. Compared with the routing-daemon used in earlier versions, the F5 router additionally supports:

This statement is false: 
1- F5 routers don't support idling pods.
2- Re-encrypt routes don't work https://bugzilla.redhat.com/show_bug.cgi?id=1431655
(from now on I might be wrong @rajatchopra to confirm)
3- wildcard routes (route.spec.wildcardPolicy) aren't supported at all
4- Some TLS options (for instance roue.spec.tls.certificate) aren't supported either.
5- AlternateBackends aren't supported at all.

Until we get Rajat's confirmation I suggest to delete this statement as soon as possible https://github.com/openshift/openshift-docs/pull/4221. And once we are certain of which fetaures are available on the F5 write what the router is capable of.

**Comment by rajatchopra** [comment]
Almost correct on all the statements. We should remove that statement. It was probably put in at a time when they were matching, things have diverged over the releases.

**Comment by bfallonf** [comment]
Thanks @juanluisvaladas . I can see you've submitted a PR to fix this as well as a few other issues. I'll merge that, close this, and make a BZ for the other F5 issues. Please let us know if there's anything more for this.

**Comment by bfallonf** [comment]
BZ created for this issue: https://bugzilla.redhat.com/show_bug.cgi?id=1445571
