### ISSUE TITLE
[F5] Native and ramp node integration need major changes

### ISSUE THREAD

**Issue by juanluisvaladas** [openshift/openshift-docs#4223]
1- According to the documentation openshift supports native integration from F5 BIG IP 11.4 which isn't true
 
Native integration works only for 12.1
Ramp node integration works, if I'm not mistaken from 11.4 to 12.1. @rajatchopra could you please confirm versions? 

2- Missing license information for F5, the F5 integration requires the sdn plugin.

**Comment by rajatchopra** [comment]
Correct on both counts. The native integration was developed together with f5 Dev team and it has not been backported in either products.
i.e. f5 v12.1 and openshift version 3.4

Furthermore, the sdn services license is needed for the F5 to avail of the native integration.

**Comment by bfallonf** [comment]
Thanks!

BZ created for this issue: https://bugzilla.redhat.com/show_bug.cgi?id=1445571

I'll close this. Hopefully it can be worked on soon.

**Comment by pennpeng** [comment]
@juanluisvaladas Hi, would you share your docs，how to integration openshift and F5？

**Comment by juanluisvaladas** [comment]
@pennpeng If you work at Red Hat email me (you can see my email on my github profile). If not I'm sorry, but the docs I have contain confidential customer information and I cannot share them.
