### ISSUE TITLE
[F5] The statement "openshift-sdn as the network plug-plugin" is technically incorrect

### ISSUE THREAD

**Issue by juanluisvaladas** [openshift/openshift-docs#4224]
In openshift-docs/architecture/additional_concepts/f5_big_ip.adoc is mentioned several times "openshift-sdn".
There isn't such a thing as "openshift-sdn" network plugin. It's quite easy to understand  it means either redhat/ovs-subnet, redhat/ovs-multitenant and redhat/ovs-network-policy, which would  be the correct thing to mention.

Despite of being easy to understand it's not correct and must be fixed with some technically correct wording.

**Comment by bfallonf** [comment]
Thanks. BZ created for this issue: https://bugzilla.redhat.com/show_bug.cgi?id=1445571

I'll close this issue. Hopefully it will be looked at soon.
