### ISSUE TITLE
[enterprise-4.9] Specify which FCOS image to use for installation OKD

### ISSUE THREAD

**Issue by jldohmann** [openshift/openshift-docs#42330]
### Which section(s) is the issue in?

Installing FCOS by using an ISO image

### What needs fixing?

The docs currently point to the stable downloads page and instruct users to grab the latest version of FCOS, but they should be instructed to look up and use the image that `openshift-install coreos print-stream-json` points to.

**Comment by jldohmann** [comment]
Related issue: https://github.com/openshift/okd/issues/1020
Related PR: https://github.com/openshift/openshift-docs/pull/40912

**Comment by hector-vido** [comment]
I corrected the PR here in https://github.com/openshift/openshift-docs/pull/42706.
