### ISSUE TITLE
[enterprise-4.9] Issue in file serverless/admin_guide/serverless-ossm-setup.adoc

### ISSUE THREAD

**Issue by rhuss** [openshift/openshift-docs#42343]
### Which section(s) is the issue in?

* Creating a certificate to encrypt incoming external traffic

### What needs fixing?

> You have installed the OpenShift Serverless Operator and Knative Serving.

Needs to be replaced with:

> You have installed the OpenShift Service Mesh Operator and a `ServiceMeshControlPlane` resource in a namespace `istio-system`.  If you want to use the mTLS functionality, this must be enabled (field `.spec.security.dataPlane.mtls` set to `true`). OpenShift Serverless with Service Mesh only is supported for use with Red Hat OpenShift Service Mesh version 2.0.5 or higher.

-------

The following item in section "Integrating Service Mesh with OpenShift Serverless" needs to be removed:

* Create a ServiceMeshControlPlane object in the istio-system namespace. If you want to use the mTLS functionality, this must be enabled for the istio-system namespace.

In the "Prerequisite" section, the item about OpenShift ServiceMesh should be removed with the wording as above about the OpenShift Service Mesh Operator.

-----

In the admonition (1) of the gateway example, add some more explanation:

* (1)  Add the name of the secret holding the wildcard certificate that you have created in the first step. ("wildcard-certs" in the example above)

----

**Comment by rhuss** [comment]
The `ServiceMesh` Operator also required the Kiali and Jaeger Operators to be installed. I think instead of explaining how ServiceMesh should be installed here, we should probably better reference the Service Mesh documentation (also, this would avoid to become this section to be stale)

**Comment by rhuss** [comment]
@kenjiro are the proposed changes an accurate enhancement ?

**Comment by cbremble** [comment]
Added to Jira: https://issues.redhat.com/browse/SRVKS-950
