### ISSUE TITLE
Wrong command flag in Verifying node health section

### ISSUE THREAD

**Issue by loganmc10** [openshift/openshift-docs#42366]
### Which section(s) is the issue in?
https://docs.okd.io/latest/support/troubleshooting/verifying-node-health.html

### What needs fixing?
Under the section:  **3. Summarize CPU and memory usage for a specific node**
The suggested command is:
```
oc adm top node -l my-node
```
However this isn't right (the -l flag shouldn't be there), see the docs for the oc adm top node command:
```
Usage:
  oc adm top node [NAME | -l label] [flags]

Examples:
  # Show metrics for all nodes
  oc adm top node
  
  # Show metrics for a given node
  oc adm top node NODE_NAME
```

Tested on 4.9:
```
[loganmc10@fedoralogan ~]$ oc adm top node -l lmcnaugh-d17u05-b09.cloud.lab.eng.bos.redhat.com
error: metrics not available yet
[loganmc10@fedoralogan ~]$ oc adm top node lmcnaugh-d17u05-b09.cloud.lab.eng.bos.redhat.com
NAME                                               CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
lmcnaugh-d17u05-b09.cloud.lab.eng.bos.redhat.com   2154m        2%     25329Mi         13%       
```

**Comment by mburke5678** [comment]
@loganmc10 Thank you for pointing this out. Making the change: https://github.com/openshift/openshift-docs/pull/42778

**Comment by mburke5678** [comment]
PR merged
