### ISSUE TITLE
Custom Builds in the Creating Images pages

### ISSUE THREAD

**Issue by thrasher-redhat** [openshift/openshift-docs#4237]
There are a few references to custom builds and docker builds in the Creating Images/Testing S2I Images page, which are not going to be available for OpenShift Online.

> [The test script assumes you have already built the image you want to test. If required, first build the S2I image using: $ docker build -t <BUILDER_IMAGE_NAME>](https://docs.openshift.com/online/creating_images/s2i_testing.html#basic-testing-workflow)

The instructions for the basic testing workflow suggest using docker build.

> $ sti build file:///path-to-sample-app <BUILDER_IMAGE_NAME> <OUTPUT_APPLICATION_IMAGE_NAME>

This command needs a refresh.  The `sti`tool has since been renamed and can probably be rewritten using oc commands.

> [To set up an S2I image builder continuous integration system, define a Custom build and use the openshift/sti-image-builder image. This image executes all the steps mentioned in the Basic Testing Workflow section and creates a new S2I builder image.](https://docs.openshift.com/online/creating_images/s2i_testing.html#using-openshift-build-for-automated-testing)

The instructions and example in this section define a custom build.

Finally, [this entire page](https://docs.openshift.com/online/creating_images/custom.html) is not applicable to OpenShift Online and probably can be removed.

**Comment by ahardin-rh** [comment]
@tiwillia @Miciah thoughts?

**Comment by tiwillia** [comment]
In regards to the section on the sti tool, we can probably hold off on the refresh until after summit, as that affects all products. The rest of this seems right to me.

**Comment by Miciah** [comment]
"sti" was renamed to "s2i" July 2015: https://github.com/openshift/source-to-image/commit/20160b963a5a61dc89d44da23c945fccc0629696

**Comment by Miciah** [comment]
This is about building the image locally and then pushing to the cluster's registry, right? Is that prohibits? I thought we were just blocking the Docker build strategy.

**Comment by thrasher-redhat** [comment]
Not sure.  All I have for instructions is "Custom & Docker builds will be disabled".  Not sure if thats the commands themselves or something else.

**Comment by Miciah** [comment]
That refers to the build strategies.  That is, you cannot tell OpenShift to build something for you using the custom build strategy or Docker build strategy, but you can still build locally on your own machine, and AFAIK, you can then push your image to the image registry and start a pod using that.

**Comment by ahardin-rh** [comment]
Addressed via https://github.com/openshift/openshift-docs/pull/4286
