### ISSUE TITLE
doc for incremental builds

### ISSUE THREAD

**Issue by bparees** [openshift/openshift-docs#424]
need to document/provide sample of how to configure incremental builds for STI strategy.

@soltysh @danmcp fyi.

**Comment by bparees** [comment]
@CowboysFan if you have permission, please assign this to me.  thanks.

**Comment by soltysh** [comment]
@bparees you're again trying to steal my work :-P

**Comment by bparees** [comment]
All yours.

**Comment by soltysh** [comment]
@bparees please close since #465 got merged.

**Comment by bparees** [comment]
thanks @soltysh !
