### ISSUE TITLE
[enterprise-4.9] Issue in file nodes/edge/nodes-edge-remote-workers.adoc

### ISSUE THREAD

**Issue by DanielFroehlich** [openshift/openshift-docs#42402]
### Which section(s) is the issue in?
There is a section MISSING on network bandwidth requirements

### What needs fixing?
There is no information on the network bandwidth requirements of a remote worker node.
There is some informal evidence (see Red Hat internal gchat https://chat.google.com/room/AAAAUdu6spg/kNseOqdbuMA) that an empty and idle remote worker nodes creates 25-50 GiB data traffic per day. So it is not advisable to use mobile network for remote workers unless you have a really unlimited data plan.

**Comment by lucamaf** [comment]
absolutely need this kind of information formalized somewhere in the docs for the majority of customers in the Edge space
