### ISSUE TITLE
Rest API generator needs to update the attribute file location

### ISSUE THREAD

**Issue by kalexand-rh** [openshift/openshift-docs#42456]
Replace `include::modules/common-attributes.adoc[]` with `include::_attributes/common-attributes.adoc[]` in 4.6+ after https://github.com/openshift/openshift-docs/pull/42077 and its cherry-picks are merged.

Each folder also needs a symlink to the `_attributes` directory.

**Comment by jboxman-rh** [comment]
@kalexand-rh looks like this was done for the existing files in 71ed9522943c5bdc6a41c31fab83ee8eb38682d1. I can update the relevant templates such that this happens in all future releases:

```
// Automatically generated by 'openshift-apidocs-gen'. Do not edit.
:_content-type: ASSEMBLY
[id="node-apis"]
= Node APIs
ifdef::product-title[]
include::_attributes/common-attributes.adoc[]
endif::[]

toc::[]
```

**Comment by kalexand-rh** [comment]
Please do - I made that change expecting it to get immediately overwritten.
