### ISSUE TITLE
Incorrect information for globallyDisableIrqLoadBalancing

### ISSUE THREAD

**Issue by loganmc10** [openshift/openshift-docs#42468]
### Which section(s) is the issue in?
https://docs.okd.io/latest/scalability_and_performance/cnf-performance-addon-operator-for-low-latency-nodes.html#use-device-interrupt-processing-for-isolated-cpus_cnf-master

### What needs fixing?
The note says:
"When globallyDisableIrqLoadBalancing is set to **true**, device interrupts are processed across all CPUs as long as they don’t belong to a guaranteed pod."

That should say **false**. When globallyDisableIrqLoadBalancing is set to true, interrupts aren't processed on the isolated CPUs. In fact, earlier on the same page, it says:
"To configure Performance Addon Operator to disable global device interrupts for the isolated CPU set, set the globallyDisableIrqLoadBalancing field in the performance profile to true. When true, conflicting pod annotations are ignored. When false, IRQ loads are balanced across all CPUs."

**Comment by loganmc10** [comment]
This is still an issue that needs fixing

**Comment by sheriff-rh** [comment]
Hey Logan, I'll start working on this. Should have a pull request together shortly.

**Comment by sheriff-rh** [comment]
Pull request created, please review when you have a chance. Thanks Logan!
