### ISSUE TITLE
[enterprise-4.8] Issue in file nodes/nodes/nodes-nodes-garbage-collection.adoc

### ISSUE THREAD

**Issue by GauravKendre** [openshift/openshift-docs#42529]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.8/nodes/nodes/nodes-nodes-garbage-collection.html#nodes-nodes-garbage-collection-images_nodes-nodes-configuring

### What needs fixing?
Understanding how images are removed though garbage collection
it should be >> Understanding how images are removed through garbage collection
The word through

**Comment by mburke5678** [comment]
@GauravKendre Thanks for catching this!
