### ISSUE TITLE
Typo: Change `Kuberbetes` to `Kubernetes` on application health

### ISSUE THREAD

**Issue by sahildua2305** [openshift/openshift-docs#4256]
There's a typo on [this](https://docs.openshift.org/latest/dev_guide/application_health.html) page under headline - [Container Health Checks Using Probes](https://github.com/openshift/openshift-docs/blob/0ab326e0a433f2fd252c0bf5adf9ca9b922c8d21/dev_guide/application_health.adoc#container-health-checks-using-probes).

**Comment by ahardin-rh** [comment]
Thank you! This is now addressed via https://github.com/openshift/openshift-docs/pull/4259

**Comment by sahildua2305** [comment]
@ahardin-rh I submitted the PR here - #4257 🙂

**Comment by ahardin-rh** [comment]
@sahildua2305 Oh, thank you! I will close my PR and merge yours then. Thanks again! :smile:

**Comment by sahildua2305** [comment]
Thanks @ahardin-rh 😄
