### ISSUE TITLE
[enterprise-4.9] Issue in file serverless/develop/serverless-pingsource.adoc

### ISSUE THREAD

**Issue by turbolocust** [openshift/openshift-docs#42724]
### Which section(s) is the issue in?

"Creating a ping source"

### What needs fixing?

`spec.jsonData` of `PingSource` is not part of the schema definitions available in OpenShift 4.9. There is `data` and `dataBase64` available in versions _v1_ as well as _v1beta2_. The code snippets on the page still show **v1alpha2**, which may cause confusion when going through the tutorial. Since this documentation is available for 4.9 it should be updated.

**Comment by cbremble** [comment]
Created a Jira for this issue: https://issues.redhat.com/browse/SRVCOM-2035
