### ISSUE TITLE
Missing JWS/Tomcat S2I documentation for Online

### ISSUE THREAD

**Issue by Miciah** [openshift/openshift-docs#4272]
We should document using [the jws30-tomcat8-mongodb-persistent-s2i template](https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_examples/files/examples/v3.6/xpaas-templates/jws30-tomcat8-mongodb-persistent-s2i.json) for Online.

**Comment by Miciah** [comment]
Starter has the jws30-tomcat8-mongodb-persistent-s2i template.  Professional may have additional templates.  Dedicated has all the templates here: https://github.com/openshift/openshift-ansible/tree/master/roles/openshift_examples/files/examples/v1.4/xpaas-templates

We can link to the Red Hat JBoss Middleware for OpenShift documentation on Red Hat JBoss Web Server for OpenShift here: https://access.redhat.com/documentation/en-us/red_hat_jboss_middleware_for_openshift/3/html-single/red_hat_jboss_web_server_for_openshift/

We can link to the following webpage for an overview of Red Hat JBoss Middleware Services on OpenShift: https://www.openshift.com/features/technologies.html#xpaas

**Comment by tiwillia** [comment]
Starter appears only to have the **jws30-tomcat8-basic-s2i** template, not the jws30-tomcat8-mongodb-persistent-s2i template.

**Comment by Miciah** [comment]
Yes, sorry.  Thanks for the correction!
