### ISSUE TITLE
Missing Redis template documentation for Online

### ISSUE THREAD

**Issue by Miciah** [openshift/openshift-docs#4273]
We should document using [the redis-persistent template](https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_examples/files/examples/v3.6/db-templates/redis-persistent-template.json) for Online.

**Comment by Miciah** [comment]
Starter includes the redis-persistent template.  Dedicated includes redis-persistent template and redis-ephemeral.  Professional may include just redis-persistent or both.

We can link to the following webpage for the Red Hat Software Collections documentation for using Redis: https://access.redhat.com/documentation/en-us/red_hat_software_collections/2/html/using_red_hat_software_collections_container_images/database-images#redis

Some information about the Redis image is also available here: https://access.redhat.com/containers/?tab=documentation&platform=openshift#/registry.access.redhat.com/rhscl/redis-32-rhel7

**Comment by Miciah** [comment]
Looks like Starter and Professional now include both redis-ephemeral and redis-persistent.

**Comment by vikram-redhat** [comment]
Closing this as per previous comments.
