### ISSUE TITLE
Missing SSO template documentation

### ISSUE THREAD

**Issue by Miciah** [openshift/openshift-docs#4274]
We should document [the sso70-mysql-persistent template](https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_examples/files/examples/v3.6/xpaas-templates/sso70-mysql-persistent.json) for Online.

**Comment by Miciah** [comment]
I just learned that we will not provide templates for Starter.  We will only provide templates (or a template) for Professional.  We also provide templates in Dedicated.

We can link to the following webpage for documentation about Red Hat JBoss SSO for OpenShift: https://access.redhat.com/documentation/en-us/red_hat_jboss_middleware_for_openshift/3/html-single/red_hat_jboss_sso_for_openshift/

We can link to the following webpage for an overview of Red Hat JBoss Middleware Services on OpenShift: https://www.openshift.com/features/technologies.html#xpaas

**Comment by tiwillia** [comment]
Just to re-iterate, this template is **not** provided in starter and shouldn't be documented yet.

**Comment by ahardin-rh** [comment]
@Miciah @tiwillia Is this something that needs documented now?

**Comment by Miciah** [comment]
@ahardin-rh, the sso template is not expected to ship in Online Professional at this time.  It is only in Dedicated.

**Comment by ahardin-rh** [comment]
@Miciah Thank you! Should I go ahead and close this issue?

**Comment by Miciah** [comment]
I guess we can.  We have a lot of templates that are in Dedicated but aren't documented, so presumably either we are tracking the general issue somewhere or just don't care.

**Comment by ahardin-rh** [comment]
@Miciah We definitely care. This particular issue was originally filed about Online. Perhaps we need to consult with our content strategist @aheslin. I think there needs to be a larger discussion about the possibility of adding information about this and other templates to our docs, and how that information would be maintained/kept up to date.

**Comment by aheslin** [comment]
Are most of the templates the same as the SSO template? Like they exist in the current xPaaS docs? If so, let me think about this. With the xPaaS transition of a central team to individual MW teams, we would want to think about how we present and maintain the templates.

**Comment by ahardin-rh** [comment]
@aheslin Not 100% sure. :thinking:  Here are some related doc requests on templates:

- https://github.com/openshift/openshift-docs/issues/4273
- https://github.com/openshift/openshift-docs/issues/4272

**Comment by Miciah** [comment]
I filed this and those requests because the three templates identified in the requests were going to be available in Starter.  However, aside from Starter, we have dozens of templates that get installed in Dedicated, and they appear to be mostly undocumented.  Specifically, all the templates under [db-templates](https://github.com/openshift/openshift-ansible/tree/master/roles/openshift_examples/files/examples/v3.6/db-templates), [quickstart-templates](https://github.com/openshift/openshift-ansible/tree/master/roles/openshift_examples/files/examples/v3.6/quickstart-templates), and [xpaas-templates](https://github.com/openshift/openshift-ansible/tree/master/roles/openshift_examples/files/examples/v3.6/xpaas-templates) under https://github.com/openshift/openshift-ansible/tree/master/roles/openshift_examples/files/examples/v3.6 get installed on Dedicated, as do the image streams under [image-streams](https://github.com/openshift/openshift-ansible/tree/master/roles/openshift_examples/files/examples/v3.6/image-streams) and [xpaas-streams](https://github.com/openshift/openshift-ansible/tree/master/roles/openshift_examples/files/examples/v3.6/xpaas-streams) (so everything but cfme-templates should be installed).

**Comment by vikram-redhat** [comment]
I am closing this issue as with the migration of the xPaaS docs to other teams, this is not something we can handle right now.
