### ISSUE TITLE
Add java-1.8.0-openjdk-headless as dependency for ansible

### ISSUE THREAD

**Issue by andrewklau** [openshift/openshift-docs#4275]
Metrics requires the command `keytool` which is provided by `java-1.8.0-openjdk-headless` otherwise the new metrics playbook will fail

**Comment by bfallonf** [comment]
Thanks @andrewklau . I've created a BZ for this:

https://bugzilla.redhat.com/show_bug.cgi?id=1446428

Hopefully it will can rectified soon.

**Comment by andrewklau** [comment]
It's mentioned in openshift-ansible spec, but for those who are cloning the repository (origin users) it's not explicit:

https://github.com/openshift/openshift-ansible/blob/adcf22d4ecf506ebc7ea74346df0f35d4f7e688d/roles/openshift_metrics/tasks/install_support.yaml#L17
https://github.com/openshift/openshift-ansible/blob/2bba1017109db3fdc6aedac02e2069f79cea4c5f/openshift-ansible.spec#L25
