### ISSUE TITLE
Line break in Configuring Catalog Categories example results in example not working when copy/pasted

### ISSUE THREAD

**Issue by rhamilto** [openshift/openshift-docs#4276]
Need to change

```
description: "An open source programming language developed at Google in
      2007 by Robert Griesemer, Rob Pike, and Ken Thompson."
```

to

```
description: "An open source programming language developed at Google in 2007 by Robert Griesemer, Rob Pike, and Ken Thompson."
```

or

```
description: "An open source programming language developed at Google in " + 
"2007 by Robert Griesemer, Rob Pike, and Ken Thompson."
```

in https://github.com/openshift/openshift-docs/blob/master/install_config/web_console_customization.adoc#configuring-catalog-categories

to resolve a bug where copy/pasting the example customization doesn't work because of the line break.

cc: @codrinbucur

**Comment by codrinbucur** [comment]
I can verify that the suggested solutioni fixed the issue on OCP 3.4. Thanks Robb!
