### ISSUE TITLE
[enterprise-4.8] Issue in file installing/installing_bare_metal_ipi/ipi-install-overview.adoc

### ISSUE THREAD

**Issue by mancubus77** [openshift/openshift-docs#42792]
### Which section(s) is the issue in?
Picture need to be updated as it doesn't have information about BMC connectivity which is mandatory

### What needs fixing?
Network diagram needs to be updated
<img width="783" alt="image" src="https://user-images.githubusercontent.com/16170560/156665338-8827bef8-4d71-4135-b3e2-07f87f2c646a.png">

**Comment by johnwilkins** [comment]
There is a router on the right side of the diagram. Do you think it requires a BMC box?

**Comment by mancubus77** [comment]
The router box on the diagram is for access to OOB. BMC is usually located in a different network. So yes, it needs can be connected to same router via another line, or additional router.
 The idea of showing it on the diagram, is to make clear that the installer needs access to BMC from Baremetal network.
