### ISSUE TITLE
Update "apiversion" in example files

### ISSUE THREAD

**Issue by bfallonf** [openshift/openshift-docs#428]
As brought up in this PR: https://github.com/openshift/openshift-docs/pull/405/files , a lot of the example files have the parameter `apiversion: v1beta3' or something similar. These should probably be updated to `v1` when the time comes. 

Are there any other example parameters that need to be updated?

**Comment by adellape** [comment]
@bfallonf I figure we'll need to do a sweep over all examples after `v1`.

FYI @tnguyen-rh

**Comment by tnguyen-rh** [comment]
@bfallonf @adellape 
Sounds about right.  See also:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/api.md#v1beta3-conversion-tips

**Comment by tomason** [comment]
architecture/core_objects/kubernetes_model.adoc contains v1beta1 replicationController

**Comment by tnguyen-rh** [comment]
You can use command

    find . -name '*.adoc' | xargs grep -nHF apiVersion:

to see all apiVersion lines in the various .adoc files.  (Filter further to taste...)

**Comment by adellape** [comment]
https://github.com/openshift/openshift-docs/pull/467 took care of updating everything to v1, looks like just 2 stragglers (in `kubernetes_model` and `provisioned_projects`). I'm currently breaking up the former into logically-chunked new sections, so that'll be taken care of. I'll take care of the latter too then if no one gets it first.

**Comment by deads2k** [comment]
@stevekuznetsov can you convert https://docs.openshift.com/enterprise/3.0/admin_guide/selfprovisioned_projects.html#template-for-new-projects by hand?  We killed v1beta1 back around tag v0.6, so you'll have to sort out the intent.

**Comment by adellape** [comment]
Fixed by https://github.com/openshift/openshift-docs/pull/854 (now uses `oadm create-bootstrap-project-template` instead).
