### ISSUE TITLE
[enterprise-4.9] Issue in file networking/ovn_kubernetes_network_provider/migrate-from-openshift-sdn.adoc

### ISSUE THREAD

**Issue by nicklesimba** [openshift/openshift-docs#42969]
### Which section(s) is the issue in?
`Table 5. Performing a rollback to OpenShift SDN`

### What needs fixing?
Reboot Each Node in the Cluster

"As nodes reboot, the cluster assigns IP addresses to pods on the OVN-Kubernetes cluster network."

This should say, "on the Openshift-SDN network". I'm not sure since I'm new to migration, but it seems as if the table entry was mistakenly taken from `Table 4. Migrating to OVN-Kubernetes from OpenShift SDN`

**Comment by JoeAldinger** [comment]
Hi @nicklesimba thank you for filing this bug. The changes were made and successfully merged on 2.25.22.
