### ISSUE TITLE
no docs on liveness

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-docs#430]
I don't think there are any docs regarding setting up liveness probes / health checks.

Please refer to: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/liveness/README.md

**Comment by adellape** [comment]
This section needs to be updated and have examples added:

http://docs.openshift.org/latest/dev_guide/application_health.html

**Comment by sosiouxme** [comment]
Agree that the dev_guide/application_health page should have at least links if not examples.

Looks like the upstream docs have moved to https://github.com/kubernetes/kubernetes/tree/master/docs/user-guide/liveness

**Comment by nak3** [comment]
If you link to the kubernetes's doc, I think this one is better http://kubernetes.io/v1.0/docs/user-guide/liveness/

**Comment by sosiouxme** [comment]
fair point, built is better than the source :)

**Comment by bfallonf** [comment]
Some more context in the "Readiness Checks" section in the following:

https://github.com/openshift/origin/blob/master/examples/deployment/README.md

**Comment by bfallonf** [comment]
@thoraxe @sosiouxme @nak3 I made a PR about this issue #1070 

I pretty much just added the links to the Kube docs. Let me know if you see differently.

Thanks.
