### ISSUE TITLE
[enterprise-4.9] Issue in file service_mesh/v2x/ossm-vs-community.adoc

### ISSUE THREAD

**Issue by dudash** [openshift/openshift-docs#43016]
### Which section(s) is the issue in?
Service Mesh and Istio Differences - Multitenancy versus cluster-wide installations
https://docs.openshift.com/container-platform/4.9/service_mesh/v2x/ossm-vs-community.html#ossm-multitenant-install_ossm-vs-istio

### What needs fixing?
Mentions of Pilot and Galley, these were combined into istiod.

**Comment by JStickler** [comment]
Added this to OSSMDOC-549.

**Comment by JStickler** [comment]
Closed via #47562
