### ISSUE TITLE
[enterprise-4.9] Issue in file service_mesh/v2x/preparing-ossm-installation.adoc

### ISSUE THREAD

**Issue by dudash** [openshift/openshift-docs#43023]
### Which section(s) is the issue in?
Service Mesh 2.x -> Preparing to Install Service Mesh -> Supported Mixer Adapters
This section indicates that the Mixer adapter for 3scale is supported. However, the 2.1.1 release notes say:
"With Mixer now officially removed, OpenShift Service Mesh 2.1 does not support the 3scale mixer adapter."

https://docs.openshift.com/container-platform/4.9/service_mesh/v2x/preparing-ossm-installation.html#ossm-supported-configurations-adapters_preparing-ossm-installation

### What needs fixing?
Probably remove the section on supported mixer adapters. Maybe add something about the WebAssembly module.

**Comment by JStickler** [comment]
Closed via #44836
