### ISSUE TITLE
Unable to navigate correctly into documentation pages

### ISSUE THREAD

**Issue by gcecchi** [openshift/openshift-docs#43050]
### Which section(s) is the issue in?
Installation guide, several install method sections impacted.
For sure the part related to vSphere installation, See below

### What needs fixing?
I'm on Fedora 34 and I was going to review installation documentation on vSphere for Okd 4.9, but I notice that scrolling is severely broken both using firefox (97.0) and Chrome (98.0.4758.102) .
I go to the site:
https://docs.okd.io/4.9/installing/installing_vsphere/preparing-to-install-on-vsphere.html
and then I can scroll about until the section regarding download of installation program and then no way to scroll more.
With latest Chrome on WIndows 10 is worse...
I tried also other sections with the same behaviour and also using 4.8 instead of 4.9.
The only thing that works is using "latest" instead of the specific version...
[https://docs.okd.io/latest/installing/installing_vsphere/preparing-to-install-on-vsphere.html](https://docs.okd.io/4.9/installing/installing_vsphere/preparing-to-install-on-vsphere.html)

Using the "latest" word in chrome is all ok, while in firefox the top horizontal navigation bar is not correctly rendered, in the sense that it is put sort in the middle of the page while scrolling, covering the content ....

**Comment by mburke5678** [comment]
We should be back! Thanks for letting us know.
