### ISSUE TITLE
[enterprise-4.10] Issue in file installing/disconnected_install/installing-mirroring-disconnected.adoc

### ISSUE THREAD

**Issue by alexisph** [openshift/openshift-docs#43098]
### Which section(s) is the issue in?

Configuring credentials that allow images to be mirrored

### What needs fixing?

Steps 2 and 4 are the same

**Comment by bergerhoffer** [comment]
Thanks for letting us know - PR #44019 opened to address this.

**Comment by bergerhoffer** [comment]
PR has been merged, closing! Updates will be live soon

**Comment by bergerhoffer** [comment]
Actually closing this time :wink:
