### ISSUE TITLE
Document oc policy scc-review and scc-subject-review

### ISSUE THREAD

**Issue by php-coder** [openshift/openshift-docs#4319]
The very useful commands `oc policy scc-review` and `oc policy scc-subject-review` aren't documented at all. It would be extremely good to have them documented.

CC @soltysh @sdminonne in case you're interesting

**Comment by vikram-redhat** [comment]
@php-coder : These are documented in the release notes here: https://docs.openshift.com/container-platform/3.5/release_notes/ocp_3_5_release_notes.html#ocp-35-can-i-command-and-scc-review-command. Do we need more information?

**Comment by php-coder** [comment]
Yes, we need. It should be placed near SCC topics and also we need more examples and explanation about differences between these commands.

**Comment by vikram-redhat** [comment]
Thanks @php-coder. Created a bug to track this: https://bugzilla.redhat.com/show_bug.cgi?id=1449878. Closing this issue.
