### ISSUE TITLE
[enterprise-4.10] authentication/identity_providers/configuring-github-identity-provider.adoc: Callback URL example is missing the cluster name

### ISSUE THREAD

**Issue by pierreprinetti** [openshift/openshift-docs#43205]
### Which section(s) is the issue in?
Registering a GitHub application

### What needs fixing?

At point 5, the docs explain what to set the callback URL to in Github.

The general form is written as:

```plaintext
https://oauth-openshift.apps.<cluster-name>.<cluster-domain>/oauth2callback/<idp-provider-name>
```

and the example:

```plaintext
https://oauth-openshift.apps.example-openshift-cluster.com/oauth2callback/github/
```

In the example, there is no `<cluster-name>`: `example-openshift-cluster.com` does not contain a dot (`.`) and is therefore just the `cluster-domain`.

---

The example should probably be:

```plaintext
https://oauth-openshift.apps.openshift-cluster.example.com/oauth2callback/github/
```

In my example, `openshift-cluster` is the `cluster-name` and `example.com` is the `cluster-domain`.

---

Additionally, it is not clear whether the ending slash `/` should be included in the callback URL: the general form does not have it, while the example does (it ends with `github/`). If the two forms are equivalent, then the docs should probably pick one and be consistent in order to avoid confusion.

**Comment by pierreprinetti** [comment]
@bergerhoffer ?

**Comment by bergerhoffer** [comment]
@pierreprinetti thanks for reporting - the PR has been merged and updates will be live shortly!
