### ISSUE TITLE
[online] Issue in file rosa_policy/rosa-policy-responsibility-matrix.adoc

### ISSUE THREAD

**Issue by StevenBarre** [openshift/openshift-docs#43284]
### Which section(s) is the issue in?

Identity and access management

### What needs fixing?
>Manage organization administrators for Red Hat to grant access to OpenShift Cluster Manager. The cluster maanger is used to configure router options and provide service load balancer quota.

`maanger` is a typo and should be `manager`.

**Comment by bergerhoffer** [comment]
Marking this as a good candidate for Hacktoberfest.

https://docs.openshift.com/rosa/rosa_architecture/rosa_policy_service_definition/rosa-policy-responsibility-matrix.html#rosa-policy-identity-access-management_rosa-policy-responsibility-matrix

Whoever takes this: make the fix against the 'main' branch, and let me know if you have any questions!

**Comment by bobfuru** [comment]
I'll take this, @bergerhoffer! 😎

**Comment by bergerhoffer** [comment]
Closing, since the PR has been merged. Thanks @bobfuru!
