### ISSUE TITLE
[enterprise-4.10] Issue in file service_mesh/v1x/installing-ossm.adoc

### ISSUE THREAD

**Issue by 24601** [openshift/openshift-docs#43298]
### Which section(s) is the issue in?

Installing the OpenShift Elasticsearch Operator

### What needs fixing?

In the follow sentence, the template variable (`{product-dedicated}`) does not appear to be replaced, it should be replaced with the appropriate string. 

```
An account with the cluster-admin role. If you use {product-dedicated}, you must have an account with the dedicated-admin role.
```

**Comment by JStickler** [comment]
Fixed via https://github.com/openshift/openshift-docs/pull/44070
