### ISSUE TITLE
[enterprise-4.10] Issue in file release_notes/ocp-4-10-release-notes.adoc

### ISSUE THREAD

**Issue by braultatgithub** [openshift/openshift-docs#43318]
### Which section(s) is the issue in?
Section:
https://docs.openshift.com/container-platform/4.10/release_notes/ocp-4-10-release-notes.html#ocp-4-10-networking-columbiaville

### What needs fixing?
We don't support the INTEL 800 series, E810/Columbiaville, with OCP due to the large number of issues faced with the driver, so this statement is misleading.
Only with a Support Exceptions, is a customer allowed to use the NIC with the current OCP release: OCP 4.8, OCP 4.9, and OCP 4.10. Expectation is that full support will come in an upcoming z-stream that has yet to be identified.

**Comment by stevsmit** [comment]
@aireilly I see that you authored the original content at https://github.com/openshift/openshift-docs/pull/41279/files.

**Comment by aireilly** [comment]
We list E810 as supported devices under SRIOV, this was recently merged to OCP 4.8 - 4.10: https://docs.openshift.com/container-platform/4.10/networking/hardware_networks/about-sriov.html#supported-devices_about-sriov

PR was merged under https://github.com/openshift/openshift-docs/pull/44945 and LGTM from @xltian
