### ISSUE TITLE
[enterprise-4.9] Issue in file updating/updating-restricted-network-cluster.adoc

### ISSUE THREAD

**Issue by dadav** [openshift/openshift-docs#43384]
### Which section(s) is the issue in?
Creating the image signature config map

### What needs fixing?
The docs say:
`If you are upgrading from version 4.4.8 or later, you can use the oc CLI to create the config map.`

But not actually tell you how to do it with the `oc`-CLI.

**Comment by sagidlow** [comment]
Closing this issue as this was resolved with the merging of this PR: https://github.com/openshift/openshift-docs/pull/43897
