### ISSUE TITLE
Dangerous: Add warning, cron jobs may be executed more times than wanted

### ISSUE THREAD

**Issue by juanluisvaladas** [openshift/openshift-docs#4346]
From kubernetes docs:

https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/

```
Cron Job Limitations

A cron job creates a job object about once per execution time of its schedule. We say “about” because there are certain circumstances where two jobs might be created, or no job might be created. We attempt to make these rare, but do not completely prevent them. Therefore, jobs should be idempotent.

The job is responsible for retrying pods, parallelism among pods it creates, and determining the success or failure of the set of pods. A cron job does not examine pods at all.
```

We don't add a warning, this can be **very** dangerous

**Comment by vikram-redhat** [comment]
@juanluisvaladas - what can users do to make sure cron jobs are not executed more than once? We can add the warning, but can we provide users with an alternative?

**Comment by juanluisvaladas** [comment]
@vikram-redhat Schedule externally the job creation would be a suitable workaround, however I'm not sure it should be on the manual, I mean, it's pretty hacky.

If you ask me, as an OpenShift user a warning would be enough and then, I, the user, should think about how can I do it.

**Comment by vikram-redhat** [comment]
Thanks @juanluisvaladas. @soltysh - your thoughts on the text of the warning?

**Comment by juanluisvaladas** [comment]
The Kubernetes docs are Apache 2.0 and I see no flaws on their text, I'd use the same.

**Comment by soltysh** [comment]
👍 for using the same, it best describes how the controller is working.

**Comment by vikram-redhat** [comment]
@bmcelvee  - can you please add this warning and then close this issue?

**Comment by bmcelvee** [comment]
I opened https://github.com/openshift/openshift-docs/pull/4410 to add the warning. I'll close this issue and continue this conversation in the PR. Thanks!
