### ISSUE TITLE
[online] Issue in file rosa_architecture/rosa-life-cycle.adoc

### ISSUE THREAD

**Issue by mann1mal** [openshift/openshift-docs#43533]
### Which section(s) is the issue in?

Introduction to OpenShift > Support Lifecycle > [Life Cycle Dates](https://docs.openshift.com/rosa/rosa_architecture/rosa-life-cycle.html#rosa-life-cycle-dates_rosa-life-cycle)

### What needs fixing?

The table does not reference 4.10, which is GA (at least as far as I am aware).

**Comment by kalexand-rh** [comment]
Thanks for opening this issue! I see 4.10 in the table now, and the gap was filled with this [commit](https://github.com/openshift/openshift-docs/commit/c5df178184f197c029940fd273b3167aea1bee35).

I'm going to close this issue, but please keep pointing out issues that you find.
