### ISSUE TITLE
[enterprise-4.10] Issue in file installing/installing_openstack/installing-openstack-installer-ovs-dpdk.adoc

### ISSUE THREAD

**Issue by EmilienM** [openshift/openshift-docs#43556]
### Which section(s) is the issue in?
`Binding the vfio-pci kernel driver to NICs`

### What needs fixing?
Remove all `inline` content, this is invalid for ignition. The content has to be encoded first.

**Comment by maxwelldb** [comment]
This section was refactored out in 4.11, looks like.
