### ISSUE TITLE
[enterprise-4.10] Issue in file nodes/scheduling/nodes-scheduler-node-selectors.adoc

### ISSUE THREAD

**Issue by cloudxabide** [openshift/openshift-docs#43667]
### Which section(s) is the issue in?

Creating project-wide node selectors
https://docs.openshift.com/container-platform/4.10/nodes/scheduling/nodes-scheduler-node-selectors.html#nodes-scheduler-node-selectors-project_nodes-scheduler-node-selectors

### What needs fixing?
`To add a default project node selector:  

Create a project or edit an existing project to add the [openshift.io/node-selector](http://openshift.io/node-selector) parameter:  

$ oc edit project <name>`

You cannot edit a project (it is immutable). 
The verbiage should, instead, indicate you edit the namespace

Added
metadata:
  annotations:
    openshift.io/node-selector: location=remote
    
and tried to save the update, and received...

\# projects.project.openshift.io "linrevwelcomepage" was not valid:  

\# * metadata.annotations[openshift.io/node-selector]: Invalid value: "location=remote": field is immutable, try updating the namespace

**Comment by bergerhoffer** [comment]
Tested this and reproduced the issue. When attempting to edit the project to add the annotation, got the following error upon saving:

```
# projects.project.openshift.io "ah-test" was not valid:
# * metadata.annotations[openshift.io/node-selector]: Invalid value: "type=user-node,region=east": field is immutable, try updating the namespace
```
Confirmed that I was able to add the annotation when editing the namespace. The text above the procedure even mentions to edit the namespace (not project)

**Comment by bergerhoffer** [comment]
Opened #43667 to address. Thanks for reporting, @cloudxabide!

**Comment by bergerhoffer** [comment]
PR has been merged and updates will be live shortly. Closing!
