### ISSUE TITLE
Restore the content for adding new etcd member

### ISSUE THREAD

**Issue by mffiedler** [openshift/openshift-docs#4369]
The steps for adding a new etcd member or replacing a failed etcd member were removed in PR #4049 (related to https://bugzilla.redhat.com/show_bug.cgi?id=1405338#c12).

This issue is to track updating the content to be clear, complete and accurate and restoring the section to the documentation.

**Comment by vikram-redhat** [comment]
@mffiedler - I am gonna close this issue, as we already have https://github.com/openshift/openshift-docs/pull/4370 for tracking. If you feel otherwise, please reopen.
