### ISSUE TITLE
[online] update custom route hosts restriction

### ISSUE THREAD

**Issue by jiri-fiala** [openshift/openshift-docs#4378]
The custom route host template restriction for OpenShift Online needs to be updated; it's still valid for the *Starter* plan, though [there's](https://github.com/openshift/openshift-docs/blame/1912bf58d1e88804816153e21def67a4b739bf5e/dev_guide/routes.adoc#L227) the old Dev Preview template `<route-name>-<namespace>.44fs.preview.openshiftapps.com`, which should be replaced with `<route-name>-<namespace>.1d35.starter-us-east-1.openshiftapps.com`, or removed.

**Comment by vikram-redhat** [comment]
Fixed via: https://github.com/openshift/openshift-docs/pull/4396. Will be in the release next week. Thanks for reporting this @jiri-fiala .
