### ISSUE TITLE
core pod definition docs don't describe how limitranges are applied to pod at json level

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-docs#438]
http://docs.openshift.org/latest/architecture/core_objects/kubernetes_model.html#pod

This pod documentation mentions resource limits, but then links to upstream docs.

The pod example JSON doesn't include any resource limits.

http://docs.openshift.org/latest/dev_guide/limits.html

This doc describes limits and provides an example but doesn't indicate where it can be used.

https://github.com/openshift/training/blob/beta4/beta4/hello-pod.json#L24

This example from the beta training shows a limit range being applied to the pod.

**Comment by tpoitras** [comment]
The Resource Limits topic now describes how to create one: https://docs.openshift.com/enterprise/3.1/dev_guide/limits.html

http://docs.openshift.org/latest/architecture/core_objects/kubernetes_model.html#pod
^ This has changed to this: https://docs.openshift.com/enterprise/3.1/architecture/core_concepts/pods_and_services.html#pods
^ and this new one no longer links to upstream.

The example from beta training is now a 404, unforunately. 

Closing. I don't think it's an issue anymore.

Submitting https://github.com/openshift/openshift-docs/pull/1233
