### ISSUE TITLE
[enterprise-4.9] Issue in file release_notes/ocp-4-9-release-notes.adoc

### ISSUE THREAD

**Issue by rludva** [openshift/openshift-docs#43873]
### Which section(s) is the issue in?
RHBA-2022:0110 - OpenShift Container Platform 4.9.15 bug fix update

### What needs fixing?
The link to the RHSA is not working: "The RPM packages that are included in the update are provided by the [RHSA-2022:0109](https://access.redhat.com/errata/RHSA-2022:0109) advisory."

**Comment by JoeAldinger** [comment]
@rludva Thanks for submitting this bug. We've updated the documentation and merged on 3.30.22.
