### ISSUE TITLE
Probably need more info on CPU

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-docs#439]
Might want to include some of the info from:

https://github.com/GoogleCloudPlatform/kubernetes/blob/0e804b03a433fb56312d9fc7a2eba90310afc41e/docs/resources.md#processor-cycles

**Comment by tnguyen-rh** [comment]
Related discussion: https://github.com/openshift/openshift-docs/pull/458

**Comment by tnguyen-rh** [comment]
Related BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1267008

**Comment by vikram-redhat** [comment]
Thanks @tnguyen-rh . Since a BZ has been created to track this I am going to close this issue.
