### ISSUE TITLE
[enterprise-4.10] Issue in file virt/install/preparing-cluster-for-virt.adoc

### ISSUE THREAD

**Issue by jstakun** [openshift/openshift-docs#44055]
### Which section(s) is the issue in?
Configuring your cluster for OpenShift Virtualization

### What needs fixing?
First bullet on top of the page: 
"Your cluster must be installed on [on-premise bare metal](https://docs.openshift.com/container-platform/4.10/installing/installing_bare_metal/preparing-to-install-on-bare-metal.html#installing-bare-metal) infrastructure with Red Hat Enterprise Linux CoreOS (RHCOS) workers"
This sentence suggests whole cluster must be bare metal but per my discussion with OpenShift Virtualization dev team only worker nodes where we want to deploy and run OpenShift Virtualization must be bare-metal. Master nodes, and also some worker/infra nodes where we don't want to use OpenShift Virtualization doesn't have to be bare metal.

**Comment by apinnick** [comment]
That [section](https://docs.openshift.com/container-platform/4.10/virt/install/preparing-cluster-for-virt.html#virt-hardware-os-requirements_preparing-cluster-for-virt) has been reorganized. Do you think it still requires clarification?

**Comment by apinnick** [comment]
@fabiand 
What do you think?
