### ISSUE TITLE
OCP 3.3 metrics storage content snuck back into OCP 3.5/head

### ISSUE THREAD

**Issue by lpsantil** [openshift/openshift-docs#4411]
The formula & tables for given in 3.3 version of the docs for metrics storage planning reappeared in 3.5.  They are less clear than the content in the 3.4 docs.

https://github.com/openshift/openshift-docs/blob/enterprise-3.5/install_config/cluster_metrics.adoc#capacity-planning-for-openshift-metrics

**Comment by lpsantil** [comment]
So it looks like someone removed the 3.4 content from head.  :/  I don't know if that is better.

**Comment by bfallonf** [comment]
@lpsantil Thanks for this. I'm not actually sure what happened here. From what I can see, this is something that's changing every 3.X version.

@ahardin-rh @jeremyeder Have you got any thoughts here? I went through the history, and I was the one who changed it up for 3.4 with [this PR ](https://github.com/openshift/openshift-docs/pull/3499)and [this BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1384763). Should this be in 3.3 and 3.5 as well?

**Comment by lpsantil** [comment]
Ping! Can we get this & the larger issue resolved?  It seems that each tagged version of cluster_metrics.adoc is an independent branch now and that makes contributing corrections to it more fun than it has to be. :smile: I have another fix I want to get into the docs (replace the old Cassandra anti-pattern link with a current one) but I might have to submit 5 PRs if I want to get it into 3.3, 3.4, 3.5, 3.6 and master.

**Comment by vikram-redhat** [comment]
Hey @lpsantil - sorry for the delay. 

I am trying to get my head around this issue, and I apologize if I haven't understood something here.

Here are my questions:

* Is the issue that, this document [1], that contains the capacity planning information for cluster metrics in our docs, needs to change for every version of OCP that comes out and that is hasn't been changed? 

* As you point out, this is now missing in 3.4 docs, but it was clearer in those docs and should be put back in with correct figures?

* Are the figures in 3.3 to 3.6 docs correct or do they still need to change?

* Is your PR https://github.com/openshift/openshift-docs/pull/4413 for this correct in terms of guidance for these figures for 3.5? And 3.6? If we merge that into master, that will build against the origin docs. Would that be correct thing to do there?

* Lastly, for your last question, if changes are NOT branch specific, then we merge content into the master and then apply labels to reflect which branches (3.3 --> 3.6 or future) it should land in. This allows us to single source our content into multiple branches. However, if changes ARE branch specific, then they should be applied directly to that particular branch. I am not sure if your proposed PR for updates to the Cassandra anti-pattern will be branch specific or not, but hopefully this explanation helps.

Let me know the answers to these questions, and we can then work on them this week. Again, sorry for the delay.

[1] https://docs.openshift.com/container-platform/3.3/install_config/cluster_metrics.html#capacity-planning-for-openshift-metrics

**Comment by lpsantil** [comment]
> Is the issue that, this document [1], that contains the capacity planning information for cluster metrics in our docs, needs to change for every version of OCP that comes out and that is hasn't been changed?

No.

But the issue is a bit complex as it relates to the multibranch nature of the doc's history.  There are 3 document features and I'll use a table show where and how things deviate.
```
| Version | Calc A | Table Set A | Table Set B |
+---------+--------+-------------+-------------+
| 3.3     | X      | X           |             |
+---------+--------+-------------+-------------+
| 3.4     |        |             | X           |
+---------+--------+-------------+-------------+
| 3.5     | X      | X           | X           |
+---------+--------+-------------+-------------+
| 3.6     | X      | X           | X           |
+---------+--------+-------------+-------------+
| master  | X      | X           |             |
+---------+--------+-------------+-------------+
```

[Calc A](https://github.com/openshift/openshift-docs/commit/7d2369f9528ca3f37170a5f4374fcc6a8ae5c365#diff-ca2a8ff7fac87b827ba21942e6b79bfbL165)
[Table Set A](https://github.com/openshift/openshift-docs/commit/7d2369f9528ca3f37170a5f4374fcc6a8ae5c365#diff-ca2a8ff7fac87b827ba21942e6b79bfbL188)
[Table Set B](https://github.com/openshift/openshift-docs/commit/7d2369f9528ca3f37170a5f4374fcc6a8ae5c365#diff-ca2a8ff7fac87b827ba21942e6b79bfbL191)

> As you point out, this is now missing in 3.4 docs, but it was clearer in those docs and should be put back in with correct figures?

I stand by that statement.

> Are the figures in 3.3 to 3.6 docs correct or do they still need to change?

The calculations are [wrong](https://github.com/openshift/openshift-docs/pull/4413/files#diff-ca2a8ff7fac87b827ba21942e6b79bfbL168).

> Is your PR #4413 for this correct in terms of guidance for these figures for 3.5? And 3.6? If we merge that into master, that will build against the origin docs. Would that be correct thing to do there?

Lines [168](https://github.com/openshift/openshift-docs/pull/4413/files#diff-ca2a8ff7fac87b827ba21942e6b79bfbL168) & [171](https://github.com/openshift/openshift-docs/pull/4413/files#diff-ca2a8ff7fac87b827ba21942e6b79bfbL171) correct the calculations.  These changes are to correct poor math.

Lines [188-189](https://github.com/openshift/openshift-docs/pull/4413/files#diff-ca2a8ff7fac87b827ba21942e6b79bfbL188) & [251-252](https://github.com/openshift/openshift-docs/pull/4413/files#diff-ca2a8ff7fac87b827ba21942e6b79bfbL251) change the language to reflect (as of 3.5+) the internal metrics code changes and new default value for `METRICS_RESOLUTION` (30s).  Unfortunately, this change is 3.5+ specific.

> Lastly, for your last question, if changes are NOT branch specific, then we merge content into the master and then apply labels to reflect which branches (3.3 --> 3.6 or future) it should land in. This allows us to single source our content into multiple branches. However, if changes ARE branch specific, then they should be applied directly to that particular branch. I am not sure if your proposed PR for updates to the Cassandra anti-pattern will be branch specific or not, but hopefully this explanation helps.

Unfortunately, my changes and the issues I identified are a bit branch specific.  I don't feel I have the ownership over metrics to authoritatively speak to as what content *_should_* be included but I am more than happy to make it more accurate when I can.  Maybe @jcantrill , @mwringe or @jeremyeder could make that decision.  If it were up to me, from 3.4+, I would drop Calc A & Table Set A and move forward with Table Set B, alone, correcting references to the default `METRICS_RESOLUTION` value as needed.

> [1] https://docs.openshift.com/container-platform/3.3/install_config/cluster_metrics.html#capacity-planning-for-openshift-metrics

**Comment by vikram-redhat** [comment]
@bmcelvee - can you please bring this issue up in the next sprint meeting?

**Comment by vikram-redhat** [comment]
Closing - please see: https://github.com/openshift/openshift-docs/pull/4413#issuecomment-408743529
