### ISSUE TITLE
[enterprise-4.10] Issue in file scalability_and_performance/ztp-deploying-disconnected.adoc

### ISSUE THREAD

**Issue by mvazquezc** [openshift/openshift-docs#44124]
### Which section(s) is the issue in?
Configuring a managed cluster for a disconnected environment

### What needs fixing?

The example file for the registry config is missing the registry.mirror configuration.
The example output of the AgentServiceConfig is missing the `mirrorRegistryRef` property.

~~~
    [[registry]]
      location = <mirror_registry_url>  
      insecure = false
      mirror-by-digest-only = true
~~~

**Comment by stevsmit** [comment]
There is currently a PR open for this. I am closing this issue because I suspect it will be merged soon.
