### ISSUE TITLE
Openshift SNO DNS requirements

### ISSUE THREAD

**Issue by hetzbh** [openshift/openshift-docs#44122]
### Which section(s) is the issue in?
Install / Installing on a Single node / Preparing to install on a single node

### What needs fixing?

At the bottom of the page, the last requirement - "Cluster node" - I just checked with the SNO assisted installer, and it seems that "Cluster node" is not needed any more.

**Comment by stevsmit** [comment]
I have merged this fix and am closing this issue. Thanks for submitting.
