### ISSUE TITLE
[enterprise-4.9] Issue in file post_installation_configuration/machine-configuration-tasks.adoc

### ISSUE THREAD

**Issue by vdrvergara** [openshift/openshift-docs#44228]
### Which section(s) is the issue in?
Applied butane config to change /etc/chrony.conf, and permission rendered was 416 instead of 644.

### What needs fixing?
Include butane version that works. The version in the docs has a bug.

**Comment by jldohmann** [comment]
@vdrvergara what version of Butane are you using?

**Comment by vdrvergara** [comment]
I was using the latest, the permission should be the 420, but instead was rendered 416. The last time I checked the problem was solved.
