### ISSUE TITLE
[enterprise-4.8] Issue in file security/compliance_operator/compliance-operator-raw-results.adoc

### ISSUE THREAD

**Issue by thomaswatts** [openshift/openshift-docs#44285]
### Which section(s) is the issue in?

The issue is in step 4, "After the pod is running, download the results:"

### What needs fixing?

The notice under this step reads:

> Spawning a pod that mounts the persistent volume will keep the claim as Bound. If the volume’s storage class in use has permissions set to ReadWriteOnce, the volume is only mountable by one pod at a time. You must delete the pod upon completion, or it will be possible for the Operator to schedule a pod and continue storing results in this location.

It should probably instead read (emphasized change below):

> Spawning a pod that mounts the persistent volume will keep the claim as Bound. If the volume’s storage class in use has permissions set to ReadWriteOnce, the volume is only mountable by one pod at a time. You must delete the pod upon completion, or it will **NOT** be possible for the Operator to schedule a pod and continue storing results in this location.

**Comment by ahardin-rh** [comment]
@thomaswatts Great catch! The fix is now merged. Thanks for taking the time to report this issue and help us improve the docs!
