### ISSUE TITLE
Unclear phrase in overcommit.adoc

### ISSUE THREAD

**Issue by codrinbucur** [openshift/openshift-docs#4428]
I find this phrase from overcommit.adoc hard to understand:

"It places pods on nodes with consideration to the pods' compute resource requests and nodes' available capacity to find for each pod the node that provides the best fit."

Can it be rewritten in a more clear fashion?

**Comment by bfallonf** [comment]
Thanks @codrinbucur . I've created #4439 . Let me know if you have any further thoughts, but for now I'll close this issue.

**Comment by codrinbucur** [comment]
@bfallonf Thanks! That was quick. The edits look good and clearer.
