### ISSUE TITLE
Docs for OCP should point to supported integration matrix

### ISSUE THREAD

**Issue by etsauer** [openshift/openshift-docs#4431]
Something like the following should be linked/discoverable from docs.openshift.com. Perhaps in the release notes?

https://access.redhat.com/articles/2176281

**Comment by bfallonf** [comment]
Thanks @etsauer . I've added this to the list of questions to ask yourself when installing and created a PR:

https://github.com/openshift/openshift-docs/pull/4438

Let me know if there's any thoughts. I'll close this issue.
