### ISSUE TITLE
[enterprise-4.10] Issue in file networking/routes/route-configuration.adoc

### ISSUE THREAD

**Issue by blues-man** [openshift/openshift-docs#44450]
### Which section(s) is the issue in?
[Creating a route through an Ingress object](https://docs.openshift.com/container-platform/4.10/networking/routes/route-configuration.html#nw-ingress-creating-a-route-via-an-ingress_route-configuration)

### What needs fixing?

Clarifying Ingress usage by adding a section and/or example that indicates:

- an ingress requires the user specify an explicit host name (unlike a route)
- the user can use `{anything}.{cluster ingress domain}` to take advantage of the cluster's `*.{cluster ingress domain}` wildcard DNS record and serving certificate or otherwise must ensure that there is a DNS record for the chosen host name.

**Comment by ahardin-rh** [comment]
@blues-man Thanks again for your feedback! The fix is now merged.
