### ISSUE TITLE
Image registry url in Online docs is incorrect

### ISSUE THREAD

**Issue by siamaksade** [openshift/openshift-docs#4454]
The integrated image registry url in the OpenShift Online docs refers to the "preview" url and needs to get updated to the url after GA:
https://docs.openshift.com/online/dev_guide/managing_images.html#accessing-the-internal-registry

Currently
```
$ docker login -u <user_name> -e <email_address> \
    -p <token_value> https://registry.preview.openshift.com
```

Should be
```
$ docker login -u <user_name> -e <email_address> \
    -p <token_value> https://registry.starter-us-east-1.openshift.com
```

**Comment by ahardin-rh** [comment]
Addressed via https://github.com/openshift/openshift-docs/pull/4455 and the link is also fixed on the web console after discussion with the Online team.
