### ISSUE TITLE
[enterprise-4.9] Issue in file rest_api/operator_apis/ingresscontroller-operator-openshift-io-v1.adoc

### ISSUE THREAD

**Issue by awaisafzalbaig** [openshift/openshift-docs#44572]
### Which section(s) is the issue in?
The description of .spec.clientTLS.clientCA does not clearly mention the name of the key that should be used while creating configmap in openshift-config

### What needs fixing?
Can you please insert the name of the key that should be used while creatig the configmap. My suggestion of the description is below

"_clientCA specifies a configmap containing the PEM-encoded CA certificate bundle that should be used to verify a client’s certificate. The administrator must create this configmap, from file, in the openshift-config namespace with the name of the key ca-bundle.pem and the value is the certificate file._"

**Comment by jboxman-rh** [comment]
Hi @awaisafzalbaig

This information is actually derived from the OCP OpenAPI spec; This would need to get fixed in the https://github.com/openshift/api repo.
