### ISSUE TITLE
[enterprise-4.10] Issue in file networking/hardware_networks/using-pod-level-bonding.adoc

### ISSUE THREAD

**Issue by zhangzepo** [openshift/openshift-docs#44625]
### Which section(s) is the issue in?
Error from server: error when creating "vf_bonding.yaml": admission webhook "multus-validating-config.k8s.io" denied the request: configuration string is not in JSON format

### What needs fixing?
yaml format

**Comment by jboxman-rh** [comment]
cc @tmulquee
