### ISSUE TITLE
will need documentation on "dividing" nodes into different "sections" for security

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-docs#447]
for example, if some nodes are "secure" and other nodes are "insecure", we can currently label the nodes to ensure workload placement, but we should include some docs on, for example, how to block SDN traffic between these nodes but not to master...

**Comment by thoraxe** [comment]
We would need "specific" docs for SDN versus an explanation of how customers can actually set up standard networking without SDN and block traffic appropriately.


lots of diagrams will be needed.

**Comment by thoraxe** [comment]
also, the "physical" interfaces connected to the SDN will need to have unique IP addresses even if their nodes are on separate networks.

In other words, two nodes cannot have 192.168.2.7 as the IP address for their SDN interfaces.

**Comment by tnguyen-rh** [comment]
Is this functionality provided by the `multitenant` SDN plug-in?  See: https://docs.openshift.org/latest/architecture/additional_concepts/sdn.html

**Comment by thoraxe** [comment]
Not entirely. They are related but the multitenant SDN plugin doesn't provide everything. It just provides project isolation.

**Comment by ahardin-rh** [comment]
@thoraxe Resurrecting this discussion. :ghost: Is this still valid? If so, I can create a docs BZ for better tracking.

**Comment by adellape** [comment]
Closing this for now due to inactivity, but feel free to reopen.

@knobunc FYI on this in case you have any thoughts from the Networking team on how it could be addressed.
