### ISSUE TITLE
[enterprise-4.10] Issue in file installing/installing_sno/install-sno-installing-sno.adoc

### ISSUE THREAD

**Issue by dantrainor** [openshift/openshift-docs#44725]
### Which section(s) is the issue in?
Generating the discovery ISO manually, Step 5

### What needs fixing?
The curl command used doesn't use the -L flag, but $ISO_URL returns a 302.  Re-running with the -L flag follows the 302.

**Comment by kelbrown20** [comment]
This issue was fixed in #45155
Live documentation: https://docs.openshift.com/container-platform/4.10/installing/installing_sno/install-sno-installing-sno.html#generating-the-discovery-iso-manually_install-sno-installing-sno-with-the-assisted-installer
Setting to close
