### ISSUE TITLE
[enterprise-4.10] Issue in file security/pod-vulnerability-scan.adoc

### ISSUE THREAD

**Issue by cloudxabide** [openshift/openshift-docs#44721]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.10/security/pod-vulnerability-scan.html#security-pod-scan-cso_pod-vulnerability-scan

### What needs fixing?
Should we replace "Container Security Operator" with "Red Hat Quay Container Security Operator"? (as CSO is not available)

**Comment by bergerhoffer** [comment]
CC @stevsmit

**Comment by stevsmit** [comment]
Merged on 4-28. Thanks!
