### ISSUE TITLE
[enterprise-4.10] Issue in file networking/nw-ingress-controller-endpoint-publishing-strategies.adoc

### ISSUE THREAD

**Issue by rchakode** [openshift/openshift-docs#44731]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.10/networking/nw-ingress-controller-endpoint-publishing-strategies.html#nw-ingress-controller-endpoint-publishing-strategies_nw-ingress-controller-endpoint-publishing-strategies

### What needs fixing?
The IP address `193.10.0.10` does match any IP addresses on the mentionned graphic

**Comment by bergerhoffer** [comment]
This has been fixed via #44539. Closing!
