### ISSUE TITLE
[enterprise-4.9] Issue in file architecture/architecture-installation.adoc

### ISSUE THREAD

**Issue by EricArrakis** [openshift/openshift-docs#44741]
### Which section(s) is the issue in?
In "[Supported platforms for OpenShift Container Platform clusters](https://docs.openshift.com/container-platform/4.9/architecture/architecture-installation.html#supported-platforms-for-openshift-clusters_architecture-installation)"

### What needs fixing?
OpenStack 13 is listed as a supported platform for OCP 4.9 IPI.  We dropped support for 13 in 4.9.  4.9 AND 4.10 only supports OSP 16.1 and 16.2  We may also want to specify in the UPI section which versions of OSP we support (16.1/16.2)

**Comment by maxwelldb** [comment]
All done.
