### ISSUE TITLE
[enterprise-4.9] Issue in file logging/cluster-logging-uninstall.adoc

### ISSUE THREAD

**Issue by pwcazenave** [openshift/openshift-docs#44808]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.9/logging/cluster-logging-uninstall.html

### What needs fixing?

The steps say to remove the `openshift-operators-redhat` project followed by a step to optionally delete the PVCs. I just did this and the removal of the `openshift-operators-redhat` project automatically deleted the PVCs since our `StorageClass` default `reclaimPolicy` is `Delete`.

It feels like the order of the steps should put the warning/section on deleting the PVCs before the step on deleting the `openshift-operators-redhat` project.

**Comment by cbremble** [comment]
Added to Jira: https://issues.redhat.com/browse/RHDEVDOCS-4331

**Comment by kalexand-rh** [comment]
Since this issue has been moved to [Jira](https://issues.redhat.com/browse/RHDEVDOCS-4331), I'm closing this issue.
