### ISSUE TITLE
[enterprise-4.10] High Availability options in CNV documentation belong to OpenShift core

### ISSUE THREAD

**Issue by peterclauterbach** [openshift/openshift-docs#44884]
### Which section(s) is the issue in?
Additionally, there are three options to maintain high availability (HA) of virtual machines:

### What needs fixing?

This section seems bolted in here.  This is really is an OpenShift topic, and the VMs just play along with that the cluster has set up.
I don't know if this section replicated elsewhere, but it should be converged with the bigger OpenSHift story.
Buried in here, it looks like we are doing our own thing for visualization.

**Comment by apinnick** [comment]
@peterclauterbach 
We are currently restructuring the installation requirements ([CNV-17405](https://issues.redhat.com/browse/CNV-17405)) I will add your comment so that it is included in the PR.

**Comment by apinnick** [comment]
@fabiand 
Should we request that the HA options be moved to OpenShift docs? Or leave it where it is and add a note?

Note: I'm not sure there is any logical place to move the information. When I searched for HA, I found info scattered in several different places. We might have no choice but to leave it here.

**Comment by fabiand** [comment]
I agree with Peter that it's relevant for OCP.

I'd restructure and create the section as part of CNV, and then request the move to OCP.

**Comment by apinnick** [comment]
Updated description of this issue: The high availability options in CNV docs ([Preparing your OpenShift cluster for OpenShift Virtualization](https://docs.openshift.com/container-platform/4.10/virt/install/preparing-cluster-for-virt.html)) should be moved to OpenShift core documentation.

Screenshot showing the relevant text:
![image](https://user-images.githubusercontent.com/31725355/169087923-03922590-e40b-4a28-951e-e9268745bad2.png)

**Comment by apinnick** [comment]
@kalexand-rh 
I created [OSDOCS-3750](https://issues.redhat.com/browse/OSDOCS-3750) for this issue.
