### ISSUE TITLE
[enterprise-4.10] Issue in file machine_management/user_infra/adding-compute-user-infra-general.adoc

### ISSUE THREAD

**Issue by avishayt** [openshift/openshift-docs#44916]
### Which section(s) is the issue in?
All sections

### What needs fixing?
Links to more information on adding compute machines in each platform are broken

**Comment by mburke5678** [comment]
@avishayt I see that the links are working for me. They are very slow at the moment. But they work. can I ask you to re-check the links? 

Thank you,
Michael

**Comment by avishayt** [comment]
Seems to work now.  Previously I got 404 errors.  Thanks.
