### ISSUE TITLE
Disconnected installation is not being pusblished in https://docs.openshift.org/latest/welcome/index.html

### ISSUE THREAD

**Issue by jtudelag** [openshift/openshift-docs#4494]
Disconnected installation is not being published in https://docs.openshift.org/latest/welcome/index.html,
although is present in the repo:

https://github.com/openshift/openshift-docs/blob/master/install_config/install/disconnected_install.adoc

**Comment by vikram-redhat** [comment]
Hi @jtudelag - yes that is correct. The disconnected installation guide is enterprise only.
