### ISSUE TITLE
Nuage SDN doc could do with a tidy up

### ISSUE THREAD

**Issue by nstrug** [openshift/openshift-docs#4495]
The Nuage SDN documentation e.g. https://docs.openshift.com/container-platform/3.5/install_config/configuring_nuagesdn.html could do with a tidy up. The page does not explain what Nuage is or why I would want or need to use it in preference to the default SDN. The page also uses undefined and unlinked initialisms (VSP, VSD). In general, the page seems to be written with a target audience that is already very familiar with Nuage in mind, which I think is an incorrect assumption.

**Comment by ahardin-rh** [comment]
@nstrug Thanks! I will start a PR soon to make some improvements. I will try to locate a Nuage SDN expert to provide some guidance.
