### ISSUE TITLE
[enterprise-4.10] Issue in file logging/cluster-logging-release-notes.adoc

### ISSUE THREAD

**Issue by arasyor** [openshift/openshift-docs#44965]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.10/logging/cluster-logging-release-notes.html#cluster-logging-supported-versions
https://docs.openshift.com/container-platform/4.8/logging/cluster-logging-release-notes.html#openshift-logging-supported-versions

### What needs fixing?
In OCP 4.8 documents, RHOL version matrix says that RHOL 5.3 is supported for OCP 4.8. But the same matrix for OCP 4.10 it says that RHOL 5.3 is not supported for OCP 4.8. We made RHOL operator upgrades to version 5.3 from 4.6 for our OCP 4.8 clusters relying on this document and Fluentd ignored .pos files and started to read all logs, caused high load on elasticsearch.

As we investigated this issue, there was an "outstanding work" on Fluentd below. According to this work, .pos file paths have changed and old files would be copied to new paths. But it didn't happened on our upgrades and Fluentd started to read all logs from beginings.

https://issues.redhat.com/browse/LOG-1311

Command outputs for RHOL 4.6:
```
[root@localhost ~]# oc get csv
NAME                                DISPLAY                            VERSION              REPLACES                                    PHASE
clusterlogging.4.6.0-202112031823   Cluster Logging                    4.6.0-202112031823   clusterlogging.4.6.0-202111191944           Succeeded
elasticsearch-operator.5.3.6-46     OpenShift Elasticsearch Operator   5.3.6-46             elasticsearch-operator.4.6.0-202112140939   Succeeded

[root@localhost ~]# oc exec fluentd-49vlx -- wc -l /var/log/es-containers.log.pos ; echo ; wc -l /var/lib/fluentd/pos ; echo
103 /var/log/es-containers.log.pos

wc: /var/lib/fluentd/pos: No such file or directory
```

Command outputs for RHOL 5.3:
```
[root@localhost ~]# oc get csv
NAME                              DISPLAY                            VERSION    REPLACES                                    PHASE
cluster-logging.5.3.6-46          Red Hat OpenShift Logging          5.3.6-46   cluster-logging.5.2.9-42                    Succeeded
elasticsearch-operator.5.3.6-46   OpenShift Elasticsearch Operator   5.3.6-46   elasticsearch-operator.4.6.0-202112140939   Succeeded

sh-4.4# wc -l /var/log/es-containers.log.pos ; echo ; wc -l /var/lib/fluentd/pos/*                                                                                               
256 /var/log/es-containers.log.pos

   1 /var/lib/fluentd/pos/audit.log.pos
  11 /var/lib/fluentd/pos/es-containers.log.pos
   0 /var/lib/fluentd/pos/journal_pos.json
   1 /var/lib/fluentd/pos/kube-apiserver.audit.log.pos
  13 total
```

**Comment by cbremble** [comment]
Added to Jira: https://issues.redhat.com/browse/RHDEVDOCS-4330

**Comment by cbremble** [comment]
This was done via this PR: [openshift/openshift-docs#44965: [enterprise-4.10] Issue in file logging/cluster-logging-release-notes.adoc](https://github.com/openshift/openshift-docs/issues/44965)

/close
