### ISSUE TITLE
[enterprise-4.10] Clarify new auto update boot source capability and side effects in virt/virt-4-10-release-notes.adoc

### ISSUE THREAD

**Issue by peterclauterbach** [openshift/openshift-docs#45003]
### Which section(s) is the issue in?

> OpenShift Virtualization now provides a unified API for the [automatic import and update of pre-defined boot sources](https://docs.openshift.com/container-platform/4.10/virt/virtual_machines/advanced_vm_management/virt-automatic-bootsource-updates.html#virt-automatic-bootsource-updates).

### What needs fixing?

This new capability of automatically updating the boot sources leaves out an important detail that we'll automatically consume more disk space, which may be significant in a large cluster, or in a much smaller deployment, such as SNO or edge.

Please add more detail about this new capability into the release notes, and also add then this capability can be disabled (with appropriate links).

**Comment by acsulli** [comment]
I would like to request that we add verbiage saying that, for both upgrades and new installs, the default set of template disks will be downloaded unless the CRD is updated per [this action in the docs](https://docs.openshift.com/container-platform/4.10/virt/virtual_machines/advanced_vm_management/virt-automatic-bootsource-updates.html#virt-disabling-bootsource-update_virt-automatic-bootsource-updates).
