### ISSUE TITLE
[enterprise-4.10] Issue in file virt/virtual_machines/virtual_disks/virt-configuring-local-storage-for-vms.adoc

### ISSUE THREAD

**Issue by krsacme** [openshift/openshift-docs#45010]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.10/virt/virtual_machines/virtual_disks/virt-configuring-local-storage-for-vms.html#virt-about-hostpath-provisioner_virt-configuring-local-storage-for-vms

### What needs fixing?

The sample content for creating HPP cr is mentioned with `apiVersion: hostpathprovisioner.kubevirt.io.v1beta1` which is wrong, it should be `/` instead of dot for specifying version, like `apiVersion: hostpathprovisioner.kubevirt.io/v1beta1`.

Also Step 3 says save the file, but it should have mentioned to create the CR using oc command.

**Comment by apinnick** [comment]
The "kubevirt.io.v1beta1" issue seems to have been fixed.

The "oc create" step is being added as part of [BZ2102745](https://bugzilla.redhat.com/show_bug.cgi?id=2102745)
