### ISSUE TITLE
[enterprise-4.9] Issue in file installing/installing_bare_metal/installing-bare-metal.adoc

### ISSUE THREAD

**Issue by hannaplehero** [openshift/openshift-docs#45085]
### Which section(s) is the issue in?
It seems that --ignition-hash type needs to be lowercase. SHA512 should be sha512.
otherwise, the command rejects.

**Comment by kelbrown20** [comment]
This issue was addressed and updated in #45132
Live updated documentation: https://docs.openshift.com/container-platform/4.10/installing/installing_platform_agnostic/installing-platform-agnostic.html#installation-user-infra-machines-iso_installing-platform-agnostic 
Closing issue
