### ISSUE TITLE
[enterprise-4.10] Issue in file machine_management/manually-scaling-machineset.adoc

### ISSUE THREAD

**Issue by parogui** [openshift/openshift-docs#45149]
### Which section(s) is the issue in?

2.3. The MachineSet delete policy

### What needs fixing?

Replace `machine.openshift.io/cluster-api-delete-machine` with `machine.openshift.io/cluster-api-delete-machine=1` , the annotation needs this value to be applied as applying the annotation empty does nothing.

**Comment by mburke5678** [comment]
PR merged. Closing
