### ISSUE TITLE
[enterprise-4.10] Issue in file logging/cluster-logging.adoc link loop back to own achore.

### ISSUE THREAD

**Issue by rsjonte** [openshift/openshift-docs#45217]
### Which section(s) is the issue in?
This section contains a link which refers back to itself.
https://docs.openshift.com/container-platform/4.10/logging/cluster-logging.html#cluster-logging-json-logging-about_cluster-logging

### What needs fixing?
The links probably was meant to point to the below link.
https://docs.openshift.com/container-platform/4.10/logging/cluster-logging-enabling-json-logging.html

**Comment by cbremble** [comment]
Added to Jira: https://issues.redhat.com/browse/RHDEVDOCS-4307

**Comment by cbremble** [comment]
This was fixed with https://github.com/openshift/openshift-docs/pull/50781
/close
