### ISSUE TITLE
[enterprise-4.10] Issue in file virt/live_migration/virt-live-migration.adoc

### ISSUE THREAD

**Issue by apinnick** [openshift/openshift-docs#45221]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.10/virt/live_migration/virt-live-migration.html#virt-about-live-migration_virt-live-migration

### What needs fixing?

Is something missing from the brackets?

![image](https://user-images.githubusercontent.com/31725355/166145535-9bd630bf-a574-41e9-a670-127b42433740.png)

**Comment by ctomasko** [comment]
https://issues.redhat.com/browse/CNV-17972

**Comment by apinnick** [comment]
Fixed
