### ISSUE TITLE
[enterprise-4.10] Issue in file virt/logging_events_monitoring/virt-viewing-information-about-vm-workloads.adoc

### ISSUE THREAD

**Issue by apinnick** [openshift/openshift-docs#45237]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.10/virt/logging_events_monitoring/virt-viewing-information-about-vm-workloads.html

### What needs fixing?

Bullet list is not rendering correctly.
![image](https://user-images.githubusercontent.com/31725355/166250104-0fd99011-14e5-4cfb-bcfa-166bd2a5e121.png)

**Comment by ctomasko** [comment]
https://issues.redhat.com/browse/CNV-17971

**Comment by apinnick** [comment]
Closing because the issue was fixed
