### ISSUE TITLE
[online] Issue in file operating/manage-vulnerabilities.adoc

### ISSUE THREAD

**Issue by dbais76** [openshift/openshift-docs#45246]
### Which section(s) is the issue in?
Vulnerability management proccess

### What needs fixing?
vulnerability management proccess. -

There is a typo in the spelling of <process> in section as well as heading of the section. In all, this spelling is incorrect in three places.
The URL is:

https://docs.openshift.com/acs/3.68/operating/manage-vulnerabilities.html#vulnerability-management-proccess_acs-operating-manage-vulnerabilities

**Comment by dbais76** [comment]
Spelling of process is incorrect.. sorry missed mention of this earlier..

**Comment by bergerhoffer** [comment]
Marking this as a good candidate for Hacktoberfest.

https://docs.openshift.com/acs/3.68/operating/manage-vulnerabilities.html#vulnerability-management-proccess_acs-operating-manage-vulnerabilities

Whoever wants to take this issue can fix the spelling of "proccess" (2 places) and submit the fix against the 'rhacs-docs' branch. Ping me with any questions!

/remove-lifecycle rotten

**Comment by bergerhoffer** [comment]
Hi @mikesmith0414! I see you opened a PR to make this fix, thank you! Do you mind commenting on this issue, just so that I can assign it to you?

**Comment by bergerhoffer** [comment]
Closing since the PR to fix this was merged!
