### ISSUE TITLE
[enterprise-4.9] Issue in file scalability_and_performance/cnf-performance-addon-operator-for-low-latency-nodes.adoc

### ISSUE THREAD

**Issue by javierpena** [openshift/openshift-docs#45300]
### Which section(s) is the issue in?

Running hwlatdetect

### What needs fixing?

There are two issues in the command:

- ginko.focus is a typo, it should be ginkgo.focus
- The type of double quotes used in ”hwladetect” is not the same one we use in a shell, so a copy/paste of the command will fail in a non-obvious way (all tests will be skipped, instead of just running 1 test).

**Comment by ahardin-rh** [comment]
@javierpena Thank you for reporting this issue! The fix is now merged.
