### ISSUE TITLE
[enterprise-4.8] Issue in file service_mesh/v2x/preparing-ossm-installation.adoc

### ISSUE THREAD

**Issue by ltitov-rh** [openshift/openshift-docs#45352]
### Which section(s) is the issue in?

Supported configuration

### What needs fixing?

 - Red Hat OpenShift Container Platform version 4.9 or later.
This should be wrong, as current OSSM release should be supported on EUS OCP 4.8, 4.6 as well as current OCP releases.

**Comment by JStickler** [comment]
Closed via #45442
