### ISSUE TITLE
[enterprise-4.10] Issue in file installing/installing_ibm_cloud_public/installing-ibm-cloud-account.adoc

### ISSUE THREAD

**Issue by msoeke** [openshift/openshift-docs#45385]
### Which section(s) is the issue in?
Supported IBM Cloud Regions

### What needs fixing?
The Sao Paulo region (MZR) is not listed. IBM's managed OpenShift service is available in that region too.

**Comment by stevsmit** [comment]
@msoeke Can you confirm the MZR region is different than the following: 

* `br-sao` (Sao Paulo, Brazil)
 
?
