### ISSUE TITLE
[enterprise-4.10] Issue in file support/remote_health_monitoring/insights-operator-simple-access.adoc

### ISSUE THREAD

**Issue by rbaumgar** [openshift/openshift-docs#45402]
### What needs fixing?

In this description is missing that the SCA has to be enabled globally.
See section _How do I enable Simple Content Access for Red Hat Subscription Management?_ at https://access.redhat.com/articles/simple-content-access

**Comment by ShaunaDiaz** [comment]
@rbaumgar This issue is not part of OCP docs repo, so we won't be able to help you here. I did let the last author know about this issue, but you can also drop a comment below the article.

**Comment by bergerhoffer** [comment]
Closing based on the above comment
