### ISSUE TITLE
[enterprise-4.8] Issue in file installing/installing_bare_metal/installing-bare-metal.adoc

### ISSUE THREAD

**Issue by gleonova** [openshift/openshift-docs#45461]
### Which section(s) is the issue in?
All sections

### What needs fixing?
"PDF" button produces 82 completely EMPTY  pages .
[installing_installing_bare_metal_installing-bare-metal.pdf](https://github.com/openshift/openshift-docs/files/8654051/installing_installing_bare_metal_installing-bare-metal.pdf)

**Comment by bergerhoffer** [comment]
@kalexand-rh Here is another PDF generation issue, for when we get that fixed!
