### ISSUE TITLE
local role/policybinding documentation is broken

### ISSUE THREAD

**Issue by bparees** [openshift/openshift-docs#4547]
The doc here seems to be broken and/or out of date:

https://docs.openshift.org/latest/admin_guide/manage_authorization_policy.html#manage-authorization-policy-creating-local-role

1) the "exampleview" role is misformatted

2) the instructions to use it don't actually tell you to/tell you how to create the role after you create the yaml file.

3) the "optionally annotate it w/ a description" comment isn't very helpful w/o an example of how to do so.

4) the add-role-to-user command doesn't actually appear to work:

```
$ oc whoami
system:admin
```

```
$ cat /tmp/role.yaml 
apiVersion: v1
kind: Role
metadata:
  name: exampleview
rules:
- apiGroups: null
  attributeRestrictions: null
  resources:
  - pods
  - builds
  verbs:
  - get
  - list
  - watch
```

( what i assume is the missing step from the doc):
```
$ oc create -f /tmp/role.yaml 
role "exampleview" created
```

```
$ oadm policy add-role-to-user exampleview system:serviceaccount:service-catalog:default
Error from server (NotFound): role.authorization.openshift.io "exampleview" not found
```

@liggitt @enj @deads2k

**Comment by enj** [comment]
@bparees all valid issues that need to be addressed.

To add the local role to a user (requires `role-namespace` so the command does not try to find a `ClusterRole` called `exampleview`):

```
oadm policy add-role-to-user exampleview <username> --role-namespace='service-catalog'
```

However, in your specific case you are trying to add it to a service account (requires additional `-z`):

```
oadm policy add-role-to-user exampleview -z default --role-namespace='service-catalog'
```

cc @benjaminapetersen @adellape

**Comment by bparees** [comment]
> However, in your specific case you are trying to add it to a service account (requires additional -z):

I thought -z was not necessary if you specify the full service account name as i did, i thought -z was just a shortcut for that full syntax.

**Comment by liggitt** [comment]
>> However, in your specific case you are trying to add it to a service account (requires additional -z):
> 
> I thought -z was not necessary if you specify the full service account name as i did, i thought -z was just a shortcut for that full syntax.

That is correct

**Comment by enj** [comment]
Sorry for the half correct `-z` information.  Just do not try to combine `-z` with the full SA name (https://bugzilla.redhat.com/show_bug.cgi?id=1425398).

**Comment by bparees** [comment]
with some help from @pweil- i learned that you must first create a policybinding object before you can create a rolebinding, so when this doc is updated, that should be part of the "how to create a local role" steps. (though i find the requirement baffling).

**Comment by enj** [comment]
> so when this doc is updated, that should be part of the "how to create a local role" steps

@bparees no need, I will be loosening that requirement as a fix to https://github.com/openshift/origin/issues/14078

**Comment by vikram-redhat** [comment]
@adellape - are you looking at this?

**Comment by vikram-redhat** [comment]
This whole section has had a reorg and I believe this is no longer an issue. Closing this.
