### ISSUE TITLE
[enterprise-4.10] Issue in file storage/persistent_storage/persistent-storage-ocs.adoc

### ISSUE THREAD

**Issue by dlbewley** [openshift/openshift-docs#45555]
### Which section(s) is the issue in?

Throughout

### What needs fixing?

Actual result: links go to ODF 4.9 docs

Expected result: OCP 4.10 docs link to ODF 4.10 docs.

**Comment by bergerhoffer** [comment]
I believe this has been resolved.

Links to the ODF docs on https://docs.openshift.com/container-platform/4.10/storage/persistent_storage/persistent-storage-ocs.html now go to the 4.10 ODF docs. Closing!
