### ISSUE TITLE
[dedicated] Issue in file welcome/index.adoc

### ISSUE THREAD

**Issue by Canalroy** [openshift/openshift-docs#45568]
### Which section(s) is the issue in?

Cluster administrator activities
<snip>
Work with Logging: Learn about OpenShift Dedicated Logging and configure the logging add-on services.

### What needs fixing?
The service **OpenShift Dedicated Logging** does not exist in the doc.
I believe it is **OpenShift Logging**, not OpenShift Dedicated Logging.

**Comment by stevsmit** [comment]
@EricPonvelle PTAL https://docs.openshift.com/dedicated/welcome/index.html

**Comment by bergerhoffer** [comment]
Marking this as a good candidate for Hacktoberfest. 

There is likely an instance of "{product-title} Logging" that should just be "OpenShift Logging".

Whoever takes this issue - open the PR against main. Ping me with any questions!

/remove-lifecycle rotten

**Comment by tonytheleg** [comment]
@bergerhoffer with regards to OpenShift Dedicated, there are two methods of setting up logging: Using the **Cluster Logging Operator add-on** which can be installed in their cluster through [console.redhat.com](https://console.redhat.com) or installing the **OpenShift Logging** operator through OperatorHub. The key difference being I believe the Add-On has some support from CEE where as the OpenShift Logging operator is customer supported so I'm not sure which we'd want to mention in this doc. Poking at the rest of the OSD docs, I don't really see instructions anywhere for either one, the only other mention of logging is [Service Logs](https://docs.openshift.com/dedicated/osd_cluster_admin/osd_logging/osd-accessing-the-service-logs.html) which is something else. Happy to submit a PR on this one but wanted to confirm which would be the preferred edit to make. Thanks!

**Comment by bergerhoffer** [comment]
@tonytheleg This issue is really just about the phrase "OpenShift Dedicated Logging" showing up on the welcome page: https://docs.openshift.com/dedicated/welcome/index.html.

That phrase isn't correct, it should really just be called "OpenShift Logging".

So the fix needing to be made is in the https://raw.githubusercontent.com/openshift/openshift-docs/main/welcome/index.adoc file - where you see `{product-title} Logging` should really just be `OpenShift Logging`.

**Comment by tonytheleg** [comment]
PR submitted, thanks @bergerhoffer

**Comment by bergerhoffer** [comment]
Closing, since PR #51540 has merged!
