### ISSUE TITLE
Docs are unclear how input secrets can be kept outside an image

### ISSUE THREAD

**Issue by mar1ged** [openshift/openshift-docs#4561]
The docs at https://github.com/openshift/openshift-docs/blob/5f1e5a89b8b48cfd17baf9c7908c9e07538bdd71/dev_guide/builds/build_inputs.adoc#using-secrets-in-the-buildconfig mention this:

> Users should always remove their input secrets from the final application image so that the secrets are not present in the container running from that image. However, the secrets will still exist in the image itself in the layer where they were added. This removal should be part of the Dockerfile itself.

S2I takes care of this automatically, but for the docker strategy this has to be done manually. I didn't yet find a solution (perhaps a `rm foo.bar` in the right place does the job ?) so other people might run into the same problem and a clearer description or link to that information would help.

**Comment by php-coder** [comment]
> I didn't yet find a solution (perhaps a rm foo.bar in the right place does the job ?

Yes, secrets should be removed and removed in the same layer where they were added. In other words, they should be in a single directive: `RUN wget http://company.com/my-secret-key -O ~/my-key && use the key && rm ~/my-key`

CC @bparees

**Comment by bparees** [comment]
@php-coder that only works if your secrets are remotely accessible which is another whole host of problems (e.g. how do you authenticate to the service hosting your secret?  you need another secret, which means.....).

The docs section in question here is about using openshift secrets as part of what is available to the build context.  That means for a dockerbuild it has to be an "ADD"  (or some crazy run command that hits the cluster api and fetches the secret, but again this begs the question of how you get your token to access the api).

So there really is no solution for Docker builds with respect to the "secrets as build inputs" feature:
ADD foo
RUN blah
RUN rm roo

is basically the best you can do.

Note that if you use the experimental imagebuilder optimization, you'll only get a single new layer (much like s2i) meaning the secret will *not* still be present in a lower layer.

**Comment by php-coder** [comment]
@bparees Thank you, Ben!

**Comment by bparees** [comment]
@openshift/team-documentation 
I think the only improvement here would be to update this section:
https://docs.openshift.org/latest/dev_guide/builds/build_inputs.html#using-secrets-docker-strategy

with an explicit example of the Dockerfile commands that would ADD, use, and remove, a secret.

**Comment by mar1ged** [comment]
@bparees: this would be perfect because I didn't find such an example

**Comment by vikram-redhat** [comment]
Thanks all. Created bug to track: https://bugzilla.redhat.com/show_bug.cgi?id=1464042
