### ISSUE TITLE
[enterprise-4.10] Issue in file virt/logging_events_monitoring/virt-openshift-cluster-monitoring.adoc

### ISSUE THREAD

**Issue by apinnick** [openshift/openshift-docs#45721]
### Which section(s) is the issue in?

[Information collected by Telemetry](https://docs.openshift.com/container-platform/4.10/virt/logging_events_monitoring/virt-openshift-cluster-monitoring.html#what-information-is-collected_virt-openshift-cluster-monitoring)

### What needs fixing?

The list of information collected by Telemetry is very difficult to read because it is a long bullet list. I recommend creating sub-lists, organized by topic if possible.

![image](https://user-images.githubusercontent.com/31725355/168640687-3ddca792-d978-4d51-9614-848253f18ceb.png)

**Comment by apinnick** [comment]
Opened https://bugzilla.redhat.com/show_bug.cgi?id=2092324

**Comment by apinnick** [comment]
https://issues.redhat.com/browse/CNV-18886

**Comment by bburt-rh** [comment]
Per the suggestion in this issue's description, the bulleted list in the topic has been split up into 3 main categories for the 4.9+ docs:
 
- System information
- Sizing information
- Usage information 

Thus I'm closing this as fixed.
