### ISSUE TITLE
[enterprise-4.8] Issue in file windows_containers/windows-containers-release-notes-3-x.adoc

### ISSUE THREAD

**Issue by savasirez** [openshift/openshift-docs#45759]
### Which section(s) is the issue in?
Below marked sentence is incorrect, there is a typo

![image](https://user-images.githubusercontent.com/765947/168824584-d6908f6e-41a4-49ec-a8c0-05309236166b.png)

### What needs fixing?
The code needs to be fixed in order to be displayed correctly.

**Comment by bergerhoffer** [comment]
Thanks for reporting! 

This was fixed via PR #46453. Closing!
