### ISSUE TITLE
[enterprise-4.8] Issue in file logging/cluster-logging-external.adoc

### ISSUE THREAD

**Issue by nayan-art** [openshift/openshift-docs#45754]
https://docs.openshift.com/container-platform/4.8/logging/cluster-logging-external.html#creating-a-secret

### Which section(s) is the issue in?
$ oc create secret generic -n openshift-logging <my-secret> \
 --from-file=tls.key=<your_key_file>
 --from-file=tls.crt=<your_crd_file>                       < ----- Its should be crt file not crd file
 --from-file=ca-bundle.crt=<your_bundle_file>
 --from-literal=username=<your_username>
 --from-literal=password=<your_password>

### What needs fixing?
$ oc create secret generic -n openshift-logging <my-secret> \
 --from-file=tls.key=<your_key_file>
 --from-file=tls.crt=<your_crt_file>                 
 --from-file=ca-bundle.crt=<your_bundle_file>
 --from-literal=username=<your_username>
 --from-literal=password=<your_password>

**Comment by nayan-art** [comment]
please correct the doc as per the comment

**Comment by cbremble** [comment]
Added to Jira: https://issues.redhat.com/browse/RHDEVDOCS-4346
