### ISSUE TITLE
[enterprise-4.8] Issue in file post_installation_configuration/machine-configuration-tasks.adoc

### ISSUE THREAD

**Issue by ashishprajapati149** [openshift/openshift-docs#45867]
### Which section(s) is the issue in?
Using MachineConfig objects to configure nodes
---
For more ideas on working with machine configs, see content related to [adding](https://access.redhat.com/solutions/5096731) or [updating](https://access.redhat.com/solutions/4510281) SSH authorized keys, [verifying image signatures](https://access.redhat.com/verify-images-ocp4), [enabling SCTP](https://access.redhat.com/solutions/4727321), and [configuring iSCSI initiatornames](https://access.redhat.com/solutions/5170251) for OpenShift Container Platform.
---

### What needs fixing?
'adding' and 'updating' links are pointing to Duplicate KCS articles.

**Comment by ahardin-rh** [comment]
@mpandya15 is looking into this

**Comment by ahardin-rh** [comment]
The fix is merged. Thank you for reporting this issue!
