### ISSUE TITLE
[enterprise-4.10] Issue in file installing/installing_vsphere/installing-vsphere.adoc

### ISSUE THREAD

**Issue by krejkrejkrej** [openshift/openshift-docs#45872]
### Which section(s) is the issue in?

Ethernet adaptor hardware address requirements

### What needs fixing?

Documentation says that one of the valid MAC address ranges is
- 00:50:56:00:00:00 to 00:50:56:FF:FF:FF

However, vCenter does not allow the entire range. According to [VMware documentation](https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.troubleshooting.doc/GUID-7F723748-E7B8-48B9-A773-3822C514684B.html), the allowed range is
- 00:50:56:00:00:00 to 00:50:56:3F:FF:FF

**Comment by kelbrown20** [comment]
Fix made in PR#50071 

Updated documentation:
vSphere: https://docs.openshift.com/container-platform/4.10/installing/installing_vsphere/installing-restricted-networks-vsphere.html#installation-network-user-infra_installing-restricted-networks-vsphere
VMC: https://docs.openshift.com/container-platform/4.10/installing/installing_vmc/installing-vmc-user-infra.html#installation-network-user-infra_installing-vmc-user-infra

Setting to close
