### ISSUE TITLE
[enterprise-4.10] Issue in file storage/persistent_storage/persistent-storage-ocs.adoc

### ISSUE THREAD

**Issue by kfryklund** [openshift/openshift-docs#45893]
### Which section(s) is the issue in?
All ODF documentation links

### What needs fixing?
Links to ODF docs are 4.9, but should probably point to 4.10 now

**Comment by bergerhoffer** [comment]
All ODF links on https://docs.openshift.com/container-platform/4.10/storage/persistent_storage/persistent-storage-ocs.html now point to the 4.10 ODF docs. Closing!
