### ISSUE TITLE
[enterprise-4.10] Issue in file nodes/clusters/nodes-cluster-overcommit.adoc

### ISSUE THREAD

**Issue by jmcmeek** [openshift/openshift-docs#45900]
### Which section(s) is the issue in?
[Configuring your cluster to place pods on overcommitted nodes](https://docs.openshift.com/container-platform/4.10/nodes/clusters/nodes-cluster-overcommit.html)
- Installing the Cluster Resource Override Operator using the web console
- Installing the Cluster Resource Override Operator using the CLI

### What needs fixing?

The mutatingWebhookConfigurationRef examples are using an api version that was removed in 4.9:The examples should use:
```
    mutatingWebhookConfigurationRef: 
      apiVersion: admissionregistration.k8s.io/v1  << currently says v1beta1
      kind: MutatingWebhookConfiguration
```

Can the 4.9 doc be updated  as well?

**Comment by bergerhoffer** [comment]
Still valid. There are a handful of other places in the repo that still use `admissionregistration.k8s.io/v1beta1` and should be updated to `admissionregistration.k8s.io/v1` once we get confirmation from the appropriate SME/QE.

/remove-lifecycle stale

**Comment by bergerhoffer** [comment]
@kalexand-rh this one is pretty straightforward for someone to take (other than getting SME/QE approval). Just not sure who the right person is for this area

/remove-lifecycle stale

**Comment by bergerhoffer** [comment]
@cbippley This is a pretty straightforward change if you could try to work this in sometime. It applies to 4.10+

**Comment by bergerhoffer** [comment]
The PR has been merged and docs are live: https://docs.openshift.com/container-platform/4.10/nodes/clusters/nodes-cluster-overcommit.html#nodes-cluster-resource-override_nodes-cluster-overcommit

Closing!
