### ISSUE TITLE
Web Console screenshots out of date

### ISSUE THREAD

**Issue by spadgett** [openshift/openshift-docs#460]
I've noticed out of date screenshots in the following topics:

http://docs.openshift.org/latest/dev_guide/new_app.html
http://docs.openshift.org/latest/dev_guide/templates.html
http://docs.openshift.org/latest/dev_guide/projects.html

**Comment by adellape** [comment]
@spadgett Yeah, for a while there the webUI was changing with enough frequency that I wanted to wait til post-beta4. I suppose things are settled enough now that it's safe to re-screenshot?

**Comment by spadgett** [comment]
@adellape It's probably a good time. Things have settled :)
