### ISSUE TITLE
[enterprise-4.10] Issue in file migration_toolkit_for_containers/installing-mtc.adoc

### ISSUE THREAD

**Issue by apinnick** [openshift/openshift-docs#46001]
### Which section(s) is the issue in?

[Compatibility guidelines](https://docs.openshift.com/container-platform/4.10/migration_toolkit_for_containers/installing-mtc.html#migration-compatibility-guidelines_installing-mtc)

### What needs fixing?
typo: "OpenShift Container Platform 4.6 later" should be "OpenShift Container Platform 4.6 or later"

![image](https://user-images.githubusercontent.com/31725355/170204345-bc8768e3-95eb-4e59-a070-2d3d73d421aa.png)

This bug should be assigned to MTC (MMS) docs team. @RichardHoch

**Comment by opayne1** [comment]
This one might be a good one to start with @skopacz1
