### ISSUE TITLE
[enterprise-4.9] Issue in file applications/deployments/deployment-strategies.adoc

### ISSUE THREAD

**Issue by frightener** [openshift/openshift-docs#46005]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.9/applications/deployments/deployment-strategies.html#deployments-rolling-strategy_deployment-strategies

Sentence: A rolling deployment means you to have both old and new versions of your code running at the same time.

### What needs fixing?
The 'to' before 'have' seems incorrect and can be removed in my opinion.

**Comment by bergerhoffer** [comment]
Closing as PR #46957 was merged!
