### ISSUE TITLE
[dedicated] Issue in file osd_architecture/osd_policy/osd-service-definition.adoc

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-docs#46030]
### Which section(s) is the issue in?
Regulatory compliance

### What needs fixing?
There is a link to the RH customer portal documentation that 404s:
https://www.openshift.com/products/dedicated/process-and-security#compliance

The OpenShift website doesn't exist any longer and the redirect takes you to a customer portal section that no longer exists.

**Comment by bergerhoffer** [comment]
Thanks for reporting!

This issue was fixed in PR #46272 in June. Closing!
