### ISSUE TITLE
[enterprise-4.10] Issue in file machine_management/user_infra/adding-compute-user-infra-general.adoc

### ISSUE THREAD

**Issue by mtulio** [openshift/openshift-docs#46036]
### Which section(s) is the issue in?

Broken links referencing the Machine management

https://docs.openshift.com/container-platform/4.10/machine_management//user_infra/adding-compute-user-infra-general.html#adding-compute-user-infra-general

### What needs fixing?

1. Open the [URL](https://docs.openshift.com/container-platform/4.10/machine_management//user_infra/adding-compute-user-infra-general.html#adding-compute-user-infra-general)
2. Try to access [any link from any Cloud](https://docs.openshift.com/container-platform/4.10/machine_management/machine_management/user_infra/adding-aws-compute-user-infra.html#adding-aws-compute-user-infra), you will get a page not found:

![Screenshot from 2022-05-25 20-59-08](https://user-images.githubusercontent.com/3216894/170388318-1130f70a-286f-426b-8d8f-d40707f5ad02.png)

**Comment by jeana-redhat** [comment]
hm, wonder what happened here - will investigate. Thanks, Marco!

**Comment by jeana-redhat** [comment]
Ok actually I am wondering how you got to the link you posted above
> `https://docs.openshift.com/container-platform/4.10/machine_management//user_infra/adding-compute-user-infra-general.html#adding-compute-user-infra-general`

Note there are two `/` after `machine_management`. If you go to https://docs.openshift.com/container-platform/4.10/machine_management/user_infra/adding-compute-user-infra-general.html#adding-compute-user-infra-general (only one `/`) and click links they all work fine.

**Comment by jeana-redhat** [comment]
Closing as discussed per Slack - seems like a fluke but I have reported it to the wider team in case some brilliant person has any ideas :)
