### ISSUE TITLE
[enterprise-4.10] Issue in file networking/associating-secondary-interfaces-metrics-to-network-attachments.adoc

### ISSUE THREAD

**Issue by apinnick** [openshift/openshift-docs#46046]
### Which section(s) is the issue in?
[Associating secondary interfaces metrics to network attachments](https://docs.openshift.com/container-platform/4.10/networking/associating-secondary-interfaces-metrics-to-network-attachments.html) 

### What needs fixing?

Assembly and module have same title. The repetition looks strange.

![image](https://user-images.githubusercontent.com/31725355/170458854-4887fd7a-7178-45f1-bd85-cf5db268d2e5.png)

I think the title could be clearer. I suggest changing either to "Associating secondary interface metrics with network attachments" or "Associating metrics of secondary interfaces with network attachments".

**Comment by ShaunaDiaz** [comment]
See https://github.com/openshift/openshift-docs/pull/50648

**Comment by ahardin-rh** [comment]
Resolved in https://github.com/openshift/openshift-docs/pull/50648. Thank you!
