### ISSUE TITLE
[enterprise-4.8] Issue in file updating/updating-restricted-network-cluster.adoc

### ISSUE THREAD

**Issue by pamandrejko** [openshift/openshift-docs#46091]
### Which section(s) is the issue in?

[Mirroring the OpenShift Container Platform image repository](https://docs.openshift.com/container-platform/4.8/updating/updating-restricted-network-cluster.html#update-mirror-repository_updating-restricted-network-cluster)

### What needs fixing?

How does the customer know what ocp release to update to for this command?

`export OCP_RELEASE=<release_version>`

We need to provide a link to this graph: https://access.redhat.com/labs/ocpupgradegraph/update_channel
so customers can figured out their upgrade path -- especially if they want to get from ocp 4.6 to ocp 4.8 and it requires an intermediate hop to ocp 4.7. They would have to mirror the compatible release of ocp 4.7 that allows them to get from 4.6 to 4.8.

For example, the tool shows this:
![Screen Shot 2022-05-26 at 5 15 32 PM](https://user-images.githubusercontent.com/36892852/170581456-0ec06152-4d75-4682-bf1e-a328e76e4b58.png)

**Comment by stevsmit** [comment]
Hi @pamandrejko ,

In the live documents, we provide a link to the upgrade channel graph in Step 1 of the procedure. If this is not what you mean, please let me know. I am closing this issue for now.

**Comment by pamandrejko** [comment]
@stevsmit  Thanks for taking a look at this. I am not see a link to the upgrade channel graph in Step 1 of the procedure.
https://www.ibm.com/docs/en/openshift?source=https%3A%2F%2Fdocs.openshift.com%2Fcontainer-platform%2F4.6%2Fupdating%2Fupdating-cluster-within-minor.html&referrer=SSGT7J_21.4%2Fupgrade%2Fupgrade_ocp.html

![Screen Shot 2022-06-29 at 7 43 21 AM](https://user-images.githubusercontent.com/36892852/176428520-81e40428-7cad-44e4-bace-b5c3d61d75c6.png)
