### ISSUE TITLE
[dedicated] Issue in file osd_architecture/osd_policy/osd-service-definition.adoc

### ISSUE THREAD

**Issue by abozzoni** [openshift/openshift-docs#46146]
### Which section(s) is the issue in?
In the section: https://docs.openshift.com/dedicated/osd_architecture/osd_policy/osd-service-definition.html#regulatory-compliance_osd-service-definition, the link [OpenShift Dedicated Process and Security Overview](https://www.openshift.com/products/dedicated/process-and-security#compliance) points to a non existent page.

### What needs fixing?
The right link to point should be: https://docs.openshift.com/dedicated/osd_architecture/osd_policy/policy-process-security.html#compliance_policy-process-security

**Comment by stevsmit** [comment]
Hi @abozzoni ,

I was unable to locate the link that you're referring to on that page ("[OpenShift Dedicated Process and Security Overview])". Please let me know where I can find it, or if you notice that it has been fixed. Thanks.
