### ISSUE TITLE
[enterprise-4.10] Issue in file machine_management/creating-infrastructure-machinesets.adoc

### ISSUE THREAD

**Issue by patrickstrick** [openshift/openshift-docs#46170]
### Which section(s) is the issue in?

Introduction of "Creating infrastructure machine sets"

### What needs fixing?

I think that the first sentence could be clarified by using the wording from the OpenShift Sizing and Subscription Guide [1]. So instead of 

> You can use infrastructure machine sets to create machines that host only infrastructure components, such as the default router, the integrated container image registry, and the components for cluster metrics and monitoring.

...it would say (bold added to show difference in this change request)

> To qualify as an infrastructure node and use the included entitlement, only components that are supporting the cluster, **and not part of an end-user application**, may be running on those instances.

The reason I believe this would be helpful is because I had a customer ask whether Service Mesh is allowed on the infrastructure nodes. The added point about "not part of the end-user application" explains why SM is not listed in the allowed applications, and might head off these questions in the future.

[1] https://www.redhat.com/en/resources/self-managed-openshift-sizing-subscription-guide

**Comment by JStickler** [comment]
@patrickstrick  FYI https://issues.redhat.com/browse/OSSM-459
