### ISSUE TITLE
Host preparation lists kexec as a package, but no such package exists.

### ISSUE THREAD

**Issue by georgegoh** [openshift/openshift-docs#4625]
Base packages listed here:

https://github.com/openshift/openshift-docs/blob/enterprise-3.5/install_config/install/host_preparation.adoc#installing-base-packages

**kexec** as a package does not exist. This should be **kexec-tools**, I believe.

**Comment by vikram-redhat** [comment]
@adellape - is this right? If yes, could you do a simple PR to fix the docs?

**Comment by adellape** [comment]
@vikram-redhat Yeah, fixing via https://github.com/openshift/openshift-docs/pull/4661. Thanks @georgegoh!
