### ISSUE TITLE
Backup docker certs when working with External secured registries

### ISSUE THREAD

**Issue by jtudelag** [openshift/openshift-docs#4647]
As the doc states, when working with external secured Registries, registry certs must be copied to the folder  /etc/docker/certs.d. [1]

This has to be taken into account when doing a backing up and restoring a cluster, otherwise, It won't be possible to pull images, so the cluster won't be fully functional after the restore.

https://docs.openshift.org/1.5/install_config/registry/securing_and_exposing_registry.html#exposing-the-registry

**Comment by vikram-redhat** [comment]
A bug [1] has been opened to track this. Closing this issue.

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1464494
