### ISSUE TITLE
[enterprise-4.9] Issue in file release_notes/ocp-4-9-release-notes.adoc

### ISSUE THREAD

**Issue by mhutter** [openshift/openshift-docs#46484]
### Which section(s) is the issue in?

>RHBA-2022:4741 - OpenShift Container Platform 4.9.36 bug fix update

### What needs fixing?

Link `https://access.redhat.com/errata/RHSA-2022:4741` should say `https://access.redhat.com/errata/RHBA-2022:4741`

**Comment by stevsmit** [comment]
I have closed this issue. Thanks for submitting.
