### ISSUE TITLE
[enterprise-4.10] Issue in file updating/updating-cluster-rhel-compute.adoc

### ISSUE THREAD

**Issue by rhatbob** [openshift/openshift-docs#46562]
### Which section(s) is the issue in?
- [Updating RHEL compute machines in your cluster](https://docs.openshift.com/container-platform/4.10/updating/updating-cluster-rhel-compute.html#rhel-compute-updating-minor_updating-cluster-rhel-compute)

### What needs fixing?
Proposal to add two nuances on the support context of RHEL 7 compute nodes:
- While RHEL 7 compute / worker nodes support has been [removed](https://docs.openshift.com/container-platform/4.10/release_notes/ocp-4-10-release-notes.html#ocp-4-10-removed-feature-rhel-7-support) in the context of RHOCP 4.10, the presence of said workers won't block the cluster upgrade from RHOCP 4.9 to 4.10
- Following the RHOCP 4.10 upgrade, the RHEL 7 compute / worker nodes will continue to run the existing workload, but the underlying components (kuberlet, cri-o release...) will remain the same as in RHOCP 4.9

**Comment by sdodson** [comment]
I'm concerned that providing these details may lead an admin to conclude that's upgrading to 4.10 prior to replacing RHEL7 workers is a documented upgrade procedure. It's not.
