### ISSUE TITLE
dev_guide/downward_api.adoc yaml example syntax error

### ISSUE THREAD

**Issue by tonykay** [openshift/openshift-docs#4660]
In the yaml example file at dev_guide/downward_api.adoc#using-the-volume-plug-in the volume-pod.yaml file the 2 annotation examples need to be quoted:

Currently is:

> annotations:
    annotation1: 345
    annotation2: 456

Should be:

> annotations:
     annotation1: "345"
     annotation2: "456"

Otherwise 

> oc create -f volume-pod.yaml 

fails:

> Error from server (BadRequest): error when creating "volume-pod.yaml": Pod in version "v1" cannot be handled as a Pod: [pos 74]: json: expect char '"' but got char '3'

**Comment by bfallonf** [comment]
Thanks @tonykay . I've fixed this in PR #4671 . Closing this issue.
