### ISSUE TITLE
Invalid link to AsciiDoc

### ISSUE THREAD

**Issue by Christoffer-Aske** [openshift/openshift-docs#46646]
### Which section(s) is the issue in?
[README.adoc](https://github.com/openshift/openshift-docs/blob/main/README.adoc) -> "[OpenShift documentation](https://github.com/openshift/openshift-docs/blob/main/README.adoc#openshift-documentation)"

### What needs fixing?
Link to AsciiDoc is invalid. Should be changed from https://www.methods.co.nz/asciidoc/ to https://asciidoc.org/

**Comment by ahardin-rh** [comment]
@mpandya15 is investigating

**Comment by maxwelldb** [comment]
Fixed by @mpandya15 in #46951.
