### ISSUE TITLE
[enterprise-4.10] Issue in file installing/installing-preparing.adoc

### ISSUE THREAD

**Issue by apinnick** [openshift/openshift-docs#46678]
### Which section(s) is the issue in?

[Have you used OpenShift Container Platform 3 and want to use OpenShift Container Platform 4?](https://docs.openshift.com/container-platform/4.10/installing/installing-preparing.html#installing-preparing-migrate)

### What needs fixing?

Remove "For more information about migrating, see [OpenShift Migration Best Practices](https://redhat-cop.github.io/openshift-migration-best-practices/01-planning.html)." 

The "OpenShift Migration Best Practices" document has been deprecated for over a year and the repository has been archived. All information relevant to migration has been moved to "Migrating from version 3 to 4".

**Comment by kelbrown20** [comment]
@apinnick Hi Avital! Can you PTAL at the linked PR for the doc changes when you get the chance? Thank you! 😄
