### ISSUE TITLE
[enterprise-4.8] Issue in file logging/cluster-logging-external.adoc

### ISSUE THREAD

**Issue by vgri** [openshift/openshift-docs#46712]
### Which section(s) is the issue in?
[Forwarding logs using the legacy syslog method](https://docs.openshift.com/container-platform/4.8/logging/cluster-logging-external.html#cluster-logging-collector-legacy-syslog_cluster-logging-external )

### What needs fixing?
Following the guide - "You cannot use the config map methods and the Cluster Log Forwarder in the same cluster.".
After creating a ConfigMap from a syslog.conf without a ClusterLogForwarder instance no logs were received in the Syslog. 
Confirmed with the OpenShift Logging team, this method is not supported with OpenShift logging operator version 5.x.x.

Please add to the guide that this method is not supported in OpenShift logging operator version 5.x.x.

**Comment by cbremble** [comment]
Added to Jira: https://issues.redhat.com/browse/RHDEVDOCS-4344

**Comment by cbremble** [comment]
This should be closed based on the outcome of https://issues.redhat.com/browse/RHDEVDOCS-4344. 
/close
