### ISSUE TITLE
Clarify glusterfs persistentVolumeReclaimPolicy

### ISSUE THREAD

**Issue by pweil-** [openshift/openshift-docs#4672]
https://docs.openshift.org/latest/install_config/persistent_storage/persistent_storage_glusterfs.html#gfs-creating-persistent-volume notes that `GlusterFS does not support the 'Recycle' recycling policy` and then later notes that the policy seems to be completely unsupported with `The Recycle policy is currently not supported with glusterfs`.

Also in the [example](https://docs.openshift.org/latest/install_config/storage_examples/gluster_example.html#complete-example-using-gusterfs-creating-the-persistent-volume) docs it simply lists the options for  `persistentVolumeReclaimPolicy` which seems to imply that they're supported

**Comment by gaurav-nelson** [comment]
Thank you @pweil- We are working on this one.

**Comment by gaurav-nelson** [comment]
Closing this, please follow https://github.com/openshift/openshift-docs/issues/4760
