### ISSUE TITLE
Incorrect xref format for top-level headings?

### ISSUE THREAD

**Issue by thatdocslady** [openshift/openshift-docs#4673]
While implementing the xref format we discovered in Minishift that if we used the anchor ID text for the H1 top-level heading then the links broke during the publication. 

Currently in the doc guidelines [1] it says to write the anchor ID text, but we discovered that if we remove it and only use the hash sign (#) then the links work.

If this is something that doesn't interfere with other implementations, I can submit a PR for this section to clarify when to use the anchor ID text.

[1] https://github.com/openshift/openshift-docs/blob/master/contributing_to_docs/doc_guidelines.adoc#links-hyperlinks-and-cross-references

**Comment by vikram-redhat** [comment]
@thatdocslady - Hey Mikey. Publication to the portal broke or to docs.openshift.org?

**Comment by thatdocslady** [comment]
@vikram-redhat I think it's to docs.openshift.org, we don't publish directly to the CP yet.

**Comment by vikram-redhat** [comment]
Closing this as I believe it was fixed on minishift side.
