### ISSUE TITLE
[enterprise-4.10] Issue in file networking/external_dns_operator/nw-installing-external-dns-operator-on-cloud-providers.adoc

### ISSUE THREAD

**Issue by sanbornick** [openshift/openshift-docs#46809]
### Which section(s) is the issue in?
Search

### What needs fixing?
Searching for "external DNS" yields top results that point to dead links such as https://docs.openshift.com/container-platform/4.10/networking/external_dns_operator/nw-installing-external-dns-operator.html instead of https://docs.openshift.com/container-platform/4.10/networking/external_dns_operator/nw-installing-external-dns-operator-on-cloud-providers.html

**Comment by JoeAldinger** [comment]
@sanbornick thanks for contributing. We've updated our documentation on 07.14.2022 to fix the links.

**Comment by pneedle-rh** [comment]
Hi all, following a discussion today, I am reopening this issue until the 404 is resolved.

We have clarified that the https://docs.openshift.com/container-platform/4.10/networking/external_dns_operator/nw-installing-external-dns-operator.html should be redirected to https://docs.openshift.com/container-platform/4.10/networking/external_dns_operator/nw-installing-external-dns-operator-on-cloud-providers.html. We are in the process of implementing that redirect.

We will update this issue after the redirect is in place.

Please let us know if you have any questions in the meantime. Thanks!

**Comment by pneedle-rh** [comment]
Redirect PR: https://github.com/openshift/openshift-docs/pull/47788

**Comment by pneedle-rh** [comment]
The redirect is now in place. @sanbornick thank you for highlighting the issue!
