### ISSUE TITLE
builds + imagestreams topic should be split

### ISSUE THREAD

**Issue by bparees** [openshift/openshift-docs#4681]
not sure why we originally lumped these together, but they should be two separate topics:
https://docs.openshift.org/latest/architecture/core_concepts/builds_and_image_streams.html

**Comment by gaurav-nelson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) ["Architecture" improvements](https://trello.com/c/lsCm60x7/29-architecture-improvements)

**Comment by gaurav-nelson** [comment]
Thanks @bparees this is a work in progress. I have added this to the related trello card.

**Comment by vikram-redhat** [comment]
We are unlikely to get to this before we modularize our docs. Closing.

**Comment by bparees** [comment]
@vikram-redhat there's still no reason for builds and imagestreams to be in the same topic.
