### ISSUE TITLE
[enterprise-4.10] Issue in file nodes/nodes/eco-poison-pill-operator.adoc

### ISSUE THREAD

**Issue by sanbornick** [openshift/openshift-docs#46935]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.10/nodes/nodes/eco-poison-pill-operator.html#clipboard-1

### What needs fixing?

Indentation

**Comment by bergerhoffer** [comment]
@abhatt-rh Are you the right person to look into fixing this?

**Comment by abhatt-rh** [comment]
Hi @bergerhoffer Sure, I can work on getting it fixed

**Comment by bergerhoffer** [comment]
Closing since this issue has been fixed
