### ISSUE TITLE
[enterprise-4.10] Issue in file hardware_enablement/psap-driver-toolkit.adoc

### ISSUE THREAD

**Issue by braultatgithub** [openshift/openshift-docs#46995]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.10/hardware_enablement/psap-driver-toolkit.html#pulling-the-driver-toolkit_driver-toolkit

https://docs.openshift.com/container-platform/4.10/hardware_enablement/psap-driver-toolkit.html#pulling-the-driver-toolkit-from-registry

### What needs fixing?
Could we have a direct link to the Driver Tool Kit vs a link to the catalog landing page.

https://catalog.redhat.com/software/containers/search?q=Driver%20Toolkit&p=1&vendor_name=Red%20Hat

**Comment by kelbrown20** [comment]
Hello! From my end the [Red Hat ecosystem catalog] in “Pulling the Driver toolkit container images from registry.redhat.io” takes me to the [Driver tool kit](https://catalog.redhat.com/software/containers/search?q=Driver%20Toolkit&p=1&vendor_name=Red%20Hat) link you mentioned. And [Container images section of the Red Hat Ecosystem Catalog] in “Pulling the Driver toolkit container image” takes me to the [general catalog](https://catalog.redhat.com/) page. Is that the same for you, or do both links take to the catalog page?
