### ISSUE TITLE
[enterprise-4.10] Issue in file security/certificate_types_descriptions/bootstrap-certificates.adoc

### ISSUE THREAD

**Issue by ugiordan** [openshift/openshift-docs#47029]
### Which section(s) is the issue in?
Purpose section.

### What needs fixing?
Both links to the **bootstrap initialization process** and **authorization of the kubelet to create a CSR** are broken.

The links referenced are:

- **bootstrap initialization process**: https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping/#bootstrap-initialization
- **authorization of the kubelet to create a CSR**: https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping/#authorize-kubelet-to-create-csr

They should be changed with:
- **bootstrap initialization process**: https://kubernetes.io/docs/reference/access-authn-authz/kubelet-tls-bootstrapping/#bootstrap-initialization
- **authorization of the kubelet to create a CSR**: https://kubernetes.io/docs/reference/access-authn-authz/kubelet-tls-bootstrapping/#authorize-kubelet-to-create-csr

**Comment by bergerhoffer** [comment]
Marking this a good candidate for Hacktoberfest.

Please open the PR against `main` and reach out if you have any questions!

**Comment by bergerhoffer** [comment]
Thanks @ugiordan! Just in case you were trying to do it as part of [Hacktoberfest](https://hacktoberfest.digitalocean.com/), just know that it won't count unless the PR is opened in October. But in the interest of getting these broken URLs fixed, we can move forward with your PR now :smile:
