### ISSUE TITLE
[enterprise-4.10] Issue in file service_mesh/v2x/ossm-federation.adoc

### ISSUE THREAD

**Issue by sjbylo** [openshift/openshift-docs#47079]
### Which section(s) is the issue in?
Federation implementation checklist

### What needs fixing?
It does not state in the list that root certificates need to be manually copied from one mesh cluster to another.   I think this would be useful information.   On the same page under "joining federated meshes" it does mention that a configmap with the root cert is needed, but it does not explicitly mention and show how to copy that over.  

This blog does show it quite well in the "Service Mesh Peering" section. 
https://www.opensourcerers.org/2022/01/24/getting-started-with-openshift-servicemesh-federation/  
e.g.

```
PROD_MESH_CERT=$(oc get configmap -n prod-mesh istio-ca-root-cert -o jsonpath='{.data.root-cert\.pem}')
STAGE_MESH_CERT=$(oc get configmap -n stage-mesh istio-ca-root-cert -o jsonpath='{.data.root-cert\.pem}')

sed "s:{{STAGE_MESH_CERT}}:$STAGE_MESH_CERT:g" prod-mesh/stage-mesh-ca-root-cert.yaml | oc apply -f -

sed "s:{{PROD_MESH_CERT}}:$PROD_MESH_CERT:g" stage-mesh/prod-mesh-ca-root-cert.yaml | oc apply -f -
```

**Comment by JStickler** [comment]
Created [OSSMDOC-635](https://issues.redhat.com/browse/OSSMDOC-635) to track this.
