### ISSUE TITLE
Reference to polling 3rd party repositories for image changes

### ISSUE THREAD

**Issue by brenton** [openshift/openshift-docs#471]
@ncdc, do we really poll 3rd party repositories today?

https://github.com/openshift/openshift-docs/blame/master/architecture/infrastructure_components/image_registry.adoc#L31

**Comment by ncdc** [comment]
@brenton we do a 1-time import. If you want to re-import, run `oc import-image <stream>`

**Comment by brenton** [comment]
@ncdc, thanks.  If the streams are reimported will it cause image change triggers to fire?

**Comment by ncdc** [comment]
@brenton yes, any update to an image stream will cause the image change controllers to reprocess it to determine if builds/deployments are needed.
