### ISSUE TITLE
incomplete cert chain on docs.openshift.org

### ISSUE THREAD

**Issue by jiri-fiala** [openshift/openshift-docs#4732]
Incomplete cert chain is reported on docs.openshift.org:
https://www.ssllabs.com/ssltest/analyze.html?d=docs.openshift.org

**Comment by adellape** [comment]
FYI @nhr

**Comment by nhr** [comment]
This is low priority but I will add it to my backlog.

**Comment by nhr** [comment]
Issue is resolved.
