### ISSUE TITLE
.vscode directory should not be present in this repository

### ISSUE THREAD

**Issue by maxwelldb** [openshift/openshift-docs#47380]
### Which section(s) is the issue in?
https://github.com/openshift/openshift-docs/tree/main/.vscode

### What needs fixing?
Remove the directory. It's added to .gitignore, but it's present in the repo right now: https://github.com/openshift/openshift-docs/tree/main/.vscode

**Comment by maxwelldb** [comment]
For when you have a sec, @EricPonvelle

**Comment by kalexand-rh** [comment]
@EricPonvelle, preferably sooner than later.
