### ISSUE TITLE
CLI Linux installation

### ISSUE THREAD

**Issue by OSobky** [openshift/openshift-docs#47400]
### Which section(s) is the issue in?
in the cli_reference/openshift_cli/getting-started-cli/linux-installation 

### What needs fixing?

in the oc CLI Linux installation steps, there is an unpacking step using the following command. 

`$ tar xvzf <file>
`

However, the tar file seems to not compressed by  gzip as it produces the following error 

`gzip: stdin: not in gzip format`

where the z flag should be removed from the command in the documentation

**Comment by bergerhoffer** [comment]
I followed the steps here: https://docs.openshift.com/container-platform/4.10/cli_reference/openshift_cli/getting-started-cli.html#cli-installing-cli_cli-developer-commands

and tested downloading the file from the suggested site (https://access.redhat.com/downloads/content/290/ver=4.10/rhel---8/4.10.24/x86_64/product-software) and it is in gzip format: `oc-4.10.24-linux.tar.gz`

So the command does work properly for me:

```
[ahoffer@ahoffer tmp] $ tar xvzf oc-4.10.24-linux.tar.gz 
README.md
oc
kubectl
```
Are you by chance downloading the oc file from somewhere else (maybe where it's not gzipped)?

**Comment by OSobky** [comment]
Hey @bergerhoffer 

I downloaded it directly from an OpenShift cluster. From ![image](https://user-images.githubusercontent.com/36420198/182840053-518bfc18-9b6f-49c2-bd6d-75bc745b3f19.png) => **Command line Tools** 

Maybe the ones from the cluster are not gzipped?

**Comment by bergerhoffer** [comment]
Hi @OSobky

Yes I just checked and if you download from the cluster it only downloads as `oc.tar`, not gzipped. Since that is a different location, the procedure written as is works properly. Is this issue okay to be closed then? Thanks!

**Comment by OSobky** [comment]
Yes, thanks for your support
