### ISSUE TITLE
The virt_sandbox_use_nfs boolean is defined by the docker-selinux package.

### ISSUE THREAD

**Issue by Jooho** [openshift/openshift-docs#4746]
Same context but different value since 3.2 to latest:

```The virt_use_nfs boolean is defined by the docker-selinux package```
https://github.com/openshift/openshift-docs/blob/master/install_config/persistent_storage/persistent_storage_nfs.adoc

```The virt_sandbox_use_nfs boolean is defined by the docker-selinux package.```
https://github.com/openshift/openshift-docs/blob/master/install_config/storage_examples/shared_storage.adoc

**However, it needs to verify following before update**
- docker-selinux package is not used any more
  - container-selinux is being used
- virt_sandbox_use_nfs is not there anymore.

Thanks,
Jooho Lee.

**Comment by Jooho** [comment]
From this [issue](https://github.com/openshift/openshift-ansible/issues/2294), 
detiber said " 3.2+, I don't think virt_sandbox_use_nfs is even needed."

**Comment by gaurav-nelson** [comment]
Thank you @Jooho we are working on this one.

**Comment by gaurav-nelson** [comment]
Closing this, please follow https://github.com/openshift/openshift-docs/issues/4755
