### ISSUE TITLE
[enterprise-4.10] Issue in file installing/installing_bare_metal_ipi/ipi-install-prerequisites.adoc

### ISSUE THREAD

**Issue by daviesow** [openshift/openshift-docs#47482]
### Which section(s) is the issue in?

Reserving IP addresses for nodes with the DHCP server
Validation checklist for nodes

### What needs fixing?

The term "Master" is used eight times in this document.  According to RedHat's "Making open source more inclusive" policy, the term should be replaced or removed.  It is used once in each of the above sections in parenthesis after "Control Plane" and six times in a table as part of exemplary host names.

**Comment by kelbrown20** [comment]
Fix was made in PR#50132
Updated documentation 
- Docs.openshift.com: https://docs.openshift.com/container-platform/4.11/installing/installing_bare_metal_ipi/ipi-install-prerequisites.html#network-requirements-dhcp-reqs_ipi-install-prerequisites
- Customer portal: https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html/installing/deploying-installer-provisioned-clusters-on-bare-metal#ipi-install-prerequisites

Closing this issue
