### ISSUE TITLE
[enterprise-4.10] config map patching not required need to be removed from virt/live_migration/virt-live-migration.adoc

### ISSUE THREAD

**Issue by peterclauterbach** [openshift/openshift-docs#47524]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.10/virt/live_migration/virt-live-migration.html#virt-updating-access-mode-for-live-migration_virt-live-migration

### What needs fixing?
We no longer need the config map patching, the CNV storage profiles handle this. Please revise and review with eng.

**Comment by apinnick** [comment]
[BZ2104917](https://bugzilla.redhat.com/show_bug.cgi?id=2104917)

**Comment by apinnick** [comment]
@alitke
Does this issue require any changes besides removing "Updating access mode for live migration"?

**Comment by apinnick** [comment]
In progress

**Comment by apinnick** [comment]
Fixed. https://github.com/openshift/openshift-docs/pull/53343
