### ISSUE TITLE
[enterprise-4.10] Issue in file logging/cluster-logging-external.adoc

### ISSUE THREAD

**Issue by madhusudanupadhyay** [openshift/openshift-docs#47575]
### Which section(s) is the issue in?

Sample log forwarding outputs and pipelines

### What needs fixing?

The following point(6) in the example seems to be typo.
`Configuration for an input to filter application logs from the my-namespace project.`

In place of the above namespace name it should be `my-project` namespace. 

It is not such big a deal but just thought it worth highlighting. 
--
 

<br class="Apple-interchange-newline">

**Comment by ahardin-rh** [comment]
@madhusudanupadhyay Thank you for reporting this typo! This is now fixed in https://github.com/openshift/openshift-docs/pull/4938. The update is merged, so I am closing this issue. Thanks again for your help!
