### ISSUE TITLE
[enterprise-4.10] Issue in file scalability_and_performance/planning-your-environment-according-to-object-maximums.adoc

### ISSUE THREAD

**Issue by mikthoma** [openshift/openshift-docs#47776]

**Comment by kelbrown20** [comment]
Issue fixed in linked PR
Updated documentation: 
https://docs.openshift.com/container-platform/4.11/scalability_and_performance/planning-your-environment-according-to-object-maximums.html#cluster-maximums-major-releases_object-limits

Setting to close
