### ISSUE TITLE
[enterprise-4.8] Issue in file logging/cluster-logging.adoc

### ISSUE THREAD

**Issue by maucb** [openshift/openshift-docs#47834]
### Which section(s) is the issue in?
In the below link, it was supposed to redirect to another page.

For information, see [**About JSON Logging**](https://docs.openshift.com/container-platform/4.8/logging/cluster-logging.html#cluster-logging-json-logging-about_cluster-logging).
https://docs.openshift.com/container-platform/4.8/logging/cluster-logging.html#cluster-logging-json-logging-about_cluster-logging

### What needs fixing?

Above link does not redirect to any page.

**Comment by cbremble** [comment]
Added to Jira: https://issues.redhat.com/browse/RHDEVDOCS-4343

**Comment by pfeifferj** [comment]
this seems to be fixed in 4.9 [https://docs.openshift.com/container-platform/4.9/logging/cluster-logging.html#cluster-logging-json-logging-about_cluster-logging](https://docs.openshift.com/container-platform/4.9/logging/cluster-logging.html#cluster-logging-json-logging-about_cluster-logging)
