### ISSUE TITLE
[enterprise-4.8] Issue in file support/troubleshooting/troubleshooting-operating-system-issues.adoc

### ISSUE THREAD

**Issue by dan-m8t** [openshift/openshift-docs#47886]
### Which section(s) is the issue in?
Analyzing a core dump

### What needs fixing?

It is fine that the documentation links to the RHEL 8 docs for analyzing a core dump. But the OpenShift documentation should mention that the `kernel-debuginfo` package is necessary to analyze the dump. This leads to a second reboot because of RHCOS immutability at runtime.

**Comment by control-d** [comment]
I don't expect that we want users to try to debug vmcores directly on RHCOS nodes.  You only need `kernel-debuginfo` on the RHEL system where you're running gdb/crash/etc. It may be better to add a note to this section indicating that the vmcore analysis should be done on a separate RHEL system.

**Comment by dan-m8t** [comment]
This was indeed unclear to me. I analyzed the vmcore on another machine.
