### ISSUE TITLE
[enterprise-4.10] Issue in file virt/live_migration/virt-live-migration.adoc

### ISSUE THREAD

**Issue by patrickstrick** [openshift/openshift-docs#47998]
### Which section(s) is the issue in?

About live migration

### What needs fixing?

In an email conversation I had with @peterclauterbach he indicated that SR-IOV is *not* required for live migration, but is supported if available. However, the language in this section makes it sound as if SR-IOV is required. Specifically, the sentence introducing the bullet on SR-IOV states, "You can use live migration if the following conditions are met". That implies that you cannot use live migration if any of those conditions are not met.

My suggestion, assuming that SR-IOV is indeed not required, would be to remove the bullet referencing it form this section and include some other statement about how SR-IOV can be used in another location of the doc.

**Comment by apinnick** [comment]
Changes merged
