### ISSUE TITLE
WINC-820: [docs] Remove Windows Server 20H2 support

### ISSUE THREAD

**Issue by mburke5678** [openshift/openshift-docs#48042]
Microsoft will drop support for OS version Windows Server 20H2 on 2022-08-09.
In line with this, WMCO will no longer support this version for vSphere worker nodes.

https://github.com/openshift/windows-machine-config-operator/pull/1145
https://github.com/openshift/windows-machine-config-operator/pull/1146

**Comment by saifshaikh48** [comment]
Also note the backports all the way to 4.7:
https://github.com/openshift/windows-machine-config-operator/pull/1147
https://github.com/openshift/windows-machine-config-operator/pull/1148
https://github.com/openshift/windows-machine-config-operator/pull/1149
