### ISSUE TITLE
[enterprise-4.10] Issue in file cli_reference/openshift_cli/getting-started-cli.adoc

### ISSUE THREAD

**Issue by rokkbert** [openshift/openshift-docs#48060]
### Which section(s) is the issue in?
"Installing the OpenShift CLI on Linux"

### What needs fixing?
It says I should extract the archive and then copy the binary to a directory in my PATH. Same instructions is also given in the included README.md. (Note: the version I downloaded is oc-4.10.23-linux.tar.gz). I copied both oc and kubectl (even though they are the same) to ~/bin, which is in my PATH. I try to run oc:

$ oc version
bash: /usr/bin/oc: No such file or directory
$ which oc
/home/rob/bin/oc

After I copied them to /usr/bin it works. So either something in oc is broken or the instructions are wrong and I can't just copy it any place I want.

OS is Fedora 36, with no other OpenShift software installed.

**Comment by rokkbert** [comment]
Hi! Thanks for checking.
I tried to repeat the problem on fresh installs of Fedora 36 Workstation and CentOS Stream 8. I tried oc-4.10.23 and oc-4.10.24. I could **not** reproduce it now. I could run oc as expected, from my private bin directory. So I assume that something is indeed wrong with the configuration my workstation which showed the weird behaviour.
Sorry for the trouble, please close this issue.

**Comment by bergerhoffer** [comment]
Great to hear! Not a problem at all, thanks :slightly_smiling_face: Closing this issue.
