### ISSUE TITLE
[enterprise-4.10] Issue in file post_installation_configuration/cluster-tasks.adoc

### ISSUE THREAD

**Issue by patrickstrick** [openshift/openshift-docs#48075]
### Which section(s) is the issue in?

Manual defragmentation

### What needs fixing?

The documentation states, "You can monitor the etcd_db_total_size_in_bytes metric to determine whether manual defragmentation is necessary" but unless I am missing something it does not give advice on how to interpret the etcd_db_total_size_in_bytes metric to make that decision.

Please add guidance so the reader will know how to determine when manual defragmentation is necessary.

**Comment by kelbrown20** [comment]
Hello Patrick! It looks like this issue was discussed in this issue #48077 and fixed in PR #49475. Please let me know if this looks to be accurate and I can close this issue. Thank you!

**Comment by patrickstrick** [comment]
yep, thanks!
