### ISSUE TITLE
Performance Addon Operator no avaiable in OKD

### ISSUE THREAD

**Issue by wangzheng422** [openshift/openshift-docs#48197]
### Which section(s) is the issue in?
The document here https://docs.okd.io/4.9/scalability_and_performance/cnf-performance-addon-operator-for-low-latency-nodes.html#installing-the-performance-addon-operator_cnf-master , it needs Performance Addon Operator from redhat-operator catalog, which is not available in OKD

### What needs fixing?
Add Performance Addon Operator to OKD, or remove the section from OKD document.

**Comment by sheriff-rh** [comment]
I have created a pull request to remove PAO from OKD documentation, please review when you have a chance. Thanks! https://github.com/openshift/openshift-docs/pull/49332
