### ISSUE TITLE
Better information on proxy setting support for 'oc' command

### ISSUE THREAD

**Issue by sspeiche** [openshift/openshift-docs#4827]
Customer had a hard time understanding how to configure the `oc` command to use their corporate proxy. The docs only talk about it from an admin point of view and proxy settings for nodes, etc.

It would be handy if the topic was covered at: https://docs.openshift.org/latest/cli_reference/get_started_cli.html
to describe the usage of HTTP_PROXY and HTTS_PROXY

/cc @spurtell @fabianofranz

**Comment by ahardin-rh** [comment]
@sspeiche Thanks! I opened a [docs bug ](https://bugzilla.redhat.com/show_bug.cgi?id=1485036)to track the work more closely.
