### ISSUE TITLE
openshift_logging_public_master_url should be openshift_logging_master_public_url

### ISSUE THREAD

**Issue by Jooho** [openshift/openshift-docs#4843]
Hi 

The parameter "openshift_logging_public_master_url" from [aggregate logging doc](https://github.com/openshift/openshift-docs/blob/master/install_config/aggregate_logging.adoc) is different from ansible script variable "openshift_logging_master_public_url".

So if I use this variable "openshift_logging_master_public_url", it will set public master url in kibana but if I use "openshift_logging_public_master_url", it does not set it.

Thanks,
Jooho Lee.

**Comment by Jooho** [comment]
Found [bugzilla ticket](https://bugzilla.redhat.com/show_bug.cgi?id=1474169) about it.

**Comment by bmcelvee** [comment]
Thanks for finding this, Jooho! Since there is an open bug, we can track the updates there.
