### ISSUE TITLE
aggregate_logging default value linked to metric

### ISSUE THREAD

**Issue by Jooho** [openshift/openshift-docs#4846]
Hi
From this [aggregate_doc](https://github.com/openshift/openshift-docs/blob/master/install_config/aggregate_logging.adoc), the default value linked to metric
~~~
Parameters for the EFK deployment may be specified to the inventory host file to override the **defaults.** Read the Elasticsearch and the Fluentd sections before choosing parameters:
~~~
https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_metrics/defaults/main.yaml[defaults]

This should be ..
==>https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_logging/defaults/main.yml

Thanks,
Jooho lee

https://kibana.cloudapps.example.com

**Comment by bfallonf** [comment]
Thanks @Jooho . I've created a PR for this: https://github.com/openshift/openshift-docs/pull/5064

If there's anything more please let us know.
