### ISSUE TITLE
[enterprise-4.10] Issue in file monitoring/managing-metrics.adoc

### ISSUE THREAD

**Issue by jan--f** [openshift/openshift-docs#48514]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.10/monitoring/managing-metrics.html#querying-metrics-for-user-defined-projects-as-a-developer_managing-metrics

### What needs fixing?
The `Additional resources` section links back to the heading of the same section. Looks like a mistake as this doesn't add information

**Comment by bburt-rh** [comment]
@cbremble Please triage

**Comment by cbremble** [comment]
@bburt-rh when you get a chance please add monitoring-issue label (I can't add because I can't merge)

**Comment by cbremble** [comment]
Added to Jira: https://issues.redhat.com/browse/RHDEVDOCS-4334

**Comment by bburt-rh** [comment]
The fix has been published to https://docs.openshift.com/container-platform/4.10/monitoring/managing-metrics.html#querying-metrics-for-user-defined-projects-as-a-developer_managing-metrics
