### ISSUE TITLE
[enterprise-4.10] Issue in file storage/container_storage_interface/persistent-storage-csi-ovirt.adoc

### ISSUE THREAD

**Issue by rhodain** [openshift/openshift-docs#48562]
### Which section(s) is the issue in?
Overview

### What needs fixing?
The chapter says that the ovirt CSI driver is installed by default. But that does not seem to the correct at least for SNO virtualization on top of RHV. I also did not find the operator in the  OperatorHub.

**Comment by kalexand-rh** [comment]
@tradej, PTAL?

**Comment by tradej** [comment]
@kalexand-rh we don't do virtualisation, and none of our writers touched this file before. Perhaps @ctomasko?

**Comment by kalexand-rh** [comment]
@tradej, I thought it might be yours because of SNO's involvement.

**Comment by tradej** [comment]
We do do SNO work, but mostly in the bare metal or ZTP context. *virt is completely out of our remit.
