### ISSUE TITLE
logging clean up ansible playbook name is wrong.

### ISSUE THREAD

**Issue by Jooho** [openshift/openshift-docs#4859]
Hi

ansible playbook to clean up efk stack is wrong.
[3.5 doc](https://docs.openshift.com/container-platform/3.5/install_config/aggregate_logging.html)
~~~
Cleanup
Remove everything generated during the deployment.

$ ansible-playbook [-i </path/to/inventory>] \ /usr/share/ansible/openshift-ansible/playbooks/common/openshift-cluster/openshift_logging.yml \
    -e openshift_logging_install_logging=False
~~~
But it should be ```/usr/share/ansible/openshift-ansible/playbooks/byo/openshift-cluster/openshift-logging.yml```

If I used the ansible playbook that is from doc, it occurs following error:
~~~
This playbook requires g_etcd_hosts to be set
~~~

Thanks,
Jooho lee.

**Comment by bmcelvee** [comment]
@Jooho I opened https://github.com/openshift/openshift-docs/pull/4864 with this change. PTAL

**Comment by vikram-redhat** [comment]
The associated issue was merged. Closing this.
