### ISSUE TITLE
[enterprise-4.10] Issue in file scalability_and_performance/ztp-deploying-disconnected.adoc

### ISSUE THREAD

**Issue by imiller0** [openshift/openshift-docs#48723]
The instructions for Installing and Upgrading the GitOps ZTP pipeline is missing a step. Before the step of:
`oc apply -k out/argocd/deployment` we need this command to be run:
```
oc patch argocd openshift-gitops -n openshift-gitops  --type=merge --patch-file out/argocd/deployment/argocd-openshift-gitops-patch.json
```
### Which section(s) is the issue in?
The section titled "Preparing the hub cluster for ZTP" (here: https://docs.openshift.com/container-platform/4.10/scalability_and_performance/ztp-deploying-disconnected.html#ztp-preparing-the-hub-cluster-for-ztp_ztp-deploying-disconnected)

The section titled "Installing the new GitOps ZTP applications" (here: 
https://docs.openshift.com/container-platform/4.10/scalability_and_performance/ztp-deploying-disconnected.html#ztp-installing-the-new-gitops-ztp-applications_ztp-deploying-disconnected)

### What needs fixing?
Add the missing step:
Patch the ArgoCD instance in the hub cluster using the patch file previously extracted into the out/argocd/deployment/ directory:
```
oc patch argocd openshift-gitops -n openshift-gitops  --type=merge --patch-file out/argocd/deployment/argocd-openshift-gitops-patch.json
```

**Comment by aireilly** [comment]
Addressed in https://github.com/openshift/openshift-docs/pull/49805

**Comment by aireilly** [comment]
Addressed in https://github.com/openshift/openshift-docs/pull/49805
