### ISSUE TITLE
Developer Guide Overview (missing links) 

### ISSUE THREAD

**Issue by sferich888** [openshift/openshift-docs#4878]
The developer guide overview does not link to any information that it says its is designed to help a developer with. 

- [x] Monitor and browse projects with the web console (do we link to): 
    - https://docs.openshift.com/dedicated/getting_started/developers_console.html
    - https://docs.openshift.com/dedicated/dev_guide/projects.html
    - All of the above
- [ ] Configure and utilize the CLI (do we link to):
    - https://docs.openshift.com/dedicated/getting_started/developers_cli.html
    - https://docs.openshift.com/dedicated/cli_reference/index.html
    - https://docs.openshift.com/dedicated/cli_reference/get_started_cli.html
        -  https://docs.openshift.com/dedicated/cli_reference/manage_cli_profiles.html
    - Some grouping of these links
    - All of the above
- [x] Generate configurations using templates (do we link to):
    - https://docs.openshift.com/dedicated/dev_guide/application_lifecycle/new_app.html#dev-guide-new-app
    - https://docs.openshift.com/dedicated/dev_guide/templates.html
    - All of the above
- [x] Manage builds, images and webhooks (do we link to):
    - https://docs.openshift.com/dedicated/dev_guide/builds/index.html
    - https://docs.openshift.com/dedicated/dev_guide/builds/basic_build_operations.html
    - https://docs.openshift.com/dedicated/dev_guide/builds/build_inputs.html
    - https://docs.openshift.com/dedicated/dev_guide/builds/build_output.html
    - https://docs.openshift.com/dedicated/dev_guide/builds/build_strategies.html
    - https://docs.openshift.com/dedicated/dev_guide/builds/triggering_builds.html
    - https://docs.openshift.com/dedicated/dev_guide/builds/build_hooks.html
    - https://docs.openshift.com/dedicated/dev_guide/builds/build_run_policy.html
    - https://docs.openshift.com/dedicated/dev_guide/builds/advanced_build_operations.html
    - All of the above  
- [x] Define and trigger deployments (do we link to):
   - https://docs.openshift.com/dedicated/dev_guide/builds/triggering_builds.html
   - https://docs.openshift.com/dedicated/dev_guide/builds/build_hooks.html
   - All of the above
- [x] Integrate external services (databases, SaaS endpoints)
   - https://docs.openshift.com/dedicated/dev_guide/integrating_external_services.html

Do we need to re-think this description / overview based on https://github.com/openshift/openshift-docs/issues/4879 

https://docs.openshift.com/dedicated/dev_guide/index.html

**Comment by bfallonf** [comment]
Thanks @sferich888 . I made a PR about this. Added some links and a few more dot points. Let me know if you have any more thoughts.
