### ISSUE TITLE
Developer Guide Overview (outline)

### ISSUE THREAD

**Issue by sferich888** [openshift/openshift-docs#4879]
The developer guide overview focus is on setting up a "set up and configure a workstation to develop and deploy applications" however it covers very little of this, or focus outlining the content to such a goal. 

The content is more structured at providing / outlining what end users have control over, when working with the system. As such a re-design of the outline/sections is in order. 

Current through on re-structure: 
### Interacting with the Cluster
- [ ] Tools Walkthrough
    - Web - https://docs.openshift.com/dedicated/getting_started/developers_console.html
    - CLI - https://docs.openshift.com/dedicated/getting_started/developers_cli.html
- [ ] Authenticating with the cluster
- [ ] (Authorization) Managing / Ensuring your have the correct permissions to perform a task. 
### Interacting with the Core Components / Defining an application and its components. 
- [ ] Overview - https://github.com/openshift/openshift-docs/issues/4885
- [ ] Managing a Project (Create, View, Update, Delete)
- [ ] Managing a Templates (Create, View, Update, Delete)
- [ ] Managing a Images (Create, View, Update, Delete)
- [ ] Managing a Routes (Create, View, Update, Delete)
- [ ] Managing a Quotas and Limit Ranges (Create, View, Update, Delete)
- [ ] Managing Environment Variables (Create, View, Update, Delete)
- [ ] Managing a Volumes (Create, View, Update, Delete)
    - [ ] Using Persistent Volumes (should be moved to a sub-subsection) 
- [ ] Managing a Secrets (Create, View, Update, Delete)
- [ ] Managing a ConfigMaps (Create, View, Update, Delete)
- [ ] Managing a Volumes (Create, View, Update, Delete)
### Interacting / Managing an Application 
- [ ] Managing an application lifecycle
- [ ] Viewing / Understanding Events
- [ ] Visualizing Application Health
- [ ] Dealing with Service Accounts
- [ ] Interacting with a running application 
    - [ ] (overview) - https://docs.openshift.com/dedicated/cli_reference/basic_cli_operations.html#troubleshooting-and-debugging-cli-operations (all the commands page below are part of troubleshooting) 
    - [ ] Opening a Remote Shell
    - [ ] Executing Remote Commands
    - [ ] Copying Files
    - [ ] Port Forwarding
- [ ] Jobs
- [ ] Scheduled Jobs
- [ ] Pod Autoscaling
- [ ] Shared Memory
- [ ] Downward API

https://docs.openshift.com/dedicated/dev_guide/index.html

**Comment by bfallonf** [comment]
Thanks @sferich888 I've created an improvements card in the docs trello board. I've added this one and a few others (I'll comment on those too).

Hopefully they can be worked on in the next sprint or two. I'll close this issue.
