### ISSUE TITLE
[enterprise-4.10] Issue in file operators/operator_sdk/osdk-installing-cli.adoc

### ISSUE THREAD

**Issue by empovit** [openshift/openshift-docs#48793]
### Which section(s) is the issue in?

Installing the Operator SDK CLI

### What needs fixing?

The link in "Procedute", step 1 "Navigate to the [OpenShift mirror site](https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/operator-sdk/4.10/)." is broken - `File not found`. 

There are multiple versions of 4.10.x, but none of them is exactly 4.10.

**Comment by Amrita42** [comment]
@empovit so from 4.9 onwards, the directory is specified as generic i.e. 4.9, etc.  The links for 4.9-4.11 are working and pointing towards the mirror registry. Please confirm. Thanks.

**Comment by empovit** [comment]
Looks good, thanks
