### ISSUE TITLE
developing-on-openshift sections/content is confusing

### ISSUE THREAD

**Issue by sferich888** [openshift/openshift-docs#4880]
The header sections for https://docs.openshift.com/dedicated/dev_guide/application_lifecycle/development_process.html#devstrategy-developing-on-openshift are titled, "Using OpenShift Dedicated as Your Development Environment" and "Bringing an Application to Deploy on OpenShift Dedicated" however in each section we define a work flow that uses the same steps, just in a slightly differen order. 

In each section we point to a different "highlighted area", but its not clear if that is where I start or if that highlights the differences in the flow?  
Should the flow questions be in their own section? 

(Again) No matter what the flow the steps seem to be the same, just in a different order! 

Should we be more detailed in each section, are/or should we link to examples of how to do this, say with https://docs.openshift.com/dedicated/dev_guide/app_tutorials/index.html or https://blog.openshift.com/binary-deployments-openshift-3/ and https://blog.openshift.com/binary-input-sources-openshift-3-2/

**Comment by sferich888** [comment]
The sections here could also link to https://docs.openshift.com/dedicated/dev_guide/application_lifecycle/new_app.html or https://docs.openshift.com/dedicated/dev_guide/application_lifecycle/promoting_applications.html to provide the additional infromation.

**Comment by sferich888** [comment]
The https://docs.openshift.com/dedicated/dev_guide/application_lifecycle/development_process.html#devstrategy-developing-then-deploying-on-openshift section likely needs to focus / cut to the chase and link to https://docs.openshift.com/dedicated/dev_guide/application_lifecycle/promoting_applications.html#dev-guide-promoting-applications-scenarios

**Comment by bfallonf** [comment]
Thanks @sferich888 I've created an improvements card in the docs trello board. I've added this one and a few others (I'll comment on those too).

Hopefully they can be worked on in the next sprint or two. I'll close this issue.
