### ISSUE TITLE
[OKD] Invalid Fedora Versions Specified in OS Requirements

### ISSUE THREAD

**Issue by tflink** [openshift/openshift-docs#48813]
### Which section(s) is the issue in?

Documentation / OKD 4 / Installing / Installing on bare metal / Installing a user-provisioned cluster on bare metal # Required machines for cluster installation

### What needs fixing?

The docs specify valid OS for compute machines as being FCOS, Fedora 8.4 or Fedora 8.5 specifying an access.redhat.com link on RHEL capabilites as a reference (I assume as to why it's just 8.4 and 8.5).

I assume that this was meant to be RHEL 8.4 or RHEL 8.5 since there was never a Fedora 8.4 or 8.5. It would make more sense to have valid Fedora versions listed here, assuming that currently supported Fedora releases are supported for compute nodes or I guess remove those listings if there are no supported Fedora releases which could be used for compute nodes.

**Comment by vrutkovs** [comment]
Also "Creating a mirror registry with mirror registry for Red Hat OpenShift" page mentions "Fedora 8"

Seems OS is being incorrectly replaced in OKD docs. cc @mburke5678
