### ISSUE TITLE
[enterprise-4.10] Issue in file scalability_and_performance/ztp-deploying-disconnected.adoc

### ISSUE THREAD

**Issue by imiller0** [openshift/openshift-docs#48820]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.10/scalability_and_performance/ztp-deploying-disconnected.html#ztp-policygentemplates-for-ran_ztp-deploying-disconnected
Under "Additional Resources". See full paragraph below.

### What needs fixing?
The link in this section does not go to the correct place in the document:
Additional resources
For more information about extracting the /argocd directory from the ztp-site-generator container image, see [Preparing the ZTP Git repository](https://docs.openshift.com/container-platform/4.10/scalability_and_performance/ztp-deploying-disconnected.html#ztp-policygentemplates-for-ran_ztp-deploying-disconnected).

It should go to:
https://docs.openshift.com/container-platform/4.10/scalability_and_performance/ztp-deploying-disconnected.html#ztp-preparing-the-ztp-git-repository_ztp-deploying-disconnected

**Comment by aireilly** [comment]
Addressed in https://github.com/openshift/openshift-docs/pull/49805
