### ISSUE TITLE
Provide more information in application_lifecycle guide on managing env vars 

### ISSUE THREAD

**Issue by sferich888** [openshift/openshift-docs#4882]
https://docs.openshift.com/online/dev_guide/application_lifecycle/new_app.html#specifying-environment-variables
https://docs.openshift.com/dedicated/dev_guide/application_lifecycle/new_app.html#specifying-environment-variables

Should link to: 

https://docs.openshift.com/online/dev_guide/environment_variables.html
https://docs.openshift.com/dedicated/dev_guide/environment_variables.html

**Comment by gaurav-nelson** [comment]
Thank you @sferich888 for pointing this out.

I have created a PR #5136 for tracking this, hence closing this one.
