### ISSUE TITLE
[enterprise-4.8] Issue in file logging/cluster-logging-deploying.adoc

### ISSUE THREAD

**Issue by annelson-rh** [openshift/openshift-docs#48838]
### Which section(s) is the issue in?
Verify the install:

### What needs fixing?
fluentd pods are named collector-* and not fluentd-*

**Comment by cbremble** [comment]
Added to Jira: https://issues.redhat.com/browse/RHDEVDOCS-4342

**Comment by cbremble** [comment]
Hi @annelson-rh I believe this should have been addressed by a duplicate issue here: https://issues.redhat.com/browse/RHDEVDOCS-4346. I will plan to close this, please let us know if you see any further issues. Thanks!
/close
