### ISSUE TITLE
application_lifecycle only show object manipulation using cli 

### ISSUE THREAD

**Issue by sferich888** [openshift/openshift-docs#4883]
Link like: https://docs.openshift.com/dedicated/dev_guide/application_lifecycle/new_app.html#using-the-web-console-na are missing how to minuputlat objects using the web console (missing a sub section / images for minipulatin the sections) https://docs.openshift.com/dedicated/dev_guide/application_lifecycle/new_app.html#new-app-output

**Comment by ahardin-rh** [comment]
@adellape @aheslin Will the Dedicated content audit address this?
