### ISSUE TITLE
Should api-objects be its own section in application_lifecycle

### ISSUE THREAD

**Issue by sferich888** [openshift/openshift-docs#4884]
Should the https://docs.openshift.com/dedicated/dev_guide/application_lifecycle/promoting_applications.html#dev-guide-promoting-applications-api-objects section be its own document? 

This way it can be used for both https://docs.openshift.com/dedicated/dev_guide/application_lifecycle/promoting_applications.html#overview as well as https://docs.openshift.com/dedicated/dev_guide/application_lifecycle/new_app.html#overview (mainly: https://docs.openshift.com/dedicated/dev_guide/application_lifecycle/new_app.html#new-app-output)

**Comment by bfallonf** [comment]
Thanks @sferich888 I've created an improvements card in the docs trello board. I've added this one and a few others (I'll comment on those too).

Hopefully they can be worked on in the next sprint or two. I'll close this issue.
