### ISSUE TITLE
Abstracting object manipulation out into its own section? 

### ISSUE THREAD

**Issue by sferich888** [openshift/openshift-docs#4885]
Should this section be the header for https://docs.openshift.com/dedicated/dev_guide/application_lifecycle/promoting_applications.html#dev-guide-promoting-application-managing-api-objects for https://github.com/openshift/openshift-docs/issues/4883

Links to: https://github.com/openshift/openshift-docs/issues/4879

**Comment by bfallonf** [comment]
Thanks @sferich888 I've created an improvements card in the docs trello board. I've added this one and a few others (I'll comment on those too).

Hopefully they can be worked on in the next sprint or two. I'll close this issue.
