### ISSUE TITLE
Online/Dedicated remove references to system:admin in favor of dedicated-admin (where applicable)  

### ISSUE THREAD

**Issue by sferich888** [openshift/openshift-docs#4886]
Where ever possible (example: https://docs.openshift.com/dedicated/dev_guide/authentication.html) we should remove referances to system:admin as uses in online/dedicated are not given access to such a user. 

In dedicated, we may want to reference: https://docs.openshift.com/dedicated/admin_guide/index.html#admin-guide-index-dedicated-admin-role

So for https://docs.openshift.com/dedicated/dev_guide/authentication.html and https://docs.openshift.com/dedicated/architecture/additional_concepts/authentication.html we should updat this to point to  https://docs.openshift.com/dedicated/admin_guide/index.html#admin-guide-index-dedicated-admin-role over system:admin

**Comment by ahardin-rh** [comment]
I believe this is being addressed in the content audit for the Dedicated docs. @adellape @aheslin Is that the case?

**Comment by vikram-redhat** [comment]
Fixed via multiple commits: https://github.com/openshift/openshift-docs/commit/c5f313431a7ae61ffe264b2843a793de3714f56e and
https://github.com/openshift/openshift-docs/commit/c3a7022dd0b64844267500431f361aa06606aa0e

Closing this issue.
