### ISSUE TITLE
Missing web ui example (create project) 

### ISSUE THREAD

**Issue by sferich888** [openshift/openshift-docs#4887]
https://docs.openshift.com/dedicated/dev_guide/projects.html#create-a-project is missing an image / referances on how to create a project using the web ui. We describe the flow in https://docs.openshift.com/dedicated/getting_started/developers_console.html#developers-console-creating-a-project so I question if this section is needed, or if an image needs to be provided to that section?

**Comment by ahardin-rh** [comment]
@adellape @aheslin Will the Dedicated content audit address this?
