### ISSUE TITLE
[enterprise-4.10] Dex SSO configuration options are out of date

### ISSUE THREAD

**Issue by yrro** [openshift/openshift-docs#48884]
### Which section(s) is the issue in?
Enabling the Dex OpenShift OAuth Connector

### What needs fixing?
The example config has `dex` directly under `.spec` instead of under `.spec.sso`; additionally `.spec.sso.provider=dex` must be set.

**Comment by Preeticp** [comment]
Completed via https://issues.redhat.com/browse/RHDEVDOCS-5098
