### ISSUE TITLE
Online/Dedicated Docs should provide a link to Migration Center

### ISSUE THREAD

**Issue by sferich888** [openshift/openshift-docs#4890]
We should link to https://www.openshift.com/get-started/migrate.html in our migration docs (https://docs.openshift.com/dedicated/dev_guide/migrating_applications/index.html) as a resouces for more examples and tutotials.

**Comment by bfallonf** [comment]
@sferich888 this page is essentially a list of components, and they all link straight to the docs anyway. The exceptions being some of the links in the "Other resources" section, with the rest of the links heading to other, similar resources. I think this one is OK as is. Thanks, and I'll close.
