### ISSUE TITLE
s2i docs need to be incorporated / linked to development flows

### ISSUE THREAD

**Issue by sferich888** [openshift/openshift-docs#4891]
If you use the following links, you can define a workflow for developing on openshift. 

- Build: https://docs.openshift.com/dedicated/dev_guide/migrating_applications/S2I_tool.html
- ref (for upcomming link): https://docs.openshift.com/dedicated/dev_guide/managing_images.html#accessing-the-internal-registry
    - Push: https://docs.openshift.com/dedicated/dev_guide/managing_images.html#creating-an-image-stream-by-manually-pushing-an-image
- Deploy: https://docs.openshift.com/dedicated/dev_guide/application_lifecycle/new_app.html#specifying-an-image
    - Likely need to link to a change trigger. 

Related to: https://github.com/openshift/openshift-docs/issues/4880 or defines a flow for https://docs.openshift.com/dedicated/dev_guide/application_lifecycle/development_process.html#devstrategy-developing-then-deploying-on-openshift

**Comment by bfallonf** [comment]
Thanks @sferich888 I've created an improvements card in the docs trello board. I've added this one and a few others (I'll comment on those too).

Hopefully they can be worked on in the next sprint or two. I'll close this issue.
