### ISSUE TITLE
[enterprise-4.8] Issue in file nodes/nodes/nodes-nodes-working.adoc

### ISSUE THREAD

**Issue by jfnixon** [openshift/openshift-docs#48999]
### Section
Openshift 4.8 Nodes / Working with Nodes
Understanding how to evacuate pods on nodes 

### What needs fixing?
The --delete-local-data=true is deprecated, but appears in the recommended commands. 
Documentation should use --delete-emptydir-data

**Comment by mburke5678** [comment]
@jfnixon Thank you for pointing this out. The change is being tracked through a BZ and this PR: https://github.com/openshift/openshift-docs/pull/47957
