### ISSUE TITLE
[enterprise-4.8] Issue in file service_mesh/v2x/removing-ossm.adoc

### ISSUE THREAD

**Issue by skachhwa** [openshift/openshift-docs#49008]
### Which section(s) is the issue in?
Accordingly to my Customer below resources also needs to be removed which is not part of the document

sa - "istio-cni"
cm - "istio-cni-config"

### What needs fixing?
Add below commands to the document:
oc delete cm -n openshift-operators istio-cni-config
oc delete sa -n openshift-operators istio-cni

**Comment by JStickler** [comment]
Created [OSSMDOC-658](https://issues.redhat.com/browse/OSSMDOC-658) to track this issue/
