### ISSUE TITLE
[enterprise-4.11] Issue in file networking/ovn_kubernetes_network_provider/configuring-ipsec-ovn.adoc

### ISSUE THREAD

**Issue by sreber84** [openshift/openshift-docs#49025]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.11/networking/ovn_kubernetes_network_provider/configuring-ipsec-ovn.html#nw-ovn-ipsec-enable_configuring-ipsec-ovn

### What needs fixing?

```
$ oc patch networks.operator.openshift.io/cluster --type=json \
-p='[{"op":"remove", "path":"/spec/defaultNetwork/ovnKubernetesConfig/ipsecConfig"}]'
```

Appears to be the wrong command to enable _IPsec encryption_. I suspect it should be at least `$ oc patch networks.operator.openshift.io/cluster --type=json -p='[{"op":"add", "path":"/spec/defaultNetwork/ovnKubernetesConfig/ipsecConfig"}]'`. But likely there are also some additional values that need to be set and therefore that section should be reviewied and fixed.

**Comment by skrthomas** [comment]
GitHub PR to address this issue: https://github.com/openshift/openshift-docs/pull/51153

There's also another openshift-docs issue reporting the same: https://github.com/openshift/openshift-docs/issues/51100
