### ISSUE TITLE
[enterprise-4.11] Issue in file nodes/pods/nodes-pods-autoscaling-custom.adoc

### ISSUE THREAD

**Issue by dlbewley** [openshift/openshift-docs#49038]
### Which section(s) is the issue in?

"Adding a custom metrics autoscaler to a job"

### What needs fixing?

Invalid YAML. Naked _envSourceContainerName_ without a `:` nor example value.

**Comment by mburke5678** [comment]
@dlbewley Thanks for catching this! A lot of eyes missed it. Can you take a look at my PR to make sure I am making the right change? Thanks!
https://github.com/openshift/openshift-docs/pull/49190

**Comment by dlbewley** [comment]
yep. thanks!

**Comment by mburke5678** [comment]
PR merged. Closing
