### ISSUE TITLE
[enterprise-4.11] Issue in file monitoring/reviewing-monitoring-dashboards.adoc

### ISSUE THREAD

**Issue by dlbewley** [openshift/openshift-docs#49059]
### Which section(s) is the issue in?

"Reviewing monitoring dashboards"

### What needs fixing?

The "Observe" screenshot is of an OKD console, not an OCP console.

**Comment by cbremble** [comment]
Added to Jira: https://issues.redhat.com/browse/RHDEVDOCS-4347

**Comment by bburt-rh** [comment]
This issue is now fixed. You can view it in the live docs at https://docs.openshift.com/container-platform/4.11/monitoring/reviewing-monitoring-dashboards.html.

Closing.
