### ISSUE TITLE
[enterprise-4.10] Issue in file installing/installing_bare_metal/installing-restricted-networks-bare-metal.adoc

### ISSUE THREAD

**Issue by Majestic3691** [openshift/openshift-docs#49109]
### Which section(s) is the issue in?
PDF button upper right side of page - produces empty (content) PDF doc.

### What needs fixing?
PDF needs the content.

**Comment by kalexand-rh** [comment]
While we investigate this issue, you can generate a PDF of the same content from the [Customer Portal].(https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html/installing/installing-on-bare-metal)
