### ISSUE TITLE
[enterprise-4.11] Issue in file installing/installing_aws/installing-aws-network-customizations.adoc

### ISSUE THREAD

**Issue by testlaben** [openshift/openshift-docs#49198]
### Which section(s) is the issue in?
Install OpenShift on AWS with network customizations

### What needs fixing?
According to the openshift installer, there's a libvirt check if any of the networks overlap the default docker bridge subnet `172.17.0.0/16`
as found here; https://github.com/openshift/installer/blob/d237b9dee575c6e9ceeba80fd3e137231d907cab/pkg/validate/validate.go#L21

And the actually check done here:
https://github.com/openshift/installer/blob/d237b9dee575c6e9ceeba80fd3e137231d907cab/pkg/types/validation/installconfig.go#L294

This should be mentioned in the documentation, that since AWS is running libvirt, that particular range, or a CIDR with that in it, can not be used.

**Comment by kalexand-rh** [comment]
> @bscott-rh Please coordinate with @yunjiang29 in getting this added to the doc. For some reason, I am unable to assign this PR to you. @kalexand-rh Any idea why I cannot assign this to Ben. His handle does not appear when I try to add him to the Assignes.

It's probably an org membership issue.
