### ISSUE TITLE
[online] Issue in file rosa_support/rosa-troubleshooting-iam-resources.adoc

### ISSUE THREAD

**Issue by mauroseb** [openshift/openshift-docs#49322]
### Which section(s) is the issue in?
Troubleshooting IAM roles. Procedure.

### What needs fixing?

The second command in the procedure is the repeating the first "rosa list ocm-role", while it should read "rosa list user-role"

**Comment by bergerhoffer** [comment]
Marking this as a good candidate for Hacktoberfest.

Link: https://docs.openshift.com/rosa/rosa_support/rosa-troubleshooting-iam-resources.html#rosa-sts-ocm-roles-and-permissions-troubleshooting_rosa-troubleshooting-iam-resources

PR should be opened against `main`, ping me with any questions!

**Comment by YashasviChaurasia** [comment]
@bergerhoffer I would like to work on this issue.
Could you assign it to me?
Thank you

**Comment by bergerhoffer** [comment]
Hi @YashasviChaurasia! I'm sorry it looks like someone fixed this already via PR #50661, but the issue wasn't assigned or closed.

If you're still interested in another straightforward issue to work on, we have this issue #51946 which I just marked for Hacktoberfest. Please feel free to comment in that issue if you'd like me to assign it to you!

Closing this issue
