### ISSUE TITLE
[enterprise-4.8] Issue in file networking/network_policy/logging-network-policy.adoc

### ISSUE THREAD

**Issue by inderpaltiwana** [openshift/openshift-docs#49379]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.8/networking/network_policy/logging-network-policy.html

### What needs fixing?
Typo in the Disabling network policy audit logging for a namespace section of the docs from version 4.8 to current

**Comment by inderpaltiwana** [comment]
Have created a PR for this issue here https://github.com/openshift/openshift-docs/pull/49380

**Comment by ahardin-rh** [comment]
Thank you! This is now addressed
