### ISSUE TITLE
[enterprise-4.10] Issue in file installing/disconnected_install/installing-mirroring-disconnected.adoc

### ISSUE THREAD

**Issue by haf-tech** [openshift/openshift-docs#49427]
### Which section(s) is the issue in?

In prerequisites

### What needs fixing?

The referenced link to retrieve oc-mirror plugin is not compatible to the OCP v4.10.x version. Using the referenced version results in non working catalog sources, see e.g. 
https://github.com/openshift/oc-mirror/issues/502

**Comment by bergerhoffer** [comment]
@jpower432 Based on your comment here: https://github.com/openshift/oc-mirror/issues/502#issuecomment-1222490477

It seems like the latest oc-mirror binary posted for 4.11 should work with 4.10. Let me know if that ends up not being the case.

Or even if it is supposed to, I wonder whether we should update the docs to download the 4.10-specific binary anyways. I'm not positive where that other location might be though. I checked the OCP web console and didn't see it listed in the CLI tools area there. Let me know what you think!

**Comment by bergerhoffer** [comment]
Thanks for the reply @jpower432, and that make sense. If the 4.11 oc-mirror binary does indeed work properly with 4.10 OCP, then I'm fine with keeping things as they are. But if it doesn't work, then it seems like we should make an update here. 

Just let me know what the outcome of the related oc-mirror issue is (https://github.com/openshift/oc-mirror/issues/502) and if we need do do anything to the docs, or leave it as is. Thanks!

**Comment by dmesser** [comment]
oc-mirror in 4.11 is the way to go and it supports mirroring catalogs of releases starting with OCP 4.9 onwards.

**Comment by haf-tech** [comment]
so the latest `oc-mirror`did not worked for OCP 4.10, this is the reason why I created both issues, this one and https://github.com/openshift/oc-mirror/issues/502

The oc-mirror version for 4.10 and 4.11 supports also not the same `ImageSetConfiguration` structure/version etc.

**Comment by dmesser** [comment]
@haf-tech It seems in #502 you are trying to use oc-mirror 4.10 to mirror a 4.11 catalog. In 4.10 oc mirror was tech preview and got significantly improved for GA in 4.11. In the process the config file formats changed. Let's keep that discussion in #502. It seems you yet have to confirm that the issue occured with 4.11 oc-mirror on a 4.10 catalog.

**Comment by haf-tech** [comment]
well, In this issue I will only emphasize that the link/references in the OpenShift docu for 4.10 is not correct, due the fact referencing the latest version of oc-mirror, which does not work with OCP 4.10
After explicitly using the binary from the 4.10 branch was the mirroring successful
