### ISSUE TITLE
[enterprise-4.9] Issue in file nodes/pods/nodes-pods-autoscaling.adoc

### ISSUE THREAD

**Issue by pjnroll** [openshift/openshift-docs#49431]
### Which section(s) is the issue in?
Creating a horizontal pod autoscaler for CPU utilization by using the CLI

### What needs fixing?
There is a repetition in the sentence "Perform one of the following one of the following:"

**Comment by bergerhoffer** [comment]
Marking this as a good candidate for Hacktoberfest.

Open the PR against the 'main' branch, and ping me with any questions!

**Comment by bergerhoffer** [comment]
This was fixed via #51170. Closing!
