### ISSUE TITLE
[enterprise-4.10] Issue in file installing/disconnected_install/installing-mirroring-disconnected.adoc

### ISSUE THREAD

**Issue by andrea-mh** [openshift/openshift-docs#49529]
### Which section(s) is the issue in?
Use case: Including arbitrary images and helm charts
https://docs.openshift.com/container-platform/4.10/installing/disconnected_install/installing-mirroring-disconnected.html#oc-mirror-image-set-examples_installing-mirroring-disconnected

### What needs fixing?
The documentation should be changed to reference version 4.10 instead of 4.9 in the OCP channel and Operator Catalog:
mirror:
 ocp:
   channels:
     - name: stable-4.9
 operators:
   - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.9

Many thanks in advance!

**Comment by bergerhoffer** [comment]
Thanks for pointing this out! I've submitted #50136 to fix these versions.

**Comment by bergerhoffer** [comment]
Closing - the PR to fix this was merged in September!
