### ISSUE TITLE
[enterprise-4.11] Issue in file migration_toolkit_for_containers/advanced-migration-options-mtc.adoc

### ISSUE THREAD

**Issue by Ejdesgaard** [openshift/openshift-docs#49531]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.11/migration_toolkit_for_containers/advanced-migration-options-mtc.html -> known issue

### What needs fixing?
Mention https://github.com/kubernetes/kubernetes/issues/7452 when talking about SPDY, since it's been deprecated since 2021.

**Comment by apinnick** [comment]
@RichardHoch

**Comment by apinnick** [comment]
@RichardHoch

**Comment by anarnold97** [comment]
JIRAPROJECT-MIG-1304
