### ISSUE TITLE
[enterprise-4.11] Issue in file updating/updating-cluster-cli.adoc

### ISSUE THREAD

**Issue by mrVectorz** [openshift/openshift-docs#49547]
### Which section(s) is the issue in?
Updating a cluster by using the CLI

### What needs fixing?
All examples and outputs were directly copied from the 4.10 docs.

Example, instead of `oc adm upgrade channel stable-4.10` it should be `oc adm upgrade channel stable-4.11`

**Comment by bergerhoffer** [comment]
@kalexand-rh FYI I did a search and it looks like there are still a lot of other instances of 4.10 that didn't get updated to 4.11 when the sweep was done prior to GA. So whoever takes this should do another sweep to catch all of the missed instances.

**Comment by sheriff-rh** [comment]
Hi @mrVectorz  would you mind reviewing #54301 ? I updated the commands and outputs to environment variables that populate the version based on the viewed version, making it future-proof.
