### ISSUE TITLE
[enterprise-4.10] Issue in file logging/cluster-logging-loki.adoc

### ISSUE THREAD

**Issue by gnunn1** [openshift/openshift-docs#49561]
### Which section(s) is the issue in?

Deploying the LokiStack

### What needs fixing?

The yaml that has effectiveDate needs to be quoted, i.e. instead of:

    storage:
      schemas:
      - version: v12
        effectiveDate: 2022-06-01

It should be:

    storage:
      schemas:
      - version: v12
        effectiveDate: '2022-06-01'
        
Otherwise it fails to deploy

**Comment by cbremble** [comment]
Added to Jira: https://issues.redhat.com/browse/RHDEVDOCS-4397
