### ISSUE TITLE
[enterprise-4.11] Issue in file windows_containers/windows-containers-release-notes-6-x.adoc

### ISSUE THREAD

**Issue by bmarlow** [openshift/openshift-docs#49619]
### Which section(s) is the issue in?
Table 1. Platform networking support.

### What needs fixing?
The previous table lists 'bare metal or provider agnostic'
This table just lists 'bare metal'

This table should be updated so that the verbiage matches and it also says 'bare metal or provider agnostic'

There are customers running Nutanix who read this as Windows Nodes will not work on OpenShift on top of Nutanix, when they will, however they just fall into the 'provider agnostic' category.

**Comment by mburke5678** [comment]
PR merged. Closing
