### ISSUE TITLE
[enterprise-4.11] Issue in file migration_toolkit_for_containers/advanced-migration-options-mtc.adoc

### ISSUE THREAD

**Issue by Ejdesgaard** [openshift/openshift-docs#49638]
### Which section(s) is the issue in?
State migration

### What needs fixing?
In section "State migration", the Prerequisites, Procedure and following NOTE repeated.
The later repeat should be removed.

**Comment by bergerhoffer** [comment]
@sbeskin-redhat Can you please look into this? It looks like the duplicate prereq/procedure/note were introduced in #45441. And I'm not sure if they're exactly the same or if one of them is more correct to keep.

**Comment by bergerhoffer** [comment]
@Ejdesgaard Thanks for noticing this error and reporting it!

**Comment by bergerhoffer** [comment]
/remove-lifecycle stale

@kalexand-rh this is still a problem (duplicate prereq + procedure in https://docs.openshift.com/container-platform/4.11/migration_toolkit_for_containers/advanced-migration-options-mtc.html#migration-state-migration-cli_advanced-migration-options-mtc)

I'm not sure of who the other migration contacts are to tag on this?

**Comment by apinnick** [comment]
@RichardHoch Could you please ping Andy Arnold and let him know?

**Comment by RichardHoch** [comment]
@apinnick -- will do.

**Comment by sbeskin-redhat** [comment]
@kalexand-rh @RichardHoch 
Fix: https://github.com/openshift/openshift-docs/pull/53811

**Comment by apinnick** [comment]
@sbeskin-redhat @RichardHoch 
The PR was never merged. It needs to be peer-reviewed, merged and cherrypicked.

**Comment by kcarmichael08** [comment]
Hi, preview is no longer available, but it looks OK. However, I think the body of the PR needs to be edited to indicate which version(s) to cherry pick to (I am not sure). Otherwise, LGTM.

**Comment by apinnick** [comment]
@sbeskin-redhat @anarnold97 
Keeping this issue open because the PR for fixing it was peer-reviewed but not merged or cherrypicked.
