### ISSUE TITLE
[enterprise-4.10] Issue in file release_notes/ocp-4-10-release-notes.adoc

### ISSUE THREAD

**Issue by tinacooke** [openshift/openshift-docs#49653]
### What needs fixing? A 106-page PDF downloads, but is entirely blank
[release_notes_ocp-4-10-release-notes.pdf](https://github.com/openshift/openshift-docs/files/9433822/release_notes_ocp-4-10-release-notes.pdf)

**Comment by bergerhoffer** [comment]
@kalexand-rh Just FYI here is a report of PDF issues - just so that we can test and hopefully close once that PDF generation fix is in.

**Comment by kalexand-rh** [comment]
Yes, the PDF printing is working. The PR that fixed it appears to be https://github.com/openshift/openshift-docs/pull/49194.
