### ISSUE TITLE
xref used in installation-initializing module

### ISSUE THREAD

**Issue by maxwelldb** [openshift/openshift-docs#49717]
### Which section(s) is the issue in?

Prerequisites section of "Creating the installation configuration file" (`modules/installation-initializing.adoc`).

### What needs fixing?

@mjpytlak I noticed this while working on a bug fix. xrefs aren't permitted in modules per our guidelines. 

The xref was introduced as part of #44537.

**Comment by mjpytlak** [comment]
Thanks @maxwelldb. I will take care of this shortly. You can track status in https://issues.redhat.com/browse/OCPBUGS-677
