### ISSUE TITLE
[enterprise-4.11] Issue in file cicd/gitops/setting-up-argocd-instance.adoc

### ISSUE THREAD

**Issue by tkagn** [openshift/openshift-docs#49816]
### Which section(s) is the issue in?

Deploying resources to a different namespace

### What needs fixing?

The "Configure the namespace" procedure has the following as a sample command:

oc label namespace <namespace> && \\
argocd.argoproj.io/managed-by=<instance_name> 

The command should be: 
oc label namespace <namespace> \ 
argocd.argoproj.io/managed-by=<instance_name>

**Comment by bergerhoffer** [comment]
Marking this as a good candidate for Hacktoberfest.

Issue is in this section: https://docs.openshift.com/container-platform/4.11/cicd/gitops/setting-up-argocd-instance.html#gitops-deploy-resources-different-namespaces_setting-up-argocd-instance

Make this change against the main branch and let me know if you have any questions!
