### ISSUE TITLE
Re-add vSphere to dynamic provisioning

### ISSUE THREAD

**Issue by ron1** [openshift/openshift-docs#4982]
OCP 3.6 supports vSphere dynamic provisioning. The documentation should be updated accordingly, PR https://github.com/openshift/openshift-docs/pull/3330 originally removed the vSphere dynamic provisioning documentation. This PR should be reverted.

**Comment by gnufied** [comment]
@gaurav-nelson can you please revert that documentation PR? It should have been reverted prior to 3.6 but I think sooner we do this better.

**Comment by gnufied** [comment]
@gaurav-nelson @ron1 I have added the documentation back - https://github.com/openshift/openshift-docs/pull/5197 ptal.

**Comment by gaurav-nelson** [comment]
Fixed by #5197
