### ISSUE TITLE
Redirect to welcome page

### ISSUE THREAD

**Issue by liggitt** [openshift/openshift-docs#499]
The following urls should redirect to the welcome page instead of giving 403 errors or hanging:

http://docs.openshift.org/latest
http://docs.openshift.org/latest/
http://docs.openshift.org/latest/welcome

**Comment by adellape** [comment]
The first two now redirect to the welcome page, however the third (http://docs.openshift.org/latest/welcome) still hangs/times out.

cc @nhr

**Comment by nhr** [comment]
Should be all set now, please verify.

**Comment by adellape** [comment]
LGTM! Thanks.
