### ISSUE TITLE
Update vSphere Cloud Provider prereqs to include VMware tools dependency

### ISSUE THREAD

**Issue by ron1** [openshift/openshift-docs#4992]
See the following vSphere Cloud Provider issue https://github.com/vmware/kubernetes/issues/223 and its proposed patch.

**Comment by gaurav-nelson** [comment]
@gnufied Can you check this one?

**Comment by gaurav-nelson** [comment]
This is already addressed via https://github.com/openshift/openshift-docs/pull/4853 and available at https://docs.openshift.com/container-platform/3.9/install_config/configuring_vsphere.html#vsphere-enabling

Closing this now.

**Comment by ron1** [comment]
Hello Guarav,

The vSphere Cloud Provider Prerequisites documentation available here: https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/prerequisites.html includes the following clause:

VMware Tools needs to be installed on the guest operating system on each Node VM. Please refer this link for instruction on installing VMware tools.

I could not find the above clause in the OpenShift vSphere Configuration documentation.

**Comment by gaurav-nelson** [comment]
Thanks @ron1 I will create a PR to address this.
