### ISSUE TITLE
[enterprise-4.10] Issue in file service_mesh/v1x/installing-ossm.adoc

### ISSUE THREAD

**Issue by faldanarh** [openshift/openshift-docs#49974]
### Which section(s) is the issue in?
Installing Service Mesh > Installing the Jaeger Operator

### What needs fixing?
There is a mentioning to install the "Jaeger Operator", however, it is not available anymore in the OperatorHub, it is called now "Red Hat OpenShift distributed tracing platform", as mentioned at the section "Installing Service Mesh > Installing the Operators".

Another question is, why do we have the sections which mention to install each operator individually like:
- Installing the OpenShift Elasticsearch Operator 
- Installing the Jaeger Operator (with the issue reported above)
- Installing the Kiali Operator

And the section "Installing the Operators" which covers all above with the right sequence and names?

**Comment by cbremble** [comment]
OSSM 1.x docs are no longer in support. This is correct in the supported versions of the docs.

**Comment by JStickler** [comment]
Closing as WONTFIX, Service Mesh version 1.0 and 1.1 are no longer supported on OpenShift 4.10 and the docs are not being updated.  **_This is noted in the warning at the top of every 1.x page in the documentation._**

Please refer to the 2.x documentation.
