### ISSUE TITLE
[enterprise-4.11] Issue in file logging/cluster-logging-deploying.adoc

### ISSUE THREAD

**Issue by LucianoRed** [openshift/openshift-docs#49985]
### Which section(s) is the issue in?

Installing the logging subsystem for Red Hat OpenShift using the web console

### What needs fixing?
In item 4, the name of the pods are not fluentd-xyz anymore. Now it's collector-xyz

**Comment by bergerhoffer** [comment]
Marking this as a good candidate for Hacktoberfest. It has a few things that need to be fixed, but is relatively straightforward.

1. In step 4 of this section: https://docs.openshift.com/container-platform/4.11/logging/cluster-logging-deploying.html#cluster-logging-deploy-console_cluster-logging-deploying, do the following:
    - Update the items in the list that start with `fluentd-` to start with `collector-` instead.
    - Since this list is alphabetical, move those `collector-*` entries to the top of the list.
2. These are also referenced in the example output of step 6 in this section: https://docs.openshift.com/container-platform/4.11/logging/cluster-logging-deploying.html#cluster-logging-deploy-cli_cluster-logging-deploying. So here, do the following:
    - Update the entries in the output that start with `fluentd-` to start with `collector-` instead.
    - Since this list is alphabetical, move those `collector-*` entries to the top of the example output.

The PR should be submitted against the main branch. Ping me with any questions!

**Comment by cbremble** [comment]
This work is already being done by @libander in https://issues.redhat.com/browse/RHDEVDOCS-3771, so I propose this issue be closed as a duplicate.

**Comment by bergerhoffer** [comment]
@cbremble Thanks for letting us know! Closing this as a duplicate - work for this will be done under https://issues.redhat.com/browse/RHDEVDOCS-3771.
