### ISSUE TITLE
Migrating Web Framework Applications: supported Node.JS versions wrong?

### ISSUE THREAD

**Issue by cben** [openshift/openshift-docs#5001]
https://docs.openshift.com/online/dev_guide/migrating_applications/web_framework_applications.html#dev-guide-migrating-web-framework-applications-node.js
https://github.com/openshift/openshift-docs/blob/master/dev_guide/migrating_applications/web_framework_applications.adoc#user-content-dev-guide-migrating-web-framework-applications-supported-Node.js-versions

- v2 and v3 both say "0.10".
  I'm trying out Openshift Online v3 and see Node.JS template offers "4" and "6 — latest".
- v3 also has a cell saying "Nodejs-mongodb-example (quickstart)" which doesn't look like a version number, unclear what is meant.
  I do see a "Node.js + MongoDB (Persistent)" template with no version dropdown, but it's not helpful to mention in versions table unless you can say something about the versions :-)

**Comment by gaurav-nelson** [comment]
Thank you @cben for pointing out this issue. 

I am closing this issue, and we are tracking it with https://bugzilla.redhat.com/show_bug.cgi?id=1487015
