### ISSUE TITLE
[enterprise-4.10] Issue in file scalability_and_performance/ztp-deploying-disconnected.adoc

### ISSUE THREAD

**Issue by joaquinfll** [openshift/openshift-docs#50050]
### Which section(s) is the issue in?

Adding RHCOS ISO and RootFS images to the disconnected mirror host. This also happens for version 4.11.

### What needs fixing?

The step "b. Download the required images:" is pointing to pre-release images in "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/"

I think this should reference the final release in "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.10/latest/"

**Comment by kelbrown20** [comment]
Updates docs
4.10 - https://docs.openshift.com/container-platform/4.10/scalability_and_performance/ztp-deploying-disconnected.html#ztp-acm-adding-images-to-mirror-registry_ztp-deploying-disconnected
4.11 - https://docs.openshift.com/container-platform/4.11/scalability_and_performance/ztp-deploying-disconnected.html#ztp-acm-adding-images-to-mirror-registry_ztp-deploying-disconnected

Setting to close

**Comment by joaquinfll** [comment]
@kelbrown20 the links in the section: 
The step "b. Download the required images:" is pointing to pre-release images in "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/"

Still points to the pre-release.

I can see you fixed the link in the section before that is also nice.

**Comment by kelbrown20** [comment]
@joaquinfll My apologies, that was my mistake. Thank you for pointing that out! Will make new PRs to fix the issue.

**Comment by kelbrown20** [comment]
Fix updated in PR #49805
