### ISSUE TITLE
[enterprise-4.10] Issue in file web_console/web-console.adoc

### ISSUE THREAD

**Issue by josgonza-rh** [openshift/openshift-docs#50168]
### Which section(s) is the issue in?
Multicluster console

### What needs fixing?
Link to the MCE documentation is wrong:
- Current / wrong one: https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.5/html/multicluster_engine_operator/index
- Correct one: https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.5/html/multicluster_engine/index

> **NOTE:** is also wrong in 4.11.

**Comment by kelbrown20** [comment]
Fix made in linked PR
Updated documentation: 
https://docs.openshift.com/container-platform/4.10/web_console/web-console.html#multi-cluster-about_web-console

Setting to close
