### ISSUE TITLE
[enterprise-4.10] Issue in file nodes/pods/nodes-pods-priority.adoc

### ISSUE THREAD

**Issue by slcmpunk** [openshift/openshift-docs#50173]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.10/nodes/pods/nodes-pods-priority.html

Including pod priority in pod scheduling decisions

### What needs fixing?
The second sentence needs the word pod capitalized since it is the first word in the sentence:
You can enable pod priority and preemption in your cluster. pod priority indicates the importance of a pod relative to other pods and queues the pods based on that priority. pod preemption allows the cluster to evict, or preempt, lower-priority pods so that higher-priority pods can be scheduled if there is no available space on a suitable node pod priority also affects the scheduling order of pods and out-of-resource eviction ordering on the node.

**Comment by bergerhoffer** [comment]
Thanks for submitting this issue and the PR to fix it @slcmpunk! We'll get it through :slightly_smiling_face:

**Comment by bergerhoffer** [comment]
PR has been merged - closing! Updates will be live shortly
