### ISSUE TITLE
Job's config lifecycle and restart command

### ISSUE THREAD

**Issue by ksemaev** [openshift/openshift-docs#5021]
The documentation https://docs.openshift.org/latest/dev_guide/jobs.html  and https://docs.openshift.org/latest/dev_guide/cron_jobs.html lacks this information: what will happen to job config, after the job is done? How to restart it?

What I mean (steps to reproduce): 
- after I created a job and it's done it's work, it is still avaliable in `oc get jobs`.
- when I make cronjob, it is leaving jobs after they are done.
But when I look at oc get jobs (several days later): all jobs are gone. 

So if I need to run the same job once again - do I have to import the same yaml? Or can I somehow restart the job one more time?

**Comment by ahardin-rh** [comment]
@ksemaev Thanks! 

@soltysh I created a [documentation bug](https://bugzilla.redhat.com/show_bug.cgi?id=1485380) to better track the work to improve the docs. Any advice here?

**Comment by ksemaev** [comment]
Updates:
- sronjob stops to create jobs, when source image:tag chnges. You have to recreate the same cronjob once again to make it work.
- so the questions now are: 
1) how to restart cronjob without deleting cronjob and making the same one from yaml?
2) how to start a job without importing the same yaml again?

**Comment by soltysh** [comment]
Once all the moving pieces are merged in k8s 1.8 we should be able to address all those concerns in our docs as well. I'll make sure to update k8s docs and we'll just need to copy&paste those, hopefully :)

**Comment by ksemaev** [comment]
@soltysh maybe you know howto restart job in current 1.6 and 1.7 ? Or will it be possible only since 1.8 ?

**Comment by ksemaev** [comment]
@soltysh  TY!
