### ISSUE TITLE
[enterprise-4.10] Issue in file installing/installing_ibm_cloud_public/installing-ibm-cloud-customizations.adoc

### ISSUE THREAD

**Issue by yocum137** [openshift/openshift-docs#50230]
### Which section(s) is the issue in?

In section "Manually creating IAM for IBM Cloud VPC" the 'Verification' step is unclear.  

### What needs fixing?

Currently it says this:

    Ensure that the appropriate secrets were generated in your cluster’s manifests directory.

Customer suggests the wording should be this:

    Ensure that the secrets are generated in your cluster's installation_dir where the manifest files are located.

SFDC Case number is 03248677.

**Comment by bergerhoffer** [comment]
@kalexand-rh I was going to mark this as a Hacktoberfest candidate, but not sure if you think we should track it differently since there seems to be a support case attached. Let me know what you think.
