### ISSUE TITLE
[enterprise-4.11] Issue in file installing/disconnected_install/installing-mirroring-creating-registry.adoc

### ISSUE THREAD

**Issue by rgordill** [openshift/openshift-docs#50240]
### Which section(s) is the issue in?

Mirroring on a local host with mirror registry for Red Hat OpenShift

### What needs fixing?

Instead of

local host registry running on port 443

Should be

local host registry running on port **8443**

Additionally, a comment should be added that in case port 8443 is in use, it can be customized by using quayHostname=host:port (I have to debug because I get an error and nothing in logs suggested what was the issue).

**Comment by kalexand-rh** [comment]
Our feedback from QE is that the mirror registry doesn't allow port customization because of a known issue: https://issues.redhat.com/browse/PROJQUAY-2903

**Comment by rgordill** [comment]
Quite strange, I have it already working in another port with the config I suggested at the beginning of this issue...
