### ISSUE TITLE
[enterprise-4.11] Issue in file authentication/managing_cloud_provider_credentials/cco-mode-sts.adoc

### ISSUE THREAD

**Issue by nmasse-itix** [openshift/openshift-docs#50305]
### Which section(s) is the issue in?

* Creating AWS resources with the Cloud Credential Operator utility
* Updating AWS resources with the Cloud Credential Operator utility

### What needs fixing?

```
oc adm release extract --credentials-requests \
--cloud=aws \
--to=<path_to_directory_with_list_of_credentials_requests>/credrequests \ 
--quay.io/<path_to>/ocp-release:<version>
```

There is a double dash "--" before the name of the image. This generates an error :

```
error: unknown flag: --quay.io/openshift-release-dev/ocp-release@sha256:e04ee7eea9e6a6764df218bcce3ee64e1816445158a0763954b599e0fc96580b
See 'oc adm release extract --help' for usage.
```

**Resolution**: remove the double dash before the image name. 

```
oc adm release extract --credentials-requests \
--cloud=aws \
--to=<path_to_directory_with_list_of_credentials_requests>/credrequests \ 
quay.io/<path_to>/ocp-release:<version>
```

**Comment by bergerhoffer** [comment]
Marking this as a good candidate for Hacktoberfest.

The PR to fix this should be submitted against the main branch, and ping me with any questions!

**Comment by skrthomas** [comment]
PR merged!
