### ISSUE TITLE
[enterprise-4.11] Issue in file serverless/cli_tools/installing-kn.adoc

### ISSUE THREAD

**Issue by hbelmiro** [openshift/openshift-docs#50385]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.11/serverless/cli_tools/installing-kn.html#installing-cli-web-console_installing-kn

### What needs fixing?
The Knative CLI (kn) doesn't appear in the Command Line Tools page on OpenShift web console.

![Screenshot from 2022-09-14 10-43-44](https://user-images.githubusercontent.com/11776454/190170809-3fd6aa68-9d66-4f22-9540-b6d3a0dbfade.png)

**Comment by Preeticp** [comment]
@hbelmiro thanks for raising the issue. Can you confirm if the OpenShift Serverless Operator was installed on your cluster as mentioned in the Prerequisites section of the doc?

**Comment by skonto** [comment]
Hi @hbelmiro could you try install Serving and report back, as kn is available when Serving CR is reconciled.

**Comment by cbremble** [comment]
@abrennan89 PTAL at this one
