### ISSUE TITLE
[enterprise-4.11] Issue in file backup_and_restore/index.adoc

### ISSUE THREAD

**Issue by hashnao** [openshift/openshift-docs#50438]
### Which section(s) is the issue in?
OADP requirements

### What needs fixing?
Does this refer to only S3-compatible object storage or all cloud storage services including Amazon S3, Azure Cloud Storage, etc? _The CloudStorage API for S3 storage is a Technology Preview feature only._
It may be applicable to only S3-compatible object storage, but it's unclear about which storage is referred to as there's no explanation about CloudStorage API.

**Comment by apinnick** [comment]
@RichardHoch Can you make sure Anjana knows about this? I don't know how to tag her here.

**Comment by RichardHoch** [comment]
@apinnick will do.

**Comment by apinnick** [comment]
@RichardHoch Does this need further action?

**Comment by RichardHoch** [comment]
@kaovilai Please check this.

**Comment by kaovilai** [comment]
We previously tried to cleanup the warning in this ticket https://issues.redhat.com/browse/OADP-300

If that is not enough.. we would appreciate the feedback as to what should be done here. We could rename the API name to something less likely to be directly associated with object storage support and just the automation pieces..

**Comment by hashnao** [comment]
@kaovilai Thanks for the info and I think it is enough with the description to let us understand. I wasn't sure about that because I didn't recognize CloudStorage API as a part of the OADP operator and missed reading [About installing OADP
](https://docs.openshift.com/container-platform/4.12/backup_and_restore/application_backup_and_restore/installing/about-installing-oadp.html).
This should be a minor fix but I found [About installing OADP](https://docs.openshift.com/container-platform/4.12/backup_and_restore/application_backup_and_restore/installing/about-installing-oadp.html) refers to _S3-compatible object storage, such as Noobaa or Minio_ and the API description, but [OADP requirements](https://docs.openshift.com/container-platform/4.12/backup_and_restore/index.html) missed them. Could you add the description to the page as well, so that we could get the meaning right away.

**Comment by RichardHoch** [comment]
@hashnao, https://docs.openshift.com/container-platform/4.12/backup_and_restore/index.html#oadp-requirements [OADP requirements] currently includes "S3-compatible object storage" as one way to meet the requirement of "object storage for storing backups." Are you asking that this be changed to "S3-compatible object storage, such as Noobaa and Minio"?

**Comment by hashnao** [comment]
@RichardHoch My apologies, it was my mistake. I meant that I wanted to have the "The CloudStorage API, which automates the creation of a bucket for object storage" comment shown in the [About installing OADP](https://docs.openshift.com/container-platform/4.12/backup_and_restore/application_backup_and_restore/installing/about-installing-oadp.html) section in the importation section in the [OADP requirements](https://docs.openshift.com/container-platform/4.12/backup_and_restore/index.html#oadp-requirements) section.

**Comment by RichardHoch** [comment]
@hashnao Thank you for clarifying. I, or someone else on the documentation team, will consult with the engineers and get back to you.

**Comment by anarnold97** [comment]
JIRAPROJECT-OADP-1227

**Comment by kaovilai** [comment]
Sure.

**Comment by briandooley** [comment]
@hashnao I have just found this issue now. Is it still an issue for you? If so, can you create a jira in the SRVCOM project with as much details as you can think of? Thanks.

**Comment by hashnao** [comment]
No, I don't think it's needed since it's already shown in the https://github.com/openshift/openshift-docs/issues/50438#issuecomment-1384432559 comment.

**Comment by briandooley** [comment]
Thanks for getting back to me. I will close this issue so.
