### ISSUE TITLE
[enterprise-4.11] Issue in file machine_management/creating-infrastructure-machinesets.adoc

### ISSUE THREAD

**Issue by patrickstrick** [openshift/openshift-docs#50528]
### Which section(s) is the issue in?
Binding infrastructure node workloads using taints and tolerations

### What needs fixing?
There are two issues; the first kind of nested in the second.

1. On the doc page for "Creating infrastructure machine sets", the [instructions for adding tolerations to the Infra workloads](https://docs.openshift.com/container-platform/4.11/machine_management/creating-infrastructure-machinesets.html#binding-infra-node-workloads-using-taints-tolerations_creating-infrastructure-machinesets) is not explictly laid out, and in fact has incorrect guidance. It states:
   ```Add tolerations for the pod configurations you want to schedule on the infra node, like router, registry, and monitoring workloads. Add the following code to the Pod object specification:```
...where the code sample is not specific, and worse adding code to the "pod" spec is not what you actually should do.
2. The broader issue is that the instructions for moving workloads to Infra nodes and setting the tolerations is duplicated in another section of the docs.
   1. For the monitoring components, that is located [here](https://docs.openshift.com/container-platform/4.11/monitoring/configuring-the-monitoring-stack.html#moving-monitoring-components-to-different-nodes_configuring-the-monitoring-stack) and in this section the accurate and detailed instructions for adding tolerations is included.
   2. For the other Infra workloads (router, registry, and logging) I do not see explicit instructions for adding the tolerations anywhere in the docs. These should be added to give the same level of detail as the monitoring has.

I would suggest removing the instructions from one of the sections, and linking the single source into the other section. Additionally, instructions need to be written up for adding tolerations to the router, registry, and logging components.

**Comment by patrickstrick** [comment]
@ahardin-rh could you help get this looked at, please?

**Comment by patrickstrick** [comment]
@bburt-rh Could you take a look at this one too, please?

**Comment by bburt-rh** [comment]
@patrickstrick I realize that some of the content you're referencing is for monitoring components, but because the gist of your suggestion involves other parts of the OCP docs, I'll have to ping other folks on the team to take a look at this one to see how best to proceed.

**Comment by JoelSpeed** [comment]
Reviewing this in standup yesterday, I think some of the ambiguity comes from how an individual interprets the statement `Add the following code to the Pod object specification:`. It's true that, as an end user, you don't go and directly edit a pod to add the toleration, but rather, you are supposed to edit the deployment/daemonset/statefulset, whichever owns the pod. But I think what the statements was trying to say, is that you need to edit the pod specification on the parent object. 
Each of these objects (unfortunately under different paths) has within it, an object `corev1.PodSpec`, this is the object that needs modifying and I think that is what `Pod object specification` is supposed to refer to.

So the challenge there would be, how do you make it obvious that we mean to edit the pod specification on the parent, when the parent could vary and be one of many options.

To actually move workloads to the infrastructure object, you need both a toleration and node selector, so if you read that section in isolation, it only permits the workloads onto the infra nodes, it doesn't force them over, but just below that [the movement is documented](https://docs.openshift.com/container-platform/4.11/machine_management/creating-infrastructure-machinesets.html#moving-resources-to-infrastructure-machinesets) so I think that's ok.

> For the other Infra workloads (router, registry, and logging) I do not see explicit instructions for adding the tolerations anywhere in the docs. These should be added to give the same level of detail as the monitoring has.

All of these are mentioned on the same page you linked under the [Moving resources to infrastructure machine sets](https://docs.openshift.com/container-platform/4.11/machine_management/creating-infrastructure-machinesets.html#moving-resources-to-infrastructure-machinesets) heading and then its subheadings. There are specific and full examples for each of the router/registry/logging in these sections

**Comment by jeana-redhat** [comment]
Thanks Joel for your input and context here.

**Pod spec edits**

> But I think what the statements was trying to say, is that you need to edit the pod specification on the parent object. [...] So the challenge there would be, how do you make it obvious that we mean to edit the pod specification on the parent, when the parent could vary and be one of many options.

Is there a command the user can run to determine the parent object of the pod they care about? If we can tell them how to find this, and then explain that they need to find `corev1.PodSpec` in the parent object and add the `tolerations` stanza to it, perhaps that would help.

**Moving workloads**

I am not sure that I agree with removing duplication - we want users to be able to find what they need from places they might be looking for it. In this case, I think that means in both the general infra area and in the docs for the specific components. Our authoring tools allow for reused content to be included with context-specific details in multiple locations, so we can leverage that for this.

It seems like the "Moving monitoring components to different nodes" procedure in the monitoring content area is a more detailed version of step 1 of "Moving the monitoring solution" in the infra machine set content. Would it be helpful to replace the "Moving the monitoring solution" procedure with the "Moving monitoring components to different nodes" procedure (and maybe add steps 2-3 of the former to the latter, since they explain how to make sure the move is happening)?

For the other components (router, registry, and logging), if we want a more detailed procedure like the one in the monitoring section, I think those could be created as an enhancement to what we already have.

**Comment by JoelSpeed** [comment]
> Is there a command the user can run to determine the parent object of the pod they care about? If we can tell them how to find this, and then explain that they need to find corev1.PodSpec in the parent object and add the tolerations stanza to it, perhaps that would help.

We could work something out. Each Pod will have an `OwnerReference` that points to it's owner. For a DaemonSet and StatefulSet, it will point to it directly. The link to a Deployment is indirectly through a ReplicaSet, so a little trickier, but yes, in theory an `oc` command could be used. In theory `
oc get pod -n <namespace> <name> -o json | jq '.metadata.ownerReferences[].kind'` would give you a hint

**Comment by jeana-redhat** [comment]
I am closing this issue in favor of Jira ticket OSDOCS-4823. This will likely yield several docs tasks to capture different facets of the work, and those are probably best to spread across the team (i.e., router, registry, and logging content is better served by the writers who know those components). Thanks @patrickstrick for bringing this up!
