### ISSUE TITLE
[enterprise-4.11] Issue in file windows_containers/windows-containers-release-notes-6-x.adoc

### ISSUE THREAD

**Issue by tosmi** [openshift/openshift-docs#50522]
### Which section(s) is the issue in?
Known issues, last sentence

### What needs fixing?
typo in _compatability_ -> compatibility

**Comment by bergerhoffer** [comment]
Thanks for reporting!

Marking this as a good candidate for Hacktoberfest.

If someone wants to take this, make the typo fix against the `main` branch. Thanks and ping me with any questions!!
