### ISSUE TITLE
[enterprise-4.10] Issue in file logging/cluster-logging-loki.adoc

### ISSUE THREAD

**Issue by EmmanuelKasper** [openshift/openshift-docs#50537]
### Which section(s) is the issue in?

Deploying the loki stack

### What needs fixing?

The pre requesites mentions for Loki:
- AWS S3 bucket for log storage

However we certainly support the following S3-compatible-APIs as stated in upstream (https://loki-operator.dev/docs/object_storage.md/).
I thus propose to replace the sentence above with:

- AWS S3 compatible bucket for log storage

**Comment by libander** [comment]
Duplicate of RHDEVDOCS-4467, done.
