### ISSUE TITLE
Incorrect placement of number icon in installation guide breaks installation command.

### ISSUE THREAD

**Issue by aditya-konarde** [openshift/openshift-docs#5057]
In the [Method 1: Running in a Container](https://docs.openshift.org/latest/getting_started/administrators.html#running-in-a-docker-container) section for the OpenShift installation guide, there is a misplaced number icon as seen in the screenshots, which introduces an additional space in the command if the command is copy-pasted directly to a terminal. The extra space causes the command to fail. Screenshot attached to show the current scenario.

![openshift docs](https://user-images.githubusercontent.com/6318164/29558577-24d69dca-874a-11e7-807d-89a5d454362a.png)

Expected fix:
Remove the '1' icon from the box that has the command, allowing users to copy-paste the command into the terminal and run it successfully.

**Comment by gaurav-nelson** [comment]
@aditya-konarde Thanks for pointing out this issue. 

I have created a bug for this at https://bugzilla.redhat.com/show_bug.cgi?id=1487017 and we are working on it. Closing this one as we are tracking it there.

**Comment by aditya-konarde** [comment]
@gaurav-nelson ack; Thanks :+1:
