### ISSUE TITLE
[enterprise-4.11] Issue in file welcome/index.adoc

### ISSUE THREAD

**Issue by rolfedh** [openshift/openshift-docs#50582]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.11/welcome/index.html

### What needs fixing?
The graphic looks like it is incorrectly sized. See attached screenshot.
![Screenshot from 2022-09-20 06-20-49](https://user-images.githubusercontent.com/350907/191233636-65f69da4-1a42-4cd9-856c-b6727d3b8b48.png)

**Comment by nate-duke** [comment]
same thing on [the okd site](https://docs.okd.io/4.11/welcome/index.html)
![image](https://user-images.githubusercontent.com/40432118/191262972-eb75f078-aca0-4195-8689-cf7b21608cd2.png)

**Comment by kalexand-rh** [comment]
@rolfedh @nate-duke does clearing your cache fix this issue?

**Comment by rolfedh** [comment]
All set. Thanks.
