### ISSUE TITLE
[enterprise-4.10] Issue in file nodes/nodes/eco-poison-pill-operator.adoc

### ISSUE THREAD

**Issue by acomabon** [openshift/openshift-docs#50581]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.10/nodes/nodes/eco-poison-pill-operator.html#configuring-machine-health-check-with-poison-pill_poison-pill-operator-remediate-nodes

### What needs fixing?
The name of the `PoisonPillRemediationTemplate` in the example `MachineHealthCheck` CR YAML should be `poisonpillremediationtemplate-sample`, or at least be consistent with the name in the `PoisonPillRemediationTemplate` CR YAML example.

**Comment by acomabon** [comment]
![image](https://user-images.githubusercontent.com/32303215/191227900-bb6834fb-2208-4d14-96bf-5d29a5d17b2f.png)

Here we call it `poisonpillremediationtemplate-sample`.

![image](https://user-images.githubusercontent.com/32303215/191227996-fd25a3f1-6876-41de-9221-0fb267a404e1.png)

Here, we call it `<poison-pill-remediation-template-sample>` which might be misleading.

**Comment by kelbrown20** [comment]
@acomabon Hi Alejandro! Can you PTAL at the attached PR to confirm the changes for this issue? Thank you!

**Comment by acomabon** [comment]
Hey @kelbrown20 thanks for reaching out.

I don't know the docs guidelines on this, but I'd be more inclined to use a "final" name in both examples, like `poisonpillremediationtemplate-sample` instead of using the replaceable one.

This would prevent copy&paste errors.

In any case, if you want to use your proposed solution, it's fine by me :)

**Comment by acomabon** [comment]
The reason about my proposal for using final names is because if someone just copy&pastes it and applies it on OpenShift, it will work well. But if they copy and paste the replaceable version, it will fail.

**Comment by kelbrown20** [comment]
Thank you or the feedback Alejandro! Yeah the adding a replaceable name in a yaml is sometimes dependent on the procedure. You brought up a great point though, so with the reasoning you mentioned,  I'll change it to `poisonpillremediationtemplate-sample`.

**Comment by kelbrown20** [comment]
@acomabon Just updated, can you add your lgtm if it looks good? Thank you!

**Comment by acomabon** [comment]
LGTM!

**Comment by kelbrown20** [comment]
Fix made in PR #51286 
Updated documentation: 
https://docs.openshift.com/container-platform/4.10/nodes/nodes/eco-poison-pill-operator.html#configuring-machine-health-check-with-poison-pill_poison-pill-operator-remediate-nodes

Setting to close
