### ISSUE TITLE
[enterprise-4.11] Issue in file migrating_from_ocp_3_to_4/installing-restricted-3-4.adoc

### ISSUE THREAD

**Issue by joaquinfll** [openshift/openshift-docs#50593]
### Which section(s) is the issue in?
`Installing the legacy Migration Toolkit for Containers Operator on OpenShift Container Platform 3` and other sections of the whole document. This is present in older version of OpenShift documentation too, ex. 4.10.

### What needs fixing?
sudo is not required for the `podman` commands. We can remove the unnecessary privilege escalation allowing a broader set of users to run it.

Example of existing code:
sudo podman cp $(sudo podman create registry.redhat.io/rhmtc/openshift-migration-legacy-rhel8-operator:v1.7):/operator.yml ./

Example of the sudo removal:
podman cp $(podman create registry.redhat.io/rhmtc/openshift-migration-legacy-rhel8-operator:v1.7):/operator.yml ./

**Comment by apinnick** [comment]
@RichardHoch Can you please make sure that Anjana is aware of this?

**Comment by RichardHoch** [comment]
@apinnick will do.

**Comment by RichardHoch** [comment]
@joaquinfll Is it safe/correct to globally replace "sudo podman" with "podman" throughout the entire MTC document, subject to QE verification of any PRs created?

**Comment by joaquinfll** [comment]
In my limited testing I found it to work without issue, I think it can be replaced in the entire MTC document.

**Comment by anarnold97** [comment]
JIRAPROJECT-MIG-1330

**Comment by sbeskin-redhat** [comment]
@joaquinfll 
Please check this PR: https://github.com/openshift/openshift-docs/pull/61274

**Comment by skrthomas** [comment]
@sbeskin-redhat Should I merge this one for 4.11 instead of cherrypicking from #61274
