### ISSUE TITLE
[enterprise-4.11] Issue in file security/certificate_types_descriptions/ingress-certificates.adoc

### ISSUE THREAD

**Issue by bit4man** [openshift/openshift-docs#50602]
Logo way too large
![Screenshot from 2022-09-20 13-40-41](https://user-images.githubusercontent.com/1713562/191327134-547bc768-6423-4ca5-87c5-6693c7ce3a4c.png)

### Which section(s) is the issue in?
I'm seeing it in most sections I open for OCP 4.11.

### What needs fixing?
Image WAY too large (see screendump attached).

**Comment by bergerhoffer** [comment]
@aireilly Didn't we see this issue a few weeks ago too? Was it just a refresh that was needed to fix it?

**Comment by aireilly** [comment]
Yes. And also a fix has gone in since that ensures this won't happen again.

**Comment by bergerhoffer** [comment]
Great thanks! Closing this issue then, sorry about that @bit4man!
