### ISSUE TITLE
[enterprise-4.11] Issue in file migrating_from_ocp_3_to_4/premigration-checklists-3-4.adoc

### ISSUE THREAD

**Issue by joaquinfll** [openshift/openshift-docs#50793]
### Which section(s) is the issue in?

In the "Target cluster" it is described:
"Set the value of the annotation.openshift.io/host.generated parameter to true for each OpenShift Container Platform route to update its host name for the target cluster. Otherwise, the migrated routes retain the source cluster host name."
This issue might be in other OpenShift versions of the documentation.

### What needs fixing?
- The described change needs to be done in the source cluster, it might be better to move it to that section or add some clarifications in this one.
- The annotation name is not correct or might be misleading. The annotation needs to be added or modified but the name of the annotation is "openshift.io/host.generated". Possible option:
    "Set the value of the annotation 'openshift.io/host.generated' parameter to 'true' for each OpenShift Container Platform route to update its host name for the target cluster. Otherwise, the migrated routes retain the source cluster host name."

**Comment by apinnick** [comment]
@RichardHoch Could you please ping Andy Arnold about this issue?

**Comment by RichardHoch** [comment]
@apinnick Have done so.

**Comment by anarnold97** [comment]
JIRAPROJECT-MIG-1320
