### ISSUE TITLE
[enterprise-4.10] Issue in file machine_management/applying-autoscaling.adoc

### ISSUE THREAD

**Issue by cepr1969** [openshift/openshift-docs#50801]
### Which section(s) is the issue in?
At least section ClusterAutoscaler resource definition

### What needs fixing?
The content in section https://docs.openshift.com/container-platform/4.10/machine_management/applying-autoscaling.html#cluster-autoscaler-cr_applying-autoscaling differs from the same section on https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html/machine_management/applying-autoscaling

In theory content on access.redhat.com/documentation/en-us/openshift_container_platform/4.10 and https://docs.openshift.com/container-platform/4.10 should be the same

**Comment by mburke5678** [comment]
@cepr1969 Thanks for pointing this out. I assume you are referring to the call-out numbering in the code block and the associated definitions? If so, this is a known issue when we use the same call-out number more than once in a code block ([Here](https://docs.openshift.com/container-platform/4.10/machine_management/applying-autoscaling.html#cluster-autoscaler-cr_applying-autoscaling), you can see that 7,8, and 9 are used twice.) We should be able to fix this up easily. 

If that is not your concern, please let me know what is.
