### ISSUE TITLE
[enterprise-4.8] Issue in file installing/installing_vsphere/installing-vsphere.adoc

### ISSUE THREAD

**Issue by rodlilearns** [openshift/openshift-docs#50837]
### Which section(s) is the issue in?
The section titled "Minimum Resource Requirements" in https://docs.openshift.com/container-platform/4.8/installing/installing_vsphere/installing-vsphere.html

### What needs fixing?
The third table does not have a title, and should have one for consistency.
The first and the second tables do have titles.
E.g. Table 1. Minimum supported vSphere version for VMware components
       Table 2. Minimum required hosts

**Comment by bergerhoffer** [comment]
Marking this as a good candidate for Hacktoberfest.

If someone is interested in taking it, please make the change against the master branch.

In this section: https://docs.openshift.com/container-platform/4.11/installing/installing_vsphere/installing-vsphere.html#installation-minimum-resource-requirements_installing-vsphere

The request is to add a `.Title` title for this table, like how the other tables in this page have them. If I had to suggest something off the top of my head it would "Minimum machine requirements" or "Minimum resource requirements" (though that's repetitive of the title), but feel free to come up with something better :smile:

**Comment by void-hr** [comment]
@bergerhoffer I would like to work on this.

**Comment by bergerhoffer** [comment]
@void-hr Great thanks! I've assigned the issue to you. Ping me once you have the PR open, or if you have any questions along the way. Thanks!

**Comment by void-hr** [comment]
@bergerhoffer I have made the changes but I was wondering if there is any way to check it is working as required before making the PR.

**Comment by bergerhoffer** [comment]
@void-hr If you want to try to build a preview locally to check, you could use 'asciibinder' to do it. The instructions to install that are here: https://github.com/openshift/openshift-docs/blob/main/contributing_to_docs/tools_and_setup.adoc#install-asciibinder-and-dependencies. And then you would just run `asciidbinder build`, and check in the `_preview/openshift-enterprise/<branch_name>/` directory for the right files and open in a browser to check.

But likely the easier thing would be to just open the PR. We have a preview bot that will generate that preview for you, usually within 10-15 minutes of opening the PR. (If you try it and you don't see a comment, let me know. And even after the comment appears, it still takes a few minutes after that to finish it). Once you get the link to your preview, you just navigate to the page with the updates and check that it looks okay that way. 

Let me know how it goes!

**Comment by void-hr** [comment]
@bergerhoffer I have opened the PR. Please take a look at PR #51164  whether I have done it decently or what improvements I could make in my PR. Or anything you would like to add.

**Comment by bergerhoffer** [comment]
Closing, since the PR has been merged!
