### ISSUE TITLE
[enterprise-4.10] Issue in file storage/persistent_storage/persistent-storage-iscsi.adoc

### ISSUE THREAD

**Issue by rhatbob** [openshift/openshift-docs#50841]
### Which section(s) is the issue in?
[Persistent storage using iSCSI ](https://docs.openshift.com/container-platform/4.10/storage/persistent_storage/persistent-storage-iscsi.html)

### What needs fixing?
"_OpenShift assumes that all nodes in the cluster have already configured iSCSI **initator**_" has a typo (i.e. "_initator_" -> initiator)

**Comment by skopacz1** [comment]
versions affected: 4.6+
