### ISSUE TITLE
[enterprise-4.11] Missing firewall requirement for installer node in vSphere UPI documentation

### ISSUE THREAD

**Issue by vagnerfarias** [openshift/openshift-docs#50868]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.11/installing/installing_vsphere/installing-vsphere.html#prerequisites
https://docs.openshift.com/container-platform/4.11/installing/installing_vsphere/installing-vsphere-network-customizations.html#prerequisites
https://docs.openshift.com/container-platform/4.11/installing/installing_vsphere/installing-restricted-networks-vsphere.html#prerequisites

### What needs fixing?
It's missing the requirement that the machine from which openshift-install is being executed must have access to vCenter.

Perhaps the following requirement could be modified from:

* If you use a firewall, you confirmed with the administrator that port 443 is accessible. Control plane nodes must be able to reach vCenter and ESXi hosts on port 443 for the installation to succeed.

To:

* If you use a firewall, you confirmed with the administrator that port 443 is accessible. Control plane nodes must be able to reach vCenter and ESXi hosts on port 443 for the installation to succeed. The computer running the installation program must be able to reach vCenter on port 443.

**Comment by jcpowermac** [comment]
Or just copy the exact text in IPI

```
The OpenShift Container Platform installer requires access to port 443 on the vCenter and ESXi hosts. You verified that port 443 is accessible.

If you use a firewall, you confirmed with the administrator that port 443 is accessible. Control plane nodes must be able to reach vCenter and ESXi hosts on port 443 for the installation to succeed.
```

fyi @GroceryBoyJr

**Comment by vagnerfarias** [comment]
@jcpowermac your suggestion sound better indeed. One question, though: does the installer need access to ESXi hosts for the UPI install?

**Comment by jcpowermac** [comment]
> @jcpowermac your suggestion sound better indeed. One question, though: does the installer need access to ESXi hosts for the UPI install?

No, the installer wouldn't but you might still need to import the ova. Now if you do it with the vCenter UI it won't require 443 to ESXi hosts. If you use `govc` or `powercli` it will.
