### ISSUE TITLE
[enterprise-4.11] Issue in file storage/persistent_storage/persistent-storage-local.adoc

### ISSUE THREAD

**Issue by NathanGuyot** [openshift/openshift-docs#50902]
### Which section(s) is the issue in?

_Automating discovery and provisioning for local storage devices_.

### What needs fixing?

There is a yaml sample of a localvolumeset. Under `spec` there is `fstype` should be `fsType` with a capital T.
I think it is present since this section have been created for 4.6.

I noticed it because I based my LocalVolumeSet on the sample of your documentation.

**Comment by bergerhoffer** [comment]
Marking this as a good candidate for Hacktoberfest.

If someone wants to take this, make the change against the `main` branch and let me know if you have any questions!

Here is the page: https://docs.openshift.com/container-platform/4.11/storage/persistent_storage/persistent-storage-local.html#local-storage-discovery_persistent-storage-local

**Comment by bobfuru** [comment]
I'll take this, @bergerhoffer. Let's see if I still got it. 😜

**Comment by bergerhoffer** [comment]
Heyooo hi @bobfuru!! Nice to hear from ya, it's all yours :tada:
