### ISSUE TITLE
Add parametr for default advanced installer

### ISSUE THREAD

**Issue by ksemaev** [openshift/openshift-docs#5092]
Acording to https://github.com/openshift/openshift-ansible/issues/5169  installer should be started with extra option  -e deployment_type=origin, otherwise installation fails.

**Comment by bmcelvee** [comment]
@ksemaev Should the command in 'Running the RPM-based Installer" (https://docs.openshift.org/latest/install_config/install/advanced_install.html#running-the-advanced-installation-rpm) be changed to the following:

`# ansible-playbook [-i /path/to/inventory] \
    ~/openshift-ansible/playbooks/byo/config.yml -e deployment_type=origin`

**Comment by ksemaev** [comment]
@bmcelvee Yes, indeed
