### ISSUE TITLE
Missing list of supported PersistentVolume plug-ins for Online

### ISSUE THREAD

**Issue by Miciah** [openshift/openshift-docs#5095]
Under OpenShift Online 3 / Architecture / Additional Concepts / Persistent Storage, the section [Types of Persistent Volumes](https://docs.openshift.com/online/architecture/additional_concepts/storage.html#types-of-persistent-volumes) states, "OpenShift Online supports the following `PersistentVolume` plug-ins:", but the section ends after this sentence, with no enumeration of the supported plug-ins.

We need to determine which `PersistentVolume` plug-ins are supported on Online Starter and Professional and add an enumeration or description of these plug-ins, conditionalized for Online.

**Comment by vikram-redhat** [comment]
This was fixed via this: https://github.com/openshift/openshift-docs/commit/b1117dbf22492da880af3f521370badf6bab9c3e#diff-2c29d4a206a2640eb896810bc42468e1. Closing this issue.
