### ISSUE TITLE
[enterprise-4.11] Issue in file hardware_enablement/psap-node-feature-discovery-operator.adoc

### ISSUE THREAD

**Issue by lalan7** [openshift/openshift-docs#50981]
### Which section(s) is the issue in?

The issue is related  this section --> [](https://docs.openshift.com/container-platform/4.11/hardware_enablement/psap-node-feature-discovery-operator.html#create-cd-cli_node-feature-discovery-operator
)

The example should be the same as we have over the  Create a NodeFeatureDiscovery CR using the web console  please refer below. Maybe the image: can be change to something more global.  The useful section will be all commented option like 

    deviceLabelFields:
      #      - "class"
            - "vendor"
      #      - "device"
      #      - "subsystem_vendor"
      #      - "subsystem_device"

### What needs fixing?

Please change the sample  section : 

Create the following NodeFeatureDiscovery Custom Resource (CR), and then save the YAML in the NodeFeatureDiscovery.yaml file:

For : The exact same sample provide by the Operator webconsole  you can fin the link here : 

https://github.com/openshift/cluster-nfd-operator/blob/master/config/samples/nfd.openshift.io_v1_nodefeaturediscovery.yaml

**Comment by louisphilippereid** [comment]
Having "class" by default in the documentation caused me some trouble when installing the Nvidia GPU Operator which is expecting "vendor" (or class_vendor) in the node labels.
