### ISSUE TITLE
[enterprise-4.11] Issue in file storage/container_storage_interface/persistent-storage-csi-vsphere.adoc

### ISSUE THREAD

**Issue by ankushmistary** [openshift/openshift-docs#51019]
### Which section(s) is the issue in?
The issue is with the section lacking: Features of Red Hat vSphere CSI Driver which can be similar to the [documentation in VMWare:](https://docs.vmware.com/en/VMware-vSphere-Container-Storage-Plug-in/2.0/vmware-vsphere-csp-getting-started/GUID-D4AAD99E-9128-40CE-B89C-AD451DA8379D.html#GUID-E59B13F5-6F49-4619-9877-DF710C365A1E__GUID-ADF6F066-9A96-4E54-8154-66519AA65B39)

So that customers get clarity with the features that are supported and those that aren't, the table mentioned in the above VMWare documentation can be referred to.

### What needs fixing?
`Features of Red Hat vSphere CSI Driver` section to be added.

**Comment by ankushmistary** [comment]
Can we have an update on this?

**Comment by lautou** [comment]
Hi could you have an update of this?
