### ISSUE TITLE
Broken or outdated links to the Kubernetes documentation

### ISSUE THREAD

**Issue by php-coder** [openshift/openshift-docs#5105]
1) https://docs.openshift.org/latest/architecture/infrastructure_components/kubernetes_infrastructure.html#node has the link to https://github.com/kubernetes/kubernetes/blob/master/docs/admin/node.md#node-management that doesn't exist.

2) https://docs.openshift.org/latest/architecture/infrastructure_components/kubernetes_infrastructure.html#kubelet has the link to https://cloud.google.com/container-engine/docs/node-images#container_manifest that does exist but looks like not what we want.

**Comment by gaurav-nelson** [comment]
I am closing this one and tracking it in PR #5133

**Comment by php-coder** [comment]
Typically we don't close the issues until PR is merged.

Also there is a special GitHub magic that allows to automatically close an issue after merging PR: https://help.github.com/articles/closing-issues-using-keywords/

**Comment by php-coder** [comment]
> Typically we don't close the issues until PR is merged.

P.S. Except the cases when issue is created in a separate issue tracker (like Bugzilla).
