### ISSUE TITLE
[enterprise-4.11] Issue in file installing/install_config/installing-customizing.adoc

### ISSUE THREAD

**Issue by pamoedom** [openshift/openshift-docs#51081]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.11/installing/install_config/installing-customizing.html#installation-special-config-storage_installing-customizing

### What needs fixing?

All Butane templates in the doc use the following layout example:
~~~
boot_device:
  layout: x86_64
~~~
However, only `ppc64le` option is mentioned as an alternative in one of the examples, we need to homogenize the doc and also include `aarch64` as optional layout for both examples.

Best Regards.

**Comment by aleskandro** [comment]
cc @kelbrown20 can you help with this issue?

**Comment by pamoedom** [comment]
**NOTE**: this doc improvement needs to cover also 4.10 doc, thanks.

**Comment by kelbrown20** [comment]
@aleskandro Will do! Thank you!

/assign kelbrown20

**Comment by kelbrown20** [comment]
Fix made in linked PR
Updated documentation: 
https://docs.openshift.com/container-platform/4.11/installing/install_config/installing-customizing.html#installation-special-config-encrypt-disk_installing-customizing

Setting to close
