### ISSUE TITLE
[enterprise-4.10] Issue in file authentication/managing-security-context-constraints.adoc

### ISSUE THREAD

**Issue by gfschmidt** [openshift/openshift-docs#51082]
### Which section(s) is the issue in?

[Default security context constraints](https://docs.openshift.com/container-platform/4.10/authentication/managing-security-context-constraints.html#default-sccs_configuring-internal-oauth)

Table 1. Default security context constraints Security context constraint ->  restricted SCC

Also applies to (older and) newer versions of OCP documentation, even if `restricted` SCC is deprecated with OCP 4.11.

### What needs fixing?

Wrong statement:
```
The restricted SCC:     
- Allows pods to use any FSGroup   
```
This implies the restricted SCC uses `RunAsAny` strategy for FSGroup but it uses `MustRunAs`:
```
# oc get scc restricted -o yaml
[...]
fsGroup:
  type: MustRunAs
[...]
```
So the `restricted` SCC does _not_ allow to pick _any_ value for fsGroup. fsGroup is using the pre-allocated default value from the namespace annotation which is the minimum value from the range specified in openshift.io/sa.scc.supplemental-groups. The selectable fsGroup range is limited to this minimum default value. So there is no choice at all.

Correct statement:
```
The restricted SCC: 
- Allows pods to use any FSGroup    <- Remove this item from the list of allowed items / it's_not_ allowed to use _any_ fsGroup  
--

**Comment by cbandy** [comment]
Seems to have been incorrect for a very long time:
- #13120

**Comment by cbandy** [comment]
Still an issue in 4.10, 4.11, and 4.12.

/remove-lifecycle stale
