### ISSUE TITLE
Issue with RedHat Logo in Openshift/OKD Doku

### ISSUE THREAD

**Issue by Contentways** [openshift/openshift-docs#51105]
There is an Issue with the RedHat Logo inside the whole Docs, see Screenshot for Details.
![Bildschirmfoto 2022-10-01 um 18 14 40](https://user-images.githubusercontent.com/96850116/193418475-d633f1ae-5756-436d-84ac-9cce08f03319.png)

**Comment by ADITYADAS1999** [comment]
can you share the page link ?

**Comment by Contentways** [comment]
https://docs.openshift.com/container-platform/4.11/welcome/index.html It's on the whole Docs.

**Comment by ADITYADAS1999** [comment]
> https://docs.openshift.com/container-platform/4.11/welcome/index.html It's on the whole Docs.

It looks fine for my local system

![8888](https://user-images.githubusercontent.com/58718316/193456170-252dfa4f-68bc-4e3a-83ac-a5478cf46cc0.PNG)

**Comment by Contentways** [comment]
lol, tested it with Firefox. Everything looks well. Seems that my Safari is the Problem.

**Comment by ADITYADAS1999** [comment]
> lol, tested it with Firefox. Everything looks well. Seems that my Safari is the Problem.

maybe your safari has some issue 🤔

**Comment by Contentways** [comment]
Yes, seems almost so. I'm going to clear the Cache and try it again later. So this issue can be closed.

**Comment by ADITYADAS1999** [comment]
> Yes, seems almost so. I'm going to clear the Cache and try it again later. So this issue can be closed.

Thanks for interacting 🙌🏻😇

**Comment by kalexand-rh** [comment]
Safari looks fine for me, too. Closing. :)
