### ISSUE TITLE
[enterprise-4.9] Issue in file welcome/oke_about.adoc

### ISSUE THREAD

**Issue by flozanorht** [openshift/openshift-docs#51102]
### Which section(s) is the issue in?

table 2

### What needs fixing?

Delete the row about the Jenkins Operator or add a note that it is deprecated since 4.8
https://access.redhat.com/errata/RHBA-2021:3243

**Comment by ADITYADAS1999** [comment]
This issue is still open for work ?

**Comment by bergerhoffer** [comment]
@ADITYADAS1999 yes it is, but in investigating I don't think any action is needed. If you're looking for something to contribute to for Hacktoberfest, you can search for other unassigned issues we have that are marked as good candidates for Hacktoberfest by using this query: https://github.com/openshift/openshift-docs/issues?q=is%3Aopen+is%3Aissue+label%3AHacktoberfest

@flozanorht It looks like the Jenkins Operator was removed in 4.10 (per this table [1] in the 4.10 release notes). It was removed from the table you suggest in 4.10, but in 4.9 it is still appropriate to be there.

For this reason, I'm closing this issue.

[1] https://docs.openshift.com/container-platform/4.10/release_notes/ocp-4-10-release-notes.html#ocp-4-10-deprecated-removed-features
