### ISSUE TITLE
[enterprise-4.11] Issue in file networking/ovn_kubernetes_network_provider/configuring-ipsec-ovn.adoc

### ISSUE THREAD

**Issue by lazharh** [openshift/openshift-docs#51100]
### Which section(s) is the issue in?

Enabling IPsec encryption

### What needs fixing?
the oc command to enable IPsec is same as the one to disable it. It must be an error
Procedure
To enable IPsec encryption, enter the following command:

$ oc patch networks.operator.openshift.io/cluster --type=json \
-p='[{"op":"remove", "path":"/spec/defaultNetwork/ovnKubernetesConfig/ipsecConfig"}]'

In the next section to disbale IPsec
---------------------
Procedure
To disable IPsec encryption, enter the following command:

$ oc patch networks.operator.openshift.io/cluster --type=json \
  -p='[{"op":"remove", "path":"/spec/defaultNetwork/ovnKubernetesConfig/ipsecConfig"}]'

**Comment by skrthomas** [comment]
A PR to fix this issue is open and pending merge once reviews are complete: https://github.com/openshift/openshift-docs/pull/51153
