### ISSUE TITLE
Enable SNO for OKD docs?

### ISSUE THREAD

**Issue by alexpdp7** [openshift/openshift-docs#51152]
### Which section(s) is the issue in?

```
- Name: Installing on a single node
  Dir: installing_sno
  Distros: openshift-enterprise
```

https://github.com/openshift/openshift-docs/blob/main/_topic_maps/_topic_map.yml#L299

### What needs fixing?

Does it make sense to make the SNO docs appear in the okd documentation?

**Comment by mburke5678** [comment]
@dmueller2001 @vrutkovs Any thoughts on this?

**Comment by vrutkovs** [comment]
It needs to be significantly rewritten:
* users will need to use installer from github releases instead of mirror.openshift.com
* references to console.redhat.com need to be replaced with selfhosted assisted installer

**Comment by mburke5678** [comment]
Added to [OKD planning board](https://github.com/okd-project/planning/issues/27).

**Comment by alexpdp7** [comment]
If https://github.com/okd-project/planning/issues/27 will be kept open even if this issue is closed, feel free to close, though.
