### ISSUE TITLE
[enterprise-4.11] Issue in file modules/storage-persistent-storage-pvc.adoc

### ISSUE THREAD

**Issue by eriksjolund** [openshift/openshift-docs#51212]
### Which section(s) is the issue in?

_Understanding persistent storage_
https://docs.openshift.com/container-platform/4.11/storage/understanding-persistent-storage.html

### What needs fixing?

Remove the word _by_ in the sentence:

_Claims must exist in the same namespace as the pod by using the claim._

A side-note: A similar sentence 

_Claims must exist in the same namespace as the Pod using the claim._

can be found here
https://github.com/kubernetes/website/blob/2f031cbfa023192a99451c47a791cb62da19792f/content/en/docs/concepts/storage/persistent-volumes.md?plain=1#L761

**Comment by void-hr** [comment]
Would like to work on this.

**Comment by eriksjolund** [comment]
@void-hr that sounds good me. (I'm not sure how issues are assigned though)

**Comment by void-hr** [comment]
I guess one with the write access can assign

**Comment by void-hr** [comment]
@aireilly Can I work on this issue. Could you assign me to this.

**Comment by aireilly** [comment]
@bergerhoffer can assign. I won't touch this one I promise 😀

**Comment by bergerhoffer** [comment]
Thanks @void-hr! I assigned this to you

**Comment by bergerhoffer** [comment]
@void-hr let me know when you open a PR and I'll take a look. Thanks again!

**Comment by void-hr** [comment]
@bergerhoffer I have opened a PR for the same. Let me know if I missed something.

**Comment by bergerhoffer** [comment]
Thanks @void-hr that PR looks great, we'll get that merged in. Thanks again for your contributions!!

**Comment by bergerhoffer** [comment]
Closing since the PR has been merged.
