### ISSUE TITLE
[dedicated] Issue in file osd_architecture/osd_policy/osd-service-definition.adoc

### ISSUE THREAD

**Issue by abozzoni** [openshift/openshift-docs#51266]
### Which section(s) is the issue in?
https://docs.openshift.com/dedicated/osd_architecture/osd_policy/osd-service-definition.html#cluster-self-service_osd-service-definition

### What needs fixing?
The **{cluster-manage-url}** has not any value in the following sentence:

Customers can create, scale, and delete their clusters from {cluster-manage-url}, provided that they have pre-purchased the necessary subscriptions.

**Comment by bergerhoffer** [comment]
@EricPonvelle @pneedle-rh @bmcelvee Can one of you take a look?

**Comment by pneedle-rh** [comment]
Hi @abozzoni and @bergerhoffer. Thanks for your updates. I am looking into this now.

**Comment by pneedle-rh** [comment]
Pull request: https://github.com/openshift/openshift-docs/pull/51278

**Comment by pneedle-rh** [comment]
This issue is now resolved.

**Comment by bergerhoffer** [comment]
Thanks @pneedle-rh!!
