### ISSUE TITLE
Formatting error in 4.9.z release notes 

### ISSUE THREAD

**Issue by opayne1** [openshift/openshift-docs#51367]
There is a formatting error in the 4.9.23 bug fixes section https://docs.openshift.com/container-platform/4.9/release_notes/ocp-4-9-release-notes.html#ocp-4-9-23-bug-fixes 

The (KCS*) is missing an additional * to make KCS bold.
Should be (**KCS**)

**Comment by void-hr** [comment]
I would like to work on this.

**Comment by void-hr** [comment]
@opayne1 @bergerhoffer Could you assign me please.

**Comment by bergerhoffer** [comment]
Thanks @void-hr!

**Comment by void-hr** [comment]
@bergerhoffer I found old PR of this release note and fixed the typo. But when I am opening the PR it includes 5000+ commits. Can you help me to figure out the solution.

**Comment by bergerhoffer** [comment]
@void-hr Looks like you figured out the solution (switching the base branch to 4.9 instead of main). Thanks for the PR - closing this issue since the PR has been merged!
