### ISSUE TITLE
[enterprise-4.10] Issue in file installing/installing_vsphere/installing-vsphere-installer-provisioned.adoc

### ISSUE THREAD

**Issue by AdamPeabody** [openshift/openshift-docs#51366]
### Which section(s) is the issue in?
Roles and privileges required for installation

### What needs fixing?
Can you also list the permissions from the vcenter gui?   The permissions you have listed do not match up with vcenter gui.

**Comment by maxwelldb** [comment]
@xenolinux I think this would go to you, according to the history of `modules/installation-vsphere-installer-network-requirements.adoc`.

**Comment by xenolinux** [comment]
@AdamPeabody Would you please provide more details on the bug? Details such as 
1. Which permissions do not match up with the Vcenter GUI?
2. Doc link.
3. What kind of permissions do we need to list for the Vcenter GUI?

**Comment by xenolinux** [comment]
There is insufficient data to proceed with this bug hence, closing this ticket.

**Comment by jkwek** [comment]
With all due respect, I would like for us to have more time to respond before closing this, as we had less than a day to respond to your request for more information.

Speaking on behalf of @AdamPeabody, the permissions listed are in the vSphere API, but setting them from the GUI requires translating them from the API name to the GUI name.  Adam is asking if we can also see the GUI names to make it easier for customers to set permissions using the GUI (i.e. the vCenter web interface).  I can get you additional information if this is unclear.

**Comment by xenolinux** [comment]
> With all due respect, I would like for us to have more time to respond before closing this, as we had less than a day to respond to your request for more information.
> 
> Speaking on behalf of @AdamPeabody, the permissions listed are in the vSphere API, but setting them from the GUI requires translating them from the API name to the GUI name. Adam is asking if we can also see the GUI names to make it easier for customers to set permissions using the GUI (i.e. the vCenter web interface). I can get you additional information if this is unclear.

I will run this information through SME. I have reopened the ticket. Thanks for reaching out :)

**Comment by AdamPeabody** [comment]
@xenolinux What @jkwek said is correct, the permissions you have listed are the permissions as they show for the api.   The issue we had was linking those api permissions to what is displayed in the vcenter console.

**Comment by xenolinux** [comment]
@AdamPeabody the PR is created to update the vCenter ui permissions https://github.com/openshift/openshift-docs/pull/52846

**Comment by xenolinux** [comment]
The PR is merged and changes are live hence closing this issue
