### ISSUE TITLE
[enterprise-4.11] Issue in file cicd/pipelines/automatic-pruning-taskrun-pipelinerun.adoc

### ISSUE THREAD

**Issue by tbrodbeck** [openshift/openshift-docs#51421]
### Which section(s) is the issue in?
![Screenshot 2022-10-10 at 13 36 23](https://user-images.githubusercontent.com/24418160/194857619-1d2f16d5-04c0-4b9b-89b0-19a539c2958f.png)

### What needs fixing?
`error: unable to decode "tekton/base/pipeline.yaml": json: cannot unmarshal number into Go struct field ObjectMeta.metadata.annotations of type string`

**Comment by apinnick** [comment]
@sounix000 Could you please follow this up?
