### ISSUE TITLE
[enterprise-4.8] Issue in file release_notes/ocp-4-8-release-notes.adoc

### ISSUE THREAD

**Issue by rludva** [openshift/openshift-docs#51581]
### Which section(s) is the issue in?
The bug fixes that are included in the update are listed in the [RHSA-2022:6511](https://access.redhat.com/errata/RHSA-2022:6511) advisory.

### What needs fixing?
Link to RHSA-2022:6511 returns 404!

**Comment by bergerhoffer** [comment]
Marking this as a good candidate for Hacktoberfest.

Looks like the link and link text should have a prefix of "RHBA", not "RHSA". https://docs.openshift.com/container-platform/4.8/release_notes/ocp-4-8-release-notes.html#ocp-4-8-50

Whoever wants to take this, please make the update against the enterprise-4.8 branch, and ping me with any questions!
