### ISSUE TITLE
Taints and Tolerations - possible incorrect meaning

### ISSUE THREAD

**Issue by noelo** [openshift/openshift-docs#5159]
In the docs @ https://docs.openshift.org/latest/admin_guide/scheduling/taints_tolerations.html
It says under the NoSchedule effect that 

NoSchedule | New pods that do not match the taint are scheduled onto that node.

Based on my reading of https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/ this should read 

NoSchedule | New pods that do not match the taint are not scheduled onto that node.

However please check as my interpretation may be incorrect

**Comment by clemSeveillac** [comment]
I agree and I've just submitted that fix :)
