### ISSUE TITLE
Duplicate "oc edit" command in YAML code block

### ISSUE THREAD

**Issue by bergerhoffer** [openshift/openshift-docs#51946]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.11/logging/config/cluster-logging-collector.html#cluster-logging-collector-limits_cluster-logging-collector

### What needs fixing?
There are two commands to do "oc edit" in step 1. The one in the first code block is correct.

The second code block in step 1 should be just the YAML, but it has another "oc edit" command in it:
![image](https://user-images.githubusercontent.com/7443887/197018061-d0d30c94-6348-48e1-a951-7d1704ad3db1.png)

That `$ oc edit ClusterLogging instance` line (and the blank space below it) should be removed from the second code block.

**Comment by YashasviChaurasia** [comment]
@bergerhoffer I would like to work on this issue.
Could you please assign it to me?
Thank you

**Comment by bergerhoffer** [comment]
You got it @YashasviChaurasia! Thanks, and let me know if you have any questions!

**Comment by YashasviChaurasia** [comment]
@bergerhoffer Could you please specify the exact file to edit?
Thank you

**Comment by bergerhoffer** [comment]
Hi @YashasviChaurasia sorry it looks like we had some inconsistency in this file, so it is actually already correct on the 'main' branch, and doesn't need fixed there.

Instead, it should be fixed on the 'enterprise-4.12' branch. So this is the file: https://github.com/openshift/openshift-docs/blob/enterprise-4.12/modules/cluster-logging-collector-limits.adoc

**Comment by YashasviChaurasia** [comment]
@bergerhoffer I have submitted a PR at : #51958
Thank you

**Comment by YashasviChaurasia** [comment]
Can the above PR be merged, or do I still need to work on it?
Kindly guide me with any further changes which are required.
Thank you

**Comment by bergerhoffer** [comment]
Thanks @YashasviChaurasia! Your PR has been merged, thanks for submitting it!

Closing this issue.

**Comment by YashasviChaurasia** [comment]
Thank You for your guidance; I appreciate your help and support.
Could you please guide me to similar issues or issues of a slightly higher difficulty level?
I want to contribute more to open source and develop my skills along the way while I complete my hacktoberfest challenge.
Thank you again.

**Comment by bergerhoffer** [comment]
@YashasviChaurasia I'm so glad to hear that! I see you found another issue to work on, but I'll take a look tomorrow and see if I can find any other good ones if you're still interested in more!
