### ISSUE TITLE
Explain or link increased security constraints on containers in admin_guide/install/setup.adoc

### ISSUE THREAD

**Issue by maschmid** [openshift/openshift-docs#520]
In admin_guide/install/setup.adoc

> OpenShift will increase the security constraints on containers in later beta releases.

There are no more beta releases. There should be an explanation or a link to a description of the increased security constraints on containers.

**Comment by adellape** [comment]
@maschmid Thanks. Following up per https://github.com/openshift/openshift-docs/pull/441 to include a link, and in general planning to remove references to beta asap.
