### ISSUE TITLE
[online] Issue in file rosa_cluster_admin/rosa_monitoring/rosa-configuring-the-monitoring-stack.adoc

### ISSUE THREAD

**Issue by flozanorht** [openshift/openshift-docs#52057]
### Which section(s) is the issue in?

Configuring a local persistent volume claim
https://docs.openshift.com/rosa/rosa_cluster_admin/rosa_monitoring/rosa-configuring-the-monitoring-stack.html#configuring-a-local-persistent-volume-claim_rosa-configuring-the-monitoring-stack

### What needs fixing?

The example ConfigMap with "storageClassName: local-storage" and that requires the local storage operator (LSO) feels like a cut-and-paste example from on-premises OpenShift that would not work on ROSA at all.

Customers on ROSA would not be able to deploy the LSO because they cannot customize their infrastructure and worker node instances to provide additional local disks for the LSO. Even if they could,  why would they want do so? They already have AWS EBS block storage.

On-premises deployments of OpenShift may not have any block storage provider available and them may require the LSO as the "best" or "quickest" alternative. This is a different scenario than cloud-based deployments of OpenShift such as ROSA and OSD.

**Comment by karanthshashank** [comment]
Created a Jira card to take a look at this and update.

**Comment by bburt-rh** [comment]
Closing this as Obsolete per the comments in the linked OSDOCS Jira issue: https://issues.redhat.com/browse/OSDOCS-8980
