### ISSUE TITLE
[rhacs-docs-3.72] Issue in file installing/install-ocp-operator.adoc

### ISSUE THREAD

**Issue by Dave-c-Ross** [openshift/openshift-docs#52063]
### Which section(s) is the issue in?
Verifing Central installation -> 6.

### What needs fixing?
It says: _Alternatively, you can use the Red Hat Advanced Cluster Security for Kubernetes web console to find the link to the RHACS portal by performing the following commands:_

The instruction is to find the Red Hat Advanced Cluster Security for Kubernetes web console URL, hence the user can not actually use Red Hat Advanced Cluster Security for Kubernetes web console to find Red Hat Advanced Cluster Security for Kubernetes web console web link. :)

I guess it should look like: _Alternatively, you can use the Red Hat OpenShift Container Platform web console to find the link to the RHACS portal by performing the following commands:_

**Comment by bergerhoffer** [comment]
Marking this as a good candidate for Hacktoberfest, if someone wants to take it.

Link to page: https://docs.openshift.com/acs/3.72/installing/install-ocp-operator.html

Looks like the attribute will need changed. The `{product-title} web console` in step 6 should be `{ocp} web console`. 

@kcarmichael08 or @gaurav-nelson Can you help with which branch this update should be submitted against? Is it `rhacs-docs`?

**Comment by YashasviChaurasia** [comment]
@bergerhoffer I would like to work on this issue.
Thank you

**Comment by bergerhoffer** [comment]
Great thanks @YashasviChaurasia! I've assigned it to you :)

**Comment by kcarmichael08** [comment]
Please merge to `rhacs-docs` and cherry pick to `rhacs-docs-3.72` `rhacs-docs-3.71`and `rhacs-docs-3.70`. Let me know if you have any questions! TY!

**Comment by bergerhoffer** [comment]
Thanks @kcarmichael08!

@YashasviChaurasia You can open the PR against `rhacs-docs` and we will take care of the cherry picking part for you :slightly_smiling_face: Thanks!

**Comment by gaurav-nelson** [comment]
@YashasviChaurasia Are you working on this one?

**Comment by YashasviChaurasia** [comment]
Yes , will submit it today.

**Comment by bergerhoffer** [comment]
Hi @YashasviChaurasia, let us know if this is something you wanted to submit the update for soon, otherwise we'll have someone else work on it. Thanks!

**Comment by YashasviChaurasia** [comment]
@bergerhoffer I was unable to find where exactly the file should have been changed.
I could not find the exact attribute to change.
Could you please help me with that?
Thank you

**Comment by kcarmichael08** [comment]
Hi,
In the modules/verify-centrall-install-operator.adoc file, line 29, the variable being used, `{product-title}`, needs to be changed to `{ocp}`.  That's it, I think.

**Comment by bergerhoffer** [comment]
Thanks @kcarmichael08!

@YashasviChaurasia you'll need to check out your branch against the `rhacs-docs` branch (instead of `main`) to be able to see this file and make the change.

**Comment by kcarmichael08** [comment]
@YashasviChaurasia did a [pull request](https://github.com/openshift/openshift-docs/pull/55634) yesterday and it looks good, just one minor comment!

**Comment by bergerhoffer** [comment]
Thanks @kcarmichael08! I'll update the PR to mention this issue so that they're linked.
