### ISSUE TITLE
admin_guide/manage_authorization_policy is outdated

### ISSUE THREAD

**Issue by php-coder** [openshift/openshift-docs#5208]
Most of the commands on the page https://docs.openshift.org/latest/admin_guide/manage_authorization_policy.html don't work because on the latest version of OpenShift there no `clusterPolicy`, `policyBindings`, and `clusterPolicyBindings`:
```console
$ oc describe clusterPolicy
the server doesn't have a resource type "clusterPolicy"
$ oc describe clusterPolicyBindings
the server doesn't have a resource type "clusterPolicyBindings"
$ oc describe policyBindings 
the server doesn't have a resource type "policyBindings"
```
Yet another page that should be updated is https://docs.openshift.com/dedicated/getting_started/dedicated_administrators.html#gs-dedicated-admin-logging-in

CC @simo5

**Comment by varac** [comment]
Please update the docs to reflect recent (?) changes. I stumbled across the same problem like @php-coder  trying to follow https://docs.openshift.com/dedicated/admin_guide/manage_authorization_policy.html#viewing-local-policy.

**Comment by vikram-redhat** [comment]
This section was recently updated in the docs for 3.9. Please reopen if the issue persists.
