### ISSUE TITLE
Few images

### ISSUE THREAD

**Issue by bit4man** [openshift/openshift-docs#521]
Looking at sections like Architecture Overview, it's very verbose. No graphics to layout the architecture, where you could click on the architecture you want to learn on and get a short/long description.

**Comment by bit4man** [comment]
Clicking on a headline only opens the section - the right side panel does not change? This means I have to click twice to start reading the overview of the section I'm interested in?

**Comment by bit4man** [comment]
CLI Overview - where do you get the binaries from? Different platforms (Windows, Fedora, Mac etc)?

**Comment by adellape** [comment]
Under "Architecture", the "Overview" topic was updated to include an arch overview diagram:

OSE: https://docs.openshift.com/enterprise/3.0/architecture/overview.html
Origin: https://docs.openshift.org/latest/architecture/overview.html

We hope to include more images soon.
