### ISSUE TITLE
Add anchors to section headers

### ISSUE THREAD

**Issue by robmoore-i** [openshift/openshift-docs#52120]
(Re-opening this to clarify my original intention in https://github.com/openshift/openshift-docs/issues/51984)

### Which section(s) is the issue in?

The document generally.

### What needs fixing?

It should be possible to get an anchor to a doc section by e.g. clicking a header name. The existing anchors for higher level headings are great, and should be extended to work for all headings.

For example, the subsection titled "Support arbitrary user ids" under [this heading](https://docs.openshift.com/container-platform/4.8/openshift_images/create-images.html#images-create-guide-openshift_create-images) does not have a corresponding anchor. I would like this so that the shell code in my containers, which implements the suggests here, can have a comment that links to the place in the OpenShift documentation where that code's rationale originates.

**Comment by robmoore-i** [comment]
Thanks for looking into this. Looking into the HTML source isn't ideal, it would be better if there was a way that the heading could have a clickable anchor, while still being excluded from the TOC. The workaround is good to know though, thanks for that.

**Comment by apinnick** [comment]
@robmoore-i 
I suspect that the headings were suppressed because this section is a list of guidelines. We no longer support 4.8 but we could update this assembly for 4.9+, since it is still being used.
