### ISSUE TITLE
CLI Overview - no installation instructions?

### ISSUE THREAD

**Issue by bit4man** [openshift/openshift-docs#522]
CLI Overview - where do you get the binaries from? Different platforms (Windows, Fedora, Mac etc)?

**Comment by adellape** [comment]
Under "CLI Reference", the "Overview" and "Get Started with the CLI" topics were updated in the OSE docs to link to the client downloads on the Customer Portal:

https://docs.openshift.com/enterprise/3.0/cli_reference/overview.html
https://docs.openshift.com/enterprise/3.0/cli_reference/get_started_cli.html#installing-the-cli

In the Origin docs, the same topics were updated to link to the Releases page on GH:

https://docs.openshift.org/latest/cli_reference/overview.html
https://docs.openshift.org/latest/cli_reference/get_started_cli.html#installing-the-cli

**Comment by bit4man** [comment]
Sorry for the late reply here. I don't think the "download" link was there earlier - glad to see it now. I am concerned that this is a tar ball binary download. For Fedora/RHEL/CentOS why not use RPMs? This seems extremely dangerous, unsupported and impossible for customers who relies on a secure/transparent system to use?

**Comment by adellape** [comment]
@bit4man Only the Origin docs (docs.openshift.org) link to the binary. The Enterprise docs (docs.openshift.com and the builds on the Customer Portal[1]) link to RPMs[2] on the Customer Portal.

[1] https://access.redhat.com/beta/documentation/en/openshift-enterprise-30-cli-reference/chapter-2-get-started-with-the-cli
[2] https://access.redhat.com/downloads/content/290/ver=3.0.0.0/rhel---7/3.0.0.0/x86_64/product-downloads

**Comment by adellape** [comment]
@bit4man Sorry, scratch that, spoke too soon. I see now they're tar.gz's as well.

**Comment by adellape** [comment]
@bit4man Double sorry, double spoke too soon. Here's the openshift-clients RPM on the Customer Portal:

https://access.redhat.com/downloads/content/rhel---7/x86_64/4025/openshift-clients/3.0.0.1-1.git.4.eab4c86.el7ose/x86_64/fd431d51/package

Or you can navigate to it from the "Packages" tab after following the link from the OSE docs.

**Comment by adellape** [comment]
Would be worth making that distinction in the OSE docs (availability of tarball vs RPM).
