### ISSUE TITLE
Headline click not consistent

### ISSUE THREAD

**Issue by bit4man** [openshift/openshift-docs#523]
Clicking on a headline only opens the section - the right side panel does not change? Some sections seems to do that others do not. That means my left and right content doesn't sync unless click twice - once for the headline, once for the actual section.

**Comment by CowboysFan** [comment]
@bit4man Can you please clarify this a bit more? I'm not sure if I understand the actual issue. Thanks.

**Comment by bit4man** [comment]
The menu on the side doesn't change the document section when you click on the headlines (those with + on them). You have to first click the headline, then click on the sub-headline to get the left side to change.

**Comment by tpoitras** [comment]
@bit4man : I'm not understanding this either. Can you please provide a link to what you're seeing so I can try to replicate the problem?

**Comment by vikram-redhat** [comment]
I think this is as-designed behavior. The click on the headlines is meant to open the submenu first. Closing this issue.
