### ISSUE TITLE
[enterprise-4.11] Issue in file monitoring/configuring-the-monitoring-stack.adoc

### ISSUE THREAD

**Issue by coffeegoesincodecomesout** [openshift/openshift-docs#52340]
### Which section(s) is the issue in?

Warning
Do not use prometheus or prometheus_replica as key names, because they are reserved and will be overwritten.

### What needs fixing?

Can we add "cluster" as reserved key name? 
we have other Red hat products that set "cluster" as an external label and cases where the CU has set the label only for RHACM to overwrite it

**Comment by bburt-rh** [comment]
This would apply to the warning on this page: https://docs.openshift.com/container-platform/4.11/monitoring/configuring-the-monitoring-stack.html#attaching-additional-labels-to-your-time-series-and-alerts_configuring-the-monitoring-stack

**Comment by jan--f** [comment]
Which products set the cluster label? I'm not sure calling this out in the OCP documentation is ideal, since it might not impact many customers. Also some customers might already use this label without issue.
Maybe RHACM and the respective products would be better of using a more explicit label name? Say `rhacm_cluster` or similar?
cc @simonpasquier wdyt?

**Comment by simonpasquier** [comment]
Regarding `prometheus` or `prometheus_replica` labels, it could be handled by the cluster monitoring operator too (e.g. fail the reconciliation if they are defined by the user). I agree that other labels like `cluster` should be handled by each product (either code or documentation).

**Comment by coffeegoesincodecomesout** [comment]
perhaps that is now happening for ACM - 

https://bugzilla.redhat.com/show_bug.cgi?id=2122244

**Comment by bburt-rh** [comment]
@jan--f @simonpasquier What's your opinion? Does this content need to be added to the core monitoring docs? Or maybe it'd be better in a KCS article?

**Comment by jan--f** [comment]
A KCS article hardly ever a bad idea. I think this should however _not_ be included in the OCP Monitoring docs. From CMO's perspective using the `cluster` label is benign. CMO doesn't reserve it so it shouldn't have an opinion on it. If other components clash with ACM or similar systems this should be raised as a bug on those components and the ACM documentation should mention that using the `cluster` label name will cause issues.

**Comment by bburt-rh** [comment]
@coffeegoesincodecomesout What do you think of the idea of a KCS article? If you agree that that's the direction to go with this issue, then could you please close this? If not, can you provide some arguments in response to the points from @jan--f , whom I agree with (I'm the docs person for OCP monitoring).

**Comment by bburt-rh** [comment]
@coffeegoesincodecomesout Can you please respond to the comment by @jan--f ?

**Comment by coffeegoesincodecomesout** [comment]
we can close this, we have a couple of different KCS touching on this. this is only one can find at the moment: 
 
 https://access.redhat.com/solutions/6981407
