### ISSUE TITLE
404 link from admission control 

### ISSUE THREAD

**Issue by pweil-** [openshift/openshift-docs#5240]
https://docs.openshift.org/latest/architecture/additional_concepts/admission_controllers.html#admission-controllers-customizable-admission-plug-ins

Restricting Role Bindings link

**Comment by php-coder** [comment]
This link is only available to OpenShift Enterprise. The fix is so trivial that I couldn't fix it and submitted #5271

**Comment by vikram-redhat** [comment]
Closing this #5271 fixed it.
