### ISSUE TITLE
[enterprise-4.11] Issue in file monitoring/config-map-reference-for-the-cluster-monitoring-operator.adoc

### ISSUE THREAD

**Issue by subbarao-meduri** [openshift/openshift-docs#52507]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.11/monitoring/config-map-reference-for-the-cluster-monitoring-operator.html#prometheusk8sconfig

### What needs fixing?
Link to [AdditionalAlertmanagerConfig](https://docs.openshift.com/container-platform/4.11/monitoring/additionalalertmanagerconfig) in the table is broken

**Comment by cbremble** [comment]
Added to Jira: [RHDEVDOCS-4735](https://issues.redhat.com/browse/RHDEVDOCS-4735)

**Comment by bburt-rh** [comment]
This fix was made in #53924. It is merged and live at https://docs.openshift.com/container-platform/4.11/monitoring/config-map-reference-for-the-cluster-monitoring-operator.html#prometheusk8sconfig. So I'm closing this issue.
