### ISSUE TITLE
Reference to nonexistant section in most UPI docs

### ISSUE THREAD

**Issue by David-Igou** [openshift/openshift-docs#52600]
### Which section(s) is the issue in?

UPI Installation sections

### What needs fixing?

As a user when I open most of UPI docs, under the `User-provisioned DNS requirements` (https://docs.openshift.com/container-platform/4.10/installing/installing_vsphere/installing-vsphere-network-customizations.html#installation-dns-user-infra_installing-vsphere-network-customizations) section, there is a reference to a section that isn't present in the docs under a Note:

> It is recommended to use a DHCP server to provide the hostnames to each cluster node. See the DHCP recommendations for user-provisioned infrastructure section for more information.

There is no "DHCP Recommendations" in the documentation. "DHCP Recommendations" is written in italics, so it's implied to users that there is one. I think this is referring to the dhcp recommendations present here: https://docs.openshift.com/container-platform/4.10/installing/installing_vsphere/installing-vsphere-network-customizations.html#installation-infrastructure-user-infra_installing-vsphere-network-customizations

But this section isn't titled "DHCP Recommendations" - it's just a section that contains dhcp recommendations. 

The "DHCP Recommendations" note and that section were added the same commit (https://github.com/openshift/openshift-docs/commit/e3a2d5205fea95389eb2fec526c8e911ed7465e6#diff-0fa2c81e4c65621038a4806a7d920472a001a8f0225d565d01a6edb5fb583d22) so I think that's a safe assumption

**Comment by mburke5678** [comment]
@pamoedom Hello. You worked on the PR that includes the above commit. Can you provide any help?

**Comment by pamoedom** [comment]
Hi @David-Igou , there is no `DHCP recommendations` section, that phrase refers to the recommendations included in the `user-provisioned` section like you mentioned.

Maybe the wording is not fully accurate and we could say this instead:
~~~
See the DHCP recommendations *within* user-provisioned infrastructure section for more information.
~~~

But in general I think the note is clear enough, DHCP configuration doesn't need too much details, right?.

Out of curiosity, did you find any issue developing your UPI BM vSphere cluster following this documentation?

Best Regards.
