### ISSUE TITLE
[enterprise-4.11] Issue in file support/troubleshooting/troubleshooting-network-issues.adoc

### ISSUE THREAD

**Issue by mistergareth** [openshift/openshift-docs#52639]
### Which section(s) is the issue in?
The sample machine config to override the network interface for kubelet

Why is the ignition version parameter set to "3.1.0" instead of "3.2.0" in the docs for OCP 4.11?

The 4.11 docs use "version: 3.1.0" when, for example, the 4.7 docs specify using "version: 3.2.0".
Is this a typo? Or is it intended? And what is the risk or potential impact if someone specifies 3.1.0 instead of 3.2.0?

```
...
spec:
  config:
    ignition:
      version: 3.1.0   <=== Shouldn't this be "3.2.0" like in earlier versions of OCP?
...
```

Wouldn't the latest version of OpenShift also use the latest ignition version of 3.2.0?

Checking docs for other OCP versions, I found that both [4.10](https://docs.openshift.com/container-platform/4.10/support/troubleshooting/troubleshooting-network-issues.html) and [4.11](https://docs.openshift.com/container-platform/4.11/support/troubleshooting/troubleshooting-network-issues.html) both use "3.1.0" while [4.7](https://docs.openshift.com/container-platform/4.7/support/troubleshooting/troubleshooting-network-issues.html), [4.8](https://docs.openshift.com/container-platform/4.8/support/troubleshooting/troubleshooting-network-issues.html) and [4.9](https://docs.openshift.com/container-platform/4.8/support/troubleshooting/troubleshooting-network-issues.html) all use "3.2.0".

### What needs fixing?
Update the code in the sample machine config to be consistent with previous versions of docs to say "version 3.2.0" instead of "version 3.1.0" Unless that is intended. If it is correct as is (with older version) then maybe have a call-out highlighting this.

**Comment by jldohmann** [comment]
Thanks for filing the issue! I think from at least OCP 4.8 and onwards, Ignition is v3.2.0. @bgilbert can you confirm?

**Comment by bgilbert** [comment]
Thanks for reporting this.  The docs have a couple instances of logic like this:

```
:ign-config-version: 3.1.0
ifeval::[{product-version} > 4.6]
:ign-config-version: 3.2.0
endif::[]
```

where the `{product-version}` test is apparently doing a numeric comparison rather than a version comparison.  I'd suggest removing this logic, since every currently-supported OpenShift version uses Ignition spec 3.2.0.

Separately, it looks like there are also a couple hardcoded instances of `3.1.0` that should be updated.
