### ISSUE TITLE
[enterprise-4.11] Issue in file release_notes/ocp-4-11-release-notes.adoc

### ISSUE THREAD

**Issue by ceanders** [openshift/openshift-docs#52653]
### Which section(s) is the issue in?

Release notes and Adding a RHEL compute node

### What needs fixing?

It is my understanding that OpenShift 4.11 is actually tested with RHEL 8.6 worker nodes, but the documentation only states RHEL 8.4 and 8.5 as supported versions of RHEL for worker nodes as follows:

>>> OpenShift Container Platform 4.11 is supported on Red Hat Enterprise Linux (RHEL) 8.4 and 8.5, as well as on Red Hat Enterprise Linux CoreOS (RHCOS) 4.11.

And also in the section "https://docs.openshift.com/container-platform/4.11/machine_management/adding-rhel-compute.html"

>>> Base OS with "Minimal" installation option.
Base OS: RHEL 8.4 or 8.5 with "Minimal" installation option.

I may be incorrect, but I believe the documentation to be wrong by not including support for RHEL 8.6 worker nodes.

**Comment by mburke5678** [comment]
@ceanders Thank you for pointing this out.

The release notes were updated here: https://github.com/openshift/openshift-docs/pull/53654

@JoeAldinger You made the change to the release notes. Can you comment on Cedric's second comment?
