### ISSUE TITLE
Remove jolokia reference

### ISSUE THREAD

**Issue by tomason** [openshift/openshift-docs#528]
architecture/infrastructure_components/web_console.adoc

Please, make sure, this piece of documentation is not in official Red Hat documentation.

Jolokia is a  very insecure component that can cause trouble (like shutting down vm) if not secured properly (it is very easy to find the port that can be used for attack). That is why jolokia is contained within official JBoss images for OpenShift, but is only bound to localhost.
That means if you know you have to add port for jolokia, know the port (can be read from docker image), you can set it properly, so connect button shows in console, but it leads to blank page because jolokia is not accessible from outside the container.

**Comment by adellape** [comment]
@tomason By "this piece" you're referring to the #extended-console-for-integration-components section, correct?

cc @gashcrumb

**Comment by gashcrumb** [comment]
AFAIK that shouldn't be the case,  Kevin Connor was working on a solution to integrate with openshift's oauth similar to how jolokia 1.3.1 works.  So no more binding the port to localhost is necessary.  In addition the jolokia website documents several different ways jolokia can be secured,  so I wouldn't call it a 'very' insecure component,  it provides tons of flexibility in how it can be secured.

**Comment by tomason** [comment]
@adellape Yea, I meant #extended-console-for-integration-components

@gashcrumb That is the case right now with middleware images that will be released as part of 3.0 GA. I believe there are plenty of options to secure jolokia, however the one Kevin took is binding jolokia to localhost. This may change in later releases, but for 3.0 it will stay bound to localhost.

**Comment by tpoitras** [comment]
@tomason & @gashcrumb : is this still an issue?

**Comment by tomason** [comment]
It is still an issue, until OSE 3.1 is released. Then there should be some changes in both OpenShift and xPaaS images that will ensure the Jolokia works as expected.

**Comment by tpoitras** [comment]
3.1 has been released. Closing this as it's no longer an issue.
