### ISSUE TITLE
OKD - references to Redhat subscriptions for network tracing

### ISSUE THREAD

**Issue by lbrigman124** [openshift/openshift-docs#52913]
### Which section(s) is the issue in?
https://docs.okd.io/latest/support/gathering-cluster-data.html#support-collecting-network-trace_gathering-cluster-data

### What needs fixing?
Reference to Redhat subscriptions and Redhat portal accounts.

Also on the same base page are references to a network troubleshooting image
registry.redhat.io/openshift4/network-tools-rhel8:latest  
This requires an account and a Pull secret.  
There is an alternative image that we used but I cannot find it at this time.

**Comment by mburke5678** [comment]
https://github.com/openshift/openshift-docs/pull/53495

**Comment by mburke5678** [comment]
@lbrigman124 
Thanks for catching this! There were several other sections and text that needed to be hidden in this assembly.

PR is merged. Closing
