### ISSUE TITLE
[online] Issue in file rosa_architecture/rosa_policy_service_definition/rosa-policy-understand-availability.adoc

### ISSUE THREAD

**Issue by faldanarh** [openshift/openshift-docs#52915]
### Which section(s) is the issue in?
In the 'Cluster failure' section.

### What needs fixing?
It says:

"ROSA clusters have at least three control plane nodes and three infrastructure nodes that are preconfigured for high availability, either in a single zone or across multiple zones, depending on the type of cluster you have selected.", 

which is not correct, as in 'Single Zone', by default only two infrastructure nodes are deployed.

**Comment by rolfedh** [comment]
@kalexand-rh It seems like https://github.com/openshift/openshift-docs/pull/56277 addresses this issue. If so, can we close it?

**Comment by bergerhoffer** [comment]
Closing since the above PR resolves this issue
