### ISSUE TITLE
OKD Updating clusters section needs to be updated

### ISSUE THREAD

**Issue by binnes** [openshift/openshift-docs#53296]
### Which section(s) is the issue in?
**Understanding upgrade channels** and generally the **Updating clusters** section

### What needs fixing?
The docs nees to be updated to explain OKD only has a single update channel and fixes aren't back ported to previous minor releases.  The docs are the OCP docs, where OCP has multiple release channels

/assign @mburke5678

**Comment by mburke5678** [comment]
@binnes Why does OKD only have a single update channel and why aren't fixes aren't back ported to previous minor releases?

**Comment by binnes** [comment]
@mburke5678  This is mainly due to OKD being a community project.  We don't have sufficient resource to be able to have concurrently supported versions, so for OKD there is only a single update thread, we don't back port any fixes to previous versions

**Comment by mburke5678** [comment]
[Removed list of update channels in Understanding upgrade channels in separate PR.](https://github.com/openshift/openshift-docs/pull/57745)

**Comment by mburke5678** [comment]
@binnes @vrutkovs PTAL at my [first attempt PR](https://github.com/openshift/openshift-docs/pull/58413). Let me know if I missed anything or made incorrect changes.

**Comment by mburke5678** [comment]
Changes are live. https://docs.okd.io/latest/updating/index.html
