### ISSUE TITLE
[RHACS] Issue in file installing/installing_cloud_ocp/install-secured-cluster-cloud-ocp.adoc

### ISSUE THREAD

**Issue by dlbewley** [openshift/openshift-docs#53356]
### Which section(s) is the issue in?

_Installing secured cluster services_

### What needs fixing?

_7. If you are using Form view, enter the new project name by accepting or editing the default value, stackrox-secured-cluster-services._

The term "project name" seems misapplied to this dialog. The requested value defines the name of the SecuredCluster resource to be created, not a projet.

**Comment by dlbewley** [comment]
Also item _9. Enter a name for your SecuredCluster custom resource. Use a unique name for each secured cluster you are configuring._ seems to be redundant with item 7.

**Comment by kcarmichael08** [comment]
> 

Isn't the "name" the namespace/project (in OCP) name? The name of the secured cluster is further down. They are two different things, I believe?

![Screen Shot 2022-12-14 at 11 35 33 AM](https://user-images.githubusercontent.com/96192119/207654198-53abed27-a5d4-4ef6-81a9-d315200aa0c5.png)
