### ISSUE TITLE
[enterprise-4.11] Issue in file virt/virt-using-the-cli-tools.adoc

### ISSUE THREAD

**Issue by dominikholler** [openshift/openshift-docs#53361]
### Which section(s) is the issue in?

Documentation[ OpenShift Container Platform ](https://docs.openshift.com/container-platform/4.11/welcome/index.html)[Virtualization](https://docs.openshift.com/container-platform/4.11/virt/about-virt.html) Using the CLI tools

### What needs fixing?

The user requires the information that it is to required to configure the virtctl binary. This can be done either by setting the environment variable KUBECONFIG like this
```
export KUBECONFIG=/home/dominik/clusters/current/auth/kubeconfig
```
or to login via the "Copy login command" flow.

**Comment by apinnick** [comment]
@dominikholler 
Is this the correct place for this change? [Installing the virtctl client](https://docs.openshift.com/container-platform/4.11/virt/install/virt-enabling-virtctl.html#virt-installing-virtctl-client_virt-enabling-virtctl): Linux procedure

I'm not sure where the "Copy login command" alternative would go.

**Comment by dominikholler** [comment]
> [enable the virtctl client](https://docs.openshift.com/container-platform/4.11/virt/install/virt-enabling-virtctl.html#virt-enabling-virtctl).

Yes, either in the end of [Enabling the virtctl client](https://docs.openshift.com/container-platform/4.11/virt/install/virt-enabling-virtctl.html#virt-enabling-virtctl) or in the beginning of [Using the CLI tools](https://docs.openshift.com/container-platform/4.11/virt/virt-using-the-cli-tools.html#virt-using-the-cli-tools).

> I'm not sure where the "Copy login command" alternative would go.

This is generic to OpenShift. According to my understanding, OpenShift should have a generic instructions about oc in https://docs.openshift.com/container-platform/4.11/cli_reference/openshift_cli/configuring-cli.html , which virtctl could just reference. Do you agree? If so, another issue for OpenShift docs would be required.

**Comment by apinnick** [comment]
@dominikholler I tagged you in PR54135. Please review the step that addresses this issue. Thanks.
