### ISSUE TITLE
[enterprise-4.11] Issue in file logging/config/cluster-logging-moving-nodes.adoc

### ISSUE THREAD

**Issue by ikke-t** [openshift/openshift-docs#53460]
### Which section(s) is the issue in?

We installed OCP  Logging and elastic search. Due to high need of capacity we created three extra infra nodes for them, and tainted nodes to NoSchedule. Now following this guide to move the elasticsearch to given infra nodes failed. We got errors of not being able to mount storage to them. With help of storage specialist, we learned the the taint requires tolerations from storage driver pods to be able to get scheduled to the same nodes. There is no mention of any of this in the guide, it should be added.

### What needs fixing?

ElasticSearch will needs always storage. This guide should be added with note that if you run ODF and have tainted the nodes to NoSchedule, know to follow also this guide in order to get storage to work for logging: 

https://access.redhat.com/documentation/en-us/red_hat_openshift_data_foundation/4.11/html-single/managing_and_allocating_storage_resources/index#managing-container-storage-interface-component-placements_rhodf

It would have saved our time if there was this chapter on this page, please consider adding it:

```
If you tainted the logging nodes to NoSchedule to dedicate nodes only for logging, you need to allow also storage to schedule to the nodes. Otherwise logging won't be able to mount storage driver on the dedicated nodes. In case you use OpenShift Data Foundations (Ceph) and you taint to nodes, here is guide how to get rbd-csi plugin to schedule to logging node:

[Managing container storage interface (CSI) component placements](https://access.redhat.com/documentation/en-us/red_hat_openshift_data_foundation/4.11/html-single/managing_and_allocating_storage_resources/index#managing-container-storage-interface-component-placements_rhodf).
```

**Comment by cbremble** [comment]
Added to Jira: https://issues.redhat.com/browse/RHDEVDOCS-4786
