### ISSUE TITLE
Chapter 1 in generated docs is present twice

### ISSUE THREAD

**Issue by jpechane** [openshift/openshift-docs#535]
Once as a *openshift-enterprise-30-documentation* link and once as a *chapter-1-openshift-enterprise-30-documentation* link

**Comment by tnguyen-rh** [comment]
@jpechane 
I believe this was a transient error, in part related to some tooling / portal work in progress, and now no longer an issue.  Could you please confirm?

**Comment by vikram-redhat** [comment]
@tnguyen-rh - I checked and your assessment is correct. Closing this issue.
