### ISSUE TITLE
[OKD] Documentation is unclear about status of cgroups v2

### ISSUE THREAD

**Issue by jacksgt** [openshift/openshift-docs#53536]
### Which section(s) is the issue in?

"Enabling Linux control group version 2 (cgroup v2)"

* https://docs.okd.io/latest/nodes/clusters/nodes-cluster-cgroups-2.html
* https://docs.okd.io/latest/installing/install_config/enabling-cgroup-v2.html

"Adding kernel arguments to nodes"

* https://docs.okd.io/latest/post_installation_configuration/machine-configuration-tasks.html#nodes-nodes-kernel-arguments_post-install-machine-configuration-tasks
* https://docs.okd.io/latest/nodes/nodes/nodes-nodes-managing.html#nodes-nodes-kernel-arguments_nodes-nodes-jobs

### What needs fixing?

Several places in the OKD documentation explain how to enable cgroups v2 and that cgroups v1 is the default, when in fact cgroups v2 is the default since OKD 4.9.
This is extremely confusing for users. We should probably also add some documentation that describes how to identify a cluster that is running with cgroups v1 only, cgroups v1 + v2 mixed or cgroups v2 only.

**Comment by mburke5678** [comment]
@jacksgt Thanks for submitting this issue. As far as I know, [cgroup V2 was added as Developer Preview to OCP in 4.10.](https://docs.openshift.com/container-platform/4.10/release_notes/ocp-4-10-release-notes.html#ocp-4-10-node-cgroups-v2). The user needs a feature gate to enable it. 
Is the same not true in OKD?

**Comment by jacksgt** [comment]
Hi, thanks for your reply.

As indicated in the issue text, cgroups V2 has been enabled *by default* (for new installs) since OKD 4.9.
See:
* https://github.com/openshift/okd-machine-os/pull/227
* https://github.com/okd-project/okd/discussions/1002
