### ISSUE TITLE
CARTRIDGES VS IMAGES - termo pod is used without being defined

### ISSUE THREAD

**Issue by jpechane** [openshift/openshift-docs#536]
OpenShift v3 uses a declarative model where **pods** bring themselves in line with a predefined state

**Comment by adellape** [comment]
In https://docs.openshift.com/enterprise/3.0/whats_new/carts_vs_images.html, "pods" in that sentence now links to https://docs.openshift.com/enterprise/3.0/architecture/core_concepts/pods_and_services.html#pods.
