### ISSUE TITLE
[enterprise-4.11] Issue in file monitoring/configuring-the-monitoring-stack.adoc

### ISSUE THREAD

**Issue by patrickstrick** [openshift/openshift-docs#53660]
### Which section(s) is the issue in?
[Creating a user-defined workload monitoring config map](https://docs.openshift.com/container-platform/4.11/monitoring/configuring-the-monitoring-stack.html#creating-user-defined-workload-monitoring-configmap_configuring-the-monitoring-stack)

### What needs fixing?
Would this section be better placed in the [Enabling monitoring for user-defined projects](https://docs.openshift.com/container-platform/4.11/monitoring/enabling-monitoring-for-user-defined-projects.html) doc instead since (I believe) it only applies when workload monitoring is enabled per that doc and the steps described in this section are listed as a pre-req for the steps in that doc.

**Comment by bburt-rh** [comment]
@patrickstrick  - I'm the tech writer working on the OCP monitoring docs. 

Maybe it does make sense not to talk here about topics related to configuring UWM, though maybe it would be enough to include in the "Prerequisites" section here that UWM needs to be enabled before you can create config maps for it? WDYT?

**Comment by patrickstrick** [comment]
In my mind they should be in the same place, where ever that ends up being. I filed this issue after going through the process of enabling UWM on a cluster and with the info in different sections, the process was not clear or easy to follow.

**Comment by bburt-rh** [comment]
@patrickstrick That makes sense. We'll write this up in Jira as a monitoring docs issue, and then it'll be put into our queue for prioritization. I'll post the link the Jira here after it has been created. Thanks so much for your feedback! Much appreciated.

**Comment by bburt-rh** [comment]
@patrickstrick This issue is now being tracked in https://issues.redhat.com/browse/RHDEVDOCS-4894

**Comment by bburt-rh** [comment]
@patrickstrick I am going to close this issue since we are tracking it in https://issues.redhat.com/browse/RHDEVDOCS-4894 now.
