### ISSUE TITLE
[enterprise-4.10] Issue in file networking/changing-cluster-network-mtu.adoc

### ISSUE THREAD

**Issue by preetsinghharpreet** [openshift/openshift-docs#53709]
### Which section(s) is the issue in?

Section : **Changing the cluster MTU**
Point : **6 [Update the underlying network interface MTU value:]**

1. If are specifying the new MTU with a NetworkManager connection configuration, enter the following command.
2. If are specifying the new MTU with a DHCP server option or a kernel command line and PXE, make the necessary changes for your infrastructure.

### What needs fixing?

Shouldn't it be **If you are specifying** instead of if are specifying  ?

**Comment by mletalie** [comment]
@bergerhoffer Yes, thanks! 
/assign mletalie
