### ISSUE TITLE
CHAPTER 4. TERMINOLOGY - etcd is used without explanation/reference

### ISSUE THREAD

**Issue by jpechane** [openshift/openshift-docs#538]
are no longer necessary because **etcd** is typically installed with each master.

**Comment by tnguyen-rh** [comment]
Created BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1271314

**Comment by vikram-redhat** [comment]
Closing this as the BZ was created to track it. Thanks @tnguyen-rh .
