### ISSUE TITLE
Infrastructure Components Overview does not contain relevant text, onyl asks for docs contribution

### ISSUE THREAD

**Issue by jpechane** [openshift/openshift-docs#540]

**Comment by adellape** [comment]
The "Infrastructure Components" > "Overview" topic was superfluous and was removed in both OSE and Origin docs. The "Infrastructure Components" category now begins straight away with:

https://docs.openshift.com/enterprise/3.0/architecture/infrastructure_components/kubernetes_infrastructure.html
https://docs.openshift.org/latest/architecture/infrastructure_components/kubernetes_infrastructure.html
