### ISSUE TITLE
Clarify usage of s2i --scripts-url parameter

### ISSUE THREAD

**Issue by f-w** [openshift/openshift-docs#5403]
[S2I Scripts](https://docs.openshift.org/latest/creating_images/s2i.html#s2i-scripts) doc says 1st script location is from `--scripts-url` but I have no idea where can the parameter be supplied. My hunch is `oc start-build` but oc rejected the option. `oc start-build --help` didn't mention it either. After googling extensively I found an example from a japanese site using it as an option of `s2i build`. But `s2i` is not normally installed at client-side. Only `oc` is. My understanding is `oc start-build` should behave the same as `s2i build` for s2i build strategy.

I am not sure if this is a docs issue or a bug in oc. Please clarify. 

Thanks.

**Comment by php-coder** [comment]
CC @bparees

**Comment by bparees** [comment]
those docs are incorrect, they were carried too directly from the s2i repo.

what --scripts-url *should* be referring to is the value of the build.spec.sourcestrategy.scripts field in your buildconfig.

**Comment by bparees** [comment]
@csrwng can you please help clean up these docs?
