### ISSUE TITLE
[enterprise-4.11] Issue in file installing/disconnected_install/installing-mirroring-disconnected.adoc

### ISSUE THREAD

**Issue by david-goudet** [openshift/openshift-docs#54059]
### Which section(s) is the issue in?

"Image set configuration parameters"

### What needs fixing?
mirror.platform.architecture should be replace by mirror.platform.architectures in first column

**Comment by bergerhoffer** [comment]
Thanks for reporting!

Submitted PR #54608 to fix this.

**Comment by bergerhoffer** [comment]
PR has merged, closing!
