### ISSUE TITLE
Wrong links in CHAPTER 9. INFRASTRUCTURE COMPONENTS

### ISSUE THREAD

**Issue by jpechane** [openshift/openshift-docs#541]
xref:../core_objects/kubernetes_model.adoc#pod[pods]
xref:../core_objects/kubernetes_model.adoc#label[labels]
xref:../core_objects/builds.adoc#builds[builds]
xref:../additional_concepts/authentication.adoc#authentication[Authentication]
xref:../core_objects/kubernetes_model.adoc#label[labels]
The Browse tab explores the different xref:../core_objects/overview.adoc#overview-4[resource types] within your project: Builds, Deployments, xref:../core_objects/openshift_model.adoc#imagestream[Image Streams], xref:../core_objects/kubernetes_model.adoc#pod[Pods], and xref:../core_objects/kubernetes_model.adoc#service[Services].

**Comment by bfallonf** [comment]
This applied to an older version of the docs. The appropriate sections are updated now to look quite differently, and I've checked the links and they work fine:

https://docs.openshift.com/enterprise/3.0/architecture/overview.html

Closing this issue.
