### ISSUE TITLE
[BZ#2102680] Address load balancer service creation limitation when the IP is specified with the in-tree cloud provider (and OSP) - 4.12 only

### ISSUE THREAD

**Issue by maxwelldb** [openshift/openshift-docs#54114]
### Which section(s) is the issue in?
https://github.com/openshift/openshift-docs/pull/51467#issuecomment-1354916577

### What needs fixing?
https://github.com/openshift/openshift-docs/pull/51467#issuecomment-1354916577

**Comment by kalexand-rh** [comment]
Commenting on this issue to clone it into Jira.

**Comment by maxwelldb** [comment]
In Jira.
