### ISSUE TITLE
[enterprise-4.10] Issue in file virt/virtual_machines/virt-installing-qemu-guest-agent.adoc

### ISSUE THREAD

**Issue by adeturner** [openshift/openshift-docs#54141]
### Which section(s) is the issue in?

Section:  [Installing QEMU guest agent on a Windows virtual machine](https://docs.openshift.com/container-platform/4.11/virt/virtual_machines/virt-installing-qemu-guest-agent.html#installing-qemu-guest-agent-on-windows-vm_virt-installing-qemu-guest-agent)

Same issue in ARO 4.10.7 and OCP 4.11

### What needs fixing?

"For Windows virtual machines, _**the QEMU guest agent is included in the VirtIO drivers**_. Install the drivers on an existing or a new Windows installation."

Whilst installing a Win2019 VM in Openshift Virtualisation I installed the drivers during installation so I could format the disk.   The docs are not quite clear on how to do this, so I used e:\amd64\2k19 as the source directory and applied both drivers.

Per the quote the docs say this will install the guest agent, however the information did not appear on the host page. In the end I logged in and manually ran e:\virtio-win-guest-tools.exe which fixed it. (the cd is called virtio-win-1.9.24)

**Comment by apinnick** [comment]
I will look into this.

**Comment by dankenigsberg** [comment]
I think that @adeturner is correct. Drivers per se are kernel modules for interfacing with hardware (such as VirtIO). The Qemu guest agent is a user space program, it is not part of the drivers - even though it is shipped in the same ISO.

We should amend the text to say  _the QEMU guest agent is included in the VirtIO drivers **ISO**_
and ensure that the documented steps end with an installed and ever-running guest agent. I suspect @ksimon1 or @dominikholler can suggest how to do that.

**Comment by apinnick** [comment]
I will create a task for this issue.

**Comment by apinnick** [comment]
In progress: https://github.com/openshift/openshift-docs/pull/55929

**Comment by apinnick** [comment]
Issue resolved.
