### ISSUE TITLE
Conflicting information about labels in Chapter 10

### ISSUE THREAD

**Issue by tomason** [openshift/openshift-docs#542]
architecture/core_objects/kubernetes_model.adoc

Bellow the pod example, I can see
"The labels are stored in key/value format in the annotation hash. The label in this example is deployment=docker-registry-1."

While in labels section I can see different example. I believe the second example is right (k8s API also shows, every object can have "lables" key).

**Comment by tomason** [comment]
AFAIK annotations hold more informative value (descriptions, display names, etc.) while labels are used for grouping, searching, etc.

**Comment by adellape** [comment]
This is no longer an issue in the latest builds:

https://docs.openshift.com/enterprise/3.0/architecture/core_concepts/pods_and_services.html
