### ISSUE TITLE
[enterprise-4.11] Issue in file operators/admin/olm-managing-custom-catalogs.adoc

### ISSUE THREAD

**Issue by shaior** [openshift/openshift-docs#54229]
### Which section(s) is the issue in?

Cluster administrators and Operator catalog maintainers can create and managing custom catalogs packaged using the [bundle format](https://docs.openshift.com/container-platform/4.11/operators/understanding/olm-packaging-format.html#olm-bundle-format_olm-packaging-format) on Operator Lifecycle Manager (OLM) in OpenShift Container Platform.

### What needs fixing?
typo
managing --> manage

**Comment by bergerhoffer** [comment]
FYI @mletalie if you want to look into this one!

/assign mletalie

**Comment by bergerhoffer** [comment]
Closing since PR #54816 has merged!
