### ISSUE TITLE
Re-add manual/API-driven user provisioning to 4.x docs

### ISSUE THREAD

**Issue by patrickstrick** [openshift/openshift-docs#54267]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.11/authentication/understanding-identity-provider.html

### What needs fixing?

The OpenShift 3.x docs had text added to describe how manual user mapping ("lookup" mappingMethod) should be done. This was not carried over into the 4.x docs.

See https://github.com/openshift/openshift-docs/issues/1982 for implementation details.

**Comment by bburt-rh** [comment]
@patrickstrick I'm still investigating this one. Hope to be able to respond with more detail by early next week. Sorry for the delay.

**Comment by bburt-rh** [comment]
@patrickstrick - @bergerhoffer handles that area of the OCP docs, so she will be able to investigate this issue further.

**Comment by bergerhoffer** [comment]
Thanks @bburt-rh!

I don't know if this section was purposefully excluded in the port to 4.x, or if it was just an oversight. I will follow up with the auth team to see if it's still appropriate to document.

@stlaz @ibihim @xingxingxia Do any of you know whether the following section of the 3.11 docs is still applicable/supported for 4.x?

https://docs.openshift.com/container-platform/3.11/install_config/configuring_authentication.html#LookupMappingMethod

**Comment by xingxingxia** [comment]
Yes, still applicable/supported. See cu's question and my answer in forum-apiserver ch https://url.corp.redhat.com/3b90119 of same content in question, and stlaz remarked "indeed this part of the lookup strategy is not well documented".
If PR goes to be QE ready, you can reach @gkarager to help review.

**Comment by bergerhoffer** [comment]
I opened https://issues.redhat.com/browse/OSDOCS-5530 to track this, so we don't lose track of it. Closing this one.
