### ISSUE TITLE
[enterprise-4.11] Issue in file support/gathering-cluster-data.adoc

### ISSUE THREAD

**Issue by Scotchman0** [openshift/openshift-docs#54365]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.11/support/gathering-cluster-data.html#gathering-data-specific-features_gathering-cluster-data

### What needs fixing?
Please append in future releases/current releases the link to SRIOV gather:

--image=registry.redhat.io/openshift4/ose-sriov-operator-must-gather

**Comment by Scotchman0** [comment]
https://github.com/openshift/openshift-docs/pull/54416 created to address this

**Comment by Scotchman0** [comment]
linked to jira: https://issues.redhat.com/browse/OCPBUGS-16697

**Comment by kalexand-rh** [comment]
Closing in favor of the Jira.
