### ISSUE TITLE
[enterprise-4.11] Issue in file cicd/pipelines/creating-applications-with-cicd-pipelines.adoc

### ISSUE THREAD

**Issue by markmc** [openshift/openshift-docs#54441]
### Which section(s) is the issue in?

Running a pipeline

### What needs fixing?

The second `tkn pipeline start` command contains `$(context.pipelineRun.namespace)` in the image name - this results in an error

This was fixed in the first command by #50363 but the second command was missed

**Comment by rolfedh** [comment]
Thanks for reporting this @markmc.

**Comment by rolfedh** [comment]
I'm marking this as a good candidate for Hacktoberfest.

If someone is interested in taking it, please make the change against the main branch.

In `modules/op-running-a-pipeline.adoc`, we [replaced](https://github.com/openshift/openshift-docs/pull/50363) one instance of `$(context.pipelineRun.namespace)` with `pipelines-tutorial`, but missed the second instance.
The task here is to update the second instance as well.

**Comment by rolfedh** [comment]
Hi @sounix000. Thanks for commenting. That's just the thing, the [PR #50363](https://github.com/openshift/openshift-docs/pull/50363/files#diff-dec6ab7079b28a7b43c24f732fbf12612442cd456f53f928d62760f603248f97) changes only one of the two instances. No worries. This is a great task for a first-time contributore to fix during Hacktoberfest.

**Comment by bobfuru** [comment]
I'll take this for Hacktoberfest. :)
I notice there were actually THREE total instances of `$(context.pipelineRun.namespace)`, not TWO. So I'll submit a PR to fix the 2 of 3 that weren't changed to `pipelines-tutorial`. But not sure if line 45 indeed needs this edit, so please confirm. Thanks!

**Comment by rolfedh** [comment]
Thanks, @bobfuru!
