### ISSUE TITLE
[enterprise-4.11] Issue in file cicd/pipelines/using-tekton-hub-with-openshift-pipelines.adoc

### ISSUE THREAD

**Issue by markmc** [openshift/openshift-docs#54443]
### Which section(s) is the issue in?

Installing and deploying Tekton Hub on a OpenShift Container Platform cluster

### What needs fixing?

> with login autorization and ratings for Tekton Hub artifacts

Authorization is typoed

**Comment by bergerhoffer** [comment]
FYI @mletalie if you want to work on this!

**Comment by mletalie** [comment]
https://github.com/mletalie/openshift-docs/pull/new/54443

**Comment by bergerhoffer** [comment]
This was fixed via #54737, closing!
