### ISSUE TITLE
34.2. CLI AUTHENTICATION - --server option is no longer required

### ISSUE THREAD

**Issue by jpechane** [openshift/openshift-docs#545]
Usage:
  oc login [URL] [options]

Examples:
  // Log in interactively
  $ oc login

  // Log in to the given server with the given certificate authority file
  $ oc login localhost:8443 --certificate-authority=/path/to/cert.crt

  // Log in to the given server with the given credentials (will not prompt interactively)
  $ oc login localhost:8443 --username=myuser --password=mypass

Options:
  -p, --password='': Password, will prompt if not provided
  -u, --username='': Username, will prompt if not provided
      --certificate-authority='': Path to a cert. file for the certificate authority.
      --insecure-skip-tls-verify=false: If true, the server's certificate will not be checked for validity. This will make your HTTPS connections insecure.

It seems that although --server option still works it is not up-to-date

**Comment by bfallonf** [comment]
@jpechane Can I ask for more information on what you're asking for here?

I can see that's the -h output of the oc login command, and that matches with my own instance.

Are you asking that we erase all cases of the --server option in the docs? Are you asking that we get it better documented as it's not in the -h output or in that the info be in the -h output even? The latter might be an engineering issue. 

I also have a feeling that --server is one of those "universal" options that is expected to be following the oc login command, and that it probably doesn't need to be in the -h output, but I may be wrong there.

Thanks!
