### ISSUE TITLE
Document new-app usage for database images

### ISSUE THREAD

**Issue by mnagy** [openshift/openshift-docs#546]
We don't have any new-app examples for in our db image docs. Should we? e.g.
```
$ oc new-app openshift/mysql-55-centos7 -e MYSQL_USERNAME=user -e MYSQL_PASSWORD=pass -e MYSQL_DATABASE=sampledb
```

https://ci.openshift.redhat.com/openshift-docs-master-testing/latest/using_images/db_images/mysql.html

@bparees @thesteve0 thoughts?

**Comment by bparees** [comment]
@csrwng was working on new-app doc in general, if it's not covered there, it should be.

**Comment by csrwng** [comment]
I should have a PR ready today

**Comment by mnagy** [comment]
Seeing #570. @bparees But I was more concerned about examples in the documentation for the images. We do have docker pull/run/exec examples, but not oc new-app/exec. I think we should change that. Also see issue by @thesteve0 https://github.com/openshift/postgresql/issues/30

**Comment by mnagy** [comment]
Should we also document database templates in `examples/db-templates`?

**Comment by bparees** [comment]
@mnagy yes we should.  probably under "using images".  i'll work on it.

**Comment by mnagy** [comment]
@bparees ok, I linked the issue from #595. Please note that I already addressed new-app docs for images in #593. Just to make sure we're not working on the same stuff.

**Comment by bparees** [comment]
@mnagy cool, thanks for the heads up, that's good stuff.

**Comment by mnagy** [comment]
Closing, since #593 was merged.
