### ISSUE TITLE
[enterprise-4.9] Issue in file cicd/pipelines/viewing-pipeline-logs-using-the-openshift-logging-operator.adoc

### ISSUE THREAD

**Issue by dgeorgievski** [openshift/openshift-docs#54670]
### Which section(s) is the issue in?
Viewing pipeline logs in Kibana 
b.i Filter the containers related to pipelines
```json
{
  "query": {
	"match": {
  	"kubernetes.flat_labels": {
    	"query": "app_kubernetes_io/managed-by=tekton-pipelines",
    	"type": "phrase"
  	}
	}
  }
}
```

### What needs fixing?

In `query` field  value replace underscores with dots to make the filter working.
```json
    "query":"app.kubernetes.io/managed-by=tekton-pipelines"
```

**Comment by dgeorgievski** [comment]
The same fix for the query field  is required in the the last two filters
`iii. Filter pipelinerun in labels for highlighting:`
`iv. Filter pipeline in labels for highlighting:`

**Comment by pmkovar** [comment]
Tracked in https://issues.redhat.com/browse/RHDEVDOCS-5200
