### ISSUE TITLE
Numbers in text referring to source code examples are not visible

### ISSUE THREAD

**Issue by jpechane** [openshift/openshift-docs#547]
https://access.stage.redhat.com/beta/documentation/en/openshift-enterprise-30-documentation/chapter-41-resource-limits - see 41.4. SAMPLE LIMIT RANGE FILE

**Comment by adellape** [comment]
@CowboysFan Is this a known issue already being addressed? It looks like they don't render very well in the HTML builds (plain number in the code block, white text on white background for the footnote number). And in PDF, they're also weird (plain number in the codeblock, lot of real estate taken up by each footnote).

**Comment by CowboysFan** [comment]
@adellape I'll have to work with the portal team on that. I'll look into it.

**Comment by adellape** [comment]
xref for this: https://bugzilla.redhat.com/show_bug.cgi?id=1236041

**Comment by tpoitras** [comment]
no longer an issue
