### ISSUE TITLE
[enterprise-4.11] Issue in file service_mesh/v2x/ossm-security.adoc

### ISSUE THREAD

**Issue by sjbylo** [openshift/openshift-docs#54705]
### Which section(s) is the issue in?

In section "Adding an existing certificate and key"
https://docs.openshift.com/container-platform/4.11/service_mesh/v2x/ossm-security.html#ossm-cert-manage-add-cert-key_ossm-security

where is states:
```
4. After creating/changing/deleting the cacert secret, the Service Mesh control plane istiod and gateway pods must be restarted so the changes go into effect. Use the following command to restart the pods: 
```

### What needs fixing?

Although this is correct, it would be helpful to explain to the reader how to update or rotate a CA certificate which is soon to expire (or has already expired).  

Questions that need to be answered:
1. If the cacerts secret - with the cacert/ca-key/root-cert files - is replaced with fresh values (i.e. rotate the cert), will Istio manage the rotation of all the proxy/workload certs *without* any app downtime due to certificate changes?  
2. Is it safe to replace the CA cert values (ca-key/certs etc) or does the user need to include multiple certs into the secret?

Would be useful to get the info from the Eng. team and clarify it here in the docs.

**Comment by cbremble** [comment]
Added to Jira: https://issues.redhat.com/browse/OSSM-3236
