### ISSUE TITLE
[enterprise-4.8] Issue in file cicd/jenkins-tekton/migrating-from-jenkins-to-tekton.adoc

### ISSUE THREAD

**Issue by ckullo** [openshift/openshift-docs#54707]
### Which section(s) is the issue in?
I've just started reading about tekton, found the documentations is like the image below.
![image](https://user-images.githubusercontent.com/35125965/212593389-d10562db-4d83-4dab-bff0-2a8e631f5365.png)

I don't know if this happen on me locally or not.

### What needs fixing?
The display on the right menu.

**Comment by bergerhoffer** [comment]
I can reproduce this issue too, thanks for reporting! 

https://docs.openshift.com/container-platform/4.8/cicd/jenkins-tekton/migrating-from-jenkins-to-tekton.html

@sounix000 @Preeticp It looks like this was fixed for 4.9+ by #42950, but it wasn't cherry picked back to 4.8. The CP to 4.8 failed to open automatically, and a manual CP wasn't done.  Can one of you please look into getting those changes to 4.8?

**Comment by sounix000** [comment]
Opened the ticket https://issues.redhat.com/browse/RHDEVDOCS-4888; will look into it soon.
