### ISSUE TITLE
[enterprise-4.12] Issue in file logging/cluster-logging-loki.adoc

### ISSUE THREAD

**Issue by rgordill** [openshift/openshift-docs#54715]
### Which section(s) is the issue in?

Deploying the log stack. Procedure. Point 4 example.

### What needs fixing?

The indentation of collection is wrong, and vector is not deployed.

**Comment by cbremble** [comment]
Added to Jira: [RHDEVDOCS-4952](https://issues.redhat.com/browse/RHDEVDOCS-4952)

**Comment by libander** [comment]
@rgordill - that section has since been updated, checked with Eng and it was confirmed it currently seems to be correct.
