### ISSUE TITLE
[enterprise-4.11] Issue in file security/compliance_operator/compliance-operator-supported-profiles.adoc

### ISSUE THREAD

**Issue by rhodain** [openshift/openshift-docs#54755]
### Which section(s) is the issue in?
Compliance profiles

### What needs fixing?
Many of the links are not functioning any more. For example 
NERC CIP Standards - https://www.nerc.com/pa/Stand/Pages/CIPStandards.aspx

**Comment by obrown1205** [comment]
@rhodain I believe this can be closed - I'm unable to reproduce this issue in 4.9+. Could you recheck?

**Comment by rhodain** [comment]
Hi,
it is still not working.  Page: https://docs.openshift.com/container-platform/4.12/security/compliance_operator/compliance-operator-supported-profiles.html

has a table "Table 1. Supported compliance profiles", This cable has a column "Industry compliance benchmark". There is for example link called "[NERC CIP Standards](https://www.nerc.com/pa/Stand/Pages/CIPStandards.aspx)"
If you follow the link, you will receive:
    "​​​​​​​​This page is no longer available.  
    You will be redirected to the correct page in 10 seconds."
