### ISSUE TITLE
[enterprise-4.12] Issue in file cli_reference/openshift_cli/getting-started-cli.adoc

### ISSUE THREAD

**Issue by cfergeau** [openshift/openshift-docs#54903]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.12/cli_reference/openshift_cli/getting-started-cli.html#cli-installing-cli-rpm_cli-developer-commands

### What needs fixing?

Step 5. is 
> Enable the repositories required by OpenShift Container Platform 4.12.
> `# subscription-manager repos --enable="rhocp-4.11-for-rhel-8-x86_64-rpms"`

This should be `rhocp-4.12-for-rhel-8-x86_64-rpms` (I checked that this repository exists)

**Comment by bergerhoffer** [comment]
Thanks for reporting!

This will be fixed as part of PR #54968.

**Comment by bergerhoffer** [comment]
Closing, as #54968 was merged
