### ISSUE TITLE
[enterprise-4.12] Issue in file scalability_and_performance/recommended-cluster-scaling-practices.adoc

### ISSUE THREAD

**Issue by bweidenb** [openshift/openshift-docs#55042]
### Which section(s) is the issue in?

404 OCP 4.12 https://docs.openshift.com/container-platform/4.12/scalability_and_performance/recommended-cluster-scaling-practices.html
OCP 4.11 doc works as expected https://docs.openshift.com/container-platform/4.11/scalability_and_performance/recommended-cluster-scaling-practices.html

### What needs fixing?
200 response vs current 404.

**Comment by bweidenb** [comment]
steps to recreate from customer journey - 
search check in ocp docs upper right search box
select the 4th [link](https://docs.openshift.com/container-platform/4.12/scalability_and_performance/recommended-cluster-scaling-practices.html)
for good measure forcefully browsed to 4.11 [version](https://docs.openshift.com/container-platform/4.11/scalability_and_performance/recommended-cluster-scaling-practices.html) that works.

**Comment by ahardin-rh** [comment]
@bweidenb Thanks for reaching out! In 4.12, we reorganized some files to reduce content duplication: https://github.com/openshift/openshift-docs/pull/53348/files

The machine management tasks now live in the Machine Management guide: https://docs.openshift.com/container-platform/4.12/machine_management/index.html while the scaling-specific topics remain in https://docs.openshift.com/container-platform/4.12/scalability_and_performance/recommended-host-practices.html
