### ISSUE TITLE
[online] Issue in file rosa_release_notes/rosa-release-notes.adoc

### ISSUE THREAD

**Issue by annelson-rh** [openshift/openshift-docs#55132]
### Which section(s) is the issue in?
release notes

### What needs fixing?
docs are still for 4.10 - 4.11 has been out for a while. 
multiple changes have occurred that are not included in the docs at all.

**Comment by kalexand-rh** [comment]
@karanthshashank

**Comment by karanthshashank** [comment]
the Release Notes is now "What's New" and will be updated regularly link to the same can be found here - https://docs.openshift.com/rosa/rosa_release_notes/rosa-release-notes.html

**Comment by karanthshashank** [comment]
closing this as per the above comment /close
