### ISSUE TITLE
Fix broken links in Cluster Administration section

### ISSUE THREAD

**Issue by gaurav-nelson** [openshift/openshift-docs#5514]
FILE: admin_guide/out_of_resource_handling.adoc
Broken LINK: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/resources.md#resource-quantities

FILE: admin_guide/sdn_troubleshooting.adoc
Broken LINK: http://kubernetes.io/v1.0/docs/user-guide/services.html#type-nodeport

PS: https://github.com/openshift/openshift-docs#contributing-to-openshift-documentation

**Comment by raghav710** [comment]
Shall i take up this one. Please let me know if you would like to reserve this for other people who are new to open source and coming in through hacktoberfest :)

**Comment by TremaineNeethling** [comment]
i'm taking this one

**Comment by TremaineNeethling** [comment]
> FILE: admin_guide/sdn_troubleshooting.adoc
Broken LINK: http://kubernetes.io/v1.0/docs/user-guide/services.html#type-nodeport

@gaurav-nelson Do you still want to link to the v1 documentation or the new v1.8?

**Comment by gaurav-nelson** [comment]
Thank you @raghav710 Its open to everyone. There is no PR linked to this yet, so who ever submits a PR first is what we will look at. Since the `Assignees` option is only limited to team members we cannot assign this to someone else who's not part of our team.

**Comment by gaurav-nelson** [comment]
@TremaineNeethling Latest ones
