### ISSUE TITLE
Fix broken links in Architecture section

### ISSUE THREAD

**Issue by gaurav-nelson** [openshift/openshift-docs#5515]
FILE: architecture/additional_concepts/overview.adoc
Broken LINK:  https://github.com/openshift/openshift-docs/blob/master/contributing_to_docs/doc_guidelines.html

FILE: architecture/additional_concepts/other_api_objects.adoc
Broken LINK: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/design/admission_control_limit_range.md
Broken LINK: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/admin/resource-quota.md
Broken LINK:  https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/design/persistent-storage.md

FILE: architecture/additional_concepts/storage.adoc
Broken LINK: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/design/resources.md

FILE: architecture/core_concepts/pods_and_services.adoc
Broken LINK: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/labels.md

FILE: architecture/core_concepts/projects_and_users.adoc
Broken LINK: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/admin/namespaces.md

FILE: architecture/core_concepts/deployments.adoc
Broken LINK: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/replication-controller.md

PS: https://github.com/openshift/openshift-docs#contributing-to-openshift-documentation

**Comment by eiguike** [comment]
I can tackle on this issue.

**Comment by gaurav-nelson** [comment]
Thank you @eiguike 
Please go ahead and submit a PR. Only team members-can be assigned to issues, therefore I self-assigned this.

**Comment by eiguike** [comment]
@gaurav-nelson Thanks!
