### ISSUE TITLE
Fix broken links in Creating Images section

### ISSUE THREAD

**Issue by gaurav-nelson** [openshift/openshift-docs#5517]
FILE: creating_images/metadata.adoc
Broken Link: https://docs.docker.com/userguide/labels-custom-metadata
Broken Link: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/design/resources.md#resource-quantities

FILE: creating_images/guidelines.adoc
Broken Link: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/volumes.md
Broken Link: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/services.md
Broken Link: https://docs.docker.com/articles/runmetrics

PS:https://github.com/openshift/openshift-docs#contributing-to-openshift-documentation

**Comment by iashok22** [comment]
Fixed - https://github.com/openshift/openshift-docs/pull/5534

**Comment by gaurav-nelson** [comment]
Thank you @iashok22
