### ISSUE TITLE
Fix broken links in Dev Guide section

### ISSUE THREAD

**Issue by gaurav-nelson** [openshift/openshift-docs#5518]
FILE: dev_guide/projected_volumes.adoc
Broken Link: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/all-in-one-volume.md

PS: https://github.com/openshift/openshift-docs#contributing-to-openshift-documentation

**Comment by rhiroyuki** [comment]
Can I take this issue?

**Comment by gaurav-nelson** [comment]
Thank you @rhiroyuki Please go ahead.

**Comment by rhiroyuki** [comment]
Hey, just to let you know I sended a PR a couple of hours ago solving this issue.  #5527

**Comment by gaurav-nelson** [comment]
Fixed in #5527
