### ISSUE TITLE
Fix broken links in Installation and Configuration section

### ISSUE THREAD

**Issue by gaurav-nelson** [openshift/openshift-docs#5519]
FILE: install_config/persistent_storage/persistent_storage_nfs.adoc
Broken Link:  https://github.com/openshift/openshift-ansible/tree/master/roles/kube_nfs_volumes

FILE: install_config/syncing_groups_with_ldap.adoc
Broken Link: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#types-kinds
Broken Link:  http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#resources

FILE: install_config/storage_examples/gluster_dynamic_example.adoc
Broken Link:  https://access.redhat.com/documentation/en/red-hat-gluster-storage/3.1/paged/container-native-storage-for-openshift-container-platform/chapter-2-red-hat-gluster-storage-container-native-with-openshift-container-platform

FILE: install_config/install/advanced_install.adoc
Broken Link:  http://kubernetes.io/v1.1/docs/admin/kubelet.html

FILE: install_config/install/host_preparation.adoc
Broken Link: https://access.redhat.com/webassets/docker/content/sigstore

PS: https://github.com/openshift/openshift-docs#contributing-to-openshift-documentation

**Comment by viswanathamsantosh** [comment]
Hi, submitted a PR for first broken link. let me know if I replaced it with the right link.
https://github.com/openshift/openshift-docs/pull/5578

**Comment by viswanathamsantosh** [comment]
and one more https://github.com/openshift/openshift-docs/pull/5579

**Comment by raghav710** [comment]
Hi @gaurav-nelson I have raised a [PR](https://github.com/openshift/openshift-docs/pull/5580) for the links in install_config/syncing_groups_with_ldap.adoc

**Comment by raghav710** [comment]
I've raised one more PR #5581 . Please let me know if I've set the correct link

**Comment by Morecai** [comment]
Hi @gaurav-nelson I have created a PR for the FILE: install_config/install/advanced_install.adoc
Broken Link: http://kubernetes.io/v1.1/docs/admin/kubelet.html
I don't believe it has been addressed yet.
