### ISSUE TITLE
Fix Broken Links in Release Notes section

### ISSUE THREAD

**Issue by gaurav-nelson** [openshift/openshift-docs#5520]
FILE: release_notes/ocp_3_3_release_notes.adoc
Broken Link: https://github.com/docker/distribution/blob/master/docs/storage-drivers/gcs.md

FILE: release_notes/ocp_3_6_release_notes.adoc
Broekn Link:  https://access.redhat.com/errata/RHBA-2017:1716

PS: https://github.com/openshift/openshift-docs#contributing-to-openshift-documentation

**Comment by VerteDinde** [comment]
Happy to take this one - I'll submit a PR.

**Comment by gaurav-nelson** [comment]
Thanks @VerteDinde :+1:

**Comment by VerteDinde** [comment]
Thanks @gaurav-nelson ! Just submitted a PR (https://github.com/openshift/openshift-docs/pull/5524). I mentioned this in the PR summary, but the link to Red Hat's original 3.6.0 release seems to have been removed entirely. I relinked to 3.6's newest stable version (https://access.redhat.com/errata/RHBA-2017:2847), but please let me know if this is incorrect. Thanks for the great documentation!

**Comment by vikram-redhat** [comment]
This has now been merged via #5524. Sorry that it got missed. Closing this issue.
