### ISSUE TITLE
Fix broken links in Security section

### ISSUE THREAD

**Issue by gaurav-nelson** [openshift/openshift-docs#5521]
FILE: security/deployment.adoc
Broken Link: http://registry.access.redhat.com/content/sigstore/

FILE: FILE: security/container_content.adoc
Broken Link: https://www.open-scap.org/930492

PS: https://github.com/openshift/openshift-docs#contributing-to-openshift-documentation

**Comment by raghav710** [comment]
I'd be happy to take this one :)

**Comment by gaurav-nelson** [comment]
Thank you @raghav710 Please go ahead and submit a PR!

**Comment by raghav710** [comment]
@gaurav-nelson I think the second link might require a vulnerability assesment to be done and the results available AFAIK. am i right?

**Comment by gaurav-nelson** [comment]
Closing this, not an issue anymore
