### ISSUE TITLE
[enterprise-4.12] Issue in file backup_and_restore/application_backup_and_restore/installing/installing-oadp-azure.adoc

### ISSUE THREAD

**Issue by mparram** [openshift/openshift-docs#55248]
### Which section(s) is the issue in?

Enabling self-signed CA certificates

### What needs fixing?

The referenced parameter .spec.backupLocations[].velero.config.insecureSkipTLSVerify is only valid for AWS plugin, with the azure plugin throw the error:  level=error msg="Current BackupStorageLocations available/unavailable/unknown: 0/1/0, BackupStorageLocation \"velero-1\" is unavailable: rpc error: code = Unknown desc = config has invalid keys [insecureSkipTLSVerify]; valid keys are [resourceGroup storageAccount subscriptionId blockSizeInBytes storageAccountKeyEnvVar credentialsFile bucket prefix caCert])" 

The code example reference to AWS plugin in Azure doc.

**Comment by anarnold97** [comment]
JIRAPROJECT-OADP-1227

Added to Jira

**Comment by kaovilai** [comment]
/close
via https://issues.redhat.com/browse/OADP-1255
