### ISSUE TITLE
[enterprise-4.12] Issue in file virt/virt-4-12-release-notes.adoc

### ISSUE THREAD

**Issue by dlbewley** [openshift/openshift-docs#55274]
### Which section(s) is the issue in?

* Removed features in 4.11 and 4.12 rel notes

### What needs fixing?

This text concerning `nmstate` can be seen as confusing:

```
Removed features are not supported in the current release.

OpenShift Virtualization 4.11 removed support for [nmstate](https://nmstate.io/), including the following objects:

NodeNetworkState

NodeNetworkConfigurationPolicy

NodeNetworkConfigurationEnactment

To preserve and support your existing nmstate configuration, install the [Kubernetes NMState Operator](https://docs.openshift.com/container-platform/4.12/networking/k8s_nmstate/k8s-nmstate-about-the-k8s-nmstate-operator.html#k8s-nmstate-about-the-k8s-nmstate-operator) before updating to OpenShift Virtualization 4.11. For 4.12 for [Extended Update Support (EUS)](https://docs.openshift.com/container-platform/4.12/virt/upgrading-virt.html#virt-about-eus-updates_upgrading-virt) versions, install the Kubernetes NMState Operator after updating to 4.12. You can install the Operator from the OperatorHub in the OpenShift Container Platform web console, or by using the OpenShift CLI (oc).
```

This conveys the message that nmstate is removed from support.

I believe the message that is intended to be conveyed is that the nmstate operator is no longer a dependency of OCP-V, and it will not be installed automatically. Also, to use nmstate API, users will be required to install the nmstate operator by other means.

**Comment by apinnick** [comment]
I think the current wording is sufficient: "OpenShift Virtualization 4.11 removed support for nmstate. ... To preserve and support your existing nmstate configuration, install the [Kubernetes NMState Operator](https://docs.openshift.com/container-platform/4.12/networking/k8s_nmstate/k8s-nmstate-about-the-k8s-nmstate-operator.html#k8s-nmstate-about-the-k8s-nmstate-operator) before updating to OpenShift Virtualization 4.11." 

This does not imply that there is no support for nmstate, only that Virt does not support nmstate.
