### ISSUE TITLE
[enterprise-4.12] Issue in file networking/cluster-network-operator.adoc

### ISSUE THREAD

**Issue by CFields651** [openshift/openshift-docs#55285]
### Which section(s) is the issue in?
Table 4. ovnKubernetesConfig object

### What needs fixing?
Two issues: 
1) I don't know what the following text is doing in this table: "For example, if the clusterNetwork.cidr is 10.128.0.0/14 and the clusterNetwork.hostPrefix is /23, then the maximum number of nodes is 2^(23-14)=128." That is not describing the v4InternalSubnet.  It belongs in the 'spec.clusterNetwork' field of the 'Table 1. Cluster Network Operator configuration object.'
2) The formula is correct, but the math is wrong for the number of nodes.  2^(23-14)=512, not 128.  With 10.128.0.0/14 and hostPrefix /23 you can have 512 nodes.  This is the default.

**Comment by ahardin-rh** [comment]
This issue is now being tracked in https://issues.redhat.com/browse/OCPBUGS-14294
