### ISSUE TITLE
[enterprise-4.12] Issue in file logging/cluster-logging-external.adoc

### ISSUE THREAD

**Issue by childofthewired** [openshift/openshift-docs#55342]
### Which section(s) is the issue in?
Cluster Log Forwarding

### What needs fixing?
The examples for how splunk is configured as a third party system is missing.

Information like 
URL, TLS secrets and the HEC token are missing.

**Comment by cbremble** [comment]
Added to Jira: [RHDEVDOCS-4954](https://issues.redhat.com/browse/RHDEVDOCS-4954)

**Comment by cbremble** [comment]
Closed with [RHDEVDOCS-4427](https://issues.redhat.com/browse/RHDEVDOCS-4427)

/close
