### ISSUE TITLE
[online] [typo]  Issue in file rosa_install_access_delete_clusters/rosa-sts-creating-a-cluster-quickly.adoc

### ISSUE THREAD

**Issue by dev-lew** [openshift/openshift-docs#55362]
### Which section(s) is the issue in?
Red Hat OpenShift Service on AWS / Installing, accessing, and deleting ROSA clusters / Creating a
RoSA cluster with STS using the default options

### What needs fixing?
In the table section "Control plane node configuration", Control plane node instance type: **m5.x2large** should be **m5.2xlarge**.

**Comment by bergerhoffer** [comment]
Closing since PR #55722 has merged!
