### ISSUE TITLE
[enterprise-4.12] EUS sections have not been updated for 4.12

### ISSUE THREAD

**Issue by demvass** [openshift/openshift-docs#55397]
### Which section(s) is the issue in?
Every section that is related to the EUS upgrades for 4.12. For example:

https://github.com/openshift/openshift-docs/blob/enterprise-4.12/modules/updating-eus-to-eus-upgrade.adoc

https://github.com/openshift/openshift-docs/blob/enterprise-4.12/updating/index.adoc#preparing-to-perform-an-eus-to-eus-update

https://github.com/openshift/openshift-docs/blob/enterprise-4.12/updating/preparing-eus-eus-upgrade.adoc#preparing-eus-eus-upgrade

(The list is not exhaustive)

### What needs fixing?
The content should have been updated for 4.12, the content seems to be identical compared to the previous version (4.11)

**Comment by bergerhoffer** [comment]
@kalexand-rh This is the section that I was telling you about when I did the 4.11 -> 4.12 bump, that it seemed really out of date (even in 4.11) and needed some extra eyes to sort. 

This is pretty high priority if you can get someone to take a look?
