### ISSUE TITLE
now need documentation on troubleshooting network

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-docs#559]
According to @rajatchopra it is now insufficient to spin a Docker container manually - the SDN does not learn that it exists so it doesn't actually have connectivity to other participants in the SDN.

As such, we actually require a pod to test connectivity and other network aspects.

We will need documentation on how to spin a pod and force it to a specific node, no matter what the scheduler configuration is, in order to be able to properly test.

**Comment by adellape** [comment]
@rajatchopra @abhgupta Does using `podManifestConfig` satisfy this Issue? Are the resulting pods connected via SDN?

**Comment by adellape** [comment]
Meant to link:

https://docs.openshift.com/enterprise/3.0/admin_guide/master_node_configuration.html#node-configuration-files

**Comment by bfallonf** [comment]
@thoraxe @rajatchopra @abhgupta This issue is a little old, and we have this topic now:

https://github.com/openshift/openshift-docs/blob/master/admin_guide/sdn_troubleshooting.adoc

In anyone's opinion, does this satisfy this issue? Or should there be an extra step added?

**Comment by thoraxe** [comment]
LGTM

**Comment by rajatchopra** [comment]
Good to close I think.

**Comment by bfallonf** [comment]
Great. Thanks, guys.
