### ISSUE TITLE
Incorrect instructions for obtaining a list of Red Hat OpenShift operators supported in a restricted network

### ISSUE THREAD

**Issue by pdfruth** [openshift/openshift-docs#55905]
### Which section(s) is the issue in?
This page in the OpenShift documentation discusses **Using Operator Lifecycle Manager (OLM) on restricted networks**;

https://docs.openshift.com/container-platform/4.12/operators/admin/olm-restricted-networks.html

On that page, there is this "IMPORTANT" notice, with instructions for obtaining a list of operators that "support running in disconnected mode" (aka restricted network environment).
![image](https://user-images.githubusercontent.com/11518334/218868882-244d48cb-2598-4f69-b24e-15ff1ed9a578.png)

In the instructions contained in that "IMPORTANT" notice, there are instructions stating;

> You can search on the Red Hat Ecosystem Catalog for a list of Red Hat Operators that support running in disconnected mode by selecting the **Disconnected** filter under **Infrastucture Features**:
> https://catalog.redhat.com/software/operators/search

Upon navigating to the linked page, there is NO filter for Infrastructure Features = Disconnected.

### What needs fixing?

Please update the above referenced OpenShift documentation to include working/valid instructions for obtaining a list of Red Hat OpenShift operators that are supported in a restricted network install.

**Comment by adellape** [comment]
I've confirmed that the entire left-nav filter category "Infrastructure Features" is gone now for some reason. Following up internally with RH stakeholders to try to find out what happened here.

**Comment by adellape** [comment]
https://docs.openshift.com/container-platform/4.12/operators/admin/olm-restricted-networks.html has been updated with the latest UI requirements to search the RHEC for disconnected Operators.
