### ISSUE TITLE
ingressIPNetworkCIDR issue in  openshift-docs/admin_guide/tcp_ingress_external_ports.adoc

### ISSUE THREAD

**Issue by jatanmalde** [openshift/openshift-docs#5599]
When I use this variable `IngressIPNetworkCIDR` it is not able to assign the value provided to it, but if we use this variable starting with small "i" letter starting then it is able to assign the value provided to it where ever necessary.
  And same is the case with `ExternalIPNetworkCIDR` variable.

**Comment by vikram-redhat** [comment]
@bfallonf - can you PTAL and the associated PR?

**Comment by bfallonf** [comment]
Sure. I've created a PR for this issue:

https://github.com/openshift/openshift-docs/pull/11491

It's a simple fix, but I'll verify with QE before merging.
