### ISSUE TITLE
Value of ingressIPNetworkCIDR error in  openshift-docs/dev_guide/getting_traffic_into_cluster.adoc

### ISSUE THREAD

**Issue by jatanmalde** [openshift/openshift-docs#5611]
Using this variable `IngressIPNetworkCIDR`, the value assigned to it is not working and hence should be altered as using the same variable starting with small "i" works.

**Comment by ahardin-rh** [comment]
Fully resolved in https://github.com/openshift/openshift-docs/pull/5710
