### ISSUE TITLE
Oadp word misspelling

### ISSUE THREAD

**Issue by lance5890** [openshift/openshift-docs#56764]
### Which section(s) is the issue in?
as the ocp 4.12 docs show

It should be **restic**, but **not rustic**
<img width="596" alt="image" src="https://user-images.githubusercontent.com/30207518/222606278-db12a8de-1c7e-4914-8599-228c41dde155.png">

and 

it should be **base64**, but **not base46**
<img width="600" alt="image" src="https://user-images.githubusercontent.com/30207518/222606376-e692a4ca-a355-435d-b0cf-ce97e527be64.png">

### What needs fixing?
we need to correct misspelled words

**Comment by lance5890** [comment]
@lahinson @geliu2016 @kowen-rh!

**Comment by obrown1205** [comment]
https://github.com/openshift/openshift-docs/pull/56765/files has been merged. This can be closed :)

**Comment by lance5890** [comment]
> https://github.com/openshift/openshift-docs/pull/56765/files has been merged. This can be closed :)

thanks
