### ISSUE TITLE
OSE 3.0 core_objects/routing.adoc Sticky sessions should be updated to reflect latest router changes

### ISSUE THREAD

**Issue by maschmid** [openshift/openshift-docs#568]
See also https://bugzilla.redhat.com/show_bug.cgi?id=1232718 and https://github.com/openshift/origin/pull/3299 (not merged) and  https://github.com/openshift/origin/pull/3300

Mostly
* haproxy router will use cookies for HTTP, keeps source for tcp
* Document current GA limitation that "balance source" will not distinguish between external client IP addresses and will route all external clients to a single backend pod, unless the router is running with hostNetwork: true (which is not yet officially supported for the ha proxy router on OSE for 3.0 GA and not the default router behavior for OSE 3.0 GA)

CC @pweil

**Comment by tpoitras** [comment]
addressed in PR#1069

https://github.com/openshift/openshift-docs/pull/1069
