### ISSUE TITLE
openshift_metrics_storage ansible variables confusion

### ISSUE THREAD

**Issue by ksemaev** [openshift/openshift-docs#5701]
According to https://docs.openshift.org/latest/install_config/install/advanced_install.html#advanced-install-cluster-metrics-storage "There are three options for enabling cluster metrics storage": 
openshift_metrics_storage_kind=nfs group, 
openshift_metrics_storage_kind=nfs host 
openshift_metrics_cassandra_storage_type=dynamic

But according to https://docs.openshift.org/latest/install_config/cluster_metrics.html#metrics-ansible-variables there is no key "openshift_metrics_storage_kind", but the variable openshift_metrics_cassandra_storage_type can be empty, pvc or dynamic.

Which of this two links provide correct information for which versions of openshift?

**Comment by fgimenezm** [comment]
I think the docs were never updated after this PR:

https://github.com/openshift/openshift-ansible/pull/11586#issuecomment-512212225
