### ISSUE TITLE
PV for openshift metrics

### ISSUE THREAD

**Issue by ksemaev** [openshift/openshift-docs#5704]
According to https://docs.openshift.org/latest/install_config/cluster_metrics.html#metrics-ansible-role  there is a "pv for persistent volumes, which need to be created before the installation", but there is no information on which parameters we need to setup for it: name, access mode, claimRef etc.

I have no idea what pv to make, so the ansible installation of cassandra would be able to mount it using it's pvc

**Comment by vikram-redhat** [comment]
This has been covered via the install docs: https://docs.openshift.org/latest/install_config/cluster_metrics.html#metrics-data-storage. Closing this issue.
