### ISSUE TITLE
Cinder auto-detection fails for OpenShift on OpenStack without bs-version set.

### ISSUE THREAD

**Issue by xsgordon** [openshift/openshift-docs#5730]
In the "Configuring for OpenStack" content an example `/etc/cloud.cfg` is provided. Not mentioned is the fact that on newer OpenStack installs that expose a Cinder endpoint using paths rather than ports this configuration will result in an error along the lines of:

> Failed to attach volume "jenkins2-volume" on node "app-node-1.openshift.staging.xxxx.co" with: BS API version autodetection failed.

To resolve this until such time as OpenShift/Kubernetes properly support Cinder V3 and/or the auto-detection login in the K8S cloud provider is changed it is necessary to force a fallback to V2 using:

```
[BlockStorage]
bs-version=v2
```
This issue arises frequently for users who frequent the #sig-openstack Kubernetes slack channel. If or when OpenShift pulls in https://github.com/kubernetes/kubernetes/pull/53115 this would also resolve the issue.

[1] https://github.com/openshift/openshift-docs/blob/master/install_config/configuring_openstack.adoc
[2] https://docs.openshift.com/container-platform/3.6/install_config/configuring_openstack.html

**Comment by tomassedovic** [comment]
FYI this patch let's us specify the Block Storage API version with openshift-ansible as well: https://github.com/openshift/openshift-ansible/pull/6607
