### ISSUE TITLE
[OKD] Broken link to install service mesh

### ISSUE THREAD

**Issue by mpeters** [openshift/openshift-docs#57499]
OKD docs for 4.12 have a broken link but the corresponding OCP doc does not.

In the  Post-installation configuration > Network configuration section (https://docs.okd.io/4.12/post_installation_configuration/network-configuration.html#ossm-supported-configurations-sm_post-install-network-configuration) there is a link to "Install Red Hat OpenShift Service Mesh" (https://docs.okd.io/4.12/service_mesh/v2x/installing-ossm.html#installing-ossm) that is broken.

The corresponding OCP links are https://docs.openshift.com/container-platform/4.12/post_installation_configuration/network-configuration.html#ossm-supported-configurations-sm_post-install-network-configuration and https://docs.openshift.com/container-platform/4.12/service_mesh/v2x/installing-ossm.html#installing-ossm which does work.

I'm happy to help with the fix, but I'm not sure what the process is for things that are broken in OKD docs but not OCP ones. @mburke5678

**Comment by apinnick** [comment]
I see that the Service Mesh guide is only published for OCP. Are you sure that Service Mesh is supported for OKD? It's possible that the Service Mesh sections should have been included only in the `openshift-enterprise` build and not in `openshift-origin`.

 @SNiemann15 Do you know whether the Service Mesh section should be part of OKD docs?

**Comment by gwynnemonahan** [comment]
:wave: 

The Service Mesh sections should be removed.

**Comment by mburke5678** [comment]
@mpeters @apinnick @gwynnemonahan  Can somone [PTAL at this internal preview](http://file.rdu.redhat.com/mburke/okd-remove-ossm/post_installation_configuration/network-configuration.html) and let me know if this is what you expect? I believe you need the VPN to access. Only the post-install book is available.

**Comment by apinnick** [comment]
LGTM
