### ISSUE TITLE
Ansible Installer user (ansible_ssh_user) must include /sbin/ folder in Its PATH

### ISSUE THREAD

**Issue by jtudelag** [openshift/openshift-docs#5850]
Currently, there is no specific note in the docs. We should warn explicitly that the user set in the variable ansible_ssh_user must include /sbin in Its PATH, otherwise, the installer will fail.

**Comment by vikram-redhat** [comment]
This is listed here: https://docs.openshift.com/container-platform/3.10/install/host_preparation.html#setting-path. Closing.
