### ISSUE TITLE
performance profile example in the 4.12 docs most likely wrong

### ISSUE THREAD

**Issue by ElCoyote27** [openshift/openshift-docs#58610]
I have a problem with the example in this section

https://docs.openshift.com/container-platform/4.12/scalability_and_performance/cnf-low-latency-tuning.html#cnf-tuning-nodes-for-low-latency-via-performanceprofile_cnf-master

Most especially this section:
```
spec:
 cpu:
  isolated: "5-15"
  reserved: "0-4"

```

IMVHO, this example is wrong (please someone confirm this) and since it's been copied everywhere it should at least be changed to something that works.
On a real platform with two sockets (2x26C Xeon SP Gen2, a proper example would be:

```
  isolated: "2-51,54-103"
  reserved: "0-1,52-53"

```

even for a node running as a VM it does not make any sense to split an odd numbers of vcpus, so I'd suggest either:

```
  isolated: "4-15"
  reserved: "0-3"

```
or
```
  isolated: "8-15"
  reserved: "0-7"
```

AFAIK 0-4 is never good except only -maybe- for a VM which is alone on its own NUMA node or if SMT is disabled at the hypervisor level.

**Comment by ahardin-rh** [comment]
@ElCoyote27 Thank you for reporting this issue. This work is now being tracked in https://issues.redhat.com/browse/OCPBUGS-14283
