### ISSUE TITLE
Charpter 60. Docker Images - Documentation completely missing

### ISSUE THREAD

**Issue by Crumby** [openshift/openshift-docs#589]
There is no documentation on using Docker images.
using_images/docker_images/overview.adoc

**Comment by adellape** [comment]
It's no longer missing:

https://docs.openshift.com/enterprise/3.0/using_images/docker_images/overview.html

But it needs major work. Opened https://bugzilla.redhat.com/show_bug.cgi?id=1271367 to track further, closing this Issue.
