### ISSUE TITLE
client-go lacks releases tags

### ISSUE THREAD

**Issue by xakepp35** [openshift/openshift-docs#58978]
Issues in [client go](https://github.com/openshift/client-go/issues) are being opened and not reviewed for years, we lack any attention mechanism there.

So this post is an attempt to draw more attention to that problem, because it makes golang developers hard to update and manage openshift client in golang, with standart `go get`, because of situation with tags.

Apologising, and very sorry for putting this post in a "wrong" repo, interacting with docs - I am not aware of support structure, but i hope that pinned repos are under more attention, and their maintainers may be more familiar their internal organisational structure, so they potentially can have ability to pass this information to someone, who is supporting go client for openshift. Thanks in advance!

**Comment by JoelSpeed** [comment]
I've responded to both open issues within the client-go repository
/close
