### ISSUE TITLE
Path to QuickStart templates does not exist

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/openshift-docs#591]
http://docs.openshift.org/latest/admin_guide/install/first_steps.html#creating-quickstart-templates
> To create the core QuickStart templates:
> ```
> $ oc create -f \
>     examples/quickstart-templates -n openshift
> ```

The path `examples/quickstart-templates` does not exist. For now templates are stored in multiple repositories under `{cakephp,dancer,django,nodejs,rails}-ex/openshift/templates/`:
- https://github.com/openshift/cakephp-ex/tree/master/openshift/templates
- https://github.com/openshift/dancer-ex/tree/master/openshift/templates
- https://github.com/openshift/django-ex/tree/master/openshift/templates
- https://github.com/openshift/nodejs-ex/tree/master/openshift/templates
- https://github.com/openshift/rails-ex/tree/master/openshift/templates

**Comment by rhcarvalho** [comment]
@bparees are intending to have all templates in a single place, or should we update the docs?

**Comment by bparees** [comment]
@rhcarvalho the installer is going to install the json files to the path listed in the docs.

see: https://github.com/openshift/openshift-ansible/pull/289

**Comment by sdodson** [comment]
So those won't exist without the user having installed via ansible and if they use ansible they'll be created unless the user opts out. Not sure how best to reflect that in the docs without changing them all to be remote urls but that's a nightmare to manage.

**Comment by bparees** [comment]
@adellape @CowboysFan is it safe to assume people using our docs used the ansible installer?  if not, should we make that assumption clear at the top of sections like this?

**Comment by adellape** [comment]
@bparees Assumption for OSE would be ansible, either using ansible directly ("Manual Installation") or via the installer tool ("Quick Installation"). Working on updates to install sections and will make this clearer.

**Comment by adellape** [comment]
I haven't tried Origin via ansible, assume it's similar but need to verify.
