### ISSUE TITLE
sourceStrategy example is missing comma

### ISSUE THREAD

**Issue by nak3** [openshift/openshift-docs#592]
http://docs.openshift.org/latest/dev_guide/builds.html#accessing-build-logs

In this doc, the example is:

~~~
{
  "sourceStrategy": {
    ...
    "env": [
      {
        "Name": "BUILD_LOGLEVEL",
        "Value": "2"
      }
    ]
  }
}
~~~

But `,` comma is necessary. The doc should be:

~~~
{
  "sourceStrategy": {
    ...
    "env": [
      {
        "Name": "BUILD_LOGLEVEL",
        "Value": "2"
      }
    ],
  }
}
~~~

**Comment by rhcarvalho** [comment]
@nak3 the comma would make it [invalid JSON](http://jsonlint.com/?json={%20%22sourceStrategy%22:%20{%20%22env%22:%20[%20{%20%22Name%22:%20%22BUILD_LOGLEVEL%22,%20%22Value%22:%20%222%22%20}%20],%20}%20})...

**Comment by nak3** [comment]
Sorry my test has `"incremental": true` next to the `],`. It was my fault. Thank you @rhcarvalho 

http://jsonlint.com/?json={%20%22sourceStrategy%22:%20{%20%22env%22:%20[%20{%20%22Name%22:%20%22BUILD_LOGLEVEL%22,%20%22Value%22:%20%222%22%20}%20],%20}%20}
