### ISSUE TITLE
Broken links in docs.openshift.org

### ISSUE THREAD

**Issue by anjannath** [openshift/openshift-docs#5946]
The following two links are not working.

- https://docs.openshift.org/latest/architecture/core_concepts/routes.html#architecture-core-concepts-routes

- https://docs.openshift.org/latest/architecture/core_concepts/templates.html#architecture-core-concepts-templates

**Comment by saritha-infosys** [comment]
1st link is not working, we can see the info in the below link

https://docs.openshift.org/latest/architecture/core_concepts/index.html

**Comment by anjannath** [comment]
found one more broken link: https://docs.openshift.org/latest/dev_guide/getting_traffic_into_cluster.html#using-ingress-IP-self-service

**Comment by gaurav-nelson** [comment]
Thank you @anjannath for creating this issue, can you please also share these links are broken on which pages?

**Comment by anjannath** [comment]
@gaurav-nelson More information can be found on this issue [openshift/origin#1593](https://github.com/openshift/origin/issues/17165)

**Comment by gaurav-nelson** [comment]
Thank you @anjannath for the updates. This one is already fixed in the current version.
