### ISSUE TITLE
More elaborate overview for database images

### ISSUE THREAD

**Issue by mnagy** [openshift/openshift-docs#595]
The overview for database images is very short and lacking. We could move a lot of stuff there and conversely be able to remove lot of duplicate stuff from documentation about images themselves.

Points that should be addressed:
* [ ] How to use `oc new-app` to quickly setup a database
* [ ] Software Collections - what are they, why do we use them, what to watch out for, explain why `oc exec <scl_binary>` won't work. We should then back-link here from DB images' SCL sections.
* [x] document examples in https://github.com/openshift/origin/tree/master/examples/db-templates (#546)
* [ ] document emptyDir behaviour https://github.com/openshift/origin/issues/2929 and warn about non-persistency of current images
* [ ] maybe mention persistent storage?
* [ ] how to add a DB service to an existing deploymentconfig for an application (copying over appropriate env variables for username/password/dbname/etc)
* [ ] explain and stress requirement variables and what happens when they are not properly set (restarting pod)

**Comment by mnagy** [comment]
cc @bparees @tnguyen-rh 
Any suggestions or warnings before I start with the work would be welcome.

**Comment by tnguyen-rh** [comment]
Definitely mention persistent storage.
The overview would be the ideal place for an intro blurb for the "concrete example" (https://github.com/openshift/openshift-docs/pull/593#issuecomment-114119861).

**Comment by mnagy** [comment]
Not sure about the concrete example. How about a totally different section with a step-by-step example/tutorial? It doesn't seem to fit into the overview and it could be kind of verbose if we included it for every image.

**Comment by bparees** [comment]
@mnagy good list.  here's another item:

document how to add a new DB service to an existing deploymentconfig for an app (ie setting up the db username/password env variables on the existing deployment config and redeploying it)

**Comment by soltysh** [comment]
I started writing down exactly what @bparees (but got distracted) mentioned about the requirements each of the images has, regarding usernames, passwords and database names with information that specific information is per image.

**Comment by bparees** [comment]
added mine to the checklist.  (abusing my edit powers..mawhahaaha)

**Comment by soltysh** [comment]
> added mine to the checklist. (abusing my edit powers..mawhahaaha)

That is nasty cheating :stuck_out_tongue_winking_eye:

**Comment by mnagy** [comment]
@bparees @soltysh can you elaborate?

**Comment by bparees** [comment]
@mnagy if i have created the rails example with no DB service, and then i go create a DB service using the DB template (or new-app), how do i configure my rails example to use the DB service?

the answer is i have to go get the username/password/dbname values from the DB service and make them env variables on the rails DeploymentConfig.  we need to document that process.

**Comment by soltysh** [comment]
Yeah, I was thinking about general usecase where you just configure the db service and the user should be aware upfront of the requirements for those images (in general, specifics info are per image), and not finding that out after his initial deployment will fail and then digging why that happened.

**Comment by bparees** [comment]
@soltysh I think we already document the required/mandatory env variables for the db images.

**Comment by soltysh** [comment]
@bparees we do, but per image, I think we should mention that requirement in the overview as well. Because people will assume nothing is required, which is the regular stuff when running docker images. Have a look at our v2 cartridge, if I'm adding mysql, at the end of the process I'm being given the credentials to access them, whereas here you need to set them upfront and we need to stress that, imho.

**Comment by mnagy** [comment]
@bparees Cool, that sounds like a good idea. We were actually discussing this with @tnguyen-rh as well. Should it be a tutorial, maybe in a separate section? It could even include more use-cases.

BTW, can we get someone from the docs team included in the loop? Not sure if there's someone specifically responsible for images. @tpoitras maybe?

**Comment by tnguyen-rh** [comment]
Yeah, i remember we (@mnagy and i) talked about two models: the db-first model and the app-first model.  IIUC deploying a db image results in a service whose particulars must be communicated to the app via env vars.  Thus, the least-hassle flow is db-first, and our docs currently assume that (actually, they kind of assume "db-only" and side-step the ordering issue entirely).

I think this ordering assumption should be documented, whether or not we add a tutorial, so that people will be prepared for the increased complexity (env vars injection via `oc env`?) involved w/ the app-first approach.

**Comment by vikram-redhat** [comment]
@CowboysFan - is this something that we could cover as a use case?

**Comment by vikram-redhat** [comment]
This issue is very old and at this point in time since we never got around to doing anything with it, I am going to close it. Please reopen if any fresh input is available.
