### ISSUE TITLE
Update GlusterFS links to latest release Red Hat Storage release (3.3) for OpenShift 3.6

### ISSUE THREAD

**Issue by Cameronwyatt** [openshift/openshift-docs#6022]
The links [here](https://docs.openshift.com/container-platform/3.6/install_config/persistent_storage/persistent_storage_glusterfs.html) for Red Hat Storage point to an older release. There is a more current release (3.3) that has updated instructions for OpenShift 3.6, found [here](https://access.redhat.com/documentation/en-us/red_hat_gluster_storage/3.3/html/container-native_storage_for_openshift_container_platform/)

**Comment by tmorriso-rh** [comment]
Notes to TW:

https://access.redhat.com/documentation/en-us/red_hat_gluster_storage/3.3/html/container-native_storage_for_openshift_container_platform/

**Comment by tmorriso-rh** [comment]
Fixed: https://github.com/openshift/openshift-docs/pull/7442
