### ISSUE TITLE
No documentation for how to open port 1936 for Default Router

### ISSUE THREAD

**Issue by oybed** [openshift/openshift-docs#6054]
The default OpenShift router exposes port 1936 by default for statistics. However, this port isn't open in the firewall / iptables. After discussing this over with a few others, we agreed that this probably needs to be covered by documentation on how to set up - part of the admin guide for the router.

https://docs.openshift.com/container-platform/3.6/admin_guide/router.html

**Comment by vikram-redhat** [comment]
This is covered as step 4. Closing.
