### ISSUE TITLE
Docs are inconsistent and inaccurate with regard to use of NFS for PVs for logging.

### ISSUE THREAD

**Issue by tdudgeon** [openshift/openshift-docs#6080]
The 3.6.0 and latest advanced (ansible) installer docs [1] specifically describes how to define using NFS for persistent storage, but the docs for "aggregating container logs" [2] says that NFS should not be used (except in one particular scenario) and seems to suggest that the only really suitable scenario is to use a volume (disk) directly mounted to each logging node. 

This needs clarifying and updating. At least:

1. remove the suggestions on how to use NFS in [1] and replace with something more accurate.
1. update [1] to better reflect the new properties defined in [2] (now that the openshift_hosted_logging_* properties are deprecated). Same for metrics
1. update [2] to make it clearer what strategies can be used for handling persistence for ES 

[1] https://docs.openshift.org/latest/install_config/install/advanced_install.html#advanced-install-cluster-logging

[2] https://docs.openshift.org/latest/install_config/aggregate_logging.html#aggregated-elasticsearch

**Comment by Neikius** [comment]
As a beginner I see no way of installing logging. The documentation also claims you can install without storage, but if you don't specify storage nothing is installed. How do you install logging using ansible scripts when there is a directly mounted physical volume on a node? There are some manual steps provided but how do you get that far when the installation fails?

**Comment by tdudgeon** [comment]
That's not really related to this topic, but assuming you are using the ansible installer you probably need to add this to your inventory file:
openshift_logging_install_logging=true
The docs state that logging is now installed by default, but in my experience this is not the case and you still need to set this flag to true for it to be installed.

**Comment by uocxp** [comment]
will this issue get ever closed ? The documentation is really confusing. I installed the cluster with Glusterfs also for logging and after about a month i realise  that [2]  suggest that using Glusterfs is not supported for Elasticsearch

**Comment by uocxp** [comment]
i don't really understand why the [documentation](https://docs.okd.io/3.10/install/configuring_inventory_file.html#advanced-install-cluster-logging) states only 3 options to configure the cluster logging (Option A: Dynamic with glusterfs,Option B: NFS Host Group,Option C: External NFS Host) and in then  another part of the [documentation](https://docs.okd.io/3.10/install_config/aggregate_logging.html#aggregated-elasticsearch) states
>Using NFS storage as a volume or a persistent volume (or via NAS such as Gluster) is not supported for Elasticsearch storage
The only way remains for me is using a local volume (hostpath) but the documentation does not state how to configure this option in the inventory file

**Comment by ToroNZ** [comment]
Somehow Red Hat says you can use PureStorage NFS though... 2+2=3
