### ISSUE TITLE
Source Build Logs doesn't have Level 4

### ISSUE THREAD

**Issue by nak3** [openshift/openshift-docs#609]
http://docs.openshift.org/latest/dev_guide/builds.html#accessing-build-logs

I'm sorry if it is intentinal, but is that true that we can set `Level 0` to `Level 5` without `Level 4`?

**Comment by nak3** [comment]
I think we should add this line:
~~~
Level 4  currently produces same information as level 3 
~~~

**Comment by tpoitras** [comment]
fixed in PR1071

https://github.com/openshift/openshift-docs/pull/1071
