### ISSUE TITLE
EFK Storage Considerations error in example scenario and calculations

### ISSUE THREAD

**Issue by dcaldwel** [openshift/openshift-docs#6113]
In the EFK Storage Considerations section (install_config/aggregate_logging_sizing), there appears to be an error in the given example scenario. 

The example scenario is:

> Assumptions:
> Which application: Apache
> Bytes per line: 256
> Lines per second load on application: 1
> Raw text data → JSON
> Baseline (256 characters per minute → 15KB/min)

I think that the line  

> (256 characters per minute → 15KB/min)

should read 

> (256 characters per **second** → 15KB/min)

Further, the table of example calculations seems to be wildly inaccurate because:
- a seconds-per-day multiplier is used when the given byte values seem to be per minute;
- the third line calculation in the table is a duplicate of the second line. 

Also, it is not made clear where the values in the calculations come from. Eg: line one in the table shows "90000" which appears to be an approximation of the product of 6 pods logging 256 bytes per line per second multiplied by 60 to give a per minute byte value.

If I am correct about the 90000 value, then I believe that the table calculations _should_ look something like this (based upon 256 bytes per line per second per pod):
6 pods total: 6 pods x 92160 bytes per minute x 1440 minutes per day = 0,124 GB/day
16 pods total: 16 pods x 92160 bytes per minute x 1440 minutes per day = 0,33 GB/day
25 pods total: 25 pods x 92160 bytes per minute x 1440 minutes per day = 0,515 GB/day

**Comment by tmorriso-rh** [comment]
Following up with aos-storage team on this issue.

**Comment by jsafrane** [comment]
There is not much from storage perspective, it's related to logging. @rflorenc is author of the page and could shed some light into the numbers there and @bmcelvee was recommended to me by our log team as the current logging point of contact.
