### ISSUE TITLE
Etcd backup and restore guide isn't valid for etcd data v3

### ISSUE THREAD

**Issue by juanluisvaladas** [openshift/openshift-docs#6141]
The current process [1] is only suitable for etcd data model 2 [2]. Since 3.6 we use data model 3 which backs up  differently [3]

1- https://docs.openshift.com/container-platform/3.6/admin_guide/backup_restore.html#etcd-backup
2- https://coreos.com/etcd/docs/latest/v2/admin_guide.html#disaster-recovery
3- https://coreos.com/etcd/docs/latest/op-guide/recovery.html

**Comment by juanluisvaladas** [comment]
Also affects 3.7 and beyond

**Comment by vikram-redhat** [comment]
@adellape - are your updates covering this?

cc: @aheslin

**Comment by vikram-redhat** [comment]
This was covered and updated recently by @kalexand-rh's changes to this topic. Closing.
