### ISSUE TITLE
Ingress IP Self-Service documentation results in a 404

### ISSUE THREAD

**Issue by pweil-** [openshift/openshift-docs#6142]
Missing target for link related to Ingress IP Self-ServiceAdditional Informationhttps://docs.openshift.org/latest/minishift/openshift/exposing-services.html links to a non-existent link https://docs.openshift.org/latest/dev_guide/getting_traffic_into_cluster.html#using-ingress-IP-self-serviceRelated issue; minishift/minishift#1651
--

@gbraad

**Comment by pweil-** [comment]
https://github.com/openshift/origin/issues/17165

**Comment by vikram-redhat** [comment]
This is a Minishift documentation issue, and I guess it was resolved via the commits. Closing.
