### ISSUE TITLE
[OKD] docs page footer covering content

### ISSUE THREAD

**Issue by jeana-redhat** [openshift/openshift-docs#61779]
### Which section(s) is the issue in?
All, but initially observed [here](https://docs.okd.io/4.13/machine_management/index.html).

### What needs fixing?
Browsers tested: Firefox, Chromium

If you scroll to the end of the page, the footer is covering the content at the bottom of pages. Example from the linked page:

![image](https://github.com/openshift/openshift-docs/assets/61474374/deaa6290-f8db-446f-af47-4d42e553f4e6)

**Comment by rolfedh** [comment]
Hi @jeana-redhat, @mburke5678, 
I'm not seeing this in the current docs. Is this issue resolved?

**Comment by jeana-redhat** [comment]
@rolfedh yeah LGTM on Firefox just now :nerd_face: :tada:

**Comment by mburke5678** [comment]
LGTM
