### ISSUE TITLE
docs.okd.io is down

### ISSUE THREAD

**Issue by RickBankers** [openshift/openshift-docs#61894]
docs.okd.io is down. seems like this happens frequently due to stuck deployments.

Can a fix be put in so if a deployment fails it restores the previous state?

**Comment by kalexand-rh** [comment]
@wgordon17 restored docs.okd.io last night. Will, is there anything else that we can do on the OKD side to prevent outages?

**Comment by wgordon17** [comment]
We've put a number of fixes in place, and (at least in my experience) the doc's sites have been more stable in the recent months. This most recent outage was an unfortunate confluence events including a PR that broke new builds and then an upgrade of the underlying cluster that took down healthy deployments. We're putting in some additional improvements and processes to prevent this in future.
