### ISSUE TITLE
topic consolidation recommendations

### ISSUE THREAD

**Issue by bparees** [openshift/openshift-docs#6208]
the "installation+configuration" section has a bunch of sub-topics that i think can be grouped+nested.

1) Configuring the SDN, Configuration the Nuage SDN  (nest under configuring the SDN.  maybe the Nuage SDN bit even just becomes a section of the SDN doc)

2) Configuring for AWS, GCE, Azure, OpenStack, VMWare (these can all nest under "configuring for specific platforms" or something)

3) configuring for local volume + deploying external persistent volume provisioners - nest under configuring persistent storage

4) aggregating container logs + aggregate logging sizing guidelines (nest as aggregated logging config?)

5) configuring custom certificates, redeploying certificates (nest as certificate management?)

@bmcelvee

**Comment by bmcelvee** [comment]
@bparees Thanks!  I opened a Documentation Trello Card for this issue.

**Comment by vikram-redhat** [comment]
We are redoing our docs for 4.0 and this may get addressed in there. Closing.
