### ISSUE TITLE
docker storage configuration is required

### ISSUE THREAD

**Issue by sosiouxme** [openshift/openshift-docs#621]
Our Docker folks have been pretty clear that the default configuration where docker creates loopback devices for container volumes is unsupportable. We need to call this out in prereqs https://docs.openshift.org/latest/admin_guide/install/prerequisites.html#host-preparation and walk through setting up storage correctly.

We did so in beta docs https://github.com/openshift/training/blob/master/beta-4-setup.md#docker-storage-setup-optional-recommended

**Comment by adellape** [comment]
It's currently conditionalized to only show up in the OSE version ("Configuring Docker Storage"):

https://docs.openshift.com/enterprise/3.0/admin_guide/install/prerequisites.html#host-preparation

I don't recall why we conditionalized it at the time. Should probably show up in both, yea?

----- Original Message -----

**Comment by nhr** [comment]
Closing; fixed in #623
