### ISSUE TITLE
tls profiles - intermediate doc is ambigious 

### ISSUE THREAD

**Issue by yuvalk** [openshift/openshift-docs#62199]
https://github.com/openshift/openshift-docs/blob/ed7c238695e7b89cce2d56d0424fb23390501305/modules/tls-profiles-understanding.adoc?plain=1#L30C1-L31C82

the wording "the profile is based on.." is making the feeling that we're only based on that list and not necessarily following it.

better clearly say whether we strictly follow the list on https://wiki.mozilla.org/Security/Server_Side_TLS#Intermediate_compatibility_.28recommended.29
and if not, provide guide on what we actually do.

I think saying something like "The profile is strictly following mozilla Intermediate compatibility recommendations" and provide the link
(assuming that what we do)

**Comment by RakshitKumar04** [comment]
Hey, @yuvalk I would like to work on this issue, would you please assign this to me?

**Comment by RakshitKumar04** [comment]
assign @RakshitKumar04
