### ISSUE TITLE
architecture -> infrastructure -> dynamic components

### ISSUE THREAD

**Issue by sosiouxme** [openshift/openshift-docs#622]
I think this needs an overhaul:
https://github.com/openshift/openshift-docs/blob/master/architecture/infrastructure_components/image_registry.adoc

I would actually propose that this be subsumed in a page that discusses the components that run on top of the basic infrastructure, which include:

1. routers
2. registry
3. keepalived
4. In the near future, private git server a la gitolite
5. optionally some authentication pieces
6. possibly other admin bits, like a project creation manager
7. Eventually - monitoring infrastructure, log aggregators, continuous integration, etc etc

These might deserve separate pages eventually, but for now I think it would be a good idea to discuss them in one place, separately from the master/nodes stuff. Partly because the great thing about all this is that using the infrastructure it can all be made redundant and HA without a great deal of trouble.

What to call this? Some candidates:

1. Dynamic components
2. Layered components
3. Infrastructure applications
4. ... ?

Opinions and name ideas welcome.

**Comment by adellape** [comment]
:+1:

Spitballing use of "Integrat*"...

Integrated Components
Integration Components
Integrated Layers

**Comment by sosiouxme** [comment]
I guess the other complication is that these pieces *could* be running on top of OpenShift, but may well not be. We'll provide implementations that are easy to integrate, but the reason they're not just compiled right into OpenShift is so they can be swapped out with something customized. So maybe the name should hint at that. Does "integration" point that way? They are certainly defined integration points. Pluggable/optional. "Integration components" may strike the right balance of clarity and ambiguity. "Integrated" to me sounds too much like just part of the product. Maybe even "extensible"? "Extended components?"

**Comment by adellape** [comment]
Yeah, good point. "Integrated" sounds like a foregone conclusion that they are running on top of OpenShift. "Integration" sounds like it could be either (internal/external).

"Extended" make them sound too optional, even if many/most technically are.

**Comment by adellape** [comment]
Moving this to https://bugzilla.redhat.com/show_bug.cgi?id=1271382

@sosiouxme It's obviously been a while since this was discussed, so if you have any newer thoughts/ideas on this, please comment in the BZ.
