### ISSUE TITLE
Application on OpenShift Online are not accessible(STARTER PLAN West-1-California)

### ISSUE THREAD

**Issue by stanky91** [openshift/openshift-docs#6266]
I can't access my application on OpenShift Online (STARTER PLAN West-1-California).But the pods are still running normally.I found some sites running on West-1-California servers through Google with the keywords "west   openshiftapps.com",And they are not available at all.

**Comment by tiwillia** [comment]
Hi @stanky91,

Thanks for bringing this to our attention. It does appear as though there are some problems with applications on the starter west-1 cluster. We are addressing this now.

**Comment by wgordon17** [comment]
@stanky91 In the future, such issues would be better reported in our [community channel](https://help.openshift.com/forms/community-contact.html), as this repository is only used for documentation.

**Comment by ahardin-rh** [comment]
@tiwillia @wgordon17 Thanks!

**Comment by stanky91** [comment]
@tiwillia @wgordon17 @ahardin-rh  I see.Thank you.
