### ISSUE TITLE
Edits and suggested changes to the Overview section of the Advanced Installation doc

### ISSUE THREAD

**Issue by IngridT1** [openshift/openshift-docs#6273]
This is a fairly complex edit, and I think it would be easier to work with one or more OpenShift writers to make sure this section is still technically correct. As a result, I'm going to provide this edit as an issue instead of a merge request.

The Overview as it currently stands is confusing and has both an **Important** warning and a separate **Note**. It would help readers more if the information marked "Important" or "Note" were included as a heading, so readers can scan and see if it applies to them.

I have also edited the text to make it more readable. I noticed that there's some text missing in the **Important** warning, between "run from" and "The", there's no period and something's missing.

"While RHEL Atomic Host is supported for running containerized {product-title} services, the advanced installation method utilizes Ansible, which is not available in RHEL Atomic Host, and must therefore be _run from The_ host initiating the installation does not need to be intended for inclusion in the {product-title} cluster, but it can be."

This Google doc has the suggested changes for reorganizing the Overview to be clearer:
https://docs.google.com/a/redhat.com/document/d/1pbpW556zJeRrHT-7RCNoFwolY9IvHHH2LlanCSBqZl8/edit?usp=sharing

**Comment by vikram-redhat** [comment]
Closing this as these edits never made it to the docs and we are unlikely to get to this for 4.0.
