### ISSUE TITLE
Edits and suggested changes to the Before You Begin section of the Advanced Installation doc

### ISSUE THREAD

**Issue by IngridT1** [openshift/openshift-docs#6294]
Could one of the OpenShift writers look at this rewrite of that section and see if it makes sense?
https://docs.google.com/a/redhat.com/document/d/1xKnzOQmcSRLu49mvXhbEA4VwieVwoUa8WJJjTgFRI2w/edit?usp=sharing

**Comment by vikram-redhat** [comment]
@adellape - can you take a look this week?

**Comment by vikram-redhat** [comment]
Most topics are rewritten so closing this.
