### ISSUE TITLE
Ambiguous wording for ellipses

### ISSUE THREAD

**Issue by apinnick** [openshift/openshift-docs#63286]
https://github.com/openshift/openshift-docs/blob/d56b81c763e80ad3730e355279876b4b1e3d18d9/contributing_to_docs/doc_guidelines.adoc?plain=1#L1276

The current wording suggests that it is OK to use either `...` or `# ...` in YAML files. 

YAML file ellipses look like this: `# ...".

**Comment by rolfedh** [comment]
Marking this as a good candidate for Hacktoberfest.
If someone is interested in taking it, please make the change against the `main` branch.
I'd revise it to say something like:
```
* For snippets or sections of a file, use an ellipsis (`...`) to show that the file continues before or after the quoted block. For YAML, use `# ...` instead.```

Feel free to come up with something better 😄

**Comment by RakshitKumar04** [comment]
Hey, @apinnick I would like to work on this issue, would you please assign this to me?

**Comment by rolfedh** [comment]
Hi, @RakshitKumar04. Thanks for your interest in this issue. I've assigned it to you. 

I'm here as the [Hacktoberfest](https://hacktoberfest.com/) "guide" to help you with this issue. Please confirm if you're participating in Hacktoberfest. To count as part of Hacktoberfest, please don't create a pull request for this issue until October 1st.

**Comment by RakshitKumar04** [comment]
Hello, @rolfedh Thank you for being my guide, this is my first time contributing to openshift. So I would love to have your guidance. Can I raise the PR before Hacktoberfest? I would like to contribute more to this repo.

Also, how would this sound?
```
* For snippets or sections of a file, use an ellipsis (`...`) to show that the file continues before or after the quoted block. While for a YAML, use (`# ...`) instead.
```

**Comment by rolfedh** [comment]
Hey @RakshitKumar04! 🎉 First off, thanks so much for your enthusiasm and for sending in this PR. I'm planning to review it later today.

Just a quick reminder: I had mentioned the ideal time to create a PR for Hacktoberfest is "**on or after** October 1st." Some of us Hacktoberfest enthusiasts sometimes submit PRs a bit early. Based on what I know, those early submissions might not be counted for those awesome Hacktoberfest badges on GitHub.

Given that, you might want to think about closing this PR and submitting a new one after October 1st. But if participating in Hacktoberfest isn't your main goal and you're focused on the contribution, just let me know, and we'll work together to get this merged.

What are your thoughts?

Cheers,
Rolfe 🚀

**Comment by RakshitKumar04** [comment]
Hey, @rolfedh I would like to go with the latter i.e. you can merge the PR as my goal is to contribute and know more and more about openshift.

**Comment by rolfedh** [comment]
Great work, @RakshitKumar04. Thank you.
