### ISSUE TITLE
Unsubstituted variable in text

### ISSUE THREAD

**Issue by mikemckiernan** [openshift/openshift-docs#63319]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.13/hardware_enablement/about-hardware-enablement.html

### What needs fixing?

The text `:op-system-first:` is bleeding through into the HTML.  Seems like variable substitution didn't work.

**Comment by apinnick** [comment]
@sheriff-rh The broken attribute was introduced in your [PR](https://github.com/openshift/openshift-docs/pull/55193). Could you fix this?

**Comment by sheriff-rh** [comment]
Thanks @apinnick!

**Comment by sheriff-rh** [comment]
@mikemckiernan I went ahead and merged since this was such an easy fix. Thanks for bringing this to our attention!
