### ISSUE TITLE
MicroShift RPM Install Procedure doesn't work on RHEL for Edge (OSTree based) - solution

### ISSUE THREAD

**Issue by markusjnagel** [openshift/openshift-docs#63578]
### Which section(s) is the issue in?
https://access.redhat.com/documentation/en-us/red_hat_build_of_microshift/4.13/html/installing/microshift-install-rpm#installing-microshift-from-rpm-package_microshift-install-rpm 
https://github.com/openshift/openshift-docs/blob/main/microshift_install/microshift-install-rpm.adoc 

### What needs fixing?

**Procedure** 
2. Install Red Hat build of MicroShift by running the following command:

`$ sudo dnf install -y microshift
`
3. Optional: Install greenboot for Red Hat build of MicroShift by running the following command:

`$ sudo dnf install -y microshift-greenboot
`

---
### Problem

The above installation procedure does not work if you are running RHEL for Edge (OSTree-based). Dnf will give you the error that it can't create a lock on the rpm db, since this is a read-only filesystem.
`error: can't create transaction lock on /usr/share/rpm/.rpm.lock (Read-only file system)`

### Solution

For RHEL for Edge, you have to replace `sudo dnf install -y microshift microshift-greenboot` with `sudo rpm-ostree install microshift` and `sudo rpm-ostree install microshift-greenboot`, respectively. 

The rest of the installation instructions works perfectly on RHEL for Edge. 

--- 
_I would change this myself by means of a PR, but I don't fully understand the branch/repo structure, so I'll just leave this here for someone to pick up. Sorry._ 

Cheers,
Markus

**Comment by rolfedh** [comment]
Hi Markus. It looks like the topic you want to change is [for RHEL only](https://access.redhat.com/documentation/en-us/red_hat_build_of_microshift/4.13/html/installing/microshift-install-rpm#microshift-install-system-requirements_microshift-install-rpm) and installing microshift on RHEL for Edge is covered in the next section, [Chapter 2. Embedding Red Hat build of MicroShift in a RHEL for Edge image](https://access.redhat.com/documentation/en-us/red_hat_build_of_microshift/4.13/html/installing/microshift-embed-in-rpm-ostree#doc-wrapper). Do you agree?

**Comment by ShaunaDiaz** [comment]
@markusjnagel Yes, @rolfedh is correct, that procedure is not meant for RHEL. The second procedure is meant for RHEL for Edge (I am the lead MicroShift tech writer).  I'm curious, did you then follow the other doc section to build the RHEL for Edge image?
