### ISSUE TITLE
Multiple instances of "the the" in documentation

### ISSUE THREAD

**Issue by mikesmith0414** [openshift/openshift-docs#63731]
### Which section(s) is the issue in? There are multiple sections in which the phrase "the the" occurs in the documentation. These modules include the follow: 

- developer-cli-odo-ref-catalog.adoc
- oc-mirror-imageset-config-params.adoc
- osd-persistent-storage-csi-efs-sts.adoc
- rosa-cluster-logging-collector-log-forward-sts-cloudwatch.adoc
- virt/getting_started/virt-using-the-cli-tools.adoc

There are also two more in the following API modules:

- /Users/mikesmith/pp/openshift-docs/openshift-docs/rest_api/config_apis/imagedigestmirrorset-config-openshift-io-v1.adoc
- /Users/mikesmith/pp/openshift-docs/openshift-docs/rest_api/security_apis/credentialsrequest-cloudcredential-openshift-io-v1.adoc

**Comment by mikesmith0414** [comment]
Submitted PR at https://github.com/openshift/openshift-docs/pull/63732.

**Comment by stevsmit** [comment]
Thanks @kelbrown20
