### ISSUE TITLE
[OKD] Remove ClusterResourceOverride Operator docs

### ISSUE THREAD

**Issue by shdwchn10** [openshift/openshift-docs#63937]
### Which section(s) is the issue in?
[Configuring your cluster to place pods on overcommitted nodes](https://docs.okd.io/latest/nodes/clusters/nodes-cluster-overcommit.html)

### What needs fixing?
ClusterResourceOverride Operator isn't available in the community catalog, so this page is irrelevant for OKD and should be removed.

**Comment by deveshidwivedi** [comment]
hello, please assign me this issue under hacktoberfest 2023.

**Comment by deveshidwivedi** [comment]
hello, could you please guide me how to go about the task please?

**Comment by rolfedh** [comment]
Hi @deveshidwivedi. I believe in `_topic_maps/_topic_map.yml`, you revise the value of `Distros:` shown below:
```
  - Name: Configuring your cluster to place pods on overcommited nodes
    File: nodes-cluster-overcommit
    Distros: openshift-enterprise,openshift-origin
```
to 
```
  - Name: Configuring your cluster to place pods on overcommited nodes
    File: nodes-cluster-overcommit
    Distros: openshift-origin
```
If you create a PR today, I can mark it as `hacktoberfest-accepted` so you get points for it.

**Comment by deveshidwivedi** [comment]
thank you! @rolfedh

**Comment by rolfedh** [comment]
I apologize. I wasn't able to tag your PR before the hacktoberfest expired. 
Nonetheless, thank you for contributing your PR.
I hope you continue contributing to open source projects like ours.
You're welcome to ask me any questions if you need help with similar projects in the future.
Hope to see you again in Hacktoberfest 2024 and beyond!

**Comment by ShaunaDiaz** [comment]
@rolfedh Looks like this issue can be closed. I'm not familiar with OKD enough to link the live doc where this was removed. Could you link it here and close the issue?

**Comment by rolfedh** [comment]
Thanks @ShaunaDiaz. This issue was fixed in https://github.com/openshift/openshift-docs/pull/67151.
