### ISSUE TITLE
Tidy up EAP migration docs

### ISSUE THREAD

**Issue by sspeiche** [openshift/openshift-docs#6397]
https://docs.openshift.com/online/dev_guide/migrating_applications/web_framework_applications.html#dev-guide-migrating-web-framework-applications-jboss-eap

To align with EAP roll out due any day.

**Current docs have**
If the repository includes pre-built .war files, they need to reside in the deployments directory off the root directory of the repository.

Create the new application using the JBoss EAP 6 builder image (jboss-eap64-openshift) and the source code repository from GitHub:

$ oc new-app --strategy=source jboss-eap64-openshift~https://github.com/<github-id>/<repo-name>.git

**We are providing EAP 7, so would be good to move people forward..no?**

**To something like this**

Create the new application using the JBoss EAP 7 builder image (jboss-eap70-openshift) and the source code repository from GitHub:

$ oc new-app --strategy=source jboss-eap70-openshift~https://github.com/<github-id>/<repo-name>.git

/cc @wgordon17 @aheslin

**Comment by thesteve0** [comment]
Hey @sspeiche and @wgordon17 I can help with this. Is this for OCP or for Online Pro?

**Comment by wgordon17** [comment]
@thesteve0 This is for the Online Pro launch of EAP

**Comment by thesteve0** [comment]
Ok there is a bunch of work happening on the templates now. Since we are no
longer exposing raw builders, we are going to have to supply the template
paramters. I think the first draft of the EAP 7 templates can be found here:

https://github.com/redhat-middleware-hackathon/openshift-files/tree/master/eap

They were made for the hackthon.

**Comment by adellape** [comment]
So we can't just make the change as @sspeiche described?

**Comment by thesteve0** [comment]
@adellape according to @knrc using the raw builder images was removed from the catalog per request by @sspeiche. The command line should still work (I think, though I haven't tested). But they will not show up in the catalog. 

I think we can quickly do 7.0 like @sspeiche said.

**Comment by sspeiche** [comment]
@adellape Yes, changes as I described. Which are an immediate need.

**Comment by bingli7** [comment]
As EAP 6 imagestreams/templates were removed from Online Pro, how to migrate EAP 6.4 to v3? Should we highlight this in the docs? Thanks!

**Comment by knrc** [comment]
Note the hackathon templates were only done for Steve's hackathon and are not official, some of these changes have already been made to the official templates and we are looking at alternative ways to simplify them further.

**Comment by vikram-redhat** [comment]
@wgordon17 @thesteve0 - did you ever submit a PR for this?
