### ISSUE TITLE
Should updated the description of distribution api

### ISSUE THREAD

**Issue by guangxuli** [openshift/openshift-docs#6406]
update: https://docs.openshift.org/latest/rest_api/index.html

The OpenShift Origin distribution of Kubernetes includes the` Kubernetes v1 REST API` and the `OpenShift v1 REST API.`  Please update the link or description.

**Comment by vikram-redhat** [comment]
Closing this as this is for the upstream docs. If someone wants to submit a PR to fix, we can look at it.
