### ISSUE TITLE
using-a-service-external-ip-to-get-traffic-into-the-cluster - typos and general misinformation

### ISSUE THREAD

**Issue by dcaldwel** [openshift/openshift-docs#6408]
RE: https://github.com/openshift/openshift-docs/blob/master/dev_guide/expose_service/expose_internal_ip_service.adoc#using-a-service-external-ip-to-get-traffic-into-the-cluster

There are typos on this page ("curl:" should not have the colon and there is inconsistency with the "192" addressing used which is very confusing). 

The section that adds routes makes no sense from a technical perspective given the previous text above it.

Overall, the concept of using an external IP service is not presented in an understandable manner. The objective of the service is not well explained. The example adding routes is inaccurate and makes no sense in the context of text above it. The reason to add routes and where they should be added (if necessary) is not discussed.

**Comment by vikram-redhat** [comment]
Multiple changes have been made to this section since the original issue was raised. I am going to close this, but please open a new one if issues still need addressing.
