### ISSUE TITLE
Need information about `examples/quickstart-templates`

### ISSUE THREAD

**Issue by nak3** [openshift/openshift-docs#641]
https://ci.openshift.redhat.com/openshift-docs-master-testing/latest/admin_guide/install/first_steps.html#creating-quickstart-templates

There are no `examples/quickstart-templates` in [origin](https://github.com/openshift/origin/tree/master/examples). What `examples/quickstart-templates` the doc point to?

~~~
To create the core QuickStart templates:

$ oc create -f \
    examples/quickstart-templates -n openshift
~~~

**Comment by adellape** [comment]
If you used the Ansible-based installer, they should already be automatically imported in the default "openshift" project that everyone can view. But to answer your question, it's referring to files on the master. See https://docs.openshift.org/latest/admin_guide/install/first_steps.html#overview:

"If you opted out of creating them during an advanced installation, you can use the following instructions to create the objects yourself. The files are installed on the file system of your master."

This could be made clearer throughout. Though, my understanding is that this situation may change in the future, e.g. https://github.com/openshift/openshift-docs/pull/719#discussion-diff-34279363.

**Comment by rafabene** [comment]
The point is that the directory `quickstart-templates` doesn't exists in https://github.com/openshift/origin/tree/master/examples

**Comment by adellape** [comment]
No longer an issue:

https://docs.openshift.com/enterprise/3.0/install_config/install/first_steps.html
