### ISSUE TITLE
Attributes in doc templates?

### ISSUE THREAD

**Issue by lucascosti** [openshift/openshift-docs#643]
After working on the xPaaS docs, I created this issue for the asciidoctor Firefox extension not working:

https://github.com/asciidoctor/asciidoctor-firefox-addon/issues/30

[The advice was](https://github.com/asciidoctor/asciidoctor-firefox-addon/issues/30#issuecomment-116361202) that some of the attributes used in [the template](
https://github.com/openshift/openshift-docs/blob/master/contributing_to_docs/templates/topic_template.adoc) are not necessary, and should probably not be used in the source doc.

**Comment by CowboysFan** [comment]
@lucascosti Thanks for bringing this up, we'll get it fixed.
