### ISSUE TITLE
[enterprise-4.13] Issue in file networking/using-ptp.adoc

### ISSUE THREAD

**Issue by tginer** [openshift/openshift-docs#64717]
### Which section(s) is the issue in?
Configuring PTP devices

### What needs fixing?
The PtpConfig CR object examples include in recommend.match field both **nodeLabel** and **nodeName**

```shell script

 match:
        - nodeLabel: "node-role.kubernetes.io/worker"
          nodeName: "<node_name>"
```

and this leads to confusion because it is contradictory to the field description in Table 1 and Table 2:
```shell script
.recommend.match : Specify .recommend.match rules with nodeLabel **or** nodeName
```

I think the PtpConfig CRs should also only target nodeLabel or nodeName because when following the documentation as it is right now, it is not straight forward that all workers will be configured, as well as <node_name> node. 

It seems as if only <node_name> from all workers will be configured, instead of the OR operation that is going on in the match field.

From all the PtpConfig CR examples, I would add one that only contains <node_name> and maybe further explain in the example contaning both of them, that all workers plus <node_name> will be targeted.

**Note**: In fact, when seeking to apply different profiles to different <node_name> but leaving the nodeLabel field under the match, PTP crashed due to simultaneous _ptp4l_ and _phc2sys_ processes running in the same nodes.

**Comment by aireilly** [comment]
Created https://issues.redhat.com/browse/OCPBUGS-19309 to track
