### ISSUE TITLE
Missing supported some cloud providers for compute machine set in docs

### ISSUE THREAD

**Issue by bergerhoffer** [openshift/openshift-docs#64725]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.12/machine_management/index.html#machine-mgmt-intro-managing-compute_overview-of-machine-management

### What needs fixing?

Under "Managing compute machines" [1] there is a list with heading "Create a compute machine set for the following cloud providers" that has 6 providers listed, although the table of contents tab lists 10.

Links need to be added to the missing cloud providers.

![image](https://github.com/openshift/openshift-docs/assets/7443887/8cd4c954-0379-4b29-bab7-dc8fd2cfb330)

### Additional information

**Note to OCP docs writers**: This issue has been temporarily duplicated from Jira (https://issues.redhat.com/browse/OCPBUGS-11502) to give an opportunity for a Hacktoberfest contributor.

**If this issue is completed through this GitHub issue, the Jira issue also needs to be closed**

**Comment by bergerhoffer** [comment]
Marking this as a good candidate for Hacktoberfest.

If someone is interested in taking it, this one actually requires 2 PRs:

1. A PR against the `main` branch that adds 5 missing cloud provider links: Alibaba, Azure Stack Hub, IBM Cloud, IBM Power Virtual Server, and Nutanix
**This PR will apply to 4.14 and 4.13**
2. A PR against `enterprise-4.12` that adds 4 missing cloud provider links: Alibaba, Azure Stack Hub, IBM Cloud, and Nutanix
**This PR will apply to 4.12 and 4.11**

**Comment by 7h3-3mp7y-m4n** [comment]
hey I love to work on this :)

**Comment by bergerhoffer** [comment]
Thanks @7h3-3mp7y-m4n , I'm assigning it to you.

If you're participating in Hacktoberfest, be sure to wait until Oct 1 to submit the PR for it to count. Let me know if you have any questions!

**Comment by 7h3-3mp7y-m4n** [comment]
thank you very much @bergerhoffer :)
