### ISSUE TITLE
Incorrect API version in buildconfig example

### ISSUE THREAD

**Issue by bergerhoffer** [openshift/openshift-docs#64730]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.13/cicd/builds/creating-build-inputs.html#builds-manually-add-source-clone-secrets_creating-build-inputs

### What needs fixing?

In [Manually adding a source clone secret](https://docs.openshift.com/container-platform/4.13/cicd/builds/creating-build-inputs.html#builds-manually-add-source-clone-secrets_creating-build-inputs) (builds-manually-add-source-clone-secrets.adoc), the API in the sample code is incorrect. It should be `build.openshift.io/v1`.

### Additional information

**Note to OCP docs writers**: This issue has been temporarily duplicated from Jira (https://issues.redhat.com/browse/OSDOCS-7419) to give an opportunity for an outside Hacktoberfest contributor.

**If this issue is completed through this GitHub issue, the Jira issue also needs to be closed**

**Comment by bergerhoffer** [comment]
Marking this as a good candidate for Hacktoberfest.

If someone is interested in taking it, open the PR against the `main` branch. And make a note in the description of the PR that it applies to versions 4.11+.

In the linked example, the following line:

```
apiVersion: "v1"
```

needs to be changed to:

```
apiVersion: "build.openshift.io/v1"
```

**Comment by BTSisLove** [comment]
I would like to work on this .

**Comment by rolfedh** [comment]
Duplicate issue: https://github.com/openshift/openshift-docs/pull/65564#issuecomment-1766416204
Granted points to @BTSisLove for their PR, #65564. Thanks!
