### ISSUE TITLE
Name of vSphere CSI Driver Operator is written incorrectly several places

### ISSUE THREAD

**Issue by bergerhoffer** [openshift/openshift-docs#64747]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.13/storage/container_storage_interface/persistent-storage-csi-vsphere.html

### What needs fixing?

In several sections on this page, there are several places where the vSphere CSI Driver Operator is incorrectly written as "vSphere CSI Operator Driver"

These two files are affected:
* persistent-storage-csi-vsphere-install-issues.adoc
* persistent-storage-csi-vsphere-stor-policy.adoc

The instances of "vSphere CSI Operator Driver" need to be fixed to "vSphere CSI Driver Operator"

### Additional information

**This issue is duplicated from https://issues.redhat.com/browse/OCPBUGS-18575. If this issue is resolved here, we need to close that Jira as well.**

**Comment by bergerhoffer** [comment]
Marking this as a good candidate for Hacktoberfest.

If someone is interested in taking it, open the PR against the `main` branch. And make a note in the description of the PR that it applies to versions 4.11+.

**Comment by AryanSharma9917** [comment]
Hi @bergerhoffer, I would like to work on this issue, could you please assign this to me?

**Comment by bergerhoffer** [comment]
Hi @AryanSharma9917, absolutely!

Just note that if you're looking to do this for Hacktoberfest, it won't count unless you wait until October to submit the PR. Let me know if you have any questions!
