### ISSUE TITLE
Missing URL 

### ISSUE THREAD

**Issue by stevsmit** [openshift/openshift-docs#64763]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.13/web_console/dynamic-plugin/overview-dynamic-plugin.html

### What needs fixing?

It doesn't look like they reference PatternFly4 anymore on the [PatternFly website](https://www.patternfly.org/); it's just called "PatternFly" and the current version is 5. I

I suggest the following:

- Re-title "PatternFly 4 guidelines" to just "PatternFly guidelines"

- Update the first link (components) to this: https://www.patternfly.org/components/all-components

- Update the second link (accessibility) to this: https://www.patternfly.org/accessibility/accessibility-fundamentals

PR will need created off the `Main` branch and cherry-picked to versions 4.12, 4.13, and 4.14. 

### Additional information

This issue is duplicated from https://issues.redhat.com/browse/OCPBUGS-17838. If this issue is resolved here, we need to close that Jira as well.

**Comment by volantxs** [comment]
hey @stevsmit I modified the url links

**Comment by JoeAldinger** [comment]
Thanks for contributing @volantxs the docs have been updated and merged on 9.18.23.
