### ISSUE TITLE
Align openshift virt `Configuring a VM network interface section` across interface types

### ISSUE THREAD

**Issue by maiqueb** [openshift/openshift-docs#64771]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.14/virt/vm_networking/virt-connecting-vm-to-linux-bridge.html#virt-attaching-vm-secondary-network-cli_virt-connecting-vm-to-linux-bridge

### What needs fixing?
The specs provided for VMs shouldbe aligned; right now, in the linux bridge reference yaml the [multus network name](https://github.com/openshift/openshift-docs/blob/1a3be1e4f3819ddd6f652fab7d7d66f040609c3d/modules/virt-attaching-vm-secondary-network-cli.adoc?plain=1#L41) appears with a namespace reference, while the [sriov reference yaml](https://github.com/openshift/openshift-docs/blob/1a3be1e4f3819ddd6f652fab7d7d66f040609c3d/modules/virt-attaching-vm-to-sriov-network.adoc?plain=1#L34) does not.

These should be aligned.

In [this other PR](https://github.com/openshift/openshift-docs/pull/64435/files#r1325652982) - where a 3rd interface type is added - it was suggested to remove the namespace reference.

**Comment by apinnick** [comment]
Tracked by CNV-33018
