### ISSUE TITLE
"Configuring Docker Storage" needs clarification

### ISSUE THREAD

**Issue by adellape** [openshift/openshift-docs#649]
The "Configuring Docker Storage" instructions about **docker-storage-setup** need clarification:

https://docs.openshift.com/enterprise/3.0/admin_guide/install/prerequisites.html#host-preparation

They should mention clearly that option *a.* will fail if the system doesn't have unpartitioned space available. Or, it may work and not give them as much space as they actually need.

An example of someone who had to debug this: 

http://unpoucode.blogspot.com.es/2015/06/docker-and-devicemappers-thinpool-in.html

We should clearly state that if option *a.* doesn't do the right thing for you that you will need to use option *c.* which may mean adding a new volume to your VM.

cc @brenton

**Comment by brenton** [comment]
@mpbarrett, this is the thing we discussed.

**Comment by danjeffries1** [comment]
Not only does this section need to be dramatically expanded and explained better, it needs to be considered and detailed in the "Pre-Reqs" section when people are setting up machines beyond just a simple note.  

Something like this would work in the Pre-Reqs section:

CRITICAL NOTE:  If you wish to use Docker Storage, which provides XYZ benefit, you will need to construct your virtual or bare metal system with an extra disk or additional unformatted free space.  This will require altering the default partitioning of the machine like so:  

- explanation of steps
- screen shot, screen shot, screen shot.

If you build a VM with no free space or no extra partition then you come to a very hard stop in that section, at which point you have to go back and either resize the LV or add another disk to the VM.  If you are working with bare metal this may even require a rebuild of the machine.
