### ISSUE TITLE
missing link: architecture/core_concepts/index

### ISSUE THREAD

**Issue by jiri-fiala** [openshift/openshift-docs#6491]
The [architecture/core_concepts index page](https://github.com/openshift/openshift-docs/blob/master/architecture/core_concepts/index.adoc) links nonexistent document in the *"Routes"* bullet point (`xref:routes.adoc#architecture-core-concepts-routes[Routes]`).

**Comment by tmorriso-rh** [comment]
Related issue opened here: https://github.com/openshift/openshift-docs/issues/7162

**Comment by tmorriso-rh** [comment]
The correct link is https://docs.openshift.com/container-platform/3.7/architecture/networking/routes.html. I will create a PR to change the link.

**Comment by tmorriso-rh** [comment]
Work in progress: https://github.com/openshift/openshift-docs/pull/7420
