### ISSUE TITLE
Update to match text. 

### ISSUE THREAD

**Issue by dstockdreher** [openshift/openshift-docs#6494]
In the Network Policy Section for the 3.6 enterprise docs. 

The following: 

Only allow HTTP and HTTPS traffic based on pod labels

To enable only HTTP and HTTPS access to the pods with a specific label (role=frontend in following example), add a NetworkPolicy object similar to:

kind: NetworkPolicy
apiVersion: extensions/v1beta1
metadata:
  name: allow-http-and-https
spec:
  podSelector:
  ingress:
  - ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443

I believe needs to also have the PodSelector have the matchLabels: role:frontend 

like the master branch has. as follows. 

kind: NetworkPolicy
apiVersion: extensions/v1beta1
metadata:
  name: allow-http-and-https
spec:
  podSelector:
    matchLabels:
      role: frontend
  ingress:
  - ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443

**Comment by bfallonf** [comment]
Thanks @dstockdreher 

Looks like this was submitted (and QE'd) via #6127 and the change never made it to the 3.6 docs. It is in all other versions 3.6 ->.

I've fixed this directly in the 3.6 branch and you can see the change here:

https://github.com/openshift/openshift-docs/blame/enterprise-3.6/admin_guide/managing_networking.adoc#L1062
