### ISSUE TITLE
diagram for authorization policy

### ISSUE THREAD

**Issue by sosiouxme** [openshift/openshift-docs#652]
A diagram would be really helpful here: https://docs.openshift.org/latest/architecture/additional_concepts/authorization.html

I made this one a while back. I think it's still fairly accurate.
[RH internal] https://docs.google.com/a/redhat.com/drawings/d/1s6Zcuil_1BfhKEtV5KYuAC5C6sGLi-4YNHRnLfHA498/edit?usp=sharing

Someone with some actual graphical skills could make something presentable of it :)

**Comment by adellape** [comment]
Moved to BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1271391
