### ISSUE TITLE
Broken link and title with typo, Chapter 09: schedoler

### ISSUE THREAD

**Issue by sborenst** [openshift/openshift-docs#653]
https://access.redhat.com/beta/documentation/en/openshift-enterprise-30-administrator-guide/chapter-9-schedoler

When using the Multi page view of the administration manual chapter 9 is spelled "schedoler" and the link points to an empty url, the url with the correct spelling (https://access.redhat.com/beta/documentation/en/openshift-enterprise-30-administrator-guide/chapter-9-scheduler) does exist.

**Comment by adellape** [comment]
Related BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1235899

**Comment by adellape** [comment]
Closing in favor of https://github.com/openshift/openshift-docs/issues/661.
