### ISSUE TITLE
Update Windows 2019 reference in Creating a Windows machine set on AWS 

### ISSUE THREAD

**Issue by mburke5678** [openshift/openshift-docs#65324]
Update the example command in Creating a Windows machine set on AWS  to remove a Windows 2019 reference. [Based on Slack thread](https://redhat-internal.slack.com/archives/CM4ERHBJS/p1695781488883589). 

### Which section(s) is the issue in?

[Creating a Windows machine set on AWS ](https://docs.openshift.com/container-platform/4.13/windows_containers/creating_windows_machinesets/creating-windows-machineset-aws.html)

### What needs fixing?

The `aws ec2 describe-images --region <aws region name> --filters "Name=name,Values=Windows_Server-2019*English*Full*Containers*" "Name=is-public,Values=true" --query "reverse(sort_by(Images, &CreationDate))[*].{name: Name, id: ImageId}" --output table` query in the Prereqs needs updating. The `Windows_Server-2019*English*Full*Containers*` string is no longer valid. 

enterprise-4.11+

PR: https://github.com/openshift/openshift-docs/pull/65600

**Comment by jrvaldes** [comment]
> Use the following aws command to query valid AMI images

I lean toward removing this section from the `Prerequisites` and/or stating it is just a sample command to list AWS images after looking at the [supported version of Windows Server](https://docs.openshift.com/container-platform/4.13/windows_containers/understanding-windows-container-workloads.html#wmco-prerequisites-supported-8.0.1_understanding-windows-container-workloads)
