### ISSUE TITLE
installation fails if we do not pass image option for docker registry

### ISSUE THREAD

**Issue by jkaurredhat** [openshift/openshift-docs#655]
When installing docker registry we should pass an additional option as below or else the installation will fail:

oadm registry --service-account=registry \
    --config=admin.kubeconfig \
    --credentials=openshift-registry.kubeconfig \
    --mount-host=<path> \
    --images='openshift3/ose-${component}:v3.0.0.0'

The error we see is "Tag v3.0.0.0 not found in repository registry.access.redhat.com/openshift3_beta/ose-docker-registry"

**Comment by adellape** [comment]
I'm assuming you're using OSE, correct? Can you verify which site/build of the docs you were viewing? This was fixed last week for the docs.openshift.com build[1]:

```
$ oadm registry --config=/etc/openshift/master/admin.kubeconfig \
    --credentials=/etc/openshift/master/openshift-registry.kubeconfig \
    --images='registry.access.redhat.com/openshift3/ose-${component}:${version}' 
```

[1] https://docs.openshift.com/enterprise/3.0/admin_guide/install/docker_registry.html#deploy-registry

The update still needs to be published for the Customer Portal build, however:

https://access.redhat.com/beta/documentation/en/openshift-enterprise-30-administrator-guide#deploy-registry

It should be getting an update soon. cc @vikram-redhat 

As for the Origin docs[2] on docs.openshift.org, the `--images` option is conditionalized to only appear in the OSE version of the docs, as the correct image is pulled by default for Origin:

https://gist.github.com/adellape/06f2a07ebc38c47c15ec

[2] https://docs.openshift.org/latest/admin_guide/install/docker_registry.html#deploy-registry

**Comment by adellape** [comment]
https://github.com/openshift/openshift-docs/pull/631/files#diff-c6ce4ea78a93cd1fe91eb65490918f2e had the OSE fix, FTR.

**Comment by sosiouxme** [comment]
People should not be hardcoding the version except as a workaround for a situation like this. Normally the version of the openshift binary should have correspondingly-tagged images available. Do we need to document doing this as a workaround, and how it's normally supposed to work? Otherwise it's not a docs bug...

BTW @jkaurredhat the GA is out, shouldn't be doing beta any more :)

**Comment by sosiouxme** [comment]
Oh, I missed that the customer portal is still wrong.

**Comment by adellape** [comment]
:sob:

**Comment by adellape** [comment]
The Customer Portal build has been updated to also now include the required `--images` option, so closing this Issue:

https://access.redhat.com/beta/documentation/en/openshift-enterprise-30-administrator-guide#deploy-registry

Note: The problems with the wacky callouts and invisible footnote numbers are a known issue and being addressed elsewhere.
