### ISSUE TITLE
Wrong flag to install Logging

### ISSUE THREAD

**Issue by wkulhanek** [openshift/openshift-docs#6558]
The advanced install documentation says to install logging this flag needs to be set:
openshift_metrics_install_logging=false

However according to the openshift-ansible repo the correct flag is this:

openshift_logging_install_logging=True

Location: https://github.com/openshift/openshift-docs/blob/master/install_config/install/advanced_install.adoc#advanced-install-cluster-logging

**Comment by jboxman** [comment]
@wkulhanek, thanks for reporting this. It looks like this was resolved in 2238956c4ae372c674963e938dce726e8f00b979 and d40264f4f2279b3e1dffb8351e252b4bfd25723a.
