### ISSUE TITLE
"N00b is now able to prune images" in OCP 3.7 release notes

### ISSUE THREAD

**Issue by e-minguez** [openshift/openshift-docs#6563]
I think this is a mistake right?

https://docs.openshift.com/container-platform/3.7/release_notes/ocp_3_7_release_notes.html#ocp-37-bug-fixes -> search for "N00b"

**Comment by miminar** [comment]
I'm not a native speaker, but I find the description accurate :smile:

**Comment by bparees** [comment]
@openshift/team-documentation we need to get this fixed.......

**Comment by bmcelvee** [comment]
Thanks! On it.

**Comment by bmcelvee** [comment]
Tracking changes in https://github.com/openshift/openshift-docs/pull/6565.
