### ISSUE TITLE
Typo "the the"

### ISSUE THREAD

**Issue by bergerhoffer** [openshift/openshift-docs#65938]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.13/networking/network_observability/understanding-network-observability-operator.html#network-observability-architecture_nw-network-observability-operator

### What needs fixing?

> Cluster-admins can view the the data in the web console.

Duplicate "the the"

**Comment by JoeAldinger** [comment]
@newfmum you want to work on this one?

**Comment by newfmum** [comment]
Sure!

**Comment by stevsmit** [comment]
Closed. Good job & thanks for contributing @newfmum
