### ISSUE TITLE
The haproxy.router.openshift.io/disable_cookies annotation needs quotations

### ISSUE THREAD

**Issue by stevsmit** [openshift/openshift-docs#65943]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.13/networking/routes/route-configuration.html

### What needs fixing?
The annotation `haproxy.router.openshift.io/disable_cookies`

must include quotations. For example: 

`"haproxy.router.openshift.io/disable_cookies:'true'"`

This issue will require QE approval. 

This will need merge to 4.11, 4.12, 4.13, and 4.14 branches. 

### Jira associated ticket

Upon merge of this issue, the following Jira ticket must be closed: https://issues.redhat.com/browse/OSDOCS-2301

**Comment by JoeAldinger** [comment]
@newfmum

**Comment by newfmum** [comment]
sure

**Comment by rolfedh** [comment]
The only reference to this annotation I found, in `modules/nw-route-specific-annotations.adoc`,  already specifies that the value must be inclosed in straight single-quotes.
```
|`haproxy.router.openshift.io/disable_cookies`| Disables the use of cookies to track related connections. If set to `'true'` or `'TRUE'`, the balance algorithm is used to choose which back-end serves connections for each incoming HTTP request. |
```
I think we can close this issue.

Also see: https://docs.openshift.com/container-platform/4.9/networking/routes/route-configuration.html#nw-route-specific-annotations_route-configuration
