### ISSUE TITLE
Breadcrumb Links in Official Docs Are Messed Up

### ISSUE THREAD

**Issue by joefern1** [openshift/openshift-docs#660]
When I am here:

https://access.redhat.com/beta/documentation/en/openshift-enterprise-30-administrator-guide/chapter-1-installation

And the breadcrumb links are:  
Products & Services > Documentation > OpenShift Enterprise 3.0 Administrators Guide > Chapter 1. Installation

And then I click the links for: OpenShift Enterprise 3.0 Administrators Guide 

It takes me back to:  https://access.redhat.com/

Instead it should take me to:  
https://access.redhat.com/beta/documentation/en/openshift-enterprise-30-administrator-guide/administrator-guide

Also there is no link to get back to the listing of all the OpenShift Enterprise Guides:
https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/

So if I realize I am in the wrong guide for OpenShift Enterprise, there is not an easy way to see what other guides I should have clicked on instead.

**Comment by danjeffries1** [comment]
I don't think this link is correct:  https://access.redhat.com/beta/documentation/en/openshift-enterprise-30-administrator-guide/administrator-guide   PLease note the /beta/ in the URL.  Is there another link for the GA docs?

**Comment by vikram-redhat** [comment]
Hey Dan. That link, with the beta is correct, for the time being.

**Comment by adellape** [comment]
The "beta" in the URL is unrelated to the release (GA vs Beta) of OSE. It's related to the newer build system for these AsciiDoc-based books on the Customer Portal (vs the DocBook-based OSE v2 books that we maintained in an internal CCMS).

@vikram-redhat Do we have a BZ for the breadcrumb issue cited here? That seems like a Portal issue vs an issue in our doc source.

**Comment by adellape** [comment]
"beta" has been dropped for the URLs as of yesterday's Customer Portal update, via:

https://projects.engineering.redhat.com/browse/CPDRUPAL-438

Existing URLs with "beta" redirect.

The breadcrumb issue still exists. Reported it to the CP Drupal team; JIRA filed here:

https://projects.engineering.redhat.com/browse/CPDRUPAL-501

cc @vikram-redhat

**Comment by adellape** [comment]
> Also there is no link to get back to the listing of all the OpenShift Enterprise Guides:
> https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/

@joefern1 Opened an RFE w/ the CP Drupal team for the above remaining issue:

https://projects.engineering.redhat.com/browse/CPDRUPAL-502

**Comment by tpoitras** [comment]
Breadcrumb issue fixed in https://projects.engineering.redhat.com/browse/CPDRUPAL-501

The "link back to product doc set" issue remains to be fixed in https://projects.engineering.redhat.com/browse/CPDRUPAL-502

This is not a docs issue, so closing this
