### ISSUE TITLE
Unable to render ditaa diagram in Minishift when its image is available 

### ISSUE THREAD

**Issue by budhram** [openshift/openshift-docs#6604]
It seems that when the ditaa digram image is available in an `images` folder on the folder containing `.adoc` file with ditaa syntax, the image is unable to render in openshift-docs.

See http://artifacts.ci.centos.org/minishift/minishift/docs/ondemand/minishift-master/openshift-origin/latest/minishift/using/basic-usage.html#basic-usage-overview.

**Steps to reproduce**
```
# Clone openshift-docs repo
$ git clone https://github.com/openshift/openshift-docs

$ cd openshift-docs && mkdir minishift

$ wget http://artifacts.ci.centos.org/minishift/minishift/docs/ondemand/minishift-master/minishift-adoc.tar

$ tar -xvf minishift-adoc.tar --strip 1

$ ls using/    # Note  'images' folder
addons.adoc  basic-usage.adoc  docker-daemon.adoc  experimental-features.adoc  host-folders.adoc  image-caching.adoc  images  index.adoc  profiles.adoc  variables.adoc

$ cat _topic_map.yml >> ../_topic_map.yml

$ cd ..

$ rake clean build

# Open following link in browser
$ google-chrome _preview/openshift-origin/latest/minishift/using/basic-usage.html

# Check 'Overview' section
``` 

Above steps are documented at [Minishift doc Integration with docs.openshift.org](https://docs.openshift.org/latest/minishift/contributing/writing-docs.html#integration-with-docs-openshift-org).

#### NOTE : We are now generating the tarball without having `images` folder which is generated as part of ditaa image generation. The issue is created to report the behavior and curious to know the reason of it.

**Comment by vikram-redhat** [comment]
Not an OpenShift docs issue. Closing.
