### ISSUE TITLE
Configuring a secret for the Image Registry Operator

### ISSUE THREAD

**Issue by stevsmit** [openshift/openshift-docs#66044]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.13/registry/configuring_registry_storage/configuring-registry-storage-openstack-user-infrastructure.html#registry-operator-config-resources-secret-openstack_configuring-registry-storage-openstack-user-infrastructure

### What needs fixing?
Replace REGISTRY_STORAGE_SWIFT_USER with REGISTRY_STORAGE_SWIFT_USERNAME

### Branches
Cherry pick to 4.11, 4.12, 4.13, and 4.14. 

### Associated Jira ticket
https://issues.redhat.com/browse/OCPBUGS-20294

**Comment by aniketgoyal51** [comment]
Hi @JoeAldinger , I would like to work on this issue, could you please assign this to me?

**Comment by aniketgoyal51** [comment]
Hi @stevsmit, I would like to work on this issue, could you please assign this to me?

**Comment by newfmum** [comment]
yes, please

**Comment by rolfedh** [comment]
Hi @JoeAldinger. It looks like this issue doesn't have a PR. Do you mind if I take it on?
