### ISSUE TITLE
Scheduler chapter has no content

### ISSUE THREAD

**Issue by joefern1** [openshift/openshift-docs#661]
When I am in the Adminstrator Guide:
https://access.redhat.com/beta/documentation/en/openshift-enterprise-30-administrator-guide/administrator-guide

And I click the link for Chapter 9. Scheduler in the left-hand pane.  It takes me here:

https://access.redhat.com/beta/documentation/en/openshift-enterprise-30-administrator-guide/chapter-9-schedoler

Which is an empty page.   The reason is that the link above has the word "scheduler" mispelled as "schedoler".  If I manually fix it - I get to the right place:

https://access.redhat.com/beta/documentation/en/openshift-enterprise-30-administrator-guide/chapter-9-scheduler

**Comment by CowboysFan** [comment]
@joefern1 This is apparently a bug in the Drupal system used for the portal docs. I believe this will be fixed in the next release, which is scheduled to be out soon.

**Comment by adellape** [comment]
The Customer Portal OSE doc builds were updated this morning and this issue still exists:

https://access.redhat.com/beta/documentation/en/openshift-enterprise-30-administrator-guide/administrator-guide

xref for the related BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1235899

**Comment by joefern1** [comment]
This is because scheduler was misspelled as "schedoler" in the doc and nav. If you fixed the url manually to the right spelling you will find the content.

**Comment by adellape** [comment]
This Drupal bug is has been fixed in https://projects.engineering.redhat.com/browse/CPDRUPAL-288. Fix is awaiting release.

**Comment by adellape** [comment]
Customer Portal Drupal's release 113 went live last night, which fixed this issue:

https://access.redhat.com/documentation/en/openshift-enterprise/version-3.0/openshift-enterprise-30-administrator-guide/administrator-guide
