### ISSUE TITLE
OpenShift Enterprise Logging Aggregation Recommends Elasticsearch

### ISSUE THREAD

**Issue by joefern1** [openshift/openshift-docs#662]
When I am in:   CHAPTER 7. AGGREGATING CONTAINER LOGS

https://access.redhat.com/beta/documentation/en/openshift-enterprise-30-administrator-guide/chapter-7-aggregating-container-logs

It recommends 2 ways for Admins to aggregate logs: 

1. Using a centralized file system
2. Using Elasticsearch

The using Elasticsearch option is probably ambitious.  It is referencing a community Fabric8 image for Elasticsearch that we aren't shipping or supporting yet:

image: "fabric8/elasticsearch-k8s:1.5.2"

You should check with Mike B and John K - but I think the documentation should state that this option is community supported only.  We are working to get this capability fully supported in a future release with official Elasticsearch images.

**Comment by adellape** [comment]
Fixed via https://github.com/openshift/openshift-docs/pull/724. Will appear in the OSE builds in the next rebase/publish.
