### ISSUE TITLE
Pruning Resources chapter lacks context

### ISSUE THREAD

**Issue by joefern1** [openshift/openshift-docs#663]
I am in CHAPTER 8. PRUNING RESOURCES:
https://access.redhat.com/beta/documentation/en/openshift-enterprise-30-administrator-guide/chapter-8-pruning-resources

All the Overview says is this:

8.1. OVERVIEW
This topic provides information on CLI operations and syntax to prune old resources from the server that accumulate over periods of use, but are no longer needed.

It lacks very basic context that should be mandatory like:

-What is a resource?
-Where do they accumulate on the server?
-Why would I want to prune them?

Please add some context into this Overview or else it is not very useful.

**Comment by CowboysFan** [comment]
@joefern1 I think this may be an issue with some of the other topics as well, and we'll definitely work to address this throughout our docs.
