### ISSUE TITLE
Getting Started guide is not useful

### ISSUE THREAD

**Issue by joefern1** [openshift/openshift-docs#664]
The Getting Started guide is not particularly useful:
https://access.redhat.com/beta/documentation/en/openshift-enterprise-30-getting-started/getting-started

What is the goal of this?  It literally provides 3 paragraphs of text split into 3 chapters.  All of that text is redundant and better gotten elsewhere.

Can we hide this Guide until there is more content to show here?   Is there a plan for what would ultimately land here or should we remove it completely?

**Comment by CowboysFan** [comment]
Indeed, I think I had brought this up a bit earlier. The Getting Started has to lead to something that customers can do from that doc. In this case we're pointing people to content that's located somewhere else. 

@joefern1 Here's the plan to get this fixed:

Getting Started experience for the developer:
*Access an OpenShift instance
*Create/build an app with the most easiest and convenient method
*Deploy it 

This would be good if it follows a typical application lifecycle as we

**Comment by adellape** [comment]
I would love to hide the Getting Started topics in the OSE builds for now, til they are actually useful (esp if we don't have an ETA on that).

Note that these topics are conditionalized between OSE and Origin, some more heavily than others. For example, the Getting Started for Admins in the Origin build has actual content:

https://docs.openshift.org/latest/getting_started/administrators.html

**Comment by tpoitras** [comment]
There have been improvements to the getting started topics, with more to come. See: https://docs.openshift.com/enterprise/3.0/getting_started/overview.html

initial issue solved, watch for more content for the 3.1 release
