### ISSUE TITLE
clarify how the sync plugin handles configmap slave pod definitions

### ISSUE THREAD

**Issue by bparees** [openshift/openshift-docs#6664]
Two things need to be clarified when using the configmap mechanism to define jenkins slave pods:

1) that you should not edit the slave definition in jenkins (any changes you make will be overridden by the configmap on the next sync)

2) that you can update the slave definition by modifying the configmap content (which will trigger an update of the jenkins slave definition).

**Comment by codrinbucur** [comment]
Thanks for this!
