### ISSUE TITLE
Minor link errors on Basic CLI Operations page

### ISSUE THREAD

**Issue by thrasher-redhat** [openshift/openshift-docs#6703]
There are a few links on the [basic CLI operations](https://docs.openshift.com/online/cli_reference/basic_cli_operations.html) page that seem to be slightly incorrect (though they resolve).

* https://docs.openshift.com/online/dev_guide/secrets.html#dev-guide-secrets
* https://docs.openshift.com/online/dev_guide/pod_autoscaling.html#dev-guide-pod-autoscaling
* https://docs.openshift.com/online/dev_guide/port_forwarding.html#dev-guide-port-forwarding

Both of these links do not have sections for `#dev-guide-topic` - and as such simple resolve to the top of the page.  The section links should be removed or fixed depending on the intended target - but since the links go to the correct page, this is very minor.

**Comment by thrasher-redhat** [comment]
@ahardin-rh FYI

**Comment by ahardin-rh** [comment]
@thrasher-redhat Thanks! Those targets are the IDs at the top of the page, so these are actually pointing to the correct place. The way our docs are structured, we can't have internal links with naked IDs so when we're pointing to whole topics, we point to the top-of-page ID.
