### ISSUE TITLE
Quickstart Guide

### ISSUE THREAD

**Issue by munchee13** [openshift/openshift-docs#671]
I created a flow for a quick start guide -- may be helpful.

https://docs.google.com/a/redhat.com/document/d/1rZa-42q2bpTiXXkZnTdmIjjrn3kFMJSmC7OeKkYyusY/edit?usp=sharing

**Comment by CowboysFan** [comment]
@munchee13 Thanks for sharing this. We'll definitely use this in our rework of the Getting Started content.

**Comment by adellape** [comment]
Related work is ongoing in https://bugzilla.redhat.com/show_bug.cgi?id=1243629. Closing issue and linking to it in the BZ.
