### ISSUE TITLE
F5 integration docs

### ISSUE THREAD

**Issue by pweil-** [openshift/openshift-docs#672]
We'd like to provide links to additional integration examples in the route core concepts guide even if they are just high level overviews.  Having a second integration example will help authors understand how to use some of the capabilities at a generic level outside of what the template router uses.

@Miciah - would you make a simple write up of the F5 integration?  It can follow the pattern of the template router example in https://docs.openshift.org/latest/architecture/core_concepts/routes.html which shows data flow and connection points between OpenShift and the router.

**Comment by adellape** [comment]
This work was completed:

https://docs.openshift.com/enterprise/3.0/architecture/core_concepts/routes.html#f5-router
