### ISSUE TITLE
Confusing note about nodejs versions

### ISSUE THREAD

**Issue by thrasher-redhat** [openshift/openshift-docs#6724]
https://docs.openshift.com/online/using_images/s2i_images/nodejs.html#nodejs-versions

This sections says:

> Currently, OpenShift Online provides versions 0.10, 4, and 6 of Node.js.

Which is then immediately followed by an important notice box:

> In OpenShift Online v3, version 0.10 is deprecated and no longer available to use.

This is confusing.  It seems to imply that nodejs 0.10 is provided by Openshift Online v2, and that this documentation applies to v2 as well.  If 0.10 is depreciated and no longer available, shouldn't it simply be removed from the first line?

**Comment by thrasher-redhat** [comment]
@ahardin-rh FYI

**Comment by ahardin-rh** [comment]
Addressed in https://github.com/openshift/openshift-docs/pull/6822
