### ISSUE TITLE
Advanced Installation logging variable incorrect

### ISSUE THREAD

**Issue by spadgett** [openshift/openshift-docs#6726]
The logging variable documented here looks incorrect.

https://docs.openshift.org/latest/install_config/install/advanced_install.html#advanced-install-cluster-logging

This is documented:

```
openshift_metrics_install_logging=false
```

but I believe it should be

```
openshift_logging_install_logging=false
```

cc @ahardin-rh @jcantrill

**Comment by spadgett** [comment]
@jcantrill Is it really true by default?

https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_logging/defaults/main.yml#L10

**Comment by vikram-redhat** [comment]
I can't find this issue anymore. I am going to close this. Please reopen if it is still a problem.
