### ISSUE TITLE
Ensure Hostname is Set Correctly Early in the Install to Avoid Pain and Suffering

### ISSUE THREAD

**Issue by danjeffries1** [openshift/openshift-docs#675]
I think more detail is required to help people avoid trouble if they are pointing to outside dns server or have incorrectly setup FQDN on their master and nodes.  I have written up the following from my own notes.

- Disable network manager

systemctl stop NetworkManager; systemctl disable NetworkManager

- Edit the hosts file on the server(s), using the master server as an example

vi /etc/hosts

- Please note that the FQDN MUST COME FIRST after the IPv4 address or hostname -f will not resolve correctly
- In this example we assume you are using a 192.168.10.x network and that you have assigned the IP 192.168.10.10 to the master server

192.168.10.10     ose-node-1.example.com ose-node-1
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

- Assuming node 1 has a .11 address, node 1 would look like the following:
192.168.10.11     ose-node-1.example.com ose-node-1
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

- Set the hostname of the machine:
hostnamectl set-hostname ose-master-1.example.com

- Restart networking

systemctl restart network

- OR

/etc/init.d/network restart

- make sure that `hostname -f` resolves correctly

hostname -f

- This should return the following:

ose-master-1.example.com  

- Please note that it must resolve to the FQDN and not simply the hostname

- If the hostname does not resolve correctly and you receive an error like "name or service not known" be sure you are pointing to the correct local DNS servers instead of external servers.  

- DO NOT PROCEED UNTIL YOU HAVE hostname -f correctly resolving or install of OSE3 WILL FAIL

**Comment by adellape** [comment]
Adding this to the BZ about enhancing the DNS information in the Prereqs topic, so that they're addressed together: 

https://bugzilla.redhat.com/show_bug.cgi?id=1271400
