### ISSUE TITLE
Minor link errors on  'using images' pages

### ISSUE THREAD

**Issue by thrasher-redhat** [openshift/openshift-docs#6754]
https://docs.openshift.com/online/using_images/s2i_images/customizing_s2i_images.html

At the end of this page, there is a link to "use `exec` for invoking it":

> https://docs.openshift.com/online/creating_images/guidelines.html#general-docker-guidelines

The "general-docker-guidelines" section doesn't exist.  It should perhaps be to:

https://docs.openshift.com/online/creating_images/guidelines.html#general-container-image-guidelines

**Comment by thrasher-redhat** [comment]
@ahardin-rh FYI

**Comment by thrasher-redhat** [comment]
Adding on to this, the first link under https://docs.openshift.com/online/using_images/db_images/mysql.html#creating-a-database-service-from-a-template has a link to:

https://docs.openshift.com/online/dev_guide/templates.html#dev-guide-templates

Where the dev-guide-templates section doesn't exist.

**Comment by thrasher-redhat** [comment]
On the [mongodb page](https://docs.openshift.com/online/using_images/db_images/mongodb.html#creating-a-database-service-from-a-template) the 'template' and 'instructions' links both link to the missing section:

https://docs.openshift.com/online/dev_guide/templates.html#dev-guide-templates

Likewise, the 'template' link in [this section](https://docs.openshift.com/online/using_images/db_images/mongodb.html#using-mongodb-replication) also points to the same missing section.

**Comment by thrasher-redhat** [comment]
On the [mariadb page](https://docs.openshift.com/online/using_images/db_images/mariadb.html#creating-database-service-from-template), the 'template' and 'instructions' links both link to the same page:

https://docs.openshift.com/online/dev_guide/templates.html#dev-guide-templates

**Comment by thrasher-redhat** [comment]
On the [jenkins images page](https://docs.openshift.com/online/using_images/other_images/jenkins.html#jenkins-creating-jenkins-service-from-template), the 'template' and 'instantiate' links both point to the same incorrect section:

https://docs.openshift.com/online/dev_guide/templates.html#dev-guide-templates

**Comment by ahardin-rh** [comment]
Issue addressed in https://github.com/openshift/openshift-docs/pull/6822
