### ISSUE TITLE
Warnings present in Origin docs missing in Online docs

### ISSUE THREAD

**Issue by lancejjohnson** [openshift/openshift-docs#6764]
The Pods section in "pods and containers" of the online docs is missing the two warnings that are present in the Origin docs.

Compare: 

* [Online](https://docs.openshift.com/online/architecture/core_concepts/pods_and_services.html#pods)
* [Origin](https://docs.openshift.org/latest/architecture/core_concepts/pods_and_services.html)

Origin has these warnings:

* > The recommended maximum number of pods per OpenShift Origin node host is 110.
* > Bare pods that are not managed by a replication controller will be not rescheduled upon node disruption.

@ahardin-rh

**Comment by ahardin-rh** [comment]
Addressed in https://github.com/openshift/openshift-docs/pull/6822
