### ISSUE TITLE
Incomplete sentence in Projects section of Online documentation

### ISSUE THREAD

**Issue by lancejjohnson** [openshift/openshift-docs#6765]
The third to last sentence in the [Projects section of the Online docs](https://docs.openshift.com/online/architecture/core_concepts/projects_and_users.html#projects) is incomplete. It states:

> Cluster administrators can also allow developers to create

The comparable sentence in the same section of the Origin docs has:

>  Cluster administrators can also allow developers to create their own projects.

The link in the Origin documentation does not have a corresponding section in the Online documentation (that I could find anyway), so my guess is the incomplete sentence should be deleted. 

@ahardin-rh

**Comment by ahardin-rh** [comment]
Addressed in https://github.com/openshift/openshift-docs/pull/6822
