### ISSUE TITLE
MongoDB link error

### ISSUE THREAD

**Issue by thrasher-redhat** [openshift/openshift-docs#6779]
In table 2 under the [environment variables](https://docs.openshift.com/online/using_images/db_images/mongodb.html#environment-variables) section, the link for `MONGODB_TEXT_SEARCH_ENABLED` is incorrect.  This link currently points to the mongodb v2.6 Text Indices page, however this variable is only available in v2.4.  The link should be updated to the one below:

https://docs.mongodb.com/v2.4/core/index-text/#text-search-text-command

**Comment by thrasher-redhat** [comment]
@ahardin-rh FYI

**Comment by ahardin-rh** [comment]
Fixed in https://github.com/openshift/openshift-docs/pull/6785
