### ISSUE TITLE
Explain project-level node selectors more explicitly

### ISSUE THREAD

**Issue by liggitt** [openshift/openshift-docs#678]
Administrators may want to limit which nodes a particular project can run pods on.

A node selector can be set as an annotation on a project/namespace, and pods within that project are restricted to that selector (in addition to any node selector on the pod itself).

A default node selector can be set in the master config file under the "projectConfig" stanza. For example:
```
projectConfig:
  defaultNodeSelector: "type=user-node,zone=east"
  ...
```

It can also be set on a project-by-project basis by an administrator, when creating a project. For example:
```
oadm new-project test --node-selector='type=user-node,zone=east'
```

**Comment by bfallonf** [comment]
I've already started a BZ on this. I'll add this issue to that to track it:

https://bugzilla.redhat.com/show_bug.cgi?id=1253125
