### ISSUE TITLE
Authorization may not want to include cluster role info

### ISSUE THREAD

**Issue by damemi** [openshift/openshift-docs#6781]
On https://docs.openshift.com/online/architecture/additional_concepts/authorization.html there is some info about cluster roles and cluster admins, which are probably not relevant to online users

@ahardin-rh

**Comment by ahardin-rh** [comment]
@damemi What sections specifically?

**Comment by damemi** [comment]
@ahardin-rh 
In Overview:
>This allows platform administrators to use the cluster policy to control who has various access levels to the OpenShift Online platform itself and all projects.

and

> Cluster administrators can visualize rules, roles, and bindings For example, consider the following excerpt from viewing a policy, showing rule sets for the admin and basic-user default roles:

(that sentence is also missing a period)

In Roles:
> Cluster administrators can visualize these roles, including a matrix of the verbs and resources each are associated using the CLI to Additional system: roles are listed as well, which are used for various OpenShift Online system and component operations.

There is also a section on the differences between cluster policy and local policy.

All of this information *could* be helpful for online users to understand the difference between local and cluster access, and help with the information flow of the doc, but I don't think an online user will ever be a cluster administrator. So if we only want info that is strictly related to OpenShift Online then this page should probably be rewritten to remove cluster admin info

**Comment by ahardin-rh** [comment]
@damemi Thanks! This is now addressed in https://github.com/openshift/openshift-docs/pull/6851
