### ISSUE TITLE
Broken link on Persistent Storage docs

### ISSUE THREAD

**Issue by damemi** [openshift/openshift-docs#6783]
https://docs.openshift.com/online/architecture/additional_concepts/storage.html contains 2 links to https://github.com/kubernetes/kubernetes/blob/master/docs/design/resources.md, which does not exist

@ahardin-rh

**Comment by ahardin-rh** [comment]
Note to self: This does not seem to exist on master, so will have to fix directly in the Online branch 🔍

**Comment by ahardin-rh** [comment]
Addressed in https://github.com/openshift/openshift-docs/pull/6865
