### ISSUE TITLE
Basic Walkthrough - Scaling Issue

### ISSUE THREAD

**Issue by jamiejackson** [openshift/openshift-docs#6786]
https://docs.openshift.com/online/getting_started/basic_walkthrough.html#bw-scaling-the-app

> OpenShift Online Stater users are unable to scale applications. Only OpenShift Online Pro users have this ability.*

> The nodejs-mongodb-example Quickstart is configured to use 512 MiB of memory per pod. Your quota will allow up to 3 replicas of the nodejs-mongodb-example pod in addition to the MongoDB database (for a total of 2 GiB).

Which is it? This is confusing to a noob. Should I be able to scale the up to 3 replicas as a free tier user? (Because I can't seem to.)

\* Note `Stater` typo, too.

**Comment by ahardin-rh** [comment]
@jamiejackson Thanks for this! 

@markturansky @tiwillia can you please offer guidance on how I should update the docs? Thanks!

**Comment by jamiejackson** [comment]
Now that I understand a little bit more about things, I think the documentation makes sense (except for the `Stater` typo :-)

If you were to want to make it crystal clear, though, it could change from:

>Your quota will allow up to 3 replicas of the nodejs-mongodb-example pod in addition to the MongoDB database (for a total of 2 GiB).`

to:

>Your OpenShift Online Pro quota will allow up to 3 replicas of the nodejs-mongodb-example pod in addition to the MongoDB database (for a total of 2 GiB).

**Comment by ahardin-rh** [comment]
@jamiejackson Thank you! This is now addressed in https://github.com/openshift/openshift-docs/pull/6866
