### ISSUE TITLE
Add "Working with HTTP Proxies" section to Administrator Guide's Installation section

### ISSUE THREAD

**Issue by trevorquinn** [openshift/openshift-docs#679]
We ran into issues with a corporate HTTP proxy in a OSE 3 installation. It would be nice to move the "Working with HTTP Proxies" discussion that was in the [Beta 4 documents](https://github.com/openshift/training/blob/master/beta-4-setup.md#appendix---working-with-http-proxies) into the Installation section of the Administrator Guide. 

This way, people will be able to add `HTTP_PROXY` env vars to the `/etc/sysconfig/openshift-master` file before running into the problems that may result from their absence.

**Comment by codificat** [comment]
Raised this request also as [RHBZ 1243740](https://bugzilla.redhat.com/show_bug.cgi?id=1243740).

**Comment by bfallonf** [comment]
This is currently being worked on and the work can be found here: #1057
