### ISSUE TITLE
unify cgroups docs for okd 4.14 and ocp 4.14

### ISSUE THREAD

**Issue by ibotty** [openshift/openshift-docs#67953]
### Which section(s) is the issue in?

https://docs.okd.io/latest/nodes/clusters/nodes-cluster-cgroups-okd.html

### What needs fixing?

Apparently the docs were split because previously OKD defaulted to cgroupsv2 while OCP defaulted to cgroupsv1.

Now that's harmonized the docs should be unified again.

See discussion in <https://github.com/okd-project/okd/issues/1310#issuecomment-1812736974>.

Also the OCP page https://docs.openshift.com/container-platform/4.14/nodes/clusters/nodes-cluster-cgroups-2.html seems to have a typo re cgroupsv1 and cgroupsv2, they are the other way around.

**Comment by mburke5678** [comment]
Jira ticket: https://issues.redhat.com/browse/OCPBUGS-26932
PR: https://github.com/openshift/openshift-docs/pull/70086

**Comment by mburke5678** [comment]
Changes are live: 
Post install -> Cluster tasks -> [Configuring Linux cgroup](https://docs.okd.io/latest/post_installation_configuration/cluster-tasks.html#nodes-clusters-cgroups-2_post-install-cluster-tasks)
Nodes -> Working with clusters -> [Configuring the Linux cgroup version on your nodes](https://docs.okd.io/latest/nodes/clusters/nodes-cluster-cgroups-2.html)
