### ISSUE TITLE
Example quickstart URL should not be a link

### ISSUE THREAD

**Issue by sallyom** [openshift/openshift-docs#6806]
@ahardin-rh

At the bottome of this file: 
https://github.com/openshift/openshift-docs/blob/master/dev_guide/migrating_applications/quickstart_examples.adoc  
There's an example quickstart link that should not be active: 

`If no SOURCE_REPOSITORY_URL is specified, the template will use the template URL (https://github.com/openshift/<quickstart>-ex) listed above as the source repository, and a hello-welcome application will be started. `

**Comment by ahardin-rh** [comment]
Addressed in https://github.com/openshift/openshift-docs/pull/6822
