### ISSUE TITLE
Broken link on dev_tutorials/ruby_on_rails.html

### ISSUE THREAD

**Issue by sallyom** [openshift/openshift-docs#6807]
https://docs.openshift.com/online/dev_guide/dev_tutorials/ruby_on_rails.html
The link for `Creating the Database Service` in the section: https://docs.openshift.com/online/dev_guide/dev_tutorials/ruby_on_rails.html#creating-the-frontend-service
is broken.  `app_tutorials` should be `dev_tutorials`

@ahardin-rh

**Comment by ahardin-rh** [comment]
Addressed in https://github.com/openshift/openshift-docs/pull/6822
