### ISSUE TITLE
Broken links in dev_tutorials/maven_tutorial.html

### ISSUE THREAD

**Issue by sallyom** [openshift/openshift-docs#6808]
The link in this section:
https://docs.openshift.com/online/dev_guide/dev_tutorials/maven_tutorial.html#nexus-introduction
for `edit the pod template` is broken.

The links in this section:
https://docs.openshift.com/online/dev_guide/dev_tutorials/maven_tutorial.html#nexus-connecting-to-nexus should not be active links? 
`http://<Nexus ` and `http://nexus:8081`

@ahardin-rh

**Comment by ahardin-rh** [comment]
Addressed in https://github.com/openshift/openshift-docs/pull/6822
