### ISSUE TITLE
oc login should not be performed as a root user

### ISSUE THREAD

**Issue by jkaurredhat** [openshift/openshift-docs#682]
When you preform oc login as root user it is possible to damage your root system user's OSE config.

Thereafter if anyone performs below commands and error is reported :

oc get pods
oc get nodes

The error is 

User "system:anonymous" cannot list pods in project "x"

or a forbidden error will be reported when doing admin tasks.

This should be pointed out in the documentation where oc login is mentioned.

To rectify it run as below 

oc config use-context default/master-example.com:8443/system:admin

**Comment by mfojtik** [comment]
@liggitt @csrwng can't we add check to `oc` commands to detect that they are running as root a print warning?

**Comment by liggitt** [comment]
> When you preform oc login as root user it is possible to damage your root system user's OSE config.

It shouldn't damage it, it just updates who you are logged in as. Did you run `oc login`, then `oc logout`, then start seeing the anonymous errors?

Your root credentials are still present, you just need to switch back to that context. This command shows you the contexts in your kubeconfig file:
```
oc config view -o template -t "{{range .contexts}}{{.name}}
{{end}}"
```

You can switch back to your cluster admin context with this command (with the context replaced with your actual cluster admin context):
```
default/10-10-10-123:8443/system:admin
```

> can't we add check to oc commands to detect that they are running as root a print warning?

I don't think that is a good idea

**Comment by liggitt** [comment]
@adellape I think we should just document how you switch back to a cluster-admin user using the command above

**Comment by thom-at-redhat** [comment]
https://access.redhat.com/solutions/3019011#comments has some additional information/commands we use
