### ISSUE TITLE
[ OKD ] Version switcher doesn't work as expected

### ISSUE THREAD

**Issue by peterroth** [openshift/openshift-docs#68234]
### Which section(s) is the issue in?
In the OKD documentation if you switch version with the version chooser next to Documentation/OKD in the top, it pops up an error message even when the version you currently read exists in the version you want to switch to.
The error message comes from _javascripts/page-loader.js, line 51:
 `This page doesn't exist in version ${newVersion}. Click OK to search the ${newVersion} docs OR Cancel to stay on this page.`
This switcher works for OpenShift without problems.

### What needs fixing?
Choosing another version in OKD documentation pops up an error message that leads to Google.com

**Comment by aireilly** [comment]
Please verify the update on the production docs site in an hour or two.

**Comment by aireilly** [comment]
let's just reopen this then

**Comment by peterroth** [comment]
If I'm not mistaken, what I see is expected. In line 29, we set the condition, and if that is met, we load the code in line 30, where the fileRequested is welcome/index.html:
https://github.com/openshift/openshift-docs/blob/main/_javascripts/page-loader.js#L29-L30
While if the condition isn't met, we go to line 32 and 33, where we construct the requested version't link based on the current site we are on:
https://github.com/openshift/openshift-docs/blob/main/_javascripts/page-loader.js#L32-L33

I'm surely not a JS guru, tho.
What do you think, @aireilly?

**Comment by peterroth** [comment]
OK, I think I found the problem.
At [line 20](https://github.com/openshift/openshift-docs/blob/main/_javascripts/page-loader.js#L20) we are looking for the version in the 2nd field, separated with "/"; however, the links are the following:
OCP: https://docs.openshift.com/container-platform/4.13/welcome/index.html
OKD: https://docs.okd.io/4.13/welcome/index.html

In case of OKD, the 2nd field is "welcome".

**Comment by aireilly** [comment]
@peterroth Nice. Can you PR that change and we'll get this updated.

**Comment by peterroth** [comment]
Sure, @aireilly, I'm about to fix it; the PR will arrive probably tomorrow.

**Comment by peterroth** [comment]
I just checked and both sites, OCP and OKD work as expected; switching version loads the same site if exists.

**Comment by aireilly** [comment]
Thanks for the PRs @peterroth :)

**Comment by peterroth** [comment]
Happy to help, @aireilly :)
If you have time, could you check my other 2 open PRs in this repo, please? They stuck for about 2 months.
