### ISSUE TITLE
openshift/team-documentation doesn't exist

### ISSUE THREAD

**Issue by peterroth** [openshift/openshift-docs#68396]
### Which section(s) is the issue in?
In the Pull Request template, it is requested to tag the @openshift/team-documentation team after the PR is opened:
https://github.com/openshift/openshift-docs/blob/main/.github/pull_request_template.md?plain=1#L25
This team doesn't exist or cannot be tagged.

### What needs fixing?
Remove the non-existing team or add one that can be tagged.

**Comment by ahardin-rh** [comment]
Hello, I just tested this in a sample PR and the syntax worked for me. I was able to successfully tag the team as indicated.

**Comment by peterroth** [comment]
Thanks for testing it, @ahardin-rh. Is it possible people outside of the organization cannot tag them?
