### ISSUE TITLE
Which ports are need to be open in Openshift Environment

### ISSUE THREAD

**Issue by jkaurredhat** [openshift/openshift-docs#684]
There should be a section in administration guide to let the users know which ports should be open   between the openshift environment if there is a firewall  between broker and nodes

Say : master to node
         node to node
         master to master 
        external to master

**Comment by adellape** [comment]
(Internal) http://post-office.corp.redhat.com/archives/openshift-sme/2015-June/msg00543.html

**Comment by goern** [comment]
Cant we put an up to date (and keep it up to date) section in the online docs?

**Comment by adellape** [comment]
Closing in favor of https://bugzilla.redhat.com/show_bug.cgi?id=1270960.

cc @thoraxe
