### ISSUE TITLE
need port map for firewalls

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-docs#685]
I don't think there is currently a table for firewall ports and which directions they need to be open. For people not using the installer, they need to know how to configure this.

**Comment by nak3** [comment]
Same report is here: https://github.com/openshift/openshift-docs/issues/684

I personally think the manual installation guide like [v2's doc ](https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/html-single/Deployment_Guide/#chap-Manually_Installing_and_Configuring_a_Broker_Host) would be great.

**Comment by adellape** [comment]
Dupe of https://github.com/openshift/openshift-docs/issues/684
