### ISSUE TITLE
Add pre-reqs for the ose-installer to install section

### ISSUE THREAD

**Issue by danjeffries1** [openshift/openshift-docs#686]
This references section 1.3.3 found here: https://access.redhat.com/beta/documentation/en/openshift-enterprise-30-administrator-guide/chapter-1-installation

This command fails without some pre-reqs installed:

sh <(curl -s https://install.openshift.com/ose/)

Please add the following:  

Before running the script, Install pre-reqs

yum -y install python-virtualenv gcc

**Comment by bfallonf** [comment]
This was worked on in a previous PR created from a BZ: #753
