### ISSUE TITLE
typo in docs.redhat router

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-docs#687]
https://access.redhat.com/beta/documentation/en/openshift-enterprise-30-administrator-guide#deploying-a-router

```
NOTE
You can xref:../../admin_guide/high_availability.adoc#high-availability[set up a highly-available router] on your OpenShift cluster using IP failover.
```

I think that's supposed to be a link.

**Comment by adellape** [comment]
Fixed in:

https://access.redhat.com/beta/documentation/en/openshift-enterprise-30-administrator-guide#haproxy-router (see 1.6.2.1. High Availability)
