### ISSUE TITLE
install doc states wrong default identity provider

### ISSUE THREAD

**Issue by mhrivnak** [openshift/openshift-docs#6891]
The origin docs rendered here: https://docs.openshift.org/latest/install_config/configuring_authentication.html#install-config-configuring-authentication

... state "If you installed OpenShift Origin using the Advanced Installation method, the Allow All identity provider is used by default, which allows access for all user names and passwords.", which I believe is incorrect. Multiple other places state that the Advanced Installation defaults to the Deny All method.

It looks like there is some logic in the docs to reference either the "Quick" or "Advanced" installation method, and then give the corresponding default identity provider of "Allow All" or "Deny All". The logic appears to just be backwards.

Below is the incorrect excerpt from https://github.com/openshift/openshift-docs/blob/master/install_config/configuring_authentication.adoc#overview

```

If you installed {product-title} using
the
ifdef::openshift-enterprise[]
xref:../install_config/install/quick_install.adoc#install-config-install-quick-install[Quick Installation] or
endif::[]
xref:../install_config/install/advanced_install.adoc#install-config-install-advanced-install[Advanced Installation]
method, the
ifdef::openshift-enterprise[]
xref:DenyAllPasswordIdentityProvider[Deny All] identity provider is
used by default, which denies access for all user names and
passwords. To allow access, you must choose a different identity provider and
configure the master configuration file appropriately (located at
*_/etc/origin/master/master-config.yaml_* by default).
endif::[]
ifdef::openshift-origin[]
xref:AllowAllPasswordIdentityProvider[Allow All] identity provider is
used by default, which allows access for all user names and
passwords.
endif::[]
```

**Comment by vikram-redhat** [comment]
Origin is indeed AllowAll, while Enterprise is DenyAll. Closing this issue.
