### ISSUE TITLE
nw-ovn-ipsec-verification command correction

### ISSUE THREAD

**Issue by xerc** [openshift/openshift-docs#68977]
```
$ oc version
Client Version: 4.13.0-0.okd-2023-09-03-082426
Kustomize Version: v4.5.7
Server Version: 4.13.0-0.okd-2023-10-28-065448
Kubernetes Version: v1.26.4-3014+636f2be6157d45-dirty
```

https://github.com/openshift/openshift-docs/blob/2b0643103d5d3d7c10be7ed2e586a41db5165d08/modules/nw-ovn-ipsec-verification.adoc?plain=1#L35

> Error from server (BadRequest): container nbdb is not valid for pod ovnkube-node-<XXXXX>

remove ` -c nbdb`

> Defaulted container "ovn-controller" out of: ovn-controller, ovn-acl-logging, kube-rbac-proxy, kube-rbac-proxy-ovn-metrics, ovnkube-node

correct ` -c ovn-controller` OR ` -c ovnkube-node` ?

**Comment by ahardin-rh** [comment]
Closing in favor of https://issues.redhat.com/browse/OCPBUGS-30262; moved to OCPBUGS for better tracking
