### ISSUE TITLE
cleanup removed `EgressNetworkPolicy`

### ISSUE THREAD

**Issue by xerc** [openshift/openshift-docs#68981]
```
$ oc version
Client Version: 4.13.0-0.okd-2023-09-03-082426
Kustomize Version: v4.5.7
Server Version: 4.13.0-0.okd-2023-10-28-065448
Kubernetes Version: v1.26.4-3014+636f2be6157d45-dirty
```
`$ oc get EgressNetworkPolicy`
> error: the server doesn't have a resource type "EgressNetworkPolicy"

ref. https://github.com/search?q=repo%3Aopenshift%2Fopenshift-docs%20EgressNetworkPolicy&type=code

**Comment by ahardin-rh** [comment]
Thank you! Closing in favor of https://issues.redhat.com/browse/OCPBUGS-30261 for better tracking
