### ISSUE TITLE
fix link to `Creating a Restore CR` or rename file

### ISSUE THREAD

**Issue by xerc** [openshift/openshift-docs#69012]
@ https://docs.openshift.com/container-platform/4.14/backup_and_restore/index.html#backing-up-and-restoring-applications
"You restore application backups by creating a Restore (CR). See Creating a Restore CR"

BROKEN https://docs.openshift.com/container-platform/4.14/backup_and_restore/application_backup_and_restore/backing_up_and_restoring/oadp-creating-backup-cr-doc.html#backing-up-applications
WORKING https://docs.openshift.com/container-platform/4.14/backup_and_restore/application_backup_and_restore/backing_up_and_restoring/oadp-creating-backup-cr.html#backing-up-applications
```patch
-- -doc
```
btw/ did not make a PR cause there might be thoughts about naming
ref. https://github.com/search?q=repo%3Aopenshift%2Fopenshift-docs+-backup-cr&type=code

**Comment by RichardHoch** [comment]
@anarnold97 broken link in OADP doc.

**Comment by RichardHoch** [comment]
Link was fixed.
