### ISSUE TITLE
S2I assemble/run/etc. scripts should be documented in images section

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-docs#696]
Each image should have its script documented.

**Comment by bparees** [comment]
what sort of documentation are you looking for?

env variables the scripts consume?  general flow of how it assembles apps?

**Comment by thoraxe** [comment]
I think each builder needs documentation on:

1) what env vars and/or secrets can be used to influence the build and/or run process
2) documentation on any other files that can be placed in the repo to influence the build process or customize how the runtime is started (eg stuff for maven with Java-based builders)
3) a link to a place to download the assemble, run and/or other scripts for customization
4) back-links to the section on how the "environment" file works.

Does that sound good?

**Comment by bparees** [comment]
(1) is covered: https://docs.openshift.org/latest/using_images/s2i_images/ruby.html#configuration (I don't think we have any images that can be influenced by secrets currently, other than the EAP ones i guess)

not clear on (4)..where do you want to back link from/to?

**Comment by thoraxe** [comment]
I don't see the xpaas docs on docs.openshift so it's hard to do, but it looks like the EAP one, for example, doesn't match the format and is missing that table:

https://access.redhat.com/beta/documentation/en/openshift-enterprise-30-using-images#jboss-eap

I actually can't even find the docs on S2I that talk about the different files. Clicking on 

https://docs.openshift.org/latest/using_images/s2i_images/overview.html

Has no info, and then takes me to an architecture section:

https://docs.openshift.org/latest/architecture/core_concepts/builds_and_image_streams.html#source-build

Which also has no info.

The actual docs about the scripts and stuff are here:
https://docs.openshift.org/latest/creating_images/s2i.html#s2i-scripts

I think the tl;dr of it is that the "overview" section of the "using images" section should probably have a little bit more info on S2I and then link to both the arch and "creating images" sections for people that want to customize more deeply.

**Comment by adellape** [comment]
> I don't see the xpaas docs on docs.openshift

@thoraxe BTW, the xPaaS images are conditionalized to only appear in the OSE build on docs.openshift.com (not .org for the Origin build):

https://docs.openshift.com/enterprise/3.0/using_images/xpaas_images/overview.html (Overview needs filling out wrt context on what xPaaS is).

That OSE branch (i.e., https://github.com/openshift/openshift-docs/tree/enterprise-3.0) is then used to build the Customer Portal OSE docs.

**Comment by ahardin-rh** [comment]
I think this is an outdated issue, so I am closing it. If we need to do more here, we can open a docs BZ for better tracking.
