### ISSUE TITLE
Misrendering of doc

### ISSUE THREAD

**Issue by lpsantil** [openshift/openshift-docs#6979]
It looks like some carriage returns got introduced into some of the lists, starting at Scaled Registry.

See
https://docs.openshift.com/container-platform/3.6/scaling_performance/optimizing_storage.html#application-storage-recommendations
https://docs.openshift.com/container-platform/3.7/scaling_performance/optimizing_storage.html#application-storage-recommendations
https://docs.openshift.com/container-platform/latest/scaling_performance/optimizing_storage.html#application-storage-recommendations

**Comment by ahardin-rh** [comment]
@lpsantil Thanks!

@tmorriso-rh I think you were creating the PRs to address this? If not, let me know and I will create the fixes.

**Comment by tmorriso-rh** [comment]
@ahardin-rh Yes, this is the email that I sent you. Here is the PR that I created: 

https://github.com/openshift/openshift-docs/pull/6747

PTAL. Thanks!

**Comment by tmorriso-rh** [comment]
https://github.com/openshift/openshift-docs/pull/7030

Changes made, waiting for the weekly released to be published.

**Comment by tmorriso-rh** [comment]
These changes are now available.
