### ISSUE TITLE
Please add section on how to add SSL certificates to your application

### ISSUE THREAD

**Issue by mpbarrett** [openshift/openshift-docs#699]
https://github.com/jboss-openshift/application-templates
The "HTTPS configuration" section.

And then the https://github.com/jboss-openshift/application-templates/tree/master/secrets for examples on how to insert the CERT into the json.

Here are the necessary steps:
1) Create service account for EAP:
  create following json file (name it eap-sa.json):
{
    "kind": "ServiceAccount",
    "apiVersion": "v1",
    "metadata": {
        "name": "eap-service-account"
    }
}
oc create -f eap-sa.json

2) Generate keystore (example of generating self-signed certificate):
keytool -genkey -keyalg RSA -alias selfsigned -keystore keystore.jks -storepass password -validity 360 -keysize 2048
(answer the first question with full address of service, e.g. test.namespace.cloudapps.example.com)

3) Create secret from keystore:
oc secrets new eap-secret keystore.jks

4) Add secret to service account:
oc secrets add serviceaccounts/deployer secrets/eap-secret

5) Create application from template (e.g. eap6-basic-sti). Make sure following variables are set:
APPLICATION_HOSTNAME (whatever you set to keystore)
EAP_HTTPS_SECRET=eap-secret (whatever you named your secret)
EAP_HTTPS_KEYSTORE=keystore.jks (whatever you named the keysotre)
EAP_HTTPS_NAME=selfsigned (whatever alias you set when creating certificate)
EAP_HTTPS_PASSWORD=password (whatever you set when creating keystore)

There are a few things to be aware of:
- service account has to be named 'eap-service-account', otherwise DeploymentConfig must be updated
- there must be same password for certificate private key and for keystore (limitation of EAP)
- bold names can be changed, but the subsequent variables and commands have to be modified accordingly.

**Comment by vikram-redhat** [comment]
@lucascosti  - can you please look at this and let me know if we included this in the xPaaS docs for EAP/JWS?

**Comment by lucascosti** [comment]
No, the xPaaS docs I did were very basic, no specific use case like this for SSL was included.

**Comment by vikram-redhat** [comment]
Thanks @lucascosti . @CowboysFan - do you see a use case for this in xPaaS docs?

**Comment by adellape** [comment]
IIRC, most of those templates won't fully deploy OOTB unless something like the described procedure is performed. From https://github.com/jboss-openshift/application-templates:

"The majority of templates contain configuration that requires the creation of resources within your project to support HTTPS, specifically a service account and a secret that can be included into the pod as a volume."

The ones that don't require this procedure:

"The following templates can be used without creating a service account or a secret: eap/eap6-basic-sti.json, webserver/jws-tomcat7-basic-sti.json and webserver/jws-tomcat8-basic-sti.json."

For the templates that do require it, if you don't create the SA and secret, when you try to deploy the app you'll get stuck in a state like this (note the Warnings at the end of the output):

https://gist.github.com/adellape/8f4828f16773327886c8

The described steps should set you straight. Once the SA and secret are created, deployments complete as expected. I think there's one typo in the above steps tho:

```
oc secrets add serviceaccounts/deployer secrets/eap-secret
```

If you're following the above example, I believe that step should be:

```
oc secrets add serviceaccounts/eap-service-account secrets/eap-secret
```

Also, the default secret name in the template is "eap-app-secret" (versus "eap-secret" in the example steps), but it's not really a typo, so long as the secret name matches what was entered for EAP_HTTPS_SECRET during app creation.

**Comment by vikram-redhat** [comment]
Closing this issue as this is over 3 years old.
