### ISSUE TITLE
OKD: documentation mentions EUS channel and update, but that doesn't exist

### ISSUE THREAD

**Issue by peterroth** [openshift/openshift-docs#70054]
### Which section(s) is the issue in?
I found references to eus-to-eus updates in OKD documentation here:
https://docs.okd.io/4.13/updating/updating-cluster-cli.html
However, the Extended Update Support is available only for OCP, not for OKD.

### What needs fixing?
Remove every reference for EUS updates in OKD documentation.

**Comment by peterroth** [comment]
I checked the code but can't find where the OCP and OKD docs diverge, where can it be removed.

**Comment by mburke5678** [comment]
Changes are live. For example, the procedure now has OKD output in Step 1: [Updating a cluster by using the CLI](https://docs.okd.io/latest/updating/updating_a_cluster/updating-cluster-cli.html#update-upgrading-cli_updating-cluster-cli)

**Comment by mburke5678** [comment]
@peterroth Thanks for the tip. Feel free to let me know if I missed anything.

**Comment by peterroth** [comment]
Thanks @mburke5678 .
I noticed a remaining eus-* mention is on [Updating a cluster by using the CLI](https://docs.okd.io/latest/updating/updating_a_cluster/updating-cluster-cli.html#update-upgrading-cli_updating-cluster-cli), at step 4, "After the update completes, you can confirm that the cluster version has updated to the new version:" in the example output.
Other than that, I found the **About EUS-to-EUS updates** title on the [Updating OKD virtualization](https://docs.okd.io/4.14/virt/updating/upgrading-virt.html#virt-about-eus-updates_upgrading-virt) page.
