### ISSUE TITLE
document getting a token using openshift-challenging-client 

### ISSUE THREAD

**Issue by akostadinov** [openshift/openshift-docs#707]
I could find no documentation about obtaining a token using the openshift-challenging-client [1][2]. Thanks to @liggitt who enlightened me about that, here's how to do with curl:

```
curl -u joe -kv -H "X-CSRF-Token: xxx" 'https://master.cluster.local:8443/oauth/authorize?client_id=openshift-challenging-client&response_type=token'
```

Then response is `302`:

```
Enter host password for user 'joe':
*   Trying ::1...
* Connected to localhost (::1) port 8888 (#0)
* Establish HTTP proxy tunnel to master.cluster.local:8443
* Server auth using Basic with user 'joe'
> CONNECT master.cluster.local:8443 HTTP/1.1
> Host: master.cluster.local:8443
> User-Agent: curl/7.40.0
> Proxy-Connection: Keep-Alive
> X-CSRF-Token: xxx
> 
< HTTP/1.0 200 Connection established
< Proxy-agent: tinyproxy/1.8.3
< 
* Proxy replied OK to CONNECT request
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* NSS: client certificate not found (nickname not specified)
* SSL connection using TLS_RSA_WITH_AES_128_CBC_SHA
* Server certificate:
*   subject: CN=kubernetes.default.svc.cluster.local
*   start date: Jun 21 23:42:15 2015 GMT
*   expire date: Jun 20 23:42:16 2016 GMT
*   common name: kubernetes.default.svc.cluster.local
*   issuer: CN=openshift-signer@1434930132
* Server auth using Basic with user 'joe'
> GET /oauth/authorize?client_id=openshift-challenging-client&response_type=token HTTP/1.1
> Authorization: Basic am9lOnJlZGhhdA==
> User-Agent: curl/7.40.0
> Host: master.cluster.local:8443
> Accept: */*
> X-CSRF-Token: xxx
> 
< HTTP/1.1 302 Found
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Expires: Fri, 01 Jan 1990 00:00:00 GMT
< Location: https://master.cluster.local:8443/oauth/token/display#access_token=VO4dAgNGLnX5MGYu_wXau8au2Rw0QAqnwq8AtrLkMfU&expires_in=86400&token_type=bearer
< Pragma: no-cache
< Set-Cookie: ssn=MTQzNjM3NzI4NXxDSkxSTl8yb0ZjUmZaSDZwNG51UjNDZEx1M29xRldQNGtGZTMwbnhfYlNRV2FuVmYxVHlKSWhWazVKWjR2RDc3X056ZVpqZXl6VWN4T0Nqc1dyX01raDhiUlNSdXFpdkhDalAwWDQzNWdyWExlTmNTUURjN3pQeW9HT1RpVmRtQ1JBPT18qi62Db0PolIHaMmAjtdKPejhCGRY-EUEruT6W_Du2bg=; Path=/; Expires=Wed, 08 Jul 2015 18:41:25 UTC; Max-Age=3600; HttpOnly; Secure
< Date: Wed, 08 Jul 2015 17:41:25 GMT
< Content-Length: 0
< Content-Type: text/plain; charset=utf-8
< 
* Connection #0 to host localhost left intact
```

Keys here are:
- use `client_id=openshift-challenging-client`, otherwise `400 Bad Request` is returned
- use `response_type=token`
- set  `X-CSRF-Token` to some non-empty value, otherwise error is returned
- actual token is returned in the `Location` header of the `302` response per the OAuth spec as `access_token=VO4dAgNGLnX5MGYu_wXau8au2Rw0QAqnwq8AtrLkMfU`

Cheers.

[1] https://docs.openshift.org/latest/architecture/additional_concepts/authentication.html#api-authentication
[2] https://docs.openshift.org/latest/architecture/additional_concepts/authentication.html#oauth

**Comment by rjhowe** [comment]
To clean this up a little: 

curl -u ryan:ryan -kI 'https://master.cluster.local:8443/oauth/authorize?client_id=openshift-challenging-client&response_type=token' |  grep  -oP "access_token=\K[^&]*"

**Comment by liggitt** [comment]
Not sure we want to promote this method of getting tokens... the doc at https://docs.openshift.org/latest/architecture/additional_concepts/authentication.html#oauth gives a better indication of the cases a token requestor should handle

**Comment by akostadinov** [comment]
If you want to create an API client for some reason, current doc is not enough to know how exactly to obtain the token using user/password.

**Comment by liggitt** [comment]
You cannot assume a username/password via basic auth will be sufficient. Some auth providers do not support basic auth. Others will only support Kerberos/negotiate auth.

**Comment by akostadinov** [comment]
Ok, then document for each standard provider? User/pass basic auth would be a common use case, no? Also `curl` does support GSSAPI/kerberos auth as far as I know. So it should be possible to obtain in a similar way.

**Comment by liggitt** [comment]
Gssapi/Kerberos would be done with the request header provider, where the auth challenge is completely up to the auth proxy. Google, Github, and OpenID providers don't support obtaining an API token via a WWW-Authenticate challenge. I'm just hesitant to document steps that will often work, but should not be depended on to work in all installations.

**Comment by akostadinov** [comment]
I think that documenting how some type of configuration works is worthy. There might be a separate doc page, how it works and explanation that other configurations do not work like that. Why not document a valid supported product feature? It doesn't have to imply this configuration is the only one or recommended.

**Comment by pbrumblay** [comment]
I found this post to be helpful in figuring out how to build client application. +1 for documentation.

**Comment by akostadinov** [comment]
@pbrumblay , FYI you can do `oc --verbose=8 ...` and you can see all HTTP requests done by `oc` command. This helps to understand and implement any operations supported by the cli client.

**Comment by nii236** [comment]
What happened to `--verbose`? It is no longer available in the `oc` command.

**Comment by liggitt** [comment]
--loglevel=8 or --v=8

**Comment by mzanini** [comment]
+1 for documentation, I am trying to figure out how to obtain a token without the need to use `oc` command line tool. Using `--loglevel=10` I can see the API calls that are made by `oc` but it is still difficult for me to make sense of the parameters and reverse engineer this. Any suggestion/links I can look at in the meantime?

**Comment by akostadinov** [comment]
@mzanini, read issue description. It's all there.

**Comment by mzanini** [comment]
You are right that works! Guess I was tricked by the fact that `oc login` makes so many HTTP calls!

**Comment by ayusho** [comment]
When i run this command, it says something like this

* Protocol "'https" not supported or disabled in libcurl
* Closing connection -1
curl: (1) Protocol "'https" not supported or disabled in libcurl
'response_type' is not recognized as an internal or external command,
operable program or batch file.

but when oc login --loglevel=9, it makes a couple of curl commands, one of the is what you @akostadinov  suggested but with more parameters like redirect_url, code_challenge, code_challenge_method.

**Comment by akostadinov** [comment]
@ayusho , you must be using some strange `curl` distribution. That's why you see this. `oc` is not using curl internally, just outputs curl-like info. wrt it setting more parameters, I trust you that it does. What I listed above is the minimum parameters required. More of them may or may not hurt. It still works for me.

**Comment by vikram-redhat** [comment]
@gaurav-nelson - PTAL.
This issue is still relevant and the first post contains the how-to. We should add this to our documentation. This also seems like a great use case.

**Comment by vikram-redhat** [comment]
@gaurav-nelson bump

**Comment by nyanloutre** [comment]
Hi, it doesn't seems to work on Openshift 3.10+

Any update ?

**Comment by avinashkumar1289** [comment]
This command doesn't work on my mac ..But it does work on ubuntu machine.

```
curl -u user:password -kv 'https://console.okd.example.com:8443/oauth/authorize?client_id=openshift-challenging-client&response_type=token' -skv -H "X-CSRF-Token: xxx" --stderr - |  grep -oP "access_token=\K[^&]*"

grep: invalid option -- P
```
