### ISSUE TITLE
Document maximum name lengths for objects

### ISSUE THREAD

**Issue by adellape** [openshift/openshift-docs#709]
We should document the maximum name lengths for various object types (projects, services, routes, etc).

Notes:

> Miciah> alexd: We should document them because they're very limiting.
alexd> Miciah: how bout in their related arch topics, as callouts for "name" in their object definitions (e.g. https://docs.openshift.com/enterprise/3.0/architecture/core_concepts/pods_and_services.html#services and https://docs.openshift.com/enterprise/3.0/architecture/core_concepts/routes.html#route-types)
Miciah> alexd: That would be helpful, but I think it would be especially helpful to have a list of all these limits in one place because people are hitting these limits in templates that define a project names and then interpolate a project name into a service name or similar.
Miciah> alexd: So you change the project name and bam, your service name is wrong.
Miciah> s/wrong/invalid/
alexd> Miciah: would aggregating the limits in a topic about templates be a good spot? in addition to the individual limits in their related arch topics
Miciah> alexd: Yes, I think so.

cc @Miciah

**Comment by vikram-redhat** [comment]
Closing this as I have created a BZ to track work for this: https://bugzilla.redhat.com/show_bug.cgi?id=1271414
