### ISSUE TITLE
AllowedRegistriesForImport format is undocumented

### ISSUE THREAD

**Issue by bparees** [openshift/openshift-docs#7123]
It's mentioned here:
https://docs.openshift.org/latest/install_config/master_node_configuration.html#master-config-image-policy-config

But no example or discussion is provided to help people understand how to actually craft a proper definition of allowed registries.  They have to go to the api to understand it:
https://github.com/openshift/origin/blob/00c65897e60f396b716b68011d691f5c0675a4c0/pkg/cmd/server/api/v1/types.go#L425-L437

@miminar since you're working on this logic anyway, can you add some appropriate doc?
It should probably be added either in this section:
https://docs.openshift.org/latest/admin_guide/image_policy.html

or as a peer to that same section.

/cc @bmcelvee

**Comment by miminar** [comment]
Will be resolved by #7788
