### ISSUE TITLE
Tyfo in Admin Guide doc

### ISSUE THREAD

**Issue by plse** [openshift/openshift-docs#717]
1.5. Deploying a Docker Registry
1.5.1. Overview

To enable this, OpenShift provides an internal, integrated Docker registry to can be deployed in your OpenShift environment to manage images "locally". 
=> "to can be deployed" need to be re-written

**Comment by adellape** [comment]
@plse Thanks for catching it. This will be fixes in the Origin nightly docs and the next re-publish of the OSE docs.
