### ISSUE TITLE
Add documentation about all the config options in master-config.yaml and node-config.yaml

### ISSUE THREAD

**Issue by csrwng** [openshift/openshift-docs#722]
https://docs.openshift.org/latest/admin_guide/master_node_configuration.html has a sample config, but not very much explaining what each setting is for. Ideally it would be generated from the comments in code.

**Comment by tpoitras** [comment]
@csrwng : I don't know how to find the comments in the code. Can you please provide a link to this content? :question:

**Comment by csrwng** [comment]
@tpoitras Here is the v1 type for config which contains comments about the individual fields: https://github.com/openshift/origin/blob/master/pkg/cmd/server/api/v1/types.go

@deads2k - besides the type definition is there additional doc that @tpoitras can look at?

**Comment by deads2k** [comment]
> @deads2k - besides the type definition is there additional doc that @tpoitras can look at?

I don't know of any.  @liggitt do you know of any?

**Comment by liggitt** [comment]
The type definitions are the most thorough description of the options we have...they're actually pretty good

**Comment by tpoitras** [comment]
I have been notified that @adellape has some ideas for this one, so I'm going to pass it to him. :+1: :rabbit:

**Comment by bfallonf** [comment]
Closing this issue in favour of #2866
