### ISSUE TITLE
Document basic manual cluster setup

### ISSUE THREAD

**Issue by liggitt** [openshift/openshift-docs#723]
I don't think the docs clearly explain how to manually set up a cluster. Not sure where that should be documented, but the steps would be something like this:
1. Start a master:
   
   ```
   $ openshift start master --master=https://$MASTER_HOST:8443
   ```
2. On the same machine as the master (in order to use the master's generated CA), generate a configuration for your node (replace with your node's hostname, and add any IP addresses or FQDN's you want the node's serving cert to be valid for):
   
   ```
   $ oadm create-node-config --node-dir=mynodeconfig --node=$NODE_HOST --hostnames=$NODE_HOST[,$NODE_FQDN_HOST,$NODE_IP,...] --master=https://$MASTER_HOST:8443 --dns-ip=$MASTER_IP
   ```
3. Take the generated directory to your node, and start your node:
   
   ```
   $ openshift start node --config=/path/to/mynodeconfig/node-config.yaml
   ```
   
   When you start your node, it should contact the master and register itself

**Comment by adellape** [comment]
These commands are doc'd individually in https://docs.openshift.com/container-platform/3.5/install_config/master_node_configuration.html, though not together as a single procedure. But I'm not sure that we need that given the documented (and for OCP, GSS-supported) installation methods we have currently?

Closing this for now but please reopen if needed.
