### ISSUE TITLE
Web console walkthrough out of date

### ISSUE THREAD

**Issue by spadgett** [openshift/openshift-docs#7254]
This topic was not updated for the new experience in 3.7.

https://docs.openshift.org/latest/getting_started/developers_console.html

cc @jwforres @ahardin-rh

**Comment by ahardin-rh** [comment]
WIP PR: https://github.com/openshift/openshift-docs/pull/7255

**Comment by ahardin-rh** [comment]
Closing, as this is now  outdated and the docs have since been updated and improved
