### ISSUE TITLE
Need more description about `LabelsPresence` predicate

### ISSUE THREAD

**Issue by nak3** [openshift/openshift-docs#727]
https://docs.openshift.com/enterprise/3.0/admin_guide/scheduler.html#configurable-predicates

> LabelsPresence checks whether a particular node has a certain label defined or not, regardless of its value.

Please add explanation about `presense` false or true. 
~~~
If "presence" is false, then returns false if any of the requested labels matches any of the minion's labels,
otherwise returns true.
If "presence" is true, then returns false if any of the requested labels does not match any of the minion's labels,
otherwise returns true.
~~~

I correct wrong example https://github.com/openshift/openshift-docs/pull/726

(Please refer)
https://github.com/openshift/origin/blob/v1.0.1/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/plugin/pkg/scheduler/algorithm/predicates/predicates.go#L213-L224

**Comment by tpoitras** [comment]
fixed in PR727

https://github.com/openshift/openshift-docs/pull/1072
