### ISSUE TITLE
Sync docs/cli with oadm command grouping

### ISSUE THREAD

**Issue by pravisankar** [openshift/openshift-docs#740]
Origin PR: https://github.com/openshift/origin/pull/3557
Changes:
  - Group commands in oadm for ease of use
  - Group oadm certificate related cmds under 'oadm ca'. 
    To maintain backward compatibility, old commands (oadm create-master-certs/create-key-pair/create-server-cert/create-signer-cert) still work with deprecated message but are not surfaced in the help message.

**Comment by adellape** [comment]
@pravisankar For OSE, this would be for 3.0.1?

**Comment by pravisankar** [comment]
https://github.com/openshift/origin/issues/3424 --> milestone 1.1.0
https://github.com/openshift/origin/issues/2461 --> milestone not set
@adellape #3557 is in the merge queue, so i'm hoping this is targeted for 3.0.1. 
@smarterclayton can you please confirm ^^

**Comment by smarterclayton** [comment]
Yes
