### ISSUE TITLE
Guide to Creating Templates

### ISSUE THREAD

**Issue by danjeffries1** [openshift/openshift-docs#748]
A comprehensive guide to creating templates for applications would be most welcome.  There is very little about the structure and necessary pieces of creating an application for Kubernetes/OpenShift out on the web, other than reverse engineering the sample templates that already exist.  

I would also welcome various "quick-start" templates so that folks can get started working on their own applications faster. 

At this point all information surrounding templates is around loading them into OpenShift, with very little if any on creating the actual templates themselves.

**Comment by CowboysFan** [comment]
@danjeffries1 Is this a direct request from a customer? I think addressing such specific use cases and customer requirements should be a priority for us. Can you provide any more details or information? I'd love to meet  up and collect some details to meet these requirements.

**Comment by danjeffries1** [comment]
Disney requested more info and we are talking with them in a few weeks for a deep dive.  

# Templates

Basically they would like to see the following:

- A breakdown of how the JSON templates are structured
- What do the various fields stand for
- Best practices/how-to construct new ones
- Debugging them
- Where the defaults templates live
- How to update the default how to add new ones
- Best practices for modifying the existing ones (bad idea? backup? cp to a new file and change the app name?)
- They would like to see examples of creating several applications both simple and complex
- Also they would like to see how they would take existing docker containers and collect them into a single application.  
- Lastly they would like to see how to create S2I based applications.  

# Custom Router Plugins

- They have also requested documentation on writing custom router plugins, with examples.  


All the best,

Daniel Jeffries
Red Hat Senior Solutions Architect
RHCE - #805010231554810
San Diego, California
619-955-7355  Office
415-816-4497  Cell

----- Original Message -----

**Comment by CowboysFan** [comment]
@danjeffries1 Thanks for that information, it's really helpful. Showing and end-to-end process of developing apps using various methods was already on my list of things I'd like to get documented, S2I being one of them.

I'll turn some of the other questions into use cases as well and see how best we can approach them.

**Comment by adellape** [comment]
A BZ was spawned for this and similar requests. Closing this Issue in favor of https://bugzilla.redhat.com/show_bug.cgi?id=1258291.
