### ISSUE TITLE
EgressNetworkPolicy is available with ovs-networkpolicy

### ISSUE THREAD

**Issue by danwinship** [openshift/openshift-docs#7488]
admin_guide/managing_networking.adoc, in the section "Using an Egress Firewall to Limit Access to External Resources" says:

> You must have the ovs-multitenant plugin enabled in order to limit pod access via egress policy.

But egress policy works with ovs-networkpolicy too. So either it should say "you must have ovs-multitenant or ovs-networkpolicy enabled", or it should say "it doesn't work with ovs-subnet".

**Comment by bfallonf** [comment]
Because there's a PR open for this, I'll close this issue. Thanks @danwinship
