### ISSUE TITLE
shouldn't need to remove NetworkManager

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-docs#749]
Removing Network Manager was done initially during early betas. This should not be required. It was only done to avoid some DNS/resolver issues, which can be easily solved by properly configuring Network Manager.

**Comment by adellape** [comment]
@rajatchopra Do you have a recommendation here? Wasn't clear if a conclusion came out of http://post-office.corp.redhat.com/archives/libra-devel/2015-July/msg00552.html.

The affected spot is "Managing Base Packages" in https://docs.openshift.com/enterprise/3.0/admin_guide/install/prerequisites.html#software-prerequisites.

**Comment by rajatchopra** [comment]
@adellape Remove the requirement. We have some datapoints that NetworkManager does not interfere with SDN anymore.

**Comment by nak3** [comment]
@adellape Could you please update the doc? We got the query about this requirement.
