### ISSUE TITLE
Instructions on SSL management using intermediate certs

### ISSUE THREAD

**Issue by ikke-t** [openshift/openshift-docs#7495]
Hi,

we are having customer stuck with SSL certificates. Our manual is not providing enough details to set that up. Use case would be "How do I set custom certificates into OCP cluster?" That then would divide into two different use cases: "How do I configure custom certs for API and Router" and "How do I configure custom certs using intermediate cert for API and Router".

In this case there is a HAproxy in front of APIs, in pass through SSL mode.

Our instructions here [certificate customization](https://docs.openshift.com/container-platform/3.7/install_config/certificate_customization.html) is too short. I was pointed to some other consultant made docs here for the issue, which should be included into official docs: [use-component-specific-custom-certificates](http://v1.uncontained.io/playbooks/installation/custom_certificates.html#option-2-configuring-openshift-to-use-component-specific-custom-certificates), of which the option 2 comes into question in this case.

Now even that is a bit short on description. While customer is using intermediate certs, there should be description how to create certfile and cafile options. This is the command:

```openshift_master_named_certificates=[{"certfile": "/path/to/console.ocp-c1.myorg.com.crt", "keyfile": "/path/to/console.ocp-c1.myorg.com.key", "names": ["console.ocp-c1.myorg.com"], "cafile": "/path/to/console.ocp-c1.myorg.com.ca.crt"}]```

Doc should describe the following files:
1. Root CA
2. one or more intermediate CA
3. host certificate

Now which of those files should be in which order put into certfile and cafile? This should be described. Also it should be described what openshift ansible does with the files. Where does it place them, so one can verify if they got fixed? Does it restart all the required services, and can one do the cert change without cluster downtime?

**Comment by vikram-redhat** [comment]
@ikke-t - brilliant. Thanks!

**Comment by vikram-redhat** [comment]
@mburke5678 - can you please take a look at this today?

**Comment by ikke-t** [comment]
Hi, I update this issue as I did quite a lot of learning and experiment on the issue. I try to summarise the use case of:

# How do I configure custom certs using intermediate cert for API and Router

The use case is for organisations who are buying intermediate certificate from their certificate authority. The intermediate certificate allows organisation to create themselves valid SSL certs for their web serving hosts, whatever SSL services they provide.

Note, for OpenShift you don't need intermediate certificate, but can use just regular host certificate. That's different use case.

To emulate the case quicker, I didn't buy a real intermediate CA, but instead created my private CA cert and used that to create trusted intermediate cert. With that intermediate cert I created host certificates for OCP master and OCP wildcard router. To create CA, intermediate cert and host certs, I used these very good instructions: https://jamielinux.com/docs/openssl-certificate-authority/introduction.html

Now I had a pre-installed OCP, which was already using self signed certificates which are created by default install. We want to keep it that way, so OpenShift uses internal self made CA to create cluster internal trust certs for different services, like kubernetes, logging, monitoring etc.

I also had the following files:

1.  Root CA certificate
1.1 Root CA key
2.  Intermediate CA certificate
2.1 Intermediate CA key
3.  OCP master host certificate
3.1 OCP master host key
4.  OCP router wildcard certificate 
4.  OCP router wildcard key 

For purpose of defining the certificates into ansible installers inventory file, I added this variables to force certificate change:

```openshift_master_overwrite_named_certificates=true```

# To define the master API public name certificate

```openshift_master_named_certificates=[{"names": ["master.148.251.233.173.nip.io"], "certfile": "/home/cloud-user/master-bundle.cert.pem", "keyfile": "/home/cloud-user/master.148.251.233.173.nip.io.key.pem" ]```

Note here, it is important to define the external client facing API name or names. It is the array variable "names". You can leave out cafile parameter here, as it actually does nothing in this case.

It's important to know what goes into that cert file. Normally defining SSL services, you have two certs defined separately in minimum: host cert, and CA cert. While defining this for OpenShift master API, we need to put all those files into the "certfile" in following order:

1. OCP master host certificate
2. Intermediate CA certificate
3. Root CA certificate

and "keyfile" contains OCP master host key.

With this setup, any SSL SNI connections coming to "names" address (master.148.251.233.173.nip.io) will be served with given master certificate, and will get provided by the CA chain for client.

# To define the wildcard router certificate

The wild card router is defined the following way in ansible inventory:

```openshift_hosted_router_certificate={"certfile": "/home/cloud-user/star-apps.148.251.233.173.nip.io.cert.pem", "keyfile": "/home/cloud-user/star-apps.148.251.233.173.nip.io.key.pem", "cafile": "/home/cloud-user/ca-chain.cert.pem"}```

In this case the files contain:

certfile contains OpenShift router wildcard certificate.

keyfile contains OpenShift router wildcard key

cafile:
2. Intermediate CA certificate
3. Root CA certificate

Now as there are new files introduced to OpenShift you need to run ansible configure to make it configure the OpenShift configure files. The cert files will end up into master's ```/etc/origin/master/named_certificates/``` directory.

```ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-cluster/config.yml```

Later if the certs expire or you want to change them for some reason, you can run:

```ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-cluster/redeploy-certificates.yml```

Note, for the above to work the cert names must not have changed, only content. If names changed, rerun the ansible config.

# Test the Certificates

Here are few ways you can verify the certs.

## Certificate report

First of all you can create a certificate report from OCP cluster:

```ansible-playbook -i /etc/ansible/hosts  /usr/share/ansible/openshift-ansible/playbooks/certificate_expiry/easy-mode.yaml```

This will create reports into /tmp.

Next you can verify from remote host that the certs verify correct using openssl s_client:

## For master public API

Change master address and name, and verify port:

```
$ openssl s_client   -CAfile certs/ca.cert.pem  -connect master.148.251.233.173.nip.io:8443 -servername master.148.251.233.173.nip.io |grep Verify
depth=2 C = FI, ST = Uusimaa, L = Helsinki, O = ITSE, OU = HQ, CN = ITSE root CA, emailAddress = ikke@iki.fi
verify return:1
depth=1 C = FI, ST = Uusimaa, O = ITSE, OU = branch office, CN = ITSE intermediate CA, emailAddress = ikke@iki.fi
verify return:1
depth=0 C = FI, ST = Uusimaa, L = Helsinki, O = ITSE, OU = branch office, CN = master.148.251.233.173.nip.io, emailAddress = ikke@iki.fi
verify return:1
    Verify return code: 0 (ok)
```

## For master interal API

Change master internal API port:
```
# openssl s_client -CAfile /etc/origin/master/master.server.crt -connect 127.0.0.1:8443|grep Verify
depth=1 CN = openshift-signer@1516734585
verify return:1
depth=0 CN = 172.30.0.1
verify return:1
    Verify return code: 0 (ok)
```


## For wildcard router
Change router address and name:

```
$ openssl s_client   -CAfile certs/ca.cert.pem  -connect master.148.251.233.173.nip.io:443 -servername apps.148.251.233.173.nip.io |grep Verify
depth=2 C = FI, ST = Uusimaa, L = Helsinki, O = ITSE, OU = HQ, CN = ITSE root CA, emailAddress = ikke@iki.fi
verify return:1
depth=1 C = FI, ST = Uusimaa, O = ITSE, OU = branch office, CN = ITSE intermediate CA, emailAddress = ikke@iki.fi
verify return:1
depth=0 C = FI, ST = Uusimaa, L = Helsinki, O = ITSE, OU = cloud, CN = *.apps.148.251.233.173.nip.io, emailAddress = ikke@iki.fi
verify return:1
    Verify return code: 0 (ok)
```

# How do I set custom certificates into OCP cluster?

Use case of using normal certs without intermediate would be about the same, except you drop the intermediate files. In both cases the root CA is likely not needed, as it should be found on your system in case of public certificate authority.

# More intstructions:
* http://v1.uncontained.io/playbooks/installation/custom_certificates.html
* https://docs.openshift.com/container-platform/latest/install_config/certificate_customization.html
* https://docs.openshift.com/container-platform/latest/admin_solutions/certificate_management.html

**Comment by vikram-redhat** [comment]
@sdodson - is @ikke-t summary of this issue correct from eng point of view?

**Comment by xltian** [comment]
@gpei  from QE will provide feedback here.

**Comment by gpei** [comment]
hi @ikke-t thanks for the detailed article about openshift_master_named_certificates and openshift_hosted_router_certificate usage. The ansible parameters setting and playbooks used looks good to me.
One thing I want to say is in upcoming ocp release - ocp-3.9, there will be a big change of the playbooks entry.
I list them here in case needed:

> ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-cluster/config.yml
> ->
> ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml
> ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml
> 

> ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-cluster/redeploy-certificates.yml
> ->
> ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/redeploy-certificates.yml
> 

> ansible-playbook -i /etc/ansible/hosts /usr/share/ansible/openshift-ansible/playbooks/certificate_expiry/easy-mode.yaml
> ->
> ansible-playbook -i /etc/ansible/hosts /usr/share/ansible/openshift-ansible/playbooks/openshift-checks/certificate_expiry/easy-mode.yaml
> 

Thanks
Gaoyun Pei  | OpenShift Cluster-Lifecycle QE

**Comment by sdodson** [comment]
> It's important to know what goes into that cert file. Normally defining SSL services, you have two certs defined separately in minimum: host cert, and CA cert. While defining this for OpenShift master API, we need to put all those files into the certfile in following order:
> 
> OpenShift master host certificate
> Intermediate CA certificate
> Root CA certificate
> and keyfile contains OpenShift master host key.

I'm not sure that's accurate. @abutcher to confirm? I believe it should be cafile = intermediate CA + Root CA, certfile = openshift master host certificate, keyfile = openshift master key.

After reviewing the following documentation I'd say the main things that aren't covered are 1) The appropriate steps to retrofit a named certificate into an environment post install. Then 2) How to handle intermediate certificates.

https://docs.openshift.com/container-platform/latest/install_config/certificate_customization.html
https://docs.openshift.com/container-platform/latest/install_config/install/advanced_install.html#advanced-install-custom-certificates

**Comment by ikke-t** [comment]
After my experiments, I don't see the ansible doing anything with the cafile contents while post-installing the certs. That's why I mentioned it not needed. Am I mistaken?

**Comment by abutcher** [comment]
> I'm not sure that's accurate. @abutcher to confirm? I believe it should be cafile = intermediate CA + Root CA, certfile = openshift master host certificate, keyfile = openshift master key.

@ikke-t is correct, the CA chain is not necessary in this case for named certificates so cafile can be omitted.

The named serving certificate or certfile must contain the intermediate CA certificate and may also contain the root CA certificate.

We also would want to use the OpenShift CA certificate as the -CAfile parameter when verifying the master's serving certificate. The OpenShift CA certificate is added to the system bundle so this command would likely return OK with anything if the master was a node (probably is).

```
# openssl s_client -CAfile /etc/origin/master/ca.crt -connect 127.0.0.1:8443|grep Verify
```

**Comment by ikke-t** [comment]
Now it's time to hunt the internal services who have set the old certs in the pod secrets. I just started fresh Jenkins pod with pipeline, and it can not connect to kube:

An exception occurred invoking a REST operation against the OpenShift master.  The operation will be retried.  Exception message "Exception trying to GET https://172.30.0.1/apis/servicecatalog.k8s.io/v1beta1 response code: 503".

@abutcher updated the caBundle field on apiservice/v1beta1.servicecatalog.k8s.ioBeyond to include the base64 encoded contents of /etc/origin/service-catalog/ca.crt then deleted the apiserver pod, when it was re-created it started up properly resolving the issue without re-running playbooks.

The instructions to do so are in here: https://bugzilla.redhat.com/show_bug.cgi?id=1523625#c37

> cat /etc/origin/service-catalog/ca.crt | base64
> oc edit apiservice/v1beta1.servicecatalog.k8s.io
> update ca_bundle field with the base64 encoded content from the first command
>

**Comment by vikram-redhat** [comment]
Thanks @ikke-t . Are we in a state that we can now update the docs with you earlier feedback or is there still some issues that need resolving?

cc: @aheslin @mburke5678

**Comment by ikke-t** [comment]
We should create an ansible or update easy-mode.yml that finds all cert secrets for all pods, and also prints out the subject line from those into report

And then either add new ansible or exist the redeploy-certificates.yml ansible to also change the required secrets from running deployments.

But as we don't have this yet, we could just add info to user to need to do this manually.

**Comment by ikke-t** [comment]
I've been building different pipelines and builds today into cluster, and it seems to work with no problems after the service-catalog cert change. I'd go with it.

**Comment by ikke-t** [comment]
I updated that into last chapter of the guide

**Comment by mburke5678** [comment]
@ikke-t The plan is to take your content above, titled _How do I configure custom certs using intermediate cert for API and Router_ and import this into the OpenShift docs? 
Which version of OpenShift is this material intended for? I see @gpei comment that the Ansible playbooks are different for 3.9. Is this the only difference between versions?

**Comment by ikke-t** [comment]
This is now tested on 3.7.

**Comment by mburke5678** [comment]
@vikram-redhat This BZ seems related.
https://bugzilla.redhat.com/show_bug.cgi?id=1485824

**Comment by mburke5678** [comment]
WIP PR:
https://github.com/openshift/openshift-docs/pull/7607

**Comment by sdodson** [comment]
In order to retrofit custom certificates into an existing cluster it's necessary to set `openshift_master_overwrite_named_certificates=true` and `openshift_master_named_certificates` as described by Ilkka. Then run `playbooks/byo/openshift-cluster/redeploy-master-certificates.yml`

In order to retrofit custom router certificates into an existing cluster it's necessary to set `openshift_hosted_router_certificate` as described above by Ilkka. Then run `playbooks/byo/openshift-cluster/redeploy-router-certificates.yml`

**Comment by mburke5678** [comment]
Making edits via https://github.com/openshift/openshift-docs/pull/7607

**Comment by jeffkight** [comment]
In https://docs.openshift.com/container-platform/3.11/install/configuring_inventory_file.html there is documentation for two variables:

openshift_master_ca_certificate | Provide the single certificate and key that signs the OpenShift Container Platform certificates. See Redeploying a New or Custom OpenShift Container Platform CA
-- | --
openshift_additional_ca | If the certificate for your openshift_master_ca_certificate parameter is signed by an intermediate certificate, provide the bundled certificate that contains the full chain of intermediate and root certificates for the CA. See Redeploying a New or Custom OpenShift Container Platform CA

Does this mean we can provide the intermediate CA cert and key to sign all Openshift 3.11 certs with our intermediate CA?
If so, what is the process?
Note, I have experimented with the obvious applications.
