### ISSUE TITLE
Router documentation is somewhat misleading

### ISSUE THREAD

**Issue by jsight** [openshift/openshift-docs#751]
Monitoring routers:

This states that it can be monitored on port 1936, but does not state that this port is not open by default.

Deploying routers:

There is a lot of information on creating routers. It would be nice if it documented how to list services and remove them.

"oc get svc" and "oc delete services <name>"

**Comment by vikram-redhat** [comment]
BZ create to track work: https://bugzilla.redhat.com/show_bug.cgi?id=1259566. Closing this issue.

**Comment by bfallonf** [comment]
@jsight I'm not too sure how "get"ing and "describe"ing works best here in the monitoring reouters section. It is documented quite well in the CLI reference topic [1]. Could you maybe point to the specific parts of the routing doc you'd like changed? 

Thanks!

https://docs.openshift.com/enterprise/3.0/cli_reference/basic_cli_operations.html#common-operations
