### ISSUE TITLE
Problem with RBAC when i deploy with Template Catalog

### ISSUE THREAD

**Issue by yeplaa** [openshift/openshift-docs#7527]
Hello,

I need to create a role, cluster role and service account in my Openshift Template.
My config is Openshift 3.6.
Below a part of my config template : 

  apiVersion: v1
  kind: Template
  metadata:
    name: prometheus
    annotations:
     description: "Prometheus"
     tags: "essai"
  labels:
    template: "prometheus"
  parameters:
  - description: Set your Namespace
    name: NAMESPACE
    value: openshift
    required: true
  objects:
  - kind: ServiceAccount
    apiVersion: v1
    metadata:
      name: prometheus
      namespace: ${NAMESPACE}
  - kind: Role
    apiVersion: authorization.openshift.io/v1
    metadata:
      name: prometheus
      namespace: ${NAMESPACE}
    rules:
    - apiGroups: [""]
      attributeRestrictions: null
      resources:
      - pods
      - endpoints
      - services
      verbs:
      - get
      - list
      - watch
  - kind: RoleBinding
    apiVersion: authorization.openshift.io/v1
    metadata:
      name: prometheus
      namespace: ${NAMESPACE}
    subjects:
    - kind: ServiceAccount
      name: prometheus
      namespace: ${NAMESPACE}
    roleRef:
      kind: Role
      name: prometheus
      namespace: ${NAMESPACE}

When i déploy my template on my namespace by : 

 oc process  -f prometheus.template.yaml -p  NAMESPACE=dbms-containerization-dev | oc  create  -f -

It's OK, the role, roleBinding and ServiceAccount are created.

But my purpose is load by The catalog for the deployment by the end-user.
In first, :  oc  create  -f prometheus.template.yaml 
Then, i deploy the template in the namespace by the catalog.
And, i have the error message : 
Cannot create role binding "prometheus". role.authorization.openshift.io "prometheus" not found.

The role prometheus is created in the openshift ressources but not roleBinding.
It 's necessary to redeploy the template that rolebinding have created.
Maybe a delay problem / dependancy between the create of role and rolebinding.
Have you already encountered this problem?

Thank's 
Loïc

**Comment by php-coder** [comment]
@enj

**Comment by enj** [comment]
This is a side effect of how the authorization policy code worked pre 3.7.  You will need to add a delay in between the steps or have some form of retry logic.  In 3.7+ it will work as expected without any changes (as the entire authz code was replaced).

/close
