### ISSUE TITLE
should list "infrastructure" docker images used and provide a section for preloading docker images onto hosts

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-docs#754]
This would be very helpful for customers operating on disconnected networks. The beta training guide had some of this information but it has not been updated.

A concise list of Docker images (eg: haproxy-router, ose-pod, etc) and a procedure for pulling them and then exporting/importing them would be valuable.

You can possibly reference these:
https://github.com/openshift/training/blob/master/beta-4-setup.md#grab-docker-images-optional-recommended

https://github.com/openshift/training/blob/master/beta-4-setup.md#appendix---importexport-of-docker-images-disconnected-use

**Comment by bfallonf** [comment]
@thoraxe Do you think the disconnected guide satisfies this issue? Specifically:

https://docs.openshift.com/enterprise/3.1/install_config/install/disconnected_install.html#disconnected-required-software-and-components

**Comment by thoraxe** [comment]
Yes/no.

1) The image tags are out of date. They should correspond with the software package version (eg; openshift rpms 3.1.1.6 -> image tag 3.1.1.6, as far as I know).

2) The logging/metrics images have tags as well. Unfortunately they don't exactly match. So we need to figure out which image tags to specify.

There's potentially yet another issue in that OpenShift itself doesn't know about the image tags for the logging/metrics images (eg: oc get imagestream). Typically this involves reaching out to a registry to obtain the information so that the deployments can happen.

How to deal with this particular issue is way outside my skillset. We may need someone like @pweil-  or @bparees or @csrwng to help us figure out how we can deal with image stream tags in a disconnected environment.

**Comment by bparees** [comment]
I think you'd need to create the imagestreamtag objects explicitly, if you're not going to be able to import them from the registry.  so you'd basically hardcode the imagstreamtag resource definition to correspond to the image that was available locally.

**Comment by thoraxe** [comment]
Sounds like it wouldn't be terribly hard to make a scriptlet to do that?

**Comment by vikram-redhat** [comment]
I am closing this issue as this hasn't been requested directly from customers (and it is 3 years old). Please reopen if you think otherwise.
