### ISSUE TITLE
How to create a new service account

### ISSUE THREAD

**Issue by cgwalters** [openshift/openshift-docs#755]
I was following:
https://docs.openshift.org/latest/admin_guide/manage_scc.html#use-mount-host-on-the-registry
which links to the service account docs: 
https://docs.openshift.org/latest/admin_guide/service_accounts.html

Yet I may be missing it, but I'm not seeing how to create a new service account for this case there.

**Comment by cgwalters** [comment]
Ah, this is actually in https://docs.openshift.org/latest/admin_guide/install/docker_registry.html

**Comment by adellape** [comment]
This can definitely be better consolidated and/or linked. Re-opening to make sure we get it addressed.
