### ISSUE TITLE
API docs do not properly identify required attributes and return values

### ISSUE THREAD

**Issue by jcantrill** [openshift/openshift-docs#756]
The API docs, in many places, identify attributes wrongly as not required.  For example: https://docs.openshift.org/latest/rest_api/openshift_v1.html#v1-projectrequest the 'metadata' field is required.  Additionally, the return object from https://docs.openshift.org/latest/rest_api/openshift_v1.html#create-a-projectrequest is a project not a project request

* Incorrect Requires flags
* Incorrect outputs

**Comment by jcantrill** [comment]
@smarterclayton @liggitt

**Comment by smarterclayton** [comment]
ProjectRequest is a gap in upstream - we would have to be able to distinguish which object types APIs return via a static call.

Requires is not populated today - short of mutating the generated output there's not much we can do to change that.  Requires go-restful changes.

**Comment by tnguyen-rh** [comment]
@smarterclayton 
Could you please point me to the generation code -- is that the "go-restful" mentioned above?  If that cannot be changed, perhaps we can add a post-hook that applies a list of manual overrides?

**Comment by tnguyen-rh** [comment]
@smarterclayton
Oops, please disregard previous message; sorry for the noise.  I see now: https://github.com/openshift/origin/blob/master/api/README.md

**Comment by vikram-redhat** [comment]
API generation issues being rolled into one BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1258235
