### ISSUE TITLE
References to emptyDir as an Ansible variable value should be all lowercase

### ISSUE THREAD

**Issue by dcaldwel** [openshift/openshift-docs#7576]
In https://docs.openshift.com/container-platform/3.7/install_config/cluster_metrics.html#metrics-non-persistent-storage there is reference to 'emptyDir' for the Ansible metrics installation. However, if the value 'emptyDir' is actually used (eg: 'openshift_metrics_cassandra_storage_type=emptyDir'), the Ansible metrics installation fails:

> 

fatal: [<ip_address>]: FAILED! => {
    "changed": false, 
    "msg": "openshift_metrics_cassandra_storage_type (emptyDir) is invalid, must be one of: emptydir, pv, dynamic\n"
}

> 

As the error message indicates, if emptyDir is required, the value 'emptydir' (all lowercase, no capital 'D') should be used.

**Comment by gaurav-nelson** [comment]
Closing this one, tracking this in PR #10584
