### ISSUE TITLE
Add documentation for externalCertificate option in secure routes

### ISSUE THREAD

**Issue by git001** [openshift/openshift-docs#76046]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.14/networking/routes/secured-routes.html

### What needs fixing?

With PR https://github.com/openshift/router/pull/565 is it now possible to use a secret object for Route object similar to Ingress Object.

I haven't seen anything about this option in the 4.14 nor in 4.15 doc except in the API doc.

It would be nice to have documented this in the secure routes and maybe a hint in the ingress object doc that this is possible since 4.14.

Please add also in the the documentation how to activate the feature-gate `RouteExternalCertificate` in already installed clusters which was updated from OpenShift versions below 4.14 to 4.14+, because of that statement.

> Everything is behind `AllowExternalCertificates` flag which is true when cluster-ingress-operator sets it, if `RouteExternalCertificate` feature-gate is enabled.

**Comment by lunarwhite** [comment]
The document is now available at: https://docs.openshift.com/container-platform/4.16/networking/routes/secured-routes.html#nw-ingress-route-secret-load-external-cert_secured-routes

Additionally, there is a detailed guide on how to integrating this feature with cert-manager: https://docs.openshift.com/container-platform/4.16/security/cert_manager_operator/cert-manager-securing-routes.html

This is a Tech Preview feature introduced in OCP 4.16, and in general Tech Preview features won't be backported to older versions. For information on how to enable a Tech Preview feature, please refer to: https://docs.openshift.com/container-platform/4.16/nodes/clusters/nodes-cluster-enabling-features.html

Hope these help!
