### ISSUE TITLE
LDAP authentication is missed in the OSE documentations

### ISSUE THREAD

**Issue by jkaurredhat** [openshift/openshift-docs#763]
Hello,

I see that LDAP authentication is completely missed from our documentation as below  

https://access.redhat.com/beta/documentation/en/openshift-enterprise-30-administrator-guide#configuring-authentication

Can this be added soon as many of the customers are looking for it.

**Comment by liggitt** [comment]
LDAP authentication isn't in an OSE release yet (it was added after 3.0.0).

**Comment by adellape** [comment]
The following LDAP auth section will be added into the OSE docs after it's released there:

https://docs.openshift.org/latest/admin_guide/configuring_authentication.html#LDAPPasswordIdentityProvider

**Comment by nak3** [comment]
@adellape We have already the doc. Can you close this ticket?

https://docs.openshift.com/enterprise/3.0/admin_guide/configuring_authentication.html#LDAPPasswordIdentityProvider

**Comment by adellape** [comment]
@nak3 Thanks for the reminder!
