### ISSUE TITLE
service account docs needs examples of read / search / etc

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-docs#764]
The current service account docs are good at describing what they are and provide a few examples of how to configure them. However, there's no examples of searching for service accounts, showing the stats of service accounts, etc.

**Comment by liggitt** [comment]
you can search for them like any other API object:
`oc get serviceaccounts`

not sure what you mean by stats

**Comment by thoraxe** [comment]
The issue, as is almost always the case, is that the administrative guide covers a tiny portion of the service account stuff, and then you have to go to the *developer* guide to find the rest of it. And, even then, it's not entirely clear.

The divide between what topics end up in which area seems difficult to find, and there seems to be a lack of cross-linking between the sections.

Oh well.

Eg:
https://docs.openshift.com/enterprise/3.0/admin_guide/service_accounts.html

vs

https://docs.openshift.com/enterprise/3.0/dev_guide/service_accounts.html

**Comment by CowboysFan** [comment]
@thoraxe I'm going to propose this fix to the team, but I think we can alleviate some of the "disconnect" issues in such cases by having a single topic that addresses both the admin and the developer audience. In this case we have two separate topics, with some content that's the same (which was probably copied and pasted).

I think we'll be better off to have a single topic that covers the concepts really well, and withing that topic we can have content that's specific to admin and/or developers. In each "guide" we just include the relevant bits. AsciiDoc/AsciiDoctor allows us to reuse parts of a topic anywhere we want to. Of course, we still have to link to the admin/dev topics accordingly from the different "guides".

**Comment by liggitt** [comment]
I have mixed feelings about that. 

There are large parts of the documentation that the developer wouldn't care about at all, and would be a pain to wade through. For example, setting up the signing and authenticating keys and the lists of managed service accounts only applies to an administrator. 

 On the other hand, there are large portions of the documentation that are relevant to both.

 I think the tricky part is when someone who is both a developer and a cluster administrator is trying to find information. I wonder if a simple link reference between the topics would be helpful there (e.g. "See topic X for information about configuring service accounts in your cluster")

**Comment by adellape** [comment]
@CowboysFan If I understand your proposal correctly, where would such a single topic live in the repo structure?

But overall, while I get the intention, it feels like a bit of an overcorrect. I assume the comment was also directed at other topics/guides in general, but at least in these topics' case, I'd rather just work on enhancing the content. Been trying to get to the service accounts stuff; I can prioritize it this week.

**Comment by vikram-redhat** [comment]
@adellape - can you do some research on the service account examples relevant to the admins and add those?
