### ISSUE TITLE
Cannot build the documentation

### ISSUE THREAD

**Issue by chmouel** [openshift/openshift-docs#765]
I am not sure if it's my system (macosx) but I can't find a way to build the documentation anymore : 

<pre>
$ bundle exec rake build
[...]
  - admin_guide/install/prerequisites
asciidoctor: WARNING: <stdin>: line 455: invalid style for paragraph: reconfiguring-docker-storage
  - admin_guide/install/quick_install
  - admin_guide/install/advanced_install
  - admin_guide/install/docker_registry
  - admin_guide/install/deploy_router
  - admin_guide/install/first_steps
  - admin_guide/master_node_configuration
  - admin_guide/manage_nodes
  - admin_guide/routing_from_edge_lb
rake aborted!
ArgumentError: invalid byte sequence in US-ASCII
</pre>

any ideas?

**Comment by adellape** [comment]
@chmouel I seem to recall we may have discussed/resolved this elsewhere back when you reported this (apologies if I'm mistaken). I think it was around the time the Note box here in the tools setup guide was added:

https://github.com/openshift/openshift-docs/blob/master/contributing_to_docs/tools_and_setup.adoc#initial-setup

If you're still having problems, please re-open. Thanks!

**Comment by chmouel** [comment]
it it still going on :( http://sprunge.us/bIYV

not sure if its my macosx laptop that has the issues, anyone else is building the docs on macos?

**Comment by adellape** [comment]
@nhr You build on MacOS, right? :point_up:

**Comment by nhr** [comment]
@adellape I'm 100% on Fedora these days but I can dust off a Mac and give this a look.

**Comment by vikram-redhat** [comment]
I am going to close this issue as it is not related to the actual docs themselves (and it is on Mac :)).

**Comment by chmouel** [comment]
Ok in case others needed it I tried again this morning and I just needed to do a : 

<pre>
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
</pre>

and it will be with a : 

<pre>
bundle install
bundle exec rake build
</pre>

hope this help
