### ISSUE TITLE
Document CLI debugging options

### ISSUE THREAD

**Issue by liggitt** [openshift/openshift-docs#766]
Not sure if this goes in troubleshooting, debugging, dev overview, or where, but the CLI commands take these `--loglevel` options to dump network traces. Example uses:

Level | Effect
-------|---------
--loglevel=6 | print URLs
--loglevel=7 | print URLs and request/response headers
--loglevel=8 | print URLs, headers, and request/response content

**Comment by bfallonf** [comment]
I'll include this in the troubleshooting guide tracking BZ. That seems the best place for it:

https://bugzilla.redhat.com/show_bug.cgi?id=1259118
