### ISSUE TITLE
apb: there is no option --openshift to push

### ISSUE THREAD

**Issue by pilhuhn** [openshift/openshift-docs#7661]
https://github.com/openshift/openshift-docs/blob/master/apb_devel/cli_tooling.adoc#apb-devel-cli-workflows-local-registry

says `apb push --openshift`  but there is no option `--openshift` available.

later there is `apb push -o --namespace <namespace>` but there is also no option `-o`.

**Comment by vikram-redhat** [comment]
@ahardin-rh - confirm with @adellape on this one as well. Related bug: https://bugzilla.redhat.com/show_bug.cgi?id=1595695

**Comment by vikram-redhat** [comment]
Closing this issue as the related BZ has been merged and content pushed live.
