### ISSUE TITLE
Missing some namespaced objects in the project backup

### ISSUE THREAD

**Issue by e-minguez** [openshift/openshift-docs#7662]
The export misses some other objects such as `configmaps`, `hpas`, `oauthtokens` and other namespaced objects.

https://github.com/openshift/openshift-docs/blob/master/day_two_guide/topics/project_backup.adoc

**Comment by e-minguez** [comment]
I've created a trello board card to incorporate this in the docs.
https://trello.com/c/9LFvfG02/1248-add-more-objects-to-the-project-backup-in-day-2-ops-guide

**Comment by vikram-redhat** [comment]
Closing since this was fixed via previous commit.
