### ISSUE TITLE
application health provides no examples

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-docs#769]
https://docs.openshift.com/enterprise/3.0/dev_guide/application_health.html

Don't we need to tell someone how to do either of these? Are they doc'd somewhere else? If so, there are no links.

**Comment by vikram-redhat** [comment]
Related to this: https://github.com/openshift/openshift-docs/issues/777. Closing this issue.

**Comment by bfallonf** [comment]
Related PR: #1070 

Closing this in favor of that one. Might need to add more info about the second option.
