### ISSUE TITLE
Document NSS wrapper for images in image guide

### ISSUE THREAD

**Issue by csrwng** [openshift/openshift-docs#776]
Explain why, how this works:
https://github.com/openshift/postgresql/blob/master/9.2/run-postgresql.sh#L107

**Comment by jawnsy** [comment]
This looks to be a dupe of https://github.com/openshift/openshift-docs/issues/1365 so I think this can be closed

**Comment by bfallonf** [comment]
@csrwng Could you confirm 1365 is a dupe? Your link above no longer works, so I'm not sure what you're asking for exactly. Thanks!

PS, if you'tr talking about PostgresQL replication, I just made this BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1400741

**Comment by csrwng** [comment]
@bfallonf it is a dupe. I believe the link was to the line that set the env var for the nss wrapper.
