### ISSUE TITLE
Describe the different types of deployments

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-docs#778]
openshift/origin#3769 describes deployments by type and demonstrates how to use them.  This should be part of the developers guide under deployments - we need to separate the three sections - explaining the types of deployment and when you would use them, explaining how you set a deployment config to use them, and then possibly a separate section with examples.

**Comment by bfallonf** [comment]
There's a BZ open for this already. Closing this in favour of that:

https://bugzilla.redhat.com/show_bug.cgi?id=1253129
