### ISSUE TITLE
router docs should talk about binding host ports

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-docs#781]
We need to tell people that the router consumes 80/443 on the host and that the router should be restricted to nodes where that port is available (eg: not consumed already by something else like httpd or nginx or something).

The reality is that people should not be installing those things directly on a node anyway... but they will.

**Comment by thoraxe** [comment]
Note that the auth docs talk about installing httpd on master:
https://access.redhat.com/beta/documentation/en/openshift-enterprise-30-administrator-guide#RequestHeaderIdentityProvider

Out of the box the installer makes the master an unschedulable node, so this normally isn't a problem. But if someone tries to do this on a schedulable node, there may be a problem.

Also, because httpd is a host-based service and kube doesn't monitor those, the "podfitsports" directive in the scheduler will not take effect and you can get a router scheduled where it can't work.

**Comment by vikram-redhat** [comment]
BZ create to track work: https://bugzilla.redhat.com/show_bug.cgi?id=1259566. Closing this issue.

**Comment by bfallonf** [comment]
@thoraxe I'm a little confused. You're saying that they should enrure the router can reach port 80/443 on its host, but then you talk about the proper placement of httpd. Can you please explain the link between the two more?

**Comment by thoraxe** [comment]
@bfallonf if for some reason someone is running httpd on the **host**, they could not run a router there unless they do something funky with which interface each consumes, if possible.

Sorry if that's unclear.

In practice you shouldn't run anything but OpenShift on the **host**, but people do strange things.

**Comment by bfallonf** [comment]
@thoraxe Ok. I think I get what you mean. I've added an important box to the routers section, which is probably enough to settle this issue, but that doesn't help the rest of what we've discussed here. 

To improve on this, there's a BZ out there that's about starting a Troubleshooting Guide. I'm thinking that it might be wise to add to that with something about a port glossary? Say, which services should work on which port, then there could also be a recommendation on which host the services should be on. 

If the above two things go forward, would you say that's enough to satisfy this issue?

**Comment by thoraxe** [comment]
@bfallonf Did we ever get the port docs posted? I think that "ancillary services" (like routers, nodeports, etc) might also be documented there?

**Comment by bfallonf** [comment]
@thoraxe I had a look around, but I'm not too sure which port docs you mean. Did we miss something about documenting the port stuff? And yes, getting that stuff into the docs might clear up some of the confusion between the different types of services.

**Comment by thoraxe** [comment]
#684
