### ISSUE TITLE
Router should be placed at specific node

### ISSUE THREAD

**Issue by nekop** [openshift/openshift-docs#782]
Currently "Deploying a Router" in Admin Guide doesn't mention this fact, no description about selector  and some users create a router on random node and getting "requests don't reach the router" issues.

We need to make it clear that we usually need to deploy a router on a specific node, typically by using labels on nodes and selector, configure wildcard DNS to point to the router, etc. It would be great if we have an example deployment with a picture how router works with wildcard DNS.

**Comment by nak3** [comment]
It is mentioned this section a little:

https://docs.openshift.com/enterprise/3.0/admin_guide/install/prerequisites.html#environment-requirements

~~~
For example, create a wildcard DNS entry for cloudapps, or something similar, that has a low TTL and points to the public IP address of the host where the router will be deployed:
~~~

However, I also have seen a lot of users who is hitting [this issue](https://access.redhat.com/solutions/1529603). I agree to the improvement of documentation with a picture.

> It would be great if we have an example deployment with a picture how router works with wildcard DNS.

**Comment by nekop** [comment]
Also it's better to mention #498 in "Deploying a Router" doc.

**Comment by vikram-redhat** [comment]
BZ create to track work: https://bugzilla.redhat.com/show_bug.cgi?id=1259566. Closing this issue.
