### ISSUE TITLE
Spacing for list continuations

### ISSUE THREAD

**Issue by adellape** [openshift/openshift-docs#786]
From http://asciidoctor.org/docs/asciidoc-writers-guide/#complex-list-content:

> If you want to attach additional paragraphs to a list item, you “add” them together using a list continuation. A list continuation is a + symbol on a line by itself, immediately adjacent to the two blocks it’s connecting.

In the rendered example that follows the paragraph in the above doc, there is a nicely sized space between the two lines. The same is seen in the following GitHub asciidoc preview of our docs using list continuations:

https://github.com/adellape/openshift-docs/blob/1c574e84986a9658088b0ec9902ee77afd658f55/whats_new/ose_3_0_release_notes.adoc#known-issues-for-xpaas-images

However in our asciidoctor builds, the spacing makes it look like they're just on the next line, which makes things look more jumbly:

(internal link) http://file.rdu.redhat.com/~adellape/072115/spacing_issue/whats_new/ose_3_0_release_notes.html#known-issues-for-xpaas-images

While not the end of the world, if we were able to adjust the line break spacing/width for a list continuation to match more how the asciidoctor.org and GH preview renders look (i.e., more pronounced white space), it would both be clearer to read and better match the source author's intended purpose.

cc @nhr @CowboysFan

**Comment by nhr** [comment]
This has everything to do with our style sheet. Pinging @sg00dwin on the off chance that he has a spare cycle to look at this. Steve, if you are slammed, no worries!

**Comment by sg00dwin** [comment]
@nhr @adellape pull request opened. 
https://github.com/openshift/openshift-docs/pull/787

**Comment by adellape** [comment]
@sg00dwin @nhr While we're on the subject, the above fix addresses unordered lists (thanks Steve), but would the similar spacing issue with numbered/ordered lists be a related but different fix? E.g., see the uneven spacing between numbered list continuations here:

https://docs.openshift.com/enterprise/3.0/admin_guide/manage_scc.html#use-mount-host-on-the-registry

Where the source looks like:

```
. Create a new link:service_accounts.html[service account].
. Add the service account user name to the *privileged* SCC using:
+
----
$ oc edit scc privileged
----
+
Note that a fully-qualified service account user name is in the form of
*system:serviceaccount:<namespace>:<name>*.

. Create the registry using:
+
----
$ oadm registry --service-account=<name> --mount-host=<dir> ...
----
```
