### ISSUE TITLE
project template docs don't describe how to add default quota to projects

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-docs#788]
https://access.redhat.com/beta/documentation/en/openshift-enterprise-30-administrator-guide#self-provisioned-projects

This is pretty good, except there's no information about how one would add a default quota.

**Comment by bfallonf** [comment]
@thoraxe There's a page on creating quotas: https://docs.openshift.com/enterprise/3.1/dev_guide/quota.html

(this will move to the admin guide soon). 

Do you think this fulfills what you were asking? Is there something special that needs to happen for self-provisioned projects?

**Comment by thoraxe** [comment]
Not really. The template that is output by:

```
oadm create-bootstrap-project-template -o yaml > template.yaml
```

Does not have a quota section, and it's not clear how to necessarily add a quota to it. You likely wouldn't know that you just need to add more items to the list in the template.

For example, see:

https://github.com/openshift/training/blob/master/content/default-project-template.yaml

So, at a minimum, I would think that the admin guide would need to describe how to add a quota or a limit range to the project request template.

**Comment by mburke5678** [comment]
@thoraxe Is this still an issue? 
If we add a link from the Self-provisioning Projects topic 
https://docs.openshift.com/container-platform/3.5/admin_guide/managing_projects.html#selfprovisioning-projects

that points to the creating a quota fro a project section?
https://docs.openshift.com/container-platform/3.5/admin_guide/quota.html#create-a-quota

**Comment by thoraxe** [comment]
Almost. It's not entirely clear that you can add a quota object to the project request template unless you have a good/solid understanding of templates to begin with. So, just a link may not be sufficient for a person to put the two things together and then extrapolate that they can add a quota object to a template...

Same goes for limit ranges.

**Comment by mburke5678** [comment]
Created a docs Bugzilla. Closing this issue.
https://bugzilla.redhat.com/show_bug.cgi?id=1461940
