### ISSUE TITLE
[logging] Track Logging and Metrics Documentation Audit

### ISSUE THREAD

**Issue by bmcelvee** [openshift/openshift-docs#7882]
We will use this issue to track our findings and link to PRs related to updating our logging and metrics documentation. 
FYI: @jcantrill, @vikram-redhat, @aheslin 

- [ ] [Document Log Throttling](https://github.com/openshift/origin-aggregated-logging/blob/master/docs/log-drivers-and-throttling.md#log-throttling)

**Comment by bmcelvee** [comment]
Should the 'Recommendations for OpenShift Container Platform Version 3.x' section be removed from versions following 3.5? 
https://docs.openshift.com/container-platform/3.7/install_config/cluster_metrics.html#capacity-planning-for-openshift-metrics

**Comment by jcantrill** [comment]
@tkatarki Can you address https://github.com/openshift/openshift-docs/issues/7882#issuecomment-370436713

**Comment by vikram-redhat** [comment]
We never got around to doing this, so closing for now.
