### ISSUE TITLE
No need to add backtic in the command.

### ISSUE THREAD

**Issue by sanjaytripathi97** [openshift/openshift-docs#78869]
Location:- ./modules/nw-ovn-kubernetes-checking-live-migration-metrics.adoc

Command:- oc -n openshift-monitoring exec -c prometheus prometheus-k8s-0 -- curl -k -H "Authorization: <eyJhbGciOiJSUzI1NiIsImtpZCI6IlZiSUtwclcwbEJ2VW9We...>" "https://<openshift_API_endpoint>" --data-urlencode "query=openshift_network_operator_live_migration_condition" | jq`

After jq there is a backtick which is causing the issue while running the command by directly copying.

**Comment by obrown1205** [comment]
Addressing in https://github.com/openshift/openshift-docs/pull/79655

**Comment by mburke5678** [comment]
Changes are live: https://docs.okd.io/4.16/networking/ovn_kubernetes_network_provider/migrate-from-openshift-sdn.html#checking-live-migration-metrics
