### ISSUE TITLE
Document how to add custom CA roots for builds

### ISSUE THREAD

**Issue by cgwalters** [openshift/openshift-docs#791]
The Docker image used for builds comes with the upstream distro ca-certificates.  As a system administrator, I want to add my organization's internal CA to the trust root.

It'd be nice if this was persistent across updates.

One option would be to suggest using the host's CA roots via `-v /etc/pki:/etc/pki:ro` (and note this only works if the base image and the host have an identical major version - you couldn't expect this to work if using a theoretical EL 8 OpenShift on EL 7 Atomic Host or vice versa).

**Comment by mburke5678** [comment]
@cgwalters In the PR you linked above (#3853), there is a suggestion that the document at the following link satisfy the request. Does that address your issue?
https://docs.openshift.org/latest/dev_guide/builds.html#using-private-repositories-for-builds

in 3.5:
https://docs.openshift.com/container-platform/3.5/dev_guide/builds/index.html

**Comment by cgwalters** [comment]
@mburke5678 Yes.

(Though there's a larger issue about apps that need those certs at runtime, but I suspect most people are addressing that today by using custom base images)
