### ISSUE TITLE
More information on accessModes and how to modify it.

### ISSUE THREAD

**Issue by jkaurredhat** [openshift/openshift-docs#795]
In Openshift Enterprise documenation no information is provided about different accessModes for persistent volumes and the usecase for it 

ReadWriteOnce
ReadOnlyMany
ReadWriteMany

Inaddition to this, how this can be modified for existing docker registry

**Comment by adellape** [comment]
@jkaurredhat The following was added recently:

https://docs.openshift.org/latest/architecture/additional_concepts/storage.html#pv-access-modes

It is live in the Origin docs and will get picked up in the next OSE docs publish.

Can you expand on your request for more registry-specific information? The current section on "Storage for the Registry" is here:

https://docs.openshift.com/enterprise/3.0/admin_guide/install/docker_registry.html#storage-for-the-registry

**Comment by jkaurredhat** [comment]
Yes, so if a user has created a persistent volume with accessMode "ReadWriteOnce" so how can he modify the accessMode to "ReadWriteMany" . What's the command ?

Is it safe to delete?

**Comment by CowboysFan** [comment]
@adellape I think it would be good to get this documented in our official docs and answer some of these questions.

**Comment by ahardin-rh** [comment]
Closing this old issue since we have since added a lot of information on access modes and [persistent storage examples](https://docs.openshift.com/container-platform/3.5/install_config/storage_examples/index.html). Let me know if there is a need to reopen.
