### ISSUE TITLE
Document bash completion

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/openshift-docs#796]
When you install openshift, you get bash completion on master.
If you install the client in a different box to do remote connection to the master, the client tar file does not contain bash_completions.

Document how to get them and how to install on linux and mac based systems, as it works for both and it is quite convenient.

**Comment by mburke5678** [comment]
@jorgemoralespou We are going through older issues.

I am not sure that we talk about bash-completion in the docs for master or other system, other than to install the package in the installation prerequisites. is this something that we should cover?

We have instructions for installing the CLI on Mac, starting around 3.0. 
https://docs.openshift.com/container-platform/3.5/cli_reference/get_started_cli.html
Does this address your second concern?

**Comment by vikram-redhat** [comment]
Closing this as no updates were received and this issue is 3 years old.
