### ISSUE TITLE
Wrong info for openshift_facts playbook

### ISSUE THREAD

**Issue by tdudgeon** [openshift/openshift-docs#8026]
The docs [here](https://docs.openshift.com/container-platform/3.7/install_config/install/prerequisites.html#prereq-cloud-provider-considerations) are not correct. It states:
 ```
# ansible-playbook  [-i /path/to/inventory] \
    /usr/share/ansible/openshift-ansible/roles/openshift_facts/library/openshift_facts.py
```
The file referenced is a python script not a playbook. 
I think the correct file is `openshift-ansible/playbooks/byo/openshift_facts.yml`.

**Comment by mhausenblas** [comment]
Thanks a bunch @tdudgeon and CC: @e-minguez for visibility …
