### ISSUE TITLE
Document backup and restore procedures

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/openshift-docs#803]
There is no information on backup/restore procedures, what files need to be backup and how they can be backuped and restored.
OpenShift configuration files backup and restore are quite easy but not etcd backup and restore.

**Comment by thoraxe** [comment]
We'll also need to differentiate between the following:

1) backup of non-clustered etcd without etcdctl
2) backup of clustered etcd with etcdctl

**Comment by thoraxe** [comment]
I think we need to capture:

/etc/openshift
/var/lib/openshift
/etc/sysconfig/*openshift*

What else?

**Comment by ivanthelad** [comment]
Openshift Registry content? 
it would also be need to part of a backup practise

**Comment by vikram-redhat** [comment]
BZ created to track work on this: https://bugzilla.redhat.com/show_bug.cgi?id=1259544.
