### ISSUE TITLE
Add an example of how to get a token from the API

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-docs#807]
Either in the additional concepts authentication (https://docs.openshift.org/latest/architecture/additional_concepts/authentication.html) page or under the rest api or both (latter is probably better).

Lots of people aren't able to successfully do this - example in curl is important.

**Comment by mburke5678** [comment]
@smarterclayton As of 3.1, the API reference guide contains a section on session tokens. Does this meet your concern here?
"...After logging in, the session token may be obtained with the oc whoami command:
$ oc whoami -t
dIAo76N-W-GXK3S_w_KsC6DmH3MzP79zq7jbMQvCOUo"
https://docs.openshift.com/enterprise/3.1/rest_api/index.html#rest-api-session-tokens

Forgive my ignorance if this does not help.
