### ISSUE TITLE
Update docs for Java STI image

### ISSUE THREAD

**Issue by dsimansk** [openshift/openshift-docs#810]
[Doc page ref](https://docs.openshift.org/latest/using_images/s2i_images/java.html)

Since https://github.com/fabric8io/java-main/commit/fe6e4ed02ca0dea8c92ea4794679fc928069145f, there's additional parameter `MAVEN_DEBUG_ARGS` to customize Maven debug output. Also note that the `MAVEN_ARGS` doesn't use `-P openshift` by default.

**Comment by mburke5678** [comment]
Closing as this topic appears only in Origin 1.2, which we are not updating any longer. 

Perhaps this issue can be brought up to the middleware team as they talk about Java S2I??
https://access.redhat.com/documentation/en-us/red_hat_jboss_middleware_for_openshift/3/html-single/red_hat_java_s2i_for_openshift/

**Comment by mburke5678** [comment]
@dsimansk It appears that this topic might have slipped into OpenShift Online 3.0. Do you know if the topic belongs there?
https://docs.openshift.com/online/using_images/s2i_images/java.html

**Comment by dsimansk** [comment]
@mburke5678 well, this issue is definitely obsolete now. No need to update anything, afaik. 

The Online [guide](https://docs.openshift.com/online/using_images/s2i_images/java.html) points to current s2i java image and all config variables.
