### ISSUE TITLE
persistent volume guide has bad kube link

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-docs#811]
https://docs.openshift.com/enterprise/3.0/dev_guide/persistent_volumes.html

Links to:

https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/persistent-volumes

Which is a 404.

It may want to link to something like:
https://github.com/GoogleCloudPlatform/kubernetes/tree/master/docs/user-guide/persistent-volumes

**Comment by adellape** [comment]
This was addressed in https://github.com/openshift/openshift-docs/pull/798. Fix is live in the Origin docs and the OSE docs will pick it up in the next publish, planning for end of week.

**Comment by adellape** [comment]
Fix is live:

https://docs.openshift.com/enterprise/3.0/dev_guide/persistent_volumes.html#claims-as-volumes-in-pods
