### ISSUE TITLE
MCO Fix Configuring updated boot images

### ISSUE THREAD

**Issue by mburke5678** [openshift/openshift-docs#81452]
https://docs.openshift.com/container-platform/4.17/machine_configuration/mco-update-boot-images.html#mco-update-boot-images-configuring_machine-configs-configure

1. Check on the code block in 1.b:

```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: operator.openshift.io/v1
kind: MachineConfiguration
metadata:
  creationTimestamp: "2024-10-16T14:33:49Z"
  generation: 2
  name: cluster
  resourceVersion: "41011"
  uid: 0d1699f4-bc7d-447f-b234-ad3c30905a43
spec:
  logLevel: Normal
  managedBootImages: 
    machineManagers:
    - resource: machinesets
      apiGroup: machine.openshift.io
      selection:
        mode: Partial
          partial:
            machineResourceSelector:
              matchLabels:
                update-boot-image: "true"
  managementState: Managed
  operatorLogLevel: Normal

```

Error in terminal:

```
# The edited file had a syntax error: error parsing edited-file: error converting YAML to JSON: yaml: line 21: mapping values are not allowed in this context 
```
Line 21 is `partial`.

Error in YAMLlinter:

```
Nested mappings are not allowed in compact mappings at line 20, column 15
Implicit keys need to be on a single line at line 20, column 15
```
Line 20 is `mode: Partial`

2. I am not seeing the validation step work

```
oc get machine configuration <machineset_name> -n openshift-machine-api -o yaml  
```
s/b
```
oc get machineconfiguration cluster -n openshift-machine-api -o yaml
```

**Comment by djoshy** [comment]
For (1) there is a spacing issue at the `partial:` field. It is a sub-field under `selection`, like mode. Here is an example used in our origin tests: https://github.com/openshift/origin/blob/master/test/extended/testdata/machine_config/machineconfigurations/managedbootimages-partial.yaml

For (2), this must've been an error that slipped through. The correct command should be:
```
oc get machineconfiguration cluster -n openshift-machine-config-operator -o yaml
``` 
I'm not sure if filtering by namespace is necessary(you have the MAPI namespace in the command, which isn't where this object resides, so not sure why that worked :thinking: )

**Comment by mburke5678** [comment]
Changes are live. Fixed code block for 1b. 

[docs.openshift](https://docs.openshift.com/container-platform/4.17/machine_configuration/mco-update-boot-images.html#mco-update-boot-images-configuring_machine-configs-configure)
[docs.acccess(https://docs.redhat.com/en/documentation/openshift_container_platform/4.17/html/machine_configuration/mco-update-boot-images#mco-update-boot-images-configuring_machine-configs-configure)
