### ISSUE TITLE
Need examples in "rest-api-reference" guide for OSE 

### ISSUE THREAD

**Issue by jkaurredhat** [openshift/openshift-docs#816]
In documentation  only GET and POST are mentioned.

 It would be good if examples on how to run the RESTAPI i.e authentication stuff before running this rest api call should be mentioned and the output we will get with the REST API would be helpful. Similar to OSE 2

**Comment by vikram-redhat** [comment]
API generation issues being rolled into one BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1258235
