### ISSUE TITLE
Documentation navigation structure is inconsistent

### ISSUE THREAD

**Issue by sean-freeman** [openshift/openshift-docs#81621]
### Which section(s) is the issue in?

All

### What needs fixing?

Navigation structure changes needed to:
- Structure/Sequence
- Grammatical inconsistencies

#### The current documentation structure is as follows (with annotation):

Inconsistency in the generic vs. vendor-specific documentation chapters, increases the difficulty for the end-user to find the relevant information for their planned installation.

1. Installation overview `[generic]`
2. Disconnected installation mirroring `[generic and is configuration, not installation]`
3. Installing on Alibaba Cloud
4. Installing on AWS
5. Installing on Azure
6. Installing on Azure Stack Hub
7. Installing on GCP
8. Installing on IBM Cloud
9. Installing on Nutanix
10. Installing on-premise with Assisted Installer `[generic]`
11. Installing an on-premise cluster with the Agent-based Installer `[generic]`
12. Installing on a single node `[generic]`
13. Installing on bare metal `[generic]`
14. Deploying installer-provisioned clusters on bare metal `[generic]`
15. Installing IBM Cloud Bare Metal (Classic)
16. Installing on IBM Z and IBM LinuxONE
17. Installing on IBM Power
18. Installing on IBM Power Virtual Server
19. Installing on OpenStack
20. Installing on OCI
21. Installing on vSphere
22. Installing on any platform `[generic]`
23. Installation configuration `[generic]`
24. Validation and troubleshooting

#### Grammatical inconsistencies throughout such as:

```
10. Installing on-premise with Assisted Installer
11. Installing an on-premise cluster with the Agent-based Installer
>>>
10. Installing on-premise with the Assisted Installer
11. Installing on-premise with the Agent-based Installer
```

```
13. Installing on bare metal
14. Deploying installer-provisioned clusters on bare metal
>>>
13. Installing on bare metal with the UPI Installer
14. Installing on bare metal with the IPI Installer
```

```
8.  Installing on IBM Cloud
15. Installing IBM Cloud Bare Metal (Classic)
>>>
8.  Installing on IBM Cloud
15. Installing on IBM Cloud Bare Metal (Classic)
```

#### Proposal re-sequence

```
### [start generic content] ###
1. Installation overview
22. Installing on any platform
10. Installing on-premise with the Assisted Installer
11. Installing on-premise with the Agent-based Installer
12. Installing on a single node
13. Installing on bare metal with the UPI Installer
14. Installing on bare metal with the IPI Installer
23. Installation configuration
    - 2. Disconnected installation mirroring   [configuration content, not installation]

### [start of platform-specific, type Cloud IaaS] ###
3. Installing on Alibaba Cloud
4. Installing on AWS
5. Installing on Azure
7. Installing on GCP
8. Installing on IBM Cloud
18. Installing on IBM Power Virtual Server by IBM Cloud
15. Installing on IBM Cloud Bare Metal (Classic)
20. Installing on OCI

### [start of platform-specific, type On-Premise] ###
6. Installing on Azure Stack Hub
16. Installing on IBM Z and IBM LinuxONE
17. Installing on IBM Power
10. Installing on Nutanix
19. Installing on OpenStack
21. Installing on VMware vSphere

24. Validation and troubleshooting
```

**Comment by sean-freeman** [comment]
@kalexand-rh Can you please review this suggestion? I'll happily raise a PR for it, but wanted to talk it out first.

**Comment by kalexand-rh** [comment]
@bscott-rh, when you have a chance, will you PTAL?

**Comment by sean-freeman** [comment]
Proposal made and rejected, closing GH Issue
