### ISSUE TITLE
PIDPressure listed twice for node conditions

### ISSUE THREAD

**Issue by peterroth** [openshift/openshift-docs#82954]
### Which section(s) is the issue in?
https://docs.redhat.com/en/documentation/openshift_container_platform/4.17/html/nodes/working-with-nodes#nodes-nodes-viewing-listing_nodes-nodes-viewing
On the above link the "PIDPressure" is listed twice, at point 6:
```
The node conditions and status. The conditions stanza lists the Ready, PIDPressure, PIDPressure, MemoryPressure, DiskPressure and OutOfDisk status. These condition are described later in this section.
```

### What needs fixing?
List is only once.

### Which versions are affected?
I checked from 4.17 back to 4.10 and all of them.

**Comment by bergerhoffer** [comment]
Closing because #82955 merged! Updates will be live shortly
