### ISSUE TITLE
update pre-requisites for masters

### ISSUE THREAD

**Issue by jeremyeder** [openshift/openshift-docs#8306]
### Which section(s) is the issue in?
https://docs.openshift.org/latest/install_config/install/prerequisites.html

### What needs fixing?
* We state 2 cores for masters.  This needs to be bumped to 4, and we need to be absolutely clear that this is a minimum and we strongly advise more than 4.

* Same goes for memory..16g is the minimum and for larger clusters, particularly when etcd is co-located on masters, 16g may not be enough.

* Add a bullet to the master section that talks about co-located etcd.  If etcd is co-located there is just no way 2 cores will work, and probably 4 will be too little for even a moderately sized/loaded cluster.

**Comment by ahardin-rh** [comment]
@jeremyeder Thanks! Does this change apply to 3.9 docs, or other versions as well?

**Comment by jeremyeder** [comment]
@smarterclayton @mffiedler

**Comment by ahardin-rh** [comment]
Addressed in https://github.com/openshift/openshift-docs/pull/8331
Closing this issue and moving the discussion there.
