### ISSUE TITLE
Document where are the builder images and templates provided by OpenShift

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/openshift-docs#832]
I haven ' t found any reference to the fact that the images and templates provided OOTB by OpenShift are in the openshift namespace.
In CLI you need to look for the with the -n openshift, and when creating a template, you need to reference they are defined in such namespace.

**Comment by adellape** [comment]
It is mentioned throughout this Admin Guide topic:

https://docs.openshift.org/latest/admin_guide/install/first_steps.html.

And the following appears in the Dev Guide topic https://docs.openshift.org/latest/dev_guide/templates.html#using-the-quickstart-templates:

"Your cluster administrator should have created these templates in the default openshift project so you have access to them. If they are not available, direct your cluster administrator to the First Steps topic."

In the Dev Guide topic, we could show an example of listing out the templates with `oc get templates -n openshift` to more obviously get the point across. @jorgemoralespou wdyt?

**Comment by jorgemoralespou** [comment]
@adellape definitely. I've been working on extending templates and it's not obvious where are the ones shipped with the product. I also think it's worth on the dev guide to mention that for a template to be global to every project a cluster admin has to install it and to be local a user can do it, creating the template in their own project. 
Also worth mentioning that in the ui and cli, templates will come both from global and local scope.
