### ISSUE TITLE
Container Networking topic should be more obvious

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-docs#835]
https://docs.openshift.org/latest/admin_guide/native_container_routing.html

Should be called Container Networking and describe the three different paths
- Configuring a subnet routed network
- Configuring OpenShift SDN
- Configuring an external SDN integration

The routing aspects of this doc are relevant for the first and the former.

**Comment by smarterclayton** [comment]
@rajatchopra @ramr @pweil- FYI but this is a really important topic

**Comment by mburke5678** [comment]
@smarterclayton A topic that *seems* to address your concerns was added in 3.2:
https://docs.openshift.com/enterprise/3.2/install_config/configuring_sdn.html

https://docs.openshift.com/container-platform/3.5/install_config/configuring_sdn.html

Does this topic meet your needs related to this PR?

**Comment by vikram-redhat** [comment]
Closing this as this is no longer an issue with what @mburke5678 added. Please reopen if you think otherwise.
