### ISSUE TITLE
layout broken for Storage Resources Managed by Quota table

### ISSUE THREAD

**Issue by ncameronbritt** [openshift/openshift-docs#8408]
### Which section(s) is the issue in?
https://docs.openshift.org/latest/dev_guide/compute_resources.html#dev-managed-by-quota

### What needs fixing?
Last two items in table are unreadable.
![screen shot 2018-03-23 at 2 41 35 pm](https://user-images.githubusercontent.com/8974593/37847775-55a5d5e6-2ea8-11e8-90c9-ab354c02ca79.png)

**Comment by vikram-redhat** [comment]
@gaurav-nelson - this must be to do with the new stylesheet issue. Can you look at it ASAP on Monday?
