### ISSUE TITLE
Advanced Install doc in admin guide missing 'deployment_type' var in ansible hosts file examples

### ISSUE THREAD

**Issue by etsauer** [openshift/openshift-docs#841]
All three sample /etc/ansible/hosts files in admin_guide/install/advanced_install.adoc are missing the 'deployment_type' variable, which will cause ansible to fail the playbook.

**Comment by adellape** [comment]
@etsauer Are you looking at them using the GH preview? They're conditionalized for Enterprise vs Origin, so they won't show up in the GH preview. E.g.:

https://github.com/openshift/openshift-docs/blame/master/admin_guide/install/advanced_install.adoc#L311-L316

Those ifdefs are used in many places in the docs, so I would not recommend relying on the GH previews, and instead use https://docs.openshift.org/latest/welcome/index.html (Origin) or https://docs.openshift.com/enterprise/3.0/welcome/index.html (Enterprise).

**Comment by etsauer** [comment]
@adellape oh, got it. Yeah I had been looking at these docs because the published version doesn't contain the HA guides yet.

**Comment by adellape** [comment]
@etsauer OK, thanks. They should get picked up in the Origin nightly build. The OSE rebuild is incoming for 3.0.1.

**Comment by adellape** [comment]
@etsauer OSE docs have been updated:

https://docs.openshift.com/enterprise/3.0/admin_guide/install/advanced_install.html#configuring-ansible

**Comment by etsauer** [comment]
ok thanks.
