### ISSUE TITLE
Enable basic authentication for private build repositories

### ISSUE THREAD

**Issue by jcordes73** [openshift/openshift-docs#846]
Currently only SSH key-based authentication is supported (see https://docs.openshift.org/latest/dev_guide/builds.html#using-private-repositories-for-builds).

Can we also add a facility for basic authentication? This is mostly useful when no direct machine access is available and GIT is made available via an HTTP interface.

**Comment by bparees** [comment]
https://trello.com/c/6EhPEbM4/569-8-add-other-auth-methods-for-accessing-private-repos-build
