### ISSUE TITLE
Update to minor releases

### ISSUE THREAD

**Issue by ksemaev** [openshift/openshift-docs#8495]
Have searched lots of manuals, but cannot find - how to update from 3.7.0 to 3.7.2 for example? It is a simple task, but what is the way of doing it?

**Comment by gaurav-nelson** [comment]
Thank you @ksemaev for creating this issue. I have created a bug for adding this in the docs. Please see https://bugzilla.redhat.com/show_bug.cgi?id=1567690 for more details. Because we are now tracking it in the bug, I am closing this one here.
