### ISSUE TITLE
Example template has incorrect field

### ISSUE THREAD

**Issue by bfallonf** [openshift/openshift-docs#852]
The example template in the self-provisioning topic [1] has "vbeta1". This prevents the template from working. The field needs to be changed to "v1".

[1] https://docs.openshift.com/enterprise/3.0/admin_guide/selfprovisioned_projects.html#template-for-new-projects

**Comment by adellape** [comment]
This is still a lingering issue from https://github.com/openshift/openshift-docs/issues/428#issuecomment-126448718. Tried correcting it the other day but the conversion tool won't convert from v1beta1. Closing this, see 428.

**Comment by adellape** [comment]
Fixed by https://github.com/openshift/openshift-docs/pull/854 (now uses `oadm create-bootstrap-project-template` instead).

**Comment by bfallonf** [comment]
@adellape Right. I should have checked what it looks like on Github... It was preventing this stuff from happening in the training course. Either way...fixed now! Thanks.
