### ISSUE TITLE
[enterprise-3.6] Edit suggested in file install_config/configuring_aws.adoc

### ISSUE THREAD

**Issue by geek182** [openshift/openshift-docs#8524]
### Which section(s) is the issue in?

IAM rules for the master. [https://docs.openshift.com/container-platform/3.6/install_config/configuring_aws.html#configuring-aws-permissions](url)

### What needs fixing?
IAM rules for the master is missing RevokeSecurityGroupIngress which is needed when deleting SG build from openshift/kubernetes.
I get this error when deleting a service in openshift which has an ELB create from it.

**Comment by vikram-redhat** [comment]
Tracking via: https://bugzilla.redhat.com/show_bug.cgi?id=1562309
