### ISSUE TITLE
REST API doc for Pod/Exec

### ISSUE THREAD

**Issue by marekjelen** [openshift/openshift-docs#8531]
### Which section(s) is the issue in?
https://docs.openshift.org/latest/rest_api/api/v1.Pod.html#Post-api-v1-namespaces-namespace-pods-name-exec

### What needs fixing?

The example shows this `Accept` header

```
Accept: application/json
```

but should be

```
Accept: */*
```

---

`Connection: close` should not be there

---

The description should mention that upgrade to `SPDY` or `Websocket` is required; and that `Websocket` is preferred. 

---

The documentation should reflect that the `command` qs parameter can be passed multiple times.

---

The response can be as well `406 Not acceptable`, e.g. when `application/json` is used, as shown in the example.

---

As per @soltysh the GET endpoint (https://docs.openshift.org/latest/rest_api/api/v1.Pod.html#Get-api-v1-namespaces-namespace-pods-name-exec) should not be there.

**Comment by vikram-redhat** [comment]
This needs to be fixed within the code so I am closing it. Please open the issue against the origin API code.
