### ISSUE TITLE
[online] Edit suggested in file cli_reference/index.adoc

### ISSUE THREAD

**Issue by YasharF** [openshift/openshift-docs#8532]
### Which section(s) is the issue in?
It is insufficient to state "The CLI is available using the oc command" on many of the pages

### What needs fixing?
Add a statement on how to install the CLI so the oc command would be available, on any page that you are stating the CLI is available via the oc command.

**Comment by vikram-redhat** [comment]
@ahardin-rh - related to #8533. I am not closing this one, but feel free to close or follow up.

**Comment by YasharF** [comment]
Some background here, it took me more than 15 min from the first point when I realized there is this `oc` command until when I was finally able to figure out how to get the related files to install.

It took me longer to realize it wasn't an easy to maintain installation like an apt-get install and I had to do bunch of untarring and fixing permissions, etc.  After about half an hour, I gave up on the CLI and tried to use the Web portal to deploy the app.  The instanes for some unknown reason just wouldn't take env environment variables that I was adding and the app kept crashing and restarting since it couldn't hook the the end-points that were in the env variables.  After an hour, I gave up unfortunately.

Another suggestion, which is not documentation related, it would be great if the CLI is distributed and updated using apt-get repos. I have used Heroku's CLI quite a bit and it is just really easy to figure out how to get the tool and knowing that the tooling is up to date.  Just search for `install heroku cli` in Google, and walla the first link is an article with a few big boxes for single command download and installs based on platform (macOS, Windows, Ubuntu).

**Comment by YasharF** [comment]
More on the background, I am one of the maintainers of Hackathon Starter project (https://github.com/sahat/hackathon-starter ) and we have instructions on how new developers can deploy their code to various platforms as part of Hackathons or in general.  Our existing instructions seemed to be out of date for OpenShift (https://github.com/sahat/hackathon-starter#deployment ) which is the reason I was trying to figure out how to deploy to OpenShift so I could update the instructions for a new or jr developer who is crunching during a hackathon weekend and trying to get their stuff to work.
