### ISSUE TITLE
[online] Edit suggested in file cli_reference/get_started_cli.adoc

### ISSUE THREAD

**Issue by YasharF** [openshift/openshift-docs#8533]
### Which section(s) is the issue in?
"The CLI for Linux is provided as a tar.gz archive; you can download it from the Command Line Tools page on the web console." does not provide a link to the download page.

### What needs fixing?
Instead of just stating that you can download the CLI from the Command Line Tools page on the web console, also provide a URL link that the reader with one click can go to the download page.

**Comment by vikram-redhat** [comment]
@YasharF - Hey there. The link to the download is available from the web console of the OpenShift instance you are running and contains instructions specific to your instance. Even though the download link is generic, the follow on instructions are specific. 

In any case, the Web Console section explains this in more details: https://docs.openshift.com/online/architecture/infrastructure_components/web_console.html#web-console-cli-downloads. 

@ahardin-rh - I am going to close this issue, but can you please take a look at the suggestion and see if it needs following up based on my explanation?
