### ISSUE TITLE
"SchedueldJob" typo in v3.9 release notes

### ISSUE THREAD

**Issue by oybed** [openshift/openshift-docs#8546]
### Which section(s) is the issue in?
OpenShift v3.9 Release notes / notable technical changes:
https://docs.openshift.com/container-platform/3.9/release_notes/ocp_3_9_release_notes.html#ocp-39-notable-technical-changes

### What needs fixing?
Typo twice `SchedueldJob` --> `ScheduledJob`

**Comment by vikram-redhat** [comment]
@bfallonf - PTAL.

**Comment by bfallonf** [comment]
Thanks @oybed . I've created a PR for this:

https://github.com/openshift/openshift-docs/pull/8547

And I've cherrypicked this into the 3.9 docs.

If there's anything else, please let us know. Closing this issue.
