### ISSUE TITLE
Document new nodes upgrade pre/mid/post hooks.

### ISSUE THREAD

**Issue by jtudelag** [openshift/openshift-docs#8549]
Document this new PR: https://github.com/openshift/openshift-ansible/pull/6816

### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/3.9/upgrading/automated_upgrades.html#upgrade-hooks

### What needs fixing?

Node hooks has to be added to the docs.

**Comment by vikram-redhat** [comment]
Since a PR has been created, I am going to close this issue.
