### ISSUE TITLE
possible header issue with "wildcard dns" in "deploying router" section

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-docs#856]
https://docs.openshift.com/enterprise/3.0/admin_guide/install/deploy_router.html#using-wildcard-dns

The environment prereq section does talk about wildcard DNS:
https://docs.openshift.com/enterprise/3.0/admin_guide/install/prerequisites.html#environment-requirements

Do we want to rename "using wildcard dns" to "using wildcard certificates"?

**Comment by sosiouxme** [comment]
Agreed, this is about wildcard certs, not DNS.

It would also be good to link to somewhere about setup for creating default
routes in that cloud domain. But I'm not sure we have that anywhere yet.
Looks like it's the routingConfig.subdomain field in master config.
