### ISSUE TITLE
[enterprise-3.9] Edit suggested in file architecture/infrastructure_components/kubernetes_infrastructure.adoc

### ISSUE THREAD

**Issue by mccormickt12** [openshift/openshift-docs#8571]
### Which section(s) is the issue in?
Overview

### What needs fixing?
The version of kubernetes and docker associated with this openshift version. The versions (openshift 3.9 with kubernetes 1.7 and docker 1.12) seems old and is contradictory to this document put out by redhat last week. https://access.redhat.com/articles/2176281

**Comment by vikram-redhat** [comment]
@ahardin-rh please close this issue when fixed.
