### ISSUE TITLE
[origin] asciibinder build has some warning

### ISSUE THREAD

**Issue by heshengbang** [openshift/openshift-docs#8593]
### Which section(s) is the issue in?
asciibinder build

### What needs fixing?

when i run `asciibinder build` , there is some warning like below:
`
asciidoctor: WARNING: image to embed not found or not readable: /home/heshengbang/Develop/github/openshift-docs/architecture/networking/images/nuageopenshift_mapping.png

asciidoctor: WARNING: image to embed not found or not readable: /home/heshengbang/Develop/github/openshift-docs/architecture/networking/images/nuageopenshift_mapping.png
`
it seems like picture's directory is too deep for asciibinder to find the picture.

I don't know if those warning will influence the docs pages, but my local page run in nginx is wrong layout.

**Comment by vikram-redhat** [comment]
Thanks @heshengbang - this is not a docs issue, but how asciibinder builds. I suggest reading the asciibinder docs.
