### ISSUE TITLE
example text in many of the day 2 operations has asterix around the text which I believe was transposed from the intended BOLD that ascii uses

### ISSUE THREAD

**Issue by mwitzenm** [openshift/openshift-docs#8601]
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/3.9/day_two_guide/host_level_tasks.html

### What needs fixing?
It appears references like the one listed below intend to be in bold when it gets transposed to just *master-0.example.com*.  There are many of them in the day to operations.  When people are copy and pasting this type of content they adjust for hostnames but don't always look beyond that simple change in the command

# ETCDCTL_API=3 etcdctl --cert="/etc/etcd/peer.crt" \
          --key=/etc/etcd/peer.key \
          --cacert="/etc/etcd/ca.crt" \
          --endpoints="https://*master-0.example.com*:2379,\
            https://*master-1.example.com*:2379,\
            https://*master-2.example.com*:2379,\
            https://*etcd0.example.com*:2379"\
            endpoint health

**Comment by bfallonf** [comment]
Thanks @mwitzenm 

I've had this feedback from another source, and I'm fixing it with #8620 . I'll close this issue, and reference this from there. If you have any more suggestions, please let us know.
