### ISSUE TITLE
deployment config has unclear API doc for triggers

### ISSUE THREAD

**Issue by akostadinov** [openshift/openshift-docs#8610]
There is unclear behavior on [deployment config object schema API docs](https://docs.openshift.org/latest/rest_api/oapi/v1.DeploymentConfig.html#object-schema).

If one clicks on `triggers` then:

- `type` has strange indentation
- no list of possible values for `type`
- there is also little to no information about `imageChangeParams` properties

**Comment by vikram-redhat** [comment]
@jim-minter - are you still working on the API docs?

**Comment by jim-minter** [comment]
@vikram-redhat no, I'm on a different team at this point.  But AFAICS the majority of fixing @akostadinov's issues should be a straightforward case of improving the struct documentation in origin.
