### ISSUE TITLE
Origin docs for 3.7 and 3.9 missing from docs.openshift.org

### ISSUE THREAD

**Issue by leoluk** [openshift/openshift-docs#8611]
Documentation for the latest releases is missing:

![image](https://user-images.githubusercontent.com/859697/38367708-bc54195c-38e3-11e8-91ce-7d39f939b437.png)

**Comment by vikram-redhat** [comment]
Fixed via: https://github.com/openshift/openshift-docs/pull/8686 and https://github.com/openshift/openshift-docs/pull/8687. Closing this issue.
