### ISSUE TITLE
[enterprise-3.7] Edit suggested in file release_notes/ocp_3_7_release_notes.adoc

### ISSUE THREAD

**Issue by bortek** [openshift/openshift-docs#8621]
### Which section(s) is the issue in?
3.7.42 has been released but release notes are not updated(yet) . Can you please update ?

**Comment by vikram-redhat** [comment]
This was updated on the 7th: https://docs.openshift.com/container-platform/3.7/release_notes/ocp_3_7_release_notes.html#ocp-3-7-42-2
