### ISSUE TITLE
sed: can't read .git/config: No such file or directory

### ISSUE THREAD

**Issue by heshengbang** [openshift/openshift-docs#8632]
### Which section(s) is the issue in?
When I run below command 
`s2i build https://github.com/openshift/openshift-docs.git openshift/asciibinder-018-centos7 openshift-docs`
 , here is a error occured:

```
sed: can't read .git/config: No such file or directory
Build failed
ERROR: An error occurred: non-zero (13) exit code from openshift/asciibinder-018-centos7
```
The truth is .git directory is exist, and the config file is also exist.

I found it where the error happened in  [assemble](https://github.com/openshift/openshift-docs/blob/master/.s2i/bin/assemble) .

I think this may be a bug?

### What needs fixing?
I think this should be fix, and so s2i can build success.

**Comment by vikram-redhat** [comment]
Hey @heshengbang - I am going to close this as this is not a docs issue. To build the docs locally, just use 

> asciibinder build

.
