### ISSUE TITLE
[enterprise-3.7] Edit suggested in file release_notes/ocp_3_7_release_notes.adoc

### ISSUE THREAD

**Issue by bortek** [openshift/openshift-docs#8639]
### Which section(s) is the issue in?
This image called openshift3/ose-base does not seem to exist but still it is present in every new image advisory like this one
https://access.redhat.com/errata/RHBA-2018:0637

Can you please review and remove it?

**Comment by vikram-redhat** [comment]
@ahardin-rh we can't republish errata, but we can perhaps make a note in the release notes?

**Comment by bortek** [comment]
That should do for this release but please make sure this is removed from the future erratas and release notes. Thanks.

**Comment by ahardin-rh** [comment]
Closing, as this has been addressed in newer releases.
