### ISSUE TITLE
Missing instructions on how to authenticate to MongoDB

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/openshift-docs#866]
https://docs.openshift.org/latest/using_images/db_images/mongodb.html

> ```
> $ oc exec -it -p <pod> -c <container> /bin/bash -c mongo
> To enter a container from the host:
> 
> $ oc exec -it -p <pod> -c <container> /bin/bash
> ```

After running `mongo` in the container, you need to authenticate to do anything useful.

**Comment by vikram-redhat** [comment]
BZ Created: https://bugzilla.redhat.com/show_bug.cgi?id=1258348
