### ISSUE TITLE
Use `oc rsh` instead of `oc exec` where appropriate

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/openshift-docs#867]
E.g.:
https://docs.openshift.org/latest/using_images/db_images/mongodb.html

> ```
> $ oc exec -it -p <pod> -c <container> /bin/bash -c mongo
> To enter a container from the host:
> 
> $ oc exec -it -p <pod> -c <container> /bin/bash
> ```

For interactive shell in a container, we have now `oc rsh`. We could describe the steps as:

```
(local) $ oc get pods
.... pick your pod name ....
(local) $ oc rsh <pod-name>
(container) $ mongo
```

**Comment by vikram-redhat** [comment]
BZ Created: https://bugzilla.redhat.com/show_bug.cgi?id=1258348
