### ISSUE TITLE
Set Namespace Annotation to an Empty String for Daemonset in 3.7 Also

### ISSUE THREAD

**Issue by mburke5678** [openshift/openshift-docs#8674]
Per email from [Jorge Luis Tudela Gonzalez de Riancho](https://mojo.redhat.com/people/jtudelag)

In 3.9 a very helpful note has been added to the DS docs:

Daemonset scheduling is incompatible with project’s default node selector. If you fail to disable it, the daemonset gets restricted by merging with the default node selector. This results in frequent pod recreates on the nodes that got unselected by the merged node selector, which in turn puts unwanted load on the cluster.
Therefore,

1.  Before you start using daemonsets, disable the default project-wide node selector in your namespace, by setting the namespace annotation openshift.io/node-selector to an empty string:

```
# oc patch namespace myproject -p \
    '{"metadata": {"annotations": {"openshift.io/node-selector": ""}}}'
```

If you are creating a new project, overwrite the default node selector using

`oc adm new-project --node-selector="".`

**This is valid for 3.7.42 too, I have tested it myself. IMHO it should be included in the 3.7 docs as well.**
**But I'm not sure if the behaviour in the 3.7.42 is the expected one or not, we better validated that with Engineering before updating the docs.**

Cheers.
Thanks!!!

https://docs.openshift.com/container-platform/3.7/dev_guide/daemonsets.html

**Comment by mburke5678** [comment]
@tnozicka @geliu2016
Should this go into 3.7 also? Or any other OpenShift versions?

Related to https://github.com/openshift/openshift-docs/pull/8125

**Comment by mburke5678** [comment]
@tnozicka @geliu2016 BUMP

**Comment by tnozicka** [comment]
Feel free to backport it as far as we support DaemonSet as this has been the issue since the beginning.

**Comment by mburke5678** [comment]
@openshift/team-documentation PTAL. Backported DaemonSet note that was added to 3.9 back to 3.2, when the _Using Daemonsets_ topic was added.  
3.2: https://github.com/openshift/openshift-docs/pull/8770
3.3: https://github.com/openshift/openshift-docs/pull/8771
3.4: https://github.com/openshift/openshift-docs/pull/8772
3.5: https://github.com/openshift/openshift-docs/pull/8773
3.6: https://github.com/openshift/openshift-docs/pull/8774
3.7: https://github.com/openshift/openshift-docs/pull/8775
