### ISSUE TITLE
Expanding the hierarchy of sections scrolls the page to the top

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/openshift-docs#871]
It's annoying when you click on the arrows to expand some section and you lose context because you're scrolled to the top as you click.
(the click event should not bubble up to fire the action of browsing to "#")

How to reproduce:

1. Browse to https://docs.openshift.org/latest/dev_guide/builds.html or any other page in the docs.
  ![selection_023](https://cloud.githubusercontent.com/assets/88819/9195386/c2bad900-4022-11e5-8472-361d225c90a0.png)

2. Click to expand a section, the browser scrolls to the top:
  ![selection_024](https://cloud.githubusercontent.com/assets/88819/9195399/dc875bba-4022-11e5-9e82-1c3408a0494b.png)

3. Expected:
  ![selection_025](https://cloud.githubusercontent.com/assets/88819/9195402/e4efd66a-4022-11e5-8ef2-94fd35d4fa15.png)

Browsers: Chrome, Firefox (possibly all others)
OS: Fedora 22

**Comment by bfallonf** [comment]
This was fixed in the 3.1 release in PR #1223
