### ISSUE TITLE
update prereqs

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-docs#872]
* not all repos are required to install ose
* minimum requirements are:
    * rhel-7-server-ose-3.0-rpms
    * rhel-7-server-rpms
* in order to install ansible, you require the epel as documented, but you also require:
    * rhel-7-server-optional-rpms

**Comment by thoraxe** [comment]
rhel-7-server-extras-rpms is required for installing stand-alone etcd.

**Comment by adellape** [comment]
@thoraxe See https://github.com/openshift/openshift-docs/pull/875 for removal of optional repo from docs.

**Comment by thoraxe** [comment]
@adellape that's my point -- you need optional to install Ansible if you're using the advanced installer. If you're using the quick installer we compile Ansible for you.

So, this docs bug is more about further adjustment to which repos are required under which circumstances.

1) we could have a single reqs/repos section that indicates which repos are required when
2) we could have a repos section for each installation method and its various options

Just kinda thinking out loud...

**Comment by adellape** [comment]
@thoraxe 

> you need optional to install Ansible if you're using the advanced installer.

My understanding is no install method requires the optional channel any longer, as discussed in https://github.com/openshift/openshift-docs/pull/875 and https://github.com/openshift/openshift-ansible/pull/410#discussion-diff-36826898 (followed up with Scott). But let me know if I'm missing something.

> So, this docs bug is more about further adjustment to which repos are required under which circumstances.

Per this issue, I went through state of the repos yesterday. Stand-alone etcd does come from extras, but so does docker (also https://github.com/openshift/openshift-docs/pull/875#issuecomment-130371316), so the conclusion seemed that it wasn't really worth pointing out further differentiation between repos/circumstances (right now we call out rhel-ha-for-rhel-7-server-rpms as a special requirement for multi-master scenarios). If all basic requirements like the docker package move out of extras at some point, then it would be worth splitting hairs more. Again, let me know if I'm missing something or if my testing in https://github.com/openshift/openshift-docs/pull/875#issuecomment-130371316 was flawed.

(I meant to telegraph this better yesterday but apparently only ever put in the above terse comment https://github.com/openshift/openshift-docs/issues/872#issuecomment-130371459, apologies.)

**Comment by thoraxe** [comment]
@adellape I think we're conflating "using the installer" with "the remote systems".

If you are running Ansible from an EL7 system then you require the optional repo in order to get the Ansible python dependencies.

Is the Docker daemon in extras *and* the OSE channel, or only extras?

**Comment by adellape** [comment]
> If you are running Ansible from an EL7 system then you require the optional repo in order to get the Ansible python dependencies.

Sorry, you're right, I see now python-jinja2 (only available in extras) is a dep for ansible.

> Is the Docker daemon in extras and the OSE channel, or only extras?

Only in extras, AFAIK. https://access.redhat.com/downloads/content/69/ver=/rhel---7/7.1/x86_64/packages

**Comment by thoraxe** [comment]
:+1:

**Comment by adellape** [comment]
> python-jinja2 (only available in extras)

Mispoke again: it's in extras and optional.

**Comment by thoraxe** [comment]
I could have sworn I needed optional for something. I just can't figure it out right now.

**Comment by adellape** [comment]
> Is the Docker daemon in extras and the OSE channel, or only extras?

Yeesh, more mispeakings. I thought you said "extras and the base channel". Docker _is_ in the OSE channel, but it's an older version. After GA, the version of Docker in the RHEL extras channel (currently 1.7.1) quickly surpassed the version in the OSE repo (1.6.2), and that's the one OSE is using now.

**Comment by adellape** [comment]
@thoraxe Merged https://github.com/openshift/openshift-docs/pull/875 to remove mention of Optional (which is no longer needed). Per discussion yesterday, I don't think there's any further distinctions that need to be made right now between installation methods given the current lay of the repo/package land (other than for the HA master scenario). Just verified again here, installing Ansible clean on RHEL7:

https://gist.github.com/adellape/32f2088abc0169273b66

For the python dependencies, python-jinja2 came from extras, a couple from base rhel, and the rest from epel (none of which were available in optional). If package requirements/locations change in the future, we can adjust the prereq instructions.

LMK if you feel this can be closed.

**Comment by thoraxe** [comment]
LGTM.
