### ISSUE TITLE
[enterprise-3.9] Edit suggested in file install_config/persistent_storage/persistent_storage_glusterfs.adoc

### ISSUE THREAD

**Issue by dmesser** [openshift/openshift-docs#8731]
### Which section(s) is the issue in?

Example: CONTAINER-NATIVE STORAGE FOR OPENSHIFT LOGGING AND METRICS
Point 6:

### What needs fixing?

Currently it is advised to use 
openshift_metrics_storage_kind=dynamic

This will result in the following error if you do not have `openshift_cloudprovider_kind` configured:

```
TASK [openshift_sanitize_inventory : Ensure that dynamic provisioning is set if using dynamic storage] ************* Friday 13 April 2018 10:27:35 +0000 (0:00:00.078) 0:00:01.990 ********** fatal: [master.internal.aws.testdrive.openshift.com]: FAILED! => {"changed": false, "msg": "Using a storage kind of 'dynamic' without enabling dynamic provisioning nor\nsetting a cloud provider will cause generated PVCs to not be able to bind as\nintended. Either update to not use a dynamic storage or set\nopenshift_master_dynamic_provisioning_enabled to True and set an\nopenshift_cloudprovider_kind. You can disable this check with\n'dynamic_volumes_check=False'."}
```

I do not agree with this behavior, see https://github.com/openshift/openshift-ansible/issues/7944

But for now we need to give users a hint on this dependency.

**Comment by vikram-redhat** [comment]
@jarrpa - can you take a look? 

cc: @tmorriso-rh

**Comment by tmorriso-rh** [comment]
Bump. @jarrpa Can you take a look at this PR? Thanks.

**Comment by jarrpa** [comment]
Apologies for the delay!

There is currently no problem with the documentation. We only tell users to add the relevant parameters for running the Logging and Metrics playbooks, not the main config playbook.

Also, note, that you don't NEED to set cloudprovider_kind, you can also simply use a variable to enable dynamic provisioning in general.

**Comment by vikram-redhat** [comment]
Thanks @jarrpa . I will close this issue in that case.

**Comment by dmesser** [comment]
> On 18. Apr 2018, at 04:35, Jose A. Rivera <notifications@github.com> wrote:
> 
> Apologies for the delay!
> 
> There is currently no problem with the documentation. We only tell users to add the relevant parameters for running the Logging and Metrics playbooks, not the main config playbook.
> 

This does not address the issue. The instructions need to be self-contained. As explained in the linked GitHub there is an undocumented dependency on the openshift_cloudprovider_kind variable in the processing of Metrics playbook with the openshift_metrics_storage_kind=dynamic in conjunction with GlusterFS (or any dynamically provisioned storage). This dependency is not explained in the docs and without this variable it will always fail. I only got it to work by either setting openshift_cloudprovider_kind or instead removing ‘openshift_metrics_storage_kind’ and replace it with 'openshift_metrics_cassandra_storage_type=dynamic'

> Also, note, that you don't NEED to set cloudprovider_kind, you can also simply use a variable to enable dynamic provisioning in general.
> 
See above. As with the docs in the current state you do need to set this variable to either ‘none’ or any of the supported cloud providers as seen here <https://github.com/openshift/openshift-ansible/blob/8ec7fd951088827ef2622140bde45bb175cdd199/roles/openshift_management/tasks/storage/storage.yml#L3> otherwise the deployment will fail. The check on this variable is part of list of checks which all need to yield true, as seen here <https://github.com/openshift/openshift-ansible/blob/664d655f8d7808e1dae513f5949eb62601fe4e26/roles/openshift_sanitize_inventory/tasks/unsupported.yml#L31-L34>.

**Comment by jarrpa** [comment]
And this happens when you run the main playbook without these variables set and then run the logging and metrics playbooks with the variables set? If so then I can just change the metrics_storage_kind to casasandra_storage_type.
