### ISSUE TITLE
Deploying Registry steps

### ISSUE THREAD

**Issue by JayKayy** [openshift/openshift-docs#876]
I recently came across trying to create a registry using the step located in the docs:
oadm registry --config=/etc/openshift/master/admin.kubeconfig 
    --credentials=/etc/openshift/master/openshift-registry.kubeconfig 
    --images='registry.access.redhat.com/openshift3/ose-${component}:${version}'

The ${components/version} variables were not set resulting in my pod failing to pull image 'registry.access.redhat.com/openshift3/ose-:'.

 Removing the --image parameter fixed this and pulled the docker-registry:v3.0.1.0. However, in the docs it says it a required parameter.

Are ${component}:${version} not necessary anymore? Docs may need to be updated.
https://access.redhat.com/documentation/en/openshift-enterprise/version-3.0/openshift-enterprise-30-administrator-guide/chapter-1-installing

**Comment by adellape** [comment]
My understanding is that is true as of OSE 3.0.1; will verify.

**Comment by vikram-redhat** [comment]
BZ created: https://bugzilla.redhat.com/show_bug.cgi?id=1259562. Closing this issue.
