### ISSUE TITLE
[enterprise-3.7] Edit suggested in file upgrading/automated_upgrades.adoc

### ISSUE THREAD

**Issue by bortek** [openshift/openshift-docs#8782]
Guys,

there are no RPM  packages with version 3.7.42-2 but there is 3.7.42-1. Please confirm and correct if possible.

https://docs.openshift.com/container-platform/3.7/release_notes/ocp_3_7_release_notes.html#ocp-3-7-42-2

Thanks!

**Comment by vikram-redhat** [comment]
@ahardin-rh - can you have a look?

**Comment by ahardin-rh** [comment]
We call the release whatever the image tag version is. That is was other sections of our documentation that use that number are using it for.
