### ISSUE TITLE
unrecognized apb argument listed

### ISSUE THREAD

**Issue by scollier** [openshift/openshift-docs#8857]
### Which section(s) is the issue in?

https://access.redhat.com/documentation/en-us/openshift_container_platform/3.9/html-single/ansible_playbook_bundle_development_guide/#writing-apbs

section 2.3.1

### What needs fixing?

When running apb push following the docs, you get:

```
$ apb push -o --namespace alertmanager-apb/
usage: apb [-h] [--debug] [--project BASE_PATH]
           
           {relist,run,help,test,prepare,setup,bootstrap,list,remove,init,version,build,push,serviceinstance}
           ...
apb: error: unrecognized arguments: -o
```

stating that the ```-o``` is not recognized.

**Comment by scollier** [comment]
adding my apb version:

```
$ apb version
Version: apb-1.1.15

$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.5 (Maipo)
```

**Comment by bit4man** [comment]
Replicated, RHEL 7.5

**Comment by vikram-redhat** [comment]
Fixed via: https://github.com/openshift/openshift-docs/pull/10718
