### ISSUE TITLE
apb builds need sudo

### ISSUE THREAD

**Issue by scollier** [openshift/openshift-docs#8858]
### Which section(s) is the issue in?

https://access.redhat.com/documentation/en-us/openshift_container_platform/3.9/html-single/ansible_playbook_bundle_development_guide/#writing-apbs

Section 2.3.1

### What needs fixing?

The docs show:

```
$ apb init my-new-apb
$ cd my-new-apb
$ apb build
$ apb push --openshift
$ apb list
```

implying that you can run these commands as a non-root user by default on a RHEL 7.5 host.  When I run the build, I get:

```
$ apb build
Finished writing dockerfile.
Building APB using tag: [my-test-apb]
Error accessing the docker API. Is the daemon running?
Exception occurred! Error while fetching server API version: ('Connection aborted.', error(13, 'Permission denied'))
```
That can be worked around by using sudo.

**Comment by scollier** [comment]
I should add my apb version:

```
$ apb version
Version: apb-1.1.15
```

**Comment by vikram-redhat** [comment]
@adellape - is this something you can look at?

**Comment by vikram-redhat** [comment]
@adellape - can you please update this or close if no longer relevant?
