### ISSUE TITLE
Deployment resources: explain difference between "limits" and "requests"

### ISSUE THREAD

**Issue by ge0ffrey** [openshift/openshift-docs#8901]
The section here:
  https://docs.openshift.com/online/dev_guide/deployments/basic_deployment_operations.html#deployment-resources
doesn't explain the difference between "limits" and "requests" decently. 

Does it make sense to use both at the same time? What's the difference? What's the impact/behaviour? What will determine the amount of memory a pod actually gets?

**Comment by vikram-redhat** [comment]
Hey @ge0ffrey ! Long time since working on the BxMS docs!

@ahardin-rh - PTAL.

**Comment by ahardin-rh** [comment]
@pecameron Can you please help me tighten up the content here, or point me in the right direction?

**Comment by pecameron** [comment]
@ahardin-rh In my reading of this, liimits: is optional and is used for general resource limits. However when a quota is specified (don't know where that is done), requests: is required to set a limit. Maybe pointing to the general discussions of limits and quotas, if they exist, would be helpful. If they don't exist the sections should be written. Depending on the limits, and quotas discussions, it may be useful to separate this into two sections, augmenting each discussion.
FWIW The above is my personal rambling. I have not worked with limits or quotas and don't really know what they do so this may be wildly wrong.

**Comment by ahardin-rh** [comment]
@pecameron Thanks! I opened https://github.com/openshift/openshift-docs/pull/9182 to add a pointer to the appropriate docs. I will work with others to see if the information presented there needs to be expanded to fully answer the questions posed here. :beers:
