### ISSUE TITLE
Typos in Minishift architecture doc

### ISSUE THREAD

**Issue by fanminshi** [openshift/openshift-docs#8907]
### Which section(s) is the issue in?

https://docs.openshift.org/latest/minishift/using/basic-usage.html

### What needs fixing?

`Failed to generate image: Could not find Java executable` appears in the Minishift architecture
 diagram. I don't think it is intentional.

**Comment by vikram-redhat** [comment]
@fanminshi - could you raise this issue with the MiniShift team? https://github.com/minishift/minishift#community
