### ISSUE TITLE
Adding Nodes needs to be updated with certificate creation/installation

### ISSUE THREAD

**Issue by sdodson** [openshift/openshift-docs#899]
This alone won't successfully add a node now that we require certificates. I don't have a good reference for how to do this manually however.

https://github.com/openshift/openshift-docs/blob/master/admin_guide/manage_nodes.adoc#adding-nodes

**Comment by thoraxe** [comment]
For non-Ansible-driven node additions, I think this is it (based on input from @rajatchopra)

1. Install software on node (eg yum -y install openshift-node)
1. Configure docker on new node to match existing nodes
1. Configure firewall on new node appropriately
1. Prepare new node's configuration, on the master:
```
 openshift admin create-node-config \
      --node-dir="<target_config_location>" \
      --node="${NODE_HOSTNAME}" \
      --hostnames="${NODE_HOSTNAME}" \
      --master="https://${MASTER_IP}:8443" \
      --network-plugin="redhat/openshift-ovs-subnet" \
      --node-client-certificate-authority="${CERT_DIR}/ca.crt" \
      --certificate-authority="${CERT_DIR}/ca.crt" \
      --signer-cert="${CERT_DIR}/ca.crt" \
      --signer-key="${CERT_DIR}/ca.key" \
      --signer-serial="${CERT_DIR}/ca.serial.txt" \
      --volume-dir="${VOLUMES_DIR}"
```
where, CERT_DIR is the directory where master's configuration is stored.

1. Copy the config dir as created above (<target_config_location>) to the node that wants to join the cluster

1. On new node `systemctl start openshift-node`

**Comment by vikram-redhat** [comment]
created BZ (https://bugzilla.redhat.com/show_bug.cgi?id=1258333) to track this work.
