### ISSUE TITLE
[enterprise-3.3] "opensfhit" typo in install_config/configuring_routing.adoc

### ISSUE THREAD

**Issue by jiri-fiala** [openshift/openshift-docs#9000]
### Which section(s) is the issue in?
Configuring route timeouts -> [`myroute` example](https://docs.openshift.com/container-platform/3.3/install_config/configuring_routing.html#install-config-configuring-route-timeouts) - (only the OCP 3.3 branch, this was already addressed in 3.4+ [before](https://github.com/openshift/openshift-docs/commit/3111f52478c619554b570bcb8e63a0a69d3e947b))

### What needs fixing?
The typo in `haproxy.router.opensfhit.io`

**Comment by gaurav-nelson** [comment]
Fixed by #9141
