### ISSUE TITLE
[enterprise-3.7] Edit suggested in file dev_guide/expose_service/expose_internal_ip_nodeport.adoc

### ISSUE THREAD

**Issue by c0rmichels** [openshift/openshift-docs#9005]
### Which section(s) is the issue in?
*Defining the Public IP Range*. 

### What needs fixing?
The entire section seems out of place for nodeport configurations as it is not necessary (at least not in my experience). I suggest removing this section from this part of the guide (obviously not from the part that explains how to use **External IP** configurations). Here, it only confuses the reader, since nowhere in the following section(s) there is any reference to this CIDR range.

**Comment by vikram-redhat** [comment]
@bfallonf - if you have bandwidth in this release, PTAL.

**Comment by bfallonf** [comment]
Thanks @c0rmichels . I've received a few comments about this section recently, so I've started #9439 to gather them together and get the sections fixed up.

Because a PR exists, I'll close this issue, but please comment here or in the PR if you have any more notes.
