### ISSUE TITLE
Running commands as Cluster Admin

### ISSUE THREAD

**Issue by slaskawi** [openshift/openshift-docs#910]
It seems that some of the command should contain additional `--config=/etc/openshift/master/admin.kubeconfig` in https://docs.openshift.com/enterprise/3.0/admin_guide/install/docker_registry.html#deploy-registry.

Otherwise the user will get similar to `Error from server: error when creating "STDIN": User "admin" cannot create serviceaccounts in project "default"`

**Comment by nak3** [comment]
@slaskawi Could you please tell us what command did you get the error?
