### ISSUE TITLE
include yum-utils as base package

### ISSUE THREAD

**Issue by slmagus** [openshift/openshift-docs#9106]
### Which section(s) is the issue in?

Hostprep 

2.3.4. Installing Base Packages Step 1.

### What needs fixing?

Need to include yum-utils for RH7 host system as a required package.
Not having the package generates errors when running the playbook, and as it isn't universally installed on a base RHEL system

**Comment by vikram-redhat** [comment]
@kalexand-rh - can you take a look. I thought we did include this.

**Comment by kalexand-rh** [comment]
@vikram-redhat, that command lists several utils packages, but not yum-utils. I opened a PR to add it: https://github.com/openshift/openshift-docs/pull/9121.
