### ISSUE TITLE
[enterprise-3.0] Edit suggested in file dev_guide/application_health.adoc

### ISSUE THREAD

**Issue by alonkashtan** [openshift/openshift-docs#9145]
### Which section(s) is the issue in?
Under **HTTP Checks** subsection it is stated:

> The check is deemed successful if the hook returns with **_200 or 399_**

### What needs fixing?
According to the [Kubernetes documentation](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#define-a-liveness-http-request) it should say:
> The check is deemed successful if the hook returns with **_between 200 to 399_**

**Comment by gaurav-nelson** [comment]
fixed by #9197
