### ISSUE TITLE
[online] Update OpenShift Online Docs to Remove References to HA Configuration

### ISSUE THREAD

**Issue by uriux-andrewd** [openshift/openshift-docs#9164]
Edit suggested in file architecture/infrastructure_components/kubernetes_infrastructure.adoc

### Which section(s) is the issue in?

[Kubernetes Infrastructure https://docs.openshift.com/online/architecture/infrastructure_components/kubernetes_infrastructure.html](https://docs.openshift.com/online/architecture/infrastructure_components/kubernetes_infrastructure.html)

>Documentation  /  OpenShift Online 3  / Architecture / Infrastructure Components / Kubernetes Infrastructure

Overview & High Availability Sections

### What needs fixing?

The documentation suggests that you can optionally configure High Availability by modifying the runbook.

This is not applicable to OpenShift Online, so all similar references should be removed or modified to clarify that High Availability cannot be configured for OpenShift Online in the manner described.

Specifically:

- (Overview Section)
   - You can optionally configure your masters for high availability (HA) to ensure that the cluster has no single point of failure.
- High Availability Section
   - A runbook entry should be created for reconstructing the master

**Comment by vikram-redhat** [comment]
@ahardin-rh - PTAL

**Comment by ahardin-rh** [comment]
Addressed in https://github.com/openshift/openshift-docs/pull/9250
