### ISSUE TITLE
Ansible variable (openshift_metrics_hawkular_hostname ) format is vague.

### ISSUE THREAD

**Issue by Jooho** [openshift/openshift-docs#9214]
### Which section(s) is the issue in?
Advanced installation - Configuring Cluster Metrics

### What needs fixing?
./install_config/install/advanced_install.adoc#1476
```
The metrics public URL can be set during cluster
installation using the `openshift_metrics_hawkular_hostname` Ansible variable,
which defaults to:

`\https://hawkular-metrics.{{openshift_master_default_subdomain}}/hawkular/metrics`
```
This part sound like we can specify `openshift_metrics_hawkular_hostname` with this format:
```
openshift_metrics_hawkular_hostname=https://hawkular-metrics.{{openshift_master_default_subdomain}}/hawkular/metrics
```
However, in the reality, the protocol must be removed  and also `/hawkular/metrics` as well so the actual value for default would be below:
```
openshift_metrics_hawkular_hostname=hawkular-metrics.{{openshift_master_default_subdomain}}
```
Therefore, giving the ansible default value for the variable could clear the ambiguous.

----
The metrics public URL can be set during cluster
installation using the `openshift_metrics_hawkular_hostname` Ansible variable,
which defaults to:

`\https://hawkular-metrics.{{openshift_master_default_subdomain}}/hawkular/metrics`

If you alter this variable, ensure the host name is accessible via your router.

`openshift_metrics_hawkular_hostname=hawkular-metrics.{{openshift_master_default_subdomain}}`

----

**Comment by vikram-redhat** [comment]
Thanks @Jooho - I am closing this issue now that your PR has merged.
