### ISSUE TITLE
[enterprise-3.9] Edit suggested in file admin_guide/scheduling/pod_placement.adoc

### ISSUE THREAD

**Issue by jmaerki** [openshift/openshift-docs#9257]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/3.9/admin_guide/scheduling/pod_placement.html#controlling-pod-placement-projects
Point 3 under "Control Pod Placement to Projects"

### What needs fixing?

Section still mentions "scheduler.alpha.kubernetes.io/node-selector" but should probably be "openshift.io/node-selector" as mentioned in https://docs.openshift.com/container-platform/3.9/admin_guide/managing_projects.html#setting-the-project-wide-node-selector under "Setting the Project-wide Node Selector".

**Comment by mburke5678** [comment]
@aveshagarwal 
The Scheduling Guide _Controlling Pod Placement_ section uses the Pod Node Selector admission controller, which uses the `scheduler.alpha.kubernetes.io/node-selector` annotation.
The _Setting the Project-wide Node Selector_ uses the `oc adm new-project` with the `--node-selector` option. This uses the `openshift.io/node-selector` annotation. 
Do we have this right? 
We have these steps the same for Container Platform and Origin. Should the processes be the same for both?

**Comment by aveshagarwal** [comment]
@mburke5678 there are 2 admission plugins doing same thing: PodNodeSelector and "NodeEnv" . NodeEnv (part of origin) uses `openshift.io/node-selector` and that means if someone is setting project node selector using  `oc adm new-project`, should use NodeEnv. PodNodeSelector (upstream one) uses scheduler.alpha.kubernetes.io/node-selector, so if someone wants to use `PodNodeSelector`, would have to edit a project directory via "oc edit" to set `scheduler.alpha.kubernetes.io/node-selector`. 

So you could update the docs along the above. Please let me know if its not clear.

**Comment by aveshagarwal** [comment]
commented directly on https://github.com/openshift/openshift-docs/pull/9417.
