### ISSUE TITLE
needs docs on moving ports after installation

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-docs#936]
We may want to provide some documentation about moving the ports (console, api, etc) after the installation is finished. I'm not really convinced it's very important, but the question has come up now and again.

**Comment by mburke5678** [comment]
@thoraxe Is this still an issue that we want to pursue? If so, who might be a good resource for info?

**Comment by thoraxe** [comment]
Not sure who a good resource would be. Someone on Group 1 for sure. 

Whether or not we want to document this hinges on whether or not we want to support it. Probably want to talk to a combination of Productization and CEE.
