### ISSUE TITLE
Various edits discovered when working with translators

### ISSUE THREAD

**Issue by mburke5678** [openshift/openshift-docs#9389]
When I was answering issues posed by translators on the Development Guide, I found issues that can be fixed in the source docs. Each issue is a separate comment below.

**Comment by mburke5678** [comment]
This sentence missing an "is"
The load balancer a single edge router IP 

Should be:
The load balancer is a single edge router IP

Also, awaiting clarification on the sentence from Phil Cameron for translators:
"Could you help clarify the sentences? What is still a single machine for initial load balancing and what doe the load balancer do to a single edge router IP?"

https://docs.openshift.com/container-platform/3.9/dev_guide/expose_service/expose_internal_ip_load_balancer.html

**Comment by mburke5678** [comment]
Could this be clearer?

"From the project to which the service account belongs, use the <literal>-z</literal> flag and specify the <literal>&lt;serviceaccount_name&gt;</literal>. This is highly recommended, as it helps prevent typos and ensures that access is granted only to the specified service account."
Translator: "I wonder why it helps prevent typos."

Me:
About the "prevent typos", there was a case where a customer used a semi-colon (;) instead of a colon (:) when using the `oc policy add-role-to-user` command. The command did not work as expected. Using `oc policy add-role-to-user -z` eliminates the need to use the colons. To me, the -z does not prevent typos, but reduces the chance of a typo that will cause bad results.

Link for ^^
https://docs.openshift.com/container-platform/3.9/admin_guide/service_accounts.html#admin-sa-user-names-and-groups

**Comment by mburke5678** [comment]
"then the version of secret will be used for the pod will not be defined"
Needs to be clarified.

https://docs.openshift.com/container-platform/3.9/dev_guide/secrets.html#secrets-and-the-pod-lifecycle

**Comment by mburke5678** [comment]
"An image tag always points to the latest image built. "
https://docs.openshift.com/container-platform/3.9/dev_guide/managing_images.html#tag-naming
BenP: An image tag always points to a single image, normally the latest version of the image that was built.  The tag also tracks the history of image versions it previously pointed to.

**Comment by vikram-redhat** [comment]
Closing this as @mburke5678 has done the fixes via #9280
