### ISSUE TITLE
Missing value for ImagePolicy.resolutionRules.policy.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/openshift-docs#9403]
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/3.9/admin_guide/image_policy.html#image-policy-configuring-the-image-policy-admission-plug-in

### What needs fixing?

If you use the example ``ImagePolicy`` config example it will fail.

```
F0518 05:10:28.629994   30168 start_allinone.go:99] Server could not start: Couldn't init admission plugin "openshift.io/ImagePolicy": [openshift.io/ImagePolicy.resolutionRules[0].policy: Required value: a policy must be specified for this resource, openshift.io/ImagePolicy.resolutionRules[1].policy: Required value: a policy must be specified for this resource]
```

The error suggests example is missing:

```
ImagePolicy.resolutionRules.policy
```

entries.

Looks like needs to have:

```
policy: AttemptRewrite
```

entry as policy to avoid error.

This needs to be confirmed by someone in the know as it is a guess that is what is required.

**Comment by GrahamDumpleton** [comment]
@bparees suggests this may be a code issue with inheritance of value from outer scope. Separate issue created for it at https://github.com/openshift/origin/issues/19775 for confirmation.

**Comment by vikram-redhat** [comment]
@GrahamDumpleton closing this since https://github.com/openshift/origin/issues/19775 is lodged. If examples still need updating, please reopen.

**Comment by bparees** [comment]
i think the docs should be updated to show an explicit policy value regardless.  i've opened a PR to do that here: https://github.com/openshift/openshift-docs/pull/9438
