### ISSUE TITLE
Document login template configuration option

### ISSUE THREAD

**Issue by spadgett** [openshift/openshift-docs#945]
See https://github.com/openshift/origin/pull/4465

Document new `oauthConfig.templates.login` master configuration option for customizing the login page.

**Comment by bmcelvee** [comment]
Looks like this has been documented: https://docs.openshift.org/latest/install_config/web_console_customization.html#customizing-the-login-page. I'm going ahead and closing this issue. Please let me know if additional documentation needs to be provided.
