### ISSUE TITLE
[enterprise-3.9] Edit suggested in file dev_guide/pod_autoscaling.adoc

### ISSUE THREAD

**Issue by logandonley** [openshift/openshift-docs#9552]
### Which section(s) is the issue in?

Starting at 'Autoscaling for CPU Utilization' and beyond.

### What needs fixing?

The apiVersions set in the examples do not align with what is available in the REST API Reference docs.

**Comment by vikram-redhat** [comment]
@logandonley. Unfortunately, the REST API docs are currently out of sync and we are trying to figure out a way to keep those docs updated. For the moment, I am going to close this issue as something we don't have the bandwidth to fix.
