### ISSUE TITLE
Scheduler configurable precidates section is not accurate

### ISSUE THREAD

**Issue by jtudelag** [openshift/openshift-docs#9598]
Predicates are boolean functions, they return true or false, so It does not make any sense to assign them a weigh, as it is stated in the configurable predicates section with ServiceAffinity and LabelsPresence predicates

### Which section(s) is the issue in?

[**Configurable Predicates**](https://docs.openshift.com/container-platform/3.9/admin_guide/scheduling/scheduler.html#configurable-predicates)

### What needs fixing?

Configurable Predicates section is wrong.

**Comment by mburke5678** [comment]
Closing. Changes made via https://github.com/openshift/openshift-docs/pull/10742
