### ISSUE TITLE
daemonset editing actually updated pods

### ISSUE THREAD

**Issue by akostadinov** [openshift/openshift-docs#9623]
### Which section(s) is the issue in?
Issue with last section of Daemon Set config:
https://docs.openshift.org/latest/dev_guide/daemonsets.html

> Currently, updating a daemonset’s pod template does not affect existing pod replicas. ...

### What needs fixing?

This section is incorrect. I am editing daemon set template `nodeSelector` element. After the edit pods are removed/created according to the change I'm doing. If some changes take effect and some not, then it needs to be clarified which ones. Or if now all changes take effect, then removing that section would be a solution.

-- tested with 3.10

**Comment by vikram-redhat** [comment]
@akostadinov 3.10 is not released officially. Are you able to test with 3.9 and report back?

**Comment by mburke5678** [comment]
@akostadinov Thank you for your input. 

I am not clear on what you are suggesting. 
1. You create a daemonset, which creates pods. 
2. You edit the daemonset and delete the existing pods.
3. The new pods are not picking up the change?

**Comment by akostadinov** [comment]
@mburke5678 , what I observe is:
1. set `nodeSelector` in DC
2. pods automatically start/stop

Have to check with 3.9

**Comment by akostadinov** [comment]
Just tested on 3.9 also:
```
[root@qe-smoke39-merrn-1 ~]# oc version
oc v3.9.30
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://host.example.com:8443
openshift v3.9.30
kubernetes v1.9.1+a0ce1bc657
[root@qe-smoke39-merrn-1 ~]# oc create -f https://raw.githubusercontent.com/openshift-qe/v3-testfiles/master/daemon/daemonset.yaml
daemonset "hello-daemonset" created
[root@qe-smoke39-merrn-1 ~]# oc get pod
NAME                       READY     STATUS    RESTARTS   AGE
docker-registry-1-x4f7m    1/1       Running   0          14h
hello-daemonset-njdq9      1/1       Running   0          4s
registry-console-1-fdrn8   1/1       Running   0          14h
router-1-92t4f             1/1       Running   0          14h
[root@qe-smoke39-merrn-1 ~]# oc edit ds hello-daemonset # add dummy node selector
daemonset "hello-daemonset" edited
[root@qe-smoke39-merrn-1 ~]# oc get pod
NAME                       READY     STATUS        RESTARTS   AGE
docker-registry-1-x4f7m    1/1       Running       0          14h
hello-daemonset-njdq9      0/1       Terminating   0          2m
registry-console-1-fdrn8   1/1       Running       0          14h
router-1-92t4f             1/1       Running       0          14h
```
Sounds like at least changes to `nodeSelector` are automatically applied. Don't know about anything else.

**Comment by mburke5678** [comment]
@akostadinov OK. Thank you. Your finding mirror what the upstream Kubernetes docs suggest:

_If node labels are changed, the DaemonSet will promptly add Pods to newly matching nodes and delete Pods from newly not-matching nodes._
https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#updating-a-daemonset

**Comment by mburke5678** [comment]
@akostadinov Changed the sentence to:
If node labels are changed, the DaemonSet adds pods to nodes matching the new labels and delete pods from nodes that do not match the new lablels.

**Comment by mburke5678** [comment]
Closing. Changes via https://github.com/openshift/openshift-docs/pull/9897
