### ISSUE TITLE
[enterprise-3.9] Edit suggested in file install_config/install/disconnected_install.adoc

### ISSUE THREAD

**Issue by kanekoh** [openshift/openshift-docs#9655]
### Which section(s) is the issue in?

Section: Syncing images

### What needs fixing?

Missing required docker images as follows:

2. Pull all of the required OpenShift Container Platform containerized components. ...

```
$ docker pull registry.access.redhat.com/openshift3/ose-template-service-broker:<tag>
$ docker pull registry.access.redhat.com/openshift3/ose-web-console:<tag>
```

3. Pull all of the required OpenShift Container Platform containerized components for ...

```
$ docker pull registry.access.redhat.com/openshift3/oauth-proxy:<tag>
```

**Comment by vikram-redhat** [comment]
Fixed via: https://github.com/openshift/openshift-docs/pull/9656. Closing this issue.
