### ISSUE TITLE
[enterprise-3.1] Edit suggested in file rest_api/kubernetes_v1.adoc

### ISSUE THREAD

**Issue by damienb-opt** [openshift/openshift-docs#9687]
### Which section(s) is the issue in?
The whole page

### What needs fixing?
All links towards http://releases.k8s.io should be replaced: the resources under this domain have no reliable URIs (let's say they are typical github.com URIs, and that is 404).

**Comment by vikram-redhat** [comment]
Sorry @damienb-opt - we are not updating 3.1 docs at the moment. I am going to close this issue.
