### ISSUE TITLE
rake build: Could not restore untracked files from stash

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/openshift-docs#981]
This is quite annoying when I need to work on docs, whenever I run `rake build` or `rake clean build` I have to manually remove two files and unstash my changes manually:

```
$ rake clean build
....
NOTE: Re-applying uncommitted changes and files to working branch.
architecture/core_concepts/images/docker-diagram.png already exists, no checkout
architecture/core_concepts/images/docker-diagram.png.cache already exists, no checkout
Could not restore untracked files from stash
ERROR: Could not apply stashed code. Run `git stash apply` manually.

All builds completed.
$ git st
On branch build-env
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	architecture/core_concepts/images/docker-diagram.png
	architecture/core_concepts/images/docker-diagram.png.cache

nothing added to commit but untracked files present (use "git add" to track)
```

I didn't do anything with those files locally, they're being created during `rake build`... any clues where to fix it?

@nhr

**Comment by rhcarvalho** [comment]
@tnguyen-rh when you build docs locally do you have the same problem? Wondering if this is only me...

**Comment by nhr** [comment]
I have a fix for this, tied in with some other changes. I will be updating
the utility soon.

**Comment by tnguyen-rh** [comment]
@rhcarvalho
I never got into the `rake build` flow, personally, for local preview.  Usually i use [`adoc2html`](http://file.brq.redhat.com/~tnguyen/adoc2html) on single files.

**Comment by rhcarvalho** [comment]
@nhr could you share the fix? This disturbs my flow every time I'm working on docs :cry:

**Comment by rhcarvalho** [comment]
`gem update ascii_binder` solves the problem. Thanks @nhr.
