### ISSUE TITLE
Obsolete step in "Exposing Registry"

### ISSUE THREAD

**Issue by PatrickSteiner** [openshift/openshift-docs#983]
https://docs.openshift.org/latest/install_config/install/docker_registry.html#exposing-the-registry

In the first sentence of this section, it is stated, that one needs to have a deployed router.

Step 3 of the instruction then again is the link to "how to deploy a router"

One of the two is obsolete, as having both in the instructions is confusing for novice user/reader.

**Comment by vikram-redhat** [comment]
BZ created: https://bugzilla.redhat.com/show_bug.cgi?id=1265055. Closing this issue.
