### ISSUE TITLE
[enterprise-3.9] Edit suggested in file install_config/persistent_storage/persistent_storage_flex_volume.adoc

### ISSUE THREAD

**Issue by CoaxVex** [openshift/openshift-docs#9921]
### Which section(s) is the issue in?

Consuming Storage using FlexVolume

### What needs fixing?

The callout number 7 indicates that the "options" field takes a "free-form dictionary of parameters", however this is untrue. It only accepts a number of flags (keys pointing to strings).
A dictionairy would be able to contain other types such as arrays. The following does not work:

```
options:
  key1:
    - value1
    - value2
```

The oc client throws the following error when trying to create such a resource:

```
Error from server (BadRequest): error when creating "pv.yml": PersistentVolume in version "v1" cannot be handled as a PersistentVolume: [pos 257]: json: expect char '"' but got char '['
```

The upstream documentation seems to call it "flags", so I suggest this is reflected here as well.

**Comment by tmorriso-rh** [comment]
@CoaxVex Hi, can you please provide the link to the upstream docs you are viewing? Specifically, where in the upstream docs is the term flags used?

**Comment by CoaxVex** [comment]
https://github.com/kubernetes/community/blob/master/contributors/devel/flexvolume.md#default-json-options

> In addition to the flags specified by the user in the Options field of the FlexVolumeSource, the following flags are also passed to the executable. Note: Secrets are passed only to "mount/unmount" call-outs.

**Comment by tmorriso-rh** [comment]
@jhou1 @liangxia Please provide QE review for this issue. Here is the URL for the document in question: https://docs.openshift.com/container-platform/3.9/install_config/persistent_storage/persistent_storage_flex_volume.html#flex-volume-usage

**Comment by tmorriso-rh** [comment]
@jhou1 @liangxia Can you provide QE review for this issue? Thanks.

**Comment by liangxia** [comment]
QE reproduced the issue on OCP v3.10.12, tried the options in 3.9 docs and the one in the first comment, both show error.

**Comment by tmorriso-rh** [comment]
Work in progress: https://github.com/openshift/openshift-docs/pull/10656

**Comment by vikram-redhat** [comment]
This has been merged. I will close this issue.

https://docs.openshift.com/container-platform/3.9/install_config/persistent_storage/persistent_storage_flex_volume.html#flex-volume-usage
