### ISSUE TITLE
[enterprise-3.0] Edit suggested in file architecture/core_concepts/pods_and_services.adoc

### ISSUE THREAD

**Issue by pmacko1** [openshift/openshift-docs#9979]
### Which section(s) is the issue in?
https://docs.openshift.com/enterprise/3.0/architecture/core_concepts/pods_and_services.html#services

### What needs fixing?
404 Kubernetes documentation link

https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/services.md

**Comment by tmorriso-rh** [comment]
Fix in progress: https://github.com/openshift/openshift-docs/pull/10109

**Comment by tmorriso-rh** [comment]
https://github.com/openshift/openshift-docs/pull/10109 merged to 3.0 and CP to 3.1 - 3.3. Closing this issue.
